### ISSUE TITLE
[shelly] Action-URL not set with FW 1.8+

### ISSUE THREAD

**Issue by MajorTwip** [openhab/openhab-addons#10012]
When not using COAP you normally want to set Action-URLs on the Device, otherwise you fully depend on Pull. 

If you set RelayEvents or ButtonEvents in the Thing-Config, the Binding sets those Action-URLs for you. 

Due to a Change in the HTTP-API of the Shelly-Devices with FW 1.8 this no longer works. 

From https://shelly-api-docs.shelly.cloud/#settings-actions

> Since v1.8.0 devices support multiple actions. Max number of URLs per action is 5. Max URLs length is 256.

Examples:
Setting two URLs for out_on_url action on channel 0:
http://192.168.33.1/settings/actions?index=0&name=out_on_url&enabled=true&urls[]=http://192.168.1.4/on&urls[]=http://192.168.1.5/on

**Comment by markus7017** [comment]
please verify with latest DEV build

**Comment by markus7017** [comment]
Why do you need Action URLs anymore? You should focus on CoAP, maybe you need some changes to your setup, but CoAP is way more efficient and providfes near-realtime updates

**Comment by markus7017** [comment]
you should use CoIOT for events, those are near-realtime and usually there is no reason for Action URLs anymore. Maybe this gets removed soon.
