### ISSUE TITLE
[shelly] 3EM Power and Current Channel not for 3 different phases possible

### ISSUE THREAD

**Issue by Bartelime** [openhab/openhab-addons#10013]
Channel mismatch / merging together with Shelly-3EM:

If I create a new Item let's say Power Meter for Phase A --> power --> meter#1currentWatts and I create a second new item for Power Meter for Phase B --> meter#2currentWatts, I overwrite the Item for Phase A. Always the last Item keeps stored and overwrites the other.

Same happens if I create a channel for the currents for PhaseA, and PhaseB in [A].

But it works for the Voltage for PhaseA, PhaseB and PhaseC.

Thanks for your reply
Regards Bartelime

**Comment by markus7017** [comment]
please verify with the latest DEV build

**Comment by markus7017** [comment]
no feedback
(fix was confirmed by other users)
