### ISSUE TITLE
[remoteopenhab] Connection to the same host not possible

### ISSUE THREAD

**Issue by berland** [openhab/openhab-addons#10026]
The remote binding refuses to work towards its own host, from the test in this line. This sounds reasonable, but it is a valid scenario to run multiple OpenHAB instances on the same host (e.g. via Docker) but on different ports.

Suggest to test for both the same IP and the same port-number before binding initialization fails.

https://github.com/openhab/openhab-addons/blob/7e06da24015dcf84d57e0f0f232793817c4fc468/bundles/org.openhab.binding.remoteopenhab/src/main/java/org/openhab/binding/remoteopenhab/internal/handler/RemoteopenhabBridgeHandler.java#L142

**Comment by berland** [comment]
Duplicate of #9487

**Comment by lolodomo** [comment]
Yes thst is exactly the same issue. So you know the workaround. 
But keep it opened, I will try to improve the check.

**Comment by lolodomo** [comment]
@kaikreuzer : how to retrieve HTTP and HTTPS ports used by the local OH server?  Is it even possible?

**Comment by lolodomo** [comment]
I believe it is not possible. 
The only solution would be I think a new advanced setting to bypass this check.

**Comment by berland** [comment]
What is the consequence if one OH instance connects to itself, infinite loop? If nothing bad happens, it could be downgraded to a warning?

**Comment by lolodomo** [comment]
Thinking about it, even if it would be stupid, linking to itself should probably work without loop. 
So as you suggest, I could just keep a warning but not blocking.

**Comment by lolodomo** [comment]
The warning could be useless for users linking to a different server on the same host. Do I will simply suppress this check.
