### ISSUE TITLE
[MQTT] Adding channel does not save with spaces

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#10043]
Hi. 
I create a new generic MQTT thing and add channels. 
If the channel identificator has a space, there is no warning/error. It is common knowledge ( well ) that the identifier cannot be space. But the binding does not require that. It works like a charm without. You can save.
When you leave the screen and then return back into the thing, the channel is gone. It did "not" save. But there is no error. 
![image](https://user-images.githubusercontent.com/43743230/106919183-31563800-670a-11eb-8cf3-f5a457ff3095.png)

## Expected Behavior
There should be a Warning when the channel identifier that was entered contains a space.

## Your Environment
OpenHAB 3.0.0 stable on Linux Debian using Mosquitto Broker on a different Server.

**Comment by Hilbrand** [comment]
The binding has no knowledge of items. So I would expect this to be an ui or core issue and not a mqtt issue. Can you check if this problem happens with other bindings too?

**Comment by openPhiL** [comment]
oh <insert curse word here>. I really wrote "item". :-( 
What I ment was thing. I fixed my typo above.

**Comment by Hilbrand** [comment]
Same reasoning :wink: This is before anything gets to the binding. So either the core api doesn't properly reject this on creation or the ui doesn't check. That can be it ignores the error returned by the api in case the api does handle it and/or it doesn't check in the ui.

**Comment by openPhiL** [comment]
well, I can replicate that problem with the generic http item. So you're off the hook :) I posted the issue on 
 https://github.com/openhab/openhab-webui/issues/876
