### ISSUE TITLE
[gpstracker] Accuracy channel doesn't work when linked to Number:Length item

### ISSUE THREAD

**Issue by baku104788** [openhab/openhab-addons#10053]
## Expected Behavior
Utilized model to 'create equipment from thing' and link in available gps tracker thing channels.  I would expect the Accuracy channel to work at that point.

## Current Behavior
Accuracy item displays 'Err' unless you manually switch the item type to "Number" 

error log upon update:
2021-02-04 12:58:31.018 [WARN ] [e.internal.SseItemStatesEventBuilder] - Exception while formatting value ‘2559.0551181102364’ of item GPSTrackerjf_Accuracy with format ‘%d’: d != java.math.BigDecimal

## Steps to Reproduce (for Bugs)
1. Configure system to use US measurement system (not certain if this impacts but I have mine set this way)
2. Create new GPS Tracker equipment from thing and allow system to auto generate items.
3. Publish update from GPS Tracker client

## Context
Basic usage of gps tracker binding

## Your Environment

* Version used: 3.0.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker image
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 20.04 LTS

**Comment by gbicskei** [comment]
Works for me on 3.1.0.M2.

**Comment by gbicskei** [comment]
I still see the problem after changing to imperial...
