### ISSUE TITLE
OH3 TR-064 Binding: IP-Adresse in Hostfeld wird nicht beachtet

### ISSUE THREAD

**Issue by jmt-cash** [openhab/openhab-addons#10067]
Hallo,

gerade habe ich festgestellt, dass die IP-Adresse, die man bei der Erstellung eines Things vom Typ Bridge (Fritz!Box) eingibt, nicht beachtet wird. Offenbar sucht das Binding immer nach dem Host fritz.box. Man muss /etc/hosts editieren, damit die Fritzbox gefunden wird - unschön.

Außerdem kann man so nicht 2 Fritzboxen konfigurieren, weil ja nur ein Eintrag in der hosts Datei möglich ist - ärgerlich!

Gibt es eine Möglichkeit, das zu patchen?

Gruß
Ilu

**Comment by J-N-K** [comment]
Already fixed in main.
