### ISSUE TITLE
[homematic] Heating level item in OH 3 is missing category

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#10064]
## Expected Behavior
Adding an item to a heating level channel in OH 2.5 also added the category "DimmableLight". 

## Current Behavior
Adding an item to a heating level channel in OH 3 is just a dimmer without category. 

## Steps to Reproduce (for Bugs)
See above.

## Your Environment
* Version used: openHAB 3.0.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Gentoo Linux

**Comment by MHerbst** [comment]
DimmableLight has been removed as a category because of the problems in #8799. I also don't think that Dimmable*Light* would be a correct category for a heating level. Instead, I would expect category "Temperature". 

Which device and HM channel is it?

**Comment by sidamos** [comment]
It is the level channel of a Homematic IP heating group.

If it is of no negative consequence, we can close this issue.

**Comment by MHerbst** [comment]
> If it is of no negative consequence, we can close this issue.

Yes, please
