### ISSUE TITLE
[miio] Support Yeelight lamp9 & lamp10

### ISSUE THREAD

**Issue by mrumpf** [openhab/openhab-addons#10061]
The following lamps are not yet supported by the binding:
* yeelight.light.lamp9 - Staria Bedside Lamp Pro https://www.yeelight.com/en_US/product/doris-pro
* yeelight.light.lamp10 - Staria Floor Lamp https://de.banggood.com/Yeelight-YLLD01YL-12W-Smart-Dimmable-LED-Floor-Table-Lamp-WIFI-APP-Control-(-Ecosystem-Product)-p-1565735.html?cur_warehouse=CN

What do I need to do to add support to the binding? Currently, I just added an entry to the "yeelink.light.lamp1.json" file:
````
{
        "deviceMapping": {
                "id": [
                        "yeelink.light.lamp1",
                        "yeelink.light.lamp2",
                        "yeelink.light.lamp3",
                        "yeelink.light.lamp4",
                        "yeelink.light.lamp5",
                        "yeelink.light.lamp6",
                        "yeelink.light.lamp7",
                        "yeelink.light.lamp8",
                        "yeelink.light.lamp9",
                        "yeelink.light.lamp10",
                        "yeelink.light.strip4",
                        "yeelink.light.ct2",
                        "yeelink.light.mono1",
                        "yeelink.light.mono2",
                        "yeelink.light.mono4",
                        "yeelink.light.mono5",
                        "yeelink.light.panel1",
                        "yeelink.light.virtual"
                ],
...
}
````
And to the MiIoDevices.java file
````
...
    YEELINK_LIGHT_LAMP8("yeelink.light.lamp8", "Yeelight", THING_TYPE_BASIC),
    YEELINK_LIGHT_LAMP9("yeelink.light.lamp9", "Yeelight Staria Bedside Lamp Pro", THING_TYPE_BASIC),
    YEELINK_LIGHT_LAMP10("yeelink.light.lamp10", "Yeelight Staria Floor Lamp", THING_TYPE_BASIC),
    YEELINK_LIGHT_MONO1("yeelink.light.mono1", "Yeelight Bulb", THING_TYPE_BASIC),
...
````
But currently the binding fails to pull the token from the cloud so that I receive communication errors.

**Comment by marcelrv** [comment]
easiest is to use the latest version of the binding and try the testcommands switch
it will try current known properties and build a best-quess json file from the responses.

![image](https://user-images.githubusercontent.com/5871213/108085365-8af92380-7075-11eb-8bc1-c382d8354335.png)

If you know the existing models have the same features as your current, you can do as described above. (testing would be as simple as updating the model in your config with any of the id's in the above list)

Don't know why it is receiving the wrong token from the cloud. Is it maybe on muliple servers? (each server has different token, or was the token not yet refreshed?), or the light maybe not online? 
In the userdata/miio folder you find the full response from the cloud, that may help in finding the right token

**Comment by marcelrv** [comment]
@mrumpf did you manage to run that test feature and get the corresponding file
