### ISSUE TITLE
All bindings gone after 3.0.1 update

### ISSUE THREAD

**Issue by pgruetter** [openhab/openhab-addons#10072]
## Expected Behavior
After Upgrade from 3.0.0 to 3.0.1, all bindings are installed.

## Current Behavior
I used the described method to update docker from 3.0.0 to 3.0.1:
```
docker stop openhab
docker rm openhab
```

I'm using the following docker-compose file to create the container:
```
version: ‘2.2’

services:
openhab:
image: “openhab/openhab:3.0.1”
container_name: “openhab”
restart: always
network_mode: host
volumes:
- “/etc/localtime:/etc/localtime:ro”
- “/etc/timezone:/etc/timezone:ro”
- “/opt/openhab/addons:/openhab/addons”
- “/opt/openhab/conf:/openhab/conf”
- “/opt/openhab/userdata:/openhab/userdata”
environment:
OPENHAB_HTTP_PORT: “9080”
OPENHAB_HTTPS_PORT: “9443”
EXTRA_JAVA_OPTS: “-Duser.timezone=Europe/Zurich”
USER_ID: ${UID}
GROUP_ID: ${GID}
ports:
- “9080:9080”
- “9443:9443”
```

When starting OH3, bindings are not installed and I get the following errors in openhab.log:

```
2021-02-06 17:58:23.130 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing ‘openhab-binding-hue, <…huge list of bindings…>, openhab-binding-meteoblue’: Error:
Error downloading mvn:com.github.oshi/oshi-core/4.5.2
Error downloading mvn:net.java.dev.jna/jna-platform/5.5.0
Error downloading mvn:net.java.dev.jna/jna/5.5.0

```
Installling a few of the bindings through the karaf console works correctly, but for most I get mvn related errors, i.e:
```
openhab> feature:install openhab-misc-openhabcloud
Error executing command: Error:
Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.jsr305/3.0.2_
Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.okio/1.13.0_1
Error downloading mvn:org.json/json/20180813
Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.okhttp/3.8.1_1
```

Also tried to downgrade to 3.0.0 again, but same problems appear now. 

## Steps to Reproduce (for Bugs)
In my case: 
1. Running 3.0.0 in docker
2. docker stop openhab
3. docker rm openhab
4. docker-compose up -d (using the docker-compose.yml mentioned above)

Other face similar issues:
https://community.openhab.org/t/docker-update-to-3-0-1-went-wrong/116529

## Context
Obviously that's a big blocker, as my OH3 installation is standing still.

## Your Environment

* Version used: 3.0.1
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Lubuntu 20.04 LTS

**Comment by pgruetter** [comment]
As a quick fix: 
I removed the container, restored a backup of userdata and re-created the container in version 3.0.0. Now everything is working again.

**Comment by wborn** [comment]
Perhaps some cloud service was down during your upgrade or it was some kind of upgrade or networking issue for which there is not enough info to fix or troubleshoot it now.
