### ISSUE TITLE
[hue] New Hue zone feature behavior

### ISSUE THREAD

**Issue by Peter-DD** [openhab/openhab-addons#10080]
## Expected Behavior
I set up  a zone with two bulbs in Phillips Hue-App. This zone will discovered by openhab and I can switch, dimm and change color of this zone via channels and items very well. If the zone is in state OFF and when I switch ON only one bulb within this zone regardless via openhab binding or Hue-App I expect the other bulbs from this zone keeps OFF. 

## Current Behavior
I set up  a zone with two bulbs in Phillips Hue-App. This zone will discovered by openhab and I can switch, dimm and change color of this zone via channels and items very well.

If the zone is in state OFF and when I switch ON only one bulb within this zone regardless via openhab binding or Hue-App all bulbs in this zone and the zone itself were switched ON. 
For testing purpose I stop the hue binding and switch ON only one bulb from this zone via Hue-App. Now it works as expected, the other bulb keeps off.

## Possible Solution
Maybe a setup option in zone-thing is needed, that the zone state should not react on zone-member state changes

## Steps to Reproduce (for Bugs)
1. Setup a zone with two bulbs in Hue-App
2. Discover this zone-thing  in openhab
3. switch the zone OFF - all bulbs went off
4. switch-ON one bulb only from this zone, regardless with Hue-App or openhab bulb item
5. the other bulbs from this zone wrongly went ON
6. if you stop the hue-binding, the behavior is as expected

## Context
I want to control the color and brightness of the zone, but each bulb from this zone, too.

## Your Environment
* Kernel: Linux 5.4.83-v7+
* Platform: Raspberry Pi 2 Model B Rev 1.1
* Version used:  3.1.0-SNAPSHOT - Build #2177   
* Java Version: OpenJDK Runtime Environment Zulu11.43+88-CA (build 11.0.9+11-LTS)

**Comment by WTKodi** [comment]
Might be this one:
https://github.com/openhab/openhab-webui/issues/789

**Comment by lolodomo** [comment]
At my knowledge, the binding only requests a hue change when receiving an item command. 
So if the binding switches ON all room lights, that is because a command was received by the openHAB room thing or any light thing.

**Comment by Peter-DD** [comment]
With openhab 3.2.0 the Issue doesn't occur anymore
