### ISSUE TITLE
[miio] stateDescription for ColorTemperature is not reflected in Slider range

### ISSUE THREAD

**Issue by mrumpf** [openhab/openhab-addons#10083]
For the ceiling10 lamp I have the following entry for ColorTemperature in the device database:
````
                        {
                                "property": "ct",
                                "friendlyName": "Color Temperature",
                                "channel": "colorTemperature",
                                "type": "Number",
                                "stateDescription": {
                                        "minimum": 2700,
                                        "maximum": 6500,
                                        "step": 1,
                                        "pattern": "%.0f K"
                                },
                                "refresh": true,
                                "ChannelGroup": "actions",
                                "actions": [
                                        {
                                                "command": "set_ct_abx",
                                                "parameterType": "NUMBER",
                                                "parameters": [
                                                        "$value$",
                                                        "smooth",
                                                        500
                                                ]
                                        }
                                ],
                                "category": "colorlight",
                                "tags": [
                                        "Setpoint",
                                        "Temperature"
                                ]
                        },
````
When I define an item for it:
````
Number             GF_Living_Smartlamp_Dining_ColorTemperature        "Color Temperature"                      (gYeelight,gYeelightCrystalPendant1) {channel="miio:basic:light1:colorTemperature"}
````
and a Slider in my sitemap:
````
                Slider item=GF_Living_Smartlamp_Dining_ColorTemperature label="Farbtemperatur" icon="temperature" visibility=[GF_Living_Light_Table==ON]
````
it is not possible to set the color temperature.
When I change the sitemap entry and define min, max and step values, it works as expected:
````
                Slider item=GF_Living_Smartlamp_Dining_ColorTemperature label="Farbtemperatur" icon="temperature" minValue=2700 maxValue=6500 step=1 visibility=[GF_Living_Light_Table==ON]
````

I would expect the value range to be derived from the stateDescription in the device database, but that does not seem to work.
Without the minValue,maxValue, and step parameters the Slider range is 0-100 and setting the color temperature with those values does not work, the value just jumps back to the current setting after the properties are refreshed.

**Comment by J-N-K** [comment]
This seems to be more an UI issue, since the state description is correct and just ignored if not explicitely defined in the sitemap.

BTW: @openhab/core-maintainers This channel would be hidden if it used the system-channel...

**Comment by marcelrv** [comment]
@mrumpf indeed I think this is not related to the binding, but instead to UI.

@J-N-K do you mean with your remark that if a system channel would have been used this would not happening?
kai made remark recently that suggested to use the system predefined channeltype for this

**Comment by J-N-K** [comment]
@marcelrv No. I mean that a PR (https://github.com/openhab/openhab-core/pull/2183) that was recently merged in core would hide this channel from the user. Unfortunately core maintainers prefer a "relative" color temperature from 0-100% (which as you correctly said in a comment to Kai has a different meaning depending on the range provided by the device) over an absolute color temperature in K (which at least in an ideal world would match independent from the device capabilities).

**Comment by lsiepel** [comment]
Seen parts of that discussion, sorry don't want to bring all that up again, but for this issue:

If i'm not mistaken, this issue should be solved in the UI as it is item-type independent. In that case i suggest this issue is moved to the webui repo.
