### ISSUE TITLE
[homematic] Create equipment from HMIP heating group - Actual Temperature is NULL

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#10085]
## Expected Behavior
Create equipment from thing HMIP heating group, select several channels for creating points, including Actual Temperature.
The new created item/point Actual Temperature should have the correct value. 
An existing old item from OH 2.5 has the correct value.

## Current Behavior
The newly created Actual Temperature point has the value NULL.
I had the same issue yesterday with another HMIP heating group, but somehow it was resolved and I do not know how.
![Screenshot 2021-02-07 at 12 35 25](https://user-images.githubusercontent.com/873537/107145334-0570c780-6941-11eb-9b74-03fa493751f3.png)

## Steps to Reproduce (for Bugs)
1. Create equipment from thing HMIP heating group and select channel Actual Temperature

## Your Environment
* Version used: OH 3.0.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome/Linux
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Linux, Java 11

**Comment by MHerbst** [comment]
You have two items connected to the ACTUAL_TEMPERATURE channel. The second item has the correct type of "Number:Temperature" but the first one has wrong type and therefore the value is NULL. Can you try to change the item type to "Number:Temperature".

BTW: is it intended that the channel is linked to two items?

**Comment by sidamos** [comment]
Correct, when I change the type then it works.
So, the issue is, when I create an item for the Actual Temperature channel in OH 3, then it has the wrong type. Just tried this again with a 3rd item and it has again the wrong type. 

I had 2 items for the same channel because I am currently experimenting with OH 3 about using existing items for the model vs. creating new items.

**Comment by MHerbst** [comment]
What happens for the first item? Is the type correct for this item? In your screenshot it looks OK.

I have tested it in my environment with the old non HmIP devices and I had no problems. But there is some special treatment for HmIP devices and temperature channels. Maybe some additional coding will be necessary. But if it only occurs if there is more than one item it may also be  problem on the Main UI side.

**Comment by sidamos** [comment]
The first item was created with OH 2.5.

I have now deleted both items and created a new one with OH 3 and the type is again wrong. So, the issue was not that it was the 2nd item.

I do not remember if this was also happening in OH 2.5 and if I fixed it manually.

Nevertheless, it looks like a bug and it does not happen for SetPointTemperature.

**Comment by MHerbst** [comment]
There is problem with the data returned from the CCU. It does not return valid units for all HmIP data points. Especially for some temperature data points the units are missing. I have already implemented some fix but it seem that it is not sufficient in case of HmIP heating groups.

Can you perform the following steps:
- remove the thing definition for the heating group
- enable TRACE log mode for the Homematic binding
- discover and create the thing again
- create an item

Post the excerpt from openhab.log starting with the discovery.

**Comment by sidamos** [comment]
Recreating the thing apparently fixed it.
When creating a new item for Actual Temperature, the type was now correct.

**Comment by MHerbst** [comment]
In this case, you have defined the things probably with a binding version that did not contain my fixes for the temperatures.

Can you close this issue if everything is working correctly?

**Comment by sidamos** [comment]
Yes, thank you!
