### ISSUE TITLE
Wrong groupId in feature.xml files referencing configs?

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#10081]
Hi,

when developing DynamoDB binding in https://github.com/openhab/openhab-addons/pull/9937, I noticed a strange mismatch of artifact names.

Many bundles reference configurations defined in `openhab-addons/features/openhab-addons-external`. Few examples below

https://github.com/openhab/openhab-addons/blob/8a2ac82b071d9a4605768676e15730c5fe5a565e/bundles/org.openhab.persistence.jdbc/src/main/feature/feature.xml#L49
https://github.com/openhab/openhab-addons/blob/8a2ac82b071d9a4605768676e15730c5fe5a565e/bundles/org.openhab.persistence.rrd4j/src/main/feature/feature.xml#L8

The entry defines that configuration artifacts should be found under group `mvn:${project.groupId}`. This naturally corresponds to `org.openhab.addons.bundles`, as specified in the pom.xml of the bundle, example from jdbc follows:

https://github.com/openhab/openhab-addons/blob/8a2ac82b071d9a4605768676e15730c5fe5a565e/bundles/org.openhab.persistence.jdbc/pom.xml#L8

Now, it seems that this is incorrect groupId to use, since `org.openhab.addons.features.karaf` is the groupId of `openhab-addons-external`:

https://github.com/openhab/openhab-addons/blob/8a2ac82b071d9a4605768676e15730c5fe5a565e/features/openhab-addons-external/pom.xml#L8

Is the above analysis is correct? Is this not verified in CI?

I can reproduce dependency issues by trying to compile `kar` locally using `mvn karaf:kar`. The issues are resolved by changing the groupId to `org.openhab.addons.features.karaf` instead of `${project.groupId}`.

**Comment by J-N-K** [comment]
I think it works because the single-features are compiled into a fullfeature.xml: https://github.com/openhab/openhab-addons/blob/main/features/openhab-addons/pom.xml and this has the correct `groupId`.

**Comment by ssalonen** [comment]
Can I somehow build kar of a single bundle somehow?

**Comment by ssalonen** [comment]
I eventually worked around the issues by building the big openhab-addons.kar including everything. I am still not certain why it works with the group id it does, but... it seems to work! See https://github.com/openhab/openhab-addons/pull/9937#issuecomment-803103093 for the build instructions.

Closing.
