### ISSUE TITLE
[MAP transformation] Pass on missing string

### ISSUE THREAD

**Issue by matsahm** [openhab/openhab-addons#10092]
Hello,

I translate incoming strings with the MAP transformation in another language. When I have in the .map-File no translation for an incoming string, the string is empty on OpenHAB and I have the following message in the log:
Could not transform 'xxx' with the file 'de.map' : Target value not found in map for 'xxx'.
The originate string would be better than none at all. I have two ideas to fix the issue:

Idea 1:
In the map-file add the default-entry with %s and resolve the placeholder. Example:
`=%s`

Idea 2:
In the "Incoming Value Transformations"-section choose a fallback.
Example: `MAP:de.map:%s` instead of `MAP:de.map`

Thanks

**Comment by clinique** [comment]
There already exists a fallback value capability (cf https://www.openhab.org/addons/transformations/map/). Doesn't it do the job ?
