### ISSUE TITLE
[mqtt.espmilighthub] expose color temperature as Number in mireds

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#10096]
Right now color temperature is exposed as a Dimmer from 0-100. However, HomeKit integration requires the color temperature in mireds (from 50 to 400; aka 2500K to 20000K in kelvin). Conveniently, the underlying
MQTT data already exposes it in mireds (from 153 to 370; aka 2700K to 6500K in kelvin). It'd be great if the binding just exposed this directly, so I can hook it up to HomeKit and be done, instead of using rules.

As a wish list item, it'd be nice if there was also a channel that exposed the temperature as a Number in Kelvin (1,000,000 / mireds), since that makes more sense for say Basic UI. I'm currently using a transform service on the items state description, but that means the slider still shows 0-100 when you're adjusting it.

**Comment by J-N-K** [comment]
@openhab/core-maintainers This underlines my point that the color temperature in K is much more useful than in %.

**Comment by cweitkamp** [comment]
This is not only a good argument for the Kelvin based channel. We now have a feature request to add a third option to set Color Temperature values: In mired. Internally a lot of bindings are using mired for communication via APIs. Why not setting it directly via openHAB? Additionally every binding implements its own conversion methods between the different units. Room for improvement and code streamlining. This really screams for a rethinking of Color Temperature handling in openHAB. A ColorTemperature Profile to do the math for all variants? A util class for converting values?

**Comment by J-N-K** [comment]
In fact it does (see the wish list item). 

I see two options:

- A `math` profile  (similar to the `offset` profile) where you could calculate `1E6/value`. Thiscould be useful for a lot of other use-cases.
- Using real UoM for the color-temperature and add `mired` to the units, and properly enable the "sending unit" on the binding. That would probably be most flexible.

**Comment by Skinah** [comment]
What is the way forward for this then? Should a new issue be raised under CORE?

**Comment by kaikreuzer** [comment]
I'd suggest to simply use the [system channel type](https://www.openhab.org/docs/developer/bindings/thing-xml.html#system-state-channel-types) `color-temperature-abs`, which allows the binding to show the value in K.

To correctly map this for HomeKit, the required conversion should imho be done within the HomeKit add-on as this will then apply to all bindings that use this system channel.

**Comment by Skinah** [comment]
@kaikreuzer (and others) Thank you for your input, however I would like to clarify some things around this and feel free to link to a better place to discuss it, or if it has already been discussed as I am not up to speed with the direction of the core, the system channels and main UI....

The end goal I would LOVE to see is that you can add any colour light with the colour temp ability with any binding and they are displayed and work the same (have a consistent look and feel). All this with ZERO need for a user to create rules, tags or metadata. Add a light as equipment to the model and it should be automatic to display in a correct and consistent way. Ask HABot to turn all lights to 6000K and it should know how to do this for any binding with it implemented. Users should have Dimmer controls to play between warm and cold whites. Even better if the color gradient displays under the Dimmer to clearly indicate which way is warm and which way is cold.

Implementing color-temperature-abs is a step in that direction, however I don't believe the controls and widgets are created to make this a slick and professional solution without creating rules to convert a Number into a PercentType? Currently `system.color-temperature` will create a Dimmer item and I like that. Implementing `color-temperature-abs` seems to be a step backwards, if the user does not get at least a Dimmer control out of the box.

So is the solution to implement both creating more work in every binding?
1.`system.color-temperature` so users get a DIMMER
2.`system.color-temperature-abs` for Homekit and HABot users

Or is it possible to implement only the `color-temperature-abs` and the Dimmer control and widgets are all handled by the core and main UI widgets?

The current dimmer the binding creates is back to front compared to `system.color-temperature` so to implement this creates a breaking change, then if the core adds support to do everything via `system.color-temperature-abs` alone, it would make sense to leave everything as it is and only introduce the `system.color-temperature-abs` and phase out the current method when it reaches maturity. Without knowing the current situation and what is planned, makes it hard to plan the direction to go in for the long term.

Hopefully I made this clear and have not hit on a sore point.
