### ISSUE TITLE
[shelly] New device#supplyVoltage channel for Shelly 2.5, 1PM and 1L

### ISSUE THREAD

**Issue by elektro-joe** [openhab/openhab-addons#10090]
## Request
It would be great if you can add the item AC **voltage** to the Shelly Binding.

## Possible Solution
On the web interface of the shelly device it's already available e.g.
**http://192.168.xxx.yyy/status**
(second to last key:value)

{
    "wifi_sta": {
        "connected": true,
        "ssid": "...",
        "ip": "192.168.xxx.yyy",
        "rssi": -78
    },
    "cloud": {
        "enabled": true,
        "connected": true
    },
    "mqtt": {
        "connected": false
    },
    "time": "14:30",
    "unixtime": 1612704620,
    "serial": 190,
    "has_update": false,
    "mac": "40F520XXXYYY",
    "cfg_changed_cnt": 2,
    "actions_stats": {
        "skipped": 0
    },
    "relays": [
        {
            "ison": false,
            "has_timer": false,
            "timer_started": 0,
            "timer_duration": 0,
            "timer_remaining": 0,
            "overpower": false,
            "overtemperature": false,
            "is_valid": true,
            "source": "input"
        },
        {
            "ison": false,
            "has_timer": false,
            "timer_started": 0,
            "timer_duration": 0,
            "timer_remaining": 0,
            "overpower": false,
            "overtemperature": false,
            "is_valid": true,
            "source": "timer"
        }
    ],
    "meters": [
        {
            "power": 0,
            "overpower": 0,
            "is_valid": true,
            "timestamp": 1612708220,
            "counters": [
                0,
                0,
                0
            ],
            "total": 0
        },
        {
            "power": 0,
            "overpower": 0,
            "is_valid": true,
            "timestamp": 1612708220,
            "counters": [
                0,
                0,
                0
            ],
            "total": 6
        }
    ],
    "inputs": [
        {
            "input": 0,
            "event": "",
            "event_cnt": 0
        },
        {
            "input": 0,
            "event": "",
            "event_cnt": 0
        }
    ],
    "temperature": 60.61,
    "overtemperature": false,
    "tmp": {
        "tC": 60.61,
        "tF": 141.1,
        "is_valid": true
    },
    "temperature_status": "Normal",
    "update": {
        "status": "idle",
        "has_update": false,
        "new_version": "20210115-103025/v1.9.4@e2732e05",
        "old_version": "20210115-103025/v1.9.4@e2732e05",
        "beta_version": "20210122-154717/v1.10.0-rc1@00eeaa9b"
    },
    "ram_total": 49368,
    "ram_free": 33724,
    "fs_size": 233681,
    "fs_free": 104918,
    **"voltage": 235.8,**
    "uptime": 10603
}

## My Environment
OpenHab 3.0 on openhabian (Raspi4B)
Shelly binding v3.0.1
Shelly 2.5 Relay (SHSW-25) - firmware 1.9.4

**Comment by markus7017** [comment]
Why is that info relevant as a dynamic state (channel)? You know what you connected, this doesn't change dynamically.

I checked the API spec and it doesn't list this parameter for Shelly 2.5, but shelly_voltage for 1PM and 1L
Did you checked the current firmware and could confirm that the parameter is still there?

**Comment by markus7017** [comment]
try updated DEV build for 3.1M5
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true
