### ISSUE TITLE
[SNMP] please add opaque Float values 

### ISSUE THREAD

**Issue by UweSeifert** [openhab/openhab-addons#10103]
OH : 3.0.0
SNMP Binding : 3.0.0
 
My UPS is sending opaque float values via snmp read command. These values are not shown correctly. 

SNMP read:
Sending 47 bytes to UDP: [10.10.101.5]:161->[0.0.0.0]:0
0000: 30 2D 02 01 01 04 06 70 75 62 6C 69 63 A1 20 02 0-.....public? .
0016: 04 7C 0F 1E 7C 02 01 00 02 01 00 30 12 30 10 06 .|..|......0.0..
0032: 0C 2B 06 01 04 01 B3 2E 04 03 01 04 00 05 00 .+....?........

response:
Received 54 byte packet from UDP: [10.10.101.5]:161->[0.0.0.0]:0
0000: 30 34 02 01 01 04 06 70 75 62 6C 69 63 A2 27 02 04.....public?'.
0016: 04 7C 0F 1E 7C 02 01 00 02 01 00 30 19 30 17 06 .|..|......0.0..
0032: 0C 2B 06 01 04 01 B3 2E 04 03 02 01 00 44 07 9F .+....?......D..
0048: 78 04 41 5B 33 33 x.A[33

should be resulted in:
SNMPv2-SMI::enterprises.6574.4.3.2.1.0 = Opaque: Float: 13.700000

but in log I found the following error message:
2021-02-08 09:17:02.083 [WARN ] [ding.snmp.internal.SnmpTargetHandler] - could not convert 9f:78:04:41:5b:33:33 to number for channel snmp:target:my-diskpool-1:nUPS_Batterie_Voltage

this is my things file:
Thing snmp:target:my-diskpool-1 [ hostname="10.10.101.5", protocol="v2c", refresh=3600 ] {
Channels:
Type number : nUPS_Runtime_Value [ oid=".1.3.6.1.4.1.6574.4.3.6.1.0", mode="READ" ]
Type number : nUPS_Batterie_Voltage [ oid=".1.3.6.1.4.1.6574.4.3.2.1.0", mode="READ", datatype="HEXSTRING"]
}

I tried it also with datatype FLOAT, same result and Type string, no success.

**Comment by lsiepel** [comment]
This has now been backported to openhab-addons by: https://github.com/openhab/openhab-addons/pull/14330
