### ISSUE TITLE
[iRobot] Make thing ID persistent

### ISSUE THREAD

**Issue by krocans** [openhab/openhab-addons#10116]
Currently IP address of iRobot is used for thing ID like irobot:roomba:192_168_57_17. 
If robot gets new IP that makes configured thing to stop working and new thing with new IP is being discovered.

Please make Roomba's ID persistent. I suggest to use Roomba's **blid** as thing ID - it never changes.

**Comment by J-N-K** [comment]
Your issue is two-fold. I agree that using the IP as representation property is a bad idea and should be fixed. However, it is always necessary to know the IP address. So you should either make the IP static or use a DNS name that is properly updated if the IP changes.

**Comment by krocans** [comment]
@J-N-K thanks for fixing it!

I am using statically configured things in .things file and DNS updates so for me problem was only bunch if bogus things in "inbox".
The situation is following:
If statically configured thing id exactly matches discovered thing id - nothing new appears in inbox and everything works.
If the same discovered item changes ID all the time (on IP change) then my statically configured Roomba works fine of course but new bogus thing is being added to inbox again and again on every IP change.

If using GUI config only then it's different story, then changing id of the same thing is really bad.
