### ISSUE TITLE
[exec] Autorun does not work

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#10110]
# Problem 1
I am ugrading from OH2.5 and have troubles with the exec binding - suspect an issue.
So here is my thing. 
```yaml
UID: exec:command:31037a2a7a
label: Diningroom Yeelights
thingTypeUID: exec:command
configuration:
  transform: REGEX((.*))
  interval: 0
  autorun: true
  command: /usr/bin/python3 /etc/openhab/python/yeelight_essbereich.py
  timeout: 15
```
and my item:
![image](https://user-images.githubusercontent.com/43743230/107288472-cdae7080-6a63-11eb-819f-6b9e3b7e71a7.png)

the command works when I run it on the console: 
![image](https://user-images.githubusercontent.com/43743230/107288687-2251eb80-6a64-11eb-806e-1c66e7c28098.png)

it is in the whitelist there is this line:

    /usr/bin/python3 /etc/openhab/python/yeelight_essbereich.py

I can enforce the script to do "something" by using the REST API posting ON to the item: 
![image](https://user-images.githubusercontent.com/43743230/107288839-69d87780-6a64-11eb-99e9-f6d31244d5b2.png)
![image](https://user-images.githubusercontent.com/43743230/107288851-7066ef00-6a64-11eb-8442-f5fbf58fbf7d.png)
that results in a change of lastexecution: 
```
2021-02-08 22:22:22.606 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DiningroomYeelights_ZeitpunktderletztenAusfuhrung' changed from 2021-02-08T22:22:10.216327+0000 to 2021-02-08T22:22:22.592125+0000
```

But I want that with every change of the item. (like the autorun should enable).

# Problem 2 

( sorry when I should have done 2 issues).
In addition, I cannot get the value of the item itself to be submitted to the script, like it used to be using %2$s. 
Imagine my script needs an argument: 
```python
import argparse
parser = argparse.ArgumentParser(description='test')
parser.add_argument('brightness', type=int, help="brightness to set")
parser.add_argument('--duration', type=int, help="duration for change")
args = parser.parse_args()
print(args)
```
the command line would have to look like this:
![image](https://user-images.githubusercontent.com/43743230/107289169-e408fc00-6a64-11eb-9bd6-23a7ffed21aa.png)
So in the past, the corresponding thing would be setup like this: 
```yaml
UID: exec:command:31037a2a7a
label: Diningroom Yeelights
thingTypeUID: exec:command
configuration:
  transform: REGEX((.*))
  interval: 0
  autorun: true
  command: /usr/bin/python3 /etc/openhab/python/yeelight_essbereich.py %2$s
  timeout: 15
```
and the whitelist like this:

    /usr/bin/python3 /etc/openhab/python/yeelight_essbereich.py %2$s

but the error is this (when executed using the RUN-Switch, see Problem1).
```
2021-02-08 22:28:52.421 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'DiningroomYeelights_Ausfuhrung' received command ON

2021-02-08 22:28:52.425 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'DiningroomYeelights_Ausfuhrung' predicted to become ON

2021-02-08 22:28:52.570 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'DiningroomYeelights_Ausfuhrung' changed from ON to OFF

2021-02-08 22:28:52.576 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EssbereichYeelights_Ruckgabewert' changed from Format specifier '%3$s' to usage: yeelight_essbereich.py [-h] [--duration DURATION] brightness

yeelight_essbereich.py: error: argument brightness: invalid int value: 'Mon'
```
It looks %2$s is still the date, not the value of the item. 

## Expected Behavior
I change value of item and the python script should do something

## Current Behavior
I change value of item, nothing is happening:
```
2021-02-08 22:14:26.471 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 33

2021-02-08 22:14:26.475 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 33

2021-02-08 22:14:26.477 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 51 to 33

2021-02-08 22:14:27.690 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 46

2021-02-08 22:14:27.700 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 46

2021-02-08 22:14:27.703 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 33 to 46

2021-02-08 22:14:28.220 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 68

2021-02-08 22:14:28.221 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 68

2021-02-08 22:14:28.234 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 46 to 68

2021-02-08 22:14:31.078 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 16

2021-02-08 22:14:31.086 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 16

2021-02-08 22:14:31.089 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 68 to 16
```

## Your Environment
```
runtimeInfo:
  version: 3.0.1
  buildString: Release Build
locale: de_DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.10
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu11.45+27-CA
  osName: Linux
  osVersion: 5.4.44-1-pve
  osArchitecture: amd64
  availableProcessors: 1
  freeMemory: 34330200
  totalMemory: 140509184
bindings:
  - amazonechocontrol
  - astro
  - exec
  - http
  - lifx
  - logreader
  - miio
  - mqtt
  - network
  - openweathermap
  - shelly
  - telegram
  - velux
  - yeelight
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: true
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    os: windows
    pixelRatio: 1
    prefersColorScheme: light
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 4
    language: de-DE
    languages:
      - de-DE
      - de
      - en-US
      - en
      - fr
    onLine: true
    platform: Win32
  screen:
    width: 3840
    height: 2160
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/88.0.4324.146 Safari/537.36
timestamp: 2021-02-08T22:36:01.546Z

```
I use current stable and therefore exec 3.0.1 
I am running on Debian 10 (linux vm). 
I have python 3.7.3

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by Rossko57** [comment]
Problem 1 - Exec binding autorun has an unusual limitation.  It does not trigger every time you send a command to an Item linked to the input channel.  It triggers when a DIFFERENT command is sent.
This is documented.

Problem 2 - if you only trigger using `run` switch, there may be NO meaningful `%2$s` to substitute into your command line.  That would be derived from a command to the `input` channel, and its going to be "used up" because you still have `autorun=true`.
When you send `run` command ON the `input` command has already been dealt with by autorun and I suspect is no longer available for `%2$s` use.

The documentation example shows a two-rule way to achieve this, with `autorun=false`

**Comment by openPhiL** [comment]
Hello Rossko, 
thanks for looking into this issue. 

I ran into problem 2 first and while trying to get to the bottom of the problem, I "build" problem 1 to prove seomthing. So not autorun the same command is totally ok with me, my example in Problem 2 has %2$s with the dimmer, so the command would be different all the time anyway. It is even documented directly in the UI -> when it 'changes' - :/ 

So let's check on Problem 2: I can follow your explaination, but I do not use the `run`-switch. Reading my Issue again, I see that I didn't post this information well - sorry for that. 
I used the run command while testing to force the binding to do "something", because just changing the input did nothing (nothing in the logs, with exec binding set to TRACE). My plan is not to use the run but the input channel with `autorun=true`
![image](https://user-images.githubusercontent.com/43743230/107612723-28ec8880-6c47-11eb-9d9b-c01fcde7c7db.png)
![image](https://user-images.githubusercontent.com/43743230/107613813-5b978080-6c49-11eb-8605-e92f6ab5ec0f.png)
![image](https://user-images.githubusercontent.com/43743230/107613849-6d792380-6c49-11eb-85f5-510010cca340.png)

If I change those values, it does 'nothing'. 
```
2021-02-11 08:07:05.807 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 27

2021-02-11 08:07:05.809 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 27

2021-02-11 08:07:05.810 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 32 to 27

2021-02-11 08:07:08.079 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Essbereich_YeelightBirnen_Helligkeit' received command 26

2021-02-11 08:07:08.085 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Essbereich_YeelightBirnen_Helligkeit' predicted to become 26

2021-02-11 08:07:08.088 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Essbereich_YeelightBirnen_Helligkeit' changed from 27 to 26
```
I am expecting the output channel or the lastexecution channel to update, like it does when I trigger the run. 

Let's reproduce this step by step: 
I disable autorun - then I change the input value - then I post ON via api to the item on the run-channel:
![image](https://user-images.githubusercontent.com/43743230/107614527-c5645a00-6c4a-11eb-9298-87fcd3aa0fa6.png)
I enable autorun - then I change the input value: nothing..
![image](https://user-images.githubusercontent.com/43743230/107614599-e88f0980-6c4a-11eb-9df2-a405c81f392b.png)

Giving your explanation, I suspect that the %2$s does not work properly. If it is not pointing to the input item (but to thurstday or null  or something like that ) than it does nothing.

**Comment by Rossko57** [comment]
It's really much better to paste the text of messages rather than screenshots.  It's searchable, copy/paste-able to highlight stuff, etc.

Let's be really clear about "change input".  You **must** send a **command** to the the Item linked to the `input` channel.  A state update will not do.
That is just terminology though, and on the face of it you ARE sending commands as shown in your `events.log` while `autorun=true`, but nothing triggers.

A possible cause though - the exec input channel is of **string** type, but it looks like you have linked to a Number? Dimmer? type Item.  You need to use a String type Item here.

In your use, you might have to have an interim String Item and a rule to make it work.

**Comment by openPhiL** [comment]
`You need to use a String type Item here`
Maybe this would work, I do have other workarounds too as my python just uses the API to read the value itself... 
But I still think it is a bug more than this issue would be a request for an enhancement. It was working in OH2.5 this way and it "should" work with any type of input. 

I removed those ugly pictures and replaced them with code.

**Comment by Rossko57** [comment]
It's a string type channel, not a bug.

**Comment by J-N-K** [comment]
It’s not a bug. The only bug is that textual configuration has not been removed as linking wrong item type is only possible in textual configuration.

**Comment by openPhiL** [comment]
I would agree to that view, but I am not using any text file, 100% of items and things are created in the webUI.

**Comment by J-N-K** [comment]
So you can link a Dimmer item to a String channel in the UI?

**Comment by openPhiL** [comment]
there are no restrictions, you can match everything. 
See this, I create a Dimmer and have all channels of a thing to link it to:
![image](https://user-images.githubusercontent.com/43743230/107742449-556bd780-6d0f-11eb-8ca8-c44b32a13ac6.png)

I was not aware that there should be a limitation, but you are right, in OH2s PaperUI, you couldn't. 

But I'm not saying you shouldn't though. It would create a lot of overhead (creating extra items and rules etc) if you could not link anything to a String channel, because you can convert pretty much anything to a String anyway. It would not be cool to restrict that, It would be cool to convert it, or better, transform it (user can define transformation). 

so.. is this issue to be moved to the UI repo?

**Comment by J-N-K** [comment]
Either UI or core. Transformation would need to be done in core.

**Comment by Rossko57** [comment]
> See this, I create a Dimmer and have all channels of a thing to link it to:

I wonder if most users come at this from the other direction, start at the Thing/channel and see what "suitable" Items it can find as potential links.

Did you ever try exec with a String Item and satisfy yourself it works as documented?
