### ISSUE TITLE
[shelly] Creating Equipment from Shelly Bulb Duo causes wrong min/max on colortemp slider

### ISSUE THREAD

**Issue by wzbfyb** [openhab/openhab-addons#10111]
## Expected Behavior
I can control the color temp from the generated items default widget :)

## Current Behavior
When an Item is created from the color temp channel, it has a wrong min/max. 
The channel is created as dimmer with min/max 2700/6500
thus the item that's created with a default widget min/max of 2700/6500 does not work, because due to the channel creation settings it maps to 0/100

## Possible Solution
don't set the min/max on creating the channel as Dimmer. Leave it as Number.
Or, at least create the default widgets with min/max 0/100

## Steps to Reproduce (for Bugs)
1. add a Shelly Duo Bulb thing
2. create Equipment from Thing
3. check the slider for colortemp. it shows 2700/6500 as min/max, which does not work. It has to be 0/100

## Context
one has to manually add a metadata entry to set the min/max of the widgets to 0/100

## Your Environment

* Version used: OH 3.0.0
* Debian 10, Docker

**Comment by markus7017** [comment]
I removed the min/max definition, please try the latest DEV build


---

Latest **DEV** builds: [3.1M5+](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true) or [3.0.x/3.1M1-M4](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true)  - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)
