### ISSUE TITLE
[homematic] gateway extras don't work when a custom id is used

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#10114]
## Expected Behavior
With OH3 I've started using custom IDs for things (added with the MainUI). The given ID should be used.

## Current Behavior
When I do so for the GATEWAY-EXTRAS Thing:

![image](https://user-images.githubusercontent.com/1475672/107434748-7542a600-6b2b-11eb-8688-59d820280029.png)

it results in:

![image](https://user-images.githubusercontent.com/1475672/107434787-812e6800-6b2b-11eb-9bbe-5302ec0c7be2.png)

It seems that the only valid value is "GWE00000000". Every other value I tried gives the above error message.

This makes it de facto impossible to use a custom ID when only one name is allowed ;-)

## Steps to Reproduce (for Bugs)
See above.

## Context
I want to use custom IDs for easier reading of my configuration files.

## Your Environment
OH 3.0.1

**Comment by MHerbst** [comment]
Yes, the only valid value currently is "GWE0000000". Because this is a "virtual device" and the binding uses this id to identify the device. Unfortunately, the documentation does not explicitly point this out.

Unfortunately, changing this is quite time-consuming.

**Comment by eikowagenknecht** [comment]
@MHerbst Thanks for looking into it. I've encountered similar issues with several bindings now. Seems like custom IDs are quite often problematic so I'm back to using the mostly cryptic autogenerated IDs again..

So what can we do about that?
1. Add functionality where a binding can signal to OH core / UI that it needs the default ID to be used. The "custom ID" button is not shown then. > Lots of work
2. Change all Addons where custom IDs are problematic > Lots of work
3. Add documentation for the cases where it is problematic. > Easy

I guess we'll stick with 3 then for the time being? I can create a PR against docs if you want.

**Comment by MHerbst** [comment]
@eikowagenknecht I agree. For the time being it's best to simply document it. If I find the time, I would like to do some greater refactorings in the binding. Then I would also try to change this.

> I can create a PR against docs if you want.
That would be great

**Comment by eikowagenknecht** [comment]
Allright, it's done :-)
