### ISSUE TITLE
[Xiaomi Mi IO] Improve robot vacuum cleaning map to ease UI integration

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-addons#10112]
### Current cleaning map implementation

The current cleaning map fills the unused area beyond the outline of the scanned cleaning area with a fixed blue color and a watermark:

![image](https://user-images.githubusercontent.com/11849305/107363503-8dd6a000-6ada-11eb-9338-790764815b52.png)

While the map is for sure an interesting element to be shown in UI's of openHAB, I see three points complicating the intergration:

1. The blue color does not subordinate well to the surrounding design
2. The blue area is too wide/to dominant
3. The openHAB watermark conflicts with neigboring or overlaid UI elements

These reasons lead to some tricky CSS workarounds to get it almost nicely integrated (notice the overlaid labels and icons to "use" the dominant blue area)
E.g.:

![image](https://user-images.githubusercontent.com/11849305/107365488-29691000-6add-11eb-998b-75842d657bd6.png)

### Improvement proposal

Currently I see the following options to ease the integration of the map into UI's

- **replace the blue** (background) color **by transparent**
- **crop the image** to the used area
- **omit the watermark** imprint

### Your Environment

- openhAB 3.1M1
- Roborock S5max

_references on the openHAB community forum:_
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1797
https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1337

_@marcelrv pointed (here: https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1725 ) to the relevant piece of code already:_

> It is not something that is selectable in the binding.
> You can recompile it with your preferred colors. Change them here https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/robot/RRMapDraw.java#L64-L91 4
>

**Comment by marcelrv** [comment]
like your sample widget!

The current 'blue style' is indeed borrowed from the v1 maps which was much less feature rich. It would be good to make the coloring configurable so it can suit everyones wishes.
If I make the style configurable, I'll also make the the text/logo optional

The cropping is indeed desirable.. I marked it in my 'roadmap' as a feature I would like https://github.com/openhab/openhab-addons/issues/7276 but it is bit beyond my programming skills. (the whole grapical thing was a first timer for me)
At the moment it just shows the picture as it is provided by the cloud
