### ISSUE TITLE
[influxdb] try to reconnect if connection lost

### ISSUE THREAD

**Issue by Fredo70** [openhab/openhab-addons#10129]
## Expected Behavior
If the connection between openHAB and influxdb is lost the service should try reconnect.

## Current Behavior
If the connection is lost, the service does not try to reconnect and no more data is stored.
In order for the data to be stored again, I have to go into the settings and save. Then the connection is re-established and the data is stored again.
https://community.openhab.org/t/influxdb-persistence-reconnection-if-connection-lost/116607

## Possible Solution
Try to reconnect. For example like jdbc or mongoDB.

## Steps to Reproduce (for Bugs)
1. Setup influxdb on another computer as openHAB
2. Disconnect and reconnect the influxdb from network (for example, unplug cable or restart DB server)
3. Check in influxdb if data are stored

## Context
openHAB and influxdb are on different computer and connected via WLAN, so the connection could be lost anytime.
I am new to openHAB and hope I haven't missed anything. I have not found a workaround either.

## Your Environment
* openhabian (Raspberry 2B), openHAB and influxdb addon 3.0.1
* InflusDB 2.0.3 on Ubuntu 20.04
* Home WLAN

**Comment by Fredo70** [comment]
@J-N-K I have tested your changes. Unfortunately without success.
The client is always there and ready. The health is also ok. But after a certain time, it no longer writes. There are also no errors in the log. Everything seems normal, except that the data no longer arrive.
I searched further myself and tried various things. Also without success.
Finally, I came up with the idea that it could be due to the authentication (that's a guess). I used the token instead of the password in the configuration and it works.

**Comment by Fredo70** [comment]
I searched further myself and tried various things. Also without success.
Finally, I came up with the idea that it could be due to the authentication (that’s a guess). I used the token instead of the password in the configuration and it works.

**Comment by lsiepel** [comment]
As a related PR was merged and the OP reported that he got it fixed after a configuration change, i close this ticket. If there is anything to add (or solve), please re-open.
