### ISSUE TITLE
Things from uninstalled Binding have to be removed twice

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#10125]
## Expected Behavior
After uninstallation of the Mail Binding I tried to remove the remaining stmp server Thing. Expectation would be that it is automatically removed together with the binding or can be manually removed later.

## Current Behavior
Thing goes into "REMOVING" state and remains there forever. After a restart of OH3 it goes back to UNINITIALIZED and a new try to remove it sets it into REMOVING indefinitely again.

This is the only log entry about it: `2021-02-11 15:46:41.383 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mail:smtp:server' changed from UNINITIALIZED to REMOVING`

## Steps to Reproduce (for Bugs)
1. Install Mail Binding
2. Create SMTP Thing
2. Uninstall Mail Binding
3. Try to remote SMTP Thing

## Your Environment
OH 3.0.1

## Workaround
Installing the binding again, removing the Thing and then uninstalling the Binding again works.

**Comment by J-N-K** [comment]
You should be able to click "remove" again and then confirm that you want to force remove. Is that not working for you?

**Comment by eikowagenknecht** [comment]
Thanks, this actually works:
![image](https://user-images.githubusercontent.com/1475672/107798251-29c30e80-6d5c-11eb-9b2e-15d6b93396de.png)
![image](https://user-images.githubusercontent.com/1475672/107798270-2f205900-6d5c-11eb-8f98-86fc5083c56d.png)
![image](https://user-images.githubusercontent.com/1475672/107798290-37789400-6d5c-11eb-9c2c-0871ec82cbe0.png)
![image](https://user-images.githubusercontent.com/1475672/107798331-3f383880-6d5c-11eb-80e5-cbbe5c057bd1.png)

I still think the user experience could be better here. When a binding is uninstalled and thus per definition can't react to the Thing deletion request, the user shouldn't have to reopen it and force remove it again.

**Comment by J-N-K** [comment]
This is an UI issue, then.

**Comment by Skinah** [comment]
Agree it is in the wrong repo unless it only happens with one binding. You have to do it twice if the handler is missing from you uninstalling the binding before removing things, or if an error occurs in the binding when the dispose function is called. Reopen it with the binding name if it only happens for one, or create a new issue in the correct repo.
