### ISSUE TITLE
[deconz] Make the lastseen channel for lights and power sockets available in openHAB

### ISSUE THREAD

**Issue by darkogorgievski** [openhab/openhab-addons#10149]
I would like to have the lastseen status for zigbee lights (all types lights) and power sockets available to use in OH. The idea is to calculate the health status (I do experience from time to time that my tradfri lights get stuck and I need to power cycle them). 
The lastseen values are already available in the REST API and are updating
```
```
{
"etag": "XX",
"hascolor": false,
"lastannounced": "2021-02-12T14:50:49Z",
"lastseen": "2021-02-14T13:21Z",
"manufacturername": "IKEA of Sweden",
"modelid": "TRADFRI bulb E27 W opal 1000lm",
"name": "Light Office",
"state": {
"alert": "none",
"bri": 254,
"on": false,
"reachable": true
},
"swversion": "1.2.214",
"type": "Dimmable light",
"uniqueid": "XXXXX"
```
```
{
"etag": "XXXXX",
"hascolor": false,
"lastannounced": "2021-01-05T08:40:23Z",
"lastseen": "2021-01-23T13:43Z",
"manufacturername": "IKEA of Sweden",
"modelid": "TRADFRI control outlet",
"name": "Lights Christmass Tree",
"state": {
"alert": "none",
"on": true,
"reachable": false
},
"swversion": "2.0.022",
"type": "On/Off plug-in unit",
"uniqueid": "XXXXXXX"
```

**Comment by J-N-K** [comment]
Fixed with #14622
