### ISSUE TITLE
[exec] Spaces in escaped argument result in multiple arguments

### ISSUE THREAD

**Issue by mariuskiessling** [openhab/openhab-addons#10158]
I just bumped openHAB from v2.5.0 to v3.0.1 and I am experiencing an issue with the exec binding. I hope that I just didn't miss anything in my update process but it looks to me like a bug with the exec add-on.

## My setup

I use the exec binding for a transformation inside a MQTT channel with the following setup.
```
Type dimmer : brightness "Brightness" [ stateTopic="zigbee2mqtt/Hue_Filament_Standard_E27_1/set", commandTopic="zigbee2mqtt/Hue_Filament_Standard_E27_1/set", transformationPatternOut="EXEC:/usr/local/bin/zlt brightness out %s", transformationPattern="EXEC:/usr/local/bin/zlt brightness in '%s'", retained=true]
```

Note the single quotes surrounding the  `%s` argument of the transformation pattern. A common expanded string for `s` is `{ "state": "ON/OFF", "brightness": 0-255 }`.

## Expected Behavior
In openHAB v2.5.0, using the single quotes around the `%s` argument resulted in the expanded string being considered one argument, not multiple space-separated ones. In my case, this resulted in an argument list of the exec script that looks like this:

Argument No. | Content
--- | ---
0 | /usr/local/bin/zlt
1 | brightness
2 | in
3 | { "state": "ON/OFF", "brightness": 0-255 }

## Current Behavior
With the update to v3.0.1, the single quotes no longer seem to be respected and result in individual arguments, broken on every space character like this:

Argument No. | Content
--- | ---
0 | `/usr/local/bin/zlt`
1 | `brightness`
2 | `in`
3 | `'{`
4 | `"state":`
5 | `"ON/OFF",`
6 | `"brightness":`
7 | ` 0-255`
8 | `}'`

## Steps to Reproduce (for Bugs)
1. Call an exec binding's script with a parameter that contains spaces but is enclosed by single quotes (e.g. { "state": "ON/OFF", "brightness": 0-255 }`
2. Print all the passed arguments in the script, e.g. using:
```
#!/bin/bash 
for i; do 
   echo $i
done
```

## Context
As said in the preamble, this issue only appeared after upgrading to openHAB v3.0.1. The setup as described above worked without issues in the previous v2.5.0 release.

## Your Environment
* openHAB: v3.0.1
* Exec binding: v3.0.1
* OS: Linux raspberrypi 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l GNU/Linux

**Comment by lsiepel** [comment]
@J-N-K  Some time ago you seem to have created a fix for this issue at your repo. It was closed without a merge. 
Can i create a PR based on your code to fix this? Or are there any other difficulties that this is not merged to openhab-addons yet?

**Comment by J-N-K** [comment]
Sure. But I'm not sue it fixes all issues.
