### ISSUE TITLE
Use “Location” from Configuration - System - Regional Setting as Global Attribute in Rules

### ISSUE THREAD

**Issue by funkstille** [openhab/openhab-addons#10163]
During the setup process of OH3 you can set up the location coordinates.
It would be very nice to use this exact location as global attribute 
in rules and functions like "distance from" and "distance  changed".

As a workaround you have to create a location like "home location" which is a duplicate to the location coordinates from the setup.

discussion thread
https://community.openhab.org/t/how-can-i-use-location-from-configuration-system-regional-setting-in-rules/53816

## Your Environment
general oenHAB Feature Request

**Comment by Hilbrand** [comment]
This repo is about add-ons. Please report this in openhab-core.
