### ISSUE TITLE
[MQTT] Deleting a MQTT Thing leaves stray subscriptions behind.

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab-addons#10177]
After deleting a MQTT Generic Thing and recreating a new one using a different Broker Thing, the new Thing is working correctly, however the system still is subscribed to the former topics via the old Broker Thing.

Raising the log:level of org.openhab.core does show WARN messages like:

`2021-02-16 13:22:29.237 [DEBUG] [.thing.internal.CommunicationManager] - Received event '98' for non-existing thing 'mqtt:topic:opuspi3MQTTBroker:Rolladen_Wohnzimmer_Thing', not forwarding it to the handler`
Actual Identifier: `mqtt:topic:opuspi4MQTTBroker:Rolladen_Wohnzimmer_Thing`

If Subscriptions are not deleted by deleting a Thing a way to delete such is needed.

**Comment by J-N-K** [comment]
Do you see a warning like `unsubscription on disposal failed for mqtt:topic:opuspi3MQTTBroker:Rolladen_Wohnzimmer_Thing`?

**Comment by JueBag** [comment]
Actually, I did notice the WARN messages only while searching for something else.
I had removed the "old" some time ago and can't say if there was such a WARN. I did notice that I had to click REMOVE twice in order to remove the thing completly.

**Comment by J-N-K** [comment]
Reboot should fix the problem. Why was it necessary to remove twice? Did you remove the broker prior to the thing?

**Comment by JueBag** [comment]
As before, the causing action happened some time ago.  However the removal of things either seems to take more time then I did expect or was blocked (by the WARN?). 
Is really a reboot needed (a restart of the openHAB service is not enough)?

**Comment by J-N-K** [comment]
Yes, restarting openHAB should be enough. Maybe even restarting the mqtt core bundle would be sufficient.

**Comment by JueBag** [comment]
Understood, however having done several restarts, reboots and stopping of the mosquitto service for deleting the mosquitto.db I was not able to get rid of those stray subscriptions.

**Comment by J-N-K** [comment]
Can you check if there are leftovers of that thing in the JSON-db? Do you see it in the REST API? There is no persistence in the mqtt bundles, so it seem that the subscriptions are newly created when openHAB starts again. That is very strange.

**Comment by JueBag** [comment]
REST API and JSON-DB have been checked, no old things in there ( I wouldn't have reported if they would have been there).

**Comment by JueBag** [comment]
I looked deeper into the JOSON-DB. There were stored LINKS correlating with the WARN messages. Reoving all those stale LINKS did stop the messages.
Actually I had more of those stale links.
IMHO such stale links do not show to the average user (I noticed only do to raising the log:level of `org.openhab.core`). Is there a real need to remove such links? If not, IMHO the procedure I did is sufficient and no change is needed.

**Comment by J-N-K** [comment]
Interesting that links alone produce subscriptions. IMO this should be investigated.

**Comment by JueBag** [comment]
OK. In this case I leave this one open?

**Comment by lsiepel** [comment]
I think this can be closed as recent openHAB version had a health check tool that enables to remove orphaned links.
Also tried to reproduce this on 4.2 and was unable to do so. If needed this can be re-opened
