### ISSUE TITLE
[jdbc] Persistence in OH 3 creates a new table for every new item, even if it is not to be persisted

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#10201]
openHAB 3.0.1.

I have defined that only items that are members of certain groups are to be persisted:

```
Items {
       Persist* : strategy = everyChange, restoreOnStartup
       HM* : strategy = every15Minutes, everyChange, restoreOnStartup
       CO2 : strategy = restoreOnStartup, every15Minutes, everyChange
       WatchDog* : strategy = restoreOnStartup, everyHour, everyChange
}
```

This still works in OH 3, but in contrast to OH 2.5, it still creates (empty) tables for ALL new items, even if they are not a member of those groups.

It should only create tables for items, that are defined to be persisted, like in OH 2.5.

**Comment by livinghere** [comment]
To me it seems NOT to be only directly related to jdbc! Similar things happen with rrd4j as persistence service (which is part of the openhab-core).

Environment:
- Raspbian Buster (32 bit, current patch level of today),
- Openhab 3.0.1 running as docker image,
- rrd4j as default persistence,
- mapdb persistence service is installed and used as well (but not for any items in the group GraphPersist),
- any item of the group GraphPersist is also listed in the .items list of the rrd4j.cfg-file (before creating it)

**openhab/conf/persistence/rrd4j.persist**:
```
Strategies { everyMinute             : "0 * * * * ?" }
Items { GraphPersist* : strategy = everyMinute }
```

**openhab/conf/services/rrd4j.cfg**:
```
# rrd4j Konfiguration für eine stark verkleinerte Datensammlung, die max. 1 Jahr lang geht,
# gegenüber den sehr langen Default-Werten.
# Achtung: die .items-Definition MUSS tatsächlich alle Items einzeln aufzählen,
# die Verwendung der Gruppe (GraphPersist*) funktioniert nicht!
rrd1y.def=GAUGE,120,U,U,60
rrd1y.archives=AVERAGE,0.5,1,480:AVERAGE,0.5,4,360:AVERAGE,0.5,15,644:AVERAGE,0.5,60,720:AVERAGE,0.5,720,730
rrd1y.items=item-nr1,item-nr2
```

What happens:
- When a new item is created, which is NOT part of the group GraphPersist, a .rrd-DB-file is created which the compiled-in default rrd-configuration (but of course: never used/updated). Usually I am deleting these unneccessary files after item creation, but...
- When an item, which is not part of the group GraphPersist, is modified (i.e. by changing the label) again a .rrd-DB-file is created with the default rrd-configuration.
- Even when an item is deleted, a .rrd-DB-file is created...

To me it looks as if the creation of a persistence DB-file always happens (at least, when rrd4j is the default service), without respecting the strategy configuration file or the service configuration file. Looks like a bug in the logic flow of item creation/modification/deletion.

**Comment by cweitkamp** [comment]
I found the reason for this behavior when using JDBC persistence - see https://github.com/openhab/openhab-addons/issues/11526#issuecomment-1004855322.
