### ISSUE TITLE
[homematic] [HmIP-SWSD] Tried to set DecimalType on StringItem error

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#10206]
## Expected Behavior
Item type == Channel type should lead to a valid configuration

## Current Behavior
![image](https://user-images.githubusercontent.com/1475672/108624466-7043f780-7445-11eb-930c-3c004c007845.png)

Item: `String	EG_Schlafen_Rauchmelder 	"Rauchalarm"	(e_EG_Schlafen_Rauchmelder)	["Alarm"]	{ channel="homematic:HmIP-SWSD:ccu3:000A58A9AC3E08:1#SMOKE_DETECTOR_ALARM_STATUS" }`

Error message in Log: `2021-02-21 12:56:12.601 [ERROR] [org.openhab.core.items.GenericItem  ] - Tried to set invalid state 0.0 (DecimalType) on item EG_Schlafen_Rauchmelder of type StringItem, ignoring it`

## Possible Solution
Workaround: Just use a switch item anyways, even though the channel says "String": `2021-02-21 12:58:23.388 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_Schlafen_Rauchmelder' changed from NULL to OFF`

Not sure if this also works for the "Alarm" / ON state, manually activating the alarm does not seem to set this to ON, just does nothing :-(

## Your Environment
OH3.0.1, CCU3 with current Raspberrymatic

**Comment by eikowagenknecht** [comment]
Just tried it again for another HmIP-SWSD and that correctly showed the String <IDLE_OFF> after the initial error:

```
2021-02-21 13:16:53.256 [ERROR] [org.openhab.core.items.GenericItem  ] - Tried to set invalid state 0.0 (DecimalType) on item EG_Flur_Rauchmelder of type StringItem, ignoring it

==> /var/log/openhab/events.log <==
2021-02-21 13:16:53.259 [INFO ] [openhab.event.ItemUpdatedEvent      ] - Item 'EG_Flur_Rauchmelder' has been updated.
2021-02-21 13:16:53.318 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_FlurRauchmelder' changed from NULL to IDLE_OFF
```

**Comment by MHerbst** [comment]
According to the documentation SMOKE_DETECTOR_ALARM_STATUS is an enum with 4 different values:
![image](https://user-images.githubusercontent.com/616792/108625426-2cec8780-744b-11eb-841c-24d2304e23a6.png)

That's why the channel type is a string and not a switch.

**Comment by eikowagenknecht** [comment]
I understand and that makes sense.. so forget about my "Switch" idea. The error message suggest that some internal conversion in the Binding is not working correctly though, I'd say?

With a String item (as it should be): `Tried to set invalid state 0.0 (DecimalType) on item EG_Flur_Rauchmelder of type StringItem, ignoring it`

**Comment by MHerbst** [comment]
This is a bit strange. Normally the binding uses the enum values retrieved from the CCU and converts the values accordingly. But sometimes the meta data provided by the ccu are incomplete for HmIP devices. Need to investigate.

Maybe some trace log output could help ...

**Comment by eikowagenknecht** [comment]
Couldn't reproduce this for a week now, so unfortunately I can't provide trace data.

**Comment by eikowagenknecht** [comment]
Closing my issues with openHAB that seem to have gone stale.
