### ISSUE TITLE
[shelly] Roller control channel flipping between 0 and 100

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#10219]
Problem description
Everything works fine with the latest Shelly binding (and also the 3.0.1 stable version) with buttons, sensors, curtains and windows. The only small problem I have is that every fifteen seconds or so, Shelly (I guess) reports the state like this, over and over again:

14:15:20.423 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 0.0 to 100.0
14:15:22.865 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 100.0 to 0.0
14:15:35.438 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 0.0 to 100.0
14:15:38.152 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 100.0 to 0.0
14:16:01.225 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 0.0 to 100.0
14:16:02.689 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Curtains' changed from 100.0 to 0.0
....
So everything is working fine except the logging. Buttons respond correctly, window and curtains open/close correctly and show up in the openHAB interface and can be controlled from there.

**Comment by s0170071** [comment]
one year later, I am still experiencing this issue. I use OH 3.2.0 and binding ver.3.2.0. Is there any workaround ?
