### ISSUE TITLE
[deconz] Update lightgroup brightness from lights in lightgroup

### ISSUE THREAD

**Issue by bakkerv** [openhab/openhab-addons#10211]
Using the color channel of a lightgroup, you can set values for all lights within the group.  In my use case, I use it to set the brightness of 5 GU-10 lights.

However, if the lights are controlled outside of OH, the group state does not represent the actual state of the group. 
For example, when I control the light via a remote, the OH channel is not updated.

Within Phoscon, light events are used to properly display the value of the group. 

* Version used: OpenHab 3.1.0M1

I'm currently implementing an approach to monitor the lights within the group and update the color channel accordingly.
(https://github.com/bakkerv/openhab-addons)

**Comment by J-N-K** [comment]
Not possible, states besides anyOn/allOn are not reported by deconz
