### ISSUE TITLE
[keba] KEBA Power reported wrong

### ISSUE THREAD

**Issue by ThomasBrodkorb** [openhab/openhab-addons#10232]
KEBA 3.0.1 binding reports wrong power and current values (different from the KEBA web page):

according to metering at web page:

Voltage:  232|0|0
Current:  0,00|0,00|0,00
RealPower:  0,00kW | 0,0%

reported by binding:

Voltage:  235|1|1
Current:  13230|5|5 (mA)
RealPower:  3085W | 100,0%

This does not match at all.
Most of the things I have to control are relying on getting proper energy vluaes from the PV and the KEBA to detect if enough power.

It seems like the binding crashes from time to time. Disabling and Enabling it helps to get the new values.
Not sure if that is a problem of the binding or OH3.0.1 running on OpenHabian on a PI4.

**Comment by kaikreuzer** [comment]
You might want to test the latest snapshot as there was just a major refactoring of the KEBA binding with https://github.com/openhab/openhab-addons/pull/10179.

**Comment by lsiepel** [comment]
@ThomasBrodkorb can you confirm if this is still an active issue with 3.4.0? As Kai pointed out this might already been fixed since 3.1.0

**Comment by ThomasBrodkorb** [comment]
Cannot tell, running on 3.3.0

**Comment by lsiepel** [comment]
> Cannot tell, running on 3.3.0

The change was added in 3.1.0, so it should be working correctly in 3.3.0

**Comment by ThomasBrodkorb** [comment]
Will check, when I next charge the car.
This might take some time as there is no sun in Austria these days.

**Comment by ThomasBrodkorb** [comment]
By the way, I changed my rule, so the power is not required currently:

`_chargepower = (Keba_CurrentPhase1.state as Number) * (Keba_VoltagePhase1.state as Number) + (Keba_CurrentPhase2.state as Number) * (Keba_VoltagePhase2.state as Number) * (Keba_CurrentPhase3.state as Number) * (Keba_VoltagePhase3.state as Number);`
So I have a workaround.
