### ISSUE TITLE
[deCONZ]  missing Brightness and On Time Channel on all things

### ISSUE THREAD

**Issue by cablesandcoffee** [openhab/openhab-addons#10233]
## Expected Behavior

Brightness and On Time Channels showing when looking on a thing channels
![Screenshot from 2021-02-25 18-15-24](https://user-images.githubusercontent.com/63468500/109191355-60eee200-7796-11eb-8d7e-e9b67784b9d7.png)

## Current Behavior

Brightness and On Time Channel are missing on all things. If removing the thing and adding it back the channels are visible again. Items previously linked to the disappeared things are still working though.

![Screenshot from 2021-02-25 18-15-16](https://user-images.githubusercontent.com/63468500/109191374-6815f000-7796-11eb-9a5e-11ebcce40f8a.png)

## Steps to Reproduce (for Bugs)

1. I installed the latest Snapshot binding of deCONZ. Version 3.1.0.202102240322. I installed it to get rid of another issue that is now fixed. I'm not used to doing this so I don't know if this can be the reason. Should you expect that to work on Openhabian 3.1.0.M1?
2.

## Your Environment

* Version used: Openhabian 3.1.0.M1, using Snapshot version of deCONZ binding. Version: 3.1.0.202102240322

**Comment by J-N-K** [comment]
Related to the change of the channel-type. Managed things do not get updated. Known issue in core since years.

**Comment by lillaeriika** [comment]
Aha, so you should just remove your things and add them again?

**Comment by J-N-K** [comment]
Yes, that's unfortunately the only way.

**Comment by lillaeriika** [comment]
Okay then I'll do that. I thought about it before but it's much easier if
someone tells you it is the only choice you have. :)

Thank you for the quick response!

**Comment by J-N-K** [comment]
Not relevant anymore, old things get updated since #14622
