### ISSUE TITLE
[Chromecast] HANDLER_REGISTERING_ERROR Netmask '-1' is out of bounds (1-32)

### ISSUE THREAD

**Issue by danjgill** [openhab/openhab-addons#10253]
All of my chromecast devices show up in THINGS with a grey circle, and the error "HANDLER_REGISTERING_ERROR
Netmask '-1' is out of bounds (1-32)".  I look into my OH3 network settings and I see that my VPN interface indeed has a 10.x.x.x address with a -1 netmask, although IPCONFIG /ALL shows the mask to be 255.255.255.0. This is running OH3 on Windows 10. 

In either case, this is wrong because I have selected my 192.168.x.x address to be my primary address, and all the Google Home devices are on the 192.168.x.x subnet.

It seems that the VPN provider sets up a point-to-point link on the 10.x.x.x network, and this somehow interferes with doing regular chromecast on my default network.

## Expected Behavior

Expect chromecast devices to register properly and show as "GREEN"

## Current Behavior

All chromecast devices exhibit an unitialized state and the error "HANDLER_REGISTERING_ERROR
Netmask '-1' is out of bounds (1-32)"

## Possible Solution

Fairly sure this is related to incorrect handling by OH3 of the point-to-point VPN connection.
 
## Steps to Reproduce (for Bugs)

1.
2.

## Context

Unable to use chromecast devices
## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
OH3 with Chromecast binding 3.0.0
Windows 10 Desktop

**Comment by lsiepel** [comment]
As this issue is allmost two years old i wonder if this has been resolved?

A netmask of -1 is certainly out of the valid range. Not sure if that is caused by the binding or some dependency or your setup. Before we proceed, i like to be sure if this issue is still happening with version 3.4.0. Could you let me know?

**Comment by danjgill** [comment]
So I tried this with 3.4.0. The good news is that it now seems to attach to the chromecast devices via IPv6, and they all show connected. 

I do see under Setting/Network Settings that the network address of my VPN adapter is showing as 10.X.X.X/-1, so there is still some sort of problem there, however, it is not keeping OH from working. We might as well close this one.

**Comment by lolodomo** [comment]
Note that the coming 3.4 patch will ignore IP v6 in discovery code.
