### ISSUE TITLE
[rfxcom] Energy Sensor - Exception while formatting value (d != java.math.BigDecimal)

### ISSUE THREAD

**Issue by roscoegray** [openhab/openhab-addons#10251]
Error with rfxcom Energy Sensor Channel, Exception while formatting value

My issue...
`[WARN ] [e.internal.SseItemStatesEventBuilder] - Exception while formatting value '7520157.67260111' of item HouseEnergyMonitor_TotalUsage with format '%d Wh': d != java.math.BigDecimal`

Belive it has something to do with the channels.xml for this energy sensor thing, having the state pattern for _totalusage_  as "%d Wh" but receiving a decimal number?
[https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.rfxcom/src/main/resources/OH-INF/thing/channels.xml](url)

![image](https://user-images.githubusercontent.com/27781584/109385488-239c6880-78ec-11eb-905e-0fd0bc207c40.png)

* Version used: openHAB 3.0.0 Release Build, rfxcom 3.0.0
* Environment: openhabian on Raspberry Pi 3 Model B Rev 1.2 #

**Comment by Rossko57** [comment]
Are you using a profile on the link to this channel?  It has been seen that "xml supplied" formatter is incorrectly applied to transform _output_ in OH3.0

**Comment by roscoegray** [comment]
No, no profile on the link to the channel. I got another energy monitor yesterday and not having the same issue, but the number is smaller...
![image](https://user-images.githubusercontent.com/27781584/109851274-668f7080-7c4b-11eb-9f6c-b564eea12e8e.png)
so is it because the length of the number is bigger than BigDecimal allows (32bit?)

**Comment by Rossko57** [comment]
> is it because the length of the number is bigger than BigDecimal allows (32bit?)

I think it might be.  The actual size of the number is well within BigDecimal scope, but that number of different digits cannot I think be represented in BigDecimal.   That's mean it's not going to fit into a Number type Item either, without rounding.
I think this needs to be dealt with within the binding.

**Comment by martinvw** [comment]
Hello @Rossko57, 

I'm working on some other related changes and do believe the issue is indeed a wrong formatter I propose the following fix:

```diff
	<channel-type id="totalusage">
		<item-type>Number</item-type>
		<label>Total Usage</label>
		<description>Used energy in Watt hours</description>
-		<state pattern="%d Wh" readOnly="true"></state>
+		<state pattern="%.2f Wh" readOnly="true"></state>
	</channel-type>
```
