### ISSUE TITLE
[iCalendar] ExecutionException 

### ISSUE THREAD

**Issue by GekoCH** [openhab/openhab-addons#10268]
I have currently 5 iCalenders from my nextcloud all working fine as a thing in OpenHAB.
Now I added another one with the same properties etc. as the others but I get this error: 

`ExecutionException message is: Max requests queued per destination 1024 exceeded for HttpDestination[https://***]@3a61f4e4,queue=1024,pool=DuplexConnectionPool@73652e5c[c=2/2,a=2,i=0]`

**Comment by andrewfg** [comment]
@daMihe ping (in case you did not see this yourself)

**Comment by daMihe** [comment]
Thank you @andrewfg for the ping, afaik github does not allow to monitor specific issues.

Are there any further messages from icalendar? Please append a bit more logs and add more details about your configuration and the system running OH.

**Comment by GekoCH** [comment]
there are not more logs... as I wrote the other calenders do work from the same source (nextcloud) however this one calendar does not work and I have no Idea what I've done differently. Should I send you a part of the calendar (ics) or what do you need?

**Comment by daMihe** [comment]
I don't think the calendar itself is the issue at this point. Maybe Nextcloud is doing something strange - or your system. Please post more details and increase the loglevel generally.

**Comment by GekoCH** [comment]
strange I changed nothing but today it started working... so no more errors everything is fine...

**Comment by andrewfg** [comment]
> Max requests queued per destination 1024 exceeded

My guess: this probably indicates that your calendar server was unresponsive and that http requests were backing up; anf presumably today the server is more responsive; so this would indicate a problem in the server, not the binding..

**Comment by daMihe** [comment]
Not sure, as the request seem to get queued up. But without further details that is just a guess. Feel free to reopen with more details if the problem appears again.
