### ISSUE TITLE
[amazonalexacontrol] Add upperSetpoint and lowerSetpoint to ThermostatController

### ISSUE THREAD

**Issue by BigGeorgeTx** [openhab/openhab-addons#10260]
I keep my thermostat in Auto mode, which means it has a lowerSetpoint property and an upperSetpoint property, but no targetSetpoint property (https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-thermostatcontroller.html).  The behavior I see in OpenHAB is consistent with this:  the actual temperature mapped to the Alexa.TemperatureSensor works great, while the TargetSetpoint is undefined.

I believe that at least one reason for this is that in the https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.amazonechocontrol/src/main/resources/OH-INF/thing/thing-types.xml file, only the targetSetpoint channel-type ID is defined.  I will look through the code and see what else I see that would need to be added.  It is probably beyond my limited my programming skills do develop a pull request, so I thought it would be better to open this request.

**Comment by BigGeorgeTx** [comment]
Continuing to look at it, it appears it would take more than just adding the channels.  The meat of the thermostat is handled here:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerThermostatController.java

This would need to be updated to handle upper and lower setpoints.

**Comment by djcampbell** [comment]
I have this fixed and working in my fork. Can submit a PR if interested.

I've added channels for thermostatMode, upperSetpoint and lowerSetpoint.
