### ISSUE TITLE
[Millheat] Unable to initialize Mill Heating API bridge due to faulty time zone

### ISSUE THREAD

**Issue by jacobm85** [openhab/openhab-addons#10271]
## Expected Behavior
When adding the Mill Heating API bridge after adding the binding, it should discover homes, rooms and heaters. 

## Current Behavior
After adding the Mill Heating API bridge, it stays at INITIALIZING. 
No other things can be found when scanning. Adding a home, room or heater thing manually does not work.
Logs shows:
`java.time.DateTimeException: Invalid ID for ZoneOffset, non numeric characters found: +1:00`

Full logs [here](https://community.openhab.org/t/solved-millheat-wifi-electric-heater-openhab-binding/17224/54?u=jacob).

## Possible Solution
Change what is allowed as a time zone. 

## Steps to Reproduce (for Bugs)
1. Make sure time zone is "GMT +1:00" in the Mill app for iOS/Android. (This can't be changed in their app, only displayed)
2. Add Mill Heating API, and provide necessary information for it to function.
3. Check logs.

## Context
Unable to use the binding. 
Can't change time zone in the Mill app either (only display the current time zone for each house), so there is no current easy workaround.

## Your Environment
* Version used: OH3.0.1 release build. OpenHABian on a RPI3b

**Comment by seime** [comment]
App shows correct timezone offset again, cannot reproduce. Assuming API has been fixed. 

No response from reporter. Closing.

**Comment by jacobm85** [comment]
> @jacobm85 This suddenly started working for me again, maybe Mill changed their response. The code should still be made more robust, but could you verify that this is still a problem for you?

Hi, yes it seems to work now! Do not know when it changed. Noticed that their app also required a logout/login.
