### ISSUE TITLE
[tr064] Provide info from AVM OnlineMonitor

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#10287]
Please provide values from the TR-064 AVM extension OnlineMonitor.

See here: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wancommonifconfigSCPD.pdf

Thanks!

**Comment by hmerk** [comment]
Isn‘t the requested information already available on the WAN subdevice channels ?
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.tr064#wan-subdevice-channels

**Comment by J-N-K** [comment]
No, what is provided is the rate for the connection (i.e. the handshake result), not the actual transfer rate. This is not directly available from TR-064 as a value.

**Comment by lsiepel** [comment]
@sidamos I'm no expert, but as @J-N-K said it is not possible to get this value from the device, i assume we can close this issue?
If not please re-open.
