### ISSUE TITLE
[somfytahoma] Why not using the common HTTP client ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10284]
@octa22 : I see the current implementation creates a specific HTTP client for the binding. Is there a valid reason to not simply use the common HTTP client provided by the core framework ?

**Comment by octa22** [comment]
I do not remember exactly, but one user had two bridges and was facing problems so I had to change the common HttpClient to this solution.

**Comment by lolodomo** [comment]
Let's close the subject.
