### ISSUE TITLE
[KNX] Number channel not displayed as Setpoint (value is readonly)

### ISSUE THREAD

**Issue by ihrigb** [openhab/openhab-addons#10283]
A configured number channel with a listening GA and a main GA does display the number, but it is not editable.

## Expected Behavior
When defining a number, it should be editable via the setpoint control.

## Current Behavior
It is displayed with the "Analyse" button, so only a readable value.

## Steps to Reproduce (for Bugs)
1. Take a KNX device (configured bridge and so on, everything is working fine). Configure a number channel for it. My GA: `2/1/0+<2/4/0`. Both are _9.001_ datapoints.
2. Use _Create Equipment from Thing_ in model builder and select device and channel.
3. Look into the newly created point. It is not editable.

## Context
Trying to setup basic control for a KNX heating actor.

## Your Environment

* Version used: 3.0.1 and 3.1.0.M2
* Environment name and version: Chrome 88; openhabian v1.6.3
* Operating System and version Desktop Win 10, Mobile Android, Mobile App
* It works in OH2 Sitemaps.

**Comment by lsiepel** [comment]
Isn’t this more a gui related issue? Not able to edit a value? Did you ever get this sorted?

**Comment by ihrigb** [comment]
Too long ago, I cannot remember the issue. Plus I currently do not use openHab.
