### ISSUE TITLE
[fronius] did not work with new Fronius TS 65a-3 no data

### ISSUE THREAD

**Issue by Schroecki83** [openhab/openhab-addons#10294]
Yesterday I finally got my PV system. Are Fronius products.

Now I only have the problem that the inverter provides me with all the data via the Datamanger 2.0, but the SmartMeter does not.

I stuck to the documentation from Openhab.org when embedding in Openhab.

I suspect that it is a completely new SmartMeter, that the error is in the binding.

## Code for OH
* fronius.things:
Bridge fronius:bridge:mybridge "Photovoltaik" @ "PV Anlage" [hostname="192.168.0.54", refreshInterval=5] {
    Thing powerinverter myinverter "Fronius Smyo" @ "PV Anlage" [deviceId=1]
    Thing meter mymeter "Fronius Smart Meter" @ "PV Anlage" [deviceId=0]
}
* fronius.itmes:
Group pv "Photovoltaik"
Group gFroniusPV_influx (Fronius_sensor)
Number Meter_EnergyConsumed "Leistung verbraucht [%.2f Wh]"     (gFroniusPV_influx) { channel="fronius:meter:mybridge:mymeter:energyrealsumconsumed" }
Number Meter_EnergyProduced "Leistung erzeugt [%.2f Wh]"        (gFroniusPV_influx) { channel="fronius:meter:mybridge:mymeter:energyrealsumproduced" }
Number Meter_Enable                                             { channel="fronius:meter:mybridge:mymeter:enable" }
Number Meter_Location                                           { channel="fronius:meter:mybridge:mymeter:location" }

## Steps to Reproduce (for Bugs)

1. New Installed Fronius Symo 6.0.3 with Datamanager 
2. New Installed Fornius Smart Meter TS 65a-3

## Your Environment

* Version used: openHAB 2.5.11

**Comment by jimtng** [comment]
@Schroecki83 as I don't have the same model of smart meter, could you please provide some sample JSON data.

To do this, open this URL in your browser:
`http://%IP%/solar_api/v1/GetMeterRealtimeData.cgi?Scope=Device&DeviceId=%DEVICEID%&DataCollection=MeterRealtimeData`

Change the `%IP%` with the ip address of your inverter, and `%DEVICEID%` to the correct deviceid (probably either `0` or `1`)

**Comment by Schroecki83** [comment]
Hi @jimtng,

meanwhile i can read data from the SmartMeter, but i didn't change anything on my system.

btw the thread can be closed.
