### ISSUE TITLE
[homematic] readTransform - link contact to digital I/O

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-addons#10297]
I use wired components for my window contacts. Some are connected to contact inputs, others to digital inputs. 
The contacts read OPEN/CLOSE, the digital inputs 0/1
When I use the windows as a group, these are displayed and handled differently when iterating through them. 

It would be handy to directly transform the value from one to the other by means of a readTransform attribute, similar to what the modbus binding offers. So that I can link a contact item to digital input.

## Your Environment
OH3.01 @RPI4

**Comment by Rossko57** [comment]
There is a workaround (in OH3 only) using a transform profile on the channel link (probably using a MAP) to connect a number(?) type channel to a Contact type Item.
But doing "at source" i.e. binding would seem more logical for a binary state.

**Comment by MHerbst** [comment]
@s0170071 Which device are you using? I will have to check the data point definitions in the Homematic documentation.

The binding creates the channel definitions based on meta data it retrieves from the CCU. Currently, channels of type "Contact" are only created if the data points are defined as "ENUM".

**Comment by s0170071** [comment]
```
Thing HMW-Sen-SC-12-DR KEQ0006336 "Wired_12I" // these are contacts
Thing HMW-IO-12-Sw14-DR MEQ0808163 "Wired_12I_14O" // these are digital I/O

```
The items are linked to these channels: 
```
channel="homematic:HMW-IO-12-Sw14-DR:ccu:MEQ08xxxxx:17#STATE" 
channel="homematic:HMW-Sen-SC-12-DR:ccu:KEQ00xxxxx:3#SENSOR"
```
Can the binding just provide both, STATE and SENSOR whenever either is offered by the hardware ? This way there is no breaking changes or syntax change :-)
Of course STATE returns 0/1 and SENSOR returns OPEN/CLOSED where 1 is the same as CLOSED

**Comment by MHerbst** [comment]
As I mentioned before, the binding uses the meta data returned from the CCU to derive the channel definitions. For the HMW-Sen-SC device the data points are named SENSOR and are booleans. This means they will be created as switches. Changing this rule would mean a breaking change.

Creating to channels for the data point ist not so easy. It would mean to implement some special handling especially for this device (and then for another one and another ...). I have got some ideas to extend the binding in a way that allows a user to customize how the channels are derived from the meta data.

In the mean time I would recommend either to use a transform profile of define a proxy item of type contact and use a simple rule.

**Comment by s0170071** [comment]
found a workaround. Since OH3, there is a transform option that you can apply to items. I use the map transform  to map 1 to CLOSED and 1 to OPEN. Of course this is then a contact item rather than a number.
