### ISSUE TITLE
[somfytahoma] Channels not set at startup

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10291]
When the binding is started, the channels are not initialized. They are as soon as there is a change of the corresponding state.
Unfortunately, the binding is relying on the hypothesis that a REFRESH command will be sent at startup to all linked channels.
This is something that was done in OH2 but no more in OH3.
@octa22 : it is necessary to trigger the refresh of channels at startup. I am not yet sure what is the best way to do it considering the binding architecture. But very probably in the `initialize` method of class `SomfyTahomaBaseThingHandler`.

**Comment by octa22** [comment]
There was this feature in the past but several users with more devices were complaining that the threshold of API was reached - there were encountering the too many requests error, so I had to change the initializatuon to a less aggressive way. So be careful ... a solution to this would be an initialization based on the getSetup cached response, but for sure a device per device initialization is a bad way.

**Comment by lolodomo** [comment]
Ok. Yes if we make a request for each channel, it could lead a many requests. So yes, the use of `getSetup` or `getDevices` looks better. We could then cache the attribute containing the unit too.

**Comment by lolodomo** [comment]
I implemented the solution with a request for each thing getting the device information. 
Works well but I agree that it could lead to a lot of requests in case the user has many Tacoma devices. 
So I will switch to your proposal to run and cache the result of getSetup. But I propose to set the cache duration relatively short like for example 30 seconds to reduce the risk of outdated data. At least, this cache will be used at binding startup.

**Comment by octa22** [comment]
Sounds good, the cache should have rather short duration
