### ISSUE TITLE
[MiIO] Error on changing binding configuration

### ISSUE THREAD

**Issue by antroids** [openhab/openhab-addons#10292]
## Expected Behavior
According with the MiIO documentation no binding configuration is required. 
I should be able to change and remove any configuration parameters.

## Current Behavior
a) Error massage added to the log file after any change of binding configuration.
b) Cannot remove Username and/or Password values from binding config.
c) 281 │ Waiting │  80 │ 3.0.1                   │ openHAB Add-ons :: Bundles :: Xiaomi Mi IO Binding

## Steps to Reproduce (for Bugs)
a1) Change any binding config value.
a2) Error message added to the log.

b1) Remove Username or Password or Country value by clicking X.
b2) Save binding config.
b3) Open binding config for editing again.
b4) Removed values restored, error message added to the log.

## Context
I have a bunch or errors in the log:
[INFO ] [miio.internal.cloud.MiCloudConnector] - Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 0
Cloud connection is not required for me anymore, so I'm trying to disable it and use only local discovery.

## Your Environment
* Version used: 3.0.1
* Environment name and version: Chromium 88, openjdk version "11.0.10" 2021-01-19
* Operating System and version: desctop, Ubuntu 20.04.2, x86_64
* 
[error.log](https://github.com/openhab/openhab-addons/files/6096041/error.log)

**Comment by antroids** [comment]
Updated config values to empty by API request with payload:
{
  "country": "",
  "password": "",
  "username": ""
}

But got the same error, as in the error.log.

**Comment by marcelrv** [comment]
I don't think I can influcence this behaviour from the binding side. (it does not seem to accept removing of already set properties. based on your finding)

I think it is better to register this as an issue in the core repo as it involves a framework capability.

Wrt to the error... I think once indeed the userID/pwd are cleared the errormessage goes away.
To fix it manually, you prob can stop OH and delete/edit the binding config file. If I remember well it is located somewhere in `userdata\config\binding` but that might be different depending yiur installation

**Comment by antroids** [comment]
Looks like there are two different issues: first on ui side with removing properties and second with "Error getting logon location URL" on binding side. 
I'll check the first on new OH release. 
Any idea on the second one? Maybe Xiaomi changed something in the login flow. I'm asking just to have info in this issue - not using Xiaomi cloud services anymore.

**Comment by marcelrv** [comment]
the 2nd one is indeed something from the binding.
Maybe Xiaomi changed something in the cloud logon process. The whole logon process  is kind of tricky and reverse engineered from looking how the mihome app is loggin on.
Newer versions may indeed use different methods, or you use different method than me (I think Xiaomi allows to logon with userId, with email and with phone#) and maybe some depending on the country.
I always logon with my email +pwd.

You can try to run the cloud stuff with trace loggin it will reveil the communication and maybe hints at what goes wrong.
`log:set TRACE org.openhab.binding.miio.internal.cloud`
(to set it back to normal later use log:set info org.openhab.binding.miio.internal.cloud)

**Comment by marcelrv** [comment]
as no more response, closing the issue
