### ISSUE TITLE
[sonos] Firmware update for Ikea Symfonisk speakers breaking discovery in OpenHAB sonos binding

### ISSUE THREAD

**Issue by Marlow925** [openhab/openhab-addons#10313]
It looks like, that some time in the last 24 hours, an update was rolled out to the Ikea Symfonisk speakers.

My bookshelf speakers were back in my inbox this morning (both in OH 2.5.12 and OH 3.1.0M2), named:
SYMFONISK Bookshelf (Dining Room) and SYMFONISK Bookshelf (Office). 2 of each.

The old properties content (before deleting the device from my Things) was:
hardwareVersion	1.20.3.3-2.0
identification	Office
ipAddress	10.55.199.122
macAddress	34:7E:5C:F8:05:9C
modelId	SYMFONISK
serialNumber	34-7E-5C-F8-05-9C:8
vendor	IKEA

The new properties content (after adding the duplicated detected device) is:
hardwareVersion | 1.20.3.3-2.0
identification | Office
ipAddress | 10.55.199.122
macAddress | 34:7E:5C:F8:05:9C
modelId | ZonePlayer
serialNumber | 34-7E-5C-F8-05-9C:8
vendor | SONOS

So the reason for the duplication is, that the modelId has changed and hence, so that the identifier for the speaker has changed from sonos:SYMFONISK:RINCON_347E5CF8059C01400 to sonos:zoneplayer:RINCON_347E5CF8059C01400

That's just a minor matter. It seems, that also the naming of the discovered item has changed.

The original item "Represents IKEA SYMFONISK speaker".

The new item "The Zone Player represents a Sonos Zone Player which is not known to this binding" and comes up in the discovery as: "SYMFONISK Bookshelf (Dining Room)". It's been a long time, since I added these speakers in my OH2.5, so I can't recall, what they were called back then, but I believe it was indeed "IKEA SYMFONISK speaker (Dining Room)" or something the likes.

Now, here's where things go bad: while the bookshelf speakers are discovered, the table lamp speakers are not. They would now probably be discovered as "SYMFONISK Table lamp (Room)".

OH 3.1.0M2 is throwing the following error in openhab.log:
2021-03-12 15:25:51.946 [ERROR] [y.upnp.internal.UpnpDiscoveryService] - Participant 'org.openhab.binding.sonos.internal.discovery.ZonePlayerDiscoveryParticipant' threw an exception
java.lang.IllegalArgumentException: ID segment 'Table lamp' contains invalid characters.

I tried to increasing logging to debug level for the Sonos binding, but it was not more conclusive. Clearly introducing the space in the device type/name has broken the strict Thing naming of OpenHAB. And by the looks both 2.5.12 and 3.1.0M2, as neither of them have rediscovered my table lamps.

/M

**Comment by lolodomo** [comment]
Just to be sure, please tell me what is the value for the tag ModelName you find in the returned XML when you run this HTTP request for your 2 Ikea devices: http://192.168.x.xx:1400/xml/device_description.xml

**Comment by Marlow925** [comment]
<modelName>SYMFONISK Table lamp</modelName> for the Table Lamp.

<modelName>SYMFONISK Bookshelf</modelName> for the Bookshelf speaker.

I'm unsure, what it was before the issue occured.

/M

**Comment by lolodomo** [comment]
I guess it was just "SYMFONISK" before.
I will fix that.

**Comment by lolodomo** [comment]
Did you really check the value in the XML files returned by the HTTP request I provided ?
I am surprised that the model name does not start with "Sonos ".

**Comment by lolodomo** [comment]
As the inbox thing label starts with the model name, I assume that "Sonos " was removed.
That makes a fix more difficult that I expected.

**Comment by Marlow925** [comment]
No, there was no Sonos in the XML. What I posted was exactly what it said.

/M

**Comment by Marlow925** [comment]
`<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
<friendlyName>10.xxx.xxx.xxx - SYMFONISK Table lamp</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S20</modelNumber>
<modelDescription>SYMFONISK Table lamp</modelDescription>
<modelName>SYMFONISK Table lamp</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S20</modelURL>
<softwareVersion>62.1-86220</softwareVersion>
<swGen>2</swGen>
<hardwareVersion>1.20.2.3-2.0</hardwareVersion>
<serialNum>XX-XX-XX-XX-XX-XX:1</serialNum>
<MACAddress>XX:XX:XX:XX:XX:XX</MACAddress>
<UDN>uuid:RINCON_XXXXXXXXXXXXX</UDN>
<iconList>
<icon>
<id>0</id>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/img/icon-S20.png</url>
</icon>
</iconList>
<minCompatibleVersion>61.0-00000</minCompatibleVersion>
<legacyCompatibleVersion>58.0-00000</legacyCompatibleVersion>
<apiVersion>1.23.0-beta.1</apiVersion>
<minApiVersion>1.1.0</minApiVersion>
<displayVersion>13.0</displayVersion>
<extraVersion/>
<nsVersion>25</nsVersion>
<roomName>Guest Room Annex</roomName>
<displayName>Table lamp</displayName>
<zoneType>22</zoneType>
<feature1>0x00000000</feature1>
<feature2>0x00403332</feature2>
<feature3>0x0001510e</feature3>
<seriesid>A100</seriesid>
<variant>0</variant>
<internalSpeakerSize>5</internalSpeakerSize>
<bassExtension>75.000</bassExtension>
<satGainOffset>6.000</satGainOffset>
<memory>512</memory>
<flash>256</flash>
<ampOnTime>10</ampOnTime>
<retailMode>0</retailMode>
<SSLPort>1443</SSLPort>
<securehhSSLPort>1843</securehhSSLPort>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:AlarmClock:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AlarmClock</serviceId>
<controlURL>/AlarmClock/Control</controlURL>
<eventSubURL>/AlarmClock/Event</eventSubURL>
<SCPDURL>/xml/AlarmClock1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:MusicServices:1</serviceType>
<serviceId>urn:upnp-org:serviceId:MusicServices</serviceId>
<controlURL>/MusicServices/Control</controlURL>
<eventSubURL>/MusicServices/Event</eventSubURL>
<SCPDURL>/xml/MusicServices1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:DeviceProperties:1</serviceType>
<serviceId>urn:upnp-org:serviceId:DeviceProperties</serviceId>
<controlURL>/DeviceProperties/Control</controlURL>
<eventSubURL>/DeviceProperties/Event</eventSubURL>
<SCPDURL>/xml/DeviceProperties1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:SystemProperties:1</serviceType>
<serviceId>urn:upnp-org:serviceId:SystemProperties</serviceId>
<controlURL>/SystemProperties/Control</controlURL>
<eventSubURL>/SystemProperties/Event</eventSubURL>
<SCPDURL>/xml/SystemProperties1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ZoneGroupTopology:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ZoneGroupTopology</serviceId>
<controlURL>/ZoneGroupTopology/Control</controlURL>
<eventSubURL>/ZoneGroupTopology/Event</eventSubURL>
<SCPDURL>/xml/ZoneGroupTopology1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:GroupManagement:1</serviceType>
<serviceId>urn:upnp-org:serviceId:GroupManagement</serviceId>
<controlURL>/GroupManagement/Control</controlURL>
<eventSubURL>/GroupManagement/Event</eventSubURL>
<SCPDURL>/xml/GroupManagement1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-tencent-com:service:QPlay:1</serviceType>
<serviceId>urn:tencent-com:serviceId:QPlay</serviceId>
<controlURL>/QPlay/Control</controlURL>
<eventSubURL>/QPlay/Event</eventSubURL>
<SCPDURL>/xml/QPlay1.xml</SCPDURL>
</service>
</serviceList>
<deviceList>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaServer:1</deviceType>
<friendlyName>10.XXX.XXX.XXX - SYMFONISK Table lamp Media Server</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S20</modelNumber>
<modelDescription>SYMFONISK Table lamp Media Server</modelDescription>
<modelName>SYMFONISK Table lamp</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S20</modelURL>
<UDN>uuid:RINCON_7828CAD3E40601400_MS</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:ContentDirectory:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ContentDirectory</serviceId>
<controlURL>/MediaServer/ContentDirectory/Control</controlURL>
<eventSubURL>/MediaServer/ContentDirectory/Event</eventSubURL>
<SCPDURL>/xml/ContentDirectory1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/MediaServer/ConnectionManager/Control</controlURL>
<eventSubURL>/MediaServer/ConnectionManager/Event</eventSubURL>
<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
</service>
</serviceList>
</device>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>Guest Room Annex - SYMFONISK Table lamp Media Renderer</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S20</modelNumber>
<modelDescription>SYMFONISK Table lamp Media Renderer</modelDescription>
<modelName>SYMFONISK Table lamp</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S20</modelURL>
<UDN>uuid:RINCON_XXXXXXXXXXX_MR</UDN>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<controlURL>/MediaRenderer/RenderingControl/Control</controlURL>
<eventSubURL>/MediaRenderer/RenderingControl/Event</eventSubURL>
<SCPDURL>/xml/RenderingControl1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<controlURL>/MediaRenderer/ConnectionManager/Control</controlURL>
<eventSubURL>/MediaRenderer/ConnectionManager/Event</eventSubURL>
<SCPDURL>/xml/ConnectionManager1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<controlURL>/MediaRenderer/AVTransport/Control</controlURL>
<eventSubURL>/MediaRenderer/AVTransport/Event</eventSubURL>
<SCPDURL>/xml/AVTransport1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-sonos-com:service:Queue:1</serviceType>
<serviceId>urn:sonos-com:serviceId:Queue</serviceId>
<controlURL>/MediaRenderer/Queue/Control</controlURL>
<eventSubURL>/MediaRenderer/Queue/Event</eventSubURL>
<SCPDURL>/xml/Queue1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:GroupRenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:GroupRenderingControl</serviceId>
<controlURL>/MediaRenderer/GroupRenderingControl/Control</controlURL>
<eventSubURL>/MediaRenderer/GroupRenderingControl/Event</eventSubURL>
<SCPDURL>/xml/GroupRenderingControl1.xml</SCPDURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:VirtualLineIn:1</serviceType>
<serviceId>urn:upnp-org:serviceId:VirtualLineIn</serviceId>
<controlURL>/MediaRenderer/VirtualLineIn/Control</controlURL>
<eventSubURL>/MediaRenderer/VirtualLineIn/Event</eventSubURL>
<SCPDURL>/xml/VirtualLineIn1.xml</SCPDURL>
</service>
</serviceList>
<X_Rhapsody-Extension xmlns="http://www.real.com/rhapsody/xmlns/upnp-1-0">
<deviceID>urn:rhapsody-real-com:device-id-1-0:sonos_1:RINCON_7828CAD3E40601400</deviceID>
<deviceCapabilities>
<interactionPattern type="real-rhapsody-upnp-1-0"/>
</deviceCapabilities>
</X_Rhapsody-Extension>
<qq:X_QPlay_SoftwareCapability xmlns:qq="http://www.tencent.com">QPlay:2</qq:X_QPlay_SoftwareCapability>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>24</depth>
<url>/img/icon-S20.png</url>
</icon>
</iconList>
</device>
</deviceList>
</device>
</root>`

**Comment by Marlow925** [comment]
I just downloaded OpenHAB 3.1.0M3 and while it doesn't throw an error about invalid errors anymore, the Table Lamps still don't turn up in my Inbox on a scan.

In the log it says:
```
2021-04-05 22:23:26.991 [DEBUG] [overy.ZonePlayerDiscoveryParticipant] - Discovered a Sonos 'sonos:SYMFONISK' thing with UDN 'RINCON_7828CAD3E40801400'
2021-04-05 22:23:27.009 [DEBUG] [overy.ZonePlayerDiscoveryParticipant] - Created a DiscoveryResult for device '10.55.199.133 - SYMFONISK Table lamp' with UDN 'RINCON_7828CAD3E40801400'
```

Yet, no entry in the Inbox.

/M

**Comment by lolodomo** [comment]
Makes no sense, your logs show that it is working well. 
Check you don't have already a thing for this device and/or your inbox entry is not marked as ignored.
