### ISSUE TITLE
[Homematic] Wrong Active Profile

### ISSUE THREAD

**Issue by MisterBJ** [openhab/openhab-addons#10312]
Hi,

I noticed a problem with the wall thermostat today. The active profile is set to 1 by default. But last week I set three thermostats in the CCU3 to 3. In openHab, 1 is always displayed on all thermostats with Channel "Active Profile".
I am using the HmIP-WTH-2 with the current firmware 2.6.0 and openHAB 3.0.0 Release Build.
Am I just making a mistake or is it a bug?

Best regards,
Björn

**Comment by MHerbst** [comment]
It is possible that the device does not send update events for this channel. If you receive other updates like actual temperature correctly, you can try the following: enable the DEBUG log mode for the Homematic binding, change the value on the CCU3 and then look into the openhab.log and or events.log whether there are any messages regarding the "Active Profile". 

According to the documentation the "Active Profile" is contained in channel 1 and sends events for updates, so I would not expect problems with values of this channel.

**Comment by MisterBJ** [comment]
Hello Martin,

It's a little strange but last night I had to restart the Pi with openHAB and then suddenly the display worked again. The only strange thing is that the temperatures were always updated.
I will keep watching.
Thank you for your help.

Best regards,
Bjorn
