### ISSUE TITLE
[lutron] LEAP Caseta thing offline but items are still working

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#10318]
@bobadair - I noticed today that the thing for my Caseta has been showing as offline for a few days.  It went unnoticed because the items are actually still working.  I can send commands and receive updates with no issues.  The same Caseta is connected a different thing as IP and that's working with no issues.  I've restarted the Caseta hub and it had no impact.  My belief is that something failed in marking the thing as online.  I don't have many logs, I didn't have the binding as debug when it happened.  This is the best I got:

```
2021-03-10 21:38:40.876 [INFO ] [openhab.core.model.script.THINGSTATE] - State Change For Lutron_LeapBridge1_ThingState - From: ONLINE To: OFFLINE
2021-03-10 21:38:40.878 [INFO ] [openhab.core.model.script.THINGSTATE] - State Change For Lutron_IPBridge1_ThingState - From: ONLINE To: OFFLINE
2021-03-10 21:38:45.905 [INFO ] [openhab.core.model.script.THINGSTATE] - State Change For Lutron_IPBridge1_ThingState - From: OFFLINE To: ONLINE
2021-03-10 21:38:59.692 [INFO ] [scovery.LutronDeviceDiscoveryService] - Exception getting HTTP response: java.net.SocketTimeoutException: Connect Timeout
2021-03-10 21:38:59.692 [INFO ] [scovery.LutronDeviceDiscoveryService] - No response for HTTP request.
```

I still have this in the broken state for the time being if you need something specific.

**Comment by bobadair** [comment]
Thanks @morph166955. I'll take a look at the code and see if I can find a place where it wouldn't update the bridge state to online properly when a reconnect happens. Do the child devices appear as online? If the bridge is offline, the children should be showing up as offline/bridge offline (or something like that).

**Comment by morph166955** [comment]
Yes, all of the child devices did appear as offline.  My OH went totally sideways today so I had to restart (I may have been messing with a new jupnp build...).  Even though they were marked as offline, they were still receiving updates and sending commands as if they were just fine.  I'm wondering if this was a "cosmetic bug" where the connection was established but for whatever reason the identifying signal was missed and it just wasn't set to ONLINE.  Would it be possible (if you don't already) to periodically check and put the thing ONLINE if it got missed?

**Comment by bobadair** [comment]
What was the extended status of the bridge? If the TLS connection is broken, it should update the status to OFFLINE/COMMUNICATION_ERROR with a description that shows the specific error. Then when it re-connects it should change to OFFLINE/NONE with a description of "Initializing".  When it finishes loading device data and button data it should then change again to ONLINE. I don't see a way in the code for it to successfully re-connect without changing the status to OFFLINE/NONE/"Initializing", but it may have had a problem loading the device or button data after that.

**Comment by morph166955** [comment]
Sorry, it aged out of my logs already.  I'll keep an eye open for this again.
