### ISSUE TITLE
[deconz] light group color and brightness state not updated

### ISSUE THREAD

**Issue by roben** [openhab/openhab-addons#10322]
## Expected Behavior
When I change the color temperature within the phoscon app, the change should be exposed to the corresponding channels within OpenHAB. The same applies to the color channel. The read only `all_on` channel works as expected, though.

## Current Behavior
Changing the color temperature of the group is ignored by the binding.

Test rule:
```
rule "test deconz"
when
	Item Licht_Badezimmer_Decke_Temperatur received update
then
	logInfo("lights.rules", "Licht_Badezimmer_Decke_Temperatur changed to " + newState)
end
```

Changing the color temperature:
![image](https://user-images.githubusercontent.com/812205/111064171-d6ef8a80-84b2-11eb-8346-da8e23164d08.png)

Log file: no update

Changing the color temperature within OpenHAB:

Log file is updated: `2021-03-14 10:49:17.522 [INFO ] [enhab.core.model.script.lights.rules] - Licht_Badezimmer_Decke_Temperatur changed to 3300`

The change is reflected in the phoscon app.

## Steps to Reproduce (for Bugs)
1. Add lightgroup `color_temperature` item
2. Change color temperature or brightness of group within phoscon app.

## Your Environment

OpenHAB 3.0.1-2 on Debian 10.8 amd64

**Comment by TheTrueRandom** [comment]
Issue still exists on openhab 3.1

**Comment by J-N-K** [comment]
Not possible since groups don't report state besides anyOn / allOn
