### ISSUE TITLE
[influxdb] "analyze" and charts not showing any data when using alias

### ISSUE THREAD

**Issue by SNival** [openhab/openhab-addons#10325]
## Expected Behavior
"analyze" item data (and charts) should display values whether or not they are persisted using an alias in influxDB.

## Current Behavior
"Analyze" draws the chart of item data that are persisted without alias, but is empty for aliased ones.

## Steps to Reproduce (for Bugs)
Persistence settings
```
influxdb.persist
...
gpTemperature* : strategy = everyUpdate
gpPower* -> "power" : strategy = everyChange
```

Items settings
```
test.items
Number:Power Pwr_Shly1     "Cons. instant. [%.1f %unit%]" <energy>
  (geLight, gpPower) ["Measurement", "Power"]
  { channel="shelly:shellyplugs:6a5cc9:meter#currentWatts" }

Number:Temperature Tmp_EnOcean1 "Temp. EnOcean [%.1f %unit%]" <temperature>
  (geThermoEO, gpTemperature) ["Measurement", "Temperature"]
  { channel="enocean:temperatureSensor:FTXMIIG5:demoTemp:temperature" }
```

Data stored in the database:
```
> select * from Tmp_EnOcean1 order by time desc limit 5
name: Tmp_EnOcean1
time                     item         value
----                     ----         -----
2021-01-31T08:10:45.946Z Tmp_EnOcean1 20.862745098039216
2021-01-31T07:53:15.855Z Tmp_EnOcean1 20.862745098039216
2021-01-31T07:35:45.441Z Tmp_EnOcean1 21.333333333333332
2021-01-31T05:07:12.139Z Tmp_EnOcean1 20.54901960784314
2021-01-31T04:51:27.372Z Tmp_EnOcean1 20.07843137254902

> select * from power order by time desc limit 5
name: power
time                     item      value
----                     ----      -----
2021-01-31T08:07:32.359Z Pwr_Shly1 0
2021-01-31T08:06:32.191Z Pwr_Shly1 21.5
2021-01-31T08:05:32.01Z  Pwr_Shly1 21.6
2021-01-31T08:04:31.832Z Pwr_Shly1 21.5
2021-01-31T08:02:31.472Z Pwr_Shly1 21.6
```

## Possible Solution
It seems that the data are queried by item name in both cases: here are the queries logged by influxdb:
For the non aliased item:
```
ts=2021-01-31T08:37:18.560153Z lvl=info msg="Executing query" log_id=0S1u9Kn0000 service=query query="SELECT value FROM appart.autogen.Tmp_EnOcean1 WHERE time >= '2021-01-30T08:36:58.447Z' AND time <= '2021-01-31T08:36:58.446Z' ORDER BY time ASC"
```

And for the aliased one:
```
ts=2021-01-31T08:37:41.207569Z lvl=info msg="Executing query" log_id=0S1u9Kn0000 service=query query="SELECT value FROM appart.autogen.Pwr_Shly1 WHERE time >= '2021-01-30T08:37:21.103Z' AND time <= '2021-01-31T08:37:21.102Z' ORDER BY time ASC"
```
The request should take the alias into acount

## Context
Aliasing is useful when downsampling

## Your Environment
I'm testing OH3.0.1 (docker version) with influxdb 1.8.3. on a Raspberry Pi 4 (2Gb ram)

**Comment by Rossko57** [comment]
> gpPower* -> "power" : strategy = everyChange

I don't think that's a very useful configuration?
`gpPower*` means to persist the state of all members of the group.
`-> "power"` means to put the states of all those different Items in one table 'power'

When requesting chart data for individual Item `Pwr_Shly1`, there is no alias for that Item.
No data can be found for Item name `Pwr_Shly1`

If you need to use aliases, then you need to use on them on individual Items.
https://community.openhab.org/t/persist-data-for-every-item-in-a-group/62066

**Comment by SNival** [comment]
Thank you for the answer.

It is a useful configuration: I have multiple power and temperature items. I don't make the same operations on both, so grouping them in 2 different tables makes things easyier. The gpPower* (and other same groups) are defined to easily configure single items persistence by just changing their definition.

I see that the alias is missing in the query, the issue is that it's a query produced by openhab when requesting data for the chart, so I have no control on that.

I also tried not using a group and defining `Pwr_Shly1 -> "power" : strategy = everyChange` in the persistence settings, with the same result (data stored but chart empty).

**Comment by Rossko57** [comment]
> It is a useful configuration
If you say so.  Reminder that using alias with group* means that all member data gets put into one table, and when data is read later there is no means to tell which Item it came from.

I suspect there may also be side effects of discarding near-simultaneous updates, depending on time granularity of database.

> I see that the alias is missing in the query,

Yes.  You assigned the alias to the group name,   
When you query for "some other Item", there **is no alias** for "some other Item", so it queries for "some other Item".
In this case, there are no records for "some other Item".
This is working as documented.

> I also tried not using a group and defining `Pwr_Shly1 -> "power" : strategy = everyChange` in the persistence settings, with the same result (data stored but chart empty).

Let's look into that, then.   You may need to drop previous table "power" having repurposed it.

**Comment by SNival** [comment]
> Reminder that using alias with group* means that all member data gets put into one table, and when data is read later there is no means to tell which Item it came from.

No : the item name is added as a tag to each "record". It is visible in the data from the DB in my sample. This is working as documented.
The default resolution for timestamps is nanosecond, so no problem with that.

I dropped the "power" table/measurement and used `Pwr_Shly1 -> "testpower" `, so a new measurement is created, named testpower, with points having the values and a column "item" containing "Pwr_Shly1" as expected.
But, when using the OpenHab UI, if I click on "analyze" on the Pwr_Shly1 item the chart is empty.

The **storage** works perfectly well. I can query everything as expected with external tools.
The **reading** by OpenHAB does not work if an alias is specified.

The persistence should take the alias into account when generating the query for the DB, and maybe use the "item" tag with the actual item name as a filter so grouping won't be a problem.

Here is a summary of what I found: 
```
OpenHAB |  Persistence cfg  |       InfluxDB         |
 item   |  item     alias   | Measurement "item"-tag | Read query : select ...
--------+-------------------+------------------------+--------------------------
MyItem  |  MyItem   <none>  | MyItem      MyItem     | from db.autogen.MyItem
MyItemB |  MyItemB  <none>  | MyItemB     MyItemB    | from db.autogen.MyItemB
        |                   |                        |
MyItem  |  ItemGrp* <none>  | MyItem      MyItem     | from db.autogen.MyItem
MyItemB |  ItemGrp* <none>  | MyItemB     MyItemB    | from db.autogen.MyItemB
        |                   |                        |
MyItem  |  MyItem   AnAlias | AnAlias     MyItem     | from db.autogen.MyItem
MyItemB |  MyItemB  AnAlias | AnAlias     MyItemB    | from db.autogen.MyItemB
        |                   |                        |
MyItem  |  ItemGrp* AnAlias | AnAlias     MyItem     | from db.autogen.MyItem  , should be from db.autogen.AnAlias where ... and item = "MyItem"
MyItemB |  ItemGrp* AnAlias | AnAlias     MyItemB    | from db.autogen.MyItemB , should be from db.autogen.AnAlias where ... and item = "MyItemB"
```
assuming MyItem and MyItemB are in the group ItemGrp.
Hope it helps...

**Comment by Rossko57** [comment]
> No : the item name is added as a tag to each "record". It is visible in the data from the DB in my sample. This is working as documented.

Okay.

> The persistence should take the alias into account when generating the query for the DB

Is this only an 'analyze' charting issue, or also do rule based persistence methods like historicState() work or not?

**Comment by SNival** [comment]
I tried rule persistence method (lastUpdate, averageSince), same behavior: measurements are queried by item name regardless of the alias presence, so no data if items were saved using an alias.

**Comment by martin67** [comment]
I found the same type of problem when using Influx ver 2. When using an alias in the influxdb.persist file, it is not possible to access the persisted data from openHAB. It is stored ok in influxdb, but it's the retrieval that does not work.

In the example above:
```
influxdb.persist
...
gpTemperature* : strategy = everyUpdate
gpPower* -> "power" : strategy = everyChange
```
Let's also say that gpTemperature contains an item MyTemperature1 and gpPower the item MyPower1.

For the first line, the value would be stored as a `_measurement = MyTemperature1` and an `item = MyTemperature1`. The second one would be `_measurement = power` and `item = MyPower1`.

When doing retrieval, the measurement name is calculated through this code (in Influx2FilterCriteriaQueryCreatorImpl.java):

```
...
        if (itemName != null) {
            String measurementName = calculateMeasurementName(itemName);
            boolean needsToUseItemTagName = !measurementName.equals(itemName);
...
```
but the calculateMeasurementName only checks if there is another name in the metadata - which it has not in this case. So the retrieval fails - for the second example, it tries to get `_measurement = MyPower1` which doesn't exist.

The solution would be to have calculateMeasurementName check the given measurement name after it checks for a name in the metadata. In this way it would be possible to override an alias name with a name given from the metadata.

**Comment by lujop** [comment]
I was not aware of the alias feature of Openhab, the problem I see is that alias is passed to `store` method, but I don't see it in the `FilterCriteria`. 
How it's supposed to work, should the alias be provided also in the `FilterCriteria`? 
Or the persistence addon is supposed to store some metadata to be able to retrieve later @openhab/add-ons-maintainers?

The problem is that I don't see a way to be compatible with older data without an item tag and support the alias if it's not provided in FilterCriteria.

But in any case @SNival and @martin67,  you can use the advanced mapping options using metadata that are explained in the documentation. See `#Measurement name by Item Metadata` in https://www.openhab.org/addons/persistence/influxdb/

**Comment by martin67** [comment]
I tried using the the advanced mapping option and it works. But I have a lot of sensors and I need to configure each one of them in that case (which would take a long time). I also have an existing group, "All temperatures" that already contains all my temperature sensor items that is now used as an alias in influxdb.

The background is that I only want to save some item values to influx, not all of them (I have 1000+ items...). By using the already existing groups (temperature, humidiy etc.) this would make it easier.

But then I think I'll just remove the alias part and having all measurements be named with the item name instead. It will be possible to sort them using the category and type fields instead of using the measurement as a filter.

The drawback with using metadata is that defining it through the GUI is very time consuming. Maybe I'll try to write some external script that can do it using the rest api.

**Comment by lujop** [comment]
If I'm not wrong you can define metadata also with the text definition files and can be quite fast to do in batch.
About the alias part, I think that if it's not provided in the Criteria it's not possible to make it work as expected maintaining compatibility with old data without item tag names.

**Comment by florian-h05** [comment]
How to proceed here? This issue is stale for a while now …
