### ISSUE TITLE
[openweathermap] API request - Current wind speed and hourly wind speed forecast

### ISSUE THREAD

**Issue by seemann77** [openhab/openhab-addons#10357]
## Current Behavior
API request via Openweathermap's "One Call API" delivers wrong current wind speed and wind speed hourly forecast values. The received values are ~4 times the actual wind speed or wind speed forecast -- compared to the posted values on th OWM webpage (and other weather services).

## Possible Solution
- Value conversion issue (e.g. metric, imperial)
- Issue of Openweathermap delivering the wrong values.
- ...

## Steps to Reproduce
- Compare values received by owm binding with same location (geo coordinates) from the owm webpage (and/or other webservices)
- I tested with view 3 locations (geo coodinates in Germany). Always with the same result.

## Your Environment
OH3, Wpenweathermap, OWM One Call API

**Comment by Rossko57** [comment]
Could you describe which channels you are looking at.  As you feel it may be a conversion issue, could you describe what type of Item these are linked to. What values does the binding update these with, as shown in your events.log.   Could you provide example numbers.

**Comment by seemann77** [comment]
I checked the conversion again and realized that the unit in OH3 is not m/s but km/h. I thought its a metric vs. imperical issue. So it seems to work fine.

**Comment by Rossko57** [comment]
Can this issue be closed then?

**Comment by seemann77** [comment]
Yes. And many thanks again.

**Comment by Rossko57** [comment]
Okeydoke.  It's your issue ... you can close it.
