### ISSUE TITLE
[linky] Authentication failing (step 3)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10360]
We have again a problem to connect to the service.
It is failign at step 3 and the thing is OFFLINE (COMMUNICATION_ERROR ) with this detail: 
```
Connection failed step 3 - auth1 : <html><head><title>Votre requete n'a pas pu aboutir.</title></head><body>Votre requete n'a pas pu aboutir.</body></html>
```
I checked my "internalAuthId" is correct.

@clinique: Gaël: do you have the same problem ?

I suspect that the URL built by the binding has to be updated.

**Comment by clinique** [comment]
Hello @lolodomo , yes there may be another change on Enedis website :-( Sorry but I'm currently moving and will not have time to investigate this in the coming weeks.

**Comment by lolodomo** [comment]
The URL used at step 3 (auth1) to get the auth data now returns a 500 status code.

**Comment by lolodomo** [comment]
@clinique : do you remember where you find your inspiration when you did the last refactoring ? I am curious if the authentification process was fixed in that place.

If no solution is found, I think we should suppress this binding from next 3.2 distributions. WDYT ?

**Comment by clinique** [comment]
@lolodomo : IIRW I think I did observe behaviour of the browser using debug console. Sure we can not rely on such a fragile approach and unless a more robust is provided, it could be removed as still it does not work at all.

**Comment by lolodomo** [comment]
What's a pitty, we spend time on this binding.

**Comment by clinique** [comment]
You're right, but it may help sometimes in the future.

**Comment by lolodomo** [comment]
> I did observe behaviour of the browser using debug console

Maybe we can try that again.

**Comment by lolodomo** [comment]
After a deeper analysis, I have the feeling the problem is the cookie we are building.
