### ISSUE TITLE
[androiddebugbridge] current package on Android >= 10

### ISSUE THREAD

**Issue by maschenborn** [openhab/openhab-addons#10366]
channel / Item "current package" doesn't get a value on Mi TV with android TV.

## Expected Behavior
should be name of current package

## Current Behavior
2021-03-21 13:01:17.140 [WARN ] [e.internal.AndroidDebugBridgeHandler] - Unable to refresh play status: Unable to read package name
2021-03-21 13:01:17.227 [WARN ] [e.internal.AndroidDebugBridgeHandler] - Unable to refresh current package: Unable to read package name

## Possible Solution
https://stackoverflow.com/questions/28543776/android-shell-get-foreground-app-package-name
Maybe the current package is searched with the old way - not the now working
adb shell dumpsys activity recents | grep 'Recent #0' | cut -d= -f2 | sed 's| .*||' | cut -d '/' -f1

## Your Environment
openHAB 3.1 Snapshot on Qnap as Docker-Image
androiddebugbridge-Binding
Xiaomi Mi TV Q1

**Comment by lsiepel** [comment]
@GiviMAD maybe something you can comment on?

**Comment by GiviMAD** [comment]
I think the issue is already fixed, in the current implementation we use a different command for devices running android >= 10

```java
        ...
        String out;
        if (isAtLeastVersion(10)) {
            out = runAdbShell("dumpsys", "window", "displays", "|", "grep", "mFocusedApp");
        } else {
            out = runAdbShell("dumpsys", "window", "windows", "|", "grep", "mFocusedApp");
        }
        ...
```

**Comment by lsiepel** [comment]
@maschenborn please upgrade to latest stable version of openHAB, if the issue remains, please feel free to re-open this issue.
