### ISSUE TITLE
[irobot] Request for more detailed authentication steps when using config files

### ISSUE THREAD

**Issue by vidia** [openhab/openhab-addons#10388]
When I was configuring my Roomba I ran in to two issues that were not covered in the documentation. 

First (a small nit) the "Home" button is not present on all Roomba devices. On my Roomba 675 I needed to press "Dock" which was not immediately clear. 

Second (the main issue I have), when using config files alongside MainUI in Openhab3, it is not immediately clear where to find the Roomba password after pressing the button. I'd like to suggest one of two solutions: 

1. Add a mention to the docs that the password will be populated in the Thing and that you must copy that into the config files in order for it to persist. Without this detail it causes confusion because the Roomba will appear to work temporarily, but as soon as the Things file is edited, the password is lost and the button needs to be pushed again. I believe this issue is specific to working with config files.
2. Make a code change to log out the password to the log file so config file users can see and copy the password easily.

**Comment by lsiepel** [comment]
1. Should be fixed by the related PR.
2. It is a bad practice to log passwords to log files (as they tend to end up everywhere). I would call that a won't fix.
