### ISSUE TITLE
[Keba] Binding doesn't recover from a single communication error

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#10385]
Keba binding goes offline and doesn't recover from a single communication error.

## Current and Expected Behavior
- On temporary communication errors between the OH server / Binding and the Keba station, the binding should not go into offline state but retry the communication.

## Possible Solution
- Do not send binding towards offline state but keep retrying.

## Steps to Reproduce (for Bugs)
1. Disconnect the network connection towards the Keba station
2. Keba binding will go offline
3. Re-connect Keba network connection
4. Binding will not change back to online / operational mode

## Relevant code part
```
    private void pollingRunnable() {
        try {
            logger.debug("Running pollingRunnable to connect Keba wallbox");
            long stamp = System.currentTimeMillis();
            if (!isKebaReachable()) {
                logger.debug("isKebaReachable() timed out after '{}' milliseconds", System.currentTimeMillis() - stamp);
                transceiver.unRegisterHandler(getHandler());
            } else {
               [...]
            }
        } catch (NumberFormatException | IOException e) {
            logger.debug("An exception occurred while polling the KEBA KeContact '{}': {}", getThing().getUID(),
                    e.getMessage(), e);
            Thread.currentThread().interrupt();
            updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
                    "An exception occurred while while polling the charging station");
        } catch (InterruptedException e) {
            logger.debug("Polling job has been interrupted for handler of thing '{}'.", getThing().getUID());
        }
    }
```
It also contains the typo `while while` that can be corrected at the same time.

## Your Environment
* Version used: OH3.1.0 snapshot
* Operating System and version: OH3 via docker container on Synergy NAS but issue is OS independent

**Comment by kaikreuzer** [comment]
You can never know whether it is a temporary error, so I do not agree that the Thing should not go OFFLINE.
But clearly, it needs to keep trying and go ONLINE again as soon as the connection is reestablished.

**Comment by MikeTheTux** [comment]
issue resolved for OH3.1.0 via #10399
