### ISSUE TITLE
Allow a custom logback(_debug).xml file in the conf folder

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-addons#104]
In the runtime folder the etc folder contains configuration of the logfiles and services.cfg.
As runtime folder should be easily overwritten with each update I would suggest to move the runtime/etc folder to the conf or userdata folder instead to loss of relevant configuration details

**Comment by marcelrv** [comment]
okay, indeed would be good to put it in the start script. Let's label it an enhancement then,
Dunno if in .bat file this is easy to do, but in the linux .sh script that should be not too difficult.

**Comment by xsnrg** [comment]
For anyone that wants, this works for the shell script start.sh. Similar would work for the _debug of course.  It checks to make sure the file has read permission and is size > 0. 


    if  [ -r ./conf/logback/logback.xml ] && [ -s ./conf/logback/logback.xml ]
     then
        LOGBACKCONF=./conf/logback/logback.xml
        echo "using custom logback.xml found in $LOGBACKCONF"
     else
        LOGBACKCONF=./runtime/etc/logback.xml
        echo "using default logback.xml found in $LOGBACKCONF"
     fi

    # program args
    prog_args="-Dlogback.configurationFile=$LOGBACKCONF  <... rest of args here>

**Comment by kaikreuzer** [comment]
Thanks @xsnrg.
Actually I am closing this issue now, since the new Karaf container does not use logback at all, so we won't have a logback.xml anymore.
But we will require some good solution for splitting default and custom config files, so your script might be a good starting point for that.

**Comment by xsnrg** [comment]
No worries.  I figured that would be the case, so I didn't spend a lot of time on it or do a PR, but it is here for posterity.

Cheers
