### ISSUE TITLE
[miio] Yeelight devices suddenly reported as unsupported

### ISSUE THREAD

**Issue by mrumpf** [openhab/openhab-addons#10405]
In my Openhab setup the Yeelight devices were not working anymore. I cannot say since when and I checked whether there was some update to the Openhab server done by automated updates, but I could not find anything.
The log was showing the following error [MiIoAbstractHandler.java#L469](https://github.com/openhab/openhab-addons/blob/b1e48e0db9c8710f94da44dbab35e41cff18b1e0/bundles/org.openhab.binding.miio/src/main/java/org/openhab/binding/miio/internal/handler/MiIoAbstractHandler.java#L469):
````
/var/log/openhab/openhab.log.7:2021-03-28 09:20:37.831 [INFO ] [internal.handler.MiIoAbstractHandler] - Mi Device model Unknown Mi IO Device (unknown) identified as: miio:unsupported, thingtype miio:basic. Does not matches thingtype miio:unsupported. Unexpected, unless manual override.
````

For debugging I turned on logging at the DEBUG level and used the log:tail command to look at the log of the binding. 
I switched on some lamps and then all was working again :(

I know that issues like that are almost impossible to reproduce and I cannot tell whether turning on the log was really the reason for the devices to respond again, but maybe someone from the contributors might have an idea why that happened.

**Comment by marcelrv** [comment]
This is indeed very odd. The value between the brackets `unknown Mi IO Device (unknown)` is normally giving the device model, it would apprear that it had `unknown` in there which is highly unusable.

Do I read your issue right that you had this with multiple devices at the same time?
The only thing I can think of that there was some sort of very strange response parsed from the cloud communication that could have caused this (as it also fixed itself later) but indeed very odd.

**Comment by marcelrv** [comment]
Is this issue recurring / still present?
Is there any trouble shooting that can be done to close it?

**Comment by marcelrv** [comment]
as no response for over a year, closing the issue
