### ISSUE TITLE
[amazonechocontrol] Switchable devices and groups not loading any Channels

### ISSUE THREAD

**Issue by kendonB** [openhab/openhab-addons#10402]
## Expected Behavior
If my understanding of the [documentation](https://www.openhab.org/addons/bindings/amazonechocontrol/) is correct, after discovery (which worked) and creating a Thing such as a smart light switch (which also worked), I should see some available channels appear in the Channels tab of the Thing.

## Current Behavior
No Channels appear, even after several hours. The Thing does show as "Online" in the green box.

## Possible Solution
Perhaps it's related to a change in the alexa.amazon.com interface? I can't find any way to interact with the devices on that website but I can interact with them on the mobile app.

## Steps to Reproduce (for Bugs)
1. Have an Amazon Echo with a smart device set up
2. Follow the instructions in https://www.openhab.org/addons/bindings/amazonechocontrol/ up to discovery
3. Wait for Things to get discovered
4. Things -> "+" -> Amazon Echo Control Binding -> Click on the device you want
5. Click Channels Tab
6. Nothing is there

## Context
I am trying to control smart light switches that don't have an openhab binding. They are Connect Smarthome light switches.

## Your Environment
openhabian raspberry pi, version from 2020-27-03

**Comment by kendonB** [comment]
I should also add that the TextCommand channel, that allows users to send an arbitrary command as if they were speaking it, is also not working. If that worked, then it could be used as a workaround for this command.

**Comment by kendonB** [comment]
OK I now have switches loading as channels for the discovered Alexa devices.

However, the switches only turn items on but not off! TextCommand is also still not working for me. I can verify that the text correctly gets set in the textcommand item but it doesn't get through to Alexa.

**Comment by lsiepel** [comment]
Chasing some older issues and checking this one needs some a follow up.
Did you manage to sort all problems? If not could you check if it is still an issue with oopenHAB 3.4.1 and clearly state the steps to reproduce and if possible with a debug log?

**Comment by kendonB** [comment]
This is from a while ago. Amazon switches do now work both ways and I haven't tried to get TextCommand to work again. Best to close for now and when someone else tries they can open another issue if needed.
