### ISSUE TITLE
[samsungtv] only Power functionality works with 2020 QLED TV

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab-addons#10400]
I can't get the Samsung TV Binding to work properly with my new 2020 Q95T Smart TV. The Power channel seems to toggle most of the time but nothing else changes. Putting the binding into debug mode gives

`[DEBUG]` [rnal.service.RemoteControllerService] - getSupportedChannelNames: [keyCode, volume, mute, power, channel, url, sourceApp, artMode]

but when I link an Item to any of the channels none of the items change apart from power, and sending commands to the keyCode doesn't do anything. I asked on the community but had no replies.

([https://community.openhab.org/t/oh3-samsung-tv-binding-most-thing-channels-dont-work-on-2020-qled-tv/119629])

I'm running OpenHAB 3.1.0 Build #2288 on Debian

**Comment by sheppy99** [comment]
Also doesn't work on Build #2326

**Comment by lsiepel** [comment]
@NickWaterton Is preparing a fancy (and large) PR improving a lot to this binding. I'm not sure if it fixes this case, but it does mention some changes to more recent models liek the 2020 Q95T

**Comment by lsiepel** [comment]
@sheppy99 can you try openHAB 4.2 m4 (out later today?) as that will have many changes regarding the smasungtv binding.

**Comment by sheppy99** [comment]
Hi there
Unfortunately Kevin, my lovely husband, passed away last year otherwise I know he’d love to try your new Samsung tv binding.
I wish I was half as clever as he is with open hab but I do love all the things he’s already programmed for us.
Cheers
Fran (Kevin’s wife)
Sent from my iPhone

On 30 Jun 2024, at 1:51 AM, lsiepel ***@***.***> wrote:

﻿

@sheppy99<https://github.com/sheppy99> can you try openHAB 4.2 m4 (out later today?) as that will have many changes regarding the smasungtv binding.

**Comment by lsiepel** [comment]
I’m very sorry to hear. 
Thanks for your reply. I will close this comment for now.  Wish you all the best.
