### ISSUE TITLE
[tacmi]receiving negative values and sending analog temperature values

### ISSUE THREAD

**Issue by Koala887** [openhab/openhab-addons#10429]
When I receive negative temperature values from the cmi, instead of -0.1 I get -3276.8 and when I send a temperature value to the cmi, ten times the value is displayed there.

**Comment by woklei** [comment]
Hi,

if you still have this problem, some additional details may increase the probability that someone can help:

- What hardware and operating system are you running the openhab server on?
- which version of openhab are you working with?
- do you use any kind of custom formatting on the values?
- what client are you using? Android app? Iphone app? Browser (which on what kind of device?)?
- is this with both sitemap and the new OH3UI?
- can you give some more examples (positive and negative, both for sending and receiving)? For examples of sending, please include the value defined in OH, the one displayed in the CMI after sending and the one displayed in OH after the next refresh.

Interestingly, 3276.8 is 0.1*32768 with 32768 = 2^15 being the maximum (or minimum, when negative) value of a signed 4 byte datatype, so it looks like some kind of data type conversion / overflow issue.
