### ISSUE TITLE
[androiddebugbridge] poweroff android device

### ISSUE THREAD

**Issue by lapicidae** [openhab/openhab-addons#10425]
## Discription
I would like to shutdown my chromecast via a wall switch.
"adb shell reboot -p" should do the trick.

## Your Environment
* openHAB docker -> 3.0.1-debian
* Chromecast with Google TV

**Comment by cweitkamp** [comment]
@GiviMAD Is this possible?

**Comment by GiviMAD** [comment]
Yes, I'll add a reboot channel.

**Comment by GiviMAD** [comment]
In case you want to test it. The channel is included on this pr https://github.com/openhab/openhab-addons/pull/10497

**Comment by lapicidae** [comment]
Works great!
But i think the channel should be renamed to "Shutdown" or "Power off"

power off => _"adb shell reboot -p"_
reboot => _"adb shell reboot"_
[Powering off Android Things](https://stackoverflow.com/questions/41503899/powering-off-android-things/44209713#44209713)

**Comment by GiviMAD** [comment]
I've changed the reboot channel to shutdown channel with options for power off and reboot.

**Comment by lapicidae** [comment]
After the following change, the shutdown-channel works great!

```
 thing-types.xml:
-  <channel id="reboot" typeId="reboot-channel"/>
+  <channel id="shutdown" typeId="shutdown-channel"/>
```
