### ISSUE TITLE
[homematic] Re-connect handling is not sufficient for HmIP devices

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-addons#10439]
If a CCU is restarted the binding sometimes shows one or more connected HmIP things as offline even if the connection to the CCU has been restored. The state won't change until the Homematic binding is restarted.

This problem does not occur with the "classic" Homematic devices and it depends on the type and number of connected HmIP devices.

There are two problems that have to be solved for this issue:

1. If a CCU is restarted it will answer to request before it completely ready again. In this case, the response message is an HTML document containing the message that the CCU is not ready yet. This needs to be checked and the binding has to wait until the CCU responds with a correct document. 
2. After the CCU is completely back all HM devices are also online. But for the HmIP devices, it can take several seconds (or minutes) until they are available in the CCU. With my HmIP-eTRV even the CCU did not show updates for some minutes after a restart. As a solution, the binding must retry the checks for each individual device whether it is online again.

This is a follow-up to issue #10075

**Comment by eikowagenknecht** [comment]
Thanks for analyzing this. If you need more help / testing I'm happy to assist again :-)
