### ISSUE TITLE
[openwebnet] allow sending generic OWN messages from rules

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#10431]
Allow sending generic OWN frames from OH rules. This should be useful to activate several actions from rules even if a specific WHO is not supported in the binding.

**Comment by mvalla** [comment]
What would you bypass the binding? 
The solution here is to define an action in the binding to send generic frames, plus some changes to the own4j lib to allow sending frames for every who

**Comment by fabgio** [comment]
Ok I’ll start trying changing openwebnet4j lib to allow sending every who, I’ll do some tests also. Please be patient with me as am not a professional developer despite I’ve got 10 years of java experience. as an hobby.
May I have the issue assigned?

**Comment by mvalla** [comment]
I cannot assign the issue.
Feel free to create a new issue on own4j related to this and work on a PR on that repo. Afterwards the change can be done on the binding to add the action
