### ISSUE TITLE
[tapocontrol] L510_Series Thing status goes offline, then online again

### ISSUE THREAD

**Issue by Binzinz** [openhab/openhab-addons#10465]
Hello, I'm on Openhab 3.1.0 M3 with  org.openhab.binding.tapocontrol-3.1.0-SNAPSHOT.jar installed in add-ons folder.

My L510_Series Thing won't start automatically, then goes offline, and online every minute.

When OpenHab start:
`2021-04-05 11:13:15.934 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from OFFLINE (COMMUNICATION_ERROR): Device Offline to OFFLINE (CONFIGURATION_ERROR): wrong device found:`

Then I Save the config in Parameter->Things without changing anything and:
`2021-04-05 11:17:16.480 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from OFFLINE (CONFIGURATION_ERROR): wrong device found:  to UNKNOWN`
`2021-04-05 11:17:17.585 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from UNKNOWN to ONLINE`

Then:

`2021-04-05 11:17:48.731 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from ONLINE to UNKNOWN (COMMUNICATION_ERROR): Device Offline`
`2021-04-05 11:18:19.730 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from UNKNOWN (COMMUNICATION_ERROR): Device Offline to OFFLINE (COMMUNICATION_ERROR): Device Offline`
`2021-04-05 11:18:55.434 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from OFFLINE (COMMUNICATION_ERROR): Device Offline to ONLINE`
`2021-04-05 11:19:26.439 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Device Offline`
`2021-04-05 11:21:00.576 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tapocontrol:L510_Series:6315dce619' changed from OFFLINE (COMMUNICATION_ERROR): Device Offline to ONLINE`

**Comment by lolodomo** [comment]
@wildcs: did you see that issue?

**Comment by wildcs** [comment]
@lolodomo 
Thank you. Didn't see it until now. The `wrong device found` issue should be outdated since 3.3.0 snapshot:

`[3.3.0]
ALERT;TapoControl: L510_Series and L530_Series Things were renamed to L510 and L530 because of manufacturer changed naming with new HW-rev. You may need to remove and create again this things.`

**Comment by lolodomo** [comment]
@Binzinz : please confirm your problem is solved using OH3.3 and then close the issue.

**Comment by Binzinz** [comment]
The problem is solved since I have the org.openhab.binding.tapocontrol-3.4.0-SNAPSHOT.jar in my add-ins. Thanks for your effort.
