### ISSUE TITLE
[telegram] Script execution failed: Conversion = '%' in rules

### ISSUE THREAD

**Issue by jwsp1** [openhab/openhab-addons#10468]
Since OH3, I cannot send a telegram message which contains % as a text.

rule (part of it):
`val telegramAction = getActions("telegram","telegram:telegramBot:asdfghjkl")`
`val receiver= 123456789L`
--> relevant part:
`telegramAction.sendTelegram(receiver,"Battery level: " + battery_state.state + "%")`

Error message:
`[ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'rules-1' failed: Conversion = '%' in rules`

The rule worked with OH2. It works fine when I remove the last part with %. The error also occurs when I put % into Battery, like Ba%ttery.

**Comment by kl8ter** [comment]
Hello,
try:  %%

**Comment by jwsp1** [comment]
Awesome, this worked! Thank you.
