### ISSUE TITLE
[openhab-cloud] Corrupted REST response after update to nightly

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#10470]
After updating to the nightlies build,  integrations using the openhab-cloud  have became unstable, this includes our mobile app, OH3 UI and our Alexa integrations.  Its seems like the response to at least GET requests is returning either a duplicate response, or mid way through the response get repeated causing invalid JSON.  its feels almost like there is some type of struct or buffer that is not being flushed/cleared, or the index of where we are in that buffer is off or gets reset.    I am still looking at this, but the only significant  change to that i can see is https://github.com/openhab/openhab-core/pull/2264  , @wborn could there be anything with that upgrade you could see might cause this?  Of course this could be my system, so i would appreciate  if someone else could load `/rest/items` or the  load OH3 app using  our cloud service and confirm.  I'll continue to look at it as well.

**Comment by digitaldan** [comment]
Well, found where the corruption is occurring, for some reason the Jetty `onContent` listener is getting called twice for every chunk is receives back  from making a rest request to OH. 

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.openhabcloud/src/main/java/org/openhab/io/openhabcloud/internal/CloudClient.java#L588

 For reference, the cloud binding takes a http request made through the cloud service and executes it against localhost, then returns the results.  So myopenHAB - > OH -> localhost:8080 -> OH  and then back again.   

Still looking why this is....

**Comment by wborn** [comment]
> could there be anything with that upgrade you could see might cause this

Most likely it is because Karaf 4.3.1 now uses Jetty 9.4.38 whereas is would previously use Jetty 9.4.20. I also had to update a unit test because of some Jetty implementation changes. Haven't tested openhabcloud yet.

**Comment by digitaldan** [comment]
Thank @wborn , I just tried a clean nightly with a new configuration and am seeing the same behavior, so I'm ruling out it being my instance or some type of migration/upgrade issue.  I'm completely stumped on why that listener in the code i referenced above is having duplicate data delivered on its onContent handler.  I can confirm that internally jetty is only making a single request to localhost, and getting a single response back, but that onContent method gets duplicated for each chunk it processes.  

This is probably a show stopper until we get it resolved, wdyt?

**Comment by cweitkamp** [comment]
Some time ago I tried to migrate Socket.IO to Jetty WebSocketClient: https://github.com/cweitkamp/openhab-addons/commit/9d958ef171096dd55018dde4171b50766f4fec13

Unfortunately Jetty does not allow to use different URL schemes than `ws` or `wss`. I just thought if this is the right time to ask if one of you has an idea.

```
[ERROR] [io.openhabcloud.internal.CloudClient] - Error while connecting socket: WebSocket URI scheme only supports [ws] and [wss], not [https]
```

**Comment by digitaldan** [comment]
does it work if you connect to wss://myopenhab.org/ ?

**Comment by cweitkamp** [comment]
Yes, I should have told you that I tried to connect to `https://myopenhab.org/`.

When using `ws` or `wss` I get the following failure:
```
[WARN ] [io.openhabcloud.internal.CloudClient] - Connection to the openHAB Cloud service errored (UUID = XXX, base URL = ws://myopenhab.org/): Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 200 OK
```

This warning got logged in the `onError()` method (`CloudClient` line 221) in my changes.

**Comment by digitaldan** [comment]
I think this might be due to how a Socket.io client does its its initial handshake, it makes 2 requests if i remember correctly, the first gets a session id, the second makes the websocket connection.   I also thought Socket.io has its own protocol on top of the basic websocket API , so you would need to implement the whole client spec as described in https://github.com/socketio/socket.io-protocol  to talk with our socket.io based cloud service.

**Comment by digitaldan** [comment]
So i have a fix, although it does not explain why it broke in the first place other than a hunch i had that our listener class was being loaded twice somewhere (pure speculation, no evidence).  I replaced our inner class that implements a bunch of the jetty listeners with lambdas.  This solves the problem, and is probably a cleaner, more modern approach then what we had, but again it does not explain why it happened.  See #10487

**Comment by cweitkamp** [comment]
@digitaldan Thanks for clarification. It looks a little bit more challenging than I expected.

**Comment by digitaldan** [comment]
Yeah, i would like to remove socket.io from the whole thing, its an old and outdated technology that prevents us from using a larger ecosystem of websocket tooling, but its a big project i have not had time to work on.
