### ISSUE TITLE
[http] spaces in stateTransformation parameter

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#10475]
This is a fairly trivial enhancement suggestion.

Supplying HTTP binding channel configuration like
`stateTransformation: JSONPATH:$.currentSetpoint ∩ JS:div100.js`
results in an error
`Transformation service JS for pattern div100.js not found!`
presumably because it is looking for a service " JS" with space?

Removal of spaces fixes problem (at cost of reduced legibility)
`stateTransformation: JSONPATH:$.currentSetpoint∩JS:div100.js`

Example
https://community.openhab.org/t/solved-js-after-json-transformation-in-statetransformation-and-commandtransformation/120215

I do not know if this best improved by behaviour at validation or runtime.

**Comment by Rossko57** [comment]
Also applies to MQTT binding

**Comment by J-N-K** [comment]
Fixed by #16282
