### ISSUE TITLE
.gitattributes contains errors causing it to not do what it is supposed to do

### ISSUE THREAD

**Issue by Daniel-42** [openhab/openhab-addons#10472]
## Expected Behavior

On windows:

- all .java and .xml files should have their lines endings converted to CRLF when cloning to the local system.
- all .java and .xml files should have their lines endings converted to LF when committing/pushing to git.

## Current Behavior

- .java and .xml files will be pushed with the lines endings as they are, resulting in CRLF line endings winding up in the remote.

## Possible Solution

Change:

.java
.xml

into

*.java
*.xml

in the .gitattribute files

## Steps to Reproduce (for Bugs)

- clone on windows
- modify a file
- just for fun run a spotless:apply on the whole repo
- commit (you'll have thousands of modified files that git won't commit) the one file you actually modified
- the actually modified file will have CRLF in the repo and spotless:check will fail there

## Context

- this happened in the context of a pull request 

## Your Environment

- windows
- OH3
- New addon

**Comment by fwolter** [comment]
Can you file a PR?

**Comment by fwolter** [comment]
For the posterity, you need to run `mvn spotless:apply` once, after the fix in the PR is applied.
