### ISSUE TITLE
[hue] Add brightness channel to color lights

### ISSUE THREAD

**Issue by mechalas** [openhab/openhab-addons#10478]
In the Hue binding, color lights use the color channel to handle brightness. This is generally fine for controls such as sliders and other UI elements, but it does not work with dynamic icons (e.g., the `light` icon, along with the state versions `light-10`, `light-20`, etc.) In the Main UI, if you set up (for example) a floor plan page, add a marker, and give it the following config:

```
component: oh-plan-marker
config:
  name: Downlight
  coords: 1330.1926950865668,1190.0514957769285
  item: MyDownlight_Color
  icon: oh:light
  iconUseState: true
slots:
  default: []
```

Then the icon will not change as the brightness of the light is changed: you always get the "default state" version of the icon. This seems to be because the item's state is returned as a triplet (H,S,B), and openHAB's UI doesn't extract the brightness from the triplet when fetching the dynamic icon. A dedicated Brightness channel would solve this more cleanly and neatly than having to modify openHAB's code to figure this out.

There are two workarounds to this problem:

1. Create a Group on the Hue Bridge for every color light, and then import the Group into openHAB instead of, or in addition to, the light. This works because Groups are always given a brightness channel, but it results in bridge clutter since every color light you want to use in this fashion needs a group.
2. Turn off the state-enabled icon. Use an expression to extract the brightness channel, and manually fetch the "correct" icon. For example:

```
icon: ='oh:recessed2-'+Math.round(items.MyDownlight_Color.state.split(',')[2]/10)*10`
iconUseState: False
```

Option #2 is preferrable to #1, but as you can see, it gets messy.

A dedicated Brightness channel would solve this. Yes, it's redundant, but its redundancy that enables functionality in the UI.

**Comment by mechalas** [comment]
Using openHAB 3.0.1 with Chromium-based browsers on Ubuntu 20.04 LTS, x86_64.

**Comment by Rossko57** [comment]
This doesn't really have anything to do with Hue.  It'd be a common icon presentation problem with Color type Items connected to any technology (or none).
"Presentation problem" begins to suggest it is something the UI should deal with.

Of course if you invent a "brightness linked icon" solution, someone is going to come along and demand one that reflects colours too :)

**Comment by mechalas** [comment]
I don't have color bulbs other than Hue, so I can't comment on whether this is a global problem. All I know from my experience with the Hue Binding is that it chooses not to expose a Brightness channel.

If it's better off being fixed in openHAB itself, then great.

**Comment by Rossko57** [comment]
It's rather the whole point of Items that they are independent of the technology.  All Color type Items look alike, all incorporate brightness information without any special channels involved.

I'd suggest one place to fix this is actually the host icon-picker service, the gubbins that serves up images to a UI request like -
`http://localhost:8080/icon/light?format=svg&anyFormat=true&state=75`
so as to also deal with raw Color state like -
`http://localhost:8080/icon/light?format=svg&anyFormat=true&state=23,45,75`
Then there _may_ need to be UI updates to take advantage.

The other approach is as you suggest, have the UI isolate the brightness element before requesting icon.

**Comment by mechalas** [comment]
> Of course if you invent a "brightness linked icon" solution, someone is going to come along and demand one that reflects colours too :)

Well, I'm not saying this should be a feature, too, but I'm not _not_ saying it, either. :)

**Comment by kaikreuzer** [comment]
As already mentioned in https://github.com/openhab/openhab-addons/issues/9741#issuecomment-813532265, adding another channel to bindings is a suitable solution.

> This doesn't really have anything to do with Hue.

This is correct, so I suggest to close this issue.

 > but it does not work with dynamic icons (e.g., the light icon, along with the state versions light-10, light-20, etc.)

I haven't tested this, but I would say that this SHOULD work. A dimmer item has a state 0-100, so the dynamic icons should work. If they don't (and that seems to be the problem you are asking to have addressed), please open an issue in openhab-core about this.

**Comment by mechalas** [comment]
> please open an issue in openhab-core about this.

Will do. Thanks!
