### ISSUE TITLE
[somfytahoma] action groups do not trigger

### ISSUE THREAD

**Issue by Numberone77** [openhab/openhab-addons#10489]
I used Tahoma action groups in OH2.5 and would like to use them in OH3 als well. I currentlc upgraded to OH3.M3 on a openhabian sytem. The action groups currently do not work. I send a sendCommand(ON), but they do not trigger at all.

**Comment by cweitkamp** [comment]
> Can the issue be moved into the correct repo ?

Done.

**Comment by lolodomo** [comment]
Sorry for this issue which was the consequence of one of my changes.
