### ISSUE TITLE
[yioremote] Bug during reconnection

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-addons#10491]
There is a bug during reconnection that a Bull error is displayed.

**Comment by miloit** [comment]
Closed by https://github.com/openhab/openhab-addons/pull/10480#issue-610081010

**Comment by lsiepel** [comment]
@miloit the mentioned PR has been merged. This issue was closed and re-opened without any further details, logs er other details.
Can I assume the issue has been resolved? If not could you provide details? Thanks

**Comment by miloit** [comment]
It's solved
