### ISSUE TITLE
In OpenHab 3.0.1, I can't see roku add-on

### ISSUE THREAD

**Issue by junalmeida** [openhab/openhab-addons#10495]
## Expected Behavior
Search for roku, see it on the list as it is an add-on available on this repository. 

## Current Behavior
![image](https://user-images.githubusercontent.com/991675/114206843-5b51f380-9921-11eb-9c60-220229388cd2.png)

## Steps to Reproduce (for Bugs)
1. Open install bindings page
2. Search for roku

## Your Environment

* Version used: openHAB 3.0.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Latest EDGE browser
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Both Windows 10 and openHABian

**Comment by wborn** [comment]
It's only available in the OH 3.1 snapshot and milestone builds. See https://github.com/openhab/openhab-addons/pull/9571.

**Comment by junalmeida** [comment]
@wborn Oh thanks, this makes sense, however shouldn't this be clear in docs? Reading Roku Binding it is not clear. 

https://www.openhab.org/addons/bindings/roku/#roku-binding

**Comment by wborn** [comment]
Yes I also think the way how versions are listed/work can be improved.

There are already a few issues about it:
* https://github.com/openhab/website/issues/275
* https://github.com/openhab/openhab-docs/issues/1470
* https://github.com/openhab/openhab-docs/issues/1469
