### ISSUE TITLE
[jinja] Empty string result when binding is missing

### ISSUE THREAD

**Issue by antroids** [openhab/openhab-addons#10496]
I'm creating an implementation of climate platform for mqtt.homeassistant binding, but found a side issue.
Variable used in state_template can be missing in the state, but Jinja returns the empty string, that considered as valid value.

## Expected Behavior
Thing state should not be updated when variable from state_template is missing in the state.

## Current Behavior
20:26:16.995 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Command '' not supported by type 'OnOffValue': No enum constant org.openhab.core.library.types.OnOffType.`

Payload:
`'{"auto_lock":"AUTO","away_mode":"OFF","away_preset_days":1,"away_preset_temperature":15,"battery_low":false,"boost_time":300,"child_lock":"UNLOCK","comfort_temperature":20,"current_heating_setpoint":20,"eco_temperature":15,"force":"normal","holidays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":20},{"hour":22,"minute":0,"temperature":15}],"linkquality":70,"local_temperature":26,"local_temperature_calibration":-1,"max_temperature":35,"min_temperature":5,"position":0,"preset":"schedule","system_mode":"auto","update":{"state":"idle"},"update_available":false,"week":"5+2","window_detection":"OFF","window_detection_params":{"minutes":10,"temperature":5},"workdays":[{"hour":6,"minute":0,"temperature":20},{"hour":8,"minute":0,"temperature":15},{"hour":11,"minute":30,"temperature":15},{"hour":12,"minute":30,"temperature":15},{"hour":17,"minute":30,"temperature":20},{"hour":22,"minute":0,"temperature":15}]}'`

Template:
`{{ value_json.valve_detection }}`

## Possible Solution
Try this config option: com.hubspot.jinjava.JinjavaConfig#isFailOnUnknownTokens

## Steps to Reproduce (for Bugs)
1. Add the template to OnOff MQTT channel with binding, that missing in state.
2. Publish MQTT message.

## Your Environment
* Version used: openHAB 3.0.1

**Comment by antroids** [comment]
Also reported to zigbee2mqtt project issue with missing properties in state payload.

**Comment by Rossko57** [comment]
When user-defined transformations are involved, common practice is to chain a REGEX that looks for presence of property to e.g. JSONPATH extracting property.  If the REGEX fails, the JSONPATH is not run and so missing field WARNS and empty updates avoided.

**Comment by antroids** [comment]
Sounds like quick fix. These transformations are defined by mqtt topic with Home Assistant configuration, they can be little complexity. Not sure that regexp can be generated to cover jinja syntax. For example: 
`{"action_template":"{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}","action_topic":"zigbee2mqtt/th1"}`

**Comment by antroids** [comment]
I've checked the option com.hubspot.jinjava.JinjavaConfig#isFailOnUnknownTokens. 
In Jinjava 2.5.0 it works only for root variables, and ignores map structures and java beans. 
To support Jinjava transformation in correct way, it must be upgraded to last version. 
Jinvava 2.5.7 works well, tested on data below:

- binding: ["value_json": "val"], pattern: "{{ value_json.val }}", result: "val"
- binding: ["value_json": "val"], pattern: "{{ value_json.asd }}", result: UnknownTokenException
- binding: ["value_json": "val"], pattern: "{{ value_json.asd is defined }}", result: false

Looks like dependency version cannot be updated just in addon's pom, and we need to OSGIfy it first? How can I do this?
