### ISSUE TITLE
[avmfritz] Add support for Humidity (FRITZ!DECT 440)

### ISSUE THREAD

**Issue by kojid0** [openhab/openhab-addons#10500]
Starting with FritzOS 7.25, FRITZ!DECT 440 got the possibilty to measure humidity. It's not yet implemented.

**Comment by cweitkamp** [comment]
This feature has been added several months ago: https://github.com/openhab/openhab-addons/pull/9467

**Comment by kojid0** [comment]
Now I see, I'm still on 3.0.1 (stable), I'll wait for 3.1, thanks!
