### ISSUE TITLE
Multiple Actions per Binding/Thing

### ISSUE THREAD

**Issue by weymann** [openhab/openhab-addons#10510]
**Problem**
In the [current review of bmwconnecteddrive binding](https://github.com/openhab/openhab-addons/pull/8576#discussion_r597866996) we faced the issue how to name the ```@ThingActionScope``` . As a binding developer the scope is bound to a Thing with a certain functionality like ```chargeprofile``` (edit your electric vehicle charging settings). There will be other Actions in future like ```pointofinterest``` (send a new destination to your vehicle) which doesn't belong to the above action. Technically this is possible but the review complains that Actions shall be named  according to the binding name.

**Current documentation:**
Actions besides bindings: https://www.openhab.org/docs/configuration/actions.html
Binding Actions: https://www.openhab.org/docs/developer/bindings/#actions-bound-to-a-thing

**Question**
Is it possible to name the ```@ThingActionScope``` to a certain functionalty scope like ```chargeprofile```?
If not @J-N-K already highlighted the _bad example_ of [telegram binding](https://github.com/openhab/openhab-addons/pull/8576#discussion_r611099985)
If yes can you improve the documentation on [Things Actions](https://www.openhab.org/docs/developer/bindings/#actions-bound-to-a-thing) to have a clear understanding of the naming conventions?

**Comment by lsiepel** [comment]
As @lolodomo is currently driving some PR's around these action scopes, i tag him. Maybe this issue is already fixed by his efforts.

**Comment by lolodomo** [comment]
Interesting as it is in relation to our current discussion in #17785.
Yes documentation has to be improved.
The recommendation is to use binding name as scope but it can be also bindingname-xxx when you need several scopes.
