### ISSUE TITLE
[miio] Support of Smartmi Air Purifier zhimi.airpurifier.za1

### ISSUE THREAD

**Issue by KHOne23** [openhab/openhab-addons#10526]
could you please add Support for the zhimi.airpurifier.za1 Smartmi Air Purifier
[test-zhimi.airpurifier.za1-20210415-162453.txt](https://github.com/openhab/openhab-addons/files/6319589/test-zhimi.airpurifier.za1-20210415-162453.txt)

**Comment by marcelrv** [comment]
@KHOne23 can you load the json file locally and run a refresh with the `log:set debug org.openhab.binding.miio` (all channels linked) and share the log.
For details how to load the file locally pls see the readme

**Comment by KHOne23** [comment]
> @KHOne23 can you load the json file locally and run a refresh with the `log:set debug org.openhab.binding.miio` (all channels linked) and share the log.
> For details how to load the file locally pls see the readme

sorry i didn´t understand what i should do. Set Log Level to Debug ok. but which Json File you mean and what i should do? where i can find the Readme?

**Comment by marcelrv** [comment]
This readme https://www.openhab.org/addons/bindings/miio/#advanced-adding-local-database-files-to-support-new-devices

The json file you find by following the link to the PR in there is a json file with your device. If you download it and save it to your local drive in the right place it will show the channels for your device
https://github.com/openhab/openhab-addons/pull/10534/files

**Comment by KHOne23** [comment]
i have no idea how to do that, is there a howto?

**Comment by marcelrv** [comment]
You can change the setting in the app and see what is the value you see in oh, so we can make a mapping for it.
Alternatively cou can send values to the channel and see what is happening and/or what value range is accepted

**Comment by KHOne23** [comment]
my problem is before :.-) i don´t know how to download the Files and where to put :-)
