### ISSUE TITLE
[tr064] phonebookLookup not working with FB cardDAV adressbook

### ISSUE THREAD

**Issue by JensHoRi** [openhab/openhab-addons#10529]
I have three configured phonebooks. One internal of Fritzbox (say A)  and two carddav (say B and C).

At the Moment the download of the phonebook B failes because of timeout (M3, bug allready solved, but waiting on M4)

So in Log:
Download A done
Download B ERROR (timeout)
Download C done

phonebooklookup in rules works fine for numbers in Phonebook A, but if number only in phonebook C, the return is only the number sent to the lookup.

My idea is, the lookup goes Phonebook by Phonebook and because of error of phonebook B stops then.

I'm sadly not able to change the sort of the phonebooks, so its my thinking for the reason, but cannot definitly confirm this is the reason for the bug.

I see no additional errors in Log, only failure on lookup phonebook B download.

**Comment by J-N-K** [comment]
So you see a successfull download of phonebook C? Then that should also be used for lookup. How many `Normalized '{}' to '{}', matchString is '{}'` lines do you see?

**Comment by JensHoRi** [comment]
In log I got one line successful download of C

2021-04-21 19:34:04.232 [DEBUG] [nternal.phonebook.Tr064PhonebookImpl] - Downloaded phonebook iCard Coryn: {xxxxx=name,......}

But I don’t think that answers your question?!? 

Can you tell where to find additional information to help?

**Comment by J-N-K** [comment]
Use TRACE instead of DEBUG for logging. You should see the line above (with {} replaced by actual values).

**Comment by JensHoRi** [comment]
I just changed to TRACE and did a call:
I saw three lines, so looks like three phonebooks are searched. 

But the result ist still the Caller Number, not the name from the phonebook.

Maybe because in Download of phonebook the number is shown like {0123/ 45 67 89 10= Name} , so 45678010 is not found?

Are chars (except numbers, + and *) eliminated after phonebook download too?

Maybe it's not the failure because of the error downloading the phonebook, but by syntax of downloaded numbers.

**Comment by J-N-K** [comment]
I guess you found a bug in the phonenumber normalization.

**Comment by JensHoRi** [comment]
Maybe because it’s a cardDAV phonebook configured in FRITZ!Box? So normal FB phonebook may not allow spaces and chars. But a cardDAV do. 

So imported phonebooks should ne internally normalized during import.

**Comment by J-N-K** [comment]
No, it‘s a faulty implementation.

**Comment by JensHoRi** [comment]
Ok. Just to be sure my engslish is understandable: 

Normalized '{}' to '{}', matchString is '{}' 

Those rows looks good, without any chars, only numbers. 

But the download of the phonebook looks ‚ugly‘

**Comment by J-N-K** [comment]
Yes. And because of the bug the comparison fails.

**Comment by JensHoRi** [comment]
Are you able to find and solve for next milestone?

**Comment by JensHoRi** [comment]
In M4 still the Same. :(
