### ISSUE TITLE
[Homematic] HmIP-STHD: change humidity channel type HmIP-STHD from Number to Number:Dimensionless

### ISSUE THREAD

**Issue by Anbeku** [openhab/openhab-addons#10533]
HmIP-STHD has a humidity channel of type Number. In my view, Number:Dimensionless is the right type for humidity. At least this should be consistent with HmIP-STHO-A I think and there the humidity channel has type Number:Dimensionless.

**Comment by MHerbst** [comment]
The binding derives the type definition from the metadata returned by the CCU. It seems that the CCU returns different type information for the humidity channels :-(. In my opinion this a Homematic bug. I have seen it several times now that especially the unit information returned by the CCU are incomplete for HmIP devices.

But I think, it would be OK to use Dimensionless for all channel types where no concreted type could be derived.

**Comment by MHerbst** [comment]
@Anbeku I have modified the binding and uploaded a test version: https://github.com/MHerbst/openhab-addons-test  I would be nice if you could give it a try before I create a PR.
