### ISSUE TITLE
[shelly] Add toggle to shelly Plug / Plug S

### ISSUE THREAD

**Issue by bentalexanderhaase** [openhab/openhab-addons#10537]
The Shelly Binding for Plug / Plug S  should include the feature to 'toggle' as per [official api](https://shelly-api-docs.shelly.cloud/#shelly-plug-plugs-relay-0). This feature would especially be useful if you want to toggle lights connected to Shelly plugs and do not care about it's current state / avoid polling the current status.

## My Environment

OpenHab version `3.1.0.M3 (Build)`
Shelly Binding `3.1.0.M3`
Operating System Debian 10.9

**Comment by markus7017** [comment]
toggle what?

**Comment by BentHaase** [comment]
@markus7017 Toggle the device ON/OFF - I'd expect to to be able to send a command to the item and it simply toggles between on and off without creating a separate rule as Shelly already offers an official API endpoint for that.

**Comment by markus7017** [comment]
Maybe addressed as part of PR #12325
