### ISSUE TITLE
[i18n] Property files for translations require ISO-8859 encoding instead of UTF-8

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#10547]
Currently our property files for translations require ISO-8859 encoding. This is a little bit confusing because we use and force UTF-8 encoding for everything else. UTF-8 encoded property files lead to unexpected artifacts in e.g. the UIs.

See https://github.com/openhab/openhab2-addons/pull/5933 or https://github.com/openhab/openhab2-addons/pull/6007

![image](https://user-images.githubusercontent.com/5131747/63086773-e31b0b00-bf50-11e9-80d0-9cd5c1f9adf9.png)

**Comment by hmerk** [comment]
closed
