### ISSUE TITLE
[netatmo] WifiStatus channel never set to "excellent"

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10540]
For the Wifi status channel, we are relying on the system channel type `signal-strength`.
This channel type expects a value between 0 and 4.
Unfortunately, the binding is only producing a value between 0 and 3. The channel value will then be "good" in best case but never "excellent".
This is due to this property set on the thing type:
```
<property name="signalLevels">86,71,56</property>
```
This list should rather contain 4 values.

In my own case, the netatrmo app is showing an "excellent" wifi level but OH is saying just "good". So I know I should add a 4th value lower than 56.

@clinique : any suggestion for the last value to add ?

**Comment by lolodomo** [comment]
The API returns 50 in my case.
I propose to replace the current thresholds 86,71,56 by these new ones: 86,76,66,56.

**Comment by clinique** [comment]
It seems to make sense. Sorry for not being very active currently. I'm moving my place and have dismantled all my home automation equipments + I changed of work and do no have much time to spend on dev. 
This modification will have to be reflected in the current PR on [this file](https://github.com/openhab/openhab-addons/pull/9486/files#diff-6c8479e2c15183dc9e4bf2bc4175ce94c2c59de60ca23e61ea0c4bbd1232e19f)

**Comment by lolodomo** [comment]
No problem Gaël. Good luck for your new job and have fun in your new location.
