### ISSUE TITLE
[mail] Actions documentation

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#10545]
It appears that at least some Mail Actions have been renamed and/or redefined 
e.g. `sendHtmlMailWithAttachment()`
but have escaped from being documented in the add-on doc.

Without understanding the underlying changes, I'm reluctant to attempt any correction myself.

This probably needs flagging as a 3.1 breaking change as well.

**Comment by lolodomo** [comment]
Documentation seems to be almost OK.
In fact, the action `sendMailWithAttachment` for example is applicable in any rule engine except in DSL rule where its name remains `sendMail`. I guess it was done like that for backward compatibility reason.

**Comment by lsiepel** [comment]
It appears to be fixed already. If not or something is overseen, feel free to re-open.
