### ISSUE TITLE
[http] Implement HTTP request time-out/response detection in HTTP Binding

### ISSUE THREAD

**Issue by dinkope** [openhab/openhab-addons#10582]
As disucssed it [this post](https://community.openhab.org/t/how-to-detect-http-binding-is-timing-out/121333), please implement time-out/response detection of GET/PUT/POST HTTP requests in HTTP Binding, similarly to `online` Switch Channel in Network Binding with `servicedevice` Thing.

Implementation of `lastseen` DateTime Channel would also be very beneficial.

Thanks

## Your Environment
* Version used: This feature does not exist of any version of openHAB and HTTP Binding

**Comment by lsiepel** [comment]
The timeout seems to be fixed some time a go, and what you call lastSeen, is now available as  `last-success`, check:  https://github.com/openhab/openhab-addons/issues/13802 and the corrosponding PR.
If not allready fixed, please re-open.
