### ISSUE TITLE
[mqtt.generic] Percentage value not configured as 0..100 if min and max use a different range

### ISSUE THREAD

**Issue by rogierhofboer** [openhab/openhab-addons#10586]
## Expected Behavior

If you create a channel with a percentage value with a min and max of for example 1..254
It converts input values from 0..100 to 1..254 and output values from 1..254 to 0..100
The channel implementation reports 0 as min and 100 as max value to the users of the channel.

## Current Behavior

The channel implementation reports 1 as min and 254 as max value to the users of the channel.

## Possible Solution

A percentage value should always report 0..100 as range and keep the internal range hidden.

## Steps to Reproduce (for Bugs)

1. Create a channel with a percentage value. 
2. Set 1 as min and 254 as max value.
3. Create an item for the channel
4. The item has a slider with a range from 1 to 254 (and values above 100 do not work)

## Context

Items created from percentage value mqtt channels do not have the correct range by default.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
OpenHAB Milestone 3.1.0 
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
N/A
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
N/A

**Comment by CSchlipp** [comment]
Could this be the root cause of https://github.com/openhab/openhab-webui/issues/832 ?
