### ISSUE TITLE
[OpenWeatherMap] UV formatting gives issues in openhab 3

### ISSUE THREAD

**Issue by mlommers** [openhab/openhab-addons#10629]
The example for all UV items in the documentation is giving following formatting:
Current UV Index [%d]

this is giving warnings in the logfile:
Exception while formatting value '4.02' of item weather_owm_localCurrentUvindex with format '%d': d != java.math.BigDecimal

please change the documentation to:
UV Index [%.1f]
and do so for all occurances of this formatting for UV index

**Comment by cweitkamp** [comment]
Hi @mlommers,

Thanks for the hint. Why don't you change it on your own?

**Comment by mlommers** [comment]
hi @cweitkamp ,

Fair question, to be honest just because I don't know how to do it in git(hub). Let me check later today to find out the wonderfull world of git and pull requests and see if I can do it myself

**Comment by mlommers** [comment]
I think I just did the trick, please let me know if I misses something
