### ISSUE TITLE
Many bindings not available in Crowdin

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10635]
Translations for the Netatmo binding is not available in Crowdin.

@cweitkamp : any idea why ? Could it be because there is no netatmo.propertioes file in the binding ?

PS: I volunteer to approve French translations in the openhab-addons repo

**Comment by lolodomo** [comment]
In fact, it looks like a lot of bindings are missing in Crowdin.
In French translations, there are 42 bindings.
Countining the projects having i18n with properties: 105 I believe
As another example, my sonyprojector binding is missing too.

**Comment by cweitkamp** [comment]
@lolodomo Yes, exactly. To be recognized and uploaded to Crowdin the bundle needs one or more `*.properties` files in the `OH-INF/i18n/` folder. Once it has been placed there it will be synchronized.

Currently I am working on a XSLT transformation to automatically generate properties files from our XML definitions. I will commit a draft later.

Thanks for volunteering. I granted Proofread permissions to you on Crowdin for French.

**Comment by lolodomo** [comment]
> Currently I am working on a XSLT transformation to automatically generate properties files from our XML definitions. I will commit a draft later.

Just for my understanding: why now do we have certain bindings but not others ? They were added manually in Crowdin ?

**Comment by cweitkamp** [comment]
Crowdin integration looks for an existing `*.properties` file to synchronize it. Property files having a location suffix are excluded. That why only part of them are already available for translation.

**Comment by cweitkamp** [comment]
See https://github.com/openhab/openhab-addons/pull/10636 for a draft of the XSLT transformation.

**Comment by clinique** [comment]
I second @lolodomo on this. My dev time is a bit restricted currently, so I can help working on translations, and I was also looking for Netatmo binding in Crowdin :-).

**Comment by cweitkamp** [comment]
@clinique Thanks you for offering to help translating add-ons. If you like to add translations for Netatmo someone has to create the properties fuel containing all English source strings and commit it to this repository. After that they will be uploaded automatically and available on Crowdin.

**Comment by cweitkamp** [comment]
Closed by https://github.com/openhab/openhab-addons/pull/11760 (and others).
