### ISSUE TITLE
[tellstick] binding fails to start after upgrade to OH3.1.0 M4

### ISSUE THREAD

**Issue by jorkki22** [openhab/openhab-addons#10642]
[tellstick] binding fails to start after upgrade to OH3 M4, worked fine in M3.

## Expected Behavior
Openhab should start normally and load the Tellstick binding without errors.

## Current Behavior
After upgrade Openhab log says it cannot download file and Openhab server will not start. it gets stuck on this. mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.2.1/1.2.1_2

I removed all bindings from the addons.config and Openhab starts. I added binding one by one until the error reoccured during tellstick binding installation.

```
2021-05-03 10:05:20.372 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-tellstick': Error:

	Error downloading mvn:org.apache.servicemix.specs/org.apache.servicemix.specs.activation-api-1.2.1/1.2.1_2

```

## Possible Solution
Workaround to remove tellstick binding from addons.config and leave the rest there. Openhab starts, but tellstick does not work.

## Steps to Reproduce (for Bugs)
1. Upgrade to OH3 M4
2. Or install tellstick binding to OH3 M4

## Your Environment
Raspberry PI4 
OH3.1.0 M4

**Comment by kaikreuzer** [comment]
Version 1.2.1_2 has been deployed to Artifactory, so M4 should work as well now.

**Comment by DanielMalmgren** [comment]
@jorkki22, could you confirm that it's working now? I'm still on M3 and I don't really dare upgrading to M4 if I risk breaking Tellstick connectivity...

**Comment by jorkki22** [comment]
Confirmed, working again. Thanks everybody.
