### ISSUE TITLE
[hueemulation] kills rest api and basic ui on M4 and SNAPSHOT

### ISSUE THREAD

**Issue by WiredLife** [openhab/openhab-addons#10656]
please fix the hue emulation addon
if its enabled it kills rest api and basic ui with this error

> 01:05:41.658 [WARN ] [.apache.cxf.jaxrs.utils.ResourceUtils] - No resource methods have been found for resource class org.apache.cxf.jaxrs.impl.ResponseImpl
01:05:41.659 [ERROR] [org.apache.cxf.jaxrs.JAXRSInvoker ] - No subresource locator found for path /

click here to read more about this error
https://community.openhab.org/t/openhab-3-1-milestone-discussion/116025/142

**Comment by MikeJMajor** [comment]
Those log messages don't appear to be new in M4:

https://github.com/openhab/openhab-core/issues/2079

Are you also using the cloud connector and the android app?

**Comment by WiredLife** [comment]
no, i dont use the cloud connector and the messages stops if i disable/uninstall the hue emulation addon

**Comment by MikeJMajor** [comment]
@wborn do you have any ideas about this?

Could it be related to this core change:

https://github.com/openhab/openhab-core/pull/2316

**Comment by wborn** [comment]
Maybe, it could perhaps also be related to the Karaf upgrade.

**Comment by WiredLife** [comment]
If i can help you to test out something, let me know

**Comment by wborn** [comment]
If you add an extra line to setenv it should be possible to install hueemulation after a restart, see:

https://github.com/openhab/openhab-distro/pull/1288/files

**Comment by WiredLife** [comment]
> If you add an extra line to setenv it should be possible to install hueemulation after a restart, see:
> 
> https://github.com/openhab/openhab-distro/pull/1288/files

You're my hero <3
Works perfect!
