### ISSUE TITLE
[pulseaudio] Error downloading in 3.1.0.M4 

### ISSUE THREAD

**Issue by Dbzman** [openhab/openhab-addons#10655]
## Expected Behavior
Installation of the pulseaudio binding should succeed.

## Current Behavior
Installation gives the following error in the log
```
[ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-pulseaudio': Error:
	Error downloading mvn:com.googlecode.soundlibs/mp3spi/1.9.5.4
	Error downloading mvn:com.googlecode.soundlibs/jlayer/1.0.1.4
	Error downloading mvn:com.googlecode.soundlibs/tritonus-share/0.3.7.4
```

## Steps to Reproduce (for Bugs)

1. Use openHAB 3.1.0.M4
2. Install the pulseaudio binding

## Context
I'm not able to install the pulseaudio binding. Since I installed it via the UI I couldn't find a way to stop that endless installation loop.

## Your Environment

* Version used: openhab 3.1.0.M4
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Docker on Raspberry PI OS Lite

**Comment by wborn** [comment]
It is probably also related to openhab/openhab-distro#1256.

Can you add these add-on dependencies also to the repository @kaikreuzer?

Meanwhile you can workaround this issue by installing the offline addons KAR file. I.e. download [openhab-addons-3.1.0.M4.kar](https://openhab.jfrog.io/artifactory/libs-milestone-local/org/openhab/distro/openhab-addons/3.1.0.M4/openhab-addons-3.1.0.M4.kar) to your `/addons` dir. If you use an APT based deployment you can also install the KAR file with: `sudo apt-get install openhab-addons`

**Comment by Dbzman** [comment]
Thanks a lot @wborn, it worked like a charm! :)
Let's leave this issue open until the dependencies have been added to the repository.

**Comment by kaikreuzer** [comment]
Sorry, only saw this message now - I have uploaded the libs to Artifactory, so it should now work without the KAR file as well.

**Comment by Dbzman** [comment]
Thanks @kaikreuzer! It seems to work now without the KAR file. I'll close this issue then.
