### ISSUE TITLE
[studer] Developer for embedded project

### ISSUE THREAD

**Issue by tommasocarbonaro** [openhab/openhab-addons#10663]
Hello,

If you’re reading this is because you’re looking for an **extra-job**. We’re working on an embedded solution using openHAB and modbus binding for an all-in-one device that will be open-source and ready to use.

We’re looking for a skilled openHAB developer able to constantly improve the binding:

- Adding new **channels** (items) to be read
- Adding write function (modbus)

Project is almost 80% done. Looking forward to find new devs able to follow it.

There's a bounty of **100$** on going
https://www.bountysource.com/issues/98358761-studer-developer-for-embedded-project

**Comment by kaikreuzer** [comment]
Please ask for a concrete feature to be implemented and for which the bounty will be rewarded - if this is not possible, please rather close this issue here. Thanks!

**Comment by tommasocarbonaro** [comment]
Ok perfectly understood.
I'll do the modification thanks.

**Comment by tommasocarbonaro** [comment]
There's a bounty of 100$ on going 

https://www.bountysource.com/issues/98358761-studer-developer-for-embedded-project

**Comment by lolodomo** [comment]
@kaikreuzer : probably an issue to close?
