### ISSUE TITLE
[Smartmeter] binding stops working

### ISSUE THREAD

**Issue by julred** [openhab/openhab-addons#10678]
## Expected Behavior
I expected that the Smartmeter Binding will work with my communication settings, which I succesfully ran on OH2.5
I'm using an IR USB interface for my Logarex LK13BE
In openhab i get a communication error. 
```
smartmeter:meter:BinderPower     [port="/dev/ttyUSB0", refresh=5, baudrate=9600, mode="D"] {
    Channels:
        Type 1-0_1-8-0 : 1-0_1-8-0
        Type 1-0_16-7-0 : 1-0_16-7-0 [
            negate="1-0_1-8-0:5:1:status"
        ]
}
```

## Current Behavior
After migrating to OH3.02, the existing binding configuration doesn't work anymore.
I already checked the serial output using Minicom (with same baudrate settings as mentioned above):

```
/LOG5LK13BE803039

1-0:96.1.0*255(001LOG006544XXXX)
1-0:1.8.0*255(002195.9138*kWh)
1-0:2.8.0*255(000000.0000*kWh)
1-0:0.2.0*255(ver.03,432F,20170504)
1-0:96.90.2*255(0F66)
1-0:97.97.0*255(00000000)
```

## Possible Solution
Have a look where are the major changes between binding from OH2.5 and OH3

## Steps to Reproduce (for Bugs)
Only possible from my understanding with the same hardware / interface setup

## Your Environment
OH-Version: 3.02, running in Docker
Hardware: Raspberry Pi 4 8GB
OS-Version: Raspbian OS 64 Bit

**Comment by mwildbolz** [comment]
I can confirm, that the setup is working in OH2.5 environment.
Same setup with OH3 is not working any more!

**Comment by julred** [comment]
Is there a possibility to fix this within release of OH3.1?

**Comment by kaikreuzer** [comment]
@msteigenberger Are you aware of any regressions here?
openHAB 3.1 release build will be done tomorrow, so if there's an easy fix, it would be great if you could do a PR asap.

**Comment by julred** [comment]
@kaikreuzer
Thanks for your great willingness to push the Release. I already had an overview of the major changes in this Version. But this issue was Not fixed. Can you declare this topic for the next Release?

**Comment by julred** [comment]
I installed OH 3.1 but still have the same problem.
I had a look into LogViewer:

`2021-06-30 22:13:34.832 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message
java.io.IOException: Received unexpected identification message start byte: 00
	at org.openmuc.j62056.internal.IdentificationMessage.<init>(IdentificationMessage.java:49) ~[bundleFile:?]
	at org.openmuc.j62056.Iec21Port$ModeDReceiver.run(Iec21Port.java:70) [bundleFile:?]`

Does anyone need additional information to solve this magic?

**Comment by julred** [comment]
Is it possible to make a transistion to commit d6364aceb1d952e80c0c8ed758af5d06d072ffa4
After this commit there were a few minor changes. And i think there are some bugs inside

**Comment by smartbee571** [comment]
Hello, 
are there any updates on this issue? The Logarex is widely used in germany. I don't want to create a complete VZLoger instance. I will be grateful for a solutions or a workaround.

**Comment by julred** [comment]
There is no Update ulon this issue. I also had a Look into the changelog of V3.3 - but no comments on this topic.
I made a workaround with node-red. It reads in my smartmeter ir-interface and parse all related information (Power on L1 etc) and Transfer it to openhab by using a openhab connector package.

**Comment by msteigenberger** [comment]
Hi, sorry for very late response.
I looked into the problem, but unfortunately couldn't find anything which could now cause such a behavior.

It seems to still be able to read data from your Serial Port, but the data is not as expected. The identification message (first byte) shall be '/', but it received '0'. 
`2021-06-30 22:13:34.832 [WARN ] [.iec62056.Iec62056_21SerialConnector] - Exception while listening for mode D data message java.io.IOException: Received unexpected identification message start byte: 00 at``
This kind of message might occur once, but does not harm - is that happening continously?

Can you please check the console output since start and provide me here?
