### ISSUE TITLE
[network] Pinging devices in other subnets does not work as expected when using docker image.

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#10675]
Devices in other subnets are always shown as online as long as DNS name resolution returns an IP.

## Expected Behavior
Only devices which are present should be shown as online.

## Current Behavior
All devices where name resolution is successful will be shown as online. Ping seems only to work in same subnet,

## Possible Solution
"ping" should be part of the openhab docker image.
Manual installation is at least possible in openhab 3.1.0 docker container using command
```
apt update
apt install iputils-ping
```

## Steps to Reproduce (for Bugs)
1. You will need openhab 2.5.x or 3.1.x as docker image
2. You will need a subnetted network with devices in subnets other than the openhab net
3. You will need a DNS server which resolves DNS names for your devices in other subnets
4. You will have to setup openhab's network binding like this

```
Thing network:pingdevice:handy_alex                 [ hostname="alexhandy.lan", retry=10, timeout=30000 ]
```

## Context
My network is subnetted due to security reasons. This worked fine when I was using openhab 2.5 native installation on raspbian OS. I think this is a quite common use case which should be supported by openhab,

## Your Environment
see steps to reproduce

**Comment by alexf2015** [comment]
While it was possible in 3.1.0 to install iputils-ping inside the docker container this fails in 3.1.1.
I used
apt update
apt install iputils-ping

apt completely fails due to signature errors.

**Comment by wborn** [comment]
Fixed by https://github.com/openhab/openhab-docker/pull/376
