### ISSUE TITLE
[http] attribute "delay" not configurable via UI

### ISSUE THREAD

**Issue by vguna** [openhab/openhab-addons#10682]
It seems that the attribute `delay` is not configurable via the OH3 3.0.2 UI.
BTW: what is the difference between `refresh` and `delay` in detail? Maybe we can enhance the description a bit ;)?

## Expected Behavior
The option should be configurable as well.

## Current Behavior
The option is not there (see images)

![grafik](https://user-images.githubusercontent.com/3257311/118111725-63032d00-b3e4-11eb-8de3-636fdb9505e4.png)

![grafik](https://user-images.githubusercontent.com/3257311/118111810-81692880-b3e4-11eb-9ea7-eabce7e656c3.png)

## Possible Solution
I set it directly in the `Thing.json` now, but not sure whether it will be respected.

## Steps to Reproduce (for Bugs)
Open the OH UI and look at the thing options with enabled advanced options.

## Context
None

## Your Environment

* Version used: OH3 3.0.2 stable, just did a apt-get upgrade to make sure I'm on latest.
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox latest, Java11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian latest

**Comment by J-N-K** [comment]
`delay` has been introduced after the 3.0 release and therefore is not available on 3.0.2. You need to upgrade to 3.1 to use it.

`refresh` is the time difference between two attempts to refresh all channels. `delay` is the delay between two individual requests. Imagine a thing with three channels: ch1, ch2, ch3

With a refresh of `5` (seconds) and a delay of `0` ms the following requests would be sent

t=0.0 s -> ch1, ch2, ch3
t=10.0 s -> ch1, ch2, ch3

with the same refresh and a delay of `100`:

t= 0.0 s -> ch1
t= 0.1 s -> ch2
t= 0.2 s -> ch3
t=10.0 s -> ch1
t=10.1 s -> ch2
t=10.2 s -> ch3

This is used to reduce the load on the remote webserver.

**Comment by vguna** [comment]
Thanks for the quick and detailed response!

> delay has been introduced after the 3.0 release and therefore is not available on 3.0.2

Ah ok, fair enough ;). Are there any plans to backport it? Or is 3.1 stable not too far away?

> With a refresh of 5 (seconds) and a delay of 0 ms the following requests would be sent
> t=0.0 s -> ch1, ch2, ch3
> t=10.0 s -> ch1, ch2, ch3

Hm, with 5 seconds wouldn't it be?:
 t=0.0 s -> ch1, ch2, ch3
 t=5.0 s -> ch1, ch2, ch3

Anyway, so If I currently only have one channel which fetches some data, it doesn't really matter if I set `delay` or `refresh` to reduce the load on the remote service correct? Setting `refresh` only to `600` would then at most call the remote service every 10 minutes. If so, forget about the backport ;).

**Comment by J-N-K** [comment]
If you have only one channel, delay does nothing. Delay is only used if you have more than one channel.

**Comment by vguna** [comment]
Perfect, thanks!
