### ISSUE TITLE
[homeconnect] Adding the response code in the UI popup displaying the request details 

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10695]
Even if it is of course a very minor enhancement, I think it would be cool to add the response code in the popup displayed when clicking on "Details" button of an API request in the UI page of the binding.

@bruestel : WDYT ?

**Comment by lolodomo** [comment]
It could be even useful to display the response code when you run a request for the specific binding UI page.
I mean in the UI popup:
![image](https://user-images.githubusercontent.com/10186704/118390114-bddb9500-b62d-11eb-838f-79e99e6727b7.png)
You can get the response code but you have to switch to the "API requests" table and look for your request (normally the last one).

**Comment by bruestel** [comment]
Good idea, should be easy to implement. Will do it.

**Comment by lolodomo** [comment]
@bruestel : do you plan to implement it? I am sure it would be easy for you than for me,

**Comment by bruestel** [comment]
Added it to the modal.

![Bildschirmfoto-20210629153809-1036x157](https://user-images.githubusercontent.com/2088078/123811414-7f571c80-d8f3-11eb-8bd9-d42509b6785e.png)

**Comment by bruestel** [comment]
@lolodomo 
> Additionally, it could be even useful to display the response code when you run a request from the specific binding UI page.
I mean in this UI popup:

I've had a second look. I wouldn't show the response code for these kind of actions. 

1. if something went wrong the user can see the status code in the response body
2. a big refactoring of the current controllers and api methods is required

**Comment by lolodomo** [comment]
PR enhancing that is merged.
