### ISSUE TITLE
[openwebnet] subscriptions to energy measures are renewed multiple times after suspension

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#10698]
After OH is suspended (for example beacuse the pc goes in standby) and then resumed, subscriptions to power measures (WHO=18) that  were not sent during the suspension are sent one after the other 

## Expected Behavior
subscriptions to power measures should be sent at regular delays

## Current Behavior
subscriptions to power measures are sent at fixed rate

## Possible Solution
Use 
`ScheduledExecutorService.scheduleWithFixedDelay` [Javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ScheduledExecutorService.html#scheduleWithFixedDelay(java.lang.Runnable,long,long,java.util.concurrent.TimeUnit))

## Your Environment
* openHAB 3.1M4 openwebnet binding

**Comment by aconte80** [comment]
[WARNING] org.openhab.binding.openwebnet.handler.OpenWebNetEnergyHandler.java:[101]
For periodically executed jobs that do not require a fixed rate scheduleWithFixedDelay should be preferred over scheduleAtFixedRate.
