### ISSUE TITLE
[KNX] Items with Dimension are not written to the bus. 

### ISSUE THREAD

**Issue by crystollic** [openhab/openhab-addons#10706]
## Expected Behavior
When sending a value to an item with a dimension the corresponding should be written to the bus.  

## Current Behavior
Value sent to an item with a dimension are not written to the KNX bus.

## Possible Solution
All dimension types should be supported by the binding. Possible solution is mentioned here [https://community.openhab.org/t/can-not-write-value-to-knx-oh3/122363/19](https://community.openhab.org/t/can-not-write-value-to-knx-oh3/122363/19)

## Steps to Reproduce (for Bugs)
Sending a value to an item defined as follows will fail to send the value to the KNX bus.
`Number:Temperature Temperature "Temp [%.2f %unit%]" <temperature> {channel="knx:device:multicast:modes:temperature"}`

Sending a value to an item defined without the dimension will update the KNX bus correctly.
`Number Temperature "Temp [%.2f %unit%]" <temperature> {channel="knx:device:multicast:modes:temperature"}`

Issue also occurs for Number:Time dimension.

## Context
Item dimensions are well documented and their use helps improve the usability of a configured openHAB system.  therefore is would be sensible for the KNX binding to support dimensions. 

## Your Environment
OpenHAB 3.1.0.M4 and earlier (OH2)

**Comment by nanosonde** [comment]
I can cofirm this bug for openHAB 3.2.0.M1.
I have to restart openhab completely to get it working after removing the dimension.

**Comment by Cybso** [comment]
Confirmed (3.1.0-1 on Ubuntu 18.04). Without adding a dimension this works. However, this means you can't directly link a KNX channel to another item (e.g. OpenWeatherMap's Temperature or Humidity) to forward it's value to KNX, but have to create a second item for KNX and use a rule to foward the value:

```
var value = itemRegistry.getItem('OneCallAPIweatherandforecast_Humidity').getState();
events.sendCommand('GenericKNX_HumidityOutdoor', value.doubleValue());
```

**Comment by mpattera** [comment]
Same on 3.1.0 release; if the item is defined as Number:Temperature knx binding won't sent anythig to the bus, if defined as Number works as expected.
