### ISSUE TITLE
[homeconnect] Washing program with missing options

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10705]
Sometimes the washing program options are returned empty by the API when called by the binding:

![image](https://user-images.githubusercontent.com/10186704/118396002-bb893300-b64d-11eb-965f-010a3eecb27d.png)

When I show the details:

![image](https://user-images.githubusercontent.com/10186704/118395652-c773f580-b64b-11eb-9962-4b20f8153591.png)

The consequence is that options are not built for the spin speed and the washing temperature channels. And as the result is cached by the binding, this will remain as it is until a restart of the binding.

But then if I run manually the same request from the UI page, it works as expected:

![image](https://user-images.githubusercontent.com/10186704/118395830-c42d3980-b64c-11eb-9c68-b73c4a3d9d64.png)

**Comment by lolodomo** [comment]
@bruestel : this one is very strange ! Do you think we should retry the request in case there is no options returned (while some are expected) ?

**Comment by lolodomo** [comment]
Maybe a hint: it happened when locally I switch quickly betwwen different programs.

**Comment by bruestel** [comment]
> Maybe a hint: it happened when locally I switch quickly betwwen different programs.

This is a good hint. 

@lolodomo Can I reproduce the behavior with the simulated washer?

**Comment by lolodomo** [comment]
I don't know for the simulator. 
I will try to find how I can reproduce it. 

I believe there is an API to get all available programs options. If true, we could use it once (still caching result per program) , rather than requesting options for each selected program.

**Comment by lolodomo** [comment]
Ok I think I know what is happening.
The API does not provide any option lists while the remote control is disabled.
I first thought it was a bug in the API. But thinking about it, it makes a certain sense: when the remote control is disabled, why providing the list of available options for a control ?
On my washer, when you change something locally on the machine, remote control is disabled and 5 seconds after the last local action, it is enabled again. If you execute the request during this time, you will get no list of available options (like temperatures and spin speeds.

I am not yet clear how to fix that properly.
