### ISSUE TITLE
[BTicinoSmarther]: API Gateway error during polling: Gateway Offline

### ISSUE THREAD

**Issue by gntouts** [openhab/openhab-addons#10709]
## Expected Behavior
Chronothermostats should be able to connect with Smarther 2.0 API and function.

## Current Behavior
Chronothermostats are offline after initial configuration and thow a COMMUNICATION_ERROR  Gateway Offline.

Using the log viewer, I got the following error `Module[bticinosmarther:module:Legrand:GroundFloor] API Gateway error during polling: Gateway Offline`

## Possible Solution
Perhaps the binding's documentation is incomplete or OpenHAB3 is not supported.

## Steps to Reproduce (for Bugs)
Install a fresh OpenHABian installation on Raspberry Pi 4 4GB and follow the official binding documentation found in [BTicinoSmarther - Bindings](https://www.openhab.org/addons/bindings/bticinosmarther/)

## Your Environment
Operating System: OpenHABian installation on Raspberry Pi 4 4GB
Version used: OpenHAB 3.0.2
Public URL accessible for Smarther 2.0 API

**Comment by lsiepel** [comment]
Gentle ping @MrRonfo as you are listed as codewoner, are you aware of this issue? 
I don't see a related PR, so i guess this is still an issue, maybe @gntouts can confirm that with 3.4.1 it still exists.

**Comment by gntouts** [comment]
@lsiepel, my setup has changed a lot since I opened this issue.  I can not confirm that the issue is still present.

**Comment by lsiepel** [comment]
I suggest we close this  issue as it is allmost two years old, no other user reported it here and the OP can;t confirm as the setup has changed. If the problem returns, this issue can be found and re-opened.
