### ISSUE TITLE
[Venstar Thermostat] binding expansion

### ISSUE THREAD

**Issue by raveydavies** [openhab/openhab-addons#10707]
Using OpenHAB 3.0 on Raspberry Pi 4.

I would like to add some more functionality in the Venstar Thermostat binding. The local API supports more variables, config options and commands than are currently included in the binding. I'd like to contribute as my first attempt at openHAB development. I will probably start with one additional parameter, to check if my skills are good enough for the job, and expand from there if it works out OK.

**Comment by digitaldan** [comment]
HI, that sounds great, would be happy to review for you.  What missing features are you planning on adding ?

**Comment by raveydavies** [comment]
Well, there's a list of lots of potential features. I'll try adding one first to see if I'm capable and understand the workflow 😆. I would probably go for home / away mode selection as an easy one. This would be a switch channel in the Thing.
The full list (combination of config and channels) is:
Away mode (off/on)
Fan setting (auto/on)
Fan state (off/on)
Schedule state (disabled /enabled)
Schedule part (5 options)
Runtimes (numbers)
Alerts. 

I'm a good self-taught programmer but have never done anything requiring following development rules or using git, so might get stuck at some point and it might take me a while. Is there a good target date to be ready by, for example a new version expected?

**Comment by raveydavies** [comment]
@digitaldan I forked the repo in github to work on it, and created a branch in my fork. I've then made some code changes on my local PC (in Eclipse IDE) and pushed them back to github to my branch. I'm unclear what I need to do now (lack of familiarity with the tools, I'm afraid).
- How can I test my code locally before doing anything else? I've seen the openHAB documentation about testing in the Eclipse IDE demo project but I can't figure out how to get my version of the binding which is currently in my fork / branch into that.
- For you to review the code, what should I do? Should I create a pull request on my fork of the repo, or on the openHAB main fork, or something else?
- What do I need to do with maven (if anything) at this point?

**Comment by raveydavies** [comment]
Thanks @digitaldan . I'll come back to you again in a couple of days. I think I'll be spending as much time learning Eclipse, git, github as I am doing the actual code.

**Comment by raveydavies** [comment]
@digitaldan sorry to bother you again....when I try to run my locally created binding in Eclipse openHAB demo environment, what GroupID should I put in the pom.xml file in openhab.demo.app? Nothing seems to work.

**Comment by digitaldan** [comment]
if you mean you are trying to add the venstar binding as a dependency, i don't think you touch groupid, but the artifactId, so you would add to the pom something like: 

``` 
<dependency>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.binding.venstarthermostat</artifactId>
    <version>${project.version}</version>
    <scope>runtime</scope>
</dependency>
```

the example at https://www.openhab.org/docs/developer/ide/eclipse.html  uses the astro binding as an example fyi

**Comment by raveydavies** [comment]
Yes. But then it starts up the binding which is already part of OpenHAB, not my new local version that I want to test. So I was thinking I need to somehow direct the groupID to my code. No idea how though.

**Comment by raveydavies** [comment]
OK I managed to make it work. No idea how, but now I can open it in the demo app. Now all I need to do is make the binding do what I want it to do.....

**Comment by raveydavies** [comment]
@digitaldan my binding update seems to work. I added only the "away mode" to the binding for the moment. I will create a PR.
