### ISSUE TITLE
[openwebnet] add support for Thermoregulation (WHO=4) for standalone thermostat and sensors

### ISSUE THREAD

**Issue by aconte80** [openhab/openhab-addons#10702]
Add support for Thermoregulation function (WHO=4) from standalone thermostat (like LN4691) and sensors

**Comment by mvalla** [comment]
Temp sensors have been already requested in issue #8582

**Comment by mvalla** [comment]
@fwolter, do you think it's possibile to include this in 3.1M5 ? This is an important and long-awaited enhancement and surely users will need to test it before merging in the upcoming 3.1 (expected in June). If we skip merge of this PR to the June milestone, that would mean that it would be integrated in the official 3.1 without much testing by users. Of course we already tested it as much as possibile in our 2 setups, but having feedback from community would be impotant. Thanks!
