### ISSUE TITLE
[voice-pollytts] config file (pollytts.cfg) not recognized/load

### ISSUE THREAD

**Issue by 1nn0v8** [openhab/openhab-addons#10723]
## Expected Behavior
According to the documentation for OH3.1 https://next.openhab.org/addons/voice/pollytts/ the configuration can still be done using configuration files: 
> Create a new file in $OPENHAB_ROOT/conf/services named pollytts.cfg

## Current Behavior
pollytts.cfg is not recognized/load. PollyTTS can only be used setting required access/secret access keys via web console.

## Possible Solution
Let openhab 3 recognize/load pollytts.cfg config file from services folder.

## Steps to Reproduce (for Bugs)
1. Install pollytts addon
2. Create/place pollytts.cfg in $OPENHAB_ROOT/conf/services --> config will no be load

## Context
Tried to copy my current OH2.5 config to OH3 using text files and could not get PollyTTS working.

## Your Environment
* Version used: 3.1.0.M4
* Operating System and version: Debian 10.9

**Comment by lolodomo** [comment]
The content of your file is probably wrong. Check in particular the path of your settings. They should no more contain smarthome but openhab.

**Comment by lolodomo** [comment]
Sorry, it was moty intention to close it.

**Comment by coriet** [comment]
@lolodomo: good hint, checked that and as expected I did update it according to the doc for 3.1. On restart I keep receiving the error message in the log that the settings were not found.

Extract from my pollytts.cfg:

`org.openhab.pollytts:accessKey=XXX
org.openhab.pollytts:secretKey=XXX
org.openhab.pollytts:serviceRegion=eu-west-1
org.openhab.pollytts:cacheExpiration=14
org.openhab.pollytts:audioFormat=mp3`

**Comment by lolodomo** [comment]
Your paths are still wrong. "voice" Is missing I guess. 
PS: the better place for such "how to user" or "how to setup" is the forum IMHO.

**Comment by lolodomo** [comment]
Normally, what is expected is:
org.openhab.voice.pollytts:setting=value

**Comment by coriet** [comment]
great, thx, that was it. Is there anything I can do to trigger a doc update to add the missing "voice" (https://next.openhab.org/addons/voice/pollytts/).

**Comment by coriet** [comment]
#https://github.com/openhab/openhab-addons/pull/10725
