### ISSUE TITLE
[fmiweather] binding communication error "Unexpected API response"

### ISSUE THREAD

**Issue by vobehu** [openhab/openhab-addons#10732]
## Expected Behavior
Fetching the weather **forecast** (Service fmi::forecast::hirlam::surface::point::multipointcoverage) for a location. Worked up to Tuesday 18.05.2021 10:20 CET.

## Current Behavior
Since then the fmiweather Binding is broken and stopped getting new data from the FMI webservice. Logentry:

```(COMMUNICATION_ERROR): Unexpected API response: No locations in response -- no data?```

This is a query the binding shows in DEBUG level:
```https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::hirlam::surface::point::multipointcoverage&starttime=2021-05-21T19:20:00Z&endtime=2021-05-23T21:40:00Z&timestep=20&latlon=50.711749,7.101946&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3```

The problem occurs since may 18 with another OH user too, which suggests the FMI service might have changed:
https://community.openhab.org/t/fmiweather-binding-unexpected-api-response/122546?u=uheb

## Steps to Reproduce (for Bugs)
Configure a FMI forecast Thing:
Thing fmiweather:forecast:forecast_home "Forecast" [location="50.711749, 7.101946"]

## Your Environment
Release: openHAB 3.0.2
Build: Release Build
OS: Openhabian, Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.10.17-v7l+

**Comment by antonmies** [comment]
Thank you for posting the issue!
I'm experiencing the exact same thing and when the issue started.

**Comment by pol-henri** [comment]
Same here thanks ;

**Comment by vobehu** [comment]
Info from FMI support, FMI didn't find any suitable information what might have changed that day.

**Comment by antonmies** [comment]
At first I thought it was OH so I restarted it, but no effect.
Then I updated OH with apt, but that didn't help either.

**Comment by Numberone77** [comment]
I have the same issue with OH 3.1.0.M4

**Comment by bifi2090** [comment]
Same here at OH 3.1.0.M4.

**Comment by myvalentin** [comment]
same with OH 2.5.12

**Comment by Numberone77** [comment]
Issue is solved in OH 3.1.0.M5: see #10765.

**Comment by vobehu** [comment]
Great, thanks!
