### ISSUE TITLE
[shelly] Shelly EM - add powerFactor channel support

### ISSUE THREAD

**Issue by Mark-VG** [openhab/openhab-addons#10737]
* Version used: openHAB 3.1.0.M4
* Environment name and version: Java Runtime Azul Systems, Inc. 11.0.9.1 (Zulu11.43+55-CA)
* Operating System and version: Windows 10/10.0 (amd64

The Shelly EM3 supports the powerFactor channel as per the docs.

It appears however that the ShellyEM does not support the powerFactor channel, even though this appears to be available on the device:
![Shelly EM PF](https://user-images.githubusercontent.com/84638697/119236259-b2f59880-bb36-11eb-8933-7a49eb220553.png)

Firmware on Device: 20210429-102232/v1.10.4-g3f94cd7

The PF is used to calculate an accurate VA value from the reported Watts value so is important.

Would it be possible to implement this as a feature?

**Comment by markus7017** [comment]
There should already be the channel meter#powerFactor
if should be created when the emeter json has the value pf
if not please provide the output from http://&lt;device ip&gt;/status

**Comment by markus7017** [comment]
implemented
