### ISSUE TITLE
[gardena] mower "Next automatic starting time" not available in OH3 after binding rewrite

### ISSUE THREAD

**Issue by michel53** [openhab/openhab-addons#10743]
In the Gardena binding, the mower "Next automatic starting time" channel is not available any more in OH3 after binding rewrite.
I would like to see this channel again.

**Comment by grichter24** [comment]
I would also like to have the feature back.

Also missing:

battery#charging
mower#source_for_next_start
mower#timestamp_next_start
mower#park_until_further_notice
mower_stats#charging_cycles
mower_stats#collisions
firmware#firmware_status
firmware#firmware_upload_progress
firmware_available_version

These still work in openhab 2.5

**Comment by lsiepel** [comment]
https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API
Whatt api data would fit in these cvhannels?
