### ISSUE TITLE
[RemoteopenHAB] issues with docker container OH2.5 and OH3 on same IP

### ISSUE THREAD

**Issue by Homer-Sim** [openhab/openhab-addons#10758]
Hello
I freshly installed OH3 in docker container on same server as OH2.5 is hosted (docker container too)
I added in bridge settings ip address and port of oh2 container but I am getting an error telling me IP address can not be the same ...

**Comment by lolodomo** [comment]
The IP check was removed few months ago. 
You are probably running 3.0. This is fixed in 3.1.
See PR #10049
