### ISSUE TITLE
Climate component in MQTT

### ISSUE THREAD

**Issue by misery** [openhab/openhab-addons#10764]
I like to request to support "climate" components in MQTT via homeassistant discovery.

https://www.openhab.org/addons/bindings/mqtt.homeassistant/
```
The HomeAssistant Climate Components is not yet supported.
```

```
[WARN ] [.mqtt.homeassistant.internal.CFactory] - Not supported
java.lang.UnsupportedOperationException: Component:Climate not supported yet
        at org.openhab.binding.mqtt.homeassistant.internal.ComponentClimate.<init>(ComponentClimate.java:38) ~[?:?]
        at org.openhab.binding.mqtt.homeassistant.internal.CFactory.createComponent(CFactory.java:66) ~[?:?]
        at org.openhab.binding.mqtt.homeassistant.internal.DiscoverComponents.processMessage(DiscoverComponents.java:99) 
```

I wrote my own heating 2 mqtt bridge and want to add auto-discovery. openhab can detect it but throws the UnsupprtedOperationException.

https://github.com/misery/HeatingMqttBridge

**Comment by misery** [comment]
@davidgraeff Is this possible to implement with current architecture of openhab3? :-)

**Comment by cribskip** [comment]
#10690 seems to implement this

**Comment by misery** [comment]
Oh, thank you for the link to the PR! Really nice.

**Comment by antroids** [comment]
I can build a custom binding bundle for you, just need to know your OH version. 
Unit tests could help you in development: https://github.com/openhab/openhab-addons/blob/cba1d07a224549dd7806dc9f5278faf17caa413c/bundles/org.openhab.binding.mqtt.homeassistant/src/test/java/org/openhab/binding/mqtt/homeassistant/internal/component/ClimateTests.java

**Comment by misery** [comment]
Thanks, I'm still using 2.5.12. Next upgrade will be 3.1. 🙂

Btw, looks like the alias "temp_unit" is missing. I See "temperature_unit" only.

**Comment by antroids** [comment]
Where the temp_unit should be? 
Cannot see it in doc: https://www.home-assistant.io/integrations/climate.mqtt#temperature_unit
Zigbee2mqtt is using the long version in */config topic.

**Comment by jochen314** [comment]
The abbreviations are listed as 'Supported abbreviations:' here: https://www.home-assistant.io/docs/mqtt/discovery/
And the 'temp_unit' is implemented in openhub here: https://github.com/openhab/openhab-addons/blob/4ad6eda9619c10a421a3919f28ac6a6a0a749d7c/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/MappingJsonReader.java#L197

Our list needs a update again, it is no longer complete :-(

**Comment by antroids** [comment]
> Thanks, I'm still using 2.5.12. Next upgrade will be 3.1. 
> 
> Btw, looks like the alias "temp_unit" is missing. I See "temperature_unit" only.

Sorry, I haven't ready to use environment for 2.5.x and cannot build it for this version. 

Personally for me migration from 2.5.x to 3.0.x was pretty simple. I still using the same config files for items and sitemaps definition. The only incompatibility was tricky global var in my rule, but it was easily replaced by an additional item.

**Comment by misery** [comment]
No problem. I can spawn a 3.0 instance in docker to have a test environment.

**Comment by antroids** [comment]
> No problem. I can spawn a 3.0 instance in docker to have a test environment.

There are 2 versions, I think they should be compatible with OH 3.x.
The simplest way to install is uninstall/stop old and place one of these bundles to addons folder.

[org.openhab.binding.mqtt.homeassistant-3.0.3-SNAPSHOT.tar.gz](https://github.com/openhab/openhab-addons/files/6575073/org.openhab.binding.mqtt.homeassistant-3.0.3-SNAPSHOT.tar.gz)
[org.openhab.binding.mqtt.homeassistant-3.1.0-SNAPSHOT.tar.gz](https://github.com/openhab/openhab-addons/files/6575074/org.openhab.binding.mqtt.homeassistant-3.1.0-SNAPSHOT.tar.gz)

**Comment by misery** [comment]
Thanks! I tried it and it works for me. Is that right that "temp_stat_t" will be mapped to a ``Point`` instead of ``Setpoint``?

**Comment by antroids** [comment]
> Thanks! I tried it and it works for me. Is that right that `temp_stat_t / temp_cmd_t` will be mapped to a `Point` instead of `Setpoint`?

Not sure what are Point and Setpoint in HVAC terminology, in HA there are:
1) [Current temperature](https://www.home-assistant.io/integrations/climate.mqtt#current_temperature_topic) for sensor, read only.
2) [Temperature](https://www.home-assistant.io/integrations/climate.mqtt#temperature_state_topic) (also low/high) for target temperature set.
