### ISSUE TITLE
[mqtt] add bytearray payload support in MQTTActions.java 

### ISSUE THREAD

**Issue by lex777777** [openhab/openhab-addons#10762]
Strings payloads have to convert to an bytearray anyway.
So it would be great if it can be addressed directly.

[openhab-addons/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/action/MQTTActions.java](https://github.com/openhab/openhab-addons/blob/19029b73589fecbc1e4eb0d1979b880ef4243edc/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/action/MQTTActions.java#L79)

**Comment by Rossko57** [comment]
Example use case
https://community.openhab.org/t/publish-mqtt-raw-bytearray/122511
Binary payloads are permitted in MQTT

**Comment by lex777777** [comment]
Thank you very much
