### ISSUE TITLE
[sonos] No Thing Type for Sub

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#10777]
When configuring my sub I noticed it comes up as zoneplayer when discovered.  According to the documentation the subs are supported so I would believe that would mean that they should have a thing type.  Looking through the code, it doesn't look like it was added when support for the sub was added.

**Comment by lolodomo** [comment]
The sub is not a standalone speaker I believe. This is more a complement to another speaker or pair of speakers. That is why it is not handled by the binding,

**Comment by morph166955** [comment]
So that's a valid point, you can't just use it like you would a speaker.  In that case, should we hide it from being detected in the inbox/etc?

**Comment by lolodomo** [comment]
Yes we could ignore it in the discovery.

**Comment by lolodomo** [comment]
Please open http://192.168.x.xx:1400/xml/device_description.xml and tells me what is the valuye for the tag "modelName".

**Comment by morph166955** [comment]
<deviceType>urn:schemas-upnp-org:device:ZonePlayer:1</deviceType>
<friendlyName>x.x.x.x - Sonos Sub</friendlyName>
<manufacturer>Sonos, Inc.</manufacturer>
<manufacturerURL>http://www.sonos.com</manufacturerURL>
<modelNumber>S26</modelNumber>
<modelDescription>Sonos Sub</modelDescription>
<modelName>Sonos Sub</modelName>
<modelURL>http://www.sonos.com/products/zoneplayers/S26</modelURL>
<softwareVersion>63.2-89260</softwareVersion>
<swGen>2</swGen>
<hardwareVersion>1.32.1.6-1.2</hardwareVersion>
