### ISSUE TITLE
[deCONZ] Window Covering not working

### ISSUE THREAD

**Issue by junalmeida** [openhab/openhab-addons#10774]
Device: MoesHouse/Tuya AM43 Blinds Drive  via deCONZ is not working

## Expected Behavior
Clicking `UP` or `DOWN` should make the blinds drive move.

## Current Behavior
When I click DOWN, I can see the following in the logs:
```
2021-05-28 18:47:13.752 [TRACE] [internal.handler.DeconzBridgeHandler] - Sending {"on":true,"ontime":0} via http://10.0.0.99:80/api/0D234FD02F/lights/6/state
2021-05-28 18:47:13.757 [WARN ] [ernal.handler.DeconzBaseThingHandler] - Sending command DOWN to channel deconz:windowcovering:000000000000:847127fffe1aa5d901:position failed: 400 - [{"error":{"address":"/lights/6/state","description":"parameter, ontime, not available","type":6}}]
```
And nothing happens.

If I click UP, I can see the following:
```
2021-05-28 19:00:23.708 [TRACE] [internal.handler.DeconzBridgeHandler] - Sending {"on":false} via http://10.0.0.99:80/api/0D234FD02F/lights/6/state
2021-05-28 19:00:23.731 [TRACE] [ernal.handler.DeconzBaseThingHandler] - Result code=200, body=[{"success":{"/lights/6/state/open":true}}]
```
And besides the successful message, and the blinds being closed/down, nothing happens.

## Possible Solution
According to a deCONZ member on https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4942 `ontime` is not a supported parameter on their API. 

## Steps to Reproduce (for Bugs)
1. Create a item like below
```
  "LivingRoomBlinds": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "LivingRoom"
      ],
      "itemType": "Rollershutter",
      "tags": [
        "Blinds"
      ],
      "label": "Living Room Blinds",
      "category": "Rollershutter"
    }
  },

```
2. Connect it to the windowcovering thing in deCONZ
3. Hit `UP` or `DOWN` commands.

## Context
Trying to control the blinds using the item:
![image](https://user-images.githubusercontent.com/991675/120072213-4576ca00-c058-11eb-9fd3-c4673e420085.png)

## Your Environment
* Version used: openHAB 3.1.0M4
* Operating System and version: openHabian

**Comment by J-N-K** [comment]
So UP is working, DOWN not?

**Comment by junalmeida** [comment]
Neither is working, however on UP I can see a successful message in logs.

**Comment by J-N-K** [comment]
Please show your thing configuration.

**Comment by junalmeida** [comment]
![image](https://user-images.githubusercontent.com/991675/120072680-ab645100-c05a-11eb-9810-0075b6c062a6.png)

**Comment by J-N-K** [comment]
If you send a position, is that working?

**Comment by junalmeida** [comment]
Currently I'm using the item below: 
![image](https://user-images.githubusercontent.com/991675/120072811-304f6a80-c05b-11eb-9412-f30d361a1594.png)

All I can send as a user is UP/DOWN/STOP.

**Comment by J-N-K** [comment]
I can confirm that this is a bug. UP (and setting a position) works for me, but neither DOWN nor STOP.  This is a regression introduced with #9914.

**Comment by junalmeida** [comment]
@J-N-K 
Is there any ETA on when this is coming to a milestone? If not, is there a way to workaround the issue ?

**Comment by MHerbst** [comment]
@junalmeida I have probably solved the problem for window coverings, but I still need to make sure that the fix does not have a negative impact on devices that support "on time" before I can submit a PR.

**Comment by cweitkamp** [comment]
@MHerbst Thanks for looking into this. Is your fix based on the deprecated `bri` field or does is cover the recently introduced [window covering parameters](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters)?

**Comment by MHerbst** [comment]
@cweitkamp The problem is caused by the newly introduced "ontime" option (see #9914). If this value is set for window coverings deConz returns an error message. In the current implementation this value was always set even if the thing has no channel for "ontime".
I have modified the implementation and the value for "ontime" will only set if a device has got an "ontime" channel.

**Comment by cweitkamp** [comment]
Fair enough. Keep going. Thanks for explanation.

I just want to spread news about improvements on deCONZ which might help us too.

**Comment by junalmeida** [comment]
Have you considered an addon based off of `zigpy-deconz` that does not rely on deconz api.

**Comment by MHerbst** [comment]
> I just want to spread news about improvements on deCONZ which might help us too.

@cweitkamp Thank you very much for this. Until last night I did not know that something has changed in the REST API :-). A clean implementation might be a bit more time-consuming, because I have to introduce a separate DTO for the window coverings.

**Comment by MHerbst** [comment]
> Have you considered an addon based off of `zigpy-deconz` that does not rely on deconz api?

I don't think that this was considered. As far as I could see the documentation of the protocol was not publicly available until some months ago. An implementation would also require knowledge of the Zigbee protocol and an implementation would be much more complex and difficult to test.

**Comment by junalmeida** [comment]
@MHerbst `zigpy` creates an abstraction layer on top of the serial protocol, and supports deconz Conbee and other devices.

**Comment by MHerbst** [comment]
@junalmeida zigpy won't help because it is written in Python 3 and not Java

**Comment by junalmeida** [comment]
@MHerbst Yeah that could be a blocker. Nm, it is just a spread of ideas. Unfortunately deconz phoscon is an specific proprietary API that adds a huge load (due to its dependencies) to a small server like a raspberry.
