### ISSUE TITLE
[TR064-binding] wrong dB-Values

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab-addons#10783]
Hello,
In the TR064 binding, the dB values are incorrectly output with a factor of 10. 50 dB is displayed here, although it is only 5 dB.
![TR064](https://user-images.githubusercontent.com/16850444/120154557-4d697200-c1f0-11eb-90c5-32d0f68087d3.png)

**Comment by Rossko57** [comment]
Use API Explorer to confirm actual Item state, to eliminate presentation issues.

I note your locale includes the comma decimal separator, which might have something to do with it.

**Comment by J-N-K** [comment]
Most likely this is indeed a bug. Looking at the v1 version of the binding, the example item-file shows a unit "dB*10" while the current code uses "dB".  I'm not sure if it is possible do define something like "deka-dB".

**Comment by LukaNoah** [comment]
Hi,
here more infos.
Yes, my locale includes the comma decimal separator.
My fritz!box DSL-info:
![2021-06-01 20_16_21-Window](https://user-images.githubusercontent.com/16850444/120371761-8e5ba680-c316-11eb-9d91-adf4af4b0f24.png)

API-Explorer:
![2021-06-01 20_24_02-Window](https://user-images.githubusercontent.com/16850444/120372355-628cf080-c317-11eb-83c3-a75700bfd227.png)
