### ISSUE TITLE
[goecharger] new hardware version v3 and new firmware v2 seem to be unstable or not supported

### ISSUE THREAD

**Issue by ako-3004** [openhab/openhab-addons#10791]
I changed the v2 hardware go-e charger to the brand new v3 hardware which I got these days.
v2 charger worked very fine in openhab. had may working rules.

v3 Hardware:
Removed the old openhab "thing", deinstalled and reinstalled the goecharger binding and added the new charger by ip. seemed to work a few seconds first, then "java.lang.IllegalStateException" is shown in thing configuration and openhab log. the api shoud be the same as the older charger has, but there may be some changes which affect the error:

## Current Behavior
Thing configuration in openhab 3 switches between "online" and "communication error" in a loop. few seconds "online", few seconds "communication error".
`Status: 
OFFLINE
COMMUNICATION_ERROR
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
`

Logfile repeats this lines in a loop:
`2021-06-02 00:31:01.142 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'goecharger:goe:413602c5bf' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

2021-06-02 00:31:01.151 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_MaxCurrent' changed from 6 to UNDEF

2021-06-02 00:31:01.156 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_PwmSignal' changed from WAITING_FOR_CAR to UNDEF

2021-06-02 00:31:01.159 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_Error' changed from NONE to UNDEF

2021-06-02 00:31:01.173 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_CurrentL1' changed from 0.0 A to UNDEF

2021-06-02 00:31:01.175 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_CurrentL2' changed from 0.0 A to UNDEF

2021-06-02 00:31:01.176 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_CurrentL3' changed from 0.0 A to UNDEF

2021-06-02 00:31:01.177 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_PowerL1' changed from 0 W to UNDEF

2021-06-02 00:31:01.178 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_PowerL2' changed from 0 W to UNDEF

2021-06-02 00:31:01.179 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_PowerL3' changed from 0 W to UNDEF

2021-06-02 00:31:01.179 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_Phases' changed from 0 to UNDEF

2021-06-02 00:31:01.180 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_SessionChargeEnergyLimit' changed from 1 to UNDEF

2021-06-02 00:31:01.182 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_TotalChargedEnergy' changed from 0.0 kWh to UNDEF

2021-06-02 00:31:01.183 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_AllowCharging' changed from OFF to UNDEF

2021-06-02 00:31:01.184 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_CableCurrent' changed from 32 A to UNDEF

2021-06-02 00:31:01.184 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_Firmware' changed from 050 to UNDEF

2021-06-02 00:31:01.185 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GoECharger_AccessConfiguration' changed from OPEN to UNDEF

2021-06-02 00:31:03.217 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'goecharger:goe:413602c5bf' changed from OFFLINE (COMMUNICATION_ERROR): java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ to UNINITIALIZED`

## Your Environment
goe charger new hardware v3, new firmware 050
Important: the new firmware has a new api ("v2") but it is also possible to use and enable the old ("v1") api which I did.
old v1 api is the same as in the past: http://192.168.1.8/status, http://192.168.1.8/mqtt?payload=amp=10 (works as it did in older hardware)
(new v2 api: http://192.168.1.8/api/status)

I already had a look at the goecharger java files and found out that the v1 api is used. Unfortunately I am not experienced in Java. If I can support any developer by giving more information and testing please ask me.

**Comment by chilobo** [comment]
I have the same configuration and get the same error message. My programming experience doesn't include java either, but I am willing to help too.

**Comment by chilobo** [comment]
Well, I installed all the necessary software, did a fork and deleted (I still have to learn how to uncomment lines in *.xml and *.java ) all the lines with temperature, Temperature and the corrseponding case-statements in GoEChargerHandler.java.java.

My first successful compile with java!

I copied the  org.openhab.binding.goecharger-3.1.0-SNAPSHOT.jar file to /usr/share/openhab/add-ons ....

It's working!

**Comment by chilobo** [comment]
To change the current the binding uses the field **amp** of the GO-E.
Support recommends to **use amx instead** because amx is not written to the EEPROM, so using it instead prolongs the life of the box.

**Comment by Drazhar** [comment]
I also plan to modify the code for the goecharger to add the overall power (nrg[11]).
My wallbox is still on V1, so I could test your modifications. Did you create a branch which I can pull?

**Comment by chilobo** [comment]
I think I am just not (yet) expierenced enough to give out the branch. Well, I managed to replace amp with amx. 
But I think this field is not available in V1.
Up to now I did not manage to use the new Temperature fields provided in tma.
Because those fields just do not exist in V2 (and V1 ?) testing it against V1 would only be useful if I added code which is valid for all three versions. That seems to be too difficult for me at the moment.

**Comment by chilobo** [comment]
> I also plan to modify the code for the goecharger to add the overall power (nrg[11]).
I guess I could try to add this, note the changes I have to do in the 4 files which are used and then you could do a fork and add them. Should I try this?

**Comment by Drazhar** [comment]
> @Drazhar wrote:
> > I also plan to modify the code for the goecharger to add the overall power (nrg[11]).
> 
> I guess I could try to add this, note the changes I have to do in the 4 files which are used and then you could do a fork and add them. Should I try this?
> 

Would be great! I currently have a lot on my plate and I'm not sure when I find the time to do it :)

**Comment by chilobo** [comment]
I added my code as a pull request:
[https://github.com/openhab/openhab-addons/pull/10861](url)
The jar can be found at:
[https://www.dropbox.com/s/fzx819g2skgem0m/org.openhab.binding.goecharger-3.1.0-SNAPSHOT.jar?dl=0](url)

Please try this jar:
To use it I had to copy it to  /usr/share/openhab/addons, delete the old thing in the UI, restart the server, add a new thing, connect the channels to my UI

**Comment by chilobo** [comment]
Just an update: The original contributor Sebastian B. suggested to keep possible usage of amp because amp offers the possibility to change the permanent current value for charging. amx doesn't. I agree, but struggle to incorporate both. Right now I can replace the occurences of "amp" by "amx", but adding code to read (!) and write values auf amx do not show up. Strange - but I am just learning to code!

**Comment by chilobo** [comment]
I compiled and tested a new version
https://github.com/chilobo/openhab-addons/commit/0bffd0347196dc5e51aed90734c1c7004b34d025

Still not working on V3.
I am not shure if I did this Push - and Commit process right.

**Comment by chilobo** [comment]
I guess I found a solution.
I had to change the method to submit the mqtt-request from POST to GET.
You find the jar at:
https://www.dropbox.com/s/jbnkijlfbul9soq/org.openhab.binding.goecharger-3.1.0-SNAPSHOT.jar?dl=0

Do I have to submit a new request to get this change approved?
Shouldn't somebody test my changes and look at the code I changed?

**Comment by chilobo** [comment]
Changed the handling of Current_session_charged_energy back to its original handling because GOE changed its output back.
[https://github.com/openhab/openhab-addons/pull/10903](url)

**Comment by ako-3004** [comment]
Charger hardware version 3 now comes with a firmware that supports MQTT. So you don't necessarily need the binding anymore.

**Comment by lsiepel** [comment]
V3 compatibility has been added by: https://github.com/openhab/openhab-addons/pull/12733 Can you confirm all is fine since openhab 3.3.0?

**Comment by ako-3004** [comment]
Unfortunately I switched to another system for Managing the goe charger long time ago. It is not included in my openhab anymore. Maybe https://github.com/chilobo still uses openhab with goe and can confirm this fix... ?

**Comment by lsiepel** [comment]
@chilobo would be nice if you can confirm it. Otherwise i would opt to close this issue and if you ever switch back, we can re-open it.

**Comment by chilobo** [comment]
I was using the binding until 3 days ago with Hardware version 3 and Firmware 054.11 with openhab 3..0.0 -> 3.4.0

Unfortunately I did an update and upgrade on openhab 3.4.0 and got stuck with a not working 4.0.0.
Seems to be a problem with Java 17, raspi is booting, openhab is not starting. 
So give me some days to find out what went wrong an I'll come back.
BTW: I do not wish to switch to MQTT, accessing the API via a binding seems to offer more possibilities of integration in the openhab UI.

**Comment by lsiepel** [comment]
The issue link is not working. openHAB 4.0.0 snapshots are very unstable at the moment, the PR has been merged before the 3.4.0 releast, so it would be enough to test 3.4.0.
It saves you from a lot of hassle for 4.0.0

**Comment by chilobo** [comment]
I tried to use my backup of 3.4.0 - didn't work on the installed upgraded 4.0.0-version.
How do I get back?
Install a fresh 3.4.0 and try restoring the backup?

**Comment by lsiepel** [comment]
Hard to give any advice with the available information , but i guess it would be a good idea to install a fresh 3.4.0 and restore your backup.

**Comment by ako-3004** [comment]
https://github.com/lsiepel You can leave this bug open, I will add the binding and test it...

**Comment by chilobo** [comment]
I guess you can close this bug. 
I reinstalled openhab, restored my backup, bundle:list shows 3.4.0 on the GO-eCharger Binding and all the parts I am using seem to work fine.

**Comment by lsiepel** [comment]
Thanks, you can always create a new issue if necessary
