### ISSUE TITLE
Modbus Binding reports wrong data type or has a faulty error message

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab-addons#10814]
When setting

`Thing data mbf_par_filt_mode [ readStart="1041", readValueType="uint8", writeStart="1041", writeValueType="uint8", writeType="holding"]`

it leads to the following error:

"readStart=X.Y must be used with value types less than 16bit!"

This message suggest to use a value type less than 16bit wich is set in the configuration.

When changing the configuration to 

`Thing data mbf_par_filt_mode [ readStart="1041", readValueType="uint16", writeStart="1041", writeValueType="uint16", writeType="holding"]`

the error is gone

**Comment by Rossko57** [comment]
> This message suggest to use a value type less than 16bit wich is set in the configuration.

Well, yes.

You specified 
`readValueType="uint8"`
which is an 8-bit datatype.   Every Modbus holding register is 16-bit.   If you specify register address 1234 that is a 16-bit register; there are two 8-bit bytes available to you.   But the system cannot guess which one you want, so you have to tell it e.g. 1234.0 for the "low" byte or 1234.1 for the "high" byte.
X.Y simply refers to the address notation syntax 1234.0

**Comment by PascalTurbo** [comment]
In this case the message should be more descriptive. The problem in this is: If you don't know much about Modbus Registers and you set valueType to an 8bit type and the message tells you that you should set it lower then 16bit you have no clue about the fault you've made.

**Comment by Rossko57** [comment]
Message
"readStart=X.Y must be used with value types less than 16bit!"
meaning, you have to pay attention to **readStart**, that's the part that you got wrong. (Because you have selected a value type of less than 16-bit.)

What would you like it to say instead?

**Comment by ssalonen** [comment]
> "readStart=X.Y must be used with value types less than 16bit!"

> This message suggest to use a value type less than 16bit wich is set in the configuration.

What the error message tries to tell is that instead of readStart=X (one number) you should have readStart=X.Y (register X and byte Y). This is direct advice to correct the configuration error.

I do not see any bug here, as also discussed above. Naturally any improvements to error messages are most welcome.

@pascalturbo any suggestions for the error message? Otherwise I think this issue should be closed.

**Comment by Rossko57** [comment]
Maybe we can rephrase for clarity

Value types less than 16bit must use readStart=X.Y notation
