### ISSUE TITLE
[enocean] Support Rollershutter Eltako FRM60

### ISSUE THREAD

**Issue by hofingerandi** [openhab/openhab-addons#10816]
I would like to control an Eltako FRM60 enocean rollershutter. The best match seems to be the `A5_3F_7F_EltakoFSB`.
This works for the teach-in process, nevertheless, the move commands are not working.

Looking at `A5_3F_7F_EltakoFSB.java` it turned out, that basically two bytes have to be reversed.
A5_3F_7F_EltakoFSB: 
`
0x00, duration, direction, TeachInBit
` (duration=0..ShutTime[s])

FRM60: 
`
position, 0x00 0x03 (fixed = move to position) 0x08 (=fixed)
` (position=0..200)

Here is the german [documentation of the FRM60](https://github.com/openhab/openhab-addons/files/6604507/FRM60_Dokumentation_OEM.pdf)

Would be great if this could be added.

**Comment by lsiepel** [comment]
If i understand the related PR, this issue is fixed and can be closed? Can you confirm?
