### ISSUE TITLE
[WLED] Sending a color to RGBW setup maxes out white channel

### ISSUE THREAD

**Issue by Rapti** [openhab/openhab-addons#10827]
I'm using WLED with a strip of SK6812 RGBW LEDs.

## Expected Behavior
When I send a color command to the MasterControls or PrimaryColor channel, I expect that color to be sent to WLED. The white channel should only be set when appropriate, or it should be left entirely up to WLED to calculate the white channel based on its own settings.

## Current Behavior
The white LEDs get always get maxed out, except when I send black to MasterControls, in which case everything gets turned off as expected. I tried changing WLED's `Auto-calculate white channel from RGB` setting, but it doesn't seem to affect this issue.

## Possible Solution

I've taken a quick look at the source code. My guess is that `sendWhite()` in `WLEDHandler.java` gets called somewhere down the line when it shouldn't, but I haven't found the cause yet.

## Steps to Reproduce (for Bugs)

1. Install WLED on a compatible microcontroller (D1 Mini in my case)
2. Attach some SK6812 RGBW LEDs
3. Configure WLED accordingly
4. Add it as a Thing using the WLED binding
5. Link a Color item to MasterControls or PrimaryColor and send any HSBType command

## Context
The result is that I can only create white lighting with a small colourful touch instead of real colors. Using WLEDs own UI or calling the XML API manually works as expected, which leads me to believe that this bug is somewhere in the realm of this binding.

## Your Environment
* WLED version: 0.12.0
* Binding version: 3.0.0
* OpenHAB version: 3.0.2

**Comment by Skinah** [comment]
@Rapti 
Now that openHAB 3.1 Stable is released, can you test and see if the issue is still there?

**Comment by Rapti** [comment]
Yes, that fixed it. Thanks!

**Comment by Rapti** [comment]
Yes, that fixed it. Thanks!
