### ISSUE TITLE
[Venstar thermostat] Add more channels to the binding, which are available in the local API

### ISSUE THREAD

**Issue by raveydavies** [openhab/openhab-addons#10823]
Raspberry Pi 4, openHAB 3

The Venstar thermostat local API has functionality which is not currently included in the openHAB binding and I think would be nice to include. Full list is here: https://developer.venstar.com/documentation/

I would focus first on the following:
Fan setting (auto/on)
Fan state (off/on)
Schedule state (disabled /enabled)
Schedule part (5 options)
Runtimes (numbers)
Alerts.

I would like to work on the code for it. This will be a continuation of work done under issue #10707 and PR #10736 where I included thermostat Away Mode (it was my first attempt at doing any openHAB code so I kept it simple and only added a single channel in my first PR).

**Comment by wborn** [comment]
Fixed by #11305
