### ISSUE TITLE
[goecharger] Add some additional status values

### ISSUE THREAD

**Issue by Drazhar** [openhab/openhab-addons#10836]
Hey,

I recently switched from a classic HTTP request to the goecharger binding to collect the data of my goEcharger.
Now the binding only supplies the power values for each phase (nrg[7..9]) and no value for the combined power (nrg[11]). Currently I added 3 items in openhab for each phase and a rule to combine them to the overall power. But in my opinion it would be better to extend the capability of the binding.

I have not so much experience in Java and no experience in developing for Openhab, but I looked at the code and this issue seems quite easy to be fixed. Should I simply give it a shot (create a branch) and push the result? I will of course read the contribution guidelines before...

**Comment by cribskip** [comment]
Hey Drazhar,

to me, thats the right procedure for getting this enhancement done. In the past, many helpful people pointed newbies to the missing bits.

So, happy coding (I'd use your feature too - if my chargers would be here yet) and please don't forget to sign your commits.

Best,
Sascha

**Comment by chilobo** [comment]
The wallbox does deliver this value. I already added it to the binding. It is called powerAll and stems from nrg[11] aka energy[11].
You find my fork at:
https://github.com/openhab/openhab-addons/pull/10903
I am not quite sure why it isn't merged yet.

**Comment by Drazhar** [comment]
Hey @chilobo 

I just added the parameters also in the code. Then I checked on Github and saw, that you have a commit pending :see_no_evil: 
You adjusted more stuff than I did, so it makes more sense, that your fork gets merged. As far as I can tell, you only have to sign off your commit for it to be merged?

**Comment by lsiepel** [comment]
Several PR's have been merged since. Is there still something left or is all ok and can we close this issue?

**Comment by lsiepel** [comment]
The request powerAll channel has allready been added by https://github.com/openhab/openhab-addons/pull/12742
