### ISSUE TITLE
[comfoair] Cannot set target temperature 

### ISSUE THREAD

**Issue by tkuehne71** [openhab/openhab-addons#10876]
This comfoair binding throws an error when I try to set the target temperature. This is new bahavior, it has worked with previous versions of the binding, although I cannot recall if I have seen it work with OH3, but I am sure it worked with OH2.5.

Item definition:
`Number:Temperature Lueftung_Komfortemperatur "Zieltemperatur [%.1f C]"        <temperature> (Lueftung) { channel ="comfoair:comfoair:myComfoAir:temperatures#targetTemperature"}`

Sitemap:
`Setpoint item=Lueftung_Komfortemperatur step=0.5 minValue=15.0 maxValue=25.0`

bundle:list:
`232 │ Active │  80 │ 3.0.2                   │ openHAB Add-ons :: Bundles :: ComfoAir Binding`

The error that I'm getting when manipulating the temperature via the UI:

`2021-06-17 08:51:59.245 [WARN ] [ng.comfoair.internal.ComfoAirHandler] - Unhandled command type: 15 C, channelId: temperatures#targetTemperature`

**Comment by Rossko57** [comment]
> Number:Temperature

That's a Quantity type, with Units of Measurement.

>[%.1f C]

Unless there's some character set display/copy/paste issue here, C is not a valid Temperature unit.
°C would be okay.

> Unhandled command type: 15 C

I'm surprised it doesn't throw other problems as well.

**Comment by tkuehne71** [comment]
Indeed, changing the item definition to include [%.1f °C] solved the issue. I would never have throught to look for the solution there, since i always thought that this is only relevant for the UI. Good to know for the future!

**Comment by Rossko57** [comment]
> i always thought that this is only relevant for the UI.

They sort of hijacked/repurposed this display attribute when adding Units to OH2, for additional service as a default unit, rather than add some new units field to Item.  Partly, the expectation is that units can come from the binding - and then no default is necessary.
