### ISSUE TITLE
InfluxDB v2 historic data are broken

### ISSUE THREAD

**Issue by t2000** [openhab/openhab-addons#10887]
Similar to
https://github.com/openhab/openhab-addons/issues/10464

I experience the same error:

```
[INFO ] [b.internal.InfluxDBStateConvertUtils] - Could not find item 'null' in registry
```

when using influxdb in version 2.

Some debugging later I found that https://github.com/openhab/openhab-addons/pull/10680 has only fixed the issue for version 1 of influxdb, why?

I will provide a fix for it.

**Comment by timo12357** [comment]
Using
OH 3.4.2
Influxdb 2

I get a bunch of these errors with my install.
 [b.internal.InfluxDBStateConvertUtils] - Could not find item " xxx " in registry.
