### ISSUE TITLE
[iCalendar] Command Tags not working for Google Calendar

### ISSUE THREAD

**Issue by Kilrath** [openhab/openhab-addons#10899]
I am pulling an ical calendar from Google Calendar and from the iCalendar bridge binding channels, it is pulling events correctly, but no actions are performed. The descriptions look like this:

BEGIN:ThermostatTargetTemperature_Heat:62:abc
END:ThermostatTargetTemperature_Heat:67:abc

I have tried with and without an Authorization Code.

Workaround (should be mentioned in the documentation):
In Google Calendar it is necessary to remove the HTML format
![Screenshot 2021-02-12 111546](https://user-images.githubusercontent.com/30173601/123056056-cbdbbd00-d406-11eb-8ebf-69d38ef29e85.jpg)

**Comment by daMihe** [comment]
This is nothing specific to the iCalendar binding. If you want, post this behavior of Google calendar to a thread in the forum.
