### ISSUE TITLE
[homeconnect] Selected program not set at startup when program state is finished

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#10904]
If you start the binding while the current state of the program is "finished", the "selected program" channel is not set.
This is apparently linked to the fact the binding tries to retrieve the available options for this program and it fails (code 409 - Request cannot be performed in the current operation state) when the program is in this state. This leads to multiple calls.
![image](https://user-images.githubusercontent.com/10186704/123537104-1ffbdf80-d72e-11eb-977a-5631ba09560a.png)
The channel should be set even if retrieving of program options is not yet possible.
The result would be certainly the same if the program state was "running".

**Comment by lolodomo** [comment]
@bruestel : this is a problem with exception not being caught.
I see several cases in AbstractHomeConnectThingHandler where no exception is caught when calling the REST API. Was there a logic in that ?

**Comment by bruestel** [comment]
Exceptions should be caught at any time. There is an exception when executing OH commands. Errors are only logged here.

Can you tell me which part you mean exactly. I'll have a look at it.

**Comment by lolodomo** [comment]
The exception not caught in my case is certainly this one:

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java#L1471

But you have a lot of other examples where catching exception seems to be missing too, like for example:

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.homeconnect/src/main/java/org/openhab/binding/homeconnect/internal/handler/AbstractHomeConnectThingHandler.java#L972

**Comment by lolodomo** [comment]
In fact, exceptions are caught in method `updateChannel`.
But it sometimes should be done a deeper level to not break the channel update.

**Comment by lolodomo** [comment]
I am working on a patch.

**Comment by lolodomo** [comment]
@bruestel : I finally found only 3 places (methods) requiring an additional exception catching.

The uncaught exception was also the cause of the repeated calls (for each channel) as the cache was not filled.

**Comment by lolodomo** [comment]
Unfortunately, when the program state is updated, there is no retry to load the program options. They will be loaded only when the program is updated. Something else to improve.

**Comment by lolodomo** [comment]
> The result would be certainly the same if the program state was "running".

In fact, it is not. The request succeeded while the program is running but I discovered that not all options are returned. I got the available spin speeds but not the available washing temperatures. I guess this is because you cannot change the washing temperature while the program is started but you can still adjust the spin speed (when you are at the beginning of the program).

This could lead to incomplete options being cached by the binding. Maybe we should cache the result only if all expected options are returned.

**Comment by lolodomo** [comment]
> Maybe we should cache the result only if all expected options are returned.

This enhancement is now included in my PR.

**Comment by bruestel** [comment]
Thank you for your PR. LGTM.

> In fact, it is not. The request succeeded while the program is running but I discovered that not all options are returned. I got the available spin speeds but not the available washing temperatures. I guess this is because you cannot change the washing temperature while the program is started but you can still adjust the spin speed (when you are at the beginning of the program).

I like how you solved this.
