### ISSUE TITLE
MCP23017 Binding doesn't work

### ISSUE THREAD

**Issue by CrysK** [openhab/openhab-addons#10911]
OH 3.0.2
Java 11.0.11
Pi4J 1.4

When using OpenHAB I get initializing errors, like here: https://community.openhab.org/t/mcp23017-on-openhab-3-0/110992/10
`[INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'mcp23017:mcp23017:chipA' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): sun/misc/SharedSecrets`

On command line (with i2cdetect, ...) everything is fine.

**Comment by wborn** [comment]
Try upgrading to OH 3.1 which was [released today](https://community.openhab.org/t/openhab-3-1-is-here/124013?u=wborn).
It should be fixed in that version, see https://github.com/openhab/openhab-addons/issues/9503, https://github.com/openhab/openhab-addons/pull/10293.
