### ISSUE TITLE
[tr064] Add current downstream/upstream rates for FritzBox

### ISSUE THREAD

**Issue by BobSilent** [openhab/openhab-addons#10919]
Please provide the information of current downstream and upstream rates in channels

**Comment by hmerk** [comment]
You should read the binding documentation, those channels already exist on the WAN subdevice.
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.tr064

**Comment by J-N-K** [comment]
See  my comment in the other issue. There is a misleading naming in what is shown.

**Comment by BobSilent** [comment]
@hmerk if you refer to: 
- `dslDownstreamCurrRate`
- `dslUpstreamCurrRate`

maybe I need to be more precise here, I do not have a DSL connection.
I have cable so these values are simply `UNDEF` for me, like all channels prefixed with DSL.
currently i only have these channels:
| channel                    | item-type                 | advanced | description                                                    |
|----------------------------|---------------------------|:--------:|----------------------------------------------------------------|
| `wanMaxDownstreamRate`     | `Number:DataTransferRate` |     x    | Max. Downstream Rate                                           |
| `wanMaxUpstreamRate`       | `Number:DataTransferRate` |     x    | Max. Upstream Rate                                             |
| `wanTotalBytesReceived`    | `Number:DataAmount`       |     x    | Total Bytes Received                                           |
| `wanTotalBytesSent`        | `Number:DataAmount`       |     x    | Total Bytes Sent                                               |

the first two show my maximum Down and Upstream Rate, which is always the same and does not change.
so it only shows me more or less: "connected" or "not connected".

So I only have the Total bytes send/received. It would be really helpful if the binding could calculate the down and upstream rates

@J-N-K if you refer to [this comment](https://github.com/openhab/openhab-addons/issues/10287#issuecomment-873595035): you are absolutely right. if this is a duplicate of #10287 i am fine with it, but on a first read i was not sure it means the same as i tried to request here.

**Comment by lsiepel** [comment]
@J-N-K in the other issue you said the requested information is not available from the device. Can i assume that is also the case for this issue? If so we can close this issue as not possible.

**Comment by J-N-K** [comment]
I did say it's not readily available from the API. I didn't say it's impossible to implement. In fact it is possible and available outside of openHAB.
