### ISSUE TITLE
[sonos] Send voice-command to Sonos

### ISSUE THREAD

**Issue by TomMarg** [openhab/openhab-addons#10920]
Feature request for the Sonos binding. 
Is it possible to add a channel to the devices to send voice-commands to them?

E.g. 
- I am currently replacing my Amazon Echo Speakers with Sonos speakers that have microphones.
- I am controlling some devices (e.g. smart lights) through voice commands to the Echo speakers because they do not have OpenHAB bindings. (e.g. "Alexa, turn off Tuya-Light-in-Kitchen" sent to the Echo binding performs the action).

Since the Sonos boxes have microphones and can be connected to Google or Alexa I'd love to have that channel available to send voice commands (as strings) to them. I know the trigger is not 100% reliable but it makes life easier.

**Comment by lolodomo** [comment]
No idea if it is possible but I doubt. 
You should check if your Sonos device exposes an UPnP service / action for that.

**Comment by TomMarg** [comment]
Ah. My bad. I guess I looked at it from the wrong perspective. 
Maybe it's more a job for the AmazonEchoControl binding that recognizes the Sonos box through the Amazon-Account somehow should be able to talk to it. Will need further research before I can find out if this might be already in....
