### ISSUE TITLE
[Automower] Binding does not connect

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#10943]
The Bridge thing is showing the following error.
![image](https://user-images.githubusercontent.com/40339145/124464964-1d843000-dd95-11eb-8c53-b357c2a7e9e4.png)

but reading the lof file shows that th problem starts earlier.
![image](https://user-images.githubusercontent.com/40339145/124465084-46a4c080-dd95-11eb-9556-4d1b53b5ab30.png)

This shows that the connection process is not working right

There are several Posts about this problem.

https://community.openhab.org/t/automower-binding-g2/2854/80?u=dibbler42

**Comment by TimmiORG** [comment]
Hi @TBail 
how did you configure the bridge?
I had the same issue and just renamed the bridge from automower:bridge:mybridge to something like automower:bridge:husqvarna and it started to connect.

Regards
Christoph

**Comment by TBail** [comment]
@TimmiORG Thanks for you advice. The uuis is typically auto created by openhAB and the label of all my Bridges starts with "Bridge" and the something.

Just tried to install the binding again and created the Bridge with default label and it goes online. After that i could rename it to "Bridge Automower Connect Bridge" and it is still online. Will have an eye on that.

But now my new bbq is delivered ....

**Comment by svenschreier** [comment]
It seemed that the Husqvarna-API has changed from username and password to an application-secret for authentication.

https://developer.husqvarnagroup.cloud/apis/authentication-api#readme

**Comment by crnjan** [comment]
@TBail - there were some changes done related to Husqvarna Authentication API change, please check latest 3.4 #3051 build (or later) and let me know if this issue is still reproducible, thank you!

**Comment by crnjan** [comment]
Binding seems to work reliable for last couple of months (at least after API changed), also haven't seen any report of above mentioned issue on forum, therefore closing. Please reopen in case it pops up again.
