### ISSUE TITLE
[irobot] Test unstable

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-addons#10954]
The test org.openhab.binding.irobot.internal.handler.RoombaHandlerTest.testDock is unstable:
```
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 

Unnecessary stubbings detected.
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at org.openhab.binding.irobot.internal.handler.RoombaHandlerTest.setUp(RoombaHandlerTest.java:78)
Please remove unnecessary stubbings or use 'lenient' strictness. More info: javadoc for UnnecessaryStubbingException class.
```

@rimago can you take a look?

Does the test make any sense as it contains no assertions nor `verify()`s?

**Comment by rimago** [comment]
It is used to test the protocol against a local iRobot instance. 
We did not add any assertions or verify's that it also runs if there is no local iRobot instance.

So in this way it is not a real Unity test, yet it is still useful to share the code. I am open to any suggestions if there is a better way to handle this.

To fix the Exception we could simply add a lenient() in line 78. If this is fine for you I could create a pull request for it.

**Comment by fwolter** [comment]
Sure, go ahead.
