### ISSUE TITLE
Timers stop working after some, only restart helps

### ISSUE THREAD

**Issue by SinisterOH** [openhab/openhab-addons#10963]
## Expected Behavior
Timers should execute command after specified time, in my case turn off lights when no motion is detected.

## Current Behavior

After few days, timers stop working and don't execute commands after specified time - in my case, they don't turn off lights.
I need to do a complete reboot of Raspberry Pi to make it work again.

## Steps to Reproduce (for Bugs)

1. Configure times on an item
2. Wait few days
3. ...
4. Times no longer work

## Context

Times are turning off lights (KNX binding) in the rooms ( for example garage) there is no motion (Satel binding) for 3 minutes.  

## Your Environment

* Version used: OpenHab 3.1

* Operating System and version RaspberryPi 4, Openhabian

**Comment by Rossko57** [comment]
This is I think "working as designed" as discussed in community thread
https://community.openhab.org/t/timer-doesnt-work-if-time-is-greater-than-59-seconds/124402
