### ISSUE TITLE
[denonmarantz]HTTP Broken in OH3.1 & 3.2 M1-3

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-addons#10962]
HTTP bi-directional communication with DenonMarantz AVRs appears to be broken in OH3.1  Several others have reported the same issues in the community forums.  ( https://community.openhab.org/t/denonmarantz-binding-broken-after-update-to-oh3-1/124275 ) The AVR is controllable from OH3.1 using HTTP but feedback such as current volume, power status, etc is not updated.  Further if changes are made using the AVR or another remote, changes are not reflected in OH3.1.  Telnet works mostly, but is limited to a single connection and has otherwise more limited functionality.

I have tried removing the AVR.thing and rediscovering using the binding.  This works fine as the AVR is auto discovered, but no change in behavior.

**Comment by lolodomo** [comment]
Closed in favor of #11502 which contains logs and a first analysis.
