### ISSUE TITLE
[netatmo] switch to enable/disable push notifications

### ISSUE THREAD

**Issue by MrMontesa** [openhab/openhab-addons#10974]
Hey Devs,
I just bought a Netatmo Outdoor cam and integration works nice so far. One thing I found to missing is the possibility to enable/disable the phone notifications via Openhab.
This is my use-case:
Generally, I only want to receive phone notifications while being away. Thus would be cool to be able to enable and disable the notifications via rule.
Via Netatmo WebGUI these are the settings one can set. Its a switch Called "all day notifications" one can set on/off. In case its turned OFF; the hours below (from/to) are used to send notifications. My current setting is to only send push notifications at night time, but would be cool to set them based on other states in openhab. E.g alarm_system.
![2021-07-11 15_13_51-Netatmo](https://user-images.githubusercontent.com/600125/125196887-d77b1080-e25b-11eb-8397-2c10863db8e0.png)
![2021-07-11 15_14_09-Netatmo](https://user-images.githubusercontent.com/600125/125196890-d944d400-e25b-11eb-818a-1ac7b9f0fdbc.png)

let me know if you have any questions, or I can be of any help implementing this. Unfortunatly, I'm not a dev to code it myself.
Thanks much

**Comment by mdillmann** [comment]
Hi,
the notifications are controlled by local settings of the app on your phone. The Netatmo-API would only allow (unofficially) to switch off the camera - this would affect all users allowed access to it.
The only thing that would come close to your usecase is buying an indoor camera as well.

**Comment by MrMontesa** [comment]
Hey,
thanks for your feedback. I'm currently investigating a different option. I setup rules based on the cameraEvent channel trigger to then send a telegram action containing an image from the CameraLivePictureUrl.
But its quite delayed. As soon as the channel is triggered, the image does not contain the thing triggering any longer.
So I'm investigating the webhook option currently which is supposed to be faster. Is there any documentation beside the 3 sentences on the official binding docu?
Thanks much.

**Comment by lolodomo** [comment]
This can be closed considering @mdillmann good explanation.
