### ISSUE TITLE
[hpprinter] Samsung CLX3305N discovery fails

### ISSUE THREAD

**Issue by learnlinuxnow** [openhab/openhab-addons#10994]
After installing the HP Printer Addon no discovery for CLX3305N networkprinter is possible.

Even if i enter the correct IP of the device. Ping is possible on IP and device name from raspberry pi where open hab is running on.

pi@pi:~ $ ping CLX3305N
PING CLX3305N.home.de(192.168.20.5) 56(84) bytes of data.
64 bytes from CLX3305N.home.de (192.168.20.5): icmp_seq=1 ttl=63 time=2.18 ms
64 bytes from CLX3305N.home.de (192.168.20.5): icmp_seq=2 ttl=63 time=10.2 ms
64 bytes from CLX3305N.home.de (192.168.20.5): icmp_seq=3 ttl=63 time=0.913 ms
64 bytes from CLX3305N.home.de (192.168.20.5): icmp_seq=4 ttl=63 time=1.01 ms
^C
--- CLX3305N.home.de ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 7ms
rtt min/avg/max/mdev = 0.913/3.567/10.168/3.843 ms
pi@pi:~ $ ping 192.168.20.5
PING 192.168.20.5 (192.168.20.5) 56(84) bytes of data.
64 bytes from 192.168.20.5: icmp_seq=1 ttl=63 time=1.30 ms
64 bytes from 192.168.20.5: icmp_seq=2 ttl=63 time=1.02 ms
64 bytes from 192.168.20.5: icmp_seq=3 ttl=63 time=0.925 ms
^C
--- 192.168.20.5 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 5ms
rtt min/avg/max/mdev = 0.925/1.081/1.302/0.164 ms

## Expected Behavior

Thing shall go online and provide @ least some of the stats mentioned in binding description.

## Current Behavior

Binding does not connects even the device

## Possible Solution
Clarification if ths printer is supported by binding, as right the support is coming from HP since HP bought Samsungs Printer Segment

See https://support.hp.com/de-de/drivers/selfservice/samsung-clx-3305-color-laser-multifunction-printer-series/17156918

## Steps to Reproduce (for Bugs)

1. Install HP Printer Binding
2. Configure Thing "CLX3305N" from paper UI
3. Enter IPv4 Address of printer/ HostName
4. Thing is created but stays offline

## Your Environment

openHAB 3.1.0        Release Build
OS                           Raspbian Buster
HW                          raspberry pi 4b+ 4GB Ram

**Comment by lsiepel** [comment]
@learnlinuxnow i don't know if the Samsung device is supported. The binding readme links to HP website for compatible devices. 
I assume this device is not supported as it was allready designed by a different brand (and thus software support/framework). So, did you ever get this working?
