### ISSUE TITLE
[influxdb] Bug in the ui generated influxdb.config file

### ISSUE THREAD

**Issue by carsoni** [openhab/openhab-addons#11006]
`/var/lib/openhab/config/org/openhab/influxdb.config`

The retention policy key in the above file has a misspelling

it should read "retentionPolicy" but it instead reads "retentionpolicy"

This creates a masked bug by which those of us using /etc/openhab/services/influxdb.cfg can never get the retention policy field to get picked up correctly.

A side effect to this is that changes made in the UI for this field are never made permanent as the field in the UI always reverts to "autogen" even after changing and saving.

**Comment by lujop** [comment]
Did you use a current version of the addon?
I've just checked mine and I have the `retentionPolicy` value

**Comment by florian-h05** [comment]
I‘ve just checked this on a fresh openHAB 4.0.0 SNAPSHOT `Build #3255` install and the file has the correct `rententionPolicy` value.
