### ISSUE TITLE
[MIIO] Roborock S7 - Historical Cleaning Data isn't correct

### ISSUE THREAD

**Issue by derSchweiger** [openhab/openhab-addons#11001]
The historical data for my Roborock S7 doesn't work. The response of the API call "CLEAN_SUMMARY_GET" might respond in a different manner than expected and the binding is not able to parse them accordingly. The values of all items only display NULL.

## Expected Behavior
The values of the corresponding items should show the historical data.

## Current Behavior
All "history" and "last cleaning details" items do not show any data except NULL
- history#total_clean_area
- history#total_clean_time
- history#total_clean_count
- cleaning#last_clean_start_time
- cleaning#last_clean_end_time
- cleaning#last_clean_area
- cleaning#last_clean_duration
- cleaning#last_clean_error
- cleaning#last_clean_finish

Debug log for the corresponding API call "CLEAN_SUMMARY_GET":
`CLEAN_SUMMARY_GET, result: {"clean_time":38629,"clean_area":650425000,"clean_count":68,"dust_collection_count":0,"records":[1626292843,1626260657,1626255012,1626206412,1626174164,1626168621,1626036597,1626036415,1626035701,1626035555,1626033643,1626028227,1626021936,1626021732,1626021575,1626020891,1626020332,1626019286,1626019207,1626019147]}, fullresponse: {"id":5018,"result":{"clean_time":38629,"clean_area":650425000,"clean_count":68,"dust_collection_count":0,"records":[1626292843,1626260657,1626255012,1626206412,1626174164,1626168621,1626036597,1626036415,1626035701,1626035555,1626033643,1626028227,1626021936,1626021732,1626021575,1626020891,1626020332,1626019286,1626019207,1626019147]},"exe_time":100}`

## Your Environment

* Version used: openHab v3.1
* Based on Docker
* Vacuum cleaner: Xiaomi Roborock S7 (roborock.vacuum.a15, firmwareVersion: 4.1.2_1140)

**Comment by lsiepel** [comment]
@marcelrv is this something you might look at?

**Comment by ZE135** [comment]
Hello all. I do have same problem with my Roborock Q7Max. Does anybody have an idea, how to receive the above mentioned items?

**Comment by marcelrv** [comment]
Can you maybe test the version I posted here to see it if now works fine.

I'm esp interested in the debug logging of the next step (the clean record bit) as that is not 100% clear to me how that is formatted for the newer robots. (pls share debug log of the refresh, note: it only refreshes once per cleaning or when binding is restarted)


https://community.openhab.org/t/miio-and-yeelight-rgb-bulbs-behavior/135788/8?u=marcel_verpaalen
