### ISSUE TITLE
[pulseaudio] Unused config file

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#11020]
@peuter : I think the file config.xml is useless. It defines a config with URI "binding:pulseaudio" which is then never used.
Can you please confirm that I am not missing something ?

**Comment by dalgwen** [comment]
What/where is this config file ?
Despite I'm using the pulseaudio binding, I don't find it on neither my main system, nor my dev environment.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.pulseaudio/src/main/resources/OH-INF/config

**Comment by dalgwen** [comment]
Oh sorry, I don't understand how I could have missed it.
Indeed it seems useless.
I just build and test the bundle without it, and it ran fine.

**Comment by lolodomo** [comment]
The config is finally useful  it is the binding config.
