### ISSUE TITLE
[gpio] lost connection is never detected/recovered

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#11038]
If the connection to pigpiod is lost (for example, if running remotely and I reboot my pi), the Thing keeps saying "online", but commands just no longer work. I have to manually Disable and Enable the thing, and then it works fine.

## Expected Behavior
When the connection to pigpiod is lost, the thing should go offline. It should automatically periodically attempt to reconnect, so that as soon as the pi comes back up, the connection is restored.

## Your Environment
openHAB 3.1.0 on ubuntu; pigpio on Raspbian Buster on a Pi 2 and a Pi 4

**Comment by jeremyrumpf** [comment]
Would you be able to test some changes I have made to the GPIO binding? I planed on using the binding to monitor some sensors in a building. I came across a lot of the same issues you are having. The biggest being that the binding does not reconnect to pigpiod. In my changes, there is now a heart beat configuration to poll pigpiod. If pigpiod goes away, a reconnect will be attempted at the heart beat frequency. The binding also properly reports when its state goes OFFLINE with a COMMUNICATION_ERROR and goes back ONLINE once pigpiod is reconnected.

Also, the binding features actions that it will perform based upon the pigpiod connection state. One of them is issuing a REFRESH on the channel to sync with the state of the GPIO pin. I saw you had another bug open for this.

If I can find at least one other person to validate my code, I will create a pull request for 3.3.0-SNAPSHOT. I created a build at: [https://github.com/jeremyrumpf/jeremyrumpf/blob/main/files/org.openhab.binding.gpio-3.3.0-SNAPSHOT.jar](url) To use it, you would have to uninstall the binding in OpenHAB (if you used the UI to install it) and add that jar file to /usr/share/openhab/addons

The code is at: [https://github.com/jeremyrumpf/openhab-addons/tree/main/bundles/org.openhab.binding.gpio](url)

Regards,
Jeremy

**Comment by jeremyrumpf** [comment]
I should also report the Java version I used: 

`openjdk 11.0.14 2022-01-18 LTS`
`OpenJDK Runtime Environment 18.9 (build 11.0.14+9-LTS)`

**Comment by ccutrer** [comment]
I actually can't. I stopped using the binding and wrote a daemon that runs on the pi and connects to MQTT (using Homie convention) to interact with OpenHAB: https://github.com/ccutrer/ruby-pigpiod. Things have been far more reliable since I did that.

**Comment by jeremyrumpf** [comment]
No worries. I agree the gpio binding isn't very reliable in its current state. Glad you found a solution!
