### ISSUE TITLE
[deconz] Hue/Saturation Conversions incorrect.

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-addons#11031]
## Expected Behavior

Updating a new Hue light (with the latest firmware) with the following command:

```
events.sendCommand("LivingRoom_TVBacklight_Colour", "0,100,33");
```

Should turn the Hue colorbulbs to red with full saturation at 33% brightness and the deconz rest API should return:

```
"state": {
    "alert": "none",
    "bri": 83,
    "colormode": "xy",
    "ct": 153,
    "effect": "none",
    "hue": 0,
    "on": true,
    "reachable": true,
    "sat": 254,
    "xy": [
      0.6915,
      0.3083
    ]
  }
```

## Current Behavior

The openHAB logs acknowledge the correct value being set in openHAB which is percent type saturation and brightness:

```
2021-07-20 01:03:06.113 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'LivingRoom_TVBacklight_Colour' changed from 0,100,36 to 0,100,33
```

However the bulb is visibly less saturated and at a different hue than it should be. The deCONZ API reports:

```
"state": {
    "alert": "none",
    "bri": 83,
    "colormode": "xy",
    "ct": 153,
    "effect": "none",
    "hue": 1032,
    "on": true,
    "reachable": true,
    "sat": 228,
    "xy": [
      0.6402,
      0.3299
    ]
  }
```

Note that `state.hue`, `state.sat` and `state.xy` are quite a way out. If the colour is changed via Hue bluetooth or through the deconz app, the blub shows the correct colour and openHAB reports the same three values for HSB (i.e. `0,100,33`)

## Possible Solution
It looks like openHAB isn't converting between HSB and the values required by the deconz API. Hue should convert from 0-360 to 0-65535 and saturation should covert from 0-100 to 0-255

## Steps to Reproduce (for Bugs)
1. Use the rule above to change the light to deep red
2. Read the state of the bulb using the deconz REST API - (`/api/<API_KEY>/lights/<light_ID>`)
3. Change the bulb colour using any method other than openHAB
4. Read the state of the bulb again

## Context
This happens with all my colour lights, all of which are Extended Colour Phillips Hue of different types (strip lights or standard bulbs) but with the latest firmware.

## Your Environment

* Version used: openHAB 3.2.0-SNAPSHOT (build <span>#</span>2453) (current as of 19/07/21)
* Java Environment: OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
* deCONZ environment: Version 2.12.03, Firmware  0x266F0700
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 21.04 arm64 on a Raspberry Pi 4

**Comment by J-N-K** [comment]
The binding used the openhab-core methods for converting hsb to xy (as does the hue binding). 

I'm not an expert on these color things, but it seems there are different colorspaces which need different conversions: https://community.openhab.org/t/solved-convert-hsbtype-to-cie-xy-needed-for-ikea-tradfri-control-through-deconz-rest/48825/12

**Comment by cweitkamp** [comment]
The observed behavior might be caused by a similar reason like described in https://github.com/openhab/openhab-addons/issues/10159 for IKEA CWS bulbs controlled by hue binding. Currently if a bulb is in CT color mode the binding will send hue/sat/bri command which is not applicable for IKEA bulbs because we only send my/bri if the current color mode is XY. Thus we changed the default behavior of the hue binding to preferr XY values over HSB unless a Bild is in HS color mode (see https://github.com/openhab/openhab-addons/pull/10608).

**Comment by BClark09** [comment]
Thanks @J-N-K and @cweitkamp,

From https://github.com/openhab/openhab-addons/blob/487dc0e49fb83282dc77d823869945d706ca1d19/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java#L213-L225 it looks like the default should be changed here too?

I'm not confident that it will solve this particular problem, in the test case above `state.colormode` is `xy` from the deCONZ api before I try to send a command with openHAB.

As @J-N-K said, the actual conversion happens in openhab-core for a specific gamma "compression", but wouldn't this mean that I would experience the same behavior if I were to use the Hue bridge and binding, then use the same rule to set the light red?

[A Hue application note for XY Color conversion](https://github.com/PhilipsHue/PhilipsHueSDK-iOS-OSX/blob/00187a3db88dedd640f5ddfa8a474458dff4e1db/ApplicationDesignNotes/RGB%20to%20xy%20Color%20conversion.md) uses different matrix coeficients than: [openhab-core's implementation](https://github.com/openhab/openhab-core/blob/79edf2b9e643ad802c31b2e5f54edb93534277fd/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java#L58-L60). Which uses the same values as found in https://en.wikipedia.org/wiki/SRGB#The_reverse_transformation_(sRGB_to_CIE_XYZ).

**Comment by cweitkamp** [comment]
> should be changed here too?

Yes, I think so. I proposed https://github.com/openhab/openhab-addons/pull/11036

I agree on that this PR will not solve your issue. Reading the linked pages I came to the following thoughts. First we need a way to use different matrix coefficients to convert RGB values to XY. This can be done in OHC by extending the `RawType` method. Second we need to change bindings like Hue or deCONZ to consider different color gamut for different lights. According to https://developers.meethue.com/develop/hue-api/supported-devices/ Hue lights support three different color gamuts.

A quick check on my Hue API shows me that we get the supported color gamut type and the color gamut specification itself in the response. Something like this:

```JSON
...
                "colorgamuttype": "C",
                "colorgamut": [
                    [
                        0.6915,
                        0.3083
                    ],
                    [
                        0.1700,
                        0.7000
                    ],
                    [
                        0.1532,
                        0.0475
                    ]
                ],
...
```

Unfortunately those are not available on deCONZ REST API.

**Comment by J-N-K** [comment]
I'll check with the deconz Team if the API can be extended.

**Comment by BClark09** [comment]
Thanks again @cweitkamp and @J-N-K,

> First we need a way to use different matrix coefficients to convert RGB values to XY. This can be done in OHC by extending the RawType method. Second we need to change bindings like Hue or deCONZ to consider different color gamut for different lights

Sounds good to me, being able to select the appropriate matrix manually in the thing's configuration would be a good first implementation, shall I create an issue on OHC?
