### ISSUE TITLE
[gpio] gpio state is cycled and set to opposite of default when thing is enabled

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#11039]
When I disable and then re-enable my pigpio-remote thing (in order to cause it to reconnect), my GPIOs on the Pi (controlling a large bank of relays) flip around for a second, and then are left in a state that is both opposite of the GPIO's state before connecting, and opposite of the state of the Switch Item that the channels are currently tied to. This is true for GPIOs configured as both Invert and not Invert.

## Expected Behavior
Previous state should be preserved, whether that be the prior state of the GPIO ignoring the openhab state of any linked items (and should probably update the linked items immediately), or immediately sending a command to pigpiod to match the GPIO's state to the state of a linked item.

## Current Behavior
Whenever I reconnect to pigpiod, I have to go through each item linked to a GPIO and flip it twice (on then off, or off then on) in order to reset the GPIO's state to what it should be. Note that I've only tested with the prior state of items as being 0 from the GPIO's perspective. So it's possible that it's not that it's inverting the state, but that it's always setting the GPIO to 1.

## Your Environment
openHAB 3.1.0 on ubuntu
pigpio on Raspbian Buster on a pi 2 and a pi 4

**Comment by ccutrer** [comment]
in the meantime, I'm working around this with a rule:


```
rule "reset GPIO states"
when
  Thing "gpio:pigpio-remote:pi" changed to ONLINE
then
  gGPIOs.members.forEach [ SwitchItem i|
    i.sendCommand(i.state.toString)
  ]
end
```

**Comment by lsiepel** [comment]
@ccutrer this might be improved/fixed by https://github.com/openhab/openhab-addons/pull/13643 Can you verify from the next snapshot / milestone (4.1)
