### ISSUE TITLE
[coronastats] problem with channel today_cases

### ISSUE THREAD

**Issue by dvehof** [openhab/openhab-addons#11042]
## Expected Behavior
today_cases should show value of column "New Cases" from homepage

## Current Behavior
channel today_cases seems to show value from channel today_deaths (just tested for countryCode DE)

## Possible Solution
-

## Steps to Reproduce (for Bugs)
Use a thing:
    Thing country germany "Corona Stats Germany" @ "Corona" [countryCode="DE"]
and an item with the channel "today_cases".

## Context
-

## Your Environment
* Version used: Openhab 3.1 and addons 3.1
* Environment name and version : OpenJDK 11
* Operating System and version : openHABian

**Comment by lsiepel** [comment]
As these stats are hardly updated anymore, it might be no longer relevant.

Anyway, i tried to reproduce, but with new New Zealand (NZ) the website and channel today_cases match. I also had a quick look at the code and i think it either was a configuration error or some other glitch.
