### ISSUE TITLE
[telegram] Update chat id before message text and other channels

### ISSUE THREAD

**Issue by valpackett** [openhab/openhab-addons#11048]
## Expected Behavior
In a "LastMessageText was updated to /something" rule, the script should be able to run something like `sendTelegram(Long::parseLong(TelegramBot_ChatId.state.toString), …)` and that should send the message to the chat where the command came from.

## Current Behavior

ChatId is updated *after* LastMessageText:
https://github.com/openhab/openhab-addons/blob/487dc0e49fb83282dc77d823869945d706ca1d19/bundles/org.openhab.binding.telegram/src/main/java/org/openhab/binding/telegram/internal/TelegramHandler.java#L327-L340

So when the last chat changes, one message goes to the wrong chat.

## Possible Solution

Reorder these lines of code?

**Comment by Skinah** [comment]
Yes I agree that makes sense to reorder them. 

CHATID and REPLYID should be updated first with LASTMESSAGETEXT being second last, and LASTMESSAGEDATE being the very last. Reasoning is that the LASTMESSAGETEXT may be the same for multiple messages in a row (?) and some people may trigger rules based off when LASTMESSAGEDATE changes.

How does that sound as I am not yet sending two way messages on my system.

**Comment by Skinah** [comment]
Change has been made. Trying it out on my system for a few days and then will make a PR.

Jar to try can be downloaded from http://pcmus.com/openhab/telegram/
