### ISSUE TITLE
[influxdb][rrd4j] changedSince does not work for switch item with persistence influxdb and rrd4j

### ISSUE THREAD

**Issue by dvehof** [openhab/openhab-addons#11041]
## Expected Behavior
If I use "changedSince" for a Switch that changed from OFF to ON or ON to OFF I expect the changedSince to return "true".
If the item did not change it should return "false"

## Current Behavior
For influxdb and rrd4j the "changedSince" always return "true". 
I assume it happens, because influxdb and rrd4j store a numeric value (0/1) and the item state is ON/OFF. 

EDIT: It also does not work for Number items (I expected it to work in my initial post, my test was wrong.).

## Possible Solution
unknown

## Steps to Reproduce (for Bugs)
Use a Switch item with influxdb or rrd4j and try "changedSince" in a rule.

## Context
I assume the behaviour of "changedSince" (and maybe updatedSince?) as a bug for Switch (and maybe Contact) items.

## Your Environment
* Version used: 3.1 release for openhab and addons
* Environment: OpenJDK 11
* Operating System and version: openHABian

**Comment by lujop** [comment]
I've just tried and I can't reproduce.
I get true or false as expected changing the since time.

The way the item is stored it must not affect since the persistence service has the responsibility to return the Historic item as an state value in the expected way for the item.

Can you check the queries that are executed and run them manually in the DB?

**Comment by lolodomo** [comment]
@dvehof : can you provide a feedback or us your problem fixed?

**Comment by J-N-K** [comment]
Probably fixed by https://github.com/openhab/openhab-core/pull/3348, if not, still a core issue, not an add-ons issue if several persistence add-ons are affected.
