### ISSUE TITLE
[MIIO] add dmaker.fan.p18 support

### ISSUE THREAD

**Issue by oOWaXOo** [openhab/openhab-addons#11053]
## Support is missing for dmaker.fan.p18
* [https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p18:1](url)

`modelId:
dmaker.fan.p18`
`vendor: Xiaomi` 
`wifiFirmware: 2709610`
`hardwareVersion: esp8266`
`firmwareVersion: 2.0.7`

**Comment by marcelrv** [comment]
Will check for you when back from holidays

**Comment by marcelrv** [comment]
[dmaker.fan.p18-miot.json.txt](https://github.com/openhab/openhab-addons/files/6961795/dmaker.fan.p18-miot.json.txt)
please try attached json file, let me know if all channels work properly.

see binding readme on how to use the local json files

**Comment by oOWaXOo** [comment]
> [dmaker.fan.p18-miot.json.txt](https://github.com/openhab/openhab-addons/files/6961795/dmaker.fan.p18-miot.json.txt)
> please try attached json file, let me know if all channels work properly.
> 
> see binding readme on how to use the local json files. note, remove .txt extension


I tested the provided JSON file. Everything implemented works so far. But one setting option is missing. Further information you'll find below.
**What i tested:**

- [x] Autodiscovery
- [x] SSID
- [x] BSSID
- [x] RSSID
- [x] Life
- [x] Fan - Switch Status
- [x] Fan - Fan Level
- [x] Fan - Mode
- [x] Fan - Horizontal Swing
- [x] Fan - Horizontal Angle
- [x] Fan - Power Off Delay Time
- [x] Fan - Brightness
- [x] Fan - Alarm
- [ ] Fan - Motor Control*
- [x] Fan - Speed Level
- [x] Physical Control Locked
_*This option can't be tested. Function is missing in the JSON file._

Additionaly i compared the [JSON](https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:fan:0000A005:dmaker-p18:1) vs the one you provided to me. There is a missing part:
**Explanation:** 
This function provide possibility to change the fan head direction with every button press to the left or right.
It is supported by the fan but can only used if "Horizontal Swing" is disabled.

This part is missing:

            {
               "iid":9,
               "type":"urn:miot-spec-v2:property:motor-control:00000038:dmaker-p18:1",
               "description":"Motor Control",
               "format":"uint8",
               "access":[
                  "write"
               ],
               "unit":"none",
               "value-list":[
                  {
                     "value":0,
                     "description":"NO"
                  },
                  {
                     "value":1,
                     "description":"LEFT"
                  },
                  {
                     "value":2,
                     "description":"RIGHT"
                  }
               ]
            },

**Comment by marcelrv** [comment]
thanks for the clear testing. Indeed seems my converter did not yet deal well with channels that only had write and no read.
