### ISSUE TITLE
[mqtt.homie] Resend settable values when device comes back from sleep

### ISSUE THREAD

**Issue by valpackett** [openhab/openhab-addons#11062]
Battery-powered devices often need to deep sleep frequently, and that sleep can lose the state that was set by the controller (openHAB).
Unfortunately with Homie the devices can't restore state from the broker, as the Homie spec forbids retained `/set` topics.
So the only way to go is to have the controller resend the state to the `/set` topics when the device says it's `ready` again.
It doesn't seem like openHAB has an option to do that? At least it's not really working with my device, and from a quick look at the code I see that [this thing](https://github.com/openhab/openhab-addons/blob/fa699b807e91b5dc2e8094e590b529a8bb9ffcd7/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/internal/handler/HomieThingHandler.java#L162) doesn't call into anything that would do it.

**Comment by Rossko57** [comment]
As this doesn't seem to be part of the Homie specification, it doesn't seem to be the business of the Thing.   You'd need some kind of manual config intervention anyway, to decide which command topics to "refresh" or not.

It's the sort of thing easily accomplished by rules.
```
when ( my thing comes back online)
then
send a command based on stored state
```
There'd be a bit of fiddling about when/what to store command for possible later re-use, but that storing should not be the business of bindings either (which are supposed to be 'stateless').

**Comment by ccutrer** [comment]
I'd also agree that within the confines of the Homie spec there's no defined behavior here, and the only way to "get it right" for your particular mix of devices would be to write your own rules, and this issue should be closed.

**Comment by lolodomo** [comment]
Closing after reading both answers
