### ISSUE TITLE
[chromecast] Documentation confusing/missing information

### ISSUE THREAD

**Issue by Shituation** [openhab/openhab-addons#11061]
Hi all!
I´m trying to make the chromecast binding to work using the official documentation but it has missing examples, for example the most important (in my opinion) which is the chromecast video configuration. All I see are examples where audio is used but no video. To be clear, I want to configure the binding to be able to send a youtube url to play on my chromecast TV.
No examples are provided and the instructions are quite confusing.

For example, what is this? its not explained anywhere:
![image](https://user-images.githubusercontent.com/43975882/127045794-48f85838-cd8b-45cb-8a0c-9a2c0e8a2725.png)

Or this example rule... what does it do? I only see code but no explanation anywhere. Also that rule doesn't seem to do anything.
![image](https://user-images.githubusercontent.com/43975882/127045963-104d4dac-b2e9-458c-ab87-d5650128cebb.png)

Also this statement says something and then contradicts itself:
![image](https://user-images.githubusercontent.com/43975882/127046284-511d33d7-0d56-49ff-a1da-149b3be839fa.png)

Please review this documentation since I think its very confusing. I still could not make this binding work correctly.

**Comment by elcosomalo1** [comment]
IMO examples should include the basic configuration to make the binding work as intended, that is being able to play video or audio at a given trigger.
Complex rules like the example given to check if chromecast is doing A or B and then trigger something is not very useful in the official documentation, it belongs to the forums.

**Comment by lsiepel** [comment]
@Shituation late response, but can i assume this resolved? I do see an example in the current documentaiton: https://www.openhab.org/addons/bindings/chromecast/#rule-action is that what you where looking for?

**Comment by Shituation** [comment]
No, its the same page from my screenshot, I don't see anything has been added honestly.
Also, I'm not using google anymore in any form.

**Comment by lsiepel** [comment]
> thing has been added honestly.
> Also, I'm not using google

I didn't pay much attention to the screenshot, sorry, as this is an 18 month old issue. But your right, it looks like it has not changed. I also agree that the documentation can be improved. So, i created a PR (see link) above to make some improvements and consistency. Now i also read your community thread and while you did get some help, it was never posssible to play a Youtube link. I understand the use case, maybe something for future development. For now i hope we can atleast improve the documentation. Thanks!
