### ISSUE TITLE
[keba] (3.1) Channel Authenticate - Unable to remote authenticate 

### ISSUE THREAD

**Issue by RoBuerger** [openhab/openhab-addons#11066]
Hi,

I need some help with remote authenticate.

I created a Javascript script for my authenticate switch and tried different combinations of rfid tag and classifier.
But with no luck. Keba P30 x-series says "Unknown card..."

What is the correct String I have to send to the Authenticate Channel?

xxxx - rfid tag
yyyy - rfid classifier

Script:
                                                
/*var master_auth_string = "xxxxxxxxxxxxxxxx yyyyyyyyyyyyyyyyyyyy";*/
/*var master_auth_string = "xxxxxxxxxxxxxxxx+yyyyyyyyyyyyyyyyyyyy";*/
/*var master_auth_string = "xxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyy";*/

events.sendCommand("KeContactEVChargingStation_Authenticate", master_auth_string);

**Comment by lsiepel** [comment]
Did you ever get this sorted? As 18 months have passed, I guess you won’t get an answer anymore. Should we close this issue?
