### ISSUE TITLE
[avmfritz] Allow inversion of shutter levels

### ISSUE THREAD

**Issue by quidam** [openhab/openhab-addons#11078]
While openHAB generally interprets a blind opening level of 0% as fully closed and 100% as fully open, the HAN-FUN blinds interpret the values vice versa. This leads to the need to convert the values in rules and to wrong representation of the opening levels in widgets.
Therefor I suggest a feature to invert the level value, both when reading the state and when sending a comman, when a configuration switch is set. The reason for the configuration switch is, that existing rules should continue working properly.

As I have already implemented this feature, this issue is to document the feature and to generate a issue number for the merge request.

**Comment by diRk262** [comment]
I use HAN-FUN blinds and they are not inverted.
Afaik openhab blinds are like: 
fully open = 0 and fully closed = 100.

**Comment by kaikreuzer** [comment]
> Afaik openhab blinds are like:
> fully open = 0 and fully closed = 100.

This is correct.
As commented in another issue on avmfritz, if something is not behaving as expected due to an inversion, this should and can be fixed in the binding and no additional configuration by the user should be necessary.
