### ISSUE TITLE
[mqtt.homeassistant] discovery unreliable in OH 3.x

### ISSUE THREAD

**Issue by ErikApption** [openhab/openhab-addons#11085]
I've been writing a mqtt client for sending sensor info to OH 3.x and wanted to leverage the HomeAssistant discovery

I'm sending the following discovery message (which is based on homeassistant discovery from Tasmota which worked perfectly with OH 2.5 and created channels).

```
homeassistant/sensor/R5EE70BB9_N321346B4/config` {"~":"Bedroom/BME280","dev_cla":"temperature","name":"Bedroom Temperature","stat_t":"~state","unit_of_meas":"°C","json_attributes_topic":"~state","val_tpl":"{{ value_json.temperature }}","uniq_id":"R5EE70BB9_N321346B4"
,"avty_t":"~status","pl_avail":"Online","pl_not_avail":"Offline","device":{"identifiers":["R5EE70BB9"],"connections":["mac","00155D009500","8C8CAAEE1F8F"],"name":"BME280 Bedroom"}}
```

I've seen this show up few times in the inbox but it is quite unreliable. I have debug set to trace for mqtt and discovery and can confirm the following:
- discovery is subscribing to the correct topic 
```
2021-08-03 16:53:36.951 [TRACE] [g.mqtt.handler.AbstractBrokerHandler] - Subscribed org.openhab.binding.mqtt.homeassistant.internal.discovery.HomeAssistantDiscovery@47868a4d to discovery topic homeassistant/# on broker mqtt:broker:6f8979a9
```

- the subscription message is sent to openhab
```
Aug  3 17:36:49 openhab mosquitto[25528]: Sending CONNACK to f2906dab586249e29e21299abf18e7cb (0, 0)
Aug  3 17:36:49 openhab mosquitto[25528]: Received PUBLISH from f2906dab586249e29e21299abf18e7cb (d0, q0, r0, m0, 'homeassistant/sensor/R5EE70BB9_N321346B4/config', ... (399 bytes))
Aug  3 17:36:49 openhab mosquitto[25528]: Sending PUBLISH to 9b6a4b16-d35c-426f-b0ad-cdc88373e133 (d0, q0, r0, m0, 'homeassistant/sensor/R5EE70BB9_N321346B4/config', ... (399 bytes))
```

## Expected Behavior
When the `homeassistant/#` topic message is received by openhab - I should be able to see a message in the logs at least.
By looking at the code from the homeassistant Discovery class, I'm wondering if the OSGi subscription fails silently.
From the current code, the log should have something around the item either created or invalid if that class received the mqtt message. Also there is no other trace of that mqtt message being processed.

## Your Environment
* Version used: openhab 3.2.0M1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): RPI4 with openhabian 64 bit and 64 bit JVM

Also I've seen few other odd issues in the forums related to homeassistant discovery
https://community.openhab.org/t/solved-homeassistant-mqtt-and-auto-discovery-no-channels/112963
https://community.openhab.org/t/solved-openhab-3-unable-to-discover-mqtt-things-with-auto-discovery/114254/9

**Comment by lolodomo** [comment]
@antroids : is this issue fixed by your merged PR?

**Comment by antroids** [comment]
> 

Yes, after the PR users should see the warning about incorrect payload.

**Comment by lolodomo** [comment]
So closing it
