### ISSUE TITLE
[surepetcare] Failure to poll pet information adjustment

### ISSUE THREAD

**Issue by dag81** [openhab/openhab-addons#11080]
As I have already implemented this feature, this issue is to document the feature and to generate a issue number for the merge request.

When a cat flap and feeder exist on the system, but the cat flap is not in use yet the SurePetcarePetHandler.updateThing fails, as the activity object under pet.status is null. The change is to simply put a defensive check in to check its not null before extracting anything under it (pet.status.activity). If a null check is added the rest of the data can be extracted for the pet without an exception stopping the processing of other data that is available. E.g. Feeder data.

**Comment by dag81** [comment]
Okay having trouble pushing the branch to raise the Pull request against :( Time for some reading.

The code change is to simply adding the first line below above the others in org.openhab.binding.surepetcare.internal.handler.SurePetcarePetHandler:

`if (pet.status.activity != null) {
                    if (pet.status.activity.deviceId != null) {
                        SurePetcareDevice device = petcareAPI.getDevice(pet.status.activity.deviceId.toString());
                        if (device != null) {
                            updateState(PET_CHANNEL_LOCATION_CHANGED_THROUGH, new StringType(device.name));
                        }
                    } else if (pet.status.activity.userId != null) {
                        SurePetcareHousehold household = petcareAPI.getHousehold(pet.householdId.toString());
                        if (household != null) {
                            Long userId = pet.status.activity.userId;
                            household.users.stream().map(user -> user.user).filter(user -> userId.equals(user.userId))
                                    .forEach(user -> updateState(PET_CHANNEL_LOCATION_CHANGED_THROUGH,
                                            new StringType(user.userName)));
                        }
                    }
                }`

**Comment by renescherer** [comment]
Hi @dag81. Apologies for the delay. This should be fixed as part of this PR: https://github.com/openhab/openhab-addons/pull/11235
