### ISSUE TITLE
[fronius] binding additional API calls

### ISSUE THREAD

**Issue by robtop100** [openhab/openhab-addons#11101]
I created additional calls to Fronius inverter API via HTTP binding
/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CommonInverterData
/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=3PInverterData
/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=MinMaxInverterData

so I can get more data from inverter (without Fronius Smart Meter device)

API method: GetInverterRealtimeData1
Body.Data.DeviceStatus.ErrorCode
Body.Data.DeviceStatus.ErrorCode
Body.Data.DeviceStatus.ErrorCode
Body.Data.DeviceStatus.MgmtTimerRemainingTime
Body.Data.DeviceStatus.StateToReset
Body.Data.DeviceStatus.StatusCode

API Method: GetInverterRealtimeData2
(Please notice -existing  Fronius binding require Smart Meter device to read those values)
Body.Data.IAC_L1.Value
Body.Data.IAC_L2.Value
Body.Data.IAC_L2.Value
Body.Data.UAC_L1.Value
Body.Data.UAC_L2.Value
Body.Data.UAC_L3.Value

optional:
API method: GetLoggerInfo1
Body.LoggerInfo.HWVersion
Body.LoggerInfo.PlatformID
Body.LoggerInfo.ProductID
Body.LoggerInfo.SWVersion

API method: GetLoggerLEDInfo1
Body.Data.PowerLED.Color
Body.Data.PowerLED.State
Body.Data.SolarNetLED.State
Body.Data.SolarNetLED.Color
Body.Data.SolarWebLED.Color
Body.Data.SolarWebLED.State
Body.Data.WLANLED.Color
Body.Data.WLANLED.State

Could those calls be added to official Fronius binding (inverter device) ?

**Comment by jimtng** [comment]
Hi @robtop100 

* ErrorCode and StatusCode is already provided in the current binding
* Could you tell me what MgmtTimerRemainingTime and StateToReset mean?
* GetLoggerInfo returns static data. In my opinion, this shouldn't be constantly polled from the inverter, it's a waste of resource and bandwidth.
* I don't quite understand the usefulness of the GetLoggerLEDInfo. On my inverter, the json data returned all green and on. However, they don't seem to correspond to the actual physical LEDs on the device.
* I'm curious to understand what you do with the data from 3PInverterData (Voltage and current)

**Comment by chr1337** [comment]
Thank you a lot for your great work!

It would really be great to read from solar_api/v1/GetStorageRealtimeData.cgi
What I'm missing in the current binding is the battery status. (Especially the SOC (StateOfCharge_Relative)). This ist the output on my gen24:
{
   "Body" : {
      "Data" : {
         "0" : {
            "Controller" : {
               "Capacity_Maximum" : 7800,
               "Current_DC" : 0.79987550575785871,
               "DesignedCapacity" : 7800,
               "Details" : {
                  "Manufacturer" : "BYD",
                  "Model" : "BYD Battery-Box Premium HV",
                  "Serial" : "P030T020Z200XXXXXXX     "
               },
               "Enable" : 1,
               "StateOfCharge_Relative" : 65.900000000000006,
               "Status_BatteryCell" : 3.0,
               "Temperature_Cell" : 16.0,
               "TimeStamp" : 1650606867.0,
               "Voltage_DC" : 321.30000000000001
            },
            "Modules" : []
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2022-04-22T05:54:31+00:00"
   }
}

**Comment by jimtng** [comment]
> It would really be great to read from solar_api/v1/GetStorageRealtimeData.cgi

Please open a separate issue so it can be tracked / resolved separately.

**Comment by sberer** [comment]
Any feedback on this? I also want to use SOC and temperature of the battery.
