### ISSUE TITLE
[Fronius] increase timeout

### ISSUE THREAD

**Issue by ramack** [openhab/openhab-addons#11117]
Using Openhab 3.2-SNAPSHOT on a RaspberryPi 4with the Fronius binding I get quite many timeouts on reading the JSON input from the inverter. This might be due to the inverter responding slow, several Modbus TCP connections in parallel to it or the "not so well" Wifi connection. When get the JSON output with a browser I count roughly 5 sec until it is shown, so probably the hardcoded 5000ms timeout is the culprit.

Even though I would prefer to fix it in the source it would be great to increase the timeout to maybe 10 sec. or even make it configurable in the bridge config.

Logs are:
```
2021-08-15 22:08:06.678 [DEBUG] [rnal.handler.FroniusBaseThingHandler] - Error running fronius request: java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed
2021-08-15 22:08:06.682 [DEBUG] [rnal.handler.FroniusBaseThingHandler] - URL = http://192.168.0.12/solar_api/v1/GetPowerFlowRealtimeData.fcgi
2021-08-15 22:08:11.688 [DEBUG] [rnal.handler.FroniusBaseThingHandler] - Error running fronius request: java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed
```

**Comment by jimtng** [comment]
[org.openhab.binding.fronius-3.2.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/7028907/org.openhab.binding.fronius-3.2.0-SNAPSHOT.jar.zip)
Please give this a try. I have just changed the API_TIMEOUT to 10 seconds, no other changes. If it works for you, I can submit a PR.

**Comment by ramack** [comment]
Great thanks! I will try it as soon as I am back from vacation!

**Comment by jimtng** [comment]
I've tried this on my system, and even after increasing the timeout to 10 seconds, I am still seeing the timeout errors.

**Comment by jimtng** [comment]
@ramack, the latest 3.3 snapshot includes some changes to fronius binding that retries the connections should it fail. Could you give it a try and see if that solved your use case? Unfortunately there's not much we can do if the fronius controller itself times out after a long time. It must have a very slow microcontroller.

**Comment by ramack** [comment]
Thanks for pinging me and sorry that I lost track about this issue. Since a long time I do not see the timeout anymore, but cannot exactly tell since when. I tried playing around with it again but failed to reproduce it. Neither with the Wifi nor with the wired ethernet connection to the fronius. I cannot exclude that a SW update in the Fronius or the removal of the 70% power reduction did the trick.

I am currently on openHAB 3.2.0 from the stable debian repository and a bit reluctant to jump to unstable with my productive system, but if it is a big help, I could give it a try.

**Comment by jimtng** [comment]
@ramack I'm glad your issue is resolved. Regarding the snapshot, there's no need to try it out until you're ready. I'd suggest closing this github issue for now.

**Comment by ramack** [comment]
fine for me - even though I have no clue what actually did the trick in my case. Anyhow, thanks for your efforts!

**Comment by ramack** [comment]
Tried again in the browser and the response time from the Fronius is significantly better than what I described above as "close to 5s". So I guess it was a Fronius issue...
