### ISSUE TITLE
[danfossairunit] Channels: Add categories, descriptions and semantic tags

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#11128]
**Categories:** All channels but humidity are missing categories.
**Descriptions:** Some channels lack descriptions.
**Semantic tags:** All channels are missing semantic tags, except Humidity which has tag "CurrentHumidity".

Furthermore, channel-id **battery_life** could use system channel type id **system.battery-level** instead of custom **percentage**.

Example:
![image](https://user-images.githubusercontent.com/19519842/129962449-e0118eaa-d3b3-4f1d-873e-094a4a430906.png)

Using system channel type:
![image](https://user-images.githubusercontent.com/19519842/129962514-4c001d40-0ed2-46fe-aa7b-a24a7440e638.png)

This feature request was created to document intended changes - I plan to prepare a new pull request with these changes. There will some dependencies though - first PR touching this area is #11121.

@pravussum - feel free to object or make suggestions. :-)

**Comment by jlaur** [comment]
Created draft pull request #11129.

**Comment by jlaur** [comment]
@kaikreuzer - it seems I cannot link this issue to #11129 - can you do this? Closing issue as done.

**Comment by kaikreuzer** [comment]
Done!
