### ISSUE TITLE
[opengarage] Cannot open garage door via openHAB Binding (openHAB 3.1.0)

### ISSUE THREAD

**Issue by tinom86** [openhab/openhab-addons#11136]
Dear all,

the opengarage binding for openHAB 3.1.0 is working partly for me. 

The connection is set-up successfully. I get all the status information correctly (door status, vehicle status, distance). However, opening/closing the garage door via the switch item in the openHAB binding is not working. Nothing happens (Opening/closing via OpenGarage App or Web App is working though).

Item to open garage door is configured as follows:
Switch 			OpenGarage_Status { channel="opengarage:opengarage:OpenGarage:status-switch" } 

Any ideas why it is not working? I do not get any issues in the openHAB log.

Best
Tino

**Comment by lsiepel** [comment]
As this post was raied more then three years ago, i hope this is resolved by now. If not, feel free to re-open or ask the community forums for advice on how to check if this is a configuration issue or an actual bug.
