### ISSUE TITLE
Easyaccess Easycodetouch Binding request 

### ISSUE THREAD

**Issue by Supermagnum** [openhab/openhab-addons#11138]
It supports a combined Easy Zigbee 3.0/BLE module,includes a MiFare classic tag reader.
It also has a EasyRing Lock module, that enables connection to a EasyRing WIFI doorbell that enables opening the lock with a cell phone app ( EasyRing App).
The product is here, and supports up to 999 access codes!
https://easyaccess.no/product/easycodetouch/

Found this:
https://www.zigbee2mqtt.io/devices/easyCodeTouch_v1.html

**Comment by wborn** [comment]
Similar to your other issues, discuss this in the community and then create an issue when someone starts working on it.
