### ISSUE TITLE
[samsungtv] - A way to tell the FrameTV which image to use in ArtMode.

### ISSUE THREAD

**Issue by geoffpaulsen** [openhab/openhab-addons#11158]
I see that there are bindings to provide [if the Samsung Frame TV is currently in ArtMode](https://www.openhab.org/addons/bindings/samsungtv/).
Unfortunately the only way to specify a new Art image is via the proprietary SamsungThings App.  I'd love to be able to use  OpenHab for this as well.  Is this possible?  Could this be extended to work?

**Comment by kaikreuzer** [comment]
The SamsungTV binding works through UPnP and afaik there is no way to select an image for the Artmode. This is purely a boolean to switch on and off. I'd hence say we should close this issue as it is technically not feasible.
