### ISSUE TITLE
[shelly/tradfri) Missing mention of Californium in NOTICE file ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#11169]
Shouldn't the californium library be mentioned in the NOTICE file as a third-party content (+license) for the tradfri and shelly bindings ?

**Comment by hmerk** [comment]
@lolodomo I don't hink so. The following post in the community by @Hilbrand gives a good explanation, what to include in the NOTICE file : 
https://community.openhab.org/t/tutorial-update-license-to-epl-v2-0-of-your-binding-in-development-or-pull-request/65088

As Californium is published under EPL and is available in maven repo, there should be no need to mention it.

**Comment by lolodomo** [comment]
What I read is:
> If you have any libraries included in your project you need to also make a reference about the licenses of those libraries.

At the same time, the Jetty HTTP client is used on a lot of bindings without being mentioned in the NOTICE file. 

Maybe @kaikreuzer can help to clarify?

**Comment by hmerk** [comment]
Yes, but these bindings don't include third party libraries but use imports from a maven repo. That's the difference.

**Comment by kaikreuzer** [comment]
It always depends if third party code is packaged within the jar of the binding - which is often the case if the dependency is not an OSGi bundle in itself, but rather a plain Java Jar. The NOTICE file then explains, that the jar file contains other stuff that is not code of the openHAB project itself.

In the case of Californium, this is a proper OSGi bundle and just being installed as a separate bundle (actually as a [Karaf feature](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.tradfri/src/main/feature/feature.xml#L7). This bundle comes with its own license information, so all is fine.
