### ISSUE TITLE
[draytonwiser] Smart Plug does not report correct state when manually triggered

### ISSUE THREAD

**Issue by RafalLukawiecki** [openhab/openhab-addons#11174]
If I manually turn the Wiser Smart Plug on or off using its mechanical button its state is not updated/received by OH. This is my item configuration:

```
Switch wiser_Master_Bedroom_Air_Purifier
    "Bedroom Air Purifier" <fan>
    {channel="draytonwiser:smart-plug:WiserHeat.***:plugOutputState",
        homekit="Outlet, Outlet.OnState"}
```

I have tested with OH2.5 only.

**Comment by lsiepel** [comment]
Do you still haev this issue with openHAB 3.4.0 ? I expect nothing has changed as there does not seem to be a related PR merged. I might look into this, but can't promise you anything.
Are you available for testing and can you provide a debug log from 3.4.0 when you switch the button?

**Comment by RafalLukawiecki** [comment]
I have not upgraded to OH 3 yet. Once I do, I would be happy to test, but for now I am on 2.5. Happy to help in any other way.

**Comment by lsiepel** [comment]
Once you made the move to 3.4.x we can try to get it fixed and tested. Let me know once you are ready.

**Comment by RafalLukawiecki** [comment]
Still an issue in 2.5…

**Comment by lsiepel** [comment]
> Still an issue in 2.5…

The 2.5 branch is (for some time) no longer maintained. Please upgrade to 4.x
