### ISSUE TITLE
[tradfri] Plug does not change state

### ISSUE THREAD

**Issue by qermit** [openhab/openhab-addons#11185]
## Expected Behavior

To power Tradfri Plug following payload should be sent to gateway
```json
{"3312":[{"5850":1}]}
```

## Current Behavior

The OpenHab sends additional field `"3":null` and as result the command is ignored
```
2021-09-01 12:29:53.564 [DEBUG] [internal.handler.TradfriThingHandler] - Sending payload: {"3312":[{"5850":1}],"3":null}
2021-09-01 12:29:53.587 [DEBUG] [g.tradfri.internal.TradfriCoapClient] - CoAP PUT request
uri: coaps://192.168.0.37:5684/15001/65556
payload: {"3312":[{"5850":1}],"3":null}
2021-09-01 12:29:53.602 [DEBUG] [.tradfri.internal.TradfriCoapHandler] - CoAP response
options: null
payload:
2021-09-01 12:29:55.072 [DEBUG] [internal.handler.TradfriThingHandler] - Sending payload: {"3312":[{"5850":0}],"3":null}
2021-09-01 12:29:55.074 [DEBUG] [g.tradfri.internal.TradfriCoapClient] - CoAP PUT request
uri: coaps://192.168.0.37:5684/15001/65556
payload: {"3312":[{"5850":0}],"3":null}
2021-09-01 12:29:55.089 [DEBUG] [.tradfri.internal.TradfriCoapHandler] - CoAP response
options: null
payload:
```

## Possible Solution

remove `"3":null` from payload
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: `openhab-3.1.0-1.noarch`
* Operating System and version: CentOS Linux release 8.1.1911 (Core)

**Comment by isrjo** [comment]
I'm under the impression this problem reach beyond the mentioned Plug Device. I have a situation now where all changes to my IKEA devices (various bulbs) from either a remote or the IKEA App are reflected in OH, however changes initiated from OH are just silently dropped.

I too spotted the rather odd payload sent from OH (with the last extra null field) and can confirm removing that last field will make the payload again accepted by the IKEA GW (and acted upon).

Not exactly sure when my setup stopped working, I think "a few days ago". I saw IKEA released a new firmware October 27th, would't suprice if that's related.

GW FW: 1.16.26
OH: 3.0.2M2 && M3, using the docker image.

**Comment by jlaur** [comment]
@isrjo, @qermit, others - is this still a problem in openHAB 3.2/3.3 when running latest version of the TRÅDFRI firmware? From what I have been able to read from the forum thread, this issue and the PR it seems the problem was introduced in FW 1.16.26, but also there are some indications that it was later fixed? In this case we could close this issue as well as the linked PR, #11187.

**Comment by lsiepel** [comment]
As there was no follow up and the linked PR was allready closed, i guess this cvan be marked as completed. If needed it can be re-opened again easily.
