### ISSUE TITLE
Binding for whereami, a presence triangulation system using WiFi.

### ISSUE THREAD

**Issue by Supermagnum** [openhab/openhab-addons#11209]
Uses WiFi signals and machine learning (sklearn's RandomForest) to predict where you are. Even works for small distances like 2-10 meters.

Your computer will known whether you are on Couch #1 or Couch #2.

Link:
https://github.com/kootenpv/whereami

**Comment by wborn** [comment]
Similar to your other issues, discuss this in the community and then create an issue when someone starts working on it.
