### ISSUE TITLE
[robonect] Binding stopped working every 1-2 Days

### ISSUE THREAD

**Issue by DJDeepT** [openhab/openhab-addons#11204]
Hello everyone.
The Robonect binding has been hanging up since a few days.
System is Openhabian on a Raspberry Pi 3 with OH 3.1 stable.
The only remedy is to deactivate the thing briefly and activate it again. Then everything is OK again for 1-2 days.
Is the problem known? Does someone have the same problems and possibly a solution?
Today I uninstalled the binding and reinstalled it.
Now wait and see.

The following is output in the log:

2021-09-03 09:38:27.747 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 

java.lang.NullPointerException: null

	at org.openhab.binding.robonect.internal.handler.RobonectHandler.refreshMowerInfo(RobonectHandler.java:228) ~[?:?]

	at org.openhab.binding.robonect.internal.handler.RobonectHandler$MowerChannelPoller.run(RobonectHandler.java:415) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]

	at java.lang.Thread.run(Thread.java:829) [?:?]

Can You Fix it?

Thanks.
Tobi

**Comment by Larsen-Locke** [comment]
I've got the same or a similar problem: The Thing states: "COMMUNICATION_ERROR
Could not send command http://192.168.1.80/json?cmd=version"
But the direct web interface is working and sending the above command via browser returns a correct answer.

**Comment by lsiepel** [comment]
Might do some work on this binding, are you available to do some basic tests? Let me know an i'll try to come up with a 3.4.x version.

**Comment by DJDeepT** [comment]
I first can test in spring when the mower goes out :-)

**Comment by DJDeepT** [comment]
> Might do some work on this binding, are you available to do some basic tests? Let me know an i'll try to come up with a 3.4.x version.

Yesterday i startet my mower season 2023. The Error of this binding is almost here. can you send me the new binding for testing?

**Comment by jlaur** [comment]
@DJDeepT - can you try this version (assuming you're on 3.4)? [org.openhab.binding.robonect-3.4.5-SNAPSHOT.jar](https://drive.google.com/file/d/1wpeK-9pDoFNJJcz34qGG3s8MEL7nWGjk/view?usp=sharing)

**Comment by DJDeepT** [comment]
Thanks. I installed it now and will test it. I think i can give feedback in 1 week.

**Comment by DJDeepT** [comment]
I Installed it 2 Days ago. The same failure again. Thing Status was ONLINE. But no actualising. I had to deactivate and reactivte it... No Log Entry.
Sorry.....

**Comment by jlaur** [comment]
Okay, too bad. The fix was towards a specific `NullPointerException` though, so it was only a slight chance that this old bug could be related.

**Comment by lsiepel** [comment]
Been a while and the stacktrace no longer matches with the current source version of the file:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.robonect/src/main/java/org/openhab/binding/robonect/internal/handler/RobonectHandler.java#L228

Could you upload a stacktrace/log from a recent version, preferable openHAB 4.x?
