### ISSUE TITLE
[rotel] Issue with connecting to Rotel RDD-1580 DAC

### ISSUE THREAD

**Issue by jkbnk** [openhab/openhab-addons#11211]
Hello,

I don't know whether I found a bug in Rotel binding, or I am missing something.

I am running OpenHAB on macOS 10.14 for testing purposes.
I have a RDD-1580 DAC connected via USB to serial connector to RPi running the latest Raspbian.
On it I have installed ser2net service and configured it with line:
`9590:raw:0:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT in /etc/ser2net.conf`
The binding is configured through web UI RPi IP: 192.168.0.10 (RPi) on PORT: 9590 and system path /dev/ttyUSB0.

The binding is unable to connect to the service giving:
```
COMMUNICATION_ERROR 
Reconnection failed".
```
When listening with netcat (with ser2net disabled) I get nothing when initializing Rotel binding. When sending commands via telnet from macOS, netcat reads what it should. With ser2net active, I am able to control the DAC via telnet without an issue.
```
cvbes-Hackintosh:~ cvbe$ telnet 192.168.0.10 9590
Trying 192.168.0.10...
Connected to 192.168.0.10.
Escape character is '^]'.
!power_toggle!
power_off!source=coax1!
```
Moreover, I am able to control Hue lights via OpenHAB, so I don't think here is a problem within OpenHAB.

Here's the log (sorry, it's messy):
[https://pastebin.com/67WCZq3a](url)

Any helpful ideas?

**Comment by lolodomo** [comment]
Do note setup a serial port for your thing if you want to use serial over IP. Just setup an IP address and a port. 

In case it does not work with a correct thing setup, please enable DEBUG logs for the binding and show the logs. 

Please note that the community forum is a better place to ask usage help. A git issue has to be opened when you are almost certain of an issue.

**Comment by jkbbnk** [comment]
Oh, sorry I get it. It is nonsensical to provide serial port when connecting to a service which knows what the port is.
It is online and working. Thank you for help.
