### ISSUE TITLE
Please add a binding for FIND3

### ISSUE THREAD

**Issue by Supermagnum** [openhab/openhab-addons#11210]
The Framework for Internal Navigation and Discovery (FIND) is like indoor GPS for your house or business.
It should be ideal for presence.
It has:
Support for any data source - Bluetooth / WiFi / magnetic fields / etc. (previously just WiFi).
It's at:
https://github.com/schollz/find3

**Comment by wborn** [comment]
Similar to your other issues, discuss this in the community and then create an issue when someone starts working on it.
