### ISSUE TITLE
POPP Z-Weather 

### ISSUE THREAD

**Issue by reyem** [openhab/openhab-addons#1121]
Hi Chris,

I was just trying to migrate from openhab1 to 2. In OH1 my POPP Z-Weather works ok. But in OH2 it is not recognized. Although your online database contains Z-Weather, it does not correspond in the manufacturer and other ids. Here the node.xml written by OH2

[node16.xml.txt](https://github.com/openhab/openhab2-addons/files/363513/node16.xml.txt)

Let me know on how I can contribute best in solving this issue. 

Thank you 
Marco

**Comment by cdjackson** [comment]
This is in the database, but as there are some new channels required I've not included it into the binding yet. I'll take a look over the next few days.

**Comment by reyem** [comment]
OK cool. I just noticed that the manufacturer id is reported as 0x0115 which maps to ZWave.me. Also in my OH1 installation the device is listed as Zwave.me device, although it is actually from POPP. But the device works ok. So this is rather a cosmetic issue which can probably not be resolved.

**Comment by reyem** [comment]
Just one note. I saw the device listed twice in the database. 
1.)  Manufacturer Zwave.me: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/258
2.) Manufacturer POPP_NEW: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/234

The first is the one which I would expect for my sensor...

**Comment by cdjackson** [comment]
If it has been marketted by two manufacturers, then it needs to go in twice - I'll try and get them both into the binding.

Thanks.

**Comment by cdjackson** [comment]
This is now merged - give tomorrows binding a try and let me know how it goes...

**Comment by reyem** [comment]
Hi Chris,

Now it seems to work correctly and my Z-Weather is detected and identified. Thank you a lot for the fast handling. 

There was an NPE in the log. No idea if it is related, but I think I post it here so you might have a look. But it did not cause any obvious effects....

`2016-07-19 00:35:04.079 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_device_155e646c9e4_node4_sensor_binary changed from ON to OFF
2016-07-19 00:35:11.590 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - Exception during ZWave thread: Send
java.lang.NullPointerException
	at org.openhab.binding.zwave.handler.ZWaveSerialHandler.sendPacket(ZWaveSerialHandler.java:309)[190:org.openhab.binding.zwave:2.0.0.201607180103]
	at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveSendThread.run(ZWaveController.java:1380)[190:org.openhab.binding.zwave:2.0.0.201607180103]
2016-07-19 00:35:19.278 [ERROR] [curityCommandClassWithInitialization] - NODE 8: SECURITY_ERROR Invalid state! Secure inclusion has not completed and we are not in inclusion mode. Aborting
2016-07-19 00:35:48.072 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_155e646c9e4_serial_sof changed from 473 to 474
`
