### ISSUE TITLE
[Homematic] Race condition causing items without channels to be created

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-addons#11214]
Since quite some time there is an issue with items without channels being created: https://community.openhab.org/t/homematic-binding-channel-not-found-for-datapoint-errors-for-definitely-existing-channels/26209

What I observed: The thing type does correctly contain the channels, the actual thing doesn't. 

I did some investigation and discovered the following: If the thing type is not available yet when the thing is created then the thing will be missing the channels afterwards. Unfortunately I don’t yet know what to do in that case, a changeThingType if no channels found is a dirty hack but it ends in a MISSING_HANDLER status (but with the channels populated properly).

If someone has any idea on how to address this I would be very grateful for suggestions so this issue can finally be resolved.

**Comment by Daniel-42** [comment]
Could this one be related? #11000 (Hue channels missing)

**Comment by Flole998** [comment]
> Could this one be related? #11000 (Hue channels missing)

Most likely not
