### ISSUE TITLE
[verisure] Support for non MFA activated user

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#11228]
Verisure has enforced MFA authentication that the binding needs to adapt to.

**Comment by jannegpriv** [comment]
Verisure has also changed the authentication process so the binding needs to be adapted to that awell. Also some endpoints used for smartlock and battery status has been removed.

I will work on 2 solutions:

- Support for new authentication process without having MFA activated on your account
- Support for MFA

**Comment by jannegpriv** [comment]
Since Verisure offers the possibility to configure per user if MFA shall be activated or not, it seems more reasonable to only support non MFA activated users for the binding, since this specific user then only can be used for automation and the primary user can then have MFA activated if that is desired.

I will therefore rename this issue to support for non MFA activated users.

**Comment by wborn** [comment]
Fixed by #11265
