### ISSUE TITLE
[homekit] "outlet" metadata not working

### ISSUE THREAD

**Issue by thales-man** [openhab/openhab-addons#11248]
I have a number of items that won't show up in HomeKit using the provided metadata 'links'.

I have some wall sockets I've tried to expose to HomeKit using the metadata tag 'outlet' along with its associated characteristics. I can expose the same items using 'lighting' or 'switchable' and they appear; change them back to 'outlet' and they disappear. For obvious reasons I don't wish to expose a wall socket to HomeKit as a light or a wall switch when it's a wall socket.

I have an openHAB 3.1 image running on a Rpi4 with deConz for Zigbee and RFXCom for 433mhz. This is a completely fresh installation, that has been patched to date.

I have posted a number of issues on the community site relating to the reliability of this integration, which I have now managed to stabilise. This particular problem doesn't appear to be fixable in that way as it has repeatable undesired behaviour.

**Comment by yfre** [comment]
@thales-man  what kind of characteristic if have fro outlet? can you share your configuration?
it just tried without any characteristics and it works as expected

here is my config (attached to openhab item of type switch, no groups):
value: Outlet
config: {}

**Comment by thales-man** [comment]
Hi Eugen,
Is this what you're looking for?
metadata JSON sample:
``` js
{
   -- this works
  "homekit:RadiatorSocketRightTYZB01hlla45kx": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "RadiatorSocketRightTYZB01hlla45kx"
        ],
        "uid": "homekit:RadiatorSocketRightTYZB01hlla45kx"
      },
      "value": "Lighting,Lighting.Name",
      "configuration": {}
    }
  },
  "homekit:DoorSocketRightTYZB01hlla45kx_Power": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "DoorSocketRightTYZB01hlla45kx_Power"
        ],
        "uid": "homekit:DoorSocketRightTYZB01hlla45kx_Power"
      },
      "value": "Lighting.OnState",
      "configuration": {}
    }
  },
   -- this works
  "homekit:RadiatorSocketRightTYZB01hlla45kx": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "RadiatorSocketRightTYZB01hlla45kx"
        ],
        "uid": "homekit:RadiatorSocketRightTYZB01hlla45kx"
      },
      "value": "Switchable,Switchable.Name",
      "configuration": {}
    }
  },
  "homekit:DoorSocketRightTYZB01hlla45kx_Power": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "DoorSocketRightTYZB01hlla45kx_Power"
        ],
        "uid": "homekit:DoorSocketRightTYZB01hlla45kx_Power"
      },
      "value": "Switchable.OnState",
      "configuration": {}
    }
  },
   -- this does not work
  "homekit:RadiatorSocketRightTYZB01hlla45kx": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "RadiatorSocketRightTYZB01hlla45kx"
        ],
        "uid": "homekit:RadiatorSocketRightTYZB01hlla45kx"
      },
      "value": "Outlet,Outlet.Name",
      "configuration": {}
    }
  },
  "homekit:DoorSocketRightTYZB01hlla45kx_Power": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "DoorSocketRightTYZB01hlla45kx_Power"
        ],
        "uid": "homekit:DoorSocketRightTYZB01hlla45kx_Power"
      },
      "value": "Outlet.OnState",
      "configuration": {}
    }
  },
}

**Comment by yfre** [comment]
could you please try without "Outlet.Name". 
Outlet.Name expects openhab item of type String but "Outlet" of type Switch. 

actually, this should not work as well "Switchable,Switchable.Name"
but i cannot see the type of openhab items and the groups.

**Comment by thales-man** [comment]
Will do. 
To be honest I find the whole thing too generalised and prone to mis-interpretation. We have spoken about this. If there is a 'name' characteristic for a component, I would expect it to export the display name of the component to HomeKit. Flexibility is great but things have to be bound by rules. This metadata can be dropped against anything, which clearly causes issues and it still doesn't cover a number of use-cases (battery characteristics in question). :)

**Comment by yfre** [comment]
agree. "Name" is confusing. actually it should not be used at all. by default it takes the name of the OpenHAB item anyway. only if the name should be dynamic, e.g changing at runtime, one should use "Name". Maybe this can be fixed by better documentation.

**Comment by thales-man** [comment]
I’ve applied the metadata Name characteristic to everything. So its probably easier if I edit the Json directly. I’ll  let you know how I get later, have to walk the dogs  now. :)

**Comment by thales-man** [comment]
Hi Eugen
I've updated the metadata file to remove from all the accessories that held a Name characteristic. this includes 6 items that were marked as 'Outlet'. 

It hasn't fixed the problem, the behaviour is still the same. If I make any of these items Lighting or Switchable they appear in HomeKit, turn them back to Outlet and they disappear.

**Comment by yfre** [comment]
very strange, but  i have never tried via json. only via .items file or mainUI.
so, that we keep this ticket open

**Comment by thales-man** [comment]
No, I'm managing through the UI. Just, in this case, I thought it might be easier to edit the JSON as I had so many to change.

**Comment by thales-man** [comment]
Hi Eugen
I've been messing with the metadata settings and this does work:

``` javascript
{
   -- this works
  "homekit:RadiatorSocketRightTYZB01hlla45kx": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "RadiatorSocketRightTYZB01hlla45kx"
        ],
        "uid": "homekit:RadiatorSocketRightTYZB01hlla45kx"
      },
      "value": "Outlet",
      "configuration": {}
    }
  },
  "homekit:DoorSocketRightTYZB01hlla45kx_Power": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "DoorSocketRightTYZB01hlla45kx_Power"
        ],
        "uid": "homekit:DoorSocketRightTYZB01hlla45kx_Power"
      },
      "value": "Outlet,Outlet.OnState", <= change here
      "configuration": {}
    }
  },
}
```
There are some clear issues with how the metadata is being applied as I can reliably repeat the appearance and disappearance of the socket in HomeKit. Why this particular metadata item works this way I really can't say.

**Comment by lsiepel** [comment]
@thales-man as this is an older issue and improvements have been made to both openHAB core as the homekit addons. Could you verify if this issue is still relevant for openHAB 4.1.x?

**Comment by thales-man** [comment]
I'll get back to you on this, I'm currently in the process of upgrading / installing 4.1.x

**Comment by thales-man** [comment]
Hi Eugen
So I've upgraded to 4.1 and all of my door locks have disappeared. And no amount of 'meta data' reissues seems to fix it. This is a major issue for me as I'm a big user of the HomeKit soft locks on my doors.
:(

**Comment by lsiepel** [comment]
> Hi Eugen So I've upgraded to 4.1 and all of my door locks have disappeared. And no amount of 'meta data' reissues seems to fix it. This is a major issue for me as I'm a big user of the HomeKit soft locks on my doors.
> 
> oh, and I've just checked 'outlet' still doesn't work. :(

Can you share the actively used item config?

**Comment by thales-man** [comment]
hi, 
I did recheck the outlet setting, and apologies it is working. In an effort to identify the problem with the doors I removed the bridge from HomeKit and reintroduced all the accessories. The doors still haven't re-appeared.

Is this the config bit you meant? =============================
  "homekit:KitchenSideDoor_DoorLock": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "KitchenSideDoor_DoorLock"
        ],
        "uid": "homekit:KitchenSideDoor_DoorLock"
      },
      "value": "Lock,Lock.LockCurrentState",
      "configuration": {}
    }
  },

**Comment by thales-man** [comment]
I should add… I can also delete the metadata and it still shows in the open HAB UI.

<img width="451" alt="Screenshot 2024-01-06 at 7 11 16 pm" src="https://github.com/openhab/openhab-addons/assets/17850586/57a475fa-381a-4522-b7da-5bd35345c7c2">

**Comment by lsiepel** [comment]
> hi, I did recheck the outlet setting, and apologies it is working. In an effort to identify the problem with the doors I removed the bridge from HomeKit and reintroduced all the accessories. The doors still haven't re-appeared.

To be clear, the metadata is now working as expected for the outlets?

**Comment by thales-man** [comment]
a step forward… 
it would appear HomeKit integration locks now not only require 'lock current state' but also 'lock target state'.
the problem with this is it now shows 2 doors in the Home App; not an ideal solution.

below and extract from OH log:
```
2024-01-06 20:17:19.655 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type Lock must have following characteristics [LockCurrentState, LockTargetState]. Found only [Item:KitchenSideDoor_DoorLock (Type=SwitchItem, State=ON, Label=Kitchen Back Door Lock, Category=Door, Tags=[Point], Groups=[KitchenSideDoor])  HomeKit type: 'Lock' characteristic: 'LockCurrentState']
2024-01-06 20:17:19.656 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:KitchenSideDoor (Type=GroupItem, Members=2, State=NULL, Label=Back Door, Category=Kitchen, Tags=[BackDoor], Groups=[Kitchen])  HomeKit type: 'Lock' characteristic: 'Empty'
2024-01-06 20:17:19.691 [WARN ] [.accessories.HomekitAccessoryFactory] - Accessory of type Lock must have following characteristics [LockCurrentState, LockTargetState]. Found only []
2024-01-06 20:17:19.692 [WARN ] [mekit.internal.HomekitChangeListener] - Cannot create accessory Item:FrontDoor (Type=GroupItem, Members=2, State=NULL, Label=Hall Front Door, Category=Hall, Tags=[Equipment], Groups=[Hall])  HomeKit type: 'Lock' characteristic: 'Empty'
2024-01-06 20:17:19.709 [INFO ] [mekit.internal.HomekitChangeListener] - Created 60 HomeKit items in instance 1 (no change from prior configuration).
```

**Comment by thales-man** [comment]
> > hi, I did recheck the outlet setting, and apologies it is working. In an effort to identify the problem with the doors I removed the bridge from HomeKit and reintroduced all the accessories. The doors still haven't re-appeared.
> 
> To be clear, the metadata is now working as expected for the outlets?

yes, outlets are working, locks are not.

**Comment by thales-man** [comment]
I think I've got it sorted, the lock requires 'lock current state' and 'lock target state', but not 'lock'. adding 'lock' breaks it. this is different behaviour to 3.4.x.

**Comment by lsiepel** [comment]
Well good that all got sorted. From what i understand from these posts is that the binding improved and the issue was fixed/changed.
 Possibly needless to say, but https://www.openhab.org/addons/integrations/homekit/ should have all information. If there is anything not clear, you can allways ask in the community forums.

Please re-open or create a new issue if there is still some bug to fix.
