### ISSUE TITLE
[MCP23017] binding not working on Openhab 3

### ISSUE THREAD

**Issue by Fisherijus** [openhab/openhab-addons#11253]
MCP23017 still does not work on Openhab3 even pi4j was updated. 

## Expected Behavior
MCp2017 binding initialize correctly with all its items

## Current Behavior
in Paper UI it shows that binding is Online, but in logs you can see errors coming thats says:
java.lang.NullPointerException: null
at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin though same configuration on OH 2 works correctly.

## Context
i cannot update my openhab to a newer version. 

## Your Environment
Openhab 3.2
java 11
pi4j 1.4

**Comment by wborn** [comment]
> in Paper UI it shows that binding is Online

Are you sure you use OH 3? That UI no longer exists.

Can you also post the full stacktrace?

**Comment by TrigerxD** [comment]
**On OpenHab 3.2.0 Release Build**

Hello, i am currently migrating from oh2 to oh3. I have read about this bindng that it is still not working, but for me is quite fine. One little problem, i cannot send any command to mcp pins (they are treated as input pins). 

_In binding configuration is some missunderstanding in output pin description_

Can somebody tell me how that binding now work or if it works? MCP23017 thing is succesfully initialized and now online, however i cannot work with it from openhab MainUI. 

Thats how look an switch item linked to output channel of mcp. Something is wrong and i dont know what :(

![image](https://user-images.githubusercontent.com/15014421/148655924-227cedec-f38c-425f-a012-18a149145549.png)

as i said thing is succesfully initialized

![image](https://user-images.githubusercontent.com/15014421/148655951-512b7c81-1d84-4b6e-8361-79e58e8b16f1.png)

as i said earlier there is some missunderstanding in description but still linked item works like a contact. Even configuration in file dont work

![image](https://user-images.githubusercontent.com/15014421/148656064-2dfe92ee-2991-4a0c-9ba5-fb2b4206d413.png)

**Comment by pin32** [comment]
hi, i have the same problem with oh3.41, who am I news on the matter

**Comment by pin32** [comment]
I don't know if the problem is fixable or not...

**Comment by adixyz** [comment]
Maybe the problem is this:
https://github.com/openhab/openhab-addons/issues/11905#issue-1091307808

**Comment by lsiepel** [comment]
This issue is a bit confusing. @Fisherijus reports a `NullPointerException` but the following posts mention other problems. 

To get any problem analyzed, it would be helpful to elaborate on the issue. What is happening, what do you expect, version used and maybe a debug log, item config, anything that is relevant.
