### ISSUE TITLE
[mqtt] Rollershutter should implement formatBeforePublish with an alternative

### ISSUE THREAD

**Issue by beulenbilly** [openhab/openhab-addons#11269]
# Current situation/behavior
I try to use the mqtt-bindung to control rollo shutter, switches and a dimmer. Dimmer and switches works as expected.
I use a configuration like:
```
Bridge mqtt:broker:localbroker "Mosquitto MQTT Broker" @ "HWR" [ host="localhost", secure=false ]
{
    Thing topic billu "Raspberry" @ "HWR" {
            Channels:
                Type switch : duschwc1 [ 
                    commandTopic="billu/5/SWITCH_POS/set",
                    stateTopic="billu/5/SWITCH_POS",
                    transformationPattern="JSONPATH:$.position",
                    formatBeforePublish="{\"command\": \"%s\"}",
                    qos=2,
                    on="ON",
                    off="OFF"
                ]
                Type dimmer : wohnzimmerdimmer [ 
                    commandTopic="billu/4/DIMMER_POS/set",
                    stateTopic="billu/4/DIMMER_POS",
                    transformationPattern="JSONPATH:$.position",
                    formatBeforePublish="{\"command\":\"POSITION\",\"value\": %.0f}",
                    qos=2
                ]
                Type rollershutter : duschwcRollo [ 
                    commandTopic="billu/7/ROLLO_POS/set",
                    stateTopic="billu/7/ROLLO_POS",
                    transformationPattern="JSONPATH:$.position",
                    formatBeforePublish="{\"command\":\"POSITION\",\"value\": %.0f}.",
                    qos=2
                ]
    }
}
```
Unfortunately the rolloshutter implemention ignores the `formatBeforePublish` configuration. On the other hand it wouldn't help me if it would be implemented because I need a different format for "GOTO" or "STOP".

# Feature / Expected Behavior
If the `formatBeforePublish` can't be applied a `formatBeforePublishAlt` (or similar) should be tried. If it fails default should you be used `%s`.

```
...
            Type rollershutter : duschwcRollo [ 
                    commandTopic="billu/7/ROLLO_POS/set",
                    stateTopic="billu/7/ROLLO_POS",
                    transformationPattern="JSONPATH:$.position",
                    formatBeforePublish="{\"command\":\"POSITION\",\"value\": %.0f}.",
                    formatBeforePublishAlt="{\"command\":\"%s\"}.",
                    qos=2
                ]
...
```

# Possible Implementation

https://github.com/beulenbilly/openhab-addons/commit/51af123b42f3b453482574f35294c8b08eba3e3a

# Environment
* Openhab 3.1.0
* Ubuntu 20.04.3 LTS

**Comment by Rossko57** [comment]
> Unfortunately the rolloshutter implemention ignores the `formatBeforePublish` configuration.

Could you provide the detail; what command did you send the Item, what message was published (or error logged).

> a `formatBeforePublishAlt` (or similar) should be tried.

I don't see the purpose of this; `formatBeforePublish=` is deliberately simplistic.  For complex if-but behaviours, scripted transformation is possible via `transformationPatternOut:=`, including chaining multiple transformations.

**Comment by beulenbilly** [comment]
Hey Ross,

I am unsure if my rolloshutter a special or not but it is possible to send UP/DOWN/STOP (normal) and GOTO_POSITION with a percentage value (maybe special).
If I configure the rolloshuter channel as described no error message appears but the 'formatBeforePublish' is ignored. Depending on the configuration if I send:
UP-COMMAND to the channel '0' or 'UP'-String will be published.
DOWN-COMMAND to the channel '100' or 'DOWN'-String will be published.
STOP-COMMAND to the channel 'STOP' will be published.
rollo-item.sendCommand(60) in rules '60' would be published.

Maybe you are right the that it is possible to use `transformationPatternOut` to get it work:
rollo-item.sendCommand -> published message
UP                                   -> {"command": "UP"} or {"command": "GOTO", "value": 0}
DOWN                            -> {"command": "DOWN"} or {"command": "GOTO", "value": 100}
STOP                               -> {"command": "STOP"}
50                                   -> {"command": "GOTO", "value": 50}

In my way of thinking my `formatBeforePublish` should handle it, maybe I am wrong. If you could describe how to configure it with `transformationPatternOut` it might help to understand how to use. Maybe it also helpful to update the documentation with a example like this. Maybe it already documented but I was not able to find it.

Kind regards.

**Comment by Rossko57** [comment]
You seem to have described what you need to do accurately.

> In my way of thinking formatBeforePublish should handle it,

I'm not sure why you think that; it's just a string formatter.  Take string "UP" or string "75" and drop it into some other fixed string.  There is no means to change "UP"into "0", no means to change the fixed string you are adding to depending on content.  
That's what  transformationPatternOut= is for.  I'd use a JS javascript; if command is numeric, do the GOTO string JSON thing, else pass the text style JSON.

**Comment by beulenbilly** [comment]
If you think that  `transformationPatternOut` is the better solution can you add an example?

**Comment by Rossko57** [comment]
This isn't really the forum for tutorials.
Item
`Rollershutter test1 "MQTT test" {channel="mqtt:topic:mosquitto:testing:Roller1"}
`
Thing and channel
`    Thing topic testing "Test topic thing" {
    Channels:
        Type rollershutter : Roller1  [ commandTopic="cmnd/blah/bleh", transformationPatternOut="JS:demo.js", on="UP",off="DOWN" ]
    }
`
Now, there is a quirk here.  Wanted or not, the binding converts UP and DOWN commands to '0' and '100' respectively.
I think that's a design mistake, when we are transforming we don't want commands pre-processed, but it is acting exactly as documented.
I've used the on=,off= features to recover 0 and 100 back to UP/DOWN.
The flaw/quirk is that genuine commands 0, 100 will get the same treatment too.
While is true that "go to position 0" is not the same as "go UP", in most cases we'll get away with it.

demo.js
`// variable "input" contains command passed by OpenHAB binding
(function(i) {
    var log = Java.type("org.slf4j.LoggerFactory").getLogger("org.eclipse.smarthome.automation.mytransform");
    // change that for OH3

    log.info("script begins with i " + i);
    var newjson = '{"deviceid"=99, ';
    if (i == "UP") {
        newjson = newjson + '"command"="banana"';
    } else if (i == "DOWN") {
        newjson = newjson + '"command"="apple"';
    } else {
        newjson = newjson + '"command"="go-to", "position"=' + i;
    }
    newjson = newjson + "}";
    log.info("built json " + newjson);
    return  newjson;
})(input)`

This **is** a demo, not a finished product.  You might want to deal with STOP, REFRESH etc.

logs
`2021-09-26 19:51:54.660 [INFO ] [pse.smarthome.automation.mytransform] - script begins with i UP
2021-09-26 19:51:54.661 [INFO ] [pse.smarthome.automation.mytransform] - built json {"deviceid"=99, "command"="banana"}
2021-09-26 19:52:15.329 [INFO ] [pse.smarthome.automation.mytransform] - script begins with i DOWN
2021-09-26 19:52:15.330 [INFO ] [pse.smarthome.automation.mytransform] - built json {"deviceid"=99, "command"="apple"}
2021-09-26 19:52:24.703 [INFO ] [pse.smarthome.automation.mytransform] - script begins with i 55
2021-09-26 19:52:24.704 [INFO ] [pse.smarthome.automation.mytransform] - built json {"deviceid"=99, "command"="go-to", "position"=55}
`
