### ISSUE TITLE
[metrics] Allow configuration via text based config

### ISSUE THREAD

**Issue by tbnobody** [openhab/openhab-addons#11279]
Currently it's only possible to configure the influxdb settings of the metrics addin via the main ui. It would be nice to also allow the configuration via text files as in many other addins.

## Your Environment
* Version used: OH 3.1

**Comment by wborn** [comment]
Currently you can already do this using a `metrics.cfg` file like this:

```java
org.openhab.io.metrics.MetricsRestController:influxMetricsEnabled=true
org.openhab.io.metrics.MetricsRestController:influxURL=https://influxdb
org.openhab.io.metrics.MetricsRestController:influxDB=metrics
org.openhab.io.metrics.MetricsRestController:influxUsername=openhab
org.openhab.io.metrics.MetricsRestController:influxPassword=77QjHkoWZEdbvXe9FWsJ
org.openhab.io.metrics.MetricsRestController:influxUpdateIntervalInSeconds=60

org.openhab.io.metrics.MetricsRestController:jmxMetricsEnabled=false
```

However this is wrong as nobody will easily guess this without looking at files or code. So I've changed it and added some docs for this.
