### ISSUE TITLE
[shelly] Shelly1 temp addon senosr channels don't show up

### ISSUE THREAD

**Issue by uschreib** [openhab/openhab-addons#11271]
## Expected Behavior

With clean/new openhab 3.1.0 installation and Shelly binding adding thing shelly1 with temp addon the sensors für temp should be visible. The shelly1 with the temp addon is showing up in the original shelly app, so correct working.

## Current Behavior

Only the standard channels (11) showing up in the openhab.

## Steps to Reproduce (for Bugs)

1. Add a Shelly1 thing with temp addon installed
2.

## Your Environment

* Version used: 3.1.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome 93.0.4577.82
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian 3.1.0 - Release Build

**Comment by markus7017** [comment]
this should work;: please enable DEBUG logging and post extract of device initialization

**Comment by uschreib** [comment]
I'm on vacation and after my return I'll provide the DEBUG logging.
BR
Uwe









Original Message processed by david® 
Re: [openhab/openhab-addons] [Shelly1] temp addon senosr channels don't show up (#11271) 5. Oktober 2021, 16:52 Uhr 
Von Markus Michels 
An openhab/openhab-addons 
Cc (2) uschreib|Author 


this should work;: please enable DEBUG logging and post extract of device initialization
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xvs03** [comment]
Hello, I have the same problem with the openHAB Binding. The channel of the external reed contact is not displayed. The status appears in the http status requests of the Shelly. I also assume this is a bug because other sensors are displayed without any problems.
It's a pity that no one else seems to have the problem. Some simply connect the reed contact to the button input, which is displayed as a channel. Personally, I don't find this a clean solution.
Dear shelly binding developers, please get in touch.

**Comment by markus7017** [comment]
I heard about this, but don't understand the details. #11970 seems to be the same, correct?

**Comment by uschreib** [comment]
Yes, the same...

**Comment by xvs03** [comment]
This is the Shelly addon, which you can put on a Shelly 1 for example.
Here you can connect up to three sensors.
Temperature sensors or DS18B20 or a DHT22.
But you can also connect only one reed contact.
This contact is displayed by the Shelly app with a garage symbol, which represents the state.

[https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#315](url)

[https://www.openhab.org/addons/bindings/shelly/](url)
Shelly 1(thing-type: shelly1)
Extern Sensors: 
              1. temperature1
              2. temperature2
              3. temperature3
              4. humidity
              
There is missing **Reed Contact Status**

This video (German) shows setup and processing of the signal in the app.
[https://www.youtube.com/watch?v=0q8pBCqb65w](url)


If you still have questions. Feel free to contact

**Comment by uschreib** [comment]
Crosspost from [markus7017](https://github.com/markus7017) to get all details in one place
/
[myfiles](https://github.com/markus7017/myfiles)

--------------------------------------------------------------
I have connected a reed contact as external switch to a Shelly 1 Addon as sensor for position of a garage door. The external switch is reflected in the JSON output, but not in OH3

Full JSON Output (provided by Sven_S):

{"wifi_sta":{"connected":true,"ssid":"SECRET","ip":"192.168.xxx.xxx","rssi":-61},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":"00:19","unixtime":1632781182,"serial":24,"has_update":false,"mac":"40F520XXXXXX","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"ext_switch":{"0":{"input":0}},"relays":[{"ison":false,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"source":"timer"}],"meters":[{"power":0.00,"is_valid":true}],"inputs":[{"input":0,"event":"","event_cnt":0}],"ext_sensors":{},"ext_temperature":{},"ext_humidity":{},"update":{"status":"idle","has_update":false,"new_version":"20210909-144114/v1.11.4-DNSfix-ge6b2f6d","old_version":"20210909-144114/v1.11.4-DNSfix-ge6b2f6d"},"ram_total":50872,"ram_free":35536,"fs_size":233681,"fs_free":149596,"uptime":6431}

Relevant Detail:

Door closed (Switch open) => "ext_switch":{"0":{"input":0}}
Door open (Switch closed) => "ext_switch":{"0":{"input":1}}

No function in OH3. Not showing up as relay or sensor.

**Comment by xvs03** [comment]
Please have a look at this topic in the German openHab Froum. There different procedures are explained.

I know this is the way around the missing shelly binding channel, **but it is not a shelly binding problem.**

For me the open close of the garage door via HTTP binding in OH3 works fine.
I think some detail doesn't fit for you yet. You can do it.
[https://openhabforum.de/viewtopic.php?t=6623](url)

**Comment by markus7017** [comment]
ok guys, let's get back. I now explored the featured and work on implementation
@uschreib @xvs03 are you available for testing?

**Comment by markus7017** [comment]
I updated the DEV build for OH 3.3 M3/M4 and added support for Shelly1's/Shelly1PM's external switch add-on (reed contact). Please verify (I can't test).

[org.openhab.binding.shelly-3.4.0M3-SNAPSHOT.jar](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.0M3-SNAPSHOT.jar?raw=true)

**Comment by HelgeT1** [comment]
Hi Markus,

testing it with a Shelly 1 which was connected without problems before (missing ext. contact channel per add on).
Now with the Snapshot.jar mentioned above i get a "COMMUNICATION_ERROR
Unerwarteter Fehler: API Timeout for" in the openhab Thing.
Another Shelly, a 1L, which i run in my setup has no Problem.

Greetings
Helge

**Comment by HelgeT1** [comment]
Hi,

just wanted to add the Info, the same Problem appears with my 1PM with add on installed.

Greetings

**Comment by markus7017** [comment]
please verify with the latest DEV build, there was an inconsistency with JSON format handling

**Comment by jwsp1** [comment]
I ordered a Shelly 1 with AddOn but it will take 2-3 weeks until it arrives. 
Maybe @HelgeT1 can test it sooner?

**Comment by anste** [comment]
I'd like to test the build on OH3.4.2 but after copying the jar (3.4.2-SNAPSHOT or 3.4.3-SNAPSHOT) to the "addons" folder, openhab.log shows several errors (NullPointerException and IllegalArgumentException). Am I missing a something?

**Comment by markus7017** [comment]
Did you checked READMEbeta?
- you need to uninstall the binding coming with the dist
- run "feature:install..." on OH console
- and then copy the 3.4.3-SNAPSHOT jar to the addons folder
-

**Comment by markus7017** [comment]
@HelgeT1 @uschreib @anste @jwsp1 Did you tried the last 3.4.3 DEV build?

**Comment by anste** [comment]
I'm not familiar with beta-testing in openhab. I tried again, while following the steps from READMEbeta.md. After clearing the cache the binding is initialised correctly.

The Shelly 1 now has a humidity channel with value NULL. The addon is actually used as "external switch".

**Comment by jwsp1** [comment]
> Did you tried the last 3.4.3 DEV build?

I have ordered a Shelly Plus 1 PM with the Plus Addon (not the old non-plus version). After I activated the Addon in the official Shelly App and added the sensors in the official Shelly App as well, channels for the sensors were automatically created in openhab. I'm on OH 3.4.3 stable.

**Comment by markus7017** [comment]
closed
check latest DEV build https://community.openhab.org/t/shelly-binding/56862/3311
