### ISSUE TITLE
Openhab 3 -> Disappear Colorpicker (found with HyperionNG Binding) - Global Issue ?

### ISSUE THREAD

**Issue by ChR-iSz** [openhab/openhab-addons#11299]
Looks like OpenHab 3 has a (general?) problem with ColorPickers if the ColorValue are NULL (as String).
The colorPicker a disappear in Widgets, Items and Sitemaps. No chance to select a color without a ColorPicker.
I see that in combination with the Hyperion NG Binding. Don't know if this is a global OH3 issue.
Not 100% sure if my attached Screenshot is the solution for this issue.

## Expected Behavior
Show ColorPicker Wheel

## Current Behavior
ColorPicker is hidden and can't open.

## Possible Solution
The Default Color Value are NULL. Change to 0,0,0 are working, and shows the ColorPicker.

## Steps to Reproduce (for Bugs)
1. Install HyperionNG Binding
2. Add Color Item
3. See the ColorPicker are not show if the Value are NULL.

## Your Environment
Openhab:
openHAB 3.2.0 (Latest)
Build #2473

HyperionNG:
Version | 2.0.0-alpha.10 (Latest)
Build | (HEAD detached at b1a4e95c) (Paulchen-Panther-975f969a/b1a4e95c-1626550299)

<img width="1087" alt="Bildschirmfoto 2021-09-24 um 18 27 23" src="https://user-images.githubusercontent.com/49807897/134711543-1733a292-d367-427e-8e39-397e50c4284f.png">

**Comment by ChR-iSz** [comment]
Is this relevant ? This was a habpanel issue for 4 year. Possible this still exist in OH3 ?

https://github.com/openhab/org.openhab.ui.habpanel/pull/175

**Comment by Rossko57** [comment]
Colorpicker is a UI feature.
It doesn't care what bindings may or may not be involved, it works on Item state
It has a deficiency in not working with Item states NULL or UNDEF
https://github.com/openhab/openhab-webui/issues/929

**Comment by ChR-iSz** [comment]
Okay, but it is not an option if the value are NULL or UNDEF, that the colorpicker nevertheless open with a default value 0,0,0 or 255,255,255 ?

The current problem are: If NULL or UNDEF the colorpicker not appear. So, i can't commit a new Value if i can't select a new color.

**Comment by Rossko57** [comment]
Yes.  It's a deficiency in the colorpicker UI, as registered in the other linked issue.  No-one has fixed it yet.

A workaround for now is to directly assign an initial value to your Item if it is NULL, by rule or REST.

**Comment by lsiepel** [comment]
Unfortunately this has not been fixed yet. But as this is an UI issue and there is an issue for that in the right repository, please continue here: https://github.com/openhab/openhab-webui/issues/929
