### ISSUE TITLE
[gpio] Invalid state of output channel after reboot

### ISSUE THREAD

**Issue by jsolanic** [openhab/openhab-addons#11296]
**My configuration:**

Openhabian: Raspbian GNU/Linux 10 (buster)
Raspberry Pi 3 Model B Rev 1.2
Openhab: 3.1.0

Thing gpio:pigpio-remote:local "GPIO localhost" [host="localhost", port=8888] {
    Channels:
        Type pigpio-digital-output : output-14 [ gpioId=14, invert=true] 
}

Switch RelaySwitch {channel="gpio:pigpio-remote:local:output-14" }

**Problem 1:**
After reboot is state of GPIO14 set to LOW and that means relay is switched ON. I would like to have it switched OFF.

GPIO 14: level=0 fsel=1 func=OUTPUT

**Proposed solution:** Add possibility to define initial value.

**Problem 2:**
My RelaySwitch item reposts invalid OFF state. GPIO14 is set to LOW and this state should be inverted which means it should be set to ON.

**Proposed solution:** Read GPIO state once GPIO thing is initialized.

**Temporary solution:** 
Initializing GPIO pins via /boot/config.txt - https://www.raspberrypi.org/documentation/computers/config_txt.html

gpio=14=op,dh

**Comment by jeremyrumpf** [comment]
[](https://github.com/openhab/openhab-addons/issues/11038#issuecomment-1048316787)Would you be able to test some changes I have made to the GPIO binding? I planed on using the binding to monitor some sensors in a building. I came across a lot of the same issues you are having. The biggest being that the binding does not reconnect to pigpiod. In my changes, there is now a heart beat configuration to poll pigpiod. If pigpiod goes away, a reconnect will be attempted at the heart beat frequency. The binding also properly reports when its state goes OFFLINE with a COMMUNICATION_ERROR and goes back ONLINE once pigpiod is reconnected.

Also, the binding features actions that it will perform based upon the pigpiod connection state. One of them is issuing a REFRESH on the channel to sync with the state of the GPIO pin. This would possibly resolve Problem 2 above. There is also a configurable action where you can force all outputs OFF at initialization.

If I can find at least one other person to validate my code, I will create a pull request for 3.3.0-SNAPSHOT. I created a build at: [https://github.com/jeremyrumpf/jeremyrumpf/blob/main/files/org.openhab.binding.gpio-3.3.0-SNAPSHOT.jar](https://github.com/openhab/openhab-addons/issues/url) To use it, you would have to uninstall the binding in OpenHAB (if you used the UI to install it) and add that jar file to /usr/share/openhab/addons (Linux)

The code is at: [https://github.com/jeremyrumpf/openhab-addons/tree/main/bundles/org.openhab.binding.gpio](https://github.com/openhab/openhab-addons/issues/url)

For you, a possible configuration would look like:

```
Thing gpio:pigpio-remote:local "GPIO localhost" [host="localhost", port=8888
                                                                                 heartBeatInterval=10000,
                                                                                 inputConnectAction="REFRESH",
                                                                                 inputDisconnectAction="NOTHING",
                                                                                 inputReconnectAction="REFRESH",
                                                                                 outputConnectAction="REFRESH",
                                                                                 outputDisconnectAction="NOTHING",
                                                                                 outputReconnectAction="REFRESH" ] {
Channels:
Type pigpio-digital-output : output-14 [ gpioId=14, invert=true]
}
```
Other possible outputConnectActions couid be: ALLON or ALLOFF

The version of Java i am using is:

`openjdk 11.0.14 2022-01-18 LTS`
`OpenJDK Runtime Environment 18.9 (build 11.0.14+9-LTS)`

Regards,
Jeremy

**Comment by lsiepel** [comment]
A somewhat related PR is now merged. I cannot fully asses if that fixes this issue. Can someone verify that https://github.com/openhab/openhab-addons/pull/13643 fxies this issue?
That PR is avaiable from the next snapshot and or milestone (4.1) ?

**Comment by jeremyrumpf** [comment]
IIRC, they were wanting the outputs state to be set during initialization
of the binding and to honor the invert flag.

#13643 makes this behaviour configurable by the user via the Output Channel
Connect Action and Output Channel Reconnect Action options.

Hopefully they can verify if they made use of #13643 and if it worked for
them.
