### ISSUE TITLE
[goecharger] Add eto and amx fields from API

### ISSUE THREAD

**Issue by lujop** [openhab/openhab-addons#11330]
There are two fields from [goEcharger API](https://github.com/goecharger/go-eCharger-API-v1/blob/master/go-eCharger%20API%20v1%20EN.md) that I think will be very useful:

- `amx`: It's like `amp`  (currently mapped to `maxCurrent`) but not persisted to flash, and it's the one recommended for PV charging. Recently I had a problem with a grid power outage where the charger flash memory was corrupted and support said that it was because a writing operation occurred during the outage. Then it's good idea to don't write the `amp` frequently for PV charghing.
- `eto`: Total charge consumed energy

I will try to contribute with a PR

**Comment by Drazhar** [comment]
Hey @lujop 

This was already done by @chilobo in his pull request #10903 (also see #10836). As far as I understand, there is just an issue with the signoff of his commit.

**Comment by lsiepel** [comment]
If i check all the (merged and some closed) PR's it looks like this issue is resolved. Can you confirm?
