### ISSUE TITLE
[iRobot] Vacuum cleaner not cleaning room

### ISSUE THREAD

**Issue by Nuesel** [openhab/openhab-addons#11340]
Hello all,
I'm trying to use my iRobot Roomba from Openhab, especially cleaning special rooms is important for me. Unfortunately, my iRobot Roomba i7 starts cleaning everything instead of cleaning only one room.

The problem seems to be the parameter _user_pmapv_id_, that is omnitted when sending the vacuum cleaner on its mission. The robot expects a command of the syntax
{"command":"start","initiator":"rmtApp","time":1633160056,"ordered":1,"pmap_id":"mymapid123456789012345","regions":[{"region_id":"18","type":"rid"}],"user_pmapv_id":"123456T123456"}
Currently, the iRobot addon does not pass _user_pmapv_id_. Consequently, last_command contains _user_pmapv_id_, but it is set to _null_. Maybe, older versions of the Roomba software did not need this parameter. But now it is obligatory.
I think, I managed somehow to add this feature in the addon (files RoombaHandler.java and MQTTProtocol.java). How do I create branch?

Additionally, the iRobot addon is not able to let the Roomba clean special zones. A region corresponds to whole rooms, zones are user defined rectangle areas within rooms. For zones, the type must not be "rid" but "zid" (zone ID). Currently, in the Java code the type is fixed to "rid". Honestly, I don't know how add this parameter since my Java knowledge is very limited. I feel a bit strange about this gson stuff.

My iRobot uses the software version 3.18.11 (currently up to date).
Thanks for any help in advance!

Regards,
Nuesel

**Comment by lolodomo** [comment]
Pinging the author of the binding: @Sonic-Amiga

**Comment by Nuesel** [comment]
Hello!
I tried to find out more about lambda expression. But the problem I'm still facing is `type` in
`this.regions = Arrays.stream(regions).map(i -> new Region(i, type)).collect(Collectors.toList());`
is not a constant String but also a String array. Each entry in the arrays `regions` and `type`, respectively, are a pair. E.g. `regions[2]` and `type[2]` should contain a pair of information.
I'm afraid, the `map` method cannot resolve such a problem. Maybe I will try it via an ordinary for loop.
Thanks a lot for your help! I appreciate that.

**Comment by Sonic-Amiga** [comment]
So in my example one type value would apply to all elements in the list. Do you need to break it and specify "type" for each region string ? Yes, in this case you'll be rewriting the whole thing. And yes, a map() method iterates only one thing, not two things simultaneously. So if you have two arrays, and want to iterate over both of them using the same indices for both, yes, you'd better scrap this modern sexy approach and write a conventional for loop.

**Comment by lsiepel** [comment]
Looks like this issue was fixed with PR [#11783](https://github.com/openhab/openhab-addons/pull/11783), i fnot pelase feel te re-open.
