### ISSUE TITLE
[smartmeter] No serial connection possible

### ISSUE THREAD

**Issue by stickybyte** [openhab/openhab-addons#11358]
## Expected Behavior

When connecting an IR-Reader to the RPi, the binding should open a serial connection to /dev/ttyUSBX
and receive the stream of data.

## Current Behavior

The binding is unable to open an connection, providing an error message through the log:

`Thing 'smartmeter:meter:55ebc5fba0' changed from UNKNOWN (HANDLER_CONFIGURATION_PENDING): Waiting for messages from device to OFFLINE (COMMUNICATION_ERROR): No provider for port /dev/ttyUSB1 found`

Sideinfo: When opening a screen-session to that serial port, you can see an encrypted bytestream. So data will be received!

## Possible Solution

No idea yet. Maybe the libariers which are opening the connection are buggy?

## Steps to Reproduce (for Bugs)

1. Connect IR-Reader
2. Install smartmeter binding
3. Check `dmesg` and get the correct serial port
4. Add Thing
5. See logfile

## Context

Without solving this issue by the developers everyone will be unable to receive data from their smartmeters anymore.
I'll track this issue and provide all necessary informations if requested ...

## Your Environment

* Version used: latest
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): -
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian latest

**Comment by Digitalvitamin** [comment]
@stickybyte: did you find a solution or workaround in the meantime? I ran into the same issue (see [openHAB community](https://community.openhab.org/t/no-serial-connection-with-smartmeter-binding-after-update-to-oh3/135469))

**Comment by wborn** [comment]
Duplicates https://github.com/openhab/openhab-core/issues/2474
