### ISSUE TITLE
[openwebnet] support for WHO=0 Scenarios

### ISSUE THREAD

**Issue by RubenFuser** [openhab/openhab-addons#11378]
hello, i'm working with openhab 3 with openwebnet binding installed but with my surprise WHO=0 scenarios are not supported.
is it possible to add the support for this?

thanks a lot

**Comment by mvalla** [comment]
are you interested in activating a scenario from OH ?  or being notified in OH when a scenario gets activated in your system?

**Comment by RubenFuser** [comment]
The idea is that when rhe physical button is pressed,it calls a scenario/rule in openhab.

**Comment by mvalla** [comment]
it would be useful then if you configure one of the physical buttons you want to use in the BTicino system, activate official OpenWebNet Client monitor mode and then copy here which messages are sent on the BUS

**Comment by RubenFuser** [comment]
if i press the scenario #1 i have this: *0*1*95##
if i press the scenario #2 i have this: *0*2*95##
if i press the scenario #3 i have this: *0*3*95##
if i press the scenario #4 i have this: *0*4*95##

thanks

**Comment by mvalla** [comment]
Can you use code fences? Just to be sure of the format of the message. See the < > button when editing the message

**Comment by RubenFuser** [comment]
yes you're right, was wrong formatted:

`*0*2*95##`

this is now right.

**Comment by mvalla** [comment]
@RubenFuser to check if configured scenarios panels can be discovered, can you try this command again with the BTicino client?
(then paste here the image of the output):
`*#0*0##`

**Comment by RubenFuser** [comment]
![image](https://user-images.githubusercontent.com/92428083/170880650-0bc1c858-0da3-4d0b-9b6c-615979af5365.png)

this is output. i have set on one scenario button, to open all rollershutters, so you'll see open command for 5 rollershutters and stop command for rollershutters.

thanks

**Comment by mvalla** [comment]
ok, so this test shows that Scenarios WHO=0 cannot be discovered automatically, at least not with the command: `*#0*0##`.
They must be configured manually or using Discovery by Activation as it's explained in the binding readme.

**Comment by RubenFuser** [comment]
So just to recap, i can do auto discover by pressing the physical button. Do i need to update binding with a special release? Which version?

**Comment by mvalla** [comment]
look at the messages/threads on the openHAB community forum

**Comment by RubenFuser** [comment]
if i press the scenario physical button number 2, the command that i see is `0*2*95##`
i've put the binding in scanning mode, but if i press the physical button of the scenario 2, it isn't detected by the binding.
mine should be CEN scenario...
so actually there isn't a way to detect scenario module. and on LCD i could be able to configure 16 scenarios... :(

**Comment by mvalla** [comment]
> i've put the binding in scanning mode, but if i press the physical button of the scenario 2, it isn't detected by the binding.
this is strange. Can you provide me the log in DEBUG mode? from when you start the scanning (and then you press the scenario 2 physical button) until it's finished.

> mine should be CEN scenario...
I do not understand what you mean here..

in conclusion: were you able to detect the activation of WHO=0 scenario 2 from a openHAB rule thanks to the test version of the binding I provided on the marketplace?

**Comment by mvalla** [comment]
hi @RubenFuser did you have time to further test the binding I have put on the Marketplace with WHO=0 support?
If it works for you I could try have it added to the official 3.3.0 release of openHAB which is due very soon..

**Comment by RubenFuser** [comment]
Ciao! Not yet,i hope to have time this late afternoon. I’ll keep you posted.

thx

**Comment by RubenFuser** [comment]
> > i've put the binding in scanning mode, but if i press the physical button of the scenario 2, it isn't detected by the binding.
> 
> this is strange. Can you provide me the log in DEBUG mode? from when you start the scanning (and then you press the scenario 2 physical button) until the scanning it's finished.
> 
> > mine should be CEN scenario...
> 
> I do not understand what you mean here: here we are talking about WHO=0 scenarios, CEN/CEN+ scenarios are already fully supported by the binding
> 
> In conclusion: were you able to detect the activation of WHO=0 scenario 2 from a openHAB rule thanks to the test version of the binding [I provided on the marketplace](https://community.openhab.org/t/openwebnet-binding-beta/129775/35?u=massi)?

For debug mode,we already discussed about this in the openhab forum and it’s where you told me that “funcion” has been removed because it’s old (or something like this). Let me know if you need again the debug output :)

**Comment by RubenFuser** [comment]
update: with new test binding i've created a rule and seems to work. 
just a couple of things that are not ok: 
- device is detected as BURGLAR_ALARM.
-  it detects in scanning mode, only from 1 to 8 scenarios. how can i add virtual scenarios configured in Bticino LCD?
- if i add the jar in addons folder, it won't work. i need to uninstall the main binding from UI, install the binding from marketplace, and it will also install the main one. this way works.
- after RPI/openhab restart, the binding stop to work and i need to uninstall/reinstall it.

should be all from my tests...

thanks

**Comment by mvalla** [comment]
Closed by #13473
