### ISSUE TITLE
Add Kichler Lighting - LED Landscape controller to Z-Wave database

### ISSUE THREAD

**Issue by freejoule** [openhab/openhab-addons#1139]
Hi @cdjackson ,
Sorry if I'm not posting in the correct place.  I tried [here ](http://www.cd-jackson.com/index.php/zwave/z-wave-device-database/)but no luck finding the tools button.

I have a Kichler Lighting - Design Pro LED Controller for landscape lighting control I would like to add to the OH2 Z-Wave database.  This is a 4-zone power supply/transformer for low voltage LED landscape lights. product info: http://www.kichler.com/products/product/200w-dc-led-controller-15dc200.aspx

Model: 15DC200  
Rev: 012.414

attached is the XML file generated by OH2

thanks!
[node22.txt](https://github.com/openhab/openhab2-addons/files/375131/node22.txt)

**Comment by johannrichard** [comment]
@cdjackson the Manufacturer (Kichler Lighting, ID 0114) is currently missing, and I have only edit rights on the devices, otherwise I'd be happy to upload and add the device to the Database.

@freejoule you have to specifically ask for edit access (by mail) to be able to submit yourself. Once you have this access, adding the device is a breeze.

**Comment by cdjackson** [comment]
@johannrichard thanks. Sorry - I missed this.  I've just added Kichler to the database.

@freejoule I've also given you edit access to the database.

I've also loaded your XML and it's created the device in the database. I don't know if there are configuration and association information supported - it would be good to get a manual uploaded and any config parameters added... Anyway - you have access, so please feel free to add...

**Comment by cdjackson** [comment]
Link to database -:
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/391

**Comment by cdjackson** [comment]
I found the manual and loaded it to the database. It doesn't seem to indicate that there are any config parameters so I'll add this to the binding as it is.

**Comment by cdjackson** [comment]
This is now in the binding
