### ISSUE TITLE
[tr064] MacOnline for Guest Wifi reports UNDEF, if device is offline

### ISSUE THREAD

**Issue by mpmario** [openhab/openhab-addons#11390]
## Expected Behavior

When a device in the guest wifi network, defined by its MAC address is offline, the switch of the macOnline channel should be OFF. If it is online, the switch should be ON (like a device in the normal wifi network).

## Current Behavior

When a device in the guest wifi network, defined by its MAC address is offline, the switch of the macOnline channel is UNDEF. If the device is online, the switch is ON.

## Steps to Reproduce (for Bugs)

1. Add a new MAC address in the parameter list of the subdeviceLan thing.
2. Create a new switch item in the new macOnline channel.
3. Turn the device on and off and observe the status of the switch.

## Your Environment

* Version used: openHAB 3.1.0, tr-064 Version 3.1.0
* Environment name and version: Node.js v12.22.7, Zulu11.45+27-CA
* Operating System and version: Raspbian GNU/Linux 10 (buster)

**Comment by J-N-K** [comment]
IIRC this has been discussed before. FritzBox does only report if a MAC is present, not if it was present before and now missing. Therefore `UNDEF` is IMO the correct value if the FritzBox reports 704/NoSuchEntryInArray and so this is not a bug.

I think you can use the `TRANSFORM` profile with the `MAP` transformation to map `UNDEF` to `OFF` if that better fits your needs.
