### ISSUE TITLE
[lifx] Support for LIFX WW 1000lm

### ISSUE THREAD

**Issue by jwindhager** [openhab/openhab-addons#11402]
Hi

I'm relatively new to OpenHAB and was amazed how easy it was to set up the Binding for my LIFX (A19) bulb. However, I also have two [LIFX White to Warm](https://lifxshop.co.uk/products/lifx-white-to-warm) (Model as per the LIFX app: `LIFX WW 1000lm`) at home, for which the autodiscovery didn't work and the temperature range isn't fully covered. I suspect that the current OpenHAB Binding does not support the 1500-9000K [LIFX Downlight White to Warm](https://github.com/LIFX/products/blob/dd692a341125a1c7b7397e058ee0d0f20f120a36/products.json#L418-L431) product, but (maybe?) recognizes the light as a LIFX **Candle** White to Warm with a 2200-6000K range instead.

## Your Environment
* Version used: openHAB 3.1.0
* Environment: Raspberry Pi Zero W
* Operating System and version: Raspbian Buster

**Comment by wborn** [comment]
> I suspect that the current OpenHAB Binding does not support the 1500-9000K LIFX Downlight White to Warm product

It should already be supported, see:

https://github.com/openhab/openhab-addons/blob/79a9aba15f61f280fd66490037835fc058ae80a0/bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxProduct.java#L65-L66

> but (maybe?) recognizes the light as a LIFX Candle White to Warm with a 2200-6000K range instead

You can check in the "Thing Properties" what kind of "Product ID" and "Product Name" is detected. 

It uses UDP broadcasts to discover lights. So if lights are in another subnet they cannot be discovered.

**Comment by jwindhager** [comment]
Hi @wborn, thanks for the quick reply! Since the light wasn't auto-discovered (even though they are on the same subnet), I added them manually by specifying the MAC. This is how it looks now:

![image](https://user-images.githubusercontent.com/7105759/137649874-50c00af6-bf84-4a98-9f3c-6fd380a668bb.png)

It appears the light is actually not detected as Product ID 39 (LIFX Downlight White to Warm), but identifies as Product ID 114 (LIFX Mini WW Intl). Apparently, my guess that the LIFX WW 1000lm would correspond to Product ID 39 was wrong, apologies. In any case, from the file you linked, it seems that LIFX IDs larger than 111 are still missing in the OpenHAB binding. Would that explain the issues with auto-discovery and temperature range?
