### ISSUE TITLE
[astro] should respect configured earliest or latest channel time

### ISSUE THREAD

**Issue by beulenbilly** [openhab/openhab-addons#11424]
## Your Environment
* Version used: OH 3.1

## Description
Due to a lack of light and temperature sensors I use the astro channels to control the rolloshutter especially in summer. To be sure that is really dark outside and get cooler air inside I use the astronomic dawn. But in summer the range end is null, if you use:
- lat: 53.5214675
- lon: 10.043392
- altitude: 10
- date: 21.06.2021, 8pm

In this case no event is triggered because of org.openhab.binding.astro.internal.job.Job line 122 even if the latest-property is configured for the channel.

## Expected Behavior
If there is a latest time configured for the channel I would expect that the time will be applied.

## Possible Solution
https://github.com/beulenbilly/openhab-addons/commit/2a91a6c312954a887a01ca713996a9ddae3f47ff

I am not really happy about adding the test-dependency as well as mocking the static method calls...

**Comment by lsiepel** [comment]
@beulenbilly i think it might get complex. If both earliest start and end are configured, and the ‘force’ configuration option is set. What value should replace the null? Earliest start or earliest end?

**Comment by lsiepel** [comment]
Think i have a fix, could you look at the PR?

**Comment by beulenbilly** [comment]
Hey @lsiepel the implementation looks really good.
I am not sure if everything works with the time calculation for start and end but your test will proof it.

Thanks.
