### ISSUE TITLE
[Tesla] Tesla add "set_charging_amps" from 2021.36

### ISSUE THREAD

**Issue by LuggyLuke** [openhab/openhab-addons#11483]
Please add the "set_charging_amps" channel added in version 2021.36.
It enables the setting of the actual charging current via a command. 
I think this feature could be quite handy for all Solar users combining it with a Tesla, that way the chargin current can be adapted to the current Solar power, instead of starting/stopping the process based on thresholds. 
for further info i found a discussion on the teslamotorclub forum: 

https://teslamotorsclub.com/tmc/threads/model-s-rest-api.13410/page-148 

Thanks & greetings

**Comment by ipweb2000** [comment]
+1. that would be great and an easier and more general way than via TWCManager

**Comment by phuongpham** [comment]
I'm happy to test out this "feature"

**Comment by DollC** [comment]
+1 I am also very interested to have this feature. If you need someone to test. I can do

**Comment by DollC** [comment]
Thanks. I just installed the snapshot of 3.3.0 and it works. I can set chargingamps an see it directly in the app of my model 3

**Comment by phuongpham** [comment]
Ok I managed to install the  binding 
321 │ Active │  80 │ 3.3.0.202201130406    │ openHAB Add-ons :: Bundles :: Tesla Binding

But I can't see the new channels.
I have tried to delete the thing and added again.
But same results.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/2634344/149614698-694bf018-6175-4ee7-b4ef-10cf0caff315.png">

**Comment by phuongpham** [comment]
Ok.
I managed to get this working. Seems like the previous binding was wrong version.
I installed follow version  3.3.0.202201150408 
I downloaded from https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220115.032535-24.jar

**Comment by ipweb2000** [comment]
Hey guys. I am having trouble to get the snapshot binding to run. Any suggestions? Thanks for your help!

> 12:36:27.715 [WARN ] [org.apache.felix.fileinstall         ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.tesla-3.3.0-20220115.032535-24.jar
> org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.tesla [291]
>   Unresolved requirement: Import-Package: org.jsoup; version="[1.14.0,2.0.0)"
> 
>         at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.300.jar:?]
>         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.16.300.jar:?]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.7.2]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.7.2]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.7.2]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.2]
>         at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.2]

**Comment by Azrael-Masters** [comment]
> 6
Try to install the requirement first, with OpenHAB [CLI](https://www.openhab.org/docs/administration/console.html).
`bundle:install https://repo1.maven.org/maven2/org/jsoup/jsoup/1.14.3/jsoup-1.14.3.jar`

**Comment by kaikreuzer** [comment]
I had implemented this feature already with https://github.com/openhab/openhab-addons/issues/11483#issuecomment-1061726929, so it is part of 3.3.0.M1 and 3.3.0.M2. No need to manually install it.
