### ISSUE TITLE
[telegram] Buttons in multiple Lines with sendTelegramQuery

### ISSUE THREAD

**Issue by agh251256** [openhab/openhab-addons#11482]
I`m using OH3.1 

What I need is a Tip. Momently the command sendTelegramQuery(text, replayid, button, button,......) show all button in one line.
**[button] [button] [button]** and so on.
How can I using multiple lines e.g.:
**[button] [button] [button]
[   button   ] [   button   ]**

The examples don`t nothing say about this feature.

**Comment by Skinah** [comment]
Possibly you mean this feature which is not yet implemented.

https://github.com/openhab/openhab-addons/issues/7279

Check out what the java library supports and can be added.
https://github.com/pengrad/java-telegram-bot-api#keyboards

**Comment by agh251256** [comment]
Yes, it is

**Comment by oriolfg** [comment]
Please!! Is a great idea implement the multiline in send query,  when send 4 options is impossible read all in one line

**Comment by lsiepel** [comment]
Let's continue in https://github.com/openhab/openhab-addons/issues/7279 as that seems to request the exact same feature.
