### ISSUE TITLE
Bindings translation in French

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#11490]
We have 60 bindings available for translation in Crowdin (first November of 2021).

We have in the addons repo 21 bindings with a French translation.

Here are the bindings still to be fixed, with a French translation in the addons repo but not available in Crowdin (no default properties file defined):

- [x] airquality => #11192 
- [x] meteoblue => #11561 
- [x] netatmo => binding refactored, available for translation in Crowdin
- [x] vigicrues => #11495

Here are the bindings requiring an optimization if the properties files:

- [x] hue => #11535  

Here are the partial (in progress) translations of bindings in Crowdin:

- [x] astro => #11573
- [x] hue => #11608 
- [x] nikohomecontrol => #11712 
- [x] openuv => #11539
- [x] openweathermap => #11807 
- [x] powermax => #11539 
- [x] tr064 => #11573 
- [x] tradfri => #11518 
- [x] volvooncall => #11573 

Here are the bindings requiring a change for discovery result:

- [ ] airquality
- [x] hue => #11501
- [x] openuv => #11500
- [ ] powermax
- [x] tradfri => #11498

@clinique for information and support

**Comment by lolodomo** [comment]
As a reminder: openhab/openhab-core#2544

**Comment by clinique** [comment]
I'll give you a help @lolodomo , please do not do anything on Netatmo current version. The one under PR has crowdin included, and I would prefer having to fight with file conflicts.

**Comment by lolodomo** [comment]
@clinique : I am going to create the default properties file for the vigicrues binding. There is nothing special to handle.

**Comment by lolodomo** [comment]
@clinique : while I was managing the vigicrues binding, I was very surprised to discover only 3 channels on my thing. I then tried with the last snapshot (2541) and that is the same thing.

![image](https://user-images.githubusercontent.com/10186704/139705069-a5f2e2df-93eb-42f2-99ac-993162cc6c86.png)

I found this log entry: : Historical flooding data are not available H226000102 : null
Is your binding removing some of the channels ?

**Comment by clinique** [comment]
Yes, it depends upon available data for the considered station

**Comment by clinique** [comment]
@lolodomo : for AirQuality, please note that there is currently a PR pending that incorporates crowdin compatibility.

**Comment by lolodomo** [comment]
@clinique : I think this is a little useless to start a translation when the default properties file is not full, like for example the lametrictime binding. First the default properties file must be updated.

**Comment by clinique** [comment]
@lolodomo : ok, clear.

**Comment by lolodomo** [comment]
@clinique : note that for openuv, few strings are still to be translated. For airquality, a change will be required to make the discovery label translatable.

**Comment by lolodomo** [comment]
@clinique: for the astro binding, did you start a translation from scratch in Crowdin ? Because we already have a file in Github, probably not full.

**Comment by clinique** [comment]
@lolodomo : finished translations for OpenUV in crowdin. Astro : yes, I started it in Crowdin directly.

**Comment by lolodomo** [comment]
> Astro : yes, I started it in Crowdin directly.

If it was empty, it is not normal as the work was already done directly in girhub. 
I will probably import the existing file from girhub inside Crowdin, hoping your proposals will not be erased in Crowdin so that I can then choose the best.

**Comment by lolodomo** [comment]
> 
> 
> > Astro : yes, I started it in Crowdin directly.
> 
> If it was empty, it is not normal as the work was already done directly in girhub. I will probably import the existing file from girhub inside Crowdin, hoping your proposals will not be erased in Crowdin so that I can then choose the best.

The file in github is for `tr` not `fr` ! So there is no problem and you can continue in Crowdin. I am going to start approving your proposals.

**Comment by lolodomo** [comment]
> 
> 
> @lolodomo : finished translations for OpenUV in crowdin. Astro : yes, I started it in Crowdin directly.

This is now in the current PR.

**Comment by clinique** [comment]
@lolodomo : VolvoOnCall finished in Crowdin

**Comment by lolodomo** [comment]
> @lolodomo : VolvoOnCall finished in Crowdin

Thank you @clinique , the PR is now opened.

**Comment by lolodomo** [comment]
Considering all your bindings @clinique, a French translation is now available except for your xmltv binding. Do you need my help to produce the default properties file ?
The netatmo binding is an exception due to your in progress refactoring.
The meteoalerte binding is another exception as French is directly provided as default !

On my side, I have the freebox binding with a missing French translation but we have your new binding freeboxos coming.
For me, remains some work still to do with the powermax and the remoteopenhab bindings.

**Comment by clinique** [comment]
Xmltv binding translation is nearly ready and will be submitted soon

**Comment by lolodomo** [comment]
I have a real difficulty with a proper translation of openHAB concepts like "thing" and "channel". Using "ce thing" or "cette chose" make no sense for me ;)
WDYT ?

**Comment by mherwege** [comment]
From my perspective, the Niko Home Control French translation is complete in Crowdin. But I am not a native French speaker. It needs to be reviewed and the translation needs to be accepted, which I cannot do. Niko is a Belgian product. I did the translation in Dutch as well, which is already available. Adding French makes a lot of sense.

**Comment by lolodomo** [comment]
> From my perspective, the Niko Home Control French translation is complete in Crowdin. But I am not a native French speaker. It needs to be reviewed and the translation needs to be accepted, which I cannot do. Niko is a Belgian product. I did the translation in Dutch as well, which is already available. Adding French makes a lot of sense.

Yes, this is in my TODO list. When I took a look, I was not fully satisfied with the proposed translation ;)
This will be before the official 3.2 version is released.

**Comment by lolodomo** [comment]
> > From my perspective, the Niko Home Control French translation is complete in Crowdin. But I am not a native French speaker. It needs to be reviewed and the translation needs to be accepted, which I cannot do. Niko is a Belgian product. I did the translation in Dutch as well, which is already available. Adding French makes a lot of sense.
> 
> Yes, this is in my TODO list. When I took a look, I was not fully satisfied with the proposed translation ;) This will be before the official 3.2 version is released.

This is now done.

**Comment by lolodomo** [comment]
I close this issue as my initial intention was to follow the migration of all existing French translations in Crowdin.
This is done now.
For the Netatmo binding, new translations have to be filled in Crowdin now that the binding was fully refactored.
