### ISSUE TITLE
[icalendar] Not ussing SNI in the https request

### ISSUE THREAD

**Issue by mpiscaer** [openhab/openhab-addons#11491]
## Expected Behavior
Using SNI in the https request. A hostname can be virtual.

## Current Behavior
Currenly there is no hostname in the TLS headers. And so if the TLS cert is an alias or virtual name, the server does not use the correct Vhost.

## Possible Solution
Currently not know.

## Steps to Reproduce (for Bugs)
1. Us a https URL in the tcpdump you don't see the server_name extention
2.

## Context
Try to setup ICalendar.

## Your Environment
I'm using OpenHab 3.1.0 and ICalendar 3.1.0

**Comment by daMihe** [comment]
Sorry, can't reproduce, as i'm using it with a virtual host (and not the default one). Please add a proof. This would also be an issue of the core, as the global shared HTTPClient is used.
