### ISSUE TITLE
[hdpowerview] Provide channels for switching automations on and off

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#11516]
A few times per year I go into the PowerView app and switch one automation **on** and another one **off**. In the summer I want the shades to go up at a specific time to wake up the kids with sunlight. In the fall when the sun rises later than wake-up time, I disable this automation and enable another one for having the shades up at sunrise. And again the opposite in the spring when the sun will start to rise too early again. Same scenario in bedroom, just different fixed time, so also different date for switching automations. Same for sunset, so again different dates.

The reason for using the PowerView automations is to have fewer dependencies. The Hunter Douglas Hub provides the needed options for activating scenes at a fixed time, sunrise/sunset or offsets from sunrise/sunset. So this works fine without a dependency to openHAB and the hardware it runs on.

What I would like the Hunter Douglas PowerView binding to do for me is managing the automations, i.e. with the Astro binding and some rules to enable/disable specific automations when needed.

With Packet Capture for Android it was a matter of seconds to find the API calls needed for this.

**GET /api/scheduledevents/**

to find all automations. Each of them can refer to either a sceneId or sceneCollectionId, for example:
```
		{
			"enabled": true,
			"sceneCollectionId": 27119,
			"daySunday": false,
			"dayMonday": true,
			"dayTuesday": true,
			"dayWednesday": true,
			"dayThursday": true,
			"dayFriday": true,
			"daySaturday": false,
			"eventType": 1,
			"hour": 0,
			"minute": 0,
			"id": 1262
		},
```

To disable this:
**PUT /api/scheduledevents/1262**

with payload
```
{
	"scheduledEvent": {
		"dayFriday": true,
		"dayMonday": true,
		"daySaturday": false,
		"daySunday": false,
		"dayThursday": true,
		"dayTuesday": true,
		"dayWednesday": true,
		"enabled": false,
		"eventType": 1,
		"hour": 0,
		"id": 1262,
		"minute": 0,
		"sceneCollectionId": 27119
	}
}
```

Scenes are fetched with **GET /api/scenes/** and scene collections with **GET /api/sceneCollections/**. Names are Base64-encoded.

**Comment by jlaur** [comment]
Created #11533 for scene collection support as prerequisite for fully supporting scheduled events.

**Comment by andrewfg** [comment]
Watching this..

**Comment by jlaur** [comment]
@andrewfg - any thoughts on implementation? I'll probably wait for #11534 to be merged before starting the work. Currently I'm considering whether it should be implemented as a thing or as dynamic channels for the hub thing, like scenes.

Simply adding channels for the hub would be consistent with how scenes are implemented. But adding new things might be cleaner and would also provide opportunity for multiple channels for each automation thing which could even make it possible to change the automation, not just enable/disable it.

**Comment by andrewfg** [comment]
^
Hmm. Just a few quick thoughts. (Maybe more later..)
- If scene collections are no longer supported by HD then I suppose that they (will)-have changed the REST API syntax so that instead of referring to a `sceneCollectionId`  it (will)-now refer to one (or more?) `sceneId`'s?
- If that is the case, then you may need to GET resp. parse an old and a new version of the REST payload to handle both such cases (and add the respective JUnit tests).
- In any case I would suggest to implement each automation as a separate Thing; then you can have separate channels for e.g. `enabled` and `day` (e.g. a 7 bit binary flag 0b1111111 having one bit for each day) and `sceneId` resp. `sceneCollectionId`..
- Don't forget the global variable `EnableScheduledEvents` which you will need to support too..

**Comment by andrewfg** [comment]
^
@jlaur isn’t there now some inconsistency with the new app? The JSON you posted above for automations refers to scene collections. According to HD scene collections are no longer supported in the app. But you have shown elsewhere that they can still be created via the REST API. However the fact that automations can still be created in the app seems to imply that when one is created, the app is still creating a hidden scene collection to link the automation to the respective scenes? Or??

**Comment by jlaur** [comment]
@andrewfg - not exactly. Scene collections are still supported by the hub, and the app also still supports editing and deleting them - but no longer supports creating new ones. Automations supports both scenes and scene collections - both are still supported by the app, but obviously, in order to create a scene collection automation, you would need to have one, i.e. created by previous version of the app, or directly through the API. Automations for scenes do not reference scene collections.

**Comment by andrewfg** [comment]
> Automations for scenes do not reference scene collections.

Aha. So if, as described in this Issue, you would create a Thing for the automation, then it would need to have a different Channel structure depending on whether it relates to a scene or a scene collection. So perhaps the Thing/Channel model is not such a good idea after all?

**Comment by jlaur** [comment]
@andrewfg - I have given it a few more thoughts. Being able to edit the automations from openHAB doesn't make much sense or bring much value. Why would anyone want to automate editing automations? IMHO the only functionality really needed is being able to enable/disable automations already created (and maintained) in the PowerView app. The question is still how to provide the best structure for this. Simply adding dynamic channels to the bridge (like scenes and scene groups) could be enough, but it might become kind of messy. Maybe we should consider a channel group for each type:
- Scene
- Scene Group
- Automation

We don't need two different types of automations as it doesn't matter to the user if the underlying configured automation refers to a scene or a scene group. When flipping the **enabled** property, all other properties should simply be preserved.

**Comment by jlaur** [comment]
Today found some time to start implementation. The approach I suggested would look like something like this:
![image](https://user-images.githubusercontent.com/19519842/143138931-1e032caa-5708-4d93-ba80-8bd97154442d.png)
