### ISSUE TITLE
[ipcamera] expose a camera ipAddress as a channel 

### ISSUE THREAD

**Issue by ares** [openhab/openhab-addons#11514]
## Your Environment
OpenHAB 3 deployed on Debian from the official repos

* Version used: (e.g., openHAB and add-on versions)
3.1.0 for both openhab and openhab-addons

* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
not relevant

* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
not relevant

It would be very handy to expose the ipAddress (and potentially other configuration options) of a Thing as a channel, so I could easily create a String Item linked to it. That way I could easily construct URLs in my rules without duplicating the IP in the rule. Also since I have multiple cameras, I could iterate over a group of items and use their IPs for a group commands, e.g. to set the DST timezone on them. It seems people prefer to store these information in constants, however since we already define it when defining a Thing, why not making it available from there?

I tried to parse out that information from other channels like imageUrl but of course that doesn't work, since that's OH url in fact.

**Comment by jimtng** [comment]
I agree, this would be a good feature.

**Comment by clinique** [comment]
I think it would somehow be better to enable access to configuration elements and properties of a thing instead of created duplication of informations with channels.

**Comment by jimtng** [comment]
> I think it would somehow be better to enable access to configuration elements and properties of a thing instead of created duplication of informations with channels.

Since the configuration includes the camera's login and password, I'm not sure I want to make it easy for everyone to have access to them via item's REST.

**Comment by clinique** [comment]
> > I think it would somehow be better to enable access to configuration elements and properties of a thing instead of created duplication of informations with channels.
> 
> Since the configuration includes the camera's login and password, I'm not sure I want to make it easy for everyone to have access to them via item's REST.

Sure but properties, why not - and configuration items has a context elements that could be omitted or obfuscated from REST answers.

**Comment by Skinah** [comment]
Agree it does not make sense to do it as a channel. It does not change, so I can't see a use case to use it as a trigger for a rule/automation, so as a channel it seems wrong. 

The two different suggested ways are. 1. Config data and 2. thing properties

Passwords are marked as a password (context) in the XML file, so the core can always refuse to supply any passwords to the REST. There would be other configs like an API key/secret for a cloud service, or a security key for the zigbee binding that may not be marked as a password context, so this may need someone to review every single addon to see if a security issue requires a config to be marked as a 'password'. If there would be further ripple effects I do not know as the core is not something I know very well.

An idea may be to add a new config parameter called 'exposed' that ONLY allows any configs that are marked with this to be accessible, and this would remove the need to review all addons. This is probably the way I would prefer it is done but it is not up to me and I don't understand the core very well.

example:
```
<parameter name="String" type="{text|integer|decimal|boolean}" min="Decimal" max="Decimal" step="Decimal" pattern="String" required="{true|false}" exposed="{true|false}"
```

I suggest you ask this question in the core github issues, if...

A new config parameter can be added that allows marked config elements to be accessed in rules/scripts/automations. The above example may help to clear up what is being asked. Also make sure you explain the use case and why you want to do it as they may say a better way that makes more sense to solve the feature request.

**Comment by ares** [comment]
Use case: I have multiple IP cameras on which I need to change the timezone because of daylight saving twice a year. I want to have a sitemap switch which basically says "DST: on/off" that flips the TZ on all of those cameras.

The TZ is changed by the API call to the camera, e.g. http://camera-ip/api/change_tz. The rule would find all items in a given group, e.g. cameras and for each such camera it would perform the API call. However I need to be able to construct the proper URL based on the IP (ip-camera part of the URL.

I can hardcode the list of all cameras in the rule with their IPs (and credentials, port and what not) but that would duplicate the same info from the Thing definition. If the IP ever changes I need to remember to update it at two places.

The other option is to have the ability to modify the timezone through this binding natively, but I'm sure there's more usecases like this, that may need and explicit API call.

**Comment by Skinah** [comment]
I would recommend you use a hostname and not an IP, then it is set once in the router/dhcp and your scripts can use a hostname that can be set in a single place.

example:
```
 http://doorbell/api/change_tz
```

I would encourage anyone that wants the feature to follow through with a suggestion to the core as the above posts have explained then every binding can get the feature.

**Comment by ares** [comment]
Thanks for the suggestion with the hostname, but that doesn't really solve the issue. I'd then hardcode the hostname instead of an IP on two places. I understand this could be useful for other bindings too, if I understand you correctly, I should open and RFE there too, right?

**Comment by Skinah** [comment]
My opinion is that using a hostname is the solution that is used in networking everywhere so this is the best way forward if something is not added to the core, or it may exist already as I am not an expert.... If you want a new feature in the core then you need to convice someone to do the work for free, so take the time to do a neat and concise request for it. There are also the bounties you can set. Perhaps post this in the forum to see if it is already possible and how much support for it there is, then open up a request for the core AFTER the forum shows the support and that no other way exists.

I'll close this issue as it is asking for a channel in one binding and this does not mean you should not take it further as something all bindings could have access to.
