### ISSUE TITLE
[jdbc] multiple entries created for the same item

### ISSUE THREAD

**Issue by keesma** [openhab/openhab-addons#11526]
I am running openhab 3.2.0.M3. I noticed that my persistence database has multiple entries for the same item:
I use mysql with the jdbc connector.

A selection from the mysql database (table items):
|    484 | Crosstrainer_currentcalories                          |
|    485 | Crosstrainer_totaltime                                     |
|    486 | Crosstrainer_speed                                         |
|    487 | Crosstrainer_totaltime                                     |
|    488 | Crosstrainer_speed                                         |

These entries were created quite recently (while running 3.2.0M3).
The entries were probably created by setting the type of the Item to Measurement (could not find this in the documentation).
Entries that listed at least twice are not defined in the text file (e.g. Crosstrainer_currentcalories is defined in jdbc.persist and appears only once).

How do I clean the multiple entries without making it worse for openhab3?

**Comment by keesma** [comment]
> Can you post an extract.of the "items" table? Are there duplicate entries too?
It seems it was not clear what I wrote before. 
The list above is from the items table. Besides that, the tables for item0484, item0485, .... are also created.

**Comment by cweitkamp** [comment]
I checked my environment and identified the same problem. I found duplicate item tables like these:

![grafik](https://user-images.githubusercontent.com/5131747/140770268-3283365b-d902-4dac-ba56-165f70320933.png)

Funny thing is both tables from the example above were empty and did not contain any value. Additionally I did not configure the Items to be persisted at all.

I deleted the entries from my items table and dropped the related tables.

Next I navigated via Main UI to Settings > Items and switched to the details page of the Item.

![grafik](https://user-images.githubusercontent.com/5131747/140772300-631c7669-e1d3-48ef-8bf0-8e315d30cad1.png)
![grafik](https://user-images.githubusercontent.com/5131747/140772888-3c3f8933-ee79-4960-aab6-1e12ce293107.png)

Now JDBC persistence logged a warning ...

```
2021-11-08 16:42:03.345 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::query: unable to find table for query, no data in database for item 'sensorBathroomBatteryLevel'. Current number of tables in the database: 564
2021-11-08 16:42:03.347 [WARN ] [jdbc.internal.JdbcPersistenceService] - JDBC::query: try to generate the table for item 'sensorBathroomBatteryLevel'
```

... and guess what has happened - the table for the Item was created again:

![grafik](https://user-images.githubusercontent.com/5131747/140772772-bd613f00-12be-4ae7-b497-1f885442cab3.png)

My conclusion - we are facing two problems here. First one is a potential concurrency issue if the JDBC persistence gets multiple requests in a very short time for one Item which does not yet have a related SQL table. Second culprit is the trend line in Main UIs Item details. The UI requests the data for the trend line in this section and in other places even if the Item itself is not configured to be persisted. Not sure if we can or want to change that.

**Comment by splatch** [comment]
This issue is fairly "old", it occurs with OH 3.0.2 as well. I would not be surprised if earlier releases face same trouble. Because it gives no obvious side effects (data is retrieved properly), nobody really notices that.

**Comment by cweitkamp** [comment]
I found the piece of code which is responsible for this behavior and I have to revoke my previous assumption partly. The culprit is **not** the the trend line in Main UI, it is a weird behavior of the JDBS persistence. There a comment in the code `if enabled, table will be created immediately` but I nowhere found a place to disable it. Thus I will remove it.

https://github.com/openhab/openhab-addons/blob/ef46e126b4ae22c2fcea316ff38a8fd1d4f13a19/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/JdbcPersistenceService.java#L194-L202
