### ISSUE TITLE
[xmppclient] Binding depends on smack-experimental, which is not in OH repository

### ISSUE THREAD

**Issue by rvbglas** [openhab/openhab-addons#11560]
Trying to install xmppclient binding on new installation of OH3, got error:

```
 2021-11-11 13:15:23.871 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-xmppclient': Error:
 	Error downloading mvn:org.igniterealtime.smack/smack-experimental/4.3.3
```
There is no smack-experimental in https://openhab.jfrog.io/ui/native/libs-milestone/org/igniterealtime/smack repository.

Openhab version 3.2.0.M4:

```
Karaf
  Karaf version               4.3.3
  Karaf home                  /usr/share/openhab/runtime
  Karaf base                  /var/lib/openhab
  OSGi Framework              org.eclipse.osgi-3.16.300.v20210525-1715

JVM
  Java Virtual Machine        OpenJDK 64-Bit Server VM version 11.0.11+9-Ubuntu-0ubuntu2.20.04
  Version                     11.0.11
  Vendor                      Ubuntu
  Pid                         3389821
  Uptime                      14 hours 13 minutes
  Process CPU time            48 minutes
  Process CPU load            0.00
  System CPU load             0.00
  Open file descriptors       389
  Max file descriptors        102,642
  Total compile time          2 minutes
Threads
  Live threads                298
  Daemon threads              136
  Peak                        390
  Total started               148887
Memory
  Current heap size           630,831 kbytes
  Maximum heap size           8,189,952 kbytes
  Committed heap size         1,867,776 kbytes
  Pending objects             0
  Garbage collector           Name = 'G1 Young Generation', Collections = 4186, Time = 45.874 seconds
  Garbage collector           Name = 'G1 Old Generation', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      23,823
  Total classes loaded        29,567
  Total classes unloaded      5,744
Operating system
  Name                        Linux version 5.4.0-89-generic
  Architecture                amd64
  Processors                  6
```
Binding - from current 3.2.0.M4 distro.

**Comment by wborn** [comment]
It seems to have been caused by https://github.com/openhab/openhab-addons/pull/11418. You should be able to workaround it by using the add-ons KAR file which does have this dependency. So either that change should be reverted or the dependencies should be added to the openHAB Artifactory by @kaikreuzer.

**Comment by Hect0rG** [comment]
Having the same issue here... [https://community.openhab.org/t/error-downloading-mvn-org-igniterealtime-smack-smack-experimental/128531/3](url)

**Comment by Hect0rG** [comment]
@wborn where would I be able to find the KAR file so that I can at least temporarily bypass the issue? Also Is it as simple as placing the file in add-ons folder and restarting openhab?

**Comment by fwolter** [comment]
I fixed the dependencies and updated smack to the latest version 4.4.4 including all transitive dependencies. But when configuring a connection, I receive the following runtime exception. Maybe any of you has an idea:

https://discourse.igniterealtime.org/t/serviceconfigurationerror-xpp3xmlpullparserfactory-not-a-subtype/91054

@gkfabs @pavel-gololobov

**Comment by fwolter** [comment]
@Flowdalic I just saw that you tried to update smack to a newer version in #9977. Maybe you have an idea as the maintainer of smack :)

**Comment by gkfabs** [comment]
The "Xpp3XmlPullParserFactory not a subtype" is not linked to the missing lib on OH repository any more. I would create a new issue to keep things separated. Sadly I have no idea what's the root cause of this second problem.

**Comment by Flowdalic** [comment]
> @Flowdalic I just saw that you tried to update smack to a newer version in #9977. Maybe you have an idea as the maintainer of smack :)

It appears that @ibauersachs gave an solution here https://discourse.igniterealtime.org/t/serviceconfigurationerror-xpp3xmlpullparserfactory-not-a-subtype/91054/3?u=flow

**Comment by Hect0rG** [comment]
Hello all, I noticed it looks like there is a solution but it's not clear to me how to resolve from my end on OH. Any suggestions?

**Comment by Hect0rG** [comment]
Hi folks, seems this may take a little bit to get resolved. Is there any workaround based on what has been found so far? I have a few rules that use XMPP and before I start commenting out all those xmpp lines I am just wondering if there is anything I can try even if it's a temporary solution. Thanks.

**Comment by kaikreuzer** [comment]
Sorry, I thought I did this already, but it must have been fallen off my plate.
The dependency should now be available in Artifactory, so I hope this issue is solved!
