### ISSUE TITLE
Add Aeon DSC17 definition to zwave binding

### ISSUE THREAD

**Issue by johannrichard** [openhab/openhab-addons#1157]
It would be great if you could add the (updated) DSC17 device definition to the binding at some point.

It's http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/81 in the database.

Since my initial edit, I've added the engineering sheet and updated the associations which, if I am not mistaken, point to node1 / the controller.

**Comment by cdjackson** [comment]
I'll do a database update tonight.

**Comment by johannrichard** [comment]
Thanks!
