### ISSUE TITLE
[netatmo] very long delay (up to 19mins) because of refreshs at the wrong time

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#11588]
## Expected Behavior
The binding should refresh the data as often as it changes on the Netatmo side (every 10min) and so should get the most current information available.

## Current Behavior
The binding refreshes every 20min and does so a little too early.

### Measurements
I measured used a 10s manual poll via python netatmo vs. openHAB. This was done on a Netatmo submodule and main module, those behave the same.

openHAB (every 20min):
```
2021-11-15 10:50:25.726 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_Buero_Netatmo_CO2' changed from 914 ppm to 937 ppm
2021-11-15 11:10:36.440 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_Buero_Netatmo_CO2' changed from 937 ppm to 1053 ppm
2021-11-15 11:30:50.165 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_Buero_Netatmo_CO2' changed from 1053 ppm to 1088 ppm
2021-11-15 11:50:59.696 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'EG_Buero_Netatmo_CO2' changed from 1088 ppm to 1173 ppm
```

Manual calls (every 10s to notice when it really changes, only the first changed value shown here):
```
10:50:48 - 984
11:00:58 - 1053
11:11:02 - 1065
11:21:02 - 1088
11:31:22 - 1140
11:41:22 - 1173
11:51:32 - 1189
```

So on a combined timescale:
```
10:50:25 - OH refresh, 937 ppm
10:50:48 - Value changes to 984 ppm on Netatmo side
11:00:58 - Value changes to 1053 ppm on Netatmo side
11:10:36 - OH refresh, 1053 ppm
11:11:02 - Value changes to 1065 ppm on Netatmo side
11:21:02 - Value changes to 1088 ppm on Netatmo side
11:30:50 - OH refresh, 1088 ppm
11:31:22 - Value changes to 1140ppm on Netatmo side
11:41:22 - Value changes to 1173ppm on Netatmo side
11:50:59 - OH refresh, 1173 ppm
11:51:32 - Value changes to 1189 ppm on Netatmo side
```

So it seems like OH polls only every 20min (or every 10min and sometimes gets it wrong?) and also does that a little too early every time so it adds another 9min delay before the new value reaches it.

## Possible Solution
Poll *after* the value changed on the Netatmo side. To do this, the exact monent of the change conveniently is in the Netatmo response "dashboard_data" > "time_utc" (format is unix time).

![image](https://user-images.githubusercontent.com/1475672/141768108-7763b0fa-3ebe-4c7e-952b-7b603d377b70.png)

Unfortunately it seems not to be exactly every 10mins and  also differs from module to module. in my setup:
- Main module: 11:41:11 >>> 11:51:18
- Outside module: 11:41:07 >>> 11:50:31
- Additional inside module: 11:40:48 >>> 11:51:03

They seem to be quite close to each other but also very unpredictable.

So maybe it's possible to go with a generous "last value change time of main module + 10min + delay" where a reasonable delay could be 1min and should be tested on a larger scale of real values from Netatmo. This would stimm have quite a big delay (1min + difference between modules).

Or (way better in my opinion) poll every 10s unless "last value change tim" for *all* modules is less than 10min ago. Maybe offline devices also have to be accounted for with this approach so that they don't lead to always polling every 10s.

## Context
I have a neat little rule that reminds me to open the window when CO2 gets higher that a set threshold and also to close it again when it gets below a threshold after opening the window. That works just fine... but it takes way too long for it to realize when the value is low enough again. That's especially annoying when it's getting colder outside and you try not to freeze too much while also having fresh air inside ;-)

## Your Environment
OH3.2M3

**Comment by lolodomo** [comment]
As the Netatmo binding was largely revamped, please try again with the new version (3.3M5 or snapshot>=2892).

**Comment by eikowagenknecht** [comment]
I am not using OH any more, so unfortunately I can not retest. Feel free to close this when you consider it fixed :-)
