### ISSUE TITLE
[homematic] BURST_LIMIT_WARNING everytime something is sent to HmIP-WRCD

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#11599]
## Current Behavior
I get several log entries every time i send a command to my HmIP-WRCD (Id is 002A5A49A6****)
```
2021-11-18 18:08:29.409 [WARN ] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint '002A5A49A6****:0#BURST_LIMIT_WARNING'
2021-11-18 18:08:29.537 [WARN ] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint '002A5A49A6****:0#BURST_LIMIT_WARNING'
2021-11-18 18:08:29.675 [WARN ] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint '002A5A49A6****:0#BURST_LIMIT_WARNING'
2021-11-18 18:08:29.814 [WARN ] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint '002A5A49A6****:0#BURST_LIMIT_WARNING'
```

## Steps to Reproduce (for Bugs)
Send command to device, e.g. using karaf openhab:send

## Your Environment
OH3.2.0M4

**Comment by MHerbst** [comment]
According to the HmIP device documentation the device does not have a data point BURST_LIMIT_WARNING. Can you remove the device an re-run a discovery with TRACE log mode? Would be interesting to see what datapoint definitions the CCU returns.

**Comment by eikowagenknecht** [comment]
Sure, so I removed it and added it again. These are the logs that contain something about the BURST_LIMIT_WARNING:
[snippet_1.txt](https://github.com/openhab/openhab-addons/files/7568663/snippet_1.txt)
[snippet_2.txt](https://github.com/openhab/openhab-addons/files/7568664/snippet_2.txt)
[snippet_3.txt](https://github.com/openhab/openhab-addons/files/7568665/snippet_3.txt)
[snippet_4.txt](https://github.com/openhab/openhab-addons/files/7568666/snippet_4.txt)

There is much more going on in the trace logs, but uploading everything doesn't seem right from a privacy point of view. If it helps, I can send the rest to you by mail or some other means.

**Comment by MHerbst** [comment]
According to your log file (snippet_2) the CCU returns a data point with name BURST_LIMIT_WARNING. But according to the HmIP device documentation from eq3 this device (BTW: named as WRCD_V2) doesn't have a data point with this name.

Do you have more than one HmIP-WRCD device, maybe with different firmware versions?  

But in order to figure out what's really going wrong, I probably need a continous log file from the discovery and also a log with trace that shows the what happens before the warning message (Channel not found) is issued.

You can send it by mail to the address in my profile.

**Comment by eikowagenknecht** [comment]
I have only this one WRCD device, so no multiple firmware versions. I sent you the full unabridged logfile from the discovery by mail.

**Comment by MHerbst** [comment]
I have finished the PR for the reconnect handling and it has been merged yesterday. I don't know whether it will solve your problem.

**Comment by eikowagenknecht** [comment]
Thank you! I'm closing this for now then and reopen if the problem occurs again.
