### ISSUE TITLE
Force manual delete of zwave controller nodes 

### ISSUE THREAD

**Issue by vespaman** [openhab/openhab-addons#1160]
The node list of a stick e.g. Aeon Gen 5 can be out of sync after a while, especially in a large network with lots of exclusions/inclusions. This issue is a request for adding support to remove such old garbage from the zwave stick.

**Comment by cdjackson** [comment]
The network update to synchronise the primary controller with secondary controllers via the SUC is now implemented - this won't allow the device to magically know about devices that have been removed through other means - for this you need to use the functions already in the binding to remove devices.
