### ISSUE TITLE
[jsscripting] Invalid CommonJS root folder - folder is missing

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#11616]
## Expected Behavior

I have installed the `jsscripting` Add-On for GraalJS support in a clean openHAB 3.2.0.M4 installation in Docker.
Then I have created a Script of type `ECMAScript` in the Scripts section of the MainUI.
I wrote a simple code snippet and tried to run the rule:
```javascript
let test = 'test';
```
I expected the script to run without any errors in the openhab log.

## Current Behavior

Instead of running without any errors, the openhab log threw an error.
The beginning of the error:
```
2021-11-21 12:17:48.722 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error while creating ScriptEngine
org.graalvm.polyglot.PolyglotException: Error: Invalid   CommonJS root folder: /openhab/conf/automation/lib/javascript/personal
```
For full log, please have a view at the attachment [openhab.log](https://github.com/openhab/openhab-addons/files/7576175/openhab.log).

## Possible Solution

Create the folder `/automation/lib/javascript/personal` in the _openhab-conf_ folder (in my case `/openhab/conf`).

So there are two solutions:
* Tell the users in the docs that they have to create the folder.
* Automatically create the folder on openHAB start-up or on Add-On installation.

## Steps to Reproduce (for Bugs)

1. Make a clean openHAB installation of 3.2.0.M4.
2. Install the `jsscripting` Add-On.
3. Create an `ECMAScript` in the Scripts section of the MainUI.
4. Write any JavaScript Code, save it and run the script.

## Context

No real life context, just tests on a non-production installation.

## Your Environment

* Version used: `3.2.0.M4 Milestone Build` for both openHAB and the Add-On
* Environment name and version: Java `11.0.13 (Zulu11.52+13-CA)`
* Operating System and version: `Linux/4.4.180+ (amd64)` (Docker Image `openhab:3.2.0.M4`)

**Comment by ssalonen** [comment]
This issue has been described on https://github.com/openhab/openhab-addons/issues/11219

Do we consider this as duplicate?

**Comment by florian-h05** [comment]
> This issue has been described on https://github.com/openhab/openhab-addons/issues/11219
> 
> 
> 
> Do we consider this as duplicate?

Oh sorry, I have checked the issue but I overlooked that.

Should I close my issue?
