### ISSUE TITLE
[Trådfri] Support for dimmable colour bulbs

### ISSUE THREAD

**Issue by PMunch** [openhab/openhab-addons#11621]
In both the official IKEA app and in my previous HomeAssistant setup I was able to dim the trådfri colour bulbs that I've got. But the OpenHAB bindings does not have a channel for this. Looking at the source code it is also said that the bulbs don't support this, but they obviously do. For reference, this is the underlying Python library that the HomeAssistant bindings are built on: https://github.com/home-assistant-libs/pytradfri

## Your Environment

* Version used: 3.1.0
* Environment name and version: IKEA Trådfri bindings 3.1.0
* Operating System and version: Raspbian

**Comment by kaikreuzer** [comment]
> Looking at the source code it is also said that the bulbs don't support this

Do you have a reference for this?

The documentation clearly states that dimmable bulbs are supported: https://www.openhab.org/addons/bindings/tradfri/

As you are talking about colour bulbs, what you might be missing is that you can link a Dimmer item to the color channel and you're all set, see also [this faq entry](https://github.com/openhab/openhab-docs/pull/1675/files#diff-4462b48fbbe0a1e2f624f446bf9bf49301d1e9a0813e47fcd5b5fdc12c7b8f1cR64-R69).

**Comment by PMunch** [comment]
Not sure what I was thinking. Reading the README again it's pretty obvious that's how it's supposed to be done.
