### ISSUE TITLE
JDBC Persistence: old PostgreSQL jar - not supporting SCRAM authentication method

### ISSUE THREAD

**Issue by jum-zh** [openhab/openhab-addons#11620]
JDBC Persistence

PostgreSQL driver/jar not supporting SCRAM authentication scheme from PostgreSQL 10 and newer

## Expected Behavior
Update postgresql*.jar to a version supporting SCRAM authentication method.
or possibility to configure openhab-addon in a way to use the newest driver.

## Current Behavior
only supporting MD5
if pg_hba.conf requires scram, connection is not possible

## Possible Solution
update postgresql*.jar file

## Steps to Reproduce (for Bugs)
set a postgresql server with pg_hba.conf to enforce scram.
try to connect, it will fail.

## Context
current hardening best practices as of PostgreSQL 10 on recommend using scram.
Security rule require to use scram. As a result, Openhab can not use PostgreSQL any longer for the persistence service.

## Your Environment
Openhab 2.5, Rasbian Buster

**Comment by kaikreuzer** [comment]
Sorry, but openHAB 2.5 is no longer supported. Does the issue also exist with openHAB 3.x?

**Comment by jum-zh** [comment]
i guess as the doc of 3.x is refering to the same postgresql jar file
i do not have 3.x available

Von meinem iPhone gesendet
