### ISSUE TITLE
[shelly] Shelly Plus 1 PM not yet supported in binding version 3.1

### ISSUE THREAD

**Issue by vankachel** [openhab/openhab-addons#11628]
Hello,
I am using Shelly Binding version 3.1.0 . It finds all my shelly devices except the "Shelly Plus 1 PM". Is it possible since it is a new model it is not yet supported by the binding addon?
Best regards,
Carlo

**Comment by r3pl1x** [comment]
Same for me. Even trying to add the device manually by providing it's IP doesn't work.

**Comment by CrazyEasy** [comment]
Same, please add Shelly Plus 1 PM binding

**Comment by Rogger** [comment]
@markus7017 in what state is the support for Shelly Plus 1, had you had a chance to already start with it? Can I help you with the implementation?

**Comment by markus7017** [comment]
Will be adressed after PR #12325 is done

**Comment by markus7017** [comment]
See PR #12336, I'm working on support for Plus/Pro devices, first build is available. Hover over the symbol to get details
