### ISSUE TITLE
[RadioThermostat] Items not being updated

### ISSUE THREAD

**Issue by rstevenson** [openhab/openhab-addons#11625]
Haven't really found out why this happens but the log shows that the thermostat responds to the get request but no items are updated. I have found this to happen more often during first start but it has occurred at other times as well. It seems to fail for 30mins to a couple hours. At a certain point the binding will start updating the items again without any manual action.

I've set the log level to DEBUG and I see these messages but i never get the item updated or any messages in the log that the binding tried to update the items. 
```
2021-11-21 13:14:17.052 [DEBUG] [mmunication.RadioThermostatConnector] - thermostatResponse = {"temp":69.00,"tmode":1,"fmode":0,"override":0,"hold":0,"t_heat":69.50,"tstate":0,"fstate":0,"time":{"day":6,"hour":13,"minute":14},"t_type_post":0}
2021-11-21 13:14:17.054 [DEBUG] [ernal.handler.RadioThermostatHandler] - onNewMessageEvent: key tstat = {"temp":69.00,"tmode":1,"fmode":0,"override":0,"hold":0,"t_heat":69.50,"tstate":0,"fstate":0,"time":{"day":6,"hour":13,"minute":14},"t_type_post":0}
```

Openhab version: 3.2.0.M3

**Comment by mlobstein** [comment]
I see that your "t_heat" value is 69.50. I did not think that the target set point could ever be a half degree. Are the items only failing to update when you have a set point that ends in .50? I could see that if the json parsing is failing then most of the channels would not get an update. What about the heat & cool runtime channels? Those get populated from a separate service call. Do the run times still update when the others are stuck?

**Comment by rstevenson** [comment]
That must be a setpoint from the thermostat itself. I know you can’t send a half degree using the api. I did notice it started working after my thermostat schedule changed the setpoint. The runtime channels were getting updated correctly.

**Comment by mlobstein** [comment]
> That must be a setpoint from the thermostat itself. I know you can’t send a half degree using the api. I did notice it started working after my thermostat schedule changed the setpoint. The runtime channels were getting updated correctly.

The issue should be fixed in this PR: https://github.com/openhab/openhab-addons/pull/11635
I also linked to a test jar on the PR if you want to try it out.
