### ISSUE TITLE
[pulseaudio] The pulseaudio audio sink cannot play some audio format

### ISSUE THREAD

**Issue by dalgwen** [openhab/openhab-addons#11630]
## Expected Behavior
Pulseaudio sink should be able to play every PCM and MP3 audio formats.

## Current Behavior
The pulseaudio sink outputs random high pitched noises when I submit PCM or MP3 sound not in the exact supported format (which is 16 bits PCM, 44100 hz and 2 channels)

## Possible Solution
Add a pass to convert sound to the right format.
I will submit a pull request in a few minutes after the creation of this issue.

## Steps to Reproduce (for Bugs)
Play a wav with the "wrong" format (for example, the output of the pico2wave TTS service in openHAB) through a pulseaudio audio sink.

## Context
I was trying to use pico2wave TTS throught the pulseaudio binding.

## Your Environment
* openHAB 3.1.0
* Java 11:
* Debian buster

**Comment by Dracrius** [comment]
https://github.com/openhab/openhab-addons/issues/11662 This was also related to this bug. The new pull request snapshot solved it https://github.com/dalgwen/openhab-addons/releases/tag/3.2.0-SNAPSHOT_pulseaudio_11630
