### ISSUE TITLE
[Doorbird] Doorbell Event not working ('Decryption Failed')

### ISSUE THREAD

**Issue by steilerDev** [openhab/openhab-addons#11632]
## Expected Behavior
Once the doorbell is pressed, the 'doorbell' trigger fires.

## Current Behavior
I was able to verify that the Binding is working in general, because I successfully receive the 'Motion' Events. However the 'doorbell' channel never fires, when pressing the doorbell. I set the Log Level to trace and saw the following logs when pressing the button:
```
2021-11-22 21:01:16.851 [TRACE] [bird.internal.listener.DoorbirdEvent] - Calling cryptoPwHash with passwordFirstFive='*****', opslimit=4, memlimit=8192, salt='<some hex>'
2021-11-22 21:01:16.852 [TRACE] [bird.internal.listener.DoorbirdEvent] - Call cryptoAeadChaCha20Poly1305Decrypt with ciphertext='DC 74 FC 8A 17 33 B4 6B 0F 9C 71 01 D8 4B 5E 79 3F 37 A9 68 10 5D 84 62 AD E5 CF 21 0F C3 1E 95 B7 1C', nonce='05 C1 4C 1E 19 F3 6F 0D', key='79 47 3D 0B FD 30 0E 5E 53 CD 57 5F C3 A5 2B F2 B1 16 BE D0 9D 68 BB DF B3 E6 6D 35 99 E7 DC B7'
2021-11-22 21:01:16.852 [TRACE] [bird.internal.listener.DoorbirdEvent] - Decryption FAILED
```

Not sure which additional information could help solve this.

## Your Environment
* Version used: OpenHAB 3.1.0, running in a docker container, network mode is set to 'host'

**Comment by mhilbush** [comment]
Not really sure what could cause this other than the user not having the proper permissions, or the password being wrong

**Comment by steilerDev** [comment]
That's what I thought as well, but the motion event is picked up correctly (unless the motion event payload is differently encrypted than the doorbell payload).

**Comment by steilerDev** [comment]
Please let me know what I can supply to narrow down the issue.

**Comment by mhilbush** [comment]
A received UDP packet from the Doorbird can be either a doorbell event or a motion event. The packet is decrypted [here](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdEvent.java#L128).

**Comment by mhilbush** [comment]
And here's where you see the failure. Note the comment.

https://github.com/openhab/openhab-addons/blob/43ff86c1b469c0441c4805bcf866ae851e21a509/bundles/org.openhab.binding.doorbird/src/main/java/org/openhab/binding/doorbird/internal/listener/DoorbirdEvent.java#L233

**Comment by steilerDev** [comment]
As I said previously: This works flawlessly and every time for motion based events, only Doorbell events produce this error message and looking at Doorbird's documentation, there should not be a difference in encryption?

I am currently working around this by using the HTTP hooks from doorbird to set the item state within openHAB through a simple nginx proxy_pass solution, however this feels very hacky...

**Comment by mhilbush** [comment]
And as I said previously, decryption failures are normal and expected, as described in the code comment linked to above. The debug information you provided in your initial post is insufficient to determine whether that decryption failure is normal or not.

Here's the comment in case you didn't look at what I posted above.
```
            /*
             * Don't log at debug level since the decryption will fail for events encrypted with
             * passwords other than the password contained in the thing configuration (reference API
             * documentation for details)
             */
            logger.trace("Decryption FAILED");
```

**Comment by qba667** [comment]
@mhilbush 
Just tried to port the code to Android - all good - the bug is in the device - depending on number of configured users the intercom sends multiple motion/ringing messages encrypted with users passwords - so every user have chance to get end decrypt UDP messages.

**Comment by Skinah** [comment]
The doorbell presses can also be fetched into openHAB by using the ipCamera binding. For testing purposes try the different binding (don't use both at the same time) as the ipcamera uses a `HTTP tcp` based stream and not UDP to communicate the doorbell press. It also supports basic and digest auth methods. If a network issue drops a UDP packet, it is not resent. If the packet is TCP it gets resent and not missed. It would be interesting to compare if it works with ipcamera and it may well be because UDP is used, but why a user above is stating the motion always works and it is only a doorbell press does not make sense unless a motion event produces multiple UDP packets so that if 1 is lost it does not matter as the next one does arrive to the binding to process.

If it is not a bug in the binding, not a bug in the camera, it may be down to UDP and a network that is dropping packets.

**Comment by mhilbush** [comment]
I don't believe there is anything to do here.
