### ISSUE TITLE
[tplinksmarthome] kl125 missing colour channel

### ISSUE THREAD

**Issue by rstevenson** [openhab/openhab-addons#11660]
## Expected Behavior
Kasa app has the ability to change brightness, colour temperature and colour for the mulicolour lightbulb kl125. A channel for each should be present in the thing configuration.

## Current Behavior
The current binding (3.2.0.M4) has the brightness and colour temperature channels but is missing the colour channel.

## Your Environment
* Version used: 3.2.0.M4

**Comment by Hilbrand** [comment]
This is indeed incorrect (same problem with KL135). As a workaround you should be able to create a item in a text file using the `color` channel as this is only a problem of the xml definition files which are only used by the UI. The code itself supports the color channel.
