### ISSUE TITLE
[http] Documentation of player parameters needs to be updated

### ISSUE THREAD

**Issue by danielgauss** [openhab/openhab-addons#11677]
In the README.md file of the http binding, the table for the player type lists e.g. parameters play and pause.

While trying to set up a few items I used trial-and-error to get it working. The parameter play actually needs to be playValue, pause actually needs to be pauseValue. (I didn't try the other available parameters)

**Comment by lsiepel** [comment]
Fixed by: https://github.com/openhab/openhab-addons/pull/16282
