### ISSUE TITLE
[ipcamera] ffmpeg audio detection stops working/does not start on start-up

### ISSUE THREAD

**Issue by giejay** [openhab/openhab-addons#11672]
The ffmpeg audio detection is a bit unstable, needing manual triggers of the threshold to keep on working.

## Expected Behavior
When setting the threshold higher than 0, it should:
- Start audio detection on openhab-3/binding bootup. 
- When the thing goes offline -> online, it should restart (basically same as above)
- When ffmpeg process has some issues with a frame, it should try to restart the stream

## Current Behavior
1. Audio detection is not started at openhab bootup. First I need to move the threshold by a bit (or post the same threshold using API). 

2. Whenever ffmpeg process has some issues/hangs:
2021-11-28 14:21:56.065 [DEBUG] [hab.binding.ipcamera.internal.Ffmpeg] - size=N/A time=02:32:22.38 bitrate=N/A speed=   1x    
2021-11-28 14:21:57.044 [DEBUG] [hab.binding.ipcamera.internal.Ffmpeg] - size=N/A time=02:32:23.44 bitrate=N/A speed=   1x    
2021-11-28 14:21:59.219 [DEBUG] [hab.binding.ipcamera.internal.Ffmpeg] - size=N/A time=02:32:23.60 bitrate=N/A speed=   1x    
2021-11-28 14:22:20.137 [DEBUG] [hab.binding.ipcamera.internal.Ffmpeg] - Stopping ffmpeg RTSP_ALARMS now when keepalive is:8

It's stopping the process, but not automatically rebooting it. Could that be an option added to the binding?

## Possible Solution
For both points, I have this rule which fixes it:

```
rule "check if audio detection is still working"
when 
    Time cron "0/30 * * * * ?"
then
    val status = getThingStatusInfo("ipcamera:onvif:cam").getStatus
    if(status == "ONLINE"){
        val ffmpegProcess = executeCommandLine(Duration.ofSeconds(3), "/openhab/conf/scripts/check-ffmpeg-process.sh");
        if(!ffmpegProcess.contains("rtsp://")){
            Camera_AudioAlarmThreshold.sendCommand(Camera_AudioAlarmThreshold.state as Number)
        }
    }
end
```

## Steps to Reproduce (for Bugs)
1. Enable audio alarms by modifying the threshold
2. Restart the binding (pause/unpause for example)
3. Process is not started

## Your Environment
Openhab 3.1.0
Ipcamera 3.2m4

**Comment by Skinah** [comment]
Can you post the link to the exact forum posts where we discussed this please as you posted helpful testing data? Busy time of year and not sure when I will find some time to look into it more then this quick post...

Proposed:
When the thing is paused/unpaused or the camera goes offline I will look at making the threshold go back to 0/off when the thing is stopped. If the detection fails or stops it should also go back to 0/off so the channel reflects what is happening. The idea is this will fix the problem of the controls state getting auto saved by openHABs framework and a restart of openHAB meaning the alarm will not be detecting even thou the control is not at 0/off.

The binding can track the desired threshold value and when the camera comes back online it can return to the desired threshold automatically. You will need to send the off or 0 command to stop the auto restart.

So this is two changes to be made.

1. Add tracking to the state so the channel always displays the state of the detection.
2. Add auto restart ability.

If you restart openHAB it will be required for you to put a rule in to auto start the alarm if that is what you wish. A binding can not ask what position a control is in to my knowledge so you will need to handle that case with rules.

**Comment by giejay** [comment]
Sounds good! Here are the link to forum posts:
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2553?u=giejay
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2574?u=giejay
