### ISSUE TITLE
[hdpowerview] Update position Channels immediately when a Scene (Collection) is triggered.

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#11697]
In [Issue #11557](https://github.com/openhab/openhab-addons/issues/11557) @arroyoj suggested the following:

> I would .. suggest doing a soft refresh after any scene is triggered. As far as I can tell from my testing, the hub responds to a `GET /shades` call with the correct JSON data for all the shade states immediately after a scene is triggered, even while the shades are still moving, so a soft refresh should be sufficient.

In addition logically a soft refresh should probably also be done when a **_Scene Collection_** is triggered (see merged PR #11534 from @jlaur).

**Comment by jlaur** [comment]
@arroyoj, @andrewfg - I can do this, but would prefer to do it after #11637 is merged as there will be a lot of conflicts after changing this part of the code. Would that be okay? Hoping also that @andrewfg would be willing to review the changes made in that PR.

**Comment by andrewfg** [comment]
> prefer to do it after #11637 is merged.. .. Would that be okay? 
> Hoping also that @andrewfg would be willing to review

Yes, and yes.
