### ISSUE TITLE
[telegram] Can't send message with underscore character

### ISSUE THREAD

**Issue by zolakk** [openhab/openhab-addons#11691]
I noticed when trying to set up a rule to send telegram messages when my zwave devices drop offline, I was getting the error "Failed to send telegram message: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 182". I narrowed it down by counting the characters and then attempting to send a message with just an _ in it, which resulted in "Failed to send telegram message: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 0"

## Expected Behavior
The message should send without issue

## Current Behavior
Attempting to send a message with a _ (underscore) character gives the message  "Failed to send telegram message: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset <character position of the _ character>". Appears to happen with the sendTelegram, sendTelegramQuery, and sendTelegramQuery actions

## Possible Solution
Internally escape the character before sending if it's an invalid character on the telegram API

## Steps to Reproduce (for Bugs)
This python script:
```
telegramAction = actions.get("telegram","<botThingID>")
telegramAction.sendTelegram("_")
telegramAction.sendTelegramQuery("_")
```
will produce these lines in the log:
```
2021-12-02 11:14:26.246 [WARN ] [gram.internal.action.TelegramActions] - Failed to send telegram message: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 0

2021-12-02 11:14:26.407 [WARN ] [gram.internal.action.TelegramActions] - Failed to send telegram message: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 0
```

## Context
I first noticed while trying to send a log snippet to my telegram with the text "COMMUNICATION_ERROR" in it but was failing with the above errors. I am able to work around that by replacing the underscore with a space but it would be good to not have to do that.

## Your Environment
* Version used: openHAB 3.2.0.M4
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Docker on raspbian buster

**Comment by lolodomo** [comment]
Closed by #13758
