### ISSUE TITLE
[InnogySmartHome] Variable Actuators show as "Gone" on OH3.2M5

### ISSUE THREAD

**Issue by derkens** [openhab/openhab-addons#11741]
I'm in the process of moving from openhab 2.5 to 3.2
So I have installed a fresh raspberrypi with openhabian.

When configuring the innogysmarthome binding I noticed the variable actuators where not discovered.
I Have tried adding a variable actuator manually, but the thing shows as "Not Found" or "Gone"

Searching the forum I came accross this thread:
[https://community.openhab.org/t/oh3-innogy-variable-actuators-gone/118530](url)
It seems this is the case since 3.1Mx?

I have put the log in DEBUG for the binding. I have attached a piece of what happens when I create a new variable actuator from the livisi website.

If more logging is needed, or access to the system, let me know.

[innogydebuglog.txt](https://github.com/openhab/openhab-addons/files/7691376/innogydebuglog.txt)

**Comment by derkens** [comment]
@Novanic  , any idea? can you help?

**Comment by Novanic** [comment]
Hi, I have found the problem and could fix it. I think I can create a pull request tomorrow.

**Comment by derkens** [comment]
Fantastic! Thank you very much!

**Comment by Novanic** [comment]
Hello @derkens , if you would like to test (or use) the fix before the release OpenHAB 3.3.0, you should find the binding including the fix here: https://ci.openhab.org/job/openHAB-Addons/lastSuccessfulBuild/artifact/bundles/org.openhab.binding.innogysmarthome/target/org.openhab.binding.innogysmarthome-3.3.0-SNAPSHOT.jar

**Comment by derkens** [comment]
Yes i really wanted to use it, downloaded, installed it, works like a charm. Thanks again!
