### ISSUE TITLE
[meteoalerte] Use English in XML files and provide English default translations

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#11761]
This binding uses French in [thing-types.xml](https://github.com/openhab/openhab-addons/blob/6077ce3c4456e4afa16ef018b9f66130937dd553/bundles/org.openhab.binding.meteoalerte/src/main/resources/OH-INF/thing/thing-types.xml) which makes it difficult to use/understand for users who do not understand French. Also we cannot use these texts for providing the default English translations to make the binding texts translatable in Crowdin.

See: https://github.com/openhab/openhab-addons/pull/11760#issuecomment-991874706

**Comment by wborn** [comment]
It's probably all French because the API only provides French info? Maybe one day they'll come to the conclusion that not everybody living in France speaks French and will also add support for English. :wink:

**Comment by lolodomo** [comment]
To defend @clinique, this binding is specific for French users or more exactly for users living in France.

**Comment by lolodomo** [comment]
I guess this is clearly not a priority for @clinique ;)

**Comment by clinique** [comment]
Yes, this binding is point less for non french users - I will not amend anything

**Comment by clinique** [comment]
Everybody living in France should wish to speak French enough to understand MeteoAlert binding. When I wrote it I asked myself if I should spend time translating it in english to have in the end only french users - the answer I gave to myself was no. On other bindings it is normal to make the effort - this one, no.
