### ISSUE TITLE
[hdpowerview] Deprecated scene channels removed after saving hub configuration

### ISSUE THREAD

**Issue by arroyoj** [openhab/openhab-addons#11778]
## Expected Behavior
PR #11637 from @jlaur introduced deprecated scene channels to allow for a smooth transition to new scene channel groups. These deprecated channels are automatically created for the user as needed to maintain old item links. The deprecated channels should always be available until the user manually migrates their items to the new channels in the scene channel group, so that the old scene items continue to work as expected prior to migration.

## Current Behavior
While running a snapshot JAR that incorporates the changes from PR #11637, I discovered that saving the Powerview Hub configuration in OpenHAB disrupted my old scene items. My old scene items had been linked to the deprecated scene channels and were working fine. However, after saving the configuration to update a value, I went to trigger a scene and nothing happened, although the item received the command according to the event.log. Restarting OpenHAB or disabling and then enabling the Hub thing restored the deprecated channels and the scenes functioned again.

## Possible Solution
@jlaur, I believe this bug comes in part from these lines:
https://github.com/openhab/openhab-addons/blob/4481ecff61143a679e0813942a5b48d666a1b545/bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewHubHandler.java#L363-L367

Doing a save of the hub Thing config appears to clear out all of the dynamic channels and reinitializes the hub. This is what my log looked like after saving the config (note: I did not actually make a change to the config, I just hit save):
```
20:37:57.669 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Initializing hub
20:37:57.681 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Scheduling poll for 5000ms out, then every 60000ms
20:37:57.686 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Scheduling hard position refresh every 180 minutes
20:37:57.690 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Scheduling hard battery level refresh every 168 hours
20:38:02.686 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Polling for state
20:38:02.799 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Received data for 11 shades
20:38:02.801 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '57040'
20:38:02.805 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '49916'
20:38:02.808 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '58131'
20:38:02.810 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '43539'
20:38:02.817 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '10734'
20:38:02.821 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '13306'
20:38:02.826 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '40481'
20:38:02.830 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '35688'
20:38:02.835 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '57893'
20:38:02.845 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '44940'
20:38:02.848 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating shade '48128'
20:38:02.953 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Received data for 9 scenes
20:38:02.954 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Updating all scene channels, changes detected
20:38:03.014 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Received data for 0 sceneCollections
20:38:03.015 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Preserving scene collection channels, no changes detected
20:38:03.044 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Received data for 0 scheduledEvents
20:38:03.045 [DEBUG] [nternal.handler.HDPowerViewHubHandler] - Preserving scheduled event channels, no changes detected
```

The log message "Updating all scene channels, changes detected" comes from `updateSceneChannels()`, which in turn calls `createDeprecatedSceneChannels()`. My guess is that because the Thing is just being reinitialized and not recreated, `deprecatedChannelsCreated` is still True, so the deprecated channels are not being recreated after being deleted during the save. My suggestion would be to set the `deprecatedChannelsCreated` flag to `false` in `initialize()` so that after an initialization (but not after other scene updates) the deprecated channels are recreated, but I don't have a way to test whether that would work.

## Steps to Reproduce (for Bugs)
1. Create an item link to a scene channel using the pre-v.3.2.0 scene channel syntax (ie, `#123` instead of `scenes#123`)
2. Disable and re-enable the hub Thing to make sure a deprecated channel is created (should be visible in the Channels tab for the hub Thing)
3. In the hub configuration page, re-save the hub config (changes are not required, just a save)
4. Checking the Channels tab again, the deprecated channel is no longer present

@jlaur, sorry I missed this bug in my original testing for #11637. It was pretty subtle.

**Comment by jlaur** [comment]
@arroyoj - thanks for finding and reporting this! I have created a draft pull request with a fix (link to JAR in PR), can you test this? I have some problems getting anything to work right now, so didn't manage to test it myself yet, and now have to go to work. I will be able to promote the PR from draft during the day, if it works, but won't be able to do much more for next ~9 hours. :-(

**Comment by jlaur** [comment]
@arroyoj - thanks also for testing. I was now also able to confirm myself that it works. It was early morning when fixing it. Forgot that deprecated channels are removed also if same scene has new channel linked, so that cheated me. :-)
