### ISSUE TITLE
[avmfritz] Handler tries to set brightness for blinds in version 3.2.0.M5

### ISSUE THREAD

**Issue by quidam** [openhab/openhab-addons#11789]
## Expected Behavior
The binding does not attempt to set the brightness of blinds.

## Current Behavior
As HAN-FUN blinds (bit mask 335888) identify themselves not only as blinds (bit 18 set), but also as dimmable lights (bit 16 set), the AVMFritzBaseThingHandler tries to update the channel "brightness", which doesn't exist. This leads to infinite messages like 
`Channel 'brightness' in thing 'avmfritz:HAN_FUN_BLINDS:192_168_nnn_n:nnnnnnnnn' does not exist, recreating thing.`
This not only results in a multitude of log entries, but also prevents openHAB to correctly initialize the blinds resulting in an unknown state of the HAN-FUN things following the blinds.

## Possible Solution
only set brightness when the thing is identified as a dimmable light and NOT as blinds. (I'm presently working on a PR)

## Steps to Reproduce (for Bugs)
1. Install avmfritz binding
2. add a blinds thing and other HAN-FUN things
3. set the log level to DEBUG for the binding
4. analyze the openhab log

## Your Environment
* Version used: openHAB and add-on version 3.2.0.M5
* Operating System and version: Raspbian Buster

**Comment by lolodomo** [comment]
Closed by #11790
