### ISSUE TITLE
[openwebnet] Add double press feature for CEN+

### ISSUE THREAD

**Issue by Interstellar0verdrive** [openhab/openhab-addons#11796]
## My Environment

* openHAB version 3.1.0 (Release Build)
* Raspberry Pi 4 Model B Rev 1.2 (oenHABian)
* OpenWebNet (BTicino/Legrand) Binding version 3.2.0.202110102314

## Improvement suggestion
I would like to suggest the addition of a double-press feature for CEN+ commands.
I first posted it in the openHAB Community here: https://community.openhab.org/t/openwebnet-adding-cen-cen-support-to-oh3/126882/60

Here is the code I am using in my .rules file:

```
rule "Check if a short press is triggered twice within a 2 seconds timer window"
	when 
		Channel "openwebnet:bus_cenplus_scenario_control:mybridge:CEN_Plus_Gen_Tapp:button#1" triggered SHORT_PRESSURE
	then 
		logInfo("bticino.rules", "button UP pressed")

		if (buttonTimerUp === null) {
			gTapparelle.sendCommand(STOP) 
			// start the timer
			logWarn("bticino.rules", "Timer Up started")
			buttonTimerUp = createTimer(now.plusSeconds(2)) [ |
				// if the timer expires
				logWarn("bticino.rules", "Timer Up expired")
				logInfo("bticino.rules", "--> Button UP SINGLE pressed")
				// reset the timer
				buttonTimerUp = null
			]
		} 
		else {
			// within the timer window
			logInfo("bticino.rules", "--> Button UP DOUBLE pressed")
			Chiudi_Tapparelle_Modalita_Estate_Giorno.sendCommand(ON)
			// reset the timer
			buttonTimerUp.cancel
			buttonTimerUp = null
		}
	end
```

In my setting, if you short press once, it stops the rollershutters (if they were moving). 
Instead if you short press twice within 2 seconds, it fires an action (a scenario that sets different rollershutters at different open %).

That may be an interesting upgrade if implemented in the binding itself.

Something like this would be cool:
```
bus_cenplus_scenario_control CEN_Plus_Gen_Tapp   "CEN+ Generale Tapparelle"   @ "Ingresso"   [ where="22", buttons="1,2", doublePressTimer="2" ]
```
So if you set `doublePressTimer` to 0 no double press is detected, if you set e.g. to 2 it is detected within 2 seconds and a “DOUBLE_PRESSED” event is triggered by the channel.

**Comment by mvalla** [comment]
Since double press event is not natively supported in BTicino MyHome / OpenWebNet CEN+ and this can be achieved with the suggested rule above, it's out of scope to support this in the binding, which hasthe goal to translate events into OH events.
This issue will be clsoed.

**Comment by mvalla** [comment]
Since double press event is not natively supported in BTicino MyHome / OpenWebNet CEN+ and this can be achieved with the suggested rule above, it's out of scope to support this in the binding, which hasthe goal to translate events into OH events.
This issue will be clsoed.
