### ISSUE TITLE
[nest] Missing a step: Enable the API

### ISSUE THREAD

**Issue by nekodojo** [openhab/openhab-addons#11814]
At the end of `#sdm-configuration-parameters` and right before section `#pub-sub-configuration-parameters`

> The SDM Account Thing should now be ONLINE and have as status description "Using periodic refresh". It should also be possible to use the configured account to discover your Nest devices via the Inbox.
> 
> You can monitor the SDM API using the Google Cloud Platform Console via API & Services > Smart Device Management API (opens new window).

This doesn't mention that if you don't visit this page, the API remains disabled and no devices will be detected.

Suggested update:

> The SDM Account Thing should now be ONLINE and have as status description "Using periodic refresh".
> 
> The last step is to enable the SDM API. Without this, your new project will not detect any devices.  Navigate to the SDM API using the Google Cloud Platform Console via [[API & Services > Smart Device Management API (opens new window).]] [[link target https://console.cloud.google.com/apis/api/smartdevicemanagement.googleapis.com/overview ]]   After this, the configured account should discover your Nest devices via the Inbox.
> 
> You can use the same link monitor the SDM API in the Google Cloud Platform Console:  [[API & Services > Smart Device Management API (opens new window).]] [[ link https://console.cloud.google.com/apis/api/smartdevicemanagement.googleapis.com/overview ]]

**Comment by lolodomo** [comment]
@wborn : WDYT ?
