### ISSUE TITLE
[opensprinkler] Sequencing station commands can lead to unexpected behaviour unless autoupdate='false'

### ISSUE THREAD

**Issue by raaahbin** [openhab/openhab-addons#11815]
Suggest editing opensprinkler binding to set autoupdate to **off** by default for station control channels.

## Expected Behavior
Rule created to switch on station 2 when station 1 is commanded off.
Should result in station 2 turning on whenever station 1 is turned off.

## Current Behavior
station2 appears (in the log) to turn on and back off again. In the opensprinkler interface, station 2 is not turned on at all, but instead results in a "scheduled" status to run 36 hours in the future.

## Possible Solution
After adding ```autoupdate="false"``` to the items, the rule operates as expected. I suspect the problem arises when the binding almost simultaneously sends the commands to stop station 1 and start station 2. However, when autoupdate is forced off, the rule doesn't trigger until after the opensprinkler device has confirmed successful completion of stopping station 1, so the command to start station 2 no longer conflicts.

## Steps to Reproduce (for Bugs)
1. Create rule as follows:
```
rule "run station2 after running station1"
when
	Item station1 changed from ON to OFF
then
	station2.sendCommand(ON)
end
```
2. using the openhab interface (BasicUI), turn on station 1.
3. still using the openhab interface, turn off station 1.

This should result in the incorrect behaviour.

## Context
https://community.openhab.org/t/opensprinkler-stations-jumping-straight-back-to-off-when-on-command-sent/130178

## Your Environment
* Versions used: openhab 3.1.0, 3.2.0M5
* Environment name and version: opensprinkler hardware version 3.1 - DC; firmware 2.1.9 (9)
* Operating System and version: openhab running on MacOS 10.15.7

**Comment by Skinah** [comment]
Added the change as it was easy to find. Veto means it will default to 'false' and you can over ride this with the metadata to re-enable it if anyone wants to.
