### ISSUE TITLE
[amazonechocontrol] openhab 3.2.0 Web Socket close 1005. Reason: null

### ISSUE THREAD

**Issue by sn0wf4ke** [openhab/openhab-addons#11822]
This could be a regression or amazon changed something again.

## Expected Behavior
* no log entries like: 'Web Socket close 1005. Reason: null'
* working 'last voice command'

## Current Behavior
* log showes above error
* `last voice command` not working

## Possible Solution
* none

## Steps to Reproduce (for Bugs)
1. upgrade to 3.2.0

## Context
* switcht to `310 │ Active │  80 │ 3.3.0.202112200814    │ openHAB Add-ons :: Bundles :: Amazon Echo Control Binding` does not work either

## Your Environment

* Version used:  3.3.0.202112200814
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): docker image tag 3.2.0

**Comment by wborn** [comment]
Duplicates #11810
