### ISSUE TITLE
[homematic] HmIP-WTH-2 does not show humidity

### ISSUE THREAD

**Issue by patrik-dev** [openhab/openhab-addons#11829]
The homematic binding does not have a channel for the humidity of the HmIP-WTH-2. In the CCU3 the item has a humidity channel.

**Comment by MHerbst** [comment]
First of all, if you create an issue, please provide always the following minimum information:

- openHAB version
- runtime environment (operating system, Java interpreter)

Did you select "Show Advanced" in the channel list? Maybe Humidity is defined as an advanced channel.

Or are there any error or warning messages in openhab.log.

If the channel is also missing in the advanced channel list, I need a log of the discovery process. To produce this log, please set the log mode for the Homematic binding to TRACE, remove the device, discover it again and attach the relevant part of the log here.

**Comment by dirkbe** [comment]
I can confirm to see homematic:HmIP-WTH-2:<bridge-id>:<thing-id>:1#HUMIDITY as an advanced channel (click "Show advanced" under channel tab). My config: OH 3.1.1-1, RaspberryMatic 3.61.7.20211218, HmIP-WTH-2 FW 2.6.0.

Maybe Humidity and other channels like Boost-Mode, Party, etc. shouldn't be "advanced" channels?

**Comment by MHerbst** [comment]
The binding uses a list with datapoint points to decide whether it is configured as an advanced channel or not.

Normally HUMIDITY is not an advanced channel, but the HmIP-WTH-2 device uses differnt namings for its channel. This means that the configuration file has to be enhanced.
