### ISSUE TITLE
[somfytahoma] Login fails with http protocol error

### ISSUE THREAD

**Issue by seime** [openhab/openhab-addons#11844]
Tested with 3.1.0 and 3.2.0.

Thing config:

`Bridge somfytahoma:bridge:*** "Somfy Connexoon Account Bridge" [ email="****@gmail.com", password="******", refresh=10 , statusTimeout=30] { ...}`
 
Used to work fine, but sometime the last few weeks the bridge started to fail to authenticate. Might have been a change on the server.

Attempted to change password on service as well to no avail. Re-logged into the app as well.

By adding a breakpoint at around line 254 I can see that I constantly get 

`org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header`

Screenshot from debugger; 

![CleanShot 2021-12-22 at 18 55 58](https://user-images.githubusercontent.com/1565156/147135274-98c45757-d8fc-4ed0-893d-6949683dd18e.png)

@octa22

**Comment by lolodomo** [comment]
What I read in the community forum is that you have to stop the binding, wait for few hours and then it is working again.

**Comment by seime** [comment]
I left it disabled over the night, tried to enable it again now. Same error message in the UI 
<img width="314" alt="CleanShot 2021-12-23 at 09 46 49@2x" src="https://user-images.githubusercontent.com/1565156/147213816-ca54b9d3-32fe-4faf-8fd5-da8611fe37f0.png">

**Comment by lolodomo** [comment]
I would suggest you find help on the community forum. 
I have seen several recent discussions about that with positive feedbacks.

**Comment by lolodomo** [comment]
@seime : I suppose you resolved your connection problem ?

**Comment by seime** [comment]
Sorry for late reply. I switched to local dev avoiding the cloud earlier this year.

The original problem of disconnect and blocked login intermittently came back throughout the whole period until going local.

**Comment by lsiepel** [comment]
> Sorry for late reply. I switched to local dev avoiding the cloud earlier this year.
> 
> The original problem of disconnect and blocked login intermittently came back throughout the whole period until going local.

Allways with the same response? Or did it change to a banned mesage like: https://github.com/openhab/openhab-addons/issues/14763
