### ISSUE TITLE
[mqtt] remove System Broker Thing from v3 binding

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#11848]
"System Broker" introduced as management aid in OH2 for bundled embedded broker no longer of use in OH3 - no bundled broker.

Indeed, it presents a trip hazard for users who try to configure one in error.

**Comment by lolodomo** [comment]
Can you please link the PR which removed the embedded broker!

**Comment by Rossko57** [comment]
I shouldn't think there is one.  It was just an add-on package that was available in OH2, but was never made available in OH3.  A pre-release strategy decision.

**Comment by lolodomo** [comment]
@kaikreuzer ; can you please confirm that the system broker thing type can be removed and should have never existed in OH3?

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab-addons/pull/8649

**Comment by lolodomo** [comment]
Thank you @J-N-K
