### ISSUE TITLE
[jdbc] even with tableUseRealItemNames=true a table name suffix is created

### ISSUE THREAD

**Issue by weberjn** [openhab/openhab-addons#11906]
Doc of tableUseRealItemNames says: "When set to true, real item names are used for table names and tableNamePrefix is ignored. "

Actually not the item name is used alone, there is the rowId of item in the items table added (which is quite useless for tableUseRealItemNames), e.g. with tableIdDigitCount=0

     Schema |    Name     | Type  |  Owner
     --------+-------------+-------+---------
      public | cpu_load1_1 | table | openhab
      public | items       | table | openhab

and items

       itemid | itemname
      --------+-----------
            1 | CPU_Load1

The relevant code is in
org.openhab.persistence.jdbc.internal.JdbcMapper.getTableName(int, String)

       return getTableNamePrefix(itemName) + formatRight(rowId, conf.getTableIdDigitCount());

which should be changed to 

        String tableName = getTableNamePrefix(itemName);
    	if (!conf.getTableUseRealItemNames()) {
    		tableName = tableName + formatRight(rowId, conf.getTableIdDigitCount());
    	}
        return tableName;

**Comment by jlaur** [comment]
@weberjn - it was a bit more tricky than anticipated due to backwards compatibility and support of different migration paths. Nevertheless, it's done - you can find a link to a JAR file in the linked pull request.
