### ISSUE TITLE
[tr064] wanBlockIPs, incorrect regular-expression for IP-address validation

### ISSUE THREAD

**Issue by syntacrsc** [openhab/openhab-addons#11909]
When specifying ip-address for parameter "wanBlockIPs" for Bridge tr064:fritzbox:SomeName addresses such as 10.0.0.35 won't be accepted due to an invalid regular expression for vaildating the IP addresses.

## Expected Behavior
an IP adresses containing zeros (e.g. 10.0.0.51) should be accepted for wanBlockIPs.

## Current Behavior
Event log shows the following errors when trying to setup the wanBlock items:

"==> /var/log/openhab/openhab.log <==

2021-12-31 10:07:05.939 [WARN ] [hab.binding.tr064.internal.util.Util] - Removing 10.0.0.51 while processing wanBlockByIP, does not match pattern ([1-9]\d{0,2}\.){3}[1-9]\d{0,2}(\s*#.*)*, check config.

2021-12-31 10:07:05.943 [WARN ] [hab.binding.tr064.internal.util.Util] - Removing 10.0.0.36 while processing wanBlockByIP, does not match pattern ([1-9]\d{0,2}\.){3}[1-9]\d{0,2}(\s*#.*)*, check config.

2021-12-31 10:07:05.945 [WARN ] [hab.binding.tr064.internal.util.Util] - Removing 10.0.0.42 while processing wanBlockByIP, does not match pattern ([1-9]\d{0,2}\.){3}[1-9]\d{0,2}(\s*#.*)*, check config."

## Possible Solution
Adjust the regular expression for validating IP addresses for parameter "wanBlockIPs"

## Steps to Reproduce (for Bugs)
Setup a tr06 bridge and specify IP addresses for parameter wanBlockIPs containing zeros (e.g. 10.0.0.35)
example:
Bridge tr064:fritzbox:Fritz7490 "FritzBox 7490 Bridge"	@ "Office"
[
	host="10.0.0.1",
	user="tr064", 
	password="somePassword", 
	refresh=30,
	missedCallDays="7",
  	tamIndices="2",
  	outboundCallDays="7",
	inboundCallDays="7",
	rejectedCallDays="7", 
	callListDays="7",
	wanBlockIPs="10.0.0.35",	
				"10.0.0.42",	
				"10.0.0.51",	
	callDeflectionIndices="5" 

Now restart the openhab service and watch for the error messages in the event log.

## Context
Since I'm using networt 10.0.0.255/24, all my ip-address contain zero-segments and hence cannot be used for wanBlockIPs.

## Your Environment
openHAB 3.2.0
Release Build
Raspberry Pi 4b+

**Comment by lsiepel** [comment]
I have altered the code with a better pattern : ^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)(\.(?!$)|$)){4}$
A JAR with the fix can be downloaded here: https://1drv.ms/u/s!AnMcxmvEeupwjpk1SGaHtptxxOD3PQ?e=TKT4Ie  
Code improvements are here: https://github.com/lsiepel/openhab-addons/tree/TR064-issues 
Once verified i will make a PR .

Please let me know your findings.

**Comment by syntacrsc** [comment]
Hi @lsiepel  .

Thanks for the attempt to fix the issue – it does not seem to work though:

My log still shows messages such as
“2022-12-10 07:59:23.935 [WARN ] [hab.binding.tr064.internal.util.Util] - Removing 10.0.0.51 while processing wanBlockByIP, does not match pattern ([1-9]\d{0,2}.){3}[1-9]\d{0,2}(\s*#.), check config.”
(see screen shot below)

Here’s how I tested:

I’m on OH 3.3.0 Release Build (not 3.4 !)

I removed the 3.3.0 TR-064 binding (via Administration->Settings->Bindings->tr-064->remove)
I’ve put your new JAR file into /usr/share/openhab/addons
Rebooted the openhab Server (twice)
Validated the new JAR file has been loaded thru console command bundle:list
it shows 3.4.0 version is active:
320 │ Active │ 80 │ 3.4.0.202212091601 │ openHAB Add-ons :: Bundles :: TR-064 Binding
(also: see screen shot below)
=> Log shows warnings for failed pattern check for WanBlockIp:

![image](https://user-images.githubusercontent.com/55259377/206837839-05067711-cf3f-4c93-833a-aac2c507331c.png)


![image](https://user-images.githubusercontent.com/55259377/206837844-295b800c-f797-4c4f-9df4-36ad46cb7588.png)

**Comment by lsiepel** [comment]
The log still shows the old pattern. I’ll rebuild a new jar to make sure the proper pattern is in it. I’ll let you know

**Comment by syntacrsc** [comment]
great, thanks a lot!

**Comment by lsiepel** [comment]
Just uploaded a new jar. Meanwhile the PR got merged.
