### ISSUE TITLE
[jeelink] Discovery documentation does not mention the need to scan for sensors.

### ISSUE THREAD

**Issue by cmorty** [openhab/openhab-addons#11986]
The [Documentation](https://www.openhab.org/addons/bindings/jeelink/#thing-discovery) says that new sensors should show up in my inbox. However, it seems I need to scan for sensors as explained in the [forum](https://community.openhab.org/t/jeelink-online-but-no-lacrosse-sensors-are-found/111163). 

Is the documentation wrong? Or does this only apply to lacrosse? Or is this a bug or missing feature? 

If I get some input, I'm willing to update the documentation.

**Comment by lolodomo** [comment]
Some bindings are implementing an automatic discovery, some are not. With the second category, the user has to trigger a  search in MainUI. 
Mentioning in the documentation whether the discovery is automayic or not eould be an appreciated bonus, but I don't consider it as a bug if the information id missing, simply because the documentation of a particular binding is not a guide on how discovery id generally working in openHAB.

**Comment by cmorty** [comment]
@lolodomo The issue I have, is that the way the documentation is written suggests that JeeLink supports automatic discovery (IMO).

**Comment by lolodomo** [comment]
You can propose a change.

I have not checked the code. @vbier : please confirm whether or not the discovery is automatic.

**Comment by vbier** [comment]
Discovery needs to triggered manually. Docs do not mention autodiscovery, afaics.

**Comment by lolodomo** [comment]
> Discovery needs to triggered manually. Docs do not mention autodiscovery, afaics.

I agree with you, I see no mention of automatic discovery in the documentation.
@cmorty  : the documentation is just correct.

**Comment by cmorty** [comment]
@vbier @lolodomo To me (I'm a noob to OH), this sounds like I just need to add the Gateway and my sensors will automatically show up in my inbox:

> Afterwards, discovery reads from the USB receiver / LaCrosseGateways to find out which sensors are currently connected. It then creates a thing for every unknown sensor and puts it in the Inbox.

Or does it mean, that discovery is automatically run after the creation?

With the knowledge I have now, I might have guessed reading the next paragraph:

> [...]  In rare cases, a second discovery run is needed.

I nobody minds I'd try to change the wording a bit and try make it easier to understand to non-experts.

**Comment by lolodomo** [comment]
discovery does not mean automatic discovery.
You could enhance something like that if you like: Afterwards, when you run it, discovery reads from the
