### ISSUE TITLE
[knx] Dimmer Item assumes a brightness value of 100% when switched on

### ISSUE THREAD

**Issue by smartheit** [openhab/openhab-addons#11985]
## Expected Behavior
When a ON command is sent the brightness value of a dimmer item should reflect the "real" brightness value not 100%.

## Current Behavior
When sending an "ON" command to the dimmer item the brightness state is always 100%. In my case the KNX DALI Gateway is configured to set the brightness value to the last known state.
This is the ETS bus monitor log:
![image](https://user-images.githubusercontent.com/88311932/148533121-6fd8446c-4afe-4c67-b170-7bb89dcb047e.png)

The On/Off commands were sent through OpenHAB. 

The dimmer item shows a brightness value of 100% not 30%:
![image](https://user-images.githubusercontent.com/88311932/148533524-a0a5f313-6aa9-419a-a2f2-fa2a23360cba.png)

The dimmer item is configured in the knx.things file:
`Type dimmer : Licht_EG_Wohnen_Wand [ switch="10/2/70+<11/2/70", position="13/2/70+<14/2/70", increaseDecrease="12/2/70" ]`

And the according item is:
`Dimmer Licht_EG_Wohnen_Wand        "EG Wohnen Wandlampe [%d %%]" <light> (gLicht, gLichterAn, gLichtAlarm) { channel="knx:device:bridge:lichter:Licht_EG_Wohnen_Wand" }`

When triggering a manual read of the GA containing the brightness readback value in the ETS the dimmer item updates with the correct value. In my test case reading from address 14/2/70 results in an updated item value (30% brightness)

## Context
The behavior is occurring in two OpenHAB installations, in my private Installation (JUNG Dali Gateway) and on the customers site (HAGER Dali Gateway) 

## Your Environment
Openhab Docker Container with OpenHAB 3.2.0
The behavior also occurred in previous versions including OH2.x

**Comment by Rossko57** [comment]
Please check your `events.log` for the effects of autoupdate feature on your Item.

**Comment by kaikreuzer** [comment]
As @Rossko57 says: The 100% event comes from the auto-update prediction. If you do not want this [you should disable auto-update for this item](https://www.openhab.org/docs/configuration/items.html#parameter-autoupdate), but in this case you should make sure that your KNX actuator sends a state update through a listening GA (`14/2/70`) to that channel.

**Comment by kaikreuzer** [comment]
Looking a bit closer at your KNX bus log, I think your problem is that the DALI gateway also sends a state update (ON) for `11/2/70`, which comes AFTER the update (30%) for `14/2/70`, so that this value gets overwritten.
I'd hence think that changing your config to 
```
Type dimmer : Licht_EG_Wohnen_Wand [ switch="10/2/70", position="13/2/70+<14/2/70", increaseDecrease="12/2/70" ]
```
should solve the issue.

**Comment by smartheit** [comment]
Autoupdate doesn't work either:

Item:
`Dimmer Licht_OG_Tim "OG Tim Spots" <light> (gLicht, gLichterAn, tim) ["Switch", "Light"]  { channel="knx:device:bridge:lichter:Licht_OG_Tim", autoupdate="false"}`

The KNX bus log:
![image](https://user-images.githubusercontent.com/88311932/148739289-9a0cbc62-fc3a-4290-af2d-c4bdbd843b65.png)

OH3 log:
```
09:50:00.323 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Licht_OG_Tim' changed from 100 to 6
09:50:00.353 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'Licht_OG_Tim' changed from 6 to 100
```

However Kai's suggestion does work: So removing the switch listening address from the dimmer item solves the issue for me.
This is due the DALI GW is configured to send always the brightness value. It could be that some DALI GWs might only send a "switch on" status value when triggered by an external light switch and then it would probably not work.

Under which circumstances does the OH dimmer item use the increaseDecrease group address? Can it be removed too?

Thanks for the hint Rossko and Kai.
Should we close the ticket ?

**Comment by kaikreuzer** [comment]
>  It could be that some DALI GWs might only send a "switch on" status value when triggered by an external light switch and then it would probably not work.

Right, but in such a case, openHAB would not stand any chance to actually know the correct status. So listening to ON/OFF and interpreting it as 100%/0% would probably the best guess then.

Glad that my suggestion solved the issue.

> Should we close the ticket ?

Yes, I'd say so.
