### ISSUE TITLE
[kostalinverter] PIKO discovery possible via Avahi/Zeroconf

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-addons#1198]
Just noticed that my Kostal inverter in the list of zeroconf devices, so it should be possible to add discovery to the binding:

```
Diensttyp: _http._tcp
Dienstname: pvserver
Domainname: local
Schnittstelle: eth0 IPv4
Adresse: PIKO.local/192.168.2.101:80
TXT seventaxZeroConf =
```
##

**Comment by cschneider** [comment]
Do you have any idea how to do this?

**Comment by thopiekar** [comment]
In java? Sadly no. But if I was using Python and the zeroconf module, then it is about asking for all available devices and filtering out by service type and name of the service.
Java itself is the restriction at the moment, that I don't contribute to OpenHAB with code.
Also I'm very limited in time at the moment, so I can't take time and learn.

**Comment by cschneider** [comment]
I think java is not the issue. As far as I know openhab uses https://github.com/jmdns/jmdns. I just have no clue how to leverage it from a binding.

**Comment by hmerk** [comment]
closed due to inactivity.
