### ISSUE TITLE
[somfytahoma] unsupported device: Ondeis rain sensor

### ISSUE THREAD

**Issue by ManInTheGitHub** [openhab/openhab-addons#11987]
Using Openhab 3.2.0 and just having an Ondeis rain sensor and Eolis IO wind sensor installed I noticed it was not picked up by the Somfy Tahoma binding. Information found in the logs:

```
Detected a new unsupported device: RainSensor with widgetName: RainSensor

Device definition:
Commands: { advancedRefresh (params: 1); }
States: {core:DiscreteRSSILevelState (values: good, low, normal, verylow); core:RSSILevelState (values: ); core:RainState (values: detected, notDetected); core:SensorDefectState (values: dead, lowBattery, maintenanceRequired, noDefect); core:StatusState (values: available, unavailable); }
2022-01-07 13:52:47.453 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 
{name='core:RainState', type=3, value=detected}
{name='core:StatusState', type=3, value=available}
{name='core:DiscreteRSSILevelState', type=3, value=normal}
{name='core:RSSILevelState', type=2, value=80.0}
```
And yes: it was indeed raining, so the RainState detected is correct :) Unfortunately it seems the wind data cannot be retrieved even though the rain sensor sends its data via the Eolis wind sensor...

**Comment by octa22** [comment]
Hi, I will look at it once I finish Hitachi Water Heating System implementation.
Thanks for your patience.
Ondrej

**Comment by ElectricBlue66** [comment]
Hi, I'm not too sure whether this is the right place to post this. But I'm sure someone can move it if it is wrong.

I recently installed my Somfy Tahoma Connectivity Kit and set everything up. In OH3 I added the SomfyTahoma binding and it automatically discovered my Somfy awning. However, OH3 does not automatically discover my roller shutters. I noticed that the log file reports the following:

`==> /var/log/openhab/openhab.log <==
2022-03-10 17:43:32.680 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: Shutter with widgetName: DynamicShutter
2022-03-10 17:43:32.695 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below
2022-03-10 17:43:32.697 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition:
Commands: { close (params: 0); goToAlias (params: 1); identify (params: 0); open (params: 0); saveAlias (params: 1); setName (params: 1); setNodeDefinition (params: 3); stop (params: 0); }
States: {core:AvailabilityState (values: available, unavailable); core:NameState (values: ); core:RemovableState (values: ); }
2022-03-10 17:43:32.700 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 
{name='core:AvailabilityState', type=3, value=available}`

This is reported 7 times, which matches the number of roller shutters. Looks like they are not supported. I tried to add them as things, but I don't know the Somfy Tahoma Device URL.

Can I find the ULR somewhere? Or are the roller shutters really not supported?

Thanks for any help.

Rob

**Comment by octa22** [comment]
Hi Rob, please create a new issue and paste the info as you did in your previous post. I will add the support.
Rollershutters are supported, but yours identify themselves as Shutters which we have not seen before.
Thanks.
Ondrej

**Comment by ElectricBlue66** [comment]
Hi Ondrej, which block should I post it in?

Rob

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by octa22** [comment]
this one :-)
```==> /var/log/openhab/openhab.log <== 2022-03-10 17:43:32.680 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: Shutter with widgetName: DynamicShutter 2022-03-10 17:43:32.695 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below 2022-03-10 17:43:32.697 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition: Commands: { close (params: 0); goToAlias (params: 1); identify (params: 0); open (params: 0); saveAlias (params: 1); setName (params: 1); setNodeDefinition (params: 3); stop (params: 0); } States: {core:AvailabilityState (values: available, unavailable); core:NameState (values: ); core:RemovableState (values: ); } 2022-03-10 17:43:32.700 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: {name='core:AvailabilityState', type=3, value=available}```
