### ISSUE TITLE
[systeminfo] Warning with remainingCapacity on system without battery

### ISSUE THREAD

**Issue by pavkamlc** [openhab/openhab-addons#12012]
## Expected Behavior
On system without battery, this shouldn't warn about this items

## Current Behavior
System warn with this:
[WARN ] [o.internal.handler.SysteminfoHandler] - No information for channel battery#remainingCapacity with device index 0 :

## Steps to Reproduce (for Bugs)

1. Only installed SystemInfo binding
2. See this warns every minute

## Context

I tried remove item with this channel, but binding generate warning always

## Your Environment

* HW guest PC on KVM (AMD hardware)
* OS Rocky Linux 8.5
* OH 3.2 from package
* Binding SystemInfo v3.2.0

**Comment by coop-git** [comment]
Did some checking: removing the item does not break the link. Deleting the Thing also removes the link.
You could create a new Item and click through to delete earlier links. Then delete item with breaking the link.
I checked the code and there is no check on IsLinked(channelUID). It compiled but I could not install it. Need to try later or it might be a hint for others.

**Comment by pavkamlc** [comment]
Yes, it was a problem. When remove item correctly, log is clean. Thanks.
