### ISSUE TITLE
[openwebnet] Thermo: add heating channel of type switch in addition to heatingValves

### ISSUE THREAD

**Issue by m4rky-m4rk** [openhab/openhab-addons#12019]
This feature was available for OH2 but not currently supported in OH3. It works at start up but the valve items are not updated after start up.

It is useful to create a heat map chart to track the whole house heating demand zone by zone

![image](https://user-images.githubusercontent.com/26285654/148777310-f0bd39ac-ccd6-4385-aa06-13fcfecbf803.png)

**Comment by mvalla** [comment]
> It works at start up but the valve items are not updated after start up.

which channel are you referring to exactly? can you provide specific steps to reproduce the issue?

**Comment by m4rky-m4rk** [comment]
Hi Massimo,
The problem was the item type changed from switch to text. Grafana/Influx  can work plot ON/OFF switch type and plots as 0,1 It does not work with text type ON/OFF. I have now created workaround rules that create a proxy item to reflect the actuator state as 0,1. 

M

**Comment by mvalla** [comment]
It looks like this is not a bug report (`heatingValves ` channel not being updated) but a new feature request to have a new `heating` utility channel of type Switch that reflects the on/off heating state for a zone (like it was defined in the binding testing version in OH2). Using rules/proxy items is possible to have the desired effect. 
Changed title and label.
