### ISSUE TITLE
[icalendar] Events without defined end are not working

### ISSUE THREAD

**Issue by daMihe** [openhab/openhab-addons#12026]
## Expected Behavior
Events without `DTEND` and `DURATION` should be valid events with start time = end time.

## Current Behavior
Events are ignored.

## Possible Solution
Use a default duration of 0s.

## Steps to Reproduce (for Bugs)
The published calendar at https://backend.stadtreinigung.hamburg/kalender/abholtermine.ics?hnIds=111111 has this issue in the wild. Use it as calendar URL.

## Context
https://community.openhab.org/t/icalender-binding-does-not-work-without-dtend/131600 (created from that thread)

## Your Environment
* Version used: OH 3.1

**Comment by clinique** [comment]
This has been adressed [here](https://github.com/openhab/openhab-addons/pull/12482).
