### ISSUE TITLE
[shelly] trv: missing channel for "schedule activated" and "schedule profile"

### ISSUE THREAD

**Issue by vandan381** [openhab/openhab-addons#12021]
hi,

first of all: excellent binding.

is it possible to add two channels: one for activating/deactivating the schedule and one to select the active schedule profile?

thank you in advance.

dan

**Comment by markus7017** [comment]
Support for boost mode is work-in-progress (check community thread)

I'm not sure if there is an inidicator for "schedule active". I don't want to implement parsing the rules and then checking if current time is within one of the schedules, but I need to check this in detailt.

**Comment by markus7017** [comment]
Implemented with PR #12325 
control#profile and
device#schedule
