### ISSUE TITLE
[knx] GroupRead / SendToKNX fails with NullPointerException

### ISSUE THREAD

**Issue by perrin-1** [openhab/openhab-addons#12040]
I recently upgraded from OH 2.5. to OH 3.2.0
In the logs I see some exceptions that seem to be related to KNX:

`2022-01-13 00:00:03.747 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.send(ProcessCommunicationResponder.java:256) ~[?:?]
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.write(ProcessCommunicationResponder.java:249) ~[?:?]
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.write(ProcessCommunicationResponder.java:226) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.sendToKNX(AbstractKNXClient.java:460) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.respondToKNX(AbstractKNXClient.java:439) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$8(DeviceThingHandler.java:297) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.sendGroupValueResponse(DeviceThingHandler.java:286) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$10(DeviceThingHandler.java:318) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupRead(DeviceThingHandler.java:312) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient$1.lambda$1(AbstractKNXClient.java:115) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$8(AbstractKNXClient.java:258) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
`
These exceptions occur roughly once a day at around 00:00. There are a couple of these exceptions (5-6) in the logs each day.

## Expected Behavior

No exceptions related to KNX should happen

## Possible Solution

I expect these exceptions to be bugs, but I currently have no idea, how to trace down the cause of the problem.

Maybe somebody can advise on steps to trace down the problem

## Your Environment

* Version used: openHAB 3.2.0
* Operating System and version: Ubuntu 18.04.6 LTS on VMware ESXi

**Comment by J-N-K** [comment]
It seems this happens when the bus tries to read a value from openHAB. Do you have control-channels in your setup? Can you read the GAs associated with these channels when using the ETS? If you can reproduce the issue: What channel-type is it and what is the state of the item linked to that channel?

**Comment by perrin-1** [comment]
Thanks for your idea to look at the -control channels. I was able to track the problem down using ets and querying the values of the control channel.
What happens is the following:
1. ETS queries value of control channel
2. OpenHAB sometimes answers with the correct value but most of the time it does not send an answer. Every time it logs the exception mentioned above.

This is the ETS log:
`#,Zeit,Dienst,Flags ,Prio,Quelladresse,Quellname,Zieladresse,Zielname,Rout,Typ,Info
39,"15.01.2022 22:44:14,632",zum Bus,,Niedrig,0.1.1,-,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueRead,
40,"15.01.2022 22:44:14,862",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 25 | 0,37"
49,"15.01.2022 22:44:31,143",zum Bus,,Niedrig,0.1.1,-,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueRead,
91,"15.01.2022 22:45:14,862",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 25 | 0,37"
124,"15.01.2022 22:46:14,862",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 2C | 0,44"
221,"15.01.2022 22:47:14,863",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 25 | 0,37"
249,"15.01.2022 22:48:14,863",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 25 | 0,37"
258,"15.01.2022 22:48:54,811",zum Bus,,Niedrig,0.1.1,-,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueRead,
265,"15.01.2022 22:49:06,380",zum Bus,,Niedrig,0.1.1,-,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueRead,
285,"15.01.2022 22:49:14,862",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 1F | 0,31"
346,"15.01.2022 22:50:14,870",vom Bus,,Niedrig,0.1.102,OpenHAB,6/0/28,Messwert Aussentemperatur SüdWest,6,GroupValueWrite,"00 19 | 0,25"`
(OpenHAB always correctly sends out the value of the temperature sensor, whenever there ist a MQTT Message with the temperature. This explains the GroupValueWrite messages)


This is the channel definition of the corresponding item in OpenHAB
`Number temperature_18b20 (esp_relay_outside) {channel="mqtt:topic:mqttbroker:ESPRelay:temperature18b20", channel="knx:device:bridge:ESPRelay:temperature"}`

This is the thing definition in knx.things:
` Thing device ESPRelay "ESP Relay" {
        // Type switch-control  : Sperre Rasenroboter [ga="1/2/12"]
        // Type number-control : temperatureDHT  "Temperature DHT" [  ]
        Type number-control : humidity     "Humidity"             [ ga="6/0/27" ]
        Type number-control : temperature  "Temperature DS18b20"  [ ga="6/0/28" ]
    }`

Is there something wrong with the channel / knx definition? Or could this be related to issues concerning persistence? (I have had numerous problems with persistence after migration)

**Comment by J-N-K** [comment]
There are two issues. The NPE is probably related to the upgrade of Calimero in #11759. 

The missing-write-after-read issue is caused by the changed behavior in https://github.com/openhab/openhab-addons/pull/4369. This is wrong. It could be that the handling of the REFRESH command changed between openHAB 2.4 and 3.x, but I'm not sure.

**Comment by perrin-1** [comment]
Since I have quiet a few of -control channels, I did some further tests with other channels.
The results are:
- no channel responds to a "GroupValueRead" with a "GroupValueResponse" or any other Response to KNX. The KNX bus remains silent. The only communication from OH to KNX are "GroupValueWrite"-Messages whenever a event triggers an update
- not every GroupValueRead to a control-channel results in a NPE. Roughly in 50% of the times a read triggers a NPE. Whenever a channel has a NPE, that NPE is reproductible on every single read. Alike when there is no NPE, a repeated read does not lead to a changed behaviour.
- I was not able to track down why a certain channel results in a NPE whereas another channel does not trigger a NPE. I have items that are linked to other channels as well as items that are calculated by OH and are only linked to KNX. NPEs occur with both channel types. 

So to conclude one can say that at the moment a "GroupValueRead" to a -control channel at OH is not answered at all and sometimes the read triggers a NPE.

Is there anything else I can to to help you track down the issue?

**Comment by FSeidinger** [comment]
I can confirm, that this issue is related to -control items and when you issue a `GroupValueRead` request from the KNX side (e.g. by reading with ETS in the group monitor).

The root cause, I guess is the introduction of the secure layer in the calimero library. The constructor of the `ProcessCommunicationResponder` now takes two arguments. A link and a `SecureApplicationLayer ` instance. This is the relevant part from the calimero lib:

```
/**
 * Creates a new process communicator attached to the supplied KNX network link.
 * <p>
 * The log service used by this process communicator is named "calimero.device.process " +
 * <code>link.getName()</code>.
 *
 * @param link network link used for communication with a KNX network
 * @param sal security application layer
 * @throws KNXLinkClosedException if the network link is closed
 */
public ProcessCommunicationResponder(final KNXNetworkLink link, final SecureApplicationLayer sal)
		throws KNXLinkClosedException {
	if (!link.isOpen())
		throw new KNXLinkClosedException(
				"cannot initialize process communication using closed link " + link.getName());
	lnk = link;
	this.sal = sal;
	logger = LogService.getLogger("calimero.device.communication " + link.getName());
	listeners = new EventListeners<>(logger);
}
```
The security application layer must not be null, although this precondition is not checked by the constructor. The problem arises, when you use the `send` method:

```
private void send(final GroupAddress dst, final Priority p, final byte[] plainApdu)
		throws KNXTimeoutException, KNXLinkClosedException {
	final var src = lnk.getKNXMedium().getDeviceAddress();
	try {
		final byte[] apdu = sal.secureGroupObject(src, dst, plainApdu).orElse(plainApdu);
		lnk.sendRequest(dst, p, apdu);
	}
	catch (final InterruptedException e) {
		Thread.currentThread().interrupt();
	}
}
```
The statement `sal.secureGroupObject(src, dst, plainApdu).orElse(plainApdu)` will result in a `NullPointerExeption` if the member `sal` is `null`.

The `AbstractKNXClient` exactly does that, initializing the `ProcessCommunicationResponder` with a security layer of `null`:

```
private synchronized boolean connect() {
    ...

        ProcessCommunicationResponder responseCommunicator = new ProcessCommunicationResponder(link, null);

    ...
}
```

After browsing the calimero code, I guess that there is an easy fix. You can initialize the `ProcessCommunicationResponder` with a security application layer, that simply has no security. It should work like that:

```
private synchronized boolean connect() {
    ...

        ProcessCommunicationResponder responseCommunicator = new ProcessCommunicationResponder(link,
                    new SecureApplicationLayer(link, Security.defaultInstallation()));

    ...
}
```

I will try that today and if it works, I will open a pull request.

**Comment by FSeidinger** [comment]
I've tested the changes and the `NullPointerException` is gone and the Binding seems fully functional. I will no create a pull request for the fix.

**Comment by perrin-1** [comment]
Thank you very much for your great work on OpenHAB
