### ISSUE TITLE
[shelly] Door/Window 2 (dw2) status events not working

### ISSUE THREAD

**Issue by TheTrueRandom** [openhab/openhab-addons#12063]
## Expected Behavior

Status events should be received for linked items.

## Current Behavior

Events are not received. Below configuration for the thing and the items are used. Thing is shown as ONLINE on the openhab UI. Also I can see no log entries for this device. Even when pressing the button no event is received. The only way the status are updated  is when reloading the thing configuration (save the .things file again) and then press the button on the shelly. However the status is only updated one single time. Afterwards no status is updated until doing the same again.

I tried with eventsCoIoT true and false. 
When not using openhab and adding the action URL on the shelly web UI to a temporary http-server, every event is correctly received (So I think the shelly is working fine.)

```
Thing shelly:shellydw2:test "Shelly dw2 test" [deviceIp="192.168.10.42", userId="", password="", eventsCoIoT=true]
```

```
Number:Temperature      ShellyDw2testSensorsTemperature     "Sensors temperature"      {channel="shelly:shellydw2:test:sensors#temperature"}
Number:Illuminance      ShellyDw2testSensorsLux             "Sensors lux"              {channel="shelly:shellydw2:test:sensors#lux"}
Contact                 ShellyDw2testSensorsState           "Sensors state"            {channel="shelly:shellydw2:test:sensors#state"}
Number:Angle            ShellyDw2testSensorsTilt            "Sensors tilt"             {channel="shelly:shellydw2:test:sensors#tilt"}
Number:Dimensionless    ShellyDw2testBatteryBatteryLevel    "Battery battery level"    {channel="shelly:shellydw2:test:battery#batteryLevel"}
Switch                  ShellyDw2testBatteryLowBattery      "Battery low battery"      {channel="shelly:shellydw2:test:battery#lowBattery"}
String                  ShellyDw2testDeviceWakeupReason     "Device wakeup reason"     {channel="shelly:shellydw2:test:device#wakeupReason"}
DateTime                ShellyDw2testSensorsLastUpdate      "Sensors last update"      {channel="shelly:shellydw2:test:sensors#lastUpdate"}
```

## Steps to Reproduce (for Bugs)

see the thing and item configuration above. 

## Your Environment

* Version used: (e.g., openHAB and add-on versions) openHAB 3.2.0 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Shelly Firmware: 20211109-125737/v1.11.7-g682a0db
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspberry Pi: Linux openhabian 5.10.63-v8+

**Comment by markus7017** [comment]
will be included in PR #12325

**Comment by TheTrueRandom** [comment]
@markus7017 I could not see a single log entry regarding shelly dw2

**Comment by markus7017** [comment]
Download and install latest DEV build
Open the DW2 Web Ui -> Settings -> COIOT and set the peer address to your OH interface IP
go to the OH console and enter:  log.set DEBUG org.openhab.binding.shelly

We tested DW2 and it worked well

**Comment by TheTrueRandom** [comment]
works :+1:
