### ISSUE TITLE
[boschshc] Support for Bosch Universal Switch Flex

### ISSUE THREAD

**Issue by mdoninger** [openhab/openhab-addons#12077]
I noticed, that the Bosch Universal Switch Flex is not supported yet by the binding. While testing with the ReST API of the Bosch controller, it looks like usage of the switch issues proper messages on the long polling API, which could be processed by the binding. Before i start looking more into detail and try to implement support for it, i just wanted to check if somebody else is already working on it. If not, i will try to work on it and submit a PR.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by haesslo** [comment]
I would also love to see the normal "Universal Switch" supported....

**Comment by pat-git023** [comment]
Hi,
I had a look into the Universal Switch Flex device and saw that the actions are received as a "scenario" via the long polling API. The changes can be found here: [https://github.com/pat-git023/openhab-addons/pull/1/files](https://github.com/pat-git023/openhab-addons/pull/1/files)
A build for testing can be found here: https://github.com/pat-git023/openhab-addons/suites/15778759822/artifacts/900543479

Please have a look and give Feedback if this would be good for a PR.

Best regards,
Patrick

**Comment by david-pace** [comment]
Scenario support is now merged (https://github.com/openhab/openhab-addons/pull/15752) and will be released with openHAB 4.1. Please test once it is released and let us know if this covers your use cases. Otherwise, please describe in more detail which things / channels you would need.

**Comment by mdoninger** [comment]
From my first short tests, your new implementation covers my usecases, thank you very much for adding the functionality. I'll close this ticket.
