### ISSUE TITLE
[miio] Support New device zhimi.airp.mb4a

### ISSUE THREAD

**Issue by Krata4** [openhab/openhab-addons#12075]
Hello,

I bought Xiaomi Mi Air Purifier 3C today and device model is "zhimi.airp.mb4a" which is unsupported. Can you add support for this model please?

[zhimi.airp.mb4a-miot-experimental.zip](https://github.com/openhab/openhab-addons/files/7898617/zhimi.airp.mb4a-miot-experimental.zip)

Thanks
Jirka

**Comment by marcelrv** [comment]
Thanks for attaching the file.
With this experimental file, can you confirm all the channels are working as expected?

**Comment by Krata4** [comment]
I tried to do manual override on "zhimi.airpurifier.mb4" and it is working fine. I gues it is only configuration that model "zhimi.airpurifier.mb4" and model "zhimi.airp.mb4a" is same.
