### ISSUE TITLE
[yeelight] Add Yeelight YLDP15YL White model to binding (mono4)

### ISSUE THREAD

**Issue by TomMarg** [openhab/openhab-addons#12073]
I've added a new Yeelight Bulb to my setup and would love to control it through the binding.

Product is a Yeelight Smart LED Bulb 1S (Dimmable) with no colors.

Here are the device details from discover_bulbs():
``[{'ip': '192.168.2.111', 'port': 55443, 'capabilities': {'id': '0x0000000011111111', 'model': 'mono4', 'fw_ver': '7', 'support': 'get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_name set_adjust adjust_bright', 'power': 'on', 'bright': '36', 'color_mode': '2', 'ct': '4000', 'rgb': '0', 'hue': '0', 'sat': '0', 'name': ''}}]`

`

Any chance to have this added to the plugin?

**Comment by TomMarg** [comment]
Nevermind - I found out that I could use another binding.

**Comment by Cypris2010** [comment]
I'd like to have it in the binding.

**Comment by TomMarg** [comment]
+1 

The Xiaomi binding drives me mad, while this binding stays very stable and responsive.
