### ISSUE TITLE
[deconz] phoscon zigbee binding, reboot issues, IP address loss

### ISSUE THREAD

**Issue by thales-man** [openhab/openhab-addons#12082]
goes into a perpetual state of 'initializing'
Advanced tab, check your IP address, for some reason mine reverts to a class C '10' address.
It's never been set to this as I don't use them

## Expected Behavior
I don't expect the IP address to change randomly and disconnect half the system.

## Current Behavior
As described.

## Possible Solution
??

## Steps to Reproduce (for Bugs)
Reboots are proving the most problematic. They don't work. It generally then requires a further OH3 restart to get the binding to 'kick in'. This is the first time this issue has occurred.

## Context
It's annoying, took time to find as the IP address change is hidden under 'advanced'.

## Your Environment
Openhab image on RPi 4. updated to 3.2.0

**Comment by olemr** [comment]
FYI:
I don't see this on my rpi4 running debian OH 3.2.0 Release build, deconz 2.13.02 on same machine. (rpi4 booting from SSD)
No problems after restarts:
![image](https://user-images.githubusercontent.com/28068256/150694398-830592f6-3a9e-48c1-acb6-435dffbe1b81.png)

**Comment by thales-man** [comment]
and your point is?

**Comment by J-N-K** [comment]
I still don‘t understand what you are trying and what your problem is. If you use the deconz binding, then the IP is not under „advanced“. If you use the ZigBee binding, then the deconz tag is wrong.

**Comment by thales-man** [comment]
i'm not 'trying' anything. i'm reporting aberrant behavior. you are right though, it isn't under the advanced tab, my bad...
