### ISSUE TITLE
[mihome] Gateway goes offline after 5 minutes

### ISSUE THREAD

**Issue by goodfore** [openhab/openhab-addons#12094]
I have a Xiaomi gateway v2. I have been using it for my OH 2.5 instance without any issues. I installed a OH 3.2 instance and started configuring it. I added the Xiaomi binding and adding a V2 gateway in. The Thing seems to be connected ok at first, showing all the connected devices etc, however after 5 minutes or so, it would go to disconnect state.

Since I have both OH 2.5 and OH 3.2 instances, I can confirm that the gateway is working as expected with the OH 2.5.

A quick search in the community forum shows that others have the same issue, and it can be fixed by adding serialNumber (MAC address of gateway without : or -) in the Thing configuration.

## Expected Behavior
It seems like serialNumber is a required field, it should be added as a required field in the add Thing menu.

## Current Behavior
When adding gateway, it does not ask for serialNumber. Without it the Thing would go offline after 5 minutes.

## Possible Solution
Make serialNumber a required field

## Steps to Reproduce (for Bugs)
1. Add Xiaomi binding in OH 3.2
2. Add Thing -> Xiaomi -> Xiaomi Mi Smart Home Bridge
3. Enter in IP and developer key

## Context
Thing don't work properly without entering the serial number

## Your Environment
OH 3.2 on docker in Raspberry Pi 4/Zerio

**Comment by goodfore** [comment]
Tested on OH 3.3 on docker in RPi 4/Zero. Bug still exists.

**Comment by lsiepel** [comment]
Still an issue with 4.0.x? When looking at the thing config, the channel is readonly.
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/config/config.xml#L16
