### ISSUE TITLE
Paring problem - how to reset and HomeKit and start all over?

### ISSUE THREAD

**Issue by maisun** [openhab/openhab-addons#12090]
Hi,
I've been trying to get HomeKit integration to work since OH 3.0 without luck, looks to me that HomeKit cannot discover the bridge and pairing always timeout with an error message "Accessory Not Found". I'm currently running OH 3.2.0 with the HomeKit add-on version 3.2.0. I have tried to remove/re-install the add-on without luck, looks to me that it alway remembers the settings like it was never removed. I run OpenHAB in Docker on my NAS with the network "--net=host". I run HomeBridge also in Docker with the same settings without problem. In Discovery (mDNS browser) I do not see the OpenHAB HomeKit bridge in the list. Any suggestion how to trouble shoot the issue? Thank you in advance!

**Comment by MrRSK** [comment]
Hi,
i've got the same issue.
Removed opbenHAB Bridge from my Home and tried to reset the pairing.

1. Uninstalled Homekit Addon
2. Restart openhab
3. Install Homekit Addon (tried and failed to connect the Bridge)
4. Changed Pin and Setup ID
5. restart openhab (tried and failed to connect the Bridge)
6. Console command homekit clearPairings
7. restart openhab (tried and failed to connect the Bridge)
8. Discovery DNS App shows txt Record sf = 0, openHAB thinks its still paired

Hope somebody can help me.

**Comment by yfre** [comment]
these are 2 different issues
1. @maisun  if you dont see OpenHAB HomeKit bridge in Discovery (mDNS browser) then 
  - it is network issue. mDNS does not get forwarded from docker to host or from host to wireless network. Please check in forum, there were several discussion related to docker settins
  - binding issue, i.e. binding is not running. please check on the list of bindings in karaf

2. @MrRSK actually "clearPairings" should be sufficient. 
if you use version 3.2 please make sure the "Block deletion of the HomeKit user" is deactivated
![image](https://user-images.githubusercontent.com/11726616/153889928-e2527bd4-d5b2-48ee-b1a1-af9da23bb8f9.png)
if it is deactivated and clearPairings still does not work, then find homekit.json file and remove "user" entry from it.

**Comment by yfre** [comment]
closing as no feedback provided. 
there were also major improvements in homekit biding since this issue was reported
