### ISSUE TITLE
[wemo] Refactoring code duplication

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12100]
When reviewing #12001 it turned out that some technical debt needs to be paid for this binding in order to progress without too much pain. The biggest issue is the code duplication between handlers which required the contributor to spend more time on duplicate work and me to spend more time on the review. While handling some regressions and looking deeper into the code some other improvement opportunities was revealed.

Phase 1:
- Remove code duplication between handlers by introducing a new `WemoBaseThingHandler` providing common logic. For example, `getHost()` is duplicated in all handlers.
- Delete class `AbstractWemoHandler` which provides no value. Move `WemoHttpCall` instance to `WemoBaseThingHandler`.
- Move service helper methods to `WemoBaseThingHandler` (for example `isUpnpDeviceRegistered()`).

Phase 2:
- Refactor UPnP subscription handling and centralize it in `WemoBaseThingHandler`.
- Remove or fix `subscriptionState` as it is unused/incorrectly implemented: Status (success/failure) is not read anywhere, so calling `addSubscription()` after `onServiceSubscribed()` has received failure will not try to subscribe again. Also, even without any confirmation from `onServiceSubscribed()`, subscription will be cached as successful.
- Fix bug in `handleCommand` in all handlers: After catching exception marking thing **OFFLINE**, it will immediately be marked as **ONLINE** in next line.

Phase 3:
- Reuse UDN configuration parameter in XML files.
- Fix already configured devices showing up in inbox (file-based configuration).

Phase 4:
- Consolidate host initialization/caching in `WemoBaseThingHandler`.
- Simplify usage of `getWemoURL` and remove redundant error handling.

See also related: #12105.

**Comment by hmerk** [comment]
Thanks @jlaur for starting this.
I already tried to find docuentation for EnergyPerUnitCost , but could not find any. Supporting this will be difficult.

**Comment by hmerk** [comment]
Here are some Ideas from my side : 
- move ZonedDate creation to WemoUtil class
- Extract shared code from attribute parsing and move to WemoUtil class

**Comment by hmerk** [comment]
I thinnk, I have found some explanation for EnergyPerUnitCost.
It delivers three params : 
EnergyPerUnitCost
Currency [3 digit code according ISO 4217]
EnergyPerUnitCostVersion

**Comment by hmerk** [comment]
Thinking a bit more about it, we could introduce a new WemoInsightHandler, with the complex parsing. Wemo Socket, Lightswitch  and Motion only deliver a BinaryState (0/1) so onValueReceived could be changed in WemoBaseThingHandler or WemoHandler to just parse the binaryStates.... All other handler classes then could override this....

**Comment by hmerk** [comment]
@jlaur Following your start, I have done some more refactoring of the WemoHandler classes. How can I create a pull request against your fork ?????

**Comment by jlaur** [comment]
> we could introduce a new WemoInsightHandler, with the complex parsing.

I agree that we should introduce new handlers for each distinct device. First we need to make sure that this can be done without introducing new redundancy, though, i.e. by using inheritance (wisely) and additional classes. However, I do not agree that the complex parsing belongs in `WemoInsightHandler`. Please see my proposal with was moved to #12105.

> Wemo Socket, Lightswitch and Motion only deliver a BinaryState (0/1) so onValueReceived could be changed in WemoBaseThingHandler or WemoHandler to just parse the binaryStates.... All other handler classes then could override this....

As WeMo Insight will not receive that form of BinaryState, it should be part of this inheritance hierarchy. I would suggest something like this:
```
| WemoBaseThingHandler
|-- WemoSomethingCommonForSocketLightSwitchAndMotionHandler
|   |-- WemoSocketHandler
|   |-- WemoLightSwitchHandler
|   |-- WemoMotionHandler
|-- WemoInsightSwitchHandler
```

I'm not much into what Socket, Light Switch and Motion are, but it seems like they have a lot in common?

**Comment by hmerk** [comment]
> I'm not much into what Socket, Light Switch and Motion are, but it seems like they have a lot in common?

Socket, Lightswitch and Motion devices only have BinaryState variable for command handling and state report, so handle command can be reduced to just a few lines if we move WemoInsight to it‘s own handler. before refactoring/ extracting the parsing, I would finish to reduce duplicate code, ass I already suggested in your PR.
Did you check the sources I did send to you via email ?
Any chance we could chat or have a call to further discuss ??
