### ISSUE TITLE
[zwave] battery device (thing) is never offline despite removed battery for weeks.

### ISSUE THREAD

**Issue by TheTrueRandom** [openhab/openhab-addons#12102]
## Expected Behavior
As stated in the [documentation](https://www.openhab.org/addons/bindings/zwave/#battery-devices) a battery device will be DEAD/OFFLINE "approximately twice the wakeup period". 

## Current Behavior

I use a [FGSD002 Smoke Detector](https://www.openhab.org/addons/bindings/zwave/thing.html?manufacturer=fibaro&file=fgsd002_0_0.html) and a Aeotec AEOEZW090-C usb zwave stick. I added the controller and the device as a thing to openhab and it works perfectly. However, the device is always listed as ONLINE. By now I removed the batteries of the smoke detector for a week and the device is still listed at ONLINE.

Also I noticed that specifying wakeup_interval on the thing configuration is ignored. I can read the value on the UI though, which is set to 21600. So the device should be considered OFFLINE after approx. 12h. By now I removed the batteries for 168h.

## Steps to Reproduce (for Bugs)

1. Add the below configuration to openhab
2. See the device to be listed as online on openhab
3. Remove the batteries of the smoke detector
```
Bridge zwave:serial_zstick:controller "ZWave Controller" [ port="/dev/ttyACM1", security_networkkey="<hidden>" ] {
    fibaro_fgsd002_03_002 office "Smoke Detector Office" [ node_id=4, wakeup_interval=60 ]
}
```

## Context

I would like to know when a smoke detector is not reachable anymore.

## Your Environment

*Version used: (e.g., openHAB and add-on versions) openHAB 3.2.0 Release Build
*Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
*Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspberry Pi: Linux openhabian 5.10.63-v8+

**Comment by lsiepel** [comment]
The z-wave binding has it's own repo. Please post this issue at https://github.com/openhab/org.openhab.binding.zwave/issues

**Comment by TheTrueRandom** [comment]
https://github.com/openhab/org.openhab.binding.zwave/issues/1742
