### ISSUE TITLE
[smaenergymeter] binding unplausible values

### ISSUE THREAD

**Issue by drego83** [openhab/openhab-addons#12142]
hey,
i tested with smaenergymeter 3.2.0 and 3.3.0 as version.
I get every 30 seconds unplausible values like:
-2210282340352
-789146370048
and others ...
mostly alternating with the correct value.
This error causes on all channels by the binding ...

anything an idea?

**Comment by DollC** [comment]
Same problem since a few days.
Got an Update of HomeManager by SMA

Firmware-Version des Hauptprozessors | 2.08.5.R | 24.01.2022 23:05:40
Firmware-Version des Betriebssystems | 3.13.0.R | 24.01.2022 23:05:40

**Comment by DollC** [comment]
Kann vielleicht jemand, der sich damit auskennt mal schauen ob sich vielleicht einfach die Multicast Message verändert hat? Habe mich heute versucht einzulesen, bin aber gerade noch etwas überfragt. Vielleicht muss man "einfach" nur andere Bereiche lesen?

**Comment by DollC** [comment]
Maybe this gives a hint how to solve the problem ? http://www.eb-systeme.de/?page_id=3005

**Comment by DollC** [comment]
@kaikreuzer, @Hilbrand , @marcelrv or @wborn I just checked the code and see that you contributed something to this binding. Maybe you can help us solving the problem? Thanks!

**Comment by wborn** [comment]
Isn't this the same issue as https://github.com/openhab/openhab-addons/issues/11497?

**Comment by DollC** [comment]
Yes. It looks like it is the same

**Comment by wborn** [comment]
OK let's close this issue then. I can't really help as I do not use that binding myself.
