### ISSUE TITLE
[millheat] Channels missing

### ISSUE THREAD

**Issue by multimartin** [openhab/openhab-addons#12166]
Channels for targetTemperature and masterSwitch is missing for thing type "heater" compared to the documentation - making the binding unusable to control the heaters ?

**Comment by KeepItSimple4all** [comment]
Hello Togehter,

here "Michael_Nemecky" maybe found the problem....
https://community.openhab.org/t/solved-millheat-wifi-electric-heater-openhab-binding/17224/66?u=smarthome4all
