### ISSUE TITLE
[tado] could not apply HVAC change on home and zone: operation updateZoneOverlay failed with error 422

### ISSUE THREAD

**Issue by Artur-Fedjukevits** [openhab/openhab-addons#12160]
## Expected Behavior
When setting a hvac mode, everything should work as normal

## Current Behavior
When trying to set the hvac mode at the moment, the following error is raised and nothing happens:

`2022-01-29 19:41:21.754 [DEBUG] [ado.internal.handler.TadoZoneHandler] - Setting overlay of home 680446 and zone 1
2022-01-29 19:41:21.820 [WARN ] [ado.internal.handler.TadoZoneHandler] - Could not apply HVAC change on home 680446 and zone 1: Operation updateZoneOverlay failed with error 422
org.openhab.binding.tado.internal.api.ApiException: Operation updateZoneOverlay failed with error 422
	at org.openhab.binding.tado.internal.api.client.HomeApi.updateZoneOverlay(HomeApi.java:625) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.setOverlay(TadoZoneHandler.java:110) ~[?:?]
	at org.openhab.binding.tado.internal.TadoHvacChange.apply(TadoHvacChange.java:123) ~[?:?]
	at org.openhab.binding.tado.internal.handler.TadoZoneHandler.lambda$0(TadoZoneHandler.java:303) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

## Steps to Reproduce (for Bugs)

I had a software update on Tado AC Control (restart AC setup). I got the mail from Tado:

> We have good news for you
> Hello Artur,
> 
> There is a free update available for your tado° Smart AC Control.
> 
> The update includes the following improvements:
> 
> **Additional fan speeds
> More swing functions
> Temperature setting in AUTO mode**
> 
> 
> How can I start the update?
> 
> 1. Make sure your Smart AC Control is connected to the internet
> 2. You need the original AC remote
> 3. Standing near to the tado° Smart AC Control
> 4. Open the tado° app and go to the Settings and select Rooms & Devices
> 5. Select the room with the Smart AC Control
> 6. Choose Restart AC Setup and follow the installation steps

After I followed these steps, I got this issue. Now I can only turn off the AC. For all other HVAC change commands, I get a 422 API exception. 

## Possible Solution

I suspect it's because Tado changed their API along with the new AC Smart Control software.

## Your Environment

* Version used: openHAB 3.2 and add-on versions 3.2
* Environment name and version: OpenJDK Runtime Environment Zulu11
* Operating System: Ubuntu 20.04

**Comment by Artur-Fedjukevits** [comment]
As I found, the new API expects new parameters (vertical swing, horizontal swing), and they changed the fan speed parameter (it is now called fanLevel).
![tado](https://user-images.githubusercontent.com/87441995/152432757-8a715cbf-626b-4a48-af63-9f8b925fbb45.jpg)

![tadofanspeed](https://user-images.githubusercontent.com/87441995/152432625-3f841862-1058-4246-9678-b4727d2f6aa3.jpg)

![tadoverticalswing](https://user-images.githubusercontent.com/87441995/152432628-91bec292-2957-49f7-9005-e06b1f51309c.png)

![tadohorizontalswing](https://user-images.githubusercontent.com/87441995/152432621-8bad989d-b97d-45c6-b92a-967be2a6da2c.png)

This parameters now I need to add somehow:

`public static enum fanLevel {
        SILENT,
        LEVEL1,
        LEVEL2,
        LEVEL3,
        LEVEL4,
        AUTO
     }
     
     public static enum horizontalSwing {
       LEFT,
       MID_LEFT,
       MID,
       MID_RIGHT,
       RIGHT,
       ON
     }
     
     public static enum verticalSwing {
       AUTO,
       UP,
       MID_UP,
       MID,
       MID_DOWN,
       DOWN,
       ON
     }`

**Comment by Artur-Fedjukevits** [comment]
I edited the addon in some places and recompiled it, now it works fine. But without backward compatibility. If anyone needs it, I can send the source code or the compiled jar file.

**Comment by hpalne** [comment]
@Artur-Fedjukevits 
Hi I would ver happy if you could send me the source code and compiled jar file

BR
Henrik

**Comment by Artur-Fedjukevits** [comment]
No problem. 

[https://fedjukevitsh.com/s/dGWHWijdy9DBqcT](url)

**Comment by Artur-Fedjukevits** [comment]
I'm just forget add MID-UP option to thing.xml, now it's fixed. And I replaced all SILENT to LEVEL5 in the code. Try it now:
[org.openhab.binding.tado.zip](https://github.com/openhab/openhab-addons/files/8103670/org.openhab.binding.tado.zip)

**Comment by hpalne** [comment]
> I just forgot to add the MID-UP option to thing.xml, now it's fixed. And I replaced all SILENT in the code with LEVEL5. Try this now: [org.openhab.binding.tado.zip](https://github.com/openhab/openhab-addons/files/8103670/org.openhab.binding.tado.zip)

Thanks it works fantastic :-)

**Comment by andrewfg** [comment]
> I edited the addon in some places and recompiled it

@Artur-Fedjukevits are you planning to open a Pull Request to merge your changes back into openHAB main?

**Comment by Artur-Fedjukevits** [comment]
> > I edited the addon in some places and recompiled it
> 
> @Artur-Fedjukevits are you planning to open a Pull Request to merge your changes back into openHAB main?

As I'm said, it without backwards compatibility.  And as it turned out there may be different options with different model of AC. This code will not work for everyone.

**Comment by andrewfg** [comment]
> This code will not work for everyone

Ok. Do you mind if I play around with your code, to see if I can make it forward / backward compatible? If I find a solution, then we can create a PR from that.

**Comment by andrewfg** [comment]
^
I put your source code on a [new branch of my fork of the OH main repo](https://github.com/andrewfg/openhab-addons/tree/tado-newer-api/bundles/org.openhab.binding.tado) and over the next few days I will have a look at how to make it work with various versions of the API..

**Comment by andrewfg** [comment]
@Artur-Fedjukevits to help identify what changed between the API / device updates, it would be interesting to compare API JSON responses when your new version of the binding talks to your (new) Smart AC controller against when my old version of the binding talks to my own (older) AC controller. Obviously I have the latter data, so could you please `log:set DEBUG org.openhah.binding.tado` on your version of the binding and post the respective log outputs for your new AC controller here?

**Comment by andrewfg** [comment]
> could you please log:set DEBUG org.openhah.binding.tado

Oops sorry @Artur-Fedjukevits but I realise that this logger setting does not log the JSON payloads; so we need to use the Chrome DevTools (as you did before) to allow me to compare my JSON with yours.

Specifically I would need to see your JSON payload for `deviceList`, `zones`, `capabilities` (for that specific a/c device), and `zoneStates` -- see screenshots below. If you click your mouse on the DevTools 'Response' tab the Ctrl-A, Ctrl-C, Open Notepad, Ctrl-C, then you can capture and save the full raw data. If you don't want to post the openly data here, then you can email me privately (you can find my address under my GitHub profile).

![Snag_b7de84b](https://user-images.githubusercontent.com/893994/156931624-9512b28b-a929-47e3-95e8-89d619181d59.png)

![Snag_b7e1f69](https://user-images.githubusercontent.com/893994/156931633-5128b5f8-8670-4685-bdae-28c1bb90ecad.png)

![Snag_b7e68a7](https://user-images.githubusercontent.com/893994/156931649-078ba5c8-56f6-4ccd-be01-e766211499ea.png)

![Snag_b7e9758](https://user-images.githubusercontent.com/893994/156931655-61745caa-eec1-4a1d-81ef-a9a5378c5443.png)

**Comment by Artur-Fedjukevits** [comment]
There was changes only in capabilities. This is my json: 
`class AirConditioningCapabilities {
    class GenericZoneCapabilities {
        type: AIR_CONDITIONING
    }
    COOL: class AcModeCapabilities {
        temperatures: class TemperatureRange {
            celsius: class IntRange {
                min: 16
                max: 31
                step: 1.0
            }
            fahrenheit: class IntRange {
                min: 61
                max: 88
                step: 1.0
            }
        }
        fanLevel: [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO]
        horizontalSwing: [ON, LEFT, MID_LEFT, MID, MID_RIGHT, RIGHT]
        verticalSwing: [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO]
    }
    HEAT: class AcModeCapabilities {
        temperatures: class TemperatureRange {
            celsius: class IntRange {
                min: 16
                max: 31
                step: 1.0
            }
            fahrenheit: class IntRange {
                min: 61
                max: 88
                step: 1.0
            }
        }
        fanLevel: [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO]
        horizontalSwing: [ON, LEFT, MID_LEFT, MID, MID_RIGHT, RIGHT]
        verticalSwing: [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO]
    }
    DRY: class AcModeCapabilities {
        temperatures: null
        fanLevel: [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO]
        horizontalSwing: [ON, LEFT, MID_LEFT, MID, MID_RIGHT, RIGHT]
        verticalSwing: [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO]
    }
    FAN: class AcModeCapabilities {
        temperatures: null
        fanLevel: [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO]
        horizontalSwing: [ON, LEFT, MID_LEFT, MID, MID_RIGHT, RIGHT]
        verticalSwing: [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO]
    }
    AUTO: class AcModeCapabilities {
        temperatures: class TemperatureRange {
            celsius: class IntRange {
                min: 16
                max: 31
                step: 1.0
            }
            fahrenheit: class IntRange {
                min: 61
                max: 88
                step: 1.0
            }
        }
        fanLevel: [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO]
        horizontalSwing: [ON, LEFT, MID_LEFT, MID, MID_RIGHT, RIGHT]
        verticalSwing: [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO]
    }
}`

**Comment by andrewfg** [comment]
@Artur-Fedjukevits many thanks for the info. I will have a look at in the next days to compare with my own (older) AC controller.

**Comment by andrewfg** [comment]
@Artur-Fedjukevits I think the reason why your code is not backward compatible is that although you correctly added the new sub-elements `fanLevel`, `verticalSwing` and `horizontalSwing` to the YAML file, you should NOT have deleted the sub-elements `fanSpeed` and `swing`. If the parser finds a JSON sub element of the respective name, it will instantiate the respective Java class, and if not then the class instance is `null`; so including both potential sets of sub-elements is not a problem.

Therefore, I will rework your code based on not deleting those older capabilities..

Nevertheless I do have a couple more questions concerning inconsistencies in your code..
1. Your `fanLevel` JSON payload (above) shows the options [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO], whereas your YAML entry definition has "LEVEL5, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO". => Was there some reason why you changed 'SILENT' to 'LEVEL5' ??

2. Your `verticalSwing` JSON payload (above) has options [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO] whereas your `horizontalSwing` is similar except without an 'AUTO' option. => Can you please tell me if your physical A/C remote control has a horizontalSwing=AUTO possibility or not? I wonder if we should in include 'AUTO' as a possibility in the code "just-in-case" ???

**Comment by hpalne** [comment]
Hi 
I don't know if it is of any relevans but if I look at the Capabilities reported back from the Tado API it is slightly different. There i e.g., no Horizontal Swing, and for Fan Level I have no Silent
`{
   "type":"AIR_CONDITIONING",
   "AUTO":{
      "temperatures":{
         "celsius":{
            "min":16,
            "max":31,
            "step":1.0
         },
         "fahrenheit":{
            "min":61,
            "max":88,
            "step":1.0
         }
      },
      "fanLevel":[
         "LEVEL4",
         "LEVEL5",
         "LEVEL1",
         "LEVEL2",
         "LEVEL3",
         "AUTO"
      ],
      "verticalSwing":[
         "MID_DOWN",
         "MID_UP",
         "DOWN",
         "AUTO",
         "UP",
         "MID"
      ]
   },
   "FAN":{
      "fanLevel":[
         "LEVEL4",
         "LEVEL5",
         "LEVEL1",
         "LEVEL2",
         "LEVEL3",
         "AUTO"
      ],
      "verticalSwing":[
         "MID_DOWN",
         "MID_UP",
         "DOWN",
         "AUTO",
         "UP",
         "MID"
      ]
   },
   "DRY":{
      "temperatures":{
         "celsius":{
            "min":16,
            "max":31,
            "step":1.0
         },
         "fahrenheit":{
            "min":61,
            "max":88,
            "step":1.0
         }
      },
      "fanLevel":[
         "LEVEL4",
         "LEVEL5",
         "LEVEL1",
         "LEVEL2",
         "LEVEL3",
         "AUTO"
      ],
      "verticalSwing":[
         "MID_DOWN",
         "MID_UP",
         "DOWN",
         "AUTO",
         "UP",
         "MID"
      ]
   },
   "HEAT":{
      "temperatures":{
         "celsius":{
            "min":16,
            "max":31,
            "step":1.0
         },
         "fahrenheit":{
            "min":61,
            "max":88,
            "step":1.0
         }
      },
      "fanLevel":[
         "LEVEL4",
         "LEVEL5",
         "LEVEL1",
         "LEVEL2",
         "LEVEL3",
         "AUTO"
      ],
      "verticalSwing":[
         "MID_DOWN",
         "MID_UP",
         "DOWN",
         "AUTO",
         "UP",
         "MID"
      ]
   },
   "COOL":{
      "temperatures":{
         "celsius":{
            "min":16,
            "max":31,
            "step":1.0
         },
         "fahrenheit":{
            "min":61,
            "max":88,
            "step":1.0
         }
      },
      "fanLevel":[
         "LEVEL4",
         "LEVEL5",
         "LEVEL1",
         "LEVEL2",
         "LEVEL3",
         "AUTO"
      ],
      "verticalSwing":[
         "MID_DOWN",
         "MID_UP",
         "DOWN",
         "AUTO",
         "UP",
         "MID"
      ]
   },
   "initialStates":{
      "mode":"COOL",
      "modes":{
         "AUTO":{
            "temperature":{
               "celsius":24,
               "fahrenheit":75
            },
            "fanLevel":"LEVEL3",
            "verticalSwing":"AUTO"
         },
         "FAN":{
            "fanLevel":"LEVEL3",
            "verticalSwing":"AUTO"
         },
         "DRY":{
            "temperature":{
               "celsius":24,
               "fahrenheit":75
            },
            "fanLevel":"LEVEL3",
            "verticalSwing":"AUTO"
         },
         "HEAT":{
            "temperature":{
               "celsius":24,
               "fahrenheit":75
            },
            "fanLevel":"LEVEL3",
            "verticalSwing":"AUTO"
         },
         "COOL":{
            "temperature":{
               "celsius":24,
               "fahrenheit":75
            },
            "fanLevel":"LEVEL3",
            "verticalSwing":"AUTO"
         }
      }
   }
}`

**Comment by andrewfg** [comment]
@hpalne many thanks for the feedback. I am guessing that the Tado API has a "full" set of capabilities and that respective real AC units report their own subset thereof. That might mean that we have to check commands from OH to see if they are valid within the reported subset, rather than with the full API..

**Comment by andrewfg** [comment]
> check commands from OH to see if they are valid within the reported subset

Actually I think it already does that :)

**Comment by andrewfg** [comment]
> it already does that

It throws a runtime exception which appears in the log file. And I added a paragraph in the ReadMe to inform users about that.

**Comment by Artur-Fedjukevits** [comment]
> @Artur-Fedjukevits I think the reason why your code is not backward compatible is that although you correctly added the new sub-elements `fanLevel`, `verticalSwing` and `horizontalSwing` to the YAML file, you should NOT have deleted the sub-elements `fanSpeed` and `swing`. If the parser finds a JSON sub element of the respective name, it will instantiate the respective Java class, and if not then the class instance is `null`; so including both potential sets of sub-elements is not a problem.
> 
> Therefore, I will rework your code based on not deleting those older capabilities..
> 
> Nevertheless I do have a couple more questions concerning inconsistencies in your code..
> 
> 1. Your `fanLevel` JSON payload (above) shows the options [SILENT, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO], whereas your YAML entry definition has "LEVEL5, LEVEL1, LEVEL2, LEVEL3, LEVEL4, AUTO". => Was there some reason why you changed 'SILENT' to 'LEVEL5' ??
> 2. Your `verticalSwing` JSON payload (above) has options [ON, UP, MID_UP, MID, MID_DOWN, DOWN, AUTO] whereas your `horizontalSwing` is similar except without an 'AUTO' option. => Can you please tell me if your physical A/C remote control has a horizontalSwing=AUTO possibility or not? I wonder if we should in include 'AUTO' as a possibility in the code "just-in-case" ???

I'm not a programmer, I'm a baker :) I don't know why, but I thought that if I leave the old fanSpeed element, it will conflict with fanLevel :))
1. First it was SILENT, and then it turned out that @hpalne had LEVEL5 instead. Therefore, I replaced SILENT with LEVEL5 for him in the code.
2. My A/C does not support AUTO for horizontalSwing. But I do not rule out that someone has A/C that support AUTO.

**Comment by andrewfg** [comment]
@Artur-Fedjukevits if I could bake bread as good as you can program ... ;)

REST API's (like this one used by Tado) comprise a nested structure of pre-defined elements, sub-elements, sub-sub- etc. And the great thing is that all sub-elements (and lower) are optional (unless specifically defined otherwise). And the parser is clever enough that if the device does not supply a particular sub-element, then that element is considered as `null`. This means that as long as the code does null checks (e.g. `if (getFanLevel() != null) { .. }` or `if (getFanSpeed() != null) { .. }` it can self adapt its functionality to whatever features the device has provided.

Concerning the `SILENT` vs `LEVEL5` & `AUTO`, my current approach in #12470 is to include the fullest set of possible options in the code. And then perhaps the individual devices may only support a sub-set thereof. That means that there will be nothing unexpected when reading from the device, although there is a certain risk when writing to the device that you might send it a value that it does not actually support. However since reading from the device is very frequent, and writing (wrong values) to the device is rather infrequent, I think this is the best way forward.

**Comment by andrewfg** [comment]
^
PS (therefore) in #12470 the A/C Thing has five Channels as follows; (so when you test it you will need to use the respective Channel id's)..
- `fanspeed` & `swing` on simple devices (and don't work on full feature ones)
- `fanLevel`, `verticalSwing`, & `horizontalSwing` on full feature devices (and don't work on simple ones)
