### ISSUE TITLE
[pwm] Incorrect processing of "maxDutyCycle" parameter value

### ISSUE THREAD

**Issue by CyborgAndy** [openhab/openhab-addons#12196]
This issue is related to [PWM automation module](http://next.openhab.org/addons/automation/pwm/)

## Expected Behavior
If the duty cycle is greater then "maxDutyCycle" value, it must be decreased to "maxDutyCycle" value.

## Current Behavior
If the duty cycle is greater then "maxDutyCycle" value, it always set to 100%

## Possible Solution
Make changes to this part of the code
https://github.com/openhab/openhab-addons/blob/02776d858548b69a5f8cf101e35618a4c51aa1c3/bundles/org.openhab.automation.pwm/src/main/java/org/openhab/automation/pwm/internal/handler/PWMTriggerHandler.java#L142-L150

## Your Environment
* OpenHAB version used: 3.2.0
* Operating System: `Linux 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux` Raspbian 11 bullseye

**Comment by fwolter** [comment]
Well, it's not a bug, it's a feature :)

The max duty cycle parameter was implemented with actuators in mind, that must not be switched too often within a specified interval. E.g. heating burners. Lets assume the duty cycle is 99%, the heating burner will switch off near the end of the current PWM period and immediately on again at the start of the next PWM period, resulting in a very short off time. The duty cycle limit parameters are supposed to prevent these short on/off intervals.

I must admit, the naming of the parameter might be a bit confusing.

You could add a boolean paramter to change the behavior of the max duty cycle limit.

May I ask what your use case is?

**Comment by CyborgAndy** [comment]
Thank you for implementing the PWM module. :)

The name of the parameter is correct and reflects its essence. But the handling of this parameter does not correspond to the documentation and logic. Why do you need this parameter if its value does not affect anything?

I use a PWM module in a special heating system. The PWM period is 10 minutes. In the current PWM implementation, my heating system at startup works constantly, without stopping, because max duty cycle parameters is ignoring. And as a result - the heater elements is overheat. I changed the code and tested the system in 10%/90% mode - the system works without overheating.

**Comment by fwolter** [comment]
Thanks for the explaination of your use case. I agree that the default behavior of the parameter should be changed. But by simply changing the behavior, a feature will be discarded (see my heating burner example). Can you come up with a PR that introduces a boolean parameter that changes the behavior as you proposed if false and keep the current behavior otherwise?

**Comment by CyborgAndy** [comment]
I propose to review and discuss the following implementation.

I also added boolean parameter for behavior of the "minDutycycle".
Sorry, but the naming of those new parameters may not be entirely correct.
You can see all changes in the last commit.

![edit-pwm](https://user-images.githubusercontent.com/8106184/153058139-27c9334f-f477-4689-8d1d-2854767e7a72.JPG)

![code-pwm](https://user-images.githubusercontent.com/8106184/153065792-3f61edca-3efd-444a-b8a5-6a9dd52bf000.JPG)
