### ISSUE TITLE
[somfytahoma] unsupported device: Wifi with widgetName: Wifi

### ISSUE THREAD

**Issue by daabm** [openhab/openhab-addons#12213]
Running openhab 3.2.0 (docker image on Synology) with the Somfy Tahoma binding. Once an hour it detects a new unsupported device "Wifi". I would not care about it, but it clutters my log :-)

2022-02-05 16:19:44.139 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition:
Commands: { clearCredentials (params: 0); setTargetInfraConfig (params: 2); setWifiMode (params: 1); }
States: {internal:CurrentInfraConfigState (values: ); internal:SignalStrengthState (values: ); internal:WifiModeState (values: ); }
2022-02-05 16:19:44.139 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 
{name='internal:WifiModeState', type=3, value=infrastructure}
{name='internal:CurrentInfraConfigState', type=3, value=<*** SSID of my Wifi network ***>}
{name='internal:SignalStrengthState', type=1, value=58.0}

A nice solution - at least for me - would be an option in the Bridge settings that takes a Regex to match widget names to be ignored upon discovery.

**Comment by octa22** [comment]
Hi @daabm , 
I does not make sense for me to add support for this thing either.
What about a new configuration item on the bridge so you can disable reporting of not supported devices?

**Comment by daabm** [comment]
@octa22  as I mentioned, I don't care about unrecognized devices at all - as an end user, I cannot use them anyway :-) 
So for me at least, simply disabling reporting on unrecognized devices would be ok. But this might add the challenge to implement future "unrecognized" devices that ARE of interest to you.

That said, my preferred solution would be a regex for unrecognized device names that should be simply ignored. If that's too much effort, I am happy with "ignore all of them", and I am also happy if nothing changes at all - kudos to you investing the effort of the Somfy binding implementation at all 👍
