### ISSUE TITLE
[jdbc] Storing and retrieving colors causes invalid cast exception

### ISSUE THREAD

**Issue by mitchellj** [openhab/openhab-addons#12218]
Currently if you utilize JDBC and persist a color state (i.e a HSBType) to the persistent store the data gets stored fine, however when you try and recall it an error is generated as the JDBC plugin tries to cast to an integer type. 

Examples of people reporting issue - 
https://community.openhab.org/t/color-historic-state/124209
https://community.openhab.org/t/jdbc-type-cast-error-for-color-item/126758

## Expected Behavior
When saving a Color state to the persistence store, recalling it should give the data back

## Current Behavior
Script fails with following message - 
`Script execution of rule with UID 'scratchpad' failed: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')`

## Steps to Reproduce (for Bugs)
Define a color item with persistence using JDBC 

`Color ExampleColoredLight "Test"          (gBedroom)  { channel="hue:0210:00xxxxxxxxxx:lbExampleColoredLight" }`

Then in either a scratchpad or in a rule try and change state/recall 

```
ExampleColoredLight.sendCommand("100,100,100") 
// Wait a period of time
ExampleColoredLight.previousState()
```

## Context
Unable to save the current state and recall it - meaning scripts that use the light bulb as a notification system (flash a color and revert to the previous state) doesn't work. 

## Your Environment
openHAB 3.2.0
MySQL

**Comment by cweitkamp** [comment]
I submitted a fix for this in #12225 .
