### ISSUE TITLE
[mqtt.generic] There is not yet any default translation properties file.

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-addons#12220]
There is not yet any default translation properties file.

_Originally posted by @lolodomo in https://github.com/openhab/openhab-addons/issues/12167#issuecomment-1030785190_

I tried creating the translations file for `org.openhab.binding.mqtt.generic` using this command:
```
$ mvn org.openhab.core.tools:i18n-maven-plugin:3.2.0:generate-default-translations -pl :org.openhab.binding.mqtt.generic
```

It created a file called `mqtt.properties`

Questions:
1. Should the existing mqttbroker_de.properties be deleted? I believe this file is an orphaned file from an older binding structure
2. The `mqtt.properties` file that was generated from the command above, don't include the texts from `thing/channels.xml` or `thing/generic.thing.xml` -  @wborn is this perhaps a bug in the `generate-default-translations` maven plugin?

**Comment by lolodomo** [comment]
As there is only one translation file for the German translation with only 2 entries, I think it can be ignored. The i18n tool should simply be run to produce the default properties file.

**Comment by jimtng** [comment]
> As there is only one translation file for the German translation with only 2 entries, I think it can be ignored. The i18n tool should simply be run to produce the default properties file.

I just updated my original post above with some more details

**Comment by wborn** [comment]
> is this perhaps a bug in the generate-default-translations maven plugin?

Yes it seems to be an issue for multi bundle bindings like MQTT because `/OH-INF/binding/binding.xml` is missing. If you'd temporarily add it by copying it over and then run the plugin it works better. :slightly_smiling_face:

**Comment by jimtng** [comment]
> If you'd temporarily add it by copying it over and then run the plugin it works better.

Thanks, that worked. I will leave the binding.xml in there so future plugin runs can be done easily.

**Comment by jimtng** [comment]
@wborn, I hit a snag with the translations generator tool. I'm not sure what `id` to use inside the binding.xml file for `org.openhab.binding.mqtt.homeassistant` and all the other `org.openhab.binding.mqtt.*` sub-bundles.


## Using id="mqtt" for homeassistant
This is great because it will pick up the contents of `config/homeassistant-channel-config.xml` and also:
```
# thing types

thing-type.mqtt.homeassistant.label = HomeAssistant MQTT Component
```

The problem is that it generates this at the top of the properties file which conflicts with/overrides the main bundle `org.openhab.binding.mqtt`:
```
# binding

binding.mqtt.name = MQTT Binding for Homeassistant Convention
binding.mqtt.description = Supports Homeassistant convention in MQTT
```

Setting `id=` to anything else doesn't seem to be picking up the correct texts.

I don't want to manually edit the properties file because I believe it needs to be easily regenerated again in the future.

Would you be able to look into handling this scenario in the generator plugin?

**Comment by wborn** [comment]
> Would you be able to look into handling this scenario in the generator plugin?

I think it should be fixed with https://github.com/openhab/openhab-core/pull/2748 @jimtng.
