### ISSUE TITLE
[shelly] Shelly binding doc: Smoke detector twice and gas detector missing

### ISSUE THREAD

**Issue by Frank-1964** [openhab/openhab-addons#12236]
In the README.md (https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.shelly) in the channels section, there is missing the shelly gas sensor. But there are two shelly smoke sensors, one of them with a gas conentration channel. I think this is a copy-past-error?

**Comment by markus7017** [comment]
fixed

**Comment by markus7017** [comment]
fixed in PR #12325
