### ISSUE TITLE
[mqtt.homeassistant] Error in config topic because zigbee2mqtt includes the group

### ISSUE THREAD

**Issue by jfmateos** [openhab/openhab-addons#12256]
## Expected Behavior

openHAB forces to use config topic with the format /homeassistant/temperature/4711/config,
but Zigbee2mqtt sends information to topics with the format homeasssistant/sensor/0x00124b002512277a/temperature/config

## Steps to Reproduce (for Bugs)

![image](https://user-images.githubusercontent.com/29097198/153395139-abcdb776-a65f-442d-b889-4b45634b8cd7.png)

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
* Windows openHAB 3.2

**Comment by jochen314** [comment]
Well, the optional `node_id` has been taken into account during codeing of the homeassistant bundle.
https://github.com/openhab/openhab-addons/blob/888cf00245f18e3b04535325327c9977a053086f/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/HaID.java#L49
I have no idee, what the problem could be.
I there anything in the logs?
