### ISSUE TITLE
[myenergi] Authentication doesn't work because myenergi authentication process has been changed

### ISSUE THREAD

**Issue by volkmarnissen** [openhab/openhab-addons#12251]
## Expected Behavior
Authentication doesn't work because the authentication has been changed.
More details at https://github.com/twonk/MyEnergi-App-Api

## Current Behavior
For some (newer or migrated) users, the authentication doesn't work.
Because the binding refers to the wrong server.
Sometimes only outdated data is available. 

## Possible Solution

Implement the approach described in https://github.com/twonk/MyEnergi-App-Api

## Context
I am trying to use the binding, but failed with authentication

## Your Environment
Currently I am using openhab development environment in eclipse.
I will try to implement the new approach

**Comment by lsiepel** [comment]
The myenergi binding is not (yet) part of the openHAB distro, it seems to be a marketplace binding. Community topic here:
https://community.openhab.org/t/myenergi-myenergi-binding/139667

It is maintained here:
https://github.com/renescherer/openhab-addons/tree/myenergi_binding_3.4.x
