### ISSUE TITLE
[Velbus] Add VMBELPIR

### ISSUE THREAD

**Issue by MDAR** [openhab/openhab-addons#12279]
@Rosen01 @cedricboon 

Is there any chance that either of you could add the VMBELPIR to the #Velbus binding?
https://github.com/velbus/moduleprotocol/blob/master/protocol_vmbelpir.pdf

It's a single button EL glass with a PIR.

(PIR features on button events 5 to 8)

Thanks in advance.

As always, if you need **anything** please just ask.

**Comment by Rosen01** [comment]
Hi @MDAR

I've added the module, but I don't have one on mine installation. 
Can you [test](https://github.com/Rosen01/openhab-addons/releases/tag/3.3.0.202202142024) it to see if everithing is fine ?

**Comment by MDAR** [comment]
Sorry, I missed this.

I'll try work out how to try this.

**Comment by lolodomo** [comment]
Closed by #12390
