### ISSUE TITLE
[deconz] Stability issues: ONLINE device stops receiving updates

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12281]
This issue is probably created a bit prematurely as I haven't been able to collect a lot of data yet, but I will provide what I have and enrich the issue once I learn more.

I have a fresh deCONZ installation running on a Raspberry Pi 2 with a Wiser socket outlet connected:
dresden-elektronik/deconz-rest-plugin#5766

Initially everything works as expected and I'm receiving events from the device. When my TV etc. is turned on, the channel `deconz:powersensor:home:wiser_socket1:power` is probably updated more then once per second. When running only devices on standby power this will stabilize to 3 W and I will only receive a few events from time to time when the current changes.

After some time I stop receiving events. I usually notice it when TV is turned on, but I still see 3 W. I'm still not sure what triggers this problem. It might be after the device has been unreachable and is reachable again (according to REST API). However, when this happens, I need to at least disable and reenable the bridge thing. The device for which I no longer receive events is still **ONLINE**, and it doesn't help disabling/reenabling this thing. Other devices seem unaffected.

## Expected Behavior
The binding should be able to recover from network issues, whether TCP or ZigBee:
- Devices becoming unreachable, then reachable again.
- deCONZ service stopping and starting.

## Current Behavior
The binding stops receiving events from devices for yet unknown reasons. I'm building a new ZigBee network which currently only has two devices, so it's still a weak network and devices can become unreachable temporarily. Being able to recover from any temporary issues seems quite critical for production use.

## Steps to Reproduce
Will provide more information as I learn more. I'm logging with DEBUG trace level and keeping an eye on exactly what's going on before experiencing the problem.

## Context
My new ZigBee network based on ConBee II and deCONZ doesn't work properly with openHAB, thus I cannot extend it and use it for anything important.

## Your Environment
openHAB 3.2 with latest version of the binding compiled from **main**.

**Comment by J-N-K** [comment]
I doubt this is an issue with the binding. Do you use the latest deconz? Can you still control the outlet from openHAB?

**Comment by jlaur** [comment]
> I doubt this is an issue with the binding. Do you use the latest deconz? Can you still control the outlet from openHAB?

Yes, latest deCONZ - and yes, I can still control it from openHAB. I checked my logs, and I don't think it was caused by device being unreachable. It happened again just 15 minutes ago, and I think it has to do with making changes in the configuration, for example adding a new device to my **things/deconz.things** file. I'm currently investigating this, will keep you updated hopefully in a short while.

**Comment by jlaur** [comment]
I just verified that I can still control the outlet while it doesn't receive events. And while doing so it still didn't receive events. It was locked at 7 W. Then turned off for a moment - no changes - and turned on again - no change. So that didn't cause it to resume receiving events.

**Comment by J-N-K** [comment]
If you enable TRACE logging you should see every message from the websocket. There is no filter, do you see status reports?

**Comment by jlaur** [comment]
> If you enable TRACE logging you should see every message from the websocket. There is no filter, do you see status reports?

I'll try to configure logging tomorrow, so I can have TRACE logging for deconz dumped somewhere else, as it will generate tons of logs until it stops receiving events.

Unfortunately I was not able to confirm my editing things file theory, at least yet. The problem was reproduced a few times this evening, but still without a clear and reproducible pattern. At least one of the times I noticed it happening for one of the outlets (I now have two) after this was logged:

```
2022-02-13 22:25:51.560 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:onofflight:home:wiser_socket2' changed from ONLINE to UNKNOWN
2022-02-13 22:25:51.636 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:powersensor:home:wiser_socket2' changed from ONLINE to UNKNOWN
2022-02-13 22:25:51.642 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:onofflight:home:wiser_socket2' changed from UNKNOWN to ONLINE
2022-02-13 22:25:51.701 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'deconz:powersensor:home:wiser_socket2' changed from UNKNOWN to ONLINE
```

Based on this configuration:

```
Bridge deconz:deconz:home "Phoscon-GW" [ host="192.168.0.53", apikey="xxx" ] {
    onofflight  wiser_socket1 [ id="3" ]
    powersensor wiser_socket1 [ id="3" ]
    onofflight  wiser_socket2 [ id="5" ]
    powersensor wiser_socket2 [ id="6" ]
}
```

**Comment by jlaur** [comment]
I'm closing this issue as I have not been able to reproduce it. I think it's related to editing the things file, so I'll open a new issue if I manage to reproduce it consistently.
