### ISSUE TITLE
[mihome] Add addon for Aqara wall switch D1

### ISSUE THREAD

**Issue by shatulsky** [openhab/openhab-addons#12296]
I got a few fresh switches from Aqara - Aqara wall switch D1.
It's 2 buttons switch (without neutral) that looks almost the same as the Aqara wall switch.
![image](https://user-images.githubusercontent.com/22248285/153956745-92d335d8-314f-420b-a267-8a68b333a6b2.png)

It behaves the same as Aqara wall switch but the model and channel names are different.

## Your Environment
* Version used: (e.g., openHAB and add-on versions) - openHAB 3.2.0

Messages examples:
Last Heartbeat Message: {"voltage":3300,"channel_0":"off","channel_1":"off"}
Last Raw Message: {"cmd":"heartbeat","model":"switch_b2lacn02","sid":"158d0005bdaa21","short_id":46985,"data":"{\"voltage\":3300,\"channel_0\":\"off\",\"channel_1\":\"off\"}"}
Last Read Acknowledgement Message: {"voltage":3300,"channel_0":"on","channel_1":"on"}
Last Report Message: {"channel_0":"off"}

For me, it looks the same as [aqara_ctrl_ln2](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.mihome/src/main/resources/OH-INF/thing/aqara_ctrl_ln2.xml). But the name is switch_b2lacn02 and channels are channel_X instead of chX. 

Can someone approve that I am right so I can try to prepare the pull request to add the new addon?
Can I somehow test addon locally after creation?

**Comment by lsiepel** [comment]
Isn’t this a duplicate of https://github.com/openhab/openhab-addons/issues/8251 ?
