### ISSUE TITLE
[PUSHOVER] HANDLER_CONFIGURATION_PENDING

### ISSUE THREAD

**Issue by xsasx** [openhab/openhab-addons#12304]
Since OH3 (3.3.0 Snapshot) I got missing handler error for my pushover things which was working before.

API Token and USer Key was putted in:

Thing pushover:pushover-account:wama [ apikey="xxxxx", user="xxxxx" ]
Thing pushover:pushover-account:trockner [ apikey="xxxx", user="xxxxx" ]
Thing pushover:pushover-account:spuema [ apikey="xxxx", user="xxxxxx" ]
Thing pushover:pushover-account:wasser [ apikey="xxxxx", user="xxxxx" ]
What cause the error from updating 3.2.0 to 3.3.0 ?

All worked before- also tried delete binding and delete thing but still same error

Also cleared OH Cache

**Comment by cweitkamp** [comment]
Fix for this https://github.com/openhab/openhab-addons/pull/12309
