### ISSUE TITLE
[tesla] TeslaSSOHandler  returns 403 Forbidden . Username/Password works on tesla home page. App works also fine.

### ISSUE THREAD

**Issue by volkmarnissen** [openhab/openhab-addons#12306]
Hi,

I tried the tesla binding for the first time in the eclipse development environment (main-Branch)
when I call the logon command, I get 

openhab:tesla login
Username (email): [myemail]@gmail.com
[myemail]@gmail.com
Password: [mypassword]

Attempting login...
Failed to retrieve refresh token

When debugging it, it fails at TeslaSSOHandler "ssoHandler.authenticate" 
line 197:  if (formSubmitResponse == null || formSubmitResponse.getStatus() != 302) {
"Failed to obtain code from SSO login page when submitting form, response status code: 403 "
           ....     

HttpContentResponse[HTTP/1.1 403 Forbidden - 295 bytes]

I use same email address and password as on teslas home page.
Do I have to use another password? 
What else can be wrong?
What can I do to get more information?

## Your Environment
Window Surface using eclipse IDE Version: 2021-12 (4.22.0)
Build id: 20211202-1639
openhab main branch 
tesla binding is not modified.

**Comment by kaikreuzer** [comment]
Please see the "NOTE" on https://next.openhab.org/addons/bindings/tesla/#bridge-configuration.
Unfortunately, it seems that openHAB is not able most of the time (never anymore?) to retrieve the token, so you have to use option 3.

**Comment by volkmarnissen** [comment]
Hi,

I agree, sorry, I missunderstood the documentation.
I assumed all options are valid.
What do you think about changing the error message when this happens
"Failed to retrieve refresh token. Read documentation an use option 3."

**Comment by kojid0** [comment]
Hi, for me the binding stopped working since this morning. I was able to make it work for a couple of days with option 3 but all of a sudden it stopped `OFFLINE (CONFIGURATION_ERROR): Failed to obtain access token for API.`
Are you guys facing the same issue? If yes, I would open a new issue.

**Comment by kaikreuzer** [comment]
> I assumed all options are valid.
>What do you think about changing the error message when this happens

@volkmarnissen Yes, the docs were misleading indeed. As I have no longer hope that options 1+2 will start working again, I have created https://github.com/openhab/openhab-addons/pull/12537, which removes them completely.
