### ISSUE TITLE
[tesla] scanVehicles works only for vehicles which are not sleeping

### ISSUE THREAD

**Issue by volkmarnissen** [openhab/openhab-addons#12312]
Hi,

first of all. I am a newie  to openhab. Sorry, if I failed to understand everything in the documentation.
I installed the tesla binding, added the resolve token properly. The account thing was online.
However, the discovery of my Model 3 failed with no error message in the log.

## Expected Behavior
If the discovery must fail if the vehicle is sleeping, a error message in the log file would be helpful.
There was only a debug message 
"An error occurred while communicating with the vehicle during request {}: {}: {}"
from TeslaAccountHandler:340

## Possible Solution
1. Make it working for sleeping cars or
2. Add an error message when this happens and mention this behaviour in the documentation.
I could do the second solution on my own, but you can decide better what to do. 

## Steps to Reproduce (for Bugs)
Try in the morning, when the tesla sleeps. Make sure, the car is really sleeping.
Remove the tesla vehicle thing.
Disable the account.
Enable it again.
The vehicle won't show up in the inbox.

## Context
It is not a severe problem, but may be it helps other newbies to get started with the tesla binding.
## Your Environment
eclipse development environment,
openhab main branch

**Comment by kaikreuzer** [comment]
@volkmarnissen As a quick fix, I have added a note to the documentation with https://github.com/openhab/openhab-addons/pull/12537.
I guess (1) would only be possible if discovery wakes up the vehicles - but that might not be desired.
So the only further enhancement might be to catch the situation (when the debug log is done) and log a warning about a sleeping vehicle instead.
