### ISSUE TITLE
[sony] Add Sony Binding

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-addons#1231]
New sony binding - currently only Bravia but will add bluray players soon
##

**Comment by Marty56** [comment]
Where can I find  some documentation?

**Comment by wborn** [comment]
See also the following:
* PR https://github.com/openhab/openhab2-addons/pull/1249
* [Community thread](https://community.openhab.org/t/sony-devices-binding/14052)

**Comment by Computences** [comment]
Hello,

It's unclear to me about how to get, install and setup the Sony Binding. It doesn't appear in PaperUI bindings, nor in console bundle:list command.

Some help would be welcome

(openhabian 2.4.0)

**Comment by hmerk** [comment]
closed due to inactivity.
