### ISSUE TITLE
[velux] catching InterruptedException or not?

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#12327]
This refers to issue #10454 whereby I wonder if the Velux binding also needs to handle InterruptedException differently?

The binding does catch InterruptedException in at least seven locations; it logs such exceptions to debug; but it does NOT call `Thread.currentThread().interrupt()` -- which now seems to be the recommended approach..

The KLF bridge is notorious for entering a so called 'zombie' state where the binding thinks the connection socket has been destroyed, whereas the bridge thinks the socket is still open, and so it refuses to accept a new socket connection attempt from the binding. This error most often occurs when shutting down OpenHab; however it does not occur every time, and the circumstances are hard to determine, so it is has proven so far to be impossible to debug. Therefore it is not obvious if catching InterruptedException and calling `Thread.currentThread().interrupt()` might actually solve this issue, or not. ??

This issue is raised as a placeholder for a discussion, before (eventually, or not) opening a PR.

**Comment by andrewfg** [comment]
Pinging @jlaur / @lolodomo / @fwolter / @kaikreuzer @gs4711 for your respective thoughts on this issue?

**Comment by fwolter** [comment]
If you catch an `InterruptedException`, you need to finish the current program flow (i.e. the current task/job) as quickly as possible. Whether you need to call `Thread.currentThread().interrupt()`, depends on your exception handling. You need to do it, if you leave the catch block and execute further code. But that could be an indicator for bad design.

Generally, you should catch `InterruptedException` at the highest level you can and don't execute any other code after leaving the catch block.

If you close the socket when an `InterruptedException` is caught and finish program flow, there should be nothing more you can do to work around the crappy firmware. If your current thread is a daemon thread, the JVM might be stopped before you even come to closing the socket. I think the thread pool threads are daemon threads by default. This might be one of the rare exceptions where you need to set your thread's daemon flag to `false`.

**Comment by andrewfg** [comment]
> You need to do it, if you leave the catch block and execute further code. But that could be an indicator for bad design.

Hmm. I think the exception handler code generally breaks a while loop, and falls through to terminate the task. So probably that is not the cause of the zombie state.

> might be one of the rare exceptions where you need to set your thread's daemon flag to false.

Aha! You might be onto something here. The main socket polling thread is currently a daemon, so it could be that OH shutdown is force killing the task before it can execute its clean socket close code. I will study this a bit more, and make some tests.
