### ISSUE TITLE
[shelly] (5 channels) => the system channel types could have probably rather be used for some of the channel types.

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#12326]

**Comment by markus7017** [comment]
which are the 5 channels? What is the criteria for the identification?

**Comment by markus7017** [comment]
@andrewfg Could you please provide some more texture?

**Comment by markus7017** [comment]
@andrewfg Any details?

**Comment by andrewfg** [comment]
Umm. I think I was just commenting on the English text of the issue title: .. say "[shelly] Use system channel types instead of binding specific types"
