### ISSUE TITLE
[shelly] Support for Gen2 devices (Plus/Pro)

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#12336]
Allterco introduced two complete new series of devices to the market
- Shelly Plus - Successor of the Generation 1 devices based on a new chipset
- Shelly Pro - Designed to be rail mounted with extended warranty

Both product lines are based on Generation 2 design/chipset and a complete new API. Therefore the current binding needs to implement this new API, it's not just an extension of the existing one.

Round 1 will address the relays: Shelly 1/1PM/1L Plus, 2/2.5 Plus, 4 Pro
then other devices will follow.

**Comment by Sese-Schneider** [comment]
@markus7017 thank you for working on this, really looking forward to the Gen2 implementation!

I'm new to openhab, but am a software developer myself. Is there anything you need help with, or someone else could implement to get this done as quick as possible?

Do you have a rough ETA for this feature?
