### ISSUE TITLE
[shelly] TRV Start Stop Feature for Booster

### ISSUE THREAD

**Issue by scheuerer** [openhab/openhab-addons#12337]
Thanks for the development from the newe booster feature in the TRV.
It seems that ist not working.

In The TRV I found the the following menue.
![image](https://user-images.githubusercontent.com/59388391/154937372-263935e1-129a-424d-9447-85744d8d6d0f.png)

here you can see the button "Start booster"

![image](https://user-images.githubusercontent.com/59388391/154937527-2d657e53-6e75-49aa-a4f2-74781156714f.png)

And Also now the stop booster.

What I have seen in your entry ist the the modus will be #modus with the value automate/manuell/boost

Will there an channel coming for the start/stop Booster mode?

**Comment by markus7017** [comment]
you could stop the booster mode by setting a new target temp
