### ISSUE TITLE
[transform.javascript] Nashorn dependency is unavailable since Java 15

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#12359]
While getting the add-ons build to work with Java 17 in https://github.com/openhab/openhab-addons/pull/12353, I noticed that the JavaScript Transformation add-on depends on the Nashorn JavaScript engine which has been removed from Java since Java 15.

## Expected Behavior

The add-on works on Java 17 and later.

## Current Behavior

It will try to get a "javascript" `ScriptEngine` but this will fail because it is no longer provided by the JVM.

## Possible Solution

The easiest way would be to embed and use the [nashorn](https://github.com/openjdk/nashorn) dependency in the bundle.
It could also be rewritten to use GraalVM.
It might also be an idea to create an add-on (or core service) supporting transformations using any of the installed/available scripting engines.

## Steps to Reproduce (for Bugs)

1. Try using the add-on with Java 17. :slightly_smiling_face: 

## Your Environment

* openHAB 3.3.0-SNAPSHOT
* OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
* Ubuntu 20.04.4 LTS

**Comment by J-N-K** [comment]
IMO your last suggestion would be the best one.

**Comment by wborn** [comment]
Yes if that works out well it would provide a lot of functionality and reduce the number of add-ons we have to maintain/install. :slightly_smiling_face: 

I also did some testing with creating a Nashorn based JS scripting engine for backwards compatibility on Java 17. The issues I ran into are probably fixed now with https://github.com/openhab/openhab-core/pull/2787. But it could become very confusing if there are 2 JavaScript automation add-ons (and still Nashorn on Java 11).

**Comment by wborn** [comment]
Let's close this now the core has a generic script transformation with https://github.com/openhab/openhab-core/pull/2883 which can be used with any scripting engine.

> I also did some testing with creating a Nashorn based JS scripting engine automation add-on for backwards compatibility on Java 17.

This can now be used by installing the [JSScripting (Nashorn)](https://community.openhab.org/t/jsscripting-nashorn/134770?u=wborn) add-on available in the Marketplace.
