### ISSUE TITLE
[zwave] 06436 Blind Control not working anymore (HANDLER_CONFIGURATION_PENDING)

### ISSUE THREAD

**Issue by TomMarg** [openhab/openhab-addons#12407]
Hi,

trying to provide the information required:
- I am on OH 3.3.0 Build #2778
- Zwave-Binding is the related 3.3.0.SNAPSHOT

My rollershutter things stopped working after recent update. They are listed as "ERROR: HANDLER" with the status HANDLER_CONFIGURATION_PENDING

When looking into the details I can not see exactly what is missing. I would assume that the error might be related to the options 4 (Full Close Time) and 5 (Full Open Time) which both show a radio buttom with "Keep in permanent motion" instead of an input field to enter the time in seconds. 

If more input would be helpful please let me know. This affects all my rollershutter controllers from ZWave.me 06436.
I had noticed in the last weeks (reason why I upgraded) that the "Invert percentage" option stopped working just for some of the modules (maybe this is somehow related).

What I tried so far:
- Rebooting - no success
- Deleting thing and adding a new thing - no success

How I solvedt it (interim):
- Went back to main release (3.2.0)

KR,
Thomas

**Comment by lolodomo** [comment]
To be moved in the right repo. 
@cdjackson for information

**Comment by TomMarg** [comment]
Problem solved through database update on the item. Thanks to @cdjackson for your guidance!
