### ISSUE TITLE
WLED since version 3.2.0 white channels are missing

### ISSUE THREAD

**Issue by MSauerland** [openhab/openhab-addons#12418]
In the WLED addon is since the version 3.2.0 no white channel available.

It is needed to Control the White LEDs if you use for example the SK6812 RGBW leds.

Please bring this channel back.

Kind reguards konty

**Comment by lolodomo** [comment]
Can you precise which channel ID is missing exactly.
From documentation and code (XML description), I find these channels: primaryWhite, secondaryWhite and tertiaryWhite.
Are you talking about these channels ?

Looking at the recent changes, I see no removing of channels for the WLED binding.

**Comment by MSauerland** [comment]
Exactly I'm, talking about these channels.

I guess there is no offical removing of these channels but if i open the WLED thing in openhab, these channels are not listed anymore, so i can't link them to an item.

There in the earlier version the white channels was listed if i enabled the show advanced option.

**Comment by lolodomo** [comment]
They are present in the code and I can confirm there are advanced channels so you have to enable advanced channels to see them.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.wled/src/main/resources/OH-INF/thing/thing-types.xml#L15

Maybe you can try to remove your thing and create it again.

**Comment by MSauerland** [comment]
I see that there are present in the code but, still not present in OH, i made an complete new clean install of OH 3.2.0 to check an incompatibility, with my version of OH or an other plugin, but i can't see the white channels, if you wish i can send you logs or pictures.

**Comment by lolodomo** [comment]
Sorry but I see no reason why channels are not displayed.
@Skinah: can you please analyse ?

**Comment by lolodomo** [comment]
Ok, I see code that removes channels.
@Skinah will certainly help you.

**Comment by Skinah** [comment]
The channels will/should show up if your wled firmware is setup correctly for rgbw strings and not just RGB strings. The channels get removed automatically if the Binding believes the firmware  is setup for RGB only.

To fault find I would need to see the output of  going to http://wledIP/json
There is another url which may be /json/info that will give less output and shows what the firmware is set to.

Pause and the. Unpause the thing if you did not have it setup correctly and the binding may get the channels back or it may need to have the thing deleted and readded.

**Comment by Skinah** [comment]
The value in particular is leds.rgbw and if it is true or false.

See https://kno.wled.ge/interfaces/json-api/

**Comment by MSauerland** [comment]
ich checked the json and the value was already set to true

i added the thing with this vlaue in the prod system and in the test system, but still no white channels

**Comment by Skinah** [comment]
What version are you using? The marketplace has a newer version in it, can you test with it to see if this still occurs in that version which is waiting to be merged? This sounds like a bug but hopefully it is fixed in the marketplace version.

**Comment by MSauerland** [comment]
i tried it with 3.2.0 and 3.3.0.M2

**Comment by Skinah** [comment]
Sorry but I don't see that as a clear, I have tried the marketplace version. If it still happens in the marketplace version I will try to reproduce this.

**Comment by MSauerland** [comment]
sorry my mistake, i also tried the marketplace version, still the same problem.

**Comment by Skinah** [comment]
OK bug found and fixed. Please uninstall the marketplace version and then install it again and test if it now works for you.

**Comment by MSauerland** [comment]
thanks, now it works well again

**Comment by lolodomo** [comment]
This is not clear for me. Is the issue present or not in the current official vetsion?
If it is, the issue must remain open until it is fixed in the official repo. 
If it is not, the issue should have not been crested here but either in the PR if it is fixed by s PR in progress or elsewhere if it concerns an alternative version of the bonding. 
Can you clarify please?

**Comment by MSauerland** [comment]
The offical Repo versions 3.2.0 and 3.3.0M2 still don't work.
The marketplace version, after your reload works fine.

**Comment by lolodomo** [comment]
So the issue must remain opened until it is fixed in the main repo.

**Comment by lolodomo** [comment]
The marketplace version is attached to an opened PR? If not, it should even not exist.

**Comment by MSauerland** [comment]
now i tested something with the marketplace version of wled, and found an little other problem, should i post it here or somewhere else?

**Comment by lolodomo** [comment]
> now i tested something with the marketplace version of wled, and found an little other problem, should i post it here or somewhere else?

Not here in this PR. You can comment in the community forum in the topic dedicated to this marketplace version
