### ISSUE TITLE
[deconz] Use lowbattery flag if this is send by deconz

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#12412]
At the moment battery_low channel is set by the binding itself if there is a battery level provided in the sensor config part of the Deconz response json.

Some newer devices (especially those driven by Tuya Hardware) don't provide battery level but the lowbattery flag by themselve send in the state part of the response. 

The binding should create the battery low channel in this case and update it by the state response of deconz

**Comment by DerOetzi** [comment]
Will provide a PR on this issue this afternoon, after work.

**Comment by lolodomo** [comment]
Closed by #12422
