### ISSUE TITLE
[shelly] SHSW-25 Roller Mode - Accumulated channels + Voltage are not updated

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#12421]
DEV Build 3.3.0.202203021926

The channels:
- device#accumulatedWatts
- device#accumulatedWTotal
- device#supplyVoltage

are not updated on Shelly 2.5 device in Roller Mode. The value is NULL. 
There is no such problem if device is in Relay Mode.

**Comment by lolodomo** [comment]
Was the PR merged?
