### ISSUE TITLE
[avmfritz] changing the color of a fritz!dect 500 lightblub isn't working

### ISSUE THREAD

**Issue by vich-667** [openhab/openhab-addons#12427]
## Expected Behavior
I have a Fritz!Dect500 LightBlub connected to my Fritzbox 7590, both with the actual firmware. I also own some other stuff for example a Fritz!Dect200 what works well.

In my things inbox a **FRITZ!DECT 500** and a  **HAN_FUN_COLOR_BULB** is shown. The *FRITZ!DECT 500* uses the *ain* shown in the Fritz!Box UI. The *HAN_FUN_COLOR_BULB* uses the same *ain* with an `-1` in addition.

## Current Behavior

- with the **FRITZ!DECT 500** nothing is working
- with the **HAN_FUN_COLOR_BULB** i can change the brightness and switch the light blub on and off, but it is not possible to change hue or saturation. See also community [posts](https://community.openhab.org/t/fritz-dect-500-cannot-control-hue-or-saturation/132076).

## Steps to Reproduce (for Bugs)

1. configure the things from inbox, create items and add them to the semantic model
2. try to change the bightness, hue and saturation.

## Your Environment
* Version used: (e.g., openHAB and add-on versions) openhab 3.2.0-1 and openhab-3.2.0-1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Rasperry Pi3
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):  Raspbian GNU/Linux 10 (buster) and OpenJDK 11.0.12
* Fritz!Dect500: 34.10.16.16.015
* Fritzbox 7590: 07.29

**Comment by sommer** [comment]
According to a German [AHA HTTP spec (section 3.5)](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf) I found online, color bulbs that use color mapping (the FRITZ!DECT 500 seems to have this attribute set) only accept a few select combinations of hue/saturation which can be queried using `getcolordefaults` switchcmd. Any other combination is silently discarded. Crude sample code for OpenHAB 3.2.0 to "snap" selected hue/saturation to a hardcoded table of legal combinations extracted from a sample light bulb might look like this: 
```
diff --git a/bundles/org.openhab.binding.avmfritz/build.sh b/bundles/org.openhab.binding.avmfritz/build.sh
new file mode 100755
index 0000000000..50b7231b2d
@@ -411,8 +425,50 @@ public abstract class AVMFritzBaseThingHandler extends BaseThingHandler implemen
                 if (command instanceof HSBType) {
                     HSBType hsbType = (HSBType) command;
                     brightness = hsbType.getBrightness().toBigDecimal();
-                    fritzBox.setHueAndSaturation(ain, hsbType.getHue().intValue(),
-                            ColorControlModel.fromPercent(hsbType.getSaturation()), 0);
+                    int hue = hsbType.getHue().intValue();
+                    int sat = ColorControlModel.fromPercent(hsbType.getSaturation());
+
+                    if      ((hue >= 0    ) && (hue <=  16.5 ) && (sat >= 146  )) { hue = 358 ; sat= 180 ; }
+                    else if ((hue >= 0    ) && (hue <=  16.5 ) && (sat >= 83   )) { hue = 358 ; sat= 112 ; }
+                    else if ((hue >= 0    ) && (hue <=  16.5 ) && (sat >= 0    )) { hue = 358 ; sat= 54  ; }
+                    else if ((hue >= 16.5 ) && (hue <=  43.5 ) && (sat >= 177  )) { hue = 35  ; sat= 214 ; }
+                    else if ((hue >= 16.5 ) && (hue <=  43.5 ) && (sat >= 106  )) { hue = 35  ; sat= 140 ; }
+                    else if ((hue >= 16.5 ) && (hue <=  43.5 ) && (sat >= 0    )) { hue = 35  ; sat= 72  ; }
+                    else if ((hue >= 43.5 ) && (hue <=  72   ) && (sat >= 127.5)) { hue = 52  ; sat= 153 ; }
+                    else if ((hue >= 43.5 ) && (hue <=  72   ) && (sat >= 76.5 )) { hue = 52  ; sat= 102 ; }
+                    else if ((hue >= 43.5 ) && (hue <=  72   ) && (sat >= 0    )) { hue = 52  ; sat= 51  ; }
+                    else if ((hue >= 72   ) && (hue <=  106  ) && (sat >= 101  )) { hue = 92  ; sat= 123 ; }
+                    else if ((hue >= 72   ) && (hue <=  106  ) && (sat >= 58.5 )) { hue = 92  ; sat= 79  ; }
+                    else if ((hue >= 72   ) && (hue <=  106  ) && (sat >= 0    )) { hue = 92  ; sat= 38  ; }
+                    else if ((hue >= 106  ) && (hue <=  140  ) && (sat >= 121  )) { hue = 120 ; sat= 160 ; }
+                    else if ((hue >= 106  ) && (hue <=  140  ) && (sat >= 60   )) { hue = 120 ; sat= 82  ; }
+                    else if ((hue >= 106  ) && (hue <=  140  ) && (sat >= 0    )) { hue = 120 ; sat= 38  ; }
+                    else if ((hue >= 140  ) && (hue <=  177.5) && (sat >= 114.5)) { hue = 160 ; sat= 145 ; }
+                    else if ((hue >= 140  ) && (hue <=  177.5) && (sat >= 62.5 )) { hue = 160 ; sat= 84  ; }
+                    else if ((hue >= 140  ) && (hue <=  177.5) && (sat >= 0    )) { hue = 160 ; sat= 41  ; }
+                    else if ((hue >= 177.5) && (hue <=  203.5) && (sat >= 148.5)) { hue = 195 ; sat= 179 ; }
+                    else if ((hue >= 177.5) && (hue <=  203.5) && (sat >= 88.5 )) { hue = 195 ; sat= 118 ; }
+                    else if ((hue >= 177.5) && (hue <=  203.5) && (sat >= 0    )) { hue = 195 ; sat= 59  ; }
+                    else if ((hue >= 203.5) && (hue <=  218.5) && (sat >= 146  )) { hue = 212 ; sat= 169 ; }
+                    else if ((hue >= 203.5) && (hue <=  218.5) && (sat >= 83   )) { hue = 212 ; sat= 110 ; }
+                    else if ((hue >= 0    ) && (hue <=  218.5) && (sat >= 0    )) { hue = 212 ; sat= 56  ; }
+                    else if ((hue >= 0    ) && (hue <=  245.5) && (sat >= 146  )) { hue = 225 ; sat= 204 ; }
+                    else if ((hue >= 0    ) && (hue <=  245.5) && (sat >= 83   )) { hue = 225 ; sat= 135 ; }
+                    else if ((hue >= 218.5) && (hue <=  245.5) && (sat >= 0    )) { hue = 225 ; sat= 67  ; }
+                    else if ((hue >= 245.5) && (hue <=  281  ) && (sat >= 146  )) { hue = 266 ; sat= 169 ; }
+                    else if ((hue >= 245.5) && (hue <=  281  ) && (sat >= 83   )) { hue = 266 ; sat= 110 ; }
+                    else if ((hue >= 245.5) && (hue <=  281  ) && (sat >= 0    )) { hue = 266 ; sat= 54  ; }
+                    else if ((hue >= 281  ) && (hue <=  315.5) && (sat >= 146  )) { hue = 296 ; sat= 140 ; }
+                    else if ((hue >= 281  ) && (hue <=  315.5) && (sat >= 83   )) { hue = 296 ; sat= 92  ; }
+                    else if ((hue >= 281  ) && (hue <=  315.5) && (sat >= 0    )) { hue = 296 ; sat= 46  ; }
+                    else if ((hue >= 315.5) && (hue <=  346.5) && (sat >= 146  )) { hue = 335 ; sat= 180 ; }
+                    else if ((hue >= 315.5) && (hue <=  346.5) && (sat >= 83   )) { hue = 335 ; sat= 107 ; }
+                    else if ((hue >= 315.5) && (hue <=  346.5) && (sat >= 0    )) { hue = 335 ; sat= 51  ; }
+                    else if ((hue >= 346.5) && (hue <=  358  ) && (sat >= 146  )) { hue = 358 ; sat= 180 ; }
+                    else if ((hue >= 346.5) && (hue <=  358  ) && (sat >= 83   )) { hue = 358 ; sat= 112 ; }
+                    else if ((hue >= 346.5) && (hue <=  358  ) && (sat >= 0    )) { hue = 358 ; sat= 54  ; }
+
+                    fritzBox.setHueAndSaturation(ain, hue, sat, 0);
                 } else if (command instanceof PercentType) {
                     brightness = ((PercentType) command).toBigDecimal();
                 } else if (command instanceof OnOffType) {
```
...though, notably this extracted table does not include values for pure white light, which the bulb can also do. It is also limited to the values that can be realized via `setcolor`, even if the bulb can realize other colors in its alternative operation mode, configurable via `setcolortemperature`.

**Comment by vich-667** [comment]
@sommer Thank you for your replay. Sorry for my late response, but it cost me some time to be able to try out your code snippets. (I'm absolutly new to Java and I don't go into that internals of openhab).

In a first step I tried to work with a rule, waht don't works well to me.

Finally I was able to run your code https://github.com/vich-667/openhab-addons/pull/1/files what works fine to me. I also read the pdf you linked. As far as I understand it, fritz box only support that dedicated values. If only this values are supported currently by the fritz box and it's light bub it would be great to add this to openhab.

In addition I have the effect that my **FRITZ!DECT 500** is detected as *FRITZ_DECT_500* and *HAN_FUN_COLOR_BLUB*, where only the HAN FUN thing works do me. I saw you only added the light temperature to the HAN FUN device. Is it the same to you?

**Comment by cweitkamp** [comment]
Hi all, I have some good news for you. There is an undocumented method "setunmappedcolor" available for the HTTP interface which allows to set a user-defined color for the bulbs without restrictions related to the predefined color mappings.

I already tried to implement a solution for this. A test version can be installed via UI.

Settings -> JSON third-party Add-Ons: Insert URL "https://christophweitkamp.de/openhab/addons.json"

![2](https://user-images.githubusercontent.com/5131747/186423373-c9fca4e1-ae3d-42b9-8b9d-bd7be49a9faa.png)

Settings -> Bindings: In section "Other Add-Ons" choose "CW - AVM FRITZ! Binding (stable)" and start installation. **Note**: Uninstall original AVM FRITZ! Binding before installing the test version.

![2 (1)](https://user-images.githubusercontent.com/5131747/186423450-f721669f-ffa7-43eb-bfdd-6cbd723789ca.png)

Happy to get some feedback.

**Comment by cweitkamp** [comment]
I submitted my changes in PR #13317 

@sommer Are you planning to contribute the code for the color temperature channel?

**Comment by vich-667** [comment]
@cweitkamp: I justed tested your solution with "setunmappedcolor". Works fine to me. But the same effect here. Only the "HAN_FUN_COLOR_BLUB" works but not the "FRITZ_DECT_500"

@sommer I would also like to have the color temperature channel in.

**Comment by outerSpaceToast** [comment]
It seems that with the current version of openHAB 3.4 changing color is working now, BUT obviously it is not possible to change back to white mode, after once having set a color option.
Did I miss something?
Is it planned to bring it back?
Also currently it is not possible to just change brightness, because as soon as you change something the bulb switches to color mode.
