### ISSUE TITLE
[pulseaudio] Problem with audio source (Pipe not connected)

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12432]
I tested the new feature recently added allowing to use a pulseaudio source as a OH audio source. I used it with dialog processor.
I have frequent errors of this kind (but not systematically):
```
11:44:55.287 [WARN ] [eaudio.internal.PulseAudioAudioSource] - IOException while reading from pulse source: Pipe not connected
```

I should admit that I am using the binding version form my PR 12423 but this PR does not change anything about the audio source handling.

@GiviMAD  for information

**Comment by GiviMAD** [comment]
Have you tried to increase the soTimeout for the sink/source you are using? under advance configuration. 
That fixed some errors for me.

**Comment by lolodomo** [comment]
No I am currently using the default settings. I will try to increase this timeout and will let you know if I helps. 

I noticed no problem with the sink, only with the source.

**Comment by GiviMAD** [comment]
@lolodomo can this one be closed now?

**Comment by lolodomo** [comment]
Yes I believe because this exception is no more logged.
