### ISSUE TITLE
[lgwebos] Make the `rcButton` channel readable

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-addons#12449]
## Your Environment

* Version used: 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian

Would it be possible to make the `rcButton` channel also readable? So one can respond to certain button presses in certain cases, for example, we use Emby to watch old movies, Emby does not respond to the 4 color buttons on the remote - I thought, maybe I can use these 4 color buttons for something else through OpenHab, for example turning lights on and off.

**Comment by lolodomo** [comment]
If you mean catching a key pressed on your remote control, this is not doable.

**Comment by lolodomo** [comment]
I close this request because not doable.
