### ISSUE TITLE
Google add-ons use deprecated OAuth out-of-band (flow)

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#12455]
Some add-ons using Google APIs still use the deprecated OOB flow. It is no longer possible to create new Google OAuth tokens using the OOB flow since February 28th.

See: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#disallowed-oob

As a result it is no longer possible to setup the following add-ons:

* Google Cloud Text-to-Speech
* Google Cloud Speech-To-Text
* Nest Binding

These need to be changed to use one of the other flows.

**Comment by Jelle28** [comment]
Is there any redirect_uri that can currently be used as an alternative for Nest Binding? Like "https://google.com"?

**Comment by wborn** [comment]
I had a look at this today and got Google TTS working by changing the redirect_url to https://www.google.com .
When creating OAuth credentials in the "Create OAuth client ID" you should now choose "Web application" as "Application type" (instead of a "TVs and Limited Input devices"). Then make sure to add "https://www.google.com" to the "Authorized redirect URIs".

Then after opening the OAuth URL in your browser it will redirect and you'll then need to copy/paste the "code" in URL parameter to the Authorization Code configuration parameter in openHAB. It would ofcourse be nicer if it would redirect to openHAB itself which could then automatically use it. But at least it is a good start to get it working again. :slightly_smiling_face: 

It'll probably also work for the other add-ons like this, so I've created a few JARs using https://www.google.com as redirect_url for now:

* [org.openhab.binding.nest-3.3.0-SNAPSHOT.jar](https://github.com/wborn/openhab-addons/releases/download/google-oauth-20220410/org.openhab.binding.nest-3.3.0-SNAPSHOT.jar)
* [org.openhab.voice.googlestt-3.3.0-SNAPSHOT.jar](https://github.com/wborn/openhab-addons/releases/download/google-oauth-20220410/org.openhab.voice.googlestt-3.3.0-SNAPSHOT.jar)
* [org.openhab.voice.googletts-3.3.0-SNAPSHOT.jar](https://github.com/wborn/openhab-addons/releases/download/google-oauth-20220410/org.openhab.voice.googletts-3.3.0-SNAPSHOT.jar)

**Comment by Jagohu** [comment]
I have a few Nest Protects, which don't link up even with this method - I keep getting this after inserting the link and selecting my Google account:
```
Can't find devices to link to NestProtectNew
If your home has multiple members, the person who first set up the home must migrate their Nest Account to a Google Account before you can link to NestProtectNew
```

It also seems like that there are no traits listed in the Device Access Console for Nest Protect - can it be the reason why?

**Comment by wborn** [comment]
Hi @Jagohu, you should also different URLs for getting an authorizaton code. I've added them to my [initial comment](https://github.com/openhab/openhab-addons/issues/12455#issuecomment-1094372114). I ran out of time yesterday to document this and also did not have time to test all add-ons. But I now did and they all seem to work this way. :slightly_smiling_face: 

> It also seems like that there are no traits listed in the Device Access Console for Nest Protect - can it be the reason why?

The SDM API does not support the Nest Protect, that is also clearly mentioned in the [add-on docs](https://www.openhab.org/addons/bindings/nest/):

> The SDM API currently does not support Nest Protect devices. There are no structure Things when using the SDM API, because the SDM API does not support setting the Home/Away status like the WWN API does.

**Comment by Jagohu** [comment]
Thanks - shoot, it's a pity that it doesn't support them - I thought from the OH documentation that it does. Well, maybe someday.. Thanks a lot!

**Comment by resetpointer** [comment]
Was there a fix for OH-2.5.x?

**Comment by wborn** [comment]
Not by me. Maybe it's time to upgrade? 😉

**Comment by resetpointer** [comment]
@wborn,

I upgraded to version 3.3.0 and found that NEST OAUTH2 authentication is not reliable.  I got it to work a few times but couldn't re-authenticate using the typical work-flow has described here.  Below is the error, please let me know if it is possible to enable debug trace of the actual URI that OH3 uses.



```
14:57:58.470 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'nest_sdm.things'
14:57:58.507 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'nest:sdm_account:my_nest_sdm_p' changed from UNINITIALIZED to INITIALIZING
14:57:58.509 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'nest:sdm_account:my_nest_sdm_p' changed from INITIALIZING to UNKNOWN
14:57:58.645 [ERROR] [.oauth2client.internal.OAuthConnector] - grant type authorization_code to URL https://accounts.google.com/o/oauth2/token failed with error code invalid_grant, description Bad Request
14:57:58.646 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'nest:sdm_account:my_nest_sdm_p' changed from UNKNOWN to OFFLINE (CONFIGURATION_ERROR): Failed to authorize SDM client. Check the authorization code or generate a new one.
14:57:59.533 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'nest_sdm.things'


```


FYI, I am able to exchange the authentication token that was copied from browser URL for an access token with this command

`curl -L -X POST -H "Content-Length: 0" 'https://www.googleapis.com/oauth2/v4/token?client_id=${NEST_CLIENT_ID}&client_secret=${NEST_CLIENT_SECRET}&code=${NEST_AUTHORIZATION_CODE}&grant_type=authorization_code&redirect_uri=https://www.google.com'`

I am not sure why OH3 is giving me that invalid grant error.  Is it possible that this is the same bug that was addressed in OH-3.4 as described here:  https://github.com/openhab/openhab-addons/pull/12711


thank you,

**Comment by resetpointer** [comment]
@wborn 

I can confirm that it was the bug related to the fix that was patched in version 3.4 (PR 12711).
Authorization only worked for a newly created credential, it wont work if auth_code is updated on an existing credential.

If you have time, would you please directly me to the procedures on upgrading to OH-3.4?  thanks

**Comment by resetpointer** [comment]
@wborn 

I just realized that I am using the latest version with the said patch (PR 12711), version 3.3.0.1

As the result, at least when configuring the nest things file for the first time, SDM authorization code and pubsub authorization codes have to be provided **only for the first time**, after that if modification is made, user must blank out these two fields for nest sdm and pubsub to work:

sdmAuthorizationCode=""
pubsubAuthorizationCode=""

Although I have not tested via web-UI, but I have a feeling that it would only work with this same work-flow.

I think this is a bug, we should address in the documentation website, oath2 registration code, web UI or some sort of verbose log.

thanks and sorry for the noise here!

**Comment by wborn** [comment]
I don't think binding code can be made aware of which means are used for configuring Things (files/UI). So perhaps it is best to add some docs for this.
