### ISSUE TITLE
[somfytahoma] Detected a new unsupported device: Shutter with widgetName: DynamicShutter

### ISSUE THREAD

**Issue by ElectricBlue66** [openhab/openhab-addons#12458]
Hi, I'm not too sure whether this is the right place to post this. But I'm sure someone can move it if it is wrong.

I recently installed my Somfy Tahoma Connectivity Kit and set everything up. In OH3 I added the SomfyTahoma binding and it automatically discovered my Somfy awning. However, OH3 does not automatically discover my roller shutters. I noticed that the log file reports the following:

`==> /var/log/openhab/openhab.log <== 2022-03-10 17:43:32.680 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: Shutter with widgetName: DynamicShutter 2022-03-10 17:43:32.695 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below 2022-03-10 17:43:32.697 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition: Commands: { close (params: 0); goToAlias (params: 1); identify (params: 0); open (params: 0); saveAlias (params: 1); setName (params: 1); setNodeDefinition (params: 3); stop (params: 0); } States: {core:AvailabilityState (values: available, unavailable); core:NameState (values: ); core:RemovableState (values: ); } 2022-03-10 17:43:32.700 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: {name='core:AvailabilityState', type=3, value=available}`

This is reported 7 times, which matches the number of roller shutters. Looks like they are not supported. I tried to add them as things, but I don't know the Somfy Tahoma Device URL.

Can I find the URL somewhere? Or are the roller shutters really not supported?

Thanks for any help.

Rob

**Comment by octa22** [comment]
Hi,

I have prepared a version, which adds the support. Can you test it please?
https://www.dropbox.com/s/4i37burwfkhc2zl/org.openhab.binding.somfytahoma-3.3.0-SNAPSHOT.jar?dl=1
Thanks.
Ondrej

**Comment by ElectricBlue66** [comment]
Hey, that sounds great. I'm in Berlin for the weekend. Will test next week.

Rob

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ElectricBlue66** [comment]
Hi Ondrej,

I installed the binding and the missing things are now discovered. I was able to add them as Items and can now operate my blinds. Haven't tested Alexa yet.

Thanks for such fast support and an update. Great work.

Rob

**Comment by lolodomo** [comment]
Closed by #12495
