### ISSUE TITLE
[wemo] Excessive channel updates of currentPower for WeMo Insight Switch

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12460]
For my WeMo Insight Switches, this is a quite common scenario:
- 2022-03-11 23:53:58.859: 23 W
- 2022-03-11 23:54:06.902: 24 W
- 2022-03-11 23:54:15.952: 23 W
- 2022-03-11 23:54:24.005: 24 W
- 2022-03-11 23:54:32.025: 23 W
- 2022-03-11 23:54:37.557: 24 W
- 2022-03-11 23:54:53.677: 23 W
- 2022-03-11 23:55:01.761: 24 W

In this period of ~a minute these values are actually received from the device:
- 2022-03-11 23:53:58.845: 23.27 W
- 2022-03-11 23:54:00.355: 23.24 W
- 2022-03-11 23:54:02.867: 23.26 W
- 2022-03-11 23:54:04.375: 23.275 W
- 2022-03-11 23:54:06.885: 23.765 W
- 2022-03-11 23:54:08.395: 23.98 W
- 2022-03-11 23:54:10.904: 24.13 W
- 2022-03-11 23:54:12.414: 24.16 W
- 2022-03-11 23:54:15.937: 23.415 W
- 2022-03-11 23:54:17.440: 23.38 W
- 2022-03-11 23:54:19.952: 23.275 W
- 2022-03-11 23:54:21.457: 23.26 W
- 2022-03-11 23:54:23.972: 23.615 W
- 2022-03-11 23:54:25.478: 23.64 W
- 2022-03-11 23:54:27.993: 23.645 W
- 2022-03-11 23:54:29.499: 23.655 W
- 2022-03-11 23:54:32.044: 23.405 W
- 2022-03-11 23:54:33.520: 23.31 W
- 2022-03-11 23:54:36.035: 23.495 W
- 2022-03-11 23:54:37.543: 23.565 W
- 2022-03-11 23:54:40.055, 23.64 W
- 2022-03-11 23:54:41.562: 23.685 W
- 2022-03-11 23:54:44.076: 23.805 W
- 2022-03-11 23:54:45.585: 23.775 W
- 2022-03-11 23:54:48.099: 23.81 W
- 2022-03-11 23:54:49.601: 23.765 W
- 2022-03-11 23:54:53.662: 23.37 W
- 2022-03-11 23:54:57.697: 23.38 W
- 2022-03-11 23:54:59.191: 23.42 W
- 2022-03-11 23:55:01.710: 24.05 W

When calculating the average current power consumption for this sample period, it will actually be closer to 23 W than 24 W, so we can safely round down.

Introducing an algorithm for calculating a moving average in a sliding window would prevent such excessive channel updates which is causing a lot of logging and data growth when using persistence.

**Comment by jaywiseman** [comment]
I would welcome this - I use this channel to determine if my washing machine is being used or not.  As you know, it jumps all over the board as you mentioned and the rule fires based on such movement.

Best, Jay

**Comment by jlaur** [comment]
@jaywiseman - I have prepared a fix for this, will push a pull request soon.

**Comment by jlaur** [comment]
@jaywiseman - please see linked pull request which also contains a link for a JAR.
