### ISSUE TITLE
[senechome] Channel "liveHouseConsumption" not present

### ISSUE THREAD

**Issue by ekrempel** [openhab/openhab-addons#12475]
## Expected Behavior
Senec thing allowing me to create an item on the channel "liveHouseConsumption"

## Current Behavior
I successfully created a OH3 thing for a SENEC.Home V3 hybrid. I now can use a wide variety of channels. The only channel I seem to be missing is liveHouseConsumption as mentioned in the docs. I tried manually adding a item via config file but this does not generate any values. 

There are no errors in the logs.

<img width="542" alt="senec" src="https://user-images.githubusercontent.com/923749/158265447-dd839ed1-b1e3-4807-bbb4-b42405ffdf30.png">

## Steps to Reproduce (for Bugs)
1. Install binding
2. Add thing to binding
3. Try to add item to channel

## Context
I want to see how much energy my house is using to calculate my level of power autonomy per day.

## Your Environment
I am running an OH 3.2 system on raspberry with latest updates.

**Comment by ekrempel** [comment]
I tried some more debugging but I have to little experience with openHAB development to add additional debugs and find where the channel went missing. 

@KorbinianP; @Hilbrand; @wborn: Can I ask you guys if you have any hints and what I can try further? Even when setting the log level to trace I do not get any errors.

**Comment by Hilbrand** [comment]
The channel is updated on this line: https://github.com/openhab/openhab-addons/blob/25a923be39f15d6ccec4282400fb8080896525f8/bundles/org.openhab.binding.senechome/src/main/java/org/openhab/binding/senechome/internal/SenecHomeHandler.java#L205 
If you debug print the value it gets here and what it passes to the updateState method. Also add a log statement if `channel` is null in `updateQtyState`.

Also does the channel show the update in the openHAB event log? If not, it might be the channel is not linked to an item.

**Comment by ekrempel** [comment]
Hi @Hilbrand, thanks for your answer. I am still at the point of the initial bug report. For some reason the channel does not exist. So if I look at the Thing in the OH3 gui, there is no channel called "liveHouseConsumption". If I try to add it manually via a configfile it does not get any values. 

I first thought that the channel does not exist as my Senec does not has a corresponding value. But as shown in my second message I can get a json with the value in it.

**Comment by lolodomo** [comment]
The channel is defined there:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.senechome/src/main/resources/OH-INF/thing/thing-types.xml#L56

**Comment by ekrempel** [comment]
I finally found the solution for my problem. As @lolodomo wrote the channel was added in OH3.1. I am using the Thing since OH3.0. 

According to my research (most) OH3 bindings do not update the channels for already existing things. https://community.openhab.org/t/how-should-i-upgrade-existing-things-when-i-update-my-binding/94842/20

So you have to delete your thing and add it again to get the new list of available channels. After doing that I now have the missing channel.
