### ISSUE TITLE
[Shelly] Binding - Shelly Duo Color(SHCB-1) - Change Color Mode

### ISSUE THREAD

**Issue by MarkusOpenHab** [openhab/openhab-addons#12480]
It seems that there is no way to toggle between color and white mode for Shelly Duo Color(SHCB-1) devices.
Would'nt it be nice to have an additional channel for Example: control#colormode(switch) to activate color mode of the SHCB-1 devices?
Of Cource another(nicer) way would be, to automatically switch to color mode if any color channel is modified and switch back to white mode when white#brightness or white#temperature changed.

## My Environment
OpenHab 3.2.0 Relase with Shelly Binding 3.2.0

**Comment by markus7017** [comment]
that is a complex thing, it would require chaging the thing type in on the fly. Possible, but tricky.

**Comment by markus7017** [comment]
This is not supported by the binding and requires significant rework. For now white mode and color mode are represented by different thing types due a different set of channels.

**Comment by kojid0** [comment]
I must say that I'm a little disappointed with the shelly openhab binding missing a simple switch. The rest works fine, thank you for the binding! 
Just wanted to leave a comment to show that I'm also interested in a simple way to switch between color and white mode. Please re-open this issue. I'll probably return my shelly duo bulb for now and keep an eye on this thread for later buy decisions.
