### ISSUE TITLE
[tado] Excessive Maven / Eclipse warnings on build

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#12498]
This is not really a bug, but more of a niggle..

While working on #12470 I noticed that the build produces over four hundred [WARNING] messages. The build succeeds, and the binding runs fine, but the build log is not a pretty sight.

The build process relies on Swagger Code-Gen to parse a YAML description of the Tado API and auto generate the respective Java classes for serialization and de-serialization. And all but a handful of the warnings are due to the building of this Swagger auto generated code.

So I would like to figure out what setting one needs to make in (for example) the POM to supress (or eliminate) the warnings when building the Swagger Code-Gen auto created classes. I would eventually create another PR post #12470 to actually implement that fix.

=> Any thoughts / suggestions?

**Comment by andrewfg** [comment]
@dfrommi ??

**Comment by andrewfg** [comment]
In Eclipse you can turn off compiler warnings on the Swagger auto generated code by setting 'Ignore optional compile problems = YES' on the respective folder in the build path. => So the question is how to do that when Maven is building it?

![image](https://user-images.githubusercontent.com/893994/159273676-e86df931-0742-4294-af38-f14bde8b83bd.png)

**Comment by andrewfg** [comment]
@cpmeister / @kaikreuzer any thoughts on this? (Probably #9125 refers..)

**Comment by wborn** [comment]
I had a look at the Eclipse m2e plugin and ECJ compiler code and found a compiler argument to suppress warnings for certain directories, see #13100.

**Comment by wborn** [comment]
You may also want to replace that old [swagger-codegen-maven-plugin:2.3.1](https://github.com/openhab/openhab-addons/blob/25e2153d1a49f86390d1c6b39908dd0357eb909d/bundles/org.openhab.binding.tado/pom.xml#L27-L29) (released in 2018) with a current version of the [openapi-generator-maven-plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin).

**Comment by dfrommi** [comment]
The code generator can also be adjusted. Depending on the warning, this can be easy or hard.
Alternatively, we can also stop generating code and just commit once the generated code and fix it manually. 
It's anyway still a unicorn, as the wider usage in OpenHAB that I was hoping for, never happened.
