### ISSUE TITLE
[openwebnet] Thermo things are refreshed twice at boot/reconnect

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#12490]
Thermo things are refreshed 2 times at boot/reconnect, first from bridge then from Thermo handler (in bridgeStatusChanged()). 
This causes unnecessary messages at boot/reconnect.

## Possible Solution
Remove method bridgeStatusChanged() from Thermo handler class

**Comment by lolodomo** [comment]
Closed by #12502
