### ISSUE TITLE
[daikin] wrong value off for TargetHeaterCoolerState characteristic of the item _HomekitMode

### ISSUE THREAD

**Issue by taggandrew1** [openhab/openhab-addons#12494]
## Current Behavior
When air conditioner is set to OFF via homekit on IOS, I.E. air is not running and setting in homekit Mode is OFF, the following log file entries occur repeatedly every few minutes:

[WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value off for TargetHeaterCoolerState characteristic of the item LivingRoomAircon_HomekitMode. Expected one of following [AUTO, HEAT, COOL]. Returning AUTO.

from:
tail -f /var/log/openhab/openhab.log /var/log/openhab/events.log

## Steps to Reproduce (for Bugs)
2. Configure Daikin binding to connect to air conditioner using Apple Homekit with 'HeaterCooler' option
1. Set airconditioner to off via HomeKit. 

## Context
No issue with the functionality, just noise in the logfiles

## Your Environment
* openHab 3.2.0 Release Build
* Daikin Binding 3.2.0
* Running on openHabian on raspberry pi 4
* Airconditioner is Daikin Zena FTXJ35TVMAW / G001952
* iOS 15.4

*The point 'Homekit Mode' has metadata:

    Apple Homekit   HeaterCooler.TargetHeaterCoolerState

*with Code:

    value: HeaterCooler.TargetHeaterCoolerState
    config:
      HEAT: HEAT
      COOL: COOL

**Comment by jimtng** [comment]
This may be a bug with `Homekit` binding, not daikin.

**Comment by jimtng** [comment]
@taggandrew1 do you still experience this issue? There's been a lot of changes in the Homekit addon which may have solved this.

**Comment by lsiepel** [comment]
Can you share your ac related  item definitions / links with channels and HomeKit metadata?

**Comment by jimtng** [comment]
The Homekit binding has undergone a lot of changes. Since there has been no response, I'd say close this issue.
