### ISSUE TITLE
[homekit] Can't control Group:Color and Group:Dimmer

### ISSUE THREAD

**Issue by NicBuh** [openhab/openhab-addons#12505]
I am using Homekit binding together with the EspMilightBinding. A group of Color items like this:

`Group:Color AllLivingroom_Color "All Livingroom Color" (Livingroom) {homekit="Lighting, Lighting.Hue, Lighting.Brightness, Lighting.Saturation" [dimmerMode="filterOn"]}
`

Results in this error:

"Item type Group is not supported for AllLivingroom_Color. Only ColorItem and DimmerItem are supported."

Group:Switch in the meantime works without issues. I am not sure if this is the expected behaviour, or by mistake.

**Comment by yfre** [comment]
thanks for reporting. currently group of colors is not supported by homekit binding.  should be easy to add

**Comment by NicBuh** [comment]
Thanks, let me also explain the motivation behind the request, in case this is helpful. I have noticed that when I group many items in openhab instead of grouping them in Homekit, the commands are executed more reliably. I haven't been able to track the root cause, but when I try to control many grouped items in Homekit at the same time, many Milights don't receive the command. I don't know if this issue is caused by the Homekit binding, the EspMilight binding or the Milight Hub (or a combindation of all three).

**Comment by ccutrer** [comment]
@NicBuh : this should be fixed by e4fe6889d0525973e0027bb97337c1dd34176c26 as of the latest 3.4.0 milestone build.

**Comment by yfre** [comment]
closing is the fix is provided with 3,4M4 and will be part of release 4
please open another ticket in case it is not working as expected.
