### ISSUE TITLE
[tesla] Configuration Error / Failed to obtain access token for API

### ISSUE THREAD

**Issue by kojid0** [openhab/openhab-addons#12516]
The tesla binding stopped working for me a couple of days ago. I haven't changed the configuration.
I was able to get a working connection to the tesla:account thing (ONLINE) by providing the API refresh token (obtained externally) and the e-mail+password.
I removed the thing and tried to re-add it with a new externally obtained API refresh token + email + password.
Not I'm getting this error

Log:
```
Thing 'tesla:account:12345' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
Thing 'tesla:account:54321' changed from UNINITIALIZED to INITIALIZING
Thing 'tesla:account:54321' changed from INITIALIZING to UNKNOWN
Thing 'tesla:account:54321' changed from UNKNOWN to OFFLINE (CONFIGURATION_ERROR): Failed to obtain access token for API.
Thing 'tesla:account:54321' changed from OFFLINE (CONFIGURATION_ERROR): Failed to obtain access token for API. to OFFLINE (CONFIGURATION_ERROR)
```

Environment: openHAB 3.3.0.M2 on ubuntu 20.04

**Comment by skylord73** [comment]
Same problem.
Tried to enter a new refresh token from external app, but still not working

`2022-03-25 17:23:30.361 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:account:b0d4449074' changed from UNINITIALIZED (DISABLED) to INITIALIZ                                                                 ING
2022-03-25 17:23:30.367 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:account:b0d4449074' changed from INITIALIZING to UNKNOWN
2022-03-25 17:23:30.390 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:modely:afe6b92cf0:LRWYGCEKXNC263951' changed from UNINITIALIZED (BRIDG                                                                 E_UNINITIALIZED) to INITIALIZING
2022-03-25 17:23:30.396 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:modely:afe6b92cf0:LRWYGCEKXNC263951' changed from INITIALIZING to UNKN                                                                 OWN
2022-03-25 17:23:30.715 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:account:b0d4449074' changed from UNKNOWN to OFFLINE (CONFIGURATION_ERR                                                                 OR): Failed to obtain access token for API.
2022-03-25 17:23:30.715 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:account:b0d4449074' changed from OFFLINE (CONFIGURATION_ERROR): Failed                                                                  to obtain access token for API. to OFFLINE (CONFIGURATION_ERROR)
2022-03-25 17:23:30.716 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:modely:afe6b92cf0:LRWYGCEKXNC263951' changed from UNKNOWN to OFFLINE (                                                                 BRIDGE_OFFLINE)
`

**Comment by DollC** [comment]
Since yesterday the tesla binding is also not working for me.

**Comment by jwsp1** [comment]
Maybe @kaikreuzer knows more? He seems to have worked on the binding in the past.

**Comment by hlemmens** [comment]
Same problem here. Tried out everything but no result.

**Comment by phuongpham** [comment]
Same problem here. Thought it might help with restarting the binding and then rebooting OH but still the same issue

**Comment by kaikreuzer** [comment]
Bad news - I have the same issue since 2 days and thus have no solution for it. 😢 
It seems Tesla has changed something about the auth of their API - let's hope the global tesla tech community can figure out how to solve it soon. I'll try to search the web for some clues...

**Comment by kaikreuzer** [comment]
Ok, and now some good news: I found https://github.com/timdorr/tesla-api/issues/548 and came up with a PR that fixes the issue locally for me. Let's hope it's merged quickly and I'm looking forward to whether it works for all of you as well!

**Comment by digitaldan** [comment]
i'll give it a try as soon as the PR build completes!

**Comment by digitaldan** [comment]
ended up just building it myself, looks good!

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1903737/160258524-ea2ea45b-6670-4f30-b7b3-7295f207e6c1.png">

**Comment by DollC** [comment]
Also Wirkung for me again . Thanks !

**Comment by kojid0** [comment]
Sorry for the question but what is the easiest way to install the fix? Can somebody please share a short instruction?

**Comment by wborn** [comment]
It will soon be available in the snapshot build now it has been merged and a build has been triggered.

**Comment by hlemmens** [comment]
@wborn Do I understand well that the Openhab binding will be updated soon? I'm afraid the Timor stuff goes way beyond my present IT skills.

**Comment by kojid0** [comment]
> @wborn Do I understand well that the Openhab binding will be updated soon? I'm afraid the Timor stuff goes way beyond my present IT skills.

I switched to the snapshot build and the update should be available in a couple of hours, I guess, according to the build status https://ci.openhab.org/job/openHAB3-Distribution/

**Comment by phuongpham** [comment]
The build is now finished.
I managed to download the latest snapshot from here: https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220327.072829-84.jar

Just run this command in karaf console:

`bundle:update org.openhab.binding.tesla https://openhab.jfrog.io/artifactory/libs-snapshot-local/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0-SNAPSHOT/org.openhab.binding.tesla-3.3.0-20220327.072829-84.jar`

**Comment by hlemmens** [comment]
it didn't work for me in Karaf console. I installed openhab in the "old" way without Openhabian. How to make the update from the Linux console?

**Comment by phuongpham** [comment]
> 

I'm not using openhabian either. But you need to make sure to connect to the karaf console. By default it using port 8101 (https://www.openhab.org/docs/administration/console.html)

What error do you get when you say it didn't work?

**Comment by hlemmens** [comment]
I didn't got an  error, but nothin changed. I still have version 3.3.0.M2:
/var/lib/openhab/tmp/kar/openhab-addons-3.3.0.M2/org/openhab/addons/bundles/org.openhab.binding.tesla/3.3.0.M2/org.openhab.binding.tesla-3.3.0.M2.jar

**Comment by hlemmens** [comment]
I used this command to connect to the karaf console: 

openhab-cli console

**Comment by phuongpham** [comment]
> I used this command to connect to the karaf console:
> 
> openhab-cli console

ok this works to.
What is the output when you run 

`bundle:list |grep Tesla`

**Comment by hlemmens** [comment]
What is the output when you run

bundle:list |grep Tesla

293 │ Active │  80 │ 3.3.0.202203270809    │ openHAB Add-ons :: Bundles :: Tesla Binding

It seems the new binding is installed. But the Tesla bridge is still offline. No refresh token is generated in the bridge, even when I pass my credentials.

**Comment by phuongpham** [comment]
> s the output when you run
> 
> bundle:list |grep Tesla
> 
> 293 │ Active │ 80 │ 3.3.0.202203270809 │ openHAB Add-ons :: Bundles :: Tesla Binding
> 
> It seems the new binding is installed. But the Tesla bridge is still offline. No refresh token is generated in the bridge, even when I pass my credentials.

Ok I thought this authentication method doesn't work any longer.
I had to generate refresh token from a 3rd party app/tools to get the token.
Then I added the token to openHAB

**Comment by hlemmens** [comment]
I got a refresh from third party app and it works now!!. Thanks a lot for your help.

I think this community is very powerful. Looking at the speed info is shared and issues are well treated, I'm astonished.

Thank you all.

**Comment by DollC** [comment]
Could it be that in this fix the possibilty to Set the chargingamps is not working? I get a null pointer exeption in my "ueberschussladung" function with this snapshot

**Comment by hlemmens** [comment]
For me the Set Charging amps function is working fine with the snapshot.

**Comment by DollC** [comment]
> For me the Set Charging amps function is working fine with the snapshot.

thanks for checking. Then I have to debug again

**Comment by tkranz** [comment]
> For me the Set Charging amps function is working fine with the snapshot.

can you share the item definition for charging Amps ?`

thanks
Thomas

**Comment by hlemmens** [comment]
There's nothing special in the item definition, except it is a setpoint.
![Screenshot 2022-03-27 at 17 25 47](https://user-images.githubusercontent.com/15854801/160288722-ed7424ad-acca-4ca1-9818-e2262f6fca2b.png)

**Comment by tkranz** [comment]
anyone else has this errors and disconnects ?
2022-03-27 17:52:41.378 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.authenticate(TeslaAccountHandler.java:259) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$0(TeslaAccountHandler.java:377) ~[?:?]
2022-03-27 17:52:41.443 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:models:cf6c1bd88a:5YJSA7E21HF178912' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2022-03-27 17:52:41.526 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'tesla:models:cf6c1bd88a:66da4728df' changed from OFFLINE (BRIDGE_OFFLINE) to ONLINE
2022-03-27 17:52:56.379 [ERROR] [internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.authenticate(TeslaAccountHandler.java:259) ~[?:?]
	at org.openhab.binding.tesla.internal.handler.TeslaAccountHandler.lambda$0(TeslaAccountHandler.java:377) ~[?:?]

**Comment by kojid0** [comment]
@tkranz 
Yes, I also get this error. Don't know when it occurs though, I enabled the account thing again and can make it work to send commands. We'll see when the account thing gets offline again.

**Comment by daabm** [comment]
Updating from openhab.jfrog.io via karaf worked for me as well. Car is now online again.

**Comment by daabm** [comment]
@kaikreuzer Update: With the Tesla binding version 3.3.0.202203290406, after some time i get
08:07:22.010 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle, response : 401, Unauthorized
08:07:22.010 [WARN ] [.internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again
08:07:22.011 [ERROR] [.internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle
This continues until stopping/starting the Tesla thing. I now enabled Trace logging for the binding, will check again later.

**Comment by kaikreuzer** [comment]
Thanks @daabm.
I am seeing some other errors in my log today:
```
08:26:10.292 [DEBUG] [.internal.handler.TeslaAccountHandler] - Setting up an authenticated connection to the Tesla back-end
08:26:10.292 [ERROR] [.internal.handler.TeslaAccountHandler] - An exception occurred while connecting to the Tesla back-end: 'null'
java.lang.NullPointerException: null
```
Will have to look at this again. 😞

**Comment by daabm** [comment]
Happened again a few minutes ago (I removed all lines which are not associated with the Tesla binding). Trace logging did not really help, unfortunately.

`16:07:28.480 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle, response : 200, OK`
`16:07:28.482 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle: VIN ******************`
[...]
`16:07:28.486 [TRACE] [.internal.handler.TeslaVehicleHandler] - The variable/value pair 'notifications_enabled':'false' is successfully processed`
`16:08:28.652 [DEBUG] [.internal.handler.TeslaVehicleHandler] - Querying the vehicle, response : 401, Unauthorized`
`16:08:28.653 [WARN ] [.internal.handler.TeslaVehicleHandler] - Got an unsuccessful result, setting vehicle to offline and will try again`
`16:08:28.653 [ERROR] [.internal.handler.TeslaVehicleHandler] - An error occurred while querying the vehicle`

If I can provide additional data, ur welcome 👍
