### ISSUE TITLE
[homekit] ColorTemperature Characteristic - item Dimmer not supported

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#12517]
Hi,

if use Dimmer with ColorTemperature Characteristic get error:

`2022-03-25 16:18:28.618 [WARN ] [ssories.HomekitCharacteristicFactory] - Item type Dimmer is not supported for LEDKorytarzSypialnia_tempvalue. Only NumberItem is supported.`

Any chance to add it.?

**Comment by hww3** [comment]
Hi-

I have run into similar situations where only NumberItems are supported but (for certain types of item) where a DimmerItem might be more natural. I've been testing a change to extend the types of allowable items to speaker accessories, so I think I might be able to come up with a fix to test for this (I don't currently have a color adjustable light set up so I'd need some help testing it out). I'll make a note to look at it this weekend.

**Comment by yfre** [comment]
closing this as the requested enhancement was implemented by @ccutrer is available in the latest 3.4M4 (https://github.com/openhab/openhab-distro/releases/tag/3.4.0.M4) and will be part of next release
please open a bug report is this still no working with M4 or 3.4 release
