### ISSUE TITLE
[tesla] Handler TeslaVehicleHandler tried updating the thing status although the handler was already disposed

### ISSUE THREAD

**Issue by jwsp1** [openhab/openhab-addons#12538]
I am getting this error
`2022-03-29 10:52:40.366 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler TeslaVehicleHandler tried updating the thing status although the handler was already disposed.`
`2022-03-29 10:52:40.366 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler TeslaVehicleHandler of thing tesla:model3:12345:ABCDE54321 tried updating channel combinedtemp although the handler was already disposed.`

Not only combinedtemp but all other channels.
The channels (like odometer, batterylevel etc) do not refresh anymore and are outdated.

Setup: openHAB 3.3.0, Snapshot Build # 2828

**Comment by lsiepel** [comment]
If i look at [the changed comitted to this binding](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+tesla) since 3.3.0 it might allready be fixed. 

Can you verify this is fixed with the most recent snapshot version of openHAB?
