### ISSUE TITLE
[shelly] Binding shows log entries like "message.offline.status-error-watchdog"

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#12535]
Due to a definition problem in the language resources the binding shows messages like "message.offline.status-error-watchdog" instead of a message text

**Comment by lolodomo** [comment]
The following line should be simply removed as there is already a log entry done by the call to updateStatus.
https://github.com/openhab/openhab-addons/blob/da59cdd255a66275dd7ae11dd294fedca4942d30/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyBaseHandler.java#L497
And the use of INFO level was by the way inappropriate.
