### ISSUE TITLE
[goecharger] Add API V2 support #12400 channels not visible in UI of openhab

### ISSUE THREAD

**Issue by chilobo** [openhab/openhab-addons#12551]
I tried to test the binding an openhab 3.3.0-SNAPSHOT (#2834)

bundle:list shows

`253 â Active â 80 â 3.3.0.202203310340 â openHAB Add-ons :: Bundles :: Go-eCharger Binding`

After installing the binding from the UI (and deleting my own version in openhab/addons):

my existing channels connect to the newly merged binding (seems to work).
When I go to Administration - Things - GOE in the UI no channel section and no code section are shown, just the thing-section and “online”.
Without the channel section connecting and inspecting stuff to the GOE-channels in the UI is not possible.

**Comment by lolodomo** [comment]
I assume you solved your problem? 
Maybe a simple browser cache problem?

**Comment by chilobo** [comment]
I was using the binding until 3 days ago with Hardware version 3 and Firmware 054.11 with openhab 3..0.0 -> 3.4.0

Unfortunately I did an update and upgrade on openhab 3.4.0 and got stuck with a not working 4.0.0.
Seems to be a problem with Java 17, raspi is booting, openhab is not starting.
So give me some days to find out what went wrong and I'll come back.

Prior to the upgrade the channel sections UI/things didn't look quite right, I have to come back to confirm that.

**Comment by chilobo** [comment]
I guess you can close this bug.
I reinstalled openhab, restored my backup, bundle:list shows 3.4.0 on the GO-eCharger Binding and all the parts I am using seem to work fine, channels apearing in the UI.
