### ISSUE TITLE
permissions to /var/lock block usage of USB serial devices on multiple openHAB 3.x containerized and direct installations

### ISSUE THREAD

**Issue by FBachofner** [openhab/openhab-addons#12560]
Since at least November 2020, there have been reports of **openHAB version 3.x** users not being able to use USB Z-Wave sticks such as the Zooz USB Z-Wave Plus S2 Stick ZST10

This has been problematic on all three major platforms for Linux (direct installations, Docker and even some new installs on openHABian / RPi )

The issue is related to OH's apparent need to write a lock file to /var/lock where openHAB does not have permissions.

The workarounds are potentially insecure and (just as bad) do not persist across reboots in certain (most?) cases

Some relevant forum posts:

- [Problem with setting up Zooz USB Z-Wave Plus S2 Stick ZST10](https://community.openhab.org/t/problem-with-setting-up-zooz-usb-z-wave-plus-s2-stick-zst10/134603)
- [OH3: zwave binding Z-Wave Serial Controller Aeotec Z-Stick Gen5 remains offline](https://community.openhab.org/t/solved-oh3-zwave-binding-z-wave-serial-controller-aeotec-z-stick-gen5-remains-offline/108182)

This may be a regression.  Some suggest a similar problem existed prior to 2.x -- it may not have been a problem in 2.5.x, however.

I am posting this in openhab-addons since it is not really core funtionality, but relates (in my specific case, at least) to Z-Wave serial device  bindings.

Feel free to move to "core" if you feel it is better placed there.  Thanks!

**Comment by wborn** [comment]
> Feel free to move to "core" if you feel it is better placed there. 

Seems more like an issue for the [nrjavaserial](https://github.com/NeuronRobotics/nrjavaserial/) library used by openHAB. That library generates the lock files which has some known issues see also https://github.com/NeuronRobotics/nrjavaserial/issues/60.

**Comment by FBachofner** [comment]
Hi @wborn 

> Seems more like an issue for the [nrjavaserial](https://github.com/NeuronRobotics/nrjavaserial/) library used by openHAB. 

Thanks for your input.  I have gotten similar feedback on the OH forums.

Wow.  6+ years!

I think your mention of this issue in _that_ thread is hopefully good enough to keep some attention on the issue.

Let's leave this here to (hopefully) enhance the likelihood people can find workaround(s) in multiple possible areas/efforts of search.

I partially misstated my concern about persistence a bit in my first post here.

Done "properly" it is not so much to do with reboots as with OS and openHAB upgrades.  I fear that such could mess with the [workaround](https://github.com/openhab/openhab-core/issues/2474) of copying /usr/lib/tmpfiles.d/legacy.conf to /etc/tmpfiles.d/legacy.conf and "enforcing" permissions to the /run/lock directory thusly

**Comment by FBachofner** [comment]
Hi @wborn 

> Seems more like an issue for the [nrjavaserial](https://github.com/NeuronRobotics/nrjavaserial/) library used by openHAB. 

Thanks for your input.  I have gotten similar feedback on the OH forums.

Wow.  6+ years!

I think your mention of this issue in _that_ thread is hopefully good enough to keep some attention on the issue.

Let's leave this here to (hopefully) enhance the likelihood people can find workaround(s) in multiple possible areas/efforts of search.

I partially misstated my concern about persistence a bit in my first post here.

Done "properly" it is not so much to do with reboots as with OS and openHAB upgrades.  I fear that such could mess with the [workaround](https://github.com/openhab/openhab-core/issues/2474) of copying /usr/lib/tmpfiles.d/legacy.conf to /etc/tmpfiles.d/legacy.conf and "enforcing" permissions to the /run/lock directory thusly

> Since at least November 2020, there have been reports of **openHAB version 3.x** users not being able to use USB Z-Wave sticks such as the Zooz USB Z-Wave Plus S2 Stick ZST10
> 
> This has been problematic on all three major platforms for Linux (direct installations, Docker and even some new installs on openHABian / RPi )
> 
> The issue is related to OH's apparent need to write a lock file to /var/lock where openHAB does not have permissions.
> 
> The workarounds are potentially insecure and (just as bad) do not persist across reboots in certain (most?) cases
> 
> Some relevant forum posts:
> 
>     * [Problem with setting up Zooz USB Z-Wave Plus S2 Stick ZST10](https://community.openhab.org/t/problem-with-setting-up-zooz-usb-z-wave-plus-s2-stick-zst10/134603)
> 
>     * [OH3: zwave binding Z-Wave Serial Controller Aeotec Z-Stick Gen5 remains offline](https://community.openhab.org/t/solved-oh3-zwave-binding-z-wave-serial-controller-aeotec-z-stick-gen5-remains-offline/108182)
> 
> 
> This may be a regression. Some suggest a similar problem existed prior to 2.x -- it may not have a problem in 2.5.x, however.
> 
> I am posting this in openhab-addons since it is not really core funtionality, but relates (in my specific case, at least) to Z-Wave serial device bindings.
> 
> Feel free to move to "core" if you feel it is better placed there. Thanks!

**Comment by wborn** [comment]
Maybe it's worth a try to use openHAB Docker container again?
I don't know what issues you ran into with that, but I'm using that myself without any issues.
That way you can keep running whatever OS you want on the host. :slightly_smiling_face:

**Comment by wborn** [comment]
Let's close this as it duplicates https://github.com/openhab/openhab-core/issues/2474
