### ISSUE TITLE
[openwebnet] add support for Alarm (WHO=5)

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#12569]
Add support for Alarm Open Web Net messages (WHO=5)

**Comment by mvalla** [comment]
actually I already assigned this to me as I already made some good progress. As soon as I have time I will publish my draft as a new branch so that you can try it and maybe give a contribution there

**Comment by fabgio** [comment]
Any news?

**Comment by mvalla** [comment]
@fabgio see this branch: https://github.com/mvalla/openhab-addons/tree/openwebnet-alarm
Feel free to test, comment, improve...

**Comment by fabgio** [comment]
OWN4J ver 0.9.1 looks unavaiable so I   downgraded to ver 0.9.0....

**Comment by mvalla** [comment]
you are right, it needs own4j 0.9.1. I have it locally, I will push/publish it this evening

**Comment by mvalla** [comment]
now it's also published on the public repos: https://repo1.maven.org/maven2/io/github/openwebnet4j/openwebnet4j/0.9.1/
