### ISSUE TITLE
[nanoleaf] LayoutTest fails on Windows because of CRLF

### ISSUE THREAD

**Issue by asprom** [openhab/openhab-addons#12562]
The method org.openhab.binding.nanoleaf.internal.model.Layout#getLayoutView() adds System dependent line separators inside the resulting string 
` view += System.lineSeparator();`

which is on Windows environment CRLF

but the unit tests only accepts LF

`String layoutView = layout.getLayoutView();
        assertThat(layoutView, is(equalTo(
                "  186       42064       61141                   45187       33626       10523                   39163 \n"
                        + "                                                                                                      \n"
                        + "19209                   60147       36604       37121                   54086        3512       16398 \n")));`

Therefore, build of that module fails on Windows hosts.

Would suggest to replace the the static LF in the expected test result with `System.lineSeparator()`.

**Comment by wborn** [comment]
I ran into the same issue and already made a fix in #12563. :slightly_smiling_face:
There was a similar issue on Windows in #12564 for which I've proposed a fix.
Maybe there are some more!
