### ISSUE TITLE
[comfoair] serialPort value does not match allowed parameter option

### ISSUE THREAD

**Issue by sim0nx** [openhab/openhab-addons#12575]
Hi,

I have a udev rule to create an alias to the correct usb-serial converter that is used for my "comfoair" device.
Since upgrading to openhab 3.3.0M3, I get an error that I can no longer use such an alias but have to use ttyUSB* ttyS* ttyAMA* only.

As I did not see comfoair in the changelog, I guess this comes from openhab itself.

## Expected Behavior
Having multiple serial converts / ports, it is very useful to be able to create device aliases (e.g. /dev/comfoair) for a specific device one wants to configure for this plugin.

## Current Behavior
Broken since v3.3.0x

## Possible Solution
Allow using arbitrary device names again.

## Steps to Reproduce (for Bugs)
Create a symling to a serial device, e.g. /dev/ttyUSB0 -> /dev/comfoair, and configure that for the plugin.

## Context
Define a fixed device name which otherwise may change on reboots.

## Your Environment
* Version used: v3.3.0M3
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): debian bulls-eye

**Comment by lolodomo** [comment]
I imagine it is fixed by #12572 ? 
Please check with next snapshot that will be built next night.

**Comment by lolodomo** [comment]
Should be fixed by #12572 
Please reopen if it is not the case.

**Comment by sim0nx** [comment]
> Should be fixed by #12572 Please reopen if it is not the case.

 I cannot easily test this but I'll do when there is a new test release as .deb version.
Judging from the discussion and your change I guess this is indeed fixed now.

Thank you for your feedback and fix!
