### ISSUE TITLE
[openhabcloud] Move "Items to Expose" option to advanced settings

### ISSUE THREAD

**Issue by scatterthought** [openhab/openhab-addons#12582]
Although support for IFTTT was removed from myopenHAB.org long ago, there's still an option to expose items in MainUI under the openHab Cloud settings:

![image](https://user-images.githubusercontent.com/47199790/161840202-467f4352-d410-4f7c-b632-c3a52d94edbc.png)

I assume this is to allow people running their own cloud servers to use IFTTT. Unfortunately, it causes confusion for many users who assume it's required for Alexa and Google Assistant integration (which is quite reasonable).

I suggest:

1. Having "Items to expose" only appear when you click "Show advanced".
2. Renaming it "Items to expose to IFTTT"
3. Updating the caption: "If you've set up a private cloud server with IFTTT integration, use this option to indicate which items can be controlled with IFTTT. This setting does not work with myopenHAB.org and is not required for integration with Amazon Alexa or Google Assistant."

Alternatively, we could just remove IFTTT support. However, that would be detrimental to anyone who has set up a cloud server specifically to keep IFTTT working with openHAB.

Thanks for you work!

**Comment by lolodomo** [comment]
@kaikreuzer : as you are referenced as the maintainer for this binding, could you please confirm that support for IFTTT was removed from myopenHAB.org long ago ?
If true, I agree with @scatterthought  and I can propose a PR.

**Comment by kaikreuzer** [comment]
As far as I am aware, yes, IFTTT is still deactivated. But the master here is @digitaldan, so it would be great if he could comment.

**Comment by digitaldan** [comment]
Yeah, i think it would be good to remove references to it and hide the option.  I might also want to update the binding to specifically never send item updates if the configured URL contains myopenhab.org, its a huge amount of data we could do without on the cloud side.
