### ISSUE TITLE
[Sonos] Device Type "Roam SL" is not recognized (invalid Character in Device ID)

### ISSUE THREAD

**Issue by fridomac** [openhab/openhab-addons#12596]
## Expected Behavior
Device is found in a scan and can be added

## Current Behavior
Error in Log:

"java.lang.IllegalArgumentException: ID segment 'Roam SL' contains invalid characters. Each segment of the ID must match the pattern [\w-]*."

Observed in OpenHAB 3.20 Release Version

## Steps to Reproduce

1. Add Sonos Roam SL to Network
2. Error can be seen in Log

## Your Environment
OpenHAB 3.20 Release Version 
Running on a Raspberry Pi4/openhabian

**Comment by lolodomo** [comment]
Ok, I will add support of this new model.

**Comment by fridomac** [comment]
Thank you very much!
