### ISSUE TITLE
[openhabcloud] Image not loading on documentation website

### ISSUE THREAD

**Issue by joepadmiraal** [openhab/openhab-addons#12590]
The openHAB Cloud Connector documentation contains a screenshot of the configuration page.
This image wont load:
![Screenshot from 2022-04-09 12-08-56](https://user-images.githubusercontent.com/1912949/162567379-1af8d480-e29f-4145-91ea-db54f7162007.PNG)

I thought I'd fix that myself, but when looking at the addon repository the image seems to be there already:
https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.io.openhabcloud

So I guess something is going wrong while building the documentation website?

**Comment by wborn** [comment]
It will work better when the image is in the `doc/` dir because suchs dirs are also added to the website.
I've created PR #12591 to fix that.

**Comment by joepadmiraal** [comment]
Cool, should I close this issue?

**Comment by wborn** [comment]
It will be closed automatically when the PR is merged. :slightly_smiling_face:
