### ISSUE TITLE
Velux Binding: Strict validation of serial numbers now requires fake serials for non-Velux devices

### ISSUE THREAD

**Issue by Oggerschummer** [openhab/openhab-addons#12601]
OH3.3 M3 introduced a strict validation of configuration parameters, resulting in the requirement that device serials need to fit into a pattern like e.g. 11:22:33:44:55:66:77:88.
Unfortunately non-Velux devices like Somfy awnings do not report a serial number, so the implemented workaround is to use the name given to the device within the KLF UI as a serial in openHAB.
This no longer works (e.g. "Terrace awning") won't be valid anymore.
The documentation needs to reflect this, a proper workaround now is to set a device name ("fake serial") in the KLF UI that fits the pattern required in openHAB.

**Comment by andrewfg** [comment]
@Oggerschummer many thanks for reporting this. Actually I am not sure if we should change the documentation, or if we should change (relax) the Thing configuration checking code. Maybe we could check if the Thing is either a Velux device (use the validation), or not (skip the validation).

**Comment by andrewfg** [comment]
^
I just checked the ReadMe, quoted below..

> Somfy devices do not provide a valid serial number to the Velux KLF200 gateway. In this case you should enter the default serial number 00:00:00:00:00:00:00:00, and in addition enter the name parameter; this is the name that you gave to the actuator when you first registered it in the KLF200 Bridge.

So, did you try entering '00:00:00:00:00:00:00:00' in the `serial` config param (thus satisfying the validation)? And then also entering the device name in the hub in the (normally optional but in your case not) `name` config param?

**Comment by andrewfg** [comment]
@Oggerschummer 

Yes indeed, the all-zero serial number '00:...:00' is a special marker. If you put that value in the `serial` parameter, the validation checks will pass, but it also makes the binding use the `name` parameter value instead of the `serial` parameter value when it talks to the KLF hub.

Notwithstanding your closing this issue, I will push a change request to the ReadMe documentation, in order to make the above point clearer.
