### ISSUE TITLE
[sonos] Support for Sonos Five should be added

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12610]
Sonos Five is certainly not yet supported by the binding.
Is there someone with such device that could confirm ?

**Comment by clinique** [comment]
> Sonos Five is certainly not yet supported by the binding.
> Is there someone with such device that could confirm ?

I have one. It works but recognized as a zoneplayer

**Comment by lolodomo** [comment]
> I have one. It works but recognized as a zoneplayer

Ok, I will add it.
Can you confirm the value of the tag `modelName` is "Sonos Five" when you open http://xxx.xxx.x.xxx:1400/xml/device_description.xml ?

**Comment by clinique** [comment]
Yes : `<modelName>Sonos Five</modelName>`

**Comment by lolodomo** [comment]
Done. This will give you the additional channel "linein".
