### ISSUE TITLE
[netatmo] Anemometer, Thing Offline, Pending parent object initialization

### ISSUE THREAD

**Issue by ucola** [openhab/openhab-addons#12628]
## Expected Behavior

I have a fresh installation with openHAB 3.2.0. After installation I was adding the Netatmo Binding. Over the Netatmo documentation (https://dev.netatmo.com/apidocumentation/weather) I found out all of my MAC Addresses from my devices. All are working fine (Rain, additional indoor etc.), only the Anemometer is not working. i Always became "Pending parent object initialization".

## Current Behavior

If I edit my "Anemometer" I always see "Pending parent object initialization". If I press pause and then start the Logfile looks like bellow. 
```
[hab.event.ThingStatusInfoChangedEvent] - Thing 'netatmo:NAModule2:cea4ba3f10:5350d44ef7' changed from OFFLINE: Pending parent object initialization to UNINITIALIZED
[hab.event.ThingStatusInfoChangedEvent] - Thing 'netatmo:NAModule2:cea4ba3f10:5350d44ef7' changed from UNINITIALIZED to UNINITIALIZED (DISABLED)
[hab.event.ThingStatusInfoChangedEvent] - Thing 'netatmo:NAModule2:cea4ba3f10:5350d44ef7' changed from UNINITIALIZED (DISABLED) to INITIALIZING
[hab.event.ThingStatusInfoChangedEvent] - Thing 'netatmo:NAModule2:cea4ba3f10:5350d44ef7' changed from INITIALIZING to OFFLINE: Pending parent object initialization
```

## Context

I also delete the device inside my Netatmo app and attached it again, but always the same issue.

## Your Environment

* openHAB 3.2.0
* Ubuntu 20.04
* openjdk version "11.0.14.1" 2022-02-08

**Comment by jlaur** [comment]
This might have been fixed by #12357. The binding has been rewritten, so you might want to give it a try. Please be aware that everything needs to be reconfigured since the bridge and thing structures have changed.

**Comment by ucola** [comment]
@jlaur how can I test the new version or update it?

**Comment by ucola** [comment]
Ok, I have updated to the 3.3 and works fine now...
