### ISSUE TITLE
[doorbird] Daily build failed last night

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12629]
Build failed last night due to doorbird binding and one of its dependency:

[ERROR] Failed to execute goal on project org.openhab.binding.doorbird: Could not resolve dependencies for project org.openhab.addons.bundles:org.openhab.binding.doorbird:jar:3.3.0-SNAPSHOT: Failed to collect dependencies at com.goterl.lazycode:lazysodium-java:jar:4.2.5: Failed to read artifact descriptor for com.goterl.lazycode:lazysodium-java:jar:4.2.5: Could not transfer artifact com.goterl.lazycode:lazysodium-java:pom:4.2.5 from/to openhab-release (https://openhab.jfrog.io/openhab/libs-release): openhab.jfrog.io: Unknown host openhab.jfrog.io -> [Help 1]
[ERROR]

**Comment by lolodomo** [comment]
@mhilbush : any idea?

**Comment by mhilbush** [comment]
Hmm. No idea. Nothing changed to the best of my knowledge.

**Comment by lolodomo** [comment]
@wborn : any idea on your side?
The unknown host is strange?

**Comment by lolodomo** [comment]
Build was ok tho morning.

**Comment by mhilbush** [comment]
That's good. Might've been a temporary DNS lookup issue.
