### ISSUE TITLE
[plugwiseha] Add boiler Return_water_temperature channel

### ISSUE THREAD

**Issue by rdoremalen** [openhab/openhab-addons#12633]
## Your Environment

* Add channel: Boiler --> Return Water Temperature
* Fixed some mistakes in readme

**Comment by lsiepel** [comment]
The issue text looks more or less like a pull request text / changelog. If you have code to share, please create a pull request. If you have trouble to do so, i'm willing to help, just let me know.

**Comment by rdoremalen** [comment]
Yes, you're right, I've got this working at home, but don't know how to get
these changes into a pull request.
If you can help that would be great.

**Comment by lsiepel** [comment]
> e issue text looks more or less like a pull request text / changelog. If you have code to share, please create a pull request. If you have trouble to do so, i'm willing to help, just let me know.

If you find it hard to add a PR with your code, i might do it for you as this is a minor change. Please send me the changes and i will add it.

**Comment by rdoremalen** [comment]
Hi,

I still have no clue how to make these changes into a PR and how that comes to you. Sorry!

I can give you the diff file? And/or also my version of the files that were changed.

[plugwisehaDiff.txt](https://github.com/openhab/openhab-addons/files/10025032/plugwisehaDiff.txt)
[plugwisehaChanges.zip](https://github.com/openhab/openhab-addons/files/10025146/plugwisehaChanges.zip)
