### ISSUE TITLE
[iaqualink] Device with SerialID not connecting

### ISSUE THREAD

**Issue by mdsolutech** [openhab/openhab-addons#12654]
Hello guys!

## Expected Behavior
The device should be "ONLINE".

## Current Behavior
The device is "OFFLINE" with error: "CONFIGURATION_ERROR: No Device for given serialId found".
"log:set DEBUG org.openhab.binding.iaqualink" does not provide any information (no logs).

## Possible Solution
None

## Steps to Reproduce (for Bugs)
1. Connect a controller without SerialID => OK
2. Connect a controller with SerialID => KO

## Context
I am trying to connect to 3 controllers through one account by providing a serial ID in the config or dynamic thing creation.
I am not able to control 2 of my controllers (1 is available by default without specifying serial ID).

## Your Environment
OpenHAB 3.2.0, running on Mac, installed using official installer.

* Version used: OpenHAB 3.2.0, iAqualink 3.2.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome 100.0.4896.88, OpenJDK 11.0.13
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Mac Big Sur 11.6.5

Thanks for the help!

**Comment by digitaldan** [comment]
Hi, so yeah i put in the code to support multiple pools a while ago in anticipation of it being needed, but don't use  it personally .  I'm not sure if it ever worked, or likely the api changed slightly which broke how we search for serial ids ( i assumed i tested it).   

I have an updated jar at https://github.com/digitaldan/openhab-addons/releases/download/iaqualink-serialid-fix/org.openhab.binding.iaqualink-3.3.0-SNAPSHOT.jar   if you want to give it a try.  You can either drop this in your addons folder (remove the old binding first) or download it somewhere on your openhab box and udpate the binding in place using the openHAB CLI with the command:

`bundle:update org.openhab.binding.iaqualink file:////tmp/userdata/org.openhab.binding.iaqualink-3.3.0-SNAPSHOT.jar` 
assuming you put it in the `/tmp` folder

**Comment by mdsolutech** [comment]
Damn you're good!

That works perfectly!

I normally use the addons.cfg file for installing the bindings I need.
How does the release of this 3.3.0 works? When will it be installed/updated directly from the addons.cfg file?

Thank you very much for your quick reply and fix!

**Comment by digitaldan** [comment]
I'll submit a PR probably tonight or tomorrow, and it will be available in the nightly builds shortly, as well as any future milestone releases and official releases.
