### ISSUE TITLE
[goecharger] Not working after #12400

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-addons#12661]
As pointed out from several people (see below), the newly introduced category Temperature seems to cause the binding to malfunction.

Best description seems to be done by kreutzer_peter in the community forum (see https://community.openhab.org/t/go-e-charger-wallbox-binding/93338/99)
```
21:08:30.073 [WARN ] [fig.xml.osgi.XmlDocumentBundleTracker] - The XML document '/OH-INF/thing/thing-types.xml' in module 'org.openhab.binding.goecharger' could not be parsed: The document is invalid, it contains further unsupported data: [NodeValue [nodeName=category, value=Temperature]]!
---- Debugging information ----
message             : The document is invalid, it contains further unsupported data: [NodeValue [nodeName=category, value=Temperature]]!
class               : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
required-type       : org.openhab.core.thing.xml.internal.ChannelTypeXmlResult
converter-type      : org.openhab.core.thing.xml.internal.ChannelTypeConverter
path                : /thing-descriptions/channel-type[22]
line number         : 209
class[1]            : java.util.ArrayList
required-type[1]    : java.util.ArrayList
converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
class[2]            : org.openhab.core.thing.xml.internal.ThingDescriptionList
required-type[2]    : org.openhab.core.thing.xml.internal.ThingDescriptionList
converter-type[2]   : org.openhab.core.thing.xml.internal.ThingDescriptionConverter
version             : 1.4.19
```

Introduced with #12400, this seem to be the source of the problem:
https://github.com/openhab/openhab-addons/blob/ba03fef082502c38fd89717c17ddd10777cf1189/bundles/org.openhab.binding.goecharger/src/main/resources/OH-INF/thing/thing-types.xml#L208

@ranzen84, maybe you may take a look at this? Would be great to use the binding with your additions :-)

Cheers,
Sascha

**Comment by niklas85** [comment]
Unfortunately the same error is also in "openHAB 3.3.0 Milestone 4"... A fix would be great!

**Comment by ranzen84** [comment]
Havn't had the issue while developing. But I have created a PR to hopefully fix the issue: https://github.com/openhab/openhab-addons/pull/12682
