### ISSUE TITLE
[homekit] IOS app OK,  control center accessory is dead

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-addons#12672]
favorite accessories in control center are often frozen, but if you go to home app they are working ok. 

Steps to reproduce: 

1/ .items metadata config : sometimes wrong config hangs ios app and control  center - both in the same time.

2/ Config ok items are working from IOS app

3/ Some of items are not working (from control center ) but working from IOS APP 

How to solve this issue: 
4/ remove accesory from "Favorites" and and it again. It will unfreez not only this accesory but also others with are hanging in control center
5/ sometimes it helps going to Settings-> Control Center -> Show home controls - and turn it off and on again

at the same time on other iOS phone everythink is OK (both app and control center) 

short movie explaining steps 1-3 : 
https://drive.google.com/file/d/1S07kgBgIRkTdJTqF3mH32W1gHrmeHR-v/view?usp=sharing

any idea if we can fix it by openhab site?

**Comment by JacekKac** [comment]
not much i think, but its kind of development system, so i am still changing the items config and often generating new item config - dont know if this is helpful


openhab> openhab:homekit list
874514676 Zraszacz 3
1743619906 Wilgotnosc
874514677 Zraszacz 4
1476267153 AktualnaTemperaturaP
344188245 Wilgotnosc
14912315 null
704059656 AktualnaTemperatura
625599125 Lampa 5
625599124 Lampa 4
1686384380 AktualnaTemperatura
1736869226 Wilgotnosc
1184241368 Podlewanie auto
1702394975 Wilgotnosc
625599121 Lampa 1
625599123 Lampa 3
46730900 AktualnaTemperatura
625599122 Lampa 2
1355133068 Domofon
874514674 Zraszacz 1
312438165 Podlej jednorazowo
874514675 Zraszacz 2

**Comment by yfre** [comment]
it is indeed not much. i have 100+ items and pretty smooth experience with control center
one thing you should try - if you have any homekit bridges (ipad, apple tv, homepod), try to disable them.

**Comment by yfre** [comment]
@JacekKac im checking the still open homekit issue. 
do you still have this issue? 

if yes, i saw in your list of accessories above that one "14912315 null"
this could lead to issue in home app. please add name/label to that openHAB item and try one more time.

if you dont have this issue anymore, please close this ticket
