### ISSUE TITLE
[netatmo] Deprecated Authentication Methods 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#12677]
@clinique @cweitkamp @lolodomo you are listed as the CODEOWNER for netamo, the openHAB foundation info email account received an email from Netamo that we using a deprecated authentication method that is being disabled. Let me know if you want me to forward the full email.    Thanks. 

------------------------------
Dear Sir/Madam,

I am Romain, API product Manager at Netatmo.

I have some important API updates coming and would like to give you some information.

Client Credentials

To improve the security of our products, we inform you that the Client Credentials Authentication method will soon be completely removed.

It will no longer be possible to authenticate the users with their username and password.

Only the Authorization Code Grant Method (often referred as OAuth2 method) will be available.

The target date for this change is 01/09/2022.

Unfortunately, we noticed you were still using that Authentication method.

How can you authenticate with Netatmo API ?

The OAuth2 authorization standard must be followed for authentication.

You can find details on this method on our website:  [Netatmo Connect | Authentication](https://dev.netatmo.com/apidocumentation/oauth#authorization-code)

**Comment by lolodomo** [comment]
To be confirmed by @clinique , I hope the rewritten binding that should be merged next weekend has the new authentication methid implemented.

**Comment by clinique** [comment]
> To be confirmed by @clinique , I hope the rewritten binding that should be merged next weekend (intensive working in progress - review & fix) has the new authentication method implemented. 

I do also think so but will check.

**Comment by clinique** [comment]
Well, reading it twice, it's not that clear. In my undestanding, they are deprecating "Client Credential Autentication" while the two current bindings use "Client credentials grant type". @digitaldan , if you can forward the full mail it may help me understand if we've got a real issue.

**Comment by digitaldan** [comment]
Just forwarded their email to you.

**Comment by clinique** [comment]
Message sent to Romain to get clarifications on the perimeter of the change.

**Comment by clinique** [comment]
Confirmation received : the only method left from September first will be the Code Grant Method. So I will have to adapt accordingly the ongoing PR.

**Comment by lolodomo** [comment]
@clinique : to not delay the ongoing PR, I propose that you implement the new authentication method in a next PR. WDYT ?

**Comment by clinique** [comment]
Closed via PR #12726
