### ISSUE TITLE
[jsscripting] Directory permissions for $OPENHAB_CONF/automation/js

### ISSUE THREAD

**Issue by DavidR1953** [openhab/openhab-addons#12692]
Expected Behavior
VS-Code users should be able to create files.

Current Behavior
When the JavaScript Scripting add-on is installed it creates the directory $OPENHAB_CONF/automation/js with permissions 755
VSCode users of the default openhabian installed setup cannot write to this directory because the user is openhabian, not openhab.

Possible Solution
Create the directory with 775 permissions
This will allow openhab group members write permissions.

Steps to Reproduce (for Bugs)
Context
Your Environment
Version used: openHAB 3.3.0.M4 and JS Scripting add-on 3.3.0.M4
Environment name and version : Java 11
Operating System and version: Raspbian Buster on RPI4, openhabian

**Comment by florian-h05** [comment]
@DavidR1953 Does this issue still persist?

**Comment by DavidR1953** [comment]
Well I guess it does if nothing has been done to correct it. I would have to completely uninstall jsscripting and reinstall to find out. I could check the code, but I'm not familiar, so it will take a while....

**Comment by florian-h05** [comment]
I’ll check, I have a dev system where I can easily reinstall openHAB to check this.

**Comment by florian-h05** [comment]
Can you please upgrade to the 3.4.0 Release Build and the latest openHABian and then use the openhabian-config tool -> Apply Inprovements -> Fix permissions.

We cannot and IMO should not change the chmod number when creating the JS Scripting folders. 
If the above doesn’t work, I’d rather recommend to modify the user/group configuration.

**Comment by DavidR1953** [comment]
That's a better solution. Using Fix permissions works.

**Comment by florian-h05** [comment]
Okay great, then it we don’t need to change something anywhere. I’ll close this.
