### ISSUE TITLE
[kostalinverter] Channel type id "deviceLocalDCPower" has incorrect data when battery charging

### ISSUE THREAD

**Issue by metkdede** [openhab/openhab-addons#12718]
## Expected Behavior
The channel type id "deviceLocalDCPower" on a 3rd generation device, like for me the PLENTICORE 5.5 w/ battery, shall reflect the total power from the generator side. This would mean that the power of all three inputs of the inverter shall be summarised. At least this shall be the case on inverters without a battery. In my opinion, and how I understand the documentation of this add-on, there shall be a special case for the use of batteries. What we would like to see is the power from the generator (the cells on the roof and not the battery).
Typically I would expect from the add-on with battery is that the Channel type id "deviceLocalDCPower" is the sum of only input 1 and input 2, but not input 3 (this is the battery).

## Current Behavior
What is currently shown by the add-on on this cannel type id is the summ of all three inputs, which means if the battery is charged, than this value will be subtracted. So the value we see, is not what is currently generated by the cells on the roof. We would need to add the inverted power of input 3 to deviceLocalDCPower to have a correction.

## Possible Solution
Check the source code for 3rd gen with battery inverters and sum only DC input 1 and DC input 2.

## Steps to Reproduce (for Bugs)
Issue is present at all time.

## Your Environment
Kostal Plenticore Plus 5.5
Kostal Inverter Binding 3.2.0
Openhab 3.2.0

**Comment by MarkusThur** [comment]
Are you sure, this is a sum done by the plugin.. Didn't look closer in it, but I'd guess this is just the representation of a field in the Interface of the inverter. Am pretty sure, that the field devicelocalDCPower represents the sum of the DCPower of all three inputs. And for me this makes sense, especially as it is in principle unknown, if on input three there is a battery or a third group of panels..
As well as the device total DC Power with a battery is: I1 + I2 - I3 if Battery is charging and I1 + I2 + I3 if Battery is uncharging.

If u want to know the total aviable DC Power from solar panels, you just could sum up I1 and I2.
