### ISSUE TITLE
[deconz] Sensor data updated infrequently

### ISSUE THREAD

**Issue by hutdev** [openhab/openhab-addons#12730]
## Expected Behavior
Please note that this did work for more than a year until two days ago. I use Raspbee II and Deconz to manage Hue motion sensors and Hue dimmable lights. I use OpenHAB rules to light up the lights if the motion sensors detect (A) a motion and (B) illuminance of less than 1 lux. OpenHAB is supposed to receive timely updates of illuminance data from the sensors.

## Current Behavior
The lights don't light up anymore. Using the Phoscon Web App I can see movement and plausible illuminance data for the motion sensors and I can enable the lights. OpenHAB on the other hand shows wrong or old illuminance data. E. g. OpenHAB displays 40 lx for a hallway that has been pitch black for the last half hour. OpenHAB Log does not  show any errors unfortunately.

## Possible Solution
I updated the deconz software recently and I suspect the addon does not work correctly with the latest deconz software release because everything worked fine up until that point.

## Steps to Reproduce (for Bugs)
1. Configure Hue Motion Sensor in Deconz / Phoscon Web App
2.  Link lightlux channel of the sensor to an OpenHAB item
3.  Change light around the sensor and observe a change of the illuminance in the Phoscon Web App but none in the OpenHAB interface

## Context
Cf. "Expected Behavior"

## Your Environment

* Version used: OpenHAB 3.1.1, Deconz Addon 3.1.1, Deconz 2.15.03
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian Buster (OpenHAB and Deconz / Raspbee share the same system)

**Comment by jlaur** [comment]
It looks like this could be the cause of it: dresden-elektronik/deconz-rest-plugin#6041. There is also an open PR with a fix: dresden-elektronik/deconz-rest-plugin#6052. If you agree, please close this issue.

**Comment by hutdev** [comment]
Yes, I'm pretty sure that's the issue here. Thanks a lot for the quick response.
