### ISSUE TITLE
[astro] `EVENING_NIGHT` and `MORNING_NIGHT` are `undef`

### ISSUE THREAD

**Issue by ThaDaVos** [openhab/openhab-addons#12746]
## Expected Behavior

Them to not be `undef` so they can be relied on in Time of Day situations, like I used to use them for in combination with motion sensors to trigger lights

## Current Behavior

Currently they show as `undef` which breaks my `Time of Day` system, after looking through all other states, there's none I can really use to determine the start of the evening correctly, see below for the `MORNING_NIGHT` and `EVENING_NIGHT`:
![image](https://user-images.githubusercontent.com/5251028/168542708-c86d091c-4f6a-42f7-8167-a05e93eeec04.png)

## Possible Solution

Can this be fixed? Or perhaps a workaround and reason given to why they are `undef`?

## Steps to Reproduce (for Bugs)

1. Sorry don't know, they are just `undef` randomly on 16th of May 2022 (the day I noticed they were)

## Context

I was using them for the Marketplace Time of Day rule to keep an up to date status of the Time of Day, currently used for motion sensors and lights

## Your Environment

* Version used: 3.3.0.M3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Openhabian
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian

**Comment by lsiepel** [comment]
Currently investigating similar issues in https://github.com/openhab/openhab-addons/pull/14078
Can you give me the following details?
long/lat/altitude/timezone of openhab/server   (if you don't feel comfortable with giving those, please DM me details.

**Comment by ThaDaVos** [comment]
@lsiepel - I created a paste for you with the data - the password is your username (as written in the @...) - know the paste is burned after reading:
https://pastebin.com/BpP0L8yN

**Comment by ThaDaVos** [comment]
Also @lsiepel I checked and they are no longer `UNDEF` at the moment

**Comment by lsiepel** [comment]
Thanks, will try to reproduce with the details you provided.

**Comment by lsiepel** [comment]
Undef is not something i would expect. But  i have seen strange behaviour when troubleshooting this and other tickets all around  12-22 may. It has to do with some inner lists of sun phases that did not get any sorting. Aftwarewards i have made several tess with the parameters you gave and i have not found any issue again.
