### ISSUE TITLE
[netatmo] Requesting favorite stations only when needed

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12769]
I have not enabled favorite stations:
![image](https://user-images.githubusercontent.com/10186704/169535212-81c1cdfc-1080-43a0-ba3f-418c5d8125ff.png)

But the binding requests favorite data anyway:
```
15:04:30.993 [TRACE] [tmo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/getstationsdata?device_id=xxx&get_favorites=true
```

This is probably triggered at this line with the second parameter set to true:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/WeatherApi.java#L66

It could (should) be optimized to use false when getStationData is called for your local weather station.

@clinique  : WDYT ?

**Comment by lolodomo** [comment]
I think I know how to enhance that, I will submit a PR after testing.

**Comment by clinique** [comment]
You're welcome, I've got many plates on the fire :)

**Comment by jlaur** [comment]
@lolodomo - can you remind me how to access binding configuration from MainUI when installed as JAR?

**Comment by lolodomo** [comment]
You click "+" to add new thing and then in the "Choose binding" you have a special icon on "Netatmo Binding" to access its configuration.
