### ISSUE TITLE
[miio] Support for Dreame L10 Pro

### ISSUE THREAD

**Issue by leifbladt** [openhab/openhab-addons#12762]
I have an unsupported Dreame L10 Pro vacuum cleaner und would love to see it supported in OpenHAB.

Currently I'm running OpenHAB 3.2.0 and I created a device testing file via the channel "(experimental) Create experimental support for new MIOT protocol devices".

I hope this helps to move forward. Is there anything else I can do?

[test-dreame.vacuum.p2029-20220518-205907.txt](https://github.com/openhab/openhab-addons/files/8750266/test-dreame.vacuum.p2029-20220518-205907.txt)

**Comment by marcelrv** [comment]
If things went right, you can now see all the channels for your device.
Based on the responses seems all of the request for properties returned values

Can you also confirm that the actions are working or at least the essential ones like start/stopping the cleaning)

**Comment by j0yze** [comment]
Thank you for creating this thread.
I can confirm the following actions at the moment:
- **vacuum-start-sweep** -> start cleaning
- **vacuum-stop-sweeping** -> pause cleaning
- **battery-start-charge** -> stop cleaning and send the robot back to recharge station

Is it already possible to start cleaning a specific room?

**Comment by leifbladt** [comment]
I also did some tests, I can confirm that the basic functions (vacuum-start-sweep, vacuum-stop-sweeping, battery-start-charge, audio locate) are working.

The values for the consumables are working and showing the correct values (compared to the app): Main Cleaning Brush, Side Cleaning Brush, and Filter. Only the sensors there are noch channels.

The basic information channels are working (battery, status, clean logs).

The only minor issue I found is, that "Vacuum Extend - Mop Mode" is not localized but shows in chinese characters

**Comment by marcelrv** [comment]
The spec typically had mix of English and mandarin. (Translation is done by the app)

You can edit the JSON file and update values.
I mostly use Google translate for it

**Comment by leifbladt** [comment]
Hi @marcelrv 
I updated the JSON file and translated the Chinese descriptions (with the help of Google Translate and the already existing p2028 file).

How can we proceed from here? Should I try to prepare a PR? And if so, is there a way to generate the relevant information for the README?
