### ISSUE TITLE
[fineoffsetweatherstation] Add support for ELV WS980WiFi

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12763]
#12464 introduces a new generic binding supporting white-labeled weather stations manufactured by [Fine Offset](http://www.foshk.com/), but rebranded by many companies.

Recently #12731 was also published, supporting a specific German-branded weather station, [ELV WS980WiFi](https://de.elv.com/elv-wifi-wetterstation-ws980wifi-inkl-funk-aussensensor-868-mhz-app-pc-auswertesoftware-250408)

A [sharp eye](@Hilbrand) detected that actually this [WS980WiFi weather station is one of those rebranded Fine Offset weather stations](https://github.com/openhab/openhab-addons/pull/12731#discussion_r874617259), WH2350:

![image](https://user-images.githubusercontent.com/19519842/168894429-11c48ae9-12fa-41b3-800d-5d5face3e55e.png)

@Andy2003 has offered to try to add support for the WS980WiFi in the Fine Offset binding when receiving some response payloads from @prof2004.

**Comment by Andy2003** [comment]
I'm starting to implement this protocol, @jlaur can you assign me to this issue please

**Comment by Andy2003** [comment]
Since I don't own the WS980 I need some support from someone owning such device (cc: @prof2004).

Can someone intercept the traffic between the App (used to display the data) and the WS980 to provide me with some data.

Here is a [small example of how this can be achieved with Java](https://community.openhab.org/t/fine-offset-weather-station-binding-beta-and-discussion/134167/47?u=andy2003).

I am especially interested in the call that reads out all the available sensors (in the original protocol this is the [Command 0x3C](https://github.com/Andy2003/openhab2-addons/blob/a9b11a7c330aafc06061c44eb4e1c12b5efed40d/bundles/org.openhab.binding.fineoffsetweatherstation/src/main/java/org/openhab/binding/fineoffsetweatherstation/internal/domain/Command.java#L194-L197)).

**Comment by Andy2003** [comment]
Discussion about the protocol: https://de.elv.com/forum/protokolldefinition-zum-datenaustausch-ws980-zum-pc-6430?p=2t
The protocol: https://github.com/RrPt/WS980/tree/master/Dokumentation

**Comment by jlaur** [comment]
@Andy2003, @prof2004 - any news on this? @Andy2003, I was wondering if you are still working on this, and if you received the needed information? Otherwise, @prof2004, perhaps you would like to extend the Fine Offset Weather Station Binding with support for the ELV WS980WiFi, since you already implemented the protocol once, and have the device at hand for testing it?

**Comment by Andy2003** [comment]
No, unfortunately I have not received any feedback yet. I have already implemented the protocol locally, but I am still missing some information.

see https://github.com/openhab/openhab-addons/issues/12763#issuecomment-1131532798

**Comment by prof2004** [comment]
I have tried the code fragment "Proxy" from Andy2003, without success. The name of the weatherstation, and the version of the firmeware is already extracted in my code and displayed in the property "description". Andy2003 has requested the results of 3 other calls: 

1. the query of all sensors (0x3c)
2. the query of the firemware version (0x50)
3. the query of the system information (0x30)

These are not valid calls. The calls are starting with 0xff 0xff call (e.g. 50 for version request) plus 2 or 3 additional bytes. Pls see the document from R. Petzoldt. Pls provide the correct call parameters, and I will excecute the calls in my environment.

This document also explains, how to build the check sum under point 1.15.

The excecution of the call for the actual data from the ws980 gets this result in hex:
FFFF0B00500401010B0201120300620401120501120629072108254B09254B0A01480B00040C000A0E000000001000000021110000002E120000014F130000100714000012FD15000B4BB816086917056D35
The last 2 bytes are the CRC1 and CRC2.

Translated into values the result is:
Innentemp.: 26.0
Aussentemp.: 27.0
Taupunkt: 9.0
gefühlte Temp.: 27.0
HitzeIndex: 27.0
InnenFeuchte: 41.0
AussenFeuchte: 33.0
abs. Druck: 954.0
rel. Druck: 954.0
Windrichtung: 328.0
Windgeschwindigkeit: 0.0
Wind Boe: 1.0
Regen h: 0.0
Regen t: 3.0
Regen w: 4.0
Regen m: 33.0
Regen j: 410.0
Regen gesamt: 486.0
Lichtstärke: 74028.0
UV Stärke: 2153.0
UV Index: 5.0
CRC1: 6D
CRC2: 35

@Andy2003: If you are in Germany, it may be easier to get on a phone call to answer your questions, may be in German :-)

**Comment by prof2004** [comment]
Andy,
The request and Analystin the answer from the station is fully implemented
in my binding, class WS980WiFi.java. It is the easiest way to use it for
your binding

Regards
Jörg

Andreas Berger ***@***.***> schrieb am Do., 19. Mai 2022,
12:44:
