### ISSUE TITLE
[Netatmo] Problem during update of 'room' thing

### ISSUE THREAD

**Issue by RickyTR** [openhab/openhab-addons#12764]
## Current Behavior
At every refresh the room thing goes offline and then online again. Channels are updated correctly.

`2022-05-19 10:27:58.038 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxx:xxxxxx:xxxxxx' changed from ONLINE to OFFLINE: Thing is not reachable

2022-05-19 10:27:58.269 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxx:xxxxxx:xxxxxx' changed from OFFLINE: Thing is not reachable to ONLINE`

Every other thing of the binding updates correctly without problems

## Your Environment
Version used: Openhab 3.3 M5
Default Netatmo binding for 3.3 M5 distribuition (3.3.0.M5)

**Comment by jlaur** [comment]
@clinique, @lolodomo - FYI.

**Comment by lolodomo** [comment]
I believe TRACE logs around the moment when the two events are produced could help to understand what is happening. It will show the different requests and what is returned by Netatmo.
So please enable temporarily the TRACE logs and just wait for the next poll: log:set TRACE org.openhab.binding.netatmo
PS: Before publishing these logs here, replace the few ids identifying your products with "xxx".

**Comment by RickyTR** [comment]
I enabled TRACE logs and I can see a lot of calls from the ApiBridgeHandler but it seems that every call is correctly completed:

executeUri returned : code [200 OK]

I cannot see any error before the switch OFFLINE/ONLINE of the room thing...

**Comment by lolodomo** [comment]
This is not a surprise that requests are succeeding. 
The question is more what data they return and in particular the reachable field.

**Comment by RickyTR** [comment]
Is there something in particular to look for?

**Comment by clinique** [comment]
@RickyTR : don't bother, I'll have a look at it soon. As @lolodomo said, we've got a good idea at what to look for.

**Comment by clinique** [comment]
Well, the weird thing is that I do not reproduce at all. My rooms are remarquably stuck ONLINE without flapping :-/

**Comment by RickyTR** [comment]
May be the problem is related to channels? I use Indoor temp, Setpoint and Thermostat mode…

**Comment by clinique** [comment]
Non, the status is disconnected from channels.

**Comment by robnielsen** [comment]
>Non, the status is disconnected from channels. Maybe we can ask @robnielsen if he observes this also ? He uses the energy side of Netatmo devices.

Sorry, I only have weather devices.

**Comment by clinique** [comment]
> > Non, the status is disconnected from channels. Maybe we can ask @robnielsen if he observes this also ? He uses the energy side of Netatmo devices.
> 
> Sorry, I only have weather devices.

Sorry, I thought to @mdillman

**Comment by clinique** [comment]
@mdillmann : do you experiment the same behaviour ?

**Comment by lolodomo** [comment]
@clinique : this looks to me similar to the problem we already got with a capability setting the status to X and another capability setting it to Y.

**Comment by clinique** [comment]
Yes, this was my first thought but from source standpoint it is already adressed.

**Comment by lolodomo** [comment]
> Yes, this was my first thought but from source standpoint it is already adressed.

If you change the ID of the second level bridge (home, weather station), I have a big doubt that the discovered things at the third level (camera, person, weather modules) will have the correct bridge UID. We are in this case in the same issue as for the unmanaged things. But I will also test it.

I think the solution is relatively simple: try to find amongst the children of the account bridge the thing matching the bridge. If found, we use its UID as bridge UID; if not, we build the default bridge UID (your current code).

**Comment by mdillmann** [comment]
> 

I did not have the time to do proper testing during the last weeks. 
I hope I can spend some time mid next week

**Comment by RickyTR** [comment]
Just a small update. After the upgrade to M6 I have the same problem also on person things.

**Comment by RickyTR** [comment]
After update to M7 I still have the same problem but with a different behaviour: the room things usually stays offline and goes online only during the update.

**Comment by lolodomo** [comment]
Why not providing trace logs so that @clinique could analyze?

**Comment by RickyTR** [comment]
@lolodomo I already tried to enable log trace but it showed nothing interested so @clinique told me he already has an idea of the problem... Let me know if you need something specific.

**Comment by RickyTR** [comment]
Hi @clinique any news on this problem?

**Comment by clinique** [comment]
> Hi @clinique any news on this problem?

Nobody's able to reproduce as far as I know

**Comment by RickyTR** [comment]
If you tell me what I can do I'll try to help solve the problem. With the latest release the person thing stays offline and it's impossible to send commands...

**Comment by mdillmann** [comment]
No flapping observed here (OH 3.3 stable and OH 3.4M2). Room is online (besides if there is a roomaction defined; I created a separte report for this).

**Comment by lolodomo** [comment]
@clinique : could this issue has been fixed by #13467 ?

**Comment by clinique** [comment]
It can help, but not 100% sure as I did not face this issue and was not able to reproduce.Maybe @RickyTR can tell ?

**Comment by RickyTR** [comment]
If you tell me where I can find the updated JAR I’ll test it and let you if it’s fixed. Thanks a lot.

**Comment by lolodomo** [comment]
You can try OH snapshot 3111 which includes the change.

**Comment by lolodomo** [comment]
Or you can download the binding jar file here: https://ci.openhab.org/job/openHAB-Addons/ws/bundles/org.openhab.binding.netatmo/target/org.openhab.binding.netatmo-3.4.0-SNAPSHOT.jar

**Comment by RickyTR** [comment]
I tried the new jar but I still have the same problem. I can add that the problem seems related to the fact that I have room things and person things (connected to welcome camera) because I have the same problem with both type of things (the online/offline status changes at every refresh) but it seems that when the room things stays online after the refresh person things stays offline and vice versa. This behaviour can change after the restart of openhab.

**Comment by lolodomo** [comment]
But can you be more precise on the OFFLINE status ? Is it a COMMUNICATION_ERROR ? What détailed message ? Is the bridge thing switching to OFFLINE too ?
Can you please show your corresponding lines in events.log when it happens. Then we will have immediately these informations and it could help.

PS: there is not a lot of places in the code when the thing status is switched to OFFLINE.

**Comment by RickyTR** [comment]
This is what's happening at every refresh:

`2022-10-05 19:46:35.518 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxxxxxx:5996b0aef5459584778b489c:1778213671' changed from OFFLINE: Thing is not reachable to ONLINE
2022-10-05 19:46:35.527 [hingStatusInfoChangedEvent] - Thing 'netatmo:person:xxxxxxxxxx:5996b0aef5459584778b489c:1fbad5cf2c2043ac8a918f5911c10acc' changed from OFFLINE: Thing is not reachable to ONLINE
2022-10-05 19:46:35.535 [hingStatusInfoChangedEvent] - Thing 'netatmo:person:xxxxxxxxxx:5996b0aef5459584778b489c:d57caa5b1bd745dab9089e519bddab63' changed from OFFLINE: Thing is not reachable to ONLINE
2022-10-05 19:46:35.543 [hingStatusInfoChangedEvent] - Thing 'netatmo:person:xxxxxxxxxx:5996b0aef5459584778b489c:de03d8193e3348e1a80c6d443a99c384' changed from OFFLINE: Thing is not reachable to ONLINE
2022-10-05 19:46:35.545 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxxxxxx:5996b0aef5459584778b489c:889776478' changed from ONLINE to OFFLINE: Thing is not reachable
2022-10-05 19:46:35.641 [hingStatusInfoChangedEvent] - Thing 'netatmo:room:xxxxxxxxxx:5996b0aef5459584778b489c:1778213671' changed from ONLINE to OFFLINE: Thing is not reachable`

Only this things switches at every refresh. The bridge never swithes nor the other type of things (Home, thermostat, plug, welcome). As you can see room things switches from OFFLINE to ONLINE and then immediately back OFFLINE and then stays OFFLINE until the next refresh. The person things switches from ONLINE to OFFLINE and then back ONLINE until the next refresh. Datas for the room things are updated at every refresh in the short time period that stays ONLINE. Sometimes after a restart  of OPENHAB this behaviour is switched between room things and person things (so basically the first stays ONLINE between every refresh and person things stays OFFLINE).

**Comment by lolodomo** [comment]
@clinique: I guess this is this line which sets the thing OFFLINE; finalReason has value "Thing is not reachable".
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/CommonInterface.java#L161

**Comment by lolodomo** [comment]
This is setthere:
https://github.com/openhab/openhab-addons/blob/a1a02f05bfb5b050d7f0579a4cb638bf913ec7ee/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/capability/Capability.java#L120
One of the devices/modules is reported/considered as unreachable.

**Comment by RickyTR** [comment]
Hi @lolodomo. I tried the updated binding included in 3.4 but the problem is still there. Any news on this?

**Comment by clinique** [comment]
@RickyTR : I think I have a serious track. Would you share your home things definitions ?

**Comment by RickyTR** [comment]
@clinique sure. Can you tell me exactly what you need? I'm not using text file defintion for things....

**Comment by lolodomo** [comment]
@RickyTR : there was a new PR just merged that could have fixed your problem. Don't hesitate to give a feedback (fix will be included in next snapshot tomorrow).

**Comment by RickyTR** [comment]
Hi @lolodomo, I tried to install the latest jar (4.0.0 Snapshot) but on my 3.4 installation it tells me that it needs com.google.gson version 2.9.0 or 3.0.0. Is there a way to test the binding in OG 3.4?

**Comment by clinique** [comment]
No, unfortunately you can not back-port it.
