### ISSUE TITLE
[tado] String values for new channels should not be hard coded

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#12789]
Support for new `light`, `fanLevel`, `verticalSwing`, `horizontalSwing` channels was added in #12470. But there were some bugs in that PR which will have been solved as part of #12570.

However during testing of #12570 it became clear that the string values provided via the Rest API for these channels are not limited to a set of predefined strings, and can in fact be **_any_** string value, depending on the make and model of AC unit being controlled.

Currently these channels are hard coded in the binding as Java Enums which by definition match only a fixed set of string values. This means that the current code will fail if it encounters AC units which provide string values that have not yet been forseen in the hard coded Enum strings.

In a future PR I intend to refactor the binding code for channel values from hard coded Enums to `List<String>` instead. The hard coded state descriptions in the channel xml definitions will also have to be removed, and replaced by the (already coded) dynamic state descriptions.

**Comment by andrewfg** [comment]
Just to put on record that since #16836 it would now be possible to modify the DTO classes to handle soft coded state values.

**Comment by lsiepel** [comment]
I have the impression that it is not _that_ dynamical/happen often, so i wonder if and how you want to proceed. 

1. Implementing a channel configuration that can override the string. Nice, works by default an whenever this hapens the user can (with some support) fix it right away.
2. Provide some file/storage with a keyvalue pair, simialar to above, just a different implementation. Similar advantage, but also uncommen and harder to maintain?!
3. Leave the string handling up to the contributer/codeowner/maintainers of the binding. Less error prone, central fix, but slower from request to fix. (while backporting reduces this, but still)

Do you see other posibilities?

**Comment by andrewfg** [comment]
@lsiepel the manufacturer seems not to introduce any new products that go beyond the existing API. So I suggest to go for your option 3 above. In which case we can close this issue as "won't fix" .. for the time being at least..

**Comment by lsiepel** [comment]
Thanks!

**Comment by lsiepel** [comment]
Thanks,
