### ISSUE TITLE
[myBMW] Provide 'DistanceFromHome' channel

### ISSUE THREAD

**Issue by martingruening** [openhab/openhab-addons#12783]
It would be super helpful to have a computed 'DistanceFromHome' (measured in Meters) channel for every vehicle. This channel should compute the distance between the OpenHAB location (as defined under Regional Settings in the system settings) and the location of the vehicle. It should update every time the vehicle location changes.

There is a methode on LocationItem objects to compute the distance between two LocationItem objects, so the distance computation code is already there.

This would be super cool for some specific use cases. For example, I could trigger a notification if my car (PHEV) is at home (DistanceFromHome <100m), the charging cable is not connected and the battery level is below 50%. This notification should not trigger when the DistanceFromHome is >100m which means I am on a roadtrip.

@weymann

**Comment by BigGeorgeTx** [comment]
This is a great idea, and for more than just vehicles.  Anything that provides location information could benefit from such a channel.  I use the iCloud binding for iPhone locations and calculate the distance from in a rule, but a channel would be cleaner.

**Comment by jlaur** [comment]
Perhaps it would make more sense to calculate the distance in a rule instead of providing redundant channels for all bindings with such a need?

**Comment by weymann** [comment]
This is a quite nice use case. I implemented it on my side in a rule and here are my thoughts.

```
rule "Distance from Home"
	when
            System started or
            Item MyBMWi394REX_Koordinaten changed
	then
            val home = new PointType("1.234,9.876")
            if( home.distanceFrom((MyBMWi394REX_Koordinaten.state as PointType)) > 100) {
                logInfo("Home Location","Vehicle on the road")
            } else {
                logInfo("Home Location","Vehicle at home")
            }
end
```

I fear @openhab/maintainers will refuse this request because this data isn't provided by the Vehicle Thing itsself, it needs to be combined with the location from system settings and this shall be done in rules.

But I guess you raised this request because there's no way in a rule to get the location settings from openHAB configuration. You need to maintain your own _Home LocationItem_ or hard code the _Home PointType_ as shown in the rule above. This isn't convenient and it was already addressed here https://github.com/openhab/openhab-addons/issues/10163. Seems the request wasn't followed up. With this you would end up in a nice one-liner in the if condition and you're done.

**Comment by jlaur** [comment]
@weymann - good idea to be able to get location configuration from rules. Can you create an issue in openhab-core describing this idea and use-case? This would be an elegant solution to the problem.

**Comment by weymann** [comment]
Request was already raised one year ago. I put an additional comment to show this is still a valid request.
https://github.com/openhab/openhab-core/issues/2211#issuecomment-1151510304

**Comment by martingruening** [comment]
Thanks for the feedback. As I am moving away from Rule DSL to JSR223 rules I have created this rule

```
itemHome = new PointType("52.165108, 8.036689");
item = ir.getItem("BMW530exDrive_Koordinaten");
distance = itemHome.distanceFrom(item.state);
events.postUpdate("BMW530exDrive_DistHome", distance);
```

I think it is very reasonable to provide a channel that provides a computed value. Otherwise lots of users will use precious time to reinvent the same rule logic over and over again. Does not make sense to me. I can see that is not extremly 'pure' and insteads is more leaning towards convenience. But a lot things in OpenHAB are there to be convenient (UIs for instance).

**Comment by fwolter** [comment]
I understood that you suggested to add another channel, calculating the distance from the location in an existing channel to your home location.

As this is a one-liner (or two) in the binding's code, I don't see any redundency issues in code. And I also think this isn't redundant *data*. IMHO, it's fully legitimate to add another channel for this purpose.

**Comment by weymann** [comment]
Delivered on Marketplace https://community.openhab.org/t/mybmw-binding-add-on/131832. 
Unfortunately my BMW is sold. But tested with JUnit and Thing creation shows new channel. But I'm not able to perform full test.
@martingruening Please try bundles from Marketplace and after confirmation I'll raise the Pull Request

**Comment by martingruening** [comment]
I upgraded to the latest milestone build and removed/re-installed the MyBMW binding from the marketplace. Unfortunately the mentioned channel does not appear. I guess it is a problem with the user in front of the screen.

**Comment by martingruening** [comment]
Got it working. The new channel works as expected.
