### ISSUE TITLE
[Netatmo] Calculation of ID

### ISSUE THREAD

**Issue by AndreasIsenmann** [openhab/openhab-addons#12799]
At the moment the following information is part of the documentation:

```
You have to calculate the ID for the outside module as follows: (it cannot be read from the app)

- if the first serial character is "h": start with "02"
- if the first serial character is "i": start with "03"

```

Looks like this can be enhanced to

```
You have to calculate the ID for the outside module as follows: (it cannot be read from the app)

- if the first serial character is "h": start with "02"
- if the first serial character is "i": start with "03"
- if the first serial character is "j": start with "04"
- if the first serial character is "k": start with "05"

```

Successfully tested with a device with starting character "k". Can anyone confirm?

**Comment by jlaur** [comment]
@clinique, @lolodomo - do you know? :)

**Comment by clinique** [comment]
No, I only use auto discovery, but this can be a documentation enhancement.

**Comment by lolodomo** [comment]
I have an example starting with h and another starting with k and your assumption looks good for my devices too. 

No one with a serial number starting with j? 

@clinique : I see the serial number is not a thing property. This is probably something that could be added.

**Comment by jlaur** [comment]
I have two outdoor modules starting with "h" and both with id's starting with 02. So can confirm that relation only.

**Comment by lolodomo** [comment]
@AndreasIsenmann : so your hypothesis is probably correct. Would you like to submit the change in the documentation?

**Comment by AndreasIsenmann** [comment]
Yes, thanks - I will create a pull request for that.

**Comment by clinique** [comment]
for documentation, you can go directly : 
![image](https://user-images.githubusercontent.com/3328789/170203254-1b22d471-6ed6-4c60-874f-08064416a5a6.png)

**Comment by AndreasIsenmann** [comment]
Got the following message:

You’re making changes in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change will write it to a new branch in your fork, so you can send a pull request.
