### ISSUE TITLE
Openweathermap binding One Call API Historical data History Day

### ISSUE THREAD

**Issue by croftsquirrel** [openhab/openhab-addons#12806]
Hi,  I've tried finding an answer to this question of being able to change "history day" under openweathermap one call api historical data  thing settings to reflect "0" (0-24 hours) instead of only from 1-5 days in the past.  I need to be able to get rainfall history for the past 24 hours.  Currently limited to only giving data for "1" day which shows between hours 24-48 rainfall history.

**Comment by lolodomo** [comment]
Looks like a duplicate of #10798
