### ISSUE TITLE
[netatmo] Possible improvements to English texts

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12836]
Can someone please confirm the good English of these entries ? is "thermpoint" ok ?
```
actionLabel = send a set room thermpoint command
actionDesc = Send set room thermpoint command with endtime.
```
@clinique : I translated them like that, I believe this is correct ?
```
actionLabel = envoyer une commande au thermostat de la pièce
actionDesc = Envoie une commande au thermostat de la pièce avec l'heure de fin.
```
Regarding these ones, is "Netatmo bridge" the good term ? Maybe rather "Netatmo service" or "Netatmo server" or "Netatmo API" ?
```
conf-error-no-client-id = Cannot connect to Netatmo bridge as no client id is available in the configuration
conf-error-no-client-secret = Cannot connect to Netatmo bridge as no client secret is available in the configuration
```

**Comment by BigGeorgeTx** [comment]
Happy to help.  Thermpoint is not a English word.  I understand what it would mean.  From the French, the same word in English, "thermostat" would work.  I'm not clear as to whether or not the command being sent to the thermostat is a temperature setpoint or another command (mode, fan speed, etc).  If it is a temperature setpoint, depending on the thermostat it could be just a setpoint, or with some thermostats in auto mode, there could be an upper setpoint (for the cooling temperature setpoint) and a lower setpoint (for the heating temperature setpoint).  

For the first one, I would suggest "send thermostat temperature setpoint command for a room" or "send temperature setpoint to the thermostat in a room"  and for the second "Send thermostat temperature setpoint with an end time for a room."

If you know the room name, it is more clear "send temperature setpoint command to bedroom thermostat."

I hope this helps.

**Comment by lolodomo** [comment]
@clinique : additionally, there are 3 versions of the action (one for setting the mode, one for setting the setpoint, ...) so I believe they should have a different label/description. I am not sure how it appears in MainUI but I guess we have to distinguish each of them to help the user choose the right action.

So here is my proposal:

1. setThermpoint version with temp and endTime parameters: label "send temperature setpoint to the thermostat for a room" and description "Sends a temperature setpoint (manual mode) to the thermostat for a room with an end time."
2. setThermpoint version with mode and endTime parameters: label "send mode to the thermostat for a room" and description "Sends a mode to the thermostat for a room with an end time."
3. setThermpoint version with temp, mode and endTime parameters: label "send temperature setpoint and mode to the thermostat for a room" and description "Sends a temperature setpoint and a mode to the thermostat for a room with an end time."

Looking at the third version of the action, I am not sure it should be exposed. If I read correctly the code, if a temperature is provided, the mode is forced to MANUAL. So there is no real case the user can provide a temperature and a mode. The two first versions of setThermpoint actions are apparently enough for the user and the last version should be only private.

@clonique: WDYT ?
