### ISSUE TITLE
Sonos Binding - Issue by installing on OH 3.3.0-Snapshot Build 2764

### ISSUE THREAD

**Issue by Cmachtel** [openhab/openhab-addons#12833]
## Current Behavior

[ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-sonos': Error:
        Error downloading mvn:com.fasterxml.jackson.jaxrs/jackson-jaxrs-base/2.12.6
        Error downloading mvn:com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.12.6
        Error downloading mvn:com.fasterxml.jackson.jaxrs/jackson-jaxrs-json-provider/2.12.6
        Error downloading mvn:com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/2.12.6
        Error downloading mvn:com.fasterxml.jackson.dataformat/jackson-dataformat-xml/2.12.6
        Error downloading mvn:com.fasterxml.jackson.module/jackson-module-jaxb-annotations/2.12.6
        Error downloading mvn:com.fasterxml.jackson.core/jackson-core/2.12.6
        Error downloading mvn:com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.12.6
        Error downloading mvn:com.fasterxml.jackson.core/jackson-databind/2.12.6.1
        Error downloading mvn:com.fasterxml.jackson.core/jackson-annotations/2.12.6

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment
 OH 3.3.0-Snapshot Build 2764

**Comment by lolodomo** [comment]
2764 is very old. 
Last snapshot is 2914.
Can you reproduce your issue with a recent snapshot?

**Comment by Cmachtel** [comment]
> 2764 is very old. Probably around 5 or 6 months old. Last snapshot is 2914. Can you reproduce your issue with a recent snapshot?

Whow, thanks it solved the issue
