### ISSUE TITLE
[MyBMW] Authorization fails

### ISSUE THREAD

**Issue by weymann** [openhab/openhab-addons#12840]
Community recognized failing Authorization calls for europe
https://community.openhab.org/t/mybmw-binding/130935/88

Home Assistent community recognizes the same so problem isn't relaetd to openHAB itsself
https://github.com/bimmerconnected/bimmer_connected/issues/444

**Comment by martingruening** [comment]
I suggest to mimic the user agent string of the MyBMW app. The access seems to be denied on specific user agent strings.
