### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by jorgeventura** [openhab/openhab-addons#12861]
At server side I get the error below:
OpenSSL Error[0]: error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm

The mosquitto server is working properly and pass in the test using mosquitto_pub.

MQTT broker

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by jorgeventura** [comment]
One possibility that come to my mind is about startup parameters for java. Below is what I am using.

docker run --name openhab --net=host --tty -v /etc/localtime:/etc/localtime:ro -v openhab_addons:/openhab/addons -v openhab_conf:/openhab/conf -v openhab_userdata:/openhab/userdata -e "EXTRA_JAVA_OPTS=-Duser.timezone=America/Chicago" --device=/dev/ttyACM0 -d --restart=always openhab/openhab:3.3.0.M5

Perhaps in the EXTRA_JAVA_OPTS I should include something specific for jdk.tls .

**Comment by wborn** [comment]
Maybe also try setting the `CRYPTO_POLICY=unlimited` environment var?

See: 
* [Java cryptographic strength policy](https://github.com/openhab/openhab-docker#java-cryptographic-strength-policy)
* [Set environment variables](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)

**Comment by jorgeventura** [comment]
Definitely  there is an issue about the cipher suite. Below is the suite presented by MQTT bind. I don't think the issue is the bind but the TLS configuration in java as suggested by @wborn.

        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        TLS_RSA_WITH_AES_128_GCM_SHA256
        TLS_RSA_WITH_AES_128_CBC_SHA
        TLS_RSA_WITH_AES_256_CBC_SHA
        TLS_AES_128_GCM_SHA256
        TLS_AES_256_GCM_SHA384

The next suite is one that works using the command mosquitto_pub.
        
        TLS_AES_256_GCM_SHA384
        TLS_CHACHA20_POLY1305_SHA256
        TLS_AES_128_GCM_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
        TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA
        TLS_RSA_WITH_AES_256_GCM_SHA384
        TLS_RSA_WITH_AES_128_GCM_SHA256
        TLS_RSA_WITH_AES_256_CBC_SHA256
        TLS_RSA_WITH_AES_128_CBC_SHA256
        TLS_RSA_WITH_AES_256_CBC_SHA
        TLS_RSA_WITH_AES_128_CBC_SHA
        TLS_EMPTY_RENEGOTIATION_INFO_SCSV

**Comment by jorgeventura** [comment]
The env var didn't work; the cipher suite is still the short one.
I am using mosquitto compiled from source; I will see if it's possible to restrict the cipher suite to the same as issued by mqtt bind.

Any other suggestion is welcome.

**Comment by jorgeventura** [comment]
I restricted mosquitto to the same short list using the parameter 'ciphers_tls1.3' but the problem persists.
Maybe the issue is related with the way that mqtt key was created; here is the command:

openssl genpkey -algorithm ed25519 > broker.key

Maybe the algorithm can't be ED25219 but I don't know witch one to use, this was suggested by the site with instructions to configure mosquitto.

**Comment by wborn** [comment]
> Maybe the algorithm can't be ED25219

Looks like support for Edwards-curve Digital Signature Algorithm (EdDSA) was only added in Java 15 and newer, see:

* https://openjdk.java.net/jeps/339
* https://www.oracle.com/de/news/announcement/oracle-announces-java-15-2020-09-15/

**Comment by jorgeventura** [comment]
BINGO!!!!
That was the issue! I changed to RSA and it's working.

**Comment by jorgeventura** [comment]
The problem was fixed when I generated the key using RSA algorithm.
