### ISSUE TITLE
[KNX] DPT 9.007 is wrongly reported

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#12922]
Cfr https://github.com/openhab/openhab-addons/issues/3408
Cfr https://github.com/openhab/openhab-addons/issues/3416
Cfr https://github.com/openhab/openhab-addons/blob/bf6d508c61d3671769e99dfe20958429836d2745/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/dpt/KNXCoreTypeMapper.java#L284

A device Thing with a Channel defined as follows

`Type number : GuestBathroomRelativeHumidity [ ga="9.007:<8/4/30" ]
`
and an Item linked to that Channel as follows

`Number:Dimensionless GuestBathroomRelativeHumidity "Guest Bathroom - Relative Humidity [%.2f %%]" {channel="knx:device:bridge:1_3_151:GuestBathroomRelativeHumidity"}`

still reports its values as 

`2022-06-11 16:46:18.405 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'GuestBathroomRelativeHumidity' changed from 0.46% to 0.47 %`

whereas the data should be interpreted as 46% and 47% instead, Cfr what is reported in ETS5

<img width="303" alt="image" src="https://user-images.githubusercontent.com/5459062/173193092-71e488ac-60b3-4fa2-b7f7-9fc2cbec8072.png">

**Comment by tmsch13** [comment]
+1 This is similar to https://github.com/openhab/openhab-addons/issues/4146 
and ists really annoying. Of course there are possible workarounds to change the value or just display it as desired.
I have 11 KNX Humidity Sensors and 5 Shelly HT Sensors. Openhab should be the place were it doesn’t matter where the data comes from. But a Humidity of 60% from KNX (stored as 0.6) is evaluated as less than 50% of the shelly HT (stored as 50) and that is a real problem in some situations.

**Comment by holgerfriedrich** [comment]
> Attention: With the introduction of Unit of Measurement (UoM) support #14534, some data types have changed (see number channel below):
> - ...
> - Data type for DPT 9.007 (Humidity) has changed from PercentType to QuantityType.

With current version of the binding, DPT 9.007 seems to work correctly and reports the percentage correctly.
Event log shows the percentage values correctly.

**Comment by holgerfriedrich** [comment]
I closed the issue, pleas reopen in case you think that this is not properly handled in the current snapshot.
