### ISSUE TITLE
[openuv] invalid json received

### ISSUE THREAD

**Issue by nesys** [openhab/openhab-addons#12932]
strange issue with Openuv Binding. I see sometimes the binding is suddenly stopping, and I see this on PaperUI:

`Invalid json received when calling `https://api.openuv.io/api/v1/uv?lat=45.465051&lng=9.094615&alt=0` : {"error":{"name":"MongoError","message":"user is not allowed to do action [find] on [openuv-billing.requests]","ok":0,"errmsg":"user is not allowed to do action [find] on [openuv-billing.requests]","code":8000,"codeName":"AtlasError"}}`

If I start again (disabling and re-enabling the API via PaperUI), everything becomes green and online.

## Expected Behavior
the binding should stay online

## Current Behavior
the binding suddenly stops working. it needs a forced restart to go back online

## Steps to Reproduce (for Bugs)
sometimes it happens, especially during the night

## Your Environment
* Version used: 3.3.0 M6
* Environment name and version: openHABian
* Operating System and version: debian "buster"

**Comment by lolodomo** [comment]
You mean MainUI, not PaperUI which does not exist anymore in v3.x.

**Comment by nesys** [comment]
exactly, apologies for that :)

**Comment by nesys** [comment]
Update: now also during the day, and it is not recovering, even disabling and re-enabling the binding

**Comment by clinique** [comment]
> Update: now also during the day, and it is not recovering, even disabling and re-enabling the binding. It saying "User with API key not found" ... but the key is correct

Yes, have it also currently. There is an error on OpenUV api side.

**Comment by nesys** [comment]
> > Update: now also during the day, and it is not recovering, even disabling and re-enabling the binding. It saying "User with API key not found" ... but the key is correct
> 
> Yes, have it also currently. There is an error on OpenUV api side.

that happened sometimes also in the past ...

**Comment by nesys** [comment]
btw this binding is becoming a nightmare for you, @clinique ... I'm really sorry for that, but thanks for your support

**Comment by clinique** [comment]
Don't bother, I've seen worst nightmares :) This one will be quite easy to fix.

**Comment by lolodomo** [comment]
Can we close the issue now?
