### ISSUE TITLE
[boschindego] Last/next cutting time

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12986]
The API provides methods for requesting last/next cutting time from the device. These timestamps could be exposed as new channels.

They should not be updated as often as normal state since each timestamp require a distinct call and information is quite static.
- Last cutting could be updated when state indicates a possible change, i.e. recently cutting.
- Next cutting will change according to calendar configuration, so it would make sense to refresh with low frequency (perhaps every few hours) in case of configuration change and after current timestamp is exceeded. However, SmartMowing should also be considered, and time could change more unpredictably.

### Last cutting
**Method:** GET https://api.indego.iot.bosch-si.com/
**Path:** /api/v1/alms/serialNumber/predictive/lastcutting

Example response:

```
{
    "last_mowed": "2022-06-21T18:14:22.425+01:00"
}
```

### Next cutting
**Method:** GET https://api.indego.iot.bosch-si.com/
**Path:** /api/v1/alms/serialNumber/predictive/nextcutting

Example response:

```
{
    "mow_next": "2022-06-22T09:30:00+01:00"
}
```

When calendar hasn't been configured yet, response body is empty and HTTP code 204 ("No Content") is returned.

See also: https://github.com/zazaz-de/iot-device-bosch-indego-controller/blob/master/PROTOCOL.md

**Comment by jlaur** [comment]
@BillGOH - FYI, I received my Indego back from repair this evening and resumed work on the binding. I started by implementing last/next cutting:

![image](https://user-images.githubusercontent.com/19519842/174894166-a28ed465-d2ad-4b55-a6c0-31f6e1c306d2.png)

I need to put some more effort in an intelligent way to determine when to refresh these timestamps, but should be able to provide a JAR for testing soon.

**Comment by BillGOH** [comment]
Looks good. Thanks again for your work.

Btw: I had a new status code today: 1537 (in the app "energy saving mode"). I do not know what that means since the mower was in the docking station.

**Comment by jlaur** [comment]
> I had a new status code today: 1537 (in the app "energy saving mode"). I do not know what that means since the mower was in the docking station.

I'll add this code. Just one question: When in this mode, can you start it from the app?
