### ISSUE TITLE
[deconz] Danfoss Ally thermostat things never enter the ONLINE state

### ISSUE THREAD

**Issue by danieldemus** [openhab/openhab-addons#13028]
## Expected Behavior
At some point the Danfoss Ally thermostat things from deconz get into the ONLINE state.

## Current Behavior
All thermostat things from deconz are always in the UNKNOWN.  I only have danfoss ally thermostats, so I don't know whether this is product specific or a general problem.

## Steps to Reproduce (for Bugs)
1. Register a Danfoss Ally thermostat in phoscon/deconz. Check that it has turned up is healthy in the phoscon UI.
2. If you have discovery enabled add the thing from there, otherwise configure the thermostat in an .things file.
3. Observe that the thing state doesn't change from UNKNOWN to ONLINE.
4. Disable and then enable the thing. Observe 3.

## Context
Updates seem to propagate from the thermostats, but you wouldn't notice if one of them goes missing, when it has never been ONLINE.

## Your Environment
Openhab 3.3 on Fedora 36 from the stable repo.
The deconz api returns the following for one of the thermostats:
```
{
    "config": {
        "battery": 81,
        "displayflipped": false,
        "externalsensortemp": -8000,
        "externalwindowopen": false,
        "heatsetpoint": 2100,
        "locked": false,
        "mountingmode": false,
        "offset": 0,
        "on": true,
        "reachable": true,
        "schedule": {},
        "schedule_on": false
    },
    "ep": 1,
    "etag": "5284c9f78e67399a7b0e08660d9766e2",
    "lastannounced": "2022-06-17T17:30:02Z",
    "lastseen": "2022-06-27T14:25Z",
    "manufacturername": "Danfoss",
    "modelid": "eTRV0100",
    "name": "Thermostat, Gildestue",
    "state": {
        "errorcode": "0",
        "lastupdated": "2022-06-27T14:25:12.864",
        "mountingmodeactive": false,
        "on": true,
        "temperature": 1983,
        "valve": 96,
        "windowopen": "Closed"
    },
    "swversion": "01.12.0008 01.12",
    "type": "ZHAThermostat",
    "uniqueid": "0c:43:14:ff:fe:c7:1c:2d-01-0201"
}
```

As a side-note, some of the channels, - mainly battery level, low battery and last seen -, don't show up after adding the thermostat thing.

**Comment by danieldemus** [comment]
I believe the reason for this might be https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6641.

**Comment by spektab** [comment]
I have installed in parallel an home assistant instance, it shows all the data expected, also the battery states...

**Comment by spektab** [comment]
> I believe the reason for this might be [dresden-elektronik/deconz-rest-plugin#6641](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/6641).

So finally I have added to the DDF

`        {
          "name": "config/mode",
          "description": "Mode of the device.",
          "refresh.intervall": 3660,
          "default": "off"
        },
`
so that the REST-API from deCONZ shows the following output

`{
    "config": {
        "battery": 41,
        "displayflipped": false,
        "externalsensortemp": -8000,
        "externalwindowopen": false,
        "heatsetpoint": 2100,
        "locked": false,
        "mode": "heat",
        "mountingmode": false,
        "offset": 0,
        "on": true,
        "reachable": true,
        "schedule": {},
        "schedule_on": false
    },
    "ep": 1,
    "etag": "ef283096d058861074798efae930ab36",
    "lastannounced": null,
    "lastseen": "2023-03-18T05:58Z",
    "manufacturername": "Danfoss",
    "modelid": "eTRV0103",
    "name": "Thermostat Flur",
    "state": {
        "errorcode": "0",
        "lastupdated": "2023-03-18T05:52:29.506",
        "mountingmodeactive": false,
        "on": false,
        "temperature": 2145,
        "valve": 1,
        "windowopen": "Closed"
    },
    "swversion": "00.20.0008 00.20",
    "type": "ZHAThermostat",
    "uniqueid": "xxxx"
}`

Nothing changed within openHAB. The thing state is always unknown. Could you please provide any further advice?

**Comment by J-N-K** [comment]
Did you use discovery? Can you show the added thing as YAML?

**Comment by spektab** [comment]
> Did you use discovery? Can you show the added thing as YAML?

Yes, I have used discovery. The Code from the thing device is shown below

`UID: deconz:thermostat:000000000000:xxx
label: Thermostat Flur (Danfoss)
thingTypeUID: deconz:thermostat
configuration:
  lastSeenPolling: 1440
  id: "77"
bridgeUID: deconz:deconz:000000000000`

The thing has the following channels.

1. Temperature (plausible)
2. Setpoint (is working, adjustable by OH)
3. Mode
4. Offset
5. Valve
6. Last updated

Annything else is missing...

**Comment by J-N-K** [comment]
I took the API response from https://github.com/openhab/openhab-addons/issues/13028#issuecomment-1474739586 and wrote a test that initializes a `SensorThermostatThingHandler` with that and the device first gets 'UNKNOWN' state and then switches to `ONLINE`. Battery and lock channels are also added.

Can you try one of the next OH4 snapshots (the current one does not include the required changes due to build issues) and see if that works? You can just download it and try on your PC, no need to configure anything besides the deconz bridge (and of course add the thing).

**Comment by jlaur** [comment]
@spektab - if you can't wait for the next snapshot, I already built the new version for testing purposes: [org.openhab.binding.deconz-4.0.0-SNAPSHOT.jar](https://drive.google.com/file/d/13fQuOMgGkbT0r1ypsiOy1v7Ki1erhfer/view?usp=sharing)

**Comment by J-N-K** [comment]
Please wait until #14636 is merged, there were some bugs in thermostat handling (which should not affect ONLINE status, but who knows).

**Comment by J-N-K** [comment]
@danieldemus @spektab Can you please check with latest snapshot if your issues are resolved? Thanks.

**Comment by spektab** [comment]
From my point of view, it works...

![grafik](https://user-images.githubusercontent.com/127825052/227721985-fc384c52-7dcf-4e1e-bbd2-f6d655b1ccb8.png)

**Comment by J-N-K** [comment]
Thanks!

**Comment by danieldemus** [comment]
The thermostat being unknown issue is resolved in the latest snapshot.
