### ISSUE TITLE
[goecharger] Binding not working anymore in latest snapshot

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-addons#13054]
Environment:
Go-e charger V3, firmware 053.4 Beta, Using API v2
Openhab Snapshot 2980

Querying the charger seems to work, however sending commands (e.g. allow to charge) results in:
```
2022-07-02T09:36:59,727 | WARN  | OH-safeCall-4    | GoEChargerV2Handler              | 314 - org.openhab.binding.goecharger - 3.4.0.202207020339 | Could not update channel allowCharging with key null and value null
```

Steps to reproduce:
- Deploy current snapshot (2980)
- Install go-e charger binding
- Add charger thing with API v2
- Link Allow Charge Channel to a switch item
- Toggle switch to ON

The apiv2 handler seems to be responsible for this. My guess, without further knowledge, would be allow_charge is not known to APIv2 handler, so key and value can not be filled with values:
https://github.com/openhab/openhab-addons/blob/ad9b4fbf791e1772e798f6b8c66234e617226e4e/bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/handler/GoEChargerV2Handler.java#L212

This seems to originate from @ranzen84 's PR #12400 

Would be really good if this could be resolved :)

Best,
Sascha

**Comment by ranzen84** [comment]
According the specification this is a read only value:

https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-de.md

If you know any workaround or other value for this please let me know.
Personally I do not need this setting...

**Comment by cribskip** [comment]
Thank you very much for pointing me to the documentation - I didn't notice the change on ALW between v1(r/w) and v2(r). Btw, for others taking the same detour, the binding documentation clearly shows this change (https://www.openhab.org/addons/bindings/goecharger/)

And also thank you for pointing me to forceState which is a substitute to the writable ALW command.

I'll add some documentation on the changed behavior with API v2.
