### ISSUE TITLE
[MIIO] Roborock - Unknown Blocktype RRMapFileParser

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-addons#13079]
The great Mi io-Binding asked me to contact the author.

Device is a Roborock Q7 Max with Firmware 4.1.5_0730

```
21:26:35.368 [DEBUG] [.internal.handler.MiIoAbstractHandler] - Received response for device xxxxxxxxxx type: GET_MAP, result: ["roboroommap%2F535491826%2F2"], fullresponse: {"id":45,"result":["roboroommap%2Fxxxxxxxxxx%2F2"],"exe_time":101}
21:26:35.371 [DEBUG] [ng.miio.internal.cloud.CloudConnector] - Getting vacuum map roboroommap%2Fxxxxxxxxx%2F2 from Xiaomi cloud server: 'de'
21:26:35.373 [DEBUG] [.miio.internal.cloud.MiCloudConnector] - Send request to https://de.api.io.mi.com/app/home/getmapfileurl with data '{"obj_name":"roboroommap%2Fxxxxxxxxx%2F2"}'
21:26:35.464 [DEBUG] [.miio.internal.cloud.MiCloudConnector] - Received  JSON message {"code":0,"message":"ok","result":{"url":"https://awsde0.fds.api.xiaomi.com/robomap/roboroommap/xxxxxxx/2?Expires=1656964595000&GalaxyAccessKeyId=yyyyyyyy&Signature=xxxxxx","obj_name":"roboroommap/xxxxxxx/2","method":"GET","expires_time":1656964595,"ok":true}}
21:26:35.603 [INFO ] [g.miio.internal.robot.RRMapFileParser] - Unknown blocktype 21 (pls report to author)
21:26:35.606 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Blocktype: 21
21:26:35.610 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Header len: 12   data len: 0 
21:26:35.612 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - H: 15 00 0C 00 00 00 00 00 00 00 00 00
21:26:35.620 [INFO ] [g.miio.internal.robot.RRMapFileParser] - Unknown blocktype 22 (pls report to author)
21:26:35.622 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Blocktype: 22
21:26:35.626 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Header len: 12   data len: 0 
21:26:35.631 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - H: 16 00 0C 00 00 00 00 00 00 00 00 00
21:26:35.636 [INFO ] [g.miio.internal.robot.RRMapFileParser] - Unknown blocktype 24 (pls report to author)
21:26:35.639 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Blocktype: 24
21:26:35.641 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Header len: 8   data len: 32 
21:26:35.643 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - H: 18 00 08 00 20 00 00 00
21:26:35.644 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - D: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
21:26:35.646 [INFO ] [g.miio.internal.robot.RRMapFileParser] - Unknown blocktype 25 (pls report to author)
21:26:35.647 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Blocktype: 25
21:26:35.649 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Header len: 12   data len: 0 
21:26:35.650 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - H: 19 00 0C 00 00 00 00 00 00 00 00 00
21:26:35.651 [INFO ] [g.miio.internal.robot.RRMapFileParser] - Unknown blocktype 26 (pls report to author)
21:26:35.653 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Blocktype: 26
21:26:35.656 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - Header len: 8   data len: 4 
21:26:35.660 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - H: 1A 00 08 00 04 00 00 00
21:26:35.662 [DEBUG] [g.miio.internal.robot.RRMapFileParser] - D: 00 00 00 00
21:26:35.670 [DEBUG] [io.internal.handler.MiIoVacuumHandler] - Mapdata saved to /openhab/userdata/miio/roboroommap%2Fxxxxxxx%2F220220704-212635.rrmap
```

The Map file is this one:
[roboroommap%2Fxxxxxxx%2F220220704-212635.rrmap.zip](https://github.com/openhab/openhab-addons/files/9041734/roboroommap.2Fxxxxxxx.2F220220704-212635.rrmap.zip)

Maybe @marcelrv is the "author to report to" ;-)

ID has been removed, hopefully, this causes no burden.

If there's anything I can do to resolve this, please let me know.

Thanks & regards
Sascha

**Comment by DrRSatzteil** [comment]
I get same messages with a max7v

**Comment by marcelrv** [comment]
Seems indeed there have some new blocks been added.
@cribskip would it be possible to share a map file (like you did) and a image / screenshot of what you see in the app. That may help understand what there new block mean.

In the mean time, to avoid flooding your log, you can do the following
`log:set warn org.openhab.binding.miio.internal.robot.RRMapFileParse`
or
`log:set warn org.openhab.binding.miio.internal.robot`

**Comment by marcelrv** [comment]
@DrRSatzteil 
same request to you  would it be possible to share a map file (like you did) and a image / screenshot of what you see in the app. That may help understand what there new block mean.

**Comment by DrRSatzteil** [comment]
Sure, here is a screenshot from the app. I will attach a map file later that day.

![image](https://user-images.githubusercontent.com/2452988/177998178-423bcd58-b900-4b0a-bd06-f77e231ad04c.png)

**Comment by marcelrv** [comment]
made quick fix to remove the messages... to decode this new stuff will take some time.
Some blocks may be tricky to get in openhab as it will need copyright free images for furnitures etc

**Comment by CobraCalle** [comment]
Hello,

I`ve a Q7 Max too. But how do you managed to access this thing with an API? I cannot login to the MiHome-App with my credentials (but it sais that there is an account and I can reset my password, but cannot login with the new password)... I think it has something to do with the fact tht I`m using the Roborock-App?! So it is impossible for me to extract the token from it...

Carl

**Comment by DrRSatzteil** [comment]
> Hello,
> 
> 
> 
> I`ve a Q7 Max too. But how do you managed to access this thing with an API? I cannot login to the MiHome-App with my credentials (but it sais that there is an account and I can reset my password, but cannot login with the new password)... I think it has something to do with the fact tht I`m using the Roborock-App?! So it is impossible for me to extract the token from it...
> 
> 
> 
> Carl

Unfortunately you cannot use both apps at the same time. You need to register your vacuum with the MiHome App. You will loose a couple of the less useful features though, like the onboard camera that is only supported by the Roborock app.

**Comment by marcelrv** [comment]
Indeed.. as @DrRSatzteil indicates and as per faq it only works if connected to mihome app 

https://www.openhab.org/addons/bindings/miio/#faq-what-to-do-in-case-of-problems
