### ISSUE TITLE
[Netatmo] Getting ID:s for Netatmo modules.

### ISSUE THREAD

**Issue by mikaelgu80** [openhab/openhab-addons#13091]
A few improvement ideas for the otherwise awesome new Netatmo binding, or its documentation really.
1) It should be noted, that in order to add devices in the "security" category, one needs to add a home (found out the hard way).
2) while searching for the proper id for home, I landed on [https://dev.netatmo.com/apidocumentation/security#homesdata](https://dev.netatmo.com/apidocumentation/security#homesdata). The ID is listed there, so no problem, but should be mentioned in the docs.

And finally, as that API call lists all devices/modules that have been installed, couldn't they be autodiscovered after succesfully creating the bridge?

**Comment by mikaelgu80** [comment]
> The discovery is already there. Just launch a manual scan in MainUI. 

Totally missed that. Good to know!

**Comment by VincentPersi** [comment]
I guess I also missed the discovery but I found out the long way that if you want to manually add an additional indoor module, you need to append not 00:00 like for the external one but rather ff:ff

**Comment by lolodomo** [comment]
We could add a console command to list all the devices/modules with their IDs.
We should then reuse the discovery code.

**Comment by lolodomo** [comment]
I will implement it as I think I have a clear idea of what to do and how to do it properly,

**Comment by lolodomo** [comment]
The PR is submitted, I think this is very interesting as the console command shows of course the IDs but also all the hierarchy of associated thing types.
