### ISSUE TITLE
[smartmeter] "Too many open files" exception with binding

### ISSUE THREAD

**Issue by mgerczuk** [openhab/openhab-addons#13092]
## Expected Behavior
Smartmeter binding reading values from serial interface without losing resources.

## Current Behavior
USB serial interface is configured with udev and added to Java config as described in https://www.openhab.org/docs/administration/serial.html. 

After enabling a smartmeter thing, the OpenHAB (Java) process is using continuosly more file handles (roughly adding 5 handles per second) as can be checked with `sudo lsof -p <java pid> | wc -l`. This happens even when no device is connected to the USB interface.

After some time other bindings stop working with "Too many open files" exceptions. The web interface is also no longer working.

## Steps to Reproduce (for Bugs)

1. Add udev rule for USB port and add port name to Java config as described in https://www.openhab.org/docs/administration/serial.html.
2. Configure smartmeter binding to use this port
3. Let run for a few hours. Check number of open files with `sudo lsof -p <java pid> | wc -l`

## Your Environment
* OpenHABian 3.20
* Raspberry Pi 4 4GB

**Comment by wborn** [comment]
This is fixed in 3.3.0, see https://github.com/openhab/openhab-core/pull/2899.
