### ISSUE TITLE
iCloud Binding COMMUNICATION_ERROR iCloud response invalid: null

### ISSUE THREAD

**Issue by BigGeorgeTx** [openhab/openhab-addons#13090]
The iCloud binding has stopped working for a number of users https://community.openhab.org/t/icloud-binding-communication-error/122131/249?u=biggeorgetx

I’m on 3.3M5, but it is also reported by 3.3 Release users.

**Comment by JensHoRi** [comment]
Saw oh 3.2 same issue

**Comment by hmerk** [comment]
@pgfeller Can you check this please.

**Comment by BillGOH** [comment]
Same issue, openHAB 3.3.

**Comment by bredmich** [comment]
Just checked my persistence and the last update was "2022-07-06 23:59:21.009".
So it seems like Apple changed something around midnight 2022-07-07.
openHAB 3.2 and 3.3

**Comment by JensHoRi** [comment]
Just checked with loglevel TRACE. Only messages are the following:
```
2022-07-09 22:24:48.741 [DEBUG] [l.handler.ICloudAccountBridgeHandler] - iCloud bridge refreshing data ...
2022-07-09 22:24:49.161 [TRACE] [l.handler.ICloudAccountBridgeHandler] - json: {"url":"https://support.apple.com/en-us/HT204230"}
```

**Comment by dathbe** [comment]
The May 11 stoppage seems to be a different issue.  Mine stopped working after the My 17 fix for that issue.

**Comment by hmerk** [comment]
Definitely a different issue, as #10699 was opened last year and fixed in the same year.

**Comment by hmerk** [comment]
@Trinitus01 As you fixed it last year, can you check once again please.

**Comment by Spock8004** [comment]
Same issue on my OH3 Docker Image, iCloud not working anymore, same timestamp of last query as bedrick experinced. Thanks for taking care of.

**Comment by hmerk** [comment]
Solution is publishe in community topic posted above.
