### ISSUE TITLE
[mqtt] Rollershutter ignores formatBeforePublish

### ISSUE THREAD

**Issue by Frank-1964** [openhab/openhab-addons#13106]
I try to bind a Shelly Plus 2PM (Rollershutter) device via the mqtt binding to openhab. The Shelly device expects a json string for controlling the rollershutter. For this reason I would like to use the formatBeforePublic pattern to convert the values to the corresponding json strings.

## Expected Behavior

formatBeforePublish will be applied.

## Current Behavior

Unfortunately the formatBeforePublish will be ignored.

## Your Environment

OH3.3
Raspbian Buster

**Comment by digitlength** [comment]
Can you share your Thing configuration?

**Comment by Frank-1964** [comment]
This is my thing configuration:

UID: mqtt:topic:fa14331939
label: Shelly Plus 2PM (Rollo 1)
thingTypeUID: mqtt:topic
configuration:
  payloadNotAvailable: "false"
  availabilityTopic: shellyplus2pm-485519996e78/online
  payloadAvailable: "true"
bridgeUID: mqtt:broker:4efecebca1
location: Terrasse
channels:
  - id: cover
    channelTypeUID: mqtt:rollershutter
    label: Cover
    description: null
    configuration:
      postCommand: true
      formatBeforePublish: '{"id":0,"src":"shellyplus2pm-485519996e78","method":"Cover.%s","params":{"id":0}}'
      stop: Stop
      commandTopic: shellyplus2pm-485519996e78/rpc
      stateTopic: shellyplus2pm-485519996e78/rpc
      off: Close
      on: Open

**Comment by digitlength** [comment]
Note that this is [expected behaviour according to the documentation](https://www.openhab.org/addons/bindings/mqtt.generic/#format-before-publish):

![image](https://user-images.githubusercontent.com/62958838/179592272-f8781e68-3c56-42af-87b9-6edbe8845fd2.png)
