### ISSUE TITLE
[jdbc] Upgrade H2 driver to 2.2.224

### ISSUE THREAD

**Issue by wollyd** [openhab/openhab-addons#13115]
Hi,

H2 1.4.191 is not suppoter anymore. 
Is it possible to upgrade H2 to 2.1.214 ?

Thanks in advance

Willy

**Comment by wborn** [comment]
I gave this a brief try a while ago but didn't see through it.

One issue is that the new version is more restricted regarding reserved key words, see: http://www.h2database.com/html/advanced.html#keywords

This is an issue with the "value" column. Now you can use double quotes as workaround for reserved keywords in column names, but then the column name becomes case sensitive too which also caused some issues. :confused:

Another workaround is to use the `NON_KEYWORDS=VALUE` as JDBC URL parameter but it is not so nice.

> There is a compatibility setting [SET NON_KEYWORDS](http://www.h2database.com/html/commands.html#set_non_keywords) that can be used as a temporary workaround for applications that use keywords as unquoted identifiers.

When it's all working you also need export your existing H2 database to SQL using the [`SCRIPT`](https://h2database.com/html/commands.html#script) command and import it using [`RUNSCRIPT FROM 'dump.sql' FROM_1X`](https://h2database.com/html/commands.html#runscript) to fix the old version quirks.

**Comment by wollyd** [comment]
Hi,

I tried to use H2 2.2.220 but did not succeed.
I dumped the database and imported it again with FROM_1X into h2-2.2.220;
I removed the bundle for H2 1.4.191

changed the url to the correct database and added  NON_KEYWORDS=VALUE (in services/jdbc.cfg)
dropped the h2-2.2.220.jar into the addons directory
restarted openhab.

in the console wit bundle:list  :
322 │ Active │  80 │ 2.2.220                │ H2 Database Engine

but openhab does not use the new h2 jdbcdriver.

Am I missing something ?

kind regards

willy

**Comment by wborn** [comment]
> Am I missing something ?

Because 1.4.191 is getting really old (2016) I created #15726 to use 2.2.224.
I had another look but didn't find an easy workaround for the reserved "value" keyword.
But it should work if you add `;NON_KEYWORDS=VALUE` to the JDBC URL.
