### ISSUE TITLE
[FineOffsetWeatherStation] Air pressure numbers are not correctly imported  

### ISSUE THREAD

**Issue by mpe-consulting** [openhab/openhab-addons#13127]
it seems  that values for absolute pressure and relative pressure are not correct shown in openhab.

## Expected Behavior
correct numbers should be displayed in openhab 

## Current Behavior
it looks like both pressure data are multiplied by 10 ...
(a value of 1001.7 hPa from the live date page on the gateway is shown as 10017,000 hPa in openhab)

## Possible Solution
change data collection process to return correct numbers for pressure data

## Your Environment
openhab 3.3.0 / weatherstation GW1100A_V2.1.5 with sensor WH65 / FineOffsetWeatherStation Binding
![screenshot_20220714_221649](https://user-images.githubusercontent.com/78204209/179076762-8bad83c1-f66e-4fc8-98d1-201dc8fcf98c.png)
![screenshot_20220714_221703](https://user-images.githubusercontent.com/78204209/179076764-0132bc98-2d1e-4cba-97cf-e6563e8d6d70.png)

**Comment by jlaur** [comment]
@Andy2003 - tagging you in case you didn't see this issue.
