### ISSUE TITLE
[fmiweather] Observation thing fails to initialize with OH 3.3

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#13129]
Thing initialization fails with cryptic error response from the API

![Screenshot from 2022-07-15 09-15-39](https://user-images.githubusercontent.com/315866/179162828-e191b12c-81fd-4346-b006-6b759ad3136d.png)

(note the FMISID being "101028.0" instead of "101028")

In JSONDB, there is integer stored
```
$ grep 'fmisid.*101028' jsondb/org.openhab.core.thing.Thing.json 
        "fmisid": 101028
```
Clicking "Save" in MainUI makes the thing go ONLINE.

Unfortunately, after restart, the thing is OFFLINE again

Likely fixed by: https://github.com/openhab/openhab-core/pull/3024

**Comment by jlaur** [comment]
@ssalonen - openhab/openhab-core#3024 was recently merged, so this should be fixed now. Perhaps you could verify with latest snapshot - otherwise it will be included in next milestone.

**Comment by ssalonen** [comment]
I confirmed
- 3.4.0 M2: can reproduce the issue
- 3.4.0-SNAPSHOT (downloaded today from openhab.org): issue resolved.

We can conclude https://github.com/openhab/openhab-core/pull/3024 fixes this issue, closing.
