### ISSUE TITLE
[Hue] Hue Tap Dial Switch -> rotating bezel support

### ISSUE THREAD

**Issue by WhiteSockedDancer** [openhab/openhab-addons#13140]
Dear Devs,

Hue released a new type of switch called "Hue Tap Dial Switch" which got 4 buttons and a rotating dial.
Button presses are already registered, but the dial events are not registered.

I would love to get support for this device and would help with any testing.

I found this issue for home assistant where someone already put up a log using the new switch. Probably that helps.
https://github.com/home-assistant/core/issues/75082

**Comment by dnwk** [comment]
Yes, supporting rotating bezel will be great

**Comment by andrewfg** [comment]
@WhiteSockedDancer / @dnwk we may be able to learn more if one of you could use a ‘curl’ command to query your Hue Bridge via the new CLIP 2 interface concerning its supported `device` resources.

```
// get the list of `device` resources
curl --insecure -H "hue-application-key: [your_username]" -X GET "https://[your_hue_ipaddress]/clip/v2/resource/device"
```

This command should produce a JSON list of all devices in your systems. It should contain (among others) your Tap Dial Switch, so please post the JSON for that one.

The Tap Dial Switch device element will contain a list of services comprising rid and rtype which will tells all its supported services. You will certainly see the obvious rtypes – namely device_power, zigbee_connectivity, and 4x button. And the open question is what other rtypes does it have in its services list?

**Comment by andrewfg** [comment]
This is just to confirm that #13570 will implement this feature.
