### ISSUE TITLE
Cannot install addon

### ISSUE THREAD

**Issue by EnziinSystem** [openhab/openhab-addons#13149]
My environment:

* Version: 3.4.0.SNAPSHOT
* Java 11 Zulu11.56+19-CA (build 11.0.15+10-LTS)
* Debian 10

I cannot install addons from **Setting>Things**
For example, OpenWeatherMap Binding hangs a long time forever.

![addon](https://user-images.githubusercontent.com/25495466/179885173-68d97a1a-411e-4dce-9d09-323182ba33a7.png)

**Comment by wborn** [comment]
Works fine for me and it doesn't seem widespread so if it is still an issue try getting some help in the [community](https://community.openhab.org/). Make sure to provide copious logging and configuration details.
