### ISSUE TITLE
[gardena] merge automower plugin

### ISSUE THREAD

**Issue by RandomReaper** [openhab/openhab-addons#13143]
Since the  automower plugin share some code with gardena, I think both plugins should be merged.
Husqvarna mowers could be a new Things type (husqvarna_mower?).

Benefits:
bugs like #12980 and  #12980 can be handled only once.

**Comment by lolodomo** [comment]
> Since the automower plugin share some code with gardena

Do you mean they share the same API?

**Comment by RandomReaper** [comment]
> > Since the automower plugin share some code with gardena
> 
> Do you mean they share the same API?

They share at least the same account and the login API.

**Comment by andrewfg** [comment]
They share the same authetication API, but they use quite different API's for the actual functionality.

https://developer.husqvarnagroup.cloud/apis

So I am not convinced that merging these two bindings would make any sense at all.

**Comment by andrewfg** [comment]
I think that with #13263 the authentication issue of the OP #12980 has been resolved. So I am closing this one now.
