### ISSUE TITLE
[modbus.e3dc] Unwanted Switch state toggling after sending command

### ISSUE THREAD

**Issue by weymann** [openhab/openhab-addons#13172]
The Wallbox thing attached to an E3DC powerplant can take commands e.g. start / stop charging the car using a switch.  Unfortunately the command needs some time being processed by the device. 

**Current behavior**
- User send sommand ON to charge the car - Switch turns to ON
- next update cycle within a few seconds updates the channel - Switch turns to OFF
- after device performed command update cycle turns to "wanted" state - Switch turns to ON again

**Wanted behavior**
State update shall happen after device has handled the command

**Comment by ssalonen** [comment]
Would you say the binding is reporting the state as communicated by the device? So in a way the binding is working as expected?

You could get perhaps better support in community forums to deal with this, eg using openHAB rules to ignore state updates for x seconds after sending commands?

**Comment by weymann** [comment]
Thx for the hint. Seems to pinpoint the problem. Let me give it a try with the original bundle. If it works I'll enhance the readme and this issue can be closed.

**Comment by ssalonen** [comment]
@weymann any reports from the testing?

**Comment by weymann** [comment]
Had similat issue again for another binding and remembered this one.
`<autoUpdatePolicy>veto</autoUpdatePolicy>` is exactly doing this.
