### ISSUE TITLE
[daikin] Switch of Specialmode to NORMAL not working

### ISSUE THREAD

**Issue by pschlosser** [openhab/openhab-addons#13198]
I'm facing some problems with setting the special mode for my Daikin AC (BRP069B4x). Daikin Binding Version 3.3.0

Changing to POWERFUL mode is working fine, the Binding calls the following URL and the AC is changing to the Powerful mode:
[TRACE] [ing.daikin.internal.DaikinWebTargets] - Calling url: http://xx.xx.xx.xx/aircon/set_special_mode?spmode_kind=1&set_spmode=1

But if changing back to NORMAL mode, the Item changes its state to NORMAL and a second later back to POWERFUL. The Binding uses the following URL to set the mode:
[TRACE] [ing.daikin.internal.DaikinWebTargets] - Calling url: http://xx.xx.xx.xx/aircon/set_special_mode?set_spmode=0

When I try to call this URL manually, the Daikin Controller answers:
ret=PARAM NG

When I try this URL with added spmode_kind=1: http://xx.xx.xx.xx/aircon/set_special_mode?spmode_kind=1&set_spmode=0
I get an OK (ret=OK,adv=13) returned and the Daikin is changing to Normal Mode correctly.

Is there any reason, why the Binding don't uses spmode_kind=1 when changing back to NORMAL?

**Comment by jimtng** [comment]
Thanks for the report. So to summarise the correct URLs to call:

* To change to POWERFUL mode: `/aircon/set_special_mode?spmode_kind=1&set_spmode=1`
* To change to NORMAL mode: `/aircon/set_special_mode?spmode_kind=1&set_spmode=0`

1. Do you know how to change to ECO mode?
2. Can you test all the three above and let me know please?

**Comment by jimtng** [comment]
I am making a guess that spmode_kind=0 is for normal, =1 for powerful and =2 for eco. Please test this jar:
https://github.com/jimtng/openhab-addons/releases/tag/daikin-specialmode-v0.0.1

I don't have an aircon that supports this so I cannot test it myself.

**Comment by pschlosser** [comment]
Hi, unfortunately my aircon is not supporting ECO mode.

/aircon/set_special_mode?spmode_kind=0&set_spmode=0 is also declined with ret=PARAM NG

My guess is, that daikin app is using:
/aircon/set_special_mode?spmode_kind=1&set_spmode=0 -> Disabling Powerful Mode 

as the powerful mode is a standalone switch, not connected to any ECO mode..

So we might check for the actual adv value from get_control_info and use the active state for the switch to normal state.

**Comment by jimtng** [comment]
The information I've gathered so far:

- To change to POWERFUL mode: `/aircon/set_special_mode?spmode_kind=1&set_spmode=1`
- To change to NORMAL mode: `/aircon/set_special_mode?spmode_kind=1&set_spmode=0`
- `/aircon/set_special_mode?spmode_kind=0&set_spmode=0` doesn't work and won't change it to NORMAL
- `/aircon/set_special_mode?set_spmode=0` doesn't work and won't change it to NORMAL

I need someone to test how to change to ECO mode. My current guess is:
* to change to ECO mode: `/aircon/set_special_mode?spmode_kind=2&set_spmode=1`

@pschlosser please test this binding version:
https://github.com/jimtng/openhab-addons/releases/tag/daikin-specialmode-v0.0.2

**Comment by pschlosser** [comment]
0.0.2 is working as expected for change from POWERFUL to NORMAL.
thanks!
