### ISSUE TITLE
[linky] Connection broken again

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13196]
@clinique : did you notice that the binding is again broken ?
The thing is OFFLINE (COMMUNICATION_ERROR) with this message: Error getting url : 'https://apps.lincs.enedis.fr/authenticate?target=https://mon-compte-particulier.enedis.fr' 
I guess that it is failing at the very beginning, at this line in the code:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java#L92

**Comment by clinique** [comment]
Being back today, I noticed the same behavior on my side...

**Comment by clinique** [comment]
Found the solution to my jsoup issue [here](https://community.openhab.org/t/eclipse-error-with-binding-dependencies/135460/3?u=glhopital). Now I can investigate.

**Comment by clinique** [comment]
I think I spotted the issue as decribed [here](https://github.com/Benoit485/linky2jsonorinfluxdb/commit/deaf8f0a1290471ad1ce7923a44da9caf75b141e) : the problem comes from their certificate :hurtrealbad:

**Comment by lolodomo** [comment]
Closed by #13281
