### ISSUE TITLE
[velux] The binding should log critical maintenance errors for devices

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#13205]
### Current Behaviour

The hub already includes 'StatusReply' codes in its polling response messages, but currently these codes are ignored.

### Desired Behaviour

In future any 'StatusReply' codes that are critical errors shall be logged to `warn`, and non critical codes shall be logged to `debug`.

The critical codes are as follows..
```
BLOCKED,
POWER_CONSUMPTION_TOO_HIGH,
THERMAL_PROTECTION,
LOCK_POSITION_OPEN,
PRODUCT_NOT_OPERATIONAL,
DEAD_BOLT_ERROR,
FILTER_MAINTENANCE_NEEDED,
BATTERY_LEVEL,
NODE_WAITING_FOR_POWER
```

**Comment by andrewfg** [comment]
@gs4711 any thought about what other status codes should be considered as critical? 

See KLF API Specification chapter 10.1.3.7

**Comment by andrewfg** [comment]
Perhaps this (???)

https://community.openhab.org/t/velux-new-openhab2-binding-feedback-welcome/32926/1338?u=andrewfg

**Comment by gs4711** [comment]
@andrewfg you're right, but the battery fault reported by an GW_ERROR_NTF is somehow weired to mention?

Even if I have never received other error responses, I'd suggest to negate the 'StatusReply' code interpretation:
Log everything beside COMMAND_COMPLETED_OK with `warn`. 

This would include more than 30 codes never seen in my life...

**Comment by andrewfg** [comment]
Hi Guenther,

Apropos the “Eingeschraenkt durch Stromfluss”, it would be interesting to have your guess about which of the StatusReply codes below would most closely match the problem you experienced; it seems more like the POWER_CONSUMPTION_XX codes rather than the LIMITATION_BY_XX codes; or?? Or perhaps LIMITATION_BY_UPS ?? I think your error was with solar / battery powered devices?

```
public enum StatusReply {
     UNKNOWN_STATUS_REPLY(0x00),
     COMMAND_COMPLETED_OK(0x01),
     NO_CONTACT(0x02),
     MANUALLY_OPERATED(0x03),
     BLOCKED(0x04),
     WRONG_SYSTEMKEY(0x05),
     PRIORITY_LEVEL_LOCKED(0x06),
     REACHED_WRONG_POSITION(0x07),
     ERROR_DURING_EXECUTION(0x08),
     NO_EXECUTION(0x09),
     CALIBRATING(0x0A),
     POWER_CONSUMPTION_TOO_HIGH(0x0B),
     POWER_CONSUMPTION_TOO_LOW(0x0C),
     LOCK_POSITION_OPEN(0x0D),
     MOTION_TIME_TOO_LONG(0x0E),
     THERMAL_PROTECTION(0x0F),
     PRODUCT_NOT_OPERATIONAL(0x10),
     FILTER_MAINTENANCE_NEEDED(0x11),
     BATTERY_LEVEL(0x12),
     TARGET_MODIFIED(0x13),
     MODE_NOT_IMPLEMENTED(0x14),
     COMMAND_INCOMPATIBLE_TO_MOVEMENT(0x15),
     USER_ACTION(0x16),
     DEAD_BOLT_ERROR(0x17),
     AUTOMATIC_CYCLE_ENGAGED(0x18),
     WRONG_LOAD_CONNECTED(0x19),
     COLOUR_NOT_REACHABLE(0x1A),
     TARGET_NOT_REACHABLE(0x1B),
     BAD_INDEX_RECEIVED(0x1C),
     COMMAND_OVERRULED(0x1D),
     NODE_WAITING_FOR_POWER(0x1E),
     INFORMATION_CODE(0xDF),
     PARAMETER_LIMITED(0xE0),
     LIMITATION_BY_LOCAL_USER(0xE1),
     LIMITATION_BY_USER(0xE2),
     LIMITATION_BY_RAIN(0xE3),
     LIMITATION_BY_TIMER(0xE4),
     LIMITATION_BY_UPS(0xE6),
     LIMITATION_BY_UNKNOWN_DEVICE(0xE7),
     LIMITATION_BY_SAAC(0xEA),
     LIMITATION_BY_WIND(0xEB),
     LIMITATION_BY_MYSELF(0xEC),
     LIMITATION_BY_AUTOMATIC_CYCLE(0xED),
     LIMITATION_BY_EMERGENCY(0xEE);
```

**Comment by andrewfg** [comment]
> the battery fault reported by an GW_ERROR_NTF is somehow weired to mention?

Yup!  ;)

> Log everything beside COMMAND_COMPLETED_OK with warn.
> This would include more than 30 codes never seen in my life...

In the PR I am now logging the errors as follows..
- errors that sound like the user must do something => `logger.warn()`
- errors that sound like just for information only => `logger.info()`
