### ISSUE TITLE
[sonos] 'currenttrack' is not updated for Music Source 'RadioApp'

### ISSUE THREAD

**Issue by sbushnell** [openhab/openhab-addons#13208]
## Expected Behavior
current track should be updated as per other Music sources

## Current Behavior
current track is updated for Sonos Radio and TuneIn Music sources

## Steps to Reproduce (for Bugs)
Enable trace logging for Sonos binding 

## Logs
Below is the trace for TuneIn source which does display the current track in bold.
`11:41:52.441 [TRACE] [os.internal.handler.ZonePlayerHandler] - Received pair 'CurrentTrackMetaData':'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconntworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-http:*:application/octet-stream:*">x-sonosapi-stream:tunein%3a7128?sid=303&amp;flag=8232&amp;sn=4</res><r:streamContent>**Soft Cell - Tainted Love**</r:streamContent><r:radioShowMd></r:radioShowMd><r:streamInfo>bd:0,sr:0,c:0,l:0,d:0</r:streamInfo><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonosapi-stream%3atunein%253a7128%3fsid%d303%26flags%3d8232%26sn%3d4</upnp:albumArtURI><upnp:class>object.item</upnp:class></item></DIDL-Lite>' (service 'AVTransport') for thing 'sonos:One:RINCON_542A1BF85FD401400'`

Below is the trace for RadioApp source which does not update the current track in bold. It appears it does not like the "TYPE=SNG|TITLE" prefixed??
`11:48:06.093 [TRACE] [os.internal.handler.ZonePlayerHandler] - Received pair 'CurrentTrackMetaData':'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-http:*:application/x-mpegURL:*">x-sonosapi-hls:radioapp_svc_2MMM?sid=267&amp;flags=40&amp;sn=6</res><r:streamContent>TYPE=SNG|TITLE **Green Day - Time Of Your Life (Good Riddance)**|ARTIST |ALBUM </r:streamContent><r:radioShowMd></r:radioShowMd><r:streamInfo>bd:16,sr:24000,c:3,l:0,d:0</r:streamInfo><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonosapi-hls%3aradioapp_svc_2MMM%3fsid%3d267%26flags%3d40%26sn%3d6</upnp:albumArtURI><upnp:class>object.item.audioItem.musicTrack</upnp:class></item></DIDL-Lite>' (service 'AVTransport') for thing 'sonos:Amp:RINCON_48A6B868928F01400'`

## Your Environment
Running Openhab 3.3.0

**Comment by lolodomo** [comment]
This is finally an answer to my question in #7657.

Specific case of `x-sonosapi-hls` has to be supported.

**Comment by sbushnell** [comment]
Hi, It is Radio App (u=x-sonosapi-hls%3a**radioapp_svc**) released for Australia as per below from Sonos WebSite.

RadioApp and Sonos
What is RadioApp?
The simple way to listen to Australian radio. RadioApp has over 250 Australian radio stations. Find local stations near you and around Australia. Listen to live streams of radio, music, talk, sport and much more. New stations are being added all the time.

**Comment by sbushnell** [comment]
Just confirming when the binding is updated to support 'x-sonosapi-hls' it will support current Album Cover Art image?

**Comment by lolodomo** [comment]
Could you please investigate a little more about the syntax inside the tag r:streamContent? Is album and artist always empty? 
How looks the value when the content is a talk show or news for example? I assume TYPE will be different.

**Comment by sbushnell** [comment]
When news or talk show is playing the Tittle is always 'Advertisement_Stop' and TYPE unchanged as per below 

10:04:13.979 [TRACE] [os.internal.handler.ZonePlayerHandler] - Received pair 'CurrentTrackMetaData':'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-http:*:application/x-mpegURL:*">x-sonosapi-hls:radioapp_svc_2MMM90S?sid=267&amp;flags=40&amp;sn=6</res><r:streamContent>TYPE=SNG|TITLE Advertisement_Stop|ARTIST |ALBUM </r:streamContent><r:radioShowMd></r:radioShowMd><r:streamInfo>bd:16,sr:24000,c:3,l:0,d:0</r:streamInfo><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonosapi-hls%3aradioapp_svc_2MMM90S%3fsid%3d267%26flags%3d40%26sn%3d6</upnp:albumArtURI><upnp:class>object.item.audioItem.musicTrack</upnp:class></item></DIDL-Lite>' (service 'AVTransport') for thing 'sonos:Amp:RINCON_48A6B868928F01400'

**Comment by lolodomo** [comment]
@sbushnell : are you enough advanced with OH to test with a jar containing the enhancement ?

**Comment by lolodomo** [comment]
> When news or talk show is playing the Tittle is always 'Advertisement_Stop' and TYPE unchanged as per below

In the current PR, this will lead to "Advertisement_Stop" being displayed. Do you prefer that I bypass the title in that case ?

**Comment by sbushnell** [comment]
Thanks for the updated binding!  'currenttrack' now displays "Radio Station - Artisit - Song Title".  I see the Radio Station in the 
'currenttitle' not the Artisit - Song Tittle.  
Are you able to populate the 'currentartist' with the artisit from 'currenttrack' & 'currenttitle' with only the song tittle and not include the artisit or will this break something else....  possible have an option to change this display? 
The 'currentalbumart' is working

**Comment by sbushnell** [comment]
I am still seeing the 'Advertisement_Stop' in currenttrack

My Items
BackSonos_currenttrack (Type=StringItem, State=Triple M 104.9 - Advertisement_Stop, Label=Current Track
BackSonos_currenttittle (Type=StringItem, State=Triple M 104.9, Label=Current Title
BackSonos_currentartisit (Type=StringItem, State=, Label=Current Artist

CurrentTrackMetaData':'<DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"><item id="-1" parentID="-1" restricted="true"><res protocolInfo="sonos.com-http:*:application/x-mpegURL:*">x-sonosapi-hls:radioapp_svc_2MMM?sid=267&amp;flags=40&amp;sn=6</res><r:streamContent>TYPE=SNG|TITLE Advertisement_Stop|ARTIST |ALBUM </r:streamContent><r:radioShowMd></r:radioShowMd><r:streamInfo>bd:16,sr:24000,c:3,l:0,d:0</r:streamInfo><upnp:albumArtURI>/getaa?s=1&amp;u=x-sonosapi-hls%3aradioapp_svc_2MMM%3fsid%3d267%26flags%3d40%26sn%3d6</upnp:albumArtURI><upnp:class>object.item.audioItem.musicTrack</upnp:class></item></DIDL-Lite>' (service 'AVTransport') for thing 'sonos:Amp:RINCON_48A6B868928F01400'

**Comment by sbushnell** [comment]
RE: "Are you able to populate the 'currentartist' with the artisit from 'currenttrack' & 'currenttitle'....  I have created my own 3 items Station, Artist & Title using 'split' from currenttrack

**Comment by lolodomo** [comment]
@sbushnell ; you have a new jar available in the PR for testing.

**Comment by sbushnell** [comment]
Many thanks for your quick updates!! The artist, song title and handling of advertisement are all working correctly.
