### ISSUE TITLE
[wundergroundupdatereceiver] HANDLER_INITIALIZING_ERROR when using air quality sensor

### ISSUE THREAD

**Issue by pawel-sw** [openhab/openhab-addons#13214]
## Expected Behavior
Both autodiscovery and file creation of a Thing works when using an air quality sensor with the AqPM2.5 parameter.

## Current Behavior
When the weather station sends request with AqPM2.5 parameter the binding tries to create invalid thing witch channel that has dot character in it, this completely breaks servlet and shows HANDLER_INITIALIZING_ERROR in UI.
The exception is:
```
HTTP ERROR 500 java.lang.IllegalArgumentException: UID segment 'pollution#AqPM2.5' contains invalid characters. The last segment of the channel UID must match the pattern '[\w-]*|[\w-]*#[\w-]*'.
```

## Possible Solution
This is a design problem as the author used the query parameters directly in a thing channel names. 
A workaround would be to replace "." with "_" character before using the query parameter.

## Steps to Reproduce (for Bugs)
1. Install wundergroundupdatereceiver binding
2. Call ```http://{openhabhost:port}/weatherstation/updateweatherstation.php?ID=test&PASSWORD=12345&tempf=84.02&humidity=35&dewptf=53.42&windchillf=84.02&winddir=342&windspeedmph=0.00&windgustmph=0.00&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.020&monthlyrainin=0.000&yearlyrainin=0.370&solarradiation=38.47&UV=0&indoortempf=80.06&indoorhumidity=41&baromin=28.337&AqPM2.5=7.0&soilmoisture=43&soilmoisture2=38&lowbatt=0&dateutc=now&softwaretype=GW1100B_V2.1.5&action=updateraw&realtime=1&rtfreq=5```
3. Go to inbox and add discovered Thing
4. Thing is created in state HANDLER_INITIALIZING_ERROR, any further calls to the `updateweatherstation.php` endpoint fail with error  500 java.lang.IllegalArgumentException

## Your Environment
OpenHab and plugin version 3.3.0
Weather station Ecowitt GW1100 with ECOWITT WH41 Wireless PM2.5 Air Quality Sensor

**Comment by jlaur** [comment]
@danieldemus - FYI.

**Comment by danieldemus** [comment]
> @danieldemus - FYI.

Noted. Is there a process for patching released versions of a binding? I have another bugfix in the pipeline.
