### ISSUE TITLE
[enocean] Problem with autodiscover of USB300 gateway path

### ISSUE THREAD

**Issue by BillGOH** [openhab/openhab-addons#13224]
I am using the USB300 gateway with openHAB 3.3 on openHABian (Raspberry Pi 4). All USB ports are used. For that reason I have created alias names for every port (see [here](https://www.openhab.org/docs/administration/serial.html) for details). So the path to the gateway on my system is not /dev/ttyUSBX, but /dev/ttyUSBEnocean.

However, if I reboot the system the binding ignores the setting and tries to autodiscover the USB300 gateway and sets the path back to e.g. /dev/ttyUSB0. For reasons unknown to me this often does not work properly and the binding uses an incorrect path leading to a binding that does not work. I have to set the path back to /dev/ttyUSBEnocean manually. In my opinion the binding should disable autodiscover if a path has been set manually.

**Comment by lolodomo** [comment]
Can you tell me what thing type you are using, I could then check its definition (and see if representation property is set or not).

**Comment by lolodomo** [comment]
> For things having a representation property, I have a doubt if my workaround is working. That is to be checked.

I looked at the code. I am not 100% sure but I believe the presence or not of a representation property has no impact. So just defining a thing UID different from the "default" UID should avoid the behaviour you are mentioning.

The feature you are not liking (auto update of the parameters) is a deliberate feature, but to be honest with you, I do not remember what benefits it adds to the user.

**Comment by lolodomo** [comment]
Maybe a server setting should be added to disable this behaviour.

**Comment by BillGOH** [comment]
Hello @lolodomo! Thank your for your response and efforts. I cannot remember whether I installed the thing via autodiscover. I will try to recreate the thing with a custom ID in the next days and report my findings.

**Comment by BillGOH** [comment]
Hello @lolodomo. It seems to work. I created a new enocean bridge thing, added the path /dev/ttyUSBEnocean and it survived the reboot! Thank you very much.
