### ISSUE TITLE
incorrect documentation for broadlink thermostat thing.

### ISSUE THREAD

**Issue by kovaga** [openhab/openhab-addons#13237]
the documentation mentions setting the mac= parameter. However, the correct parameter that needs to be set is macAddress=

**Comment by lolodomo** [comment]
You're right.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.broadlinkthermostat/src/main/resources/OH-INF/config/config.xml#L14

Could you please submit the doc fix?

**Comment by kovaga** [comment]
by doc fix, do you mean the text that should go to the documentation?

**Comment by lolodomo** [comment]
I mean the update of the README.md file. You can do it directly in GitHub.

**Comment by lolodomo** [comment]
I have done it!
