### ISSUE TITLE
[wled] Preset Handling issues in UI

### ISSUE THREAD

**Issue by Ungeridus** [openhab/openhab-addons#13249]
Im not sure if this is a WLED plugin issue, An OpenHAB issue or a bad config on my part.

After updating OpenHAB to 3.3.0 and updating my configuration for the WLED 3.3.0 Binding I am getting some weird behavior.

I have 3 presets saved in WLED

"Default" saved to ID 1
"Playing" saved to ID 2
"Off" saved to ID 16

When selecting the presets on the item I linked to the bridge presets channel it lists the presets out of order and selects the wrong preset.

![default](https://user-images.githubusercontent.com/31721178/184200201-b12042dd-afe1-498b-9abe-fef5a3cc0a7b.png)

Clicking on Off selects the "Default" preset saved to ID 1
Clicking on Default selects the "Playing" preset saved to ID 2
Clicking on Playing Does Nothing

my events.log offered a hint with

[INFO ] [openhab.event.ItemCommandEvent      ] - Item 'WLED_Computer_Pre' received command 3

After Moving the "Off" preset to ID 3 in WLED - Clicking on Playing selects the "Off" preset saved to ID 3

With a test rule I can send the item commands of 1, 2 and 16 and it behaves correctly.
The problem only appears when selecting a preset in the Main UI or my Basic UI Sitemap

Ubuntu Server 22.04
OpenHab 3.3.0 running in docker
WLED 3.3.0

**Comment by lolodomo** [comment]
Looks like a binding issue when building the state options.

**Comment by Skinah** [comment]
Sorry only just seen this. Thanks for reporting it, I hopefully will find some time soon to look into it but the following may help.

The state options are only built or updated when you restart the thing/binding or send the REFRESH command. This means if you edit and change presets you need to trigger the update of the binding so they match. Easiest way to do this is pause and unpause the thing.

**Comment by Ungeridus** [comment]
Pausing and Un-Pauseing the Thing didn't fix it for me. 
I don't know if these are relevant but I also ran the bundle:refresh and bundle:restart commands on the WLed bundle in the console with no change.

It's not really an issue for me since I trigger the preset changes with rules.

**Comment by Skinah** [comment]
Feel free to try the JAR file that can be downloaded in the linked PR that contains a fix.

**Comment by Ungeridus** [comment]
Awesome, That did it.

Thank you for looking into this.
