### ISSUE TITLE
[Netatmo] Reenabling one decimal digit for pressure values

### ISSUE THREAD

**Issue by Yogi4301** [openhab/openhab-addons#13243]
Actually the values of the weather station for pressure#value and pressure#absolute are shown without any decimal digit like '1018'. By looking at the response from Netatmo you can see values like '1018.5'

Please reenable the binding to show the complete value from the Netatmo response like in older versions of the binding. I'm using openhab 3.3.0 on a RPi3.

`"dashboard_data":{"time_utc":1660115428,"Temperature":25.2,"CO2":436,"Humidity":48,"Noise":33,"Pressure":1021.5,"AbsolutePressure":1006.6,"min_temp":24.6,"max_temp":26.5,"date_max_temp":1660082595,"date_min_temp":1660112701,"temp_trend":"up","pressure_trend":"stable"},
`

**Comment by lolodomo** [comment]
@clinique: we just have to replace the third parameter from 1 to 0.5 (or 0.1) at this line ?
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java#L84

**Comment by clinique** [comment]
Will take a look but currently on holidays

**Comment by lolodomo** [comment]
@Yogi4301 : until the default channel pattern is changed, you can simply define your own state pattern on your item.

**Comment by Yogi4301** [comment]
@lolodomo I tried that by creating a new item - but it also shows xxxx.0. Am I doing something wrong?

`Number Air_Pressure "Pressure [%.1f hPa]" <pressure> (g_Netatmo) { channel="netatmo:weather-station:70ee50178726:pressure#value" }`

**Comment by jlaur** [comment]
@clinique - I'm on it, I hadn't seen you comment, but will assign you to PR coming up. :)
