### ISSUE TITLE
[homematic] temperature of HmIP-DRSI4 always null

### ISSUE THREAD

**Issue by davidgiga1993** [openhab/openhab-addons#13267]
## Expected Behavior
The same value as on the CCU should be shown 

## Current Behavior
The value is always null. I can get the temperature from the CCU using the following script:
```
var curTemp = (datapoints.Get("HmIP-RF.00259D89B06E08:0.ACTUAL_TEMPERATURE")).Value();
WriteLine(curTemp);
```
This implies that the value is correctly received from the actor.

When assigning an item to the channel its always null/0: `homematic:HmIP-DRSI4:ccu:00259D89B06E08:0#ACTUAL_TEMPERATURE`

## Steps to Reproduce (for Bugs)
1. Go to the DRSI4 thing
2. Select advanced channels
3. Link the temperature channel
Depending on the value type it will always stay null or 0

## Context
I would like to display and monitor the value in openhab

## Your Environment
OpenHab 3.3.0
Homametic Binding 3.3.0

**Comment by MHerbst** [comment]
Are there any messages in openhab.log? Can you see information about received events in events.log?

If you can't see anything please enable debug log mode for the Homematic binding, restart OH, wait for temperature changes and post the openhab.log starting from the restart.

**Comment by davidgiga1993** [comment]
Sorry for the late reply, I've just enabled debug logging and restarted openhab, and now the value works. I haven't touched anything else. Could it be that openhab requires a restart if a new HMIP device was onboarded? The DRSI4 device was added to the CCU while openhab was running and I've just added it via the inbox to openhab.

Do you still need the log from the startup?

**Comment by MHerbst** [comment]
No problem. Please check that the temperature values are really updated. When OH and the binding is started is explicitely requests the current values from the device. After that it waits for events that it receives from the CCU. If there values are not changing there may be a problem with the events.

I would only need a log if the values are not changing. If everything works fine now, please close this issue.

**Comment by davidgiga1993** [comment]
So after the last restart for collecting debug logs it seems to work just fine - including value updates. Thanks for your quick support!
