### ISSUE TITLE
[tado] Air Conditioning: Timer not resetting when switching AC off

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-addons#13270]
I have a Tado Smart AC Control in my house which is properly working.

## Expected Behavior
The timer duration is reset or set to "0" after triggering HAVC to "off".
When setting the timer duration to "0" the HAVC state is set to "off".

## Current Behavior
The timer remains counting and sends another api request to the Tado device, resulting in switching off an already switched of AC device (I hear just a beep without any action from my AC).

## Steps to Reproduce (for Bugs)
1. Setup a "Tado Home" Thing
2. Setup a "Tado Air Condition" Thing with "Tado Home" as Bridge and Zone-Id=2
3. Setup an Item for HAVC state
4. Setup an Item for timer duration
5. Set HAVC to e.g. "cooling", set any timer and then set HAVC to "off" > results in following state in the Tado UI (which doesn't make any sense to me)

![Screenshot_20220815_233307](https://user-images.githubusercontent.com/34278179/184724898-bdc56f25-61e2-4675-aac2-27bd86fbdc89.png)

## Your Environment
* Version used: openHAB 3.3.0 (stable)
* Hardware: RaspberryPi 4 8GB with PoE+ Hat
* Operating System and version: Ubuntu 22.04 Server for RasPi
* Other bindings installed: MQTT Broker, Netatmo

**Comment by andrewfg** [comment]
> Set HAVC to e.g. "cooling", set any timer and then set HAVC to "off"

The tado binding has a command buffer / pipeline. So if you send (say) the above three commands within a very short time, the commands will be merged into a single combined command set to the server. Whereas if you send the the above three commands each separated by a delay (say 30 seconds) then three separate commands are sent to the server.

=> @dandjo it would be interesting if you see the same behaviour in both of the above cases.

**Comment by dandjo** [comment]
The steps within 30 seconds (one command buffer)
* HAVC mode to "cooling"
* Timer to "02:30:00"
* HAVC mode to "off"
result in:
![image](https://user-images.githubusercontent.com/34278179/184911114-25fad655-6d62-41c6-b669-418056324e1e.png)

The steps in separate buffers result in
![image](https://user-images.githubusercontent.com/34278179/184912270-5ddcd67f-5071-4d4b-ac7a-4285a995fe89.png)

So there's no difference.

Additional info:
When a timer was previously set and running, the HAVC ist set to "off" and the timer changed to "0", the state will fall back to the previously set timer of "02:30:00" resulting in turning on the AC unit.

**Comment by dandjo** [comment]
I'm not able to set this status in the App. I guess it is technically possible, but not designated.

**Comment by andrewfg** [comment]
I am not sure that what you are reporting is actually a bug.

When you send a command, it comprises a bundle of (some or all of) the following elements.
1. Power e.g. on/off
2. Device mode e.g. cool/fan
3. Target temperature e.g. 23.0 C
4. Fan speed e.g. low/med/high
5. Swing e.g. on/off
6. Light e.g. on/off
7. Zone operating mode (@ duration) e.g. schedule/manual/until_change/timer @ duration

When you issue a Power:Off command (1.) then obviously items 2. thru 6. are not relevant, but item 7. **IS** still always relevant. The duration element is built from a combination of two channel values `zoneOperationMode` and `duration` whereby the former selects the mode and the latter is the duration in seconds that applies (only) for the 'timer' mode.

So if you are not specifically changing `zoneOperationMode` to 'manual' then when you send the Power:Off command, that command will also be sent for the duration that you had previously set in the respective items via the UI.

**Comment by dandjo** [comment]
As long as it's a valid status for the API, I agree that flagging it as an error isn't appropriate. Maybe there are scenarios where somone turns off the HAVC for a certain time? Is this possible? Thanks for the input, maybe I will try to work on a widget which sets the HAVC to "off" and the zoneOperationMode to "manual"

**Comment by andrewfg** [comment]
> Maybe there are scenarios where somone turns off the HAVC for a certain time?

Yes :)
