### ISSUE TITLE
[hdpowerview] Create channels dynamically depending on shade capabilities

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#13273]
### Background

As suggested in this [community forum thread](https://community.openhab.org/t/dynamically-created-channel-not-showing-up-in-main-ui/138150/3?u=andrewfg) we should perhaps create shade channels dynamically depending of the shade capabilities.

### Proposed Solution

The `secondary` and `vane` channels should be created dynamically depending on whether the shade reports support for a secondary vertical sliding panel (e.g. top down bottom up) or a shade with vane tilt capability.

### Open Issue

Input requested from @jlaur on the following..

In addition to the `secondary` and `vane` channels, there may be some other channels which may or may not be supported on different types of shades (e.g. `lowBattery` `batteryLevel` `batteryVoltage` on mains powered shades). So before finalising this issue and creating a respective PR we need to decide if such channels shall be included.

**Comment by jlaur** [comment]
@andrewfg - mains powered shades also provide battery/voltage-related channels. They can be powered either by external power supply or external battery, so the power source is actually configured by the user in the PowerView app and not built into the shade.
