### ISSUE TITLE
[velux] Wrong Serialnumber

### ISSUE THREAD

**Issue by carlep** [openhab/openhab-addons#13288]
Hi Community,
since the Update to 3.3 i have the issue, that my Velux Things are in state

HANDLER_CONFIGURATION_PENDING
{serial=Der Wert TerrasseLinks entspricht nicht dem Muster ([0-9A-Fa-f]{2}[:]){7}([0-9A-Fa-f]{2}).} 

It told me, that my Serialnumber is wrong and must be "Required Acht hexadezimale Ziffern (bspw. 65:23:3E:26:0C:1B:00:10)."

I still deleted the Things and scaned new. The new Thing appears with the same Serialnumber "TerrasseLinks"

I added a Screenshot with the Error.

Thanks for help!

Regards, Christian

![Unbenannt](https://user-images.githubusercontent.com/14252488/185410249-24fc0836-bf5f-4e91-9398-3d34c7204e19.PNG)

**Comment by carlep** [comment]
Yes, it's a Somfy Device via KLF200. I use this Configuration since 2.5 - 3.2. Since 3.3 I get this Problem.

**Comment by andrewfg** [comment]
^
Ok. I will look at it tomorrow.

**Comment by andrewfg** [comment]
I think this is explained in the documentation chapter "Thing Configuration for "actuator", "window", "rollershutter", Note 2)

https://www.openhab.org/addons/bindings/velux/#thing-configuration-for-actuator-window-rollershutter

**Comment by andrewfg** [comment]
@carlep I am closing this issue because is as it should be, and the error is because your device configuration is wrong

**Comment by carlep** [comment]
Hi Andrew,
sry for the late response, I wasn't at home. The Guide solved the problem, I looked in the Binding Documentation before, but didn't see it.
Thanks for the quick help and have a nice day :-)
