### ISSUE TITLE
[miele] Time inconsistencies and problems

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#13316]
I'm currently working on some rule logic for calculating the cheapest period for running my dishwasher. The goal is to make it finish at latest by the programmed end time, but with the possibility of triggering an earlier start based on electricity prices for each hour interval.

During this I found some inconsistencies in the time-based channels which I can work around, but which I think should be reviewed and could be candidates for improvements.

# The channels

In general the channels are of type `DateTime`, since there is no native type for containing a duration. First observations from this fact:
- Initialization is done by applying duration as epoch milliseconds to local time with time-zone "GMT+0". For example, if programmed start time is 6 hours from now, this would be stored as "1970-01-01T06:00+01:00" for CET, which equals 1970-01-01T05:00:00Z.
- Probably duration of more than 24 hours cannot be expressed correctly.

## start

- **Label:** Start Time
- **Description:** Programmed start time of the program

The actual value is the duration from now and until the program will start. This means that this channel will be updated every minute until the program starts. This doesn't seem consistent with the label or description.

In a rule, to get an `Instant` for when the program actually starts, some conversions/calculations are needed:

```javascript
val DateTimeType startTimeState = (Dishwasher_StartTime.state as DateTimeType)
val ZonedDateTime startTimeZoned = startTimeState.getZonedDateTime()
val programmedStart = now.plusSeconds(startTimeZoned.getHour() * 60 * 60 + startTimeZoned.getMinute() * 60).toInstant()
```

Because of time-zone issues, epoch seconds cannot be used directly as there will be an offset from local time-zone.

Proposal:
- Change to represent the actual start time, i.e. date and time. This would change the channel from being a countdown and instead contain full information about when the program will start. That of course also implies that the channel will no longer be updated each minute while in state **waiting to start**.
- Update state to **UNDEF** when no longer in state **programmed**/**waiting to start**/**running**.

## finish

- **Label:** Finish Time
- **Description:** Time to finish the program running on the appliance

The actual value is the duration from now and until the program will end. This means that this channel will be updated every minute until the program ends. This doesn't seem consistent with the label or description.

While the program is running, the could be interpreted as "Remaining Time", but until the program starts it seems somewhat strange to have this value count down.

Additionally there is a Miele bug when triggering start ahead of the programmed start time: Initially the original finish time is kept, and during the program this will catch up with the actual predicted finish time. Example - programmed to finish 07:00, but started ~01:00 using the **switch** channel:

```
2022-09-07 00:59:00.852 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T06:02:00.000+0100 to 1970-01-01T06:01:00.000+0100
2022-09-07 01:00:01.537 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T06:01:00.000+0100 to 1970-01-01T06:00:00.000+0100
2022-09-07 01:01:00.530 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T06:00:00.000+0100 to 1970-01-01T05:59:00.000+0100
2022-09-07 01:01:01.234 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T05:59:00.000+0100 to 1970-01-01T05:58:00.000+0100
2022-09-07 01:02:38.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T05:58:00.000+0100 to 1970-01-01T05:56:00.000+0100
2022-09-07 01:02:47.626 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T05:56:00.000+0100 to 1970-01-01T05:49:00.000+0100
2022-09-07 01:02:59.041 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T05:49:00.000+0100 to 1970-01-01T05:48:00.000+0100
2022-09-07 01:03:00.857 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T05:48:00.000+0100 to 1970-01-01T05:47:00.000+0100
...
2022-09-07 04:50:49.838 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T00:03:00.000+0100 to 1970-01-01T00:01:00.000+0100
2022-09-07 04:53:14.648 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_FinishTime' changed from 1970-01-01T00:01:00.000+0100 to 1970-01-01T00:00:00.000+0100
```

Proposals:
- Change to represent the actual end/finish time, i.e. date and time. This way the value should only change when the appliance reevaluates end time based on the running program.
- Additionally a channel "remaining" could be introduced containing remaining duration of running program.
- Consider renaming to "End Time" for clarity.
- Update state to **UNDEF** when no longer in state **programmed**/**waiting to start**/**running**.

## duration

- **Label:** Duration
- **Description:** Duration of the program running on the appliance

The actual value is:
- Total duration of program until the program starts.
- Remaining duration when program is running (like **finish**), i.e. countdown.

Proposals: None, since actual total duration is probably not available anymore when the program is running. Perhaps it should change to UNDEF at this point to not overlap with remaining, if this is introduced.

## elapsed

- **Label:** Elapsed Time
- **Description:** Time elapsed in the program running on the appliance

Proposals: None.

# Implementation notes

Start Time at 17:39 (local time):

```json
                {
                    "Name": "startTime",
                    "Value": 561,
                    "Polling": 0,
                    "Metadata": {
                        "unit": "min",
                        "Filter": "true",
                        "description": "Property name for the selected start time of the appliance.",
                        "LocalizedID": "Start Time",
                        "LocalizedValue": "3:00",
                        "access": "RWE"
                    }
                },
```

Value is start time in minutes from now. However, this is relative to the appliance's (or gateway's) clock. Therefore, using it to calculate absolute time is susceptible to subtle inaccuracies and undesired updates. Example - programmed to start 06:00:

```
2022-09-13 20:08:08.023 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_StartTime' changed from 2022-09-14T06:00:00.000+0200 to 2022-09-14T06:01:00.000+0200
2022-09-13 20:09:15.585 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_StartTime' changed from 2022-09-14T06:01:00.000+0200 to 2022-09-14T06:02:00.000+0200
2022-09-13 20:09:52.959 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Dishwasher_StartTime' changed from 2022-09-14T06:02:00.000+0200 to 2022-09-14T06:00:00.000+0200
```

Corresponding three payload snips:

openHAB timestamp: 2022-09-13 20:08:07.750
```
{
	"Name": "startTime",
	"Value": 593,
	"Polling": 0,
	"Metadata": {
		"unit": "min",
		"Filter": "true",
		"description": "Property name for the selected start time of the appliance.",
		"LocalizedID": "Start Time",
		"LocalizedValue": "6:01",
		"access": "RWE"
	}
}
```

openHAB timestamp: 2022-09-13 20:09:15.508
```
{
	"Name": "startTime",
	"Value": 593,
	"Polling": 0,
	"Metadata": {
		"unit": "min",
		"Filter": "true",
		"description": "Property name for the selected start time of the appliance.",
		"LocalizedID": "Start Time",
		"LocalizedValue": "6:02",
		"access": "RWE"
	}
}
```

openHAB timestamp: 2022-09-13 20:09:52.944
Multicast packet: `type=7&id=xxxxxxxxxxxx&property=startTime&value=591`

As seen, it actually wouldn't help much to use **LocalizedValue** as Miele@home itself has problems calculating a stable value because of internal implementation problems.

In order to avoid frequent updates with these small differences, some algorithm would be needed.

**Comment by jlaur** [comment]
@kaikreuzer, @kgoderis - I'm considering changing **start**/**finish** channels as proposed above, and possibly introduce a new **remaining** channel. Do you have any objections? @kaikreuzer, you changed **finish** into `DateTimeType` at some point:

https://github.com/openhab/openhab-addons/blob/c4625992afe56190e5e91763ca7fb45359ce169f/bundles/org.openhab.binding.miele/src/main/java/org/openhab/binding/miele/internal/handler/DishwasherChannelSelector.java#L45

In this commit: https://github.com/openhab/openhab2-addons/commit/d57c788ad9d0fff00be312b4b636d3e44cc9e863

But this seems to be from `StringType` to `DateTimeType`, so more of a technical correction. I'm now suggesting to keep `DateTimeType`, but change it to provide date + time instead of remaining duration until program starts (as a countdown).

**Comment by kaikreuzer** [comment]
Hey @jlaur everything you propose sounds sensible to me and I think it should be ok to do those breaking changes as I doubt that the current channels are much in use.

We should definitely add the suggested "remaining" channel, though, as this is what is usually interesting for interaction: The answer to "how long does it still take?".

**Comment by jlaur** [comment]
@kaikreuzer - as I was looking into **remaining**, I realized that **duration** already covers this. Raw values from API:
- **finishTime**: Number of minutes until end of program.
- **duration**: Number of minutes for program duration when programmed/waiting to run. When program starts, countdown will start and this value will be the same as **finishTime**.

Now when channel **finish** has been redefined, the time until end of program - before program starts - will no longer be available, but I don't think it has much use anyway. I would expect a channel called **remaining** to monitor a running program, and **duration** does exactly that.

#13393 is now ready.
