### ISSUE TITLE
[openweathermap] Repeated 401 errors with new api key due to deprecated URL for One Call Api

### ISSUE THREAD

**Issue by Argurth** [openhab/openhab-addons#13314]
## Expected Behavior

When I add a valid ApiKey to the binding it should work correctly

## Current Behavior

See https://community.openhab.org/t/openweathermap-onecall-invalid-api-key/138296

Actually, the call is made to the 2.5 version of the One Call API, but it is now deprecated and every new accounts get a 401 error when trying to use the binding.

## Possible Solution

Normally, just replacing 2.5 with 3.0 in the One Call APIs URLs should make the request valid (tested using a navigator)

## Steps to Reproduce (for Bugs)

1. Create a new account on OpenWeatherMap (it MUST be new, if you have an old Api Key, it should continue working for now)
2. Configure the binding following the documentation with the new Api Key
3. It should throw a 401 HTTP Error

## Context

I'm trying to use the weather for my rules and a widget in OpenHab but can't.

## Your Environment
* Version used: OpenHab 3.3, OpenWeatherMap 3.3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox, Java 8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): OpenHabian

**Comment by JuWag81** [comment]
Hi, 
also having the same problem like described in the linked community post. 
Is there any update on this topic or something I could change myself to make it work temporarly until a fix is released?

**Comment by drrgrewe** [comment]
You can change the API URLs in `OpenWeatherMapConnection.java` as suggested by @Argurth and build the plugin - I did just that and it works. But you need an API key for the Call-by-Call (v3.0) API and you need to sign up with your credit card for that service. 1000 calls/day are free and you can set a limit of daily calls - so you do not have to pay for anything.

**Comment by cweitkamp** [comment]
One question: Aren't you able to sign-up for the free subscription anymore?

I am afraid just changing the URL to 3.0 version of the One Call API will lock out all the other users having an old API key. Mine doesn't work with the new API but with the old one. We will need an additional configuration for the One Call Weather Thing to let the user choose which API version to be used.
