### ISSUE TITLE
[linky] Communication error

### ISSUE THREAD

**Issue by xebmin** [openhab/openhab-addons#13336]
Hello,

I've read some people had the same issue but after completing username, password and authId retrieved in cookies, I keep getting the "communication error" :
 
COMMUNICATION_ERROR
Error getting url : 'https://apps.lincs.enedis.fr/authenticate?target=https://mon-compte-particulier.enedis.fr'

When I open it in my browser, everything is fine I can grab informations about Linky.

**Comment by wborn** [comment]
Did you try 3.4.0-SNAPSHOT? It has this fix https://github.com/openhab/openhab-addons/pull/13281.

**Comment by xebmin** [comment]
Thank you for your answer. I thought fix was applied on milestone version which I used but you are right. I changed for snapshot version and this error is now vanished... 
But got a new one : "Error opening connection with Enedis webservice".  I searched for similar problems and cookies seemed to be the first aim.
I use openhab docker on Unraid Server if that might help.

**Comment by wborn** [comment]
Maybe it works better with Docker if you set the environment variable:

`CRYPTO_POLICY=unlimited`

See: https://github.com/openhab/openhab-docker#java-cryptographic-strength-policy

**Comment by xebmin** [comment]
It works like a charm! Thanks for your support 👍

**Comment by wborn** [comment]
Great! :partying_face:

**Comment by lolodomo** [comment]
Maybe you could enhance the binding documentation to mention the docker requirement.

**Comment by gd35** [comment]
I tried the latest openhab snapshot and ran it on a rpi4 without using Docker. Unfortunately, connecting to the enedis web site seems to fail:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/6339942/189529938-9d77b085-a858-452c-a480-be0f5d96bfa0.png">

I checked login name, password and internalAuthId. They are all correct.

Any idea to solve this issue ?

**Comment by gd35** [comment]
I tried the latest openhab snapshot and ran it on a rpi4 without using Docker. Unfortunately, connecting to the enedis web site failed. I checked login name, password and internalAuthId. They are all correct.

Any idea to solve this issue ?
