### ISSUE TITLE
[squeezebox] Add channels for composer, band and conductor tags.

### ISSUE THREAD

**Issue by schup011** [openhab/openhab-addons#13353]
In the squeezebox add-in, there is only a limited set of tags of the played music piece, such as title, artist, year and so on available as player thing channels.

It would be great to enhance this set by some tags commonly used with classical music pieces, such as:

COMPOSER
BAND
CONDUCTOR

Is it possible to add those?

**Comment by mhilbush** [comment]
If those tags are returned by the LMS in the status message, then it would be pretty straightforward to add new channels for these tags.

To see the status message, and whether or not those tags are included, you would need to enable TRACE level logging.

**Comment by schup011** [comment]
I looked with TRACE level enabled, but unfortunately the status message doesn't contain those tags. I am not familiar with the LMS CLI, so maybe the status message can be configured to display those?

**Comment by schup011** [comment]
OK, I found something. You can configure the status query to contain more (or other?) tags. 

This is what I could get (first line my query, from second on the response from the server):

`aa:bb:cc:dd:ee:ff status - 1 tags:A`
`aa%3Abb%3Acc%3Add%3Aee%3Aff status - 1 tags%3AA player_name%3ApiCorePlayer player_connected%3A1 player_ip%3A192.168.x.y%3A39052 power%3A1 signalstrength%3A0 mode%3Aplay time%3A525.891481090546 rate%3A1 duration%3A1644.711 can_seek%3A1 mixer%20volume%3A36 playlist%20repeat%3A0 playlist%20shuffle%3A0 playlist%20mode%3Aoff seq_no%3A0 playlist_cur_index%3A0 playlist_timestamp%3A1662403022.92523 playlist_tracks%3A5 digital_volume_control%3A0 playlist%20index%3A0 id%3A112368 title%3ADas%20Buch%20mit%20den%20sieben%20Siegeln%20-%20Erster%20Teil albumartist%3A%C2%A0 band%3ASymphonieorchester%20und%20Chor%20des%20Bayerischen%20Rundfunks composer%3AFranz%20Schmidt conductor%3AFranz%20Welser-M%C3%B6st trackartist%3AStig%20Andersen%2C%20Ren%C3%A9%20Pape`

**Comment by schup011** [comment]
The documentation that the standard tag configuration is "tags:gald" = genre, artist, album, duration.
Should be sufficient to query "... tags:Agald". The "A" stands for a whole list of all artists like:
albumartist
trackartist
band
conductor
composer

**Comment by mhilbush** [comment]
Yeah makes sense. The binding currently sends this.
```
tags:yagJlNKjc
```

**Comment by schup011** [comment]
I found the status query in SqueezeBoxServerHandler.java, line 100:

`private static final String JSONRPC_STATUS_REQUEST = "{\"id\":1,\"method\":\"slim.request\",\"params\":[\"@@MAC@@\",[\"status\",\"-\",\"tags:yagJlNKjcB\"]]}";`

would have to be changed to 

`private static final String JSONRPC_STATUS_REQUEST = "{\"id\":1,\"method\":\"slim.request\",\"params\":[\"@@MAC@@\",[\"status\",\"-\",\"tags:yagJlNKjcBA\"]]}";`

I would request to add channels for:

albumartist
trackartist
band
conductor
composer

**Comment by mhilbush** [comment]
@schup011 Are you interested in trying out a version of the binding that includes channels for those tags?

**Comment by schup011** [comment]
Yes, would be happy to, thanks a lot! Could you provide some instructions how to install the new version of the binding?

**Comment by mhilbush** [comment]
This is the file to download
https://github.com/mhilbush/openhab-binding-releases/blob/master/squeezebox/org.openhab.binding.squeezebox-3.4.2-SNAPSHOT.jar?raw=true

Instructions for installing are here.
https://github.com/mhilbush/openhab-binding-releases/tree/master/squeezebox

Note: The new channels are designated "advanced", so you need to tick the advanced checkbox in the UI to see them.

**Comment by schup011** [comment]
It works perfectly. Thank you very much. I tested albumartist, trackartist, composer, conductor, band.
They all display the correct values! Thanks again.
