### ISSUE TITLE
Implement Ecowatt Binding

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13351]
I plan to create a binding for Ecowatt : https://www.monecowatt.fr
Of course, this would be something of interest only for the French users.
On the Website, they announce a simplified API to be released during the month of September. So I will wait for this new version.
The only small "challenge" will be the required OAuth2 authentication.
@clinique : you could be interested ? Maybe you are already working on that ?

**Comment by clinique** [comment]
No, I don't know this service but you'll have my helping hand
