### ISSUE TITLE
[goecharger] Temperature Readouts not availabe

### ISSUE THREAD

**Issue by Firebird231** [openhab/openhab-addons#13370]
Hi,
with openhab 3.2.0 and the official binding I can't acess the temperature values.

Number:Temperature         GoEChargerTemperatureType2Port       "Temperature type 2 port"    <temperature>    (gTemperature)      {channel="goecharger:goe:8653ddaeb4:temperatureType2Port"} 
=> Undefined

Number:Temperature         GoEChargerTemperatureCircuitBoard    "Temperature circuit board"  <temperature>    (gTemperature)      {channel="goecharger:goe:8653ddaeb4:temperature"} 
=> NULL

**Comment by lsiepel** [comment]
I see [several PR's](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+in%3Atitle+goecharger+created%3A%3E2020-12-12+) after release 3.2.0. Can you confirm this is still an issue with 3.4.0?

**Comment by Firebird231** [comment]
Still an issue in 3.4.3.Von meinem iPhone gesendetAm 31.12.2022 um 15:23 schrieb lsiepel ***@***.***>:﻿
I see several PR's after release 3.2.0. Can you confirm this is still an issue with 3.4.0?

**Comment by lsiepel** [comment]
You mean 3.3 or 3.4? I think you made a type as 3.4.3 is not out yet.
If the problem is still there with 3.4.0 we can try to fix it. Are you able to provide a debug log when you initialize the thing with these channel linked to an item?

**Comment by Firebird231** [comment]
I‘ll send a debug log by next week!Happy New Year!!Von meinem iPhone gesendetAm 31.12.2022 um 20:35 schrieb lsiepel ***@***.***>:﻿
You mean 3.3 or 3.4? I think you made a type as 3.4.3 is not out yet.
If the problem is still there with 3.4.0 we can try to fix it. Are you able to provide a debug log when you initialize the thing with these channel linked to an item?

**Comment by lsiepel** [comment]
@Firebird231 Would be nice to have those files as i do have some time the next few weeks to look at it.
