### ISSUE TITLE
[pioneeravr] Volume set for VSX 528 like AVRs

### ISSUE THREAD

**Issue by joeduck** [openhab/openhab-addons#1344]
Hi,
very nice Binding. It works very well for me. But some receivers, like my VSX 528, has no volume set command (VL), only VU and VD. For my homematic i had a workaround with a loop who set the Volume with x VU/VD commands. It would be nice, the binding has a function like this.

Here some code, sadly i am no java programmer (i am at the end no Programmer ;-))
This code is from http://forum.logicmachine.net/showthread.php?tid=15

`function setvolume(host, port, volumelevel)

  local currentvolume = getvolume(host, port)

  if volumelevel > currentvolume then
    for i = currentvolume, volumelevel -1, 2 do
      telnetsend(host,port,VOLUME_UP)
    end
  else
    for i = volumelevel, currentvolume-1, 2 do
      telnetsend(host,port,VOLUME_DOWN)
    end
  end

  currentvolume = getvolume(host, port)
  return currentvolume

end

`

Greetings, Jochen
##

**Comment by Stratehm** [comment]
I will take a look at it. 

The main question is how to detect that an AVR support or not the "Set volume" request. My AVR support it so I cannot test it. Could you try to open a telnet connection to your AVR and send a 001VL command (request to set the volume to -80.0 dB) ? What is the response of the AVR (maybe E4) ?

**Comment by joeduck** [comment]
HI. Many thanks! Sadly my receiver is by pioneer Germany for repair. It was not reachable on the lan any more. I have to wait 6 Weeks told me the repair station :-( .

Perhaps you can make a parameter in the binding for receivers without VL command like "vl=no"?

**Comment by joeduck** [comment]
Hi,
i have my Receiver back. If I send the „001VL“ command, nothing Comes back. „?V“ gives the volume back. It would be great if you make a try.

**Comment by Stratehm** [comment]
Ok thanks for the test. A new version should soon be ready, but my AVR supports the Set Volume command so I cannot really test the new implementation. Will you be able to make some test with the new binding version when it is ready ?

**Comment by Sschhsd** [comment]
![test](https://cloud.githubusercontent.com/assets/2945621/20934422/5d7db568-bbdb-11e6-95be-4bdc568a19f7.PNG)

**Comment by joeduck** [comment]
Hi,

many thanks for your work on this. I also can do tests with my vsx 528k

**Comment by Stratehm** [comment]
Could you test the new [binding](https://github.com/Stratehm/openhab2-addons/releases/tag/2016-12-10) version ? It is a jar file that you have to put in the addons folder of your openhab2 installation. (Make sure to have uninstalled the old binding before).

**Comment by joeduck** [comment]
Hi,
i vaed stoped openhab. Then i has copied it to "/usr/share/openhab2/runtime/karaf/system/org/openhab/binding/org.openhab.binding.pioneeravr/2.0.0.b4" and renamed to "org.openhab.binding.pioneeravr-2.0.0.b4.jar". then i started openhab "service openhab2 start".

Then i removed it from paperui and added again. I use "autodetect" but the avr is shown offline.
I go on testing. Thanks

**Comment by Spilota** [comment]
If you're avr is shown as offline, you may need to cycle power to free up the telnet connection.

**Comment by Sschhsd** [comment]
My Pioneer is online and linked.

- removed Pioneer-binding (OpenHab2 PaperUI)
- stoped openhab2-service
- copied new binding to /usr/share/openhab2/addons
- started openhab2-service

when i press the volume up button, then the volume will be set to max volume (like the script hangs up)...

**Comment by joeduck** [comment]
Did a new try like Sschhsd decribed. But the AVR ist still shown as offline. But i can get the Volume with  "printf '%s\r\n' ?V | nc 192.168.178.15 8102" and switch Power, VU, VD and so on on cmdline.
Whar is wrong?

**Comment by joeduck** [comment]
If I go to "things" an show properties, IP and protocol shown empty. When I go to the edit Button, the configuration Parameters are right. My AVR listen to Port 8102

**Comment by joeduck** [comment]
after a restart of openhab2 the AVR is shown online. But no command works. On Commandline i can do commands to the avr.

**Comment by Sschhsd** [comment]
Do you update your channel-ids in your items.config?

Befor i removed the pioneer-binding, i have deleted the pioneer-thing (openha2 paperui). After i have copied the new bining, i add manually my pioneer with IP-Adresss and Port Number. I set the new settings "volume-auto..." to disabled.

**Comment by Stratehm** [comment]
Thank you all for testing.

To let me investigate your problems, I will need your binding debug logs. Could you add the following lines to your logback.xml file (at the end of the file, but before the _\</configuration\>_ line) ?

```   
<appender name="PIONEERFILE" class="ch.qos.logback.core.FileAppender">
        <file>${openhab.logdir:-userdata/logs}/pioneer.log</file>
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-30.30logger{36}:%-5line] - %msg%ex{10}%n</pattern>
        </encoder>
    </appender>
    
    <logger name="org.openhab.binding.pioneeravr" level="DEBUG" additivity="false">
        <appender-ref ref="PIONEERFILE"/>
    </logger>
```

After restarting openHab, it will create a new file named _pioneer.log_ in your log directory containing the debug logs of the binding. Play a bit with the binding to generate enough data, post the file.

**Comment by Sschhsd** [comment]
Where i can find the logback.xml in openhab2?

There is no logback.xml at path /etc/openhab2/logback.xml...

**Comment by Stratehm** [comment]
My bad, it is a development file.

Append the following lines to <openhabInstallDir>/runtime/karaf/etc/org.ops4j.pax.logging.cfg :

```
# Pioneer Binding debug
log4j.logger.org.openhab.binding.pioneeravr=DEBUG,pioneer
log4j.additivity.org.openhab.binding.pioneeravr=false
log4j.appender.pioneer=org.apache.log4j.RollingFileAppender
log4j.appender.pioneer.layout=org.apache.log4j.PatternLayout
log4j.appender.pioneer.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n
log4j.appender.pioneer.file=${openhab.logdir}/pioneer.log
log4j.appender.pioneer.append=true
log4j.appender.pioneer.maxFileSize=10MB
log4j.appender.pioneer.maxBackupIndex=10
```

**Comment by Sschhsd** [comment]
Thank you.

Logging is enabled. I will do some tests and will provide you the log-file, at the next few days.

**Comment by Spilota** [comment]
I've tested this implementation of the volume set on a VSX-1122.  It appears to be working as expected.  When the slider is moved too far, it does have some trouble keeping up.  Log file below
[pioneer - VSX-1122 Unsupported.zip](https://github.com/openhab/openhab2-addons/files/644704/pioneer.-.VSX-1122.Unsupported.zip)

**Comment by Stratehm** [comment]
Improved volume level  tracking with this [version](https://github.com/Stratehm/openhab2-addons/releases/tag/2016-12-13)

**Comment by Sschhsd** [comment]
It doesn't work. same issue with the max volume, when i pressed volume up one time....


[pioneer.txt](https://github.com/openhab/openhab2-addons/files/649031/pioneer.txt)

**Comment by joeduck** [comment]
Hi. Did some testings with the latest version. It works 1 or 2 times. then the Volume runs max Vol or low vol. I have enabled the logging, but where can i finde the logfiles in karaf? Realy: Doont understand the Openhab2 file system :-( .

**Comment by Stratehm** [comment]
@joeduck the log file is located here : openhabInstallDir/userdata/logs/pioneer.log

A new version of the binding is [available](https://github.com/Stratehm/openhab2-addons/releases/tag/2016-12-22). It is an heavy refactoring with breaking changes. Before installing this version, be sure to remove your AVR Things.

Now, to declare things, the AVR model as to be one of the list (no more ipAvr):

- VSX-921
- VSX-529
- VSX-1122
- VSX-1021
- genericAvr

genericAvr has to be used for AVR that are not yet supported. If you have an AVR that is not supported, you can try the genericAvr with default configuration or play with the parameters of the thing in PaperUI. If you find the configuration that works with your AVR, please tell me and I will add your AVR in the supported list.

You can also enable the logs as described above, play with your AVR genericAvr and give me the log, I will try to extract the good parameters for your AVR.

Thank you all for testing.

**Comment by Sschhsd** [comment]
Thank you!

I have the same issue. When i press volume up, the volume is set to max.


[pioneer.txt](https://github.com/openhab/openhab2-addons/files/670554/pioneer.txt)

**Comment by Spilota** [comment]
Testing this with the VSX-1122 and VSX-1021, it is working great. I'm using the VSX-1021 and VSX-1022, which both support the set volume command.  Log file below in case you need it.

[pioneer.txt](https://github.com/openhab/openhab2-addons/files/670885/pioneer.txt)

A couple small issues:

- The slider for Zone 2 dB volume is scaled -80 to 12 dB ( instead of the configured parameters, -80 to 0 in my case).  I love how the dB volume is now a slider.  The tracking works well.

- Although my VSX-1122 was discovered as a thing, I was not able to add it directly.  I got "Error: 500 - Internal Service Error", but I didn't see anything in the log.  I added it as a generic device and it worked fine.

The 2011 and 2012 models listed below _should_ be supported, they all support the same basic command set:

- SC-1222
- SC-55
- SC-57
- SC-61
- SC-63
- SC-65
- SC-1522
- SC-67
- SC-68
- VSX-1021
- VSX-1022
- VSX-1121
- VSX-1122
- VSX-42
- VSX-50
- VSX-51
- VSX-52
- VSX-522
- VSX-53
- VSX-60
- VSX-822

Thanks for all the work on this!

**Comment by joeduck** [comment]
Many Thanks for your work! Now it works correct with my VSX-528-K. It was recognized as VSX-528-K and Generic AVR. I let all on standard settings but change port to 8102.

Again: Many thanks!
One OT question: How can i set the Volume with a script without the Slider to a absolute value?

**Comment by Sschhsd** [comment]
@Stratehm Any update for my issue?

**Comment by Stratehm** [comment]
Sorry guys, I am really out of time for now. I am still working on the refactoring of the binding (the previous snapshots were an intermediate state) but not as fast as I would like.

I will try to give you some updates of the advancement...

**Comment by joeduck** [comment]
O.k. Thanks for your Work. One Thing: If I restart openhab2 the binding forgets the Port. The Port of my Receiver is 8102. If i set this in the Paper UI, the AVR is still offline. Looking at the log, shows it wants to connect still to Port 23.

**Comment by mbuchberger1967** [comment]
Hi all,
I have the same issue with my VSX-828. According to some doc I found in the internet "VSX-82TXS RS232C Protocol, 2006" the VSX-82 series should know the VOLUME_SET command, but with 2 digits: XXVL<CR>

When I tried the current pioneer binding I noticed that everything works, except for the VL command. I supposed it is because of the 2 or 3 digits (OH sends 3 digits, my spec said 2 digits). SO I downloaded the source for the binding and changed the command to 2 digits, but no effect. 
As far as I know VSX528 and 828 are very similar, so now I guess my VSX-828 doesnt know the command.

My questions:
1. Can someone send me the spec for the IP protocol for VSX-528/828 ?
2. In the stable relase the modification discussed here seems not yet to be delivered? Can I get this binding that support 528/828 model 2012?
3. Can I get access to the source as well?
4. My VSX-828 often answers with an "R" response which is not recognized by the binding. Could we add this? I could do impl and testing if I get some hints what to do.

Thanks Markus

**Comment by mbuchberger1967** [comment]
Hi,

I found a link in this post to a special snapshot from 23-12-2016, but if I install this one I'll get an exception "hostname can't be null" though I configured the IP and port. The port alwys shows 23, the address is empty in PAPER UI and if I modify the parameters in the UI I cannot save them (Erro 409 Conflict)

Any ideas?

**Comment by mbuchberger1967** [comment]
@Stratehm 
Can u give us an update about the refactoring?
I'm really awaiting the solution to set a volume for VSX_528/828 by sending multiple VU/VD commands.

Maybe this is already avail in a snapshot?

Cheers markus

**Comment by Sschhsd** [comment]
Hi @Stratehm,

could you please implement a simple VolUp and VolDown-Channel (like advanced commands at binding for openhab 1.x)? Your slider does not work for my pioneer.

Thanks in Advance.

**Comment by Sschhsd** [comment]
Hi @Stratehm 

after i reboot my openhab-service, i get this error with all channels:
Command for zone 1 not send since zone 1 is not supported by the AVR@192.168.0.5:8102.

[pioneer.txt](https://github.com/openhab/openhab2-addons/files/949104/pioneer.txt)

Pioneer-Snapshot: 2016-12-22 SNAPSHOT

**Comment by Sschhsd** [comment]
Hi @Stratehm,

i think there is a timeout problem at checking the support for zone 1. Could you please increase the timeout.

2017-04-23 09:48:52.854 [DEBUG] [internal.protocol.ip.IpAvrConnection] - Connected to 192.168.0.5:8102
_2017-04-23 09:48:52.859 [DEBUG] [nternal.protocol.StreamAvrConnection] - Command sent to AVR @192.168.0.5:8102: ?P_
**_2017-04-23 09:48:53.365 [DEBUG] [oneeravr.internal.handler.AvrHandler] - Timeout during checkStatus.
java.util.concurrent.TimeoutException: No response received after 500 ms for the command ?P**
_2017-04-23 09:49:16.942 [DEBUG] [nternal.protocol.StreamAvrConnection] - Command sent to AVR @192.168.0.5:8102: ?P_
2017-04-23 09:49:17.444 [INFO ] [oneeravr.internal.handler.AvrHandler] - Zone 1 not supported. Cause: Timeout.
**2017-04-23 09:49:18.903 [DEBUG] [nternal.protocol.StreamAvrConnection] - Data received from AVR @192.168.0.5:8102: PWR0**
2017-04-23 09:49:18.907 [DEBUG] [nternal.protocol.StreamAvrConnection] - Data received from AVR @192.168.0.5:8102: PWR0

Thanks in Advance.

**Comment by Sschhsd** [comment]
Hi @Stratehm,

could you please provide me a new snapshot includes the latest commits?

Thank in advance.

**Comment by joeduck** [comment]
Hi,

I am also interrestet.

Thanks

**Comment by Sschhsd** [comment]
Hi @Stratehm 

i have testet the newest release of OpenHab (openHAB 2.2.0 Build #106). Your Snapshot 2016-12-22 SNAPSHOT does not work anymore with the latest OpenHab-Release. The pioneer-binding which is included into the latest snapshot of openhab does not have your implementation for my pioneer vsx-529.

Are you interested to insert your implementation to the official pioneer binding or could you please provide ma a new snapshot?

Thanks in Advance.

**Comment by Stratehm** [comment]
Hi @Sschhsd,

Could you test the last SNAPSHOT I have built 2 weeks ago? [Here](https://community.openhab.org/t/new-pioneeravr-version-for-testing/34861/1) is the details of the version. 

Thank you for your help.

**Comment by joeduck** [comment]
Hi Strathem,

wich version is now actual? I am on Openhab 2.2 with the Pioneer Addon wich comes with this Release. I have my Pioneer VSX-528 configured as "genericAvr". But the Volume Adust does not work like the old Version. I can not adjust the Volume propper. I have all settings testet and need help.

Can you give me a hint?

Thankes, Jochen

**Comment by thebeater** [comment]
Hi @Stratehm,

is your binding in the official Release for Version Openhab 2.4 integrated with the setvolume Feature. Ican't get it working because no Version of the Pioneer's in the "choose thing"-Dialog is working for me.

Could you provide an Snapshot or inform when you plan the integration in Openhab official?

**Comment by thebeater** [comment]
@joeduck Did you get the binding working?

**Comment by J-N-K** [comment]
According to https://github.com/openhab/openhab2-addons/issues/1344#issuecomment-269010761 the original issue was solved. @Stratehm are these changes merged? If not, can you point me to the PR or raise a new PR? Thanks.

**Comment by nils** [comment]
I have an VSX 528 as well, currently maintaining my own copy of the binding to support it.

@Stratehm: Do you see a chance that you finish your refactoring? Otherwise I could try and tackle the topic.

**Comment by hmerk** [comment]
closed due to inactivity.
