### ISSUE TITLE
[shelly] Shelly TRV "Open Window" function and target temperature in OpenHAB

### ISSUE THREAD

**Issue by dralli72** [openhab/openhab-addons#13450]
Hello,

I am currently testing my first smart radiator valve. I chose the "Shelly TRV" together with "Shelly Door/Window 2". One idea is, that the valve closes when the corresponding window opens.

Both devices are added to OpenHAB through the Shelly binding.

Shelly TRV offers a HTTP endpoint "http://<IP-of-TRV>/window/state=xxx" (with "xxx" set to "open" or "close") to change the target temperature to 8°C when the window is "open" and return the target temperature to the previous state when the window is "close".

Shelly DW2 offers the possibility to access a URL when the window is opened or closed. I thought that this would be the easiest way to implement the needed behaviour.

Unfortunately, the event log in OpenHAB shows some events for the target temperature that should not be there. I have already reached out to Shelly support, but according to the debug log from TRV, everything works fine on their side.

## Expected Behavior

1. Current State: Window is closed, TRV has a target temperature of 21°C
2. The window is opened, Shelly DW2 wakes up and accesses `http://<IP-of-TRV>/window?state=open`. The new state and tilt of DW2 is also logged in OpenHAB event log.
3. Shelly TRV sets its target temperature to 8°C. This is also logged in OpenHAB event log (`Item 'TRV_target_temperature' changed from 21 °C to 8 °C`)
4. As long as nothing changes, nothing should happen with DW2, TRV or OpenHAB
5. When the window is closed, Shelly DW2 wakes up and accesses `http://<IP-of-TRV>/window?state=open`. The new state and tilt of DW2 is also logged in OpenHAB event log.
6. Shelly TRV sets its target temperature back to 21°C. This is also logged in OpenHAB event log (`Item 'TRV_target_temperature' changed from 8 °C to 21 °C`)

## Current Behavior

Currently, OpenHAB logs (randomly?) some events during step 4.

Today, I got about 2 minutes after the window has been opened the event `Item 'TRV_target_temperature' changed from 8 °C to 21 °C` in OpenHAB events log, although the window has not been closed. I closed the window after about 17 minutes, and no event from TRV is logged in OpenHAB. TRV itself (the device) showed the new temperature on its display. The debug log of TRV (`http://<IP-of-TRV>/debug/log`) always shows a target temperature of 8°C while the window was open and 21°C before and after.

Today's two line from OpenHAB's events.log:
```
2022-09-26 18:31:39.113 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TRV_target_temperature' changed from 21 °C to 8 °C
2022-09-26 18:33:41.507 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TRV_target_temperature' changed from 8 °C to 21 °C
```

The "minute ticks" from the Shelly TRV debug log:
```
1664209860.466 minutes_tick:	Target: 21.0C; Current: 21.07C; Correction: -0.66C; Pos: 39.38% -> 39.38%
1664209920.453 minutes_tick:	Target: 8.0C; Current: 21.04C; Correction: -0.65C; Pos: 39.38% -> 0.00%
1664209980.362 minutes_tick:	Target: 8.0C; Current: 21.02C; Correction: -0.65C; Pos: 0.00% -> 0.00%
1664210040.398 minutes_tick:	Target: 8.0C; Current: 20.99C; Correction: -0.63C; Pos: 0.00% -> 0.00%
1664210100.472 minutes_tick:	Target: 8.0C; Current: 20.99C; Correction: -0.62C; Pos: 0.00% -> 0.00%
1664210160.399 minutes_tick:	Target: 8.0C; Current: 20.96C; Correction: -0.60C; Pos: 0.00% -> 0.00%
1664210220.481 minutes_tick:	Target: 8.0C; Current: 20.97C; Correction: -0.59C; Pos: 0.00% -> 0.00%
1664210280.379 minutes_tick:	Target: 8.0C; Current: 20.96C; Correction: -0.57C; Pos: 0.00% -> 0.00%
1664210340.393 minutes_tick:	Target: 8.0C; Current: 20.93C; Correction: -0.56C; Pos: 0.00% -> 0.00%
1664210400.264 minutes_tick:	Target: 8.0C; Current: 20.95C; Correction: -0.54C; Pos: 0.00% -> 0.00%
1664210460.322 minutes_tick:	Target: 8.0C; Current: 20.95C; Correction: -0.53C; Pos: 0.00% -> 0.00%
1664210520.228 minutes_tick:	Target: 8.0C; Current: 20.94C; Correction: -0.52C; Pos: 0.00% -> 0.00%
1664210580.182 minutes_tick:	Target: 8.0C; Current: 20.95C; Correction: -0.50C; Pos: 0.00% -> 0.00%
1664210640.142 minutes_tick:	Target: 8.0C; Current: 20.94C; Correction: -0.49C; Pos: 0.00% -> 0.00%
1664210700.042 minutes_tick:	Target: 8.0C; Current: 20.93C; Correction: -0.48C; Pos: 0.00% -> 0.00%
1664210760.932 minutes_tick:	Target: 8.0C; Current: 20.96C; Correction: -0.47C; Pos: 0.00% -> 0.00%
1664210820.006 minutes_tick:	Target: 8.0C; Current: 20.92C; Correction: -0.46C; Pos: 0.00% -> 0.00%
1664210880.065 minutes_tick:	Target: 8.0C; Current: 20.93C; Correction: -0.44C; Pos: 0.00% -> 0.00%
1664210940.886 minutes_tick:	Target: 21.0C; Current: 20.93C; Correction: -0.43C; Pos: 0.00% -> 0.00%
```

The output of `http://<IP-of-TRV>/window?state=open` (see `unixtime` and compare to minute ticks above - this happened between first and second line):
`{"wifi_sta":{"connected":true,"ssid":"***","ip":"***","rssi":-64},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"18:31","unixtime":1664209898,"serial":0,"has_update":false,"mac":"***","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"thermostats":[{"pos":39.4,"target_t":{"enabled":true,"value":21.0,"value_op":8.0,"units":"C"},"tmp":{"value":21.1,"units":"C","is_valid":true},"schedule":true,"schedule_profile":3,"boost_minutes":0,"window_open":true}],"calibrated":true,"bat":{"value":100,"voltage":4.132},"charger":false,"update":{"status":"unknown","has_update":false,"new_version":"20220811-152343/v2.1.8@5afc928c","old_version":"20220811-152343/v2.1.8@5afc928c","beta_version":null},"ram_total":97280,"ram_free":22848,"fs_size":65536,"fs_free":59420,"uptime":417215,"fw_info":{"device":"shellytrv-8CF68108C88D","fw":"20220811-152343/v2.1.8@5afc928c"},"ps_mode":0,"dbg_flags":0}`

`"unixtime":1664209898` is 18:31:38 in my local time zone.

The output of `http://<IP-of-TRV>/window?state=close`:
`{"wifi_sta":{"connected":true,"ssid":"***","ip":"***","rssi":-50},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":false},"time":"18:48","unixtime":1664210929,"serial":0,"has_update":false,"mac":"***","cfg_changed_cnt":0,"actions_stats":{"skipped":0},"thermostats":[{"pos":0.0,"target_t":{"enabled":true,"value":21.0,"value_op":8.0,"units":"C"},"tmp":{"value":20.9,"units":"C","is_valid":true},"schedule":true,"schedule_profile":3,"boost_minutes":0,"window_open":false}],"calibrated":true,"bat":{"value":100,"voltage":4.130},"charger":false,"update":{"status":"unknown","has_update":false,"new_version":"20220811-152343/v2.1.8@5afc928c","old_version":"20220811-152343/v2.1.8@5afc928c","beta_version":null},"ram_total":97280,"ram_free":22848,"fs_size":65536,"fs_free":59420,"uptime":418246,"fw_info":{"device":"shellytrv-8CF68108C88D","fw":"20220811-152343/v2.1.8@5afc928c"},"ps_mode":0,"dbg_flags":0}`

The first time I saw this in the events log, it flapped between the two states `changed from 8 °C to 21 °C` and `changed from 21 °C to 8 °C`. I thought that the TRV is misbehaving and reached out to the Shelly support, but the debug log shows it's behaving correctly.

## Context

Although this doesn't effect the expected behaviour in the real world, OpenHAB displays the state of the target temperature wrong. For example, when OpenHAB creates a graph for the target temperature, it shows 8 °C only for two minutes.

![image](https://user-images.githubusercontent.com/36745210/192371745-9d09b7b7-b895-44b1-b21e-0272478fce10.png)

Blue: Position of the valve (left axis)
Yellow: Measured temperature (right axis)
Green: Target temperature (right axis) - only at 8°C for about 2 minutes instead of 17

## Your Environment

* Version used: OpenHAB 3.3.0 and Shelly binding 3.3.0 running on a Raspberry Pi 3+
* Shelly TRV firmware 20220811-152343/v2.1.8@5afc928c (latest according to Web interface)

Thank you in advance for your support.

Regards, Thorsten

**Comment by markus7017** [comment]
Please provide a DEBUG log, I need to see what happens on the OH side, the TRV log is nice, but the binding processes the device messages and then updates the channels.

**Comment by markus7017** [comment]
Do you have more TRV devices on the network, what are the IP addresses?

**Comment by dralli72** [comment]
Hi @markus7017, thank you for your answer. To be honest, I forgot about this thread a while ago, because I changed the logic to be controlled 100% by openHAB. In the beginning, I thought it would be easier to "pin" every Door/Window sensor to a TRV by using the built-in methods. It turned out, that this was not very stable...

At this time, I'm using rules and timers in openHAB to control the TRVs (currently 11 active, one more in the pipeline). The Door/Window sensors (currently 8 active) trigger some openHAB timers at every change, when this timer finishes, openHAB calculates the target temperature for the corresponding TRV and sets it. This works as expected (besides two TRV, which undependently switched to "Station mode" once - whatever that is - and were not reachable on the network anymore).

That said, the issue might still be there, but has no impact on me anymore ;-) If you are interested in debugging, I can try to reproduce the problem again, but that might take a while. Otherwise, you could just close this thread.

**Comment by markus7017** [comment]
ok, no need to invest time into a scenario, which is no problem an issue
Nevertheless, you should use the latest DEV build.
Let me know if you see more issues

Switching to station mode sounds to be a firmware bug, if this persists open a ticket with Shelly support
