### ISSUE TITLE
[boschshc] Support obtaining battery states

### ISSUE THREAD

**Issue by MiGro1194** [openhab/openhab-addons#13461]
Hello all,

The Bridge from Bosch provides in addition to the currently provided values also the battery - level of the different thermostats. 
I had already seen this with another provider outside of Openhab, but decided to use Openhab for other reasons.

Is it possible to include this in this binding as well?

**Comment by david-pace** [comment]
Technically this should be possible. I know what has to be done in the code but I don't have the hardware at home to test it. 

However, I have other sensors (shutter contacts, twinguard, motion sensor) that also transmit their battery levels. I assume that they all use the same format for transmitting the state, so I could implement it for the other sensors and add it to the thermostat "blindly". But of course it would be better if someone could implement it who also has the hardware at home.

Maybe @GerdZanker, @coeing or @stefan-kaestle have thermostats at home and/or know someone who might be interested in implementing and testing this?

**Comment by david-pace** [comment]
I managed to get some experimental code running that retrieves the current battery state from shutter contacts, motion sensors and twinguards. The tricky part is to test this, especially the transition when the battery goes from OK to low, but I'll try to figure something out 🤔

Does anyone here have one or more of the following devices (and a few nearly drained batteries 😉) and wants to help testing this?

* Smoke Detector (non-Twinguard)
* Thermostat
* Wall Thermostat
* Univesal Switch
* Water Leakage Sensor

If someone here has the permissions you can assign me to this issue.

**Comment by GerdZanker** [comment]
I just have a smoke detector from your device list.

**Comment by OlliHein** [comment]
Hi I read this post and I have some thermostats with batteries from last year.
Why not, I can test it to get battery status in Openhab.

**Comment by david-pace** [comment]
Thanks to my highly sophisticated low battery simulator I was able to finalize and test the code 😁

![LowBatterySimulator](https://user-images.githubusercontent.com/5941717/199124298-61a4c9fa-ab2d-4d4f-a734-42da2bae445d.jpg)

![LowBattery](https://user-images.githubusercontent.com/5941717/199124315-d2cb5f75-add4-4596-a05c-77499344879c.png)

Current test status:

- [x] Motion Sensor
- [x] Shutter Contact
- [ ] ~~Smoke Detector (non-Twinguard)~~ (no binding yet)
- [ ] Thermostat
- [x] Twinguard
- [ ] ~~Universal Switch~~ (no binding yet)
- [ ] Wall Thermostat
- [ ] ~~Water Leakage Sensor~~ (no binding yet)

If I'm not mistaken we can't test simple smoke detectors, universal switches and water leakage sensors because the binding does not support them yet. So I guess we just have to test (wall) thermostats for now. Thanks to @OlliHein for volunteering 👍 

What is the easiest way for @OlliHein to obtain the JAR and test it? Can he download it somehow from the automated build and drop it in some folder in openHAB?

**Comment by OlliHein** [comment]
Hi all,

Short correction,  I do not have wall thermostat but radiator thermostats.

What is the best way to get the binding to test it?

Thanks
Oliver
________________________________

**Comment by david-pace** [comment]
That's fine @OlliHein, every device test will be helpful and radiator thermostats are also on the list (just named _Thermostat_). Note that some changes were discussed in the pull request that I have to implement first. Also the code needs to be reviewed which might trigger further iterations. We will let you know as soon as the [pull request](https://github.com/openhab/openhab-addons/pull/13631) is finalized.

@jlaur, could you please rename the title of this issue to something more generic like _Support obtaining battery levels_ or _Support obtaining battery states_ (as the change will enable this not only for thermostats, but other devices as well)? And do you know if there is a simple way to put the SNAPSHOT-JAR into an openHAB installation for testing?

**Comment by jlaur** [comment]
> could you please rename the title of this issue to something more generic

Done.

@kaikreuzer - can you add @david-pace as contributor? He has contributed with a few high-quality PR's for the Bosch Smart Home binding: https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+author%3Adavid-pace

> And do you know if there is a simple way to put the SNAPSHOT-JAR into an openHAB installation for testing?

Do you mean testing the binding JAR in your installation? You can simply copy it into the addons directory (after having uninstalled the bundled binding), for example `/usr/share/openhab/addons` for openHABian. There might be incompatibilities if the installation is older. Currently for 3.4 bindings on 3.3 systems there are API changes related to OAuth2 and console extensions, but most bindings will probably work.

**Comment by kaikreuzer** [comment]
> @kaikreuzer - can you add @david-pace as contributor? 

Sure thing! Done.

**Comment by GerdZanker** [comment]
>  And do you know if there is a simple way to put the SNAPSHOT-JAR into an openHAB installation for testing?

@david-pace, see also the [Bosch SHC Developer MD](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.boschshc/DEVELOPERS.md).

**Comment by david-pace** [comment]
> > @kaikreuzer - can you add @david-pace as contributor?
> Sure thing! Done.

Thank you @jlaur and @kaikreuzer , it's an honor :heart:

**Comment by david-pace** [comment]
Cool it's merged, thank you all 😎

@OlliHein and all others who want to test the battery level support before it is released with OH 3.4, this is how you can test it (@jlaur and @GerdZanker please correct me if those steps are not correct):

1. Make an OH backup (just in case)
2. Go to your OH web frontend and find your thermostat(s) or other sensors with batteries
3. Switch to the _Code_ tab and copy the configuration(s) to a text editor and save it (to be able to restore it quickly later)
4. Uninstall the Bosch Smart Home binding
5. Shut down the server
6. Download the latest JAR [here](https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.boschshc/3.4.0-SNAPSHOT/org.openhab.binding.boschshc-3.4.0-SNAPSHOT.jar)
7. Copy the JAR into your `addons` folder (e.g. `/usr/share/openhab/addons`)
8. Start the server and check the console and/or logs if it starts up correctly
9. Find a battery-powered sensor you want to test, copy its device ID, and delete the thing
10. Create the thing again (paste the ID from the step before)
11. Switch to _Channels_. You should now see two battery level-related channels there.
12. Add items to the channel(s) you are interested in
13. If your batteries are full the level should be displayed as `100%` in the `battery-level` channel and the `low-battery` channel state should be `OFF`.
14. If possible, try using the sensor with nearly drained / old batteries as well. The `battery-level` should be `10` or `1` and the `low-battery` channel state should be `ON` if the batteries are low. This might be hard to enforce/test. You might need to trigger an event on the sensor side to trigger an update (including the battery level) to be transmitted to the bridge.
15. When you're done with testing, delete the battery-related items and delete the things you tested
16. Shut down the server
17. Delete the `SNAPSHOT` JAR from your `addons` folder (the one you copied in step 7)
18. Start the server
19. Re-install the Bosch Smart Home Binding
20. Re-create the battery-powered devices you tested using the configurations you copied in step 3

If this seems too cumbersome (which I could understand to be honest 😉) you could also wait for the OH 3.4 release. The advantage of testing now would be that we could fix potential bugs before they are even released. When testing with OH 3.4 we could integrate fixes only after some time in the subsequent OH release.
