### ISSUE TITLE
[tapocontrol] Bridge connection fails with error API Rate limit exceeded (-20004)

### ISSUE THREAD

**Issue by elte0** [openhab/openhab-addons#13465]
## Expected Behavior
1. Enter credentials for the tapo cloud connect bridge. 
2. Bridge connects to cloud.
3. Done

## Current Behavior
Bridge is OFFLINE with a COMMUNICATION_ERROR:  API rate limit exceeded (-20004) 

## Steps to Reproduce (for Bugs)
1. Install TapoControl binding
2. Create new "Cloud-Login" bridge
3. Enter credentials
4. Save

**Comment by poggs** [comment]
I have a fix for this in https://github.com/poggs/openhab-addons - PR coming in the next couple of hours

**Comment by poggs** [comment]
PR at https://github.com/openhab/openhab-addons/pull/13468

**Comment by lolodomo** [comment]
Closed by #13468
