### ISSUE TITLE
[orvibo] Support for AllOne IR Blaster

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-addons#1346]
Continuing from here: https://github.com/tavalin/orvibo-sdk/issues/15

Hey @tavalin, your fork didn't have Issues activated but here might be a better place to discuss this topic anyway. ;)

I'm proposing to (1) switch from a file based solution to an item based (base64 encoded?) storage of the IR codes and (2) add the experimental AllOne support here.

How do you feel about that?
##

**Comment by tavalin** [comment]
Hi @ThomDietrich 

Can you explain a bit more how you foresee (1) working? As you know the experimental AllOne support saves the IR code to file storage and you send the saved IR code by specifying the filename to a String item.

How would you expect learning and emitting the IR code to work when storing the IR as an Item value?

**Comment by ThomDietrich** [comment]
I would imagine to have this set of items:
```java
Switch orviboRxEnable "Start listening for IR signal" {channel="orvibo:allone:living:rxenable"}
String orviboRx "Last received IR code [%s]" {channel="orvibo:allone:myallone:rx"}
String orviboTx "Emit IR code" {channel="orvibo:allone:myallone:tx", autoupdate="false"}
Switch orviboTVPower "ActivateTV" {channel="orvibo:allone:myallone:tx:IAlUZXN0CSANCg=="}
```
By activating the first switch, the binding starts listening for IR signals. The received signal will be logged and saved in the item orviboRx (e.g. "IAlUZXN0CSANCg==").
A user could now either build a rule and call `orviboTx.postUpdate("IAlUZXN0CSANCg==")` or he could define a dedicated item like the last example. I am however not sure if a channel definition in this way is allowed.

The described behavior is quite similar to other bindings. The xbmc binding for example has channels to receive the currently played movie or to send a notification to the screen.

**Comment by kubawolanin** [comment]
Has there been any progress for that binding? I received mine AllOne recently and am able to test it :) Can't localize the jar file, though.
Many thanks!

**Comment by tavalin** [comment]
[Here](https://github.com/tavalin/openhab2-addons/releases/download/1.0.1/org.openhab.binding.orvibo-2.0.0-SNAPSHOT.jar)'s the previously built jar.  However further development is pretty much bottom of my list of priorities.

**Comment by kubawolanin** [comment]
I'm attaching built JAR from latest work from @tavalin :
[org.openhab.binding.orvibo-2.1.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/819235/org.openhab.binding.orvibo-2.1.0-SNAPSHOT.jar.zip)

**Comment by davidgraeff** [comment]
Closing as no progress. Please reopen or provide a PR.
