### ISSUE TITLE
Auto discovery for homematic:bridge not working

### ISSUE THREAD

**Issue by dslad** [openhab/openhab-addons#13475]
## Expected Behavior

* [homegear](http://homegear.eu) is auto-discovered and appears in the Inbox
* Clicking on it and selecting _Add as Thing_ should add the bridge and enable discovery of devices known by homegear
## Current Behavior

* Clicking on the homegear inbox item and trying to _Add as Thing_ returns an onscreen message: "Error during thing creation. Conflict"
* openHAB Log contains the line: ` [WARN ] [g.discovery.internal.PersistentInbox] - Cannot create thing. No binding found that supports creating a thing of type homematic:bridge.`
* Adding the thing manually results in "Thing created" but it remains _UNINITIALIZED_ and the log contains the line: `[WARN ] [ore.thing.internal.ThingRegistryImpl] - Cannot create thing. No binding found that supports creating a thing of type 'homematic:bridge'.`
* Adding the thing via a config file containing `Bridge homematic:bridge:homegear [ gatewayAddress="nnn.nnn.nnn.nnn" ]results` in the log line: `[INFO ] [.thing.internal.GenericThingProvider] - No ThingHandlerFactory found for thing homematic:bridge:homegear (thing-type is homematic:bridge). Deferring initialization.`

## Steps to Reproduce (for Bugs)

1. create Ubuntu 20.04 VM/container and install homegear from https://homegear.eu/downloads.html (any version)
2. create separate Ubuntu 20.04 VM/container and install openHAB3 (I've tried a selection of versions from 3.0.0-1 up to the latest nightly)
3. install homematic binding
4. Auto-discovery should make the homegear server appear as thing of type homematic:bridge in the Inbox
5. Try to add the thing as described above

## Context
* linked forum post [here](https://community.openhab.org/t/error-during-thing-creation-conflict/139513)

## Your Environment

* openHAB 3, from 3.0.0-1 via 3.3.0 to latest nightly
* lxd containers running Ubuntu 20.04 server on 20.04 server host
* java11 provided by Zulu11 11.0.16.1

**Comment by lolodomo** [comment]
Are you sure the homematic binding is properly installed on your server ?
Please log in and type this command in the console: `bundle:list -s | grep homematic`

**Comment by dslad** [comment]
I get:
`237 │ Waiting │  80 │ 3.3.0                  │ org.openhab.binding.homematic`
where everything else is Active

**Comment by lolodomo** [comment]
You have your answer, the binding is not started.

**Comment by MHerbst** [comment]
If you are running OH in a container, check that all ports are mapped and communication is possible. The HM binding uses UPNP to discover CCUs (and probably Homegear). This means all ports for UPNP must also be available.
In the bridge configuration you have to set the callback address to the external IP address of the machine running the container.

**Comment by dslad** [comment]
Thanks for the pointers, hugely appreciated.

> If you are running OH in a container, check that all ports are mapped and communication is possible. The HM binding uses UPNP to discover CCUs (and probably Homegear). This means all ports for UPNP must also be available. In the bridge configuration you have to set the callback address to the external IP address of the machine running the container.

The OH container and the homegear container are running on the same host are are both set up with bridged NICs - so they are assigned IP addresses by my LAN DHCP server. Neither is running any firewall and each can see the other's open ports. 

The OH container auto-discovers the homegear container and adds a new thing to the Inbox, but I can't get it to initialize.

Looking at the DEBUG log as the homematic binding starts up, I think the problem stems from here:
`2022-10-03 08:27:41.870 [ERROR] [t.http.internal.WebClientFactoryImpl] - Could not start Jetty web socket client
java.lang.IllegalStateException: Insufficient configured threads: required=44 < max=40 for QueuedThreadPool[OH-httpClient-common]@634c7189{STARTED,10<=20<=40,i=0,r=-1,q=0}[ReservedThreadExecutor
@3df11a89{reserved=0/4,pending=0}]
`

Additional pointers very welcome!
