### ISSUE TITLE
[enocean] Add support for air quality sensors, e.g. Eltako FLGTF55

### ISSUE THREAD

**Issue by BillGOH** [openhab/openhab-addons#13472]
Currently the enocean binding does not support air quality sensors (CO2, VOC), like Eltako FLGTF55. The encoean profile A5-09 is missing.

Here is the current specification for Eltako FLGTF55 (but would apply to other similar products as well):

```
FLGTF65, FLGTF55 (EEP A5-09-0C AND A5-04-02)
FLT58 (EEP A5-09-05 AND A5-04-02)
TVOC data telegram acc. to EEP A5-09-0C
Data_byte3 + Data_byte2 = 0..65535 ppb (0..255)
Data_byte1 = 0x00
Data_byte0 = 0x0A
Teach-in telegram: 0x24600D80
VOC data telegram acc. to EEP A5-09-05
Data_byte3 + Data_byte2 = 0..500
Data_byte1 = 0x1B
Data_byte0 = 0x0A
Lerntelegramm: 0x24280D80

Temperature humidity data telegram acc. to EEP A5-04-02
Data_byte3 = -
Data_byte2 = rel. air humidity 0..100% (0..250)
Data_byte1 = temperature -20..+60°C (0..250)
Data_byte0 = 0x0F
Teach-in telegram: 0x10100D87
```
I think an implementation would make sense because of the growing importance of air quality.

**Comment by lovery** [comment]
I think I could make an implementation for this sensor this week. Are you up to test it with your device and openHab?

**Comment by BillGOH** [comment]
Hello @lovery,
thank you for your quick response. I can test it, if you can provide me a jar-file of the addon?

**Comment by lovery** [comment]
@BillGOH great, I will ping you when I have the jar.

**Comment by lovery** [comment]
Hello @BillGOH,

I added support for EEP A5_09_0C - check out [this branch](https://github.com/lovery/openhab-addons/tree/enocean-gasss-02_08_09_0C)
I have a generated .jar file if you prefer I can send it to you - this is my email zhivka.dimova @ myforest.net

**Comment by BillGOH** [comment]
Close with https://github.com/openhab/openhab-addons/pull/13793.
