### ISSUE TITLE
[avmfritz] battery_level channel created on unsupported FRITZ!OS version

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#13471]
## Expected Behavior

- Use a Fritzbox with OS < 7
- Connect a  FRITZ!DECT 302 
- No channel `battery_level` appears

From the docs:

> The battery_level channel will be added to the thing during runtime - if the interface supports it (FRITZ!OS 7 or higher).

## Current Behavior

- Channel `battery_level` appears, but linked Item is always `UNDEF`.

## Your Environment

* Version used: (e.g., openHAB and add-on versions) 3.3.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Linux

**Comment by cweitkamp** [comment]
Can you provide a TRACE log if the avmfritz binding which shows the polling results? You may want to send it via PM in the community forum to me. I will look into it.

**Comment by mueller-ma** [comment]
I don't have this device combinatiom anymore.
