### ISSUE TITLE
[avmfritz] Issue with SmartHome Wandtaster

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#13513]
## Expected Behavior

The device https://www.smarthome.de/geraete/smarthome-wandtaster-weiss works as mentioned in the docs: https://www.openhab.org/addons/bindings/avmfritz/

## Current Behavior

I have multiple issues with this switch:

- A rule with `Channel "avmfritz:HAN_FUN_SWITCH:1:zzzzzzzzzzzz_2:press" triggered` isn't triggered when I press the button
- The "last change" Item is always `NULL`
- A channel `contact_state` is created  and changes with some delay after pressing the button between "OPEN" and "CLOSED"

## Your Environment

* Version used: openHAB 3.3.0
* FritzOS: 06.86
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lsiepel** [comment]
Does this issue still exist with 4.1.x?

**Comment by mueller-ma** [comment]
It works fine with 4.1.1.
