### ISSUE TITLE
Doc Issues - Following them Verbatim , install doesnt work. 

### ISSUE THREAD

**Issue by decyphertek-io** [openhab/openhab-addons#13581]
Here are the instructions that I compiled. I modded them, when the original docs failed and still not working. I used Ubuntu 22.04 & Debian 11. I had the most success with Debian 11, except could not get OpenHab Cloud or OpenHab working.

docs - https://decyphertek.readthedocs.io/en/latest/#Openhab/

Cloud Install
--------------
   
     # Doesnt work based off the instructions provided? 
     $ sudo apt-get update && sudo apt-get upgrade -y
     $ curl -fsSL https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
     $ echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
     $ sudo su -c "curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -" 
     $ curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
     $ sudo apt update
     $ sudo apt-get install -y build-essential redis-server mongodb-org nodejs nginx python3 git
     $ sudo npm install -g npm@latest
     $ sudo systemctl enable mongod
     $ sudo systemctl start mongod
     $ sudo systemctl enable redis
     $ sudo systemctl start redis
     $ cd  /home/$USER/ 
     $ git clone https://github.com/openhab/openhab-cloud.git
     $ cd openhab-cloud
     $ sudo npm install --force
     $ sudo npm audit fix --force
     $ redis-cli ping
     $ cp config-production.json config.json
     $ sudo npm install pm2@latest -g 
     $ pm2 start app.js
     $ pm2 save
     $ pm2 startup
     $ sudo cp /home/$USER/openhab-cloud/etc/nginx_openhabcloud.conf /etc/nginx/sites-available/default
     $ sudo cat /etc/nginx/sites-enabled/default
     $ sudo mkdir /etc/nginx/ssl
     $ sudo openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout /etc/nginx/ssl/openhabcloud.key -out /etc/nginx/ssl/openhabcloud.crt -subj "/C=US/ST=Any/L=Anytown/O=decyphertek-io/OU=adminotaur/CN=decyphertek"
     $ sudo systemctl restart nginx
     $ sudo systemctl restart pm2-adminotaur
     
Debian Install 
--------------

     $ curl -fsSL "https://openhab.jfrog.io/artifactory/api/gpg/key/public" | gpg --dearmor > openhab.gpg 
     $ sudo mv openhab.gpg /usr/share/keyrings 
     $ sudo chmod u=rw,g=r,o=r /usr/share/keyrings/openhab.gpg
     $ echo 'deb [signed-by=/usr/share/keyrings/openhab.gpg] https://openhab.jfrog.io/artifactory/openhab-linuxpkg stable main' | sudo tee /etc/apt/sources.list.d/openhab.list
     $ sudo apt-get update
     $ sudo apt-get install openhab openhab-addons
     # http://openhab-device:8080

TroubleShooting
----------------

     $ sudo systemctl start openhab.service
     $ sudo systemctl status openhab.service
     $ sudo systemctl daemon-reload
     $ sudo systemctl enable openhab.service

Upgrade
--------

     $ sudo apt-get update 
     $ sudo apt-cache showpkg openhab
     $ sudo apt-get install openhab=[version]

OpenHabian Install
-------------------

     # Raspberry Pi & Balena Etcher
     $ wget https://github.com/openhab/openhabian/releases/download/v1.7.4b/openhabian-pi-raspios32-202208151955-gitbe9d23e-crc075defd9.img.xz
     # burn image to sd card using Balena Etcher
     # load and boot in Raspberry Pi
     # http://openhabian:8080/

References
----------

     https://www.openhab.org/
     https://www.openhab.org/docs/installation/linux.html
     https://github.com/openhab/openhab-cloud/blob/master/README.md
     https://www.openhab.org/docs/tutorial/first_steps.html
     https://github.com/openhab/openhabian/releases

**Comment by wborn** [comment]
Please create issues (or even better PRs) in the appropriate repos for this.

**Comment by decyphertek-io** [comment]
What is the appropriate repo?

**Comment by wborn** [comment]
You provided links to them in your references list :wink: :

> https://github.com/openhab/openhab-cloud
> https://github.com/openhab/openhabian

The documentation on the website is maintained here:

https://github.com/openhab/openhab-docs

At the bottom of each documentation page on the website is also a link which you can click to submit a PR for improving the page:

![Screenshot from 2022-10-30 10-13-05](https://user-images.githubusercontent.com/12213581/198871166-5af66573-fbc0-47fa-9bb5-26e5c17cd47c.png)
