### ISSUE TITLE
[HomeKit] Use Number item as Value for Heater/Cooler, Thermostat current and target mode

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#13595]
Hi,

Heater/Cooler and Thermostat accessory can be used with string item to control current/target mode, it will be very help full to add possibility use number item. Right now I need convert thing channel number to string item and vice versa.

Thanks
Grzegorz

**Comment by ccutrer** [comment]
FYI @grzegorz914: #14036 is now ready for review, and fully closes this issue (it took a while to get dependent semi-related PRs through first).

**Comment by grzegorz914** [comment]
@ccutrer any progress?

**Comment by ccutrer** [comment]
The PR is up and linked from this issue, and there are comments going back and forth.

**Comment by grzegorz914** [comment]
@ccutrer why the PR is pause, any chance we get any progress wit it?
