### ISSUE TITLE
[jsscripting] Discuss the implementation of timers

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#13594]
## Current situation

The `setTimeout` and `setInterval` polyfill methods returns an openHAB `Timer` which **does not conform** to standard JS.

## The problem

1. If we get the option to move to standard JS (when GraalJS implements those methods and we don't need the polyfills) this will break existing JS code.
2. Timers might be removed from openHAB at sometime:
> It exposes Timers to openHAB users, when it seems from @kaikreuzer like they are planned to be removed

@jpg0 
Continuing the discussion from https://github.com/openhab/openhab-addons/pull/13582.

**Comment by florian-h05** [comment]
@jpg0
Are you referencing on any discussion with Kai when you say it seems like Timers are planned to be removed?

**Comment by kaikreuzer** [comment]
I assume @jpg0 referred to my statement that DSL-support could potentially be considered an optional feature in the future. The current Timer was introduced solely for DSL rules and thus it is linked to them. If we want to make them available for any scripted rule, we should decouple it indeed from Xtext/Xbase. Not sure how easily this can be done without breaking backward compatibility with DSL rules, though.

**Comment by jpg0** [comment]
Yes, this is what I meant.

**Comment by digitaldan** [comment]
I am very fine revisiting timers and making them follow the JS spec.  Honestly the decision to return the raw timer was laziness on my part. At the time It was easier to pass around the raw timer object then to create a mapping of integer -> timers and handle that lifecycle. Looking back i probably should have spent the little extra time to do that, but was in a rush to make our release date.  

One benefit of mapping these in the binding is being able to cancel timers when scripts reload.  We have a whole warning section in the docs on caching the timer reference or using unload hooks to manage them.  This is probably different than every other JS environment where timers are destroyed along with the reloading of scripts.   For end users this can mean timers that run forever until you restart openHAB if you are not very careful.

**Comment by florian-h05** [comment]
> One benefit of mapping these in the binding is being able to cancel timers when scripts reload.

One more benefit. The benefits clearly outweigh the breaking change that is implicated when we move closer to standard JS.

**Comment by florian-h05** [comment]
I am making pretty good progress on the reimplementation, should be able to open a PR the next two days.
