### ISSUE TITLE
[gardena] Binding throws connection errors and seems to break some other bindings

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#13609]
As reported on the forum, it seems that the binding throws connection errors and seems to break some other bindings.

Obviously the main issue is to prevent the binding from throwing connection errors in the first place. But I would like to understand how an error in the Gardena binding might cause other bindings to stop working. => So I would like to ask other maintainers if they have any suggestions. 

https://community.openhab.org/t/gardena-binding-throws-connection-errors-and-seems-to-break-some-bindings/140085

**Comment by lolodomo** [comment]
I assume the gardena binding is using the common binding thread pool (not checked).
The impact on other bindings could be because the Gardens binding is not releasing the threads (HTTP requests) or consumes all the threads of the common thread pool.

**Comment by lolodomo** [comment]
Checking quickly the code, the binding creates its own HTTP client and web socket client so it can't break the common HTTP client.

**Comment by lolodomo** [comment]
It must be checked that no long running thread are created by the binding using `scheduler`.

**Comment by andrewfg** [comment]
^
@lolodomo many thanks for the kind suggestion. My problem is that on my system I don't get the crash that the OP has reported, so it is hard trace which of the many scheduled tasks in the binding might be the culprit. Sadly (apparently) the OH core scheduler doesn't throw an exception if it runs out of resources, or the OP would have reported the stack trace in his log. (Perhaps this could be added to the TODO list?) So perhaps you can tell me if there is some particular module in the OH core where I could suggest the OP to set log trace in order to learn more about the causes?

**Comment by andrewfg** [comment]
^ .. more on the above..

Actually the OP DID report a stack trace as follows. And it does seem to relate to a scheduled task timeout. However (please correct me if I am wrong) this seems not to be related to the OH scheduler (at least not directly), but rather to some Jetty SSL activity, (which maybe INDIRECTLY has an effect on the OH scheduler?) -- I am no expert on the inner workings of Jetty so any clues would be much appreciated. :)

```
2022-10-18 16:05:29.515 [DEBUG] [rdena.internal.GardenaSmartWebSocket] - Gardena Webservice error (Gardena_Account-My Garden)
org.eclipse.jetty.websocket.api.CloseException: java.util.concurrent.TimeoutException: Idle timeout expired: 150010/150000 ms
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:564) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:172) ~[?:?]
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:539) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:317) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillableFail(SslConnection.java:591) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillInterestedFailed(SslConnection.java:419) ~[?:?]
	at org.eclipse.jetty.io.ssl.SslConnection$2.failed(SslConnection.java:170) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:140) ~[?:?]
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:407) ~[?:?]
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:171) ~[?:?]
	at org.eclipse.jetty.io.IdleTimeout.idleCheck(IdleTimeout.java:113) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 150010/150000 ms
	... 8 more
```

**Comment by Hilbrand** [comment]
It's likely the threadpool is locked up. There are many scheduled tasks in this binding. If for some reason there is a deadlock and the thread is locked it will cause all other tasks to lock too. In general tasks on the scheduled tasks should be short running because of the shared resources. So timeouts should be short, and thread sleep be avoided. I also see the bridge starts discovery and wait for the discovery to finish. This is also looks like it could take some time. So this wait would be better to be an async call. So the discovery passes the information to the bridge and handles it then, or the bridge in repeating scheduled tasks checks for information from the discovery.

See also my comment on the forum in the related topic on how to see what threads are locked up. https://community.openhab.org/t/gardena-binding-throws-connection-errors-and-seems-to-break-some-bindings/140085/13

You could try to reproduce it by replacing the actual websocket call with a sleep with same time as the timeout and throw the exception after it.

**Comment by andrewfg** [comment]
@Hilbrand many thanks for this insight. As you suggest, the cause may actually be the call to `discoveryService.waitForScanFinishing()` when the bridge is initialized, since the scan creates a call on the server, which might block, and if the initialization fails it keeps retrying, thus perhaps creating many blocking calls on  the server. ?? In that case I think that setting a lower read timeout on the server call should (also) fix it. Nevertheless I will go through ALL of the scheduled tasks in the binding just to be sure..

**Comment by andrewfg** [comment]
^
I think the issue is connected to the timeouts here (below) where `webSocketClient.setMaxIdleTimeout(150000)` exactly matches the OP's crash dump posted above. Now the odd thing is that this 150 second timeout should never occur since the binding has a scheduled task to send a ping to the server every 120 seconds.

**_THEREFORE I am now wondering if the fault is actually NOT in the Gardena binding_**: perhaps another of the OP's bindings is locking up the threadpool? And that would prevent the scheduler from firing the Gardena ping task, which in turn would cause the Idle timeout expired error. 

https://github.com/openhab/openhab-addons/blob/618b7a4e3a72b9de6958d413499c12c6f0b85f53/bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java#L112

**Comment by lolodomo** [comment]
Ask the user to list all his installed bindings. And suggest to him to uninstall first all non official (reviewed) bindings.

**Comment by andrewfg** [comment]
^
https://community.openhab.org/t/gardena-binding-throws-connection-errors-and-seems-to-break-some-bindings/140085/15?u=andrewfg

**Comment by andrewfg** [comment]
Closed via post on community forum..

https://community.openhab.org/t/gardena-binding-throws-connection-errors-and-seems-to-break-some-bindings/140085/31?u=andrewfg

**Comment by lolodomo** [comment]
But an issue has to be open for the Kodi binding?

**Comment by andrewfg** [comment]
> an issue has to be open for the Kodi binding?

Yes, I think so. (I am not a Kodi user, so probably I am not the best person to open such an issue however..)

**Comment by andrewfg** [comment]
FYI opened => #13716
