### ISSUE TITLE
[mqtt.homeassistant] Add support for device type "number"

### ISSUE THREAD

**Issue by brydling** [openhab/openhab-addons#13603]
The device type "number" is currently not supported by the mqtt.homeassistant binding.

**Comment by Jamoth** [comment]
The "select" type is unsupported, too.

**Comment by ccutrer** [comment]
> The "select" type is unsupported, too.

https://github.com/openhab/openhab-addons/pull/14230 is for select

**Comment by ccutrer** [comment]
.. and Number as well (I used the same PR with an additional commit, since the two commits would conflict with each other if done separately)

**Comment by brydling** [comment]
> .. and Number as well (I used the same PR with an additional commit, since the two commits would conflict with each other if done separately)

Thank you! 🙂
