### ISSUE TITLE
[zwave] donexon varmo TZ pro thermostat - sensor type 0x17 Water temp indication

### ISSUE THREAD

**Issue by markus7h** [openhab/openhab-addons#13608]
The donexon thermostat is a danfoss derivate which include additional sensor information over the the original and other derivates like devolo etc. 

under the commend class COMMAND_CLASS_SENSOR_MULTILEVEL with sensor type 0x17 the water temp value can be read from the device

please include device specific detection for the donexon with additional water sensor channel
device type: slave
manufacturor id: 0x002
product type: 0x5fff
product id: 0xa010

**Comment by lolodomo** [comment]
To be moved in the appropriate git repo. 
Sorry I don't know how do that myself,

**Comment by markus7h** [comment]
moved to zwave repo
