### ISSUE TITLE
[miio] Error loggin to Xiaomi cloud in miio binding -  Return code: 0

### ISSUE THREAD

**Issue by xduseko** [openhab/openhab-addons#13611]
## Expected Behavior
Addon logs in to the Xiaomi cloud and retrieves the supported device list.

## Current Behavior
Login fails due to unexpected JSON response.

```
17:38:22.934 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi Login step 1
17:38:22.984 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi Login step 1 content response= &&&START&&&{"serviceParam":"{\"checkSafePhone\":false,\"checkSafeAddress\":false,\"lsrp_score\":0.0}","qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"0psXfr43eNI0IX6q9Suk3qWbRqU=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"https://account.xiaomi.com/fe/service/login?_json=true&sid=xiaomiio&qs=%253Fsid%253Dxiaomiio%2526_json%253Dtrue&callback=https%3A%2F%2Fsts.api.io.mi.com%2Fsts&_sign=0psXfr43eNI0IX6q9Suk3qWbRqU%3D&serviceParam=%7B%22checkSafePhone%22%3Afalse%2C%22checkSafeAddress%22%3Afalse%2C%22lsrp_score%22%3A0.0%7D&showActiveX=false&theme=&needTheme=false&bizDeviceType=","pwd":0,"child":0,"desc":"登录验证失败"}
17:38:22.985 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi Login step 1 response = HttpContentResponse[HTTP/1.1 200 OK - 760 bytes]
17:38:22.986 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi Login step 1 sign = 0psXfr43eNI0IX6q9Suk3qWbRqU=
17:38:22.986 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi Login step 2
17:38:23.047 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login step 2 response = HttpContentResponse[HTTP/1.1 200 OK - 1014 bytes]
17:38:23.048 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login step 2 content = &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=passport&context=sMlx600MPFo9smESNZmGDdkmc7e2Z4sYqW81z2t4F3LTh9vz7gf0sNeze4znW9ytwEsqYzgWj0KQ1dl2CDw9Sne6w9qMFRCC6zg0de7L_8y-8xeaHHo6nn35dLNtMQOi8NvYi-RGx0rkivMCpbaPnsFYzDoRliupXK-Ox_r5MWElldDjtKTCY2mxQGinj_eAQdcERP5iV2wG2TqxQdy3AdXAKmfyg6y044u1491wG7tosQAIQriMFmPnhZqBzQjNN8rBmHfnogcvbfxGV0-eqRJTN4XemWcLkO_lLNB0sC26tx4W1rQ2chwK1v5N3DOxJxGofmuXkmq1VqVBqFp7DdVWoy5nGsZnI3CK0WT9cfTQWCXpOeYyJRWGkLP35irZ_X4SukwbSFzQPgu5gMfMPkaSdY0ShZv-BACKoUYW_QQIrf1A0Rc0HReupBQNBbuDcQofNskAvVNLoUOcfV4MSb_s7PGsCh0UP4tk-LGenpNMhMhIT2tcEehGtG8gqgsqIFdYcK7Uwc5KmnGtdRvJTOhuvxUZXSuVB7-aoh86urjJl4n5VMMl7nWUXmZORNXYyfNZ4rhSOWzrBMZiTrQK0JewQkWO3YuXJrGe4h6x33rcSRHGwTPzo2cRpCMg_Xf5xTYe_Fqd-ggqp0NRzZEvntc7y_DRAb8PSo1k_RNf4yWYg7Vg-P4SwhhVUU2nUcQ7FFFJKwG5pooL7UZwbPI5PeU2Up4YEnmrQlQvcmxppnBJNj9PNIna0N8sQomhMl2E&_locale=de_DE","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
17:38:23.049 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login ssecurity =
17:38:23.050 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login userId =
17:38:23.050 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login cUserId =
17:38:23.051 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login passToken =
17:38:23.052 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login location =
17:38:23.052 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Xiaomi login code = 0
17:38:23.053 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Cookie dump for https://account.xiaomi.com/pass/serviceLoginAuth2
17:38:23.054 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Cookie (.xiaomi.com) : sdkVersion --> accountsdk-18.8.15     (path: /. Removed: false)
17:38:23.055 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Cookie (.xiaomi.com) : deviceId --> cuhdom     (path: /. Removed: false)
17:38:23.055 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Cookie (.xiaomi.com) : uLocale --> de_DE     (path: /. Removed: false)
17:38:23.055 [TRACE] [.miio.internal.cloud.MiCloudConnector] - Cookie (account.xiaomi.com) : pass_ua --> web     (path: /. Removed: false)
17:38:23.056 [INFO ] [.miio.internal.cloud.MiCloudConnector] - Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 0
```

## Steps to Reproduce (for Bugs)

1. Start fresh openhab instance (3.3.0-alpine)
2. Install Miio binding addon
3. Enter Xiaomi cloud email and password to the addon configuration. Also set country to "cn" (I have a device that is supported only in cn region).
4. Try to add a new thing from Miio binding
5. Hit the "Scan" button
6. Check the openhab log. There will be login error.

## Context

It seems to be working from my home PC but not from cloud VPS. It looks like there is some kind of user verification step that is missing in openhab addon.

Unfortunately completing the verification flow using home PC browser doesn't help. Openhab addon is still unable to logon. It could be connected to an unverified IP address or something like that.

## Your Environment

* Version used: openhab:3.3.0-alpine build, Mi IO binding 3.3.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu, Oracle cloud VPS, ARM cpu

![image](https://user-images.githubusercontent.com/9591957/198341501-bf21b164-0aaa-435a-bb43-7d89433aa4d6.png)

![image](https://user-images.githubusercontent.com/9591957/198341519-6e24e419-efc1-46cd-90d8-89aa41b86648.png)

![image](https://user-images.githubusercontent.com/9591957/198341551-a562d1ab-1f47-4e05-9369-0e0a71296ef4.png)

**Comment by xduseko** [comment]
I have found a temporary workaround.

1. Run docker image [browserless/chrome](https://hub.docker.com/r/browserless/chrome) on VPS
2. Tunnel port 3000 to your home PC
3. Visit http://localhost:3000 (or http://<vps>:3000) in your browser
4. Enter the Xiaomi verification URL and follow steps to verify by your e-mail
5. Rerun Miio addon scan. Xiaomi cloud should trust the IP of your VPS by now.

**Comment by lolodomo** [comment]
@marcelrv for information

**Comment by marcelrv** [comment]
Thanks that is helpful.

From the way you got it to work, my understanding is that you basically logged on from the VPS (using the remote chrome) and basically convinced the Xiaomi cloud that the ip you were logging in from was belonging to you.

I do see these 2 entries in the first response. Don't really know if these are true if the ip is right/validated
"checkSafePhone\":false,\"checkSafeAddress\":false,\"

There is also the dreadful `code":70016,"description":"登录验证失败` which is a not very descriptive message that authentication failed. (but does not provide a reason why)

Anyway, I'll add a line in the miio  problems FAQ pointing to this solution.

**Comment by marcelrv** [comment]
@xduseko see the discussion in #13715
Would you mind if I re-use your screenshots in the miio readme. (I have never seen the screen you have, hence can't reproduce similar screenie)

**Comment by xduseko** [comment]
[marcelrv](https://github.com/marcelrv) I wouldn't mind.
