### ISSUE TITLE
Tuya zigbee cordinator not working

### ISSUE THREAD

**Issue by botioni** [openhab/openhab-addons#13633]
Problem tuya ember serial ower enternet socket connection not working .
It is working witout any isu on home asistant  here conection error same setup any advice ?

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lolodomo** [comment]
I found no tuya binding. Is it something for the Zigbee binding ? In that case, the should be moved to the proper Git repo.

**Comment by lsiepel** [comment]
There seems to be a tuya binding maintained here: https://github.com/smarthomej You could raise an issue at that repo here: https://github.com/smarthomej/addons/issues

If you do, it would help to elaborate on the issue, and share more details about your system, verisons used and model of tuya devices. I close this now, if needed it can be re-opened.

**Comment by J-N-K** [comment]
The SmartHome/J Tuya binding is for Tuya WiFi devices, not ZigBee devices. Tuya ZigBee devices need to be paired to a supported ZigBee coordinator (e.g. deconz, hue). I'm not sure if the ZigBee binding supports the Tuya coordinator.

**Comment by lsiepel** [comment]
Ah thanks. In that case @botioni can you provide more details?
