### ISSUE TITLE
[evcc] Failed to get state after evcc update to 0.106

### ISSUE THREAD

**Issue by pauxus** [openhab/openhab-addons#13646]
## Expected Behavior
evcc device is correctly connected

## Current Behavior
after updating to evcc 0.106 the binding fails. Trace log shows a failure message and the result of the underlying call to `api/state`

See https://github.com/evcc-io/evcc/issues/5035

**Comment by pauxus** [comment]
Problem is that `vehicleCapacity` is now a float. Workaround: don't use floats for that value for now. 

Fix: Change type to float/double in DTO

**Comment by florian-h05** [comment]
@pauxus 
Thanks for creating this issue.
I will provide a fix for this ASAP, but I am currently busy with another PR.

**Comment by florian-h05** [comment]
@pauxus 
To avoid issues with changed data types in the future, I will probably change all int/long to float/double in the DTO.
