### ISSUE TITLE
[avmfritz] decode alarm state of blinds

### ISSUE THREAD

**Issue by quidam** [openhab/openhab-addons#13663]
Rollershutters provide a numeric value as alarm state, which are presently interpreted as OFF, when the value is 0 and ON, when the value is 1. But for blinds, the value represents a bit map of possible alarm reasons (bit 0 for obstructions and bit 1 for overheating).
So, I propose to decode this into two channels of the contact type (one per reason) to allow easy usage in rules. I have implemented this locally and can provide a merge request, if my proposal is accepted.

**Comment by lolodomo** [comment]
Closed by #13672
