### ISSUE TITLE
[jdbc] Provide console tools for identifying problems and assisting migration

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#13661]
It would be cool having a way to interact with JDBC persistence to help identifying issues:
- Tables where referenced item no longer exists.
- Mapped items where table doesn't exist.
- Mapped items where neither table nor item exists.
- Orphan tables (not having any mapping).

Perhaps some kind of assisted repair could be added also.

It would also be nice to be able to do a dry-run migration to verify everything before performing a real migration. See also #13544.

**Comment by lsiepel** [comment]
Would it also be possible to add a check if the column type matches the item type ?

**Comment by jlaur** [comment]
> Would it also be possible to add a check if the column type matches the item type ?

I actually have that on my internal TODO. :-) It's a bit more tricky because I need to check column definitions in a way that works for all databases, and I only have a setup for MySQL. Which database do you use?

**Comment by jlaur** [comment]
@lsiepel - I have a draft version now for finding incorrect column types. It needs further work, but I can see already that I have many value columns with unsigned integer types which are expected to be signed. I will need to have a closer look at this and understand how this discrepancy was introduced. I would also like to provide a repair option for safe fixes which cannot truncate data.
