### ISSUE TITLE
[keba] State Item should be Number not String

### ISSUE THREAD

**Issue by maihacke** [openhab/openhab-addons#13679]
The example items configuration defines the item for the state as string item:

`String 						KebaState  				"Operating State [%s]"						{channel="keba:kecontact:1:state"}`

This in incorrect end results in the state being shown as a bogus datetime.
Correct would be a number item:

`Number 						KebaState  				"Operating State [%s]"						{channel="keba:kecontact:1:state"}`

**Comment by lolodomo** [comment]
That is true, the "state" channel type is defined as Number. Can you please propose a fix of the README example ? I will then merge your proposal.

**Comment by maihacke** [comment]
Yes, will do in the next days.

**Comment by maihacke** [comment]
Interestingly when trying to "correct" the readme example there was already the right type. Nevertheless in the describing table it was wrong and is now corrected.
