### ISSUE TITLE
[lifx] LIFX thing stays in offline state after power break

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-addons#13682]
My openHAB instance is UPS battery backed-up, so it doesn't go down if there is a "short" power break, but LIFX devices obviusly will. When LIFX devices go down because of power break, biding will recognise that and but things in offline state (COMMUNICATION_ERROR). When power resume, thing status stays in OFFLINE state. 

I enabled trace level logs to the binding and following can be seen from the log.

```
19:06:42.487 [TRACE] [internal.LifxLightOnlineStateUpdater] - 192.168.40.35 : Light is not online, unicasting request
19:06:42.487 [TRACE] [.lifx.internal.util.LifxSelectorUtil] - 192.168.40.35 : Sending packet type 'GetServiceRequest' from '/172.18.0.12:40024' to '/192.168.40.35:56700' for 'D0:73:D5:24:86:58' with sequence '187' and source '2f49573d'
```

My LIFX devices are in different VLAN than openHAB instance, therefore binding use unicast communication (host ip is set to the thing configuration).

I can see that UDP packet is sent to the LIFX device (tcpdump), but device doesn't response it. Should all LIFX devices support GetServiceRequest?

LIFX details:

```
productVersion  131072
productId       27
hostVersion     2.80
host            192.168.40.35
wifiVersion     2.80
vendorId        1
vendorName      LIFX
productName     LIFX A19
```

Because thing state stays in offline, binding doesn't poll the state either

```
19:07:00.078 [TRACE] [nternal.LifxLightCurrentStateUpdater] - 192.168.40.35 : The light is not online, there is no point polling it
```

After I send command to the light, thing status will be changed to online.

```
19:42:12.811 [DEBUG] [.lifx.internal.LifxLightStateChanger] - 192.168.40.35 : Sending SetLightPowerRequest packet

19:42:12.812 [TRACE] [.lifx.internal.util.LifxSelectorUtil] - 192.168.40.35 : Sending packet type 'SetLightPowerRequest' from '/172.18.0.12:40024' to '/192.168.40.35:56700' for 'D0:73:D5:24:86:58' with sequence '74' and source '2f49573d'

19:42:12.836 [TRACE] [ternal.LifxLightCommunicationHandler] - 192.168.40.35 : Packet type 'AcknowledgementResponse' received from '/192.168.40.35:56700' for 'D0:73:D5:24:86:58' with sequence '74' and source '2f49573d'

19:42:12.837 [TRACE] [nternal.LifxLightCurrentStateUpdater] - 192.168.40.35 : The light just went online, immediately polling the state of the light

19:42:12.862 [TRACE] [.lifx.internal.util.LifxSelectorUtil] - 192.168.40.35 : Sending packet type 'GetRequest' from '/172.18.0.12:40024' to '/192.168.40.35:56700' for 'D0:73:D5:24:86:58' with sequence '75' and source '2f49573d'

19:42:12.862 [DEBUG] [.lifx.internal.LifxLightStateChanger] - 192.168.40.35 : SetLightPowerRequest packet was acknowledged in 50ms

19:42:12.888 [TRACE] [ternal.LifxLightCommunicationHandler] - 192.168.40.35 : Packet type 'StateResponse' received from '/192.168.40.35:56700' for 'D0:73:D5:24:86:58' with sequence '75' and source '2f49573d'
```

**Comment by paulianttila** [comment]
Should EchoRequest be used rather than GetServiceRequest when sending unicast message in OnlineStateUpdater?

https://github.com/openhab/openhab-addons/blob/cdff5a06e7e9b719b9d3bc484c52012eeed30ba2/bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightOnlineStateUpdater.java#L81-L82

**Comment by wborn** [comment]
Maybe it can use the Echo and fallback to GetService if it cannot find the light. According to the docs it is also possible the port can change which is returned the the GetServiceResponse.

See: https://lan.developer.lifx.com/docs/information-messages#stateservice---packet-3

> The port of the service. This value is usually 56700 but you should not assume this is always the case.

I've also seen lights not properly respond which can only be fixed by power cycling them which is probably some kind of firmware bug.

**Comment by paulianttila** [comment]
I changed binding to send both Echo and GetService requests in unicast online check. I have many lifx bulbs and strips, but they are all rather old versions. My lights does NOT response to **unicast** GetService request (sequence number 46 in the log), but maybe there is a difference in different lifx models and firmware versions.

```
15:32:34.791 [TRACE] [.internal.LifxLightOnlineStateUpdater] - D0:73:D5:13:DB:E8 : Light is not online, unicasting request
15:32:34.799 [TRACE] [g.lifx.internal.util.LifxSelectorUtil] - D0:73:D5:13:DB:E8 : Sending packet type 'GetEchoRequest' from '/192.168.20.170:55763' to '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '45' and source '60c12f78'
15:32:34.859 [TRACE] [g.lifx.internal.util.LifxSelectorUtil] - D0:73:D5:13:DB:E8 : Sending packet type 'GetServiceRequest' from '/192.168.20.170:55763' to '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '46' and source '60c12f78'
15:32:34.861 [TRACE] [nternal.LifxLightCommunicationHandler] - D0:73:D5:13:DB:E8 : Packet type 'EchoRequestResponse' received from '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '45' and source '60c12f78'
15:32:34.862 [TRACE] [internal.LifxLightCurrentStateUpdater] - D0:73:D5:13:DB:E8 : The light just went online, immediately polling the state of the light
15:32:34.873 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'lifx:colorlight:f8f350772c' changed from OFFLINE (COMMUNICATION_ERROR) to ONLINE
15:32:34.910 [TRACE] [g.lifx.internal.util.LifxSelectorUtil] - D0:73:D5:13:DB:E8 : Sending packet type 'GetRequest' from '/192.168.20.170:55763' to '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '47' and source '60c12f78'
15:32:34.972 [TRACE] [nternal.LifxLightCommunicationHandler] - D0:73:D5:13:DB:E8 : Packet type 'StateResponse' received from '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '47' and source '60c12f78'
15:32:35.050 [TRACE] [internal.LifxLightCurrentStateUpdater] - D0:73:D5:13:DB:E8 : Polling the state of the light
15:32:35.052 [TRACE] [g.lifx.internal.util.LifxSelectorUtil] - D0:73:D5:13:DB:E8 : Sending packet type 'GetRequest' from '/192.168.20.170:55763' to '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '48' and source '60c12f78'
15:32:35.085 [TRACE] [nternal.LifxLightCommunicationHandler] - D0:73:D5:13:DB:E8 : Packet type 'StateResponse' received from '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '48' and source '60c12f78'
15:32:38.057 [TRACE] [internal.LifxLightCurrentStateUpdater] - D0:73:D5:13:DB:E8 : Polling the state of the light
15:32:38.062 [TRACE] [g.lifx.internal.util.LifxSelectorUtil] - D0:73:D5:13:DB:E8 : Sending packet type 'GetRequest' from '/192.168.20.170:55763' to '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '49' and source '60c12f78'
15:32:38.089 [TRACE] [nternal.LifxLightCommunicationHandler] - D0:73:D5:13:DB:E8 : Packet type 'StateResponse' received from '/192.168.40.30:56700' for 'D0:73:D5:13:DB:E8' with sequence '49' and source '60c12f78'
15:32:40.464 [DEBUG] [ng.lifx.internal.util.LifxNetworkUtil] - Updating network information
15:32:41.063 [TRACE] [internal.LifxLightCurrentStateUpdater] - D0:73:D5:13:DB:E8 : Polling the state of the light
```

Anyhow, it should be rather safe to send them both I guess. @wborn, if you agree, I will do PR.

**Comment by xeroiv** [comment]
I recently updated my lfix devices to firmware version 2.9 and 3.9 depending on the bulb type and this morning a lot of the devices started going offline my openhab instance.

![image](https://user-images.githubusercontent.com/6626311/201152855-6823b9fd-3b49-4ab2-bcb0-1ca217ee4347.png)

**Comment by wborn** [comment]
> I changed binding to send both Echo and GetService requests in unicast online check. I have many lifx bulbs and strips, but they are all rather old versions. 
> Anyhow, it should be rather safe to send them both I guess.

I don't know how many you have but I have 40+ lights. :wink: I'm a bit reluctant to add unneccessary messages because it will cause more traffic for each light. With the current nummer of messages, the UDP traffic is sometimes already unreliable for me on the overly crowded 2.4GHz band where I live. So adding more traffic will probably only make it worse. :neutral_face: 

If GetService does not work with unicast maybe it can then use Echo instead with unicasts?

**Comment by paulianttila** [comment]
> I'm a bit reluctant to add unneccessary messages because it will cause more traffic for each light. With the current number of messages, the UDP traffic is sometimes already unreliable for me on the overly crowded 2.4GHz band where I live. So adding more traffic will probably only make it worse.

But these messages are sent only when light is in **offline** state and broadcast is not enabled (line 82), so not in normal circumstances.


https://github.com/openhab/openhab-addons/blob/1471709b52944b1e6197ad40068129cdfd354f46/bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/LifxLightOnlineStateUpdater.java#L66-L84
