### ISSUE TITLE
[homekit] Thermostat needs Target Heating and Cooling temperatures in Auto mode

### ISSUE THREAD

**Issue by rrgeorge** [openhab/openhab-addons#1368]
The HomeKit Thermostat group only allows for one Target Temperature, which is fine for Heating or Cooling. However, when the thermostat is set to Auto, it should have a separate Target Temperature for Heating and Cooling respectively.

**Comment by J-N-K** [comment]
Can you elaborate why this should be the case? I guess that we have one temperature that is desired by the user, no matter what mode the thermostat is in.

**Comment by rrgeorge** [comment]
When the thermostat is in Auto mode, you can set a target cool and target heating temperature.

**Comment by rrgeorge** [comment]
@yfre You are mistaken. Cooling threshold temperature and heating threshold temperature are optional characteristics. Page 155 of the HomeKit Accessory Protocol Specification.

**Comment by yfre** [comment]
@rrgeorge you are complete right. sorry, i had it wrong in my memory. it is the limitation of openHAB binding but not of the spec. 

but good news, with the PR above for heater and cooler it will also work for thermostat. just tested. works fine. 

![image](https://user-images.githubusercontent.com/11726616/84404290-ecbfde80-ac06-11ea-875e-482bc5b60b10.png)

**Comment by rrgeorge** [comment]
Honestly, I thought this binding was dead. I submitted this issue 4 years ago. I have since moved to using a node-red bridge, since it has access to the full HomeKit spec.

**Comment by yfre** [comment]
yes, it was kind of dead. but i dont like to have a bridge of the bridge. 
so, im trying to add missing accessories and characteristic one-by-one to the binding and get great support for this work from maintainers.
 
we have already 20 accessories types. around 8-9 will follow over the next weeks and then we should have everything except of video/audio and linked services. 

so, maybe you should give another try with the "native" binding.
