### ISSUE TITLE
[nibeheatpump] NibeGW software incorrectly rejects 16 bit addressed data

### ISSUE THREAD

**Issue by elupus** [openhab/openhab-addons#13684]
The nibegw software incorrectly assumes all addresses are 8 bit and the start byte is always followed by 0x00. This is incorrect for 2120-8 pumps. These pumps will send a sequence of "5c 41 c9 f7 00 7f 06" every 2 seconds.

## Expected Behavior

Correctly parses the full message, and asks for token.

## Current Behavior

Rejects data as invalid and potentially start parsing next message at the wrong location, if the 16bit addressed data contains 5C bytes.

## Possible Solution

Adjust software similarly as: https://github.com/elupus/esphome-nibe/pull/17 and https://github.com/yozik04/nibe/pull/65

## Steps to Reproduce (for Bugs)

Run nibegw software against a 2120 heatpump and watch it's debug output.

**Comment by elupus** [comment]
For reference. I don't think this is a major problem for the current nibegw solution. It will mostly just consider the data garbage and continue parsing looking for next message. But since it was found out, i think I should report it here. Background home assistant issue: https://github.com/home-assistant/core/issues/81748

**Comment by elupus** [comment]
Issue is here: https://github.com/openhab/openhab-addons/blob/cdff5a06e7e9b719b9d3bc484c52012eeed30ba2/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW/NibeGw.cpp#L284
and here: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi/nibegw.c#L278

These checks should be removed.

**Comment by lolodomo** [comment]
Signalling the issue to @paulianttila

**Comment by paulianttila** [comment]
@elupus thanks for the notice.

**Comment by paulianttila** [comment]
@elupus it seems that this fix is not enough. Byte 1 (data[1]) should also be included to the checksum calculation. So far byte 1 has been 0, so it has not been influence the xor checksum even it has not been taken into account, but now in the case where byte 1 is '0x41', checksum doesn't match anymore.

Last byte ('06') of the example message '5c 41 c9 f7 00 7f 06' is actually ack, so checksum is 0x7F. Checksum match only if xor is calculated over bytes  "41 c9 f7 00".

**Comment by elupus** [comment]
Ah sorry, yes its part of checksum too. I wonder if i forgot to fix that in the esp32 code.

**Comment by elupus** [comment]
Indeed i did. Hadnt got a report back since fixing. Had it fixed in upper lever parsing.

**Comment by lolodomo** [comment]
Closed by #13752
