### ISSUE TITLE
[WLED] LED Count

### ISSUE THREAD

**Issue by AJErazzor** [openhab/openhab-addons#13698]
Used to be in the old binding format and I believe still available in JSON at 
/json/info/leds/count

https://kno.wled.ge/interfaces/json-api/

**Comment by lolodomo** [comment]
What do you mean by "old binding format" ?

**Comment by lolodomo** [comment]
@Skinah for information.

**Comment by Skinah** [comment]
No idea here, need more information. AFAIK I put all features across so perhaps they have not seen the advanced channels that need to be ticked to see them.

**Comment by Skinah** [comment]
It has now been more than a year and no further info. @AJErazzor can you give an example of how you will use the channel if added?
