### ISSUE TITLE
[deconz] Raspbee2 openHAB 3.3 with Raspbian

### ISSUE THREAD

**Issue by adisD** [openhab/openhab-addons#13692]
There is an issue with openHAB 3.3 on Raspbian that led to Zigbee gateway (Raspbee2) appears as unavailable. 

Phoscon Gateway web application zigbee channel and network parameters have values as in the picture below
![image](https://user-images.githubusercontent.com/136997/201196260-76eaca91-7850-442c-b946-89776c2a5671.png)

Consequence of failure shown above is that all of zigbee sensors in a portfolio are out of function.
 
Version used: openHAB 3.3 and deconz firmware is 2.19.01 dated at 19.8.20222
Operating System is Raspbian

**Comment by J-N-K** [comment]
I don't understand this issue. What exactly is not working? Is deconz not properly starting? Is the connection to deconz not established? Logs from openHAB?
