### ISSUE TITLE
[homematic] HMS100-TF Channels missing while autodiscovered

### ISSUE THREAD

**Issue by litronics** [openhab/openhab-addons#13700]
I am using oder HMS100-TF Sensors to receive temp and humidity readings.

Infrastructure runs on:

- Raspberry4 with Raspbian and docker installed
- all components (OH, Raspberrymatic, MQTT, InfluxDB) running as docker container
- CuxD is used to connect FS-20 devices to Raspberrymatic

Connection from the HMS100 to Raspberrymatic works fine and I see all available readings of the sensor. However within Raspberrymatic the device is reported as "HM-WS550STH-I". This is because CuxD is only providing this option.
Within the deviceconfiguration the Device is set to the correct device type:
![Raspberrymatic_Device_Config](https://user-images.githubusercontent.com/22157317/201463045-f4ca268e-9924-4b2d-b6d6-a3b1b3ef8af6.png)

![Raspberrymatic-readings](https://user-images.githubusercontent.com/22157317/201463445-6d687068-30b9-4944-9230-dc07477dfc79.png)

In OH the homematic bridge is installed an autodiscovery picks up all the devices available in my CCU.

## Expected Behavior
When creating the Thing from the autodiscovered item all available readings of the sensor are available as channels within OH.

## Current Behavior
The Thing created contains temp readings only.

## Possible Solution
no idea

## Steps to Reproduce (for Bugs)

1. Select the item within the inbox and click  "Add as Thing"
2. Thing gets created with missing readings

## Your Environment

* Version used: openHAB 3.3.0 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): EDGE on Win11
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspberry4 -> all components running in docker container

**Comment by MHerbst** [comment]
Are there any messages regarding this device in openhab.log? If not, please proceed as follows:

- remove the thing
- set log mode for the openHAB binding to TRACE
- run a new discovery and add this thing again

Post the relevant parts of openhab.log starting with the discovery (can be quite large).

**Comment by litronics** [comment]
Here the logs:
[scan.log](https://github.com/openhab/openhab-addons/files/9995726/scan.log)
[add_item.log](https://github.com/openhab/openhab-addons/files/9995727/add_item.log)

**Comment by litronics** [comment]
> Are there any messages regarding this device in openhab.log? If not, please proceed as follows:

Doublechecked after removal and recreation of the thing - there are no messages in openhab.log.

**Comment by MHerbst** [comment]
I can see that the binding detects 4 devices of the same type. Are they really the same? If e.g. one of them is different and does not provide all data points all other devices would also only provide these types.

```
 <entry name='CUX1200001' value='HM-WS550STH-I CUX1200001' />
  <entry name='CUX1200002' value='HM-WS550STH-I CUX1200002' />
  <entry name='CUX1200003' value='HM-WS550STH-I CUX1200003' />
  <entry name='CUX1300001' value='HM-WS550STH-I CUX1300001' />
```

In the logs I can't see any data points like "ABS_HUMIDITY". Either they are not requested because of the 4 similar devices or the CCU (and CUXd) are not returning metadata for these data points.

**Comment by litronics** [comment]
No, they are not exactly the same.

CUX12xxx are HMS100-TF (temp & humiditiy) and
CUX13xxx is HMS100-T (temp only)

**Comment by MHerbst** [comment]
I have checked the logs again und according to the scan.log CUX12 and CUX13 are of the same type:
```
{
		ADDRESS=CUX1200001
...
		TYPE=HM-WS550STH-I
}
...
{
        	ADDRESS=CUX1300001
...
		TYPE=HM-WS550STH-I
}
```

This device does has a data point for Humitidy only for Temperature. In my opinion this is not a problem of the binding but a problem of the configuration in CuxD resp. Raspberrymatic.

**Comment by litronics** [comment]
Thanks for digging into the logs again.

In Raspberrymatic the CUX13xxx has the same type but not the same readings:
![Raspberrymatic-readings1](https://user-images.githubusercontent.com/22157317/204156018-8238f36e-3c94-4b0a-8602-7307760f021f.png)

As I am not able to change de device type in Raspberrymatic nor in CuxD I'll file an issue with CuxD as this is initially providing the type for the devices.

Thanks for your support!

**Comment by litronics** [comment]
Just a quick update if some others have the same issue :)

When configuring the devices in CUxD, in order to get the humidity readings, the device-icon must be set to "Wetter Kombisensor". This will configure the device type to "HM-WDS100-C6-O" which provides temp and humidity readings in OH.
