### ISSUE TITLE
[kodi] Binding seems to break some other bindings

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#13716]
On the forum, it was originally reported that the Gardena binding was causing issues with other bindings (including Kodi).

However after testing it turned out that it is actually the Kodi binding which is causing issues with other bindings (including Gardena).

https://community.openhab.org/t/gardena-binding-throws-connection-errors-and-seems-to-break-some-bindings/140085

**Comment by andrewfg** [comment]
@lolodomo for info..

**Comment by lsiepel** [comment]
The kodi binding seems to have a decent userbase, so i would expect more reports of these kind of issues. How can we find out if this is still an issue and if where to fix? As there does not seem to be a log or other direct lead to this binding.

**Comment by andrewfg** [comment]
The then hypothesis was that it was an issue of OH core threadpool exhaustion, where if a binding (including Kodi) would block on a thread, the core would eventually run out of threads. I don't recall if it was solved either in a binding or in the core. So probably you can close this issue.
