### ISSUE TITLE
[openwebnet] Thermo: add support for AUTO/NORMAL mode to bus_thermo_zone

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#13754]
For thermo zones configured as non-standalone (i.e. when they are configure in a system with a 4-zone or 99-zone thermo central unit) the AUTO/NORMAL mode should be supported by the binding.
(This mode was supported in the experimental version 2.5 of the binding)
With this new mode it should possible to set a zone to MANUAL and then set it back to AUTO/NORMAL whiche means the zone thermostat will be set back to the current programming of the central unit.
The name of the mode should be the same as one used in the thermo control panel setting (i.e. AUTO or NORMAL or PROGRAMMING).

**Comment by hyzteric** [comment]
I can help debug if needed, I have a 99 zone central and 8 zones configured. I am using openhab 3.3 at the moment with the bticino binding running well (except I assumed 'program' was 'auto' ;-))
