### ISSUE TITLE
[daikin] Wifi Adapter BRP069B4X

### ISSUE THREAD

**Issue by obrador** [openhab/openhab-addons#13751]
Daikin binding Readme says that module BRP069B41 is supported.

For Daikin devices with external Wifi controller, I’ve looked at the [Compatibility table](https://www.daikin.eu/en_us/product-group/control-systems/daikin-online-controller/connectable-units.html) from Daikin and I see up to 5 different BRP069B4X modules (BRP069B41 to BRP069B45) which are not mentioned in documentation.

Are all BRP069B4X adapters supported by Daikin binding? or only BRP069B41. Should the codumentation be corrected?

**Comment by jimtng** [comment]
I think the documentation only stated the models that have been known / tested to work. The other models _may_ work too. If _someone_ can confirm it, we can add it to the docs.
