### ISSUE TITLE
[enocean] Support for A5_09_04 CO2 gas sensor (+ temperature and humidity)

### ISSUE THREAD

**Issue by lovery** [openhab/openhab-addons#13785]
I have a [Nexelec Insafe+ Carbon CO2 (I420EO)](https://shop.smarthome-europe.com/en/nexelec/4294-nexelec-enocean-air-quality-and-co2-detector-insafe-carbon.html) gas sensor device - A5_09_04 (temperature and humidity sensors also included) Currently openHAB doesn't support any devices from the A5_09 group. I tried to use the generic thing type but I wasn't able to configure it in such a way that I can access the data from the 3 sensors. It would be nice if this is natively supported in openHAB.

I am working on an implementation.

**Comment by BillGOH** [comment]
Hello @lovery,
good work! Might it be possible to address my issue https://github.com/openhab/openhab-addons/issues/13472 in this context, too?

Thank you very much in advance!

**Comment by lsiepel** [comment]
Don't want to hijack this issue, but as github does not have a decent DM feature:
@lovery and @BillGOH, i made [a PR for enocean binding](https://github.com/openhab/openhab-addons/pull/14023) and refactored some code to improve the binding. Are you able to test this version, would be highly appreciated? Just use it for some time and report any problems. There should be no functional changes. 

Jar files:
3.4.2 : https://1drv.ms/u/s!AnMcxmvEeupwjqVDjFvBt87oLIW42Q?e=8pKZTn
4.0.0 : https://1drv.ms/u/s!AnMcxmvEeupwjqVCE_YtH3yeZG5hXA?e=a1d7Hv

**Comment by BillGOH** [comment]
Hello @lsiepel,
thanks for your great work. I tried to use your binding under openHAB 3.4 (openHABian), but it did not work. After I switched the binding the gateway (USB 300) went offline an remained so ("trying to get base id"). I did several reboots, switched back to the original binding, nothing worked - gateway remained offline. I don't know why but after some reboots and removing the USB 300 it went online again - however, with the original binding provided by openHAB 3.4.
I am not sure whether it is a binding problem or a problem with my installation. If you can give me instructions, I could find out (if you like).
Nevertheless is there a possibility to add support for my VOC-sensor (issue https://github.com/openhab/openhab-addons/issues/13472)? So far @lovery and I did not find a working solution.
Thanks again für your efforts!

**Comment by lsiepel** [comment]
Too bad the first try didn't work out. 

1. Remove the current binding.
3. Drop the jar in you addons folder.
4. The binding should be autoamtically installed and initialize your thing's
5. Check if the thing is online and the channels are populated as expected.
6. If something is wrong please provide a log file with the details (prefer debug level)

What did you try with @lovery to get the device listed? We can continue about that in the other issue, as i don't want to hijack this issue as this should be all about the A5-09_04 CO2 sensor :-)

**Comment by BillGOH** [comment]
Hello @lsiepel,
thanks for your answer and your tips. I did it that way, however. I will test it again in due course. @lovery has kindly informed me that she will provide a new version with VOC support in the near future.

**Comment by lsiepel** [comment]
If you get the 'trying to get base id' message again, could you perform the same steps, but then with the updated version installed? Hopefully that will be fix it and you might get some results.
If not, let me know and i'll try to adjust this version. 

Your testing is highly appreciated!

**Comment by BillGOH** [comment]
Hello @lsiepel I am currently testing a binding version form @lovery supporting my VOC sensor. If that's finished I can get back to you.

A bit off-topic: I ordered the following device https://www.piotek.de/PioTek-EnOcean-Multigateway-POE, which supports ser2net. However, I could not get it running with openHAB. Always "Trying to get base ID".
