### ISSUE TITLE
[gree] StHt 8degC heating function missing

### ISSUE THREAD

**Issue by antonmies** [openhab/openhab-addons#13799]
I previously used the 'New Gree Air Conditioner Binding' in OH 2.5.x with Gree GWH09QB-K6DNB8 that has in built 8°C heating feature.

I currently have a 3.3.x branch OH in use and installed the Gree binding from add-on's, but it lacks the StHt feature that was previously functioning.

There is a reference to the commands in https://github.com/tomikaa87/gree-remote/issues/1#issuecomment-430030212 

Quote: "Just checked with an android packet capturing application and can confirm that "opt":"StHt","p":"1.0" is used to turn on and "opt":"StHt","p":"0.0" is used to turn off the 8°C heating mode."

The mode is pretty much optimal to avoid freezing with only little energy consumption and doesn't rely on Openhab being alive or not.

**Comment by Hilbrand** [comment]
This is a duplicate issue of #9438. It looks like this feature/channel (`safetyheat`) was never part of the official 2.5 binding, but only in a custom build.[custom build](https://community.openhab.org/t/new-gree-air-conditioner-binding/36429/414). I could not find the actual code it was part of. I suggest to close this issue and continue discussion in the other issue.

**Comment by lolodomo** [comment]
Duplicate #9438
