### ISSUE TITLE
[http] Expose time of last run (feature request)

### ISSUE THREAD

**Issue by peterhoeg** [openhab/openhab-addons#13802]
It would be awesome if the http binding could expose the datetime of when it last fetched whatever URL it is configured to fetch.

Today, if you have a few items based on data using this binding, it's impossible to tell if the information is stale or not. If there was a "last run/fetched" channel, we could check the timestamp.

**Comment by lolodomo** [comment]
Did you have a look to the profile timestamp-change? I have the feeling your request is already covered through this profile.

**Comment by peterhoeg** [comment]
Didn't know about that, so thank you for that!

I guess *technically*, the timestamp isn't related to each item but instead to the thing itself, but I can make it work this way. I'll give it a go at least!

**Comment by lsiepel** [comment]
Did you succeed? Otherwise, https://github.com/openhab/openhab-addons/pull/15376 could be what you are looking for.

**Comment by lsiepel** [comment]
Fixed by: https://github.com/openhab/openhab-addons/pull/16282
