### ISSUE TITLE
[MIIO] Add support for roidmi.vacuum.v66 (ROIDMI EVA)

### ISSUE THREAD

**Issue by Wqty** [openhab/openhab-addons#13813]
HI! 

I just purchased ROIDMI EVA
The Xiaomi Wifi devices (Mi IO) binding do find the vacuum and after using experimental functions it’s listed as "miio:generic".
This way it's not posiible to to add all functionalities (eg maps)

openhab> bundle:list org.openhab.binding.miio

 ID │ State  │ Lvl │ Version  │ Name

256 │ Active │  80 │ 3.4.0.M5 │ openHAB Add-ons :: Bundles :: Xiaomi Wifi devices (Mi IO) Binding

I've enclosed experimental script output file. 
Please add support for roidmi.vacuum.v66.

[test-roidmi.vacuum.v66-20221130-230016.txt](https://github.com/openhab/openhab-addons/files/10131099/test-roidmi.vacuum.v66-20221130-230016.txt)

**Comment by marcelrv** [comment]
Note, it is currently not foreseen to implement maps for other robots, unless the robot is using the existing rockrobo format
