### ISSUE TITLE
[miele] Migrate time channels from DateTime to Number:Time

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#13840]
This issue is for discussing and proposing a migration from `DateTime` to `Number:Time` for channels **duration**, **elapsed** and **finish**. This is a continuation from #13316.

This would be a breaking change requiring users to recreate items with the new type. In case anyone would persist such channels (which I doubt), for JDBC it would mean migrating from TIMESTAMP to DOUBLE, which would also be breaking.

I'm not sure if this proposal is controversial, since `DateTimeType` actually supports time-only. However, this implementation doesn't seem "clean" to me, at least not when we have `QuantityType` supporting time as unit. Example:

```xtend
rule "Oven 5 minutes left"
when
    Item Oven_FinishTime changed to "1970-01-01T00:05:00.000+0100"
then
   //
end
```

or (because of time-zone issues, epoch seconds cannot be used directly as there will be an offset from local time-zone):

```javascript
val DateTimeType durationState = (Dishwasher_Duration.state as DateTimeType)
val ZonedDateTime durationZoned = durationState.getZonedDateTime()
val endTime = now.plusSeconds(durationZoned.getHour() * 60 * 60 + durationZoned.getMinute() * 60).toInstant()
```

and in logs:
```
2022-12-03 22:22:22.368 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TumbleDryer_FinishTime' changed from 1970-01-01T00:57:00.000+0100 to 1970-01-01T00:56:00.000+0100
2022-12-03 22:23:22.482 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TumbleDryer_FinishTime' changed from 1970-01-01T00:56:00.000+0100 to 1970-01-01T00:55:00.000+0100
```

Usually users will probably prefer to display these values in the format HH:MM. This is equally possible with `Number:Time` by simply using state pattern `%1$tR`. However, this would simplify rules and make logs more readable:

```xtend
rule "Oven 5 minutes left"
when
    Item Oven_FinishTime changed to "5 min"
then
   //
end
```

And in logs:
```
2022-12-03 22:50:21.737 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'TumbleDryer_FinishTime' changed from 29 min to 28 min
```

Since time-only `DateTime` is overlapping in functionality with `Number:Time`, I'm not sure about the reason for having a time-only DateTime at all, and when to actually prefer it over Number:Time?

**Comment by jlaur** [comment]
@kaikreuzer - your opinion here would be appreciated. No rush, just something which has been nagging me for some time with those time-only `DateTime` channels vs. `Number:Time`. I'm not sure if this is just personal preference, or if there are any hard arguments for preferring one over the other in specific cases. The rule example dealing with UTC and local time-zone is probably my best argument for migrating towards something simpler.

**Comment by jlaur** [comment]
Perhaps other @openhab/core-maintainers or @openhab/add-ons-maintainers might also have some input/opinions about time-only `DateTime` vs. `Number:Time` in general.

**Comment by J-N-K** [comment]
I did not follow the discussion, so just a general opinion:

- `DateTime` should be used for a point in time (like "dishwasher program will be finished AT 15:05")
- `Number:Time` should be used for durations or amounts of time (like "dishwasher program will be finished IN 1:05h)

**Comment by jlaur** [comment]
@J-N-K - thanks for the clarification, it makes sense. With this clear definition, for this binding the channels **duration**, **elapsed** and **finish** are all wrong and should be changed to `Number:Time`. I will publish the proposed PR.

**Comment by J-N-K** [comment]
But keep in mind that this is a breaking change that requires all UI users to delete, re-add and re-configure their things.

**Comment by jlaur** [comment]
@J-N-K - yes, I have mentioned the consequences in this issue description and also noted it in the now published PR. I would prepare a PR towards openhab-distro to add a note about this on upgrade.
