### ISSUE TITLE
[DSMR] returns values in Joule instead of kWh

### ISSUE THREAD

**Issue by Mickroz** [openhab/openhab-addons#13847]
## Expected Behavior
Values returned in kWh instead of Joule

## Current Behavior
Values are returned in Joules instead of kWh, now my friend runs 3.3.0 Release, but he hasn't got this issue, and since my P1 port returns the correct values, there must be something changed in the binding itself?

## Your Environment
running openhab 3.4.0.M5 with openhabian on a rpi 4.
DSMR V5 meter connected with usb cable on P1 port.

EDIT:
when changing or forcing an item from default item in the GUI or `%unit%` to `kWh` in .items file, the correct value is shown.

**Comment by Hilbrand** [comment]
The binding itself did not change. So it's not a bug in the binding. In [core ](https://github.com/openhab/openhab-core/pull/3143)there was added that `J` is default for energy quantity types. This seems to cause this issues. It also affects other bindings that use `%unit%` for energy channels that display in `kWh`.

**Comment by Mickroz** [comment]
Ah, thanks that would explain it alot, then this is not a bug, thanks 👍
