### ISSUE TITLE
SAT error and Test method names.

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#13874]
Hope this question fits here. I 'm trying to improve my knowledge about the openhab addons code by grabbing some bindings and perform SAT improvements or code refactoring. While doing so i discovered many warnings about Tests methods that have wrong naming convention.
Like livisismarthome binding that has `testOnDeviceStateChanged_IsReachable` method naming that looks familiar from other projects i know of. I think it is perfectly fine and readable, but just wondering. Is this a well-made decision to not only enforce this convention for regular classes, but also for testing classes?
If not, would it be possible to detect Test controllers and alter SAT check for those like: '^[a-z][a-zA-Z0-9]*[_][A-Z][a-zA-Z0-9]*$'.

**Comment by wborn** [comment]
Most Java projects like openHAB adhere to the Sun/Oracle convention of only using only camel case method names (without underscores):

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

Nowdays with JUnit 5 you can also use `@DisplayName` which allows for using spaces etc which is even better for naming tests:

https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-names

It will also be used as the test names shown in IDEs when running them.

**Comment by lsiepel** [comment]
I'm aware of those conventions, just used to have it different for Test classes. I'll remove the _ and annotate with @DisplayName. 

Thanks.
