### ISSUE TITLE
[Documentation] Second post merge refactoring for bindings f to m needed

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-addons#13882]
@Confectrician, @wborn FYI - I've made some additional review comments after PR has been merged.

_Originally posted by @jlaur in https://github.com/openhab/openhab-addons/pull/13866#pullrequestreview-1210729889_

**Comment by jlaur** [comment]
@Confectrician - I ended up going ~halfway through all the files, and I found only two types of issues:
- Table column alignment (no impact on rendering).
- Tabs to spaces conversion with only one space per tab (readability issue).

If you could take these into consideration for the other PR's also, everything should be fine. :-)

**Comment by Confectrician** [comment]
I can't promise to get this right for each and every tab to space conversion, 
but i have already started to change tabs to spaces manually (instead of applying a automated fix) while working on the next pr. 🙂
