### ISSUE TITLE
[goecharger] API V1 can't change amx (temporary max current)

### ISSUE THREAD

**Issue by machtnichts** [openhab/openhab-addons#13891]
GoECharger binding API V1 can't change amx (temporary max current)

2022-12-09 17:40:00.130 [WARN ] [r.internal.handler.GoEChargerHandler] - Could not update channel maxCurrentTemp with key null and value null

Probably because 

because in thing-types.xml the channel id is defined as 

		<channels>
			<channel id="maxCurrent" typeId="current"/>
			<channel id="maxCurrentTemp" typeId="maxCurrTmp"/>

## Expected Behavior
max Current can be changed by changing the value of item linked to channel maxCurrentTemp

## Current Behavior
the max current is noit changed, only trace
Could not update channel maxCurrentTemp with key null and value null
appears in log file

## Possible Solution
GoEChargerBindingConstants
public static final String MAX_CURRENT_TEMPORARY = "maxCurrentTemporary";

should be 

public static final String MAX_CURRENT_TEMPORARY = "maxCurrentTemp";

## Steps to Reproduce (for Bugs)
try to change the value of item linked to channel maxCurrentTemp

**Comment by machtnichts** [comment]
Update: 
I have just changed public static final String MAX_CURRENT_TEMPORARY = "maxCurrentTemp"; and now it works.

**Comment by machtnichts** [comment]
Patch:

Index: bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java b/bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java
--- a/bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java      (revision 712262fb1e1f84aff3e3fbe75cd6b2d958bc7906)
+++ b/bundles/org.openhab.binding.goecharger/src/main/java/org/openhab/binding/goecharger/internal/GoEChargerBindingConstants.java      (date 1670853080199)
@@ -31,7 +31,7 @@

     // List of all Channel ids
     public static final String MAX_CURRENT = "maxCurrent";
-    public static final String MAX_CURRENT_TEMPORARY = "maxCurrentTemporary";
+    public static final String MAX_CURRENT_TEMPORARY = "maxCurrentTemp";
     public static final String ACCESS_CONFIGURATION = "accessConfiguration";
     public static final String PWM_SIGNAL = "pwmSignal";
     public static final String ERROR = "error";
Index: bundles/org.openhab.binding.goecharger/pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bundles/org.openhab.binding.goecharger/pom.xml b/bundles/org.openhab.binding.goecharger/pom.xml
--- a/bundles/org.openhab.binding.goecharger/pom.xml    (revision 712262fb1e1f84aff3e3fbe75cd6b2d958bc7906)
+++ b/bundles/org.openhab.binding.goecharger/pom.xml    (date 1670854490747)
@@ -11,6 +11,7 @@
   </parent>

   <artifactId>org.openhab.binding.goecharger</artifactId>
+  <version>3.4.0-amx-fix</version>

   <name>openHAB Add-ons :: Bundles :: Go-eCharger Binding</name>

**Comment by wborn** [comment]
I think you're right! Can you create a pull request with the change to get it fixed?

**Comment by lolodomo** [comment]
I am preparing the fix. I checked all channel IDs in constants. Only one was wrong.
