### ISSUE TITLE
[airq] naming conflic between CO and CO2 items

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#13909]
When creating items for the channels `CO Concentration` and `CO₂ Concentration`, in both cases a short-name `<thing>_COConcentration` is proposed. This leads to a naming conflict.

The same problem might exist for other CO₂ channels as well.

## Expected Behavior
Item `<thing>_CO2Concentration` for channel `CO₂ Concentration`
Item `<thing>_COConcentration` for channel `CO Concentration`

## Current Behavior
Item `<thing>_COConcentration` for channel `CO₂ Concentration`
Item `<thing>_COConcentration` for channel `CO Concentration`
naming conflict

## Your Environment
openHAB 3.4.0.M4

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.airq/src/main/resources/OH-INF/thing/thing-types.xml#L191

This is certainly due to the special 2 character that will be ignored. 
Replacing with CO2 in the channel label should fix the problem.

**Comment by MikeTheTux** [comment]
In addition, is there a reason why `performance` and `health` shows up as a number between 0 and 1000 and not as a percentage (0 ... 100%)? `Number:Dimensionless` is used as DataType already.

**Comment by lolodomo** [comment]
Pinging binding author/maintainer:  @aurelio1

**Comment by lolodomo** [comment]
One issue per problem please. So, you have 2 more issues to create. 
The current one is only for your initial problem jCO2).

**Comment by lolodomo** [comment]
Looking at the XML thing description, I realize that the author of this binding makes a mismatch between channel label and description. I find no channel description and channel label are most of the time a description, not a short label !
I can fix the CO2 channel but a full update of channels would be better.

**Comment by lolodomo** [comment]
@Hilbrand : is this issue now fixed since the UI PR is merged? 

@MikeTheTux : I would suggest that you test with 3.4RC1 coming this evening.

**Comment by Hilbrand** [comment]
Yes this should be fixed with the UI PR merge.
