### ISSUE TITLE
[airq] Use Percentage for Health- and Performance-Index

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#13926]
Is there a reason why performance and health shows up as a number between 0 and 1000 and not as a percentage (0 ... 100%)? Number:Dimensionless is used as DataType already.

## Your Environment
openHAB 3.4.0.M4

**Comment by MikeTheTux** [comment]
The same enhancement was already requested here: https://community.openhab.org/t/new-air-q-binding/115989/5

**Comment by fwolter** [comment]
As of OH 4.2.0 there are new channels `healthIndex` and `performanceIndex` providing these indices in percent.
