### ISSUE TITLE
WIP: [iCloud] improve binding

### ISSUE THREAD

**Issue by maihacke** [openhab/openhab-addons#13942]
This issue collects ideas for future improvement of the icloud binding.

**Comment by maihacke** [comment]
Improve device initialization (see https://github.com/openhab/openhab-addons/pull/13691#pullrequestreview-1214373514)

**Comment by maihacke** [comment]
Rethink 2-FA authentication flow. It makes init very complex. Maybe a extra UI (Servlet) is a better solution.

**Comment by lsiepel** [comment]
Please create seperate issues for features and or bugs improving the icloud binding.
