### ISSUE TITLE
[rrd4j] Documentation does not render properly in Main UI

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13953]
When you open the RRD4j add-on documentation in Main UI with OH 3.4.0-SNAPSHOT (or 3.3.0) it does not render properly, instead you'll see:

![Screenshot from 2022-12-14 23-41-33](https://user-images.githubusercontent.com/12213581/207731910-c82d1595-fbd0-460c-861a-ce9bea109701.png)

To reproduce this navigate to "/settings/addons/persistence-rrd4j/" in Main UI and click "More".

I had a brief look at the [webui code](https://github.com/openhab/openhab-webui/blob/68d3ef4234940699f9ba6b1331765ea30431a7c3/bundles/org.openhab.ui/web/src/pages/settings/addons/addon-details.vue#L304-L309) that generates the error.

Perhaps it does not like the `---` separator in the README Markdown on [line 263](https://github.com/openhab/openhab-addons/blame/main/bundles/org.openhab.persistence.rrd4j/README.md#L263).

Maybe @ghys or @Confectrician has seen this before?

**Comment by ghys** [comment]
This is probably it - marked (the Markdown parser library) doesn't support extracting the front matter and the UI's code to do that isn't the best I suppose. [This is a better suggestion](https://github.com/markedjs/marked/issues/485#issuecomment-497506686) but adding a 12kb library for this single purpose is perhaps overkill.
It could probably be solved by removing the `---` in this particular readme.

**Comment by wborn** [comment]
It's fixed now, which is especially useful for new users who get rrd4j preinstalled. :slightly_smiling_face:
