### ISSUE TITLE
[knx] Improve German translation of channel types

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-addons#13959]
With regional setting of the browser configured to German, the "Add channel" dialog looks a bit strange. The translations seem to be done independently over time. 

KNX distinguishes normal and "...-control" channels (see channel desc), and this is sometimes translated as "Kontrolle", sometimes as "Steuerung". Sometimes we use a hyphen, sometimes a space to separate the words. Just have a look here:
![image](https://user-images.githubusercontent.com/2121139/207872160-1cc490ec-1c27-4528-aa56-77d008e582fc.png)

I know this is an issue for Crowdin, and I have already uploaded new suggestions. I think we need some coordination here and support from someone who can set/approve translations.

**Comment by florian-h05** [comment]
@holgerfriedrich 
As I‘ve contributed larger parts of the German translation, I think that I am able to influence it in some ways. I‘ve removed a few of my translations and upvoted yours to have „Steuerung“ instead of „Kontrolle“ and no hyphens for `-control` channels. Hopefully this makes Crowdin to use your translations instead.

**Comment by jlaur** [comment]
@florian-h05 - can you also approve these four strings if they look correct to you?
![image](https://user-images.githubusercontent.com/19519842/207897973-4545e7f8-307d-4c57-a06f-75c960223bcf.png)

To start the automatic workflow of creating a PR all strings must be translated and approved.

**Comment by florian-h05** [comment]
Unfortunately no, I can't approve them.
Looking at who approved the other strings, we can ping @cweitkamp to approve those strings.

**Comment by florian-h05** [comment]
Oh wow, thanks!

@jlaur I've approved the strings for KNX.

**Comment by holgerfriedrich** [comment]
Thanks, everybody, it looks better now. 

But still some inconsitencies (somehow the term "Kontakt-Kontrolle" is still there....,). @florian-h05 could you help to convince Crowdin to switch to the new translations? It seems we to approve the new translations again....
![image](https://user-images.githubusercontent.com/2121139/207984375-056b2b9d-1237-4068-a82d-692bfb15a931.png)

**Comment by florian-h05** [comment]
Yes, I'll have a look at it this midday and convince Crowdin to to what we want.

**Comment by florian-h05** [comment]
@holgerfriedrich I‘ve removed the incorrect translations and approved your translations, hopefully openhab-bot/Crowdin does open a PR now.

**Comment by holgerfriedrich** [comment]
Thanks a Lot, @florian-h05. PR looks good.
