### ISSUE TITLE
[shelly] shellyem3 in 3.4.0.M6 update of status is not working anymore

### ISSUE THREAD

**Issue by kreutpet** [openhab/openhab-addons#13961]
i recently updated to 3.4.0.M6.
all my shelly devices have been working before and after the update the 3EM stopped updating the channels 

the firmware version of the 3EM is 
20221027-110030/v1.12.1-ga9117d3

Binding version is
297 │ Active │  80 │ 3.4.0.M6               │ mvn:org.openhab.addons.bundles/org.openhab.binding.shelly/3.4.0.M6

issue has also been reported [here](https://community.openhab.org/t/shelly-binding/56862/2961?u=kreutzer_peter) 

## Expected Behavior
after update the already configured thing and items of 3EM should continue to work.
## Current Behavior
The 3EM shelly is sending the updates and channels are updated , see debug log.
[3EM.log](https://github.com/openhab/openhab-addons/files/10239604/3EM.log)
the update stops with below exceptions:
```
shellyem3-zaehlerkeller: Unable to refresh status: Status konnte nicht aktualisiert werden
java.lang.NullPointerException: null
        at org.openhab.binding.shelly.internal.provider.ShellyChannelDefinitions.createRelayChannels(ShellyChannelDefinitions.java:350) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyRelayHandler.createRelayChannels(ShellyRelayHandler.java:293) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyRelayHandler.updateRelays(ShellyRelayHandler.java:337) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyRelayHandler.updateDeviceStatus(ShellyRelayHandler.java:202) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.refreshStatus(ShellyBaseHandler.java:522) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

Here the current thing configuration:
`Thing shelly:shellyem3:zaehlerkeller "Energiemessung" @ "Keller"  [deviceIp="192.168.1.91"]`

Here my current item configuration:
`Switch                     WPEnergiemessungRelayOutput "Schalter" <switch> (gZaehler) ["Switch"] {channel="shelly:shellyem3:zaehlerkeller:relay#output"}
Number:Power               WPEnergiemessungDeviceAccumulatedWTotal "Gesamte Energie [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Energy"] {channel="shelly:shellyem3:zaehlerkeller:device#accumulatedWTotal"}
Number:Power               WPEnergiemessungDeviceAccumulatedWatts "Gesamte Leistung [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Power"] {channel="shelly:shellyem3:zaehlerkeller:device#accumulatedWatts"}
Number:Power               WPEnergiemessungMeter1CurrentWatts "Leistung L1 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Power"] {channel="shelly:shellyem3:zaehlerkeller:meter1#currentWatts"}
Number:ElectricPotential   WPEnergiemessungMeter1Voltage "Spannung L1 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Voltage"] {channel="shelly:shellyem3:zaehlerkeller:meter1#voltage"}
Number:ElectricCurrent   WPEnergiemessungMeter1Current "Strom L1 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Current"] {channel="shelly:shellyem3:zaehlerkeller:meter1#current"}
Number:Power               WPEnergiemessungMeter2CurrentWatts "Leistung L2 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Power"] {channel="shelly:shellyem3:zaehlerkeller:meter2#currentWatts"}
Number:ElectricPotential   WPEnergiemessungMeter2Voltage "Spannung L2 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Voltage"] {channel="shelly:shellyem3:zaehlerkeller:meter2#voltage"}
Number:ElectricCurrent   WPEnergiemessungMeter2Current "Strom L2 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Current"] {channel="shelly:shellyem3:zaehlerkeller:meter2#current"}
Number:Power               WPEnergiemessungMeter3CurrentWatts "Leistung L3 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Power"] {channel="shelly:shellyem3:zaehlerkeller:meter3#currentWatts"}
Number:ElectricPotential   WPEnergiemessungMeter3Voltage  "Spannung L3 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Voltage"]  {channel="shelly:shellyem3:zaehlerkeller:meter3#voltage"}
Number:ElectricCurrent   WPEnergiemessungMeter3Current "Strom L3 [%.2f %unit%]" <energy>  (gZaehler) ["Measurement", "Current"] {channel="shelly:shellyem3:zaehlerkeller:meter3#current"}
`
i tried to clean the cache already.

## Possible Solution
no idea

## Steps to Reproduce (for Bugs)
1. update a working 3EM configuration to M6 bundle 

## Context
In the beginning the issue was only on 1 item "WPEnergiemessungDeviceAccumulatedWatts" that did not update.
I thought is may be an issue with the cache. After cleaning the cache all items of the 3EM did not update anymore.

## Your Environment
running openhab in proxmox container running ubuntu 22.04 server

**Comment by lolodomo** [comment]
@markus7017 : no chance you have a look before OH3.4 is released?

**Comment by stefanheijnen** [comment]
Last night I'd also upgrade to 3.4.0 RC1 and have the same issue. Seems like only the device channel is there. Meter1, meter2 and meter3 are gone.

Top part is before the update, below is the channels available after the update.

![image](https://user-images.githubusercontent.com/1306331/208304397-97592244-7ad6-460d-ac5f-dcaef51c4f1b.png)

**Comment by kaikreuzer** [comment]
@markus7017 If you have any chance to comment, please do so!

**Comment by kreutpet** [comment]
I remove the relay output from the item definition.
Still the same error.

**Comment by kreutpet** [comment]
good news. just updated to 3.4.0.1 and issue is resolved. now item get updated
