### ISSUE TITLE
[shelly] Broken images in docs

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#13993]
There are 7 broken images on top of the Shelly Binding documentation:

![Screenshot from 2022-12-17 22-43-28](https://user-images.githubusercontent.com/12213581/208267014-598b0c11-d20e-4e8e-b4af-5b5f816e6d35.png)

See: https://next.openhab.org/addons/bindings/shelly/

Maybe @markus7017 can have a look?

**Comment by holgerfriedrich** [comment]
@wborn The images source is on an external web page. Do we have a policy regarding embedding external content, esp. regarding copyright?

**Comment by wborn** [comment]
I'm not aware of any existing policies regarding that. There was some related discussion about logos in #8513. Maybe @Confectrician knows of a policy? INAL but maybe the @openhab/foundation-staff can consult one to get some clarity on these kinds of subjects and if it is [Fair use](https://en.wikipedia.org/wiki/Fair_use).

**Comment by Confectrician** [comment]
> Maybe @Confectrician knows of a policy?

No. This is topic that is not really resolved, even for the addon images.

**Comment by wborn** [comment]
Apparently an EU court has ruled that embedding images is not copyright infringement, see:

https://torrentfreak.com/embedding-copyright-infringement-eu-court-rules-141025/

**Comment by markus7017** [comment]
I used the external images to avoid problems when including those in the binding repo. Not sure how to handle that, I could update the links

**Comment by markus7017** [comment]
I think it's ok to remove the images, was just for cosmetics

**Comment by wborn** [comment]
> I think it's ok to remove the images, was just for cosmetics

They already got removed in #14007.
Do you plan to re-add images because you added the "PR pending" label @markus7017?

**Comment by markus7017** [comment]
no :-)
