### ISSUE TITLE
[wolfsmartset] Broken link for https://www.wolf.eu/fileadmin/Wolf_Daten/Dokumente/FAQ/3065655_201711.pdf

### ISSUE THREAD

**Issue by jpj-berlin** [openhab/openhab-addons#13995]
The link for Related Documentation from WOLF is broken.

**Comment by holgerfriedrich** [comment]
Following the official Wolf download page
https://www.wolf.eu/de-de/professional/downloads/downloadcenter?selection=tag_%23WRS

The link should be updated to 
https://oxomi.com/service/json/catalog/pdf?portal=2024876&catalog=10406695
