### ISSUE TITLE
[jsscripting] Memory leak when saving a corrupted script file?

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#14019]
When you have a corrupted JS script file (means something that has a bug, like referencing a non existent var) and upgrade a npm module, the dependency tracker seems to recognize several modified dependency files (which is correct for npm modules, but it should only reload all scripts after all dependencies were upgraded, this is another problem) and tries to reload the script multiple times.

After some time, openHAB logs heap space and OoM warnings.

The following happens and is important:

1. A script file is loaded
2. Evaluation/Loading of the script file fails with a `ScriptException`
3. Seems like the engine is not cleaned up (closed) after such a failure

The question is: What does core when a script loading fails? Does it close the engine then? Or does the engine need to close itself on such a failure?

Please note that I still need to reproduce the issue and a have a closer look (heap dump/VisualVM) to be 100% sure that it is how I described it.

@J-N-K Can you please help me here with your knowlegde of core?
@jlaur FYI

**Comment by J-N-K** [comment]
Regarding the multiple reloads: 

The `DependencyTracker` is free to choose when a change in dependencies is reported (remember that it is not even necessary that the dependency is a file, a tracker could also check some remote repository or a memory resource). So it is of course possible that changes are collected and reported only once. This needs to be implemented in the dependency tracker itself.

It might be - I didn't check thoroughly - that there is a concurrency issue when several attempts are made to reload the same file. There is something `synchronized` in the `AbstractScriptFileWatcher`, but I'm not 100% sure that is the best way.

Regarding flood failures:

Correct, I believe the engine is not properly removed if loading fails. I'll check that and propose a fix.

**Comment by florian-h05** [comment]
@J-N-K 

> So it is of course possible that changes are collected and reported only once. This needs to be implemented in the dependency tracker itself.

So it is not possible to implement this in the addon itself? 
I‘ve seen your Refactor WatchService PR, does this help here?

> Can you add an issue in core to track that - in case I forget about it?

Done, see https://github.com/openhab/openhab-core/issues/3242.

**Comment by J-N-K** [comment]
Exactly the opposite. JS Scripting extends the abstract dependency tracker in core. There you need to add special handling code. I‘m currently not on reach of a dev system, I can give some advice later (or more likely tomorrow).
