### ISSUE TITLE
[deCONZ] Add support for Air Purifiers

### ISSUE THREAD

**Issue by fsedarkalex** [openhab/openhab-addons#14011]
I would like to request addition of Air purifier thing type to the deCONZ binding.

I was loooking for it but it seems as there was no feature request for that yet.

In detail I am trying to control my STARKVIND device which works perfectly from deCONZ but seems like OpenHAB simply does not know about this thing type: ZHAAirPurifier

For further reference: https://dresden-elektronik.github.io/deconz-rest-doc/devices/ikea/starkvind_air_purifier/

**Comment by J-N-K** [comment]
Please provide the REST API response for this device.

**Comment by vivienbo** [comment]
Hello,

On my side I'm rather trying to use it with another binding but I found [this thread from `zigpy` project that may contain the information needed](https://github.com/zigpy/zha-device-handlers/issues/1215)

```json
{
  "node_descriptor": "NodeDescriptor(logical_type=<LogicalType.Router: 1>, complex_descriptor_available=0, user_descriptor_available=0, reserved=0, aps_flags=0, frequency_band=<FrequencyBand.Freq2400MHz: 8>, mac_capability_flags=<MACCapabilityFlags.AllocateAddress|RxOnWhenIdle|MainsPowered|FullFunctionDevice: 142>, manufacturer_code=4476, maximum_buffer_size=82, maximum_incoming_transfer_size=82, server_mask=11264, maximum_outgoing_transfer_size=82, descriptor_capability_field=<DescriptorCapability.NONE: 0>, *allocate_address=True, *is_alternate_pan_coordinator=False, *is_coordinator=False, *is_end_device=False, *is_full_function_device=True, *is_mains_powered=True, *is_receiver_on_when_idle=True, *is_router=True, *is_security_capable=False)",
  "endpoints": {
    "1": {
      "profile_id": 260,
      "device_type": "0x0007",
      "in_clusters": [
        "0x0000",
        "0x0003",
        "0x0004",
        "0x0005",
        "0x0202",
        "0xfc57",
        "0xfc7d"
      ],
      "out_clusters": [
        "0x0019",
        "0x0400",
        "0x042a"
      ]
    },
    "242": {
      "profile_id": 41440,
      "device_type": "0x0061",
      "in_clusters": [],
      "out_clusters": [
        "0x0021"
      ]
    }
  },
  "manufacturer": "IKEA of Sweden",
  "model": "STARKVIND Air purifier",
  "class": "zigpy.device.Device"
}
```

Also [this thread from OpenHAB forum implementing a solution using Zigbee2MQTT](https://community.openhab.org/t/use-case-integrating-ikea-starkvind-air-purifier-into-openhab/142860) might be of related use.

**Comment by J-N-K** [comment]
Unfortunately I need the response from the deconz REST API
