### ISSUE TITLE
[easee] Missing values from https://api.easee.cloud/api/chargers/.../state

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhab-addons#14037]
I recently upgraded to openHAB 3.4 on my Raspi 4 and was happy to see an Easee-Addon. Before I was parsing the results from https://api.easee.cloud/api/chargers/[SERIALNUMBER]/state after requesting an access token. After setting up Easee Binding I'm now missing quite a few values that I used in my sitemap, these include (not a complete list):

energyPerHour
cellQuality
wifiQuality
inVoltageXYZ (XYZ replaced by phase etc. like inVoltageT2T3)
inCurrentXYZ (XYZ replaced by phase etc.like inCurrentT4)
cableRating

Did Easee change their API, seems I can't find documentation for https://api.easee.cloud/api/chargers/.../state anymore... well it seems that call is deprecated, but how can we get these values now?

@alexf2015 Thank you for the initial contribution!

**Comment by Diapolo** [comment]
Did no other person using this addon make these observations?

**Comment by alexf2015** [comment]
It seems that the endpoint was moved to the site which now returns overall site state + all charger states.

**Comment by Diapolo** [comment]
Could you also consider adding the missing values I mentioned in the first posting? I'm willing to discover which ones are missing, but I can't help in implementing the changes for this addon.

**Comment by Diapolo** [comment]
@alexf2015 It seems they changed their JSON-response so that `latestFirmware` isn't promoted anymore (was often lagging behind the installed version anyway) and the added a boolean value `connectedToCloud`. Just for reference if you plan to update your addon.

**Comment by alexf2015** [comment]
The endpoint was readded to the docs. But as I already assumed it is now deprecated: https://developer.easee.cloud/reference/get_api-chargers-id-state

I will rework that when I find some time that means I will switchover to the new endpoint and also add the missing values.

**Comment by alexf2015** [comment]
@Diapolo 
Do you have an idea what is the difference between
1. isOnline and connectedToCloud
2. totalPower and energyPerHour (the unit is different but the value should be the same)

**Comment by Diapolo** [comment]
@alexf2015 AFAIK totalPower is the current charging power in kW (for me this sits around 10.X in the top, which is reasonable for a 11 kW charger), energyPerHour is a value I've not seen yet? Where are you getting that from?

My understanding for isOnline would be that a charger is CURRENTLY online and reachable from the Easee network, whereas connectedToCloud could be a more precise and show that the Easee cloud connection is working? It's just a guess and perhaps they are deprecating some old values and just reworded them?

**Comment by alexf2015** [comment]
should be implemented by #14614
