### ISSUE TITLE
[jrubyscripting] Configuration table hard to read

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#14049]
The table used in the [JRuby Scripting Configuration](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.automation.jrubyscripting#jruby-scripting-configuration) has columns that use up too much space making it hard to read.

The website has the same issue, see: https://www.openhab.org/addons/automation/jrubyscripting/

![Screenshot from 2022-12-23 13-25-44](https://user-images.githubusercontent.com/12213581/209336501-f704c980-44b5-4037-bfd2-39e865275473.png)

Maybe @boc-tothefuture, @ccutrer or @jimtng can have a look.

**Comment by jimtng** [comment]
very aware of this

**Comment by jimtng** [comment]
This has been resolved with #14489 but has merge conflicts if it were to be applied onto 3.4.x branch.

Should we prepare a separate PR to merge just the README.md to the 3.4.x branch? The information in it applies to both versions.

**Comment by wborn** [comment]
> Should we prepare a separate PR to merge just the README.md to the 3.4.x branch?

We can do that but I can imagine the @openhab/documentation-maintainers will also need to do something for any 3.4.x doc changes to be published on the website.

**Comment by Confectrician** [comment]
Thanks for the notification.
Yes, we would need to add this manually to the stable docs in this case.
Ther is no autmated build for bringing up addon docs changes into the stable docs after a release.

Here's how to do it:

1. Grab all needed changes for the readme
2. Open a dedficated Pull Request to the openhab docs repo agains the branch `final stable` with those changes.

The needed readme file is located here:
https://github.com/openhab/openhab-docs/blob/final-stable/_addons_automation/jrubyscripting/readme.md
