### ISSUE TITLE
[MyBMW] Bridge is not able to connect

### ISSUE THREAD

**Issue by JuergenSmo** [openhab/openhab-addons#14065]
Since about two weeks the bridge is not able to connect anymore. Afer enabliing the debug log I get following error message:

 2022-12-26 11:34:02.112 [DEBUG] [.internal.handler.MyBMWBridgeHandler] - ###### Discovery Fingerprint Data - BEGIN ######
2022-12-26 11:34:02.114 [DEBUG] [.internal.handler.MyBMWBridgeHandler] - {"url":"https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?tireGuardMode\u003dENABLED\u0026appDateTime\u003d1672050839283\u0026apptimezone\u003d60","status":500,"reason":"Internal Server Error","params":"{tireGuardMode\u003dtireGuardMode\u003d[ENABLED], appDateTime\u003dappDateTime\u003d[1672050839283], apptimezone\u003dapptimezone\u003d[60]}"}
2022-12-26 11:34:02.115 [DEBUG] [.internal.handler.MyBMWBridgeHandler] - ###### Discovery Fingerprint Data - END ######

![image](https://user-images.githubusercontent.com/95683172/209540154-f2bd1c00-21b8-43f4-b9c9-d658282f6e4c.png)

## Expected Behavior
The bridge should be able to connect to the BMW server.

## Current Behavior
The brdige try to connect, get the error and switch back to ofline.

## Possible Solution
With the BMW app on my mobile phone I am able to connect. I also check the data flow using wireshark but I was not able to see any kind of error in it. The data flow from Openhab looks similar to what the app on the mobile phone is doing.

## Steps to Reproduce (for Bugs)
1. Set the binding to disable
2. Set the bridge to enable
3. See the debug log

## Context
Without a working bridge the whole binding is of course not working.

## Your Environment
Raspberry PI 4B 4 GB mit Raspian Buster and OpenHAB 3.4

**Comment by mherwege** [comment]
More info is available in the [forum](https://community.openhab.org/t/mybmw-binding/130935/131).
The binding was using some V1 API calls and these do not work anymore. The have to be replaced with V2 calls. This also changes all the data transfer formats, so is a major effort. See the forum for discussion of the work on this.

**Comment by JuergenSmo** [comment]
@mherwege: Thank you very much. I will follow the forum to see the progress. I am also fine to test.

**Comment by jlaur** [comment]
@weymann - FYI.

**Comment by martingrassl** [comment]
working on it

**Comment by pudermueller** [comment]
Same error behaviour in my config.

**Comment by sheilbronn** [comment]
I am also looking forward to see a fix during the cold weather ;) !
(I'm using the binding to start the car's heating 15 minutes before leaving the house only when outside temperature is not high to prevent frost on the window... ;)
Thanks for your work!

**Comment by martingrassl** [comment]
Hi, I built the first beta version, you can find more information here: https://community.openhab.org/t/mybmw-binding/130935/139

**Comment by JuergenSmo** [comment]
Hi,
many thanks for your work!! The beta is working like a charm for me. I have not yet tested lights and horn bt will do later today. But all the values are back now.

**Comment by JuergenSmo** [comment]
Lights and horn also working for me.

**Comment by lolodomo** [comment]
I would suggest to keep the issue open until a change is proposed and merged.

**Comment by JuergenSmo** [comment]
make sense

**Comment by sheilbronn** [comment]
> I am also looking forward to see a fix during the cold weather ;) ! (I'm using the binding to start the car's heating 15 minutes before leaving the house only when outside temperature is not high to prevent frost on the window... ;) Thanks for your work!

I can also confirm, that lights, honk, and heating (Standheizung) can also be controlled remotely with the new test version! Thanks!

**Comment by JuergenSmo** [comment]
fixed with 3.4.2.
Many thanks.
