### ISSUE TITLE
[shelly] Wrong profile after restart of thing / rereading configuration on Shelly TRV

### ISSUE THREAD

**Issue by goligo** [openhab/openhab-addons#14069]
## Expected Behavior
When OpenHAB is restarted, or a thing is restarted, its configuration should not be changed and should match the actual configuration on the device.

## Current Behavior
When the current selectedProfile is 0 (schedule disabled) and the thing is restarted, the selectedProfile is changed to 1. However only in OpenHAB, the selected profile on the device itself stays 0 (disabled). 

The reason seems to be the way, how the profile state is persisted in the shelly settings:
"schedule":false,"schedule_profile":1

So when the profile is set to 0, the shelly TRV does not set "schedule_profile" to 0, but instead "schedule" to false.

## Possible Solution
I guess the binding needs to take care of this behaviour, and do it the other way round - if "schedule" equals false, then selectedProfile should be set to 0, regardless of the value of "schedule_profile"

## Steps to Reproduce (for Bugs)
1. Have an item linked to the selectedProfile channel of a Shelly TRV
2. Change selectedProfile to 0 (DIsabled)
3. Disable and enable thing to reinitialize configuration
4. See that selectedProfile has wrongly been set to 1 

## Context
UI does show wrong data, which does not match the actual setting on the device.

## Your Environment
OpenHAB 3.4 on a Raspberry 3 with OpenHabian

**Comment by goligo** [comment]
Hmmm... the code looks like it does exactly what I was proposing as a solution. So why does it still go wrong?

https://github.com/openhab/openhab-addons/blob/3.4.x/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/handler/ShellyComponents.java#L441-L445

**Comment by goligo** [comment]
Ah, I think I found the root cause, in the latest changes to profile handling

https://github.com/openhab/openhab-addons/commit/5b038786d586e47880ffca4343bdd35d9c94101f#diff-719dc6767a12baa72226bcfcb8539394229258660c3b55a6a84b7bc9d2ec09a7

Before it was
```
            if (id <= 0) {
                return "DISABLED";
            }
```
now it is
```
        if (id <= 0 && settings.thermostats != null) {
            id = settings.thermostats.get(0).profile;
        }
```

Which is wrong, if id is 0, it is disabled, it should NOT return the last set profile id, which can be found in the settings object, but just 0.

@markus7017 I guess. you want to have a look at it?

**Comment by goligo** [comment]
Another thing I discovered while looking into this: The profile list/state options do also miss the 0 entry to disable the schedule. So if you just bind it and use the predefined options, there is no possibility to disable.

**Comment by goligo** [comment]
On my test installation the behaviour is even more strange - when trying to change the state to 0, the profile is set to disables on the device, but stays on its old value in OpenHAB. I guess the behaviour varies dependent on whether Coiot is used or not.

**Comment by goligo** [comment]
This is a fix for a regression in OpenHAB 3.4, so the fix should also be downported. Is there any automation or tool support for downports, or do I have to make an additional PR for the downport?

**Comment by markus7017** [comment]
The will be now jackpots to 3.3 or earlier, you need to upgrade to 3.4.2, which is very stable and then 3.4.3-SNAPSHOT

**Comment by goligo** [comment]
I gave up on reporting or fixing bugs in the Shelly binding, so I am closing this one as well.
