### ISSUE TITLE
[openwebnet] BTicino binding does not process general/area/group commands

### ISSUE THREAD

**Issue by TheNinth7** [openhab/openhab-addons#14063]
Individual things/items in openHAB are not updated if their status is changed in the BTicino system via a general, area or group command.

**Comment by TheNinth7** [comment]
One comment for this enhancement: if it is implemented, also a way to deal with devices in PUL mode needs to be implemented. If the PUL option is set on the actuator, it is excluded from general/area/group commands. To reflect this, such an option would need to be introduced to the Things in openHAB and if it is set, those should not be affected by general/area/group commands. It may be possible to set this option automatically during discovery, at least the My Home Suite is able to read the actuator's configuration via the bus, but not sure if the binding can. If not, then setting it manually is probably a good-enough solution.

**Comment by mvalla** [comment]
discussio on desing here: https://community.openhab.org/t/group-of-lights-as-new-thing-or-not/148464

**Comment by mvalla** [comment]
@TheNinth7 as you may have seen this issue has been resolved and included in the latest OH Milestone. If you could test it before official release it would be useful.

**Comment by TheNinth7** [comment]
> @TheNinth7 as you may have seen this issue has been resolved and included in the latest OH Milestone. If you could test it before official release it would be useful.

Hi @mvalla, I am very sorry for coming back to you only now. Unfortunately health and family reasons have prevented me from working on those home automation stuff in recent months. Is this still open? If yes, I may be able to test it now.

**Comment by mvalla** [comment]
@TheNinth7 the issue has been already closed and integrated in the official OH version. 
Feel free if you have time to upgrade to the lastert OH version and test the support for general/area/group commands (read carefully the related documentation in the README).
