### ISSUE TITLE
[daikin] Fan Movement not working for Alira X with built in wifi

### ISSUE THREAD

**Issue by carda21** [openhab/openhab-addons#14084]
## Expected Behavior
When I update the Fan Movement channel, the Fan Movement should update on the Akira X.

## Current Behavior
Instead of the above, the channel is not updating.

I have some trace logs for the daikin split system in questions and I believe I know where the issue is.  the current binding is looking for a f_dir variable from the Daikin API.  It uses this variable to set / get the fan movement.  On the Alira X split system, there is no f_dir variable.  Instead there is a f_dir_ud (Vertical) and f_dir_lr (Horizontal).  these variables are either set to 0 for off, or S for on.

So f_dir_ud=S,f_dir_lr=0 - Means Vertical
So f_dir_ud=0,f_dir_lr=S - Means Horizontal
So f_dir_ud=S,f_dir_lr=S - Means Horizontal and Vertical
So f_dir_ud=0,f_dir_lr=0 - Means Stopped.

Logs below

```
Up and Down
ret=OK,pow=0,mode=3,stemp=21.0,shum=0,adv=13,dt1=21.0,dt2=M,dt3=21.0,dt4=25.0,dh1=0,dh2=0,dh3=0,dh4=0,dhh=0,alert=16,f_rate=3,dfr1=A,dfr2=A,dfr3=3,dfr4=A,dfr6=A,dfrh=0,f_dir_ud=S,f_dir_lr=0,ndfd1=00,ndfd2=00,ndfd3=S0,ndfd4=00,ndfd6=00,ndfdh=00

Lef and Right
ret=OK,pow=0,mode=3,stemp=21.0,shum=0,adv=13,dt1=21.0,dt2=M,dt3=21.0,dt4=25.0,dh1=0,dh2=0,dh3=0,dh4=0,dhh=0,alert=16,f_rate=3,dfr1=A,dfr2=A,dfr3=3,dfr4=A,dfr6=A,dfrh=0,f_dir_ud=0,f_dir_lr=S,ndfd1=00,ndfd2=00,ndfd3=0S,ndfd4=00,ndfd6=00,ndfdh=00

Stopped
ret=OK,pow=0,mode=3,stemp=21.0,shum=0,adv=13,dt1=21.0,dt2=M,dt3=21.0,dt4=25.0,dh1=0,dh2=0,dh3=0,dh4=0,dhh=0,alert=16,f_rate=3,dfr1=A,dfr2=A,dfr3=3,dfr4=A,dfr6=A,dfrh=0,f_dir_ud=0,f_dir_lr=0,ndfd1=00,ndfd2=00,ndfd3=00,ndfd4=00,ndfd6=00,ndfdh=00

3D
`ret=OK,pow=0,mode=3,stemp=21.0,shum=0,adv=13,dt1=21.0,dt2=M,dt3=21.0,dt4=25.0,dh1=0,dh2=0,dh3=0,dh4=0,dhh=0,alert=16,f_rate=3,dfr1=A,dfr2=A,dfr3=3,dfr4=A,dfr6=A,dfrh=0,f_dir_ud=S,f_dir_lr=S,ndfd1=00,ndfd2=00,ndfd3=SS,ndfd4=00,ndfd6=00,ndfdh=00

```
## Your Environment

* Version used: OpenHAB 3.4.0 Daikin 3.4.0

**Comment by lsiepel** [comment]
Do you now the last previous version that did not hold this bug?

**Comment by carda21** [comment]
I believe this has always been there. This is a newer Daikin split system

**Comment by lsiepel** [comment]
@carda21 can you test the jar from the linked PR? Thanks!

**Comment by carda21** [comment]
Will do
