### ISSUE TITLE
[gardena] Log-warn: String can not be castet to Number

### ISSUE THREAD

**Issue by kuczerek** [openhab/openhab-addons#14083]
If there is a mower thing connected to the gardena bridge, every time the battery state of the mower changes, the following log entry is reported in openhab.log

`.... [WARN ] [internal.handler.GardenaThingHandler] - Value of propertyPath 'common.attributes.batteryState.value' can not be casted to Number: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')`

## Expected Behavior

No log entries in openhab.log, when the battery state of the mower changes.

## Current Behavior

Right now my mower is offline because of winter timer. Nevertheless there is a mower thing in openhab connected to the gardena bridge. If I disable and re-enable the bridge, I get the following log entries in DEBUG mode: [gardena.log](https://github.com/openhab/openhab-addons/files/10313583/gardena.log). The "WARN" log entry is at 2022-12-28 11:05:07.649.
I think, I noticed these log entries the first time during this summer, when the mower was active. Despite the log entries, I never noticed wrong battery states in openHAB. The mower channel "common#batteryLevel" seems to show the correct values.

## Possible Solution

Don't know ;-)

## Steps to Reproduce (for Bugs)

1. Attach a mower thing to the gardena bridge
2. Disable gardena bridge
3. Enable garden bridge and watch the log.

## Context

Keep the log clear

## Your Environment

* Version used: openHAB 3.4
* Environment name and version: OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
* Operating System and version: Raspbian GNU/Linux 11 (bullseye)

**Comment by jlaur** [comment]
@gerrieg, @andrewfg - FYI.

**Comment by andrewfg** [comment]
I am guessing that the mower is reporting its battery level as a continental number with decimal comma, rather than point. Or something like that. But in order to track it down we need to see the log trace data. => @kuczerek can you please do that?

**Comment by kuczerek** [comment]
Yes, no problem. Is there a documentation how to do a log trace? I pasted the log output in DEBUG level in the log file provided with this issue, but I think that's not what you are looking for...

**Comment by andrewfg** [comment]
> Is there a documentation how to do a log trace?

From the OH console just type in the following.. 

```
log:set TRACE org.openhab.binding.gardena
```
and when you have finished you can do log:set DEFAULT

**Comment by kuczerek** [comment]
I did that as I opened this issue. Please have a look at my provided log-file:  [gardena.log](https://github.com/openhab/openhab-addons/files/10313583/gardena.log). It is already in the issue description.

**Comment by andrewfg** [comment]
^
@kuczerek the log that you provided is at DEBUG level; but in order to find the problem, we need to go deeper with logging at TRACE level.

**Comment by kuczerek** [comment]
Sry, this is my log in TRACE mode: [gardena_TRACE.log](https://github.com/openhab/openhab-addons/files/10318384/gardena_TRACE.log)

I managed to setup a OH 4.0 development environment, but wasn't able to reproduce the issue in 4.0 master stream. So I tried to find the differences between my productive 3.4 installation and the 4.0 environment.

I stopped the 3.4 server, checked that there are no custom addons in the addons folder,  cleared the cache and restarted the server. I deleted the gardena bridge and mower and recreated them --> Same problem as before.

But I noticed, that there is a difference between 3.4 and 4.0: In 3.4 the channel of the mower is shown as "String":
![gardena_Screenshot_1](https://user-images.githubusercontent.com/59532326/209925776-cb3e4482-cb2e-4ab9-bb5e-6268fdf5b744.png)

If you try to create and link an item to this channel, the definition changes to "number":
![gardena_Screenshot_2](https://user-images.githubusercontent.com/59532326/209926276-4e60fe18-7558-412b-9401-aa37811c1cb0.png)

If I have a look at 4.0, everything is defined as "String". 

Before upgrading to 3.4 some days ago I used a 3.4 snapshot version in OH 3.3, because of the authentication changes. Don't know, if now something is mixed up in my configuration.

**Comment by andrewfg** [comment]
Hmm. From the trace log we can see that the mower is sending 'battery state' = OK (a string) and 'battery level' = 100 (a number). The latter could be passed to a string or a number item, but the former can only be passed to a string item.

**Comment by andrewfg** [comment]
@kuczerek shall we close this issue?

**Comment by kuczerek** [comment]
@andrewfg, yes!

It was my fault. I changed the type to the Item from Number to String and reconnected it to the battery state channel. Everything is fine, it was not a bug.

Thanks,
kuczereck
