### ISSUE TITLE
[modbus] Updating Unchanged Values not working

### ISSUE THREAD

**Issue by gilsdorfer** [openhab/openhab-addons#14112]
I'm trying to control active load balancing with my Alfen wallbox. It works the way, that you can set the max current. This value needs to be written at least each second, otherwise the wallbox will fall back to a fix safe value of 16.0 A.

I can read all kinds of values and I can also set the load balancing current, but this will only work for a short period, then the wallbox falls back to 16.0 Ampere. I have set the "Interval for Updating Unchanged Values" in advanced settings to 400ms, which is the same frequency the regular data poll will happen. 
In the log I can see regular poll will read from the wallbox every 400ms, but will only once write the new value (if changed in the dashboard) to the wallbox. Am I doing something wrong or is this not working as expected?

`UID: modbus:poller:1bd5287f84:aa59a0a48c
label: Regular Poll
thingTypeUID: modbus:poller
configuration:
  length: 15
  start: 1200
  refresh: 400
  maxTries: 3
  cacheMillis: 50
  type: holding
bridgeUID: modbus:tcp:1bd5287f84
location: Carport
`

`UID: modbus:data:27c8045264
label: Modbus Slave Max Current
thingTypeUID: modbus:data
configuration:
  readTransform: default
  writeTransform: default
  writeType: holding
  updateUnchangedValuesEveryMillis: 400
  writeValueType: float32
  writeMultipleEvenWithSingleRegisterOrCoil: true
  writeMaxTries: 1
  writeStart: "1210"
bridgeUID: modbus:poller:1bd5287f84:aa59a0a48c`

**Comment by ssalonen** [comment]
> I have set the "Interval for Updating Unchanged Values" in advanced settings to 400ms, which is the same frequency the regular data poll will happen.

This makes no sense to me, what are you trying to achieve?

From binding docs

> Interval to update unchanged values. 

> Modbus binding by default is not updating the item and channel state every time new data is polled from a slave, for performance reasons. Instead, the state is updated whenever it differs from previously updated state, or when enough time has passed since the last update. The time interval can be adjusted using this parameter. Use value of 0 if you like to update state with every poll, even though the value has not changed. In milliseconds.

Normally you would not this setting. It can be used for cases where you want to have high poll rate, but not spam openHAB with events for no reason when the value is not changing.


---

Please also check autoupdate documentation section, I have a guess that you might get confused by that one.

You might want to disable the autoupdate, so that item state always reflects value actually read from the device

https://www.openhab.org/addons/bindings/modbus/#autoupdate-parameter-with-items

**Comment by gilsdorfer** [comment]
Hello, maybe I did not describe correctly what I'm trying to achieve. 
My use case:
Charge my electric vehicle  with available solar power. That means I have to reduce charging current in winter.

From the documentation of my charger:
"When a maximum current is enabled and the Modbus master did not update this for a certain time, the
charging station will fall back to its safe current."

That means I have to write a max current value to the charger frequently, even if it does not change at all, otherwise the charger will set back the value to the fallback value after a period. The concept is similar to OH expiration timers in meta data.

**Comment by ssalonen** [comment]
Ok.

the parameter in question has no relation to writes, perhaps that is something that was unclear.

If you want to write the value every second/every 400ms/whatever, you need use openHAB rules for that. I actually do similar thing with my own setup

**Comment by gilsdorfer** [comment]
Ok, thank you for clarifying. 
Maybe I will do with a script, maybe with metadata expiration. That came to my mind, when I wrote the previous comment.
