### ISSUE TITLE
[mqtt] Outgoing Value Format should not use localised decimal separator

### ISSUE THREAD

**Issue by jlaba** [openhab/openhab-addons#14118]
Following situation:
I have an item with a floating point value and I want to sent it to an MQTT broker. Outgoing Value Format is set to %.2f. Language is set to german and country is also set to german.

Result: The MQTT broker recieves e.g. 500,20

Expected Result: MQTT broker should recieve 500.20 (dot instead of comma as decimal separator)

From my understanding, the problem is, that the java Formatter replaces the decimal separator with a locale specific separator.

How can I avoid the replacement or especially, how can I make sure, that the MQTT broker recieves a number with . as decimal separator.

**Comment by lsiepel** [comment]
The binding can’t automatically detect what the remote endpoint expects as seperatoe, so the best thing it can do is to adjust to the openHAB locale.

One option could be to use [transformationPatternOut](https://www.openhab.org/addons/bindings/mqtt.generic/)
If you need help to configure this, I would suggest to post it in the community forums as there are way more users that see your question.
