### ISSUE TITLE
Bindings maintained at multiple places

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#14129]
The last couple of weeks i have been chasing several older issues and i was noticed by @jlaur about some bindings maintaned elsewhere. He pointed me at https://github.com/openhab/openhab-addons/issues/13706 where some of that came to light. The discussion that followed is very interesting and as far as i know it did not come to a conclusion yet.
I completely agree that that discussion was (partly) off-topic from the issue that @lolodomo raised and it would be better to have a seperate issue for it.

That is why i create this issue. I like to know how to proceed with bindings that are maintained at different places. If i understand it right, @hmerk [raised](https://github.com/openhab/openhab-addons/issues/13706#issuecomment-1321054007) an issue about this with the AC. I could not find it, but did it came to a conclusion?

@ccutrer pointed out there are about four options (feel free to add more suggestions):

_1. The status quo. You don't. The official addons bitrot, and continue to ignore that smarthomej versions exist.
2. The official addons continue to bitrot, but at least add a note in their READMEs that acknowledge the existence of and links to smarthomej. Not a great experience, but at least makes it more possible for an end user to discover smarthomej, instead of getting frustrated at brokenness and apparent non-maintenance of an addon that might be critical to them, and losing them from the openHAB platform altogether.
3. Smarthomej (or at least those addons that duplicate official addons, but maybe all of them) merges back into the official repo. 4. Sounds like there's history here that may make this difficult.
4. openhab-addons admits that their version of these bindings have been abandoned, and that better versions are available in the community. Just remove them completely, possibly at least leaving their readmes in place on the openHAB docs website pointing to smarthomej._

Also @florian-h05  and others commented. So can we proceed with this discussion? Also to determine the size of this issue it might also be good to have a list of affected bindinds. My knowledge is limited :-) so please feel free to add bindings to this list:

- deCONZ [Backport thread](https://github.com/openhab/openhab-addons/issues/14124) /  [all open issues](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+deconz)

**Comment by florian-h05** [comment]
- KNX (no backport thread) / [all open issues](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+knx) / [smarthome/J version](https://github.com/smarthomej/addons/tree/3.2.x/bundles/org.smarthomej.binding.knx)

In general, you can have a look at the SmartHome/J Addons Repo: https://github.com/smarthomej/addons/tree/3.2.x/bundles, since there are more

**Comment by J-N-K** [comment]
Difference and benefits can be derived from the [Changelog](https://docs.smarthomej.org/Changelog.html). The motivation: ostly technical issues that can't be solved in openHAB at the moment. @kaikreuzer and me are working on resolving these.

**Comment by holgerfriedrich** [comment]
@J-N-K I could help porting back fixes into the KNX binding. I am not sure how to give credits, a joint signoff or just via the commit message as you recently did it for other backports?

**Comment by J-N-K** [comment]
@holgerfriedrich I'm currently only back porting changes in add-ons that do not require core-changes (i.e. those that do not depend on `org.smarthomej.commons`) because what is implemented there is the solution to the technical issues mentioned above. Once these functionality is implemented, I'm happy if you take over for KNX and a joint sign-off is fine.

**Comment by jlaur** [comment]
Short update - @J-N-K seems to be on fire at the moment. 😉
- **influxdb:** #14304 -> smarthomej/addons#459
- **dmx:** #14327 -> smarthomej/addons#455
- **snmp:** #14330 -> smarthomej/addons#456

And openhab/openhab-core#3330 has been reviewed by @kaikreuzer and just moments ago approved. I'm now crossing my fingers for a deconz backport. 🙂

**Comment by lsiepel** [comment]
Great! Allready chasing some issues that could be closed. 
For the ninfluxdb, i see some older issues and find it somewhat hard to determine if the issue is close4d or not. Offcourse i can ask all to check, but maybe @J-N-K  can have a brief look at https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+influxdb+in%3Atitle and comment on issues that might be fixed with th esnmp backport.

**Comment by lsiepel** [comment]
Update: **tr064** https://github.com/openhab/openhab-addons/pull/14468  fixing 2 issues from this repo and adding a ton of other fixes.

**Comment by lsiepel** [comment]
I think allmost all bindings have been backported now, so i close this issue.

**Comment by lsiepel** [comment]
@J-N-K there are some bindings left that are both in smarthomej and in openhab repo's. Are there any plan's to also move them here?

Like amazoneechocontrol. It has some issues here, but i see most fixes where done by you in smarthomejj repo:  https://github.com/smarthomej/addons/pulls?q=is%3Apr+amazonechocontrol+is%3Aclosed

**Comment by J-N-K** [comment]
I just added a backport for `http`. As far as I can see `amazonechocontrol` and `androiddebugbridge` are left. I can't do anything for the latter one, I don't use it and can't assess what needs to be done, because I believe some issues have been fixed/features added in both versions in different ways.

**Comment by lsiepel** [comment]
Close this now as most of the bindings (2 exceptions) are backported.
