### ISSUE TITLE
[shelly] TRV binding behaves unexpected when having connection issues

### ISSUE THREAD

**Issue by goligo** [openhab/openhab-addons#14127]
## Expected Behavior
When sending a command to update the target temperature on a TRV, but the communication with the device fails, so the change is not applied to the device, then the state also should not change in OpenHAB. 

## Current Behavior
Currently the item state is updated to the new value, even if the communication failed. So as a user you have the impression the target temperature has successfully been changed, but in fact it did not.

openhab.log shows the following entry
```
2022-12-29 15:08:46.746 [WARN ] [y.internal.handler.ShellyBaseHandler] - shellytrv-588e81a60915: FEHLER: Der Befehl 14 für Kanal shelly:shellytrv:588e81a60915:control#targetTemp kann nicht verarbeitet werden - API Timeout for GET http://192.168.1.67/thermostat/0?target_t_enabled=1&target_t=14
```

## Possible Solution
First of all, item state should not change/be updated if communication with the Shelly device failed. In general I guess network issues will occur in the real world, so such errors will happen. So the binding should handle them as gracefully as possible. So maybe, it can retry a few times, or store state changes which could not be executed, and send them again as soon the device is available again? 

## Steps to Reproduce (for Bugs)
1. Bind an item to the targetTemp channel of the Shelly TRV binding
2. Break the network connection, by kicking the TRV out of the WLAN or use physical shielding
3. Change the target temperature in BasicUI or MainUI

## Context
In case of network issues the item state does not match the actual device state.

## Your Environment
OpenHAB 3.4.0 on OpenHABian

**Comment by markus7017** [comment]
I understand your problem, but that's a general problem, not just the settemp
The OH framework writes the new value to the channel
which triggers the binding
passing this value to the device API
causing an exception

handling this situation requires to update the channel value if this was not reported by the device

If communication goes down / devices becomes unavailable the thing goes OFFLINE after a while
when communication is restored the binding reads the current status and updates the channels
you should have a rule, which monitors the device status, see getThingStatusInfo() and check for status != ONLINE
in this case the device is not present and the set temp will fail

**Comment by goligo** [comment]
If I understand your response correctly you are saying this is not specific to the Shelly binding, but a generic issue of the OH framework. 
I doubt this is the case, on the one hand have not experienced such issues with other bindings, on the other hand it would be a fatal architectural issue, if values which cannot be applied by the binding would stay in the UI. On the contrary, with other bindings I have experienced that a changed value is not accepted, and immediately jumps back to the old value, in case the device is offline or another issue occurs.

It may be theoretical possible to write a rule to check the case where a device really is offline, but it is not practical to do so for hundreds of bindings. It also would not catch temporary network issues reliably. 

Rather the binding should update the channel with the old value again, in case the new value could not be applied.

**Comment by markus7017** [comment]
This is not the framework. It sends a command to the channel the rest will be handled by the binding.
However, there is not a transactional API with the device, so the binding doesn't know where the request broke. Was the device offline before sending, was the command executed and then the connection broker. The binding has various recovery mechanism to re-initialize the connection (e.g. resend the command up to 3 times, reconnect on next poll), but can't queue requests until the device becomes available, e.g. a roller close is sent, connection breaks, devices comes back and now magically the roller closes even you didn't issued the command at this time.

I added another check before the channel command is executed and re-initialize if thing is offline. Try this.

However, is this happens again and again you should work on network stability, in fact this is the root cause.

**Comment by goligo** [comment]
> However, is this happens again and again you should work on network stability, in fact this is the root cause.

I think we should differentiate here - of course the issues I experience happen due to network problems. In packet based networking, such issues can and will occur. There will be Shelly devices in the real world, which do not have optimal connectivity. 

Also the issue I see is not that in such a case the change is not applied to the device. Obviously, if a device cannot be reached, cannot be communicated with, it can not be sent a commend. The issue is that the binding pretends that the change has been applied and on the OpenHAB UI the value appears changed. So the user doesn't get any feedback, that something went wrong, UI is showing the correct target temperature, but the room stays cold.

You  wrote "I added another check" - can you please link the commit or PR for this change?

**Comment by markus7017** [comment]
you have to use the DEV build to test this change, without confirmation I'll not add this to a PR

**Comment by goligo** [comment]
I give up. Obviously there is no interest in improving the situation or fixing bugs. I am using a custom build for several weeks now, which does address my issues. I wish everyone else good luck with the Shelly binding.

**Comment by markus7017** [comment]
> I give up. Obviously there is no interest in improving the situation or fixing bugs. I am using a custom build for several weeks now, which does address my issues. I wish everyone else good luck with the Shelly binding.

Interesting, I added a change to the binding, but have no interest to improve the handling?!
Do the test and provide the result, maybe that fixes your situation

**Comment by goligo** [comment]
Sorry, I am just a little frustrated. If it takes 4 weeks for every response, and the responses don't even answer my questions or bring any progress, I don't see this way the issues will ever be resolved. Maybe there are other people out there who have the patience to follow up and persue this, I don't.

Honestly, I don't understand how you changed code without committing a change, this is beyond my imagination. I will not spent my time digging through your changes trying to find the one you are referring to.

**Comment by markus7017** [comment]
The PR process takes weeks, therefore I'm providing a DEV build with the current changes
and keep in mind: People have to do this in their spare time.
You get faster response when reporting to the community thread: https://community.openhab.org/t/shelly-binding/56862/3159?u=markus7017
Go and install the DEV build and we could improve the situation. The only thing I have to say: It will never be 100% if the network connection is not almost stable.

**Comment by markus7017** [comment]
closed, no update
check latest DEV build https://community.openhab.org/t/shelly-binding/56862/3311
