### ISSUE TITLE
[dominoswiss] Binding is not working with version Openhab 3.4

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#14143]
The former dominoswiss binding for Openhab 2.x was working for about 2 years without any issue. Now I decided to upgrade Openhab to the latest stable version 3.4. Since version 3 of Openhab, there is an official binding available for dominoswiss. But unfortunately, I can't get it work. Even on a fresh installation of Openhab 3, I always get a "communication_error" when adding the dominoswiss bridge.

## Expected Behavior
- Adding the binding [dominoswiss]
- Manually add a new thing (Dominoswiss EGate Server)
- Provide IP address and port 1318
- Status of the thing should change to "online"

## Current Behavior
After adding a new thing via the "+" icon, the thing changes its status from "initializing" to "communication_error".

The log shows always the following error:
2023-01-03 10:46:19.598 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'dominoswiss:egate:0455761552' changed from OFFLINE (COMMUNICATION_ERROR): java.net.SocketException: Socket is closed to OFFLINE (COMMUNICATION_ERROR)

I double checked the settings on the eGate G1. All looks fine (IP address, Port 1318, etc.)

## Steps to Reproduce
The behaviour can also be reproduced with a fresh installation of Openhab 3.4 without any other binding installed.

## Your Environment
Openhab version 3.4 (stable) on a RasperryPi

The former binding of dominoswiss for Openhab 2 was working fine for 2 years.

**Comment by lolodomo** [comment]
@Friesoch : any idea?

**Comment by Friesoch** [comment]
@lolodomo seems to be this Bug https://github.com/openhab/openhab-addons/pull/14172 
@mjenny1 can you try it with this binding: https://github.com/Friesoch/org.openhab.binding.dominoswiss/blob/master/org.openhab.binding.dominoswiss-3.4.0-SNAPSHOT.jar

**Comment by mjenny1** [comment]
Yeah! Thanks a lot for your help! Now it works again as expected!

**Comment by lolodomo** [comment]
Fix not yet merged
