### ISSUE TITLE
[mqtt.homie] Channels not created even though MQTT topics are being subscribed -SOLVED-

### ISSUE THREAD

**Issue by mythjuha** [openhab/openhab-addons#14147]
## Current Behavior
My home automation system is using a industry type PLC (Beckhoff), with custom code to make it homie compliant. It used to work well with OH 3.1. After any later version (including the newest OH 3.4), creating a new homie thing through autodiscovery fails.

I keep getting the following error:

`Attempt to update thing 'mqtt:homie300:01eb25de8d:plc' with a thing containing invalid configuration 'Configuration[{key=deviceid; type=String; value=plc}, {key=removetopics; type=Boolean; value=false}, {key=basetopic; type=String; value=homie}]', blocked. This is most likely a bug.`

Setting the log level to DEBUG or even TRACE doesn't show me any reason why it's failing. I can see it correctly identifies all topics and subscribes to them.

Cleaning the cache after an upgrade or even clean installs of OpenHab give me the same error.

## Your Environment
* Version used: >= OH 3.2 (currently on 3.4)
* Operating System: Windows 10

Any assistance on resolving this issue would be highly appreciated. I already made a report of this on the OH community forums 6 months ago but had very little response. More info and screenshots can be found there: https://community.openhab.org/t/mqtt-homie-thing-containing-invalid-configuration/137356/1

**Comment by mythjuha** [comment]
Issue was found. My device was sending '$datatype ' with an added space at the end as topic.

**Comment by lolodomo** [comment]
Ok so issue can be closed
