### ISSUE TITLE
[shelly] Shelly actions very slow (delayed reception in openHAB)

### ISSUE THREAD

**Issue by Patschifig2021** [openhab/openhab-addons#14145]
**Expected Behavior**
House Electric switch equipped with shelly devices feeds/pushes status change to openHAB for instantaneously. This has worked perfectly fine from openHAB version 1.X to version 3.2.0. However with update to 3.3.0 and now to 3.4.1 causes serious troubles.

**Current Behavior**
I have been using my set-up with openHAB successfully for several years. Unfortunately after updating to openHAB / openhabian 3.3.0 and now 3.4.1 I encounter serious issues with my Shelly’s (Shelly Binding). I use different shelly’s e.g. 1, 1PM, 2.5 etc. to trigger actions in other bindings which used to work more or less in “real time” ever since. However after updating to openHAB 3.3.0 and now 3.4.1 this works with a huge time delay and the state of the Shelly’s is only changed in openHAB (according the log) when the Shelly is polled by the “heartbeat”, so with a delay of up to 60 seconds. When I restart the raspberry pi 4 it works again fine for a few minutes but then the behaviour is back as described above.

I de-installed ALL Bindings and than installed one by one including the shelly binding. But this did not help.

In the German openHAB Facebook group, other user have reported the same issue. They downgraded to Version 3.2.0 and it worked all fine again.

**Possible Solution**
1. fix the binding / process etc.
2. short time solution: restart/reboot Raspberry pi 4, it then works fine for LESS than 5 minutes
3. Downgrading back to Version 3.2.0
4. use of Home Assistant instead 

**Steps to Reproduce (for Bugs)**
https://community.openhab.org/t/shelly-actions-very-slow/138757
or
https://github.com/openhab/openhab-addons/issues/13395

**Context**
Switching the status of the Shelly triggers actions in other related systems (e.g. switches on Ikea Tradfri bulbs (via Tradfri Gateway) or Philips HUI.

**Your Environment**
openHAB 3.4.1 stable
Bindings: Astro, openweather, Tradfri, Shelly, Sonos, system binding
Operating System and version: openhabian 3.4.0 on Rasberry pi 4 (4GB)

**Comment by markus7017** [comment]
This is most likely related to issues with CoAP processing. Please make sure to select CoAP peer mode using Shelly Manager or device UI and try latest 3.4.3-SNAPSHOT from my myfiles repor
joine here: https://community.openhab.org/t/shelly-binding/56862/3128

**Comment by markus7017** [comment]
@Patschifig2021 any feedback?

**Comment by kojid0** [comment]
I had similar issues and activated CoAP. Since then I had no delays anymore. I'm on v 3.4.2 and haven't used your linked binding. Maybe my issue was another though, lets wait for feedback from the issue creator

**Comment by kojid0** [comment]
> I also have an issue with very slow Shelly Updates in Openhab. Where do you activate CoAP, I cannot find any option?

Look at the device settings in the official shelly app

**Comment by Patschifig2021** [comment]
Dear all, thank you very much indeed and after all that there is now attention on this issue. Much appreciated. I am also not familiar with CoAP and the direct installation of Bindings from Github. Consequently, I will have to dig into these things when I find some time. I will provide my feedback asap. Thanks once again

**Comment by markus7017** [comment]
Open Shelly Manager with http://deviceip/shelly/manager, Clock on the device actions for the selected device, enable CoIoT peer mode. This directs to send CoAP updates directly to the OH host. The Manager also shows a "Protocol messages" stats value, which should increase every time a CoAP packet is processed. If you still have issues enable DEBUG and check if Coop traffic shows up in the log. If not, I'm pretty sure you have a network issue, docket setup is misconfigured etc. CoAP supports works since a long time and is confirmed by dozens of users.

**Comment by markus7017** [comment]
no update
always check latest DEV build https://community.openhab.org/t/shelly-binding/56862/3311
