### ISSUE TITLE
[jsscripting] Install/Manage npm modules from MainUI

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#14148]
I've noticed that the jRuby add-on has the ability to define which `gems` to install from the add-ons config page. You provide a list of the names of the gems and the add-on somehow installs them.

I'm not sure how feasible this is but you never know unless you ask.

## Your Environment

* Version used: (e.g., openHAB and **JS Scripting add-on version**) OH 4.0 `#3265`
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian Docker image on an Ubuntu VM

**Comment by florian-h05** [comment]
I don‘t think this is possible, because npm is no part of NodeJS and no part of GraalJS (if I haven‘t overlooked it). See https://community.openhab.org/t/openhab-4-0-snapshot-discussion/142322/85?u=florian-h05 for more details.

**Comment by florian-h05** [comment]
I would also like to have such a option for the user, but I don‘t see a way how we achieve this.
I‘ll close this issue :-/
