### ISSUE TITLE
[hue emulation] Tests failing due to recent core change

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#14153]
The Hue Emulation Add-On tests (and therefore the CI and SNAPSHOT addons build) are failing due to recent core change https://github.com/openhab/openhab-core/pull/3298.

See:
- https://github.com/openhab/openhab-addons/actions/runs/3835730456/jobs/6529218620#step:9:2362
- https://ci.openhab.org/job/openHAB-Addons/948/org.openhab.addons.bundles$org.openhab.io.hueemulation/console

/cc @openhab/add-ons-maintainers

**Comment by jlaur** [comment]
@florian-h05 - thanks, hadn't noticed you created this issue when commenting yesterday: https://github.com/openhab/openhab-core/pull/3298#issuecomment-1371536110

**Comment by florian-h05** [comment]
@jlaur I have a PR to fix this, see #14161.
