### ISSUE TITLE
[influxdb] Duplicate datapoints returned

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#14152]
## Expected Behavior

When I request persistence data from the REST endpoint GET `/persistence/items/{itemname}`, I expect it to return persisted data.

## Current Behavior

It returns the persisted data, but with duplicate datapoint (except the first datapoint):

```json
{
  "name": "Florian_Licht",
  "datapoints": "21",
  "data": [
    {
      "time": 1672837223228,
      "state": "OFF"
    },
    {
      "time": 1672837223242,
      "state": "OFF"
    },
    {
      "time": 1672837223242,
      "state": "OFF"
    },
    {
      "time": 1672837288783,
      "state": "OFF"
    },
    {
      "time": 1672837288783,
      "state": "OFF"
    },
    {
      "time": 1672837360183,
      "state": "OFF"
    },
    {
      "time": 1672837360183,
      "state": "OFF"
    },
    {
      "time": 1672837427396,
      "state": "OFF"
    },
    {
      "time": 1672837427396,
      "state": "ON"
    },
    {
      "time": 1672837510439,
      "state": "ON"
    },
    {
      "time": 1672837510439,
      "state": "ON"
    },
    {
      "time": 1672837510444,
      "state": "ON"
    },
    {
      "time": 1672837510444,
      "state": "ON"
    },
    {
      "time": 1672837511135,
      "state": "ON"
    },
    {
      "time": 1672837511135,
      "state": "ON"
    },
    {
      "time": 1672837552563,
      "state": "ON"
    },
    {
      "time": 1672837552563,
      "state": "ON"
    },
    {
      "time": 1672837604329,
      "state": "ON"
    },
    {
      "time": 1672837604329,
      "state": "OFF"
    },
    {
      "time": 1672837648324,
      "state": "OFF"
    },
    {
      "time": 1672837648324,
      "state": "OFF"
    }
  ]
}
```

As you can see, several datapoints have exactly the same timestamp.

## Steps to Reproduce (for Bugs)
1. Persist for example a Switch Item in InfluxDB
2. Request persistence data for this example from the REST API (use the API Explorer: GET `/persistence/items/{itemname}`)

## Context

This already has been mentioned in issue #10121.
It does not lead to problems in usage (AFAIK), but we should probably check this.

## Your Environment

* Version used: (e.g., openHAB and add-on versions): openHAB 3.4.0 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian 11 Bullseye
 
/cc @lujop

**Comment by J-N-K** [comment]
Can you check if these entries are also duplicated in the database? You can use the `influx` CLI tool to login to influxdb, `USE` the database, then `SELECT * FROM Florian_Licht`.

**Comment by florian-h05** [comment]
I have recreated that series a few minutes ago and InfluxDB contains:

![IMG_1979](https://user-images.githubusercontent.com/73423173/216764302-6e6405c8-bddd-40a7-be26-08ebb7aebd63.jpeg)

However REST API delivers:

```json
{
  "name": "Florian_Licht",
  "datapoints": "13",
  "data": [
    {
      "time": 1675509302591,
      "state": "OFF"
    },
    {
      "time": 1675509342584,
      "state": "OFF"
    },
    {
      "time": 1675509342584,
      "state": "ON"
    },
    {
      "time": 1675509342596,
      "state": "ON"
    },
    {
      "time": 1675509342596,
      "state": "ON"
    },
    {
      "time": 1675509342599,
      "state": "ON"
    },
    {
      "time": 1675509342599,
      "state": "ON"
    },
    {
      "time": 1675509342600,
      "state": "ON"
    },
    {
      "time": 1675509342600,
      "state": "ON"
    },
    {
      "time": 1675509342602,
      "state": "ON"
    },
    {
      "time": 1675509342602,
      "state": "ON"
    },
    {
      "time": 1675509342614,
      "state": "ON"
    },
    {
      "time": 1675509342614,
      "state": "ON"
    }
  ]
}
```

These two requests were performed nearly the same time.

**Comment by J-N-K** [comment]
But that is intended behavior: https://github.com/openhab/openhab-core/blob/da81c6a6bed78af89cafe4ae275a2275af7f7db6/bundles/org.openhab.core.io.rest.core/src/main/java/org/openhab/core/io/rest/core/internal/persistence/PersistenceResource.java#L331-L338

**Comment by florian-h05** [comment]
Ah okay, thanks for that information, I wasn’t aware of that.

I‘ll close that issue since it’s no bug then.
