### ISSUE TITLE
[velux] Broken links in documentation

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#14157]
In the [Full Example](https://next.openhab.org/addons/bindings/velux/#full-example) there are links to these files:
- bundles/org.openhab.binding.velux/doc/conf/items/velux.items
- bundles/org.openhab.binding.velux/doc/conf/rules/velux.rules
- bundles/org.openhab.binding.velux/doc/conf/sitemaps/velux.sitemap
- bundles/org.openhab.binding.velux/doc/conf/things/velux.things

However, these links are broken:
https://next.openhab.org/addons/bindings/velux/doc/conf/things/velux.things

Furthermore, these four files contain license header information which is not automatically updated by the command `mvn license:format` - see #14154.

Could these example be embedded directly into the documentation like for all other bindings? This would also allow for syntax highlighting.

**Comment by andrewfg** [comment]
@jlaur /@Confectrician -- this is the same issue as was fixed in the recent "markdown improvements" PRs for other bindings done by @Confectrician in the last months. However I think you did not yet get as far as letter "v" in the list of bindings. ??

**Comment by andrewfg** [comment]
@Confectrician are you working on these last bindings? If so, I don't want to overlap with you. But if not, then I am happy to make a PR to resolve this Velux binding. => Please advise.

**Comment by Confectrician** [comment]
Sorry for being late to the party here. I am pretty busy currently.
I think i have branch open for the next edits, but i can rebase/merge when i go on with markdown improvements.

I would do it anyway when starting work after this long pause.
