### ISSUE TITLE
[Velbus] Add the relay / OP channel of the Edge Lit panels

### ISSUE THREAD

**Issue by MDAR** [openhab/openhab-addons#14179]
Hi

Can I ask that the Output channel of Edge Lit panels be added to the binding?

Or

Can someone point me in the direction of how to learn how to do it and add it into the binding?

I have various demo units that can be connected with remotely to explore the edge lit panels.

**Comment by Rosen01** [comment]
Hi MDAR,

Normaly the "Output" is already implemented.
It's not a relay, but only a representation of the differents status of the heating system :
heater, boost, pump, cooler, alarm1, alarm2, alarm3, alarm4

If you attempt to add an action in Velbulink, you will see that the channel (CH18) is not available, but rather the differents status.

**Comment by MDAR** [comment]
Hi Daniel


Thanks for that.

I don't mean the Channels of the thermostat, I mean the GPio output on the back of the edge lit panels, available via the tiny Molex connection.

It has all the basic functions of a Velbus relay and can be assigned a PWM rate.

If you look at an Edge Lit panel in Velbuslink, you'll see this feature at the very bottom of the list (below the thermostat functions).

**Comment by Rosen01** [comment]
I think I was a little bit too tired when I looked at the protocol.
I looked for a relay channel... It's referenced has an open collector output.
I will implement the "on/off" function on it.

**Comment by MDAR** [comment]
> It's referenced has an open collector output.

Sorry, you are 100% correct.
