### ISSUE TITLE
[deconz] Thermostat thing missing channel type: openclosesensor

### ISSUE THREAD

**Issue by phuongpham** [openhab/openhab-addons#14176]
I'm currently using Namron Panel Heater.
I have managed to get the thing created in openHAB.
But I'm missing the relay status.
This attribute is available in deConz and I can read it.
I assume this attribute is connect to channel type: open and item type: Contact
When I check the "documentation:
https://www.openhab.org/addons/bindings/deconz/
It seems like this channel is only available thru thing type: openclosesensor

Please add this channel also to the thing type Thermostate

**Comment by J-N-K** [comment]
Please provide the full REST API response of that device.

**Comment by phuongpham** [comment]
API URL: http://192.168.1.13/api/TOKEN/sensors/82

The relay is part of the State and i changed between "on": false  and "on": true

    "state": {
        "on": false
    },


Full REST API Response:
```

{
    "config": {
        "heatsetpoint": 2200,
        "locked": false,
        "mode": "off",
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "etagXXXXXXXXXXXXXX",
    "lastannounced": "2023-03-10T06:11:09Z",
    "lastseen": "2023-03-18T18:10Z",
    "manufacturername": "NAMRON AS",
    "modelid": "5401395",
    "name": "ZB_E1_PanelOvn",
    "state": {
        "lastupdated": "2023-03-18T18:10:39.296",
        "on": false,
        "temperature": 2039
    },
    "swversion": "6.9.1.0_r4",
    "type": "ZHAThermostat",
    "uniqueid": "IDXXXXXXXXX"
}
```

**Comment by J-N-K** [comment]
Thanks. I'll have a look.

**Comment by phuongpham** [comment]
Great! Let me know when I can test the snapshot
