### ISSUE TITLE
[telegram] Invalid escape of underscore character when sending messages

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#14204]
It seems that https://github.com/openhab/openhab-addons/pull/13758 was resolved incomplete.
When `parseMode` of Telegram Bot Thing is configured to `None`, underscore characters are now sent as `\_` instead of `_`.

## Expected Behavior
When `parseMode` is configured to `None`, `sendTelegram("_")` transmits `"_"` via Telegram

## Current Behavior
When `parseMode` is configured to `None`, `sendTelegram("_")` transmits `"\_"` via Telegram

## Possible Solution
The obvious fix would be to skip the changes from https://github.com/openhab/openhab-addons/pull/13758 in case  `parseMode` is configured to `None`.

But there is more fishy with https://github.com/openhab/openhab-addons/pull/13758: Replacing `_` by `\_` will break any markdown formatting when using italic. There is already a comment on this in the PR https://github.com/openhab/openhab-addons/pull/13758#issuecomment-1345151729.
I guess https://github.com/openhab/openhab-addons/pull/13758 needs to be fully reverted.
Instead the user documentation must be extended, stating that unwanted markdown characters need to be escaped by the user, when using `parseMode` `Markdown`.
E.g. `result.replace("_", "\\_").replace("*", "\\*").replace("[", "\\[").replace("`", "\\`")`
Similar approach will be required when using `HTML` `parseMode`.

## Steps to Reproduce (for Bugs)
1. `parseMode` of Telegram Bot thing is configured to `None`
2. telegramAction.sendTelegram("_")
3. "\_" is transmitted via Telegram

## Context
-

## Your Environment
- OH 3.4.0

**Comment by lsiepel** [comment]
Can confirm this issue. 
@clinique are you aware of theses issues?

**Comment by Daniel-at-git** [comment]
After I reverted https://github.com/openhab/openhab-addons/commit/1d23c32de1e3831644494751c961d17d10628ec8 (in branch 3.4.x) it's working again.

@clinique: Please revert this commit or fix it in a way that it didn't affect other parts.
