### ISSUE TITLE
[openwebnet] Documentation of auto-calibration and shutterRun

### ISSUE THREAD

**Issue by TheNinth7** [openhab/openhab-addons#14216]
The [description of the shutter position and shutterRun parameter](https://www.openhab.org/addons/bindings/openwebnet/#shutter-position) also covers the auto calibration. However, it fails to mention that the auto calibration cannot measure actual runtime, but only measures the time between a command (up/down) being issued and the auto-stop sent by the actuator.

For older actuators that support only physical configuration or virtual configuration via My Home Suite the auto-stop is fixed to 60 seconds, newer actuators that support advanced configuration via the My Home Suite can be configured to other values.

The auto calibration sets the shutterRun to a value slightly higher than that, probably due to processing delays. E.g. if the auto-stop is set to 60 seconds, the shutterRun is set to about 61 seconds.

I am not sure if this should be considered an issue with the implementation (does the auto calibration make sense like that), especially since this seems to lead to [another issue](https://github.com/openhab/openhab-addons/issues/14215).

But at least it would be useful to clearly document how the auto calibration works and the implications of it reacting to auto-stop not actual shutter runtime.

**Comment by lsiepel** [comment]
Yvan you make a PR with your documentation suggestions? Always good to improve documentation 😁

**Comment by TheNinth7** [comment]
> Yvan you make a PR with your documentation suggestions? Always good to improve documentation 😁

Not sure if I understand right, are you asking me to make a suggestion? What is a PR? :-)

**Comment by lsiepel** [comment]
Yes, made a typo, sorry.  PR is a pull request, a way to contribute to the code/documentation. If you don’t know anything about it, I’m willing to do it for you but either way, it would need you to suggest the exact changes, so I can copy/paste it in.

**Comment by TheNinth7** [comment]
I'd be happy to contribute some texts and also learn how to do a PR.

However, for this particular topic, I'd need some input from the developer, because I am not 100% sure how the auto-calibration really works.

@mvalla: from the discussion thread I understand that the auto-calibration listens to the auto-stop message from the actuator? Is that correct? Is there any other mechanism that the auto-calibration uses, or is it always that auto-stop message?

**Comment by lsiepel** [comment]
Let me know if you need any help with the PR, i hope the codewoner/binding developers can help you out with the content.

**Comment by mvalla** [comment]
as documented in the README, auto calibration is performed by doing "a UP >> DOWN >> Position% cycle will be performed automatically the first time a Percent command is sent to the shutter" and it' based solely on the timing calculated beween the DOWN command the the (auto-)stop sent on the BUS from the actuator. 
So if auto-stop is misconfigured, also calibration gets mis-configured.
So if you want you can submit a concise  addition to the README to suggest to check auto-stop setting to be correctly set as close as possible to the actua shutter runtime.

**Comment by TheNinth7** [comment]
OK, created the PR now, hope I did everything correctly:

https://github.com/openhab/openhab-addons/pull/14266
