### ISSUE TITLE
[homekit] Remove redundant configs

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-addons#14211]
While starting to play with the homekit integration I found some mandory configs, which do not make sense in my opinion.
For Example : 
Thermostat : It is mandatory to set Thermostat.currentHeatingMode and Thermostat.targetHeatingMode
While having used many different Thermostats in the past, I did not see one distinguishing between those modes.

For simplification, I would suggest to add an binding internal mapping, so homekit sees both, but the user only has to configure one item.

This applies to other mode options for different accessories as well.

**Comment by ccutrer** [comment]
It's relatively easy to link a single item to multiple characteristics if you really feel that they should be. But there _is_ a very important difference. In the case of thermostat, the current mode is "what is the thing currently doing", and target mode is "how have I set it up". For example, you can have HEAT mode set as the target, but if it's a bright sunny day, heat might not be needed at the moment, so the current mode of the thermostat is OFF. Another example is a thermostat might have AUTO mode, where you configure it to stay between a lower and upper bound. The current mode is not allowed to be AUTO - it's either currently heating, currently cooling, or doing nothing.

Thermostat is a pretty extreme case where there is a huge variety of implementations, and I would venture a guess that fewer than 50% _cannot_ report back what their current state is (in my house, two out of 12 thermostats can't report at least "running" vs. "idle"). And those 2 thermostats have an AUTO mode, and thus cannot directly link the same item to both CurrentHeatingCoolingMode and TargetHeatingCoolingMode. I would posit that for Thermostat, we're not actually helping anyone by attempting to hide the differences between the two.

For other accessories, though, it is quite common that HomeKit exposes "current" and "target" state, while openHAB devices rarely show the difference. Shades, locks, and garage doors are my most common devices that fit this. But these are devices that also are rarely complex, and thus you just link the item with the accessory name itself, and the add-on will link all the required characteristics to that same item to do so.

For example, here is one of my shades: `Rollershutter GreatDrapes_Rollershutter "Great Room Drapes [%d%%]" <if:mdi:window-shutter-open> (eGreatDrapes, gEastShades, gInflux, gMapDB) [ "OpenLevel" ] { alexa="Curtain", homekit="WindowCovering" [instance=3], retention="P1M" }`. No need to mess with individual characteristics, or worry about the difference between current and target.

For GarageDoorOpener, I've already written a commit to ease linking it directly to a Rollershutter: https://github.com/openhab/openhab-addons/commit/a6834208a27ae518dda57a95d8bf70380d3af087. I'll open a PR as soon as its dependent commit is merged.

If there are any other accessory types that you feel would benefit from intelligent simplification like GarageDoorOpener, I'd be happy to look in to them.
