### ISSUE TITLE
Searching this repo yields no code results

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-addons#14220]
This happens when searching this repo, as well as my fork of this repo. It happens whether or not I'm logged in to GitHub. I see issues and PRs that match. Just no hits on code.

I don't see it happening on any other repos (openHAB-related or otherwise).

And, it appears I'm not the only one.
https://github.com/openhab/openhab-addons/pull/14199#issuecomment-1382718184

Curious if anyone else is seeing this.

**Comment by lsiepel** [comment]
Searching on readme finds many results on the different search types, but nothing on code. 

https://github.com/search?q=repo%3Aopenhab%2Fopenhab-addons+readme+extension%3Ajava&type=Code&ref=advsearch&l=&l=

When i use the same query to some other repository's it returns result, so that suggest there is some repo or organisation level isseu preventing a search on the code.

**Comment by wborn** [comment]
I think it is some kind of GitHub bug. The same happens when searching your own openhab repo forks.

Creating a discussion about it here may help with getting some GitHub support:

https://github.com/orgs/community/discussions/categories/code-search-and-navigation

**Comment by wborn** [comment]
The search does work fine for me on some other big repos like:

* https://github.com/chromium/chromium
* https://github.com/torvalds/linux

**Comment by wborn** [comment]
I created a [new repo](https://github.com/wborn/openhab-addons-search) (not a fork) with the same content and it first showed "The requested content has not yet been indexed, please try again in a few moments."... after that it can be [searched](https://github.com/wborn/openhab-addons-search/search?q=openhab) properly. So I think it some kind of indexing problem.

Apparently GitHub does not index forks as it will show "Sorry, forked repositories are not currently searchable." when searching your fork for code.

**Comment by mhilbush** [comment]
Hmm. Yes, I think you're right. It does seem like there's a problem with the index.

https://github.com/orgs/community/discussions/44388

**Comment by mhilbush** [comment]
This morning I was added to the beta for GitHub's new Code Search and Code View.

I now get the expected results when I search the repo. So, this would be another indicator that there's something wrong with the index used by the old search.

**Comment by mhilbush** [comment]
@wborn Worth a try?

https://github.com/orgs/community/discussions/44388#discussioncomment-4732726

**Comment by wborn** [comment]
If toggling the repo visibility fixes it maybe @kaikreuzer can do that as I see:

`Organization members can’t change repo visibility.`

It would also be nice to first test if such an operation does not mess something up like breaking the link between forks and the repo they are forked from.

**Comment by lsiepel** [comment]
Have not tested it, but don't think it is a good idea:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility

public => private: GitHub will detach public forks of the public repository and put them into a new network.

**Comment by wborn** [comment]
Looks like it will indeed mess something up.

If GitHub cannot fix it might get automatically fixed when the new code search goes from beta to general availabilty for everyone.
Meanwhile I also signed up for the beta and got admitted within 1 day and see results again.

You can sign up here as workaround :slightly_smiling_face: : https://github.com/features/code-search-code-view/signup

**Comment by mhilbush** [comment]
> You can sign up here as workaround

Yeah I signed up a few days ago. It works fine. Well, in fact, it works better than the old search. 😉

**Comment by mhilbush** [comment]
I'll just close this issue. If anyone has problems searching and finds this issue, they'll see that signing up for the new code search is the solution.
