### ISSUE TITLE
[renault] Support for MyDacia accounts and Dacia Spring car

### ISSUE THREAD

**Issue by raulmatei** [openhab/openhab-addons#14227]
## Your Environment
* Version used:  openHAB 3.4.0 / Renault Binding 3.4.0
* Chrome 109.0.5414.74
* openjdk version "11.0.16" 2022-07-19
  OpenJDK Runtime Environment (build 11.0.16+8-post-Debian-1deb11u1)
  OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Debian-1deb11u1, mixed mode)
* NodeJS v16.19.0
* Operating System: Debian GNU/Linux 11 (bullseye)
   Kernel: Linux 5.15.76-v8+
   Architecture: arm64

I'm trying to get the Renault Binding to work with MyDacia account and I'm not able to because the account type is hard coded to MYRENAULT account type here: https://github.com/openhab/openhab-addons/blob/0f272d85234901d463ae3f447037492a2ab032fb/bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java#L194. 

Authentication using https://github.com/hacf-fr/renault-api works as expected and I'm able to query the Renault APIs to get the car details, battery-status, location, cockpit, hvac-status. The lock-status is not working, there are some limitations for Dacia Spring cars discussed here: https://github.com/hacf-fr/renault-api/pull/534. I haven't tried the actions yet but I'm willing to do that soon.

I'm not a Java programmer, but I can help with testing if someone gets an update that allows MYDACIA accounts to get registered.

Regards,
Raul.

**Comment by dougculnane** [comment]
@raulmatei There was a recent PR https://github.com/openhab/openhab-addons/pull/14527 that might be of interest to you. It adds the charge pause channel with might work on your car.  You should be able to test this with the latest openhab 4.0-snapshot.

I can add a line to get the accountType=="MyDacia" if the accountType=="MYRENAULT" does not find anything.  I have no way to test this so you would need to test it for me.  What is the exact value I need to look for "MyDacia", "myDacia", "MYDACIA"...

**Comment by rouallet** [comment]
Dear Dougculname,

I just changed it to "MYDADIA", build and test it: working perfectly fine:
![image](https://github.com/openhab/openhab-addons/assets/2677316/98bbdffb-122f-4c41-8cab-dc90924b01c1)

My test setup: openhab 3.4.4, on a rpi4.
A Dacia Spring.

Regards,

Robin

**Comment by dougculnane** [comment]
@rouallet Thanks to the test.

This will be quite easy to add in a 2nd loop if no MyRenault account is found.  I will prepare a PR for including in openHAB 4 as soon as I can.

**Comment by dougculnane** [comment]
PR to close this issues here: https://github.com/openhab/openhab-addons/pull/15101

**Comment by dougculnane** [comment]
PR Merged (https://github.com/openhab/openhab-addons/pull/15101) and so we can close this issue.  Support for MyDacia accounts will be in OpenHAB 4
