### ISSUE TITLE
[netatmo] Web hook events aren't supporting different devices

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#14237]
The home thing has a trigger channel which is triggered by web hook events ("welcomeHomeEvent"). I would like to react on such an event and sent a live picture / snapshot of the camera via mail or telegram message. But I have 2 cameras (one doorbell and one outdoor camera). How can the rule know which live picture is required?

I solved that by extending the old binding (< OpenHAB 3.3) with new trigger channels on camera device thing level (not home thing level). I think it would be a good solution for the current binding.

More problems regarding the web hook events:
- The documentation of the current binding is outdated. I don't see a "cameraEvent" trigger channel and the "welcomeHomeEvent" trigger channel is displayed as "security#home-event" within in MainUI.
- I can't get the "security#home-event" to work. For testing I'm also sending events via the tool "Postman" and getting a response with status code 200, but my rule isn't triggered. What is a correct channel id for this trigger channel? An example within the documentation for such a rule would be useful.
- The trigger channel options "HUMAN", "ANIMAL", "VEHICLE" and "MOVEMENT" aren't existing (anymore). It would be useful when the "welcomeHomeEvent" channel or the new camera thing trigger channels are supporting these types/options. Maybe that is also my problem of point 2.
- There are no trigger channel options for the new doorbell events like incoming call. This is required for a useful integration of the doorbell device.

**Comment by Novanic** [comment]
Hello @clinique , is it possible that the trigger channel "home-event" is not working? I can't find any code which triggers the channel and web hook events are only implemented in DoorbellCapability, not in PresenceCapability (outdoor camera).

I will now try to fix that but I'm wondering if I have the current source code ;-)

**Comment by clinique** [comment]
Hello @Novanic , nice to see you back here.
I must admit that most of the webhook logic is present but has not been heavily tested. I did setup the needed peaces some weeks ago (reverse proxy) to start dive deeper in this portion of the binding, but have been diverted with the arrival of OH4 and its impacts on some other ongoing PR I have. Last evolution is available [here](https://github.com/openhab/openhab-addons/compare/main...clinique:openhab-addons:netatmo_webhook_v4).

**Comment by Novanic** [comment]
Hello @clinique , I have now got it to work and fixed all the mentioned issues and could provide a PR soon. I would like to update the channels of the doorbell and presence with the data from the web hook events. Can you tell me what is the difference between last event and sub event? Doorbell has both, Presence has only last event. Should both get updated by a web hook event or only sub event?

**Comment by clinique** [comment]
IIRW sub-events are provided by pull API

**Comment by Novanic** [comment]
> IIRW sub-events are provided by pull API

Yes, it seems that last-event is only updated via refresh/polling and sub-event is updated via web hook events. I have now added the sub-event channels also for the presence camera and tested successfully. The pull-request is here: https://github.com/openhab/openhab-addons/pull/14252

**Comment by lsiepel** [comment]
Fixed by: https://github.com/openhab/openhab-addons/pull/14252
