### ISSUE TITLE
[tplinksmarthome] KL135 missing On/Off channel and brightness

### ISSUE THREAD

**Issue by kamakazie2** [openhab/openhab-addons#14239]
I have added 2 KL135 Color bulbs.
The plugin detected both bulbs. I can control the color and see power consumption.

KL135 Kasa Smart Wi-Fi Bulb Multicolor
**_Power On/Off_**
Fine-tune colors
Adjust light appearance from soft white (2500k) to daylight (6500k)
**_Adjust the brightness_**
Actual power usage
Wi-Fi signal strength (RSSI)

I am missing Power On/Off and Brightness channels.

running Oh 3.3 
plugin version: 3.3

**Comment by Hilbrand** [comment]
They are not missing, but are available via the color channel. Define an item as switch on the color channel and you have toe on/off. Use a dimmer item and you can control the brightness. This is standard behavior.

**Comment by kamakazie2** [comment]
thank you for the clarification
