### ISSUE TITLE
[Netatmo] Weekly (Monthly) Min-Temperature not less then 0°C ?

### ISSUE THREAD

**Issue by LukaNoah** [openhab/openhab-addons#14256]
I'm running OH 3.4.1 with the new netatmo-binding on a nuc with ubuntu 22.04 and java 11.

I have a problem with the generated minimum values for the outside temperature. The Min will not be less than 0°C. The daily min comes from the corresponding channel. Weeks and Months-Min are generated via the new ability to add channels.
Configured as a minimum temperature channel with a week or month period.
You can clearly see in the diagram that it was colder than 0 °C last night.

Thanks
Heiko
![image](https://user-images.githubusercontent.com/16850444/213876595-3b61f6dd-3339-44e2-a239-0963f9d1f663.png)

**Comment by lolodomo** [comment]
This is also wrong currently for my feeling temperatures which should be -2 but is 0.

**Comment by lolodomo** [comment]
Maybe INSIDE_TEMPERATURE is wrongly used? 
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/NetatmoConstants.java#L81

**Comment by lolodomo** [comment]
I hope the problem is not #13015...

**Comment by lolodomo** [comment]
The feeling temperature is probably the heat index channel (I have to check). In this case, it is computed by the binding using the temperature and the humidity. We may simply use different formula than Netatmo.

**Comment by LukaNoah** [comment]
The feels-like-outside-temperature is then green graph in my chart ;)
Also booth outside-temperatures are "broken".

**Comment by clinique** [comment]
> I hope the problem is not #13015...

Could be. I'll have a look at it, it was my first thought also.

**Comment by lolodomo** [comment]
> The feeling temperature is probably the heat index channel (I have to check => Edit: confirmed). In this case, it is computed by the binding using the temperature and the humidity. We may simply use different formula than Netatmo.

Just to conclude on that subject: the binding computes the heat index while Netatmo computes the feeling temperature which also considers the wind speed. So yes, this is two different data and that is normal they are not identical.

**Comment by clinique** [comment]
> I hope the problem is not #13015...

You are correct. Problem lays here in `MeasureCapability.java`: 
```
                            MeasureClass.AS_SET.stream().filter(mc -> mc.apiDescriptor.equals(descriptor)).findFirst()
                                    .ifPresent(mc -> {
                                        State state = result instanceof ZonedDateTime
                                                ? toDateTimeType((ZonedDateTime) result)
                                                : result instanceof Double ? toQuantityType((Double) result, mc)
                                                        : UnDefType.UNDEF;
                                        measures.put(channel.getUID().getIdWithoutGroup(), state);
                                    });
```
The first match goes to `INSIDE_TEMPERATURE`, resulting in the trunction to 0°C of the API returned value.

**Comment by clinique** [comment]
@lolodomo : I've got a quick and ... working solution that would preserve current code structure, in line with my comment in #13015 : OUTSIDE_TEMP being the second MeasureClass added in the Map, it's the only one kept. So I could, instead of taking the first result, take the last. If done that way, I'll comment code accordingly for future reference. WDYT ?
