### ISSUE TITLE
[telegram] Underline in message text gets escaped ("hello_world" -> "hello\_world")

### ISSUE THREAD

**Issue by Daniel-at-git** [openhab/openhab-addons#14255]
## Expected Behavior
If you are going to send "hello_world" in a rule
~~~java
telegramAction.sendTelegram("hello_world")
~~~
you should get "hello_world" in telegram

## Current Behavior
Since upgrade from 3.3.0 to 3.4.1 I get all underlines escaped by "\\". So I get in above example "hello\\_world"

## Steps to Reproduce (for Bugs)

1. Create a rule that sends a Telegram message which includes text with a "_"
2. Check the message in Telegram
3. Message gets an additional "\\" in front of the "_"

## Context
I send Telegram messages from rules that includes triggeringItemName like here
~~~java
telegramAction.sendTelegram(triggeringItemName + " " + triggeringItem.state)
~~~
and some of my items have underlines in the name (e.g. "Window_Bathroom").

## Your Environment
Running under Debian 11 (bullseye)
~~~
openhab> bundle:list org.openhab.binding.telegram
START LEVEL 100 , List Threshold: 50
 ID │ State  │ Lvl │ Version │ Name
────┼────────┼─────┼─────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
278 │ Active │  80 │ 3.4.1   │ openHAB Add-ons :: Bundles :: Telegram Binding
~~~

**Comment by Daniel-at-git** [comment]
Is it related to https://github.com/openhab/openhab-addons/pull/13758/commits/088669b44de687b54bbc288f2975fa621c6abb99?

**Comment by lolodomo** [comment]
Yes, it is, you're right.
