### ISSUE TITLE
[evcc] - Some state attributes are not recognized

### ISSUE THREAD

**Issue by prior-philip** [openhab/openhab-addons#14276]
## Problem Statement
evcc binding receives status attributes thru REST API. Some received attributes are not recognized correctly:
Thats is what the binding gets from evcc (copied from openhab-console tracelog of the binding)
eg: You'll find vehicleSoc, minSoc, phasesConfigured, phasesActive received with values but related channels are not getting updated.

`19:36:33.206 [TRACE] [hab.binding.evcc.internal.api.EvccAPI] - GET http://localhost:7071/api/state - {"result":{"auth":{"vehicles":null},"battery":[{"power":0,"soc":19,"capacity":0}],"batteryCapacity":0,"batteryConfigured":true,"batteryPower":0,"batterySoc":19,"bufferSoc":0,"currency":"EUR","gridConfigured":true,"gridCurrents":[7.08,7.46,5.69],"gridEnergy":7463.094,"gridPower":4330,"gridPowers":[1480,1580,1260],"homePower":690,"loadpoints":[{"chargeCurrent":6,"chargeCurrents":[5.4,5.4,5.2],"chargeDuration":4645000000000,"chargePower":3670,"chargeRemainingDuration":4185000000000,"chargeRemainingEnergy":4266.666666666666,"chargeTotalImport":245.753,"chargedEnergy":4704.69,"charging":true,"connected":true,"connectedDuration":0,"enabled":true,"maxCurrent":16,"minCurrent":6,"minSoc":20,"mode":"minpv","phaseAction":"inactive","phaseRemaining":0,"phasesActive":3,"phasesConfigured":3,"phasesEnabled":0,"planActive":false,"pvAction":"inactive","pvRemaining":0,"targetEnergy":0,"targetSoc":35,"targetTimeActive":false,"title":"Garage","vehicleCapacity":64,"vehicleDetectionActive":false,"vehicleFeatureOffline":false,"vehicleIcon":"car","vehicleOdometer":4076.3,"vehiclePresent":true,"vehicleRange":108,"vehicleSoc":29,"vehicleTargetSoc":90,"vehicleTitle":"Hyundai Kona Electric"}],"prioritySoc":0,"pv":[{"power":0}],"pvConfigured":true,"pvPower":0,"residualPower":0,"savingsAmount":0,"savingsEffectivePrice":0.2589999999999997,"savingsGridCharged":4.702751651377047,"savingsSelfConsumptionCharged":0,"savingsSelfConsumptionPercent":0,"savingsSince":1674649294,"savingsTotalCharged":4.702751651377047,"siteTitle":"Blammer79","sponsor":"prior-philip","tariffFeedIn":0.08,"tariffGrid":0.259,"vehicles":["Hyundai Kona Electric"],"version":"0.111.1"}}
`
 
 

**Channel Vehicle SoC is 0 while returned GET value "vehicleSoc":29**
![image](https://user-images.githubusercontent.com/68287405/214654189-4c10d551-f71a-4683-a0db-1ebc31fb5dad.png)
 
 
 
 
**Other channels gets populated with value as expected.**
eg vehicleRange
![image](https://user-images.githubusercontent.com/68287405/214654497-165b6eb4-89e3-4629-b701-3c8ecb8da568.png)
 
 
 

## Possible Solution
refer to evcc documentation and adjust GET parameters accordingly
https://docs.evcc.io/docs/reference/api/#rest-api

## Context
This started to happen with evcc 0.111.1
Relevant information of car or loadpoint dont get displayed or is empty. So far its affecting following parameter
- Vehicle Soc
- Charging target Soc
- Charging enabled phases
- Charging min Soc
- Charging active phases
- Battery Power
- Battery Soc
- Battery Priority Soc

## Your Environment

* Version used: (3.4.0M4)
* Operating System and version (Ubuntu 22.40 Pi4B):

**Comment by prior-philip** [comment]
Seems to be related to https://github.com/evcc-io/evcc/discussions/5522

**Comment by florian-h05** [comment]
Already fixed with https://github.com/openhab/openhab-addons/pull/14245. 

You can get the fixed version from the community marketplace (I don’t recommend to use the SNAPSHOT version in production), you need to enable displaying of unpublished addons. 

See https://community.openhab.org/t/evcc-binding-electric-vehicle-charging-control-beta/135209.
