### ISSUE TITLE
[dsmr] New channel types for peak demands (capacity tariff Belgium)

### ISSUE THREAD

**Issue by sceppi** [openhab/openhab-addons#14279]
In Belgium a new "capacity tariff" is in place since 1/1/2023. In this new tariff, the distribution tariff is based on the 15-min average peak load of power of each month. Recently, the DSMR meters have been upgraded and new objects are now available to read these peak load valuesfrom the P1 port. The dsmr binding therefore needs to be upgraded to include these object as new channel types.

Three new objects are available:

- Current average demand - Active energy import (1-0:1.4.0.255)
- Maximum demand – Active energy import of the running month (1-0:1.6.0*255)
- Maximum demand – Active energy import of the last 13 months  (0-0:98.1.0*255 )

See also following document for a more detailed technical description and examples (text in yellow): [https://maakjemeterslim.be/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cdd9b48fd0838e89b177f03b745b23450fd8f53e/e-MUCS_P1_Ed_1_7_1.pdf?disposition=attachment](url)

**Comment by coop-git** [comment]
I could compile a binding for the Maximum demand of the current month. However, I had to delete the tests. 
It failed on the telegram testing for the new channel, so it seems. How can this be solved?

**Comment by Hilbrand** [comment]
@coop-git Did it fail on all testcases or only the adapted electricity meter? Without seeing the code it's difficult to see what is wrong. Did you adapt the test data to add new channels? Might be the new channels are added as required channels, while should be in the optional part?

**Comment by coop-git** [comment]
@Hilbrand I managed to uncomment the test for the Belgium meter. I added the channels to the first part. I was already wondering why there were 2 objects.
Let me try that again, merge the code so you can have a look.

**Comment by coop-git** [comment]
> @coop-git Did it fail on all testcases or only the adapted electricity meter? Without seeing the code it's difficult to see what is wrong. Did you adapt the test data to add new channels? Might be the new channels are added as required channels, while should be in the optional part?

Wauw, that was the missing hint I needed.
You can have a look at [https://github.com/coop-git/openhab-addons/tree/3.4.x/bundles/org.openhab.binding.dsmr](https://github.com/coop-git/openhab-addons/tree/3.4.x/bundles/org.openhab.binding.dsmr)
If you agree, I will then do an official pull request

**Comment by sceppi** [comment]
@coop-git For me the binding is working perfectly as intended. Thanks very much.
For me you can launch the official pull request.

**Comment by coop-git** [comment]
@sceppi OK, thanks. For me it is also working fine. Now I don't have to wait for Fluvius to update their portal.
I will need to do Pull Request on OH 4.0 and need to update my environment for that. Always tricky for me.
So it will be done, just not sure when :)

**Comment by coop-git** [comment]
Please see [this PR](https://github.com/openhab/openhab-addons/pull/15038)
This will be closed.
