### ISSUE TITLE
[avmfritz] Fritz DECT 500 lightbulb - not possible to change from color to white mode

### ISSUE THREAD

**Issue by outerSpaceToast** [openhab/openhab-addons#14287]
It seems that with the current version of openHAB 3.5 changing color is working now, BUT obviously it is not possible to change back to white mode, after once having set a color option.
Did I miss something?

## Expected Behavior
There is an option to chose white mode (or even better to chose the color temperature) on a Fritz DECT 500 light bulb (created as `HAN_FUN_COLOR_BULB`).
There should be a separate channel for the brightness.

## Current Behavior
As soon as you select a certain color value, the bulb switches to color mode, no more change to white mode possible via openHAB.
Brightness can only be changed, when another manual Dimmer item is linked to the color chaannel.

## Possible Solution
I've tested this changeset from @sommer and @vich-667, which implements a temperature color channel. It is working fine:
https://github.com/vich-667/openhab-addons/pull/1/files
Discussion here: #12427 
What is missing to bring this change into the main development branch?
Can I support somehow?

## Steps to Reproduce (for Bugs)
1. Add bulb as `avmfritz:HAN_FUN_COLOR_BULB`
2. Connect `Color` item to its `color` channel
3. Select a color

## Your Environment
openHAB 3.4.0

Best regards,
Thomas.

**Comment by vich-667** [comment]
Hi @outerSpaceToast!

Thanks four interest on that light blub. I saw that you already mentioned that problem in the old issue! I'm also not happy with the behavior of that Light Blub Thing, but when I had some of my very limited time to play with openhab I had was busy with other things. Yesterday I re setup the dev enviroment, so I hope I can give that old PR a more detailed look and finalize it.

I remember there still was some problem with swiching the light blub totally off. Did it work to you?

I hope my very limited java knowlage is enought to get it working.

KR Vich

**Comment by outerSpaceToast** [comment]
> Yesterday I re setup the dev enviroment, so I hope I can give that old PR a more detailed look and finalize it.

That would be geat :-)

> I remember there still was some problem with swiching the light blub totally off. Did it work to you?

The behaviour is not intuitive, but it works, when you create separate items for the switch, the brightness and the color, which are linked to the color channel.
I think it would be more intuitive, if there were separate channels for that. However, if you know how to do it, then it works well as it is.

> I hope my very limited java knowlage is enought to get it working.

Same situation here, only working with plain C at work.
However, I could merge your changes into the current 3.4-branch locally.

**Comment by vich-667** [comment]
I check that issue with ON/OFF:
- Fritz box has an seperate channel for *on/off* and *brightness*. You can see the brightness value in fritz box GUI
- In OpenHAB you can attach a conrol for on/off, Percantage or HSB to the color channel. all depend on the brightness value
This ended up in you swith off in FritzBox gui but in open hab it's still on. I asume I found a way that it works much more intuitive.

I finally added also the update of color temperature is reflected to OpenHAB GUI.

Here is my PR to fix this issue: https://github.com/openhab/openhab-addons/pull/14373

Thanks to @sommer for providing the base code of this PR. Without it my knowlage is currently not enought to do this changes.

**Comment by outerSpaceToast** [comment]
Thank you very much for your time and good work!
I am looking forward to the next release including this update.

One question: I saw that the brightness is coupled to the On/Off-switch. If you set brightness to 50%, then switch off, then switch on again: Does it remember the brightness with your changes?

**Comment by vich-667** [comment]
- If you switch on/off via a button, it remembers the brightness. Because OH only sends on off commands to fritz box and takes care of the value.
- If you set brightness to zero it's the same behavior, becuse in this case i send now just off to the fritz box and do not change the brightness itself.
- If it's off OH always show a brightness of 0 because it dosn't know the fritz box value. If you just place the brightness to 50% it sends a on + 50% command to fritz box that it's finally on.
- If you move the brightness slider from 0% to 50% in an HSB element to switch on and white mode was set before, the mode will be canged, because a new color value is send as well.

**Comment by outerSpaceToast** [comment]
That sounds like a good solution.
Thanks for the explanation!

**Comment by vich-667** [comment]
I created a branch to make it OH3.4.x compatible, what I use currently in my "produktive" setup: https://github.com/vich-667/openhab-addons/tree/task/3.4.x/colortemp

**Comment by vich-667** [comment]
It I learned that the PR for 3.4.x version is not welcome. If someone is interrested either see the branch or here you can find the jar file: [org.openhab.binding.avmfritz-3.4.3-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/10787104/org.openhab.binding.avmfritz-3.4.3-SNAPSHOT.zip)

**Comment by vich-667** [comment]
Rebuild on base of latest 3.4.x release:
[org.openhab.binding.avmfritz-3.4.5-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/11470793/org.openhab.binding.avmfritz-3.4.5-SNAPSHOT.zip)
