### ISSUE TITLE
[openwebnet] Energy: implement partial totalizer for current day and month

### ISSUE THREAD

**Issue by aconte80** [openhab/openhab-addons#14285]
BTicino energy meters (such as the F520) have the capability of counting the total kWh over a day and over a month.
It is useful to read this data with specific channels to create graphs of consumed energy.

**Comment by fabgio** [comment]
Hi @aconte80 How are you doing? are you going to handle this?
So long!

**Comment by fabgio** [comment]
@mvalla I think I can handle this!

**Comment by mvalla** [comment]
@fabgio if you can add this day/month measurements and are also able to test the new feature on a real system, you are welcome to submit a PR proposal.
I strongly suggest you first describe here how you would define the new channels, so we can discuss the design.

**Comment by fabgio** [comment]
I would define the channels as follows: 

JAVA DEFINITIONS:

public static final String CHANNEL_POWER_DAY = "powerDay";
public static final String CHANNEL_POWER_MONTH = "powerMonth";

XML CHANNELS' DEFINITION:

	<channel-type id="powerMonth">
		<item-type>Number:Power</item-type>
		<label>Power per month</label>
		<description>Monthly partly totalized power</description>
		<category>Energy</category>
		<state readOnly="true" pattern="%.0f %unit%"></state>
	</channel-type>

     <channel-type id="powerDay">
		<item-type>Number:Power</item-type>
		<label>Power per day </label>
		<description>Daily partly totalized power</description>
		<category>Energy</category>
		<state readOnly="true" pattern="%.0f %unit%"></state>
	</channel-type>

XML THING/CHANNELS DEFINITION:

          <channels>
			<channel id="power" typeId="power"/>
			<channel id="powerDay" typeId="powerDay"/>
			<channel id="powerMonth" typeId="powerMonth"/>
	     </channels>

**Comment by mvalla** [comment]
I think these measurements are related to Energy and not Power.
Which OWN request/event will you connect them to? Where is it described in the official specification documents ?

Also, it came up in my mind that @aconte80 had already a working solution for this issue: he sent me some messages with screenshot already in Jan 2023.
Maybe you want first to check the solution from @aconte80 and test it ?

**Comment by fabgio** [comment]
> I think these measurements are related to Energy and not Power.`

You are right, this kind of measure is related to Energy

>Which OWN request/event will you connect them to? 

OpenWebNet message request to get current day partial totalizer:


<code>*#18\*WHERE\*54##</code>

OpenWebNet message request to get current month partial totalizer:

<code>*#18\*WHERE\*53##</code>

openwebnet4j 0.10 version has already implemented proper methods to tackle such kinds of OWN requests:

<code>

 /**
     * OpenWebNet message request to get current month partial totalizer <code>*#18*WHERE*53##</code>.
     *
     * @param where WHERE string
     * @return message
     */
    public static EnergyManagement requestCurrentMonthTotalizer(String where) {
        return new EnergyManagement(
                format(FORMAT_DIMENSION_REQUEST, WHO, where, DimEnergyMgmt.PARTIAL_TOTALIZER_CURRENT_MONTH.value()));
    }
    /**
     * OpenWebNet message request to get current day partial totalizer <code>*#18*WHERE*54##</code>.
     *
     * @param where WHERE string
     * @return message
     */
    public static EnergyManagement requestCurrentDayTotalizer(String where) {
        return new EnergyManagement(
                format(FORMAT_DIMENSION_REQUEST, WHO, where, DimEnergyMgmt.PARTIAL_TOTALIZER_CURRENT_DAY.value()));
    }
</code>

> Where is it described in the official specification documents ?

at page 5 of the Bticino WHO=18 official docs

> Maybe you want first to check the solution from @aconte80 and test it ?

I will

**Comment by fabgio** [comment]
@mvalla I been testing @aconte80 solution for two days now. Got good feedback. I just made some minor  udjustments in  commits to reflect updates then it works fine

**Comment by mvalla** [comment]
@fabgio I contacted @aconte80: I suggest you fork his orginal branch, create a new branch to include additional changes (if needed) by you and prepare a new PR.
This way his initial work is preserved with his commits and you can contribute by further improving and finalizing the PR.

This the branch you should fork and work on:
https://github.com/aconte80/openhab-addons/tree/dev-energy-history
