### ISSUE TITLE
[openwebnet] Alarm: zone alarm not reset after system is re-armed

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#14305]
For `bus_alarm_zone` things, the channel  `alarm` should be reset when the system is re-armed

## Expected Behavior
Channel alarm for an active zone should be reset to NULL when system is re-armed

## Steps to Reproduce (for Bugs)
1. system is armed, Zone 2 active
2. intrusion detected in Zone 2: channel alarm=INTRUSION
3. system disarmed
4. system re-armed
5. Zone 2 channel alarm is still = INTRUSION

**Comment by fabgio** [comment]
I think I can handle this issue

**Comment by mvalla** [comment]
Good @fabgio! I have been collecting  some logs to understand when to reset the alarm channel. If you have a solution describe it here or submit some code to review

**Comment by fabgio** [comment]
I committed some changes, as you suggested i focused on resetting the alarm channel (i.e. CHANNEL_ALARM_ZONE_ALARM_STATE) via  a modified refreshDevice method (refreshing alarm zone also) and calling it in updateAlarmSystemArmed method. I will test it tomorrow morning. As I already made some tests which caused my siren starting, maybe someone  could support me  also making a some tests!

**Comment by mvalla** [comment]
Looking [at the code on your branch](https://github.com/openhab/openhab-addons/compare/main...fabgio:openhab-addons:14305_openwebnet_4.0.0_alarm):
- updateAlarmSystemArmed is called when alarm is both armed/disarmed
- then refreshDevice(false) is self-called on the alarm_system Thing handler, so the lines added at L113-116 are never executed
- in any case requestChannelState() gest called, but this does not guarantee that the channel is updated correctly and alarm state is reset for all zones

Where you able to debug/test your changes ?

**Comment by fabgio** [comment]
I got what you pointed out...
> Where you able to debug/test your changes ?
unfornately I can't figure out why the remote debugging on my test docker container does not hit any break point with Intellij, I remember it worked last year. I have been trying for days... the port 5005 is open though...

**Comment by fabgio** [comment]
I have been struggling.  Add-ons 4.0 are targeting jdk 17, which would  require core 4.0 to run at  the same jdk level.  Still, it turned out  to be obviously unstable so far. So I was wondering if there is any side effect in downgrading the addons target level to 11 (and how to
do it) to use oh3 to make tests,debugging etc...etc

**Comment by mvalla** [comment]
I suggest you search and ask on the forum, for example here:
https://community.openhab.org/t/how-to-build-updates-for-oh-3-4/143097
