### ISSUE TITLE
[netatmo] Add support for Carbone Monoxid detector

### ISSUE THREAD

**Issue by riesermauf** [openhab/openhab-addons#14302]
Please include Carbone Monoxid detector

## Your Environment
Raspberry PI 4 4GB
Openhab Distribution
Openhab V3.4.1
* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by clinique** [comment]
I have just ordered one of these.
Will soon be able to act on this.
