### ISSUE TITLE
[gpstracker] Altitude missing

### ISSUE THREAD

**Issue by VanDeStouwe** [openhab/openhab-addons#14317]
## Expected Behavior
The altitude info is missing 

## Current Behavior
The location channel does not include the altitude information. Allthough it is send by OwnTrack

## Possible Solution
Adding the altitude to: LocationMessage

**Comment by lsiepel** [comment]
Was looking to add this channel and foudn the detials on the owntracks api docus. Unfortunately i could not find any documentation for gpslogger.app so not sure if this channel shoudl be added if only one provider supports it.

Just to verify: you expect the altitude to be a seperate channel, next to location?

**Comment by lsiepel** [comment]
I have created the PR with the channel, could you test this? A jar file is supplied in the PR. Thanks.

**Comment by VanDeStouwe** [comment]
Wil test on friday on the road rigjt now

Verstuurd vanaf mijn iPhone

Op 15 feb. 2023 om 10:36 heeft lsiepel ***@***.***> het volgende geschreven:

﻿

I have created the PR with the channel, could you test this? A jar file is supplied in the PR. Thanks.

**Comment by VanDeStouwe** [comment]
Can I please have sum guidance where to find the jar file? I do not seem to be able to find  it.

**Comment by VanDeStouwe** [comment]
I added the jar file to the add-ons directory.
bulble:list shows the new binding as:
`344 │ Installed │  80 │ 4.0.0.202302150918     │ openHAB Add-ons :: Bundles :: GPSTracker Binding`
when I started this I recieved the following:
`Error executing command: Error executing command on bundles:
        Error starting bundle 344: Could not resolve module: org.openhab.binding.gpstracker [344]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.9.0,3.0.0)"`

**Comment by lsiepel** [comment]
ah, dependency nightmare with  these drop in jar's. If you install ecobee (just install it from the ui) the com.google.gson should be satisfied. Hopefully that is all.

**Comment by VanDeStouwe** [comment]
Still no you:
`348 │ Installed │  80 │ 4.0.0.202302150918     │ openHAB Add-ons :: Bundles :: GPSTracker Binding
openhab> bundle:start 348
Error executing command: Error executing command on bundles:
        Error starting bundle 348: Could not resolve module: org.openhab.binding.gpstracker [348]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.9.0,3.0.0)"`

**Comment by VanDeStouwe** [comment]
Please keep in mind that gpstracker binding runned as an add-on worked without needing de gson package

**Comment by VanDeStouwe** [comment]
So I checked and Gson is allready installed and active by default but version 2.8.9
You have a dependicy from google.gson [2.9.0,3.0.0]

**Comment by lsiepel** [comment]
Created a 3.4.x jar here: https://1drv.ms/u/s!AnMcxmvEeupwjqVz2X6-OsiWofyLLw?e=vcvSgn
Hope this will give some test results.

**Comment by VanDeStouwe** [comment]
I have checked your changes. In one thing is missing. You need to add gettin gthe altitude from the location message like:
`        
142      return "LocationMessage [" + ("type=" + type + ", ") + ("trackerId=" + trackerId + ", ")
143               + ("latitude=" + latitude + ", ") + ("longitude=" + longitude + ", ") + **_("altitude=" + altitude + ", ")_**
144               + (gpsAccuracy != null ? "gpsAccuracy=" + gpsAccuracy + ", " : "")
145               + ("batteryLevel=" + batteryLevel + ", ") + ("timestampMillis=" + timestampMillis) + "]";
`
This is need because the location channel sows 0m all the time. While in my case it should have been 3m

**Comment by lsiepel** [comment]
Just installed and tested it. All working as expected, i'm also on +3m :-) Thanks for the code suggestions. I did forget to add the altitude to that method, while it is only used for some logging.

**Comment by VanDeStouwe** [comment]
Do you want me to confirm? If yes please send the jar. Must i go to openhab snapshot to pickup the updated gpstracker binding?

**Comment by lsiepel** [comment]
> Do you want me to confirm? If yes please send the jar. Must i go to openhab snapshot to pickup the updated gpstracker binding?

You can use the same link. Confirm you use this version from from the console bundle:list 3.4.3.20220227 something

**Comment by VanDeStouwe** [comment]
I have tested version: 3.4.3.202302272057  GPSTracker Binding
I herewith confirm that the adding of the altitude has been succesfull.
