### ISSUE TITLE
[MQTT] transformationPattern SCRIPT(graaljs:filename.script) not working under OH4/Java17

### ISSUE THREAD

**Issue by kjoglum** [openhab/openhab-addons#14334]
Following [DOCS](https://github.com/openhab/openhab-js#script-transformation), `SCRIPT(graaljs:filename.script)` should supposedly work under OH4/Java17. For comparison, I get the readTransform and writeTransform for Modbus to work using `SCRIPT(graaljs:filename.script)`, however, when using the same input directly for MQTT transformationPattern from main UI, the following log is reported:

`[WARN ] [t.generic.ChannelStateTransformation] - Transformation service SCRIPT(GRAALJS for pattern compressorPercentage.script) not found!`

I have JS Scripting add-on installed (as mentioned, Modbus Script transformation works as expected).

And just for reference, as I get the same warning for all scripts used for MQTT (none for Modbus), the `compressorPercentage.script` file referred to in the log warning above contains:

`(function(inputData) {
    var array = inputData.split(";")
    return parseFloat(array[0]);
})(input);`

**Comment by J-N-K** [comment]
Did you take into account the different syntax for MQTT (and HTTP and some others): https://www.openhab.org/addons/bindings/mqtt.generic/#incoming-value-transformation

**Comment by kjoglum** [comment]
To be honest, I have just chased how to go directly from `transformationPattern: JS:compressorPercentage.js` working under OH 3.4 to a working transformation without JavaScript Transformation, thus ending up with  `transformationPattern: SCRIPT(graaljs:compressorPercentage.script)` based on docs, which reports the log warning `Transformation service SCRIPT(GRAALJS for pattern compressorPercentage.script) not found!`.

The  complete code for the channels btw is:
`- id: compressorPercentage
    channelTypeUID: mqtt:number
    label: Vaillant Compressor Percentage
    description: Compressor Percentage
    configuration:
      formatBeforePublish: "%s"
      stateTopic: ebusd/hmu/State
      transformationPattern: SCRIPT(graaljs:compressorPercentage.script)`

Where the incoming value for the channel would be (example):
`85;339;on;heating`

The transformation script itself (referred to above) is set up to fetch/return value `85`, and thus linked item becomes updated to `85%`, which has historically been working using JS Transformation under OH 3.4. 

Please guide me if I am chasing the wrong route.

**Comment by J-N-K** [comment]
`transformationPattern: SCRIPT:graaljs:compressorPercentage.script`

should work

**Comment by kjoglum** [comment]
Sure thing: changing from `transformationPattern: SCRIPT(graaljs:compressorPercentage.script)` to `transformationPattern: SCRIPT:graaljs:compressorPercentage.script` did the trick. 

Thanks!
