### ISSUE TITLE
[evcc] 0.112.x: targetXXX channels not working because of upstream API changes

### ISSUE THREAD

**Issue by prior-philip** [openhab/openhab-addons#14348]
## Expected Behavior
targetSOC written with value

## Current Behavior
targetSOC is not written. Log indicates API is not set correctly
`Handling command 90 % (class org.openhab.core.library.types.QuantityType) for channel evcc:device:evcc_test_jar:loadpoint0#targetSoC
POST http://localhost:7071/api/loadpoints/1/targetsoc/90 - 404 page not found`

## Possible Solution
follow evcc API Doc [https://docs.evcc.io/docs/reference/api/](url)
correct API path to `POST /api/loadpoints/<id>/target/soc/<soc>`
eg:
```
curl -X POST http://localhost:7071/api/loadpoints/1/target/soc/65
{"result":65}
```

## Your Environment
Version used: 3.4.1
Environment name and version: RaspberryPi 4B
Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu Server 22.04

**Comment by florian-h05** [comment]
Which evcc version are you on? 0.112.x right?

FYI: You could have added this to your existing issue #14293 because this is clearly a bug.

**Comment by florian-h05** [comment]
I guess the other target channels don‘t work anymore as well because evcc changed all target APIs.

**Comment by prior-philip** [comment]
> Which evcc version are you on? 0.112.x right?
> 
> FYI: You could have added this to your existing issue #14293 because this is clearly a bug.

Yes, its 0.112 (forgot to mention)
Didnt update #14293 since it belongs to different evcc version and I didnt regression test with 0.111.1.
