### ISSUE TITLE
[shelly] Add support for Shelly Pro 3EM

### ISSUE THREAD

**Issue by DM6JM** [openhab/openhab-addons#14346]
Support for the new Shelly Pro 3EM would be great.
I couldn't find a repo for the shelly binding where there would be some code I could work on and trigger a PR miself, so all I can do right now is open this issue and hope for someone to pinpoint me to where the dev is being done.

Since the two pages (http://<device ip>/settings and http://<device ip>/status) don't exist in Pro devices, I don't know where to start.

**Comment by markus7017** [comment]
try current 3.4.3/4.0.0-SNAPSHOT from myfiles repo; in general done, but final testing/fixing is missing
join here

**Comment by markus7017** [comment]
Did you tried the DEV build, will become part of PR #14532

**Comment by DM6JM** [comment]
@markus7017 Thanks for the work. For me as an OH newby it took some while to get this running, but all I could test (Pro 3EM) worked like expected.
