### ISSUE TITLE
[KEBA] Binding doesnot initialize using Keba P30

### ISSUE THREAD

**Issue by wolfijenne** [openhab/openhab-addons#14353]
Using Openhab on Raspberry PI 4. Installed Keba Binding.
Keba Firmware: 3.10.16
However, Keba Binding does not initialize:

openhab/things/keba:kecontact:fdcca03587/statuschanged
ThingStatusInfoChangedEvent
[{"status":"ONLINE","statusDetail":"NONE","description":""},{"status":"INITIALIZING","statusDetail":"NONE"}]

openhab/things/keba:kecontact:fdcca03587/status
ThingStatusInfoEvent
{"status":"UNINITIALIZED","statusDetail":"HANDLER_INITIALIZING_ERROR","description":"Cache expire time must be greater than 0"}

openhab/things/keba:kecontact:fdcca03587/statuschanged
ThingStatusInfoChangedEvent
[{"status":"UNINITIALIZED","statusDetail":"HANDLER_INITIALIZING_ERROR","description":"Cache expire time must be greater than 0"},{"status":"ONLINE","statusDetail":"NONE","description":""}]

Other bindings (usually with Modbus TCP) work fine. The wallbox interface in question does actually work using a self developed interface.

**Comment by maihacke** [comment]
It might be a problem with your thing configuration. Did you set an refresh interval > 0?

**Comment by wolfijenne** [comment]
Thx for the answer, its set to 2 seconds. I also tried 5 seconds.

**Comment by maihacke** [comment]
Does it work with 6?

**Comment by wolfijenne** [comment]
Yes, it actually works with 6. Well... thats quite slow for something that should be controlled instantly. That was actually the reason why I switched to openhab from a self programmed solution. Anyway, I consider it as closed. Maybe that would be an enhancement request to have it update faster.
