### ISSUE TITLE
[shelly] CoIoT Temperature readings of 999 should be excluded 

### ISSUE THREAD

**Issue by rossbuggins** [openhab/openhab-addons#14360]
## Expected Behavior
Readings of 999 shoudln't be recorded into openhab:

> Temperature (in C) measured by an external sensor (e.g. Shelly 1 with DS1820/DHT22 add-on) or ambient temperature (e.g. Shelly H&T). This is a separate property since some devices also measure internal device temperature and it should be distinguished between the two. 999 if no valid temperature reading is available at the moment.

https://shelly-api-docs.shelly.cloud/gen1/docs/coiot/v1/CoIoT%20for%20Shelly%20devices%20(rev%201.0)%20.pdf

## Current Behavior
999 degrees are stored for shelly sensors using CoIoT

## Possible Solution
Check value isn't 999
https://github.com/rossbuggins/openhab-addons/pull/1/files
Is it possible to record N/A / Null / undef at this point instead? 

## Steps to Reproduce (for Bugs)
Shelly sensor, using CoIoT, with temperature (I'm seeing this on a Shelly 1)

## Context
Skews all data / graphs.

## Your Environment
3.4.1

**Comment by markus7017** [comment]
Is this problem reproducible? Do you have a log?
post here: https://community.openhab.org/t/shelly-binding/56862/3117?u=markus7017

**Comment by markus7017** [comment]
I'm working on changes checking all temp channel updates for 999

**Comment by markus7017** [comment]
This should be fixed, check latest DEV build, will become part of PR #14532
