### ISSUE TITLE
[Systeminfo] Version 3.4.1 produces warnings for channel "sensors#fanSpeed" on system with no fan

### ISSUE THREAD

**Issue by pgfeller** [openhab/openhab-addons#14370]
## Expected Behavior
I'm running openHAB 3.4.1 on a Intel NUC with Ubuntu 22.04.1 LTS. This system is not equipped with a cpu fan. 

## Current Behavior
I had an item linked to the fan channel, as I was not aware that the device does not have one. Once I realized this, I deleted the item & channel link - but still get warnings in the log file:

```log
2023-02-09 12:02:17.769 [WARN ] [o.internal.handler.SysteminfoHandler] - No information for channel sensors#fanSpeed with device index: 0
```
![image](https://user-images.githubusercontent.com/9395643/217796383-8c0a61b9-a3cb-4a1e-a9d0-a09a29f9514a.png)

## Context
This is a minor problem - as I can filter the logs to exclude this line. However - it might make sense to address this if that code area is touched.

## Your Environment
openHAB 3.4.1 (Build) on Ubuntu 22.04.1 LTS (x64)

```
OS: Ubuntu 22.04.1 LTS x86_64 
Host: NUC8i3BEH K31299-305 
Kernel: 5.15.0-60-generic 
Shell: bash 5.1.16 
CPU: Intel i3-8109U (4) @ 3.600GHz 
GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] 
Memory: 2014MiB / 3791MiB 
```

```
-Sensors-
../../thermal_zone0/temp1	Temperature	-263.20°C	
../../thermal_zone0/temp2	Temperature	27.80°C	
../../thermal_zone2/temp1	Temperature	37.00°C	
coretemp/temp1	Temperature	45.00°C	
coretemp/temp2	Temperature	35.00°C	
coretemp/temp3	Temperature	45.00°C	
thermal/thermal_zone2	Temperature	37.00°C	
thermal/thermal_zone0	Temperature	-263.20°C	
thermal/thermal_zone1	Temperature	27.80°C	
thermal/thermal_zone4	Temperature	45.00°C	
```
![image](https://user-images.githubusercontent.com/9395643/217797869-a6121b9a-9aef-48af-b09c-d91edeaeafac.png)

Please let me know if you need more specific info about the system.

**Comment by lsiepel** [comment]
Did the warning go away after a binding restart?

**Comment by pgfeller** [comment]
Hi @lsiepel,

no - I did an upgrade to OH 3.4.2, which included a server restart and the warning is present after that restart. Let me know if more information about the HW is required. I'm not a linux specialist - so I would need some instructions on how to collect them (did my best in the initial post).

with kind regards,
Patrik

**Comment by lsiepel** [comment]
Are you sure the channel is no longer linked ? as this log entry is only shown when the channel is linked. That together with the reboot, i suspect there is stilll a link.

**Comment by pgfeller** [comment]
According to the UI it should not be linked anymore - but maybe there's something off that I can not see in the GUI:

![image](https://user-images.githubusercontent.com/9395643/218994207-e1a40834-09a1-4750-8b83-e8f7d0086633.png)

... but your hint is a good one - I read a little about how to check the consistency of the links and there indeed is an orphan link present:

```bash
links orphan list | grep fan
Item missing: openHAB_Server_Information_Luftergeschwindigkeit -> systeminfo:computer:openHAB:sensors#fanSpeed Configuration[]
```

I can imagine that this is the problem ... I'll clean the orphans out of the system and restart it => I'll let you know if this resolved the issue.

**Comment by pgfeller** [comment]
Removing the orphan links from the configuration solved the problem - not a bug after all; but a configuration/user error. I'll close the issue. Hope this is ok for you and thank you for the help!
