### ISSUE TITLE
[shelly]3EM AccumulatedTotal and Returned do not update

### ISSUE THREAD

**Issue by MacroScooter** [openhab/openhab-addons#14412]
Hi, is it possile that after the update 3.4.2 the channels 

device#accumulatedWTotal (Number:Power)square_on_square
device#accumulatedReturned (Number:Power)square_on_square

aren`t updated any more although everything is online (thing and channel)

thx Macro

**Comment by markus7017** [comment]
try the 3.4.3-SNAPSHOT, if this doesn't help report here and then we could iterate
https://community.openhab.org/t/shelly-binding/56862/3123

**Comment by markus7017** [comment]
I tried and seems to work (only phase B was connected)

<img width="590" alt="Bildschirmfoto 2023-02-26 um 19 00 24" src="https://user-images.githubusercontent.com/12601656/221427940-6c9a3c29-89d9-4eaa-a9cf-598e364b1573.png">

**Comment by markus7017** [comment]
@MacroScooter Check #14539 there is a fix regards the meter#current channel, but I don't think that this fixes your issue. Nevertheless try updating to the DEV build.

**Comment by markus7017** [comment]
no update
