### ISSUE TITLE
[tapocontrol] Did not get option to add L930 RGBW Lightstripe, even it is in the Docs

### ISSUE THREAD

**Issue by MerlinChiodo** [openhab/openhab-addons#14428]
I want to add my new 930 Lightstripe, but I cant add it beacause there is no option for the 930.
<img width="652" alt="image" src="https://user-images.githubusercontent.com/60719496/219822659-5f111757-b767-4404-9218-a594be780fb3.png">

Docs says it is compatible:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/60719496/219822765-b24686ba-3615-402d-a08e-3090ac2fef15.png">

## Your Environment
Rasb 3b+
Oh Version 3... I could check exact version if needed.

**Comment by MerlinChiodo** [comment]
Tried to add it over the L920 one. Didnt work either. 
![Screenshot_20230224_110536](https://user-images.githubusercontent.com/60719496/221151356-5b288267-ef56-4734-a7a6-28e1d25f802c.jpg)

**Comment by wildcs** [comment]
@MerlinChiodo 
can you confirm that this is fixed? i can see it in my binding (4.1-Snapshot)
![image](https://github.com/openhab/openhab-addons/assets/40909464/d0062c4b-bf08-4c9e-bcb6-4caa15a87e8b)

**Comment by lsiepel** [comment]
L920 support was [added in 3.3.0](https://github.com/openhab/openhab-addons/pull/11967), so i guess you used an older openHAB version. Please re-open if you still have this issue with openHAB 4.2.x
