### ISSUE TITLE
[Netatmo] Floodlight not working on Presence Camera (with siren)

### ISSUE THREAD

**Issue by multimartin** [openhab/openhab-addons#14458]
I am on OH3.4 and have an issue with the Netatmo binding related to the floodlight function on my Netatmo Presence Outdoor camera (with siren).

The floodlight on/off/auto simply does not work according to docs: [Netatmo - Bindings | openHAB](https://www.openhab.org/addons/bindings/netatmo/)

My floodlight works fine using either Homekit, the Netatmo app and through the Netatmo api (https://dev.netatmo.com/) - but not through OH. Everything else through OH seem to work fine (camera/snapshots etc).

The docs describe the channel as a switch - but with three states (on, off or auto). Perhaps that is the issue ?

(EDIT: the enhancement request regarding the siren function has been cut out of the text above and put into a seperate issue)

**Comment by clinique** [comment]
Could you split your issue in two ? One is an enhancement, the other a potential bug. Thanks

**Comment by clinique** [comment]
> The floodlight on/off/auto simply does not work according to docs: [Netatmo - Bindings | openHAB](https://www.openhab.org/addons/bindings/netatmo/)
> 
Does the binding report correctly the current status of the flood light if activated/deactivated by movement or Netatmo App ? (my Presence does not work anymore so I'm unable to test this currently).

**Comment by clinique** [comment]
Ok, thanks. I'm going to try to address this issue that may not have been heavily tested or used since the global binding revamp. I'll probably need your help - get ready to switch the binding in trace mode -, because as said my Presence is out of order.

**Comment by multimartin** [comment]
I am ready ;-)

**Comment by clinique** [comment]
Ok. Would you be able to catch the API answer when a request to update camera values is sent ?
Something that would look like this : 
''''{status:"ok"time_exec:"0.060059070587158"time_server:"1553777827"body:{home:{id:"59xxxxxxxxxxxxxx23"modules:[{id:"70:xx:xx:xx:c3"type:"NACamera"firmware_revision:5011001firmware_name:"5.11.1"wifi_state:"string"wifi_strength:57monitoring:"string"sd_status:4alim_status:2vpn_url:"https://prodvpn-eu-5.netatmo.net/10.255.228.11/72xxxxxxxxxxxxxxxxx6f6940/MTYXXXXXXXXDMDoe_XXXXXXXXXbKIYYg,,"is_local:true}{id:"70:xx:xx:xx:c3"type:"NOC"firmware_revision:272wifi_state:"string"wifi_strength:57monitoring:"string"floodlight:"string"sd_status:4alim_status:2siren_status:"no_sound"vpn_url:"https://prodvpn-eu-5.netatmo.net/10.255.228.11/72xxxxxxxxxxxxxxxxx6f6940/MTYXXXXXXXXDMDoe_XXXXXXXXXbKIYYg,,"is_local:true}{id:"70:xx:xx:xx:c3"type:"NIS"status:"no_news"firmware_revision:106monitoring:"string"battery_level:6190battery_state:"string"rf_strength:49rf_state:"string"last_seen:1567515767reachable:truebridge:"70:xx:xx:xx:c3"}{id:"70:xx:xx:xx:xx"firmware_revision:106last_seen:1567515767type:"NSD"}{id:"70:xx:xx:xx:xx"firmware_revision:106last_seen:1567515767type:"CO"}{id:"70:xx:xx:xx:c3"type:"NDB"firmware_revision:5011001firmware_name:"5.11.1"wifi_state:"string"wifi_strength:57sd_status:4alim_status:2vpn_url:"https://prodvpn-eu-5.netatmo.net/10.255.228.11/72xxxxxxxxxxxxxxxxx6f6940/MTYXXXXXXXXDMDoe_XXXXXXXXXbKIYYg,,"is_local:true}{id:"70:xx:xx:xx:c3"type:"NACamDoorTag"status:"no_news"battery_level:6190battery_state:"string"rf_strength:49rf_state:"string"firmware_revision:106last_seen:1567515767last_activity:1567515767bridge:"70:xx:xx:xx:c3"}{id:"70:xx:xx:xx:c3"type:"BNEU"firmware_revision:1reachable:truebridge:"00:03:xx:xx:xx:c3"}{id:"70:xx:xx:xx:c3"type:"BNDL"firmware_revision:1reachable:truebridge:"00:03:xx:xx:xx:c3"}{id:"70:xx:xx:xx:c3"type:"BNSL"firmware_revision:1reachable:truebridge:"00:03:xx:xx:xx:c3"}{id:"70:xx:xx:xx:c3"type:"BNCX"firmware_revision:1wifi_strength:57reachable:true}]persons:[{id:"540xx-b1xa-4xxxf-8xxx0-40b05xxxx607"last_seen:"156xxxxxxxxx7"out_of_sight:true}]}errors:[{id:"00:04:74:00:01:00"code:6}]}}''''

**Comment by multimartin** [comment]
2023-02-22 09:53:32.565 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri GET  https://api.netatmo.com/api/homestatus?home_id=607XXXXXXXXXXXXXXXXXXX 
2023-02-22 09:53:33.136 [TRACE] [mo.internal.handler.ApiBridgeHandler] - executeUri returned : code [200 OK] body {"status":"ok","time_server":1677056013,"body":{"home":{"id":"607XXXXXXXXXXXXXXXXXXX","modules":[{"id":"70:XX:XX:XX:XX:XX","type":"NSD","firmware_revision":1150,"last_seen":1675145355,"wifi_strength":61},{"id":"70:eX:XX:XX:XX:XX","type":"NOC","firmware_revision":3010000,"wifi_state":"high","wifi_strength":64,"sd_status":4,"alim_status":2,"siren_status":"no_sound","vpn_url":"https://prodvpn-eu-12.netatmo.net/restricted/10.xx.xx.xx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,,","is_local":true,"floodlight":"off","monitoring":"on"}]},"errors":[{"code":6,"id":"70:XX:XX:XX:XX:XX"}]}}

**Comment by clinique** [comment]
I think there is an error in the documentation. The channel is clearly a String, accepting ON/OFF/AUTO ( so could be linked to a Switch item also probably).
Maybe the API used to activate this function has changed. Will take a look (in the current version the binding emulates the access like if it was the Netatmo App - this function was not documented back in the past IIRW).

**Comment by multimartin** [comment]
The .jar file you sent me a link to in the seperate issue related to the siren on this camera, seem to work regarding the floodlight issue; I can now turn on / off the floodlight - and it seems to sync with changes done in the Netatmo app.
So far so good - however the .jar file only works for OH 4, / Java 17 - so I will wait until I migrate/upgrade my production setup until I can benefit from this...
I guess you can consider the issue closed ?

**Comment by lolodomo** [comment]
I merged the PR.
