### ISSUE TITLE
[shelly] Add support for Shelly Plus Plug S

### ISSUE THREAD

**Issue by jlaba** [openhab/openhab-addons#14519]
Support of the Shelly Plus Plug S would be very nice.

It is mentioned under https://community.openhab.org/t/shelly-binding/56862/3064 as work in progress. But there are no updates related to the Plus Plug S and it is not listed in the supported devices so far.

**Comment by markus7017** [comment]
It's in the DEV build

join here: https://community.openhab.org/t/shelly-binding/56862/3136?u=markus7017

**Comment by markus7017** [comment]
See PR 14532
