### ISSUE TITLE
[chromecast] STOP channel not accepting commands in 3.4.2

### ISSUE THREAD

**Issue by scatterthought** [openhab/openhab-addons#14516]
## Expected Behavior
Sending an `ON` command to the STOP channel will stop casting to a Chromecast device.

## Current Behavior
After upgrading to 3.4.2, the STOP channel no longer accepts `ON` commands. After downgrading to the 3.4.1 binding, the STOP channel works again.

## Possible Solution
I suspect this is related to [[chromecast] Fix for NPE when playerState is null #14191](https://github.com/openhab/openhab-addons/pull/14191). I think there may be an extra } on line 177.

## Steps to Reproduce (for Bugs)
1. Cast to a Chromecast device
2. Send an `ON` command to the device's STOP channel

## Your Environment

* Version used: OH 3.4.2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Raspberry Pi 4 4G
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openHABian

**Comment by mhilbush** [comment]
> I think there may be an extra } on line 177.

If there was an extra `}`, the binding wouldn't compile. Plus, the changes in the PR you referenced have nothing to do with how the binding handles commands to the stop channel.

Did you consider that [this commit](https://github.com/openhab/openhab-addons/commit/5b8300ad60344d0ce75382ab5fb8a0ce58faaa14), which actually modified the handling of the stop channel, might be in play as well?

**Comment by scatterthought** [comment]
Thanks, @mhilbush! I thought that would be the case, but I'm not a programmer.

I only saw #14191 listed in the [3.4.2 release notes](https://github.com/openhab/openhab-distro/releases/tag/3.4.2), so I didn't think to look for anything else. Apologies, as I don't know my way around Github very well.

**Comment by mhilbush** [comment]
No worries. I can see how you easily could've drawn that conclusion given the absence of that other commit from the release notes.

**Comment by lsiepel** [comment]
That PR did fix an issue, but might have introduced this. Are you able to provide a debug log ? 
I currently don't have my chromecast setup, so i can't look into this before thursday.

**Comment by scatterthought** [comment]
I'll provide a debug log later today. No need to rush on my part, as the 3.4.1 binding is working for me.

I don't think I've run into the offline issue you fixed, but I suspect that's due to how I'm set up. I use a group item to manage the STOP channels for all of my Chromecasts. I'm guessing that when I trigger it, the group only passes the `ON` command to the Chromecasts that are `OFF`.

**Comment by scatterthought** [comment]
> What app are you trying to stop? Probably not MEDIA_PLAYER ?

Is that the same as "Default Media Player"? I use that and Spotify regularly, but I can only be certain that it didn't work with Spotify.

**Comment by lsiepel** [comment]
> > What app are you trying to stop? Probably not MEDIA_PLAYER ?
> 
> Is that the same as "Default Media Player"? I use that and Spotify regularly, but I can only be certain that it didn't work with Spotify.

Oke in that case i allready know what is going on. That commit checks if the app is running before closing it. But the check is only for media_player, not for others. So if media_player is not running it exits. In your case spotify is running and it exits.

**Comment by scatterthought** [comment]
Sounds good. I'll test it with the Default Media Player and generate a debug log to confirm. Thanks!

**Comment by scatterthought** [comment]
I tested the 3.4.2 binding with Default Media Player, TuneIn Free, and Spotify. As expected, the STOP channel worked for the Default Media Player, but did not work for the other two apps.

I set the binding to debug, but nothing shows up when I trigger STOP to `ON`. I don't even see the item change in the log. But if I stop the player through Google Assistant, I see the STOP channel change from `OFF` to `ON` as expected.

Here's a brief log. I definitely sent an `ON` command to STOP during this time frame (I bracketed it with volume changes so that I'd know when to cut/paste).

Let me know when you want to test, but like I said before, I'm in no hurry. I can use the 3.4.1 binding for now.

[Chromecast debug log.txt](https://github.com/openhab/openhab-addons/files/10856664/Chromecast.debug.log.txt)

**Comment by nils2410** [comment]
We are at version 3.4.4, unfortunately the bug still exists. Anyone know a workaround?

**Comment by scatterthought** [comment]
The workaround is to manually install the 3.4.1 binding.

**Comment by nils2410** [comment]
Can you describe to me how this works?
Thank you

**Comment by scatterthought** [comment]
1. Download the .jar file. Here's a [direct link](https://openhab.jfrog.io/openhab/libs-release-local/org/openhab/addons/bundles/org.openhab.binding.chromecast/3.4.1/org.openhab.binding.chromecast-3.4.1.jar) to the JFrog repository (which was conveniently still in my Chrome history).
2. Remove the 3.4.4 Chromecast Binding from your system through Main UI.
3. Copy the .jar file into your addons folder to manually install it. Your existing things will start using the the manual installation immediately.

**Comment by jlaur** [comment]
When quickly looking through this issue, it seems that it might be a regression of #14158. @lsiepel, any chance you will find time for looking into this issue, as it seems you already had an idea how to fix it?

**Comment by lsiepel** [comment]
Still have this on my todo list. If someone can ccome up with a fix, don;t wait for me. Otherwise i will fix this as soon as i have some hours of free time.

**Comment by lsiepel** [comment]
Got it fixed. Test jar is here: https://1drv.ms/u/s!AnMcxmvEeupwjq1Zw3n0MTdrkMY4ZQ?e=lEs4Uz

It should work as before (and a little better). When an ON command is send to the STOP channel, it stops the running app. 
However not all running apps make this channel go to Off position. I'm pretty sure this has allways been the case. Only some casting and media apps do make it go to Off position. Netflix Disney and Prima don't, will casting with youtube did, so did the default media app.

**Comment by scatterthought** [comment]
Cool. Does the test jar work in 3.4? If so, I'll test it this weekend. I haven't upgraded to OH4 yet.

**Comment by lsiepel** [comment]
> Cool. Does the test jar work in 3.4? If so, I'll test it this weekend. I haven't upgraded to OH4 yet.

You could give it a try in 3.4, but i think it won't work as some xml files have changes name/structure.

**Comment by scatterthought** [comment]
Gotcha. I won't be able to test for awhile then, as I probably won't get to 4 for a few weeks (maybe longer). Thanks!

**Comment by sidamos** [comment]
Test JAR fixes the STOP command for me. OH 4.0.2, Nest Hub.
