### ISSUE TITLE
[shelly] Mismatch in representationProperty leading to devices reappering in inbox

### ISSUE THREAD

**Issue by seime** [openhab/openhab-addons#14533]
Problem: Things already added keeps popping up in the inbox again and again.

Tested both using config files and by adding via inbox.

Possible issue: thing config file states `serviceName` as `representationProperty` (ie https://github.com/openhab/openhab-addons/blob/2ec097d5295364370013f83a6bd82611e2486ac8/bundles/org.openhab.binding.shelly/src/main/resources/OH-INF/thing/shellyGen1_relay.xml#L218 - seems to be the same for most things) while discovery service uses `deviceName`as representationProperty (https://github.com/openhab/openhab-addons/blob/2ec097d5295364370013f83a6bd82611e2486ac8/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/discovery/ShellyDiscoveryParticipant.java#L191 and https://github.com/openhab/openhab-addons/blob/2ec097d5295364370013f83a6bd82611e2486ac8/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java#L95) 

Possible solution: Use _either_ `serviceName`or `deviceName` as `representationProperty`, and also expose selected field as a configuration field.

**Comment by markus7017** [comment]
I know this issue and kept it for backward compatibility, I don't want to run in the situation where all user report "I updated the build and now I have all things again in the Inbox"- Did you tried to change " .withRepresentationProperty(PROPERTY_DEV_NAME).build(); " into " .withRepresentationProperty(PROPERTY_SERVICE_NAME).build(); "?

**Comment by seime** [comment]
No I did not try to make any changes to the codebase.

Since neither `serviceName` nor `deviceName` can be specified as _configuration_ parameters, I guess they still would pop up in my inbox even if pre-configured via a thing file.

**Comment by seime** [comment]
I have a mix of Plus and non-Plus devices. Happens to all.
Did you configure your things via the UI or file @hmerk? I have all my Shelly things in files.

**Comment by seime** [comment]
```Thing shelly:shellyplugs:shellyplug1 "Shelly plug 1" @ "Udefinert" [deviceIp="192.168.2.140"]```

**Comment by hmerk** [comment]
Ok, I see your issue.
This is how one of my shellys is created via UI: 
UID: shelly:shelly2-relay:55973f
label: SHSW-21 Dining (shellyswitch-55973f@192.168.0.177)
thingTypeUID: shelly:shelly2-relay

In Things file it would look like this: 
Thing shelly:shelly:shelly2-relay:55973f "Shelly 2" @ "Somewhere" [deviceIp="192.168.xxx.xxx"]

It will never appear again in the inbox....

**Comment by markus7017** [comment]
@seime Did you verified homer's advise? 

The UID is the part after "-" of the service name. This are usually the last 6 digits of the MAC address or 12 digits MAC address (depending on device mode). Add the device in the UI, take the id from generated Thing UID, delete thing and add it manually to the .thing file.
