### ISSUE TITLE
[persistence] All persistence stopped saving data suddently

### ISSUE THREAD

**Issue by PanicMan** [openhab/openhab-addons#14544]
Hello,
I already issued that in the [Forum](https://community.openhab.org/t/all-persistance-stopped-saving-data-suddently/144824/5), but no permanent solution until now.

The problem is, that all persistence services, I'm using RRD4j and InfluxDB, on an specific moment, are stopping saving data.
Reading data is no problem, but saving data is not possible anymore until I restart the openhab service.

Internal Openhab RRD4j item Data:
![grafik](https://user-images.githubusercontent.com/4090506/223074926-ba9932fb-a3e9-4587-b827-cd3eaaea9ebe.png)

Grafana with InfluxDB Data. Ignore the orange data, as this is added by NodeRed directly to InfluxDB.
![grafik](https://user-images.githubusercontent.com/4090506/223076719-f991d96a-dbc3-4d61-a9cc-ee491d3ddc78.png)

Before that update to OpenHab 3.4.2, I had v3.4.1 before, I didn’t had that problems, that began after that update, some days later.
After restart of openhab service it work again for some time. In LogViewer nothing is shown. Items are updated all the time, this is also shown in LogViewer.

Please tell me what information you also need to investigate that problem.
Thanks a lot!

**Comment by lolodomo** [comment]
What binding is updating your items? 
Maybe this binding stopped working and no new persistence data is just a consequence of that? 

Note that there were only few changes between 3.4.1 and 3.4.2. You can find them in the release notes.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-distro/releases/tag/3.4.2

Changes in jdbc but not on other persistence services.

**Comment by PanicMan** [comment]
Mostly they are updated through MQTT. But that is working, I see the item values changed, also seen in the log.
But something must be changed between them, as this was working before and I changed nothing else.
I also checked disk space and ram, everything is fine there.

**Comment by PanicMan** [comment]
The only thing what I have around that time is in the syslog:

> Mar  6 09:18:10 openhab influxd-systemd-start.sh[3506]: [httpd] 127.0.0.1 - openhab [06/Mar/2023:09:18:10 +0100] "POST /write?db=openhab&rp=autogen&precision=n&consistency=one HTTP/1.1 " 204 0 "-" "okhttp/3.14.9" 6e6e3bca-bbf7-11ed-8bfb-e45f010be81e 7758
Mar  6 09:18:20 openhab influxd-systemd-start.sh[3506]: [httpd] 127.0.0.1 - openhab [06/Mar/2023:09:18:20 +0100] "POST /write?db=openhab&rp=autogen&precision=n&consistency=one HTTP/1.1 " 204 0 "-" "okhttp/3.14.9" 745958ec-bbf7-11ed-8bfc-e45f010be81e 7925
Mar  6 09:18:21 openhab influxd-systemd-start.sh[3506]: [httpd] 127.0.0.1 - openhab [06/Mar/2023:09:18:21 +0100] "POST /write?db=openhab&rp=autogen&precision=n&consistency=one HTTP/1.1 " 204 0 "-" "okhttp/3.14.9" 7521b46a-bbf7-11ed-8bfd-e45f010be81e 6347
Mar  6 09:18:22 openhab karaf[1053]: Exception in thread "OH-items-4" java.io.IOError: java.io.EOFException
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:1000)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume.getUnsignedShort(Volume.java:109)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1046)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:899)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1098)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreDirect.physAllocate(StoreDirect.java:666)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.update(StoreWAL.java:404)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Caches$HashTable.update(Caches.java:270)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.BTreeMap.put(BTreeMap.java:643)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.store(MapDbPersistenceService.java:186)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.lang.Thread.run(Thread.java:829)
Mar  6 09:18:22 openhab karaf[1053]: Caused by: java.io.EOFException
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:947)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:997)
Mar  6 09:18:22 openhab karaf[1053]: #011... 17 more
Mar  6 09:18:22 openhab karaf[1053]: Exception in thread "OH-items-1" java.io.IOError: java.io.EOFException
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:1000)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume.getUnsignedShort(Volume.java:109)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.longStackGetPage(StoreWAL.java:1046)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.longStackTake(StoreWAL.java:899)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreDirect.freePhysTake(StoreDirect.java:1098)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreDirect.physAllocate(StoreDirect.java:666)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.StoreWAL.update(StoreWAL.java:404)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Caches$HashTable.update(Caches.java:270)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.EngineWrapper.update(EngineWrapper.java:63)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.BTreeMap.put2(BTreeMap.java:707)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.BTreeMap.put(BTreeMap.java:643)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.store(MapDbPersistenceService.java:186)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.persistence.internal.PersistenceManagerImpl.handleStateEvent(PersistenceManagerImpl.java:152)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.persistence.internal.PersistenceManagerImpl.stateChanged(PersistenceManagerImpl.java:473)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar  6 09:18:22 openhab karaf[1053]: #011at java.base/java.lang.Thread.run(Thread.java:829)
Mar  6 09:18:22 openhab karaf[1053]: Caused by: java.io.EOFException
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.readFully(Volume.java:947)
Mar  6 09:18:22 openhab karaf[1053]: #011at org.mapdb.Volume$FileChannelVol.getByte(Volume.java:997)
Mar  6 09:18:22 openhab karaf[1053]: #011... 17 more
Mar  6 09:18:53 openhab npm[1279]: #033[32mZigbee2MQTT:info #033[39m 2023-03-06 09:18:53: MQTT publish: topic 'zigbee2mqtt/0x00158d0007f724e0', payload '{"battery":19,"humidity":82.66,"linkquality":55,"pressure":926.2,"temperature":-0.37,"voltage":2745}'
Mar  6 09:19:25 openhab npm[1279]: #033[32mZigbee2MQTT:info #033[39m 2023-03-06 09:19:25: MQTT publish: topic 'zigbee2mqtt/0x60a423fffed27294', payload '{"linkquality":55}'
Mar  6 09:20:54 openhab grafana-server[3504]: logger=cleanup t=2023-03-06T09:20:54.766640711+01:00 level=info msg="Completed cleanup jobs" duration=16.951305ms
Mar  6 09:20:54 openhab grafana-server[3504]: FileLogWriter("/var/log/grafana/grafana.log"): close /var/log/grafana/grafana.log: file already closed

**Comment by scotthraban** [comment]
The forum post resolved the problem, this issue should be closed, yes @PanicMan ?
