### ISSUE TITLE
[neeo] ops4j webservice duplicate servlet

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#14545]
Neeo started throwing this after the karaf update when OH starts.  The binding looks to work otherwise.  To note I've updated to SNAPSHOT 3347 to update beyond the JuPnP upgrade.

2023-03-05 12:30:13.342 [ERROR] [org.openhab.io.neeo.NeeoService     ] - Error during servlet startup
org.osgi.service.http.NamespaceException: ServletModel{id=ServletModel-35,name='org.openhab.io.neeo.internal.NeeoBrainServlet',alias='/neeo/NEEO-05dbea22',urlPatterns=[/neeo/NEEO-05dbea22/*],servlet=org.openhab.io.neeo.internal.NeeoBrainServlet@597ccd7b,contexts=[{HS,OCM-31,default,/}]} can't be registered. ServletContextModel{id=ServletContextModel-3,contextPath='/'} already contains servlet named org.openhab.io.neeo.internal.NeeoBrainServlet: ServletModel{id=ServletModel-34,name='org.openhab.io.neeo.internal.NeeoBrainServlet',alias='/neeo/NEEO-713af1e8',urlPatterns=[/neeo/NEEO-713af1e8/*],servlet=org.openhab.io.neeo.internal.NeeoBrainServlet@aab7de4,contexts=[{HS,OCM-31,default,/}]}
        at org.ops4j.pax.web.service.spi.model.ServerModel.addServletModel(ServerModel.java:1458) ~[?:?]
        at org.ops4j.pax.web.service.internal.HttpServiceEnabled.lambda$doRegisterServlet$1(HttpServiceEnabled.java:477) ~[?:?]
        at org.ops4j.pax.web.service.spi.model.ServerModel.lambda$run$2(ServerModel.java:541) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by morph166955** [comment]
@wborn thank you for moving it. I was concerned that this was more a core issue as neeo hasn't been updated in a very long time and this only sprang up after the kaeaf update, similar to the jupnp issue recently.

**Comment by wborn** [comment]
Perhaps due to Jetty/Pax Web implementation changes the timing is different or it could fail because of better sanity checks.
Maybe @tmrobert8 can have a look?

**Comment by morph166955** [comment]
Agreed it's probably either a new exception or check being fired, I'm assuming in pax. Unfortunately I think @tmrobert8 has stopped developing here, it's been a long time since I've seen him post. Also unfortunately, Neeo is a dead product so I don't see much work being done on it either. Those of us that have them still use them, but they will die off eventually. From what I'm reading, if I'm interpreting it correctly, it's not checking if it started a servlet already when a second thing comes online (I have 2 remotes).  It probably needs a check of some kind added.

**Comment by morph166955** [comment]
@J-N-K - As you've probably had the most exposure to the Karaf/Jetty/Pax upgrade, any idea why this is throwing now?  I'm going to attempt to find the offending code in the binding (which unfortunately isn't in the exception dump) but it would help if you had any additional insights.

**Comment by J-N-K** [comment]
Unfortunately I know nothing about this code. Maybe you can shortly describe what the servlet is used for, when and how it is created.

**Comment by morph166955** [comment]
My limited understanding, as I'm more or less just a user of the binding, is that the servlet is what is generating the web interface used to configure the OH side of the remote.  Basically (once you configure the Bridge) you go to http://oh-server/neeo/index.html and are presented with a landing page.  From there, you provide the data that the binding uses to tell the Neeo remote/brain what it needs to do to interact with OH (basically creating virtual devices or exposing OH things which you then go to the remote and add just like you would a TV).  As an example, I have a virtual device configured for my TV.  The configuration dictates that when the Neeo remote is interacting with the TV, if I hit the enter button on the remote it should send a string of TV_ENTER to an item I have on OH called NEEO_Command.  My rules then watch that item and when it gets TV_ENTER it sends the correct command to my TV.  

I believe the problem here is that the binding is not looking for existing servlets when it attempts to create a servlet (basically for the 2nd, 3rd, etc).  I don't see a reason why one would need more than one servlet in this instance as you aren't creating different configurations per device (they all get the same list of exposed virtual devices or things and you choose if you want to add them to the remote).

**Comment by morph166955** [comment]
Pictures for examples...

![neeo1](https://user-images.githubusercontent.com/53797132/223203741-8eabc23f-652b-4347-8b79-c1156ad12a2c.png)

![neeo2](https://user-images.githubusercontent.com/53797132/223203761-56592c88-7e28-44bc-95ad-2c3408175c71.png)

**Comment by morph166955** [comment]
And this is what we see on the Neeo GUI side.  This is pushed by the binding to the Neeo brain...

![neeo4](https://user-images.githubusercontent.com/53797132/223204704-ab823746-21cd-49f0-a61e-81a5e4336dd2.png)

**Comment by wborn** [comment]
I changed the code a bit so I could simulate having several brains like you do. 
Then I could reproduce it and fix it by making sure the servlet names are always unique with #14554.

**Comment by morph166955** [comment]
Thank you!  I'll confirm as soon as it's merged and I can pull a snapshot.

**Comment by morph166955** [comment]
This seems to be working properly. Thank you!

**Comment by wborn** [comment]
It's another error so create a new issue with detailed info on how to reproduce it.
