### ISSUE TITLE
[somfytahoma] Local API becomes unavailable once Somfy servers go down

### ISSUE THREAD

**Issue by rubensworks** [openhab/openhab-addons#14555]
## Expected Behavior

If the Somfy servers become unavailable, I would expect the local API to still be accessible.

## Current Behavior

Once the Somfy servers go down (Tahoma app also is inaccessible), the local API also stops working.
OpenHAB shows COMMUNICATION_ERROR - Bad credentials.

## Possible Solution

Unknown

## Steps to Reproduce (for Bugs)

1. Enable the local API
2. Wait for the Somfy servers to go down (they are down at the time of writing of this issue)

## Context

I hoped the local API would offer a more stable usage of Somfy Tahoma via OpenHAB, which does not rely on the public Somfy API server.

I'm not sure if this is an inherent limitation of Somfy's local API, or if this is just a bug in the implementation here (where it may first check for cloud access, but not fallback to the local API if that fails).

## Your Environment

* Version used: openHAB 3.4.1
* Environment name and version: OpenHABian
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): OpenHABian

**Comment by lsiepel** [comment]
Not 100% sure, but i think this can't be fixed as the local API still requires the cloud for authentication tokens. So while this local API improves throttling, speed and is a step towards less cloud dependendcy, it still requries the cloud.

**Comment by rubensworks** [comment]
If I understand correctly, these auth tokens are only valid for a short period of time, so if they become invalid while the cloud is down, the local API will not function anymore either?

If so, I guess we're stuck with this limitation until Somfy decides to make these auth tokens more flexible (or at least increase their duration).

**Comment by maisun** [comment]
Has anybody who uses Somfy binding experienced random account lock out due to bad credentials? I have Tahoma switch and every 2-3 months I need to call Somfy technical support to unlock my user account. I only use Somfy iOS app and OpenHAB, and in both cases username/pwd are correct. Many thanks

**Comment by panis16** [comment]
Problem here is that box appears disconnected on iOS app, and OpenHAB shows communication error, can´t register events. I experience this behavior more or less after a week, and it solves unplugging AC and recovering power. After a while, box appears again available.

**Comment by maisun** [comment]
> Problem here is that box appears disconnected on iOS app, and OpenHAB shows communication error, can´t register events. I experience this behavior more or less after a week, and it solves unplugging AC and recovering power. After a while, box appears again available.

Ok, great to know that. In my case support told me there were failed login attempts from my IP address and therefore my account is locked. When they unlock it, both my app and OpenHAB binding start to work. This happens every 1-2 months, I don't know what triggered it as the credential is 100% correct.

**Comment by lsiepel** [comment]
> Has anybody who uses Somfy binding experienced random account lock out due to bad credentials? I have Tahoma switch and every 2-3 months I need to call Somfy technical support to unlock my user account. I only use Somfy iOS app and OpenHAB, and in both cases username/pwd are correct. Many thanks

Not related to this issue. But i think it is the same as: https://github.com/openhab/openhab-addons/issues/14763

**Comment by lsiepel** [comment]
I close this issue, as renewing expired tokens while the somfy cloud servers are down is not swomething that can be solved from the binding.
