### ISSUE TITLE
[homekit] dimmer groups not working

### ISSUE THREAD

**Issue by PaulchenP** [openhab/openhab-addons#14550]
## Expected Behavior
Changing values in the homekit app for Group:Dimmer items should also change them in openHAB.

## Current Behavior
The current dim level values of the group items are shown in the homekit app. But changing values/sending dim values in the homekit app leads to errors.

```
[WARN ] [ristics.impl.base.BaseCharacteristic] - Error while setting JSON value 11 for characteristic io.github.hapjava.characteristics.impl.lightbulb.BrightnessCharacteristic

java.lang.ClassCastException: class org.openhab.core.items.GroupItem cannot be cast to class org.openhab.core.library.items.DimmerItem (org.openhab.core.items.GroupItem and org.openhab.core.library.items.DimmerItem are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @324a50)
```

## Steps to Reproduce (for Bugs)

Group:Dimmer:MAX items lead to the error from above when changing values in homekit while Dimmer items work as intended.

## Your Environment
openHAB 3.4.2 and homekit addon version 3.4.2

**Comment by lsiepel** [comment]
@PaulchenP Would be nice if you can confirm this issue is still hapening on openHAB 4.2.0 

If so, i'm sure @ccutrer or @yfre can comment on this issue.

**Comment by ccutrer** [comment]
I'm able to repro this with these simple items:

```
Group:Dimmer:MAX TestLights "Test Lights" { homekit="Lighting" }
Dimmer TestLight1 "Test Light 1" (TestLights)
Dimmer TestLight2 "Test Light 2" (TestLights)
```
