### ISSUE TITLE
[transform.JSONPath] Installation failing

### ISSUE THREAD

**Issue by Hertiwolfi** [openhab/openhab-addons#14579]
OpenHAB 3.4.2 JSONPath Trans....installation cannot be fullfilled...progress display stays in installation modus and isn´t finished - have you got any hints ?

Thanks in advance

**Comment by wborn** [comment]
> have you got any hints ?

Have you got some logging?

**Comment by wborn** [comment]
That's still pretty vague. Maybe you can paste all the relevant logging here?

**Comment by Hertiwolfi** [comment]
Sorry...here the complete message out of the log from openhab:

Resource mvn:org.openhab.addons.bundles/org.openhab.transform.jsonpath/3.4.2 does not contain a manifest

**Comment by wborn** [comment]
If I search the community on ["does not contain a manifest"](https://community.openhab.org/search?expanded=true&q=%22does%20not%20contain%20a%20manifest%22%20order%3Alatest) it looks like your downloaded add-on file got corrupt somehow.

Maybe it helps to clean the cache so the add-on gets redownloaded. 
You could also upgrade to 3.4.3 which was recently released and it will then also redownload add-ons.

**Comment by markus7017** [comment]
Is the problem solved?

**Comment by Hertiwolfi** [comment]
Yeah - problem was fixed with cleaning the cache and redownload - issue closed
