### ISSUE TITLE
[knx] Dimmer Control does not stop after latest 4.0.0.M1 update

### ISSUE THREAD

**Issue by djreudink** [openhab/openhab-addons#14598]
Hello Everyone,

After upgrading to 4.0.0.M1 today I realized KNX dimmer control devices with a frequency != 0 no longer stops due to PR #14504.

Just to double check I changed in DeviceThingHandler.java line 396 to

                    if (UnDefType.UNDEF.equals(type) || UnDefType.NULL.equals(type)) {

to catch UnDefType.NULL, too.

Honestly I am not very familiar yet with github and pull requests. So please excuse not raising one myself. That, plus I am not quite sure if that is the ideal solution tbh.

Cheers,
Dominique

**Comment by J-N-K** [comment]
Where does this NULL come from?

**Comment by holgerfriedrich** [comment]
Unfortunately, my tests did not include dimmer-control :-/

@J-N-K this part is not ported yet, it is included in #14534.
#14534 should resolve this issue, but it is not ready yet.

Do you think we need a hot-fix here?

**Comment by J-N-K** [comment]
No, that requires extra work for an intermediate solution that probably lasts a week or less.

**Comment by J-N-K** [comment]
Yes. I would include them in the other PR. I think we can finish that one until the end of the week and the hopefully someone will do a review shortly. @jlaur I'm counting on you :-)

**Comment by J-N-K** [comment]
@holgerfriedrich You can also let me know if you want me to look into something special. I'm busy tomorrow and Thursday, but can probably find some time on Friday and Saturday.

**Comment by jlaur** [comment]
> Yes. I would include them in the other PR. I think we can finish that one until the end of the week and the hopefully someone will do a review shortly. @jlaur I'm counting on you :-)

I'll have a look. 👍 Perhaps @kaikreuzer would also like to step in as code owner, and of course it would be much appreciated if you could also verify, @J-N-K, as you know the code now being merged.
