### ISSUE TITLE
[ekey] While using kubernetes the paketAdresss does not matches the sourceIP

### ISSUE THREAD

**Issue by querdenker2k** [openhab/openhab-addons#14599]
I am getting "Packet received from unknown source" when behind a kubernetes service with NodePort
When i comment this check out it's working because the packet address is the real host address.

## Your Environment
openHAB 3.4.0 M6
Kubernetes with own Chart and behind NodePort-Service
and of course using the eKey binding

@hmerk I would create a merge request but using 3.4.0 M6 and when i compile with from the current main i am getting an osgi dependency error

**Comment by hmerk** [comment]
Sorry, but don’t know anything about your dependency error, especially as you are not showing the error.

On the other hand, I don‘t like the idea to remove this check, as it was implemented by intention.
I don’t think I will approve such a PR.

**Comment by querdenker2k** [comment]
I don't want to discuss my osgi error here.

The eKey binding worked fine for me the last year while using docker (with host network).
I switched to kubernetes now and this check prevents it from working.
The eKey ip is x.x.x.160 (which is configured) and my host ip (where kubernetes is running on) is x.x.x.200.
The problem is now that the arriving package from eKey does not have the ip x.x.x.160, but x.x.x.200.
My intention is not to just remove some checks, but maybe add a new optional parameter such sourceIP.
I would like to use this binding from the repository instead of having my own compiled version.

**Comment by hmerk** [comment]
This sounds different from your initial post.
Adding a config option for the sourceIP check instead of complete removal will be fine.
Please feel free to create a PR.

**Comment by lolodomo** [comment]
Can the issue be closed now?

**Comment by querdenker2k** [comment]
Yes thanks
