### ISSUE TITLE
[MQTT] mqtt.generic syntax validation error

### ISSUE THREAD

**Issue by phinnay** [openhab/openhab-addons#14609]
When working on converting my OH2 install, i ran into a validation error in the MQTT Generic ([Things and Channels??](https://www.openhab.org/addons/bindings/mqtt.generic/)) binding.

```
11:27:39.676 [INFO ] [del.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'MQTT.things', using it anyway:
Provide a thing type ID and a thing ID in this format:
 <thingTypeId> <thingId>
```
I assumed the binding syntax had changed and updated my .things file to use the above syntax but this caused all Item values to return NULL and no messages to be sent to the broker. 

Returning to the previous ```mqtt:topic:myBroker:myThing``` syntax got everything working again, but with the above validation error. 

There is inconsistent documentation [here](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.mqtt.generic/xtend_examples.md#converting-an-mqtt1-installation) showing both syntax? i'm not sure if demo1.things refers to the V1 syntax and demo2.things refers to V2(or OH3?) way of doing it? 

I did find an open [issue](https://github.com/eclipse-archived/smarthome/issues/6706) mentioning this from back in 2018 that set me on the right path - it's been sitting open since, even though the repo has been archived. 

## Expected Behavior
Configuring MQTT Things in the correct format does not result in a validation error.

## Current Behavior
Configuring MQTT Things in a working format results in a validation error. 

## Possible Solution
I don't care what format is used, though the ```<thingTypeId> <thingId>``` method does look cleaner. Whatever way ya's want just make sure it passes internal validation checks :D  

## Steps to Reproduce (for Bugs)
Configure MQTT and define things / channels using the 'generic' binding.

## Context
Took me a bit of headscratching to understand why my .things file was all good to OH3 however none of the MQTT messages were getting to the broker. I am glad to have found the post from 2018 and was able to move on with the migration. 

## Your Environment
```
Linux openhab3 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64

                           _   _     _     ____
   ___   ___   ___   ___  | | | |   / \   | __ )
  / _ \ / _ \ / _ \ / _ \ | |_| |  / _ \  |  _ \
 | (_) | (_) |  __/| | | ||  _  | / ___ \ | |_) )
  \___/|  __/ \___/|_| |_||_| |_|/_/   \_\|____/
       |_|       3.4.2 - Release Build

Use '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
To exit, use '<ctrl-d>' or 'logout'.
```

**Comment by lsiepel** [comment]
Hope you got it all working by now.

the examples from https://www.openhab.org/addons/bindings/mqtt.generic/#examples should work. If you still have issues to get this to work it might be a good idea to raise this question on the community forums as there more users will see it.
