### ISSUE TITLE
[eccobee] Typo in disconnectDateTime channel description propagates to item name and label

### ISSUE THREAD

**Issue by tcgerhard** [openhab/openhab-addons#14606]
The Description of the "disconnectDateTime" is "Disconnected Date Timee" (note extra "e" at end).   When creating an item via the channel link UI, this typo carries into the Item name and label fields.   Once created, the item has to be deleted and recreated in order to fix the item name.
The description in the documentation carries the same error.

## Expected Behavior
Correct the spelling of the description

## Steps to Reproduce (for Bugs)
1. From an Ecobee Thermostat thing, click the channels tab
2. Click the "advanced" checkbox
3.Select the  disconnectDateTime channel
4. Select Create New Item

## Context
Relatively minor annoyance that have to go back and recreate items that were created.

## Your Environment
* OH 3.3.0, but 4.0 milestone docs suggest the bug is still present.

**Comment by mhilbush** [comment]
Thanks for reporting. Submitted the fix.
