### ISSUE TITLE
[Netatmo] Cannot toggle monitoring of Presence camera

### ISSUE THREAD

**Issue by Owlbertz** [openhab/openhab-addons#14617]
## Expected Behavior
In a previous version of the binding it was possible to toggle the monitoring state of a camera with the `status#monitoring` channel.

## Current Behavior
While the channel still exists, it does nothing and only displays:
> [INFO ] [andler.capability.SecurityCapability] - Monitoring changes can only be done on local camera.

Both the camera and the openHAB server are on the same network.

## Steps to Reproduce (for Bugs)
1. Configure Netatmo Account thing, Home thing and Smart Outdoor Camera
2. Add item to camera's `status#monitoring`
3. Toggle item

## Context
I guess this issue is related to the recent change in the Netatmo API. 
The behavior itself is still possible via the API: https://dev.netatmo.com/apidocumentation/security#setstate with `"monitoring": "on"`.

Related forum thread: https://community.openhab.org/t/monitoring-changes-can-only-be-done-on-local-camera/139430/5

## Your Environment
Tested on my openhabian system with 3.4.0 Release and also tested on latest 4.0.0-Snapshot docker image.

I would really appreciate this being fixed to the state as it was last year. I am really missing the functionality of having my monitoring and thus notifications paused when I am at home.

**Comment by Owlbertz** [comment]
I just received feedback from Netatmo support. They told me that they recently removed the feature to toggle the monitoring due to security concerns. I kindly ask them to consider re-enabling this feature as I think this is an important use case to toggle monitoring using home automation.

I guess it makes sense if anyone that is also interested in this feature to also contact their support and ask for it to come back.

**Comment by lolodomo** [comment]
@Owlbertz : someone on the community forum said it is working again. Can you please confirm and then close the issue?

**Comment by Owlbertz** [comment]
I observed the behavior over the past few days. Seems indeed like this has been fixed.
Strangely, the API docs from Netatmo still state you can only toggle the floodlight, but not the monitoring...
