### ISSUE TITLE
[homekit] Problems assigning and editing metadata through mainUI in oH3.4.2

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-addons#14628]
## Expected Behavior
Assigning HomeKit related metadata should work as it does in other bindings.

## Current Behavior
Assign a device type at Equipment level. This now spawns a JavaScript error.

This should enable you, when successful, to assign sub properties of Points associated to that Equipment, and to propagate those edits by one click. This action unfortunately does nothing, so you need to manually add the HomeKit metadata to each relevant Point.

Second problem: if assinging multiple device types at Equipment level, the mainUI unpredictably either displays nothing or presents a garbled list of characteristics which, unfortunately, also can't be assigned to.

The `openhab.log` entries report nio characteristics are assigned when added multiple device types at Equpment level, but MainUI seems to remember that multiple types were actually assigned (although these don't show up in the settings afterwards).

## Possible Solution
Probably an identifier has been updated in the mainUI, or the way metadata must be interacted with in MainUI.

## Steps to Reproduce (for Bugs)
See above.

## Context
This bug makes assigning HomeKit metadata more time consuming than necessary, more error-prone and in some cases even impossible, resulting in unresponsive Homekit accessories due to some mingled metadata.
See https://community.openhab.org/t/problems-with-homekit-binding-in-openhab3-4-2/145265

## Your Environment
openHAB 3.4.2 (clean install on clean openhabian image, new microSD card)
raspberry Pi 3B+

**Comment by ccutrer** [comment]
Issues with configuring the HomeKit add-on via MainUI belong in the [WebUI repo](https://github.com/openhab/openhab-webui/)
