### ISSUE TITLE
[Velbus] feature request - VMBDALI

### ISSUE THREAD

**Issue by rvilwei** [openhab/openhab-addons#14654]
Hi,

Would it be possible to add support for the VMBDALI module in the velbus binding?

It would be great if the lights could be switched and the dimmer controlled from openhab. 
Maybe it is possible to be incorporated as a multi channel dimmer?

I contacted MDAR who has a demo rig that can be remotely accessed if necessary.

Thank you,

Roel

**Comment by MDAR** [comment]
> I contacted MDAR who has a demo rig that can be remotely accessed if necessary.


Indeed, as always, I'm happy to give anyone remote access to any #Velbus hardware for development.

I just wish I had the skills to do the coding magic
