### ISSUE TITLE
[boschshc] Unsupported devices during discovery

### ISSUE THREAD

**Issue by david-pace** [openhab/openhab-addons#14672]
Hi,

I just tested the latest state (`4.0.0-SNAPSHOT`) with the discovery and logged on debug level. I saw the following unsupported devices during discovery:

```
16:30:46.182 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.182 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'LEDVANCE_LIGHT'! Please create a support request issue for this unknown device model.
16:30:46.182 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.182 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SMOKE_DETECTION_SYSTEM'! Please create a support request issue for this unknown device model.
16:30:46.182 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.185 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.186 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.188 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'TRV_GEN2'! Please create a support request issue for this unknown device model.
16:30:46.201 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.201 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.201 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.201 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.201 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'MULTISWITCH'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'LEDVANCE_LIGHT'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'PRESENCE_SIMULATION_SERVICE'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'VENTILATION_SERVICE'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_BRIDGE_MANAGER'! Please create a support request issue for this unknown device model.
16:30:46.202 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'HUE_LIGHT_ROOM_CONTROL'! Please create a support request issue for this unknown device model.
16:30:46.203 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD'! Please create a support request issue for this unknown device model.
16:30:46.203 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'SWD2'! Please create a support request issue for this unknown device model.
```

The deduplicated and sorted list of device models is:

- `HUE_BRIDGE_MANAGER`
- `HUE_LIGHT_ROOM_CONTROL`
- `LEDVANCE_LIGHT`
- `MULTISWITCH`
- `SMOKE_DETECTION_SYSTEM`
- `SWD`
- `SWD2`
- `TRV_GEN2`
- `VENTILATION_SERVICE`

@GerdZanker do you have an idea how those can be mapped to our supported devices?

Also I'm wondering whether we should log this on `INFO` or `WARNING` level, because regular users will not log on `DEBUG` level and will therefore not see the messages.

**Comment by GerdZanker** [comment]
> Also I'm wondering whether we should log this on `INFO` or `WARNING` level, because regular users will not log on `DEBUG` level and will therefore not see the messages.

Some information was logged on ``Info`` level, but this was changed on request during the Discovery Pull request to ``Debug``.

Because we have quit a long list of things we could support, I want to investigate the idea of a console command line support to get e.g. status of bridge and devices and also more "debug" info about available devices + services and returned data from the SHC.

Compare with [this command example](https://github.com/openhab/openhab-addons/pull/13615) and image commands like

    openhab> openhab:boschshc status
    openhab> openhab:boschshc bridgeinfo
    openhab> openhab:boschshc devicesinfo
    openhab> openhab:boschshc servicesinfo

**Comment by david-pace** [comment]
I debugged further and found out that the following devices are behind the device model names:

- `SWD`: Door/Window Sensor I
- `SWD2` -> Door/Window Sensor II
- `LEDVANCE_LIGHT` -> Zigbee Smart Bulb
- `TRV_GEN2` -> Thermostat II
- `MULTISWITCH` -> Twist

Since we already support the Door/Window Sensor and the Zigbee Smart Bulbs, we should add those associations in `ThingDiscoveryService`. I guess the `MULTISWITCH`/Twist is not supported yet.

About the 2nd generation models: what is the general strategy to support them? Should they be separate devices that extend the functionality of the 1st generation devices, or should we only have one device covering everything that is possible, no matter if it's a 1st or 2nd generation device?
