### ISSUE TITLE
[xmpp] Reconnection every 30 min

### ISSUE THREAD

**Issue by Bart1478** [openhab/openhab-addons#14713]
Hi,

I have some issues with the xmpp communication in Openhab 3.4.2. 
Every 30 minutes the binding encounters a "Connection XMPPTCPConnection” -error and the connection is reestablished.
But, the messages are only replied the first seconds of the reestablished connection... after a while new messages are not replied until the connection encounters a error and reestablished the connection again. 
Don't know is this is a bug or a wrong setup.....

Can someone help me out?

![image](https://user-images.githubusercontent.com/73669901/228069544-cc07e656-6f13-4b08-883f-bdf0891b8434.png)

**Comment by lsiepel** [comment]
A while ago i started work on improving the connection handling for the xmppclient. I suspect this issue has been fixed by https://github.com/openhab/openhab-addons/pull/14397 
Could you test the 4.x jar from that PR?

**Comment by Bart1478** [comment]
Hi,

Just upgrade openhab to version 4.0.0...
Can't load the binding, if i look into the openhab.log i get this error 
![image](https://github.com/openhab/openhab-addons/assets/73669901/eccd18f0-126e-48ab-b988-72f1642cf5c9)

**Comment by lsiepel** [comment]
i'll try to build a kar (that includes the dependencies)

**Comment by lsiepel** [comment]
With this kar it should work bette as it holds all dependencies: https://1drv.ms/u/s!AnMcxmvEeupwjq5ie1voAOj-Co_mEg?e=L3adOH 
Uninstall the xmpclient, remove the jar and drop this car in the addons folder.

**Comment by Bart1478** [comment]
Uninstalled the xmpclient binding, removed the Jar and dropped the Kar file into the add-on folder, Restarted openhab...
Still some errors when starting up... see attached log file.

[openhab.log](https://github.com/openhab/openhab-addons/files/12248238/openhab.log)

**Comment by lsiepel** [comment]
Hi Bart, i followed: https://community.openhab.org/t/how-to-build-kar-files-for-marketplace-that-is-compatible-with-milestone-and-snapshot-builds/128433 to generate this KAR. It seems that it only works with snapshot versions. 
And you seem to use 4.0.1 stable. 

The kar should work with the 4.1.0-snapshot version of OH, but i can understand you prefer your current setup. 
My knowledge to this kar building with dependencies is limited. Maybe @jlaur has some suggestions?

**Comment by Bart1478** [comment]
Hi Isiepel,

Still struggeling with the same issue.....losing xmpp connection to the server and after 30min it reconnects for 1 minuut... 
Meanwhile upgraded to openhab 4.1.0 and installed xmpp version 4.1.0....
Could you please help me out?

![image](https://github.com/openhab/openhab-addons/assets/73669901/e6c58d21-2c5d-40bf-b871-eacc19df8468)
![Schermafbeelding 2024-02-25 174534](https://github.com/openhab/openhab-addons/assets/73669901/06166e3e-f0e4-473b-8834-fc7a77204b7c)

**Comment by lsiepel** [comment]
Will try to get you an updated version of the binding for a 4.1.1 build with a fix this week.
