### ISSUE TITLE
[Shelly] binding can't be turned on / logged after update to 20230308-091612/0.14.1-g22a4cb7 /  0.14.1

### ISSUE THREAD

**Issue by devtos** [openhab/openhab-addons#14723]
After update to 0.14.1 i can't turn on anything or log anything anymore. with 0.12 everything was fine. Shelly 1 PM, around 9 Shellys

**Comment by markus7017** [comment]
what do you mean with "turn on anything". This seems like a corrupted setup, I have many devices on 0.14.1 and some on 1.0 beta 5
