### ISSUE TITLE
[mqtt.homeassistant] Binary sensor should create a Contact channel

### ISSUE THREAD

**Issue by obones** [openhab/openhab-addons#14721]
I have a door/window contact sensor that gets detected just fine by mqtt homeassistant which in turns creates a Thing with 6 channels: 
Battery voltage
Battery percentage
Link quality
Low battery indicator
Tamper indicator
Contact state

## Expected Behavior
The state and two indicators are reported as `binary_sensor` and as such should create a "read-only" channel, a Contact one being expected in my case.

## Current Behavior
Unfortunately, the three channels come up as Switch channels as seen below:
![image](https://user-images.githubusercontent.com/1314739/228570283-99eb8847-5014-4d3d-b6b4-9f3865ab3b34.png)

When creating an item linked to this channel openHAB UIs use a switch to display the state and allows turning on or off the element when it's not even logical to do so.

## Possible Solution
As generating Contact channels for all cases may not be desirable, using the device_class value from the announcement would allow to determine cases where Open/Closed is better suited and thus a Contact channel appropriate. 
The documentation from homeassistant is quite comprehensive on the subject: https://www.home-assistant.io/integrations/binary_sensor/#device-class

## Steps to Reproduce (for Bugs)
1. Add a window/door contact to the zigbee network in zigbee2mqtt
2. Add the new Thing from the inbox
3. See the created channels.

## Context
As the native zigbee binding has some limitations in the device it supports, I'm experimenting with zigbee2mqtt. homeassistant auto discovery is very nice, it avoids spending a lot of time repeating the same actions for my dozen of existing zigbee devices.
I already have groups and rules relying on the fact that door/window detectors are reported as Contact channels and so would like the sensors to show up a such when used via zigbee2mqtt.

## Your Environment
    Hardware: amd64 / 4 cores / 8G RAM
    OS: Manjaro
    Java Runtime Environment: Oracle 11.0.18
    openHAB version: 3.4.2

Thanks a lot for your hard work.

**Comment by ccutrer** [comment]
The analogous Homie issue was rejected. It feels like we're going to leave this one as-is as well. See the linked PR for more discussion.
