### ISSUE TITLE
[zwave] unsigned 8-bit values displayed incorrectly in Thing configuration

### ISSUE THREAD

**Issue by tcgerhard** [openhab/openhab-addons#14729]
## Expected Behavior

device parameters that are defined as unsigned are displayed as 8 bit signed values, i.e., "-1" is displayed instead of "255", should be displayed as 0-255

Found on the device "Dome Z-Wave Plus Motion Detector with Light Sensor and Flexible Magnetic Mount"

manufacturerId
021F
manufacturerRef
0003:0083
dbReference
797
zwave_deviceid
131

## Current Behavior
Values  from 128 => 255 are displayed as -128 => -1

Examples:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/758059/229261501-5e553ca8-8e32-48a3-bfd7-a81afeae5a14.png">

<img width="459" alt="image" src="https://user-images.githubusercontent.com/758059/229261359-11d03609-f1f4-4428-8c87-a809639e14f5.png">

## Steps to Reproduce (for Bugs)

1. include "Dome Z-Wave Plus Motion Detector with Light Sensor and Flexible Magnetic Mount" or other device using 8-bit unsigned parameters
2. view thing properties

## Context

Makes it difficult to set the value you'd like if you don't understand the relationship between the displayed and intended values.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
OH 3.3.0
ZWave 3.3.0 (as reported by bundle:list)
Raspbian
Chrome 111.0.5563.110, MainUI

**Comment by lsiepel** [comment]
The z-wave binding has it's own repository that can be found here: https://github.com/openhab/org.openhab.binding.zwave
As this is a specific z-wave issue, i suggest you re-post your issue there, sorry.

**Comment by tcgerhard** [comment]
Thanks @lsiepel.   Looks like it's already covered by [issue 763 in that repository].(https://github.com/openhab/org.openhab.binding.zwave/issues/763)
