### ISSUE TITLE
[goecharger] Gemini charger API sending Kommavalues

### ISSUE THREAD

**Issue by soulid** [openhab/openhab-addons#14736]
I am using a new Go-E Gemini 22KW Version Software revision 055.0 using with openHAB 3.4.2 and latest revision go-e binding. 
- Thing setup :
`UID: goecharger:goe:e887e8d76a
label: Go-eCharger
thingTypeUID: goecharger:goe
configuration:
  refreshInterval: 5
  apiVersion: 2
  ip: 192.168.*.*
`

My issue is that the app is not working
- Device is shown as "Online". No issue on logfile shown.
- Channels opened are shown as either UNDEF or NULL
- Binding seems to expect non-comma values. When using URL http://192.168.*.*/api/status?filter=nrg the return is:
`{"nrg":[220.1,226.3,226.61,2.48,15.732,0.038,0.076,3450.994,4.9,7.855,0,3463.749,99.66444,56.98337,45.61027,100]}`
- Go-E is readable through MQTT.
- Tried to configure binding as well as Go-E wallbaox API1 or API2 or both. Shows "OFFLINE" with go-e=API V1. No success therefore.

**Comment by soulid** [comment]
Not sure what happened. Re-installing the binding solved the issue

**Comment by chilobo** [comment]
I had the same problem. Re-installing the binding and **switching API version from 1 to 2** solved the issue.
