### ISSUE TITLE
[vdr] getting error logs with active things

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#14747]
## Current Behavior
When a vdr Thing is active, when loading the Items list results in an error message (one line for each active Thing)
```
[ERROR] [al.ChannelCommandDescriptionProvider] - Dynamic command description matches original command description. DynamicCommandDescriptionProvider implementations must never return the original command description. class org.openhab.core.internal.types.CommandDescriptionImpl has to be fixed.
```

For reference:
https://community.openhab.org/t/vdr-binding/10839/30

## Your Environment

* Version used: openHAB 3.4.2, addon from official store
* Java 11-64 openjdk 11.0.18 
* debian bullseye 11.6 amd-64

**Comment by udo1toni** [comment]
Same error in  
* openHAB 4.0.1,
* Java 17-64 openjdk 17.0.8 2023-07-18
* debian bookworm 12.1 amd-64

**Comment by lolodomo** [comment]
@MatthiasKlocke : could you please investigate ?

**Comment by MatthiasKlocke** [comment]
Sure, I will have a look beginning of next week @udo1toni,  @lolodomo.

**Comment by MatthiasKlocke** [comment]
Hello @udo1toni , 
so far I wasn't lucky to reproduce the issue in the VDR binding. Would you be so kind enough to give me some more details? 
You mentioned that this happens when you reload the items list. How do you do that? Putting text file configuration into the conf directory or does this happen when you open the item list in the openhab user interface? Thanks!

**Comment by udo1toni** [comment]
It's sufficient to click the update button in VS Code, even selecting Semantic Model or Items in the Main UI will trigger the error.

**Comment by MatthiasKlocke** [comment]
Hello @udo1toni , 

thanks for your reply. I'm sorry, but I still can't reproduce it...

I have defined VDR things in text files and also in MainUI. I added items to them with an assigned semantic class. I've gone through all pages but the error is not shown in log file. 
I checked in openHAB github repo to see where your log message is being generated. It comes from a class that is not used by the VDR binding. 

Can you set the VDR's binding log level to TRACE and also the following log level to debug?
-> KARAF console
`log:set TRACE org.openhab.binding.vdr`
`log:set DEBUG org.openhab.core.thing.internal.ChannelCommandDescriptionProvider`

Thanks!

**Comment by udo1toni** [comment]
The log did not give any  hints. 
But: I deleted my things (created via text file) and recreated one of them via UI -> no Error message.
I then recreated the Things via text file but set all parameters (I did not set the port before because this was the default port anyway. Seems that did the trick, the error is gone since.

**Comment by udo1toni** [comment]
Sorry, have to reopen the Issue, I had a small typo in my things file, so the things were never populated...
After correction, the error is back... :(

**Comment by udo1toni** [comment]
Finally, after a restart, the error is gone... This is a strange behavior, Maybe I'll have to rebuild my machine from scratch...

**Comment by MatthiasKlocke** [comment]
Hello @udo1toni , sorry to hear that it's still not working. 

I can't reproduce... I now took your things file (which looks unspectacular) and tested it in a fresh 4.0.1 on debian bullseye (raspberry) with DNS spoofing for your local hostnames. Everything looked fine. 

Can you do a similar test with a fresh openHAB 4.0.1 and share the openhab log file with me?

**Comment by udo1toni** [comment]
yes, sure, will report

**Comment by udo1toni** [comment]
Seems that redoing the complete configuration has done the trick. Lucky me I'm using text configuration wherever possible, so the only stuff which went do be done after copying all text files was to copy the yaml for widgets and main ui :)
