### ISSUE TITLE
[knx] `-control` channels do NOT work

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-addons#14753]
Since the recent SNAPSHOTs, `*-control` channels have stopped working. 
I have checked when the issue first occured, and it seems that SNAPSHOT `#3390` from 31st of March 2023 isn't affected by this problem. This means, that there was no change in the KNX binding that can cause this: https://github.com/openhab/openhab-addons/commits/main/bundles/org.openhab.binding.knx.

It must be a core changes, however I have no clue which one, it must be one between March 31st and April 2nd (https://github.com/openhab/openhab-core/commits/38a6d1e87bdd3fadcc2adcd4604a2bed90ab4c06), because this is the timeframe the issue first occured.

I did some debugging, and very interesting: for `-control` channels, the [`handleCommand`](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/DeviceThingHandler.java#L198) method of the KNX Thing is never called when I send a command to Items linked to a -control channel.
This is the right behaviour when the [`SystemFollowProfile`](https://github.com/openhab/openhab-core/blob/4a82f5ba4943bc363f1a482c0d7e6b06f30205ba/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/profiles/SystemFollowProfile.java#L69) is applied to the channel link, and this is recommended by the [`KNXProfileAdvisor`](https://github.com/openhab/openhab-addons/blob/c12715bda7f93ed7f958590291627ef6b19fa2b7/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/profiles/KNXProfileAdvisor.java#L53) for `-control` channels. 
I also wonder if it is correct to suggest follow profile for -control channels by default. Either way, this should be documented.

Manually setting `system:default` profile for the affected channel links should help for now, but I think there is a problem with the `system:follow` profile not forwarding state updates anymore.

**Comment by florian-h05** [comment]
@J-N-K @holgerfriedrich Can you reproduce?

**Comment by J-N-K** [comment]
I didn‘t check, but will have a look tomorrow. Probably openhab-core#3141 is the cause.

**Comment by florian-h05** [comment]
@J-N-K Seems like I found an error in `org.openhab.core.thing.internal.CommunicationManager`, I will test my fix and then open a PR.

**Comment by holgerfriedrich** [comment]
@florian-h05 sorry cannot test right now, my test system is still on M1 and has no control channels in use.
If yo need additional testing, give me some time to adapt. In contrast to @J-N-K I typically only use the text config....

**Comment by J-N-K** [comment]
I guess this only affects the follow profile, and that's why it went unnoticed.

**Comment by florian-h05** [comment]
Yeah, I agree. 

`-control` channels broke because `CommunicationManager` had a wrong event subscription and did not receive `ItemStateUpdateEvent`s. In consecuence, the follow profile broke, because it only releays state updates, which were not received.

Therefore: Will be fixed by https://github.com/openhab/openhab-core/pull/3529.
