### ISSUE TITLE
[solax] New binding with local and cloud data retrieval

### ISSUE THREAD

**Issue by theater** [openhab/openhab-addons#14782]
The Solax inverters so far supported only a cloud based data retrieval via cloud API. It has a limitation that the push from the inverter to the API is made on every 5 minutes which makes dynamic calculation and optimization of the load very hard.
With wi-fi dongle version 3.x they now support a very simple JSON with all counters provided as a data array.
So far I used the HTTP binding with a JSON path mapper.

Probably it's a good idea to implement a binding with two bridges - one for the cloud connectivity and one for the local connection.

More details from home assistant page could be found here: 
https://community.home-assistant.io/t/solax-x1-hybrid-g4-local-cloud-api/506172

The reverse engineered/parsed data is structured here: https://docs.google.com/spreadsheets/d/1oGyKNfWlnITlZqLPHhwn08_T6jStLcCWGZFltYz7Tyw/edit#gid=0

I plan to implement this binding in my free time the next couple of weeks. Adding it here for tracking and collecting ideas.

Please make sure to have 3.x firmware version of the wi-fi dongle if you want to consume it.

Cheers,
Konstantin

**Comment by coop-git** [comment]
Any progress on this? I might get a WIFI dongle as well to start using it locally.Thanks.

**Comment by theater** [comment]
Hi. Yes. 
There is also an initial binding version posted here that I currently use with 10 seconds refresh interval. I have to check if it's the latest one but you can test with this .jar for sure: https://community.openhab.org/t/solax-binding/146324
Having issues with parsing the persistent data (e.g. the long term consumption, etc). Probably it's not in the place where the guys from home assistant posted it...

**Comment by theater** [comment]
Closed by #14880
