### ISSUE TITLE
[Sonos] 'Sonos Era 100' is not yet a supported model

### ISSUE THREAD

**Issue by dankr3** [openhab/openhab-addons#14802]
## Expected Behavior
System should support the new Sonos devices without any warnings.

## Current Behavior
System throws the following warning in the log:
`2023-04-14 11:40:06.843 [WARN ] [overy.ZonePlayerDiscoveryParticipant] - 'Sonos Era 100' is not yet a supported model, thing type 'sonos:zoneplayer' is considered as default; please open an issue`

## Possible Solution
Please add the new Sonos devices as supported model.
As far as I know the following models are new:
- Sonos Era 100 and
- Sonos Era 300

## Steps to Reproduce (for Bugs)
Add a new Sonos model to your openHAB setup.

## Your Environment
Version used: openHAB is 3.4.3 in Docker

**Comment by lolodomo** [comment]
Can you please check if you have controls for bass/trebble/loudness in the Sonos app for this model ?

**Comment by lolodomo** [comment]
> The Era 100 has options to adjust bass, treble and loudness; speech

Ok, thank you.
