### ISSUE TITLE
[tradfri] Implement trigger on tradfri button push, motion sensor move detection and scene controller button push

### ISSUE THREAD

**Issue by vivienbo** [openhab/openhab-addons#14841]
## Further details

Quite some Home Automation systems now support triggering on Tradfri buttons / motion sensors / scene controlers, however this features is not supported on OpenHAB tradfri binding.

There are probably a couple of additional status information related to these things and missing from the binding other than the trigger.

## Related issues
The following opened issues all refer to this same description which are probably relying on one single solution:
* #9953
* #9204
* #10248 

## Your Environment
* Version used: OpenHAB 3.4.3, org.openhab.binding.tradfri 3.4.3
* Environment: Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)
* Operating System and version Debian GNU/Linux 11 (bullseye)

**Comment by vivienbo** [comment]
After investigation the Tradfri gateway still does not communicate these information through the COAP API hence it is not possible to implement this feature.

Tested on:
* Tradfri firmware 1.19.52
* OH Version: OpenHAB 3.4.3, org.openhab.binding.tradfri 3.4.3
* Environment: Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)
* Operating System and version Debian GNU/Linux 11 (bullseye)

**Comment by lsiepel** [comment]
@vivienbo do you still pursue this scene functionality? It seems to be availabler to the API:
https://github.com/glenndehaan/ikea-tradfri-coap-docs?tab=readme-ov-file#get-a-list-of-all-scenes

**Comment by vivienbo** [comment]
Thanks a lot @lsiepel I will prioritize it in my backlog as it sounds promising.
I just need to finish the first release of another project first (as I need it to cut costs on some of my cloud infra costs) but I'll certainly look into it in the coming months!
