### ISSUE TITLE
[icalendar] doesn't handle all exceptions to recurring events (Google calendar ical)

### ISSUE THREAD

**Issue by mystryx1337** [openhab/openhab-addons#14855]
This Problem seems similar to issue  #9735.

While creating a recurring event and change a single element, this element disappears from the vision of the binding.
[rolandmas](https://github.com/rolandmas) told, that the binding does ignore a single change.
As far as I can see, the event completely disappears at the moment.

### Expected Behavior
Creation of the event: next_start is 2023-04-17 12:00
Make it recurrent daily: next_start is 2023-04-17 12:00
Delete the occurrence of today (2023-04-20): next_start is the day after (2023-04-21)
Edit the 2023 occurrence (in time, example: 2023-04-20): next_start is the changed time

### Current Behavior
Creation of the event: next_start is 2023-04-17 12:00
Make it recurrent dayly: next_start is 2023-04-17 12:00
Delete the occurrence of today (2023-04-20): next_start is the day after (2023-04-21)
Edit the 2023 occurrence: next_start is the day after (here's the bug: the event is gone like deleted)

### Steps to Reproduce (for Bugs)
Use this as an icalendar source:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Test
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20230420T173000
DTEND;TZID=Europe/Berlin:20230420T183000
DTSTAMP:20230423T120830Z
UID:6snafilgr8gsi0nt7q6820mks7@google.com
RECURRENCE-ID;TZID=Europe/Berlin:20230420T170000
CREATED:20230420T074305Z
DESCRIPTION:
LAST-MODIFIED:20230420T074328Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:changed event
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20230417T170000
DTEND;TZID=Europe/Berlin:20230417T180000
RRULE:FREQ=DAILY
DTSTAMP:20230423T120830Z
UID:6snafilgr8gsi0nt7q6820mks7@google.com
CREATED:20230420T074305Z
DESCRIPTION:
LAST-MODIFIED:20230420T074305Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:normal recurring event
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```
Define the appropriate items (at least ...:next_start)
Check the ...:next_start item

### Context
This issue is a problem because I use the calendar for radiator controlling. Changed single events lead to cold rooms.

### Your Environment
Version used: up-to-date OpenHAB 3.4.x, installed from http://dl.bintray.com/openhab/apt-repo2 stable/main
Environment name and version: calendar stored on Google Calendar
Operating System and version: Raspberry Pi OS Buster on Raspberry Pi4

**Comment by daMihe** [comment]
It seems like your example for reproduction was shortened (no `BEGIN:VCALENDAR`). This calendar is not even parseable by icalendar binding. Please upload a reproducible example.

**Comment by daMihe** [comment]
Okay i tried with your provided file but with the changed event tomorrow (edited in texteditor). I can't reproduce the issue as it shows me correctly only the changed instance and does not "loose" it. Also i am not sure whether i fully understand your change. You delete an item and then edit it? I have now just tested it using your provided calendar.

Please also verify if your binding version matches the openHAB version (in openHAB console command `bundle:list`).

**Comment by mystryx1337** [comment]
The binding version matches the openHAB version.

Deleting and changing were just examples to show, that I get the same result, whatever I do with a single event out of a row of recurring events.

When I use the example above the event with DTSTART 20230417T170000 will not be shown when I use Items. Not as calendar items and not as eventfilter items. it is just like i would have deleted that one.

Additionally i tried upgrading to OpenHAB 4 and also tried with a freshly installed raspberry pi.

**Comment by daMihe** [comment]
I'm still not able to reproduce your issue. Please provide a different example, if possible some days in the future so i can debug it "live".

**Comment by borazslo** [comment]
I think that I have the same problem so i try to help you reproduce the issue.

Public calendar: https://calendar.google.com/calendar/embed?src=c_qssbhpdrcj135o533mvm8d2ch4%40group.calendar.google.com&ctz=Europe%2FBudapest

I think that the icalendar binding does not see the event starting at 2020-11-06 07:00 .

OH 4.0.1.-Snapshot

(I do not know any easy method to debug the binding so as to find out which calendar items are seen by the binding. Sorry. Any help is appreciated)
