### ISSUE TITLE
[hue] NUPnP discovery broken

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#14852]
I noticed this in my logs when investigating a problem with devices not being discovered:

```
2023-04-19 21:07:46.717 [DEBUG] [al.discovery.HueBridgeNupnpDiscovery] - Bridge not discovered: Description does not containing the model name:
```

(the rest of the line as reformatted JSON):
```json
{
	"name": "Philips hue",
	"datastoreversion": "149",
	"swversion": "1957113050",
	"apiversion": "1.57.0",
	"mac": "xxx",
	"bridgeid": "xxx",
	"factorynew": false,
	"replacesbridgeid": null,
	"modelid": "BSB002",
	"starterkitid": ""
}
```

My bridge is Hue Bridge 2.1, EAN 8718696511800.

## Expected Behavior
No such log.

## Current Behavior
The bridge is discovered through mDNS.

The log entry is from:
https://github.com/openhab/openhab-addons/blob/c130ca11a28487d995ca6f443bda77a9ea95a9e3/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java#L127-L130

The constant:
https://github.com/openhab/openhab-addons/blob/c130ca11a28487d995ca6f443bda77a9ea95a9e3/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java#L52

notice the capital "H" in "Philips Hue". In my JSON response it's "Philips hue". I have checked that the MAC address in indeed my Hue bridge, not an emulator.

It was changed by #11842 here:
https://github.com/openhab/openhab-addons/pull/11842/files#diff-e4515c27b2f3e638e7180e594d00f7664dcd413a49e811840b14399fdf2e0c6aL56

## Possible Solution

I'm wondering why we have two different methods of discovering bridges:
- mDNS - local discovery
- NUPnP - i.e. through cloud service

Additionally, what does Hue Bridge 1 report back for NUPnP?

Example:
->
`GET https://discovery.meethue.com/`

<-
```json
[
    {
        "id": "xxx",
        "internalipaddress": "192.168.0.251",
        "port": 443
    }
]
```

->
`GET http://192.168.0.251/api/0/config`

<- response?

**Comment by jlaur** [comment]
@lolodomo - perhaps you can help by providing the response for bridge 1? (see last two lines in description, just a single GET request needed)

@cweitkamp - do you remember why you changed "Philips hue" to "Philips Hue" and if you tested NUPnP specifically after this?

Anyone - why cloud discovery when openHAB can use mDNS for local discovery? I understand this can be useful for web apps: https://developers.meethue.com/develop/application-design-guidance/hue-bridge-discovery/

**Comment by andrewfg** [comment]
I'm not sure if this is entirely relevant but Philips / Signify has officially deprecated UPnP discovery. (Actually since some time now). So they may indeed be in process of removing it or "doing stuff" with it. And/or it might be related to their 'work-in-progress' on Matter (which probably uses some kind of cloud based discovery).

https://developers.meethue.com/develop/hue-api-v2/migration-guide-to-the-new-hue-api/
https://developers.meethue.com/develop/application-design-guidance/hue-bridge-discovery/

**Comment by lolodomo** [comment]
https://discovery.meethue.com/ returns `[]`

http://192.168.0.251/api/0/config returns `{"name":"Philips hue","datastoreversion":"59","swversion":"01043155","apiversion":"1.16.0","mac":"xxx","bridgeid":"yyy","factorynew":false,"replacesbridgeid":null,"modelid":"BSB001"}`

**Comment by lolodomo** [comment]
So yes for me too, "hue" is in lowercase.
And I see no hue bridge discovered in my inbox. Even if I have one bridge thing already created, I should probably find one marked as "ignored".

**Comment by jlaur** [comment]
> And I see no hue bridge discovered in my inbox. Even if I have one bridge thing already created, I should probably find one marked as "ignored".

Thanks for confirming that the response for Bridge v1 is the same. I can revert the text comparison so that the cloud discovery will work again. Still, I don't really understand why we need cloud discovery. Is mDNS supported by the old bridge? If not, UPnP still?

**Comment by lolodomo** [comment]
> Still, I don't really understand why we need cloud discovery. Is mDNS supported by the old bridge? If not, UPnP still?

If I correctly understand, the NUPnP discovery is the one using https://discovery.meethue.com/ ? In that case, for a bridge V1, it seems to be useless as it returns an empty JSON !

Regarding mDNS discovery, I have now a big doubt if it even works for a bridge V1. If it worked, I should probably find an entry in my OH inbox for my bridge and it is not the case. I should probably try with nothing setup for hue to confirm that.

**Comment by jlaur** [comment]
> If I correctly understand, the NUPnP discovery is the one using https://discovery.meethue.com/ ?

Yes.

> In that case, for a bridge V1, it seems to be useless as it returns an empty JSON !

It seems cloud services are no longer supported for the old bridge? That would explain it.

https://www.philips-hue.com/en-us/support/legal/end-of-support-policy

_"Since 30 April 2020, no software updates are made available for the Hue Bridge v1 mobile application and compatibility with our online services has been terminated at that time."_

> Regarding mDNS discovery, I have now a big doubt if it even works for a bridge V1. If it worked, I should probably find an entry in my OH inbox for my bridge and it is not the case. I should probably try with nothing setup for hue to confirm that.

I wonder if UPnP is still supported by the old bridge then? We could consider bringing that back in order to support that bridge.

**Comment by lolodomo** [comment]
> > Regarding mDNS discovery, I have now a big doubt if it even works for a bridge V1. If it worked, I should probably find an entry in my OH inbox for my bridge and it is not the case. I should probably try with nothing setup for hue to confirm that.
> 
> I wonder if UPnP is still supported by the old bridge then? We could consider bringing that back in order to support that bridge.

J tried to disable all my hue things and restarted OH. Unfortunately, I have no bridge v1 discovered in my inbox. Either the current code for mDNS discovery is not working with a bridge V1 or this old bridge does not support mDNS.
We should probably consider bringing UPnP discovery back to support the bridge V1.
