### ISSUE TITLE
[deconz] thermostat valve value shows UNDEF - regression from pr #14622

### ISSUE THREAD

**Issue by LukasA83** [openhab/openhab-addons#14867]
Deconz Thermostat things are, starting from 4.0.0.M2, showing the valve value as "UNDEF", when the thermostat is open > 40%.
![grafik](https://user-images.githubusercontent.com/58861945/233709968-2b8d600b-f4e2-48da-b728-5b61d8c76f31.png)

This is a regression introduced by PR #14622. The code expects value 0-100, but deconz delivers 0-255, where 255 means 100% open.
![grafik](https://user-images.githubusercontent.com/58861945/233710832-1cc9fabb-9d32-452f-83ee-a5d041046a16.png)

old code:
`            case CHANNEL_VALVE_POSITION:
                updateQuantityTypeChannel(channelUID, newState.valve, PERCENT, 100.0 / 255);
                break;`
new code:
`            case CHANNEL_VALVE_POSITION -> {
                Integer valve = newState.valve;
                if (valve == null || valve < 0 || valve > 100) {
                    updateState(channelUID, UnDefType.UNDEF);
                } else {
                    updateQuantityTypeChannel(channelUID, valve, PERCENT, 1.0);
                }
            }`

**Comment by J-N-K** [comment]
After a discussion with deconz developers, the correct value is 0-100. This is also what most devices report and the reason why we changed it. A device that reports values above 100 has a broken firmware.

If you are on the latest deconz firmware this should be fixed. If it is not fixed, you need to create a DDF for the device.
