### ISSUE TITLE
[tesla binding] API not responsive to invoking vehicle_config, drive_state, vehicle state: error 404: not found.

### ISSUE THREAD

**Issue by hlemmens** [openhab/openhab-addons#14894]
```
2023-04-28 11:03:55.636 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: vehicle_config
2023-04-28 11:03:55.815 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request vehicle_config: 404: Not Found
2023-04-28 11:03:58.470 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: drive_state
2023-04-28 11:03:58.654 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request drive_state: 404: Not Found
2023-04-28 11:03:59.471 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: vehicle_state
2023-04-28 11:03:59.655 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request vehicle_state: 404: Not Found
2023-04-28 11:04:13.470 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: drive_state
2023-04-28 11:04:13.653 [WARN ] [internal.handler.TeslaAccountHandler] - Reached the maximum number of errors (3) for the current interval (15 seconds)
2023-04-28 11:04:13.660 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request drive_state: 404: Not Found- 
```

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by theater** [comment]
Just wanted to confirm that since today I have the same issue. Probably they have changed some endpoints or the structure of the response... :(

**Comment by theater** [comment]
Probably this is related. Not sure if this repo is used as an API source: https://github.com/timdorr/tesla-api/issues/711

**Comment by humphreysl** [comment]
> <!-2023-04-28 11:03:55.636 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: vehicle_config 2023-04-28 11:03:55.815 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request vehicle_config: 404: Not Found 2023-04-28 11:03:58.470 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: drive_state 2023-04-28 11:03:58.654 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request drive_state: 404: Not Found 2023-04-28 11:03:59.471 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: vehicle_state 2023-04-28 11:03:59.655 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request vehicle_state: 404: Not Found 2023-04-28 11:04:13.470 [DEBUG] [internal.handler.TeslaAccountHandler] - Invoking: drive_state 2023-04-28 11:04:13.653 [WARN ] [internal.handler.TeslaAccountHandler] - Reached the maximum number of errors (3) for the current interval (15 seconds) 2023-04-28 11:04:13.660 [DEBUG] [internal.handler.TeslaAccountHandler] - An error occurred while communicating with the vehicle during request drive_state: 404: Not Found- Provide a general summary of the issue in the _Title_ above -->
> 
> ## Expected Behavior
> ## Current Behavior
> ## Possible Solution
> ## Steps to Reproduce (for Bugs)
> 
> ## Context
> ## Your Environment
> * Version used: (e.g., openHAB and add-on versions)
> * Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
> * Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

I have exactly the same issue as here on my OpenHAB instance. Only started last night (27/4/2023 at 9pm UK time).

**Comment by thekev** [comment]
Another confirmation here. A number of projects are scrambling to fix their implementations today.

**Comment by hlemmens** [comment]
It seems a new endpoint has been created by Tesla. See https://github.com/jonasman/TeslaSwift/issues/138

Anyone able to implement thos in the binding?

**Comment by kaikreuzer** [comment]
I just noticed that issues in the logs as well (didn't see this issue here the past days).
I'll have a look at what I can do - not sure yet, what impact the API changes will have on the functionality of the binding...

**Comment by kaikreuzer** [comment]
I think I managed to fix it and have created https://github.com/openhab/openhab-addons/pull/14922 for it.

**Comment by phuongpham** [comment]
> I think I managed to fix it and have created #14922 for it.

Great! Will this fix work for 3.4.x as well?

**Comment by kaikreuzer** [comment]
Once merged, I will check whether it is feasible to backport it to 3.4.x.

**Comment by kaikreuzer** [comment]
@phuongpham You might want to test the jar that I attached to https://github.com/openhab/openhab-addons/pull/14924.

**Comment by phuongpham** [comment]
> @phuongpham You might want to test the jar that I attached to #14924.

great! I'm testing it now.
Will give you some update tommorow.
thanks for the great job!

**Comment by phuongpham** [comment]
@kaikreuzer ok it has been running for a while now.
Everything looks fine

**Comment by maisun** [comment]
Is the jar only compatible with OH 4 or does it work with 3.4 as well?

**Comment by phuongpham** [comment]
> Is the jar only compatible with OH 4 or does it work with 3.4 as well?

You can download the snapshot for 3.4.x from here https://github.com/openhab/openhab-addons/pull/14924
This one will work with OH 3.4

**Comment by maisun** [comment]
> > Is the jar only compatible with OH 4 or does it work with 3.4 as well?
> 
> You can download the snapshot for 3.4.x from here #14924 This one will work with OH 3.4
> 
> Or just run this command in karaf
> 
> `bundle:update org.openhab.binding.tesla https://github.com/phuongpham/temp/raw/main/org.openhab.binding.tesla-3.4.4-SNAPSHOT.jar `

Thank you! I just download and drop the jar file into add-on folder (before I removed the official Tesla add-on). Everything works again, many thanks for the fix!

**Comment by kojid0** [comment]
First, thank you for fixing the binding! I've installed the jar and it started to work again.
The only thing I have trouble with is channel "shiftstate". It seems to be stuck at "D".
Any one else facing this bug?

**Comment by phuongpham** [comment]
> also for me the channel **eventstamp** and **shiftstare** are not updated with the fixed version. thx for the fast fix :-)

I notice the same. At least everything else working :)

**Comment by kojid0** [comment]
FYI, I created a [new issue](https://github.com/openhab/openhab-addons/issues/14967).
