### ISSUE TITLE
[ipcamera] ONVIF - Not possible to stop "Poll Image"

### ISSUE THREAD

**Issue by tb4jc** [openhab/openhab-addons#14910]
I have two ONVIF ipcameras (TP-Link Tapo C200 and C210) configured in the ipcamera binding, which use the snapshot based streaming.
I don't want to have "Poll Image" enabled all the time with a ffmpeg process giving additional load to my system.
When stopping it, the handler gets communication error in checkCameraConnection() which leads to a restart and activating polling again.
I see the problem in the way, how the connection is checked with the camera.

With some small adapations, I managed to get the connection supervision using the event receive handler.
I will make a pull request.

**Comment by Skinah** [comment]
Thanks for the PR, consider using my suggestion after first testing it if your too busy to look at changing the online/offline detection for your use case. I am happy to accept a workaround and then when you have time to then improve the online offline detection later. More info on this is inside the PR linked to this issue.
