### ISSUE TITLE
[Homematic] New switch Item added from Homematic Binding does not show switch slider in sitemap

### ISSUE THREAD

**Issue by wseifert** [openhab/openhab-addons#14973]
I added a Homematic switch Thing HmIP-PCBS to my openHAB via admin gui, created a coresponding item via .items file as I had done multiple times in the past and added this item in default.sitemap. But the item does not display the switch slider, only the switch state is shown
![grafik](https://github.com/openhab/openhab-addons/assets/16413002/9c63c1d3-de17-49a9-ba54-3724a906d6cf)

I removed item and thing from openHAB, removed the HmIP-PCBS from Homermatic with reset to defaults, recreated it in both worlds but the same result again. No switch slider.

I have multiple switches from same type in Homematic and corresponding things and items in openHAB, all of them created in the same way, all of them have switch slider(s):
![grafik](https://github.com/openhab/openhab-addons/assets/16413002/8a8de1b7-138d-46cb-a5da-d3626cc0f16e)

## Your Environment

* Version used: openHAB 3.4.4 running on Debian GNU/Linux 11 (bullseye) fully patched
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox 113 on Windows 10, Microsoft EDGE on Win10, Firefox on Android

**Comment by lsiepel** [comment]
Can you share the item definition and channel ?

**Comment by wseifert** [comment]
Things definition:

 

[cid]

 

[cid]

 

items definition:

 

Dimmer PoolLight_globalBrightness    "Poolbeleuchtung"   <pool> {channel=
"wled:json:PoolLight:globalBrightness"}

String PoolLight_Playlist            "Playlist"                 {channel=
"wled:json:PoolLight:playlists"}

String PoolLight_Presets             "Presets"                  {channel=
"wled:json:PoolLight:presets"}

String PoolLight_Effect              "Effect"                   {channel=
"wled:segment:PoolLight:fx"}

Dimmer PoolLight_Speed               "Speed"                    {channel=
"wled:segment:PoolLight:speed"}

Dimmer PoolLight_Intensity           "Intensity"                {channel=
"wled:segment:PoolLight:intensity"}

String PoolLight_Palettes            "Palettes"                 {channel=
"wled:segment:PoolLight:palettes"}

Switch PoolLight_Mirror              "Mirror"                   {channel=
"wled:segment:PoolLight:mirror"}

Switch PoolLight_Reverse             "Reverse"                  {channel=
"wled:segment:PoolLight:reverse"}

 

Regards

Werner

Von: lsiepel ***@***.***>
Gesendet: Sonntag, 20. August 2023 22:03
An: openhab/openhab-addons ***@***.***>
Cc: wseifert ***@***.***>; Author ***@***.***>
Betreff: Re: [openhab/openhab-addons] [Homematic] New switch Item added from
Homematic Binding does not show switch slider in sitemap (Issue #14973)

 

Can you share the item definition and channel ?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Das Bild wurde vom
Absender entfernt.Message ID: <openhab/openhab-addons/issues/14973/
***@***.***>

**Comment by lsiepel** [comment]
The attachments are not added to this issue, and the items only seem to hold wled, not homematic

**Comment by wseifert** [comment]
Sorry, wrong item and thing posted, have a second issue with wled. This issue is solved since I updated to OH 4.02.
