### ISSUE TITLE
[Shelly] Shelly 1: Since upgrade to 3.4.4 when linking the input channel to an item it breaks the item state.

### ISSUE THREAD

**Issue by hsjankie** [openhab/openhab-addons#14997]
Hi,
Since upgrading to OH 3.4.4 the shelly binding seems to be working fine for most devices but, when linking the input channel to an item I get a "ClassCastException: null" in the logs, which in turn breaks the model as well as the item pages (Or any page that should display the state of this item).
From what I could see, it seems to be only with the input channel, linking the power channel works.
I also see duplicates of the same shelly device type when adding shelly devices manually, can this be related. (I dont have any other jar's in the classpath for shelly either)

**Comment by markus7017** [comment]
please try latest DEV build
https://community.openhab.org/t/shelly-binding/56862/3311

If problem persists, provide log output, esp. the exception information.
Please report result here

**Comment by markus7017** [comment]
no response
