### ISSUE TITLE
[astro] Documentation missing: sun:phase:name NOON

### ISSUE THREAD

**Issue by Elgin1** [openhab/openhab-addons#15005]
The current documentation is missing that there is a sun phase name "NOON":

> 2023-05-18 13:41:47.307 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SunPhase' changed from DAYLIGHT to NOON
> 2023-05-18 13:42:47.232 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'SunPhase' changed from NOON to DAYLIGHT

It's short but it upset my rule controlling the hall lights in any state other than "DAYLIGHT"...

It would be great if this could be added to the documentation.

Many thanks in advance!

**Comment by clinique** [comment]
Documentation modifications/enhancements can be directly done online. you're welcome to do it.

**Comment by stefan-hoehn** [comment]
@Elgin1 
Can you say what exactly you want to have documented differently and how?
Do you refer to this documentation?  https://www.openhab.org/addons/bindings/astro/ which you can find [here](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.astro/README.md) on github.

**Comment by boehan** [comment]
`MORNING_NIGHT` and `EVENING_NIGHT` seem to be missing as well. I created a PR.
