### ISSUE TITLE
[systeminfo] - Do unlinked channels get updates?

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#15007]
I run openhab 3.4.3 on a system with limited resources.  I have installed the systeminfo package.  My understanding is that this package provides many channelsD, which have different priority - high, medium, and manual.  I do not want to use all channels.

Do channels with medium or high priority consume resources to be updated, if they are not linked to items?

This is unclear from the documentation.  If they do consume periodic resources to be updated, I am going to set the priorities of all unused channels to “manual”.

Thanks for the clarification.

**Comment by mherwege** [comment]
Unlinked channels do not get updates. The scheduler that schedules the updates for high/medium/low priority filters them and doesn't call the refresh for these.
