### ISSUE TITLE
[miio] Add support Roborock S8 Pro Ultra

### ISSUE THREAD

**Issue by marioschouten** [openhab/openhab-addons#15020]
Hi, please add support for the Roborock S8 Pro Ultra.

OH Log message:
``
Mi Device model Unknown Mi IO Device (unknown) identified as: miio:unsupported, thingtype miio:vacuum. Does not matches thingtype miio:unsupported. Unexpected, unless manual override.
``
The device ID of the unit is: 577446476
OH Version: 3.4.3
Firmware version: 4.3.5_1508
Binding version: Installed May 23rd, 2023

Let me know if I can provide any additional information. In the meantime using roborock.vacuum.a70 but keeps throwing above error but seems to work.

Thanks and best regards,

Mario

**Comment by marcelrv** [comment]
Hi @marioschouten 
Can you share the modelId of your vacuum..   (something like the ` roborock.vacuum.a70 `, so not the commercial name`

you can find it in the thing properties liek in the screenshot below
![image](https://github.com/openhab/openhab-addons/assets/5871213/9fde476f-6d62-468b-aad0-53b85a23ab24)
