### ISSUE TITLE
[shelly] Energy channel not available for Shelly EM

### ISSUE THREAD

**Issue by mtraxiot** [openhab/openhab-addons#15036]
* OPENHAB v3.4.4
OS: Linux Ubuntu
I can see MQTT messages with energy and Shelly API documents this output, however I don't see a Channel on the shelly device which captures this data

API doc:
shellies/shellyem-<deviceid>/emeter/<i>/energy energy counter in Watt-minute

MQTT output
shellies/shellyem-##MAC##/emeter/0/energy 325
shellies/shellyem-##MAC##/emeter/0/energy 354
shellies/shellyem-##MAC##/emeter/0/energy 328
shellies/shellyem-##MAC##/emeter/0/energy 324
shellies/shellyem-##MAC##/emeter/0/energy 996
shellies/shellyem-##MAC##/emeter/0/energy 1710
shellies/shellyem-##MAC##/emeter/0/energy 1895

**Comment by markus7017** [comment]
Are you using the Shelly binding, then check latest DEV build
https://community.openhab.org/t/shelly-binding/56862/3311
otherwise I can't help

**Comment by markus7017** [comment]
no response
