### ISSUE TITLE
Translations for next release

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-addons#15037]
We have a lot of addons which have a translation status close to 100%, and for a few we are missing the approvals for the translations.
Since translations are only updated when the status for the plugin in 100% approved, no new updates are included.

For the next release, we should try to finish all almost-complete translations, get them approved and merged.

I can only speak for the German translations, there the first part is almost done now.
Help is needed.

**Comment by lolodomo** [comment]
I will myself monitor French translations and try to finish/validate what is almost finished. 
Already done just before a precedent milestone.

**Comment by florian-h05** [comment]
I have started proof reading and approving translations that are 100% complete but not 100% approved.

**Comment by holgerfriedrich** [comment]
Just to ping everybody watching this issue. We have the 4.0rc1 out, but there are a few add-ons which have 100% translated but lack approval.

I will close this ticket after the 4.0 release, as this is typically ongoing work.....
