### ISSUE TITLE
[shelly] Authentication with Shelly plus 1 not working

### ISSUE THREAD

**Issue by donfranio** [openhab/openhab-addons#15041]
When I connect my Shelly plus 1 to openhab Version 3.4.0-1 (from debian-Package), I get

Status:
OFFLINE
CONFIGURATION_ERROR
Access denied, check user id and password. 

Looking into the tcpdump I see, that the response string in the request is not correctly calculated.
I see something like
```{"id":1339663633,"src":"shellyplus1-de17b98c1a","method":"Shelly.GetConfig","auth":{"username":"admin","nonce":XXX,"cnonce":XXX,"nc":1,"realm":"shellyplus1-XXXX","algorithm":"SHA-256","response":"XXXX","auth_type":"digest"}}```
and an error in the WebUI of Openhab (see above)

When I take the values from this string,
    recalculate the response field as described in the Shelly docu and
    use it in some curl command like
```
 curl -v -X POST -d '<JSON-Object from above with altered response-field>' http://${SHELLY}/rpc
```
I get HTTP 200 and data from the Shelly.

Can you please have a look into this?
Thanks in advance.

**Comment by markus7017** [comment]
I saw this issues with the 1.0 beta firmware, but only with 1 device, others incl Pro series working as expected
which device and firmware are you using?

**Comment by donfranio** [comment]
Hi,

first of all thanks for the effort.

Here is what it said on the bottom right corner of the Web-Frontend of the shelly:
```Shelly Plus1 | Id: 441793AAB1F8 | Firmware: 0.14.1 | Web: 767992a8```

Then I updated the firmware, now it says in the bottom left corner
```Shelly Plus1 441793AAB1F8| 1.0.0-beta5| fc19b072``` and the Time.

Did not do the same analysis as above but again I cannot connect openhab to the device with authentication.

As I tried to point out: It seems like openhab is misbehaving here.

**Comment by mes85** [comment]
I use three Plus2PM devices in cover mode. I have updated one of them to 1.0.0-beta5. The device is now showing the same issue in OpenHAB (latest version available as docker image).

How can I generate useful logs for you to narrow down the issue?
