### ISSUE TITLE
[knx] Console commands do not use UoM

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-addons#15065]
Looking at #15049 there seems to be an issue sending data with UoM from the openHAB console to a KNX installation.

We have defined in item with DPTs 7.007 (time in hours) with textual config. Here are the snippets from ```knx.things``` and ```default.items```:
```        
Type number: t_t_h "t std" [ ga="7.007:10/0/7" ]

Number:Time time_h "T [%.1f h]" {channel="knx:device:ip:test:t_t_h"}
```

Receiving data properly respects UoM and converts data to seconds, which is the representation of time on OH.

Using the OH console to send data, however:

```
openhab> openhab:send time_h "7 s"
Command has been sent successfully.
openhab> openhab:items list time_h
time_h (Type=NumberItem, State=7 s, Label=T, Category=null)
openhab> openhab:send time_h "2 h"
Command has been sent successfully.
openhab> openhab:items list time_h
time_h (Type=NumberItem, State=7200 s, Label=T, Category=null)
openhab> openhab:send time_h "5 kg"
Command has been sent successfully.
openhab> openhab:items list time_h
time_h (Type=NumberItem, State=7200 s, Label=T, Category=null)
openhab> openhab:send time_h 1
Command has been sent successfully.
openhab> openhab:items list time_h
time_h (Type=NumberItem, State=1 s, Label=T, Category=null)

```
The internal state is properly updated for h and s; the wrong unit "kg" is ignored. The last command without unit uses default for time (s).

But the knx addon sends out the data in all 4 cases (even the one with wrong unit). It used the plain number without any conversion. See the bus log:
```
A_Group.write 00 07
A_Group.write 00 02
A_Group.write 00 05
A_Group.write 00 01
```

## Expected Behavior

Data converted according to UoM, data on the bus is in hours.

## Steps to Reproduce (for Bugs)

see above

## Context

UoM

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

 4.0.0-SNAPSHOT - Build 3487, custom build of KNX addon, based on current main branch

**Comment by J-N-K** [comment]
Core has more strict type checking. As a result the KNX channel (which reports to be `Number` which is a plain number without unit) only receives a `DecimalType` (unit stripped). 

I'll have look how this can be handled. It probably also affects HTTP and MQTT which use a similar concept.
