### ISSUE TITLE
[knx] Changing DPT in text config requires restart to take effect

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-addons#15066]
## Expected Behavior

Like all other parameters configured in *.things file, changed DPTs should be effective after the things file is reloaded.

## Current Behavior

Restart of OH is necessary for a DPT change to become effective.
See also #15049.
Changing other parameters in the things file works, e.g. after changing a PA, the device is immediately polled. Changing the GA also works immediately.

## Steps to Reproduce (for Bugs)

Change DPT in things file. Send a command to the linked item. With enabled trace you will see the DPT in the log.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

4.0.0-SNAPSHOT - Build 3487, custom build of KNX addon, based on current main branch

**Comment by J-N-K** [comment]
Works fine for me with latest code.

**Comment by holgerfriedrich** [comment]
Just checked with my PR #15134, which shows all GAs with DPT mapping.
It seems this issue is resolved.
