### ISSUE TITLE
[fronius] powerflowchannelpakku upside down description

### ISSUE THREAD

**Issue by marcquark** [openhab/openhab-addons#15074]
## Expected Behavior
According to the documentation, the powerflowchannelpakku Battery Power channel is positive (+) when the battery is charging, negative (-) when the battery is discharging

## Current Behavior
The value is negative (-) when battery is charging and positive (+) when it's discharging, the opposite of what the docs say. I've checked the API response when accessing the inverter's webinterface via browser. Battery is currently charging, number returned from API is negative. So i assume it's a bug in the documentation.

## Possible Solution
If others observe the same behaviour, i can simply submit a PR to correct the documentation. If it depends on model, software version or other factors, might have to make a more complicated distinction.

## Steps to Reproduce (for Bugs)
Add a Fronius Bridge and Fronius Inverter Thing, create an Item to display the power and link it with the powerflowchannelpakku Channel

## Context
n/a

## Your Environment
OpenHAB 3.4.4 (running in Docker - Alpine image)
Fronius Binding 3.4.4

Inverter is a Fronius Symo Hybrid 5.0-3-S with a 63A Smart Meter and software version 1.25.2-1 (info from the webinterface - if there's other things i need to gather, i'd be happy to get instructions where to look)

**Comment by jimtng** [comment]
The documentation is wrong. 

Basically `+` is when power is flowing in and `-` is when power is flowing out. 
So when charging, power is flowing out of the inverter and into the battery, so it should be `-`.
