### ISSUE TITLE
[electroluxair] Cannot connect to Electrolux API (COMMUNICATION_ERROR)

### ISSUE THREAD

**Issue by kwn** [openhab/openhab-addons#15136]
Electrolux Delta API bridge suddenly stopped working and seems to be down for the last couple of weeks. Actually, I'm not sure if the Delta API is down, or did rather Electrolux introduce some BC breaking changes. This might be related to Electrolux retiring the Wellbeing App.

I tried to reconfigure and re-add Electrolux Delta API "thing" but no luck. I'm sure I provide the right username and password.

Calling the original author: @jannegpriv 

## Expected Behavior
Electrolux Delta API should connect to Electrolux API and allow to control my Elextrolux Air Pure A9 device.

## Current Behavior
After adding Electrolux Delta API it displays status of `Offline` and error message saying `COMMUNICATION_ERROR`.

Logs from `events.log`:
```
2023-06-25 20:41:52.895 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'electroluxair:api:649f361c19' changed from UNINITIALIZED to INITIALIZING
2023-06-25 20:41:52.897 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'electroluxair:api:649f361c19' changed from INITIALIZING to UNKNOWN
2023-06-25 20:41:53.007 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'electroluxair:api:649f361c19' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR)
```

<img width="1263" alt="Screenshot 2023-06-25 at 20 22 54" src="https://github.com/openhab/openhab-addons/assets/3968616/739259f0-88ba-4428-84ca-f03549b23de5">

## Possible Solution
Unfortunately I have no clue how to fix it. I guess reverse-engineering Electrolux API and the new unified Electrolux mobile app is the only way to go.

## Steps to Reproduce (for Bugs)
Prerequisite: Ensure that ElectroluxAIR binding is installed. 
1. Go to things -> add thing
2. Select ElectroluxAIR binding
3. Select Electrolux Delta API
4. Enter credentials in the bottom of the form
5. Click "save"

## Context
Missing Electrolux Delta API bridge does not allow to control my Electrolux Air Pure A9 device which I'm using as a temperature monitor.

## Your Environment
* Version used: 3.4.4
* Environment name and version: Java 11, Chrome 114
* Operating System and version: Ubuntu 22.04 LTS

**Comment by jannegpriv** [comment]
I can confirm the issue, the API seems to have been changed.

I will try to update to the new API, keep you posted!

**Comment by kwn** [comment]
Thanks @jannegpriv 

Do you have any hints on how to track requests to the Electrolux API from the new mobile? Should I use some proxy or something?

How did you reverse-engineer the Wellbeing app?

**Comment by jannegpriv** [comment]
I have now created a [jar-file](https://drive.google.com/file/d/1SYk800YV0epnPfmbSvvlfVqmg0MX_7Km/view?usp=sharing) that would be great if you could test @kwn.

**Comment by kwn** [comment]
Hey @jannegpriv 

Sorry for the late response. Thank you for fixing it (and adding the additional channels). I'll take a look at it this weekend.

I saw that @jlaur closed your pull request. Perhaps it's worth re-opening? You'd only need to re target it to the `main` branch.

**Comment by jlaur** [comment]
> Perhaps it's worth re-opening? You'd only need to re target it to the `main` branch. Once you re-open it please ping me, I'll review the PR as well.

@jannegpriv already created #15187, so you can have a look already. 🙂 There are now some 4.0-specific changes, so a manual backport will be needed to fix this in 3.4.x as well.

**Comment by kwn** [comment]
Hey @jlaur 

I tested the updated version and it works well! Thank you for fixing it!!

**Comment by jlaur** [comment]
> I tested the updated version and it works well! Thank you for fixing it!!

I'm glad to hear that it works well! But you need to thank @jannegpriv since he was the one fixing it. 😄

**Comment by kwn** [comment]
Ah apologies. Of course I meant to thank @jannegpriv!! 😄 Thank you Jan!!
