### ISSUE TITLE
[knx] Unable to write KNX 5.001 values 

### ISSUE THREAD

**Issue by frenchc** [openhab/openhab-addons#15131]
I am using a Zennio KLIC-DD v3 and a Zennio KLIC-DI v2 to control Daikin air conditioners. 

Most of the Zennio objects can be controlled by openhab KNX Binding, apart from 5.001 objects such as fan percentage. I am able to read the current state, but unable to set the state. Changing the state will never be propagated to KNX.

I use dimmer for both the channel and the item. 

Example channel configuration (5.001 is redundant, I know).

   id: FanPercentage
    channelTypeUID: knx:dimmer
    label: Fan Percentage
    description: ""
    configuration:
      position: 5.001:0/0/20+<0/0/21

In log level debug I found out that sending an update will fail in CommunicationManager line 420.
 "Received event '{}' ({}) could not be converted to any type accepted by item '{}' ({})",

I turned on remote debugging and found the following details.

1. Sending an item update using DSL will send a PercentType to CommunicationManager. 
2. In CommunicationManager#toAcceptedType the channel returns String as acceptedItemType
3. Since String does not match my originalType (PercentType) the method toAcceptedType will return null.
4. The item update will be ignored, the log statement above will be logged.

I altered via hot code replacement the method toAcceptedType, and set acceptedItemType to Dimmer for my FanPercentage update. Now the update will be carried out, but fails due to the empty implementation of SystemDefaultProfile#onStateUpdateFromItem. I changed my DSL statement to sendCommand ... and now it works.

Using number type channel/item for 5.001 won't get updates too, so I assume it behaves as written above.

My openhab knowledge is pretty much limited. I think it is safe to say that

1. CommunicationManager get Dimmer instead of String for acceptedItemType.
2. CommunicationManager#420 should not log the statement in level debug but warn.3. 

I am using 3.4.4 at the moment (running within docker).

**Comment by frenchc** [comment]
Channel during runtime

<img width="785" alt="Screenshot 2023-06-24 at 01 27 17" src="https://github.com/openhab/openhab-addons/assets/900937/e08f6809-155a-4a2a-a53e-28862e1f4cbb">

**Comment by J-N-K** [comment]
Please check if this is still the case with 4.0.0 snapshot. The binding has undergone some serious refactoring that can't be backported.

**Comment by frenchc** [comment]
Tested with current 4.0.0 snapshot. Works out of the box.

I will not upgrade in the short term. What is your recommendation then? Worst case I will add an altered CommunicationManager that just fixes the mismatch till I have time to upgrade to 4.0.x stable.

**Comment by J-N-K** [comment]
I have no other suggestion than upgrading to OH4, sorry. The changes can't be backported to OH3 because they make use of Java 17 features.
