### ISSUE TITLE
[androidtv] Add CLI for PIN process

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15143]
As requested in #14282 by @jlaur -

Recommend adding a CLI interface for the PIN process similar to the BoschIndego binding.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.boschindego/src/main/java/org/openhab/binding/boschindego/internal/console/BoschIndegoCommandExtension.java

**Comment by morph166955** [comment]
@jlaur I notice in your example that you apply the command to the bridge. I don't think that will work here for people with multiple local devices (like me).  Is there a mechanism where we can specify the thingId on the cli and match against it?

**Comment by mlobstein** [comment]
Take a look at this one also... It is almost exactly the same use case to trigger a PIN display and submit it back: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.vizio/src/main/java/org/openhab/binding/vizio/internal/console/VizioCommandExtension.java

**Comment by morph166955** [comment]
Thank you @mlobstein !  This is exactly the logic I was looking for.

**Comment by morph166955** [comment]
I decided to take a slightly different approach on this.  Instead of locking this to the pin, I basically made the interpreter send to any channel.  This serves three purposes.  1) It resolves this feature request by enabling pin on the command line.  2) It allows users to also send keypress/keycode from the command line for testing.  3) It allows me to work a little easier with the debug channels when doing testing.

PR coming forthwith.
