### ISSUE TITLE
[hydrawise] Binding stops updating

### ISSUE THREAD

**Issue by BillGOH** [openhab/openhab-addons#15170]
I am using openHAB 3.4.4 on openHABian with the hydrawise binding. Since some time, the binding stops updating. I can easily see that, because the last contact item does not change any more.

There is no error message in the logs, the account and controller thing always remain online. The binding is working again for a short period of time if I disable/enable the account thing.

Thanks for any help!

**Comment by digitaldan** [comment]
Thanks for reporting this.  Yeah, i can see this happening as  well, i'll take a look.
