### ISSUE TITLE
[Miio] Dreame L10S Ultra - Add support

### ISSUE THREAD

**Issue by francemgit** [openhab/openhab-addons#15217]
As suggested by @marcelrv this issue to request to add official support to Dreame L10S Ultra.

All the channed found via unsupported channel method seems to work properly although some mapping need to be adjusted (e.g. many channel can be mapped as switch but having custom values for ON and OFF)

Probably my fault but was not able to configura a Map channel....

Please find attacched :

- test-dreame.vacuum.r2228o-20230619-232217.txt
- info_DreameL10sUltra.json renamed .txt

[test-dreame.vacuum.r2228o-20230619-232217.txt](https://github.com/openhab/openhab-addons/files/11996024/test-dreame.vacuum.r2228o-20230619-232217.txt)
[info_DreameL10sUltra.json.txt](https://github.com/openhab/openhab-addons/files/11996033/info_DreameL10sUltra.json.txt)

**Comment by marcelrv** [comment]
Note: map channel indeed will not be supported.
Unless someone will contribute map decoding for the dreame models.. (or donate such a vacuum to me...)

**Comment by francemgit** [comment]
Thanks for your support! I'll test the binding as soon as available in a milestone release.

> Note: map channel indeed will not be supported. Unless someone will contribute map decoding for the dreame models.. (or donate such a vacuum to me...)

I can try to give my contribution, If you tell me how to work on map decoding I'll give it a try!!

**Comment by marcelrv** [comment]
> I can try to give my contribution, If you tell me how to work on map decoding I'll give it a try!

Here you can see some of my starting points for the OH decoder... I made first an offline version to understand the file format and what the fields mean before bringing it to openhab.
https://github.com/marcelrv/XiaomiRobotVacuumProtocol/tree/master/RRMapFile

So my steps
1. try to understand the communication between the app and the cloud for getting the map.
e.g. my using MITM proxy or maybe easier the vevs (hacked) mihome app

2. find the way to download the map data in the first place and save it to a file.

3. Compare the files with the image you see and see if you can somehow recognize structures & patterns
4. build simple offline decoder as I did to see if it works.  

What could help a lot: I think there is already an implementation done by https://github.com/PiotrMachowski/
so you can use that as guide...  There might be other implementations, that can help.
Also downloading the mihome plugin for the dreame and look at the source can help a lot (PM me in the forum if needed)

**Comment by marcelrv** [comment]
note. once you manage to save the map files to a file and you have the screenshots from the map in the mihome app at the same time I might be able to help as well (if my time permits...).
