### ISSUE TITLE
[InfluxDB persistence] defined strategies in influxdb.persist are not working after restart

### ISSUE THREAD

**Issue by JoWutal** [openhab/openhab-addons#15236]
Hi Community

I'm facing an issue with the InfluxDB persistence.
Defined in the influxdb.persist are the following strategies:

`Strategies {
    everyMinute : "0 * * * * ?"
    everyHour : "0 0 * * * ?"
    everyDay : "0 0 0 * * ?"
    every2Minutes : "0 */2 * ? * *"
}`

I am also using everyChange which is working correctly after reboot.
But the other strategies are ignored until I touch the .persist file. Then the strategies are loading and working.

I would expect all strategies to be loaded after restart of OH as it was working with OH3.
Behavior is reproducible after every reboot.

Maybe there are issues with registering the cron for the persistence service?

Workaround atm is to touch the .persist file after reboot.

![Screenshot 2023-07-14 201433](https://github.com/openhab/openhab-addons/assets/119458551/401830c0-ea01-4f1f-87a6-7b4d5160f706)
OH restart at about 13:30, .persist file touched at about 20:05.
As you can see the persistence itself is collecting data after reboot as expected, but only with the everyChange strategy.

Any ideas or thoughts?
Every hint is appreciated.

Thanks in advance
JoWuTal

* openHAB 4.0.0.M4, InfluxDB persistence add-on 4.0.0.M4, InfluxDB v1 Database
* latest openHABian 1.8 (openhabian-pi-raspios64-202306251519) fresh install with working config from OH3

**Comment by J-N-K** [comment]
Can you check if this also happens for MapDB if you install that?

**Comment by JoWutal** [comment]
I'll try that and come back to you.

**Comment by JoWutal** [comment]
Installed MapDB and did the test.
Issue is not observed with MapDB
BUT:
Since installing MapDB the issue with InfluxDB is solved too.

I'll test it in the next days and will report my findings.

Thanks so far.

**Comment by JoWutal** [comment]
Just removed MapDB and InfluxDB is still working correctly with everyMinute after restart...
Strange thing

**Comment by JoWutal** [comment]
Update:
I forgot to restore my original influxdb.persist file.
For the test with MapDB I commented out every restoreOnStartup strategy.

With the original file the issue is there again: After restart of OH the strategies are not loaded; after touching the file they are working.

Seems to be the restoreOnStartup in the influxdb.persist.

Maybe someone can try to reproduce?

Thanks in advance

**Comment by J-N-K** [comment]
Can you please share the full file?

**Comment by JoWutal** [comment]
influxdb.persist with the issue occuring:
`Strategies {
    everyMinute : "0 * * * * ?"
    everyHour : "0 0 * * * ?"
    everyDay : "0 0 0 * * ?"
    every2Minutes : "0 */2 * ? * *"
}

Items {
    Strom_aktuellerVerbrauch, Strom_aktuellerVerbrauch_ohne_PV, Strom_aktuellerVerbrauch_ohne_WP : strategy = everyChange, restoreOnStartup
    DG_Wetterstation_Helligkeit_Ost, DG_Wetterstation_Helligkeit_Sued, DG_Wetterstation_Helligkeit_West : strategy = everyChange, restoreOnStartup
    Waermepumpe_aktuellerVerbrauch, Waschmaschine_aktuellerVerbrauch, Trockner_aktuellerVerbrauch, Tiefkuehler_aktuellerVerbrauch, DG_Wetterstation_Windgeschwindigkeit : strategy = everyChange, everyMinute, restoreOnStartup
    Wasser_aktuellerVerbrauch, Lueftungsanlage_aktuellerVerbrauch : strategy = everyChange, everyMinute, restoreOnStartup
    WPM_Aussentemperatur, gEG_Temperaturen_Ist*, gOG_Temperaturen_Ist*, gKG_Temperaturen_Ist*, gStellwerte*, gSollwerte* : strategy = everyChange, everyMinute, restoreOnStartup
    gSileno* : strategy = everyChange, everyHour
    Strom_Zaehlerstand, Strom_EinspeiseZaehlerstand, Strom_Tagesverbrauch, Strom_Tagesverbrauch_ohne_WP, Waermepumpe_Zaehlerstand, Waermepumpe_Tagesverbrauch, Waschmaschine_Zaehlerstand, Waschmaschine_Tagesverbrauch, Trockner_Zaehlerstand, Trockner_Tagesverbrauch, Tiefkuehler_Zaehlerstand, Tiefkuehler_Tagesverbrauch, Lueftungsanlage_Zaehlerstand, Lueftungsanlage_Tagesverbrauch, Wasser_Zaehlerstand, Wasser_Tagesverbrauch : strategy = everyDay
    gPVHistData* : strategy = everyChange
    inverter1BatStateCharge, inverter1BatTemp, inverter1PreBatCharge, inverter1PreBatDischarge : strategy = everyChange, everyMinute
    inverter1BatCharge, inverter1BatDischarge : strategy = everyDay
    gBYD* : strategy = everyChange
}`

influxdb.persist without issues, but no restoreOnStartup:
`Strategies {
    everyMinute : "0 * * * * ?"
    everyHour : "0 0 * * * ?"
    everyDay : "0 0 0 * * ?"
    every2Minutes : "0 */2 * ? * *"
}

Items {
    Strom_aktuellerVerbrauch, Strom_aktuellerVerbrauch_ohne_PV, Strom_aktuellerVerbrauch_ohne_WP : strategy = everyChange //, restoreOnStartup
    DG_Wetterstation_Helligkeit_Ost, DG_Wetterstation_Helligkeit_Sued, DG_Wetterstation_Helligkeit_West : strategy = everyChange //, restoreOnStartup
    Waermepumpe_aktuellerVerbrauch, Waschmaschine_aktuellerVerbrauch, Trockner_aktuellerVerbrauch, Tiefkuehler_aktuellerVerbrauch, DG_Wetterstation_Windgeschwindigkeit : strategy = everyChange, everyMinute //, restoreOnStartup
    Wasser_aktuellerVerbrauch, Lueftungsanlage_aktuellerVerbrauch : strategy = everyChange, everyMinute //, restoreOnStartup
    WPM_Aussentemperatur, gEG_Temperaturen_Ist*, gOG_Temperaturen_Ist*, gKG_Temperaturen_Ist*, gStellwerte*, gSollwerte* : strategy = everyChange, everyMinute //, restoreOnStartup
    gSileno* : strategy = everyChange, everyHour
    Strom_Zaehlerstand, Strom_EinspeiseZaehlerstand, Strom_Tagesverbrauch, Strom_Tagesverbrauch_ohne_WP, Waermepumpe_Zaehlerstand, Waermepumpe_Tagesverbrauch, Waschmaschine_Zaehlerstand, Waschmaschine_Tagesverbrauch, Trockner_Zaehlerstand, Trockner_Tagesverbrauch, Tiefkuehler_Zaehlerstand, Tiefkuehler_Tagesverbrauch, Lueftungsanlage_Zaehlerstand, Lueftungsanlage_Tagesverbrauch, Wasser_Zaehlerstand, Wasser_Tagesverbrauch : strategy = everyDay
    gPVHistData* : strategy = everyChange
    inverter1BatStateCharge, inverter1BatTemp, inverter1PreBatCharge, inverter1PreBatDischarge : strategy = everyChange, everyMinute
    inverter1BatCharge, inverter1BatDischarge : strategy = everyDay
    gBYD* : strategy = everyChange
}`

**Comment by J-N-K** [comment]
I just tried and it works for me. Can you please go to the API Explorer, `persistence`, `GET /persistence/{serviceId}`, set `serviceId` to `influxdb` and "Execute"? What is the result?

**Comment by JoWutal** [comment]
Here is the result.
I checked and can confirm that the result is exactly the same after restart and after touching the file. But still not working as expected after restart.

`{`
`  "serviceId": "influxdb",`
`  "configs": [`
`    {`
`      "items": [`
`        "Strom_aktuellerVerbrauch",`
`        "Strom_aktuellerVerbrauch_ohne_PV",`
`        "Strom_aktuellerVerbrauch_ohne_WP"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "restoreOnStartup"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "DG_Wetterstation_Helligkeit_Ost",`
`        "DG_Wetterstation_Helligkeit_Sued",`
`        "DG_Wetterstation_Helligkeit_West"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "restoreOnStartup"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "Waermepumpe_aktuellerVerbrauch",`
`        "Waschmaschine_aktuellerVerbrauch",`
`        "Trockner_aktuellerVerbrauch",`
`        "Tiefkuehler_aktuellerVerbrauch",`
`        "DG_Wetterstation_Windgeschwindigkeit"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "everyMinute",`
`        "restoreOnStartup"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "Wasser_aktuellerVerbrauch",`
`        "Lueftungsanlage_aktuellerVerbrauch"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "everyMinute",`
`        "restoreOnStartup"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "WPM_Aussentemperatur",`
`        "gEG_Temperaturen_Ist*",`
`        "gOG_Temperaturen_Ist*",`
`        "gKG_Temperaturen_Ist*",`
`        "gStellwerte*",`
`        "gSollwerte*"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "everyMinute",`
`        "restoreOnStartup"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "gSileno*"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "everyHour"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "Strom_Zaehlerstand",`
`        "Strom_EinspeiseZaehlerstand",`
`        "Strom_Tagesverbrauch",`
`        "Strom_Tagesverbrauch_ohne_WP",`
`        "Waermepumpe_Zaehlerstand",`
`        "Waermepumpe_Tagesverbrauch",`
`        "Waschmaschine_Zaehlerstand",`
`        "Waschmaschine_Tagesverbrauch",`
`        "Trockner_Zaehlerstand",`
`        "Trockner_Tagesverbrauch",`
`        "Tiefkuehler_Zaehlerstand",`
`        "Tiefkuehler_Tagesverbrauch",`
`        "Lueftungsanlage_Zaehlerstand",`
`        "Lueftungsanlage_Tagesverbrauch",`
`        "Wasser_Zaehlerstand",`
`        "Wasser_Tagesverbrauch"`
`      ],`
`      "strategies": [`
`        "everyDay"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "gPVHistData*"`
`      ],`
`      "strategies": [`
`        "everyChange"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "inverter1BatStateCharge",`
`        "inverter1BatTemp",`
`        "inverter1PreBatCharge",`
`        "inverter1PreBatDischarge"`
`      ],`
`      "strategies": [`
`        "everyChange",`
`        "everyMinute"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "inverter1BatCharge",`
`        "inverter1BatDischarge"`
`      ],`
`      "strategies": [`
`        "everyDay"`
`      ],`
`      "filters": []`
`    },`
`    {`
`      "items": [`
`        "gBYD*"`
`      ],`
`      "strategies": [`
`        "everyChange"`
`      ],`
`      "filters": []`
`    }`
`  ],`
`  "defaults": [],`
`  "cronStrategies": [`
`    {`
`      "name": "everyMinute",`
`      "cronExpression": "0 * * * * ?"`
`    },`
`    {`
`      "name": "everyHour",`
`      "cronExpression": "0 0 * * * ?"`
`    },`
`    {`
`      "name": "everyDay",`
`      "cronExpression": "0 0 0 * * ?"`
`    },`
`    {`
`      "name": "every2Minutes",`
`      "cronExpression": "0 */2 * ? * *"`
`    }`
`  ],`
`  "thresholdFilters": [],`
`  "timeFilters": [],`
`  "equalsFilters": [],`
`  "includeFilters": [],`
`  "editable": false`
}

**Comment by J-N-K** [comment]
Can you please enable DEBUG logging for `org.openhab.core.persistence.internal.PersistenceManager`? Do you see messages like `Scheduled strategy {} with cron expression {} for service {}`?

**Comment by JoWutal** [comment]
Nothing about Scheduled strategy during restart.
But the first time i noticed this:

`2023-07-15 17:47:03.261 [WARN ] [sistence.internal.PersistenceManager] - Querying persistence service 'influxdb' takes more than 5000ms.`
`2023-07-15 17:47:03.263 [ERROR] [sistence.internal.PersistenceManager] - bundle org.openhab.core.persistence:4.0.0.M4 (208)[org.openhab.core.persistence.internal.PersistenceManager(233)] : The addPersistenceService method has thrown an exception`
`java.lang.NullPointerException: Cannot invoke "java.lang.Iterable.iterator()" because the return value of "org.openhab.core.persistence.QueryablePersistenceService.query(org.openhab.core.persistence.FilterCriteria)" is null`
`	at org.openhab.core.persistence.internal.PersistenceManager.restoreItemStateIfNeeded(PersistenceManager.java:267) ~[?:?]`
`	at org.openhab.core.persistence.internal.PersistenceManager.lambda$15(PersistenceManager.java:287) ~[?:?]`
`	at org.openhab.core.persistence.internal.PersistenceManager.startEventHandling(PersistenceManager.java:287) ~[?:?]`
`	at org.openhab.core.persistence.internal.PersistenceManager.addPersistenceService(PersistenceManager.java:143) ~[?:?]`
`	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]`
`	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]`
`	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]`
`	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:937) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:874) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:262) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]`
`	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:937) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:874) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:141) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:262) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:500) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:752) ~[?:?]`
`	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]`
`	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217) ~[org.eclipse.osgi-3.18.0.jar:?]`
`	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136) ~[org.eclipse.osgi-3.18.0.jar:?]`

After touching the file:

`2023-07-15 17:51:33.134 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'influxdb.persist'`
`2023-07-15 17:51:33.206 [DEBUG] [sistence.internal.PersistenceManager] - Removed scheduled cron job for persistence service 'influxdb'`
`2023-07-15 17:51:33.215 [DEBUG] [sistence.internal.PersistenceManager] - Scheduled strategy everyMinute with cron expression 0 * * * * ? for service influxdb`
`2023-07-15 17:51:33.218 [DEBUG] [sistence.internal.PersistenceManager] - Scheduled strategy everyHour with cron expression 0 0 * * * ? for service influxdb`
`2023-07-15 17:51:33.221 [DEBUG] [sistence.internal.PersistenceManager] - Scheduled strategy everyDay with cron expression 0 0 0 * * ? for service influxdb`
`2023-07-15 17:51:33.225 [DEBUG] [sistence.internal.PersistenceManager] - Scheduled strategy every2Minutes with cron expression 0 */2 * ? * * for service influxdb`
