### ISSUE TITLE
[rrd4j] Persistence stops working after some time

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-addons#15237]
This appears to be a regression in the latest Milestone.

After some time (it seems like it is every full hour) charts aren't loading anymore. When I restart openHAB there's a flat line that begins for example at 15:00 in the charts, so I believe no data was written since then, even though the values changed later aswell (I can see that in the event log). That indicates, that the RRD4J persistance service I am using apparently completely stopped working, it can't be queried anymore and doesn't write data anymore.

My persistence config looks like this:

```
Strategies {
	// for rrd charts, we need a cron strategy
	everyTenSeconds : "0/10 * * * * ?"
	everyMinute : "0 * * * * ?"
	everyHour   : "0 0 * * * ?"
	everyDay    : "0 0 0 * * ?"
}
Items {
	PersistenceLog*		: strategy = everyTenSeconds, everyMinute, everyHour, everyDay, restoreOnStartup
	RRDPersistence*		: strategy = everyTenSeconds, everyMinute, everyHour, everyDay, restoreOnStartup
}
```

Could it be that everyMinute and everyHour try to update at the same time, causing this issue? It was working fine on Milestone 3, so I believe this should be adressed before the release.

**Comment by Flole998** [comment]
I can check it once the new build is available. I have fixed my configuration now to avoid those double-saves which also fixed the issue mostly.

**Comment by Bitrider11** [comment]
I think I have the same or equal problem. After update from openHAB 4.0.0.M4 to 4.0.0.M5 Persistence rrd4j stops working. It looks like, that there is a problem with the database of the rrd4j datafile. Header is corrupt or there is an incompatibility with the database file.

Error message when openHAB starts:
2023-07-19 20:47:54.027 [ERROR] [d4j.internal.RRD4jPersistenceService] - Could not create rrd4j database file '/var/lib/openhab/persistence/rrd4j/WC_Day4_Night_TemperatureWindChill.rrd': Invalid file header. File [/var/lib/openhab/persistence/rrd4j/WC_Day4_Night_TemperatureWindChill.rrd] is not a RRD4J RRD file

**Comment by jlaur** [comment]
I also had a problem with invalid headers in **all** .rrd files shortly after installing 4.0M5. Unfortunately I destroyed all evidence by deleting them all, and it hasn't reappeared. I thought I might had cut the power from the Raspberry Pi before completing a shutdown, but thinking again, probably this was not the case.

**Comment by Flole998** [comment]
That's not the same issue I was having. I caused the issue by modifying the persistence strategy in an attempt to prevent double (or triple) persisting every hour and I think the rrd4j file format is based on that, so it was complaining about the structure no longer being correct.

The "real" issue I was having was, that rrd4j files were opened again and again leaking file descriptors in certain cases until openHAB eventually ran out of available file descriptors/hit the limit allowed. That appears to be resolved now, so this can be closed.

**Comment by mhett** [comment]
In which openhab version this issue (missing close() commands) has been fixed / will be fixed?
