### ISSUE TITLE
[OpenSprinkler]- Program Channel not displaying properly OS Firmware v2.2

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-addons#15260]
## Expected Behavior

With OpenSprinkler Firmware v2.19 Program names were properly displayed by the binding (3.4.x,4.0.x).  With Firmware v2.20 this is no longer the case.

## Current Behavior

Since updating Opensprinkler firmware from v2.19 to v2.2 the program channel no longer displays correctly.  Instead of the Program Name, 415.0] is displayed for each/all Programs.  From reviewing the API documentation for each version of the firmware, there appears to have been a change in JSON structure for how Programs are stored, so it appears as though the JSOn is no longer being parsed correctly.
 These examples were taken directly from the API Docs.

v2.2
Example Return:
{“nprogs”:3, “nboards”:1, “mnp”:40, “mnst”:4, “pnsize”:32,“pd”:[[3,127,0,[480,2,240,0],[0,2700,0,2700,0,0,0,0],“Summer”,[0,33,**415]**], [2,9,0,[120,0,300,0],[0,3720,0,0,0,0,0,0],“Fall Prog”,[0,33,**415]**],[195,16,0,[1150,-1,-1,-1],[0,0,0,0,0,0,64800,0],“Pipe”,[1,67,**415]**]]}

v2.19
Example Return​:
{“nprogs”:3, “nboards”:1, “mnp”:40, “mnst”:4, “pnsize”:32,“pd”:[[3,127,0,[480,2,240,0],[0,2700,0,2700,0,0,0,0],“Summer”], [2,9,0,[120,0,300,0],[0,3720,0,0,0,0,0,0],“Fall Prog”],[67,16,0,[1150,-1,-1,-1],[0,0,0,0,0,0,64800,0],“Pipe”]]}
## Steps to Reproduce (for Bugs)

1.
2.

## Context

OpenSprinkler Programs can no longer be differentiated and selected from OpenHAB UI.  No way to tell one program from thenext as they all have the same, incorrect, name.  **415.0]**

## Your Environment

 Running OpenHAB 4.0Mx in a Docker container on a Linux Server.  Same issue exists running OpenHAB 3.4.3 in Docker.

**Comment by Skinah** [comment]
A jar should be built shortly which it would be great if you can test it and report back. The TRACE level log should give helpful info if it does not work for you so please provide that if its not fixed. Works here on my setup.
