### ISSUE TITLE
[hue] Parallel PUT commands cause bridge to fail

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#15322]
### Problem

PR #15169 fixed (among other things) an issue where the bridge could get confused if multiple PUT requests were made in parallel over multiple HTTP2 streams on the same session. But there is a closely related problem that was not solved in that PR -- namely that the bridge can also get confused if a PUT request is made in parallel with one or more GET requests.

### Solution

The binding shall continue to allow multiple parallel GET requests. But if a PUT request is made, the call shall be synchronized so that the request does not start until all other open GET and PUT calls have returned.

**Comment by jlaur** [comment]
@andrewfg - out of curiosity, which symptoms does the bridge expose when it gets "confused"? I assume this can also happen when using other integrations (like the Hue app) at the same time?

**Comment by andrewfg** [comment]
"Confused" is when the Hue Bridge responds with an HTML message instead of XML. The message says something like "no lighting found". It seems to happen when the Bridge is asked to do too many things at the same time.
