### ISSUE TITLE
[sonnen] batteryFeedIn, batteryCharging, ... description in Watt is not matching type Number:Energy

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-addons#15365]
batteryFeedIn, batteryCharging, batteryDischarging, consumption, gridFeedIn, gridConsumption are providing Power units expressed in Watt. However the binding sets them up as Number:Energy. 

## Expected Behavior
Provide power units as type Number:Power

## Current Behavior
Power units are provided as Number:Energy. Documentation is also wrong.

**Comment by lsiepel** [comment]
You probably mean it is expressed in watt/hour.
If that is true for all mentioned channels, it won't be that hard to fix. You need any help with creating a fix?

**Comment by timbms** [comment]
Energy is expressed in Joule = Watt second or for larger amounts in Wh = Watt hour
Power is expressed in W

**Comment by lochmueller** [comment]
Hey @timbms ,
Hey @lsiepel ,

I can confirm this issue. Some notes...
"batteryFeedIn" is not found in the binding. I think it is wrong/old in the documentation?! 


Affected channels are:

- batteryCharging
- batteryDischarging (Found twice in the table of the README.md?!)
- consumption
- gridFeedIn
- gridConsumption
- solarProduction

I think the wrong type is part of this configuration, right? https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.sonnen/src/main/resources/OH-INF/thing/thing-types.xml 

Should I send a PR, and adapt the thing-types.xml & README.md?
Internally the channels are already created with "Power" instead with "Energy": https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.sonnen/src/main/java/org/openhab/binding/sonnen/internal/SonnenHandler.java#L237

I am no Java developer, but I can send a PR to fix documentation and XML configuration?!

Regards,
Tim

**Comment by lsiepel** [comment]
If you want to submit the PR, i'm able to assist if needed.

**Comment by lochmueller** [comment]
Hey @lsiepel thank you. 
I try my first PR... I hope I got feedback, if there are any problems. 👍 
Regards,
Tim

**Comment by timbms** [comment]
> I can confirm this issue. Some notes... "batteryFeedIn" is not found in the binding. I think it is wrong/old in the documentation?!
> 
You are certainly right. I took reference to the documentation.
