### ISSUE TITLE
[twitter] rename to [x]

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#15370]
Don't know if it lasts, but Twitter has become X.

This also impacts the openHAB binding. For now the URL's endpoint etc. don't seem to change. But the documentation, logo's, binding labels, descriptions etc. should be updated. I can prepare a PR to fix some labels etc., but i also wonder if the binding itself and/or namespaces should be updated. 
I would opt to first limit the update to labels and docs, but @openhab/add-ons-maintainers WDYT?

cc: @computergeek1507 as codeowner

**Comment by kaikreuzer** [comment]
For me, it still feels too early for that change - I'd rather wait on what might further happen wrt the name. Should be good enough to do the change towards the end of this year, just before 4.1 is released.
