### ISSUE TITLE
[shelly] Improve devices discovery for protected devices

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#15399]
For now the binding discovers devices dynamically. If the are password protected and the credentials do not match the defaults from the binding config the thing gets created using thing type shellydevice. When the user then enters the correct credentials in the thing config the thing type is changed, but shellydevice is still referenced in the thing uid.

This has been improved to use the information from /shelly and create the corresponding correct thing type (not shellydevice, which is still supported for backward compatibility)

**Comment by lolodomo** [comment]
Closed by #15898
