### ISSUE TITLE
[sonyprojector] Ability to send cursor/key commands

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15409]
I currently use the Sony Projector binding for my VW285.  I would like to use it to replace the IR remote completely.  Currently missing is the ability to send commands like up/down/left/right/enter/menu/info/etc. which exist on the remote.  Feature request would be a channel that could either receive documented keys (e.g. KEY_UP, KEY_DOWN, etc) or some sort of channel to send raw keycodes if they are documented somewhere.  This is helpful for moving around OSD menus, adjusting zoom/focus, etc.

**Comment by lolodomo** [comment]
I will have to reopen an old protocol manual to check if such commands are available. 

Is everything available in the binding working well as expected with your model? If not, I can try to tune the binding to match precisely your model.

**Comment by morph166955** [comment]
Much appreciated. If you have the spec I can give a shot at the PR since I can test it directly. 

I haven't had any issues that I can recall. That said I mostly just use power and input day to day.

**Comment by morph166955** [comment]
I'm not sure if it's the same protocol, but I found... 

https://pro.sony/s3/2018/07/05140342/Sony_Protocol-Manual_Supported-Command-List_1st-Edition.pdf

Section 2.3 seems to indicate a command called "key" which looks like it does exactly what I'm looking for.  Thoughts?

**Comment by lolodomo** [comment]
No this is not the right documentation, a different protocol for other projectors.

But good news, I found in the Sony docs I was able to download in the past what you would like and I can even tell you that the method to send IR code to the device is already implemented in the binding. It is used to power on or off the device in certain circumstances.
So this would be easy to add (just a new channel with command options). I will probably propose only keys that do not match already available settings.

**Comment by morph166955** [comment]
That's perfect.  If I'm looking at the code right it's just a different hex code for each IR button?  Could you do one that covers the main one and a second channel that would just forward the hex codes for those that have corner cases outside that?

**Comment by lolodomo** [comment]
Or I can finally embed all IR codes.

**Comment by morph166955** [comment]
That'd work too. Let me know if I can do anything to help. Greatly appreciated.

**Comment by morph166955** [comment]
I don't mind doing the leg work on this to get it in and tested, I just need a copy of the manual to use as a reference.

**Comment by lolodomo** [comment]
Be patient, I will provide something.

**Comment by morph166955** [comment]
Sounds good. Was just offering to help, not trying to rush ya.
