### ISSUE TITLE
[shelly]  Support for Plus-Pro Range extender

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#15425]
The Plus/Pro series offer the so-called Range Extender. If enabled the gateway device acts as a proxy for other Shellys using WiFi (not the BLU ones, they use the BLU Gateway feature also supported by the binding).

The Range Extender could be enabled under the AP settings of the device. When activated an AP is offered to other Plus/Pro Shellys. You could add connect those linked devices by selecting the AP name of the primary Shelly. It's strongly recommended to protect the AP with a password of proper complexity.

Once the linked device is connected, the primary Shelly creates a dynamic port forward, so you could connect ro both (or even more) with
- ip to the primary device and
- ip:port to the linked devices (each linked device gets its own port)

The binding will support
- Regular things (as usual)
- Linked devices addressed through the primary device
- and discovery of linked devices by reading the list of connects AP clients and getting the port information.

Linked devices will show up in the Inbox and can be manGed as usual.

The device channel group gets a new channel, which indicates the primary device serving this device. And for the primary device a channel indicating the number of linked devices.

The mechanism itself gets active when range extender is enabled in the device settings and  one or more linked devices are detected.

**Comment by markus7017** [comment]
implemented

**Comment by lsiepel** [comment]
Will be available in 4.2 https://github.com/openhab/openhab-addons/pull/16419
