### ISSUE TITLE
[ChatGPT] Binding any more than one channel fails

### ISSUE THREAD

**Issue by AJErazzor** [openhab/openhab-addons#15436]
creating a second channel for a ChatGPT thing doesnt work
item.sendCommand() resutls in 

[ERROR] [ding.chatgpt.internal.ChatGPTHandler] - ChatGPT request resulted in HTTP 400 with message: Bad Request

First channel works

**Comment by holgerfriedrich** [comment]
Could you try to change all channel settings and save the channe config again?
Could be related to #15451.

**Comment by lsiepel** [comment]
Closed by mentioned PR
