### ISSUE TITLE
[mqtt.homie] Unsettable boolean should be discovered as Contact

### ISSUE THREAD

**Issue by Jollerprutt** [openhab/openhab-addons#15439]
The Homie convention specifies whether a boolean is settable/controllable or not, therefore the auto discovery in openhab should convert it to the correct item types.

## Expected Behavior

A non-settable boolean should be discovered as a Contact rather than a Switch.

## Current Behavior

Right now a boolean is always turned into a Switch item, independently of the "settable" property flag.

## Possible Solution

Determine Switch/Contact based on settable flag.
PR opened. https://github.com/openhab/openhab-addons/pull/15440

## Steps to Reproduce (for Bugs)

1. Add a homie node with a boolean value
2. Add the node thing from the inbox
3. See the created channels

## Context

Has been discussed [here](https://community.openhab.org/t/mqtt-autodiscovery-default-type-for-contact-switch-channels/115526).
All homie door and window sensors are now switches and require extra mapping to use.
Also I think the Semantic model is affected as OpenState shouldn't (?) be applied to a Switch.

## Your Environment

* openHAB 4.0.1
* Openhabian on rpi4.

**Comment by ccutrer** [comment]
I'm not sure we want to do this. There is plenty of precedent for unsettable boolean channels in openHAB to be represented as switches. The Zwave binding and binary_sensors from the homeassistant bindings being examples. Just because something isn't settable doesn't mean "open/close" makes sense for it. For example, if it's representing a button that's pressed, but you obviously can't set the state of the button. The alternative would be setting an autoupdate policy on the channel to VETO any updates, so that you can't actually send a command to the channel and have the item unexpectedly update.

**Comment by Jollerprutt** [comment]
Sure, but the opposite is true too. Just because something is settable doesn’t mean ON/OFF makes sense. Right now there is no way to get a contact item from homie in openHAB, with this PR you get a choice. You can still define an unsettable item as settable in homie if you want it to appear as a switch in OH.

**Comment by ccutrer** [comment]
There certainly is a way to link a non-settable Boolean property to an openHAB ContactItem. Use a profile. It should be trivial using a MAP transform.

And I would not call changing the Homie device to make a Boolean property settable as "having a choice." The device may be outside of your control.

While I definitely see your point, I think it's a toss up on if a non-settable Boolean property should be a switch or a contact. And given that it's already a Switch, it would be a breaking change to make it a contact, and definitely "break" some other subset of users. So without a compelling reason or a way to determine "this should be a contact", I don't think it's worth introducing that breaking change.

**Comment by ccutrer** [comment]
So I did a bit of digging, and indeed the Homie binding already sets a state description of read only, and an AutoUpdate policy of VETO, so it's not possible to actually send a command to non-settable, retained, boolean property.
