### ISSUE TITLE
[shelly] OH 4.0 crashes when installing the shelly binding

### ISSUE THREAD

**Issue by MrHenky93** [openhab/openhab-addons#15432]
I just updated to OH 4.0.0 stable. When I try to install the shelly binding, the UI of OH seems to crash. It keeps hanging on this screen:
![image](https://github.com/openhab/openhab-addons/assets/98335574/4838841e-f6e1-4158-aeb9-78cabf7a66a3)

After a little while the UI comes back again, but the binding is uninstalled. 

Normal logs don't show anything unusual. I've tried DEBUG logging, but I really don't know where to start with that.

For the record: I've tried installing several other bindings and they all install just fine. All the bindings I had in OH3 before also work fine. Any thoughts for a solution?

I'm running openhabian on an Ubuntu VM.

**Comment by markus7017** [comment]
Please try with latest DEV build


[4.1-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar?raw=true) | [4.0.-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.0.5-SNAPSHOT.jar?raw=true) | [3.4.5-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.5-SNAPSHOT.jar?raw=true) | [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) | **[READMEbeta](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)** 
[Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) -  [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server) | [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de)

---

Note: The DEV build is always newer than the version in the official Distro or Milestone builds. Current development is based on 4.1-SNAPSHOT, **4.0.x and 3.4.x might be outdated**.

**Comment by tik5io** [comment]
Hi Markus7017
I had same trouble (OH4, Shelly binding cause crash after install)

I have tried with 4.1DEV : similar crash from my side (OH4.10)

My error log contain confirmation install was OK, and just after: 
```
Shelly Manager started at http(s)://192.168.1.18:8080/shelly/manager
[re.xml.osgi.XmlDocumentBundleTracker] - The XML document '/OH-INF/addon/addon.xml' in module 'org.openhab.binding.shelly' could not be parsed:
```
I hope this can be usefull !

**Comment by markus7017** [comment]
this was related to the packaging of the dev binding
