### ISSUE TITLE
[Enocean] Humidity and temperature readings incorrect in 4.0.2

### ISSUE THREAD

**Issue by diRk262** [openhab/openhab-addons#15458]
## Expected Behavior
The readings for temperature and humidity with EEP A5-10-12 should be correct.
 
## Current Behavior
The readings are incorrect. Please see the drop in temperature and non changing humidity readings after updating from latest openocean version 3.2.0.0 to official Enocean binding 4.0.2.
![IMG_3182](https://github.com/openhab/openhab-addons/assets/76136884/de109d4f-8b4d-4e2a-b344-0a6ca1ccabb7)

## Possible Solution
Merge all changes from the latest openocean version 3.2.0.0 to to official enocean binding. The wrong profile was fixed years ago but never merged into the official binding:

https://github.com/fruggy83/openocean/issues/106

**Comment by jlaur** [comment]
FYI @fruggy83

**Comment by diRk262** [comment]
Maybe @lsiepel can help here? I saw you are pretty active with this binding.

**Comment by fruggy83** [comment]
I will do the "cherry pick" this week.

**Comment by fruggy83** [comment]
@diRk262 I have merged the changes from openocean into the official binding. Tested successfully with my room panels (EEP A5_10_06).

**Comment by diRk262** [comment]
@fruggy83 
Thank you for merging the changes into the official binding. I will test and report asap.
Will the changes be available in 4.0.3 or are they already available in snapshot 4.1?
Btw:
Will be the openocean version compatible with future openhab versions or is 3.x the last compatible version?

**Comment by fruggy83** [comment]
@diRk262 I guess it will be merged into the next version and should be contained in one of the next snapshot builds. If I find some time, I will update the openocean binding to be compatible with the current openhab version. I still have some plans and ideas for new features and openocean is my  playground.

I just mentioned EEP A5-10-06 because it is the only EEP of this family which is used by one of my panels. I have updated the whole EEP family (including A5-10-12) 😉

**Comment by diRk262** [comment]
@fruggy83 
This sounds great, thanks 👍🏼
I am curious to see these new features.
There is no smarthome solution with such a great enocean compatibility like opehab with your binding! 

Like I already offered you some time ago, if you need someone who will support you testing some new features just let me know. I got a lot of different devices. 
My F4HK14 and bidi (A5-10-06) room panels would also be happy to get some smart connection wirh openhab 😉
