### ISSUE TITLE
[hue] taurus_7455 (undocumented) resource type

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#15468]
Philips seems to have introduced a new resource type `taurus_7455` (see JSON below).

This is most probably an unintended mistake by a Hue developer with the Taurus birth sign and a birthday on 1974-05-05 so we assume it will go away. Currently no action is proposed..

See https://developers.meethue.com/forum/t/taurus-7455-wtf/6944

```
{
    "id": "dummy11-not2-my333-res4-id5555555555",
    "id_v1": "/lights/18",
    "product_data": {
        "model_id": "LTA001",
        "manufacturer_name": "Signify Netherlands B.V.",
        "product_name": "Hue ambiance lamp",
        "product_archetype": "sultan_bulb",
        "certified": true,
        "software_version": "1.104.2",
        "hardware_platform_type": "100b-112"
    },
    "metadata": {
        "name": "Table Lamp E",
        "archetype": "table_shade"
    },
    "identify": {
    },
    "services": [
        {
            "rid": "dummy11-not2-my333-res4-id5555555555",
            "rtype": "light"
        },
        {
            "rid": "dummy11-not2-my333-res4-id5555555555",
            "rtype": "zigbee_connectivity"
        },
        {
            "rid": "dummy11-not2-my333-res4-id5555555555",
            "rtype": "taurus_7455"
        }
    ],
    "type": "device"
}
```

It manifests in the OH log with the following entries..

```
2023-08-20 15:39:13.711 [DEBUG] [e.internal.handler.Clip2ThingHandler] - dummy11-not2-my333-res4-id5555555555 -> updateResource() from resource id:dummy11-not2-my333-res4-id5555555555, type:error
2023-08-20 15:39:13.712 [DEBUG] [.internal.handler.Clip2BridgeHandler] - getResources() id:dummy11-not2-my333-res4-id5555555555, type:error
```

**Comment by stpe** [comment]
Can confirm. I also unexpectedly discovered `taurus_7455` as a type appearing in `/eventstream/` on my bridge.

**Comment by jlaur** [comment]
Still present in firmware 1.59.1959194040.

**Comment by andrewfg** [comment]
@jlaur 4yi: I sent an email to `philipshuedev@signify.com` today to report this. I will let you know when/if there is any response.

**Comment by aaronp613** [comment]
I am not apart of this community but i was diffing the iOS app this morning and found this, not sure if its helpful for you guys or not. It's from today's iOS update of the Hue app. 

	<key>taurus.creatingArea.please.wait</key>
	<string>Please wait</string>
	<key>taurus.creatingArea.subtitle</key>
	<string>Make sure nobody (including pets!) is in the area.</string>
	<key>taurus.creatingArea.title</key>
	<string>Creating area...</string>
	<key>taurus.creatingArea.unableToCreateTaurusFailure</key>
	<string>Unable to create Taurus!</string>
	<key>taurus.failedFetching.banner.title</key>
	<string>Something went wrong while fetching Tauruses. Reopen this taurus page to try again.</string>
	<key>taurus.leaveRoom.subtitle</key>
	<string>Make sure nobody (including pets!) is in the area before continuing.</string>
	<key>taurus.leaveRoom.title</key>
	<string>Leave the area</string>
	<key>taurus.lightsSelection.subtitle</key>
	<string>Your shape can be made up of 3 or 4 lights. Only compatible lights in %s are listed.</string>
	<key>taurus.lightsSelection.title</key>
	<string>Choose lights</string>
	<key>taurus.lightsSelection.tooManyLightsFailureMessage</key>
	<string>Maximum of 4 lights reached</string>
	<key>taurus.overview.empty.createAreaButton.title</key>
	<string>Create area</string>
	<key>taurus.overview.empty.howDoesItWorkButton.title</key>
	<string>How does it work?</string>
	<key>taurus.overview.empty.subtitle</key>
	<string>Select a room and create Taurus area to get started.</string>
	<key>taurus.overview.empty.title</key>
	<string>Create Taurus area</string>
	<key>taurus.overview.title</key>
	<string>Taurus</string>
	<string>Tauruses</string>
	<key>taurus.roomSelection.room.subtitle</key>
	<string>%s compatible lights</string>
	<key>taurus.roomSelection.selectRoom.subtitle.alreadyInUse</key>
	<string>Already in use</string>
	<key>taurus.roomSelection.subtitle</key>
	<string>Taurus area requires at least 3 compatible lights in a Room. Outdoor spaces are not recommended.</string>
	<key>taurus.roomSelection.title</key>
	<string>Where do you want to create Taurus area?</string>
</dict>
</plist>

**Comment by jlaur** [comment]
Upgraded from 1.60.1960062030 to 1.60.1960149090, and it's still there. Since it looks like it's not going away, maybe we should log this a debug rather than warn? Unsupported resources are not causing the binding to break, so logging warnings each time something like this is introduced seems a bit excessive in terms of logging?
```
2023-10-23 21:58:44.604 [WARN ] [.hue.internal.connection.Clip2Bridge] - Resource '00000000-0000-0000-0000-000000000000' type 'Error (taurus_7455)' unknown => GET aborted
```

**Comment by andrewfg** [comment]
^
Agreed.
