### ISSUE TITLE
[hue] Error handling improvements

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#15460]
Placeholder for some minor issues found.

## Status description missing

This was observed in my logs:
```
2023-08-19 13:43:23.638 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge-api2:home' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): An unexpected exception null occurred.
```

When looking in the UI:
- OFFLINE
- COMMUNICATION_ERROR
- An unexpected exception {} occurred.

One issue seems to be a problem related to I18N. This works:
```ini
offline.api2.comm-error.exception = An unexpected exception occurred: {0}
```

This doesn't:

https://github.com/openhab/openhab-addons/blob/a293fc8fd99e469dcaaaf89deaf66dbaeda6123d/bundles/org.openhab.binding.hue/src/main/resources/OH-INF/i18n/hue.properties#L235

This doesn't work either:
```ini
offline.api2.comm-error.exception = An unexpected exception '{0}' occurred.
```

It seems the placeholder variable needs to be at the end. Perhaps this feature is some kind of pure luck and is not designed to be used like this at all. I would need to investigate further.

## Incomplete HTTP status code check

Another issue is here:
https://github.com/openhab/openhab-addons/blob/52c657ff414edbaf55ef9aa5198fbe6c8f645337/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java#L986

This will usually happen when HTML content is returned. Most likely there is a HTTP status code that would be more interesting than the MIME type. However, only a few are explicitly handled, and the code is not returned:

https://github.com/openhab/openhab-addons/blob/52c657ff414edbaf55ef9aa5198fbe6c8f645337/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/connection/Clip2Bridge.java#L154-L159

I'm not sure what would be the best implementation for this, but a straight-forward one would be:
- Add instance variable `int httpStatus` to `BaseStreamListenerAdapter`.
- Add method `int getHttpStatus()` for returning it.
- Set the variable just before the `switch` statement above.
- Check it in `putResource` and make sure to log it and also use the HTTP status rather than MIME type for determining if the call was successful. We can still check MIME type even for code 200 for being safe.

**Comment by andrewfg** [comment]
> also use the HTTP status rather than mimetype for determining if the call was successful. We can still check MIME type even for code 200 for being safe.

Regardless of whether the response is valid JSON or an HTML error message, the payload is returned with HTTP 200 OK, so the ContentType is the only way to tell if something was wrong.

**Comment by andrewfg** [comment]
@jlaur the Hue API documentation (e.g. see link below) gives all the error codes that might potentially be reported for each type of call i.e. 400, 401, 403, 404, 405, 429, 500, 503, 507 (maybe others too). In reality I only ever saw 401, 403 and of course 200..

https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_light__id__put

**Comment by jlaur** [comment]
> Regardless of whether the response is valid JSON or an HTML error message, the payload is returned with HTTP 200 OK, so the ContentType is the only way to tell if something was wrong.

OK, I didn't know that because the HTTP error code is not logged. 🙂 Anyway, it doesn't contradict what I wrote:

> > We can still check MIME type even for code 200 for being safe.

So my suggestion would be to check error code first and react appropriately on that. For 200 we would then move ahead and check `Content-Type` like now, since nginx seems to react in ways not taken into consideration in the documentation. And last, even for `application/json` we should anticipate that the deserialization can fail if we receive an unexpected payload. This part is probably already handled correctly.

> the Hue API documentation (e.g. see link below) gives all the error codes that might potentially be reported for each type of call i.e. 400, 401, 403, 404, 405, 429, 500, 503, 507 (maybe others too). In reality I only ever saw 401, 403 and of course 200..

Thanks for the link. I briefly checked and they claim `application/json` for all those codes, which you have proven wrong.

**Comment by andrewfg** [comment]
> they claim application/json for all those codes

Yes. Although I think that strictly the HTML error is not an API error but rather a default fallback error of the bridge when the API is not running. If you open the HTML in a browser it displays a simple web page saying "sorry no lighting found" (something like that).

**Comment by andrewfg** [comment]
> my suggestion would be to check error code first and react appropriately on that

@jlaur as you know from #15350 I am doing some work to improve the stability of `Clip2Bridge` in relation to GO_AWAY and re-starting the session. And I have already added some code to my work in progress to read and check the HTTP status code. So you don't need to write anything for this check yourself.

**Comment by andrewfg** [comment]
> It seems the placeholder variable needs to be at the end. Perhaps this feature is some kind of pure luck and is not designed to be used like this at all. I would need to investigate further.

@jlaur can I leave this one up to you?

**Comment by jlaur** [comment]
> > It seems the placeholder variable needs to be at the end. Perhaps this feature is some kind of pure luck and is not designed to be used like this at all. I would need to investigate further.
> 
> @jlaur can I leave this one up to you?

Yes. In the meantime I found the documentation:
https://www.openhab.org/javadoc/latest/org/openhab/core/thing/i18n/thingstatusinfoi18nlocalizationservice

I'm currently looking into the implementation. This **should** work:
```ini
offline.api2.comm-error.exception = An unexpected exception '{0}' occurred.
```

when used like this:
```java
updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR,
        "@text/offline.api2.comm-error.exception [\"" + e.getMessage() + "\"]");
```

However, for some reason I'm seeing this in my tests:

![image](https://github.com/openhab/openhab-addons/assets/19519842/4a123bcd-8132-4b52-8f50-e0c49daf3a52)

**Comment by jlaur** [comment]
> I'm currently looking into the implementation. This **should** work:

Okay, I found the issue. The position is not the problem, the surrounding apostrophes are.

**Comment by jlaur** [comment]
Small note - log from this morning:
```
2023-08-30 06:53:12.430 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge-api2:home' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): An unexpected exception 'Error sending request' occurred.
2023-08-30 07:53:10.830 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'hue:bridge-api2:home' changed from OFFLINE (COMMUNICATION_ERROR): An unexpected exception 'Error sending request' occurred. to ONLINE
```

This raises two questions:
- What caused it to go offline?
- Why was it offline almost a full hour?

I will try to add better logging for the "Error sending request" part in my own build to get more information the next time it happens. And also have a look at the code regarding reconnect logic. If any of this justifies a new issue (and/or PR), I will then create that as a result.

**Comment by andrewfg** [comment]
^
I am pretty sure that this was related to the GO_AWAY issue; after wrongly handling a GO_AWAY the bridge would get into a bad state that would take time to recover from; and as we have fixed that issue then this issue should probably no longer occur..

**Comment by jlaur** [comment]
> and as we have fixed that issue then this issue should probably no longer occur.

It did.
