### ISSUE TITLE
[smaenergymeter] Incomplete German localization

### ISSUE THREAD

**Issue by chkpnt** [openhab/openhab-addons#15499]
The German localization of smaenergymeter is incomplete, so when adding items from the thing, it's a mix of German and English for the user:

<img width="741" alt="grafik" src="https://github.com/openhab/openhab-addons/assets/1956979/9a0dbb58-961f-4299-9291-813fe02da4ce">

I'm shortly filing a PR.

**Comment by lsiepel** [comment]
Some translations are missing. You can add translations by Crowdin. For reference: 
https://www.openhab.org/docs/developer/utils/i18n.html#managing-translations
