### ISSUE TITLE
openHAB Cloud no longer appears in Settings

### ISSUE THREAD

**Issue by EnziinSystem** [openhab/openhab-addons#15517]
My environment:

- openHAB 4.0.1 and 4.0.2
- OpenJDK Runtime Environment Zulu17.44+15-CA (build 17.0.8+7-LTS)
- Raspberry OS 64-bit

After I installed openHAB Cloud Connector, it no longer appears in Settings.

Same issue with InfluxDB persistence addon.

![OpenhabCloud](https://github.com/openhab/openhab-addons/assets/25495466/8ea4c22d-7569-4eb1-93a7-5119b2fd1238)

![Setting](https://github.com/openhab/openhab-addons/assets/25495466/5c19a4f7-b712-4e23-8235-450ff59da20a)

**Comment by vidia** [comment]
I am also seeing the same behavior on OpenHab 4.0.2 installed via OpenHabian. This behavior started after upgrading from version 3. I have restarted the system already just in case, and I have tried to reinstall the addon but the behavior remains the same.

`java --version`: 
openjdk 17.0.7 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Raspbian-1deb11u1rpt1)
OpenJDK Client VM (build 17.0.7+7-Raspbian-1deb11u1rpt1, mixed mode, emulated-client)

**Comment by wborn** [comment]
It got removed with https://github.com/openhab/openhab-webui/pull/1891.
But there is https://github.com/openhab/openhab-webui/pull/1997 to bring it back in some form.

Until then, just click on the settings gear to open the settings:

![settings](https://github.com/openhab/openhab-addons/assets/12213581/3b749e3e-b25b-41d0-bf86-b8cc1f35188b)

**Comment by EnziinSystem** [comment]
> It got removed with [openhab/openhab-webui#1891](https://github.com/openhab/openhab-webui/pull/1891). But there is [openhab/openhab-webui#1997](https://github.com/openhab/openhab-webui/pull/1997) to bring it back in some form.
> 
> Until then, just click on the settings gear to open the settings:
> 
> ![settings](https://user-images.githubusercontent.com/12213581/264002220-3b749e3e-b25b-41d0-bf86-b8cc1f35188b.png)

This is really a problem, for openHab Cloud we can follow the steps as you said.

However, for InfluxDB Persistence addon it doesn't appear in Settings > Persistence and I don't know what to do.

![store](https://github.com/openhab/openhab-addons/assets/25495466/c5804a8f-21c3-4917-80ae-fd2e7f4afda9)

**Comment by EnziinSystem** [comment]
It seems that the openHAB Cloud Connector has been abandoned in the version 4.0.2, I have configured it with UUID and Secret identity but always get the message:

"Your openHAB is not online. Please check if your installation is running or recheck the openHAB settings in your account."

(https://myopenhab.org)

Note that I have successfully done this for openHab 3 versions.

This is an important feature and cannot be arbitrarily removed. If a smart home system doesn't have the ability to remotely control it over the internet, it doesn't make any sense.

Thanks.

**Comment by wborn** [comment]
Let's close this issue now it got fixed with openhab/openhab-webui#1997.
