### ISSUE TITLE
[mercedesme] does not work anymore, service stopped since August 31, 2023 by Mercedes Developers Program

### ISSUE THREAD

**Issue by clown-m** [openhab/openhab-addons#15527]
## Expected Behavior
Mercedes Me Binding gaves information about Battery Soc, Range, Window and Door status etc.

## Current Behavior
Does not work anymore, account is not longer "ACTIVE" state.

The Callback gives me the following messages:

Call Parameters
{}
Configured scopes
openid
offline_access
mb:vehicle:mbdata:payasyoudrive
mb:vehicle:mbdata:vehiclestatus
mb:vehicle:mbdata:vehiclelock
mb:vehicle:mbdata:evstatus

Get your access token for openHAB MercedesMe Binding
[Start Authorization]

Answer:
{
    "error": "invalid_client",
    "error_description": "Client is not in ACTIVE state"
}

## Possible Solution
Mercedes offers in the news that the service is canceled !!

BringYourOwnCar products will be discontinued
Since June 2020, we have been offering you the opportunity to access selected data from your own Mercedes-Benz vehicle with the #BringYourOwnCar initiative.

During this time, the underlying technology has changed significantly and the BYOCAR infrastructure no longer meets our current technical requirements. Therefore, we have to shut down all BYOCAR data products by August 31, 2023. Due to technical conditions, we will start the stepwise sundown on 28.08.2023 already.

We thank all users for their commitment to BYOCAR in the past. Of course we are working on a new solution to experiment with your own Mercedes-Benz and will keep you informed via this news section and our newsletter.

## Context
Is there any other chance to get the data from, is there a new version of the Binding in work or already ready?

## Your Environment

* Version openHAB 4.0.2-1
* Environment Virtual Synology Environment
* Operating System and version Debian Bullseye

**Comment by lsiepel** [comment]
This was fixed by https://github.com/openhab/openhab-addons/pull/15628 and released in openHAB 4.2.0
