### ISSUE TITLE
[remoteopenhab] Image type item is not updated to issuing remote openHAB-server

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-addons#15532]
When a remote oh-server ("remote") publishes an Image item to a local oh-server ("central"), a remote Image type item is not updated ("push" use case Not OK), while item is updated flawlessly when central server publishes its items to remote server, with remote server linking to its item ("pull" use case OK).

## Expected Behavior
A local-oh Image item should be pushed to remote-oh server, just as e.g. Switch or Number items do. Remoteopenhab connection initiated and maintained by central server.

## Current Behavior
I have a local Image item on central oh server, receiving images from ftpupload binding from local webcam.
Image item receives updates frequently:
`Item 'webcamimage' changed from raw type (image/jpeg): 25832 bytes to raw type (image/jpeg): 28033 bytes`
A remote oh server at another family member, to receive that same image by using remoteopenhab binding. 
Central server has remote server Thing configured, remote receiving item appears as channel, uses follow-profile on central webcamimage item:

- Remote openHAB server:

```
Image webcamimagepush "Central Webcam push"
```

- Central openHAB server:

```
Bridge remoteopenhab:server:remote "Remote openHAB" [ host="myopenhab.org", port=443, useHttps=true, trustedCertificate=true, username="<login>", password="<pw>", token="oh.remoteopenhab.rL3j1...Y9xA" ]
```

```
Image webcamimage "Central Webcam" { channel="ftpupload:imagereceiver:ftpbilder:webcam", channel="remoteopenhab:server:remote:webcamimagepush"  [profile="system:follow"]}
```

The above doesn't work as expected. A controversial connection was created, pull use case, which is working OK.

- Remote openHAB server:

```
Bridge remoteopenhab:server:central "Central openHAB" [ host="myopenhab.org", port=443, useHttps=true, trustedCertificate=true, username="<login-y>", password="<login-y>", token="oh.oh.S9a...YWg" ]
```
```
Image webcamimagepull "Central Webcam pull"	{ channel="remoteopenhab:server:central:webcamimage" }
Image webcamimagepush "Central Webcam push"
```
But: remote oh should not have access to all central oh items, so it's not wanted to raise remoteopenhab thing on remote server, as it discloses all central items, >1,800.
Goal is to have remote oh thing on central server, push Image content to remote server. This works for e.g. Switch or Number items.

In main UI on local server I see both (Image) channel links updating, but content (state) is not transferred to remote server. Remote item webcamimagepush stays on NULL (push not OK).
In main UI on remote server with remoteopenhab set up to connect to central server, Image item webcamimagepull is easily updated on any change (pull OK).

Central DSL rule, triggered on central webcamimage change, to postUpdate or sendCommand on remote item webcamimagepush didn't succeed as well, same behaviour.

On both sides default log doesn't show any suspects, as this issue is transparent to oh. The image data transfer inside remoteopenhab binding seems to be unidirectional only.

## Your Environment
* Version used: openHAB 4.0.2 + bindings 4.0.2, behaviour was identical on 3.4.5
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): default
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): PiOS bullseye, default openhabian
* HW: Raspi4-4GB on central and remote sites

**Comment by lolodomo** [comment]
I have the strange feeling you did not understand the principles of this binding. 
Maybe you should read again the introduction in the documention. 

Commands are supported in only one direction (from local to remote) and state updates only in the other direction (from remote to local). 
The principles are the same whatever the type of items, but keep in mind that an image item accepts no command. So state updates to your local server will never be transferred to your remote server. The reverse is true.

**Comment by lolodomo** [comment]
With similar words, here is the description in doc: "The binding on the local server listens to any item state updates on the remote server and updates accordingly the linked channel on the local server. It transfers any item command from the local server to the remote server."

My feeling is that you expect something different, more or less the reverse. In that case, rather install the binding on the remote server.

**Comment by cwihne** [comment]
Your strange feeling is right. I didn't get the intro correctly, your words helped understanding it better. The secondary information that Image item type doesn't support commands (except REFRESH) concludes my updated view.
My focus was on the doc's "The communication is bidirectional", interpreting that the local state update is covered - although not listed or excluded in further details.
Thank you for the effort, I will close this issue.
