### ISSUE TITLE
[hue] Add channel for last motion (API v2)

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#15546]
As reported here:
https://community.openhab.org/t/philips-hue-clip-2-api-v2-discussion-thread/142111/216

The Hue API v2 implementation in 4.0 does not support the equivalent of Hue API v1 channel `last_updated` for thing type 0107.

This is actually supported by the API, so we are simply missing a channel for this:

`GET /clip/v2/resource/device/00000000-0000-0000-0000-000000000000`

**Response:**

```json
{
    "errors": [],
    "data": [
        {
            "id": "00000000-0000-0000-0000-000000000000",
            "id_v1": "/sensors/250",
            "product_data": {
                "model_id": "SML003",
                "manufacturer_name": "Signify Netherlands B.V.",
                "product_name": "Hue motion sensor",
                "product_archetype": "unknown_archetype",
                "certified": true,
                "software_version": "2.53.6",
                "hardware_platform_type": "100b-11b"
            },
            "metadata": {
                "name": "Office motion sensor",
                "archetype": "unknown_archetype"
            },
            "identify": {},
            "usertest": {
                "status": "set",
                "usertest": false
            },
            "services": [
                {
                    "rid": "00000000-0000-0000-0000-000000000001",
                    "rtype": "zigbee_connectivity"
                },
                {
                    "rid": "00000000-0000-0000-0000-000000000002",
                    "rtype": "light_level"
                },
                {
                    "rid": "00000000-0000-0000-0000-000000000003",
                    "rtype": "device_power"
                },
                {
                    "rid": "00000000-0000-0000-0000-000000000004",
                    "rtype": "temperature"
                },
                {
                    "rid": "00000000-0000-0000-0000-000000000005",
                    "rtype": "motion"
                }
            ],
            "type": "device"
        }
    ]
}
```

`GET /clip/v2/resource/motion/00000000-0000-0000-0000-000000000005`

**Response:**

```json
{
    "errors": [],
    "data": [
        {
            "id": "00000000-0000-0000-0000-000000000005",
            "id_v1": "/sensors/250",
            "owner": {
                "rid": "00000000-0000-0000-0000-000000000000",
                "rtype": "device"
            },
            "enabled": true,
            "motion": {
                "motion": false,
                "motion_valid": true,
                "motion_report": {
                    "changed": "2023-09-04T20:04:30.395Z",
                    "motion": false
                }
            },
            "sensitivity": {
                "status": "set",
                "sensitivity": 2,
                "sensitivity_max": 4
            },
            "type": "motion"
        }
    ]
}
```

I believe a new DTO should be created for `motion_report`, which could then be included in the motion DTO here:

https://github.com/openhab/openhab-addons/blob/a0dc5c05f293b4268d76221b2d80cdcc1d41d64a/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/dto/clip2/Motion.java#L29-L30

I now also noticed that `motion` used in the current DTO is deprecated since it has been moved to `motion_report`:

https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_motion__id__get

As a work-around a profile can be used:
```java
DateTime HueMotionSensor_Mailbox_LastMotion "Last motion" <time> { channel="hue:device:home:motion1:motion" [profile="timestamp-change"] }
```

However, this does not support historical timestamps, i.e. when the binding is started after last motion was detected, the value will obviously not be reflected. Also, it's not accurate or fully corresponding to the timestamps seen in the Hue app.

## Your Environment
* Version used: 4.0.2

**Comment by andrewfg** [comment]
Yeah. @jlaur do you want to do it? Or shall I?

**Comment by andrewfg** [comment]
On GETs it would need to use 'motion_report' if that element is present, or 'motion' if it is not. And we would need to check if the SSE event DTO contains either or both elements.

**Comment by jlaur** [comment]
> do you want to do it? Or shall I?

I'll give it a go. I hope assistance can be arranged. 🙂

**Comment by jlaur** [comment]
Some context about when this was introduced: https://hueblog.com/2023/03/14/hue-bridge-update-brings-back-popular-feature/
