### ISSUE TITLE
[velux] failed to connect to second roller shutter 

### ISSUE THREAD

**Issue by bodo1987** [openhab/openhab-addons#15548]
Hi,

I have 2 roller shutters installed. Both of them are succesfully connected to the KLF200 and I can see that both can be controlled by the KLF200 (using the identify button in the webfrontend).
I integerated the KLF as bride Thing in the GUI and I also added the support thing as well.
After searching for new things in the inbox, I got the first roller shutter without problems. I linked an item and it could be controlled as expected. However, I was not able to discover the second roller shutter. Neither automatically, nor manually. 

The problem with the manual add is mostly because of the lag of the serial number. Also, I am not so sure if this would help anyway since i ofter read, that the serial number is identically if you have original velux roller shutters (as i have).

![image](https://github.com/openhab/openhab-addons/assets/19614356/b61cc8ae-5cc7-4ec1-bf40-74339c00be74)

So, I tried to play around with the name of the roller shutter as I assigned it in the KLF GUI. There I have two different names: D05 and D07 for the roller shutters in the rooms D05 and D07. But also this was without success. Please be aware that I also used the 00:00:...:00 serial number as mentioned in the documentation. More things I tried as names are:
- '#0
- '#1
- 1

All of them without success.

Next thing was to have a look in the log. I put it on TRACE level. (see atachment) Also here, I can see only one device popping up with bridgeIndex 0. As i read elsewhere, other devices should be added with incrementing bridgeIndex, but for some reason that is not happening in my case.

So, for the time beeing, I am asuming a bug. Or is there any hint of what I could still try.

[VELUX_LOG.txt](https://github.com/openhab/openhab-addons/files/12523923/VELUX_LOG.txt)

general setup:

openhab version: 4.02 
os: openhabian
hardware: raspi 3b

KLF200 firmware: 0.2.xxx

**Comment by andrewfg** [comment]
I suppose the roller shutters are Somfy devices?

**Comment by bodo1987** [comment]
I use the standard Velux rollershutters with solar cells as energy source. 

I also tried to play around with some bridge options and indeed, I can claim success.

What I did:

- deactivating the "Massenabfrage" option (mass querries in english?)
- without that option, I could see a second roller shutter from time to time during the discovery porcedure 
- after some tries, I also got a second serial number
- with that, I could agin activate the "Massenabfrage" option
- I had to reboot, since the binding kept going to throw connection erros
- remove the names in the roller shutter things
- deactivate everything and activate it aging

Success!

So all together, the binding seems to do what I was expecting finally. However, there are some major stability issues and also there is a problem with the discovery procedure. I'm not sure if this is a general problem or only something related to my setup, but at least if there are more complaints, I can only encurage you to have look on this. If you need more logs of any kind, tell me. I'll try to help, if I can.

Best regards

**Comment by lsiepel** [comment]
As the isssue seems to be resolved I close this for now.
If there are still improvements that can be made to the discovery proces, please create a new issue with specifics for that improvement.
