### ISSUE TITLE
[neeo] Excessive Thread Leak - HttpClient-*-SelectorManager

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15563]
Moved from https://github.com/openhab/openhab-core/issues/3794 

What I believe to be the transport part of neeo seems to be creating threads such as:

```
"HttpClient-14819-SelectorManager" Id=38543 in RUNNABLE (running in native)
    at java.base@17.0.8/sun.nio.ch.EPoll.wait(Native Method)
    at java.base@17.0.8/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:118)
    at java.base@17.0.8/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
      - locked sun.nio.ch.Util$2@11af4028
      - locked sun.nio.ch.EPollSelectorImpl@13b07a12
    at java.base@17.0.8/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
    at platform/java.net.http@17.0.8/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:889)
```

And not closing them.  This is eventually causing OH to run out of available space for threads.  My last crash showed over 4000 similar threads.  When neeo transport is not installed, I have 1 open HttpClient thread.  Within a minute of adding it (after waiting a considerable time) I had over 500.

**Comment by morph166955** [comment]
From what I can tell, the HttpRequest function seems to build the client but then never releases it.  It should run on close() by AutoClosable but it never seems to actually do it...

https://github.com/openhab/openhab-addons/blob/edaf17b345e489172d616a79327cf428278adba7/bundles/org.openhab.io.neeo/src/main/java/org/openhab/io/neeo/internal/net/HttpRequest.java#L110

**Comment by mherwege** [comment]
I upgraded to the OH4.1 milestone yesterday and I am running into the same issue. I never had an issue before and I have been using the Neeo binding and io service for years. My thread count was always stable, and now suddenly rises like crazy. I have not been able to do much analysis yet, and won't have much time in the coming weeks, but there is definitely something that made this problem appear now.

**Comment by mherwege** [comment]
> Moved from [openhab/openhab-core#3794](https://github.com/openhab/openhab-core/issues/3794)

There is a change in the distribution that is causing this, and not only for the Neeo binding and transport. See https://community.openhab.org/t/outofmemoryerror-after-migration-to-4-1-0-m1/149796/8.
