### ISSUE TITLE
[mqtt.homie] Channel types or config descriptions for thing 'mqtt:homie300:Default:<thing_id>' are missing

### ISSUE THREAD

**Issue by rhierlmeier** [openhab/openhab-addons#15577]
After upgrading from OH3 to OH4 I have after each restart the following warning in openhab.log:

```
023-09-10 12:36:41.961 [WARN ] [core.thing.internal.ThingManagerImpl] - Channel types or config descriptions for thing 'mqtt:homie300:Default:<thing_id>' are missing in the respective registry for more than 120s. In case it does not happen immediately after an upgrade, it should be fixed in the binding.
```

In https://community.openhab.org/t/error-for-configuration-after-upgrade-to-oh4-failed-to-normalize/148138 the maintainer laursen suggest to file an issue.

**Comment by s0129** [comment]
I am also seeing the same issue with mqtt/homie things
