### ISSUE TITLE
[hue] mdns change

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#15598]
I just noticed the following post, and I am not sure if the binding need to be fixed?

https://developers.meethue.com/forum/t/firmware-1960028010/6945/5

**Comment by andrewfg** [comment]
@jlaur ??

**Comment by jlaur** [comment]
@andrewfg - mDNS still seems to work fine:

![image](https://github.com/openhab/openhab-addons/assets/19519842/cdd654e7-980b-4ef4-9b3b-2a18faa028bd)

![image](https://github.com/openhab/openhab-addons/assets/19519842/72754102-a061-4f97-be0d-23d1da7479ff)

However, UPnP is indeed broken by this change. I have a fix ready.
