### ISSUE TITLE
[Shelly] Shelly manager broken since 3.4

### ISSUE THREAD

**Issue by matzehh84** [openhab/openhab-addons#15609]
Ever since OpenHAB version 3.4 I can no longer start the shelly manager. The following error message shows:

![image](https://github.com/openhab/openhab-addons/assets/1667923/a919e3ef-1708-42c6-9809-b5aab3728403)

The problem seems to be related to devices of type "Shelly-Plug-S". If I disable all devices of this type, shelly manager can be started, showing the other shelly devices.

![image](https://github.com/openhab/openhab-addons/assets/1667923/ff4b76d7-eadf-4944-87b6-306232330ad1)

If I re-enable a single Shelly-Plug-S device, the error message re-appears.

**Comment by lsiepel** [comment]
What is the exact version you use now?

**Comment by matzehh84** [comment]
Current version is 4.0.3. Last version that worked was 3.3.0.

**Comment by lsiepel** [comment]
Can you provide the details from openhab.log? it probably has some exception stacktrace. 

Possible suspected PR's:
https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+shelly+is%3Aclosed+milestone%3A3.4

**Comment by markus7017** [comment]
Please try latest DEV build 4.0.5 even if you are still on 4.0.3
Please provide DEBUG log if problem still exist


[4.1-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar?raw=true) | [4.0.-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.0.5-SNAPSHOT.jar?raw=true) | [3.4.5-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.5-SNAPSHOT.jar?raw=true) | [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) | **[READMEbeta](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)** 
[Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) -  [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server) | [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de)

---

Note: The DEV build is always newer than the version in the official Distro or Milestone builds. Current development is based on 4.1-SNAPSHOT, **4.0.x and 3.4.x might be outdated**.

**Comment by markus7017** [comment]
no response
