### ISSUE TITLE
[miele] Multicast message does not result in state change

### ISSUE THREAD

**Issue by aurelio1** [openhab/openhab-addons#1561]
I have an installation with four Miele@home devices and problems with this binding. The status of the devices appears unregularly on openhab, and items are usually not updated (I also checked on the karaf console), but sometimes they get updated. I don't understand when and why, as the connection to the Bridge is stable. I found out that openhab receives the multicast event, for example:
`21:03:01.866 [DEBUG] [ing.miele.handler.MieleBridgeHandler] - Received a multicast event 'type=45&id=000127907948&property=phase&value=6' from '/192.168.0.11:41055'`
How can I find out where the information gets stuck and why it never reaches the item? I set `log:set DEBUG org.openhab.binding.miele` but that doesn't help yet...

**Comment by kaikreuzer** [comment]
@kgoderis Can you help?

**Comment by aurelio1** [comment]
And btw... the log shows just this one entry for every property change in the multicast event. As I see in the source of the binding, it should at least also log `Updating the property '{}' of '{}' to '{}'` or `Update state of {} with '{}'`. It doesn't.

**Comment by kgoderis** [comment]
@aurelio1 You correctly received the multicast event, but unfortunately, Miele is quite inconsistent (well, without a doubt consistent from their point of view, but not from our reverse engineering point of view) with respect to the device ID's it uses when communicating. In the example here above, the id is not a "zigbee" id, and thus, the binding does not have a clue as to what device that multicast message is relating to. The problem they use 2 different id's for each device, one being the (more logical, and more often used) Zigbee id, and sometimes this other id. And the same kind of information (Phase of the dishwasher programme, ...) is relayed in different ways to clients.

The XGW3000 is in fact an Zigbee gateway above all. You can look up the Zigbee ID through the web interface of the gateway in case you wonder. 

Me too I also noticed that some other magic is happening when comparing what the for example the iOS app is doing/showing. Without formal documentation (@kai do not shoot me on this one ;-) ) further development is a bit hard

Now, I would appreciate if you could delve into this and report any further findings. That would help me a great deal given that the time I can devote to OH/ESH is rather limited (e.g. I am not an Software Engineer by profession)

**Comment by kaikreuzer** [comment]
> @kai do not shoot me on this one ;-)

Only, if you haven't done yet what we recently discussed 😛

**Comment by hmerk** [comment]
closed due to inactivity
