### ISSUE TITLE
[shelly] Authentication does not work with Shelly Plus 2PM Gen2 devices since FW 1.0.3

### ISSUE THREAD

**Issue by Struppie** [openhab/openhab-addons#15629]
Since the latest update to FW 1.0.3 for Shelly Plus 2PM Gen2 devices, the authentications of the Shelly Binding does not work anymore.

Was using OpenHAB v3.4.4 with FW 0.14 and authentication successfully.
Since update to FW 1.0.3 authentication fails with CONFIGURATION_ERROR and access denied message. Thing does not go online.

Workaround:
Disable authentication at Shelly device.

Solution:
I think something changed with FW 1.0.3 breaking the current login mechanism of the binding at the Shelly Gen2 device.
Seems a fix/adaptation of the Shelly Binding is required to make it work with FW 1.0.3 and authentication again.

(Community discussion here: [click](https://community.openhab.org/t/shelly-plus-2pm-gen2-devices-with-latest-firmware-1-0-3-not-working/149727))

**Comment by MiniOh** [comment]
>>Workaround:
>>Disable authentication at Shelly device.

I think a downgrade to FW 0.14 is the better Workaround.

**Comment by Struppie** [comment]
@MiniOh the problem is, that FW downgrade is not yet supported by Shelly for Gen2 devices, because the devices are new and they warn, that you may break it with downgrade (Shelly does also not offer the "old" FW files to prevent doing this ;))

**Comment by MiniOh** [comment]
That's true, but technically it's not a problem.
With the Plus 1 you can do this via drag and drop, with the Pro 4 PM via link.
In both cases it was no problem for me.

**Comment by Struppie** [comment]
Hint: According to @Matze0211 it seems, that Shelly binding tries to connect via HTTP, but should via HTTPS for Gen2 devices:

> `2023-10-14 17:21:27.573 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellyplus2pm-d4d4da09c5b4: Using userId admin from bindingConfig
> 2023-10-14 17:21:27.578 [DEBUG] [y.internal.handler.ShellyBaseHandler] - shellyplus2pm-d4d4da09c5b4: Device config: IP address=xxx, HTTP user/password=admin/***, update interval=60` 
> 
> It seems the binding tries to authenticate via HTTP basic, but as its a Gen2 device, it has a different authentication…
>

**Comment by Matze0211** [comment]
> Hint: According to @Matze0211 it seems, that Shelly binding tries to connect via HTTP, but should via HTTPS for Gen2 devices:

My comment was not about http va https but more about basic auth vs digest, that was (as per my knowledge) newly introduced to gen2 devices.

However I tested same Shelly device with OH4.0.3 and the issue is already fixed in latest version.

**Comment by Struppie** [comment]
Ups, sorry, you are right and I just gave it a try with OH4.0.3, too. This also succeeded here! :)

**Comment by Struppie** [comment]
fixed with OH4.0.3
