### ISSUE TITLE
[avmfritz] FritzOS 7.30 from September 5th 2023 breaks binding

### ISSUE THREAD

**Issue by lukas-bechtel** [openhab/openhab-addons#15625]
Since the latest update of the FRITZ!Box 7560 on September 5th 2023, the AVM FRITZ!Box Binding (binding-avmfritz) cannot connect anymore.

## Expected Behavior
With correct IP address, Protocol/Port, Username, and Password configuration, the binding should connect to the FritzBox.

## Current Behavior
It does not connect anymore and shows a communication error.

![IMG_2891](https://github.com/openhab/openhab-addons/assets/11645862/2d9d329a-c68a-4002-9754-1f56e8eddf2c)

I already deleted the user in the FritzBox and reconfigured a new one, no change. Also uninstalling and reinstalling the binding, as well as removing and adding the Thing in OH3 does not help.

## Possible Solution
Did the authentication at the FritzBox change?

## Steps to Reproduce (for Bugs)
1. Update a FritzBox 7560 to 7.30
2. Configure OH3 binding-avmfritz

## Context
Integration of PowerPlugs and Thermostat does not work anymore.

## Your Environment
OpenHAB 3 on an Ubuntu Server

**Comment by tobiloeb** [comment]
Maybe the same issue I opend a few weeks ago: https://github.com/openhab/openhab-addons/issues/15363

**Comment by Struppie** [comment]
@tobiloeb Yes, sounds similar. Does the workaround to set the timeout like described above work in your scenario?
(my guess is, that the FritzBox is slower with the new FW and therefore the OH binding needs to be a bit more tolerant regarding timeouts)

**Comment by lukas-94** [comment]
Thanks a lot @Struppie ! I had to increase the syncTimeout to 15000, which is the max value, (only 10000 did not work) and restart openHAB. Now everything is back online.

**Comment by tobiloeb** [comment]
> Thanks a lot @Struppie ! I had to increase the syncTimeout to 15000, which is the max value, (only 10000 did not work) and restart openHAB. Now everything is back online.

For me every restart fixes the issue for some time or some days until it breaks again. :(

My timeout is at 5000, but this didn't help.

**Comment by tobiloeb** [comment]
@lukas-94  Does this fix the issue for you? I increased the timeout but it's not working. I have to restart my Openhab instance daily. :(

**Comment by lukas-94** [comment]
@tobiloeb Yes, it works since my last comment without interruption… sorry to hear that it does not work for you :(
