### ISSUE TITLE
[miio] Add support "Mi Smart Antibacterial Humidifier" - deerma.humidifier.jsq2w

### ISSUE THREAD

**Issue by rheos13** [openhab/openhab-addons#15639]
Add support for the following humidifier model:

- "Mi Smart Antibacterial Humidifier" - deerma.humidifier.jsq2w

Works in OH 3.4.2
[deerma.humidifier.jsq2w.zip](https://github.com/openhab/openhab-addons/files/12706059/deerma.humidifier.jsq2w.zip)

**Comment by marcelrv** [comment]
closed with https://github.com/openhab/openhab-addons/pull/15676
