### ISSUE TITLE
[homekit] support possibility to define Enum values for HeaterCooler current and target state

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#15674]
it will be nice to have possibility change Enum values for HeaterCooler current and target state, same as in thermostat. and other accessory.
Right now this values are fixed as current state: INACTIVE (0), IDLE (1), HEATING (2), COOLING (3)
target state: AUTO (0, OFF), HEAT (1, ON), COOL (2).

Also as my request in #15672 add possibility to use multiple Enum Values for state.

Thanks
Grzegorz

**Comment by ccutrer** [comment]
ALL enum values should be customizable from the PoV of the HomeKit add-on. If you're not able to do so from MainUI, that is an issue to be opened in [the appropriate repo](https://github.com/openhab/openhab-webui).
