### ISSUE TITLE
[kermi] Support for kermi x-center heat pump 

### ISSUE THREAD

**Issue by col-panic** [openhab/openhab-addons#15680]
I work on implementing support for the [kermi](https://www.kermi.com/en/de/indoor-climate/products/heat-pumps-and-storage/x-center-controller/) heat-pump x-center manager.

This issue is to track the contribution progress.

More information will follow.

**Comment by col-panic** [comment]
Draft PR https://github.com/openhab/openhab-addons/pull/15687

**Comment by col-panic** [comment]
Channels are now dynamically resolved after traversing all datapoints. Number and OnOff channels are already implemented. Multiple enhancements and refactorings.

**Comment by col-panic** [comment]
Please have a look at https://github.com/openhab/openhab-addons/pull/16329 - development on this implementation is currently halted.

**Comment by col-panic** [comment]
Project continued in https://github.com/col-panic/homeassistant-boesch-heatpump-integration

**Comment by lsiepel** [comment]
> Project continued in https://github.com/col-panic/homeassistant-boesch-heatpump-integration

@kaanee is almost finished with the PR. It is close to being merged and looks like it is going to be part of openHAB 4.3.0
