### ISSUE TITLE
[shelly] TRV setting the target temperature only possible in integers

### ISSUE THREAD

**Issue by xvs03** [openhab/openhab-addons#15695]
A setpoint item that has been created can only send integers as the target temperature.
If float target temperature values are sent, the TRV will not accept them.

I have run a test series with different setpoint temperature values with the following result:

**Result of this test:**
Send integers OK
Send float numbers **not** OK
Receive integers OK
Receive float numbers OK

I just specified the set temperature via the HTTP API.

Send URL:
`http://<IP-ShellyTRV>/settings/thermostats/0?target_t=29.4`

The TRV accepts all numbers via this. Even 1/10 steps.

**More Info**
OpenHab Community Topic:
[https://community.openhab.org/t/setting-the-target-temperature-from-shelly-trv-only-possible-in-integers/150047?u=xvs03](url)

Openhabian: Version 3.4.4 on RPi4

**Comment by xvs03** [comment]
I got rid of the handler warning by rebooting the system.
However, I still cannot send decimal numbers as the setpoint temperature to the TRV. The TRV simply rounds up to an integer.

**Comment by markus7017** [comment]
no response

**Comment by xvs03** [comment]
Hi, I recently upgraded to 4.1.1 and set the steps in the temperature set item to 0.5. They are now applied without error message. Many thanks for your info
