### ISSUE TITLE
[RFXCom] New firmware

### ISSUE THREAD

**Issue by jbuekens** [openhab/openhab-addons#15698]
Hi,

Using an RFXCom RFX433XL Wifi and get the following error when installing the binding:

The firmware type reported (20) isn't known to the RFXCom binding. Please raise an issue at https://github.com/openhab/openhab-addons/ to have it included.

Can this be included please

Thanks

**Comment by lolodomo** [comment]
Duplucate of #13024

**Comment by lolodomo** [comment]
Closed as duplicate.
