### ISSUE TITLE
[telegram] Add Possibility to delete Messages / Questions

### ISSUE THREAD

**Issue by fd0cwp** [openhab/openhab-addons#15716]
I would like to delete a Telegram message / question.

Use case:
I check my temperature sensors once an hour. If one didn't change the value since some hours, I consider the device to be faulty. Unfortunately, this happens very often. In this case, I get a question sent via Telegram to reset the device, to which response OH reacts and performs a re-init of the device. Now it may happen that the temperature has actually not changed in time, or the device magically heals itself. In this case the question is no longer valid and I would like to delete it from the Telegram chat.
I'm just starting to use the Telegram bot, but I think this would be useful for normal messages as well. E.g. for a notification that a window is open in winter time for too long. If it is then closed, the notification is moot and could be deleted to have the tidiest chat possible.

Technically, this should be no problem, at least not for normal messages: https://core.telegram.org/bots/api#deletemessage
The REST call would look like https://api.telegram.org/botToken/deletemessage?chat_id=0815&message_id=4711

Environment: I think this info is not necessary, but I use openHAB 4 on a Raspberry Pi 4

**Comment by Skinah** [comment]
By question do you mean the sendTelegramQuery? If so you can already delete them by sending an answer with null as the message.

**Comment by Skinah** [comment]
If you want to delete a normal message since you provided the api syntax it should be easy to implement if you know the chat ID and message ID and can have that stored across a reboot. It may be possible to do it from just the message ID and have the binding keep track of the last 50 messages to make life easier in rules, but it would not persist across reboots unless it is stored out to a file which the binding does not currently do.

**Comment by fd0cwp** [comment]
> By question do you mean the sendTelegramQuery? If so you can already delete them by sending an answer with null as the message.

Hi @Skinah 

Yes, I would like to delete Queries. As an example:
`telegramAction.sendTelegramQuery("Licht ausschalten?", "2", "JA!", "Nein")`
reuslts in
![image](https://github.com/openhab/openhab-addons/assets/36006493/f743183b-a0e3-452d-9f01-9c9c6eb3ca23)

When I then call (what I already do)
`telegramAction.sendTelegramAnswer("2", null)	`
I can no longer answer the question (the buttons are gone) but the question itself is still there
![image](https://github.com/openhab/openhab-addons/assets/36006493/9a6697c7-ea59-45e9-8021-59faca659206)

I would like to have also that the question is removed as it is no longer valid and you even cannot answer it any longer.

I had in mind that it could be occasionally reasonable to also delete normal messages.
If you add this functionality, do not care for the ID. This should be known / handled by the user in my point of view.

**Comment by fd0cwp** [comment]
I did some testing. If I would have the message ID, I could delete the complete question (not only the buttons as it is the case by answering the question). I used this call for testing:
`https://api.telegram.org/botID/deleteMessage?chat_id=0815&message_id=4711`

So, I assume the following changes are necessary:
1. give back the message ID when sending a message or a query (or add a possibility to get the latest message ID sent from the binding)
2. let the user handle storing the message ID(s), e.g. in an array together with e.g. the reply ID of sending a query
3. add a new function deleteTelegram(messageID) to the binding to delete a message (query)

**Comment by fd0cwp** [comment]
I had a look into the source code. It already stores a mapping of chat ID, message ID and reply ID (`replyIdToMessageId `in `TelegramHandler`). So, adding a function `deleteQuery(replyID)` should be possible.
I was able to debug into the source code but unfortunately, I do not understand how to implement a new execute functionality for the "deleteMessage" API call.

**Comment by fd0cwp** [comment]
I think I have a working prototype. There is already a class available to delete a message. I use this to delete a query by using the replyId (known by the user) and the internal replyIdToMessageId list.
I have to do some more coding, clean up and documentation. After some tests, I will come up with a PR.
