### ISSUE TITLE
[Milight] Add Milight iBox support (API v6)

### ISSUE THREAD

**Issue by lala-rob** [openhab/openhab-addons#1571]
I have a Problem controlling RGBWW 8W Bulbs.
No command is working

The Bulb are connected to an Mi-Light Wifi iBox

Description on the Bulb:
Mi-Light 8W RGB+CCT LED Bulb

Binding:
Milight Binding 2.0.0.201611222318

Product:
https://www.aliexpress.com/item/Tanbaby-Mi-light-Wireless-E27-Smart-Bulb-8W-RGB-Color-temperature-changing-85-265V-Dimmable-RGBWW/32596233965.html

Log:
13:18:38.060 [DEBUG] [ternal.protocol.MilightCommunication] - milight: sendNightMode
13:18:38.060 [DEBUG] [ternal.protocol.MilightCommunication] - milight: messageBytes to transform: '46:00:55'
13:18:38.061 [DEBUG] [ternal.protocol.MilightCommunication] - Sent packet '46:00:55' to bridge '' (192.168.0.201)
13:18:38.161 [DEBUG] [ternal.protocol.MilightCommunication] - milight: messageBytes to transform: 'C6:00:55'
13:18:38.161 [DEBUG] [ternal.protocol.MilightCommunication] - Sent packet 'C6:00:55' to bridge '' (192.168.0.201)

**Comment by hmerk** [comment]
This is not a problem, it is juast not implemented yet.
These Bulbs need API V6.0 to be implemented, so please feel free to start a feture request.

**Comment by davidgraeff** [comment]
@kaikreuzer: Could you assign this to me and label this issue as feature reuqest?
@lala-rob: Could you please rename the title of this issue to "Add Milight iBox support (API v6)"?

Thanks,
David

**Comment by davidgraeff** [comment]
Work in progress in merge request #1779

**Comment by DomQuixote** [comment]
Hello, 

Just wondering what the status on this issue/feature request is. 

Apart from the new v6 bridge not yet being supported, I also think the 9W RGBW lights support is not complete, as setting the warmth of the bulb is not supported for rgb lights, only for white bulbs. Will this be included in the v6 update?

**Comment by davidgraeff** [comment]
Hey @dom,

Are u talking about the old 9w rgbw bulbs? They don't support color temperature for white. Please doublecheck with the official app. If u think the documentation is incomplete please add another issue. 

My new version hasn't been accepted yet by other reviewers. That's the reason why it takes so long. 

Thanks David

**Comment by DomQuixote** [comment]
Hello David,

Sorry for the late reply.

Yes, talking about those. I seem to remember they did, but I might be mistaken. 

For the RGBW bulbs, is there another way than sending  (64, 3, 100)  to get them back to 'whitemode'? Nightmare is implemented, but switching between white and colour, has that been implemented as well?

I'll install your version, this is taking longer than my patience can handle. New toys and can't use them!

**Comment by davidgraeff** [comment]
@kaikreuzer, @openhab/maintainers Issue is resolved, please close
