### ISSUE TITLE
[evcc] Temperature instead of Percent for heating devices

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#15744]
If the charger is a heating device (no car), the SOC channels shall use `Number:Temperature` instead of `Number:Dimensionless` (Percent).

Parameter in `evcc.yaml`:
`chargers.heating: true`

Flag in API:
![image](https://github.com/openhab/openhab-addons/assets/44850211/7a1c9f1d-928d-4047-95cc-36677c7022e9)

In GUI:
![260809676-9fe2d90a-3241-486d-963d-81b526074b54](https://github.com/openhab/openhab-addons/assets/44850211/356399c9-e9c1-4980-a94c-683503c47ba9)

See also the following change in evcc: https://github.com/evcc-io/evcc/pull/9393

**Comment by ElementFlo** [comment]
Hey i got the issue that i am using a shelly Plug for charge via 230V but it always shows Temp instead of SoC.
i already change Charger: heating: false butnothing changed

**Comment by MikeTheTux** [comment]
> Hey i got the issue that i am using a shelly Plug for charge via 230V but it always shows Temp instead of SoC. i already change Charger: heating: false butnothing changed

Did you find a way to solve your issue? I guess you should ask these kind of questions, together with your full config in evcc but not the openhab forum ...

**Comment by florian-h05** [comment]
Closed by #16378.
