### ISSUE TITLE
[luxtronikheatpump] temperatureHotWaterTarget not working as expected

### ISSUE THREAD

**Issue by ccbur** [openhab/openhab-addons#15758]
In OH 4.2 I'm controlling an Alpha Innotec LWD 70A heat pump with the _luxtronikheatpump_ binding and the channel _temperatureHotWaterTarget_ is not working as expected. The value set there is not reflected in the heatpump at all. Everything worked in OH 2.5 with the _novelan_ binding and the channel _temperature_servicewater_reference_, though.

I looked through the code in [HeatpumpChannel.java](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.luxtronikheatpump/src/main/java/org/openhab/binding/luxtronikheatpump/internal/enums/HeatpumpChannel.java) and found this:

```
/**
     * Hot water target temperature
     * (original: Warmwasser Soll-Temperatur)
     */
    // Not needed as it duplicates writable param (2)
    // CHANNEL_EINST_BWS_AKT(18, "temperatureHotWaterTarget", NumberItem.class, SIUnits.CELSIUS, false, null),
```

Okay, so I looked for a channel with the channelId 2 and found this:

     /**
     * Coverage Heat pump (Hot Water)
     * (original: Deckung Wärmepumpe)
     */
    CHANNEL_EINST_BWS_AKT(2, "temperatureHotWaterCoverage", NumberItem.class, SIUnits.CELSIUS, true,
            HeatpumpVisibility.BRAUWASSER),

EINST_BWS seems to be German and means setting (EINST) hot water target (BWS / BrauchWasserSoll). So I tried the channel _temperatureHotWaterCoverage_ instead and it seems to be able to set the target temperature for hot water in my heat pump. But I have no idea what "coverage" (German Abdeckung!?) could mean in this context. This channel is not documented in the [README.md](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.luxtronikheatpump/README.md) at all.  Is this just a documentation issue or are both channels messed up somehow?

**Comment by lsiepel** [comment]
Maybe @sgiehl as code owner can comment?

**Comment by sgiehl** [comment]
The heatpump provides two types of parameters. writable and readonly values. The channel with id `18` would be read only. And as far as I know it would only provide the same value as the one with (writable) id `2`.
This assumption could be wrong, but in any case, the channel with id 18 would not allow to set any value.

There should also be a channel with the name `temperatureHotWaterTarget`, wich should allow setting a value for the hot water target temperature.
If I remember correctly someone also reported in the forum that only setting `temperatureHotWaterCoverage` corretly worked and updated the other one.
What the "coverage" exactly means for the other channel is unfortunatelly out of my knowlege.
Maybe there are heatpumps with additional heat sources like solar thermal energy, where the heatpump only covers the hot water temperature up to a certain limit maybe :shrug: 

Anyway, not sure why we didn't add the channel to the readme as well. Would make sense to add it I guess. 
But I unfortunatelly can't give any advice when which channel would need to be used.

Note: For my heatpump (Novelan LD7) the channel `temperatureHotWaterTarget` works correctly.
