### ISSUE TITLE
[influxdb] values stop being persisted if the network connection to the server breaks temporarily

### ISSUE THREAD

**Issue by nagisa** [openhab/openhab-addons#15763]
## Expected Behavior

Values should be persisted according to the persistence rules whenever there is a way to make a connection to the influxdb server.

## Current Behavior

As noted in https://community.openhab.org/t/influxdb-persistence-stops-permanently-when-influx-db-server-has-outage/149446, a temporary connectivity issue (such as the one caused by restarting the influxdb server) will result in an exception(s) within the binding and the binding will stop persisting the values, even after the server/networking recovers. 

## Possible Solution

Catch the offending exceptions and/or handle them gracefully. For something like InfluxDB a ringbuffer of values to be saved could also be maintained to avoid loss of data.

## Steps to Reproduce (for Bugs)
0. Set up influxdb and influx persistence
1. `sudo systemctl stop influxdb; sleep 120; sudo systemctl start influxdb`

## Context

OpenHAB automations and core functionality continues working, but it starts failing to record important factual information about the items sporadically until manual intervention is applied to rectify the problem:

(e.g. by restarting openhab, or less invasively `bundle:restart`ing `org.openhab.persistence.influxdb`)

## Your Environment

* Version used: 4.0.3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): N/A
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): NixOS

Also see: https://community.openhab.org/t/influxdb-persistence-stops-permanently-when-influx-db-server-has-outage/149446

**Comment by nagisa** [comment]
Ah, the improvements from https://github.com/openhab/openhab-addons/pull/15452 have not made their way into a release yet… Closing for now, but will retry reproduction when 4.1.0 comes out.

**Comment by wborn** [comment]
You can also try 4.0.4 when it gets released as that PR has been backported.
