### ISSUE TITLE
[shelly] Wrong vendor ID in Shelly binding description

### ISSUE THREAD

**Issue by ErikDB87** [openhab/openhab-addons#15776]
The description (https://www.openhab.org/addons/bindings/shelly/) claims Shelly Plus 1 Mini is supported, which I hope, because I intend to use them. But the vendor ID is listed as SNSW-001X16EU, which should be SNSW-001X8EU.

**Comment by lolodomo** [comment]
@markus7017 : is there still something to fix in README?

**Comment by markus7017** [comment]
No, it might be that they have a new hardware revision, there is also a new Gen3 Plus 1 Mini, just received a sample

**Comment by markus7017** [comment]
You are right, the model ids in README are wrong, fixed

**Comment by ErikDB87** [comment]
Apparently, the documentation has been corrected.
