### ISSUE TITLE
[xmppclient] Sending XMPP groupchat messages to room

### ISSUE THREAD

**Issue by jlaba** [openhab/openhab-addons#15799]
As described at https://community.openhab.org/t/sending-xmpp-groupchat-messages-to-room/124216 sending messages to groupchats is a very nice feature. For example, we have one group for notifications related to our house, as we have more than 1 person living in the house.

With groupchats, I can just add people to the room and they receive all informationen. Otherwise I need to tweak the recipient JIDs in every rule, sending xmpp messages.

**Comment by akallabeth** [comment]
https://github.com/openhab/openhab-addons/pull/17938
