### ISSUE TITLE
[lcn] getActions isnt working anymore in OH 4.0.3

### ISSUE THREAD

**Issue by harteknut** [openhab/openhab-addons#15803]
The getActions-Command isnt working anymore:

Code (part of a rule):
```
val actions = getActions("lcn","lcn:module:edb2e504:S000M019")
actions.sendDynamicText(2, some_text)
```

Errorlog (reproducible):
``` 
[internal.handler.ScriptActionHandler] - Script execution of rule with UID 'anzeige-3' failed: Cannot invoke "org.openhab.binding.lcn.internal.LcnModuleActions.sendDynamicText(int, String)" because "actions" is null in anzeige
```
The command (in a rule) was working well for more than a year till the last update.

**Comment by jlaur** [comment]
Can you show your thing definition?

**Comment by harteknut** [comment]
Thanks for the response!
I habe to admit that the Error disapeared after a few reboots.
