### ISSUE TITLE
[Homekit] Detected value out of range for light sensors continue to occur

### ISSUE THREAD

**Issue by lukiep** [openhab/openhab-addons#15818]
I use a Aeotec Zwave multisensor which produces a light reading in Lux. 

## Expected Behavior
When it is totally dark a reading of 0 lux is correct.

## Current Behavior
Noting: https://github.com/openhab/openhab-addons/issues/9722 and https://github.com/openhab/openhab-addons/pull/11803

Although in the posts above I can see this reported and fixed in 2021, I still regularly see the errors below in the logs when it is totally dark and the device produces a reading of 0 lux.

Do I need to change the logging level as suggested in above post or does the fix negate the need to do so? And if fixed any ideas why its still occurring?

```
08:45:42.597 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:47:03.373 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:47:49.132 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:47:58.336 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:49:07.749 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:49:51.074 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:51:35.511 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:54:07.587 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:55:13.694 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:57:19.617 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
08:57:45.707 [WARN ] [ristics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@4634ff
```

## Possible Solution
?

## Steps to Reproduce (for Bugs)
not sure how to reproduce. I have observed that the warnings do not follow a specific pattern in terms of timing.

## Your Environment
OH 4.1.0 M1 n RPI 4 through openhabian.

**Comment by ccutrer** [comment]
Note that the logging is saying "Detected value out of range 0.0" is saying "0.0 is the value I was given, which is less than the minimum <which is not logged here>", _not_ that "0.0 is the minimum value". You can use `homekit show <accessory name>` in the openHAB CLI in order to find out what the minimum value is currently being populated as. The default minimum value is `0.0001`. You can use metadata configuration to override the minimum to set it to actual 0.

**Comment by lsiepel** [comment]
> Note that the logging is saying "Detected value out of range 0.0" is saying "0.0 is the value I was given, which is less than the minimum ", _not_ that "0.0 is the minimum value". You can use `homekit show <accessory name>` in the openHAB CLI in order to find out what the minimum value is currently being populated as. The default minimum value is `0.0001`. You can use metadata configuration to override the minimum to set it to actual 0.

As this is a common scenario, can’t the 0 be overridden to 0.0001 ? I guess many users will face this issue. Can als o understand that it can get very difficult to workaround all sub use cases.
Just a suggestion to try improve user experience

**Comment by ccutrer** [comment]
Agreed. Some of the default ranges in HAP are... questionable.

**Comment by lsiepel** [comment]
> Agreed. Some of the default ranges in HAP are... questionable.

Before it is send into HAP, the binding could ‘snap’ to the allowed range of this is something g that can’t/won’t be changed in HAP

**Comment by lsiepel** [comment]
@lukiep fix should be available in the next snapshot and milestone. Pretty confident there are no regressions, but  would be nice if you could use the binding and check all is fine.

**Comment by lukiep** [comment]
I just upgraded to 4.3M2 and the log errors seem to be gone for the device that routinely registers 0 lux.  

Thank you for your work on this.
