### ISSUE TITLE
Using /dev/serial/by-id for device naming instead of /dev/ttyUSBx on systems with multiple serial usb controllers

### ISSUE THREAD

**Issue by clown-m** [openhab/openhab-addons#15810]
Belongs to the Modbus Binding with serial adapters

Could you pls. add the possibility to use /dev/serial/by-id/xxx device names instead of /dev/ttyUSBx?

It#s really worth that i have to edit all device names after a reboot and find out what is running on which device name.
I have running a Modbus serial adapter and an serial adapter for RME cistern device.

Thank's , will help me a lot if you could add this.

## Your Environment
Version = openHAB Version 4.03
Operating Sytsem = Debian Bullseye

**Comment by udo1toni** [comment]
Would be better to use a udev rule to ensure that every serial adapter is always recognized correctly.

**Comment by clown-m** [comment]
The RME Binding work with the /dev/serial/by-id, so i thought that this is the standard, while the documentation also mention this method. Someday i tried it by udev, but it does not work, so i checked the correct interfaces after each reboot.
Are you using the udev method? Does it work with you?
Thanks fpr replying to my question !

**Comment by wborn** [comment]
Duplicates https://github.com/openhab/openhab-addons/issues/15509
