### ISSUE TITLE
[jdbc-sqlite] Sometimes fails with SQLITE_BUSY with OH 4.0.3 

### ISSUE THREAD

**Issue by kennetn** [openhab/openhab-addons#15821]
## Expected Behavior
I have a rule that updates two items every 10 minutes.
I am expecting both item updates to be store in the SQLite database every time that they are changed. 
This was working in OH 3.4.0.

## Current Behavior
After upgrading to 4.0.3 I started getting occasional exceptions with SQLITE_BUSY and the item updates not being stored.
In the last 24 hours I had 8 times that it failed and the items are being updated every 10 minutes.
I set the level logs to debug on the sqlite binding and the log is attached that shows when this happens.
[SQlite-debug-log.txt](https://github.com/openhab/openhab-addons/files/13197839/SQlite-debug-log.txt)

I have only seen the error happen on one of the two items, never both.
I tried restarting both NAS and OH several times.
If I try and insert the values afterwards via the SQLite command line tool I can insert the values without any problems.

## Possible Solution
I am guessing this is a threading issue that the SQLite database can not handle two item updates (writes) at the same time. 
So some times the updates run so synchronously that the data write happens at the same time and then it fails.
Other times they er not aligned and everything works fine.
So a possible solution might be a global lock that prevents more then one thread from writing to the databased at a time. 

## Steps to Reproduce (for Bugs)
My jdbc.persist look like this:
[jdbc.persist.txt](https://github.com/openhab/openhab-addons/files/13197881/jdbc.persist.txt)
The rule look like this
```
rule "Update 10 minute value"
when
  Time cron "57 9/10 * ? * * *" 
then
...
    smartmeter_10_min_energy_usage.postUpdate( current_value - last_10_min_power_value )
    smartmeter_10_min_cost.postUpdate( (current_value - last_10_min_power_value) * (energi_data_service_total_price.state as Number ))
end
```

## Context
I am trying to store the power usage and cost every 10 minutes so that I can create a graph of this.

## Your Environment
* Version used: 4.0.3
* Environment name and version: Docker image openhab/openhab:4.0.3
* Operating System and version: Synology DS720+ NAS with DSM 7.2-64570 Update 1

**Comment by jlaur** [comment]
@kennetn - can you try this backport?
- [org.openhab.persistence.jdbc-4.0.4-SNAPSHOT.jar](https://drive.google.com/file/d/1Ui9PVC3DGxB7h0vNPjPly2YDkfro7VyM/view?usp=sharing)
- [sqlite-jdbc-3.42.0.0.jar](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.42.0.0/sqlite-jdbc-3.42.0.0.jar)

You will need to uninstall the persistence add-on and then copy both JAR files into your addons directory. The file `sqlite-jdbc-3.42.0.0.jar` should be renamed to `sqlite-jdbc.jar`.

The backport contains currently merged fixes and improvements for 4.1 and also #15801 which is not yet merged. This fix might help.

**Comment by kennetn** [comment]
I have installed the backport and will get back once it has run for some time.
I did notice one thing when I tried to uninstall the previous version.
I have most of the binding installed via conf\services\addons.cfg but after I removed it from that file it was not removed in the UI. So I clicked the uninstall in the UI also and now it was removed.
I dont know it it is relevant but I just thought I would mentions it. 
I do not know if it was possible that the binding was installed twice and that could cause it to try and write to the same database twice. But my guess is that in that case it would have resulted in the values getting stored.

**Comment by kennetn** [comment]
Hi @jlaur 

It has have been running all night now and still no exceptions.
I also checked the database and all value has been store correctly.

So I guess it is safe to say it works.
I guess I can just use the backport until OH 4.1 is released.
Or is there something else you would like me to test ?
Thanks.

**Comment by jlaur** [comment]
> So I guess it is safe to say it works.

Thanks for reporting back on this. You also helped testing an upgrade of the SQLite library. 👍

> I guess I can just use the backport until OH 4.1 is released.

Yes.

> Or is there something else you would like me to test ?

It would be nice to rule out any issues with two parallel bindings running like you described.

If you could remove the JAR file from the addons directory again and go back to the 4.0.3 version installed only from the UI and not present in addon.cfg, then the issue should reappear. If it does, that would confirm the fix is really working.

**Comment by kennetn** [comment]
I have tried running 
307 │ Active │  80 │ 4.0.3                  │ openHAB Add-ons :: Bundles :: Persistence Service :: JDBC
308 │ Active │  80 │ 3.40.0.0               │ SQLite JDBC
installed via the GUI and the error did not return. 
So I guess its must have be related to having the bundle installed twice.

**Comment by kennetn** [comment]
Ok so maybe there is still something wrong in the old binding, because now the issue is back.
So after I had seen it working for about a day (installed via the GUI) I though the issue was ok so I tried going back to how I originally had it installed via addons.cfg. What I did was.
1. Check version installed via bundle:list
2. Uninstall from GUI
3. Verify it was removed with bundle:list
4. Added jdbc-sqlite to the line : persistence = rrd4j,jdbc-sqlite in  addons.cfg.
5. Verify that the same version was installed via bundle:list.

I dont remember the exact time I did this but I think that about a day after I started getting the messages again.
So I am guessing that maybe there is also a time element from the time that the binding is installed until the issue happens.

When I see the issue now I have checked that there is just one version.
```
openhab> bundle:list | grep JDBC
310 x Active x  80 x 4.0.3                  x openHAB Add-ons :: Bundles :: Persistence Service :: JDBC
312 x Active x  80 x 3.40.0.0               x SQLite JDBC

```
I tried installing same version via the GUI and will monitor this for more and just a day and report back.

**Comment by jlaur** [comment]
You could now try to let the JAR version run for some time, since it should fix the issue.

**Comment by kennetn** [comment]
Ok I will do that instead of running with the GUI installed version.
This is how I verified my upgrade:

```
openhab> bundle:list | grep JDBC
316 x Active x  80 x 4.0.3                  x openHAB Add-ons :: Bundles :: Persistence Service :: JDBC
317 x Active x  80 x 3.40.0.0               x SQLite JDBC
openhab> bundle:list | grep JDBC
openhab> bundle:list | grep JDBC
318 x Active x  80 x 4.0.4.202310291407     x openHAB Add-ons :: Bundles :: Persistence Service :: JDBC
319 x Active x  80 x 3.42.0.0               x SQLite JDBC

```

**Comment by kennetn** [comment]
One week now still not issues.
I think its safe to say issues is solved in new version
