### ISSUE TITLE
[roku] Secret Screens

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#15822]
Roku has a few screens that are hidden from normal use. They are accessed through key combos from the remote. It would be a nice feature to add to trigger them with a single command.  Perhaps as an extension off of the button channel?

**Comment by mlobstein** [comment]
Secret screens do not seem to be accessible via the web api. Closing issue for now.

**Comment by morph166955** [comment]
Agreed and thank you for the attempt.
