### ISSUE TITLE
[luxtronikheatpump] Failed to update item ControlSignalCirculatingPump after upgrading to OH4

### ISSUE THREAD

**Issue by jamietownsend** [openhab/openhab-addons#15836]
## Current Behavior
After upgrading from OH3 to OH4, the following messages are now appearing in the log file:
`15:12:28.103 [WARN ] [openhab.core.library.items.NumberItem] - Failed to update item 'HeatpumpwithLuxtronikControl_ControlSignalCirculatingPump' because '0 %' could not be converted to the item unit 'kWh'
`

I think it may be related to the definition here:
https://github.com/openhab/openhab-addons/blob/59c3135ccb911f9c9225c4f449e23b7f09e56ffb/bundles/org.openhab.binding.luxtronikheatpump/src/main/resources/OH-INF/thing/channels.xml#L1578

Any ideas if this may be the case or how to fix this otherwise?

**Comment by lsiepel** [comment]
That channel definition does look a bit odd.  The type suggest energy, the label suggests some percentages. Readme is also not clear about it.
