### ISSUE TITLE
[onkyo] Return to previous input source after playSound

### ISSUE THREAD

**Issue by chiefymuc** [openhab/openhab-addons#1584]
Currently the Onkyo binding does not return to the previous input source after playing a sound from openhab. I believe this should at least be an option.

Maybe @vbier can help?

Thanks!

**Comment by Cossey** [comment]
I’ll see what’s involved regarding this... if I recall OH should know when playback is finished. It’ll be down to capturing this event and also storing the last input type and restoring it after completion. 

What I’m not too sure about how to solve is if you’re playing music through Chromecast built-in/AirPlay/Spotify/etc as that would need the user to reconnect from their device so in that case maybe we could either ignore switching back to that input or just switch it back anyway and wait for user interaction.
