### ISSUE TITLE
[jdbc] Mistake in Settings->Persistence

### ISSUE THREAD

**Issue by agricolaXIII** [openhab/openhab-addons#15847]
Hello,

on the HTML-page on Settings->Persistence to install Maria-DB is one problem:
the installation of the MariaDB-Service is labeled as “JDBC-Persistence (SQLite)”, this Label is also used for another service to install- please see the uploaded screenshot:

![Screenshot_20231102](https://github.com/openhab/openhab-addons/assets/47088650/30506e18-3f65-431d-b57c-8c4e5ab932e5)

Sincerely
:-) Jens Hirsch

**Comment by jlaur** [comment]
@agricolaXIII - which version of openHAB and with which configured language in regional settings?

**Comment by agricolaXIII** [comment]
Hallo, my OpenHab-Version is 4.0.3 the Language: German (Germany) :-) Jens Am 06.11.23, 23:27 schrieb Jacob Laursen ***@***.***>:

   
  @agricolaXIII - which version of openHAB and with which configured language in regional settings?
