### ISSUE TITLE
[boschshc] intrusion-detection-system.active-configuration-profile is not updated

### ISSUE THREAD

**Issue by PLeusmann** [openhab/openhab-addons#15848]
## Expected Behavior
The Channel intrusion-detection-system.active-configuration-profile should return "0","1" or "2" depending on the  selected alarm type

## Current Behavior
Channel always returns "0"

## Possible Solution
`org.openhab.binding.boschshc.internal.devices.intrusion.IntrusionDetectionHandler.updateChannels(IntrusionDetectionControlState)` should be updated to 

```
private void updateChannels(IntrusionDetectionControlState controlState) {
        super.updateState(CHANNEL_ARMING_STATE, new StringType(controlState.value.toString()));
        super.updateState(CHANNEL_ACTIVE_CONFIGURATION_PROFILE, new StringType(controlState.activeProfile));
    }
```

## Your Environment
* openHAB 4.0.3
* Raspbian Bullseye

**Comment by david-pace** [comment]
Thanks for the detailed bug report @PLeusmann :+1: I created a pull request containing the suggested code.
