### ISSUE TITLE
[shelly] Ressource leak in case of successful ShellyPlusHT Discovery

### ISSUE THREAD

**Issue by xxthunder** [openhab/openhab-addons#15885]
## Expected Behavior
Successfully discovered and configured shellyplusht thing shall not cause an OOM exception.

## Current Behavior
When I connect and configure my shellyplusht in openHAB, the number of threads in openHAB's JVM is slowly but steadily rising until nothings works anymore after one or two days. What I investigated so far:

* When the shellyplusht is connected and configured as thing I see the following warning in my logs. I disconnected it last weekend and connected it again yesterday. You see this in the timestamps:

```shell
zgrep QueuedThreadPool /opt/docker/openhab/userdata/logs/*.gz
/opt/docker/openhab/userdata/logs/openhab.log.2.gz:2023-11-04 16:46:20.772 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.2.gz:2023-11-04 16:47:05.497 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.5.gz:2023-11-05 07:23:26.505 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.5.gz:2023-11-05 09:13:40.826 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.5.gz:2023-11-05 11:30:13.045 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.5.gz:2023-11-05 13:20:41.700 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.5.gz:2023-11-05 17:07:20.791 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-11 23:58:25.254 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-12 02:27:43.718 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-12 03:15:35.561 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-12 04:26:27.203 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-12 06:12:40.309 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
/opt/docker/openhab/userdata/logs/openhab.log.7.gz:2023-11-12 10:32:31.369 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - Stopped without executing or closing null
``` 

* In parallel when I connect VisualVM to openHAB's JVM I see constant rise of the number of threads. (number of threads almost doubles in 3.5h, see attached screenshots).

![image](https://github.com/openhab/openhab-addons/assets/2987157/55e29c28-ccd8-4dfd-928c-ac8ea770bcf0)

<img width="1128" alt="image" src="https://github.com/openhab/openhab-addons/assets/2987157/01a63930-5abd-46d5-b4e5-383976ab8317">

 
## Possible Solution
The only solution is to switch the shellyplusht off and delete the thing. (so this is not my favorite solution ;-) )

## Steps to Reproduce (for Bugs)
I switch my shellyplusht on by connecting it to USB-C power supply. It is already configured in my router and connected to my WLAN with a fixed IPv4 address. When I add the discovered thing via openHAB's web interface and connect two items for temperature and humidity the fun begins.

## Context
Nothing special.

## Your Environment
Latest openHAB stable (4.0.4) docker container running on an Raspberry Pi 4 (32 bit OS).

**Comment by markus7017** [comment]
please try latest DEV build or OH 4.1 version, this should be fixed in between

**Comment by xxthunder** [comment]
Hi @markus7017 ,

installed latest dev shelly binding yesterday, works like a charm.

Thanks and happy new year!
