### ISSUE TITLE
All official plugins do not show up in my openhabian OH4 installation anymore.

### ISSUE THREAD

**Issue by MarkusThur** [openhab/openhab-addons#15890]
Pretty easy:

I can't see any of the official plugins of OH4 in the webinterface anymore.. All commuinity addons are visible.

The installed official addons still work, but I neither can uninstall them, nor install any otherofficial addon..

I have no idea, where the system is broken, somehow it seems, that it lost the information, where to look for the official addons, while it still nows where to look for the community ones..

(obenhabian mit OH4.0.3)

--edit--
maybe obsolete, after update to OH 4.0.4-2

**Comment by MarkusThur** [comment]
Problem solved after two steps:

Update from 4.0.3 to 4.0.4, which ended with a entry in OH-log (the ones u can see via the openhab-cli command) saying some URL is missing..
stopping the OH.-service, 'openhab-cli clean-chache', starting the service solved the issue..
So most probably a cleaning of cache alone would have solved it also...

Suggestion: clean-cache should be executed from time to time automatically

**Comment by lsiepel** [comment]
Good to see you resolved the matter yourself! This is exactly one of those cases that the cli command was designed for.
