### ISSUE TITLE
[hue] color-temperature gets set to UNDEF for 3rd party ZigBee controller (API v2)

### ISSUE THREAD

**Issue by simonihmig** [openhab/openhab-addons#15926]
I have a few older GLEDOPTO GLC-C-008 controllers connected to my Hue bridge. They used to work fine until upgrading to OpenHab 4 and the API v2 bridge (not sure if the same thing happens on v1). Some newer models (I believe GLC-C-008P) don't observe that broken behavior luckily.

## Expected Behavior

The item bound to the `color-temperature` channel should not updated with an `UNDEF` value.

## Current Behavior

When playing with the Main UI and setting new values, they are getting sent to the Hue bridge and the color temperature is updated as expected. However, after some delay, there is a `onEventData` event (SSE?) coming in with a payload of `{"mirek":null,"mirek_valid":false}`. This seems to make the item's value get set to `UNDEF`. See the logs:

<details>
  <summary>TRACE log</summary>

```
18:22:42.331 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'LightRaisedBed_ColorTemp' changed from 59 to 59.12
18:22:42.335 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'color' update with '38.904,51.03800,96.84' (fullUpdate:false, isDefined:true)
18:22:42.342 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'color-xy-only' update with '38.904,51.03800,100' (fullUpdate:false, isDefined:true)
18:22:42.350 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'dimming-only' update with '96.84' (fullUpdate:false, isDefined:true)
18:22:42.356 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'on-off-only' update with 'ON' (fullUpdate:false, isDefined:true)
18:22:42.367 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'LightRaisedBed_Color' changed from 52.0122,10.95800,96.84 to 38.904,51.03800,96.84
18:22:42.400 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> handleCommand() put resource id:f04626d0-6194-4164-ac0f-3eb00323765a, type:light
18:22:42.405 [DEBUG] [e.internal.handler.Clip2BridgeHandler] - putResource() id:f04626d0-6194-4164-ac0f-3eb00323765a, type:light
18:22:42.401 [INFO ] [openhab.event.ItemCommandEvent       ] - Item 'LightRaisedBed_Color' received command 52,11,97
18:22:42.422 [INFO ] [openhab.event.ItemStatePredictedEvent] - Item 'LightRaisedBed_Color' predicted to become 52,11,97
18:22:42.424 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'LightRaisedBed_Color' changed from 38.904,51.03800,96.84 to 52,11,97
18:22:42.434 [TRACE] [g.hue.internal.connection.Clip2Bridge] - PUT https://192.168.100.72/clip/v2/resource/light/f04626d0-6194-4164-ac0f-3eb00323765a HTTP/2 >> {"type":"light","id":"f04626d0-6194-4164-ac0f-3eb00323765a","on":{"on":true},"dimming":{"brightness":97.0},"color":{"xy":{"x":0.3433,"y":0.3538}}}
18:22:42.370 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'alert' update with 'NO_ACTION' (fullUpdate:false, isDefined:true)
18:22:42.476 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'last-updated' update with '2023-11-19T18:22:42.476730066+0100' (fullUpdate:false, isDefined:true)
18:22:42.489 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> onResource() consumed resource id:f04626d0-6194-4164-ac0f-3eb00323765a, type:light
18:22:42.515 [TRACE] [g.hue.internal.connection.Clip2Bridge] - HTTP/2 200 (Content-Type: application/json) << {"data":[{"rid":"f04626d0-6194-4164-ac0f-3eb00323765a","rtype":"light"}],"errors":[]}
18:22:43.301 [TRACE] [g.hue.internal.connection.Clip2Bridge] - onEventData() data:[{"creationtime":"2023-11-19T17:22:42Z","data":[{"color":{"xy":{"x":0.3433,"y":0.3538}},"color_temperature":{"mirek":null,"mirek_valid":false},"id":"f04626d0-6194-4164-ac0f-3eb00323765a","id_v1":"/lights/27","owner":{"rid":"9f537a94-3adb-4fec-b8d7-22cb88c4ca85","rtype":"device"},"type":"light"}],"id":"540d0ad1-69ba-46cf-ba13-443d3575e67e","type":"update"}]
18:22:43.315 [DEBUG] [e.internal.handler.Clip2BridgeHandler] - onResourcesEventTask() resource count 1
18:22:43.327 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateChannels() from resource id:f04626d0-6194-4164-ac0f-3eb00323765a, type:light
18:22:43.334 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'color-temperature' update with 'UNDEF' (fullUpdate:false, isDefined:true)
18:22:43.336 [DEBUG] [ue.internal.handler.Clip2ThingHandler] - 9f537a94-3adb-4fec-b8d7-22cb88c4ca85 -> updateState() 'color-temperature-abs' update with 'UNDEF' (fullUpdate:false, isDefined:true)
18:22:43.338 [INFO ] [openhab.event.ItemStateChangedEvent  ] - Item 'LightRaisedBed_ColorTemp' changed from 59.12 to UNDEF
```
</details>

## Possible Solution

It seems there is some incompatibility of some sort here with that 3rd party controller and the Hue bridge, at least its API v2 AFAICT. And I guess we cannot do much about this, at the root of it. But can't we just ignore any updates coming in with `mirek_valid: false`? After all, the previous value that we have is always better than having `null`/`UNDEF`. 

## Steps to Reproduce (for Bugs)

Nothing I can provide here other than the logs above.

## Context

After getting `UNDEF`, the Main UI is kinda broken without reloading, as moving the Dimmer slider around does not cause any new values to be set. Also, this is likely not playing well with rules listening to changed values...

Btw, I am seeing some similar weirdness in the Hue app with those devices, as when setting the color temperature in the app, it "jumps" to some other (wrong) temperature value after a while. But in the app, the UI remains responsive.

## Your Environment

openHAB 4.0.4

**Comment by andrewfg** [comment]
I don’t think that is really a bug. The SSE event in which Mirek is null, also contains a ColorXY element, and probably the respective reported color simply does not lie on the color temperature line within the xy gamut.

**Comment by andrewfg** [comment]
![image](https://github.com/openhab/openhab-addons/assets/893994/cee9e312-5762-48bc-ae7e-c20099dc57ae)

**Comment by andrewfg** [comment]
So, in short, the work around for you is to use the Color HSB channel rather than the Color Temperature channel.

**Comment by simonihmig** [comment]
> the work around for you is to use the Color HSB channel rather than the Color Temperature channel

That does not really work. The device is a RGBCCT controller, connected to LED stripes which have dedicated cold white and warm white LEDs besides RGB. Only using the color temperature channel will make use of those. When I use a `Color` item, it'll use the RGB leds and that will never yield a proper white color.

**Comment by andrewfg** [comment]
> it'll use the RGB leds and that will never yield a proper white color.

Your problem is that your lamp is actually reporting a colour in XY space which is actually a non white colour; specifically the colour does not lie on the white line in the colour space; and if a colour is not on the white line in the colour space, that means that its colour temperature is indeed undefined.

The Hue bridge is telling us that mirek is null. This is not a bug in the binding. And there is nothing that the binding could do to change that.

**Comment by kiba-2020** [comment]
There seem to be a lot of RGB-CCT controllers with this misbehavior. What about the suggestion to simply ignore invalid values? (or at least have an option to do so automatically) This would fix the behavior of the MainUI that the slider for the color temperature is no longer operable. In the Android app, the last valid value would then simply remain set in the slider instead of jumping back and forth.
Such controllers will probably never be fixed, OpenHAB is often used to smooth out exactly such problems. Workarounds with a mirror-item are possible, but are very cumbersome and error-prone. Please re-evaluate.
