### ISSUE TITLE
[hue] Added or removed scenes in Philips Hue bridge are not updated in the APIv2 binding

### ISSUE THREAD

**Issue by hundertvolt** [openhab/openhab-addons#15936]
The Hue API v2 binding offers a feature which allows commanding a scene saved in the Hue Brigde (the Philips / Signify hardware, not the virtual bridge of OH ;-) )by its clear name (string) for scenes in a room or a zone. The names are even offered as suggestions in the OH GUI when creating a rule.
The issue I found is that once a Thing is created from a room or a zone, the scenes are never updated anymore. This was already discussed in the forum [here](https://community.openhab.org/t/philips-hue-clip-2-api-v2-discussion-thread/142111/387?u=hundertvolt1).

In my understanding, these clear names are being read out of the bridge when first time creating a Thing from a zone or a room. If scenes are added or removed later, leading to errors when commanding deleted or newly added scenes.

## Expected Behavior
When adding, renaming or deleting scenes in the  physical Hue bridge (e.g. with the original Hue app), these changes are updated (by whatever trigger) in the Thing linked to the room or zone, the suggestions in the GUI are reflecting the current state of the Hue Bridge.

## Current Behavior
The list of scenes stays the same as it was at creation time of the Thing. In the GUI, the names of deleted scenes remain, not suprisingly leading to errors when being called. New scenes are not added and are not commandable, even if the command contains the correct name.
A workaround to update the scenes is to first change the scenes in the physical Hue bridge, then inside OH delete the Hue room or zone Thing (while not touching the channel links at all), reboot OH, and after the reboot recreate the Things exactly as before (then the channel links come back to life). The reboot is actually required; if you leave it out, the Things are correctly found again by autodetection, but the old scenes are read from some cache instead of the real bridge, so nothing lost but nothing won.

## Possible Solution
Sync the scenes of existing Things with the Hue bridge by reading out the names from the API and updating the OH internal list.
A somewhat ideal solution would be if the APIv2 could actively callback when scenes are changed. 
At least to me, a regular polling feels imperfect no matter what you do - if you keep it up to date, it creates a heavy API load for values changing in weeks range, if you update it once per 15 minutes it's already dead slow if you're actively working on it.
So if there's no cool APIv2 solution, I'd opt for a trigger which is either pure and simple manual, or maybe it's triggered by a scene name command which produces an error.

## Steps to Reproduce (for Bugs)
Add new scenes to a Hue room or Hue zone which have an already existing binding to a Thing and command the new scene (sendCommand) by its name.

## Context
I added some scenes to my Hue system already with the goal of commanding them via a OH automation and was suprised that it did not work.

## Your Environment
openHABian 4.0.4 on a Raspberry Pi 4 / 8GB.
Chrome as access browser (Ubuntu machine).
Philips Hue Bridge v2 (the new square version, all updates installed) connected with physical Ethernet cables (no wifi).

**Comment by andrewfg** [comment]
It turns out that scenes ARE refreshed. So I am closing this now.
