### ISSUE TITLE
[pioneeravr] Update documentation for multizone support

### ISSUE THREAD

**Issue by SpaceMaster85** [openhab/openhab-addons#1594]
After the introduction of multizone support for the pioneeravr binding the documentation is outdated and wrong.
I posted my configuration already in the forum.
Please see [(https://community.openhab.org/t/pioneer-binding-update-dokumentation/18544](https://community.openhab.org/t/pioneer-binding-update-dokumentation/18544)

**Comment by kaikreuzer** [comment]
If you know what needs to be changed: Will you create a PR for it?

**Comment by SpaceMaster85** [comment]
I will make a PR within the next days

**Comment by wborn** [comment]
Is this still an issue @SpaceMaster85 ? Did your PR got merged some day?
