### ISSUE TITLE
[boschshc] Door/Window Contact II (New Version)

### ISSUE THREAD

**Issue by jkarsten** [openhab/openhab-addons#15954]
Hello,

i bought a Door/Window Contact II (New Version).
It is a zigbee Device (The App says this).
When i make a Scan it dosnt apear and in the openhab.log there is no new "Added new thing" 

I have openhab Version 4.1.0 Build 3738

Thank you for this wonderfull Binding.
Jörg

**Comment by david-pace** [comment]
Hi @jkarsten, thanks for the enhancement request. We will look into supporting the Door/Window Contact II in a future version.

Meanwhile you can already use the basic functionality by adding it as as "regular" Door/Window contact:

1. Obtain the ID of your door/window contact by looking at `openhab.log`. All device IDs are printed during startup. The ID should look like this: `hdm:ZigBee:[device ID]`
2. Manually add a new Thing of type Door/Window contact
3. Enter the ID from step 1 as device ID

Then you should be able to retrieve the open/close status and the battery status.

By the way, the next openHAB release will contain channels to listen to triggered scenarios and to trigger scenarios from openhab (see https://github.com/openhab/openhab-addons/pull/15752). This means that if you trigger scenarios with the buttons on your Door / Window Contact II, you will soon be able to react on them in openHAB as well.

**Comment by jkarsten** [comment]
Hello @david-pace, it works with Manually created Items.
First my openhab.log had no item from bosch. After i set the log level from info to debug i can see the IDs.
Thank you for this wonderfull Binding.
