### ISSUE TITLE
[tellstick] Binding doesn´t work any more.  Have to change api url to pa-api.telldus.com

### ISSUE THREAD

**Issue by dabj123** [openhab/openhab-addons#15987]
Telldus live have change the api url to pa-api.telldus.com. 

## Expected Behavior
Same as before but api have to change to pa-api.telldus.com.

## Current Behavior
same as before

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by ulfwin** [comment]
Would be great if this is fixed. Besides the new path, there are two also two new limitations that probably should be honored in the the binding, if not already (see https://telldus.com/driftinformation/ (swedish)):
1. Max 10 requests per minute
2. Retries must wait at least 10 seconds

If not implemented, the IP might be blocked.
