### ISSUE TITLE
[boschshc] User-defined states

### ISSUE THREAD

**Issue by pat-git023** [openhab/openhab-addons#16008]
Bosch added recently a new feature called [„User-defined states“](https://www.bosch-smarthome.com/uk/en/release-notes/bosch-smart-home-system/2023-11-20.html). With this states you can activate or deactivate your automation's based on the state. Receiving or setting this states in openHAB would enhance the system with a lot of new possibilities. For example if your presence detection in openHAB reports that you left your home you could automatically activate the intrusion detection and stop the heating in the Bosch System while you are away.

I already provided a pull request to enhance the openAPI spec with the new [endpoints](https://github.com/BoschSmartHome/bosch-shc-api-docs/pull/93)

@david-pace @GerdZanker 
How do you think about this feature?
What do you think how this would best fit in the current binding?

Best regards,
Patrick

![Bildschirmfoto 2023-12-04 um 09 58 16](https://github.com/openhab/openhab-addons/assets/54861416/2cb87cc8-0988-4f6c-bfc1-1593145e5f8c)

**Comment by david-pace** [comment]
Thank you very much for your pull request @pat-git023 :+1: I will test and review it as soon as I find some free time.
