### ISSUE TITLE
[shelly] - missing channels for shelly 1PM after adding as a thing

### ISSUE THREAD

**Issue by markdh1983** [openhab/openhab-addons#16009]
## Expected Behavior
 
these channels should show up 

![image](https://github.com/openhab/openhab-addons/assets/80985159/aaee2281-b43e-47e0-9deb-a8ee4ee9e22f)

## Current Behavior

after adding the shelly 1PM as a thing not all expected channels are showing up

![image](https://github.com/openhab/openhab-addons/assets/80985159/84c2546e-b923-4698-97a7-e2cdf0f9fd0d)

## Your Environment

* Version used: openHAB 4.0.4

**Comment by markdh1983** [comment]
factory reset helped

**Comment by markus7017** [comment]
ok :-)
