### ISSUE TITLE
[miio] Roborock "Cleaning Start" shows "Cleaning End"

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-addons#16005]
A DateTime-Item linked to channel "Cleaning Start" does show "Cleaning End". Both channels show same time.
I have seen this in openHAB 4.1.0.M3 and 4.1.0.M4. In openHAB 4.0.4 everything is OK.

Thing Type: Xiaomi Robot Vacuum

**Comment by marcelrv** [comment]
can you share a debug log to see the responses and what is going wrong in the parsing.

note this field is only refereshed after a cleaning or at binding start, so the log  should be ' timed'  to capture this bit of the communication
