### ISSUE TITLE
[tplinksmarthome] Add support for EP25

### ISSUE THREAD

**Issue by mikeseese** [openhab/openhab-addons#16027]
As listed in the [addon](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.tplinksmarthome/src/main/resources/OH-INF/thing) there isn't support for EP25, however I believe that the [EP25 is essentially the same as the KP125](https://community.tp-link.com/us/smart-home/forum/topic/557220?replyId=1105388) and the xml should just be a copy/paste

**Comment by Hilbrand** [comment]
Until added the workaround is to manual use a KP125 thing to control the EP25. If it works the same as the KP125 this should work.

**Comment by joshproehl** [comment]
I can confirm that creating a manual KP125 device with the IP address of the EP25 seems to work fine. Of course auto-discovery does not work, and this requires the device being manually assigned a fixed IP address on the router to remain stable. 

If there's anything I can do to further test this and support getting the EP25 added as a supported device please let me know.
