### ISSUE TITLE
[deconz] Binding suggestion not working

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#16036]
The deCONZ binding is not suggested for me.

## Expected Behavior
The UPnP discovery should find my deCONZ installation and suggest the binding.

## Current Behavior
The binding is not suggested.

## Possible Solution
I have the following properties:

![image](https://github.com/openhab/openhab-addons/assets/19519842/0c0f9ca2-c2cd-4aa2-b1ed-aa970c706b96)

The metadata:
https://github.com/openhab/openhab-addons/blob/8c560a409c5a79c6f935b14b9acb64600fccd0cb/bundles/org.openhab.binding.deconz/src/main/resources/OH-INF/addon/addon.xml#L16-L25

It seems it could be matched by Manufacturer URL (or model URL), I'm not sure if related to "Manufacturer URL" vs. "manufacturerURI"?

The discovery does find it:

![image](https://github.com/openhab/openhab-addons/assets/19519842/06c87eea-6cc9-420f-b28c-a7ee42e7c49d)

So this seems to work:
https://github.com/openhab/openhab-addons/blob/9f4b8a6cb7d8c30aabcbc251fc5f7797e41800b2/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/discovery/BridgeDiscoveryParticipant.java#L87-L94

## Your Environment
* Version used: 4.1.0-SNAPSHOT build 3763

**Comment by jlaur** [comment]
FYI @J-N-K, @lolodomo, @mherwege, @andrewfg. I don't know if the shown property from Device Spy is "pretty printed" or actual property names, so not sure how to properly fix this.

**Comment by andrewfg** [comment]
> not sure how to properly fix this.

Not sure either. One hypothesis is that the regex `.*dresden.*` may not be correct for matching `http://www.dresden-elektronik.de` due to the '.' prefix or the '-' suffix .. or even the '//' separator ??

**Comment by mherwege** [comment]
Does a trace log of org.openhab.core.config.addon give any hint?

**Comment by andrewfg** [comment]
I am suspecting an issue of character encoding in the URI.toString() method. I which case the following change might fix it. Just a thought..

```
                        ManufacturerDetails mfrDetails = devDetails.getManufacturerDetails();
                        if (mfrDetails != null) {
                            URI mfrUri = mfrDetails.getManufacturerURI();
                            manufacturer = mfrDetails.getManufacturer();
// change this line
                            manufacturerURI = mfrUri != null ? mfrUri.toString() : null;
// to this
                            manufacturerURI = mfrUri != null ? mfrUri.getHost() : null;
                        }
```

**Comment by andrewfg** [comment]
But then again, it may simply be that JUpnp is not discovering the deconz device (yet). @jlaur you say that the thing discovery does work while OH is running; however it is possible that deconz is a 'late responder' so has not yet been discovered during the startup phase. => So try waiting a while and look for it in the Add-on Store instead.

**Comment by mherwege** [comment]
> But then again, it may simply be that JUpnp is not discovering the deconz device (yet). @jlaur you say that the thing discovery does work while OH is running; however it is possible that deconz is a 'late responder' so has not yet been discovered during the startup phase. => So try waiting a while and look for it in the Add-on Store instead.

@jlaur To analyze this further, one would really need a trace log.
The moment the device is discovered in the network, there should be a trace log entry from the `org.openhab.core.config.discovery.addon.upnp` package, something like `Added device: displayString` where displayString is probably the friendly name. If this log entry does not apear, the issue is not with the finder. And as @andrewfg indicates, it may just be a timing issue. If it appears, but still is not suggested, there is a problem in the finder service code.

**Comment by jlaur** [comment]
@mherwege - sure, of course, I will produce a trace log, just didn't find the time yet. I plan to do it in the evening today. Btw, it was from Add-on Store.

**Comment by jlaur** [comment]
@mherwege - indeed it doesn't show up as a "[discovery.addon.upnp.UpnpAddonFinder] - Checking device: " entry in the log even hours after starting openHAB, so this problem should probably be hunted elsewhere.

**Comment by andrewfg** [comment]
> it doesn't show up as a "[discovery.addon.upnp.UpnpAddonFinder] - Checking device: " entry in the log even hours after starting openHAB

@jlaur you wouldn’t expect to see a message with the word ‘checking’ in it; the actual log line to look for is below..

https://github.com/openhab/openhab-core/blob/5ffeb1fc724c1c7eefc4f7e2f75119ade69c0cad/bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java#L112

**Comment by andrewfg** [comment]
@jlaur a question: is this ‘deconz’ device an actual physical device? i.e. something with an actual ip address on your LAN? Or is it a simulated device of some sort, that runs on the same PC as OH .. i.e. what one might call a ‘local device’?

https://github.com/openhab/openhab-core/blob/5ffeb1fc724c1c7eefc4f7e2f75119ade69c0cad/bundles/org.openhab.core.config.discovery.addon.upnp/src/main/java/org/openhab/core/config/discovery/addon/upnp/UpnpAddonFinder.java#L214C5-L214C5

**Comment by jlaur** [comment]
> a question: is this ‘deconz’ device an actual physical device? i.e. something with an actual ip address on your LAN?

Yes, it's a separate Raspberry Pi on the LAN (wired) and on the same subnet. The strange thing is that it's correctly discovered, and I can also see it in Device Spy.

**Comment by andrewfg** [comment]
@jlaur for the avoidance of doubt, do you see any 'Added device:' messages in the log for any other devices on your LAN (i.e. not deconz devices)?

I saw from your screen shot that the deconz is masquerading as a Hue bridge, so you might confuse the "Added device" log entry with a very similar one coming from your real Hue bridge. So can you perhaps try removing the real Hue bridge from the network?

**Comment by jlaur** [comment]
> for the avoidance of doubt, do you see any 'Added device:' messages in the log for any other devices on your LAN (i.e. not deconz devices)?

Yes.

> I saw from your screen shot that the deconz is masquerading as a Hue bridge, so you might confuse the "Added device" log entry with a very similar one coming from your real Hue bridge. So can you perhaps try removing the real Hue bridge from the network?

That could indeed be the case, I'll try that in the evening.

**Comment by andrewfg** [comment]
^
In particular if the deconz is masquerading the same UDN (unique device number) then it is not going to appear as a unique upnp device.

**Comment by jlaur** [comment]
@andrewfg - I disconnected the Hue Bridge, and it is still suggested (and deCONZ still not):
```
2023-12-12 18:25:20.463 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Added device: Royal Philips Electronics Philips hue bridge 2015 BSB002
```

So it seems that there are at least the issue that this:
https://github.com/openhab/openhab-addons/blob/f45630064a4959c294ac01f9835df68190ac875d/bundles/org.openhab.binding.hue/src/main/resources/OH-INF/addon/addon.xml#L16-L24

will match deCONZ via UPnP from the model name:

![image](https://github.com/openhab/openhab-addons/assets/19519842/f65f717e-f4fb-4c9f-b559-82d260d0244d)

The Hue bridge itself:

![image](https://github.com/openhab/openhab-addons/assets/19519842/d7a716f3-f5f7-495b-98ae-cc5896292de9)

Maybe we could avoid this by adding some other properties, but we would need to be sure that we do not exclude the old V1 bridge. Maybe @lolodomo can post the properties for that? Still, even without any enhancement it's not a big issue to have it suggested. FYI also @mherwege

**Comment by jlaur** [comment]
@andrewfg - I have built and replaced org.openhab.core.config.discovery.addon.upnp-4.1.0-SNAPSHOT.jar in my installation of latest snapshot from openhab/openhab-core#3918 and now see:

```
2023-12-12 18:47:51.297 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Added device: Signify Philips hue bridge 2015 BSB002
2023-12-12 18:47:51.298 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Added device: Royal Philips Electronics Philips hue bridge 2015 BSB002
```

The last one must be deCONZ? But still no suggestion.

I also noticed:
```
2023-12-12 18:48:01.135 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking candidate: binding-deconz
2023-12-12 18:48:01.136 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Sonos, Inc. Sonos Arc S19
2023-12-12 18:48:01.136 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Synology Inc DS918+
2023-12-12 18:48:01.136 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Miele & Cie. KG XGW3000
2023-12-12 18:48:01.136 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Samsung Electronics UE55D8000 1.0
2023-12-12 18:48:01.138 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Signify Philips hue bridge 2015 BSB002
2023-12-12 18:48:01.140 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Google Eureka Dongle
2023-12-12 18:48:01.140 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Royal Philips Electronics Philips hue bridge 2015 BSB002
2023-12-12 18:48:01.140 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Sonos, Inc. Sonos Move 2 S44
2023-12-12 18:48:01.141 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Synology DS918+ DS918+ 7.2-64561
2023-12-12 18:48:01.141 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Samsung Electronics UE55D8000 1.0
2023-12-12 18:48:01.141 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking candidate: binding-hue
2023-12-12 18:48:01.142 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Sonos, Inc. Sonos Arc S19
2023-12-12 18:48:01.142 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Synology Inc DS918+
2023-12-12 18:48:01.142 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Miele & Cie. KG XGW3000
2023-12-12 18:48:01.143 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Samsung Electronics UE55D8000 1.0
2023-12-12 18:48:01.143 [TRACE] [discovery.addon.upnp.UpnpAddonFinder] - Checking device: Signify Philips hue bridge 2015 BSB002
2023-12-12 18:48:01.143 [DEBUG] [discovery.addon.upnp.UpnpAddonFinder] - Suggested addon found: binding-hue
```

**Comment by jlaur** [comment]
I tried to change the XML for deCONZ to:
```xml
	<discovery-methods>
		<discovery-method>
			<service-type>upnp</service-type>
			<match-properties>
				<match-property>
					<name>manufacturerURI</name>
					<regex>.*dresden.*</regex>
				</match-property>
			</match-properties>
		</discovery-method>
		<discovery-method>
			<service-type>upnp</service-type>
			<match-properties>
				<match-property>
					<name>manufacturer</name>
					<regex>dresden elektronik</regex>
				</match-property>
			</match-properties>
		</discovery-method>
	</discovery-methods>
```

And now it's suggested:

![image](https://github.com/openhab/openhab-addons/assets/19519842/432f2100-e142-429a-acb2-2321454ff92c)

Is it correct that all match-properties for a discovery-method are AND'ed? In that case it would explain why it didn't work for me, because I don't have "dresden elektronik" as manifacturer.

**Comment by andrewfg** [comment]
> all match-properties for a discovery-method are AND'ed?

Yes. Within a discovery method each match property restricts the search further. i.e. AND

By contrast, if you want an OR function then you can add more discovery methods.

**Comment by andrewfg** [comment]
@jlaur as you have both devices, can I please leave it to you to fix both the real Hue and the deconz Hue so that they are mutually compliant?
