### ISSUE TITLE
[jsscripting] <item>.PostUpdate() and Quantity() in JS rules do not support Strings using scientific notation

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#16034]
I've implemented a rule, where `<item>.history.deltaSince()` returns a very small number `-1e-10` (almost `-0.0`).
In a next step I would like to update an Item of type `Number:Energy`.

When using the following syntax, it fails because the implicit `toString()` returns a string in scientific notation:
```
const value = -1e-10;
items.Inverter_Energy_Today.postUpdate(value + " Wh");
```

`[WARN ] [rnal.defaultscope.ScriptBusEventImpl] - State '-1e-10 Wh' cannot be parsed for item 'Inverter_Energy_Today'.`

The following doesn't work as well:
```
const value = -1e-10;
const qnt = Quantity(value + " W*h");
items.Inverter_Energy_Today.postUpdate(qnt);
```

```
[ERROR] [hab.automation.script.file.energy.js] - Failed to execute rule Inverter_ToFromGrid_Power: QuantityError: Failed to create QuantityType from -1e-10 W*h: java.lang.IllegalArgumentException: Invalid Quantity value: -1e-10 W*h: QuantityError: Failed to create QuantityType from -1e-10 W*h: java.lang.IllegalArgumentException: Invalid Quantity value: -1e-10 W*h
	at o (@openhab-globals.js:2)
	at O (@openhab-globals.js:2)
	at c (@openhab-globals.js:2)
	at getQuantity (@openhab-globals.js:2)
	at execute (energy.js:590)
	at execute (@openhab-globals.js:2)
```

Workarounds for my use-case (number almost zero):

```
const value = -1e-10;
items.Inverter_Energy_Today.postUpdate(value.toFixed() + " Wh");
```

or 

```
const value = -1e-10;
const qnt = Quantity(value.toFixed() + " W*h");
items.Inverter_Energy_Today.postUpdate(qnt);
```

See [stackoverflow.com](https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript) regarding the full complexity on JS and numbers in scientific notation.

The usage of the scientific notation is quite unpredictable and therefore error-prone.
Can the js `Quantity` type as well as `<item>.postUpdate()` and other APIs support `strings` in scientific notation in order to be more robust?

## Your Environment
* openHAB 4.0.4
* JavaScript Scripting rules

**Comment by florian-h05** [comment]
The openHAB JavaScript library of the JavaScript automation add-on is only wrapping openHAB core functionality to provide pure JS APIs.
So this is no JS issue, but a openHAB core issue.

Also have a look at https://github.com/openhab/openhab-core/issues/3883.
There the REST API is used, but I guess the code to parse the string is the same as for postUpdate.

Can you please open a core issue for that?
