### ISSUE TITLE
[fronius] Add Setpoint to enable/disable charging from grid (ChaGriSet)

### ISSUE THREAD

**Issue by biggestcrunch** [openhab/openhab-addons#16086]
It would be very helpful for the use of a dynamic energy price like Tibber to have read and write access to the Register 40331 (ChaGriSet).

**Comment by jimtng** [comment]
Got any more details or link to related documentation?

**Comment by biggestcrunch** [comment]
[Fronius DM Modbus TCP & RTU.pdf](https://github.com/openhab/openhab-addons/files/13727450/Fronius.DM.Modbus.TCP.RTU.pdf)

My feature request is about the functions and informations from page 94 to 97.
Especially the part "ChaGriSet"

**Charging the energy storage via the grid**

The ChaGriSet register can be used to allow or prevent inverter storage charging via the
grid. The register ChaGriSet and the field "battery charging from DNO grid" in the Fronius system monitoring settings are AND-linked (Fronius system monitoring - Settings -
DNO Editor - Battery charge). If the behavior is to be controlled by the ChaGriSet flag,
"battery charging from DNO grid" must be checked.
The battery can be woken from standby mode via the IC124 model. If the SocMin under
the last known SoC is set while the battery is in standby mode, this will be enabled.

**Comment by jimtng** [comment]
The fronius binding doesn't communicate through Modbus.

**Comment by biggestcrunch** [comment]
Isnt it via Modbus TCP?

**Comment by bahnwaerter** [comment]
No, the Fronius binding uses the [Fronius Solar API V1](https://www.fronius.com/en/solar-energy/installers-partners/technical-data/all-products/system-monitoring/open-interfaces/fronius-solar-api-json-) as stated in the binding's README. The Fronius Solar API V1 is a RESTful API to query Fronius inverters and other components (e.g., smart meters). This API can be accessed via HTTP over TCP, but has nothing to do with the Fronius Modbus TCP interface. One would have to implement another binding that supports the Modbus TCP interface to read and write your desired register value.

**Comment by bahnwaerter** [comment]
#16047

**Comment by lsiepel** [comment]
As it is a deuplicate and modbus i guess it is better to continue discussion in #16047
