### ISSUE TITLE
[EVCC] API changed from loadpoint to vehicles

### ISSUE THREAD

**Issue by Barnecke** [openhab/openhab-addons#16098]
## Expected Behavior
With evcc Release 0.123.0 there is a general change in the API. Vehicles are used instead of loadpoints.

## Current Behavior
With Release 0.122.x the openhab binding called API with loadpoint, which causes 404 now. E.g:

> 2023-12-22 21:57:00.628 [TRACE] [ab.binding.evcc.internal.api.EvccAPI] - POST http://localhost:7070/api/loadpoints/1/target/soc/85 - 404 page not found

## Possible Solution
Adjust evcc binding based on the new API. I found this https://github.com/evcc-io/evcc/discussions/10978

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: OH 4.1.0 M4, EVCC 0.123.0
* Operating System: RPI4

**Comment by lucaarn** [comment]
the new api uses both loadpoints and vehicles. Vehicles are now used for:
- vehicle specific maxSoC that should be used when the vehicle is connected to the loadpoint
- specific minSoC, same as maxSoC
- SoC-Plans are now controlled via vehicles

the maxSoC can still and should still be set via the loadpoint (addresses for some api calls changed)

I will open a pull request later where I updated the whole evcc binding to current version 0.123.1

**Comment by Barnecke** [comment]
@lucaarn great job, your fix is working with the new Thing limitSoC. Thx
