### ISSUE TITLE
REST API Docs: Too many fields required

### ISSUE THREAD

**Issue by sja** [openhab/openhab-addons#161]
Nearly all fields are marked as required in swagger. For example GET /items requires the parameter "tags" and "type". Thats not true, I can query without those criteria.

On the first look I did not see how to achieve this. Give me a hint in the comments below and I can do the code changes.

**Comment by kaikreuzer** [comment]
I noticed this as well already and would like to get rid off it. I didn't look into it either yet though, hence I cannot give any advice on how to fix it...

**Comment by sja** [comment]
The parameters which have default values are handled correctly. But `@DefaultValue(null)` is not possible and ugly.

**Comment by kaikreuzer** [comment]
Somehow the entries on http://localhost:8080/doc/index.html do not expand anymore at all - @sja, do you have any good idea what might be wrong here?

**Comment by kaikreuzer** [comment]
According to http://stackoverflow.com/questions/13968261/required-queryparam-in-jax-rs-and-what-to-do-in-their-absence, there are no required query params for JAX-RS. I have therefore changed Swagger to always consider parameters to be optional.

**Comment by sja** [comment]
Oh no. Thats really bad for generating clients from swagger api, but anyhow thanks for inquiry.
