### ISSUE TITLE
[nuki] Bridge Callback set to wrong IP when using managed bridge calbacks on a docker deploy

### ISSUE THREAD

**Issue by MathiasVDA** [openhab/openhab-addons#16113]
## Expected Behavior
I expect callbacks to work on any type of deployment or that a documentation entry is made to warn users when deploying with Docker.

## Current Behavior
This is the current 
`2023-12-25 22:54:16.653 [DEBUG] [i.internal.handler.NukiBridgeHandler] - Successfully added callbackUrl[http://172.17.0.1:8080/nuki/bcb?callbackId=fd49dfb1-6cbd-4975-8849-70138d5863e7] on Bridge[192.168.10.9]!`

## Possible Solution
Multiple solutions are possible:
- Make sure Openhab sends the correct IP address 
- Make it possible to set the callback IP in the Thing bridge settings.

## Steps to Reproduce (for Bugs)
1. Deploy openhab using Docker
2. Install the Nuki binding
3. Configure a bridge with managed callbacks = true
4. Configure a smartlock
5. Set the log level `log:set TRACE org.openhab.binding.nuki`
6. Tail the log for the relevant callback log trace
7. Disable and enable the bridge thing to initiate a new callback and take a look at the trace log

## Context
-

## Your Environment
Openhab 4.1 deployed using the official Docker image.

**Comment by lolodomo** [comment]
What I understand from the code is that it uses the primary IP v4 address you setup in the OH network settings.
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/NukiHandlerFactory.java#L109
Did you setup this setting properly?

**Comment by MathiasVDA** [comment]
Indeed @lolodomo, I wasn't aware of the network settings page. Up until now I haven't needed to use it. I will make a change request on the documentation of the Nuki bridge to add this information.

**Comment by lolodomo** [comment]
Note that without this primary IP v4 address set, the nuki binding is logging a warning: "No network interface could be found to get callback address"
