### ISSUE TITLE
[ecovacs] Add support for Ecovacs DEEBOT T20e OMNI

### ISSUE THREAD

**Issue by aaxxeell** [openhab/openhab-addons#16121]
Ecovacs Binding for Openhab
Adding support for Ecovacs DEEBOT T20e OMNI - is the matter of this robot model extension request.

The binding works, the bridge is online, I get the following message::
23:11:09.524 [INFO ] [vacs.internal.api.impl.EcovacsApiImpl] - Found unsupported device DEEBOT T20e OMNI (class 9ku8nu, company eco-ng), ignoring.

## Your Environment
openhabian -> OH4.1.0

Merry Xmas!

**Comment by maniac103** [comment]
I'll add it to the DB once #16187 is fixed.
