### ISSUE TITLE
[sonos] Add Support For Sonos Sub Mini To Sonos Binding

### ISSUE THREAD

**Issue by msw1970** [openhab/openhab-addons#16125]
As per title.... Sonos binding doesn't appear to currently support the Sonos Sub Mini. On startup the following log message is received...

`2023-12-27 19:35:09.698 [WARN ] [overy.ZonePlayerDiscoveryParticipant] - 'Sonos Sub Mini' is not yet a supported model, thing type 'sonos:zoneplayer' is considered as default; please open an issue`

Your Environment
* Version used: OpenHAB 4.0.4, Sonos Binding 4.0.4

**Comment by lolodomo** [comment]
The sub is a "special" device that is associated to a main device (or a pairs).
You do not expect to get an openHAB thing linked to it.
So the change will be to avoid such a warning for a sub device.
