### ISSUE TITLE
[jdbc] REST API - Issue to request data of JDBC persisted item when there is a digit in Item Name 

### ISSUE THREAD

**Issue by LuiSauberhorn** [openhab/openhab-addons#16126]
## Expected Behavior
When having an item that is persisted via JDBC using mariadb and containing a digit, it should behave like all other items that do not contain a digit. When I request data for a time windows via rest API, I expect to get the corresponding data as json reply.
 
## Current Behavior
Instead, when requesting data of such with a digit in it via REST API, an empty data set is returned and three error messages are logged. That can be reproduced with arbitrary item names containing a digit.

Following item is specified:
```
Switch      http_external_pegelstand_rhein_hochwasser06MOnOff  "Pegelstand in Bonn - Hochwassermarke 6m"
```

Following request is called:
```
https://<SERVER>/rest/persistence/items/http_external_pegelstand_rhein_hochwasser06mOnOff?serviceId=jdbc&starttime=2023-12-24T22%3A19%3A09.228Z&endtime=2023-12-27T22%3A19%3A09.228Z&boundary=true
```

Return value is:
```
{"name":"http_external_pegelstand_rhein_hochwasser06mOnOff","datapoints":"0","data":[]}
```

The following log is generated in openhab.log:
```
2023-12-27 23:28:35.651 [ERROR] [jdbc.internal.JdbcPersistenceService] - JDBC::query: unable to get item for itemName: 'http_external_pegelstand_rhein_hochwasser06mOnOff'. Ignore and give up!
2023-12-27 23:28:35.651 [ERROR] [jdbc.internal.JdbcPersistenceService] - JDBC::query: unable to get item for itemName: 'http_external_pegelstand_rhein_hochwasser06mOnOff'. Ignore and give up!
2023-12-27 23:28:35.652 [ERROR] [jdbc.internal.JdbcPersistenceService] - JDBC::query: unable to get item for itemName: 'http_external_pegelstand_rhein_hochwasser06mOnOff'. Ignore and give up!
```

However, the database contains the following data:
```
select * from items where ItemName = 'http_external_pegelstand_rhein_hochwasser06mOnOff';
+--------+--------------------------------------------------------+
| ItemId | ItemName                                               |
+--------+--------------------------------------------------------+
|    770 | http_external_pegelstand_rhein_hochwasser06MOnOff |
+--------+--------------------------------------------------------+

select * from item0770;
+-------------------------+-------+
| time                    | value |
+-------------------------+-------+
| 2023-12-25 15:58:46.682 | ON    |
| 2023-12-25 15:58:50.529 | OFF   |
| 2023-12-25 16:18:26.408 | ON    |
| 2023-12-26 11:52:43.066 | OFF   |
| 2023-12-26 11:52:48.452 | ON    |
+-------------------------+-------+
```

All other items are working well. When replacing different parts of the item name, the behavior changes once I replace the digits in the item name. 

## Steps to Reproduce (for Bugs)
Create item with a digit, make it part of persistence config and try out. Please note: I did not check whether this is a general problem or only JDBC / mariadb related. If that helps, I can check, please let me know.

## Your Environment

1. Intel NUC i3, 32GB RAM, 2TB HHD
2. Debian 12
3. openHAB 4.1.0, Release Build
4. JS, Chrome and Safari tested

Please let me know in case you need more.

**Comment by jlaur** [comment]
@LuiSauberhorn - can you check if:
```
https://<SERVER>/rest/persistence/items/http_external_pegelstand_rhein_hochwasser06MOnOff?serviceId=jdbc&starttime=2023-12-24T22%3A19%3A09.228Z&endtime=2023-12-27T22%3A19%3A09.228Z&boundary=true
```

works?

Item names are case-sensitive.

**Comment by jlaur** [comment]
See above. Feel free to re-open if in fact you can reproduce an issue with digit in item names. I have plenty those and they are persisted just fine in MySQL. 😉
