### ISSUE TITLE
[tellstick] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16139]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's addon.xml file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by lsiepel** [comment]
tellstick as no active maintainer, so maybe it is better to ask in the communities for an active user to confirm and or list usb details?

**Comment by wborn** [comment]
I think it uses `1781:0c31` after a bit of Googling. However the binding is broken, see https://github.com/openhab/openhab-addons/issues/15987.

**Comment by andrewfg** [comment]
> I think it uses 1781:0c31 after a bit of Googling

Ok. As there is no active maintainer I could raise a PR to add that.

> the binding is broken, see https://github.com/openhab/openhab-addons/issues/15987

@wborn is that a subtle hint that I should try to fix also in my PR? I do not use this binding so the fix would be rather 'ad hoc' though. Is that Ok?

**Comment by lsiepel** [comment]
I think that is ok, there seem to be atleast two people in the other thread that might offer to test a fix. I don't have the stick, so i can;t test, but can review the code.

**Comment by wborn** [comment]
> is that a subtle hint that I should try to fix also in my PR?

Users may be disappointed when they are suggested to install a broken binding. :wink: 

Maybe @dabj123 or @ulfwin can provide the output of `lsusb -v`?

**Comment by ulfwin** [comment]
I'm afraid I only have tellstick net and znet, which connects through Ethernet...

**Comment by dabj123** [comment]
Ah sorry, I only have tellstick which connects through Ethernet...

**Comment by andrewfg** [comment]
@wborn @lsiepel see #16220

**Comment by andrewfg** [comment]
Closed via #16228
