### ISSUE TITLE
[openwebnet] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16136]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's addon.xml file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by lsiepel** [comment]
@mvalla can you confirm that an usb device is used and if possible list the usb details `lsusb -v`?

**Comment by mvalla** [comment]
Yes I confirm the bindng integrates also one type of gateway which is a [serial-USB stick to control BTicino/Legrand Zigbee devices via Openwebnet protocol](https://www.legrand.be/fr/catalogue/zigbee-interface-openzigbee-3578); however it uses a closed Zigbee protocol variant making the system BTicino/Legrand only.

I myself use this gateway for my home syetem, however it's impotant to note that:
- the product is not sold anymore
- it was a very special-case product, maybe even ahead of the Zigbee success, but much less popular than the wired BUS BTicino MyHOME system (also supported by this binding). Therefore I think it was installed in very few households mainly in Italy/France, before the new [BTicino Living Now](https://www.bticino.com/living-now/3modules/what-it-can-do/) (this time based on Zigbee 3.0) product line has been launched on the market, making this gateway and related devices obsolete.

Another issue is that the gw USB device is recognized as generic **Silicon Labs CP2102 USB to UART Bridge**, so it could be confused with other devices based on the same chipset.

Anyway - just for curiosity - I could try and test the USB add-on suggestion. 

The following is the output of `lsusb -v`:

```
Bus 001 Device 003: ID 10c4:ea60 Silicon Labs CP210x UART Bridge
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x10c4 Silicon Labs
  idProduct          0xea60 CP210x UART Bridge
  bcdDevice            1.00
  iManufacturer           1 Silicon Labs
  iProduct                2 CP2102 USB to UART Bridge Controller
  iSerial                 3 0001
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              2 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
```

**Comment by andrewfg** [comment]
> USB device is recognized as generic Silicon Labs CP2102 USB to UART Bridge, so it could be confused with other devices based on the same chipset

Ok. Closing this issue to avoid false positives
