### ISSUE TITLE
[meteostick] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16138]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's addon.xml file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by lsiepel** [comment]
@cdjackson can you confirm that an usb device is used and if possible list the usb details `lsusb -v`?

**Comment by cdjackson** [comment]
Yes, it's a USB stick, but I no longer have this device - sorry.

**Comment by wborn** [comment]
It's also using a FTDI chip, see the output here:

https://community.openhab.org/t/solved-oh3-meteostick-stuck-in-status-unknown/114225

**Comment by andrewfg** [comment]
> It's also using a FTDI chip
