### ISSUE TITLE
[mihome] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16134]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's `addon.xml` file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by lsiepel** [comment]
What binding do

**Comment by wborn** [comment]
> It looks like this binding depends on a USB stick to connect to OH

I think it's using a Wi-Fi gateway that uses ZigBee to communicate with the devices, see: 

https://www.openhab.org/addons/bindings/mihome

**Comment by andrewfg** [comment]
> it's using a Wi-Fi gateway 

Ok. Closing this.
