### ISSUE TITLE
[deconz] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16135]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's addon.xml file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by J-N-K** [comment]
No, that's not correct. It requires a running deconz server, which MAY connect to the ZigBee network via a ConBee (USB) stick. There is also a RaspBee (a shield for RPis) to do that and the server can be on another system, so even if the USB stick is used, it can be connected to another system than the one OH is running on.
