### ISSUE TITLE
[plugwise] support add-on suggestions via USB finder

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16133]
It looks like this binding depends on a USB stick to connect to OH (??) so in theory the binding could be automatically suggested via the core USB add-on suggestion finder. If that is the case, it simply needs the respective discovery-methods to be added to the binding's `addon.xml` file.

Signed-off-by: Andrew Fiddian-Green <software@whitebear.ch>

**Comment by lsiepel** [comment]
@wborn as you are codeowner for this binding, do you own the plugwise zigbee stick?
I can also create a PR with these details, but i only have the PlugwiseHA system and am not sure if that Adam holds the same zigbee stick.

**Comment by wborn** [comment]
Yes I have the stick but it is uses 0403:6001 like so many other sticks, see https://github.com/openhab/openhab-addons/issues/4421.

**Comment by lsiepel** [comment]
So @andrewfg if this id is the only information to base the discovery on, it is hard to decide to include it or not. If plugwise is included we might generate many false positives, i guess this applies to many other bindings that use usb discovery too.

Could this setup discovery also take other information into account? Like the country tag in the addons.xml as Plugwise is mainly focused to dutch and belgian market?

**Comment by andrewfg** [comment]
> stick but it is uses 0403:6001 like so many other sticks
> Could this setup discovery also take other information into account?

@wborn / @lsiepel - it may be that the stick uses this very common OEM chip (with chipId 0403:6001) but perhaps the manufacturer of the stick itself wrapped it with their own 'manufacturer' or 'product' description texts? In which case we can search on those (hopefully less generic) texts rather than using the (generic) chipId. => Can you please let me know what 'manufacturer' or 'product' description texts appear on your system?

**Comment by wborn** [comment]
Unfortunately nothing specific.

`lsusb -v` shows:

```
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x0403 Future Technology Devices International, Ltd
  idProduct          0x6001 FT232 Serial (UART) IC
  bcdDevice            6.00
  iManufacturer           1 FTDI
  iProduct                2 FT232R USB UART
...
```

**Comment by andrewfg** [comment]
> lsusb -v shows:

Does `dmesg` show anything different?

**Comment by wborn** [comment]
It's just as generic in Windows as it is in Linux:

![image](https://github.com/openhab/openhab-addons/assets/12213581/5ee0eabc-8a61-4e5e-9bcc-9b427ab4fb38)

**Comment by andrewfg** [comment]
@wborn thanks for testing. I think this means that we shall have to close this issue. Nobody wants to have false positives from generic chips.

**Comment by wborn** [comment]
`dmesg` also shows its version of own version of the genericness:

```
[23734.405579] ftdi_sio 1-2:1.0: FTDI USB Serial Device converter detected
[23734.405616] usb 1-2: Detected FT232R
[23734.406180] usb 1-2: FTDI USB Serial Device converter now attached to ttyUSB0
```

**Comment by lsiepel** [comment]
Maybe a last question before this is closed. Do you know if there is only one stick? Or did Pluwise ship different versions/revisions?

**Comment by wborn** [comment]
AFAIK there is only one type of Stick.
I have 2 of them and they both identify as FTDI device.

This has advantages and disadvantages according to:

https://www.ftdichip.com/Support/Documents/TechnicalNotes/TN_100_USB_VID-PID_Guidelines.pdf

![image](https://github.com/openhab/openhab-addons/assets/12213581/32c868e7-c878-421e-a01a-1d5dde5c710b)

You also have to pay $ to get your own vendor ID:

https://www.usb.org/getting-vendor-id

**Comment by lsiepel** [comment]
In that case i guess we are out of options.
