### ISSUE TITLE
[roku] representation-property seems to be tied to an unused field

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#16164]
I noticed that my inbox has entries for all of my Roku devices despite them being added already.  I believe this may be due to the fact that the representation-property in the xml is tied to a uuid field which doesn't seem to exist.  From what I can tell this may need to be changed to the serial number instead.

https://github.com/openhab/openhab-addons/blob/706ae583239d0fbfaffd8d38564fdbf62697f56b/bundles/org.openhab.binding.roku/src/main/resources/OH-INF/thing/roku.xml#L34C4-L34C27

**Comment by mlobstein** [comment]
Did you add the Roku things manually? In that case the uuid is not set on the thing and the discovery service will pick them up again. The discovery debug should look like this:
![image](https://github.com/openhab/openhab-addons/assets/26532542/fe988eca-bed4-4a65-a0cc-cd74c286885c)

Is this a TV? I also just noticed that the label for a TV (model name + model number) in the inbox is not very friendly when compared to a non-tv Roku device.

**Comment by morph166955** [comment]
Yes, these were manually added TVs.  It's my understanding that the intention is even manually added devices should be able to be tracked to orevent duplicate entries in the inbox.  Perhaps the uuid field needs to be exposed to be manually set in this case?  Could you rely on the serial number or something else that's discoverable instead?

**Comment by mlobstein** [comment]
Right now the uuid is the serial number obtained from the ssdp packet. I guess the thing configuration could be updated by the handler to add the uuid/serial number. Something like this maybe?
```
        Configuration configuration = this.getConfig();
        configuration.put(PROPERTY_UUID, serialNumber);
        this.updateConfiguration(configuration);
        this.thingUpdated(this.getThing());
```
Or just use the ignore button in the inbox?

**Comment by morph166955** [comment]
Given that uuid is just the serial number, is there any reason for uuid to exist at all?  My understanding of representation-property is that as soon as the property is set (either through discovery or once it comes online and the binding sets it) the inbox will auto match and hide it.

**Comment by mlobstein** [comment]
> Given that uuid is just the serial number, is there any reason for uuid to exist at all? My understanding of representation-property is that as soon as the property is set (either through discovery or once it comes online and the binding sets it) the inbox will auto match and hide it.

Try adding this in RokuHandler line 116:

thing.setProperty(PROPERTY_UUID, deviceInfo.getSerialNumber().toLowerCase());

**Comment by morph166955** [comment]
That worked for the roku_tv devices in the inbox.  I still get a duplicate entry of roku_player for 6 out of 10 of them.

**Comment by morph166955** [comment]
https://github.com/morph166955/openhab-addons/tree/roku-16164 branch is here.

**Comment by morph166955** [comment]
I have a possible answer to the 6/10 issue.  Those devices are all new in the house.  I'm wondering if,while they were going through the setup process they were not announcing properly.  I deleted and rescanned and now they aren't coming back.
