### ISSUE TITLE
[boschsch] New devices for Bosch Smart Home

### ISSUE THREAD

**Issue by wwinandy** [openhab/openhab-addons#16203]
Hello,

i bought a light / shutter control II.
When i make a Scan it dosnt apear and in the openhab.log there is no new "Added new thing"

I am using openhab Version 4.1.0 stable and Smart Home Controller II.

Would appreciate for extension of boschshc binding with new  devices from Bosch Smart Home,
Winfried

**Comment by david-pace** [comment]
Hi @wwinandy,

thank you for your enhancement request, but there is already an enhancement request for the Light / Shutter Control II here: https://github.com/openhab/openhab-addons/issues/14562

The next openHAB release 4.2 will already come with support for the Door/Window Sensor II (https://github.com/openhab/openhab-addons/pull/16093). If you need support for other devices, feel free to open new enhancement requests (one for each device).

I will add a note to https://github.com/openhab/openhab-addons/issues/14562 that you also requested support for Light/Shutter Control II, mark this issue as a duplicate and close it.
