### ISSUE TITLE
[shelly] alert events misspelled (should be without '_' for OVERLOAD, OVERPOWER, OVERTEMP)

### ISSUE THREAD

**Issue by crazyelectron-io** [openhab/openhab-addons#16207]
Due to a mixup of powerplugs I received an event in the log (for the first time):

shelly:shellyplugs:c16841:device#alarm triggered OVERPOWER
However, the documentation states this event as 'OVER_POWER'. After having a look at the source code, this applies to 2 other events as well.

OVER_POWER should be OVERPOWER
OVER_LOAD should be OVERLOAD
OVER_TEMP should be OVERTEMP

I'll try to create a tiny PR for the README.md file.

**Comment by markus7017** [comment]
merged
