### ISSUE TITLE
[ecovacs] Deebot N8+ vacuum Thing not online

### ISSUE THREAD

**Issue by pationair** [openhab/openhab-addons#16201]
Hello, sorry for my bad English. 

I updated from Openhab 3.4.1 to 4.1.0 at the weekend, since then something with the Ecovacs binding no longer works. My API account goes online but the vacuum cleaner Ecovacs N8+ doesn't go online (but it will detected via autodiscovery). I have deleted the binding and reinstalled it several times, but it always gets stuck during initialization. 

Thanks for your help

**Comment by maniac103** [comment]
Please
- enable DEBUG logging for ecovacs binding (`log:set DEBUG org.openhab.binding.ecovacs` in OH console)
- try to recreate the vacuum thing
- share the log snippet from that attempt

Thanks.

**Comment by pationair** [comment]
Thanks for your Reply.

I cant open the Debug @ my Screenshot

**Comment by maniac103** [comment]
Not sure if it's just me, but I don't actually see a screenshot, only a seemingly broken link?

**Comment by pationair** [comment]
Okay 

This is the entry when

openhab> log:set DEBUG org.openhab.binding.ecovacs                                        Error executing command: Unable to set level for logger

**Comment by pationair** [comment]
Hello, just wanted to let you know that my problem has been solved. For some reason that I don't know, the Ecovacs binding version 3.4.1 was still installed, which is why the N8+ thing didn't go online. Thanks for trying to help
