### ISSUE TITLE
[netatmo] Several weather-stations under the same netatmo account

### ISSUE THREAD

**Issue by DefCon-CC** [openhab/openhab-addons#16230]
## Expected Behavior
I'm not really sure if this is a bug or if it is a feature request. 
I'm having two netatmo weather-stations (plus respectively rain gauge and outdoor module). They are at different locations, 
but are handled using the same netatmo account. 
In the thing configuration of the netatmo binding I found no way to add two netatmo weather-stations that on item (channel) level it is possible to differentiate between each other.

## Current Behavior
The current behavior seems to be that it is not possible to handle more then one weather-station on the same netatmo account on openhab with the current implementation of the netatmo binding

## Possible Solution
Add possibility to differentiate between several weather-stations on the same netatmo account

## Steps to Reproduce (for Bugs)
see below

## Context
thing configuration
```
Bridge netatmo:account:default "Netatmo" [ clientId="xxx", clientSecret="xxx", refreshToken="xxx" ] 
{
    Bridge weather-station inside "Netatmo Inside" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ] {
        Thing outdoor outside "Netatmo Outside" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ]
        Thing rain rainGauge "Netatmo Rain" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ] 
    } 
	
    Bridge weather-station inside "Netatmo Inside" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ] {
    	Thing outdoor outside "Netatmo Outside" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ]
        Thing rain rainGauge "Netatmo Rain" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ] 
    }
}
```

In OpenHAB only appears:
netatmo:weather-station:default:inside
netatmo:outdoor:default:inside:outside
netatmo:rain:default:inside:rainGauge

But I would like to have something like this:
netatmo:home1:weather-station:default:inside
netatmo:home1:outdoor:default:inside:outside
netatmo:home1:rain:default:inside:rainGauge

netatmo:home2:weather-station:default:inside
netatmo:home2:outdoor:default:inside:outside
netatmo:home2:rain:default:inside:rainGauge
## Your Environment
Linux
OpenHAB 4.0.4 
RHEL 9

**Comment by jlaur** [comment]
This is already possible, but you have an error in your configuration - you have given the two things the same id. Try this instead:
```
Bridge netatmo:account:default "Netatmo" [ clientId="xxx", clientSecret="xxx", refreshToken="xxx" ] 
{
    Bridge weather-station inside1 "Netatmo Inside" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ] {
        Thing outdoor outside "Netatmo Outside" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ]
        Thing rain rainGauge "Netatmo Rain" @ "Home 1" [ id="xx:xx:xx:xx:xx:xx" ] 
    } 
	
    Bridge weather-station inside2 "Netatmo Inside" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ] {
    	Thing outdoor outside "Netatmo Outside" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ]
        Thing rain rainGauge "Netatmo Rain" @ "Home 2" [ id="xx:xx:xx:xx:xx:xx" ] 
    }
}
```

**Comment by DefCon-CC** [comment]
Yes you are right. This solved by problem. I thought that inside is something like a keyword which is fixed.
