### ISSUE TITLE
[influxdb] persistence service does not recover from connection loss after UnknownHostException

### ISSUE THREAD

**Issue by kaistierl** [openhab/openhab-addons#16233]
## Expected Behavior

When the InfluxDB gets unavailable for a short time during operation, OpenHAB recovers from this condition and continues to write data as soon as InfluxDB is available again. This should work in a dockerized setup, where the InfluxDB container is stopped, and started again a few seconds later.

## Current Behavior

When the InfluxDB container is stopped and started again during operation of OpenHAB, OpenHAB completely stops writing data and does not recover. It throws a `UnknownHostException` after the InfluxDB container was stopped and seems not to recover the connection once the InfluxDB would be available again.

There is a `Connection lost, trying re-connection` message but even after some minutes, there is still no `database status is OK` message in the logs. Therefore, I suspect the reconnection logic to not work properly here.

To recover from this, I need to manually run a `bundle:restart` of the InfluxDB persistence service. Then it works again and it even writes queued data from the "lost" minutes.

Here is a log, I cut it right before the `bundle:restart`

[openhab_influx_connection_lost.log](https://github.com/openhab/openhab-addons/files/13853705/openhab_influx_connection_lost.log)

persistence service config:

```
version=V1
url=http://influxdb:8086
user=admin
password=''
db=openhab
retentionPolicy=autogen
```

## Steps to Reproduce (for Bugs)

1. Setup influxDB and OpenHAB in docker containers, with a shared docker network between those. Configure OpenHAB to address the InfluxDB by it's container name using docker based name resolution (i.e. use `url=http://influxdb:8086` with the InfluxDB container named `influxdb`).
2. Stop the InfluxDB container, wait a few seconds, then start it again.

## Your Environment

* Version used: OpenHAB 4.1.0 with InfluxDB 1.8.10, both in docker containers (Official images from Docker Hub)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Host runs on Debian 12

**Comment by jlaur** [comment]
@kaistierl - can you try this: [org.openhab.persistence.influxdb-4.2.0-SNAPSHOT.jar](https://drive.google.com/file/d/14btBio1CmRXoLRWSib1rMHS3_3dRv76o/view?usp=sharing)

Although it's named 4.2, it should work with 4.1. Please uninstall the bundled version before dropping this to your addons directory.

**Comment by jlaur** [comment]
@kaistierl - can you verifiy the provided fix?

**Comment by kaistierl** [comment]
Will do but have been too busy the last days. Will be able to test on friday latest.

**Comment by kaistierl** [comment]
I was now able to verify the fix and can confirm that it works in my case. In the DEBUG log I now see several reconnection tries and as soon as InfluxDB is available again, the re-connection succeeds.
