### ISSUE TITLE
[boschshc] Support for Smoke Alarm II

### ISSUE THREAD

**Issue by wwinandy** [openhab/openhab-addons#16243]
Hello,

i bought a smoke alarm II.
When i made a Scan it didn't apear and in the openhab logs there was no "Added new thing".

I am using openhab Version 4.1.0 Release and Bosch Smart Home Controller II.

Would appreciate for extension of boschshc binding with new devices from Bosch Smart Home,
Winfried

**Comment by pat-git023** [comment]
@david-pace @GerdZanker 
If you are not already have a look into it I could try my best on this one

**Comment by david-pace** [comment]
Hi @pat-git023, your code contribution for Smoke Alarm II would be highly appreciated since I currently don't have much free time available and also don't have the hardware to test the code. Thanks in advance 👍

**Comment by pat-git023** [comment]
Sorry for the delay but had a little stressful week.  
I have now prepared a pull request for the Smoke Detector II.

@wwinandy 
Here you can find the current binding with the smoke detector II support: https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.boschshc/4.2.0-SNAPSHOT/
Would be nice if you could also do a little test if everything is working as expected also at your end.

Thank you very much
Patrick
