### ISSUE TITLE
[boschshc] Support for Universal Switch II

### ISSUE THREAD

**Issue by wwinandy** [openhab/openhab-addons#16244]
Hello,

i bought a Universal Switch II.
When i made a Scan it didn't apear and in the openhab logs there was no "Added new thing".

I am using openhab Version 4.1.0 Release and Bosch Smart Home Controller II.

Would appreciate for extension of boschshc binding with new devices from Bosch Smart Home,
Winfried

**Comment by david-pace** [comment]
Hi @wwinandy and @mike-bike, I managed to finish an implementation for Universal Switch I + II. It works well with my Universal Switch II, but I don't own an old Universal Switch, so I can't verify the functionality of the older device. If you could help me testing with any of the two devices, it would be great :+1:

Some things to notice in advance:
* if you have a dedicated second openHAB system just for testing it would be optimal just to be sure your productive system is not affected during testing
* please make a backup of your system to be safe (I don't expect that exchanging the JAR can destroy the system but just in case...)

The test JAR is available [here](http://davidpace.de/openhab/org.openhab.binding.boschshc-4.2.0-SNAPSHOT-universal-switch.jar).

Testing process:
* start an openHAB console with `openhab-cli console`
* find out the bundle ID of the `boschshc` binding: `la -s | grep boschshc`
* replace the JAR with `bundle:update [bundle ID from previous step] /path/to/JAR.jar
* (sometimes openHAB needs to be restarted)
* check if the discovery of universal switches works
* add universal switch as thing
* add items to all channels of the universal switch
* press buttons on the universal switch and check if all channels are updated correctly
* when you're finished with testing, delete & unlink all created items and to delete the universal switch thing (in case there are updates/enhancements later, they would become incompatible)
* finally, replace the bundle JAR with the original JAR of your release. JARs for all releases can be found [here](https://openhab.jfrog.io/ui/repos/tree/General/libs-release-local/org/openhab/addons/bundles/org.openhab.binding.boschshc)

Let me know if you run into any problems or have any questions. The JAR was built using the latest openHAB state (`main` branch). It should work with openHAB `4.1.1` but I'm not 100% sure. Please let me know if it doesn't, then I can try to rebase on an older state which is closer to `4.1.1`.

**Comment by mike-bike** [comment]
Sorry I don’t own a universal switch. Neither I or II. I join with dimmer and roller shutter / light switch II😀GrußMichaelAm 13.01.2024 um 22:42 schrieb David Pace ***@***.***>:﻿
Hi @wwinandy and @mike-bike, I managed to finish an implementation for Universal Switch I + II. It works well with my Universal Switch II, but I don't own an old Universal Switch, so I can't verify the functionality of the older device. If you could help me testing with any of the two devices, it would be great 👍
Some things to notice in advance:

if you have a dedicated second openHAB system just for testing it would be optimal just to be sure your productive system is not affected during testing
please make a backup of your system to be safe (I don't expect that exchanging the JAR can destroy the system but just in case...)

The test JAR is available here.
Testing process:

start an openHAB console with openhab-cli console
find out the bundle ID of the boschshc binding: la -s | grep boschshc
replace the JAR with `bundle:update [bundle ID from previous step] /path/to/JAR.jar
(sometimes openHAB needs to be restarted)
check if the discovery of universal switches works
add universal switch as thing
add items to all channels of the universal switch
press buttons on the universal switch and check if all channels are updated correctly
when you're finished with testing, delete & unlink all created items and to delete the universal switch thing (in case there are updates/enhancements later, they would become incompatible)
finally, replace the bundle JAR with the original JAR of your release. JARs for all releases can be found here

Let me know if you run into any problems or have any questions. The JAR was built using the latest openHAB state (main branch). It should work with openHAB 4.1.1 but I'm not 100% sure. Please let me know if it doesn't, then I can try to rebase on an older state which is closer to 4.1.1.
