### ISSUE TITLE
[boschshc] Support for Dimmer

### ISSUE THREAD

**Issue by mike-bike** [openhab/openhab-addons#16241]
Hi,

my feature request to implement support for the new Bosch Dimmer device (https://www.bosch-smarthome.com/uk/en/products/devices/dimmer/) 

I am offering test and analysis support on a PI2 with current openHABian 4.1.

Many thanks for your great effort and support.

Regards,
Michael

**Comment by mike-bike** [comment]
Hi all, this is the result from a freshly installed dimmer module - not sure if that helps:

First long poll response before stopping/starting the bridge thing:
`2024-01-11 19:25:29.342 [DEBUG] [.internal.devices.bridge.LongPolling] - Long poll response: {"result":[{"rootDeviceId":"64-da-a0-10-83-a7","serial":"60B647FFFE14A1E1","@type":"device","supportedProfiles":[],"profile":"GENERIC","name":"DimmerMM_60b647fffe14a1e1","deviceModel":"MICROMODULE_DIMMER","id":"hdm:ZigBee:60b647fffe14a1e1","deviceServiceIds":["CommunicationQuality","PowerSwitch","ChildProtection","ElectricalFaults","MultiLevelSwitch","DimmerConfiguration","SwitchConfiguration"],"childDeviceIds":[],"manufacturer":"BOSCH","status":"UNDEFINED"}],"jsonrpc":"2.0"}`

Forced discovery with pause / unpause bridge thing:
`2024-01-11 20:34:31.545 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Found device: name=Dimmertest id=hdm:ZigBee:60b647xxxxxxxxx
2024-01-11 20:34:31.547 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: CommunicationQuality
2024-01-11 20:34:31.548 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: PowerSwitch
2024-01-11 20:34:31.549 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: ChildProtection
2024-01-11 20:34:31.551 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: ElectricalFaults
2024-01-11 20:34:31.552 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: MultiLevelSwitch
2024-01-11 20:34:31.553 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: DimmerConfiguration
2024-01-11 20:34:31.554 [DEBUG] [rnal.discovery.ThingDiscoveryService] - .... service: SwitchConfiguration`

`2024-01-11 20:34:32.037 [DEBUG] [rnal.discovery.ThingDiscoveryService] - Unknown deviceModel 'MICROMODULE_DIMMER'! Please create a support request issue for this unknown device model.`

After that I have not observed any further long poll responses from the device...

**Comment by mike-bike** [comment]
Hi David,

I am happy to do so. Stay tuned…

Regards,
Michael

**Comment by mike-bike** [comment]
Hi @david-pace, downloaded JAR and did a quick test. Dimmer device has been automatically identified and thing placed into inbox. All channels seem to be working fine. 

Minor observation: Dimmer Device shows the Bosch Room as Location property in the thing. Seems to be a new feature. However, it does not get any updates. In the Bosch app I have moved the device into a new room, but the change is not reflected in the Thing - even a OpenHAB restart does not force an update...
I'd suggest removing that property if updates are not coming through.

Anyway: Great work again! MANY THANKS for your continuous effort.

Let me know, if I could do anything else.

Regards,
Michael

**Comment by mike-bike** [comment]
Hi @david-pace, what does the new status mean to the code? Is this feature now included into the daily snapshots of the openHAB i.e. 4.2.0-SNAPSHOT? 

Thanks,
Michael

**Comment by david-pace** [comment]
Hi @mike-bike, yes this is correct. The Dimmer support (as well as the Light/Shutter Control II support) will soon be included in the `SNAPSHOT` version of openHAB, currently `4.2.0-SNAPSHOT` 😎
