### ISSUE TITLE
The Console (SSH): transfer org.apache.karaf.shell.cfg params to runtime.cfg.

### ISSUE THREAD

**Issue by yndtrud** [openhab/openhab-addons#16256]
Topic: https://www.openhab.org/docs/administration/console.html

When I needed to change several values ​​from the org.apache.karaf.shell.cfg file, I did not understand: any values ​​can be written to runtime.cfg based on the org.apache.karaf.shell.cfg:param rule or not. 
It turned out that I can freely transfer the settings to runtime.cfg. 
The documentation says (using port as an example) that I should edit org.apache.karaf.shell.cfg.

Forum: https://community.openhab.org/t/how-to-save-settings-from-org-apache-karaf-shell-cfg/152875

**Comment by hmerk** [comment]
Sorry, but this is the wrong repository. As I understand, our docs are not correct, therefore this should be filed there.
