### ISSUE TITLE
[homekit] No negative temperature values (0°C instead)

### ISSUE THREAD

**Issue by PatrickGlatz** [openhab/openhab-addons#16257]
Hi team,

It's getting cold with temperatures below zero. Lately i recognised i was dressed too less because Homekit told me, it was only 0°C. In fact, it was -5.5°C. The values in openHAB are correct, but in Homekit they are limited to the bottom at 0°C.

## Expected Behavior
Report also negative temperatures in Homekit

## Current Behavior
Positive values of temperature are reported correctly (living room: Source (ecowitt weather station) = 20.7°C, OH = 20.7°C, homekit = 20.7°C)
Negative values of temperature are reported incorrectly (garden: Source (ecowitt weather station) = -5.5°C, OH = -5.5°C, homekit = 0.0°C)

Weird is, that karaf reports a min and a max value at the homekit instance, although none are configured (but the upper limit will probably only be reached in case climate warming is continuing in this speed ...).

P.S.: Also other users are facing this issue:
https://openhabforum.de/viewtopic.php?p=59191

## Steps to Reproduce (for Bugs)
1. Configure `Number:Temperature `item
```
Number:Temperature          ecowitt_temperature_outdoor    "Outdoor Temperature"                    <Temperature>         (g_ecowitt_outdoor)    ["Measurement", "Temperature"]    {channel="fineoffsetweatherstation:gateway:GW2000A:temperature-outdoor", unit="°C", homekit="TemperatureSensor.CurrentTemperature"}
Number:Temperature          ecowitt_temperature_indoor     "Inside temperature"                     <Temperature>                                ["Measurement", "Temperature"]    {channel="fineoffsetweatherstation:gateway:GW2000A:temperature-indoor", unit="°C", homekit="TemperatureSensor.CurrentTemperature"}
```
2. Check temperatures in karaf
```
openhab> openhab:status ecowitt_temperature_indoor
19 °C
openhab> openhab:status ecowitt_temperature_outdoor
-0.5 °C
openhab>
```
3.  Check homekit in karaf
```
openhab> homekit show "Outdoor Temperature"
557186122 Outdoor Temperature
Services:
  Service Type: TemperatureSensorService (0000008A-0000-1000-8000-0026BB765291)
    Characteristics:
      CurrentTemperatureCharacteristic: {"iid":0,"type":"11","perms":["pr","ev"],"format":"float","value":0.0,"minValue":0.0,"maxValue":100.0,"minStep":0.1,"unit":"C"}
```
4. Check item in webUI
<img width="703" alt="image" src="https://github.com/openhab/openhab-addons/assets/26554156/6849f511-d488-42ca-b53c-66c46dce8b27">
<img width="861" alt="image" src="https://github.com/openhab/openhab-addons/assets/26554156/80833a46-d9cf-43b6-acb2-b9166c6e9775">

5. Check item in Homekit

<img width="400" alt="image" src="https://github.com/openhab/openhab-addons/assets/26554156/df09c9b5-a471-4910-80c3-a0567b929640">

## Context
I was freezing in the morning due to wrong cloths ;-)

## Your Environment
* Version used: openHAB 4.0.4, homekit directly delivired with this Version
<img width="671" alt="image" src="https://github.com/openhab/openhab-addons/assets/26554156/d85f85ef-fc9a-4b97-8973-35c50548b9f2">

* Environment name and version:
```
$ java --version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Debian-1deb11u1, mixed mode, sharing)
$ node --version
v18.17.1
```
* Operating System and version:
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -mrs
Linux 6.1.21-v8+ aarch64
```

**Comment by alaub81** [comment]
Same here! I think the following warning in `openhab.log` are related to that issue:
```
2024-01-17 16:08:20.166 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range -1.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.thermostat.CurrentTemperatureCharacteristic@573a6ccf
```

and I also get a warning for my dimmer item, but I can not see the problem here in home app, because there is no negative value used by a dimmer:
```
2024-01-17 16:14:39.345 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range 0.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.lightsensor.CurrentAmbientLightLevelCharacteristic@5cf21a85
```

**Comment by crnjan** [comment]
Please check https://www.openhab.org/addons/integrations/homekit/#min-max-temperatures and add something like
```
value: TemperatureSensor,TemperatureSensor.CurrentTemperature
config:
  minValue: -50
```
to you config ...

**Comment by PatrickGlatz** [comment]
@crnjan 

Hi Boris,

seems to be my fault. Working perfectly for me when doing it like this
` {channel="fineoffsetweatherstation:gateway:GW2000A:temperature-outdoor", unit="°C", homekit="TemperatureSensor.CurrentTemperature" [minValue=-25, maxValue=50]} `


Topic closed, thanks
