### ISSUE TITLE
[MQTT] Cannot send STOP to generic roller shutter

### ISSUE THREAD

**Issue by zankia** [openhab/openhab-addons#16276]
Since I upgraded from 4.0.4 to 4.1.1, I can't send STOP command to my mqtt channel configured as roller shutter. UP and DOWN still work

## Expected Behavior

Send a message "STOP" to the topic linked to a generic roller shutter MQTT channel when the related item got the STOP command

## Current Behavior

sendCommand(STOP) to the item responds OK but no message in the mqtt topic.

In the logs, I got this exception :
```
[ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.mqtt.generic.internal.handler.GenericMQTTThingHandler@8ec84e': STOP is not a valid command for MQTT.
java.lang.IllegalArgumentException: STOP is not a valid command for MQTT.
	at org.openhab.binding.mqtt.generic.values.RollershutterValue.parseType(RollershutterValue.java:97) ~[?:?]
	at org.openhab.binding.mqtt.generic.values.RollershutterValue.parseCommand(RollershutterValue.java:137) ~[?:?]
	at org.openhab.binding.mqtt.generic.ChannelState.publishValue(ChannelState.java:369) ~[?:?]
	at org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.handleCommand(AbstractMQTTThingHandler.java:153) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy479.$Proxy594.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:95) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [bundleFile:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Possible Solution

I managed to fix on my side by deleting `&& stopCommandString != null` in RollershutterValue.java:94 that comes from https://github.com/openhab/openhab-addons/pull/15875/
I guess it is only a workaround and the problem may be deeper

## Steps to Reproduce (for Bugs)

1. Create a Generic MQTT Thing
2. Add a channel type Rollershutter (default configuration is good)
3. Create an item of type Rollershutter linked to that channel
4. Send command STOP to that item

## Context

I saw the introduction of the bug was about mqtt.homeassistant. In my case, I only use mqtt.generic because I want to keep it simple and low level

## Your Environment

* Version used: 4.1.1
* Environment name and version : openjdk 17.0.9, node 16.20.2
* Operating System and version : Openhabian (Raspbian 11)

**Comment by gbrsml** [comment]
Same issue is here (version 4.1.1, openjdk 17.0.9). Only the first 3 rollershutter items are affected (out of 13). Thanks!

**Comment by Stepko2409** [comment]
+1
Same here!
Version: 4.1.1
Environment: OpenHab in Docker :latest

STOP doesn't work with my 15 rollershutter things using Zigbee2Mqtt with generic MQTT Things.

**Comment by lsiepel** [comment]
@ccutrer do you have some thoughts on this issue?

**Comment by ccutrer** [comment]
Yes, I'll try to look into it today. It's possible https://github.com/openhab/openhab-addons/pull/16051 already fixes it, but I don't think so.

**Comment by ccutrer** [comment]
Just to be clear @zankia, you've explicitly configured a "STOP" command string on your channel? Also, are you using file based configuration or UI? Part of the Home Assistant Cover commit "fixed" the "bug" of assuming that any MQTT rollershutter channel can accept STOP commands. It can be debated if that should be considered a bug or not, and/or a breaking change or not, since it wasn't clearly documented before that the STOP command string is required in order to accept command strings. The configuration still also defaults to having STOP, and I feel like I tested that that is still true, but perhaps I didn't test far enough, and file based things will not inherit that default, or that UI based things that already existed won't get it.

**Comment by gbrsml** [comment]
My case: file based config:
```
Rollershutter REDONY_FSZ_KONYHA_UTCAI           "FSZ.Konyha utcai"              (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_KONYHA_UTCAI", autoupdate="false" }
Rollershutter REDONY_FSZ_KONYHA_OLDAL           "FSZ.Konyha oldal"              (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_KONYHA_OLDAL", autoupdate="false" }
Rollershutter REDONY_FSZ_ETKEZO_AJTO            "FSZ.Étkező ajtó"               (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_ETKEZO_AJTO", autoupdate="false" }
Rollershutter REDONY_FSZ_ETKEZO_FIX             "FSZ.Étkező fix"                (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_ETKEZO_FIX", autoupdate="false" }
Rollershutter REDONY_FSZ_NAPPALI_OLDAL          "FSZ.Nappali oldal"             (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_NAPPALI_OLDAL", autoupdate="false" }
Rollershutter REDONY_FSZ_NAPPALI_HATSO          "FSZ.Nappali hátsó"             (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_NAPPALI_HATSO", autoupdate="false" }
Rollershutter REDONY_FSZ_SZOBA          "FSZ.Szoba"             (gGF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_FSZ_SZOBA", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA1_UTCAI            "Em.Szoba1 utcai"               (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA1_UTCAI", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA1_OLDAL            "Em.Szoba1 oldal"               (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA1_OLDAL", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA2          "Em.Szoba2"             (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA2", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA3_OLDAL            "Em.Szoba3 oldal"               (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA3_OLDAL", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA3_HATSO            "Em.Szoba3 hátsó"               (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA3_HATSO", autoupdate="false" }
Rollershutter REDONY_EM_SZOBA4          "Em.Szoba4"             (gFF, Shutters) { channel="mqtt:topic:diosgyori:arduino:REDONY_EM_SZOBA4", autoupdate="false" }
```

I see that there are java exceptions after pressing stop button on the android app on the first 3 items. The remaining ones work fine, I see the STOP commands on the MQTT topic. Only the first 3 items are faulty in my case.

**Comment by ccutrer** [comment]
@gbrsml : those are your items; what about your things? And can you post the exceptions?

**Comment by ccutrer** [comment]
Perfect, thanks. I'll check my production openHAB. I have some very similarly configured rollershutters that are working, but I'm not running vanilla 4.1 (or snapshot). I won't be at my computer for at least a few hours though.

**Comment by ccutrer** [comment]
Yes, definitely a weirdness with the default value. I was able to reproduce with a UI created generic MQTT thing, but not a file based (which is what the shades in my production instance are). I wrote a fix, but did not have time to test it yet. In the meantime, you can work around by explicitly setting `stop = "STOP"` on the channel for a file based thing, or for a UI based thing, configure it to something else (like "ST") first, save it, and then change it to "STOP" (do _not_ click the little X to clear it and get the default) to get it to persist the literal string.

**Comment by zankia** [comment]
Indeed, I use the UI to configure my things. The STOP string is definitely the default one in my case.
Thanks @ccutrer for your work.

**Comment by Stepko2409** [comment]
Thanks for your help and work @ccutrer. I use the UI to define my things and your workaround to change the STOP string and change it back to "STOP" works for me!

**Comment by gbrsml** [comment]
@ccutrer, thanks!
I added `stop="STOP"` only to the first rollershutter channel and now the first 3 channels are OK again. Thanks!

**Comment by ms235** [comment]
I have got the same Problem after an Update to OH 4.2.

MQTT Rollershutter don*t stop after I send command stop via MQTT .

How do you solve the issue?

Here is my config:

`Thing topic rollo-Buero "rollo Buero" {
    Channels:
        Type rollershutter  : Position  "Rollo Prozent"      [stateTopic="tele/Rollo-Buero/SENSOR", transformationPattern="JSONPATH:$.Shutter1.Position" , commandTopic="cmnd/Rollo-Buero/ShutterPosition"] 
  }`

**Comment by gbrsml** [comment]
from @ccutrer: you can work around by explicitly setting stop = "STOP" on the channel for a file based thing.

It resolved my issue by adding it only to the first thing. But after upgrading to newer releases, I had to add it to the following things in the config file. Now it is added to all rollershutter things and it works.
Eg.:
Type rollershutter : REDONY_FSZ_NAPPALI_OLDAL "FSZ.Nappali oldal" [ stateTopic="shutter/status/FSZ_NAPPALI_OLDAL", commandTopic="shutter/control/FSZ_NAPPALI_OLDAL", **stop = "STOP"** ]

**Comment by ms235** [comment]
Perferct ... it works great. Thanks a lot.

**Comment by ccutrer** [comment]
For future readers: it was decided the accidental change to behavior was actually desirable, and documented as a breaking change at https://github.com/openhab/openhab-distro/pull/1632
