### ISSUE TITLE
[chromecast]  Unable to Skip to the next song

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#1629]
When i am playing for example something from spotify on the chromecast i am able to pause and resume playback, however i cannot skip the current track or go back.

openHAB 2.0 Build #684
Chromecast Binding Build #225

There are no errors in the openhab.log file.

Here is my items file:
```
Group gTest "Test"

Player P_BR_Chromecast_Player (gTest) { channel="chromecast:audio:2233408551fc01019e6a2a027ea76298:control"}
Dimmer P_BR_Chromecast_Volume (gTest) { channel="chromecast:audio:2233408551fc01019e6a2a027ea76298:volume"}
String P_BR_Chromecast_URL    (gTest) { channel="chromecast:audio:2233408551fc01019e6a2a027ea76298:playuri"}

```

**Comment by lolodomo** [comment]
I just tried the Chromecast binding. It discovered my Freebox Player Mini 4k (running Android TV).
I can play and pause YouTube videos but previous and next commands are ignored.

**Comment by lolodomo** [comment]
Looking at the code, previous and next commands are simply not implemented.

**Comment by holmes** [comment]
I attempted to implement them, but I can't find the actual command to send to the ChromeCast that works. I tried NEXT, SKIP_FORWARD, FORWARD, FAST_FORWARD, SKIP. 

All to no avail. If someone figures out the command it's trivial to update the library. 

One thing I noticed, the Chromecast notification on icon only has play/stop/mute options, it doesn't offer skip. Wonder if that's related.

**Comment by holmes** [comment]
If they got it to work in Python we can just copy what command they sent.

Only problem is that I'm in the midst of a whole house remodel and won't have my home automation stuff set up until at least October.

And while it might be fun to just try and see what happens it's a lot of work if it can't be tested locally.

**Comment by JohanPotgieter** [comment]
Any news on this? I would also be very interested to have the next and previous buttons work on Chromecast and Chromecast audio groups.

**Comment by holmes** [comment]
I still haven't had a chance to get my audio/video stuff set up, so I haven't been able to do anything with this.

It looks like the other binding mentioned implements skip by fast-forwarding to the end of the song - 1 second. 

Clever, although incredibly gross and won't work for apps like Pandora.

**Comment by imaginator** [comment]
I tried to do the `end-of-song - 1s` approach, but it appears that moving within a song is also unsupported.  See: https://community.openhab.org/t/chromecast-next-track-sendcommand/122121

**Comment by hmerk** [comment]
closed due to inactivity
