### ISSUE TITLE
[Fronius] Smart Meter IP

### ISSUE THREAD

**Issue by carlee82** [openhab/openhab-addons#16300]
In the Fronius Binding the Smart Meter is supported. There is a new version (Fronius Smart Meter IP) which is not connected by RS485 to the inverter. Instead it has an own IP address (coneczed by LAN or WIFI). 
It would be great if the binding is able to get the values out of the SmartMeter through conneting by the IP connection.
My Smart Meter states, beside my internal LAN IP(Modbus address: 1 and Modbus TCP Port: 502)

**Comment by jimtng** [comment]
The Fronius binding (currently) only works with the fronius solar api via http.

It seems that they only support Modbus protocol. In this case perhaps you could already use the Modbus binding to integrate the Smart Meter IP ?

**Comment by jimtng** [comment]
@carlee82 can you confirm whether it's a modbus compatible device or does it have its own API (HTTP?)

**Comment by carlee82** [comment]
Hi.

I can confirm that it is a Modbus compatible device.

Best wishes 
Karl-Heinz 

Am 23. August 2024 12:49:06 MESZ schrieb jimtng ***@***.***>:

**Comment by jimtng** [comment]
I assume this issue can be closed? Feel free to reply again if necessary.

**Comment by carlee82** [comment]
Yes. It is solved.
It worked after a few tweaks.

Thx

Am 23. August 2024 13:21:57 MESZ schrieb jimtng ***@***.***>:

**Comment by aMU5Ed** [comment]
> Yes. It is solved.
> It worked after a few tweaks.
> 
> Thx
> 
> Am 23. August 2024 13:21:57 MESZ schrieb jimtng ***@***.***>:
> […](#)

Hi, please tell us what tweaks you made. Thanks in advance
