### ISSUE TITLE
[pentair] Pool/Spa temperature are not updating

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#16302]
Even the controller is initialized and communication is shown in the log the current pool and spa temp only get rarely updated.
It turned out that the temps are updated when receiving the heat status message from the controller. This contains the heat status, but not the current water temperature. This comes with the controller status, so updates to the poolheat and spaheat channel groups were added there.

@jsjames This Issues should be linked to the pending PR https://github.com/openhab/openhab-addons/pull/13485

**Comment by lsiepel** [comment]
As the [related PR](https://github.com/openhab/openhab-addons/pull/13485) is merged. I close this issue, feel free to re-open if needed.
