### ISSUE TITLE
[pentair] Log improvement

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#16301]
Logging has been improved
- Each message includes the device id (source/dest address)
- Clear separation between DEBUG (control/status messages) and TRACE (packet dumps)

@jsjames This Issues should be linked to the pending PR #13485

**Comment by lsiepel** [comment]
As the [related PR](https://github.com/openhab/openhab-addons/pull/13485) is merged. I close this issue, feel free to re-open if needed.
