### ISSUE TITLE
[network] blocks all threads

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#16305]
After some time (usually 1 1/2 days) suddenly all thinghandler-threadpool threads are WAITING with this stack trace:

```
Thread 553 OH-thingHandler-1 WAITING
Stacktrace:
jdk.internal.misc.Unsafe.park line: -2
java.util.concurrent.locks.LockSupport.park line: 211
java.util.concurrent.CompletableFuture$Signaller.block line: 1864
java.util.concurrent.ForkJoinPool.unmanagedBlock line: 3465
java.util.concurrent.ForkJoinPool.managedBlock line: 3436
java.util.concurrent.CompletableFuture.waitingGet line: 1898
java.util.concurrent.CompletableFuture.get line: 2072
org.openhab.binding.network.internal.PresenceDetection.getValue line: 269
org.openhab.binding.network.internal.PresenceDetection.lambda$13 line: 553
org.openhab.binding.network.internal.PresenceDetection$$Lambda$2072/0x000000010119e000.run line: -1
java.util.concurrent.Executors$RunnableAdapter.call line: 539
java.util.concurrent.FutureTask.runAndReset line: 305
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run line: 305
java.util.concurrent.ThreadPoolExecutor.runWorker line: 1136
java.util.concurrent.ThreadPoolExecutor$Worker.run line: 635
java.lang.Thread.run line: 840
```

openHAB 4.2, Snapshot 3839 on a Debian

**Comment by J-N-K** [comment]
@wborn could this be related to #16235?

**Comment by wborn** [comment]
Yes it could be that one of the futures never completes and it then keeps waiting forever:

https://github.com/openhab/openhab-addons/blob/9e1f87db86409ec2ea1a36ea0de64bbd14c79608/bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java#L378-L380

Perhaps a max timeout can be used or it should interrupt the future when the next presence detection starts when it takes too long or it failed to complete.

Perhaps it should also not use the common `scheduledExecutorService` as it may take a while before all futures complete:

https://github.com/openhab/openhab-addons/blob/9e1f87db86409ec2ea1a36ea0de64bbd14c79608/bundles/org.openhab.binding.network/src/main/java/org/openhab/binding/network/internal/PresenceDetection.java#L395

**Comment by wborn** [comment]
Maybe you can give https://github.com/openhab/openhab-addons/pull/16315 a try @J-N-K?
