### ISSUE TITLE
Activating Amazon Echo Binding Account Thing creation fails

### ISSUE THREAD

**Issue by KDB-F95** [openhab/openhab-addons#16314]
After aktivating the Amazon Echo binding, I‘ve tried to setup the account thing as described in the binding documentation - calling

[#](https://www.openhab.org/addons/bindings/amazonechocontrol/#first-steps) First Steps
Create an 'Amazon Account' thing
open the url YOUR_OPENHAB/amazonechocontrol in your browser (e.g. http://openhab:8080/amazonechocontrol/), click the link for your account thing and login.

There is no link, only the message: 

„ Amazon Echo Control

No Account thing created.“

Unfortunately I cannot find any blog  upon this issue, therefore I open up a bug report.

**Comment by lsiepel** [comment]
Did you create an Amazon Account Thing in openHAB ?

If so, can you share your configuration, openHAB version?

**Comment by KDB-F95** [comment]
I've found this article/blog 

https://community.openhab.org/t/unable-to-configure-amazon-account-thing-amazon-echo-control-binding/79933 

I tried 👍 Steps to reproduce:

1. Add Amazon Echo Control Binding from Add-ons in PaperUI
2. Inbox->±>Amazon Echo Control Binding->Add Manually->Amazon Account
3. Visited openhab:8080/amazonechocontrol/[ID]
4. Entered Amazon credentials

And it worked fine - you should definetly update the documentation for the addon, because this hasen't been desribed anywhere on the binding documentation! - Issue / bug solved

**Comment by lsiepel** [comment]
Sorry, but i have to comment on this. 

Maybe you have to re-read your own first post, you quoted the offical documentation from here: https://www.openhab.org/addons/bindings/amazonechocontrol/#first-steps your quote does not have the step numbers (probably lost when copy/paste) but the linked docs clearly state STEP 1 (create thing) en STEP 2 (go to the url)


You second post:
> Hi, according to the documentation the account thing will be created when you open the URL 
> http://172.19.40.111:8080/amazonechocontrol/" as outlined in my initial statements. or am I wrong?

No, re-read the linked documentation it tells you to create the Thing _before_ going to the url.

The linked post from the community just adds one step (installing the binding) but yeah, it has the same steps....
