### ISSUE TITLE
[mongodb] Should implement ModifiablePersistenceService

### ISSUE THREAD

**Issue by ulbi** [openhab/openhab-addons#16338]
Using the REST API persistence methods against the MongoDB persistence is not possible when using mongodb persistence services.
Following REST API should become available as well:
- unable to store historic value through (PUT /persistence/items/{itemname})
- unable to remove persisted values throught (DELETE /persistence/items/{itemname})

## Your Environment
* Version used: latest openhab docker release 4.1-alpine

**Comment by lsiepel** [comment]
Pr is merged
