### ISSUE TITLE
[mybmw] make update interval more flexible and introduce manual updates

### ISSUE THREAD

**Issue by martingrassl** [openhab/openhab-addons#16351]
as the BMW API restricted the number of requests to the API, the continuous polling of updates leads to quota errors. One solution is to 

- separate the calls to the status updates, the charging statistics and the images
- allow users to force the update of status, charging and image

Therefore it should be possible to disable automated polling by setting the refresh interval to e.g. 0

## Your Environment

* Version used: (e.g., openHAB and add-on versions) 4.1.x
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 17
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Openhabian

**Comment by TheTrueRandom** [comment]
@martingrassl additionally I would suggest to add a thing config property `refreshIntervalWhileCharging` (or similar).
A typical usecase is to have a smart wallbox which uses data from this binding. 
Personally I would choose the default `refreshInterval` high (30 minutes) to not exceed the ratelimits but during charging I need more frequent data than this for accurate charging control.

**Comment by martingrassl** [comment]
> @martingrassl additionally I would suggest to add a thing config property `refreshIntervalWhileCharging` (or similar). A typical usecase is to have a smart wallbox which uses data from this binding. Personally I would choose the default `refreshInterval` high (30 minutes) to not exceed the ratelimits but during charging I need more frequent data than this for accurate charging control.

Hi @TheTrueRandom,

I think this should be controlled by a rule. We would need a charging switch which has to be turned on to enable this refresh while charging.

I'm planning to implement a rule which checks if the car is in the garage and then triggers the refresh only each two hours and when the car is outside the refresh is triggered more frequently. This should avoid to reach the limit. You could do the same when you connect to the wallbox.

I'm almost done with the implementation, I just have (again) the issue that the main branch is already at 4.2 and there is a change which prevents the binding to run successfully at 4.1. I'm about to build a jar file for 4.1 and once it is working fine for me I'll upload it to my repo so you can check if it fits your need.

**Comment by lsiepel** [comment]
Does rule in this case stand for an openHAB rule or some logic rule within the binding, I hope the latter. 
As the API has some quota, are these documented or reverse engineered in some way?

**Comment by martingrassl** [comment]
For me the rule has to be in OH, not in the binding. The purpose of the binding is to bring the car data into OH which is represented by the vehicle thing. The wallbox thing is separate and to bring both together is the purpose of the OH rules. If supporting functionality is required, for sure it could be implemented within the binding - like the switches I'm implementing right now. 

Unfortunately there are some discussions going on regarding the quota, but as far as I know nobody found out yet what exactly this means...

**Comment by lsiepel** [comment]
> nfortunately there are some discussions going on regarding the quota, but as far as I know nobody found out yet what exactly this means...

Too bad the API is not clear about the quota.

From a user perspective, having a low frequency update interval is fine, but like @TheTrueRandom explains, while charging you typically want to have a higher frequency of updates. Why do you want to control this from an openHAB rule and not have this incorperated intto the binding?

**Comment by martingrassl** [comment]
Unfortunately I have no EV so maybe I misunderstand the request. In general for sure we can introduce this property for EVs and when the state is charging, then the frequency should be different to when the state is not charging. My problem is right now that usually the car starts charging when you connect the cable to the wallbox or the power outlet. And if you configure an update frequency quite high like 2 hours, in the worst case you would detect only 2 hours later that the car is charging and then maybe the higher refresh frequency would be activated.

What I'm thinking about is rather that the wallbox most probably is integrated into OH as well and there you get immediate status if charging starts - and then you can create a rule which runs e.g. each 5-10 mins to check if charging is active and then trigger the "force immediate refresh" which I'm about to introduce with the next release.

I have only an ICE car so maybe I don't have the need for those frequent updates. I just want to get a nice consumption curve in a diagram, that's why I'm thinking about creating a rule which checks if the vehicle is at home and if not, it updates more frequently and if it is at home, it just updates every 2 hours or so to avoid running into the limit...

**Comment by martingrassl** [comment]
I got it working now in my OH 4.1.2 sandbox environment. If you want to be my beta testers, just try the 4.1.2 jar file from https://github.com/martingrassl/openhab-mybmw.

I had to delete the official binding and put the jar into the addons folder. You can now set the refresh interval to 0 and you get for ICE cars two new channels and for xEV cars three new channels for each vehicle:
![image](https://github.com/openhab/openhab-addons/assets/28385614/a864c7f6-90f8-4661-afa7-ea9a0b61fa1c)
these switches trigger the update of the data separately. If the automated refresh is triggered, all data is updated at the same time. If everything works fine and as expected, I would try to get the change into 4.2.0

Feedback very welcome :)

**Comment by TheTrueRandom** [comment]
@martingrassl thanks. I agree that making it rule controlled would be more adequate, as you explained the trigger is external, not from the bmw binding (plugging in the car to the wallbox). This would be perfectly fine for me, however the updateInterval needs to be a channel then? I think it's not possible or a good practice to patch the thing configuration from a rule. 
> You can now set the refresh interval to 0
what's the result of that? No automatic updates by the binding itself? Only using the Force update command? If so, that would probably solve the issues with a simple rule (need to try it)

**Comment by martingrassl** [comment]
So if you set the interval to 0, no automated update will be triggered - there is a log message informing you about that. 
My idea was to rather configure the interval in the openhab rule like you would have maybe two rules:
- one triggered each 10-15 min which trigger the update only if the charging is active
- one complementary rule triggered each one or two hours which updates the state only if charging is not active

BTW I didn't mention that if you set the force switch to on, it will immediately be set to off so that you can just switch to on in the rule and don't have to take care about switching it off again. I had no better and easier idea how to do that 😀

**Comment by lsiepel** [comment]
I better understande your use case now. How are you going to implement this?
Something like low frequency updates, and if the binding detects it is charging or a command 'high frequency updates' is set, it updates more frequently. Afdterwards the BMW binding knows when the charging is completed so it can finish it by itself (and obivously also by the switch?

**Comment by TheTrueRandom** [comment]
@martingrassl that's perfect.

**Comment by martingrassl** [comment]
> I better understande your use case now. How are you going to implement this? Something like low frequency updates, and if the binding detects it is charging or a command 'high frequency updates' is set, it updates more frequently. Afdterwards the BMW binding knows when the charging is completed so it can finish it by itself (and obivously also by the switch?

So what I could do is to check if the charging state is charging, then trigger the scheduler job and when the charging state is different to charging, stop the scheduler job.

Then it would look something like this (prerequisite - separate configuration property for the charging update interval):
1. plug vehicle into wallbox / charger -> the Openhab rule would trigger the force update when it detects that the wallbox is charging
2. the state update of the vehicle would show that the vehicle is charging
3. the scheduler would be triggered with the interval of the charging updates
4. stop charging / unplug vehicle from wallbox
    - the Openhab rule would trigger again the force update when it detects that the wallbox is not charging anymore
    - alternatively the next run of the scheduler job would detect that the vehicle is not charging anymore and stop the scheduler job

then there would be only the minimum requirement to create the start trigger rule in Openhab, everything else would be done within the binding. 

This could be implemented. The current beta version only supports the control from Openhab by just creating the two rules explained above... I'm not sure if a binding should have so much implicit functionality or just be a plain provider for data, but I see as well the advantage in having this functionality inside of the binding.

**Comment by lsiepel** [comment]
> s could be implemented. The current beta version only supports the control from Openhab by just creating the two rules explained above... I'm not sure if a binding should have so much implicit functionality or just be a plain provider for data, but I see as well the advantage in having this functionality inside of the binding.

Yes, that sounds great as the trigger would be generic, for this use case it would be for charging, but there might be more use cases to perform an extra aditional manual update.

**Comment by lsiepel** [comment]
> st didn't create a PR yet, as I have to up


Yes.
