### ISSUE TITLE
[Melcloud] triggering "We have detected excessive traffic from your account" and not working

### ISSUE THREAD

**Issue by WereCatf** [openhab/openhab-addons#16385]
## Expected Behavior
Binding is supposed to connect to Mitsubishi's Melcloud service and allow for querying and controlling of ACs and heat pumps.

## Current Behavior
It seems like Melcloud has begun to track how often the service is queried and throttles its usage. The Melcloud binding doesn't work and attempting to log in to the Melcloud service directly via a web browser only results in an "We have detected excessive traffic from your account, your access to the service has been limited for a few hours." error message and won't let me so much as get the current room temperature, let alone do anything else.

Disabling the binding and waiting several hours before trying again lets one log in via a browser again. Enabling the binding works only for a short period of time and then causes a repeat of the issue.

## Possible Solution
How often the binding queries whatever it queries by default should probably be adjusted. No idea how much, though; still testing.

## Steps to Reproduce (for Bugs)
1. Install Melcloud binding.
2. Log into your Melcloud account and set up your AC/heat pump.
3. Wait for the issue to appear.

## Your Environment
* Version used: 4.1.1
* Environment name and version: ?
* Operating System and version: Ubuntu 23.10

**Comment by willyfromtheblock** [comment]
+1, same issue with home assistant probably https://github.com/home-assistant/core/issues/109728

**Comment by WereCatf** [comment]
> +1, same issue with home assistant probably [home-assistant/core#109728](https://github.com/home-assistant/core/issues/109728)

Yeah, looks like it. I am trying to figure out, if changing the interval helps and if so, what it needs to be changed to. Alas, it takes at least three hours for the lock-out by Melcloud to get released, so this is an annoying thing to test...

**Comment by hjw2015** [comment]
+1

**Comment by WereCatf** [comment]
Setting a query interval of 10 minutes worked the entire night without triggering the throttling. Gonna try 5 minutes next.

**Comment by WereCatf** [comment]
I see Home Assistant went with 5 minutes, but with 5 minutes, I got intermittent, shorter errors every now and then. With 6 minutes, I haven't gotten any. As such, I propose changing the default interval to 6 minutes, ie. 360 seconds.

**Comment by thewiep** [comment]
Thanks for reporting!
I've got similar info from a forum topic and am looking into it, I'll perform the required changes and try to create a PR somewhere next week.

@WereCatf, how many devices do you have in your account?
Could be useful to determine min and default values.

**Comment by WereCatf** [comment]
@thewiep I only have a single device, unfortunately. It did occur to me that someone with a large number of devices might run into the issue even with a 6min interval, but I have no good way of testing that.

**Comment by rrrrado** [comment]
I have 4 devices . Could it help?

**Comment by thewiep** [comment]
@WereCatf Perfect! In a forum topic I have info from people with 2 or 3 and I have 3 myself so good to know that 6 minutes works for you.

I just made some changes and am testing myself with 6 minutes so will see what this gives tomorrow.

@rrrrado You could test with 6 minutes to see if you still have the error or not.

**Comment by sanjoyprasad** [comment]
Struggling to find out where I to change the polling frequency in HA. Can anyone help?

**Comment by lucacalcaterra** [comment]
> Struggling to find out where I to change the polling frequency in HA. Can anyone help?

@sanjoyprasad change pollingInterval according doc https://www.openhab.org/addons/bindings/melcloud/

I'll submit a PR that fix default value

**Comment by WereCatf** [comment]
@lucacalcaterra They were asking about Home Assistant (ie. HA), not OpenHAB. I don't see how HA is relevant here, though.

**Comment by jcarlosrga** [comment]
Same problem. :(

**Comment by rrrrado** [comment]
300 secs polling interval fixed the problem for 4 devices

**Comment by thewiep** [comment]
I submitted a PR that sets the minimum value to 300 and the default value to 360.

**Comment by lucacalcaterra** [comment]
@thewiep good !
