### ISSUE TITLE
[shelly] Support for Shelly Plus H&T 3rd Gen

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#16404]
A new device generation of Plus H&T was launched

Technical Information: https://kb.shelly.cloud/knowledge-base/shelly-h-t-gen3

**Comment by markus7017** [comment]
inmplemented

**Comment by lsiepel** [comment]
Do you have a jar like you have on the other shelly issues? (i really like those posts with all details, really helpfull!)

**Comment by markus7017** [comment]
has already been merged, there is always the DEV build
