### ISSUE TITLE
[shelly] "Web socket error" during channel setup (Shelly 2.Gen 1PMplus with Add-on)

### ISSUE THREAD

**Issue by xvs03** [openhab/openhab-addons#16417]
Shelly Binding in connection with shelly 2.Gen 1PMplus with Add-on

When setting up the temperature channels, the binding goes into "web socket error" and has to be restarted. In addition, assigning the sensors is a game of chance because the channels are not assigned to a sensor address. A sensor is assigned to a channel at random.

OpenHAB Community Topic:
[https://community.openhab.org/t/shelly-binding-thing-websocket-error/153927?u=xvs03](url)

## Expected Behavior
The temperature sensors should be assigned to the addresses given to them by the Shelly (100),(101),(102) so that the values can be assigned to an item.

## Current Behavior
The sensors are assigned at random and you never have the right item assigned.

## Possible Solution
The Shelly diagnosis writes an error message that is not explained to me anywhere. 
`shelly_notification:116 ch type=WS_in info=192.168.178.22:43900 has no DST`
maybe you can find the bug about it

## Steps to Reproduce (for Bugs)
1. Add Shelly as a Thing and try to assign the sensors.
2. Thing then goes into "Web Socket error"

## Your Environment
OpenHABIAN with openHAB 4.1.1
Shelly Plus1PM Firmwar 1.2.0

**Comment by markus7017** [comment]
which OH release?
release build, SNAPSHOT-BUILD or DEV-Build for 4.2?

**Comment by markus7017** [comment]
no feedback

**Comment by lsiepel** [comment]
> which OH release? release build, SNAPSHOT-BUILD or DEV-Build for 4.2?

Isn’ that available in the last two lines of the start post?

> OpenHABIAN with openHAB 4.1.1
Shelly Plus1PM Firmwar 1.2.0
