### ISSUE TITLE
[VeSync] Add "Change mode to auto" for Air Purifier Core 300S

### ISSUE THREAD

**Issue by icsAT** [openhab/openhab-addons#16456]
I just got an Levoit Air Purifier Core 300S. And I am Using openHAB 4.1.1.

When I try to set fanMode to "auto" using openHAB with the VeSync-Binding I receive:
`Fan mode command for "auto" is not valid in the (Core200S/Core300S) API possible options manual,sleep`
The openHAB Documentation says the same, so the error makes sense. Works as designed.

If I use the VeSync App I am able to set the fanMode to "auto" and the value of the channel in openHAB becomes "auto", too.

Therefore I think there should be a possibility to set "fanMode" to "auto" for the Core 300S through the API and it would be great if someone could add this to the binding.

**Comment by dag81** [comment]
I'll have a look when I can and compare to the latest PyVeSync revision. It was ported directly from that pyton lib, so it maybe at that point in time either no support existed, if its documented that way - that would have been the mappings originally ported over. It may be no one has reverse engineered the lib for PyVeSync for the auto functionality, that could be another reason in which case the command is unknown for what to send. I'll check as soon as I can @icsAT, just wrapping up a different binding at the moment first.

**Comment by dag81** [comment]
Hi @icsAT,

Sorry it took a really long time to get back. I compared the spec's and can see fan speeds 1...5 are now listed as valid for that device, and fan modes auto, manual, sleep.

I've just raised a PR with the changes, could you possibly check with this build the fan modes now work as you expect please, and possibly the fan speed's 1..5 as well please, given the new spec details.

Many thanks - and big apologies for not having the time until now to look at this.

David

Download link to the build from the PR I believe is here:

https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.vesync/4.3.0-SNAPSHOT/org.openhab.binding.vesync-4.3.0-SNAPSHOT.jar

**Comment by icsAT** [comment]
Hey @dag81,

no need to apologize. I know the value of time and I have developement projects myself, where I am not able to step foreward, because of time issues and prioritization.

I am on Stable 4.2.3 now.

As far, that I can tell from a short test, it is possible to set the 'auto' fanMode on my Core 300S now.

Thanks a lot.

Setting fan speed between 1 and 3 (C300S only has 3 levels) is also possible, as it was before. (For additional Information see #16457)


Greetings

icsAT

**Comment by dag81** [comment]
> Hey @dag81,
> 
> no need to apologize. I know the value of time and I have developement projects myself, where I am not able to step foreward, because of time issues and prioritization.
> 
> I am on Stable 4.2.3 now.
> 
> As far, that I can tell from a short test, it is possible to set the 'auto' fanMode on my Core 300S now.
> 
> Thanks a lot.
> 
> Setting fan speed between 1 and 3 (C300S only has 3 levels) is also possible, as it was before. (For additional Information see #16457)
> 
> Greetings
> 
> icsAT

I replied on the wrong thread, thanks for confirming. Let clean up the change to just the mode options, the pyvesync code didn't align to the manuals I was reading earlier. That clarifies thank you! :)
