### ISSUE TITLE
[jsscripting] Memory Leak on .js file Reloading

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#16462]
I use OH 4.1.1 on 64bit ARM (AARCH64, to be precise `qemu-system-aarch64 -M raspi3b -cpu cortex-a72`) with jsscripting/graalvm.  Before I start OH, the directory /etc/openhab/automation/js is empty (contains only node_modules directory). I create /etc/openhab/items/a.items with content
```
Switch x1 "x1" ["Energy", "Light"]
```
I start openHAB on a system with 1GB RAM, OH uses 40.5% of the RAM. Then I execute
```bash
#!/bin/bash

function wawa() {
  sleep 120
  while : ; do
    cat /proc/loadavg | awk '$1 > 2 { exit 1 }'
    [ $? -eq 0 ] && return
    sleep 10
  done
}

cat > /etc/openhab/automation/js/abcd.js <<EOF
let m = new Map, volts = items.getItem('x1')
for (let i = 0; i < 100000; i++) m.set(i, new String(i))

rules.JSRule({
 name: 'T', triggers: [triggers.GenericCronTrigger("0 0 17 * * ?")],
 execute:() => {
   console.log('abcd');
 }
})
EOF

while : ; do
  wawa
  echo -n "{" >> /etc/openhab/automation/js/abcd.js
  wawa
  echo -n "};" >> /etc/openhab/automation/js/abcd.js
done
```

First run - [openhab.log](https://github.com/openhab/openhab-addons/files/14410197/log1.txt) - after 24 hours OH uses 61.4% of RAM, then load avegare is 0.50, so system does nothing, despite abcd.js being changed.

Second run, after repeating the steps above from the beginning - [openhab.log](https://github.com/openhab/openhab-addons/files/14410201/log2.txt) - takes 5 hours, uses 62.6% of RAM afterwards.

Once abcd.js is loaded 2-3 times, the memory usage is 55.4%.  After OH logs all of the above, it stops reloading `abcd.js` and it uses 61.4% or 62.6% of the RAM.  While the above bash programme runs, the memory usage of OH does increase slowly.  The system (qemu-system-aarch64) does nothing else, which is not mentioned here.  This is a new installation.

For me the increasing memory consumption and the `org.graalvm.polyglot.PolyglotException: Java heap space` message are indications for a memory leak.  Also working on a normal system with real devices I have the feeling that each .js reload takes longer time than the previous one.

The third test.  Here I stop openHAB, delete everything from /etc/openhab/automation/js/ except node_modules, start OH.  Once everything is loaded, I start the same script as above, but with doubled sleep times and also waiting when the load avegare is above 1:
```bash
#!/bin/bash

function wawa() {
  sleep 240
  while : ; do
    cat /proc/loadavg | awk '$1 > 1 { exit 1 }'
    [ $? -eq 0 ] && return
    sleep 30
  done
}

cat > /etc/openhab/automation/js/abcd.js <<EOF
let m = new Map, volts = items.getItem('x1')
for (let i = 0; i < 100000; i++) m.set(i, new String(i))

rules.JSRule({
 name: 'T', triggers: [triggers.GenericCronTrigger("0 0 17 * * ?")],
 execute:() => {
   console.log('abcd');
 }
})
EOF

while : ; do
  wawa
  echo -n "{" >> /etc/openhab/automation/js/abcd.js
  wawa
  echo -n "};" >> /etc/openhab/automation/js/abcd.js
done
```
This way, once `abcd.js` is modified and Java needs CPU to handle the change, `abcd.js` is not modified as long as the load average is not below 1.  As time passes, the interval between the moments where the load average is below 1 get bigger.  This can be seen by the increasing time gaps between the “(Re-)Loading script” lines. That is, OH is doing something else, apart from parsing the new script, and then throwing away the old JS file.  Here again, per cent of memory used increases over time.  I have observed, that at 12:18 the memory used was 56.8%, while at 13:53 it was 56.5%, so it has decreased.  After 60h the memory used was 58.5%, but the load average was above 1, so the .js file was not changed. To be precise, after 25h of running, the load average went above 1 and since then the .js file was not changed.

Thirt run - [openhab.log](https://github.com/openhab/openhab-addons/files/14410194/log3.txt).

**Comment by jlaur** [comment]
Looks similar to #12577.

**Comment by florian-h05** [comment]
Hmm, you are right, there is a memory leak, but only if the execution of a script failed.
If a script does not fail to load/execute, you can change and reload it as many times as you want and heap usage always goes back to a normal level when GC runs (also verified by checking heap dumps with VisualVM).

However, if scrit loading/execution fails, there is a memory leak, which is also visible in the heap dump (screenshot from VisualVM):
![image](https://github.com/openhab/openhab-addons/assets/73423173/ae2d8d5a-9ca8-4d29-8e43-aa6e3d814471)

As you can see, the GC root is the logging library used by openHAB, which causes the `OpenhabGraalJSScriptEngine`s created on script loading to be not removed from heap by GC. 
Luckily, I think I have already identified the problem ...

**Comment by florian-h05** [comment]
With #16578 and https://github.com/openhab/openhab-core/pull/4162, heap usage and heap dumps both look good to me. There is now only one instance of `OpenhabGraalJSScriptEngine` in the heap, which is the correct behaviour.

**Comment by dilyanpalauzov** [comment]
I am very glad that this was aprroached, as OH went instable, when I changed the JS files on the disk and occasionally made syntactic errors.

The change in https://github.com/openhab/openhab-core/pull/4162/ contains
```
  // Only call logger if debug level is actually enabled, because OPS4J Pax Logging holds (at least for
  // some time) a reference to the exception and its cause, which may hold a reference to the script
  // engine.
  // This prevents garbage collection (at least for some time) to remove the script engine from heap.
```
My feeling is that these references are hold forever, so «at least for some time» is not accurate.

**Comment by florian-h05** [comment]
> My feeling is that these references are hold forever, so «at least for some time» is not accurate.

Foreever would make sense wrt your reported issue, however I’m not entirely sure if it is for some time or forever, I have to check this in the heap snapshots, but I  am AFK at the moment.

**Comment by florian-h05** [comment]
So, additional testing and a few more heap dumps have shown that the references are not hold forever, but only for some time, see https://github.com/openhab/openhab-core/pull/4162#issuecomment-2026960133.

After running the reproduce script from above with sleep time 5 seconds for 20 minutes with both the fixed add-on and fixed core, i have taken a heap dump, and I can only see two OpenhabGraalJSScriptEngines for abcd.js, one is currently loading the script file, the other one is not unloaded yet.
This means there is no memory leak left wrt to the JS Scripting add-on :-)

FYI, I can see the heap usage increasing over time, but as soon as GC is triggered, heap usage goes back to the normal level. On my laptop with max heap size 6 GB, GC seems to not run very often, but if I trigger it manually, heap usage goes back to the value before the reproduce script was invoked.
