### ISSUE TITLE
[Zigbee] SLZB-06M does not connect

### ISSUE THREAD

**Issue by madhacker3kxl** [openhab/openhab-addons#16473]
Using SLZB-06M to connect to openhab does not work. It will say socket connection fail. Any way to support Ethernet connected devices?

Reply from vendor:

> I can see that the communication between the SLZB-06 and openhab is working and packets are being forwarded but the requests that openhab is sending are incorrect.
> SLZB-06 runs on koenk's z-stack firmware and it's designed to work with Z2M and ZHA, and it looks like some commands are different/missing in it so openhab won't work.
> I also tested SLZB-06M here the situation is the same, communication starts but it seems that openhab is designed for the old version of ezsp and does not work with the new ones that are flashed into our coordinators.

Openhab Version: openHAB 4.1.1

**Comment by lsiepel** [comment]
Can you raise this issue here: https://github.com/openhab/org.openhab.binding.zigbee  as Zigbee has its own repository.
