### ISSUE TITLE
OH4 and Homematic HM-PB-6-WM55 does not work

### ISSUE THREAD

**Issue by MA74SC** [openhab/openhab-addons#16470]
Updated today from openhab 3.4.5 to openhab 4.1.1. on my unraid device. (docker installed via unraid docker app)
Both eco systems run with homematic binding connected to homegear 0.7.51.
Now I figured out that this device will not be updated on event long press or short press.
In parallel I created new items connected to HM-PB-6-WM55 channels TEST_COUNTER and SIM_COUNTER.
Both values do not change on any event - doesn’t matter if button 1,2,3,4,5 or 6 is pressed until restarting openhab server.
Connected to homegear server, each button press is recognized, checked by TEST_COUNTER and SIM_COUNTER which are counting up.
After openhab started up I can see that connected items will show identical values like homegear session.

I tried several configurations

adding the Thing manually (scanning doesn’t work, even with OH2 and OH3), adding items manually
adding the Thing manually, items by old config file
adding the Thing and Items by old config file
adding the Thing by old config file, items manually
Noone of above mentioned worked, all shows same results

Thank you for your help

**Comment by maniac103** [comment]
> Now I figured out that this device will not be updated on event long press or short press.

What exactly do you mean by 'updated' here? Normally I'd expect the use case for buttons to trigger rules by their trigger channels?

In any case, setting log level to trace (`log:set TRACE org.openhab.binding.homematic`), and providing the log of pressing a few buttons would be helpful.

**Comment by MA74SC** [comment]
found the issue that ports 2001, 2002 and 2003 were not mapped correctly
