### ISSUE TITLE
[HTTP] Don't translate a few technical strings

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#16483]
## Expected Behavior

I expect some very technical terms not to be translated, e.g. the HTTP method "POST" or the content type "application/json":

## Current Behavior

They are translated to German:
![grafik](https://github.com/openhab/openhab-addons/assets/22525368/569d36e0-048e-483a-90ca-6d4743b1915f)

## Possible Solution

Exclude them from Crowdin.

## Steps to Reproduce (for Bugs)

1. Start openHAB in German
2. Add a HTTP binding thing

**Comment by jlaur** [comment]
This is a result of:

```xml
			<parameter name="stateMethod" type="text">
				<label>State Method</label>
				<description>HTTP method (GET,POST, PUT) for retrieving a status.</description>
				<options>
					<option value="GET">GET</option>
					<option value="POST">POST</option>
					<option value="PUT">PUT</option>
				</options>
				<limitToOptions>true</limitToOptions>
				<default>GET</default>
				<advanced>true</advanced>
			</parameter>
```

generating this when running `mvn i18n:generate-default-translations`:

```ini
thing-type.config.http.url.stateMethod.label = State Method
thing-type.config.http.url.stateMethod.description = HTTP method (GET,POST, PUT) for retrieving a status.
thing-type.config.http.url.stateMethod.option.GET = GET
thing-type.config.http.url.stateMethod.option.POST = POST
thing-type.config.http.url.stateMethod.option.PUT = PUT
```

I'm not sure what would be the best way to fix this properly, but I'm not sure the HTTP binding is the place for that. Maybe some way of excluding strings from the I18N tool?

**Comment by lsiepel** [comment]
If it is due to the translation file, i think this should be corrected in crowdin, not in the binding.

Another cause might be that this is correct in the properties file, but translated by the browser on the fly. If so, we could choose to add a html tag `notranslate` to the option elements, but that would need this issue to be transferred to the webui. And it has some side effects, so don't know.

**Comment by J-N-K** [comment]
Someone (I don't have enough rights) need to change it on Crowdin. @mueller-ma already posted the correct value for this translation. This is not a binding issue but QA of the translations.
