### ISSUE TITLE
Translations from Bulgarian not reviewed for 9 months

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#16505]
Similar to https://github.com/openhab/openhab-webui/issues/1929 I have made translations to Bulgarian at https://crowdin.com/editor/openhab-addons/all/en-bg for `openhab-addons` nine months ago.  These are neither approved nor disapproved yet.

**Comment by lolodomo** [comment]
We probably need someone talking Bulgarian to review and validate translation proposals. Would you like to be this one ?

**Comment by lolodomo** [comment]
@wborn : can you do that?

**Comment by wborn** [comment]
Even if they were approved they will not be merged as only files that are 100% translated are added to PRs generated by Crowdin.

**Comment by wborn** [comment]
You are now a proof reader for Bulgarian so you can approve them yourself @dilyanpalauzov. :wink:

**Comment by dilyanpalauzov** [comment]
For https://crowdin.com/project/openhab-addons/bg it works now, as opposed to https://crowdin.com/project/openhab-webui/bg.

**Comment by dilyanpalauzov** [comment]
> Even if they were approved they will not be merged as only files that are 100% translated are added to PRs generated by Crowdin.

This is not good, as sometimes it is unclear what the context of the string is, in other words there are no terms in the destination address, so translating does not make the translation more understandable, than the original wording.
