### ISSUE TITLE
[boschindego] Mower not found anymore

### ISSUE THREAD

**Issue by BillGOH** [openhab/openhab-addons#16517]
New season, new problems. Single ID login works. However, the mower is not connected any more. The thing says: "The request failed with error: 403"

I tried to use the discovery feature of the binding: no result.

I am using openHAB 4.1.1.

I guess Bosch has changed something on their servers again (should better spend their time on improving their mowers)?

Any ideas?

P.S.: Maybe the colleagues form Home Assistant have faced the same problem? See https://github.com/jm-73/Indego/issues/204

**Comment by jlaur** [comment]
See also https://community.openhab.org/t/bosch-indego-how-to-use-bosch-single-id/146299/20. It seems I forgot to create an issue for tracking this - thanks.

**Comment by BillGOH** [comment]
Thanks - as always - for your quick response and helpful remarks. I am not an expert here, but is there a chance to "simulate" the "UserAgent" of the app?

In any case: That's another reason to avoid Bosch products in the future.

**Comment by jlaur** [comment]
> I am not an expert here, but is there a chance to "simulate" the "UserAgent" of the app?

See my comment here: https://community.openhab.org/t/bosch-indego-how-to-use-bosch-single-id/146299/24

Besides that, I think we are now also in lack of a method for getting the initial OAuth2 access token. At least I'm not sure if this is still possible through a browser using the browser's user-agent.

**Comment by BillGOH** [comment]
SingleID login worked for me after the winter with the method described in the docs.
