### ISSUE TITLE
[hue] Step size for INCREASE/DECREASE commands is too large for APIv2

### ISSUE THREAD

**Issue by maniac103** [openhab/openhab-addons#16532]
The hue binding accepts IncreaseDecreaseType for brightness channels for both CLIP1 and CLIP2 light resources. For CLIP2, the number of steps is significantly lower than for CLIP1.

## Expected Behavior
The number of steps should be similar for CLIP1 and CLIP2, and it should be of reasonable size.

## Current Behavior
CLIP1 uses a step size of 30 on a 0..255 scale leading to 9 possible steps.
CLIP2 also uses a step size of 30, but on a 0..100 scale, leading to only 4 possible steps, which seems way too coarse.

## Possible Solution
Shrink step size for CLIP2 from 30 to 10, leading to 10 possible steps, which additionally are spaced evenly.

**Comment by maniac103** [comment]
@andrewfg Do you agree to my behavior expectations? If so, I can submit a PR.

**Comment by andrewfg** [comment]
> Do you agree to my behavior expectations? If so, I can submit a PR.

@maniac103 yes that's fine with me. My original choice of 30 was fairly arbitrary.
