### ISSUE TITLE
[shelly] Wrong model for Shelly Plus 10V

### ISSUE THREAD

**Issue by martin67** [openhab/openhab-addons#16542]
My Shelly Plus 10V only gets the channels 
* relay#input
* relay#button

Thing properties are:
```
deviceGeneration 2
coiotAutoEnable false
wifiNetwork Hagelin IoT
deviceMode 
updateStatus
firmwareVersion 1.2.2-/20240223
deviceAuth no
devUpdatePeriod 70
serviceName shellyplus010v-e86beae44c70
updateNewVersion
deviceName Yttre hall
updateAvailable no
modelId SNDM-00100WW
macAddress E86BEAE44C70
updateCurrentVersion 1.2.2-
vendor Shelly
```

When looking in the source code, it seems like this device has another modelID (SNDM-00100WW) than whats defined in:
`public static final String SHELLYDT_PLUSDIMMER10V = "SNGW-0A11WW010";`

I don't know it this has anything to do with the problem

## Expected Behavior
I'd expect that all values as described in https://www.openhab.org/addons/bindings/shelly/#shelly-plus-dimmer-10v-thing-type-shellyplus10v to show up.

BUT - In the Shelly native web UI, there are no meter values or any option to calibrate. I don't know if it's even possible to calibrate these devices.

## Current Behavior
So it seems to be some mismatch between my Shelly Plus 10V and what's defined in openHAB. Right now I'm not able to control it from OpenHAB which is a problem.

## Your Environment
* openHAB 4.2.0.M1, Linux

**Comment by markus7017** [comment]
you are right, it seems that the model id has changed from pre-production to production
try this build: 
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true

**Comment by markus7017** [comment]
@martin67 Did you verified the updated build?


[4.2-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true) | [4.1-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar?raw=true) | [4.0.-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.0.5-SNAPSHOT.jar?raw=true) | [3.4.5-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.5-SNAPSHOT.jar?raw=true) | [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) | **[READMEbeta](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)** 
[Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) -  [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server) | [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de)

---

Note: The DEV build is always newer than the version in the official Distro or Milestone builds. Current development is based on 4.2-SNAPSHOT, **4.0.x and 3.4.x are outdated**.
