### ISSUE TITLE
oh4.2M1 missing sungrow binding

### ISSUE THREAD

**Issue by Trickx** [openhab/openhab-addons#16558]
According to the [release notes for openHAB 4.2M1](https://github.com/openhab/openhab-distro/releases) the new sungrow binding is included.
But it seems not being included.
[openhab-addons-4.2.0.M1.kar](https://github.com/openhab/openhab-distro/releases/download/4.2.0.M1/openhab-addons-4.2.0.M1.kar) does not include any sungrow binding.

**Comment by wborn** [comment]
It's part of the Modbus binding but it didn't install the bundle so I've created #16557 to fix that.
