### ISSUE TITLE
[Renault] Cockpit/odometer information no longer retrieved

### ISSUE THREAD

**Issue by maxonthegit** [openhab/openhab-addons#16669]
## Expected Behavior
One of the channels exposed by things created with the [Renault binding](https://www.openhab.org/addons/bindings/renault/) is `odometer`, which is supposed to indicate the total distance traveled so far. Linking a _Number_ type item to this channel is expected to provide a reading of the car odometer.

## Current Behavior
Up to a few days ago, the odometer reading was regularly available. Then, suddenly, the linked item just ceased to be updated: the car odometer in the _My Renault_ mobile app continued to increase, confirming that such information is available in the My Renault cloud, but the item was just frozen at the last available reading.

None of the following attempts restored the expected odometer reading:
* pausing and resuming the thing created with the Renault binding
* creating a new Renault car thing from scratch and linking the existing item to its `odometer` channel
* forcedly setting the existing item to a different value from the Karaf console and waiting for it to be updated
* creating a new item and linking it to the `odometer` channel

No relevant errors appear in the Karaf console using `log:tail` when either of the aforementioned actions is undertaken (just some warnings about known unsupported features of this car model, like lock status update, HVAC and battery status; these have always been there anyway).

## Possible Solution
Developers of the [renault-api project](https://github.com/hacf-fr/renault-api), the openHAB Renault binding is based upon, have already spotted a change in the Renault API that causes cockpit reading to fail being retrieved: this is documented in their [issue #1135](https://github.com/hacf-fr/renault-api/issues/1135).

As a fallback, the API call for the cockpit data should be reverted to using version 1 of the API. As of version 4.1.2 of openHAB and of the `org.openhab.binding.renault` binding, this corresponds to updating [line 238](https://github.com/openhab/openhab-addons/blob/f466c88406c506baf75ddccd9df597cf4aa3d964/bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api/MyRenaultHttpSession.java#L238) of file `/bundles/org.openhab.binding.renault/src/main/java/org/openhab/binding/renault/internal/api//MyRenaultHttpSession.java` from:
```
                + "/kamereon/kca/car-adapter/v2/cars/" + config.vin + "/cockpit?country=" + getCountry(config));
```
to:
```
                + "/kamereon/kca/car-adapter/v1/cars/" + config.vin + "/cockpit?country=" + getCountry(config));
```

To verify this suggestion, I have attempted to rebuild the addon using Maven after applying this change, and the `odometer` reading became available again in the usual expected way.

## Steps to Reproduce (for Bugs)
1. Install the [Renault binding](https://www.openhab.org/addons/bindings/renault/) in an openHAB 4.1.2 instance.
2. Create a thing using the Renault binding.
3. Create a _Number:Length_ item pointing to the `odometer` channel of the freshly created thing.
4. Check that the item is never updated.

## Context
N/A

## Your Environment
I am using the latest stable (4.1.2, release build) version of openHAB, packaged in a Docker container created from its [stock `openhab/openhab` image](https://hub.docker.com/r/openhab/openhab/).
Although this is of limited relevance, Docker is executed on a Raspberry Pi OS/Raspbian installation which is at release 11 (bullseye).

**Comment by dougculnane** [comment]
https://github.com/openhab/openhab-addons/pull/16675 applies suggested fix. 

Thanks for the excellent work @maxonthegit
