### ISSUE TITLE
[Netatmo] Siren channel on Netatmo Presence Outdoor Camera with Siren not working

### ISSUE THREAD

**Issue by multimartin** [openhab/openhab-addons#16707]
Happy to announce that will the latest update to the Netatmo binding (latest 4.2.0 snapshot), my Netatmo Presence Outdoor Camera with Siren is working fine (again).

Except for one thing: the Siren channel is still not working in the binding.

The channel is an ON/OFF type - which initalizes to "null". When switching ON, the log produce the following:

`2024-04-30 09:07:21.534 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setstate 
2024-04-30 09:07:21.684 [WARN ] [andler.capability.SecurityCapability] - Error changing siren status 'SOUND' : Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']
`

When switching OFF, the log produce the following:
`2024-04-30 09:07:59.025 [DEBUG] [mo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setstate 
2024-04-30 09:07:59.119 [WARN ] [andler.capability.SecurityCapability] - Error changing siren status 'NO_SOUND' : Rest call failed: statusCode=INVALID_ARGUMENT, message=property /home/modules/0: should NOT have additional properties ['siren_status']
`

When I originally requested the channel to be added, we discussed it in this bug report: [https://github.com/openhab/openhab-addons/issues/14466#issue-1592328235](url)

I can still switch the siren using CURL - and in the Netatmo App - so the siren as such is working. Just not in the binding.

I am happy to test any bug-fixes - but cannot suggest changes to the code myself ;-)

I am running openHAB 4.2.0.M2 with the latest snapshot of the binding in the add-on folder. My Openhab is run in Ubuntu 22.04.4 LTS.

**Comment by clinique** [comment]
@multimartin : you'll maybe not like the way this one has been closed but it is the way it is.

**Comment by lolodomo** [comment]
Closed by #17397
