### ISSUE TITLE
[solarforecast] suspend API calls over night

### ISSUE THREAD

**Issue by weymann** [openhab/openhab-addons#16728]
Copied from https://github.com/weymann/OH3-SolarForecast-Drops/issues/2

Thanks for the great work on the binding. Saves me a ton of JSON fiddling! ;)

Would it be possible to define a period of no polling? So you could spare precious API calls over night, when there's no need to update information? Possible having the chance to either:

1) define a switch-item, which tells the binding to do API-Calls or suspend them
2) define Astro-binding items/channels which trigger local dusk/dawn periods?

ad 1
I could then use whatever means to turn that item ON or OFF (possibly using Astro-binding)

ad 2
I could then just use a fully configured Astro-binding to use for suspending

**Comment by weymann** [comment]
The throttling of the free Solcast account is very strict and contains ~24 calls per day. 2 calls are necessary per plane  so this will result into the default update frequency of 2 hours.

Community discussion is already raised to find a better strategy like [here ]( https://community.openhab.org/t/solar-forecast-pv/137681/23)and [here](https://community.openhab.org/t/solar-forecast-pv/137681/26). Also this [enhancement was raised in my drop repo](https://github.com/weymann/OH3-SolarForecast-Drops/issues/2) and I tranferred it to openHAB addons repo.

**My proposal:**
- user has the opportunity to switch off bindings regular schedule with _advanced configuration parameter_ `refreshManual`
- user can implement his own strategy in rules and `triggerUpdate` via _Rule Action_
- example is given in readme with update after startup plus 2 hours update _only during daytime_

**Comment by lsiepel** [comment]
Maybe offer three modes?
1. Even, each 2 hours one call
2. Daytime, each hour from 8:00, and last at 19:00 ?
3. Manual

**Comment by weymann** [comment]
> Maybe offer three modes?

To be very honest I don't want to offer modes. Too much strategy possibilities and then binding is dependemt on Astro binding plus I've to maintain them.

- maybe you want one update after midnight even if sun is down
- maybe one update after sunrise and then hourly
- maybe you want more frequent updates in winter - shorter day time => more frequent updates possible

I'm personally fine with the given `refreshInterval` of 2 hours but if any user wants something different they can start with the example rule and then evolve.

**Comment by lsiepel** [comment]
> > Maybe offer three modes?
> 
> To be very honest I don't want to offer modes. Too much strategy possibilities and then binding is dependemt on Astro binding plus I've to maintain them.
> 
> * maybe you want one update after midnight even if sun is down
> * maybe one update after sunrise and then hourly
> * maybe you want more frequent updates in winter - shorter day time => more frequent updates possible
> 
> I'm personally fine with the given `refreshInterval` of 2 hours but if any user wants something different they can start with the example rule and then evolve.

That is ok, effectively two ‘modes’ (auto vs manual) is already giving a lot of flexibility.

**Comment by lsiepel** [comment]
@weymann did you manage to proceed on this issue?

**Comment by weymann** [comment]
@lsiepel Yes, feature branch is finished. Waiting for bugfix https://github.com/openhab/openhab-addons/pull/16996 to be integrated in order to avoid conflicting PRs.

**Comment by weymann** [comment]
@lsiepel please close this issue because PR #17335 is merged

**Comment by weymann** [comment]
Solved with #17335
