### ISSUE TITLE
[dsmr] Just tested it in 4.2.0-SNAPSHOT and the "Actual Power Delivery" channel is shown twice in the UI.

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#16731]
Just tested it in 4.2.0-SNAPSHOT and the "Actual Power Delivery" channel is shown twice in the UI. 
![image](https://github.com/openhab/openhab-addons/assets/15975712/65968e63-773a-439a-91e6-2d38f673f5f0)

_Originally posted by @dequeckerp in https://github.com/openhab/openhab-addons/issues/15038#issuecomment-2102649211_
            
It seems the label is wrong here, the channel id is emeter_actual_demand @coop-git is that a good conclusion and are you able to come up with a PR if that is the case?

**Comment by coop-git** [comment]
Yes, it was a copy of another/existing channel type. I can come up with a PR but need to setup my environment to 4.2
Depending on personal/work planning this can take a while.

**Comment by lsiepel** [comment]
> Yes, it was a copy of another/existing channel type. I can come up with a PR but need to setup my environment to 4.2 Depending on personal/work planning this can take a while.

Just created a PR, maybe you can just have a look and confirm this is all it takes.
