### ISSUE TITLE
[shelly] BLU HT - sensor channels missing

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#16736]
Binding version: SNAPSHOT 4.2.0.202404071245

The BLU HT device only shows the standard channels after discovery. The temperature and humidity sensor channels are not generated.

![grafik](https://github.com/openhab/openhab-addons/assets/61476442/6f591e6c-3b1f-43e6-a3da-20b37776977d)

The log file from adding the device:
[openhab_BLU_SBHT.log](https://github.com/openhab/openhab-addons/files/15272508/openhab_BLU_SBHT.log)

The script console output on the gateway device shows when BT button is pressed:
BTH: unknown type

**Comment by ijasan** [comment]
I found out that some sensor id definitions were incorrect and some were missing.

Based on the documentation at:
[https://shelly-api-docs.shelly.cloud/docs-ble/Devices/ht/](url)
and
[https://bthome.io/format/](url)

the definitions should be adjusted:

Typo in line "BTH[**0x43**] = { n: "UVIndex", t: uint8 };" --> wrong ID, should be **0x46**.

According to Shelly documentation above, BLU HT uses the following ID's for the temperature and humidity sensor:

```
BTH[0x2e] = { n: "Humidity", t: uint8 };
BTH[0x45] = { n: "Temperature", t: int16, f: 0.1 };
```

These two must be added to the script. The sensors are then recognized and the two missing channels are generated by the binding.


In addition, the other definitions should also be checked. For example, the factor for sensor 0x51 "Acceleration" is 0.01, which differs from the documentation. Here 0.001 is specified.

**Comment by markus7017** [comment]
yes, you are right

try this build
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw?true

**Comment by markus7017** [comment]
verified @ijasan
