### ISSUE TITLE
[shelly] Range Extender Support is enabled by default

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#16734]
Binding version: SNAPSHOT, **4.2.0.202404071245**
 
When new Things are added, Range Extender Support is enabled by default in the Thing configuration. 
This option should be switched off by default.

![grafik](https://github.com/openhab/openhab-addons/assets/61476442/1e48cca0-7aea-43ec-b33f-9febf94b2cab)

As an example, the log file from Discovery of a Plus Plug device:
[openhab_RExt.log](https://github.com/openhab/openhab-addons/files/15271520/openhab_RExt.log)

**Comment by markus7017** [comment]
try this build, you need to remove and re-discover the device
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true
