### ISSUE TITLE
[Shelly] New Device Mini 1 Gen 3

### ISSUE THREAD

**Issue by SimoBa80** [openhab/openhab-addons#16773]
http://192.168.101.126/rpc/Shelly.GetConfig:
[Shelly.GetConfig.json](https://github.com/openhab/openhab-addons/files/15368733/Shelly.GetConfig.json)

http://192.168.101.126/rpc/Shelly.GetStatus
[Shelly.GetStatus.json](https://github.com/openhab/openhab-addons/files/15368731/Shelly.GetStatus.json)

openhab> bundle:list | grep Shelly
316 x Active x  80 x 4.2.0.202405112307     x openHAB Add-ons :: Bundles :: Shelly Binding

If more informations are needed i will will provide it :)
Thanks and Regards
Simon

**Comment by markus7017** [comment]
Please try latest DEV build


[4.2-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true) | [4.1-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar?raw=true) | [4.0.-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.0.5-SNAPSHOT.jar?raw=true) | [3.4.5-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.5-SNAPSHOT.jar?raw=true) | [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) | **[READMEbeta](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)** 
[Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) -  [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server) | [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de)

---

Note: The DEV build is always newer than the version in the official Distro or Milestone builds. Current development is based on 4.2-SNAPSHOT, **4.0.x and 3.4.x are outdated**.

**Comment by SimoBa80** [comment]
openhab> bundle:list | grep She
282 x Active x  80 x 4.2.0.202405241838     x openHAB Add-ons :: Bundles :: Shelly Binding

I could add it under the name "ShellyPlus 1 Mini" so it seems to work now, could you add an seperate name for it like "mini 1 Gen3"?

Simon

**Comment by alaub81** [comment]
Under openHAB 4.2.0 the 1PM mini Gen3 Device is working for me. Discovery was fine, adding it, read the values and switching on and off, too!

**Comment by lsiepel** [comment]
@markus7017 I'm not into the Shelly names, can you confirm this was added in: https://github.com/openhab/openhab-addons/pull/16335 ? If so, this issue can be closed.

**Comment by markus7017** [comment]
this will be supported by PR #17166, which will just be merged
