### ISSUE TITLE
[homeconnect] Bridge is online, but all connections 401

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#16788]
I followed the guide in the docs, but I cannot make the homeconnect binding work.

## Expected Behavior

When the bridge says "Online", it's working.

## Current Behavior

The bridge Thing is Online and `/homeconnect` looks like this:

![grafik](https://github.com/openhab/openhab-addons/assets/22525368/972ff115-fe8b-4271-a228-28b441506249)

However no appliances show up and the Thing inbox is empty. Also a manual Thing scan for new Homeconnect things doesn't show up any appliances.
![grafik](https://github.com/openhab/openhab-addons/assets/22525368/9216c5fe-e3ca-491d-bfdd-fb01cf26ce52)

![grafik](https://github.com/openhab/openhab-addons/assets/22525368/9b124f4e-94c8-4105-9362-c76a68db8158)

## Your Environment

````
runtimeInfo:
  version: 4.1.2
  buildString: Release Build
````

**Comment by lsiepel** [comment]
When you clicked the authorized bridge button and you completed the steps on the remote site, did you enter the same emailadres as you use in the homeconnect app or the emailadres of your developer account ?

**Comment by mueller-ma** [comment]
Yes, I used the same email adress for:
- Homeconnect app
- Dev account
- as "Home Connect User Account for Testing"

**Comment by lolodomo** [comment]
In your home connect dev app, did you use HTTP or HTTPS for the redirect URL ? Mine is HTTP with IP of my local OH server as domain name.

**Comment by lolodomo** [comment]
You can click on "API Requests" in the left menu to see all requests and which one is failing. This should give information of the reason.

**Comment by mueller-ma** [comment]
There are several requests with the same error code. One can be seen in the last screenshot in my first post here.

**Comment by lolodomo** [comment]
Oh sorry, I did not see it.
Token is invalid because revoked.
Strange, sorry I have no idea why it( does not work for you.
How is set your redirect URL in your Home Connect app ?

**Comment by mueller-ma** [comment]
The URL is set to the one shown on the /homeconnect dashboard. Does it have to be reachable from the Home Connect servers?

**Comment by lolodomo** [comment]
Here is how it looks in my case:
![image](https://github.com/openhab/openhab-addons/assets/10186704/59c1e384-d1c3-4592-af6e-35ef51cfde4b)

> Does it have to be reachable from the Home Connect servers?

No. But it should be properly defined and should link to an OH URL. In my case: http://<OH IP>:8080/homeconnect
