### ISSUE TITLE
[homekit] Thermostat mode HEAT is recognized although disabled 

### ISSUE THREAD

**Issue by tmsch13** [openhab/openhab-addons#16791]
## Expected Behavior
the docs (https://www.openhab.org/addons/integrations/homekit/) says: 
> Example: if your thermostat does not support cooling, then you need to limit mapping to OFF and HEAT values only:
> 
> String          thermostat_current_mode    "Thermostat Current Mode"            (gThermostat) {homekit = "CurrentHeatingCoolingMode" [HEAT="HEATING", OFF="OFF“]}

So, because I only whant to setup "cooling" an „off“ for my AC Inverters, I configured as follows in OH GUI
```
config:
  COOL: ON
  OFF: OFF
```

Expected Behavior would be a Thermostat Device in Homekit, that has the modes „cooling“ an „off“ and shows the state „cooling“ when the connected openhab item hast state ON, and OFF when the item is in state OFF.
 
## Current Behavior
The device only shows „cool" and „off“ in Homekit, but it allways says „heating“ when turned on.

In openhab-cli i found the answer:
`[TRACE] [essories.HomekitCharacteristicFactory] - getKeyFromMapping: characteristic Thermostat, state OFF, mapping {OFF=OFF, HEAT=ON, COOL=ON}`

So HEAT seams to have the value „ON“ by default, even if only cool and off is configured, an so heat is not beeing displayed in homekit. That way, ON is always reported as HEAT to Homekit.

So there seems to be no way to exclude the HEAT Mode and use a switch item to control the AC Inverter.

## Possible Solution
maybe 
```
config:
  COOL: ON
  OFF: OFF
  HEAT: disabled
```
or just disable it when no config is set

## Steps to Reproduce (for Bugs)
Setup a Homekit.Thermostat group in OH.
Setup a Switch item, within that group with homekit config: 
```
value: Thermostat.CurrentHeatingCoolingMode,Thermostat.TargetHeatingCoolingMode
config:
  COOL: ON
  OFF: OFF
```

## Your Environment
openhabian with openHAB 4.1.2

**Comment by ccutrer** [comment]
I have a fix for this ready, but it conflicts with #17134, so I need that merged first before I can send a PR for this.
