### ISSUE TITLE
[Cloud] myOpenhab Cloud service is connected, but MainUI remains empty in mobile App and myOpenhab Webview

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-addons#16809]
## Expected Behavior
Until yesterday, connections via myOpenhab worked with presenting the MainUI overview page

## Current Behavior
Noticed this morning, that

- Android App 3.7.0
- iPhone App 2.4.56
- HomeDashboard via myOpenhab web service

just show a blank screen where it had the MainUI overview page before. Lokal access via Android/IOS App as well as lokal web access still work.

BUT: Remote integration via **Alexa is still working**. I can switch items via voice commands.

I already restarted the  openHAB Cloud connector service. It gets connected immediately:
```
2024-05-27 13:04:42.732 [INFO ] [io.openhabcloud.internal.CloudClient] - Shutting down openHAB Cloud service connection
2024-05-27 13:04:42.740 [WARN ] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected: io client disconnect
2024-05-27 13:04:42.750 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = 4e...71, base URL = http://localhost:8080)
2024-05-27 13:04:49.473 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = 4e...71, base URL = http://localhost:8080)
```
 ... as well as the mobile apps. 

## Steps to Reproduce (for Bugs)
The behaviour persists after all restarts of the mobile apps and the cloud connector service and has been reported on the community forum as well, e.g.:
https://community.openhab.org/t/openhab-is-offline-error/154427/11

## Context
Remote UI control is no longer possible, at least not when using MainUI.

## Your Environment
Server openHAB 3.4.0 Release Build
Android app 3.7.0
IOS app 2.4.56

**Comment by digitaldan** [comment]
Sorry about that, we did a small deployment that created an api endpoint to return some info on the proxy settings for our mobile clients. Unfortunately this set the host header we send in the request to a users’s openHAB to https://home.myopenhab.org:443 instead of home.myopenhab.org:443 (its not suppose to have the protocol in it). Jetty, which is what openHAB uses for web requests, choked on this and was trying to parse it as a ipv6 address. So while openHABs where connected, http requests back to them will malformed.

I just made a fix and deployed it, things should be back to normal now or at least in a few mins when everyone connects.

**Comment by snemias** [comment]
> Sorry about that, we did a small deployment that created an api endpoint to return some info on the proxy settings for our mobile clients. Unfortunately this set the host header we send in the request to a users’s openHAB to https://home.myopenhab.org:443 instead of home.myopenhab.org:443 (its not suppose to have the protocol in it). Jetty, which is what openHAB uses for web requests, choked on this and was trying to parse it as a ipv6 address. So while openHABs where connected, http requests back to them will malformed.
> 
> I just made a fix and deployed it, things should be back to normal now or at least in a few mins when everyone connects.

Thank you

**Comment by curlyel** [comment]
Many thanks. Just tried: Works again as before...
