### ISSUE TITLE
[aWattar] Bestprice Thing -> feature request: "WorstPrice" channel

### ISSUE THREAD

**Issue by AndyNeubacher** [openhab/openhab-addons#16813]
Hi,

i'm using the best-price feature from the aWattar binding ... works great and many thx for that!!

What i've added with a dsl-rule is a "WorstPrice" channel where the grid-price is the most expensive. With this trigger/channel i block my heatpump and other high power consumers from beeing enabled. Usually the gridprice is similar to a sine-wave with the highest peak in the morning (6-8am) and a high peak in the evening (7-9pm).

With my dsl-rule i split the day in two 12h sections an find the "WorstPrice" hour(s) in each section. With a "Duration" i can set how many (consecutive) hours i block the consumers.

Unfortunately my java-skills aren't good enough to extend the bestprice-thing with this function :|  ... maybe someone could help out :)

thx & br,
Andy

**Comment by tl-photography** [comment]
https://github.com/openhab/openhab-addons/pull/16877

**Comment by tl-photography** [comment]
Can this be closed?

**Comment by AndyNeubacher** [comment]
yes, and many thx for the feature!
