### ISSUE TITLE
[atlona] use new SDDP discovery in core

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16825]
We recently implemented an SDDP discovery service in OH core. Currently this binding uses a binding specific custom version of SDDP for thing discovery. So perhaps the author should consider to replace that with the core SDDP discovery instead?

**Comment by andrewfg** [comment]
Ping @mlobstein :)

**Comment by mlobstein** [comment]
I had forgotten about this one that I had adopted. I also have a small tweak to SddpDiscoveryService that I will raise a PR for.
