### ISSUE TITLE
[volumio] play playlist not working

### ISSUE THREAD

**Issue by stargazer74** [openhab/openhab-addons#16826]
## Expected Behavior
If I send a name of a playlist to volumio, the playlist should play. 

`items.getItem('Volumio_Play_Playlist').sendCommand('rock');`

## Current Behavior
Nothing is playing.

## Possible Solution
The commands defined in 
`public class VolumioCommands`
have to be camel-case.

`public static final String PLAY_PLAYLIST = "play-playlist";` must be changed to `public static final String PLAY_PLAYLIST = "playPlaylist";`

See: https://developers.volumio.com/api/websocket-api

## Steps to Reproduce (for Bugs)
1.  define playlist in Volumio
2. try to play it via addon_channel "Play Playlist"

## Your Environment
* Version used: openhab v 4.1.2

**Comment by lolodomo** [comment]
Closed by #16828
