### ISSUE TITLE
[hue] Managing automations

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#16904]
I see some use-cases in being able to manage automations from openHAB:

![image](https://github.com/openhab/openhab-addons/assets/19519842/96d60566-66f5-4920-96a6-8aa11b5f4211)

It would be useful if openHAB could turn these automations on or off.

I imagine exposing each automation as a `Switch` channel. These channels could be on the Bridge thing, since there would be only once instance of them, and they do not represent any physical devices. This would be similar to [automations on the Hunter Douglas PowerView Hub](https://www.openhab.org/addons/bindings/hdpowerview/#channels-for-hub-1-2-thing-type-hub-or-gateway-3-thing-type-gateway). They should belong to a channel group, and they could be marked as advanced.

The resource type representing these automations is `behavior_instance`.

Getting all instances:
`GET https://{{host}}/clip/v2/resource/behavior_instance`
(also included in `GET https://{{host}}/clip/v2/resource`)

Example for [enabling an automation](https://developers.meethue.com/develop/hue-api-v2/api-reference/#resource_behavior_instance__id__put):

`PUT https://{{host}}/clip/v2/resource/behavior_instance/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

Payload:
```json
{
    "enabled": true
}
```

**Comment by jlaur** [comment]
@andrewfg - WDYT?

**Comment by andrewfg** [comment]
Yes.

**Comment by andrewfg** [comment]
@jlaur I will create a PR for this
