### ISSUE TITLE
[boschshc] Bosch devices do not get battery level updates

### ISSUE THREAD

**Issue by mike-bike** [openhab/openhab-addons#16930]
Hi there, I do have 13 battery powered Bosch devices (Twinguards, Thermostats I & II, Door contacts II) and all reported battery levels are constant 100% since months. For the thermostats opening/closing multiple times / day, I’d expect some change at least. For me it seems that the channels do not receive any updates. Even a restart of the bridge binding or OpenHAB does not give any other reading. Same is happening on current stable as well as snapshot release.

Regards,
Michael

PS: Running openHAB 4.2.0 on a RPI4 with openHABian.

**Comment by mike-bike** [comment]
@jlaur, many thanks for flagging that as a bug. I wanted to check with other users if this is not working for my setup only before filing an issue. I take no response from the community, that I am not alone :-)

**Comment by lsiepel** [comment]
> @jlaur, many thanks for flagging that as a bug. I wanted to check with other users if this is not working for my setup only before filing an issue. I take no response from the community, that I am not alone :-)

It is just a label, no confirmation. Maybe @david-pace can comment here?

**Comment by mike-bike** [comment]
My ask was if I need to file an issue or not? I had started with a question to the group. ThanksAm 04.07.2024 um 21:18 schrieb lsiepel ***@***.***>:﻿

@jlaur, many thanks for flagging that as a bug. I wanted to check with other users if this is not working for my setup only before filing an issue. I take no response from the community, that I am not alone :-)

It is just a label, no confirmation. Maybe @david-pace can comment here?

**Comment by lsiepel** [comment]
I think this question is better to bne asked in the community forums. Anyway, battery devices usually do not report a linear degradation, typically they 'suddenly' drop. I have multipel devices from other brands (zigbee and zwave) that act the same.

When the app or software from Bosch reports something different then the binding you can file it as an issue. If they are the same, please close this as it is not an issue in this binding.

**Comment by david-pace** [comment]
The battery level can only be reported as low or critically low once this is reported by the Smart Home Controller as well. In this case you will see device-specific warnings in the App (in the upper right corner when tapping on the bell icon). Please confirm whether any battery level warnings are present there.

**Comment by mike-bike** [comment]
Thanks for the explanation, David. This was a misunderstanding on my side. I assumed the Bosch battery levels are reported similar to HUE devices; at least the motion sensors seem to report "linear" degradation. All devices report 100%. I recall one replacement earlier this year. OpenHAB graph shows a sudden drop from 100% to 10%. Not sure if 10% is considered as "low" or "critical low". I may check a bit closer when the next device gets low.

**Comment by mike-bike** [comment]
Bosch battery level are reported as few discrete values (e.g. full, low, critical low) and not as linear % values. Binding is working correctly.
