### ISSUE TITLE
[aWATTar] Update prices more than once a day

### ISSUE THREAD

**Issue by thomasleber** [openhab/openhab-addons#16939]
Following up todays havoc on the EEX, we should consider updating the price more than once a day.

The EEX had a hick-up today, spiking the price in Germany and Austria up to 4€ per kwh.

The plugin would only update the price once at 1500 (afaik from code). The prices seemed normal at 1500 CEST.
But at 1508 it seems an update occurred, showing new data.

The plugin would not update the prices, leading the schedules to not be aligned with the updated data.

## Expected Behavior
New marked prices will be used when an update occurs.

## Current Behavior
Scheduler will update once a day at 1500, ignoring all the following updates.

## Possible Solution
Schedule more often an update eg. at 1500, 1800, 2300

## Steps to Reproduce (for Bugs)
--

## Context
https://montelnews.com/news/e072de7e-5651-4abe-b817-cf76e8e95d28/decoupling-causes-huge-price-variations

## Your Environment
OpenHAB 4.1.3

**Comment by tl-photography** [comment]
I have only mobile screenshots but I have made one before and after restarting the bridge today:

![Screenshot_20240626-101908](https://github.com/openhab/openhab-addons/assets/30150514/92a2df54-d2fa-4a09-b54a-6344bdb10510)
![Screenshot_20240626-102242](https://github.com/openhab/openhab-addons/assets/30150514/5001b835-a7c1-490b-ad88-30c37c6e61ed)

**Comment by J-N-K** [comment]
@thomasleber Can you check with the latest code (i.e. 4.3.0-SNAPSHOT)? I believe this is also fixed by #17032.

**Comment by thomasleber** [comment]
`localPrices.last().timerange().start() < Instant.now().toEpochMilli() + 9 * 3600 * 1000;` will return true when the the current time plus 9h is larger than last entry of todays prieces.

**Comment by tl-photography** [comment]
I have tried to fix that here: https://github.com/openhab/openhab-addons/pull/17068
