### ISSUE TITLE
[openhabcloud] Support new notification features

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#16934]
# Mobile Notification Enhancements

Using this ticket to coordinate changes between our various projects to support new notifications features. This includes:

* click action - Allowing the user to specify an 'action' to execute when a mobile notification is clicked
* button actions -  Allowing the user to provide addition custom buttons (long press on notification) that execute an 'action' when clicked
* media attachments - Allowing the user to provide a URL to media that will be attached to the notification

## Message Payload Keys (Proposal)
* `title` - Title of the notification
* `on-click` - Click Action (see action format)
* `actions` -  Button Actions
* * Format is `["title1" : "action", "title2" : "action",...]`
* * See Action Format for `action`
* `media-attachment-url` -  URL of media (must be reachable by device)

##  Action Format

An action can be either a `command`,  `ui`, `http` or `https` action.

### Command Action
`command:itemName:commandString`

Example: `command:KitchenLights:ON`

### UI Action
`ui:$itemCommandSyntax`

where `$itemCommandSyntax` is  the same syntax as defined  at https://next.openhab.org/docs/mainui/about.html#ui-command-item

Example 
* `ui:navigate:/page/my_custom_page`
* `ui:popup:$target` (where $target is "page: + a page ID",  or "widget: + a widget ID", etc...) 
*  `ui:sheet:$target`

**OR**

`ui:$path`

where `$path` is either `/basicui/app?.....` for sitemaps (native sitemap renderer will be used) or `/some/absolute/path` for navigating the view.  `$path` in either case starts with a `/`  

Example
* `ui:/basicui/app?w=0000&sitemap=main` (use the WebUI to get sitemap URL locations)
* `ui:/page/page1` (will force the browser to go to this page)

### http | https action

`https://openhab.org`

This will open the link in a embedded browser, and is meant for loading external web pages. 

## Sample Payload

This is what may be sent from the binding to openHAB Cloud

```json
{
  "media-attachment-url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/OpenHAB_logo_2.svg/541px-OpenHAB_logo_2.svg.png",
  "message": "Test Notification",
  "title": "openHAB",
  "on-click": "ui:popup:widget:myKitchenWidget",
  "actions": [
    {
      "title": "Turn Kitchen Lights ON",
      "action": "command:KitchenLightst:ON"
    },
    {
      "title": "Turn Kitchen Lights OFF",
      "action": "command:KitchenLights:OFF"
    },
    {
      "title": "View Kitchen",
      "action": "ui:navigate:/page/Kitchen"
    }
  ]
}
```

## Associated Tickets
Android: https://github.com/openhab/openhab-android/issues/3193 (original discussion here)
IOS: https://github.com/openhab/openhab-ios/pull/764
Cloud:  https://github.com/openhab/openhab-cloud/pull/462
MainUI: https://github.com/openhab/openhab-webui/pull/2622
Cloud Addon: #16938
openhab-js: https://github.com/openhab/openhab-js/pull/351
Blockly: TBD
Docs: #16941 and https://github.com/openhab/openhab-docs/pull/2320

## TODO

Checklist for implementation:
- [x] Binding
- [x] openHAB Cloud
- [x] Android app
- [x] iOS app
- [x] Main UI
- [x] Blockly
- [x] Docs

Notify maintainers of other UIs:
@openhab/webui-maintainers 
@openhab/android-maintainers 
@openhab/ios-maintainers 

Sample Screen Shot (IOS)
![IMG_5C6672F754A4-1](https://github.com/openhab/openhab-addons/assets/1903737/62d47c3e-14f6-4d32-9272-3f99e3b30256)

**Comment by maniac103** [comment]
Does iOS limit the number of actions? Buttons in Android are limited to a maximum of 3, FWIW, so if iOS has a similar limitation, we may want to state that in the documentation of the feature.

**Comment by digitaldan** [comment]
Its a good question, a quick search shows that its also 3 for IOS , not sure what happens when you try adding more then that, guess i'll test, but yes thats a good point, and will need to document. 

FYI, i have a central issue to centralize our discussions, https://github.com/openhab/openhab-android/issues/3193

**Comment by florian-h05** [comment]
If we get the required change to the openHAB Cloud Connector add-on done before the feature freeze, it would be possible to roll out the new notifications after the 4.2.0 release as we then only need to change cloud and the apps.

**Comment by digitaldan** [comment]
I had a similar thought, I think its very possible, I have the work half done, its actually not all that much to change, just adding a new overloaded method with the new fields.  I can at least try to get something ready for review today or tomorrow and see how close we are.  The cloud code is done, and i plan on pushing that out soon.

**Comment by seime** [comment]
What I would love to see is the possibility to cancel or retract notifications!

Use case(s): Retract an open door notification when it is closed. Or whenever something that passed a threshold value is reduced below the threshold again like power usage, temperature, humidity etc.

**Comment by digitaldan** [comment]
In rules, our send notification looks like this:

```java
public static void sendNotification(String userId, String message, @Nullable String icon,
            @Nullable String severity)
```

I was thinking to extend it to this, especially now that i know there is a max of 3 action buttons you can add on IOS/Android, notice that many parameters are optional (null) 
```java
public static void sendNotification(String userId, String message, @Nullable String icon, @Nullable String severity,
            @Nullable String onClickAction, @Nullable String mediaAttachmentURl, @Nullable String actionButton1,
            @Nullable String actionButton2, @Nullable String actionButton3) {
```
an action button String would have the following format `ButtonTitle=Action`,  for example  `Turn Kitchen Lights ON=command:KitchenLightst:ON`

Alternatively, we could have one actionButton string which `,` delimits actions, so `ButtonTitle=Action,ButtonTitle=Action`, but i kinda like having the 3 since it makes it clearer as @maniac103 pointed out.

**Comment by florian-h05** [comment]
> I can at least try to get something ready for review today or tomorrow and see how close we are.

Great!

> What I would love to see is the possibility to cancel or retract notifications!

Yeah, that would be absolutely amazing, but I think if we are able to ship the actions and images to openHAB 4.2.0 we already have a big improvement, but this would be a nice improvement for openHAB 4.3.0.

> In rules, our send notification looks like this:

I like that proposal, makes IMO more sense than the single, big string.

The JS and Ruby helper libraries could create a builder around this method to allow easier usage of it.

**Comment by digitaldan** [comment]
> I like that proposal, makes IMO more sense than the single, big string.

Excellent, I'll go with that then and work on this tonight.  Thanks for the feedback !

**Comment by digitaldan** [comment]
So i have a version of the cloud binding working and ready for a PR.  Just FYI, I'll probably give it a once over tomorrow, but its working nicely on my system so far.   See #16938

**Comment by florian-h05** [comment]
BTW I have already created a WIP PR for a notification builder for the openHAB JavaScript library: https://github.com/openhab/openhab-js/pull/351.

**Comment by digitaldan** [comment]
@mueller-ma @maniac103  quick question,  right now notifications have a single message.  In IOS notifications have both a `Title` and `Body` , we set the `Title` to `openHAB` and `Body` to the value of the message.   Should we allow the user to optionally set the Title as well (but would default to openHAB if not set) .  Hoping for a quick answer here, would be a small thing to add, but i want to do this (or not) before we merge anything.

**Comment by digitaldan** [comment]
Actually i think we should support Title, lets make Notifications as powerful as possible, and i don't want to have to come back and create another overloaded method just to support this in the future.

**Comment by mueller-ma** [comment]
It's similar to Android: Right now we don't set a title, but only a summary (probably what body is on iOS). Adding an optional title should be fine 👍

**Comment by digitaldan** [comment]
Great, thanks for the quick feedback.  I just updated the binding PR to support this and was able to test end to end with a IOS client.

**Comment by mueller-ma** [comment]
What about allowing an Image or Video Item name as value for media-attachment-url?

**Comment by digitaldan** [comment]
> What about allowing an Image or Video Item name as value for media-attachment-url?

I was also thinking to allow relative paths like `/static/html/....` and we would try hitting the user's openHAB instance.  The IOS client code right now is very simple and is just making a dumb http request, i need to implement using the remote/local connection info so we can use myopenhab if needed for proxing this connection .

**Comment by florian-h05** [comment]
But this should be client code, not cloud connector, so we should be able to merge the openHAB server changes now.

**Comment by digitaldan** [comment]
@florian-h05 correct, binding and cloud code should not care.  I think we can detect url patterns , maybe event item://imageItem or something like that for advanced use of pulling of images from items from clients.

**Comment by digitaldan** [comment]
btw, cloud code is deployed, so the binding should work in production

**Comment by mueller-ma** [comment]
> maybe even item://imageItem or something like that for advanced use of pulling of images from items from clients

The `item://` prefix should be required when the client handles it like this:
````
if value startsWith "/" -> relative url
else if value startsWith "http(s);//" -> absolute url
else -> item
````

**Comment by digitaldan** [comment]
So I started to actually use this feature on my home system, very very cool

![image](https://github.com/openhab/openhab-addons/assets/1903737/7f07c022-4612-4671-a949-67afe93b4ddc)

**Comment by ghys** [comment]
@digitaldan it's a great development, I've been wanting to get rich notifications for a long time.

I don't know if you're aware or remember, but I made an implementation of the Web Push API for HABot (see [here](https://community.openhab.org/t/habot-walkthrough-7-n-push-notifications/56045)). Depending on the browser and OS it can also display an image and action buttons in some cases:

https://developer.mozilla.org/en-US/docs/Web/API/Notification/image
https://developer.mozilla.org/en-US/docs/Web/API/Notification/actions

My main problem at the time was the authentication - since the web push notification feature didn't need openHAB Cloud at all it was difficult to get more than a basic notification because it would require authenticated access to your instance to get the image or perform the actions.

I wonder if it's the right time to resuscitate this web push thing, only in the main UI, with possibly rich notifications? On mobile you would be better served with the apps, of course, but this could introduce notifications for your desktop or laptop computer as well.

**Comment by digitaldan** [comment]
@ghys i'll definitely read up on browser notifications, its an area i know very little about, but it does sound like an awesome feature, especially if there might be a way to tie it in or unify it with mobile push.

**Comment by jimtng** [comment]
Suggestion: for action, add two more:

- `url:https://xxxxxx` - open the given url (using a built in browser? or launch default system browser?). This allows us to open e.g. Frigate's UI to show the full camera interface
- `app:appid` - launch the given app id - but this would not be the same between android vs ios, so might be tricky.

**Comment by jimtng** [comment]
Ruby support has been merged https://github.com/openhab/openhab-jruby/pull/285

```ruby
    notify "Someone pressed the doorbell!",
      title: "Doorbell",
      attachment: "http://myserver.local/cameras/frontdoor.jpg",
      buttons: {
        "Show Camera" => "ui:/basicui/app?w=0001&sitemap=cameras",
        "Unlock Door" => "command:FrontDoor_Lock:OFF"
      }
```

**Comment by digitaldan** [comment]
@jimtng those sound like good ideas.   The way IOS works, for `http(s):` i think we would need to bring the app to the foreground first (like we do with `ui:`) , then we could either launch an external web browser or the internal one.  And would be similar for `app:` as well.    I think on IOS, apps need to register  themselves to be opened via a URL , so like `myApp://somePath?foo=bar` , on Android i thought apps are launched via their bundle id, like `com.openhab.app`, but its been awhile since i have looked into it.  

Thanks for getting the ruby support in so quick!

**Comment by digitaldan** [comment]
when using image items for the `media-attachment-url` ,  how about using `item:myItemName` ?  This can still be parsed as a valid URI in both Swift and Kotlin for easy parsing

Kotlin , when using a URI object, would see this as 
```
Scheme: item
Host: null
Path: null
Query: null
Port: -1
Scheme Specific Part: myItemName
```
the item name would be located at `uri.schemeSpecificPart`

**Comment by digitaldan** [comment]
So the IOS app now supports using the `item:itemName` format for media attachments, i'm waiting on testflight to approve our initial build so we can start getting users on it to test.  Once that happens I'll update the IOS readme with the new App link and we can coordinate some messaging on the forums  to point users to it.

**Comment by digitaldan** [comment]
I updated the actions description to include  http/https links in actions , this has also been added to the IOS client.

**Comment by jimtng** [comment]
Please update https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.openhabcloud/README.md as that's my source of reference for this :)

**Comment by digitaldan** [comment]
I'll update the docs today, i don't think it should affect the rule libraries other then documentation ?  This was strictly a mobile client side implementation.

**Comment by florian-h05** [comment]
It is only a documentation update (in case of JS Scripting I just add a link to the new section for the media attachment url in the cloud add-on docs).

**Comment by digitaldan** [comment]
So i was looking into how to remove notifications from rules/actions,  which has been asked for a few times.

If we allow a user to pass an id (can be any string) when sending the notification, then we can add a new action method like `removeNotification(String id)` which would send a hidden notification that the app would use to remove any notification with that ID.  

I bring this up now b/c if its something we want to do, i would suggest we add this to the existing function now before anyone is using the new existing signature, otherwise we will have to create an extended one again later. 

@mueller-ma would this work for android ?

**Comment by mueller-ma** [comment]
Yes, that would work. Maybe we can have two more extensions to that:
1. Add a function `removeNotificationBySeverity(String severity)`, which uses the already present severity. Depending on the personal setup this might work as intended.
2. Add a new field to the database called `isShown` which is set to false when the `removeNotification()` is called. That way clients without push features can make use of this new feature.

**Comment by digitaldan** [comment]
>Add a new field to the database called isShown which is set to false when the removeNotification() is called. That way clients without push features can make use of this new feature.

I would need to check how we want to do this, i guess i would query the DB for messages with the user provided ID, and mark them hidden/not shown before sending the payload to the user.

> `removeNotificationBySeverity(String severity)` 

whats the use case for removing be severity?  I would think  different  notification types share the same severity (like my house alarm is going off, or i have a water leak).  On IOS this might be a little hard, i would need to track the ID's in local storage by severity (we don't get a apns message id until the message delivers to track, unless you set the collapse ID) 

One last thought, both android and IOS have the ability to set a collapse ID, so if i push a second message with this same ID, it replaces the existing one.  I think setting the same "user-notification-id" on multiple message should do the same thing.  This would be a really really great feature, when my garage door opens and closes for example, i don't want dozen of notifications hanging around for it, just the last one with the current state (for me at least) 

Here's how i would describe it:

## User Notification ID
* Messages with the same user provided ID will replace (collapse) existing notifications on the user's device with that ID
* The user provided ID can be used with `removeNotificationById(String id)` to remove a message from the user's device.

**Comment by digitaldan** [comment]
> On IOS this might be a little hard, i would need to track the ID's in local storage by severity (we don't get a apns message id until the message delivers to track, unless you set the collapse ID)

Actually, I think i can query for notifications still up and have access to their payloads, so maybe not so hard to implement.  So if there's a good use case, then i think it should be pretty easy.   We would probably then modify the payload to have a `remove-notifications-with-id` and `remove-notifications-with-severity` ?

**Comment by digitaldan** [comment]
@mueller-ma i was just looking into the `severity` field,  i think i misunderstood how this was being used, I assumed this was an Android SDK specific notification feature, but it seems like `severity` is more like a `tag` that you can use to group notifications together for filtering and sorting ?  The IOS client does not do anything with the `severity` value today, but i could see this being a useful feature, especially for removing groups of notifications.

I wonder if we should change the name `severity` to `tag` ?

**Comment by digitaldan** [comment]
One other thing @mueller-ma , we have an existing payload key `type` thats used for android here https://github.com/openhab/openhab-android/blob/143fe5372ba04d677c15ee28d59a9e7c7832907b/mobile/src/full/java/org/openhab/habdroid/core/FcmMessageListenerService.kt#L60   

I think thats ok to keep using.  If the notification has a type of `hideNotification`, then the payload would contain  at least one (or more) fields the clients would use to remove notifications.   

* `notificationId` Remove by persisted  ID (used in Android today, so not changing,  would not be in the binding)
* `severity` Remove by severity
* `user-notification-id` remove by the user supplied id

Let me know your thoughts, especially about naming of payload keys. 

Thanks !

**Comment by mueller-ma** [comment]
> I wonder if we should change the name severity to tag ?

Yes, sounds good 👍 

> Let me know your thoughts, especially about naming of payload keys.

I'd say: notificationId, tag (prev. severity) and referenceId should be fine.

**Comment by digitaldan** [comment]
Great, i have those changes in.  FYI  the severity field in REST response for `getnotifications` on the cloud service will still be there, but will represent the `tag` value for backwards compatibility, the payload data however on that response will use the key `tag`.   The notification payload from FCM will use the key `tag` even if severity is sent by older openHABs, the cloud service will make the translation, so severity should not be needed to check for in code.

**Comment by florian-h05** [comment]
As severity is now renamed to tag, should we update the notification builder in openhab-js?
I don‘t see a problem with doing that with the feature freeze, but changing it after the release would be a problem as user would already use it …
@digitaldan WDYT?

**Comment by digitaldan** [comment]
For sure!!! We should support `tag` in the builders over `severity`.   The legacy actions in the UI will still support the `severity` configuration parameter for backwards compatibility,  but i updated the label/description to indicate this is now equivalent to using tag.  Thanks!!!

**Comment by digitaldan** [comment]
Ok, cloud, binding and IOS code are ready (for review).  I'l deploy the cloud code probably later today when i have some time to test more.

**Comment by digitaldan** [comment]
Cloud code is deployed to production,  if you install the change in  #16979 you can use them.  Still waiting on Apple to approve our new test flight build of the client.

**Comment by florian-h05** [comment]
I have created a PR for openhab-js to adjust to #16979: https://github.com/openhab/openhab-js/pull/353

**Comment by digitaldan** [comment]
Apple has approved our new app for testing.  Just FYI ,  this is a new app, so your phone will have 2 openHAB apps.   Once we are close to releasing, we will push an update to our existing app to rename it  to "openHAB V1".  The V1 app will notify users of the new app and prompt them to install it.  The V1 app will be there for older IOS versions (pre  IOS 16) and for openhab 1.x support. 

https://testflight.apple.com/join/0uFYONeF

**Comment by florian-h05** [comment]
> So the IOS app now supports using the item:itemName format for media attachments, 

Can you please add this to the docs in your PR?

**Comment by florian-h05** [comment]
I have just installed the TestFlight app, however I cannot install p12 client certificate bundles. The app just keeps me asking for the password over and over again without installing the bundle.

**Comment by digitaldan** [comment]
>I have just installed the TestFlight app, however I cannot install p12 client certificate bundles

Hmm, i have not used that feature before, i'll see if i can get something up to test today.

**Comment by digitaldan** [comment]
>Can you please add this to the docs in your PR?

Good point, i added that in.

**Comment by digitaldan** [comment]
@florian-h05  looks like Apple does not work with the default pk12 export options in OpenSSL v3.   

See https://github.com/openssl/openssl/issues/19871 

adding `-legacy -certpbe pbeWithSHA1And40BitRC2-CBC` to the pk12 export command fixed the issue for me. 

I plan on massively updating the IOS README, maybe this weekend, I'll make sure to include this there.

**Comment by florian-h05** [comment]
@digitaldan 

> adding -legacy -certpbe pbeWithSHA1And40BitRC2-CBC to the pk12 export command fixed the issue for me.

Thanks! That fixed the issue for me.

**Comment by Mark-VG** [comment]
> As severity is now renamed to tag, should we update the notification builder in openhab-js?

These updates look amazing. Just one thing that I noticed is not on the Top Do list is to update Blockly to reflect these changes?

![image](https://github.com/openhab/openhab-addons/assets/84638697/c6fcd8de-eff9-4d08-bd85-6f0c5e14319d)

Currently Blockly uses "severity" only?

Thanks all - Appreciate Your Work.

**Comment by mueller-ma** [comment]
I saw the suggestion (not sure exactly where, though), that opening other apps via notification actions might be useful. I did some research on this and have bad news: When the app is published via Play Store, the required permission `QUERY_ALL_PACKAGES` is only allow for apps like anti-virus apps: https://support.google.com/googleplay/android-developer/answer/10158779

That means that it could be implemented in the app flavor distributed via F-Droid, but that's probably only a small user base.

**Comment by digitaldan** [comment]
Since everything has been completed here, i'm closing.   Thanks all for the quick work !

**Comment by mueller-ma** [comment]
> I saw the suggestion (not sure exactly where, though), that opening other apps via notification actions might be useful.

@digitaldan Can you check if that's possible on iOS?

**Comment by digitaldan** [comment]
Yes, this is possible.   You need to know the app's registered URL scheme,  its up to the 3rd party app to register that, for example i know spotify can be opened with `spotify://spotify:artist:SomeArtist`

**Comment by mueller-ma** [comment]
My usecase is: Send a notification when there's no alarm clock set for the next morning. A button can open the alarm clock app.
That app doesn't register custom URL, so I need to open it via package name (e.g. visible in the Play Store URL: https://play.google.com/store/apps/details?id=com.google.android.deskclock). Is it possible to open apps via package name on iOS as well? I'd keep both implementations similar.

> spotify://spotify:artist:SomeArtist

When you open e.g. https://open.spotify.com/intl-de/track/4uUG5RXrOk84mYEfFvj3cK on iOS, does it open the app? If so, that's a good workaround.

**Comment by digitaldan** [comment]
>Is it possible to open apps via package name on iOS as well?

It is not, but i don't think the package name would always align anyways, maybe we can support something like

app:ios:spotify://spotify:artist:SomeArtist,android:com.spotify.app`  ?

So the key is `app:` then each platform splits the rest of the string on `,` and looks for a entry that is prefixed with `ios:` or `android:`

**Comment by digitaldan** [comment]
also here is a good list of known apple URL schemes

https://github.com/bhagyas/app-urls

**Comment by mueller-ma** [comment]
Maybe with `=` for the platforms: `app:ios=spotify://spotify:artist:SomeArtist,android:=om.spotify.app` ?

**Comment by digitaldan** [comment]
yeah i think that works (and is close to the action command syntax, so consistent)

**Comment by digitaldan** [comment]
@mueller-ma, if we are good with that format, i can get the ball rolling on the IOS changes and doc changes.  

Also was chatting with @stefan-hoehn , he mentioned also wanting to add a `rule` action.   Seem reasonable. I was thinking about the format: `rule:uuid:prop1:prop2....propN` , thoughts?

**Comment by sebastiencastermans** [comment]
Hi guys,
I just read this whole conversation, it’s great work 👍🙌!!
Here are some comments, which I hope can be constructive 🙂 :
- On my OnePlus 11 phone, with the Openhab App (3.15.2) and with Firefox as default browser, http(s) actions do not work and crash the application, the Android dialog box appears to tell us that the app has crashed.
- The app action doesn't work too but I guess it's not yet implemented given the date of the last messages...
- It would be great to be able to implement all of this in blocky in order to have the JS code and to be able, for example, to send a notification with a body variable depending on an item. I still know how to do it with the old system but I haven't yet succeeded with a title, actions, image and all that stuff. Is it already possible to do this from JS scripts (application/javascript) ?

Big thanks for your work 😎🙃!

Sébastien

**Comment by Mark-VG** [comment]
> * On my OnePlus 11 phone, with the Openhab App (3.15.2) and with Firefox as default browser, 

I am only seeing 3.15.0 in teh APP Store? Just checked again.

> * The app action doesn't work too but I guess it's not yet implemented given the date of the last messages...

I have managed to get most of the actions to work. Just the ```ui``` and ```https``` seem to be a problem - see: 
https://github.com/openhab/openhab-android/issues/3755

> * It would be great to be able to implement all of this in blocky

Blockly enhancements are underway:

https://github.com/openhab/openhab-webui/pull/2672

**Comment by florian-h05** [comment]
> Is it already possible to do this from JS scripts (application/javascript) ?

Yes, only the Blockly implementation is missing (but it is worked on): https://www.openhab.org/addons/automation/jsscripting/#cloud-notification-actions

> I am only seeing 3.15.0 in teh APP Store? Just checked again.

I guess there is a staged rollout, so not everyone does receive the update at the same time.

**Comment by mueller-ma** [comment]
>  Seem reasonable. I was thinking about the format: rule:uuid:prop1:prop2....propN , thoughts?

Sure, why not. I guess there's some API to execute rules.

**Comment by digitaldan** [comment]
>Sure, why not. I guess there's some API to execute rules.

Yeah, there is a `runnow` endpoint (i did have to look that one up)  that takes in a rule `id` and then a param map like `{key1=value1,key2=value2}` so maybe the format should be

`rule:uuid:prop1=prop2,prop2=prop2`. where the props are optional

**Comment by mueller-ma** [comment]
Can you prepare a PR with the docs change? Please add me as reviewer to that PR.

**Comment by digitaldan** [comment]
Sorry for the late reply, yeah, i'll get that in this week.  I have a build of the IOS client that supports `app` and `rule`

**Comment by florian-h05** [comment]
@digitaldan Can you please update the docs?
