### ISSUE TITLE
[livisismarthome] Support for rebooting the smart home controller

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#16968]
It is possible to reboot the SHC (SmartHomeController) via the API. That should also be possible via OpenHAB for example to realize a rule that reboots the device at regular intervals or as a workaround for a memory leak that seems to still exist at some SHC1 devices.

**Comment by lsiepel** [comment]
Do you have documentation about that endpoint? If so it should not be that hard to implement.
