### ISSUE TITLE
[HomeWizard] request to add current and voltage channels to Wi-Fi P1 Meter thing

### ISSUE THREAD

**Issue by NickB1** [openhab/openhab-addons#16988]
Request to add current and voltage channels to Wi-Fi P1 Meter thing.
This can be helpful for current based load balancing applications.

**Comment by lsiepel** [comment]
Not sure if the p1 telegram’ data is fully available in homewizard. Are you aware of some documentation?

**Comment by NickB1** [comment]
The P1 telegram is fully available (https://api-documentation.homewizard.com/docs/endpoints/api-v1-telegram), not sure if the binding uses the telegram endpoint for it's channels though.
Current and voltage data is also available in the recent measurement endpoint: https://api-documentation.homewizard.com/docs/endpoints/api-v1-data

**Comment by NickB1** [comment]
Just took a look at the binding, it seems to use the /api/v1/data endpoint.

**Comment by lsiepel** [comment]
I have created a fix by adding these channels (active_current + L1/L2/L3 and active_current + L1/L2/L3)  Are you able to test? 
1. Upgrade openHAB to version 4.2 milestone 4. 
1. Uninstalled the bundled HomeWizard binding.
1. Drop this jar in your addon folder: https://1drv.ms/u/s!AnMcxmvEeupwjvdWkLJWkKqrC259XA?e=a4KupC
1. Without re-creating the Thing, you should now have all new channels listed at the Thing in openHAB.

Can you confirm all channels are available (this tests upgrade instructions) and have the proper value (this tests the mapping) ?

**Comment by NickB1** [comment]
Hi, thanks for the fast update!
The voltages seem to be working.
For the linked number items to the currents I get an UNDEF:
![image](https://github.com/openhab/openhab-addons/assets/1638255/f72630e3-fb42-4bce-81f9-520132c604e0)
These are my items, maybe I did something wrong here?
![image](https://github.com/openhab/openhab-addons/assets/1638255/4d47e1ef-c63d-47a0-b32b-81320644df47)

**Comment by lsiepel** [comment]
Current is in AMP not Volt, so the u it label is wrong in your definition file.

**Comment by NickB1** [comment]
Ah yes, copy paste error, working fine now.
I'm only seeing the same current on all three phases.
I looked at the PR, maybe this is the error, getActiveCurrentL1() is used for the three phases:
![image](https://github.com/openhab/openhab-addons/assets/1638255/cbcafac8-f7f3-4915-87f8-f876c3b0685e)

**Comment by Summm1t** [comment]
Thanks for picking this up!

I was also creating something for Homewizard at the same time, and would also create a PR, but I think I can better wait and incorporate your changes. However, you'll need to pass the checks of the CI build (which currently aren't).

I also want to add socket and KWH meters (1P and 3P). These won't work at the moment, because the handler will only work when the meter_model has some value in it (HomeWizardHandler.java:146-149).

There was also an interesting PR some time ago, made by the founder of the Homewizard add-on: 
[https://github.com/openhab/openhab-addons/pull/13495/files](https://github.com/openhab/openhab-addons/pull/13495/files)
It's a pitty that this PR wasn't merged, because it also handles the other Homewizard products.

**Comment by lsiepel** [comment]
Updated jar: https://1drv.ms/u/s!AnMcxmvEeupwjvhXkfIKBYTP1txbyg?e=BFXq1Q  (4.3.0 snapshot, should be compatible with 4.2 stable)

Fixed the issue @NickB1 reporeted, also added two more channels (any power failure count + long power failure count)

**Comment by NickB1** [comment]
Current looks good now, thanks!

**Comment by lsiepel** [comment]
> Thanks for picking this up!
> 
> I was also creating something for Homewizard at the same time, and would also create a PR, but I think I can better wait and incorporate your changes. However, you'll need to pass the checks of the CI build (which currently aren't).
> 
> I also want to add the Homewizard socket, water meter and KWH meters (1P and 3P). These products don't work currently, because the handler will only work when the meter_model has some value in it (HomeWizardHandler.java:146-149). Only the P1 meter will have this meter_model.
> 
> There was also an interesting PR some years ago, made by the founder of the Homewizard add-on: https://github.com/openhab/openhab-addons/pull/13495/files It's a pitty that this PR wasn't merged, because this one also handles the other Homewizard products.

Trying to bring that PR to the finish line. If possible, would you be able to test that PR? Unfortunately it does not have the added channels from this issue, but it is just for testing.

**Comment by Summm1t** [comment]
> > Thanks for picking this up!
> > I was also creating something for Homewizard at the same time, and would also create a PR, but I think I can better wait and incorporate your changes. However, you'll need to pass the checks of the CI build (which currently aren't).
> > I also want to add the Homewizard socket, water meter and KWH meters (1P and 3P). These products don't work currently, because the handler will only work when the meter_model has some value in it (HomeWizardHandler.java:146-149). Only the P1 meter will have this meter_model.
> > There was also an interesting PR some years ago, made by the founder of the Homewizard add-on: https://github.com/openhab/openhab-addons/pull/13495/files It's a pitty that this PR wasn't merged, because this one also handles the other Homewizard products.
> 
> Trying to bring that PR to the finish line. If possible, would you be able to test that PR? Unfortunately it does not have the added channels from this issue, but it is just for testing.

I personally don't have a P1 meter, that's why I want to add the other meters. So I cannot test the PR in a real-world situation.

**Comment by lsiepel** [comment]
> > > Thanks for picking this up!
> > > I was also creating something for Homewizard at the same time, and would also create a PR, but I think I can better wait and incorporate your changes. However, you'll need to pass the checks of the CI build (which currently aren't).
> > > I also want to add the Homewizard socket, water meter and KWH meters (1P and 3P). These products don't work currently, because the handler will only work when the meter_model has some value in it (HomeWizardHandler.java:146-149). Only the P1 meter will have this meter_model.
> > > There was also an interesting PR some years ago, made by the founder of the Homewizard add-on: https://github.com/openhab/openhab-addons/pull/13495/files It's a pitty that this PR wasn't merged, because this one also handles the other Homewizard products.
> > 
> > 
> > Trying to bring that PR to the finish line. If possible, would you be able to test that PR? Unfortunately it does not have the added channels from this issue, but it is just for testing.
> 
> I personally don't have a P1 meter, that's why I want to add the other meters. So I cannot test the PR in a real-world situation.

So you don’t own any homewizard devices?

**Comment by Summm1t** [comment]
> > > > Thanks for picking this up!
> > > > I was also creating something for Homewizard at the same time, and would also create a PR, but I think I can better wait and incorporate your changes. However, you'll need to pass the checks of the CI build (which currently aren't).
> > > > I also want to add the Homewizard socket, water meter and KWH meters (1P and 3P). These products don't work currently, because the handler will only work when the meter_model has some value in it (HomeWizardHandler.java:146-149). Only the P1 meter will have this meter_model.
> > > > There was also an interesting PR some years ago, made by the founder of the Homewizard add-on: https://github.com/openhab/openhab-addons/pull/13495/files It's a pitty that this PR wasn't merged, because this one also handles the other Homewizard products.
> > > 
> > > 
> > > Trying to bring that PR to the finish line. If possible, would you be able to test that PR? Unfortunately it does not have the added channels from this issue, but it is just for testing.
> > 
> > 
> > I personally don't have a P1 meter, that's why I want to add the other meters. So I cannot test the PR in a real-world situation.
> 
> So you don’t own any homewizard devices?

I have Wi-Fi kWh meter 3-phase MID and Energy Socket
