### ISSUE TITLE
[bluetooth.hdpowerview] Add support for Bluetooth Low Energy

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#16992]
HD Powerview Gen 3 shades can be monitored/controlled either via a Gateway (over IP) or directly via Bluetooth Low Energy (BLE). The OH HD Powerview binding currently only supports the former. This issue is a place holder for adding support for the latter.

There is already someone working on such an integration in HA https://github.com/patman15/hdpv_ble and I am in contact with him to share his efforts on HA in order to create the OH BLE integration.

**Comment by andrewfg** [comment]
@jlaur / @patman15 for info..

**Comment by jlaur** [comment]
@andrewfg 👍Probably it should be provided as a Bluetooth sub binding, i.e. `bluetooth.hdpowerview`.

**Comment by andrewfg** [comment]
> Probably it should be provided as a Bluetooth sub binding, i.e. bluetooth.hdpowerview

Yes.

My hypothesis would be to combine the existing OH Bluetooth OSI layers 1-4, the HA layer 5-6, and the existing OH Gateway binding layer 7.

**Comment by andrewfg** [comment]
@jlaur in case you are interested, you can follow my work in my branch [here](https://github.com/andrewfg/openhab-addons/tree/hdpowerview-ble). I already got it partly working; you can manually add shade things, and their position and rssi channels are dynamically updated. Missing are thing auto discovery, position commanding, battery status monitoring, and thing properties. You probably don't have any Gen 3 shades, so here is a screen video..


https://github.com/openhab/openhab-addons/assets/893994/ac9d9b57-82b0-4ffe-a312-6eb2630d1c37
