### ISSUE TITLE
[openhabcloud] Multiple connections are established

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#1700]
I have noticed twice now in our cloud server logs that the cloud connector seems to get in a state where it has two active connections going.  Because our openhab cloud server only allows one connection, it constantly kicks the other connection. This creates a infinite loop  of connecting/disconnecting on the server (and presumably the client).  The first time I saw this I emailed the user, he restarted his openhab and the problem stopped.  

FYI the current user with this issue seems to be on OH 2.0 fwiw.

**Comment by davidgraeff** [comment]
Still an Issue?

**Comment by hmerk** [comment]
closed due to inactivity
