### ISSUE TITLE
[shelly] Shelly Color Bulb Not Working

### ISSUE THREAD

**Issue by nextogroup** [openhab/openhab-addons#17008]
If I update from version 4.2.0.M2 to any later version (M3,M2 and RC1) the "Shelly Color Bulb" devices no longer work returning this error "Unable to connect to device - java.lang.IllegalArgumentException: Unsupported Auth type /algorithm requested by device(class java.lang.IllegalArgumentException)".
All other Shelly devices work without problems.

**Comment by holgerfriedrich** [comment]
see also current discussion on Gen1 devices [in the forum](https://community.openhab.org/t/openhab-4-2-milestone-discussion/), and proposed solution #17006
(Just mentioning as Color Bulb seems to be a Gen1 device)

**Comment by lolodomo** [comment]
@nextogroup : please try again with OH 4.2 RC2 that will be available in the afternoon.

**Comment by edo89b** [comment]
> @nextogroup : please try again with OH 4.2 RC2 that will be available in the afternoon.

I am the author of this issue, which I accidentally opened with an old company account. As soon as it is available I will try to update it and give you feedback. Thank you

**Comment by edo89b** [comment]
@lolodomo update performed and problem solved! Thanks

**Comment by holgerfriedrich** [comment]
Resolved by #17009
