### ISSUE TITLE
[Shelly] Thing /device offline after a power failure 

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-addons#17014]
Thing type 
@text/thing-type.shelly.shelly1mini.description

## Expected Behavior

Thing online after a power failure and reboot of openhab / openhab host and shelly device

## Current Behavior
- Shelly device was online and connected to wifi, it was accessible via Shelly APP 
- Thing was offline not configured or sth like that. Aster disabling the thing and enabling it again thing is online and working as expected. The configured lan IP of the devices in the binding Was the same / correct. 

## Possible Solution
not sure - probably retrying to enable the thing

## Steps to Reproduce (for Bugs)
power failure

## Your Environment
openHAB 4.2.0.M3
Milestone Build

**Comment by jlaur** [comment]
@JacekKac - can you reproduce this with 4.2RC2?

**Comment by jlaur** [comment]
@JacekKac - and just to be sure, what do you mean by your issue description:

> Thing type
> @text/thing-type.shelly.shelly1mini.description

?

**Comment by jlaur** [comment]
> @JacekKac - and just to be sure, what do you mean by your issue description:
> 
> > Thing type
> > @text/thing-type.shelly.shelly1mini.description
> 
> ?

Maybe somehow related to https://github.com/openhab/openhab-addons/issues/17013#issuecomment-2212491844?

**Comment by JacekKac** [comment]
> elly1mini

just the correct device

**Comment by jlaur** [comment]
> > elly1mini
> 
> just the correct device

I'm sorry, I don't understand what you mean.

**Comment by JacekKac** [comment]
i past it from the thing configuration to show you what type of shelly device is connected ;) 
![image](https://github.com/openhab/openhab-addons/assets/72306272/fd04dd55-9d23-42a0-aaf7-f309da48f170)

i will upgrade a try to reproduced it.

**Comment by markus7017** [comment]
I could reproduce the bug and need to check

**Comment by markus7017** [comment]
Please check latest DEV build, I could reproduce it during a firmware upgrade, maybe re-init on power-cycle is also fixed


---
[4.3-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.3.0-SNAPSHOT.jar?raw=true) |
