### ISSUE TITLE
[aWATTar] After 4.2. update the hourly prices do not refresh

### ISSUE THREAD

**Issue by aMU5Ed** [openhab/openhab-addons#17027]
## Expected Behavior
After the update from openhab 4.1 stable to openhab 4.2. stable the hourly prices get the most recent prices from the aWATTar API.

## Current Behavior
After the update from openhab 4.1 stable to openhab 4.2. stable the hourly prices do not refresh and the thing remains in status "unknown". The openhab.log does not state any warns or errors. The uninstallation and installation of the add-on did not change anything.

## Possible Solution
unknown

## Steps to Reproduce (for Bugs)
1. configure aWATTar Bridge with Land: AT, Ust-Satz: 20 and Basispreis: 1,5
2. update from openhab 4.1 stable to openhab 4.2

## Your Environment
runtimeInfo:
  version: 4.2.0
  buildString: Release Build
locale: de-AT
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 17.0.9
  javaVendor: Azul Systems, Inc.
  javaVendorVersion: Zulu17.46+19-CA
  osName: Linux
  osVersion: 6.8.0-1006-raspi
  osArchitecture: aarch64
  availableProcessors: 4
  freeMemory: 207981056
  totalMemory: 970981376
  uptime: 72776
  startLevel: 100
addons:
  - automation-jsscripting
  - binding-automower
  - binding-awattar
  - binding-doorbird
  - binding-fronius
  - binding-harmonyhub
  - binding-homeconnect
  - binding-hue
  - binding-icalendar
  - binding-knx
  - binding-mqtt
  - binding-network
  - binding-openweathermap
  - binding-systeminfo
  - binding-telegram
  - binding-unifi
  - misc-openhabcloud
  - persistence-influxdb
  - persistence-mapdb
  - transformation-jsonpath
  - transformation-map
  - transformation-scale
  - transformation-xpath
  - transformation-xslt
  - ui-basic
  - voice-picotts

**Comment by lsiepel** [comment]
Are you able to provide a debug log file?
