### ISSUE TITLE
[bluetooth.bluez] throws UnsatisfiedLinkError on Windows

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17035]
On OH 4.2 release version, when running on Windows, the `bluetooth.bluez` binding throws an UnsatisfiedLinkError when the binding is loaded.

```
2024-07-10 11:33:39.256 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.UnsatisfiedLinkError: The specified procedure could not be found.

	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40) ~[?:?]
	at jnr.unixsocket.Native$LibC$jnr$ffi$0.socket(Unknown Source) ~[?:?]
	at jnr.unixsocket.Native.socket(Native.java:92) ~[?:?]
	at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:101) ~[?:?]
	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:65) ~[?:?]
	at org.freedesktop.dbus.connections.transports.UnixSocketTransport.connect(UnixSocketTransport.java:59) ~[?:?]
	at org.freedesktop.dbus.connections.transports.TransportFactory.createTransport(TransportFactory.java:44) ~[?:?]
	at org.freedesktop.dbus.connections.AbstractConnection.<init>(AbstractConnection.java:161) ~[?:?]
	at org.freedesktop.dbus.connections.impl.DBusConnection.<init>(DBusConnection.java:334) ~[?:?]
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:149) ~[?:?]
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:169) ~[?:?]
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:219) ~[?:?]
	at org.freedesktop.dbus.connections.impl.DBusConnection.getConnection(DBusConnection.java:184) ~[?:?]
	at com.github.hypfvieh.bluetooth.DeviceManager.createInstance(DeviceManager.java:74) ~[?:?]
	at org.openhab.binding.bluetooth.bluez.internal.DeviceManagerFactory.lambda$0(DeviceManagerFactory.java:83) ~[?:?]
	at org.openhab.binding.bluetooth.util.RetryFuture$CallableTask.run(RetryFuture.java:67) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
```

**Comment by andrewfg** [comment]
Probably the issue is limited to Windows.

The error comes from the 'bluetooth.bluez' module, and since BlueZ is specifically a Linux feature, it is likely that BlueZ might indeed fail on Windows.

I found this while testing #17099 on Windows with a BlueGiga dongle. And in that constellation I would expect 'bluetooth.bluez' to NOT be loaded at all.

**Comment by andrewfg** [comment]
It may be sufficient to add a `catch (UnsatisfiedLinkError e)` clause here.. but I am no expert on BlueZ so would prefer if someone else can look at it please.

https://github.com/openhab/openhab-addons/blob/12a1f76c3ce9da812a26458ecfddfa36b360274d/bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/internal/DeviceManagerFactory.java#L84

**Comment by andrewfg** [comment]
@cpmeister ping!

**Comment by lsiepel** [comment]
I really wonder why bluetooth.bluez was loaded at all.

Besides that i noticed we use a rather old version of the dbus-java. It seems the dbus-java was sort of wrapped as osgi bundle, unfortunately that bundle is no longer maintained. I'm no dependency expert, and wonder why this should be an OSGI package and not a dependency as any other?

Totally speculative if updating this library would help, but it might be worth trying to get this updated.

**Comment by andrewfg** [comment]
> we use a rather old version of the dbus-java. It seems the dbus-java was sort of wrapped as osgi bundle, unfortunately that bundle is no longer maintained.

@hypfvieh describes his version as an 'improved' version of the original dbus-java .. but @lsiepel like you I wonder why we use that rather than another version. Personally I have no idea what it is for so I am hesitant to try messing with it.

**Comment by lsiepel** [comment]
I can imagine when it is a bundle it can act as a service that is made available by dependency injection to other bundles. Creating a single service (sort of singleton).

Updating could be wise, but I’m not familiar with the workflow. Who would know how to do this? @wborn maybe?

**Comment by andrewfg** [comment]
I will do a trawl through addons to see if in reality any of them other than BlueZ have such a dependency.

**Comment by andrewfg** [comment]
Please notice the comment about Windows and Mac in the BlueZ.DeviceManagerFactory code after the `catch (DBusException ex)` line. Therefore I think that my original suggestion to simply add 'UnsatisfiedLinkError' to that catch is probably a sufficient hack to fix this issue. => WDYT ?

```
   public void initialize() {
        logger.debug("initializing DeviceManagerFactory");

        var stage1 = this.deviceManagerFuture = RetryFuture.callWithRetry(() -> {
            try {
                // if this is the first call to the library, this call
                // should throw an exception (that we are catching)
                return DeviceManager.getInstance();
                // Experimental - seems reuse does not work
            } catch (IllegalStateException e) {
                // Exception caused by first call to the library
                try {
                    return DeviceManager.createInstance(false);
                } catch (DBusException ex) {
                    // we might be on a system without DBus, such as macOS or Windows
                    logger.debug("Failed to initialize DeviceManager: {}", ex.getMessage());
                    return null;
                }
            }
        }, scheduler);
```

**Comment by hypfvieh** [comment]
> > we use a rather old version of the dbus-java. It seems the dbus-java was sort of wrapped as osgi bundle, unfortunately that bundle is no longer maintained.
> 
> @hypfvieh describes his version as an 'improved' version of the original dbus-java .. but @lsiepel like you I wonder why we use that rather than another version. Personally I have no idea what it is for so I am hesitant to try messing with it.

To shed some light in this confusion: dbus-java and bluez-dbus only make sense on Linux systems.
On Windows and Mac there is no DBus-Service (which dbus-java can provide, but thats another story) and no bluez due to lack od bluez-stack from kernel.
 
For me it looks like dbus-java 3.x is used which is EOL for some time right now. The UnsatisfiedLinkError is caused by libmatthew, a library of the original author of dbus-java which contains some native binaries to connect to unix sockets.
This library does not include any native libs for windows as well.

Anyway, the newer dbus-java version would be able to provide a suitable unixsocket implementation (by e.g. using the implementation which is part of Java sind Java 16). Libmatthew is no longer used since major version 4.x of dbus-java. 
But anyway that will not solve the issue here (no dbus/bluez on non-Linux OSes).

Regarding OSGi: I still provide a OSGi artifact with each new version. I don't know if this is still working as I don't have any knowledge about OSGi. The module was provided by someone who had the needs for it some time ago. I know that there were also some PRs to fix stuff, but as I said: I don't use OSGi and have no clue of it.

If you want to update the used dbus-java library, I would appreciate that. Note, that the current version 5.x needs Java 17 as minimum requirement. 
If you have trouble with the OSGi bundle because something is broken, please provide a PR and I'll happily merge it.

**Comment by lsiepel** [comment]
Thanks for your explenation, really helpfull. openHAB is  java17, so that should not be a problem.
I looked at the wrong resource, i see there are still recent versions of the OSGi package: https://mvnrepository.com/artifact/com.github.hypfvieh/dbus-java-osgi/5.0.0

**Comment by andrewfg** [comment]
@lsiepel it looks like there would be two PRs..

1. My #17107 adds handling for the exception on Windows and macOS and fixes the original issue.
2. Another PR could be written to update the dependencies. Personally I am not sure if I can do that, so perhaps you can offer to do it?

Does the above make sense?

**Comment by lsiepel** [comment]
> @lsiepel it looks like there would be two PRs..
> 
> 1. My [[bluetooth.bluez] Handle UnsatisfiedLinkError on Windows (and macOS) #17107](https://github.com/openhab/openhab-addons/pull/17107) adds handling for the exception on Windows and macOS and fixes the original issue.
> 2. Another PR could be written to update the dependencies. Personally I am not sure if I can do that, so perhaps you can offer to do it?
> 
> Does the above make sense?

Totally makes sense
