### ISSUE TITLE
[freeboxos] Strange default value for parameter httpsPort

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17075]
For the bridge thing, the default HTTPS port is set to 15682.
When I use the default domain, that is "mafreebox.freebox.fr", the expected port is 443 but 15682 is used by default if HTTPS is enabled and as a result the request fais.
Why did you set the default to 15682 @clinique ?
The workaround is to force the port to 443 in the thing configuration.

**Comment by clinique** [comment]
I'll take a look at this in two weeks @lolodomo - being currently on holiday. Nice to see you starting to use it.

**Comment by lolodomo** [comment]
In case there is a valid reason to use 15682 as default, at least it should be documented that 443 has to used with mafreebox.freebox.fr.
