### ISSUE TITLE
[freeboxos] Channel xdsl-status not found on revolution thing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17073]
The channel xdsl-status is documented in README but not found in revolution thing.
This channel was present in the original binding and the main channel I was using.

**Comment by clinique** [comment]
I'll take care of this adding both FTTH and XDSL. Will be able to test FTTH but I will need your help in testing xdsl.

**Comment by lolodomo** [comment]
The issue is not yet resolved, the PR started by @clinique for fiber connection has to be enhanced for xDSL connection
