### ISSUE TITLE
[gpio] Add GPIO Binding

### ISSUE THREAD

**Issue by watou** [openhab/openhab-addons#1707]
Moved from https://github.com/openhab/openhab/issues/4976.  cc: @ThomDietrich 

Functional requirements:

* Event-driven GPIO changes (no polling)
* Logical pin numbering system that does not require any openHAB reconfiguration when moved to new hardware
* Package any required native libraries in the binding using the OSGi `Bundle-NativeCode` directive so no prior native installation is required
* Functions by having added any needed privileges to openhab user account instead of requiring openHAB to be run as root (whenever possible)
* Support multiple common platforms where GPIO access is possible, with ability to add future platform support when available
* Clear, usable, sensible Things and Channels

**Comment by falkena** [comment]
There is already pull request for OpenHab2: https://github.com/openhab/openhab2-addons/pull/1334

**Comment by hmerk** [comment]
closed a binding has been merged
