### ISSUE TITLE
[pioneeravr] Add VSX-922 as a supported unit

### ISSUE THREAD

**Issue by scurb** [openhab/openhab-addons#1710]
I have a VSX-922 unit and it works really well with the binding. However, it is not in the source codes list of supported unit. Is that possible to add?

**Comment by Andirs55** [comment]
Same for my VSX-924.

**Comment by scurb** [comment]
Lets give @Stratehm a ping :)

**Comment by Stratehm** [comment]
I will add them when the issue #1344 is fixed. For now, I am refactoring the binding. You can check this issue for more details on the advancement.

**Comment by hmerk** [comment]
closed due to inactivity
