### ISSUE TITLE
[bluetooth.grundfosalpha] Entry is not in footer.xml file.

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17102]
While working on #17099 I noticed that there is no entry for `org.openhab.binding.bluetooth.grundfosalpha` in the 'footer.xml' file. I don't know if that is intended or not. ??

https://github.com/openhab/openhab-addons/blob/12a1f76c3ce9da812a26458ecfddfa36b360274d/features/openhab-addons/src/main/resources/footer.xml#L16

**Comment by andrewfg** [comment]
@kaikreuzer I think this is something for you. Or??

**Comment by andrewfg** [comment]
@tisoft ping!

**Comment by kaikreuzer** [comment]
@andrewfg I agree, this seems to be missing. Do you want to create a PR to add it or shall I?
