### ISSUE TITLE
[telegram] log spamming with duplicate messages in case of network/telegram outage

### ISSUE THREAD

**Issue by rdslw** [openhab/openhab-addons#17113]
Using telegram binding, requires working internet. Network outage (or Telegram servers outage/maintenance), results in binding spamming openhab.log with about 7 messages per second. Even relatively short network outage results in 6300 duplicate messages emitted to log which can quickly overwhelm logging machine.

## Expected Behavior
telegram binding should log "GetUpdates failures" once per outage (minimal), or (alternative) have some rate limit.

## Current Behavior
Emitting duplicate messages with rate 7/s for whole outage duraation. Example message:
```
2024-06-08 21:54:57.551 [WARN ] [.openhab.binding.telegram.internal.TelegramHandler] Telegram exception: GetUpdates failed with error_code 502 Bad
 Gateway
```

## Possible Solution
Implement some kind of error handling.

## Steps to Reproduce (for Bugs)
1. Use telegram binding. 
2. Disconnect connection to telegram servers. 
3. Try to one message using rules.

## Context
More context provided here: https://community.openhab.org/t/telegram-excessive-logging-problem/156631

Other users confirm the problem.

## Your Environment
OH 3.4

**Comment by lsiepel** [comment]
See linked PR for a test jar. You need to upgrade to 4.2.0 before you can use it. Please provide test feedback.

**Comment by rdslw** [comment]
Thank you kindly for ultra fast fix. I'll have to update whole OH on that environment to be able to test it. Plan to do it in two weeks around Aug 2nd.

In the meantime have two questions regarding fix, will post them to the PR.
