### ISSUE TITLE
[tibber] Make live measurements optional.

### ISSUE THREAD

**Issue by pacive** [openhab/openhab-addons#17187]
I have a Tibber pulse, but have no need to get these values into OH. Instead I have a separate script to get these for visualization purposes (I use InfluxDB and want to have a different retention policy for these values than for OH persistence) but since the Tibber API only allows two websocket connections for the subscriptions the binding will be in conflict with my other script and they might be disconnected intermittently.

If there was an option to disable this functionality in the binding, I could still use the other channels for price information etc. Without risk of interference.

## Your Environment

* Version used: 4.2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): N/A
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian bullseye

**Comment by pacive** [comment]
PR to come soon.

**Comment by lsiepel** [comment]
Why not configure openHAB to match your persistence requirement? Simpeler setup, no scripts or whatever needed. 
also fine to create a PR. With advanced config to disable it, but better to keep it simple

**Comment by pacive** [comment]
Because OH only allows one persistence configuration per service, all items persisted with influxDB goes into the same bucket, which can only have one retention policy. And for most items I want to have them stored for quite a long period, but to store several data points every 10 seconds will use more storage space. (Perhaps it wouldn't be an issue and I'm just overly cautious). The alternative would be to use rrd4j persistence for these Items, but that seems to be incompatible with grafana that I use for graphing.

I know my use case is probably on the edge, but it's currently a blocker for me to use the binding.

I have already coded the change, only a few lines is needed. The default will still be to have it enabled, so shouldn't affect existing users.
