### ISSUE TITLE
[mqtt.homeassistant] When a component disappears from MQTT, the channels remain on the Thing in openHAB

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#17182]
## Expected Behavior

If I remove something in MQTT from Home Assistant discovery, I expect the channels for that component to disappear in openHAB, otherwise I'm left with cruft, especially if I'm say designing a new device in ESPHome and adding and removing components from it often. It should happen right away if the discovery topic receives a message explicitly deleting it (as opposed just not sending the discovery message again in the future, when not using retained discovery messages).

## Current Behavior
I believe the configuration topic gets removed from the Thing configuration, but the channels remain.

## Possible Solution
Probably set a time after a thing initializes, and go through all the channels to ensure their component still exists. Can be triggered right away if a topic is removed from the thing config.

## Steps to Reproduce (for Bugs)
1. Have a Home Assistant MQTT Device with multiple components
2. Add the discovered thing from the Inbox
3. Delete the discovery config for one of those components
4. Observe that the channels still exist on the thing

## Your Environment
* Version used: openHAB 4.3.0-SNAPSHOT
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 22.04 jammy

**Comment by lsiepel** [comment]
Are there besides the merged PR any additional steps needed to finish cleanup when components are removed?

**Comment by ccutrer** [comment]
Yes. It should automatically remove those components' topics from the Thing configuration (at least for managed things). And it probably needs to do this even if it doesn't see the "delete" message - i.e. if it happens when openHAB isn't running, and then the binding starts, and doesn't receive a new discovery message within some timeout.
