### ISSUE TITLE
[freeboxos] Better default display for the uptime channel

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17205]
I would like to set another default state pattern for the uptime channel, something like "25 day 12 h 24 min 35 s". Do you know what is the syntax to use to show such duration?

**Comment by mherwege** [comment]
If it is a Number:Duration channel, you can use patterns from https://docs.oracle.com/en/java/javase/17/docs//api/java.base/java/text/SimpleDateFormat.html. They will get interpreted slightly differently, see patterns in https://github.com/openhab/openhab-core/pull/4169/files#diff-80a92db5cc2012f97f4419ddf2f91b86759b475ad6d3f82af3f9d415f5576d6e.

**Comment by lolodomo** [comment]
Closed by #17218
