### ISSUE TITLE
[freeboxos] Audio sink not created

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17208]
The audio sink is not created in case the player was OFF when the thing was initialized and capabilities were not set (previously) in the thing properties (that is the systematic case when the thing is defined in a thing file).

Additionally, the video capability should be checked instead of the audio capability.

**Comment by clinique** [comment]
I do not use this feature. Do you agree that I leave correction to you ?

**Comment by lolodomo** [comment]
@clinique : I suppose the Delta server has no audio headphone (audio capability) ?

**Comment by clinique** [comment]
You're correct
