### ISSUE TITLE
Official Support for Tuya Devices

### ISSUE THREAD

**Issue by constambeys** [openhab/openhab-addons#17230]
Hello,

I have modified an add-on that interacts with Tuya Devices

Can this add-on be merged in this repository?

https://github.com/constambeys/openhab3-addons-tuya

Thanks

**Comment by lsiepel** [comment]
New bindings (and contributors) are very welcome. To have your binding added as official addon, you can create a pull request and wait for a maintainer to review.
But before you create a pull request, I noticed you created this binding on an old archived fork. I would recommend to coy your code, create a fork from openHAB/main repository and add your code to that fork. Your code might need to be adapted to compile again.

**Comment by lsiepel** [comment]
Also be aware of a similar binding in the smarthomej repository.  https://github.com/smarthomej/addons/tree/4.2.x/bundles/org.smarthomej.binding.tuya
it is fully openHAB compatible.

**Comment by constambeys** [comment]
I wasn't aware of that !

**Comment by lsiepel** [comment]
If you are still looking for adding this binding, we can leave this open, otherwise it is better to close this issue.
