### ISSUE TITLE
[Groovy] Default preset does not include OnOffType

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#17247]
https://www.openhab.org/docs/configuration/jsr223.html#default-preset-importpreset-not-required says that the OnOffType is available in Groovy, as part of the Default preset.

I create a file in openhab/automation/jsr223/onoff.groovy with content:
```
OnOffType v = ON
```
Loading it fails:
```
2024-08-12 20:53:31.386 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script '/etc/openhab/automation/jsr223/onoff.groovy': org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/etc/openhab/automation/jsr223/onoff.groovy: 2: unable to resolve class OnOffType
 @ line 2, column 11.
   OnOffType v = ON
             ^

1 error
```
If I change onoff.groovy to:
```
import org.openhab.core.library.types.OnOffType
OnOffType v = ON
```
there is no error on loading.

So in OpenHAB 4.2.1 the Default preset for Groovy does not include OnOffType, contrary to the statement at https://www.openhab.org/docs/configuration/jsr223.html#default-preset-importpreset-not-required.

**Comment by lsiepel** [comment]
Are you aware of the last version that worked? Maybe @wborn can comment as most groovyscripting PR’s are his. I’m also interested in how this mechanism is setup, to provide future support

**Comment by dilyanpalauzov** [comment]
> Are you aware of the last version that worked?

No, this is the first version I tried (OH 4.2.1).

**Comment by wborn** [comment]
I don't think it ever worked but I figured out a way for importing these additional classes in scripts with #17383.
