### ISSUE TITLE
[melcloud] after update to openHAB 4.2.1: HANDLER_REGISTERING_ERROR

### ISSUE THREAD

**Issue by Jimmi68** [openhab/openhab-addons#17268]
Binding doesn't start working after openHAB was updated from 4.2.0 to 4.2.1.

See more details in the Forum:

https://community.openhab.org/t/melcloud-binding-mitubishi/62199/119

HANDLER_REGISTERING_ERROR
Cannot invoke “org.openhab.binding.melcloud.internal.api.MelCloudConnection.isConnected()” because “this.connection” is null

Thanks for your help,
Best Regards,
JB

**Comment by lsiepel** [comment]
The last PR to this binding was from 4.2.0 and not a backport for 4.2.1. Also from the release notes there is not something that sticks out as a possible cause: https://github.com/openhab/openhab-distro/releases/tag/4.2.1
