### ISSUE TITLE
[solarforecast] After OH Upgrade SolarForecast shows exception

### ISSUE THREAD

**Issue by ericbodden** [openhab/openhab-addons#17264]
Hello. I have one question. I just update to OH 4.2.1 (from 4.1.0) and now I am seeing this error on my Thing:

```
Exception during update: solarforecast:fs-plane:homeSite:homeNorthEast # Forecast invalid time range
```

My definition looks like this:
```
Bridge solarforecast:fs-site:homeSite   "ForecastSolar Home" [ location="auto-detect", channelRefreshInterval=1] {
         Thing fs-plane homeNorthEast   "Vorhersage NordOst-Panels" [ refreshInterval=30, azimuth=45, declination=9, kwp=5.88, damping=1]
         Thing fs-plane homeSouthWest   "Vorhersage SüdWest-Panels" [ refreshInterval=30, azimuth=-135, declination=9, kwp=5.88, damping=1]
}
```

This looks like a bug to me. Could you please confirm this? Thanks

**Comment by weymann** [comment]
Discussed in [Community Topic](https://community.openhab.org/t/solar-forecast-pv/137681/248) and after correcting thing configuration released binding works as expected.
