### ISSUE TITLE
[freeboxos] Phone / calls: mismatch with default refresh interval

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17262]
Default is set to 30s for phone while it is set to 2s for calls.
It is the reverse compared to the original binding.
The idea to have the short refresh interval was to detect quickly a phone suddenly ringing. This is a channel on the phone thing. So the short refresh should be on fvs thing type.
There is no hurry to refresh last call.
By the way, the short refresh is interesting only if the `ringing` channel is linked. So maybe we could have a default refresh set to 30s and the user will reduce it if he links the `ringing` channel. WDYT @clinique ?

PS: what does "FXS" mean for ? It is too late to change thing type but at least the label of discovered thing should have a label that talks to any user.

**Comment by clinique** [comment]
This seems to make sense. FXS is the telecom name for fixed line.

**Comment by lolodomo** [comment]
@clinique : did you test the channels for DECT ? It is relatively probable that the "set" API will fail due to convert into enum during "get" (capitalize the value) ? Potential similar problems as already encountered in two other places.
I am not able to test that.

**Comment by lolodomo** [comment]
> @clinique : did you test the channels for DECT ? It is relatively probable that the "set" API will fail due to convert into enum during "get" (capitalize the value) ? Potential similar problems as already encountered in two other places.

These two values (type and network) seem to be in lowercase:
```

14:26:51.454 [DEBUG] [ing.freeboxos.internal.api.ApiHandler] - executeUrl GET: https://mafreebox.freebox.fr:443/api/v12/phone/config
14:26:51.612 [TRACE] [ing.freeboxos.internal.api.ApiHandler] - executeUrl GET - https://mafreebox.freebox.fr:443/api/v12/phone/config returned {"success":true,"result":{"network":"working","dect_eco_mode":false,"dect_pin":"0000","dect_ring_pattern":1,"dect_registration":false,"dect_nemo_mode":false,"dect_enabled":false,"dect_ring_on_off":false}}
14:26:51.619 [DEBUG] [ing.freeboxos.internal.api.ApiHandler] - executeUrl GET: https://mafreebox.freebox.fr:443/api/v12/phone/1
14:26:51.732 [TRACE] [ing.freeboxos.internal.api.ApiHandler] - executeUrl GET - https://mafreebox.freebox.fr:443/api/v12/phone/1 returned {"success":true,"result":{"is_ringing":false,"type":"fxs","id":1,"gain_tx":50,"vendor":"unknown","gain_rx":50,"on_hook":true,"hardware_defect":false,"type_id":1}}
```
