### ISSUE TITLE
[miio] Xiaomi Mi Robot X10 robot vacuum support

### ISSUE THREAD

**Issue by vpant** [openhab/openhab-addons#17297]
I recently purchased Xiaomi Mi Robot X10 and used `Create channels for new/unsupported devices (MIOT protocol)` to successfully create a database file.

[test-dreame.vacuum.r2209-20240813-212109.txt](https://github.com/user-attachments/files/16663573/test-dreame.vacuum.r2209-20240813-212109.txt)

The following properties were tested successfully (using the Xiaomi app in parallel):

### actions (Actions) with the predefined menu in the Semantic model:
- Working actions: Vacuum Start Sweel, Vacuum Stop Sweeping, Vacuum Start Room Sweep, Battery Start Charge, Brush Cleaner Reset Brush Life (reset **both** brushes at once), Filter Reset Filter Life, Collect Dust Collect 
- No reaction by Vacuum: Vacuum Extend Start Clean, Vacuum Extend Stop Clean, Map Map Req, Map Update Map, Audio Position, Audio Play Sound, Time Delete Timer

Working channels: 
- volume (Audio - Volume)
- voice_packet_id (Audio - Voice Packet Id)
- voice_change_state (Audio - Voice Change State): Reports `{\"id\":\"IT\",\"state\":\"success\",\"progress\":100}`
- battery_level (Battery - Battery Level)
- charging_state (Battery - Charging State)
- brush_left_time (Main Cleaning Brush - Brush Left Time)
- brush_life_level (Main Cleaning Brush - Brush Life Level)
- first_clean_time (Clean Logs - First Clean Time)
-total_clean_time (Clean Logs - Total Clean Time)
- total_clean_times (Clean Logs - Total Clean Times)
- total_clean_area (Clean Logs - Total Clean Area)
- auto_collect (Collect Dust - Auto Collect)
- clean_times (Collect Dust - Clean Times)
- dust_enable (Collect Dust - Dust Enable)
- enable (Do Not Disturb - Enable)
- start_time (Do Not Disturb - Start Time)
- end_time (Do Not Disturb - End Time)
- filter_life_level (Filter - Filter Life Level)
- filter_left_time (Filter - Filter Left Time)
- mult_map_info (Map - Mult Map Info): Reports json `{"object_name":"6257942110/1064458274/9","md5":"723c094848425020c7484e58ab7768e9"}`
- fault (Robot Cleaner - Device Fault)
- mode (Robot Cleaner - Mode)
- status (Robot Cleaner - Status)
- brush_left_time1 (Side Cleaning Brush - Brush Left Time)
- brush_life_level1 (Side Cleaning Brush - Brush Life Level)
- time_zone (Time - Time Zone)
- timer_clean (Time - Timer Clean)

Vacuum Extend channels and values (not sure how to test them):
- break_point_restart (Vacuum Extend - Break Point Restart): Open
- carpet_press (Vacuum Extend - Carpet Press): Close
- clean_extend_data (Vacuum Extend - Clean Extend Data): NULL
- clean_rags_tip (Vacuum Extend - Clean Rags Tip): 0s
- cleaning_area (Vacuum Extend - Cleaning Area): 0
- cleaning_mode (Vacuum Extend - Cleaning Mode): Standard
- cleaning_time (Vacuum Extend - Cleaning Time): 0s
- faults (Vacuum Extend - Faults): (no value)
- keep_sweeper_timer (Vacuum Extend - Keep Sweeper Time): 0s
- mop_mode (Vacuum Extend - Mop Mode): Medium
- nation_matched (Vacuum Extend - Nation Matched): NULL
- relocation_status (Vacuum Extend - Relocation Status): 0
- remote_state (Vacuum Extend - Remote State): NULL
- serial_number (Vacuum Extend - Serial Number): reports the actual serial number
- task_status (Vacuum Extend - Task Status): 1
- waterbox_status (Vacuum Extend - Waterbox Status): No
- work_mode (Vacuum Extend - Work Mode): 14 

Not working channels:
- set_voice (Audio - Set Voice): Not sure if I tested properly. I used a rule to change the value to IT but it did nto change the language

Not sure how to test:
- fame_info (Map - Frame Info): Reports `NULL`
- map_extend_data (Map - Map Extend Data): Reports `NULL`

**Comment by lsiepel** [comment]
@marcelrv this might be helpfull information.

**Comment by marcelrv** [comment]
thx. Will add this device
