### ISSUE TITLE
[sonos] - Sonos Boost is not yet a supported model

### ISSUE THREAD

**Issue by pgfeller** [openhab/openhab-addons#17307]
During initialization a warning is generated, if as "[Sonos Boost](https://www.sonos.com/en-us/guides/boost)" is discovered - and a fallback device type is used to create a thing:

```
2024-08-20 22:16:15.425 [WARN ] [overy.ZonePlayerDiscoveryParticipant] - 'Sonos Boost' is not yet a supported model, thing type 'sonos:zoneplayer' is considered as default; please open an issue
```
![image](https://github.com/user-attachments/assets/3eced609-80ca-47de-878a-b8504fff329f)
<details>
<summary>System Information - <b>openHAB 4.2.1</b></summary>
<p><pre>
<b>Karaf</b>
  Karaf version               4.4.6
  Karaf home                  /openhab/runtime
  Karaf base                  /openhab/userdata
  OSGi Framework              org.eclipse.osgi-3.18.0.v20220516-2155
<b>JVM</b>
  Java Virtual Machine        OpenJDK 64-Bit Server VM version 17.0.12+7-Debian
  2deb11u1
  Version                     17.0.12
  Vendor                      Debian
<b>Operating system</b>
  Name                        Linux version 6.5.0-44-generic
  Architecture                amd64
  Processors                  4
  Total physical memory       16,293,704 kbytes
  Free physical memory        311,108 kbytes
</pre></p>
</details>

## Expected Behavior
This device is a repeater/range extender and the binding should ignore this device type.

## Current Behavior
A device is added to the openHAB inbox.

## Possible Solution
Boost devices/repeaters should be ignored by the `ZonePlayerDiscoveryParticipant` - a warning is not necessary. I propose to create a `TRACE` message in this case - but to keep the inbox and log clean in this case.

**Comment by lolodomo** [comment]
Yes, it should be simply ignored.
I have in mind it already was but maybe it was updated and now it is no more properly identified ?

**Comment by lolodomo** [comment]
There is a case to add here:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.sonos/src/main/java/org/openhab/binding/sonos/internal/SonosXMLParser.java#L1020

Please tell me what is the thing type ID of the discovered thing. Is it "boost" ?

**Comment by lolodomo** [comment]
Forget, I have this information in the log you provided.

**Comment by pgfeller** [comment]
@lolodomo - will you take care of this - or shall I create a PR? The required change seems to be quite trivial ...

**Comment by lolodomo** [comment]
I will propose a fix before the end of day.
