### ISSUE TITLE
[electroluxappliances] New binding for Electrolux Appliances

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#17325]
The Electrolux Delta API has been discontinued in favour of the new Electrolux Group [API](https://developer.electrolux.one/documentation/gettingStarted).

We need to have support for the new Electrolux Group API.

I will start to work on a first version.

**Comment by lsiepel** [comment]
Need any support regarding the new binding? As the old one was removed on last stable, it would be nice to have this in 4.3.0 again. Maybe a bit challenging due to limited remaining time. 
let me know if I can assist you in any way.

**Comment by jannegpriv** [comment]
I will create a PR.
