### ISSUE TITLE
[goecharger] Awp (eco-mode) parameter for go-e charger

### ISSUE THREAD

**Issue by geert-claes** [openhab/openhab-addons#17369]
If i am correct the awp api key is not included in the binding.  Can it be added ?
Thanks !

https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md : 
awp | R/W | float | Config | awattarMaxPrice in ct

**Comment by lsiepel** [comment]
I tried to implement this `awattarMaxPrice` channel on the V2 handler. A test jar is here: https://1drv.ms/u/s!AnMcxmvEeupwj4hluFPg-uckkh-Bzw?e=YMMYgN it should work with 4.2.0 or later.

1. make sure you ahev openHAB 4.2.0 or later.
2. uninstall the goecharger binding (your items/channels etc will not be affected)
3. drop the jar in your addon folder.
4. delete and create the `goe` Thing (your items/channels etc will not be affected) 
5. observe the new added channel and see if you can read and write data to it.

Would be nice if you can provide some test results as i don't own such a device, it is purely from the documentation.

**Comment by lsiepel** [comment]
Gentle ping @geert-claes

**Comment by geert-claes** [comment]
Sorry for the delay.
Installed the binding on my test OH, and the channels seems to work just fine.
I will install it later on in the "production" OH.   I'll keep you informed if things go wrong (which I do not expect).

This channel means that the script(s) that controls the charging can be simplified to a great extend.

Thanks !
