### ISSUE TITLE
[fineoffsetweatherstation]  Rule DSL rule not triggered 

### ISSUE THREAD

**Issue by fabgio** [openhab/openhab-addons#17376]
I have been testing a simple rule DSL rule as such:

rule "Curtain_down"
when 
  Item weather_illumination received update
then 
   if(weather_illumination.state > 8000) {
 		logInfo("pippo")
		}
end 

Nothing appears in the log and the value is met for sure. Probably there's something wrong in the condition! Any suggestion?
OpenHab 4.2.1 on Docker with fineoffset Binding installed

Thanks

**Comment by lsiepel** [comment]
The community forums is the best placee to get support for this question.

If nothing shows up `weather_illumination.state` is not greather then 8000. Just before the condition you can output its value (quick n dirty)
`logInfo("pippo", "" + weather_illumination.state)`
