### ISSUE TITLE
[icalendar] Add User-Agent property for iCalendar binding

### ISSUE THREAD

**Issue by sneudert** [openhab/openhab-addons#17392]
I'm trying to integrate my waste disposal company's calendar into openHAB. The URL of the calendar (in ICS) format is 

https://api.abfall.io/?key=0d7a92192ba3ae914c028ac37d73e222&mode=export&idhousenumber=645&wastetypes=20,66,18,53,260&timeperiod=20240101-20241231&showinactive=false&type=ics

If you access it using your browser (Edge, Chrome, Firefox), for example, the calendar will be downloaded. However, the HttpClient uses its own (Jetty) header and the request ends with a 404 status. 

The HTTP header “User-Agent” should be configurable by the user.

**Comment by sneudert** [comment]
This is request as send by browser, resulting in 200 status and fetching calendar source: 
`curl "https://api.abfall.io/?key=0d7a92192ba3ae914c028ac37d73e222&mode=export&idhousenumber=645&wastetypes=20,66,18,53,260&timeperiod=20240101-20241231&showinactive=false&type=ics" -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"`
And same request sent with iCalendar/Jetty HttpClient: 
`curl "https://api.abfall.io/?key=0d7a92192ba3ae914c028ac37d73e222&mode=export&idhousenumber=645&wastetypes=20,66,18,53,260&timeperiod=20240101-20241231&showinactive=false&type=ics" -A "User-Agent: Jetty/9.4.54.v20240208"`
resulting in a 404 error.

**Comment by jlaur** [comment]
The last command will result in an invalid **User-Agent** header. Can you try:
```shell
curl "https://api.abfall.io/?key=0d7a92192ba3ae914c028ac37d73e222&mode=export&idhousenumber=645&wastetypes=20,66,18,53,260&timeperiod=20240101-20241231&showinactive=false&type=ics" -A "Jetty/9.4.54.v20240208"
```

**Comment by sneudert** [comment]
This looks like a strange security feature. 

It would be nice if you could set the HTTP headers manually. 

Or if you could specify a special instance of the HTTP binding.

**Comment by lsiepel** [comment]
@sneudert please test the jar that is in the linked PR.  It now has a parameter added that can be used to set the user agent manually. Please report back if it works as expected.

**Comment by sneudert** [comment]
I tried it and it works. Thank you! 

Maybe it would be possible to link the binding to the HTTP binding, or to implement a general configuration option for headers like there?

**Comment by lsiepel** [comment]
Not merged yet, so still an active issue :-)
