### ISSUE TITLE
[evcc] Command to start charging - mode "now" doesn't seem to work

### ISSUE THREAD

**Issue by pmknowles** [openhab/openhab-addons#17393]
I may be missing something but changing the mode string to "now"/"off" doesn't seem to start/stop my WallBoxes charging.
I have resorted to creating an MQTT Switch channel with the message
`tele/evcc/loadpoints/2/mode/set `
and custom ON as now and OFF as off
That will then start and stop the charger
It also doesn't help the the binding is 0 based when evcc is 1 based (I have 2 chargers)

**Comment by lsiepel** [comment]
What openHAB and binding version do you use? Can you share some details about your Thing / Channel / Item configuration ? 
Do you see anything in the debug log of the binding?

**Comment by pmknowles** [comment]
Hi, I'm on 4.1.3 Release version. If I change the Mode to Fast (the docs say 'now' not 'Fast' but never mind) in the UI it will start the charger. But if I change the Mode to Fast or now by using a rule (or using the API Explorer)  it doesn't work.

SOLVED - if I use sendCommand(ESModeS, "now") it works.
