### ISSUE TITLE
[zigbee] Dead link in Zigbee binding docs

### ISSUE THREAD

**Issue by Stepiiis** [openhab/openhab-addons#17473]
In [this section](https://www.openhab.org/addons/bindings/zigbee/#configuration-via-ui-recommended) of the ZigBee binding documentation the link to Coordinator Configuration leads to a non existing page. 
The link should lead to a fragment rather than another resource "https://www.openhab.org/addons/bindings/zigbee/#coordinator-configuration".

**Comment by lsiepel** [comment]
Created a PR to fix this.
This binding is maintainted at another repo: https://github.com/openhab/org.openhab.binding.zigbee/

**Comment by lsiepel** [comment]
Pr is merged.
