### ISSUE TITLE
OH 4.2.2 issue with showing trendlines in items in Main UI

### ISSUE THREAD

**Issue by scheuerer** [openhab/openhab-addons#17507]
I updated today my three PI systems from OH 4.2.1 to OH 4.2.2.
From now on, trendline from the icons under basic UI works in this way, that only a
black screen comes up, and not more the graph from the item.

This happens only under iOS devices in different browser or the native client app for iOS.
So simelar issue as with the graph summery but this time with trendlines from items values.

It can be fixed with reload the app in the main section.

Please have a look why this happenes…

The error is confirmed here:

https://community.openhab.org/t/openhab-4-2-2-analyzer-in-widget-does-not-work-as-expected/159416/2

Thanks 

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lolodomo** [comment]
I am sorry but I do not understand at all what you are describing.
Can you please provide a screenshot showing what you are talking about ?
Is it really something relative to Basic UI run in a WEB browser ?

**Comment by scheuerer** [comment]
Please see here: All happens only iOS based device. e.g. iPad. in Browser and aso in the OH App. Not on Windows based browser etc.

See my startscreen:

![pic1](https://github.com/user-attachments/assets/2b6c7f45-da41-4dda-af17-c61145894c29)

 When I click on the Icon " Außentemperatur"

This windows comes up:

![pic2](https://github.com/user-attachments/assets/a1cd29b5-7ed8-428b-ad7a-3ae9a2e5140c)

When I then go the main section from OH iteself, and click the "reload the application button", go back and click the 
Icon once more it looks like it should:

![pic3](https://github.com/user-attachments/assets/787675fe-fe77-42fb-a011-52cb197dcf81)

I also noticed that the main menue overlaps my default main screen.
Please see on the first pic, left side.

BR
Jochen

**Comment by florian-h05** [comment]
> I also noticed that the main menue overlaps my default main screen.

In that case you have to reload the tab.

**Comment by lolodomo** [comment]
This is Main UI, not Basic UI...

**Comment by florian-h05** [comment]
And this is the wrong repo ... please re-open that issue in https://github.com/openhab/openhab-webui and follow the issue template there!

**Comment by scheuerer** [comment]
Opened a new issue under https://github.com/openhab/openhab-webui 

https://github.com/openhab/openhab-webui/issues/2797
