### ISSUE TITLE
[linky] Broken again

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17513]
Looks like the binding is broken again since 3 days !

The requests ends with: .../donnees-energie?dateDebut=01-01-2023&dateFin=05-10-2024&mesuretypecode=CONS

`{"message":"Internal server error. Please try again","code":"INTERNAL_SERVER_ERROR"} `

@clinique : can you confirm and can you please help (again) ?

**Comment by clinique** [comment]
Yes, linky is broken again. Api modification. I'm going to push an update.
