### ISSUE TITLE
[Viessmann API binding] parsing error

### ISSUE THREAD

**Issue by MaTr74** [openhab/openhab-addons#17516]
## Expected Behavior
Binding is working without parsing error.

## Current Behavior
Since 2024-10-03 13:20 CEST I get the following error from the binding:

`2024-10-03 13:20:31.903 [WARN ] [ernal.handler.ViessmannBridgeHandler] - Parsing Viessmann response fails: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 15 column 21 path $.data[0].properties.entries.value`

Switching logging to TRACE level gives me a full json response (see attachment).

The binding was working for months without problems.

## Your Environment
* openHAB 4.2.0 and 4.2.2 docker container
* Viessmann API binding for OpenHAB 4.0 [4.0.0;5.0.0)
[viessmann.log](https://github.com/user-attachments/files/17273493/viessmann.log)

**Comment by lsiepel** [comment]
Thank you for raising this issue. As this is a marketplace binding and not part of the official distribution, this issue won't be picked up from here.
The binding is discussed here: https://community.openhab.org/t/viessmann-api-binding-for-openhab-4-0-4-0-0-5-0-0/
It is maintained here: https://github.com/rtuck99/openhab-binding/issues 

Please report the issue on either one, with the API response you provided, this should be a fixable issue.

**Comment by MaTr74** [comment]
Thank you for clarification!
