### ISSUE TITLE
[jsonpath] path with `..*` not reliable

### ISSUE THREAD

**Issue by MaTr74** [openhab/openhab-addons#17533]
## Expected Behavior
MQTT plugin isn't treat a message/field/command as NULL.

## Current Behavior
I have the following MQTT thing configured:
```
    Thing topic test "Test" {
         Channels:
             Type switch: Status [ stateTopic="tele/wp-zigbee-coordinator-01/SENSOR", transformationPattern="REGEX:(.*ZbReceived.*test.*ZoneStatusChange.*)∩JSONPATH:$..*.ZoneStatusChange", on="1", off="0" ]
             Type number: LinkQuality [ stateTopic="tele/wp-zigbee-coordinator-01/SENSOR", transformationPattern="REGEX:(.*ZbReceived.*test.*LinkQuality.*)∩JSONPATH:$..*.LinkQuality" ]
             Type number: BatteryVoltage [ stateTopic="tele/wp-zigbee-coordinator-01/SENSOR", transformationPattern="REGEX:(.*ZbReceived.*test.*BatteryVoltage.*)∩JSONPATH:$..*.BatteryVoltage", unit="V" ]
             Type number: BatteryPercentage [ stateTopic="tele/wp-zigbee-coordinator-01/SENSOR", transformationPattern="REGEX:(.*ZbReceived.*test.*BatteryPercentage.*)∩JSONPATH:$..*.BatteryPercentage", unit="%" ]
             Type datetime: LastSeen [ stateTopic="tele/wp-zigbee-coordinator-01/SENSOR", transformationPattern="REGEX:(.*ZbReceived.*test.*)∩JS:currentDateTime.js" ]
     }

```
When I send the following message a second time:
```
{"ZbReceived":{"0xA7E2":{"Device":"0xA7E2","Name":"test","Cluster":10,"Read":[7],"ReadNames":{"LocalTime":true},"Endpoint":1,"LinkQuality":76}}}
```
... the following WARN messages appear in the log:
```
2024-10-12 09:29:52.535 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'NULL' from channel 'mqtt:topic:mosquitto:test:LinkQuality' not supported by type 'NumberValue': Character N is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
```

## Steps to Reproduce (for Bugs)
1. Create docker network `sudo docker network create openhab-test`
2. Install docker Mosquitto image (see attached mosquitto-docker-compose.yml)
3. Install docker openHAB image (see attached openhab-docker-compose.yml)
4. Install the following openHAB addons:
    * MQTT Binding
    * JSONPATH transformation
    * Regex transformation
5. Add mqtt.things file to `conf/things`  (file attached)
6. Send the message above twice to topic `tele/wp-zigbee-coordinator-01/SENSOR`

## Your Environment
* Version used: openHAB 4.2.0 as docker image

[files.zip](https://github.com/user-attachments/files/17349258/files.zip)

**Comment by lsiepel** [comment]
Not really sure what is going on there, might be related to the chaining, might be something different. I suspect it is rather introduced into 4.2.0 and not in in 4.2.2 as the changelog does not show something i can tie to this. Maybe @jimtng has some thoughts on this issue?

**Comment by MaTr74** [comment]
I went back step by step through the releases and can confirm that the warnings occur with 4.2.0. On 4.1.3 everything is working well. I will fix the title.

**Comment by MaTr74** [comment]
I've just created a minimal example with which you can reproduce the behaviour.

**Comment by MaTr74** [comment]
@lsiepel @jimtng Could you have a look in the meantime?

**Comment by lsiepel** [comment]
> @lsiepel @jimtng Could you have a look in the meantime?

I’lll try, just short on time these days.

**Comment by lsiepel** [comment]
Was able to reproduce the issue. As the first succeeds and every other attempt failes, i thought there might be some caching or state issue. Stopped all related transformations and bundles without effect. Eventually restarted openHAB. Still no effect.
Installed 4.2.0 M2 no effect.

**Comment by lsiepel** [comment]
4.2.0M2 Debug log:
```
2024-11-01 16:23:33.569 [DEBUG] [.internal.RegExTransformationService] - about to transform '{"ZbReceived":{"0xA7E2":{"Device":"0xA7E2","Name":"test","Cluster":10,"Read":[7],"ReadNames":{"LocalTime":true},"Endpoint":1,"LinkQuality":78}}}' by the function '(.*ZbReceived.*test.*LinkQuality.*)'
2024-11-01 16:23:33.569 [DEBUG] [ternal.JSonPathTransformationService] - about to transform '{"ZbReceived":{"0xA7E2":{"Device":"0xA7E2","Name":"test","Cluster":10,"Read":[7],"ReadNames":{"LocalTime":true},"Endpoint":1,"LinkQuality":78}}}' by the function '$..*.LinkQuality'
2024-11-01 16:23:33.570 [DEBUG] [ternal.JSonPathTransformationService] - transformation resulted in '[]'
```

**Comment by lsiepel** [comment]
`$..*.LinkQuality` seems an invalid notation. 
`$.*.*.LinkQuality` or `$.ZbReceived.*.LinkQuality` solves the issue

**Comment by lsiepel** [comment]
https://jsonpath.fly.dev/ also uses the same jsonpath library as openHAB uses. 2.9.0 is the most recent version.

I obse4rve the same behavior with your provided JSON and path. The first attempt is fine, any consecutive call shows no value. The library must use some sort of internal cache. I can reproduce this odd behavior by adding a suffix to the last property and increase it each attempt. Short demonstration:

https://github.com/user-attachments/assets/71049a32-f54e-4aa1-9cd9-c816451e550f

**Comment by MaTr74** [comment]
@lsiepel Many thanks for your investigation! It's not very clear, how someone has to use the recursive descent `..`. Some sites seem to don't have constraints for the usage like [https://goessner.net/articles/JsonPath/index.html#e2](https://goessner.net/articles/JsonPath/index.html#e2), other say you have it to use in that way `..property` like [https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html](https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html). As I assume (it's long time ago) my intentation was to simply select the property recursively e.g. `$..LinkQuality` is absolutely sufficient and always works even with [https://jsonpath.fly.dev/](https://jsonpath.fly.dev/). So I'll change my expressions respectively.

**Comment by lsiepel** [comment]
Hopefully the specs will be more clear in the future and fixed in the underlying library. 
I close it here for now
