### ISSUE TITLE
[SamsungTV] Wake up on lan Power ON/OFF

### ISSUE THREAD

**Issue by francemgit** [openhab/openhab-addons#17542]
## Expected Behavior
After sending the Turn On command to the Samsung TV the TV turns ON.

## Current Behavior
Just updated to the latest 4.3.0 Milestone 2. 
After sending the Turn On command to the Samsung TV, the SmartTV turns ON, but just after gets switched OFF

Debug Logs:
[openhab.log](https://github.com/user-attachments/files/17345909/openhab.log)

## Steps to Reproduce (for Bugs)

1. TV is switched Off
2. Turn ON TV via OpenHab either via Browser/Web or Mobile App

## Context
Trying to turn the TV on via OpenHab

## Your Environment

* Version used: openHAB 4.3.0 Milestone 2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): either via Chrome Browser or OpenHab App
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Mac Os X or iOS

**Comment by francemgit** [comment]
The JAR file fixed the initial WOL double ON/OFF issue but.... now there's a strange behaviour:

- Send ON command via OH, the TV turns ON
- Send OFF command via OH, the TV stays turned ON while is displayed as OFF in OH
- Send ON command via OH, the TV switchs OFF and just after OH aligns corretly on TV status and shows it as OFF

**Comment by lsiepel** [comment]
> The JAR file fixed the initial WOL double ON/OFF issue but.... now there's a strange behaviour:
> 
> * Send ON command via OH, the TV turns ON
> * Send OFF command via OH, the TV stays turned ON while is displayed as OFF in OH
> * Send ON command via OH, the TV switchs OFF and just after OH aligns corretly on TV status and shows it as OFF

Could you provide a debug log?

**Comment by francemgit** [comment]
> Could you provide a debug log?

Here attached: 
[openhab.log](https://github.com/user-attachments/files/17606580/openhab.log)

**Comment by NickWaterton** [comment]
As you have discovered, the power on/off behavior of Samsung TV's is very complex. The key line in the log is this:
```
2024-11-02 11:26:48.124 [DEBUG] [tv.internal.handler.SamsungTvHandler] - XXX.XXX.XXX.XXX: PowerState is: off
```
This means that the TV has powered up in response to the WOL, but is reporting that it is in "standby" or "off", which means that another "ON" command has to be sent.

It is possible that this version of the TV (series 6) simply does not report the `PowerState` - I have found some odd versions out there that do not. You can tell by issuing the command:
```
http://xxx.xxx.xxx.xxx:8001/api/v2/
```
Where `xxx.xxx.xxx.xxx` is the ip of your TV. By the way, you don't need to redact your TV's ip, nobody can do anything with it, it's not a public ip. Then post the results here. Mine looks like this:
```
{
"device": {
"EdgeBlendingSupport": "false",
"EdgeBlendingSupportGroup": "0",
"FrameTVSupport": "true",
"GamePadSupport": "true",
"ImeSyncedSupport": "true",
"Language": "en_US",
"OS": "Tizen",
"PowerState": "on",
"TokenAuthSupport": "true",
"VoiceSupport": "true",
"WallScreenRatio": "-1",
"WallService": "false",
"countryCode": "CA",
"description": "Samsung DTV RCR",
"developerIP": "192.168.100.31",
"developerMode": "1",
"duid": "uuid:dfb1ca7c-4458-49b4-bef7-de7554704418",
"firmwareVersion": "Unknown",
"id": "uuid:dfb1ca7c-4458-49b4-bef7-de7554704418",
"ip": "192.168.100.32",
"model": "22_PONTUSM_FTV",
"modelName": "QN43LS03BAFXZC",
"name": "Bedroom TV",
"networkType": "wired",
"resolution": "3840x2160",
"smartHubAgreement": "true",
"type": "Samsung SmartTV",
"udn": "uuid:dfb1ca7c-4458-49b4-bef7-de7554704418",
"wifiMac": "f0:70:4f:cb:4f:4b"
},
"id": "uuid:dfb1ca7c-4458-49b4-bef7-de7554704418",
"isSupport": "{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"true\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n",
"name": "Bedroom TV",
"remote": "1.0",
"type": "Samsung SmartTV",
"uri": "http://192.168.100.32:8001/api/v2/",
"version": "2.0.25"
}
```
I want to see what `PowerState` reports, if it exists, plus what the other values are.

Thanks,

**Comment by francemgit** [comment]
Here it is:

{
   "device":{
      "FrameTVSupport":"false",
      "GamePadSupport":"true",
      "ImeSyncedSupport":"true",
      "OS":"Tizen",
      "TokenAuthSupport":"true",
      "VoiceSupport":"false",
      "countryCode":"IT",
      "description":"Samsung DTV RCR",
      "developerIP":"0.0.0.0",
      "developerMode":"0",
      "duid":"uuid:28c7c67a-c4df-4aa1-8985-aa1eaedf0611",
      "firmwareVersion":"Unknown",
      "id":"uuid:28c7c67a-c4df-4aa1-8985-aa1eaedf0611",
      "ip":"192.168.1.13",
      "model":"17_KANTM_UHD_BASIC",
      "modelName":"UE55MU6220",
      "name":"[TV] Samsung 6 Series (55)",
      "networkType":"none",
      "resolution":"3840x2160",
      "smartHubAgreement":"true",
      "type":"Samsung SmartTV",
      "udn":"uuid:28c7c67a-c4df-4aa1-8985-aa1eaedf0611",
      "wifiMac":"none"
   },
   "id":"uuid:28c7c67a-c4df-4aa1-8985-aa1eaedf0611",
   "isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"false\"}\n",
   "name":"[TV] Samsung 6 Series (55)",
   "remote":"1.0",
   "type":"Samsung SmartTV",
   "uri":"http://192.168.1.13:8001/api/v2/",
   "version":"2.0.25"
}

**Comment by NickWaterton** [comment]
As I suspected, the `PowerState` value is missing. I have seen this in series 7 TV's before, and included a workaround for it. it looks like series 6 TV's are also missing this value.

I will have to check what I did for series 7 TV's, and include series 6 TV's as well.

Might take me a couple of days to come up with something.

**Comment by francemgit** [comment]
I'll provide you the log later or in a couple of day but, let me clarify that before Openhab 4.3.0 Milestone 2 everything was working correctly.

**Comment by francemgit** [comment]
Trace Log:

[openhab.log](https://github.com/user-attachments/files/17623048/openhab.log)

**Comment by NickWaterton** [comment]
Try this jar.

I'm guessing as to what is going on, but this might tell me something:
https://www.dropbox.com/scl/fi/9ew5h9lm9xdfc7sm9mt6q/org.openhab.binding.samsungtv-4.3.0-SNAPSHOT.jar?rlkey=cevm9ulpgs3i0tlf1yvplz9li&dl=0

**Comment by francemgit** [comment]
Near to be solved but, something still missing:

0. Binding just installed OR TV status is OFF from more than 1 minute from last Switch OFF
1. Turn on Command --> TV turns ON immediately
2. Turn off Command --> TV turns OFF immediately
3. Turn on Command --> it takes 15-20 sec to turn ON TV, I see a lot Sent WOL packet from in the Trace Log before TV turns ON

**Comment by NickWaterton** [comment]
This is normal behavior.

What happens is that the TV goes into standby (not off), as part of what Samsung calls "instant ON". However, this means that the TV network card is still active, and so will not respond to WOL commands.

You have to wait 30 seconds or so, for the TV to shut down completely after sending an OFF command, before a subsequent ON command will work properly.
