### ISSUE TITLE
[fmiweather] Add possibility to use fmi::forecast::edited in addition to fmi::forecast::harmonie

### ISSUE THREAD

**Issue by masipila** [openhab/openhab-addons#17548]
# Problem / Motivation
The fmiweather binding fetches weather forecast from the Finnish Meteorology Instititute's (FMI) API. The binding uses currently the fmi::forecast::harmonie::surface::point::multipointcoverage stored query. The forecast provided as a response is based on the Harmonie weather model, which is different to what FMI publishes as their official forecast on their website and in their mobile app.

The meteorologists at FMI use multiple different weather models and their experience to provide an official FMI forecast which they publish on their website and in the FMI mobile app. [This official forecast, which is often times more accurate than the Harmonie-based forecast, has been available via their API since 6 June 2023](https://en.ilmatieteenlaitos.fi/open-data-changelog). During the past two winters, there have been cases where the Harmonie based forecast has been off by almost 10 degrees while the forecast provided by the FMI meteorologists have been accurate.

Having as accurate weather forecast as possible is cruicial for optimizing the heating of a house using openHAB. There are solutions like the [openHAB Spot Price Optimizer](https://community.openhab.org/t/spot-price-optimizer-advanced-algorhitms-to-optimize-heating-charging-of-electric-vehicles-water-boilers-and-more/159539) to do this (I'm the maintainer of that solution). At the moment the Spot Price Optimizer doesn't use the FMI Binding, but has it's own javascript module to fetch the FMI forecast.

# Proposed change
I would like to see this official FMI Weather Binding to allow users to be able to choose between the fmi::forecast::edited model and the current fmi::forecast::harmonie model.

**Comment by jlaur** [comment]
This query also needs a `place` parameter, which can be something like "helsinki". Also the response payload is different, so it's not a simple matter of adapting the request URL parameters, but also the handling of the response payload.

**Comment by masipila** [comment]
I had a (very) quick look at this. The binding seems to currently be using the multipointcoverage stored query. The "edited" forecast is also available as a multipointcoverage stored query.

**Query against Harmonie weather model (I believe this is the URL structure that the binding currently uses)**
https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&latlon=60.192059,24.945831&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3

**Similar query against the Edited forecast** 
https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::edited::weather::scandinavia::point::multipointcoverage&latlon=60.192059,24.945831&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3

Disclaimer: As mentioned above, this is a result of very quick inspection. I have been using the `fmi::forecast::edited::weather::scandinavia::point::simple` stored query instead of `fmi::forecast::harmonie::surface::point::multipointcoverage`

**Comment by jlaur** [comment]
@masipila - can you try this? [org.openhab.binding.fmiweather-4.3.0-SNAPSHOT.jar](https://drive.google.com/file/d/1lFBAyN4x7Np4OHnlmR3vG8wlG31xNOfm/view?usp=sharing)

**Comment by masipila** [comment]
Thanks @jlaur ! I'm travelling at the moment but I might have some time on Wednesday or Thursday. 

Markus

**Comment by masipila** [comment]
Heya, I was able to install the snapshot JAR and noticed that it's now a configuration option to select which forecast model to use. :)

A bit stupid question since I haven't used this Binding or the other ones which are storing the forecasts as future time series (I just know that this capability has been around for a while now). This Binding has so many Channels that I'm confused what am I supposed to do to correctly create an Item which has the forecast stored as a proper time series?

**Comment by masipila** [comment]
Disregard the previous comment, I managed to figure it out. 

If some other community members are wondering the same thing, it was as simple as to create an Item for the `forecast#temperature` channel and then configure the persistence startegy `forecast` for this newly created Item.

@jlaur : I'll continue my checks here but it looks very promising!

**Comment by masipila** [comment]
@jlaur: And here's an example from tomorrow's forecast which illustrates the slight difference in the forecast made by a meteorologist compared to the "raw" Harmonie weather model.

Time will tell tomorrow which one is closer to the reality, but adding the configuration option to use the data from the `fmi::forecast::edited` dataset is a much welcome improvement IMHO.

![image](https://github.com/user-attachments/assets/10386c86-4e9e-468c-81d1-ebc5b88e2b0d)

Cheers,
Markus

**Comment by masipila** [comment]
Updated issue title summary to reflect the direction where users can choose between the edited model and harmonie model. I like this approach because it's fully backwards compatible for existing users of this binding.

**Comment by jlaur** [comment]
> a) the time horizon of the forecast with this binding is ~one day less than what I get with the other kind of API call that I use currently

We could add a configuration parameter for this. This is part of the URL, but currently hardcoded:

https://github.com/openhab/openhab-addons/blob/main/bundles%2Forg.openhab.binding.fmiweather%2Fsrc%2Fmain%2Fjava%2Forg%2Fopenhab%2Fbinding%2Ffmiweather%2Finternal%2FForecastWeatherHandler.java#L63

> b) the resolution of the persisted forecast with this binding is PT20M whereas I currently get PT60M.

See here:

openhab/openhab-addons/blob/main/bundles%2Forg.openhab.binding.fmiweather%2Fsrc%2Fmain%2Fjava%2Forg%2Fopenhab%2Fbinding%2Ffmiweather%2Finternal%2FForecastWeatherHandler.java#L61

This one I don't understand, because the binding so far only published hourly forecasts, so it seems excessive to request three times more data than actually used.

I think we could add a parameter here as well, which would only be effective when one of the time series channels are linked. Otherwise we could use PT60M.

@ssalonen - WDYT?

> But neither of these observations have anything to do with the scope of this feature request

Agreed, could be enhanced in another PR.

**Comment by ssalonen** [comment]
@jlaur there is one detail with how the FMI API works that explains this detail. Indeed we query with 20min resolution but output only hourly forecasts.

FMI API "rounds" the start time to the future based on this "resolution". When we use 20min resolution, and round start and end time accordingly (1),  the first data point pretty much matches current time. 

If we would have 1h resolution, we might be off by one hour with the forecast. With 20min resolution, we are at most off by 20min. 20min was selected arbitrararily, compromise between data amount and this forecast "time accuracy" (in 20min, usually weather remains relatively stable)

(1) https://github.com/openhab/openhab-addons/blob/65004e5645c112e13b0bfc5fd2830c103cf66283/bundles/org.openhab.binding.fmiweather/src/main/java/org/openhab/binding/fmiweather/internal/ForecastWeatherHandler.java#L126


The API behaviour is perhaps best illustrated by these examples
```
#curl 'https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&starttime=2024-10-17T15:22:00Z&endtime=2024-10-17T18:22:00Z&timestep=60&latlon=60.19,24.94&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3'
#starttime=2024-10-17T15:22:00Z&endtime=2024-10-17T18:22:00Z&timestep=60
#  <gml:TimePeriod gml:id="time-interval-1-1">
#                    <gml:beginPosition>2024-10-17T16:00:00Z</gml:beginPosition>
#                    <gml:endPosition>2024-10-17T18:00:00Z</gml:endPosition>
#                </gml:TimePeriod>

#curl 'https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&starttime=2024-10-17T15:00:00Z&endtime=2024-10-17T18:00:00Z&timestep=60&latlon=60.19,24.94&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3'
#starttime=2024-10-17T15:00:00Z&endtime=2024-10-17T18:00:00Z&timestep=60
#<gml:TimePeriod gml:id="time-interval-1-1">
#                    <gml:beginPosition>2024-10-17T15:00:00Z</gml:beginPosition>
#                    <gml:endPosition>2024-10-17T18:00:00Z</gml:endPosition>
#                </gml:TimePeriod>

#curl 'https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&starttime=2024-10-17T15:01:00Z&endtime=2024-10-17T18:01:00Z&timestep=120&latlon=60.19,24.94&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3'
#starttime=2024-10-17T15:01:00Z&endtime=2024-10-17T18:01:00Z&timestep=120
#                <gml:TimePeriod gml:id="time-interval-1-1">
#                    <gml:beginPosition>2024-10-17T16:00:00Z</gml:beginPosition>
#                    <gml:endPosition>2024-10-17T18:00:00Z</gml:endPosition>
#                </gml:TimePeriod>


#curl 'https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&starttime=2024-10-17T15:00:00Z&endtime=2024-10-17T18:00:00Z&timestep=120&latlon=60.19,24.94&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3'
#starttime=2024-10-17T15:00:00Z&endtime=2024-10-17T18:00:00Z&timestep=120
#                <gml:TimePeriod gml:id="time-interval-1-1">
#                    <gml:beginPosition>2024-10-17T16:00:00Z</gml:beginPosition>
#                    <gml:endPosition>2024-10-17T18:00:00Z</gml:endPosition>
#                </gml:TimePeriod>

#curl 'https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::harmonie::surface::point::multipointcoverage&starttime=2024-10-17T14:20:00Z&endtime=2024-10-17T21:00:00Z&timestep=20&latlon=60.19,24.94&parameters=Temperature,Humidity,WindDirection,WindSpeedMS,WindGust,Pressure,Precipitation1h,TotalCloudCover,WeatherSymbol3'
#starttime=2024-10-17T14:20:00Z&endtime=2024-10-17T21:00:00Z&timestep=20
#                <gml:TimePeriod gml:id="time-interval-1-1">
#                    <gml:beginPosition>2024-10-17T14:20:00Z</gml:beginPosition>
#                    <gml:endPosition>2024-10-17T21:00:00Z</gml:endPosition>
#                </gml:TimePeriod>
```

**Comment by ssalonen** [comment]
Re. hardcoded forecast horizon, I was gauging true available forecast with a simple script https://github.com/openhab/openhab-addons/pull/13693#issuecomment-1336400256

**Comment by jlaur** [comment]
> there is one detail with how the FMI API works that explains this detail.

Thank you for your very detailed explanations. I'm on a short holiday, but will have a closer look when I'm back home, where it will be easier to check things out. 🙂

**Comment by jlaur** [comment]
@masipila - perhaps you can help me out [here](https://crowdin.com/editor/openhab-addons/5207/en-fi#154252:drl:1940:mikael.gustafsson80)? 😄 Regarding a question when doing the Finish translation.

**Comment by masipila** [comment]
I upvoted "Skandinavian sääennuste (meteorologin muokkaama)" in crowdin.com, that's correct translation for this.
