### ISSUE TITLE
[shelly] BLU H&T stuck initializing or in sleep mode

### ISSUE THREAD

**Issue by kojid0** [openhab/openhab-addons#17568]
When I try to add my Shelly BLU H&T, it is not detected automatically. After adding manually via MAC-adress, the device is displayed online but as initializing or in sleep mode

OpenHAB 4.2.2

**Comment by chakjer** [comment]
Block access to internet for device.
I had similar problem, blu motion stuck at `stuck initializing or in sleep mode` but i can found it in inbox. Removing, factory reset  didn't help.
I have seprate wifi for it with no access to internet but some time to times I enabled it for update. Last time i forgot ;).

**Comment by kojid0** [comment]
@chakjer Shelly BLU H&T doesn't have internet access, it's a bluetooth-only device which connects to another shelly device.

**Comment by chakjer** [comment]
Correct, how long my blu gateway ( tested on shelly plus 1PM and plus i4) has access to internet as long i have stuck initializing or in sleep mode.I have never register any device in shelly api, always worked on openhab but via mqtt.
Now I use shelly bindings but only for  BLU Gateway Support.
It occurs only during initialization, normal working is not affected.

**Comment by kojid0** [comment]
I found the solution. The observer device must have BLU Gateway support enabled in OpenHAB as well as in ShellyControlApp. Now it works fine, even with internet access.
