### ISSUE TITLE
[Netatmo] Error when sending temperature commands to the thermostats

### ISSUE THREAD

**Issue by nelsonaponte** [openhab/openhab-addons#17585]
## Current Behavior
Sending temperature change commands to the thermostats fails with the following error:
`11:58:48.082 [WARN ] [l.handler.capability.EnergyCapability] - Error setting room thermostat mode 'MANUAL' : Rest call failed: statusCode=INVALID_ARGUMENT, message=Endtime in the past`

This is the DEBUG output:
`11:58:47.894 [DEBUG] [tmo.internal.handler.ApiBridgeHandler] - executeUri POST  https://api.netatmo.com/api/setroomthermpoint?home_id=xxxxxxxxx&room_id=yyyyyyy&mode=manual&endtime=1729245467&temp=21.5`

All Things are ONLINE and the Items receive information from the Thing channels.

## Steps to Reproduce

1. Ensure the Account, Relay, Room, and Thermostat Things are ONLINE.
2. Send an update command to the room's setpoint#value channel with a valid temperature
3. Check the error message on the Karaf console

## Your Environment
* OH Version: OH 4.2.1 and 4.2.2
* Binding Versions: Confirmed with 4.2.1, 4.2.2, 4.2.3-SNAPSHOT (https://boeckmanns-my.sharepoint.com/:u:/g/personal/nils_boeckmanns_de/EV8R7BnSz0VKrDhDbzgCE28BammtaspolYQjxzpHOVIpoQ?e=ksnsst)

**Comment by clinique** [comment]
Got it. The answer was done with default ZoneID, not the ZoneID belonging to the house.
