### ISSUE TITLE
[evcc] Charge Plan Time is not converted to correct Timezone

### ISSUE THREAD

**Issue by tmsch13** [openhab/openhab-addons#17620]
## Expected Behavior
If i set the VehiclePlanTime in openhab I expect to see the same time in EVCC.

## Current Behavior
If I set the VehiclePlanTime to eg "2024-10-24T05:30:00.636+02:00“ using Blockly
<img width="1000" alt="Bildschirmfoto 2024-10-23 um 11 39 45" src="https://github.com/user-attachments/assets/b3c16af7-f064-4999-8b8a-0218829c1b23">

it converts to 7:30 in EVCC
<img width="188" alt="Bildschirmfoto 2024-10-23 um 11 40 10" src="https://github.com/user-attachments/assets/6c965e45-4571-4f0b-84e2-f3433c006af3">

The correspondig MQTT Topic (evcc/vehicles/Tesla_Y/plans/1/time) then shows 1729747800 
which is
**GMT:** Thursday, 24. October 2024 05:30:00
**My time zone:** 24. Oktober 2024 07:30:00 [GMT+02:00]

By the way: If i change the Planed Time in EVCC, the MQTT Topic gets updated, but not the EVCC channel of the EVCC Binding in Openhab...

## Steps to Reproduce (for Bugs)
Set the Plan Time via openhab to a not GMT Time and see the result in EVCC

## Your Environment
Openhab: 4.2.1
EVCC: 0.130.2

**Comment by Laith-Budairi** [comment]
does it also display the same time in the item linked to the channel? I tried running the same blockly code and I have this result:

![image](https://github.com/user-attachments/assets/b2f960bc-c260-4b33-9d2a-bb7942bda9b9)

**Comment by tmsch13** [comment]
6:30 is strange... Is it converting the Item value to some other local time zone at your system?


The Item shows 5:30:00 for me.
<img width="764" alt="Bildschirmfoto 2024-10-24 um 08 52 21" src="https://github.com/user-attachments/assets/531fa1fb-bc87-489b-8c35-e8b047aa8960">

The log shows: 
`2024-10-24 08:52:06.322 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'EVCC_TeslaY_Plan_Time' received command 2024-10-25T05:30:00.320+0200`

But thats as expected in openHAB, because „copy of now“ uses ZonedDateTime.

<img width="373" alt="Bildschirmfoto 2024-10-24 um 08 55 02" src="https://github.com/user-attachments/assets/271e0d5e-2dc4-4b4c-9ad1-39d2eadf1f0d">

**Comment by Laith-Budairi** [comment]
my time zone is UTC+2. Just to make sure, the plan should be displayed here right? I am using https://demo.evcc.io/

![image](https://github.com/user-attachments/assets/0a3314f2-3705-4d9a-8819-feaad99f3e58)

**Comment by tmsch13** [comment]
Yess, thats where the Plan Time is displayed.

I just checked openhab and evcc system, which are each individual vms: 
Seems fine for me:


```
root@evcc:~# date
Thu Oct 24 09:06:02 CEST 2024

openhabian@openhab3:~$ date
Thu Oct 24 09:06:21 CEST 2024

```

**Comment by Laith-Budairi** [comment]
so the bug is not there anymore?

**Comment by tmsch13** [comment]
no it is still there. 
the system time on both systems (openhab and evcc) is the same, but when I set a time plan i have different times:

 
<img width="770" alt="Bildschirmfoto 2024-10-24 um 09 23 45" src="https://github.com/user-attachments/assets/1e0250fb-209f-4d07-84f5-2dd20c6f9299">

<img width="623" alt="Bildschirmfoto 2024-10-24 um 09 24 10" src="https://github.com/user-attachments/assets/fb1c0682-971a-4f9a-8ef4-149bf98a6e4d">

**Comment by Laith-Budairi** [comment]
yeah, I just tried to reproduce the bug and had this result, it is two hours ahead from what I set:

![image](https://github.com/user-attachments/assets/718c0cc5-36e5-4821-888b-6edfa08d686f)

**Comment by Laith-Budairi** [comment]
actually there is a weird behavior, if I try to set it to tomorrow at 5:30, the value is:
![image](https://github.com/user-attachments/assets/ca6388b9-39fc-49d3-877b-41932cd3f34b)


but if I try to set it for any day after tomorrow with the same time (5:30), the value displayed on the item is correct:
![image](https://github.com/user-attachments/assets/2700cdb8-eda8-4c7e-bd30-b8c10eda6379)

**Comment by Laith-Budairi** [comment]
yeah I think you are right with the winter/summer time. So we can assume that the time is displayed correctly from the defined item, the only issue now is the time on EVCC

**Comment by tmsch13** [comment]
I just tried the evcc api and i think its also not working correct:

```
curl -X POST "http://192.168.XX.XX:7070/api/vehicles/Tesla_Y/plan/soc/90/2024-10-25T05:30:00Z"
{"result":{"soc":90,"time":"2024-10-25T05:30:00Z"}}

curl -X POST "http://192.168.XX.XX:7070/api/vehicles/Tesla_Y/plan/soc/90/2024-10-25T05:30:00-01:00"
{"result":{"soc":90,"time":"2024-10-25T05:30:00-01:00"}}

curl -X POST "http://192.168.XX.XX:7070/api/vehicles/Tesla_Y/plan/soc/90/2024-10-25T05:30:00+01:00"
404 page not found
```

so positiv offsets from Zulu time (aka UTC ) doesn’t work.  

But as the openhab Binding is able to send a plan to evcc it is using „Z" time or "-0:00“ offset, which is not a problem, but than the binding has to make shure to convert correctly from local time (5:30:00+02:00 in this case) to UTC.

**Comment by tmsch13** [comment]
I raised an Issus at EVCC [Link](https://github.com/evcc-io/evcc/issues/16827)
But I think the Problem needs also be addressed in the openhab binding as said: 

> the binding has to make sure to convert correctly from local time (5:30:00+02:00 in this case) to UTC

**Comment by Laith-Budairi** [comment]
although in the binding after it updates the time using the POST API, it retrieves the whole values using the GET API /api/state, and I can see that the effective plan time is set correctly: 
![image](https://github.com/user-attachments/assets/79c7657c-5f7f-4457-916e-9d6cefada19c)

**Comment by tmsch13** [comment]
Yeah, what you see is the problem.

You set the time in openhab to 5:30+2:00 (which is 3:30Z aka UTC)
and your screenshot shows  5:30Z (which is 7:30+2:00) 

that because the binding takes 5:30+2:00 and send it as 5:30Z which means 5:30+0:00, so is a total different time. 
The binding should send: 5:30+2:00 (which seems to be impossible due to an api bug in evcc) or 3:30Z which is the same time just in Zulu time zone.

**Comment by Laith-Budairi** [comment]
Hi @lucaarn,

Can you share your insights on this?

**Comment by Laith-Budairi** [comment]
@tmsch13 have you tried it after the fix they merged?

**Comment by lsiepel** [comment]
The binding does not make use of the `TimeZoneProvider` so it does not respect the timezone set in openHAB. It uses the zone information from the running proces/java/systemI might come up with a fix, but i need someone able to test and verify. (mayube in 2 iterations)

**Comment by tmsch13** [comment]
@Laith-Budairi  Just tried the nighty EVCC Release with the Fix, positive time offset is now working fine. Remember as we will switch to Winter time this night the offset in Europe is now +01:00

`curl -X POST "http://192.168.XX.XX:7070/api/vehicles/Tesla_Y/plan/soc/90/2024-10-27T09:30:00+01:00"
{"result":{"soc":90,"time":"2024-10-27T09:30:00+01:00"}}`

But openhab binding is (as a expected) still not working correct:

Set Item to 5:30h

Log has the correct Time including Timezone:
Item 'EVCC_TeslaY_Plan_Time' received command 2024-10-27T05:30:00.763+0100

But I see 6:30h in EVCC. So openhab Binding is sending 5:30 UTC to EVCC which is 6:30+01:00

@lsiepel  Let me know if i can test anything, would be glad to help.
You say, the binding uses the Timezone of the running process, but as my system time is the same as the openhab timezone, I think the problem really is, that the binding is ignoring any timezone and just sends out the time as if it would be utc. Maybe this is working if the System is set to utc...

**Comment by Laith-Budairi** [comment]
@tmsch13 I tried to fix it in the binding and I have a jar file, would you like to test out and see if it works in your time zone? 

jar file: https://files.fm/u/wdfevpaa9g

**Comment by tmsch13** [comment]
Just tested the jar and can confirm, that times are now send correctly to evcc. Thanks very much :)

Nevertheless if i edit chardplan time or target SOC in EVCC, the binding seems not to get the new values... But thats maybe another bug and not as important for me as i just want to send plans from OH to EVCC

**Comment by lucaarn** [comment]
> Hi @lucaarn,
> 
> 
> 
> Can you share your insights on this?

Sorry for not responding. Recently I have some uni and private stuff to do.

**Comment by Laith-Budairi** [comment]
> > Hi @lucaarn,
> > Can you share your insights on this?
> 
> Sorry for not responding. Recently I have some uni and private stuff to do. I hope you can fix/fixed this bug🙏

no worries, thank you

**Comment by Laith-Budairi** [comment]
> Just tested the jar and can confirm, that times are now send correctly to evcc. Thanks very much :)
> 
> Nevertheless if i edit chardplan time or target SOC in EVCC, the binding seems not to get the new values... But thats maybe another bug and not as important for me as i just want to send plans from OH to EVCC

good to hear!
