### ISSUE TITLE
[freeboxos] Missing label/description in UI for action inputs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17635]
Some annotations are probably missing.

![image](https://github.com/user-attachments/assets/32224c1b-d36f-43c7-ad68-5fee0e7c1ce4)

It is not UI issue as it works well for other bindings.

**Comment by lolodomo** [comment]
@florian-h05 : I have a doubt. How this action without `@ActionInput` can be supported by UI ?

**Comment by florian-h05** [comment]
From the linked code above I can see it has a `@ActionInput` annotation.

**Comment by lolodomo** [comment]
> From the linked code above I can see it has a @ActionInput annotation.

Yes, you're right ! So, it is normal that they appear in UI.

What is missing is only label and description parameters.

**Comment by lolodomo** [comment]
I am going to extend this issue to all bindings defining action inputs without any label. This is a lot...

**Comment by lolodomo** [comment]
@florian-h05 : maybe you could use the name as label in UI when there is no label provided ?
It could be changed in UI side or in core side in the helper class we created.

**Comment by florian-h05** [comment]
That’s what I’ve also thought.
I would tend to apply that default in the UI.

**Comment by lolodomo** [comment]
> I would tend to apply that default in the UI.

Yes, I think it is better.

**Comment by florian-h05** [comment]
Applied in the UI: https://github.com/openhab/openhab-webui/pull/2840.
The UI now also displays the output description if provided.
