### ISSUE TITLE
Add min/max color temperature capabilities to channel state descriptions

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17638]
Several bindings which support colour temperature absolute channels (i.e. channels for a colour temperature in Kelvin) should have the absolute minimum and maximum Kelvin colour temperature capabilities added to their state descriptions. This should be done:

1. either, statically in the channel type description xml, 
2. or, dynamically in code via a channel state description provider

See the discussion here https://github.com/openhab/openhab-core/issues/3891

The following bindings are foreseen to have this update:

- AVMFritz
- AmazonEcho
- Dali
- Deconz
- Govee
- Hue
- Lifx
- MQTT:EspMiLightBulb / HomeAssistant / Homie
- NanoLeaf
- Tapo
- TPLink
- Zigbee

Depends on https://github.com/openhab/openhab-core/pull/4420
Depends on https://github.com/openhab/openhab-core/pull/4429

Note: there are several other bindings which have a more rudimentary control over colour temperature -- eith on a simple 0..100% scale or in steps low/medium/high or similiar. I am noting these below, but currently no action is forseen:

- [ ] Dmx
- [x] Epson projector => nothing to change, the value is not directly a Kelvin or mirek value
- [ ] Feican
- [ ] LG Tv serial
- [ ] MiHome
- [ ] MiLight
- [x] Samsung TV => nothing to change, the value is not directly a Kelvin or mirek value
- [ ] Smart things
- [x] Sony projector => nothing to change,, the color temperature is a list of discrete values
- [ ] Tradfri
- [ ] Yeelight
- [ ] ZWay

**Comment by andrewfg** [comment]
@lolodomo for info..

**Comment by andrewfg** [comment]
Having now studied the code of the bindings mentioned above, the following is my proposed list of actions:

#### AVMFritz
Supports fixed min/max of 2700 K / 6500 K.
Action: modify the channel type xml description.

#### AmazonEcho
Supports fixed min/max of 1000 K / 10000 K.
The `system.color-temperature-abs` uses this range, so continue to use it (i.e. no further action needed).

#### Dali 
Supports fixed min/max of 1000 K / 20000 K.
The current maximum colour temperature in ColorUtil is 10000 K.
Proposed Action: continue to use `system.color-temperature-abs` (i.e. no further action needed).

#### Deconz
Supports dynamic min/max in Kelvin.
Already implements a dynamic state description provider (i.e. no further action needed)

#### Govee  
Supports fixed min/max of 2000 K / 9000 K.
Action: modify the channel type xml description.

#### Hue
Supports dynamic min/max in Kelvin.
Implement a dynamic state description provider -- already work in progress -- see #17637

#### MQTT:EspMiLightBulb
Supports dynamic min/max **in Mirek**!! 
@lolodomo can you please give your thoughts if your PR can read the min/max in Mirek?
Or shall we modify the binding to use Kelvin as a base unit?
https://github.com/openhab/openhab-addons/blob/abe819978feec579f26e94d9f4f4cff9b7ba3b76/bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightStateDescriptionProvider.java#L64

#### NanoLeaf
Supports dynamic min/max in Kelvin.
Action: implement a dynamic state description provider.

#### Zigbee
Supports dynamic min/max in Kelvin. 
Action: implement a dynamic state description provider.

**Comment by lolodomo** [comment]
> Supports dynamic min/max **in Mirek**!!

What is the difference between mired and mirek ?

**Comment by lolodomo** [comment]
> #### MQTT:EspMiLightBulb
> Supports dynamic min/max **in Mirek**!! @lolodomo can you please give your thoughts if your PR can read the min/max in Mirek? Or shall we modify the binding to use Kelvin as a base unit?

This is not yet clear for me too.
I assume the unit defined in pattern implicitly defined the unit of min/max ?
I will have to test to understand the unit I retrieved with the method I am using and if this unit is consistent with the min/max values in the state description.

**Comment by andrewfg** [comment]
> What is the difference between mired and mirek ?

Actually they are identical. Originally Mired was defined ("**mi**cro **re**ciprocal **d**egree"). However the term "degree" is not properly defined. Therefore, subsequently, and properly, the SI committee defined the unit as Mirek ("**mi**cro **re**ciprocal **k**elvin"). The problem is that many people are stuck in the past with Mired, whereas we should look to the future proper SI unit.

**Comment by lolodomo** [comment]
I own two models of hue lights. None of my things expose a color temperature channel. I will give you the models so that you can confirm this is expected.

I have a Matter bulb with color temperature but te current channel is currently only a 0%-100%.

So not ideal to t st but not f course I can set a state description on any virtual item.

**Comment by lolodomo** [comment]
@andrewfg : I plan to simply use the unit in pattern of the state description to infer the unit of min)max of the state description.
Can you please confirm that each time a pattern is provided and it contains mired or K?

We could also list all bindings having a relative color temperature channel to potentially extend them with an absolute color temperature channel. WDYT?

**Comment by lolodomo** [comment]
> I own two models of hue lights. None of my things expose a color temperature channel. I will give you the models so that you can confirm this is expected.

First is model RB_265 from vendor INNR.
Second is model LLC011 from vendor Philips.

Normal that I have not colour temperature channel?

**Comment by andrewfg** [comment]
> Normal that I have not colour temperature channel?

I would not say "normal" but it is certainly possible.
In my experience there are four classes of lights from Hue (and other Zigbee providers):

1. On/Off only e.g. smart plug
2. On/Off plus Brightness at fixed Color Temperature i.e. CT channel not supported
3. On/Off plus Brightness plus Color Temperature
4. On/Off plus Brightness plus Color Temperature plus Full Color
 
> First is model RB_265 from vendor INNR.

Yes, I think this is indeed class 2. above

> Second is model LLC011 from vendor Philips.

I think this should be class 4. above.

---

As I recal it, you are using Hue Bridge v1 (round one). So this can't support Hue API v2. So the lamps cannot declare their capabilities dynamically, Which may mean that the CT channel is no available in your case. Or??

**Comment by andrewfg** [comment]
> Option 1 is the preferred.

Ok. (Just a tip to remember that min and max become reversed when Mired is inverted into Kelvin).

**Comment by ccutrer** [comment]
I highly lean towards option 1. Besides ESPMilightHub, many (most?) things coming in via MQTT use mired, not Kelvin. In particular, Home Assistant [explicitly specifies](https://www.home-assistant.io/integrations/light.mqtt/#color_temp_command_topic) color temperatures are in mireds only. It would be non-trivial to plumb a change of units all the way through from device discovery to the mqtt.generic value wrappers - we rely on core to do exactly that when we get a command, or post updates! And if you're using a Homie device that supports color temperature (in mired), it would be even more special casing, since Homie has no higher level concept of lighting or color temperature - just a number that just happens to have a particular unit.

**Comment by andrewfg** [comment]
@ccutrer thanks for your feedback.

> Home Assistant

I am not sure that this is really relevant. ?? In OH we have UoM QuantityTypes with (to be specific) conversion both ways Mirek <=> Kelvin. However I would ignore this comment, since it certainly does not relate to this Issue here.

> Homie has no higher level concept of lighting or color temperature - just a number that just happens to have a particular unit.

In OH many bindings produce such bare numbers. However IMHO that does not prevent usin UoM since the "particular unit" is known at the time of writing code. But again I would ignore this comment, since it certainly does not relate to this Issue here.

Conclusion: I shall not touch EspMiLight. And @lolodomo will handle the state description min/max values bases on the unit provided in the state description pattern.

**Comment by maniac103** [comment]
> And @lolodomo will handle the state description min/max values based on the unit provided in the state description pattern.

When doing decisions here, please don't think only of what BasicUI can do, but make sure the REST API response contains enough details to also make other clients work. I'm thinking of cases like min/max in Mirek in state description, item value in Kelvin and min/max specified without unit on the widget level. Since state description and item units can differ, it's not clear to me yet what unit to assume for the sitemap widget.

**Comment by ccutrer** [comment]
> I am not sure that this is really relevant. ?? In OH we have UoM QuantityTypes with (to be specific) conversion both ways Mirek <=> Kelvin. However I would ignore this comment, since it certainly does not relate to this Issue here.

It's relevant because it's a binding that provides a state description with mireks, and not in your list of bindings doing so.

> > Homie has no higher level concept of lighting or color temperature - just a number that just happens to have a particular unit.
> 
> In OH many bindings produce such bare numbers. However IMHO that does not prevent using UoM since the "particular unit" is known at the time of writing code. But again I would ignore this comment, since it certainly does not relate to this Issue here.

It's not a bare number. It's a quantity type, with a unit provided by the end device, and that unit could be either mirek or kelvin. If the color temperature picker can't handle mirek, it would exclude using it with any of these devices.
 
> Conclusion: I shall not touch EspMiLight. And @lolodomo will handle the state description min/max values based on the unit provided in the state description pattern.

👍 

> Since state description and item units can differ, it's not clear to me yet what unit to assume for the sitemap widget.

I'm also a little confused here. Currently, I have items with an item unit of mired, with a (final - because I'm explicitly setting it) state description using K because in my sitemaps that's more familiar. I most of my color temp items are linked with channels that provide it in mired, but I think a couple use Kelvin - but I don't really care because the item ends up as described above. I leave the item in mired because it's easier for doing math with in my rules that automatically adjust color temperature throughout the day. But someone else might prefer keeping it in Kelvin, and only converting to mired to do the math.

BUT... this whole paragraph is more relevant to the root issue of https://github.com/openhab/openhab-core/issues/3891 (because it's about items), and less relevant to what state descriptions bindings provide (which is only a guidance to when the item is created).

**Comment by andrewfg** [comment]
@ccutrer / @maniac103 for the avoidance of doubt, the issue is the following: A typical binding with a colour temperature absolute channel (a channel of type Number:Temperature or just plain Number) would have a channel type description as shown below.

There is NO PROBLEM concerning the main live value of the channel because it is a QuantityType:Temperature which carries a UoM and can therefore be presented in Mirek or Kelvin and cast both ways.

Our problem is with the minimum and maximum colour temperature values for the light in question. Which we need to set the two ends of the colour gradient in the color temperature picker widget. The current plan is to get those from the `min` and `max` attributes of the XML `state` element. Unfortunately those attributes are BARE numbers i.e. without any UoM attached. So the issue is how to interpret what they mean.


```
	<channel-type id="color-temperature-abs" advanced="true">
		<item-type>Number:Temperature</item-type>
		<label>Color Temperature</label>
		<description>Controls the color temperature of the light in Kelvin</description>
		<category>ColorLight</category>
		<tags>
			<tag>Control</tag>
			<tag>ColorTemperature</tag>
		</tags>
		<state min="2000" max="6500" pattern="%.0f K"/>
	</channel-type>
```

There are a number of uses cases as follows:
- `<state min="2000" max="6500" pattern="%.0f K"/>` => widget gradient goes from 2000K/500mk to 6500K/153mk
- `<state min="2000" max="6500" pattern="%.0f"/>` => ditto
- `<state min="2000" max="6500" pattern="%.0f aardvark"/>` => ditto
- `<state min="2000" max="6500"/>` => ditto
- `<state min="153" max="500" pattern="%.0f mirek"/>` => ditto (but note that min/max must be swapped to calculate)
- `<state min="153" max="500" pattern="%.0f K"/>` => ERROR !!
- `<state min="2000" max="6500" pattern="%.0f mirek"/>` => ERROR !!

**Comment by andrewfg** [comment]
@ccutrer in reply to your above..

> also a little confused here

Hopefully my post above makes it clearer.

> relevant because it's a binding that provides a state description with mireks

Aha!! I though you were referring to the Home Assistant platform (in contrast to OH). But I now realise you are talking about the mqtt:homeassistant sub- binding. => I will look at that further and give more comments if any.

> It's a quantity type, with a unit provided by the end device

I now realise you are talking about the mqtt:homie sub- binding. => I will look at that further and give more comments if any.

> less relevant to what state descriptions bindings provide (which is only a guidance to when the item is created)

I guess this is true. But it is still important to set the right guidance IMHO..

**Comment by ccutrer** [comment]
Somewhat relevant to this discussion: https://github.com/openhab/openhab-core/pull/4079. I hadn't yet seen this, and perhaps need to go add it to my bindings?

**Comment by andrewfg** [comment]
> Somewhat relevant to this discussion: https://github.com/openhab/openhab-core/pull/4079.

Indeed! The UnitHint would indeed be an alternate source for the UoM for the `state` `min`/`max` attributes, => @lolodomo WDYT?

**Comment by andrewfg** [comment]
@ccutrer here is my further feedback on the other two mqtt sub- bindings:

> mqtt:homeassistant .. it's a binding that provides a state description with mireks

I can see that you do use Mirek in some places. And I see that the min/max mirek values are available in the JSON. However, in contrast to mqtt:espmilight I don't see that it provides a StateDescription for the colour temperature channels -- neither in XML nor via a dynamic provider. => Therefore I think this sub- binding is also a strong candidate to have a DynamicStateDescriptionProvider analogous to what I have written for other bindings in #17641 (or what you have written in mqtt:espmilight). => WDYT?

> mqtt:homie .. It's a quantity type, with a unit provided by the end device, and that unit could be either mirek or kelvin

Hmm. Again I don't see that it provides a StateDescription for the colour temperature channels. I see that the channels do have configuration parameters for min/max/step/unit but I don't see if or where this information may be provided as a StateDescription to OH core. => Again I think this sub- binding is also a strong candidate to have a DynamicStateDescriptionProvider, albeit providing the state description for any type of channel rather than just for colour temperature ones. This probably goes beyond the scope of this issue, but worth thinking about it. => WDYT?

**Comment by lsiepel** [comment]
Have seen contributors struggle with similar but more common cases where temperature is used (fahrenheit vs celsius) and the min/max (and what about step) is not having a unit set. The state pattern is not usable in those cases as it usually is set to `%unit%`, the `unitHint` is in most cases set, but not always.

I'd like to have some @openhab/core-maintainers to join the discussion as this still feels a bit hackish. and maybe there are idea's from core on how to solve this.

**Comment by andrewfg** [comment]
Apropos UnitHint: It is currently implemented at the level of the ChannelType/StateChannelTypeBuilder and NOT at the level of StateDescription/StateDescriptionFragment/StateDescriptionFragmentBuilder. As we are here discussing the state description and various providers thereof, then unfortunately UnitHint seems to be located in the wrong place. Or??

**Comment by lolodomo** [comment]
> * Sony projector

The color temperature channel just allows choosing one of predefined color temperature. Choosing a precise temperature value is not relevant for this binding.
I guess it is the same for the Epson projector binding even if I have not verified.
Probably also for TV bindings.

**Comment by lolodomo** [comment]
> > And @lolodomo will handle the state description min/max values based on the unit provided in the state description pattern.
> 
> When doing decisions here, please don't think only of what BasicUI can do, but make sure the REST API response contains enough details to also make other clients work. I'm thinking of cases like min/max in Mirek in state description, item value in Kelvin and min/max specified without unit on the widget level. Since state description and item units can differ, it's not clear to me yet what unit to assume for the sitemap widget.

@maniac103 : I have not checked but I believe the item state description is part of the response, no ?
What we are discussing should absolutely not impact the current way to determine the unit of the widget. This must remain unchanged.
What we are discussing here is just how to determine the unit of min/max from the state description and the idea is to consider the unit in state description pattern.

**Comment by lolodomo** [comment]
> > Somewhat relevant to this discussion: [openhab/openhab-core#4079](https://github.com/openhab/openhab-core/pull/4079).
> 
> Indeed! The UnitHint would indeed be an alternate source for the UoM for the `state` `min`/`max` attributes, => @lolodomo WDYT?

The `UnitHint` is not there to define the unit of min/max, the only purpose of this parameter is to provide a hint to the UI so that it can propose to the user this unit as preferred unit.

**Comment by lolodomo** [comment]
> Have seen contributors struggle with similar but more common cases where temperature is used (fahrenheit vs celsius) and the min/max (and what about step) is not having a unit set. The state pattern is not usable in those cases as it usually is set to `%unit%`, the `unitHint` is in most cases set, but not always.

@andrewfg is going to set a proper unit (either "K" or "mired") in the state pattern of all absolute color temperature channel types. So the case with `%unit%` will never happen in practice for color temperature channels.

**Comment by holgerfriedrich** [comment]
I am wondering if this can be assured for all bindings. I am thinking of the ones creating channels dynamically or the ones from marketplace...

**Comment by lsiepel** [comment]
> > Have seen contributors struggle with similar but more common cases where temperature is used (fahrenheit vs celsius) and the min/max (and what about step) is not having a unit set. The state pattern is not usable in those cases as it usually is set to `%unit%`, the `unitHint` is in most cases set, but not always.
> 
> @andrewfg is going to set a proper unit (either "K" or "mired") in the state pattern of all absolute color temperature channel types. So the case with `%unit%` will never happen in practice for color temperature channels.

In that case I’m concerned we proceed with this and leave many other cases unsolved. I’d prefer a full solution for all min/max in all bindings. 
maybe it is as simple as adding an xml attribute next to min max step and `rangeUnit` solely used to describe the unit for the min max step?

**Comment by lolodomo** [comment]
> In that case I’m concerned we proceed with this and leave many other cases unsolved. I’d prefer a full solution for all min/max in all bindings.

This is something pending in core framework.:
https://github.com/openhab/openhab-core/pull/3132

> maybe it is as simple as adding an xml attribute next to min max step and `rangeUnit` solely used to describe the unit for the min max step?

Maybe a good idea. To be suggested for a general solution for the state des

**Comment by maniac103** [comment]
> maybe it is as simple as adding an xml attribute next to min max step and rangeUnit solely used to describe the unit for the min max step?

Or allow UoM for the min/max/step values.

**Comment by maniac103** [comment]
> I have not checked but I believe the item state description is part of the API response, no ?
What we are discussing should absolutely not impact the current way to determine the unit of the widget. This must remain unchanged.
What we are discussing here is just how to determine the unit of min/max from the state description and the idea is to consider the unit in state description pattern.

@lolodomo It does contain it, I'm just unsure how to mix'n'match the response values. For reference, here's a sitemap JSON response for a `Slider` widget bound to a (Hue) absolute color temperature channel:

```json
        {   
            "widgetId": "010102",
            "type": "Slider",
            "visibility": true,
            "label": "Decke Farbtemperatur abs [- K]",
            "labelSource": "SITEMAP_WIDGET",
            "icon": "colorlight",
            "staticIcon": false,
            "pattern": "%.0f K",
            "unit": "K",
            "mappings": [
                    
            ],      
            "switchSupport": false,
            "releaseOnly": false,
            "sendFrequency": 0,
            "minValue": 2000.0,
            "maxValue": 6000.0,
            "step": 100.0,
            "item": {
                "link": "http://<ip>:8080/rest/items/BathroomCeilingLightAbsColorTemperature1",
                "state": "NULL",
                "stateDescription": {
                    "minimum": 1000,
                    "maximum": 10000,
                    "pattern": "%.0f K",
                    "readOnly": false,
                    "options": [
            
                    ]
                },
                "unitSymbol": "K",
                "type": "Number:Temperature",
                "name": "BathroomCeilingLightAbsColorTemperature1",
                "label": "Farbtemperatur",
                "category": "ColorLight",
                "tags": [ 
                    "Control",
                    "ColorTemperature"
                ],
                "groupNames": [
                    "BathroomCeilingLight"
                ]
            },
            "widgets": [
            
            ]
        },
```

You see 2 sets of min/max values (widget vs. item), 2 patterns (I wasn't aware of a pattern in `Widget` so far, is this new?), 2 units (same, is this new?) and 2 states (widget as part of label vs. item combined of item state and item pattern).
From discussion here I gather it should be safe to apply item pattern to item `minimum` and `maximum` values, but is the same thing safe for `minValue` and `maxValue` as well? FWIW, the Android app currently does just that. This means that if the item pattern is given in Mirek (btw, @andrewfg the short unit is `MK⁻¹`, not `mirek`), either explicitly (`%.0f MK⁻¹`) or implicitly (`%.0f %unit%` with unit taken either from widget state [if present] or item state), sitemap widget specifications also would need to follow that unit.

Thinking about it, to make things simple from a user's POV and for ease of documentation, I'd prefer if we'd settle on Kelvin at least for state description. That way, specification of the sitemap element becomes free of surprises.

**Comment by andrewfg** [comment]
> adding an xml attribute next to min max step and rangeUnit solely used to describe the unit for the min max step

Yes. I think that would be a good way forward. A new attribute would not break any legacy code.

> allow UoM for the min/max/step values.

These xml attributes are of type "decimal" rather than "string". So adding a UoM to them would risk breaking a lot of legacy code.

**Comment by andrewfg** [comment]
> the short unit is MK⁻¹, not mirek

Two things:

- The unit named "mirek" (with 'k') is simply an informal abbreviation, and its official unit designation is MK⁻¹ 
- The unit named "mired" (with 'd') is derived in code from MK⁻¹ (see below), so its official unit designation is also MK⁻¹

Therefore for color temperature state descriptions there are just two allowed unit designations -- `K` or `MK⁻¹` -- and the **_designations `mired` resp. `mirek` are NOT allowed_**. => @lolodomo do you agree?

If so, the MQTT:EspMiLight code [here](https://github.com/openhab/openhab-addons/blob/abe819978feec579f26e94d9f4f4cff9b7ba3b76/bundles/org.openhab.binding.mqtt.espmilighthub/src/main/java/org/openhab/binding/mqtt/espmilighthub/internal/EspMilightStateDescriptionProvider.java#L64) is in fact wrong. And presumably the analog code in MQTT:HomeAssistant and MQTT:Homie is also wrong. => @ccutrer do you agree? And if so, would you like me to add such corrections to this PR?

```
Units.MIRED = MetricPrefix.MEGA(tech.units.indriya.unit.Units.KELVIN).inverse();
```

**Comment by lolodomo** [comment]
> Therefore for color temperature state descriptions there are just two allowed unit designations -- `K` or `MK⁻¹` -- and the **_designations `mired` resp. `mirek` are NOT allowed_**. => @lolodomo do you agree?

Our documentation is mentioning "mired" as symbol:
https://www.openhab.org/docs/concepts/units-of-measurement.html#list-of-units

My tests were done with unit=""mired" set on an item and I got no warning.
But I will check that it leads to Units.MIRED.

**Comment by lolodomo** [comment]
> MK⁻¹

With a simple basic editor, I am not sure how you enter such an exponent!

**Comment by andrewfg** [comment]
> log Units.MIRED.getSymbol()

It is confusing..

```
        for (Unit<?> unit : List.of(Units.KELVIN, MetricPrefix.MEGA(Units.KELVIN).inverse(), Units.MIRED)) {
            System.out.println("id=" + unit.toString());
            System.out.println("name=" + unit.getName());
            System.out.println("symbol=" + unit.getSymbol());
            System.out.println("baseUnits=" + unit.getBaseUnits());
            System.out.println();
        }

// ===
id=K
name=Kelvin
symbol=K
baseUnits=null

id=mired
name=null
symbol=null
baseUnits={MK=-1}

id=mired
name=null
symbol=null
baseUnits={MK=-1}
```

**Comment by andrewfg** [comment]
^
So, in summary, all of the following are Ok..

```
        QuantityType<?> a = QuantityType.valueOf("500 /MK");
        QuantityType<?> b = QuantityType.valueOf("500 mired");
        QuantityType<?> c = QuantityType.valueOf(500, Units.MIRED);
        QuantityType<?> d = QuantityType.valueOf(500, MetricPrefix.MEGA(Units.KELVIN).inverse());

        assertEquals(2000, a.toInvertibleUnit(Units.KELVIN).intValue());
        assertEquals(2000, b.toInvertibleUnit(Units.KELVIN).intValue());
        assertEquals(2000, c.toInvertibleUnit(Units.KELVIN).intValue());
        assertEquals(2000, d.toInvertibleUnit(Units.KELVIN).intValue());
```

**Comment by maniac103** [comment]
> So, in summary, all of the following are Ok..

That's good :+1: I went from [core code](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java#L191), but missed [this](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core/src/main/java/org/openhab/core/library/unit/Units.java#L296).

> With a simple basic editor, I am not sure how you enter such an exponent!

I copied Unicode characters out of a character table ;-)

**Comment by andrewfg** [comment]
> I copied Unicode characters out of a character table

Hmm. Two things:

- QuantityType.valueOf("500 MK\u207B\u00B9") throws an exception; => what unicode characters were you trying?
- QuantityType.valueOf("500 /MK") works fine!

**Comment by maniac103** [comment]
> QuantityType.valueOf("500 MK\u207B\u00B9") throws an exception; => what unicode characters were you trying?

I didn't actually try this in code.

> perhaps we should consider adding the following line here

That sounds like a good idea, since `MK⁻¹` is at least semi-official, while `mired` is our own invention.

**Comment by ccutrer** [comment]
While `mired` isn't an official SI unit, I wouldn't say it's our own invention. It's the unit [Home Assistant](https://www.home-assistant.io/integrations/light.mqtt/#max_mireds) uses. And I believe various Philips Hue integrations say `mired` instead of `mirek` or `MK⁻¹` (at least in their documentation, even if the actual field/argument/parameter in the API is called "color temperature".

**Comment by andrewfg** [comment]
^
Yeah. It's quite a common usage albeit not a formal one. I guess that one day it will go the same way as Degrees Rankin though..

**Comment by lolodomo** [comment]
@andrew: one improvement would be to set unit hint to color temperature channel types. I will try to add it to the system channel type. Can you have a look for channel types defined in bindings ?
Without unit hint, °C (or °F depending on your region) is proposed as unit for the new item which is of course inappropriate for a color temperature.

**Comment by andrewfg** [comment]
> set unit hint to color temperature channel types

Good idea. Will do.

**Comment by lolodomo** [comment]
I have updated your initial message in which you listed bindings that still requires investigation. I am sure that tradfri requires something for example. As explained, some ohter probably not (like Sony projector).

**Comment by andrewfg** [comment]
> sure that tradfri or Yeelight require something for example

Not necessarily. Some bindings have only a dimensionless CT setting in percent (Number:Dimensionless / Dimmer) or even a low/medium/high setting (Number 1/2/3 etc.) .. and as I recall the Ikea lights are indeed of that latter class.

However I will look again at all of them..

**Comment by lolodomo** [comment]
Same for Samsung TV binding, the channel is not a value in Kelvin or mirek.

**Comment by andrewfg** [comment]
Re-closing this issue since it is now tracked in #17754
