### ISSUE TITLE
[openweathermap] Initializing handler takes more than 5000ms

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17634]
While installing the last snapshot, I saw this warning:
```
Initializing handler for thing 'openweathermap:weather-and-forecast:api:local' takes more than 5000ms.
```
To be checked but generally this happens when the initialize() is doing stuff that can takes time like executing HTTP requests instead of creating a thread to run it.

**Comment by lsiepel** [comment]
It does some basic channel creation and removal. Might be better to do all that in a async task, but still nothing fancy.

**Comment by lolodomo** [comment]
It does not occur again, so let close the issue.
