### ISSUE TITLE
[evcc] Chargeplan changes on the app are not synced to openHAB

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#17645]
Just tested the jar and can confirm, that times are now send correctly to evcc. Thanks very much :)

Nevertheless if i edit chardplan time or target SOC in EVCC, the binding seems not to get the new values... But thats maybe another bug and not as important for me as i just want to send plans from OH to EVCC

_Originally posted by @tmsch13 in https://github.com/openhab/openhab-addons/issues/17620#issuecomment-2440889102_

**Comment by lsiepel** [comment]
@tmsch13 and @Laith-Budairi maybe we can continue here to look at this remaining issue. 

A debug log would be helpfull in addressing this issue.

**Comment by Laith-Budairi** [comment]
after an initial debug, I can see from the code that when the refresh method is called, it does not consider the most recent values for the vehicle plan from the API result, but from the vehiclePlans HashMap.

the vehiclePlans HashMap is only updated when you update the items from openHAB itself, but not from EVCC

![image](https://github.com/user-attachments/assets/15cc50f4-12f5-44df-819e-e03da170741e)


![image](https://github.com/user-attachments/assets/f7bb96f6-f8b1-42b1-b282-ee89d9bca380)
