### ISSUE TITLE
[IpObserver] Yearly Raining WS3500 Weather Station

### ISSUE THREAD

**Issue by ATNALDC** [openhab/openhab-addons#17658]
## Behavior
Since last firmware update on WS3500 weather station the yearlyrainin value is default set to -9999 but this value now comes in the totalrainin field.

## Possible Solution
Create a new channel called "Total Rain" to register totalrainin value

## Your Environment

* Version used: 4.2.2
* Operating System and version: Raspbian Buster
* Weather Station Sainlogic WS3500

**Comment by Skinah** [comment]
Can you post some logs or more info on what the data looks like?

**Comment by ATNALDC** [comment]
Hi Skinah,

This is the trace log:

`Update received:tempf=54.5&humidity=91&dewptf=52.0&windchillf=54.5&winddir=167&windspeedmph=0.22&windgustmph=1.12&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.571&yearlyrainin=-9999&totalrainin=17.732&solarradiation=29.92&UV=0&indoortempf=72.0&indoorhumidity=54&absbaromin=27.900&baromin=30.215&lowbatt=0&dateutc=now&softwaretype=EasyWeatherPro_V5.1.6&action=updateraw&realtime=1&rtfreq=5`

As you can see the parameter yearlyrainin is set by default to -9999 and the totalrainin corresponds to the yearlyrain

Other thing I've seen is that in IpObserverHandler, in setupServerChannels function, the createChannelHandler for Absolute Pressure is missing. Than could be the reason why this channel doesn't updates.

Thank you very much;
Kind regards,

**Comment by lsiepel** [comment]
Are you aware of some release notes or changelog? As this seems a breaking change on the firmware side.

**Comment by ATNALDC** [comment]
I've seen that since yesterday there is a new firmware release but nothing seems to be changed. The notes doesn't especify nothing but "fix some bugs". 

The data format is still the same:

`Update received:tempf=58.6&humidity=76&dewptf=51.1&windchillf=58.6&winddir=163&windspeedmph=0.45&windgustmph=1.12&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.571&yearlyrainin=-9999&totalrainin=17.732&solarradiation=116.71&UV=1&indoortempf=72.1&indoorhumidity=55&absbaromin=27.965&baromin=30.280&lowbatt=0&dateutc=now&softwaretype=EasyWeatherPro_V5.1.7&action=updateraw&realtime=1&rtfreq=5
`

**Comment by lsiepel** [comment]
Test jar openHAB 4.2.x+: https://1drv.ms/u/s!AnMcxmvEeupwj4t1vX2gRaW7_nbaRA?e=kyJilR

1.  Make sure you have openHAB 4.2.x or 4.3.0
1. Uninstall the current binding (all things, channels and configuration remains available)
1. Drop the jar into your addon folder.
1. Observe the new behavior and please report your results.

**Comment by ATNALDC** [comment]
I've added the jsoup as addon too.

It seems that it recognizes the value of total rain, but doesn't updates the channel. Linked item remains as null. 

`10:58:49.871 [DEBUG] [ver.internal.IpObserverUpdateReceiver] - Weather station packet received from 192.168.1.46
10:58:49.876 [TRACE] [ipobserver.internal.IpObserverHandler] - Update received:tempf=57.7&humidity=75&dewptf=49.8&windchillf=57.7&winddir=207&windspeedmph=1.12&windgustmph=1.12&rainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.571&yearlyrainin=-9999&totalrainin=17.732&solarradiation=244.54&UV=2&indoortempf=72.1&indoorhumidity=52&absbaromin=27.968&baromin=30.283&lowbatt=0&dateutc=now&softwaretype=EasyWeatherPro_V5.1.7&action=updateraw&realtime=1&rtfreq=5
10:58:49.886 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element tempf, value is 57.7
10:58:49.896 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element totalrainin, value is 17.732
10:58:49.903 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element indoorhumidity, value is 52
10:58:49.908 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element windchillf, value is 57.7
10:58:49.913 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element monthlyrainin, value is 0.571
10:58:49.917 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element dailyrainin, value is 0.000
10:58:49.923 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element solarradiation, value is 244.54
10:58:49.937 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element softwaretype, value is EasyWeatherPro_V5.1.7
10:58:49.943 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element lowbatt, value is 0
10:58:49.946 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element humidity, value is 75
10:58:49.949 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element action, value is updateraw
10:58:49.952 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element UV, value is 2
10:58:49.955 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element rtfreq, value is 5
10:58:49.958 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element windspeedmph, value is 1.12
10:58:49.961 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element realtime, value is 1
10:58:49.964 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element yearlyrainin, value is -9999
10:58:49.967 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element dewptf, value is 49.8
10:58:49.969 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element rainin, value is 0.000
10:58:49.973 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element winddir, value is 207
10:58:49.980 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element windgustmph, value is 1.12
10:58:49.985 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element dateutc, value is now
10:58:49.988 [TRACE] [ipobserver.internal.IpObserverHandler] - UNKNOWN element absbaromin, value is 27.968
10:58:49.990 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element baromin, value is 30.283
10:58:49.997 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element indoortempf, value is 72.1
10:58:50.009 [TRACE] [ipobserver.internal.IpObserverHandler] - Found element weeklyrainin, value is 0.000
`
Thanks

**Comment by Skinah** [comment]
Pore some water in to make the value change, does it update then?

**Comment by ATNALDC** [comment]
Thanks!,

Now it seems to work!! 

Another issue i found is that in IpObserverHandler, in setupServerChannels function, the createChannelHandler for Absolute Pressure is missing. That could be the reason why this channel doesn't updates.

**Comment by lsiepel** [comment]
Updated the JAR with the fix for absbaromin please check if that is fixed.

**Comment by lsiepel** [comment]
> Thanks!,
> 
> Now it seems to work!!
> 
> Another issue i found is that in IpObserverHandler, in setupServerChannels function, the createChannelHandler for Absolute Pressure is missing. That could be the reason why this channel doesn't updates.

Check the linked issue to continue on the absolute pressure, might already be fixed there.

**Comment by ATNALDC** [comment]
Both issues where solved
