### ISSUE TITLE
JSR223/Groovy “unable to resolve class org.openhab.binding.mqtt.internal.action.MQTTActions” with 4.3.0.M2

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#17683]
With OH 4.2.2 this automation/jsr223/z.groovy file
```groovy
var org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger("org.openhab.core.model.script.rele1")
var mqtt_broker = actions.get("mqtt", "mqtt:broker:b1")

logger.info('A')
logger.info(mqtt_broker.toString())
```
does work and prints:

> 2024-10-08 15:06:41.346 [INFO ] [ort.loader.AbstractScriptFileWatcher] - (Re-)Loading script '/etc/openhab/automation/jsr223/z.groovy'
> 2024-10-08 15:06:41.411 [INFO ] [org.openhab.core.model.script.rele1 ] - A
> 2024-10-08 15:06:41.421 [INFO ] [org.openhab.core.model.script.rele1 ] - org.openhab.binding.mqtt.internal.action.MQTTActions@12788b8

With OH 4.3.0.M2 it logs

> 2024-10-08 15:11:43.819 [INFO ] [ort.loader.AbstractScriptFileWatcher] - (Re-)Loading script '/etc/openhab/automation/jsr223/z.groovy'
> 2024-10-08 15:11:43.901 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script '/etc/openhab/automation/jsr223/z.groovy': org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
> /etc/openhab/automation/jsr223/z.groovy: -1: unable to resolve class org.openhab.binding.mqtt.internal.action.MQTTActions
> @ line -1, column -1.
> /etc/openhab/automation/jsr223/z.groovy: -1: unable to resolve class org.openhab.binding.network.internal.action.NetworkActions
> @ line -1, column -1.
> 2 errors
>
> 2024-10-08 15:11:43.903 [WARN ] [ort.loader.AbstractScriptFileWatcher] - Script loading error, ignoring file '/etc/openhab/automation/jsr223/z.groovy'

I do not know, if this is problem in JSR223/Automation or with Groovy.

**Comment by MikeJMajor** [comment]
@openhab/add-ons-maintainers are there plans to fix this or revert the change that caused it before the 4.3 release?

I'm assuming this is the same issue that stops all my rules which use Groovy from initialising. 4.3 looks unusable at the moment for anyone using Groovy scripts.

**Comment by MikeJMajor** [comment]
![Screenshot_20241121-200102](https://github.com/user-attachments/assets/26c8c4e2-c958-48f2-b215-f5fbcf94e2f3)
![Screenshot_20241121-200130](https://github.com/user-attachments/assets/515074f9-fd91-4c5a-a515-b5b90879d538)

**Comment by wborn** [comment]
Do you use .things files?
I noticed that if I don't use the .things files so far the issue doesn't occur.
It also seems to have no issues when I start without .things files and then add them after startup.

**Comment by MikeJMajor** [comment]
No I don't use .things files.

Just looking now after starting my test system (rpi 2), all my rules which use Groovy scripts except one were in the error state. The one working one went into the error state after I disabled/enabled it.

Tried clearing the cache which result in all rules being green and idle, but they don't look like they have run properly since some bits of my system are left uninitialised. Following another restart all the rules are in the error state except for one, but a different one than previously.

I have about 38 UI defined rules which use Groovy and 1 script in the transform directory.

**Comment by MikeJMajor** [comment]
This scripts:

```
import org.openhab.core.library.types.OnOffType;

if (ir.getItem("houseOccupied").getState().equals(OnOffType.OFF) ||
    ir.getItem("sleeping").getState().equals(OnOffType.ON)) {
  events.sendCommand("kitchenCamera", OnOffType.ON.toString());
} else {
  events.sendCommand("kitchenCamera", OnOffType.OFF.toString());
}
```

Fails with:

```
Failed to pre-compile action: 3(org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: Script44.groovy: -1: unable to resolve class org.openhab.binding.tplinksmarthome.internal.handler.TPLinkSmartHomeActions @ line -1, column -1. Script44.groovy: -1: unable to resolve class org.openhab.binding.astro.internal.action.AstroActions @ line -1, column -1. Script44.groovy: -1: unable to resolve class org.openhab.binding.network.internal.action.NetworkActions @ line -1, column -1. 3 errors )
```

**Comment by dilyanpalauzov** [comment]
I use .things files.

**Comment by MikeJMajor** [comment]
@wborn do you need any further details to help fix this?

**Comment by wborn** [comment]
I will have another look this weekend.

**Comment by wborn** [comment]
I figured out what is happening so I created #17860 so it should work again while also being able to use #17383.
