### ISSUE TITLE
[verisure] Bridge cannot login

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#17730]
Bridge cannot login, log contains:

2024-10-21 22:12:47.395 [WARN ] [ng.verisure.internal.VerisureSession] - Failed to login org.eclipse.jetty.client.HttpResponseException: Max redirects exceeded 8

Verisure API must have changed.
I'm working on a fix.

**Comment by lsiepel** [comment]
The patch label was not added on purpose?

**Comment by jlaur** [comment]
> The patch label was not added on purpose?

It was added on the merged PR after cherry-picking the commit into 4.2.x.

**Comment by lsiepel** [comment]
> > The patch label was not added on purpose?
> 
> It was added on the merged PR after cherry-picking the commit into 4.2.x.

I thought we leave the 4.2.x unlabeled and have the PR against main labeled as patched. Would be more clear to me. Als wonder what the effects are on the release notes generating

**Comment by jlaur** [comment]
> I thought we leave the 4.2.x unlabeled and have the PR against main labeled as patched. Would be more clear to me. Als wonder what the effects are on the release notes generating 

Exactly. There was no PR targeting 4.2.x, only main. And that PR has the patch label. Did I miss something?

**Comment by lsiepel** [comment]
> > I thought we leave the 4.2.x unlabeled and have the PR against main labeled as patched. Would be more clear to me. Als wonder what the effects are on the release notes generating
> 
> Exactly. There was no PR targeting 4.2.x, only main. And that PR has the patch label. Did I miss something?

No, it is as expected. My bad, i watched the labels in the issue not the pr.
