### ISSUE TITLE
[ipobserver] Absolute Pressure is missing

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#17735]
Another issue i found is that in IpObserverHandler, in setupServerChannels function, the createChannelHandler for Absolute Pressure is missing. That could be the reason why this channel doesn't updates.

_Originally posted by @ATNALDC in https://github.com/openhab/openhab-addons/issues/17658#issuecomment-2467857260_

**Comment by lsiepel** [comment]
@ATNALDC

Updated the JAR with the fix for absbaromin please check if that is fixed.

Test jar openHAB 4.2.x+: https://1drv.ms/u/s!AnMcxmvEeupwj4t1vX2gRaW7_nbaRA?e=kyJilR

1. Make sure you have openHAB 4.2.x or 4.3.0
2. Uninstall the current binding (all things, channels and configuration remains available)
3. Drop the jar into your addon folder.
4. Observe the new behavior and please report your results.

**Comment by ATNALDC** [comment]
Fixed! Thanks!
