### ISSUE TITLE
[onkyo] Audio sink does not play any sounds on TX-NR646

### ISSUE THREAD

**Issue by druciak** [openhab/openhab-addons#17755]
## Expected Behavior
After setting the receiver thing as default audio sink it should be possible to play sounds from CLI:
```
openhab> openhab:audio play doorbell.mp3
```

## Current Behavior
There is no sound coming out of the receiver speakers after issuing `openhab:audio play` commands.
After enabling `TRACE` level it looks that the binding sends proper commands to the receiver, but nothing happens.

## Possible Solution
It turned out, that the binding sends "SetAVTransportURI" action with empty "CurrentURIMetaData" element in request body.
Tested other UPnP players (BubbleUPnP, Windows Media Player) send this action with filled "CurrentURIMetaData" element and the receiver plays any media without problems. It seems that at least some of Onkyo receivers (including TX-NR646) require this field to play media streams. After several exepriments it looks like required element is "res" with "protocolInfo" attribute.

## Steps to Reproduce (for Bugs)

1. Install Onkyo binding
2. Configure "Callback URL" parameter in the binding configuration
4. Discover your receiver and add new thing
5. Set it as default audio sink in "Sounds" configuration
7. Login to the console
8. Enter `openhab:audio play doorbell.mp3`
9. Nothing happens

## Your Environment

* Official docker image 4.2.2
* Java 17
* Onkyo TX-NR646 receiver with latest possible firmware

Relevant discussion is [here](https://community.openhab.org/t/using-onkyo-as-audio-sink/29946/16).

**Comment by lsiepel** [comment]
As you seem to have debugged this extensively and figured out what xml needs to be send, are you creating a PR?

**Comment by druciak** [comment]
Yes, I will create a PR soon. I'd like to make few tests more.
