### ISSUE TITLE
[solax] Total Consumption is off by one decimal Point

### ISSUE THREAD

**Issue by Andre1Becker** [openhab/openhab-addons#17765]
## Expected Behavior
Item/channel value is off by a decimal point
Should be f.e. 165.84 but Shows 1658.4
Channel: Inverter_Total_Consumption

## Steps to Reproduce (for Bugs)

Well, the Smart meter that is connected to the inverter (X3_HYBRID_G4) is a Chint DTSU666.
But I don't know if anybody could reproduce this...

## Your Environment

Im using openHAB Docker Ver. 4.2.2
javaVersion: 17.0.12

Raw Data:

`{"sn":"MASKED","ver":"3.015.02","type":14,"Data":[2381,2374,2366,12,12,12,159,162,152,473,0,0,0,0,0,0,4994,4993,4993,2,0,0,0,0,0,0,0,0,0,0,0,0,0,1,41,0,0,0,0,31450,65366,64971,3143,65518,64971,1,46,432,256,283,4629,6155,100,0,34,0,0,0,0,0,0,0,0,0,0,0,0,0,1351,0,181,10,0,0,368,0,454,0,51,94,1500,0,236,0,0,0,1727,0,16584,0,423,0,491,0,0,0,0,0,0,0,0,0,1,52,1,31,48,256,3504,2400,300,300,265,250,33,33,5,1620,780,16448,16448,16448,0,0,0,3277,3274,43880,1,20564,12339,18753,12355,16697,12868,13361,20564,12339,19266,12855,16697,12359,14391,20564,12339,19266,12855,16692,12359,13363,20564,12339,19266,12855,16697,12359,13367,0,0,0,0,0,0,0,258,257,769,1539,0,31450,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"Information":[15.000,14,"MASKED",8,1.30,0.00,1.29,1.09,0.00,1`

**Comment by lsiepel** [comment]
Could this already be fixed by https://github.com/openhab/openhab-addons/pull/17726 

You could upgrade to the latest snapshot to verify.

**Comment by Andre1Becker** [comment]
Hey @lsiepel : Thanks for the quick reply! That fixed the issue indeed! i used this version for future reference: [org.openhab.binding.solax-4.3.0-20241114.032510-87.jar](https://openhab.jfrog.io/artifactory/libs-snapshot/org/openhab/addons/bundles/org.openhab.binding.solax/4.3.0-SNAPSHOT/org.openhab.binding.solax-4.3.0-20241114.032510-87.jar)

**Comment by Andre1Becker** [comment]
Hey @lsiepel : Thanks for the quick reply! That fixed the issue indeed! i used this version for future reference: [org.openhab.binding.solax-4.3.0-20241114.032510-87.jar](https://openhab.jfrog.io/artifactory/libs-snapshot/org/openhab/addons/bundles/org.openhab.binding.solax/4.3.0-SNAPSHOT/org.openhab.binding.solax-4.3.0-20241114.032510-87.jar)

**Comment by Andre1Becker** [comment]
Well after testing this binding, openHAB is getting unresponsive after 4-5 hours. There is a memory leak. The container uses 98% CPU and consumes double amount of Memory than normal. After removing the snapshot version, restarting and install the marketplace binding, everything is back to normal.

**Comment by lsiepel** [comment]
> Well after testing this binding, openHAB is getting unresponsive after 4-5 hours. There seems to be a memory leak. The container uses 98% CPU and consumes double the amount of memory than normal. After removing the snapshot version, restarting and install the marketplace binding, everything is back to normal.
> 
> Should I open another issue for this problem?

Yes please, also provide a list of installed bundled if not 100% sure it is this binding
