### ISSUE TITLE
Discussion: Hue Emulation and Hue API V2

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17762]
For discussion: does Hue Emulation need to be rewritten using Hue API V2? (I believe it is currently based on API V1 which may no longer be supported..)

https://community.openhab.org/t/hue-emulator-alexa-app-only-displays-one-light/159556/14

**Comment by andrewfg** [comment]
@davidgraeff @digitaldan => any thoughts?

**Comment by jlaur** [comment]
Hue API v2 support would be nice. However, at the same time it's also important to keep support for Hue API v1. For the Hue emulation it doesn't matter how long API v1 will be supported by Signify, the only thing that matters is how long third party integrations will support it. As an example, Logitech Harmony will only ever support Hue API v1.

**Comment by andrewfg** [comment]
> only thing that matters is how long third party integrations will support it

Indeed. Good point. But I suppose that if/when Signify does drop it then the third parties must immediately switch to V2 anyway.

> it's also important to keep support for Hue API v1

Ok. Understood. But it seems from the referenced community thread that the V1 emulation is, was, or has become broken. And apparently there were no recent breaking changes on the OH side. (??) So presumably this break is something on the third party side. This means that someone here needs to commit to active further development of the V1 emulation to match changes on the the third party side. => Any volunteers? ;)

**Comment by lolodomo** [comment]
I believe noone is really maintaining the hue emulation binding since years.

**Comment by andrewfg** [comment]
@digitaldan many thanks for the feedback. As mentioned in the community forum thread above, it seems that some uses have an issue when trying to link OH items into Alexa via this Hue Emulation, and I am trying to find the way forward to fix that. I think the summary of the posters here so far are saying not to mess with this integration too much, and basically to focus on maintenance fixes only. So I am trying to find out who we can 'volunteer' to do that work.

**Comment by MikeJMajor** [comment]
I've been patching up the hue emulator over the years to keep it working with Alexa.

I'll volunteer since trying to reproduce the issue has messed up my working Alexa setup.

**Comment by andrewfg** [comment]
Many thanks to @MikeJMajor for fixing the bug.

I think this means that there is no need to migrate the emulation to API v2. When Philips / Signify finally drops support for v1 this will force the third party integrators to drop v1, and switch to another integration pathway. Most probably this will be Matter rather than them having to support multiple new pathways. And I suppose -- therefore -- that Philips / Signify will not drop support for v1 until their Matter implementation is fully working. (Which currently is definitely not the case..)

**Comment by lolodomo** [comment]
> that Philips / Signify will not drop support for v1 until their Matter implementation is fully working. (Which currently is definitely not the case..)

By curiosity, what is not working with Matter ?

**Comment by andrewfg** [comment]
> what is not working with Matter ?

If you look at the Hue developer forum there are still quite a few people complaining about issues. To sum up in a few words, it is probably a) stability issues, and b) interworking issues between different Matter platforms (I would say that the Matter "standard" is not completely standard yet, and different manufacturers are not (yet) fully aligned.
