### ISSUE TITLE
[solax] Possible memory / cpu leak issue with snapshot 4.3.0-20241114.032510-87

### ISSUE THREAD

**Issue by Andre1Becker** [openhab/openhab-addons#17771]
## Current Behavior
Because of [Fix the parsing of total consumption channel](https://github.com/openhab/openhab-addons/pull/17726) i've installed the [snapshot version of this binding](https://community.openhab.org/t/solax-binding/146326/228). Memory Usages creeps up from 2.3 GB to around 9 GB and CPU goes up to 98%ish of that container

I removed the Marketplace binding (Ver, 4.2.2) and copied the jar to the addons folder and restarted the docker container. After that it takes roughly 4-5 hours till openHAB becomes unresponsive. 
Removing the jar and installing the Marketplace addon, everything is working normal again.

I could reproduce this issue, but i cloud not troubleshoot it any further because lack of skills ;-) i cloud not see anything suspicious in the openhab logs regarding this problem.

Running openHAB Docker container 4.2.2 on unraid 6.12.13 with an Intel Core i5-6500 CPU @ 3.20GHz and 32 GB of RAM.

**Comment by Andre1Becker** [comment]
I just noticed this myself: I'm using oh 4.2.2 with a 4.3.0.x binding. Maybe that's causing the problem?

**Comment by lsiepel** [comment]
> I just noticed this myself: I'm using oh 4.2.2 with a 4.3.0.x binding. Maybe that's causing the problem?

I would not expect that to be the cause. You could upgrade to the latest snapshot for both openHAB and the binding.

**Comment by Andre1Becker** [comment]
That's not that easy because this is my "production" setup :-)

**Comment by lsiepel** [comment]
Let's do some other checks before we try something like that.

**Comment by lsiepel** [comment]
Had a quick look and did not find anything directly pointing towards a leak. 
I did notice that the refresh command is calling an async update of _all_ data causing a remote api call.

If you have many channels linked, this might cause some DDOS-like actions towards the remote API. Not 100% iuf this is the cause, but this can be improved.

There are some karaf commands that you could use to minitor threads:
`shell:threads | grep -i runnable | wc -l`

**Comment by Andre1Becker** [comment]
Hey,
no - stock version runs fine. I've just switched to the snapshot binding and try to look into it a bit further. i try to monitor the threads as you mentioned. Anything else i could do?

**Comment by Andre1Becker** [comment]
Well, after switching it back to the snapshot version, everything is running fine...
I'm really sorry for any inconvenience - I don't know what was going on back then.
I will closed this issue now.
