### ISSUE TITLE
[linky] Binding again unavailable

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17773]
![image](https://github.com/user-attachments/assets/7b6d4f1d-1030-4fc2-a0a5-0b1139e69afe)

@clinique @lo92fr for information

**Comment by lo92fr** [comment]
Hello lolodomo,

Do you see my message this morning ?
The url have changed since last week.

Laurent.

**Comment by clinique** [comment]
Can you direct me to the appropriate modification so I make yet another patch ?

**Comment by lo92fr** [comment]
Yes, of course.
This is this commit : https://github.com/openhab/openhab-addons/pull/16355/commits/d273eefc292bb4b8fc516b5d8da170eb6e1808e6.
Only change the URL, the response is the same as before.

Laurent.
