### ISSUE TITLE
Bindings with several classes with the same thing action scope

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17785]
It is not allowed to have several classes with the same thing action scope.
Here are the bindings not respecting this rule:

- [ ] caddx
- [ ] deconz
- [ ] freeboxos
- [ ] hue
- [ ] openwebnet

**Comment by clinique** [comment]
I assume the correct way is like it is done in `max` for example ? "`max-cube`", "`max-device`"... ?
Will provide a fix for `freeboxos`

**Comment by clinique** [comment]
Well @lolodomo , while I was on it I did it all.

**Comment by lolodomo** [comment]
Note that changing the scope is a breaking change for users.

For hue binding for example, I believe one is for API v1 and the other for API v2. @andrewfg  can you please confirm.
We could then decide to not change the scope for the second and only change the scope of the first. Users of API v1 are now probably less than API v2.

**Comment by lolodomo** [comment]
@clinique : bindings README should be updated as the new scope has to be mentioned for each action.

**Comment by clinique** [comment]
This seems a bit counter-intuitive, I thought getActions was defined: 
`getActions(String bindingId, String thingUid)`

but it's
`getActions(String scope, String thingUid)`

It's fine when there's only one action class that can define `scope` = `bindingID`

then for Caddx it would give:
`val actions = getActions("caddx-zone","caddx:zone:thebridge:zone4")`

correct ?

**Comment by lolodomo** [comment]
Yes, that's my understanding.

**Comment by lolodomo** [comment]
Please make a test with freeboxos binding for example to confirm.

**Comment by lolodomo** [comment]
> It is not allowed to have several classes with the same thing action scope.

This information is coming from @J-N-K . Please comment and confirm to avoid marking useless changes.

**Comment by andrewfg** [comment]
> I believe one is for API v1 and the other for API v2. @andrewfg can you please confirm

Yes. I think that is the case. I agree that if we should 'break' something, it should be rather in v1 than v2. But let me check in detail tomorrow..

**Comment by lolodomo** [comment]
> I use rebootPlayer and rebootServer in Freeboxos, thus they had the same some and it used to work fine.

That's a good reason I would like to have first a GO from @J-N-K before applying these changes.

**Comment by lolodomo** [comment]
For information, the only binding currently using different scopes is the max binding.

**Comment by lsiepel** [comment]
Slighlty offtopic; i'm implementing some actions for the telegram binding and want to use an array as parameter. It's not working, might be something different. But the question is if i can find some documentation on allowed/supported parameters.

The method with this signature does not show up in main UI (4.3.0M4) as other methods do.
```
    @RuleAction(label = "send a test message", description = "Send a Telegram using the Telegram API.")
    public @ActionOutput(label = "Success", type = "java.lang.Boolean") boolean sendTelegramTo(
            @ActionInput(name = "chatIds") @Nullable Long @Nullable [] chatIds,
            @ActionInput(name = "message") @Nullable String message,
            @ActionInput(name = "replyMessageId") @Nullable Integer replyMessageId,
            @ActionInput(name = "silent") @Nullable Boolean silent,
            @ActionInput(name = "messageThreadId") @Nullable Integer messageThreadId,
            @ActionInput(name = "args") @Nullable Object... args) {
```

**Comment by lolodomo** [comment]
The type of your parameters chatIds and args are not supported by Main UI.

The supported types are listed in this PR:
https://github.com/openhab/openhab-core/pull/4392

String, boolean, Boolean, byte, Byte, short, Short, int, Integer, long, Long, float, Float, double, Double, Number, DecimalType, QuantityType<?>, LocalDateTime, LocalDate, LocalTime, ZonedDateTime, Date, Instant and Duration

Ps how a variable list of java Object could be...

**Comment by Nadahar** [comment]
I'm confused about the `@ThingActionsScope`. I need different Actions for different Thing-Types, so as far as I can understand, that means using different `ThingActions` implementations and "bind" them to the different thing-type handlers. It requires different scopes from what I understand, but as soon as I change the scope from being just "bindingid" to "bindingid-xxx", the Actions stop working from MainUI. They show up, but when you try to execute them, the UI just "hangs" with "Executing..." and the actual Action method is never called.

The documentation merely states
```java
@ThingActionsScope(name = "mqtt") // Your bindings id is usually the scope
```

I'm lost - I can't get it to work.

**Comment by lolodomo** [comment]
In fact we are all a little confused, it is still not so clear. I hoped we could discuss with @J-N-K but he does not answer.

Regarding run of action from Main UI, it might be that you need to reload Main UI or maybe a bug in Main UI ?
Use API Explorer from Main UI and request all thing actions from your thing and see what scope is returned for each action.

![image](https://github.com/user-attachments/assets/8813d66c-1bb1-41af-8d22-22fc83752c36)

**Comment by Nadahar** [comment]
> Do we allow the "-"
I've tried with "." and ":" too - same result.

**Comment by lolodomo** [comment]
I believe the problem is here in the REST API, you do not accept a "-" in the first part of the action id:

https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.rest/src/main/java/org/openhab/core/automation/rest/internal/ThingActionsResource.java#L222

**Comment by Nadahar** [comment]
I can't see any information about scope at all when running `/actions/{thingUID}
` from the API Explorer.

**Comment by lolodomo** [comment]
Try using bindingidxxx instead of bindingid-xxx just to confirm my hypothesis.

**Comment by lolodomo** [comment]
actionid in the REST API is scope followed by a "." and followed by the method name.

**Comment by Nadahar** [comment]
> Try using bindingidxxx instead of bindingid-xxx just to confirm my hypothesis.

That works 👍 

It's kind of "messy" to not have any separator at all though, so something should probably be changed. And the documentation must definitely explain how to use the scope much better.

**Comment by lolodomo** [comment]
As you can see with this issue, this is something new and we have to fix it.
We have only one binding in the official distribution using something else than the binding id as scope, the max binding.
And calling actions from REST API and Main UI is something rrecent, to not say very recent.

So as soon as we are all sure that bindingid cannot be used for different action classes, we will have to fix the REST API also.

**Comment by florian-h05** [comment]
> It is not allowed to have several classes with the same thing action scope.

I rather think that it is not allowed for a single ThingType to have multiple action classes in the same scope. A binding may habe multiple action class for different ThingTypes.

**Comment by J-N-K** [comment]
@florian-h05 Correct. In fact the restriction is "one action class with the same scope per THING", not per `ThingType`. The key is build from the thing UID and the scope. In principle it could be that the `ThingHandler` selects from several action classes with the same scope and return only one in `getServices` but I believe there are not many use-cases for that and the risk of failure is high. So "one action class with the same scope per thing-type" seems like a good policy.

**Comment by florian-h05** [comment]
Thanks for the feedback.
I am already working on improving the developer docs for Thing actions, I will make sure to put that in there.

**Comment by florian-h05** [comment]
>  In principle it could be that the ThingHandler selects from several action classes with the same scope and return only one in getServices but I believe there are not many use-cases for that and the risk of failure is high.

That would also make using Thing actions from scripts very difficult, as the user would have to check which ThingActions implementation is returned.

**Comment by J-N-K** [comment]
The use-case I can imagine is that a `ThingHandler` is implemented for a generic thing type (e.g. `binding:actuator`) and the available channels for the specific device are created dynamically t runtime. The available actions could also depend on the specific device, the developer could create separate `ThingActions` implementations for each device and the `ThingHandler` selects and returns the only correct one. The user knows what device he has, so the available actions could be retrieved from the documentation, but he could always use the same scope (e.g. the binding id).

**Comment by lolodomo** [comment]
Thank you @J-N-K for clarification.

If we want to allow bindingname-xxx as scope, we should update the REST API to allow the "-" character. Until that, actions from the max binding are certainly not runnable from REST API.

**Comment by lolodomo** [comment]
Using bindingname-xxx is 'ow possible.

**Comment by Nadahar** [comment]
Will this be from `4.3.0` onwards?

**Comment by lolodomo** [comment]
Yes.
https://github.com/openhab/openhab-core/pull/4495
