### ISSUE TITLE
[miio] Add support for Xiaomi Robot Vacuum X20+

### ISSUE THREAD

**Issue by darkestDark** [openhab/openhab-addons#17796]
Attached the needed files from test channel.
Device only works with cloud connection (stays offline with direct connection).
Thanks!

[test-xiaomi.vacuum.c102gl-20241123-155547.txt](https://github.com/user-attachments/files/17880187/test-xiaomi.vacuum.c102gl-20241123-155547.txt)
[xiaomi.vacuum.c102gl-miot-experimental.json](https://github.com/user-attachments/files/17880188/xiaomi.vacuum.c102gl-miot-experimental.json)

**Comment by darkestDark** [comment]
@marcelrv 
If you are busy, i could write the pr and you would only have to review it.

**Comment by darkestDark** [comment]
.

**Comment by darkestDark** [comment]
@marcelrv 
If you are busy i could write the pr to be reviewed.

**Comment by marcelrv** [comment]
let me fix it right now
