### ISSUE TITLE
[govee] Govee H7070 Support

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#17900]
I have Govee H7070 projectors which show in OH.  Right now I only get 2 channels, I'm sure there are a ton more.  What information do you need me to provide so we can get them added with all the channels they can support?

**Comment by andrewfg** [comment]
I am guessing it shows actually THREE channels:

- color
- color-temperature
- color-temperature-abs (you need to check the 'show advanced' checkbox)

> sure there are a ton more

For example what do you expect?

> What information do you need me to provide

I am pretty sue that a trace log from the current stable binding might tell us something. (But a trace log from #17812 will probably tell us more..)

**Comment by stefan-hoehn** [comment]
@andrewfg Can you add a * to the H7070 in the docs while working on #17812? 🙏🏻

**Comment by andrewfg** [comment]
.. already done :) .. but not yet committed.


Regards,
Andrew Fiddian-Green

**Comment by morph166955** [comment]
My hope would be more channels I guess.  Even something basic like on/off.  I'm very new to govee, these are my first of their products and I like them so far.  The app has so many options for configuration I assumed I could do that with the local API also.

**Comment by andrewfg** [comment]
> My hope would be more channels I guess.

If you run the binding with logging, we might see indications of other potential channels in the device status telegrams.

> Even something basic like on/off.

Color channels can accept three types of input controls — namely Color selector (HSBType), Dimmer (PercentType), and Switch (OnOffType). So you can link an item of each of those three control types to the one Color channels, and you will get the functionality you would expect from the respective control. (This is OH standard practice for all bindings having Color channels).

**Comment by stefan-hoehn** [comment]
@morph166955 unfortunately this is due to the nature of their [LAN API](https://app-h5.govee.com/user-manual/wlan-guide) which is very limited. There is a [cloud API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf) which surprisingly even doesn't offer more. I am not 100% sure but I think that what the App does might go over bluetooth only but at least nothing has been disclosed of what the App can do compared what the LAN-API supports.

**Comment by andrewfg** [comment]
> My hope would be more channels I guess.

@morph166955 do `log:set TRACE` and look at the logs. You will see some JSON as follows. If you see more fields than `onOff`, `brightness`, `color`, and `colorTemInKelvin`, that would be evidence of more possible channels. But if not then you are out of luck I am afraid.

```
{
	"msg": {
		"cmd": "devStatus",
		"data": {
			"onOff": 1,
			"brightness": 82,
			"color": {
				"r": 0,
				"g": 0,
				"b": 0
			},
			"colorTemInKelvin": 2200
		}
	}
}
```

**Comment by morph166955** [comment]
Is this what you're looking for?

2024-12-22 16:23:36.159 [TRACE] [.govee.internal.CommunicationManager] - Received response from XXXXXX with content = {"msg":{"cmd":"devStatus","data":{"onOff":1,"brightness":100,"color":{"r":0,"g":0,"b":0},"colorTemInKelvin
":2000}}}

**Comment by andrewfg** [comment]
^
Yup. Thanks. Unfortunately it shows no evidence of new data that would lead to new channels.

**Comment by andrewfg** [comment]
Request cannot be fulfilled in current binding.
