### ISSUE TITLE
Are we sure that all bindings accept properly a value in Kelvin and a value in mirek as command?

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#17917]
@andrewfg : I have a doubt, are we sure that all bindings accept properly a value in Kelvin and a value in mirek as command?

_Originally posted by @lolodomo in https://github.com/openhab/openhab-core/issues/3891#issuecomment-2546145215_

**Comment by andrewfg** [comment]
#### AmazonEchoControl => Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/smarthome/HandlerColorTemperatureController.java#L130

#### AVMFritz => Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseThingHandler.java#L547

#### Bluetooth => TBD

TBD

#### Dali => Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.dali/src/main/java/org/openhab/binding/dali/internal/handler/DaliDt8DeviceHandler.java#L72

#### Deconz = Not Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/LightThingHandler.java#L247

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/GroupThingHandler.java#L141

#### Govee => See #17812

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.govee/src/main/java/org/openhab/binding/govee/internal/GoveeHandler.java#L183

#### Hue => Ok (albeit bad code)

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/api/dto/clip2/helper/Setters.java#L101

#### Lifx => Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/handler/LifxLightHandler.java#L622

#### MQTT => TBD

TBD

#### NanoLeaf => Ok ??

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.nanoleaf/src/main/java/org/openhab/binding/nanoleaf/internal/handler/NanoleafControllerHandler.java#L921

#### TapoControl => Not Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/bulb/TapoBulbHandler.java#L149

#### TpLinkSmartHome => Not Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.tplinksmarthome/src/main/java/org/openhab/binding/tplinksmarthome/internal/device/BulbDevice.java#L94

#### Wiz => Ok

https://github.com/openhab/openhab-addons/blob/2f7b727d145b354db2f4a71be5cc0aad361a3d18/bundles/org.openhab.binding.wiz/src/main/java/org/openhab/binding/wiz/internal/handler/WizHandler.java#L190

**Comment by mueller-ma** [comment]
I think Tradfri doesn't support that as well. Here's a device:
![grafik](https://github.com/user-attachments/assets/8fd150c6-6f36-40b1-89cf-0702972cd56e)
(It says "Thing type: Colortemperature Bulb (white)")

And here are all channels, brightness and color are Dimmer:

![grafik](https://github.com/user-attachments/assets/cdbd1b05-101a-49e9-a7a0-bd6b327c6cb4)

**Comment by maniac103** [comment]
> I think Tradfri doesn't support that as well.

Right, but this issue is about a different topic: it's not about absolute color temperature not being supported, it's about absolute color temperature commands potentially not being handled correctly *if* supported.

**Comment by blue-kaleidoscope** [comment]
Is this the reason why I receive an error "type" 2 since I switched to openHAB 4.3?

I just updated to 4.3 and since then I cannot change the color temperature of my deconz bound lights.
Logs say:
```2024-12-18 13:21:03.115 [WARN ] [ernal.handler.DeconzBaseThingHandler] - Sending command 4000 °C to channel deconz:colortemperaturelight:raspi4:Deckenlampe_Hobbyraum_Mitte:color_temperature failed: 400 - [{"error":{"address":"/lights/2/state","description":"body contains invalid JSON","type":2}}]```

Thing:
```
Bridge deconz:deconz:raspi4 [ host="<ip>", httpPort="8090", apikey="<key>", port="4431" ] {
        colortemperaturelight   Deckenlampe_Hobbyraum_Mitte                             "Deckenlampe Hobbyraum Mitte"           @ "Hobbyraum"   [ id="2" ]
}
```

Item:
```
Number:Temperature          Deckenlampe_Hobbyraum_Farbtemperatur
                "Farbtemperatur Deckenlampen Hobbyraum"
                <colorpicker>
                (Deckenlampen_Hobbyraum, Lampen_Farbtemperatur)
                ["Control", "ColorTemperature"]
                {
                    stateDescription=" "[
                            min="250",
                            max="454",
                            step="1"
                        ],
                    unit="mired",
                    homekit="Lighting.ColorTemperature" [minValue=250, maxValue=454],
                    nightshift= " " [startzeit="21:00"],
                    channel ="deconz:colortemperaturelight:raspi4:Deckenlampe_Hobbyraum_Buecherregal:color_temperature" [ profile="ruby:mired_to_kelvin" ],
                    channel ="deconz:colortemperaturelight:raspi4:Deckenlampe_Hobbyraum_Mitte:color_temperature" [ profile="ruby:mired_to_kelvin" ],
                    channel ="deconz:colortemperaturelight:raspi4:Deckenlampe_Hobbyraum_Schreibtisch:color_temperature" [ profile="ruby:mired_to_kelvin" ],
                    farbtemperatur=" " [
                            tageslicht=250
                        ]
                }
```

According to [Error handling - deCONZ REST-API](https://dresden-elektronik.github.io/deconz-rest-doc/misc/errors/) error "2" means "This will be returned if the JSON in the body couldn't be parsed."

No idea what I should do with it. 😳
Any recommendations?

**Comment by andrewfg** [comment]
> Is this the reason why I receive an error

Yes unfortunately that is indeed the case. We were "too fast" in improving the OH functionality.

It will in particular occur when you try to command the color temperature via the new Colortemperature picker control.

There is a fix in #17919 which will certainly appear in OH 5.0 and probably hopefully back ported into OH 4.3. @lolodomo ??

In the meantime, the work around for you is to command the channel from an item of type 'Number' rather than one of type 'Number:Temperature' (or from within rules send a plain number value e.g. `4000` rather than `4000 K`.

**Comment by blue-kaleidoscope** [comment]
First of all thanks for the reply. In this case I went back to 4.2 as `Number` typed items also throw the same error both on UI and via my JRuby defined rules.

**Comment by holgerfriedrich** [comment]
KNX binding does not accept mirek/mired as unit for color temperature commands yet.

KNX uses defined data types, which only include `K` and `°C` for temperatures. DPT 7.600 DPT_Absolute_Colour_Temperature is intended for color temperatures, to other DPTs may be used, e.g. 14.069 DPT_Value_Absolute_Temperature. 
Internally, the binding uses ```QuantityType.toUnit(K)``` which returns null for MIRED. I can change this to use ```toInvertibleUnit``` at least for DPTs that are `K` or `°C`.

Is this something I should do, or is it sufficient to listen to commands with unit °C and K?

**Comment by andrewfg** [comment]
> the binding uses QuantityType.toUnit(K) which returns null for MIRED.
> I can change this to use toInvertibleUnit at least for DPTs that are K or °C.
> Is this something I should do, or is it sufficient to listen to commands with unit °C and K?

See reference code [here](https://github.com/andrewfg/openhab-addons/blob/354bd6022f56530b7553ce0521168a5048a7da1c/bundles/org.openhab.binding.tapocontrol/src/main/java/org/openhab/binding/tapocontrol/internal/devices/wifi/bulb/TapoBulbHandler.java#L150)

**Comment by holgerfriedrich** [comment]
@andrewfg thanks, this is what I basically did here to make it work 👍 

The question I still have is basically about the use case. What are the bindings or devices that would send a color command to KNX binding in MIRED?

**Comment by lolodomo** [comment]
> What are the bindings or devices that would send a color command to KNX binding in MIRED?

A command in a user rule for example.

**Comment by holgerfriedrich** [comment]
OK, thanks. PR for KNX is submitted, #18004.
