### ISSUE TITLE
[gpstracker] Unable to link regionTrigger to item

### ISSUE THREAD

**Issue by danhead** [openhab/openhab-addons#17913]
I've just upgraded from 4.2.3 (Docker image) to 4.3.0 and coincidentally my first task was to create a new item linked to a new regionTrigger with the GPS Tracker addon and I was unable to. On the "Link channel to Item" view, all of the profiles (including "Geofence" and "Toggle Switch") are disabled, making it impossible to link the channel with the item.

I downgraded my Docker container to 4.2.3, followed the same process and "Geofence" and "Toggle Switch" were both available again. Chose Geofence and it's all working as expected.

## Expected Behavior

Should allow me to select Geofence or Toggle Switch on Openhab 4.3.0 when linking an item to the GPS Tracker regionTrigger channel.

## Current Behavior

All profiles are disabled

## Steps to Reproduce (for Bugs)

1. Load settings > things > gpstracker:tracker:* > channels > region trigger > add link to item...
2. Create a new item
3. Attempt to choose "Geofence" in the Profile section

## Your Environment

OpenHAB 4.3.0 docker container (openhab/openhab:4.3.0)

WebUI running in Firefox 134 on Arch Linux

**Comment by lsiepel** [comment]
This seems to be a main UI bug. A fix was merged yesterday: https://github.com/openhab/openhab-webui/pull/2941
This will become available in the next maintenance release (4.3.1)
