### ISSUE TITLE
[mqtt.homeassistant] Device with an empty component name has no channels after upgrading to OH 4.3.0

### ISSUE THREAD

**Issue by OlegAndreych** [openhab/openhab-addons#17920]
I have an ESPHome powered device that produces the following discovery [payload](https://github.com/user-attachments/files/18169505/payload.json) in the topic: `homeassistant/climate/living-room-tion-3s/living-room-tion-3s/config`.

## Expected Behavior

Thing for this device is created with channels based on the discovery payload.

## Current Behavior

Currently, a Thing is created without channels.

There's an [exception in logs](https://github.com/user-attachments/files/18169533/exception.log) in logs.  
I've found that the exception is caused by this entry `"name": ""` in the discovery payload.  
After I've set a non-empty value for this entry, an exception is gone and all the expected channels appeared.

While adding non-empty value is a workaround, there should be no errors when the `name` entry is empty. It wasn't an issue in OH 4.2.<latest> and not an issue in Home Assistant.

## Possible Solution

Maybe we can use some constant instead of empty value.

Another way to solve the issue can be to reuse some upper level component name as ESPHome firmware itself does.  
As I stated earlier discovery topic with an empty `name` value looks like: `homeassistant/climate/living-room-tion-3s/living-room-tion-3s/config`, wile this topic with the `name` value set to `Tion Climate` will look like `homeassistant/climate/living-room-tion-3s/tion-climate/config` so `living-room-tion-3s` is used instead of an empty name.

**Comment by danielstosch** [comment]
Same with Nuki Smart Lock Pro 3 and Nuki Smart Lock Pro 4

**Comment by lsiepel** [comment]
fyi @ccutrer
