### ISSUE TITLE
[squeezebox] Add control for Alarms

### ISSUE THREAD

**Issue by overrunner** [openhab/openhab-addons#1855]
would it be possible to add support to control the alarms if the devices?
It would be great to turn on/off alerts if no one is at home e. g. 
Thank you.

**Comment by staehler** [comment]
+1

**Comment by mhilbush** [comment]
I can take a look at the alarm functionality, but I may not get to it for a while.  

The first thing to add, which is probably the simplest, would be to enable/disable all alarms for a player.  That's a simple CLI command (enableall & disableall), and could be tied directly to a switch channel on each player.

**Comment by staehler** [comment]
Yes, this is a "sinple" CLI command. At the moment I execute a external bash script which does this:
$ECHO '00%3A04%3A20%3A17%3A44%3A8d playerpref alarmsEnabled 1' | $NC -w 1 192.168.2.1 9090

More interesting would be to selectively en/disable the single alarms.
Maybe you could also have a look at dimming the display? It quite interesting for boxes which are placed in a bedroom. My wife wants the lowest dim at bedtime and I agree with her. Might be interesting for others as well? I solve this at the moment with a http call like
	sendHttpGetRequest("http://192.168.x.x:9000/status.txt?p0=playerpref&p1=powerOffBrightness&p2=4&player=mac_address_here")

**Comment by pigetto** [comment]
+1 for the alarm thing
Is it possible to enable/disable them via http?

**Comment by staehler** [comment]
I need following alarm items:
- switch all alarms on/off
- string alarm time(s)
With the alarm time, I can manage time based actions, like dim 5 minutes before alarm my bedroom lights
@mhilbush did you find time to dig into it?

**Comment by staehler** [comment]
Any progress on this? I'm keen on this features ;-)

**Comment by RURon** [comment]
...I have the same idea of using the alarm times to control other items (simulating sunrise before alarm time, heating bathroom...) so would be great to be able to get the alarm times and dates. I know there is a CLI command "alarms" to query LMS for alarms, but of course it would be nice to implement this to be able to directly use it in OpeHAB rules...

**Comment by hmerk** [comment]
closed due to inactivity
