### ISSUE TITLE
Compat layer does not correctly delegate UnDef events

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#186]
When sending UnDef status updates, a NPE is thrown, see https://groups.google.com/d/msg/openhab2/TtxPhsP5KY4/iJFlWVmznwMJ

**Comment by teichsta** [comment]
see fix proposal in #187 …

**Comment by kaikreuzer** [comment]
Considering https://github.com/openhab/openhab2/pull/187#issuecomment-93293742, we actually see that the problem is that UnDefType overrides toString as the only enum type (none of the others like OnOffType etc. do this).
Therefore, a toString() serialization and instantiation through valueOf(String) fails - we should find a general applicable solution for this.

**Comment by teichsta** [comment]
why not simply remove the toString() mapping from UnDefType?

**Comment by maggu2810** [comment]
> UnDefType overrides toString as the only enum type (none of the others like OnOffType etc. do this).
org.openhab.core.types.EventType also overrides toString.

We could perhaps also change from enum to class...

**Comment by maggu2810** [comment]
Okay, EventType is not a state, command or primitive type. So this seems to be no problems.

**Comment by kaikreuzer** [comment]
Removing toString might work, it could just potentially break some backward compatibility (e.g. transform map files which map "Undefined" to something else).

And it does not solve a deeper problem: If you post UNDEF on a StringItem, it will not reconstruct an UnDefType, but a StringType instead. So I wonder if we might have to introduce some reserved keyword and put the UnDefType at the top of the acceptedDataTypes in StringItem...?

**Comment by teichsta** [comment]
the reserved keywords could be "UNDEF" and "NULL" ;-)

**Comment by kaikreuzer** [comment]
Which would mean that these could never be used within a String item - might be quite a tough and unexpected constraint, don't you think?

**Comment by kaikreuzer** [comment]
> the reserved keywords could be "UNDEF" and "NULL" ;-)

I know went for this solution. Anyhow, in ESH we will soon introduce a more complex eventing, where this limitation might not be relevant anymore.

**Comment by kaikreuzer** [comment]
@mrguessed: Please check if this now solves your issues with the MIOS binding!

**Comment by idserda** [comment]
Seems like the UnDefType from OH is still reconstructed as a StringType in ESH because of the deviating toString(). This makes c440e6034ae645f0fbf052d68aeaf0b2254ee74e a bit less functional. Any ideas on how to proceed?

**Comment by kaikreuzer** [comment]
@idserda, with the latest fix, this problem should now also be solved!

**Comment by idserda** [comment]
Great stuff! Works as expected now.
