### ISSUE TITLE
[pulseaudio] Use sinks for output

### ISSUE THREAD

**Issue by mtzro2003** [openhab/openhab-addons#1895]
Hi!

As far as I see, the binding can only be used to set volume of the sinks... You cannot output sound to a pulseaudio sink.
Could it be extended to register the sinks in openHAB to allow to play notifications?
Would it be feasible?
The binding right now uses `module-cli-protocol-tcp` and this cli has a `play-file` command, but I don't know if this can be used to output sound from openHAB.
Maybe change the binding to use another module like `module-simple-protocol-tcp` or something else that allows to play sound from openHAB like audio notifications or voice prompts?

**Comment by vKnmnn** [comment]
in theory we should be able to install pulseaudio libraries on the openhab server and stream audio to remote pulseaudio sinks with the module-native-protocol-tcp.
we would then only need to be able to switch these streams around with the binding.

**Comment by vKnmnn** [comment]
The play-file command, i imagine, could work if you put your sound files on a NFS which is mounted on the same location on all your pulseaudio sink devices

**Comment by vKnmnn** [comment]
@dalgwen have you looked at icedtea (libpulse-java)? with that it should be possible to use the native pulseaudio protocol without implementing too much stuff yourself

**Comment by dalgwen** [comment]
Hello,

libpulse-java seems to serve different purpose. It is a JNI wrapper, allowing java program to output sound transparently to the local (not completely sure about this?) pulseaudio server. It has several drawbacks over the solution I choosed : 
- necessity to know the pulseaudio API to use it properly (I'm not even sure it is made for the kind of objective we want here ?)
- not sure if it can be used for remote sound
- not available for OpenHAB on Windows ?
- lack of documentation (? in fact I could not find any example ?)

The solution I choosed is, in fact, the lazy one. And I'm completely fine with that :-D !
(and last but not least, it's done and it's working)

Anyway, thanks for taking time to think about it, it is always good to think about alternative.

**Comment by vKnmnn** [comment]
Thank you for clarifying.

This library (icedtea is indeed bigger than just the pulseaudio java part) can be used to play networked sound.

For example, to use sound from openhab-docker, you will need to install pulseaudio and libpulse-java to the container and link a few files in just the right places for java to pick it up and you can have the java-sound output to the pulseaudio server (transparently) on the docker host (or elsewhere, depending on client.conf).

This means, that the pulseaudio apis are already implemented in libpulse-java. The implementation of the sound sink would be very similar to the current javasound

The way i remember it, you can have an instance of a pulse server with a remote IP. i failed wrapping my head around the whole thing with the static classes in there... java isn’t my strong suit. Plus, as you mention, the documentation is 'somewhat lacking' and pulseaudio isn’t available for windows.

Anyway: Thank you for this patch!

**Comment by dalgwen** [comment]
OK, I see, thank you for the additional informations. You put a lot more thinking than me in this !
By reading you, I may have taken this path, and as I see it now, it could have been prettier than just sending raw PCM bytes to a socket. And maybe the libpulse-java could have handled the MP3 support I had to take in another library ?

On the other side, I like the simple-protocol for the simplicity : It allows a fast 100% java solution, with no installation, no input or configuration from the user perspective needed. One of the last commit I made add the ability to search/load the simple protocol module remotely by itself, no need to load the module manually in configuration file or command line (unlike what I said in my first comment here).

Are you the original contributor of this binding ? If so (and even if not), thank you !

**Comment by ScanxTaz** [comment]
> Thank you for clarifying.
> 
> This library (icedtea is indeed bigger than just the pulseaudio java part) can be used to play networked sound.
> 
> For example, to use sound from openhab-docker, you will need to install pulseaudio and libpulse-java to the container and link a few files in just the right places for java to pick it up and you can have the java-sound output to the pulseaudio server (transparently) on the docker host (or elsewhere, depending on client.conf).
> 
> This means, that the pulseaudio apis are already implemented in libpulse-java. The implementation of the sound sink would be very similar to the current javasound
> 
> The way i remember it, you can have an instance of a pulse server with a remote IP. i failed wrapping my head around the whole thing with the static classes in there... java isn’t my strong suit. Plus, as you mention, the documentation is 'somewhat lacking' and pulseaudio isn’t available for windows.
> 
> Anyway: Thank you for this patch!

Hey, thanks for this very useful information, I was also thinking about installing pulseaudion in the Docker container, in order to be loosely coupled from the "real sink", installed on a "pi" somewhere on the network. 

Could we maybe elaborate a bit here about this ? I see that you are telling that installing the two pulseaudio and libpulse-java libraries would be enough, but is this really the case ? I mean, I guess that in the container, we have to physically set the "/etc/pulse/client.conf" file to redirect the pulseaudio client to the server and connect to the sink, but is this well the journey to follow ?

Thanks for your lights, really appreciated !

**Comment by vKnmnn** [comment]
@ScanxTaz Most of this is documented in [this issue](https://github.com/openhab/openhab-docker/issues/273)

But i just checked, and there’s nothing about icedtea, so i added that. It’s a [forum post](https://community.openhab.org/t/play-sound-over-standard-java-sinks-via-pulseaudio-to-bluetooth-device/22107/5).

**Comment by dalgwen** [comment]
@ScanxTaz I don't understand your use case.
Do you want to play something from within openhab to a pulse audio server somewhere on the network ?
If so, you don't need to install anything on the openhab machine (beside the pulseaudio binding), This is the purpose of this PR.

**Comment by ScanxTaz** [comment]
Yes, I'd like to play a song/sound from Openhab (in Docker) on a PulseAudio
Server (in PA mode).

But then, I'm lost... How shall I use the created things to play a song ?
The sink does not appear in Karaf... So how shall I use this one ?

Thanks a lot for your help,
Thierry.

**Comment by dalgwen** [comment]
1. Install this [test release for the pulse audio binding](https://github.com/dalgwen/openhab-addons/releases/tag/3.1.0-SNAPSHOT-Audiosink) **OR** wait for the official openhab 3.1.0 release and install the binding normally. Disclaimer : this is a test release, and I didn't have any feedback from other tester. It works for me ;)
2. As per [the documentation](https://github.com/dalgwen/openhab-addons/tree/3.1.0-SNAPSHOT_Audiosink/bundles/org.openhab.binding.pulseaudio) is saying, you need a running pulseaudio server **with the module module-cli-protocol-tcp loaded**. This is where you want the sound to be played. You DON'T NEED to have pulse audio on the openhab machine. In fact, your openhab instance could even be on a Windows machine.
In my case, my openhab is a PC server and I play sound on a raspberry pi over the network.
3. Create a pulse audio bridge for openhab to connect to your pulse audio server (see documentation)
4. Create or use the auto detection feature to add an "audio sink" thing (see documentation)
5. Activate the functionnality "Create an Audio Sink with simple-protocol-tcp" in the newly create thing configuration
6. Use the [openhab play sound functionnality](https://www.openhab.org/docs/configuration/multimedia.html).  You should be able to choose the pulse audio sink as a destination.

Feedback welcome :)

**Comment by ScanxTaz** [comment]
I'll check and to the tests for you then :)

My pulse audio server is well in TCP, I'm currently redirecting the sound
from a linux computer to the PA server. (inside an ESX farm with USB sound
card) Working pretty well, the bridge seem installed as well as I see in my
logs, on the PA server that a connection is intiated (and accepted) by my
openhab instance.

Small question as a start, I'm currently reading the read.me and it seems I
need to install a full development environment to compile the sources,
could you confirm ?
Or is there somewhere a compiled version of the binding ?

Thanks,

Thierry.

**Comment by dalgwen** [comment]
Yes, sorry, I put the wrong link.
I made a [JAR release here](https://github.com/dalgwen/openhab-addons/releases/tag/3.1.0-SNAPSHOT_Audiosink).

**Comment by ScanxTaz** [comment]
What is really strange is that the binding got back the correct name of the
sink on my PA server

[image: image.png]
So I guess something wrong there, but a bit stuck, shall  I raise up the
loglevel ? (and if yes, could you please send the command in Karaf :D)

Le mar. 25 mai 2021 à 18:04, Thierry Parmentier ***@***.***> a
écrit :

> So, installation done, I got a
>
> 17:48:40.920 [INFO ] [dio.internal.PulseaudioHandlerFactory] - pulseaudio
>> configuration update received ({component.name=org.openhab.binding.pulseaudio.internal.PulseaudioHandlerFactory,
>> component.id=331})
>>
>
> So I guess it's ok, no other errors in Karaf,
>
> What I've done :
> - Stopping docker container
> - Emptying Temp & Cache folder
> - Restarting docker container
>
> Accessing Web UI to see if binding is well loaded and following install
> procedure.
> What I see is the following screenshot (a lot of information, and that
> would be useful to explain a bit, while, coming from sound processing
> world, I "understand a bit".
>
>
> [image: image.png]
>
> I select the the first "bridge" of the list, to setup my connection.
> In the logs, I receive the following :
>
> 2021-05-25 17:56:51.380 [INFO ] [rnal.handler.PulseaudioBridgeHandler] -
>> Established connection to Pulseaudio server on Host '192.168.1.7':'4712'.
>>
>
> Going back to the binding pulseaudio, I try then now to add an audio sink,
> but I'm a bit lost, not easy to understand what to do here.
> I click on "Scan" but nothing appears special.
>
> I then decide to add a "PulseAudio Sink" manually.
> I jump on a screen asking me to select a bridge, I select the "Pulse
> Server", as per pre-config.
> Nothing moves in the log trail...
>
> And I get a new thing, but seems to be "offline".
>
> [image: image.png]
>
> Will try to re-do the setup.
>
> T.
>
>
>
>
>
>

**Comment by ScanxTaz** [comment]
Oh, and I can't disable or remove the things created, buttons disappeared

Le mar. 25 mai 2021 à 18:07, Thierry Parmentier ***@***.***> a
écrit :

> What is really strange is that the binding got back the correct name of
> the sink on my PA server
>
> [image: image.png]
> So I guess something wrong there, but a bit stuck, shall  I raise up the
> loglevel ? (and if yes, could you please send the command in Karaf :D)
>
> Le mar. 25 mai 2021 à 18:04, Thierry Parmentier ***@***.***> a
> écrit :
>
>> So, installation done, I got a
>>
>> 17:48:40.920 [INFO ] [dio.internal.PulseaudioHandlerFactory] - pulseaudio
>>> configuration update received ({component.name=org.openhab.binding.pulseaudio.internal.PulseaudioHandlerFactory,
>>> component.id=331})
>>>
>>
>> So I guess it's ok, no other errors in Karaf,
>>
>> What I've done :
>> - Stopping docker container
>> - Emptying Temp & Cache folder
>> - Restarting docker container
>>
>> Accessing Web UI to see if binding is well loaded and following install
>> procedure.
>> What I see is the following screenshot (a lot of information, and that
>> would be useful to explain a bit, while, coming from sound processing
>> world, I "understand a bit".
>>
>>
>> [image: image.png]
>>
>> I select the the first "bridge" of the list, to setup my connection.
>> In the logs, I receive the following :
>>
>> 2021-05-25 17:56:51.380 [INFO ] [rnal.handler.PulseaudioBridgeHandler] -
>>> Established connection to Pulseaudio server on Host '192.168.1.7':'4712'.
>>>
>>
>> Going back to the binding pulseaudio, I try then now to add an audio
>> sink, but I'm a bit lost, not easy to understand what to do here.
>> I click on "Scan" but nothing appears special.
>>
>> I then decide to add a "PulseAudio Sink" manually.
>> I jump on a screen asking me to select a bridge, I select the "Pulse
>> Server", as per pre-config.
>> Nothing moves in the log trail...
>>
>> And I get a new thing, but seems to be "offline".
>>
>> [image: image.png]
>>
>> Will try to re-do the setup.
>>
>> T.
>>
>>
>>
>>
>>
>>

**Comment by ScanxTaz** [comment]
Wait I found something strange.
My previous setup "tries" with the previous binding where always present.
Those ones are undeletable, the new ones are perfectly deletable.
But, as I can't suppress the old one, it's always present in the list of
the sink (even when disabled), and I see now that this one is the one that
is taken automatically, even if I change it in the thing definition, it
comes back automatically to the "first bridge of the list" (when I leave
the window) --- the old one which is then not compatible I guess...

Le mar. 25 mai 2021 à 18:08, Thierry Parmentier ***@***.***> a
écrit :

**Comment by dalgwen** [comment]
If you configured your old bridge / thing by an .item file, you can't edit (or delete) them from within the UI. You must edit (delete) the file. It could explain part of your issue ?

Also, it's better if you uninstall the old binding before manually installing the snapshot I made, I'm not familiar with the behavior of openhab when two versions cohabits.

I suggest we continue this conversation on [the topic binding](https://community.openhab.org/t/pulse-audio-binding/74265), as it appears to be a more broad subject than this PR (which was just to add audio sink capability to the binding, and I think we are not yet at this point).

(And last but not least, you could have more help than only mine ;-) !)

**Comment by ScanxTaz** [comment]
Héhé :) Ok, I was simply replying to mail, I thought that was in the forum,
and not on the PR, sorry for that.
Switching to the forum then. Thanks :)
