### ISSUE TITLE
[wifiled] Request for additional protocol

### ISSUE THREAD

**Issue by glasruit** [openhab/openhab-addons#1896]
Hi,

I own a similar Wi-Fi led controller which has a slight different protocol. I kindly ask if you could incorporate this protocol in your openhab2 wifiled binding aswell. I managed to write a simple working python driver for eventghost to control the leds, but would like to use it in openhab2.

device: [https://nl.aliexpress.com/store/product/Original-Wifi-RGB-LED-controller-for-Iphone-Ipad-Android-mobile-phone-2-3Version-IOS-system-DC7/905340_1032823060.html?isOrigTitle=true](url).
protocols:

discover: (is already discovered with wifiled binding in fading mode)

query status led, 3 bytes: "\xEF\x01\x77"
response 11 bytes:
//  [0] 66 always start with 66-01
//  [1] 01
//  [2] PowerOff
//  [3] Mode
//  [4] program
//  [5] programSpeed
//  [6] Red
//  [7] Green
//  [8] Blue
//  [9] 01
// [10] 99 - always end with 01-99

set rgb color #RRGGBB, 5 bytes: "\x56\xRR\xGG\xBB\xAA"

set program, 4 bytes: 
// [0] BB
// [1] program - same as in wifiled
// [2] program speed
// [3] 44

**Comment by davidgraeff** [comment]
Please provide a pull request on your own to add that functionality. Thanks :)
