### ISSUE TITLE
(MAX! Binding) German umlauts not correctly shown (neither in GUI nor in log file)

### ISSUE THREAD

**Issue by habnefrage** [openhab/openhab-addons#191]
I have recognized some kind of encoding problem with german umlauts in MAX! Binding.
Room names and device names are incorrectly encoded in GUI and in logfiles.

**Details of my setup:**
- Windows 7 running Chrome browser
- OH2 is installed on Ubuntu 64Bit
- OH2 sources are compiled on Windows 7, Java 8

**Example screenshots**
![image](https://cloud.githubusercontent.com/assets/1625918/7189486/a0570d42-e47f-11e4-8b68-4648b9c82465.png)

![image](https://cloud.githubusercontent.com/assets/1625918/7189507/bf0561d0-e47f-11e4-9b8e-f292111558aa.png)

**Comment by kaikreuzer** [comment]
@marcelrv, could you please have a look if you can reproduce this?

**Comment by marcelrv** [comment]
Yes, think this I'd an issue with oh1 as well. Will check, assume it's an
characterset issue
Op 18 apr. 2015 16:18 schreef "Kai Kreuzer" <notifications@github.com>:

**Comment by habnefrage** [comment]
@marcelrv, I could find and fix the encoding problem.
Now it works

**Comment by kaikreuzer** [comment]
Fixed with https://github.com/openhab/openhab2/pull/193.
