### ISSUE TITLE
[samsungtv] High CPU load openHAB process when TV is turned on

### ISSUE THREAD

**Issue by mlommers** [openhab/openhab-addons#1944]
When the samsung TV is turned on the openhab process has a high CPU load.
see: [https://community.openhab.org/t/samsung-tv-2-binding-and-cpu-utilization/20803/7](https://community.openhab.org/t/samsung-tv-2-binding-and-cpu-utilization/20803/7)
to see the CPU load and the correlation when the TV is turned on:
![cpu_vs_tv_power](https://cloud.githubusercontent.com/assets/3784834/23231025/7e322c46-f946-11e6-8293-48a4664b0dcd.png)
the update interval is set to 1000 ms

**Comment by MHerbst** [comment]
I have tried the Samsung binding but CPU load was OK when the Samsung TV is on. Can you reproduce the problem with the latest binding? If it is OK now, please close this issue.

**Comment by wborn** [comment]
Is this still an issue @mlommers?

**Comment by davidgraeff** [comment]
Please reopen if this is still an issue.
