### ISSUE TITLE
[autelis] Password resets back to admin

### ISSUE THREAD

**Issue by soveryvaried** [openhab/openhab-addons#1973]
When I start OH2, it will connect with the Autelis pool controller and function fine for awhile. Later I will see in PaperUI that the pool controller shows as "Offline - Communication Error". In the logs I see the message:

`[DEBUG] [nding.autelis.handler.AutelisHandler] - Method failed: 401 Unauthorized`

I then check the configuration of the pool controller Thing and find that the password has reset back to the default ("admin"). I type in the correct password, save the change, and OH2 reconnects. A random time later I'll find the pool controller offline again and it's because the password reset.

I've tried setting up the pool controller through PaperUI using auto discovery and also through a things flat file. The password reset happens no matter how it is setup.

**Comment by hmerk** [comment]
closed due to inactivity
