### ISSUE TITLE
[silvercrestwifisocket] Add support for Aldi EasyHome devices

### ISSUE THREAD

**Issue by Ronson1909** [openhab/openhab-addons#1990]
Based on #1952 (pull request created and pending) I will try to add the functionality to control 433 MHz slaves as it is possible with the Aldi EasyHome system. Control requests are known and already tested on a linux shell.

The idea is to add another field/property with the slave id (3 bytes in hex format). If it's left empty then the master is switched (current functionality).

Any comments are welcome.

**Comment by martinvw** [comment]
@Ronson1909 can this also be closed?

**Comment by Ronson1909** [comment]
Hi @martinvw , no that's an additional enhancement since the Aldi device has the capability to control slave device(s) via RF 433 MHz. It's already working for me, I "only" have to rebase it and push it for a review. Hopefully soon, so please leave it open.
