### ISSUE TITLE
[smaenergymeter] Status: offline

### ISSUE THREAD

**Issue by devUBi** [openhab/openhab-addons#2032]
I'm trying the SMAEnergyMeter binding in OH 2 but i can't get it working. Current Thing status is:
**Status: OFFLINE - CONFIGURATION_ERROR java.net.SocketTimeoutException: Receive timed out**
I tried naming the thing like the energy meter ID but no change. 
I tested with a little Java program sending a discovery call to the multicast address and it's answering. 
Webinterface from the energy meter is accessible too. The complete photovoltaics environment is running perfectly but the binding did not get access to the values. 
Any ideas, any help?

**Comment by steveknoefler** [comment]
Hi,
i have the same problem
i restart the switch and it works a few hours later no COMMUNICATION
(OFFLINE - COMMUNICATION_ERROR java.net.SocketTimeoutException: Receive timed out)

an ios app is always working, so connection is correct and working

**Comment by hmerk** [comment]
closed due to inactivity
