### ISSUE TITLE
[exec] Bind output to Number items

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-addons#2149]
Please add support for binding output of exec 2.0 binding to Number items.

Currently it is impossible to bind the output of a command to a Number item. If the item is defined as String type, it will work.

Example.

**uptime.sh**
```sh
#!/bin/sh

# return uptime of openHAB process in seconds

PID=`ps aux --sort=start_time | grep openhab.*java | grep -v grep | awk '{print $2}' | tail -1`
UPTIME=`ps -o etimes= -p "${PID}"`
echo $UPTIME
```

**demo.things**
```xtend
Thing exec:command:uptime [command="/path/to/uptime.sh", interval=10, timeout=2]
```

**demo.items**
```xtend
Number Uptime_Number { channel = "exec:command:uptime:output" }
String Uptime_Text { channel = "exec:command:uptime:output" }
```

**Comment by rtvb** [comment]
cc @kgoderis

**Comment by Stormwind99** [comment]
This (bind output to Number item) works in OH1.8's exec binding but not OH2.

**Comment by mepi0011** [comment]
Same problem as @metbril here!
Please add support to use exec 2.0 binding with Number Items.

**Comment by jacob-roldan** [comment]
Is Uptime_Text working in the Basic UI?
I've defined a Thing and its item associated, and I put it on a .sitemap file.
I see this value in Paper UI /Control and in HABmin/Sitemaps, but the Basic UI doesn't show any value.

**Comment by kgoderis** [comment]
This will be covered in https://github.com/openhab/openhab2-addons/pull/2012

**Comment by hmerk** [comment]
closed due to inactivity
