### ISSUE TITLE
Add Carrier Infinity Touch Binding

### ISSUE THREAD

**Issue by gk4** [openhab/openhab-addons#2158]
The Carrier Infinity Touch Controller has lacked any resemblance of home automation until recently.  They just published an Alexa skill which tells me they are using the www.myinfinitytouch.carrier.com cloud accounts to control their thermostat.   They also have mobile apps for it.  It would be nice if OH2 could do the same. 

http://alexa.amazon.com/spa/index.html#skills/dp/B01N1T72HY/?ref=skill_dsk_skb_sr_1

**Comment by kjohns3** [comment]
These links may be helpful for anyone interested in implementing this binding... http://dms.hvacpartners.com/docs/1010/Public/00/sw_openapi_gs.pdf
https://github.com/nebulous/infinitude
https://github.com/acd/infinitive

**Comment by B34N** [comment]
I'm also very interested if this could be done. Preferably I would not have to replace the standard my infinity capabilities.

**Comment by hmerk** [comment]
closed due to inactivity
