### ISSUE TITLE
[pioneeravr] Airplay volume update every 7 second

### ISSUE THREAD

**Issue by rhjensen79** [openhab/openhab-addons#2190]
When i use the binding, to connect to my Pioneer VSX-922, i get a volume update on my screen, every 7 second, when i use airplay to send the sound from my ATV thru my Amplifier.

Is there something updating the status of the volume, at that interval, that makes Airplay, thing that the volume is being shifted up or down ?

**Comment by martinvw** [comment]
I assume this is about the PioneerAVR Binding, I'll update the title to reflect it.

**Comment by hmerk** [comment]
closed due to inactivity
