### ISSUE TITLE
[wifiled] Add support for Flux WiFi LED lamps

### ISSUE THREAD

**Issue by triphoppingman** [openhab/openhab-addons#2336]
I have a patch for the wifiled binding to support FLUX Wifi led lamps.   Any interest in getting this into the repo?

**Comment by davidgraeff** [comment]
@triphoppingman 
If it is just a few changes, create a github gist for it, with a license header at the beginning (eclipse license 1.0). If it is more complex, create a merge request with your changes.

**Comment by hmerk** [comment]
closed due to inactivity
