### ISSUE TITLE
[marytts] Sample rate '16kHz' from audioFormat is not used

### ISSUE THREAD

**Issue by Celaeno1** [openhab/openhab-addons#2340]
related to #1982
[see also here](https://github.com/openhab/openhab2-addons/pull/1982/commits/33c7baf2f380c90b6b933bf6773e3b64db4fb0e6)

## Expected Behavior
Using german voice(s) should use 16kHz sample rate.
A testing with a changed 
`long srate = (this.audioFormat != null) ? this.audioFormat.getFrequency() : 16000l; ` 
instead of 48000l in **MaryTTSAudioStream.java** (line 92) brought the correct speed. 
So it seems that audioFormat from original voice is not used, but 48000l always is used!

## Current Behavior
It uses always 48kHz. So both german voices are too fast. English speed is OK.

 [see discussion here](https://community.openhab.org/t/sonos-audio-sink-say/15576/102)

## Your Environment

* Version used: OH2, Build 920,   2.1.0.201705282306  | MaryTTS Voice Service
* Environment name and version: jdk1.8.0_111
* Operating System and version: Windows 10 Home, 32bit

**Comment by jmone1** [comment]
I commented on the [forum ](https://community.openhab.org/t/mary-tts-english-tempo-is-too-slow-german-sounds-ok/99405/2)that the English voice sound "drunk" as the tempo is too slow and was redirected to this post.

**Comment by hmerk** [comment]
closed as related PR was merged.
