### ISSUE TITLE
Make Dashboard dynamic

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#235]
Currently, the Dashboard is hardcoded and has links to all UIs that could be potentially available - this implementation was done quick&dirty to have something available for the start.

For a good solution, UIs should register as a service and thus only be listed, if they are really installed and available.

**Comment by kaikreuzer** [comment]
@cdjackson: Please note that you will have to add such a service in the HABmin bundle as well in order to have it listed there again.

**Comment by cdjackson** [comment]
Will-do... Thanks.

**Comment by cdjackson** [comment]
Is this still using the css and images that are defined in the dashboard UI? ie the image doesn't get defined by the tile?

**Comment by kaikreuzer** [comment]
Yes correct - I didn't spend the effort to also allow dynamic contribution of images; so I have kept them within the dashboard bundle, see also https://github.com/openhab/openhab2/blob/master/bundles/ui/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/DashboardTile.java#L13. Also the HABmin image is still present there. The image/css name is derived this way: https://github.com/openhab/openhab2/blob/master/bundles/ui/org.openhab.ui.dashboard/src/main/java/org/openhab/ui/dashboard/internal/DashboardServlet.java#L51

**Comment by cdjackson** [comment]
Thanks. I implemented this last night so it's all working, but I just wanted to make sure I understood in case I missed something...

Maybe it's simple to add another method to get the image - or more specifically a reference to the image, and then have the image itself served from the apps folder...

**Comment by kaikreuzer** [comment]
> Maybe it's simple to add another method to get the image - or more specifically a reference to the image, and then have the image itself served from the apps folder...

Well, it is not that simple, because the image is referred to within the CSS and you would need another servlet that provides the images data. It is quite some effort which I wanted to spare for the moment.

**Comment by cdjackson** [comment]
I know it's in the CSS now, but I don't see why it has to be. It should be able to be added to the style rather than into the class, and then instead of providing another servlet, just reference the image inside the current servlet...

ie, you have getUrl() that returns ../habmin/index.html, you could also have getTileImage() that returns ../habmin/assets/tile.png

**Comment by kaikreuzer** [comment]
Ok, should be feasible. Feel free to create a PR - I am afraid, I will not find the time for this myself...

**Comment by cdjackson** [comment]
Ok - I'll take a look...
