### ISSUE TITLE
[feed] Enhance binding to generate feeds from events

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-addons#2454]
Hi,
Would it be possible, to enhance the feed binding to generate feeds, e.g. from events?
I'ld like to present a feed of some important events on my mobile feed reader or I would like to generate a feed of my daily appointments ....

It should be something like the logInfo method, like

rss ("feedname", "this is my feed text and this is an item state:" + item.state)

Regard 
Michael

**Comment by hmerk** [comment]
closed due to inactivity
