### ISSUE TITLE
Add IntesisHome Binding

### ISSUE THREAD

**Issue by dk8pn** [openhab/openhab-addons#2490]
It would be very nice if one of the openHAB2 experts would be willing to program a binding which can include the WiFi air conditioner (A/C) controller from "Intesishome" suited for e.g. Panasonic and many other A/Cs. A description of the required Intesishome API can be retrieved from: https://www.intesishome.com/developers/rest-api-documentation/.

**Comment by hmerk** [comment]
Closing, as the intesis binding is part of openHAB3,
