### ISSUE TITLE
[orvibo] Can I reflect orvibo binding device status by some REST API? 

### ISSUE THREAD

**Issue by laohixdxm** [openhab/openhab-addons#2557]
I notice after orvibo binding discovery, UI item does NOT reflect S20 device status. 
E.g. device is ON, but UI item on sitemap shows off.

I am NOT sure whether there's such an REST API. while I see UI item status is inconsistent with real device status. By that REST API, openhab server & binding can update status on UI item to make them consistent.

I do find REFRESH command on openhab REST page. However, it seems REFRESH command does NOT implemented in orvibo binding.

So here is my question, for orvibo binding, is there some feature to sync up UI item status with real device status while they are inconsistent?

Thank you very much. 

Reference:
https://community.openhab.org/t/does-orvibo-zwave-hue-binding-not-support-refresh/33164

**Comment by laohixdxm** [comment]
Sorry, I may miss something.

The Device I used for orvibo binding is an wifi switch called "wifi smart socket S20". Basically, we can turn it on/off.

However, is it possible to query the current device status is On or Off? 
If so, then we can add REFRESH command to command handler & call updateState to sync up UI item state with the device status we just query.

Can some expert shed some light for that? Or provide suggestion what I should look into for that purpose?
Thank you very much.

**Comment by tavalin** [comment]
The S20 devices report the state in all responses so this is possible.  Unfortunately I don't know when I will get time to look at implementing this.

**Comment by laohixdxm** [comment]
Thank you very much.
It looks like you are saying there's NO direct command to query ON/OFF status.
Instead, we send a command with other specific purpose, the ON/OFF status is included in the response from the device.
1 Am I correct to say that?

2 Is the low level part already implemented? 
Like, notice you already implemented 7 low level command, which is GLOBAL_DISCOVERY / LOCAL_DISCOVERY / POWER_REQUEST / POWER / SUBSCRIBE / LEARN / EMIT.

I mean, do we only need to add some code for one of these 7 command handling?
Or still there's another low level command need to be implemented?

Thank you very much.

**Comment by hmerk** [comment]
closed due to inactivity
