### ISSUE TITLE
[gardena] Minor problem with signal strength items

### ISSUE THREAD

**Issue by Dan1001** [openhab/openhab-addons#2660]
The Gardena binding Thing shows that signal strength is a Number. Copying the example in the documentation, I defined my item as:

`Number WateringSignal "Watering signal [%d %%]" {channel="gardena:watering_computer:home:[redacted]:radio#state"}` 

This gives an error when the sitemap is viewed:

`2017-08-31 10:49:32.220 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value 'average' of item WateringSignal with format '%d %%': {}`

The problem goes away if the item is instead defined as

`Number SensorSignal "Sensor signal [%s]" {channel="gardena:sensor:home:xxxx:radio#state"}`

Although, oddly, the Number item then reads "average" on the sitemap.

Trying to fix this by defining the item as a String gives an error:

`2017-09-01 08:06:20.191 [ERROR] [pse.smarthome.core.items.GenericItem] - Tried to set invalid state 2 (DecimalType) on item SensorSignal of type StringItem, ignoring it`

Dan

**Comment by hmerk** [comment]
closed due to inactivity
