### ISSUE TITLE
[chromecast] Continue playing music after notification 

### ISSUE THREAD

**Issue by haltmann** [openhab/openhab-addons#2675]
## Expected Behavior
If a Notification is provided while music is playing, the music stops play the notification and resume the music afterwards. 

## Current Behavior
At the moment the music never resumes

## Your Environment
Latest openhabian with latest openhabsnapshot

**Comment by haltmann** [comment]
Link to the community forgotten:
https://community.openhab.org/t/chromecast-announcement/33942

**Comment by JueBag** [comment]
I started thinking on how to implement that feature.Not sure if I'm able to finish it, however it will be worth a try.
Questions: 
Am I stepping into to work done by anybody else?
Does anybody have a link to the documentation of the Chromecast API?

**Comment by kubawolanin** [comment]
> Does anybody have a link to the documentation of the Chromecast API?

There you go:
https://developers.google.com/cast/docs/reference/

**Comment by holmes** [comment]
Try the jar in this PR: https://github.com/openhab/openhab2-addons/pull/2097

I have no idea if it works, but it might.

**Comment by JueBag** [comment]
Will look into it and try it. However, I'm presently on vacation  and afterwards on a longer business trip,  so the testing has to wait probably till the end of november.Sorry for that.

**Comment by fab33** [comment]
The problem still exist with last version when you use "say" music stop (deezer for me) and don't restart.

**Comment by ellisbjohns** [comment]
same issue here.  I'm too busy to code things up at this time but will look into things if this request lingers too long.

**Comment by holmes** [comment]
How do you get a notification on your Chromecast? I'm in the middle of a remodel so my system isn't set up but curious why this isn't working

**Comment by ellisbjohns** [comment]
holmes: There is a running thread on the [openhab community forum](https://community.openhab.org/t/chromecast-bindings/16294/49?u=ellisbjohns) explaining how to do this.  It's not perfect though.  At present if you send an announcement/notification to chromecast it stops your music and the music does not restart

**Comment by dr-eamy** [comment]
Any news on this issue ?

**Comment by cweitkamp** [comment]
Most of the bindings supporting playing audio or notifications from OH2 use vendor specific playlist features to solve this. IIRC the Google Cast API supports something similar.

@vitalidze Any ideas how to add this feature? Can we use the Google Cast [QueueManager](https://developers.google.com/cast/docs/reference/caf_receiver/cast.framework.QueueManager) to handle it? Does your library support it?

**Comment by vitalidze** [comment]
> @vitalidze Any ideas how to add this feature? Can we use the Google Cast QueueManager to handle it? Does your library support it?

I have no idea how to add this. I can say that it is not supported out of the box. However, since it is possible to define custom messages and then send/receive them, it should be possible to implement it if someone can reverse-engineer the protocol.

**Comment by paul43210** [comment]
There seems to be a new Cast Application Framework (CAF) that replaces Sender v2:
https://developers.google.com/cast/docs/migrate_v2/ccl_sender
One of the added features is "Queueing is a major feature introduced as part of CAF Receiver. The earlier Receiver v2 implementation carries a basic sender-initiated queue while the new queueing implementation in CAF Receiver introduces receiver-implemented queueing."

**Comment by chris400** [comment]
any news on that request? :)

**Comment by jimtng** [comment]
+1 I'd like this ability too

**Comment by stdestro** [comment]
+1

**Comment by eric1905** [comment]
+1

**Comment by xsirpreisx** [comment]
+1

**Comment by asdfsafd** [comment]
+1

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by SeeDborg** [comment]
+1

**Comment by negmos** [comment]
+1
