### ISSUE TITLE
[ipp] Malformed URL with IPP Binding and IP V6

### ISSUE THREAD

**Issue by cveith** [openhab/openhab-addons#2764]
The IPP Binding is using the IPv6 Address when discovering my CUPS Printserver, when operating an Network in Dualstack IP Mode (V4 and V6 together)

As a result the openhab logfile contains errors such as these:

**[ERROR] [inding.ipp.handler.IppPrinterHandler] - malformed url http://2003:50:f44:5400:216:3eff:fedc:d0bc:631/printers/FS-1370DN, printer thing creation failed**

Manually reconfiguring the thing url, via Paper UI, will work until restart of openhab. After restart the initial IPv6 address is used again.

## Expected Behavior
I would expect the IPP Binding to properly format the url. The IP part of the url should be encapsulated in square brackets, when the address is an IPv6 Address with Port extension.
http://**[**2003:50:f44:5400:216:3eff:fedc:d0bc**]**:631/printers/FS-1370DN

The second expected behaviour is that overridden configuration settings should be persisted and not be reset on restart of openhab. Especially when it's changed from IP address to a fully qualified domain name.

## Current Behavior
The url is formatted via ip:port, which results in the errors as there's no differentiation between the host and port part of the url. The status of the thing is **online**, even when the ab

Manual reconfiguration of the thing is overwritten on restart or not persisted upon shutdown.

## Possible Solution

1. Encapsulate the found IPv6 address in square brackets.
2. Try to resolve the ip address to a fully qualified domain name and use it instead.
3. Persist the manually overwritten settings of the thing and protect them from automatic changes.

## Steps to Reproduce (for Bugs)
1. Discover a CUPS printer via IPP Binding in a network supporting IPv6 and IPv4
2. Review the url parameter. It should be printed like **http://IP:PORT/...**
3. Change the url parameter to a fqdn.
4. Restart openhab
5. Review the url parameter. It should be the original value again.

## Context
Issues makes the use of the binding impossible, as the printer is not accessible via the incorrect url parameter and violates RFC2732 which defines the format of literal IPv6 Addresses in url's.
See https://tools.ietf.org/html/rfc2732

## Your Environment

- OS: Debian 8
- Kernel: 3.16.43-2+deb8u2
- Architecture: x86_64
- Ram: 1GB
- Browser:  Google Chrome  61.0.3163.100

**Comment by Andirs55** [comment]
Unfortunately same problem for me :(
However even putting the ipv6 in [] doesn't work.
The Thing is online but still non functional. I get the following logs:

> Handler IppPrinterHandler tried updating the thing status although the handler was already disposed.

**Comment by hmerk** [comment]
closed due to inactivity
