### ISSUE TITLE
[opensprinkler] Feature request: can have an item for flow meter?

### ISSUE THREAD

**Issue by jnoam** [openhab/openhab-addons#2789]
Have an opensprinkler with a flow meter connected (supported in the recent firmware versions).
Would someone be willing to try and add an item with the flow meter reading? that would allow volume-based activation as well as general monitoring.

Thanks!

**Comment by davidgraeff** [comment]
Nobody seem to be interested :/ Closing this now. Pull requests to add this functionality are welcome.
