### ISSUE TITLE
[zoneminder] Logs COMMUNICATION_ERROR even if Operating mode is NONE 

### ISSUE THREAD

**Issue by michaelHH1** [openhab/openhab-addons#2835]
By intention the Operating mode of a monitor is set to NONE, which will regularly stop the Capture Daemon, the ZoneMinder Binding reports in the openhab.log:
Thing status changed from 'OFFLINE' to 'OFFLINE' (DetailedStatus='COMMUNICATION_ERROR', Description='Capture Daemon is not running')
[ERROR] [andler.ZoneMinderThingMonitorHandler] - [MONITOR-4]: Capture Daemon is not running

should be avoided in that case.
thanks

**Comment by hmerk** [comment]
closed due to inactivity
