### ISSUE TITLE
Add Sensibo A/C Controller Binding

### ISSUE THREAD

**Issue by michaeldavie** [openhab/openhab-addons#2911]
I'd like to start working on a new binding for the [Sensibo](https://sensibo.com) family of air conditioner controllers.

## Expected Behavior
Allow OpenHAB to control Sensibo systems.

## Current Behavior
Currently using rules-based scripts: https://github.com/michaeldavie/Sensibo-and-Openhab-2

**Comment by martinvw** [comment]
Great thanks for informing us!

**Comment by JAMESBOWLER** [comment]
I very interested I can help out with testing

**Comment by janroarjensen** [comment]
I can test too. or is it done?

**Comment by michaeldavie** [comment]
Unfortunately, I haven't been able to start on this. However, in the meantime you can test out the rules-based scripting available at https://github.com/michaeldavie/Sensibo-and-Openhab-2.

**Comment by Zodiarc** [comment]
I started development of a binding for the sensibo sky yesterday. I´m completely new to openHAB so development is slow but I´m currently at a state where I can read the data from the API and I think I´ll be able to control my A/C tomorrow. The thing  descriptions are currently static but as soon as I´m able to control everything I´ll create a fork of this repo and push my binding. After that I´ll start working on dynamic thing definitions.

**Comment by michaeldavie** [comment]
That's great news. Since opening this issue I've moved from OpenHAB to Home Assistant, so I probably won't be of much help. For what it's worth, here are the Python implementations that Home Assistant uses:

Sensibo API client: https://github.com/andrey-git/pysensibo
Home Assistant component: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/climate/sensibo.py

**Comment by Zodiarc** [comment]
Funny enough I was on Home Assistant before openHAB, but stuff happened with it which drove me nuts. That´s why I switched

**Comment by JAMESBOWLER** [comment]
Cool I still down for testing if it works I have 2 sky's

**Comment by Zodiarc** [comment]
That's awesome. I have only one so testing it for multiple devices isn't possible. I'll get in touch as soon as I think I have it set up for multiple.

**Comment by Zodiarc** [comment]
The First version is now available for testing. If you have more than one Sensibo Sky with one account, please don´t enter the deviceID at first and see if the log viewer shows an error that there are more then one available. Please let me know if there are any errors. I´ll clean the code up in the next days and make the thing definition dynamic so it suits the capabilities of the connected A/C. Right now I have only options which my A/C supports so it may be that some settings are not available for your A/C.
