### ISSUE TITLE
[samsungtv] SamsungTvHandler implements DiscoveryListener

### ISSUE THREAD

**Issue by sjsf** [openhab/openhab-addons#2916]
In Eclipse SmartHome, the discovery mechanism is an optional concept. All bindings (i.e. the handlers) must work without. Therefore the ONLINE/OFFLINE state of things _must not_ depend on discovery results.

**Comment by sjka** [comment]
@paulianttila as the original author (and supposably possessor of a Samsung TV), could you please take care of this?

**Comment by kaikreuzer** [comment]
I'd assume that implementing `UpnpIOParticipant` is probably the better approach - which can be used to be informed about UPnP device availability.
To relieve @paulianttila from any blame: This interface didn't exist at all at the time when he implemented the binding and the current solution was discussed and agreed to solve the specific situation of that binding.

**Comment by masto182** [comment]
What about a Samsung connect binding?  The main think I want is the ability to know what source is active.  Because there will be a different sequence of button presses if I was in the Netflix app vs on hdmi for example.

**Comment by kaikreuzer** [comment]
@martinvw I do not remember how the different UDNs were "merged" into a single thing, but this part can still be done through the discovery.
I think @sjka's main point here is that you must not depend on the inbox for ONLINE/OFFLINE recognition in the handler - and once you have all UDNs available in the handler config, the `UpnpIOParticipant` should be just fine to deal with that aspect. Or am I missing something?
