### ISSUE TITLE
[ipp] IppPrinterHandler implements DiscoveryListener

### ISSUE THREAD

**Issue by sjsf** [openhab/openhab-addons#2917]
In Eclipse SmartHome, the discovery mechanism is an optional concept. All bindings (i.e. the handlers) must work without. Therefore the ONLINE/OFFLINE state of things must not depend on discovery results.

**Comment by kaikreuzer** [comment]
I assume the proper way would be to implement `UpnpIOParticipant`, would you agree?

**Comment by sjka** [comment]
No, the proper way would be letting the runnable do its job and setting the thing to `ONLINE` **or**  `OFFLINE` depending on whether it could communicate with the printer successfully. I really would keep UPnP out of the game here.

**Comment by hmerk** [comment]
closed due to inactivity
