### ISSUE TITLE
[zway] Binding doc states no configuration is necessary

### ISSUE THREAD

**Issue by travellingkiwi** [openhab/openhab-addons#2952]
## Expected Behavior
Binding requires at least password configuration 

## Current Behavior
Docs state no configuration is necessary

## Possible Solution
Doc update to state password config is necessary

## Context
Affects first time user

## Your Environment
openHab2, R-Pi using zWay binding and zWay server with non-default password

**Comment by hmerk** [comment]
closed due to inactivity
