### ISSUE TITLE
[zway] Watchdog for Z-Way Interface

### ISSUE THREAD

**Issue by travellingkiwi** [openhab/openhab-addons#2993]
Occasionally (Sometimes frequently) openHab2 (Especially the snapshots :slight_smile: ) go catatonic. It logs messages, rules (mostly) run, but the REST API just isn’t doing anything.

When this happens the ZWay plugin for openHab logs errors. e.g.

[2017-12-17 10:17:32.226] [I] [core] openHAB item not notified Waterfall_Switch
[2017-12-17 10:17:32.313] [E] [core] Callback execution error: TypeError: Cannot read property ‘error’ of undefined
at Function.http.request.error (automation/userModules/OpenHABConnector/index.js:403:107)

Now it’s not zWays fault that the catatonia has been initiated, but it would sure be nice if the plugin handled it a little better (ie. backoff a bit? Because when you have lots of devices you just get an endless stream of callback execution errors against index.js).

Now having the ability to use the callback as a watchdog would be nice too… Perhaps just an easy status that can get queried for whether the openHab connection is up ok, or down (RST received) or catatonic (got a connection but the REST PUT itself is not completing)

## Expected Behavior
When the openhanded plugin for Z-Way gets an error from the openHab REST api it would be good to have this alerted so that it could be escalated to a restart of openhab

## Current Behavior
We just log errors. And continue. Systems stays broken.

## Possible Solution
Direct call to systemd to restart? Possibly not the best place...
Alternatively, a watchdog daemon that looks for confirmation openhab is responding when it is running and restarts after a suitable interval if it is not.

## Steps to Reproduce (for Bugs)
NA

## Context
Affects me when openHAB goes catatonic you don't know till it starts to get cold and you notice the lights don't come on...

## Your Environment
OpenHAB 2.2.0-1 on R-Pi2 with RaZBerry using ZWay binding

**Comment by hmerk** [comment]
closed due to inactivity
