### ISSUE TITLE
[homekit] Add support for user permissions

### ISSUE THREAD

**Issue by AlexeyVitalevich** [openhab/openhab-addons#2998]
permission for homekit users

## Current Behavior

in current version of Apple HomeKit i can not do different permission  for different users. All of users connected to HomeKit can do anything. 

I need do different permission for different users.
(i successful connect my OpenHab2 to homekit & apple tv - all work!)
 

## Possible Solution

i think, if run second homekit addon on OpenHub2 with
1. different homekit.cfg 
2. different path
i can pair second "home" to homekit. In second "home" i can manage what exactly items can control second user over apple homekit  

## Steps to Reproduce (for Bugs)

1.
2.

## Context

i have some member of my family. I need reject for famaly member menage  some items over home kit. In the same time i need do access to homekit for this person. 

please, help me with run second homekit addon on OpenHab2

## Your Environment

* Version used: (e.g., openhab and addon versions)

org.openhab.io.homekit-2.0.0

openhab> version 4.0.8

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

Linux raspberrypi 4.9.27-v7+ #997 SMP Tue May 9 19:58:37 BST 2017 armv7l GNU/Linux

* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by hmerk** [comment]
closed due to inactivity
