### ISSUE TITLE
[tellstick] Sending ON to device, state changes ON -> OFF -> ON

### ISSUE THREAD

**Issue by jakobstenfeldt** [openhab/openhab-addons#3020]
## Expected Behavior
That the state does not toggle. 

## Current Behavior
See post i community: https://community.openhab.org/t/tellstick-sending-on-to-device-state-changes-on-off-on/37562

## Steps to Reproduce (for Bugs)
See post i community, link above.

## Your Environment
openHAB 2.2.0 Release Build
Bridge tellstick:telldus-live:2 “Tellstick net” [refreshInterval=30000 … ]

**Comment by hmerk** [comment]
closed due to inactivity
