### ISSUE TITLE
[pioneeravr] Switches power back ON after power OFF

### ISSUE THREAD

**Issue by ericsnis** [openhab/openhab-addons#3030]
I am trying to use the PioneerAVR binding version 2.2 with my older VSX-82 connected via serial. I was sending commands to it with the serial binding in OH2.1 which worked except that I couldn't figure out how to transform responses to list system status information, so it wasn't the ideal situation.

I uninstalled the serial binding to prevent possible conflicts, then installed the PioneerAVR binding through the PaperUI interface then set up a thing using /dev/ttyUSB0. I also set up new item names after pulling out the old items, sitemaps and rules referencing the old serial interface. I can change the inputs and turn off the power as expected. However when the power switches back on again after a couple of seconds when I attempt to turn the power off.

I found entries in the log suggesting it is polling the receiver for status which is waking it. I tried unlinking the channel for device status in the thing, but it still powers up the receiver. The command reference says that the receiver switches on when it receives a command. Is there a way to disable polling when the device is powered off?

Here are the entries in the log, full log from the Pioneer set to debug below.

`25-Dec-2017 15:09:49.651 [DEBUG] [ing.pioneeravr.internal.handler.AbstractAvrHandler] - Checking status of AVR @/dev/ttyUSB0
25-Dec-2017 15:09:49.654 [DEBUG] [g.pioneeravr.internal.protocol.StreamAvrConnection] - Command sent to AVR @/dev/ttyUSB0: ?P
25-Dec-2017 15:09:49.658 [DEBUG] [g.pioneeravr.internal.protocol.StreamAvrConnection] - Command sent to AVR @/dev/ttyUSB0: ?AP
25-Dec-2017 15:09:49.665 [DEBUG] [g.pioneeravr.internal.protocol.StreamAvrConnection] - Command sent to AVR @/dev/ttyUSB0: ?BP`

[Pioneer.log](https://github.com/openhab/openhab2-addons/files/1586157/Pioneer.log)

This is the command reference for the VSX82. [https://www.pioneerelectronics.com/pio/pe/images/portal/cit_3424/349506363VSX82TXS_RS232C_Protocols.pdf](url)

**Comment by gersilex** [comment]
@ericsnis Is this still relevant to you? I think we could disable polling altogether, using a setting for the thing.

**Comment by gersilex** [comment]
@davidgraeff It seems like it is not relevant anymore. Should we close this issue?

**Comment by hmerk** [comment]
closed due to inactivity
