### ISSUE TITLE
Improved rollershutter control for Alexa

### ISSUE THREAD

**Issue by Barnecke** [openhab/openhab-addons#3064]
Hi,

during the last days I made some experience with OH2 on my RPI.

Now I found a solution to control my rollershutter (Elero with transmitter stick) in a suffient way. My problem was, that Alexa can only switch ON and OFF and with the rollershutter only fully up, or fully down. But I want to stop by ALexa-command or give a special percentage (e.g. 50% for half down).

I defined 2 items for each rollershutter.
Item 1 (e.g. "eins") for UP, DOWN and percentage control
Item 2 (e.g. "eins stop") for manual stop by Alexa command
roller.items:
```
Dimmer eins "eins" [ "Lighting" ]
Switch eins_stop "eins stop" [ "Switchable" ]

```

And rules to convert the Alexa commands 
roller.rules:

```
rule "Rolladen 1 über on/off und Prozent steuern"
when
	Item eins received command
then
	logInfo("hue.rules","eins received command")
	
	var int wert = ( eins.state as DecimalType ).intValue
	var int sec

	logInfo("hue.rules","eins received command" + wert)

	if ( wert == 100 ) {
		logInfo("roller.rules","eins command ON")
		Rolladen1_Control.sendCommand(DOWN)
	}	

	if ( wert == 0 ) {
		logInfo("roller.rules","eins command OFF")
		Rolladen1_Control.sendCommand(UP)
	}	

	if ( wert > 1  &&  wert < 99 ) {
		Rolladen1_Control.sendCommand(DOWN)
		sec = ( wert * 25 / 100 )
		createTimer (now.plusSeconds( sec ), [| 
			logInfo("roller.rules","eins command" + sec)
			Rolladen1_Control.sendCommand(STOP)
		] )
	}	

end

rule "Rolladen 1 stoppen"
when
	Item eins_stop received command
then
	logInfo("roller.rules","eins_stop received command")
	Rolladen1_Control.sendCommand(STOP)
end

```

May be this helps or you have some improvements.

**Comment by elcoda** [comment]
Hi, 
I have Elero rollingshutter and Bticino-Legrand brand new domotic system and I'm not able to set position by percentage. Seems something similar to your situation.
Do you thing this can be a problem/limit of Elero motors?

**Comment by Barnecke** [comment]
Hi, 
As I know, you can not set a special percentage. Elero only know the status top, bottom, or somewhere between.
As you see in my code, I control it by time. Full move from top to bottom needs 25 seconds, 50 % is 12,5 seconds and than I stop it. It only works, when the rollershutter is at top position.

**Comment by davidgraeff** [comment]
The issue is unfortunately not exact enough. Is the hue emulation used or the echo binding or myopenhab? However, this is a shortcoming of Alexa as it does not natively supports rollershutters and they need to be handled like lights basically for percentage support.
