### ISSUE TITLE
[airquality] Individual AQI dimensions

### ISSUE THREAD

**Issue by emme-g** [openhab/openhab-addons#3113]
Hello,
as suggested I moved here my post about the Air Quality binding indexes dimensions.
Some weeks ago I tried to understand in a better way how the AQI is calculated because some values I could read through the binding were unclear for me. I understood that the total AQI is calculated as the maximum value among the individual AQIs related to the single pollutants (PM2,5, PM10, O3, NO2, CO), as it is better explained in Wikipedia
https://en.wikipedia.org/wiki/Air_quality_index
I noted that in the air quality binding the values of the items related to the single pollutants appear with the μg/m³ dimension, but it seems to me that the AQIs related to the single pollutants are just indexes (without dimensions) and not values with μg/m³ dimensions, as we can read in this page
http://aqicn.org/faq/2013-09-09/revised-pm25-aqi-breakpoints/
where for example it is explained that a value 50 of the PM2,5 individual AQI corresponds to a PM2,5 concentration of 12 μg/m³.
So, I think that it should be better that the item values would appear in the binding without any dimension.
It would be also very interesting to receive the values of the concentrations of the single pollutants too (using some more new channels), but I think that this totally depends on the AQIcn.org service and eventually it should be asked to them.

**Comment by clinique** [comment]
Regarding the dimensionless aspect of the channel, this is now done. Values are indices without any unit. Reconstructing the value behind is out of the scope of the binding.
