### ISSUE TITLE
[hyperion] Polling frequency set to 0 causes error while startup

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-addons#3117]
## Expected Behavior
Start up even if polling frequency is set to 0.

## Current Behavior
Setting polling frequency to 0 and restarting openhab causes the Thing to fail while initializing the handler. 

## Possible Solution
Temporarily set the frequency to bigger than zero. After the Thing had come up once, you may change it back to 0.

## Steps to Reproduce (for Bugs)
1. Create a hyperion Thing
2. Wait for it to come online
3. Change polling frequency to 0
4. Change succeeds, thing still online.
5. Restart openhab
6. Thing will not come online
7. Change frequency to bigger than 0
8. Restart openhab / bundle
9. Thing will come online
10. (You may now change back to 0)

## Context
I've set the polling frequency to 0 because hyperion seems to have a memory leak, causing it to fill up RAM. Taking longer when less often queried. Zero turns the polling off, thus mitigating the issue.
See also PR #2319 

## Your Environment
* Version used: openhab 2.2 stable, market:binding-3472338 - 1.0, hyperion V1.03.3 (brindosch-2fbbcff/2f01dfa-1495880388
* Operating System and version Raspian

**Comment by tavalin** [comment]
The Hyperion binding hasn't made it into this repo yet so unfortunately this isn't the right place for the issue. However I also wonder what your use case is for a poll time of 0 seconds.

**Comment by cribskip** [comment]
@tavalin Thanks for your comment.
Shall I post in https://github.com/tavalin/openhab2-addons/tree/hyperion?

My use case is:

- Hyperion and openhab are running on the same pi
- Control is only done with openhab (not thru e.g. hyperion-app)
- Hyperion has a memory leak triggered every time the binding refreshes the current state
- Mitigating is to set refresh to a very high value (or zero)

(We've already talked about this in https://github.com/openhab/openhab2-addons/pull/2319#issuecomment-355041978)

**Comment by tavalin** [comment]
Yes either on my fork or on the pull request as that's where I'm going to be looking when I come back to this. 

Thanks for the report anyway.
