### ISSUE TITLE
[yamahareceiver] RX-V781: Choose HDMI-Output

### ISSUE THREAD

**Issue by LiPoPower** [openhab/openhab-addons#3149]
Hi,
is it possible to extend the 2.2 Yamaha Receiver binding with a channel for choosing the HDMI-Output (1, 2, 1+2, none/off)?

There are two reasons for that request:

The receiver is not capable to send the HDMI-signal on both outputs to TV-set and beamer simultaneously. The beamer is connected via a 10m long cable, it only works if set the output only to it.
When i switch off my “stoneage”-TV-set, because i want to hear music, the red HDMI-Indicator starts flashing. Thats annoing! Therefor i have to switch off both HDMI-Outputs.

Thanks in advance…
Kind regards, Oliver

**Comment by zarusz** [comment]
Hi @LiPoPower,

What Yamaha model do you have? 

Can you send me the response file?
`http://<Your_Yamaha_IP>/YamahaRemoteControl/desc.xml`

**Comment by fragger42** [comment]
Hi @zarusz : I'm having the same issue with RX-V775. Here is my desc.xml:
[desc.zip](https://github.com/openhab/openhab-addons/files/5664906/desc.zip)

**Comment by hmerk** [comment]
closed due to inactivity
