### ISSUE TITLE
[vitotronic] VitotronicThingHandler does not handle the command REFRESH

### ISSUE THREAD

**Issue by armintan** [openhab/openhab-addons#3206]
## Expected Behavior
VitotronicThingHandler should handle the framework command REFRESH

## Current Behavior
Framework command REFRESH sent to optolink daemon, which cannot handle it

## Possible Solution
Filter the REFRESH command and do not send it to the optolink daemon.

## Your Environment

* Version used: (openhab2)
* Environment name and version: (e.g. Chrome, Java 8, ...):
* Operating System and version: (openhabian):

**Comment by hmerk** [comment]
closed due to inactivity
