### ISSUE TITLE
[systeminfo] Add channel "systeminfo:computer:<name>:memory#freePercent"

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-addons#3210]
Currently, the sysinfo binding doesn't provide a "% of used memory" or "% of fee memory" - at least on a RPi.

Would love to have an information about the used/free memory to determine a potential memory leak.
The information is in general available on Raspberries:

> [23:22:13] openhabian@openHABianPi:~$ egrep --color 'Mem|Cache|Swap' /proc/meminfo
> MemTotal:        1000312 kB
> MemFree:           47200 kB
> MemAvailable:     515456 kB
> Cached:           429636 kB
> SwapCached:         3676 kB
> SwapTotal:        102396 kB
> SwapFree:          71224 kB

Remark: "MemAvailable" is available as channel in OH2, but it doesn't seem to have anything to do with the current memory usage at all.

**Comment by hmerk** [comment]
closed due to inactivity
