### ISSUE TITLE
[samsungtv] Add support for 2014 and 2016 models

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-addons#3228]
Samsung TV’s models from 2014 (H series) and 2015 (J series) use a different, encrypyed protocol that requires pairing tv and remote. The current binding does not support this. I have found a thread within another repo that points to some promising libraries. 

Perhaps someone feels like investigating and porting the code. 

https://github.com/Ape/samsungctl/issues/22#issuecomment-359063253

**Comment by sectroyer** [comment]
Let me know what you need 😃

**Comment by metbril** [comment]
@sectroyer Well, more or less what I asked for. :wink:

I have a J-series TV (2015 model) which I think uses the same protocol as the 2014 series.
What I would like is the SamsungTV binding to support the 2014/2015 series, to be able to control my TV just like any older or more recent model.

**Comment by sectroyer** [comment]
Ahh than samsungctl is what you need 😄

**Comment by codefalk** [comment]
@sectroyer, thanks for the hint with samsungctl. 
Are you aware of possibilities to get information from a Samsung TV as well? I am thinking of controlling the light in the living room in dependence of the kind of program that is being watched. Therefore I would need to know which channel has been selected.

**Comment by codefalk** [comment]
okay, thanks. Somewhat radical ... but still a possible solution ... 😉

**Comment by sectroyer** [comment]
I would say it's MANDATORY 😄 I don't use TVs without proper shell 😄

**Comment by tnemrap** [comment]
I am also interested of this i have a UE65HU8505.

**Comment by hmerk** [comment]
closed due to inactivity
