### ISSUE TITLE
[pioneeravr] Input List for Pioneer HM-82

### ISSUE THREAD

**Issue by koenig-dro** [openhab/openhab-addons#3250]
Hi,
I'm using the binding for power on and off my Pioneer AVR HM82, works for me.

Trying to change Input list, but seems that theres some IDs missing.
With an other Project I found out:
CD = 1
Tuner FM = 2
ipod/USB = 17
Internet Radio = 38
M.Server = 44
Favorites = 45
Audio In = 51
Line1 = 52
BT Audio = 56
Spotify = 57
Line2 = 58
Digital In = 59

Would be nice if i get this into it to use it
Thanks!

**Comment by hmerk** [comment]
closed due to inactivity
