### ISSUE TITLE
[homekit] Extend accessories with additional characteristics

### ISSUE THREAD

**Issue by ptweety** [openhab/openhab-addons#3267]
## Expected Behavior
I have several devices that are battery driven. I want them to show their battery level in HomeKit as well.

## Current Behavior
AFAIK any accessory that OH2 will expose to homekit will have a fixed set of characteristics. There is mostly one characteristic mapped to exactly one item in OH2 with thermostats as an exeption.

## Possible Solution
The implementation of thermostats has shown that it is possible to group several characteristics into one accessory, but this is fixed in the way you have to setup them.

I wonder whether we can make this more generic?

CC: @beowulfe

**Comment by ccutrer** [comment]
this depends on linked services in the HAP-Java library, which was just recently added. i.e. this is now unblocked on the OpenHAB side

**Comment by hmerk** [comment]
closed due to inactivity
