### ISSUE TITLE
[openhabcloud] Feature request: Allow notifications to return values (for rules)

### ISSUE THREAD

**Issue by bdleedy** [openhab/openhab-addons#3296]
I'm speaking specifically for iOS or Android. It would be great to write a rule that says, "it's after 11PM, the garage door is open. Close it?" and give you yes/no options and then handle that in a rule to then close the door. I'm sure there are MANY more scenarios but this allows for a much more comprehensive 'fuzzy' automation that allows for intelligent input. Maybe I'm working in the garage and want it open.

So as far as the technical is concerned. I know it's possible to prompt in this way, the question becomes is it possible for the responses to be custom. On the other side of things, I would assume that sendNotification would need extended or a different method like sendPrompt would need to the written.

Mistaken reuqested here https://github.com/openhab/openhab.ios/issues/154 first.

**Comment by martinvw** [comment]
I'm in doubt what the correct location would be... but I love the idea

**Comment by openhab-5iver** [comment]
This reminded me of this https://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/, which is unfortunately still only available in the iOS OwnTracks app.

**Comment by bdleedy** [comment]
Yes, it allows some human decision into the automation. I'm sure there are many times it would actually be _required_ to implement certain rules. In my case though, I'm thinking about certain requirements/states being met and then a human decision being required.

For instance in my example, what if I'm in the garage working and want the door open still? It shouldn't be an automatic decision to close the door.
Which brings up another thought. What if I'm not? What if I'm asleep and don't get the notification? Is there a timeout? A default response? Is this handled in the rule of as part of the notification? I would say that for the user, in the notification would be MUCH easier.

Computer's are only as smart as the user right? Well, I can't preload all of my decisions into the config.

**Comment by stritti** [comment]
Yesterday I had same idea:
- Notification: Hey Windows is still Open. Temperatur is below 15*C.
- Battery of Sensor X is low.
- ...

+1 Looking forward it

**Comment by kaikreuzer** [comment]
Does anyone know whether it is technically feasible? I so far thought that GCM and APN are uni-directional and that there isn't any chance to provide a return value (anyhow, due to user involvement that would be much delayed and thus rather be async, i.e. no return value).

In any case, for anything that goes more towards an interaction design, it might make sense to rather focus on https://github.com/ghys/habot - this imho has a huge potential. @ghys, Can you say whether the web push notifications can work in the background and potentially provide such interactions directly from within the notifications?

**Comment by ghys** [comment]
@kaikreuzer yes, there are a number of things possible from within the notification, including calling an API in response to the click of the notification itself or an [action button](https://web-push-book.gauntface.com/chapter-05/02-display-a-notification/#actions) - those buttons are a Chrome-only feature currently. In fact most websites supporting notifications will make API calls to tracking/analytics services as soon as the push data is received (even before the notification is displayed).

Details here: https://web-push-book.gauntface.com/chapter-05/03-notification-behaviour/
and demo sites at https://web-push-book.gauntface.com/demos/notification-examples/ and https://tests.peter.sh/notification-generator/

Potential example - you could potentially click the "turn on heating" button even without opening the site:
![image](https://user-images.githubusercontent.com/2004147/37279225-7478c31e-25ea-11e8-8479-68065185cf76.png)

 In the https://github.com/ghys/habot context however I was planning on keeping the notification simple and display a card with details in the chat and action options along with the message when the notification is clicked.

**Comment by ghys** [comment]
Also keep in mind that there are no public signs of the Push API being supported one day in Safari (https://caniuse.com/#feat=push-api, https://platform-status.mozilla.org/#push), and while Chrome has the largest market share worldwide, in Western Europe and America people are more likely to be using iOS...

https://clicky.com/marketshare/us/operating-systems/mobile/
https://clicky.com/marketshare/de/operating-systems/mobile/
https://clicky.com/marketshare/gb/operating-systems/mobile/
https://clicky.com/marketshare/nl/operating-systems/mobile/

**Comment by mueller-ma** [comment]
This seems to be the same feature as the last one here: https://github.com/openhab/openhab-cloud/issues/160

> I so far thought that GCM and APN are uni-directional and that there isn't any chance to provide a return value

When we implement it as @redeye86 suggests, the client knows which item has to be changed, so there is no need to use GCM for the return value.

**Comment by hmerk** [comment]
closed due to inactivity
