### ISSUE TITLE
[foxtrot] Add Foxtrot Binding

### ISSUE THREAD

**Issue by radovansninsky** [openhab/openhab-addons#3346]
I’ve created new binding for the Tecomat Foxtrot system.

Tecomat Foxtrot is a compact modular control and regulation system to build smart home electroinstallation. Foxtrot system provides powerful processor, original two-wire and wireless connection with intelligent electroinstallation elements and peripherals. More about Tecomat Foxtrot can be found here:
https://www.tecomat.com/products/cat/cz/plc-tecomat-foxtrot-3

The code for new binding is in my forked openhab2-addons repo:
https://github.com/radovansninsky/openhab2-addons

More about what the binding can do is described in binding's README file.

**Comment by wborn** [comment]
See also PR https://github.com/openhab/openhab2-addons/pull/3348.

**Comment by martinvw** [comment]
@wborn I once introduced this label to be able to quickly see in the issue overview whether a PR is yet there, so if you see other cases feel free to use that label as well.

**Comment by hmerk** [comment]
closed due to inactivity. Related PR does not exist anymore.
