### ISSUE TITLE
[knx] PercentType.class should map to DimmerItem.classs

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#3383]
Currently in the KNXCoreTypeMapper we have

`        defaulItemTypeMap.put(PercentType.class, NumberItem.class);
`
However, since DPT 5.001 is commonly used by Dimmer Actors to the absolute position, and since DPT 5.001 is mapped by the KNXCoreTypeMapper onto PercentType.class, consequently it would be better to have PercentType.class mapped onto a DimmerItem. NumberItem accepts DecimalType, and thus PercentType, but since DimmerItem is "more specific" (and directly accepts PercentTypes), DimmerItem should be preferred above NumberItem in the defaulItemTypeMap

**Comment by J-N-K** [comment]
But please make sure that PercentType can be shown in NumberItems. Otherwise e.g. humidity values are difficult to use.

**Comment by kgoderis** [comment]
@J-N-K Yes Indeed, this might be working through the Type conversion that is done by CommunicationManager core class. This has to be verified indeed

**Comment by pdcemulator** [comment]
Is this also causing that percent values (humidity) are shown as 0.51 instead of 51%?

**Comment by hmerk** [comment]
closed due to inactivity
