### ISSUE TITLE
[smaenergymeter] Binding should support more that 1 device

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-addons#3429]
Right now only 1 Thing is auto discovered....even if there are more that one energy meters in the network.
The result is, that the channels (power in, power out, energy in, energy out) are switching between the different energy meter values (according refresh interval).

It's already possible to add all energy meters to the Things-File. But with the same result. All Things are jumping between the values.

It would be good if the binding can filter the data according serial numbers. Maybe an additional parameter "serialnumber" for each thing?

The binding itself is very helpful, but with more than one meter it's not really usable.

My system:
openHAB 2.3 latest snapshot
2x SMA Energy Meter
Raspi3

**Comment by wborn** [comment]
@monnimeter could you implement these changes?

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by FeKn** [comment]
I've the same problem: 
The simultaneous operation of e.g. a SMA Energy Meter and a SMA Sunny Home Manager 2.0 in the same network is not possible, because the binding does not seem to evaluate the serial numbers in the Multicasts and therefore permanently updates the (wrong) values for all Things.

Is there a way to fix this?

**Comment by michaeljoos72** [comment]
No, not with this binding. Instead I'm using this:

https://github.com/datenschuft/SMA-EM

Does support serial numbers and different options to send the data. I'm using MQTT to send the data to openHAB.

**Comment by lsiepel** [comment]
re-opened: Issue has an active PR attached.
