### ISSUE TITLE
[avmfritz] Implement TR064 and additional features

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab-addons#344]
As discussed in https://github.com/openhab/openhab/issues/2953, the fritzbox binding of openHAB2 should be extended to support the TR064 protocol and allow various interactions with the fritzbox.

Appearently the extension of the binding was already discussed in the [openHAB2 forum](https://groups.google.com/d/topic/openhab2/UjwL7sIHnmw/discussion) some month ago.

@robbyb67, as it seems you already put quite some effort into this. Are you currently implementing this feature for openHAB2?
##

**Comment by robbyb67** [comment]
Indeed I've planed to implement this. But currently my time is eaten up by family, summer, home improvement and job ... ;-)
I could last till October/November until you will see significant progress here.

**Comment by martinvw** [comment]
@robby67 was this change picked up by you or other people, is this issue still relevant?

**Comment by martinvw** [comment]
@cweitkamp can you quickly see whether this problem is already solved?

**Comment by cweitkamp** [comment]
@martinvw I can quickly tell you that the avmfritz OH2 binding doesn't support these features, yet.

**Comment by davidgraeff** [comment]
Seems like no interest in implementing this since 3 years time. Closing now.
