### ISSUE TITLE
Add Worx Landroid S (Modell 2017/2018) Binding

### ISSUE THREAD

**Issue by orificer** [openhab/openhab-addons#3440]
There has been an binding request to support the Landroid S (2017) and even a working solution at issue #2468 from @Silencer80, but it has been removed because the used polling mode has been bothering the vendors server. 

The vendors engineering has been very cooperative and worked with some people from [roboter-forum.com](url) to find a solution to implement the Landroid S mowers at different Smart Home solutions without side effects to "normal" users which are using the App to control their mowers.

Most of the discussions has been at this thread (in german): http://www.roboter-forum.com/showthread.php?22535-Landroid-S-in-Smarthome-einbinden-endlich-m%F6glich/page18

As a result there is a working adapter for IoBroker which has been developed from MeisterTR together with the engineering of Worx/Positec (https://github.com/MeisterTR/ioBroker.landroid-s). There is also an FHEM module which is using parts of this code.

The most important part of the IoBroker adapter is landroid-cloud-2.js (https://github.com/MeisterTR/ioBroker.landroid-s/blob/master/lib/landroid-cloud-2.js). There js is receiving the userdata and is sending the data from the mower (received from the vendors server).

It would be great if anyone is able to adapt this code to an openhab binding.

Best regards
orificer

**Comment by int5749** [comment]
I'm very happy to see some progress as I do own a Landroid S and use OpenHab for house automation already ;-) Any idea when a first version would be available for testing?

**Comment by webcharlyx** [comment]
https://github.com/weweave/landroid-bridge might be a solution

**Comment by hmerk** [comment]
closed due to inactivity
