### ISSUE TITLE
binding.max: actual_temp could not be formatted correctly

### ISSUE THREAD

**Issue by dennobaby** [openhab/openhab-addons#351]
Hi,

i'm using openhab2  (latest build from 08/20/15) with the latest plugin for max.

Everything works perfectly but the actual temperature: in the classic-UI i get "err" for the temp. In the log i can see this:

```
2015-08-25 15:32:50.677 [WARN ] [s.u.i.items.ItemUIRegistryImpl] - Exception while formatting value '29.800000000000000710542735760100185871124267578125' of item max_wallthermostat_JEQ0437559_LEQ1465192_actual_temp with format '%d °C': java.util.IllegalFormatConversionException: d != java.math.BigDecimal
```

I think this is a bug. 

Any advice?

**Comment by kaikreuzer** [comment]
Looks indeed like a bug. The formatting pattern in the thing description should rather be %.1f instead of %d.
@marcelrv, Could you please have a look?

**Comment by marcelrv** [comment]
Yes, seems to make sense. Will create a PR to fix this

2015-08-25 22:47 GMT+02:00 Kai Kreuzer <notifications@github.com>:

**Comment by marcelrv** [comment]
Interesting enough it does not generate the error in the paperUI which I use mostly for testing.

**Comment by kaikreuzer** [comment]
fixed by #355, thanks!

**Comment by marcelrv** [comment]
Hi @dennobaby,
can you confirm and close the issue.
Thx

**Comment by marcelrv** [comment]
Hi @dennobaby 
can you confirm and close the issue.
Thx

**Comment by dennobaby** [comment]
Sorry, didn't see it. It works now perfectly :)
