### ISSUE TITLE
[telegram] Add SOCKS5 support

### ISSUE THREAD

**Issue by Zoolu74** [openhab/openhab-addons#3527]
<a alt="bounty" href="https://www.bountysource.com/issues/57694823"><img src="https://api.bountysource.com/badge/issue?issue_id=57694823"></a>

Hi! I live in Russia and we have blocked the Telegram ... Could you help with setting up SOCKS5 proxy in Telegars action?

**Comment by wborn** [comment]
The link to the bounty (by @martinvw :+1:) is: 
https://www.bountysource.com/issues/57694823-telegram-need-socks5

**Comment by wborn** [comment]
Shouldn't this be an issue in the openhab1-addons repo instead @martinvw? That's the repo which hosts the telegram action.

**Comment by Zoolu74** [comment]
I'm sorry, I did not know exactly where it was located ... I'm using OphenHAB2, so I wrote it here ...

**Comment by martinvw** [comment]
I opened https://github.com/openhab/openhab1-addons/issues/5566 instead.

**Comment by ehorohorin** [comment]
The ticket should be reopened again, because of telegram binding 2.5 is added to official repository :)

**Comment by wborn** [comment]
Yes it would be better to put effort in adding it to the new binding.
Maybe @martinvw can transfer the bounty again? :smile:

**Comment by ehorohorin** [comment]
@wborn i have a solution for that in https://github.com/openhab/openhab1-addons/issues/5566

**Comment by wborn** [comment]
Perhaps @ZzetT can have a look at it and comment if that's the preferred way of adding it to the binding?

**Comment by ZzetT** [comment]
Yes, I'll have a look.

**Comment by ehorohorin** [comment]
Updated commit is here: https://github.com/ehorohorin/openhab2-addons/commit/8455e710e07ad04d7f8a204396c42a05c643c017

**Comment by ehorohorin** [comment]
One more update to add proxyType: https://github.com/ehorohorin/openhab2-addons/commit/ecd3ab7a7b36a03693d28f769c5bc7674878c0b6

**Comment by martinvw** [comment]
I moved the bounty back to this issue :-)

**Comment by wborn** [comment]
Thanks! :+1: I hope it can stay here and can be claimed soon. :-)

**Comment by martinvw** [comment]
Solved via #6824
