### ISSUE TITLE
[opensprinkler] Feature-Request: HTTPS and HTTP basic authentication

### ISSUE THREAD

**Issue by itn3rd77** [openhab/openhab-addons#3540]
Currently it is not possible to use OpenSprinkler in a secure manner with HTTPS or even HTTP basic authentication  (e.g. behind NGINX Reverse Proxy).

As far as I could see the usage of HTTP is fix by usage of a constant named HTTP_REQUEST_URL_PREFIX

https://github.com/openhab/openhab2-addons/blob/fc3988a9054f19d7fac88a0c0ac1c059f7245750/addons/binding/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerApiFactory.java#L41

My current knowledge of the whole openHAB development is not sufficient to tackle this myself. So I submit this ticket in hope someone with more superpowers will take care of this.

Regards
Ingo

**Comment by cweitkamp** [comment]
@FlorianSW Can you work on this?

**Comment by FlorianSW** [comment]
Sounds legit, will take a look if I find the time to implement it :)
