### ISSUE TITLE
[sonos] Feature request: add device by ip

### ISSUE THREAD

**Issue by mitch-geht-ab** [openhab/openhab-addons#3638]
Hi,
I wonder if it could be possible to add a sonos device/thing by his IP address instead of his upnp udn.
You could assign a fix IP for example by DHCP.

Problem is, my openhab server is placed in another VLAN than my WLAN devices like my sonos player, smartphones etc.

**Comment by J-N-K** [comment]
While I support your request, you can get it working across VLANs with UPnP. See my post on the OpenHAB forum.

**Comment by wborn** [comment]
The source code of the Sonos Binding is part of the Eclipse SmartHome repository. 
Please use the [Eclipse SmartHome issue tracker](https://github.com/eclipse/smarthome/issues) for creating Sonos Binding issues.

**Comment by sumnerboy12** [comment]
This doesn't seem to have been raised in ESH and hasn't been implemented. I would like to see this added also, so I can run OH inside a docker swarm environment where UPnP is not possible.

**Comment by lolodomo** [comment]
Sonos is based on UPnP. The binding fully relies on UPnP for example to be notified on any change. 
Sorry but the binding is not usable in case UPnP is not available between the OH server and your Sonos devices. I will not change that.

**Comment by sumnerboy12** [comment]
It can be configured to work without UPnP (see [here](https://github.com/svrooij/sonos2mqtt)) for an example. You define each device by IP address and setup event callbacks so each device knows where to send the events - i.e. the IP of your openhab server.

I doubt this is an easy change however, so understand if you don't want to implement it. In the meantime I will stick with the sonos2mqtt bridge and do everything using mqtt bindings in openhab.

Thanks for getting back to me.

**Comment by nesys** [comment]
Team, my config is exactly as mentioned in the thread above in openHAB Community. 2 vlans, one for controllers and openHAB, one for Sonos devices. UPnP and mDNS enabled on my unifi router. Controllers (S2) are working perfectly, and they are able to discover the Sonos devices. OH can't. Enabling the upnp logs, I see some datagrams coming from the router, but apparently not understood by OH.

**Comment by lolodomo** [comment]
As noone looks interested in implementing such feature after 3 years, I close it.
