### ISSUE TITLE
[azureiot] Breaking exceptions

### ISSUE THREAD

**Issue by MichielVanwelsenaere** [openhab/openhab-addons#3647]
Hi all,

I was very happy to see that there was a binding for Azure IotHub in OpenHAB2.3, playing around with it I'm however encountering some (breaking) issues. Observations:

1. the items are correctly created as devices in the IoThub instance. creation is done when an item receives an update.

2. When I update an item in OpenHAB (a switch for example), an error is logged 

> ERROR com.microsoft.Azure.sd.iot.device.transport.IotHubSendTask - IotHubSendTask constructur called with null value for parameter transport

and no messages arives at the IotHub. This behavior is however not persistent.

3. For no apparent reason the binding logs 'Lost Connection to the server. Reconnecting in 0 time.' several hundred times (my internet connection is however stable)

4. When starting up OpenHAB an error is logged for each item:

```
OpenHAB2_1   | 07:43:58.367 [safeCall-20] ERROR org.openhab.io.internal.azureiothub.CloudClient - Failed to obtain azure device
OpenHAB2_1   | java.io.IOException: Unable to subscribe to topic :devices/DO_01_6/messages/devicebound/# because java.io.EOFExceptionConnection lost
OpenHAB2_1   |  at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:138) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:209) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:184) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at org.openhab.io.internal.azureiothub.AzureDevice.<init>(AzureDevice.java:47) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at org.openhab.io.internal.azureiothub.AzureDevices.getDevice(AzureDevices.java:61) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at org.openhab.io.internal.azureiothub.CloudClient.sendItemUpdate(CloudClient.java:82) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at org.openhab.io.internal.azureiothub.CloudService.receive(CloudService.java:83) [234:org.openhab.io.azureiothub:2.3.0]
OpenHAB2_1   |  at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
OpenHAB2_1   |  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
OpenHAB2_1   |  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
OpenHAB2_1   |  at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [101:org.eclipse.smarthome.core:0.10.0.oh230]
OpenHAB2_1   |  at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [101:org.eclipse.smarthome.core:0.10.0.oh230]
OpenHAB2_1   |  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
OpenHAB2_1   |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
OpenHAB2_1   |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
OpenHAB2_1   |  at java.lang.Thread.run(Thread.java:748) [?:?]
```

Environment: OpenHAB2.3 dockerized

**Comment by kaikreuzer** [comment]
@nikotanghe May I ask you to have a look at that?

**Comment by wborn** [comment]
I think you can fix this by updating the client to 1.4.34 or newer. 
See: https://github.com/Azure/azure-iot-sdk-java/issues/125

**Comment by kaikreuzer** [comment]
Careful - when merging this add-on, I tried to use the latest version of the sdk and miserably failed - I had all kinds of issues, that I do not remember the details anymore...

**Comment by nikotanghe** [comment]
@kaikreuzer, @wborn I also get all kinds of errors when upgrading. Fixing them one by one...it's a slow process with a lot of googling involved...

**Comment by shanekuz** [comment]
Did this get resolved as im having the same issue with the NULL values and then it timing out.

**Comment by Petorrrrr** [comment]
> Did this get resolved as im having the same issue with the NULL values and then it timing out.

Same here. Any update on the progress would be appreciated

**Comment by shanekuz** [comment]
Not from what I can see so I can’t use it unfortunately

**Comment by shanekuz** [comment]
Is there any way we can get something added so we can select which devices send updates?  This might resolve the NULL issue as then items like amps source and volume etc. wont show null when they are powered off.  If we had a way in a config file or something like that to add items that we want to send to IOTHUB this might just fix the issues we are having here.   Im really keen to use this plugin but at the moment cant and it sounds like the permanent fix it some time off.

**Comment by AdamKamizelich** [comment]
What is the current status? Any plans for any fix introduction? My Azure Iot Hub Connector in OpenHAB in v2.4.0 has exactly the same issue.

**Comment by davidgraeff** [comment]
Maintainers here are not responsible to keep addons working.
Only the initial binding contributor or any other interested party will fix this.

**Comment by adamkamizelich** [comment]
Thanks for the info.

@nikotanghe could you provide me more information about eventually fix?

**Comment by nikotanghe** [comment]
The main problem with this issue back then was the maturity of the Azure IOT java library. This bug was fixed in a later version of the library that used in the binding. But unfortunately I wasn't able to upgrade the library and make it work due to various issues and things that were refactored.
However, this was 1 year ago, maybe I can try again.

**Comment by adamkamizelich** [comment]
It would be great :) Thanks for the support.

**Comment by shanekuz** [comment]
Any update on this?   The ideal fix for this seems simple, like for other persistence bindings there should be a persistence file and if the item is in this file then its state changes are send to IOT HUB.

If this was added to the code i feel this would resolve all of our issues. Im still really keen to use this but cant due to NULL values stopping the binding.

**Comment by davidgraeff** [comment]
azureiot is not a persistence service, but an IO service (like myOpenHAB or hue emulation). IO Services do not support restrictions on what items are to be sync'ed.

**Comment by J-N-K** [comment]
@nikotanghe is that refactoring the migration to the bnd build system or within the azure iot library?

**Comment by nikotanghe** [comment]
> @nikotanghe is that refactoring the migration to the bnd build system or within the azure iot library?

It's within the java azure iot library (https://azure.github.io/azure-iot-sdk-java)

Azure technology changes too. 
Now there is Azure IOT Hub (automatic) Device provisioning service -> 
https://docs.microsoft.com/en-us/azure/iot-dps/

So a new device is created automatically in the IOT Hub when a new device is broadcasting a (MQTT?) message. This might be a clean way to get around the need of this binding.

**Comment by hmerk** [comment]
closed due to inactivity
