### ISSUE TITLE
[knx] Performance problems in high-load environment

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#3664]
When using the KNX2 binding (or as in my case, a derivative that is built on top of https://github.com/openhab/openhab2-addons/pull/3500 but that does use the same core logic of the KNX Basic binding) in a "high-load" environment, which for the purpose of this discussion define as one whereby the number of KNX Things is >1000, each having at least one Channel, and whereby the number of ETS bus telegrams is >10 per second, then the binding is having performance problems in that sense that there is often - but not always - a delay of up to 5 seconds between the handling of a Command and the corresponding telegram being sent on the KNX bus. Another problem is that the concurrency of KNX actors is out of sync. For example, I have about 40-ish blinds that can be controlled individually, or in groups through a single Group Address. However, I also have scenario's which require a dynamic grouping of those blinds, and that grouping is off-loaded to OH. In short, it means that OH is steering these blinds individually. Due to the performance problems, instead of acting together, the blinds ofter act one after another, due to bus telegrams not being sent quickly enough by the binding.

During the initial development of the ancestor of the KNX Basic binding I also noticed these issues, and at the time I solved this by introducing a degree of concurrency in the binding itself (i.e. the binding had it's own ThreadPool apart from the core ThreadPools in order to chop up stuff). This concurrency was removed in the KNX Basic binding

IMO concurrency should be re-introduced in order to cope with this

**Comment by hmerk** [comment]
closed due to inactivity
