### ISSUE TITLE
[yeelight] Handle device disconnects

### ISSUE THREAD

**Issue by claell** [openhab/openhab-addons#3666]
As announced in https://github.com/openhab/openhab2-addons/pull/3582#issuecomment-393624668:

Noticing when device gets disconnected and also recovering without an error or the need to send a command to the bulb first.

**Comment by claell** [comment]
@daw87 regarding your suggestion of a keepalive request to solve this: It seems like there is something like that already in https://github.com/claell/openhab2-addons/blob/b9d2b3e5518599ce493d9c9554cc177da74bbc12/addons/binding/org.openhab.binding.yeelight/src/main/java/org/openhab/binding/yeelight/lib/device/connection/WifiConnection.java#L78
I don't have experience in this field, do you thing there is a problem with the implementation there causing this problem?

**Comment by hmerk** [comment]
closed due to inactivity
