### ISSUE TITLE
[yeelight] Improve library

### ISSUE THREAD

**Issue by claell** [openhab/openhab-addons#3667]
As announced in https://github.com/openhab/openhab2-addons/pull/3582#issuecomment-393624668:

General improvement of the library
- [ ] Rewrite some parts
- [x] Maybe direct integration into the binding - done in #3673
- [ ] Use a `UPnPDiscoveryParticipant` instead (https://github.com/openhab/openhab2-addons/pull/3582#discussion_r190328872)

**Comment by claell** [comment]
Afaik this has not been done completely. The UPnPDiscoveryParticipant part seems still to be missing. Although I probably won't be the one to implement this, I reopen it, if this is ok.

**Comment by davidgraeff** [comment]
So this is a kind of ToDo list for the binding. I'm not sure if that is a good idea. Look at how many open issues we have. And bug reports getting lost if we allow too many discussion and "future direction" issues.

**Comment by claell** [comment]
Exactly. I think it depends a bit on what this issue tracker is or should be used for. Many open issues **can** be a problem but not necessarily. In my opinion tagging provides enough freedom that enhancement / "future direction" issues can be sorted out from bugs. But that is only my opinion and experience with this.

**Comment by davidgraeff** [comment]
I think it gotten better with the codeowners file that now directly notifies the main contributor and the issue naming pattern. Before that you had to skim through all issues once in a while to find the ones dedicated to your bindings.

Just this one thought: This is open source. Nobody will pick up a random todo list here. If a binding does not work for yourself, you'll fix those parts. So the usefulness of the todo list, which is basically your personal list, is questionable. I have triaged bugs and just closed same-kind issues, 3 years old.

**Comment by claell** [comment]
> Before that you had to skim through all issues once in a while to find the ones dedicated to your bindings.

Ah understood. Makes more sense from that perspective.

> Nobody will pick up a random todo list here.

It is unlikely, but not completely.

> If a binding does not work for yourself

It does work, but there could be improvements made to the code.

> which is basically your personal list

It contains comments from @kaikreuzer from the PR of this binding that did not make it into the initial version but I thought were worth to put into an issue for further improvements of the binding.

> just closed same-kind issues, 3 years old.

Personally I don't like such behaviour, although I know it seems to be common in some or even many projects.

**Comment by hmerk** [comment]
closed due to inactivity
