### ISSUE TITLE
[samsungtv] hostName does not work with fqdn

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#3681]
## Expected Behavior
When configuring a fqdn in the Thing:
```
Thing samsungtv:tv:mytv "My TV" [ hostName="my.private.fqdn" ]
```
The thing should go online

## Current Behavior
The Thing stays offline. When changing the `hostName` to the real IP, the Thing goes straight online.
As I use the fqdn in most other bindings, I'm surprised that this does not work for samsungtv.

Of course I tested the DNS through 
```
ping -c4 my.private.fqdn
```
from the openHAB host, which did work as expected.

**Comment by udo1toni** [comment]
Ah, I see. The point is, the parameter is named `hostName`, while you must not use a hostname...

**Comment by davidgraeff** [comment]
@paulianttila You can use an `InetAddress.getByName` so that IPs and hostnames are accepted?

**Comment by J-N-K** [comment]
@arjanmels, is this still the case in latest snapshot or can we close this issue?

**Comment by udo1toni** [comment]
will have to check this (but please let me wait until 2.5M2 :) )

**Comment by arjanmels** [comment]
@J-N-K Not certain, need to check. Will try to look into it and see if I can fix in the next 2 weeks or so.

**Comment by udo1toni** [comment]
I have checked and can confirm that also a fqdn seems to work. But... 

If using autodiscovery, the TV is almost at once recognised and ONLINE, if using manual configuration (with same parameters), the thing is UNKNOWN. I think this is another issue, so I'm closing this one...
