### ISSUE TITLE
[knx] Can not change DPT for Type "number", only 9.001 (default) is working

### ISSUE THREAD

**Issue by fritzrichter** [openhab/openhab-addons#3691]
I am not able to read in a numeric value with any other DPT for type **Number** such as 5.010 as or  7.007. It seems only the default numeric DPT 9.001 is working.

My configuration looks like this:

Type number             : filter_replace_time           "Filterwechsel (h)"             [ga="7.007:<3/2/20"]
Type number             : ventilation_mode              "Lüftungsvoreinstellung"        [ga="5.010:3/2/2+<5.010:3/2/9"]

If I add my custom DPT, the values are simply never processed.

**Comment by kaikreuzer** [comment]
@sjka Could you have a look?

**Comment by AngelosF** [comment]
Notes:
1) I have some Channels with type number and they work with a different DPT than the default.
Example: `Type	number	:	Ch_VL1N		"Channel VL1N"		[ ga="14.028:<3/2/1" ]`

I haven't tested 5.010 or 7.007

2) You shouldn't use the DPT twice in the ga area.  It seems that this doesn't work.
```
Type number : ventilation_mode "Lüftungsvoreinstellung" [ga="5.010:3/2/2+<3/2/9"]
```

Ref;
a) https://community.openhab.org/t/knx2-solved-none-of-the-configured-gas-on-channel-could-handle-the-command/46196/3
b) https://community.openhab.org/t/knx2-mismatch-between-declaration-and-example-of-dpt/46089

**Comment by sjka** [comment]
Nothing to add from my side - the way you configured `filter_replace_time` should actually work fine and `ventilation_mode` suffers from two problems: The DPT must only be specified once at the very beginning, and the "<" must be in front of the GA, not in front of the DPT (although this doesn't make any difference anymore because the DPT has to be dropped at this location anyways).

**Comment by AngelosF** [comment]
another case here: https://community.openhab.org/t/solved-knx2-room-controller-config/58136/6
@fritzrichter did you ever solve this one? Can this issue be closed ?

**Comment by hmerk** [comment]
closed due to inactivity
