### ISSUE TITLE
[yamahareceiver]  Sitemap is not responding properly (or PaperUI)

### ISSUE THREAD

**Issue by Paulchen-Panther** [openhab/openhab-addons#3692]
Hello Openhab Team.

My problem is the (ON/ OFF) reaction of the Yamaha AV receiver RX-V575 with a switch in the Sitemap or in direct use via PaperUI.
The receiver is set up properly in OpenHab and also responds to the ON OFF commands.
The problem, the ON / OFF slider in PaperUI or the linked switches in the sitemap jumps back to off immediately after the receiver is turned on. After a repeated switch on, the slider or switch remains on. Turning off the receiver does not cause this phenomenon. I have noticed this problem since the introduction of the zones.

Log output after turning on the receiver: https://pastebin.com/fhuG87nR
Log output after repeatedly turning on the receiver: https://pastebin.com/2FarqanQ

Hardware used: Raspberry Pi Zero W, Yamaha RX-V575
Version used: openHAB 2.3.0-1 (Release Build)  + yamahareceiver-2.4.0-SNAPSHOT
Environment name and version: openjdk version "1.8.0_152"
Operating System: openHABian 1.4.1

If any Information is needed i submit it.
Thanks in advance for the help.
Paulchen

**Comment by zarusz** [comment]
Hi @Paulchen-Panther, 

Thanks for raising this. I am aware of this issue as I experience a similar behavior on RX-S601D. I also find this slightly annoying. 

The challenge here is that after every command the binding sends it does an immediate status read. Some functions that take longer to execute (eg turning tuner FM on, powering on) hence the status read is wrong. The next status refresh (polled every 60 seconds by default) should reflect the new state albeit this experience is poor.

Adding a simple delay won't do and won't work for all channels. I was thinking how to improve this.
I plan to do a PR for this, but not sure if I find time to do it on my current PR (#3700).

**Comment by zarusz** [comment]
The PR #4155 is somewhat related with this one - it fixes the refresh timer.

I still did not have the time to address the actual glitch that is described as part of this issue. To be done properly it will involve a bit of refactoring of the addon.

**Comment by Paulchen-Panther** [comment]
Thank you for your message. Unfortunately, the problem still exists with your current PR. If I turn on the Yamaha receiver with OH2, the receiver goes on and the status jumps from on to off. After the ThingUpdatedEvent, OH2 shows me that the receiver is switched on. The annoying thing is, the OH2 rule that turns on the subwoofer via a Sonoff S20 responds instantly and then turns off the subwoofer too.

**Comment by zarusz** [comment]
Yes, that behavior is still (unfortunately) expect with the PR mentioned.

Can you please clarify which power channel do you use? 
The bridge or the zone thing (i.e. `yamahareceiver:zone:yamaha:Main_Zone:zone_channels#power` vs. `yamahareceiver:yamahaAV:yamaha:power`). Ideally please check both.
