### ISSUE TITLE
[seneye] Binding fails with a wrong data type error

### ISSUE THREAD

**Issue by MickUrsell** [openhab/openhab-addons#3710]
When running the Seneye binding on OH2.3 running on a Win 10 machine
I get an error every time it tries to download data, the error is:-
2018-07-04 09:12:07.182 [DEBUG] [inding.seneye.internal.SeneyeService] - failed to read seneye ‘java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 113 path $.wrong_slide’
No data is displayed.

Also to get the binding to go online I had to change the thing description from:-
seneye:seneye:mySeneye (as shown in the examples) to seneye:monitor:mySeneye I believe this is a deliberate change that just needs to be shown in the examples.

Apologies if I haven't reported this correctly as this is the first time I have tried to do this!

Mick

**Comment by MickUrsell** [comment]
Update, the error appears to be caused when the slide in the Seneye has expired.

**Comment by hmerk** [comment]
closed due to inactivity
