### ISSUE TITLE
[openhabcloud] Support for sending images, not just icons

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#3715]
It would be nice to have the ability to send images via openHAB cloud notifications, e.g. an image from a webcam. See https://community.openhab.org/t/myopenhab-cloud-push-notifications-with-picture/47404

**Comment by kschu91** [comment]
Hi folks, any updates this? Would love to see that feature coming 🙂

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by mueller-ma** [comment]
@hmerk Why has this issue been closed? IMO this is a valid feature request with seven 👍

**Comment by hmerk** [comment]
@mueller-ma This feature request has been open for 3 years now with nobody showing up to implement it. How long do you think we should keep such requests open ?
