### ISSUE TITLE
[loxone] Support for analog virtual inputs from Loxone

### ISSUE THREAD

**Issue by sstroot** [openhab/openhab-addons#3744]
## Expected Behavior

Support for analog virtual inputs from Loxone.

## Current Behavior

Only digital virtual inputs are shown as channels.

## Possible Solution

Map analog virtual inputs from Loxone as number in openHAB.

## Steps to Reproduce (for Bugs)

1. In Loxone add a virtual input
2. Remove "Use as digital input"
3. Upload Loxone configuration
4. The virtual input is not shown as a channel

## Context

I've a Gardena humidity sensor in garden. Gardena is connected fine with the openhab binding, Loxone too. I would like to send the humidity value from the sensor to a analog virtual input in loxone.

## Your Environment

* Version used: 2.3
* Operating System: openhabian 1.4.1

**Comment by ppieczul** [comment]
@sstroot this should be supported as part of #2905 commit. Could you check if it works for you? There should be Slider or UpDownAnalog or LeftRightAnalog channel depending on the type of virtual input.
