### ISSUE TITLE
[lgwebos] Changing tv channel switches from tv to radio mode

### ISSUE THREAD

**Issue by thovoigt** [openhab/openhab-addons#3781]
## Expected Behavior
When changing the channel of the tv with a INCREASE or DECREASE command the current mode (tv/radio) should be the same as before the change.
Additionally an item to switch the mode would be appreciated.

## Current Behavior
TV is on, showing a tv program (Das Erste HD) on channel 23. If I send an INCREASE command to the LGWebOSTV_Channel item the tv changes to channel 24 (TSF JAZZ) BUT IN RADIO MODE.

events.log shows:
2018-08-02 18:22:07.140 [ome.event.ItemCommandEvent] - Item 'LGWebOSTV_Channel' received command 24
2018-08-02 18:22:07.142 [vent.ItemStateChangedEvent] - LGWebOSTV_Channel changed from 23 to 24
2018-08-02 18:22:10.091 [vent.ItemStateChangedEvent] - LGWebOSTV_ChannelName changed from Das Erste HD to TSF JAZZ

## Possible Solution
Detect the mode, in which the tv set is currently in. Store the mode and respect it while changting channels. 

## Steps to Reproduce (for Bugs)
1. start tv set in tv mode
2. send INCREASE command to the LGWebOSTV_Channel item
3. tv set changes to radio mode

## Context
Trying to remote control my LG WebOS tv set via openhab2. 

## Your Environment
openhab2-2.3.0-1.noarch
binding-lgwebos - 2.3.0
openSUSE Leap 42.3
LG TV 42LB650V-ZN, Software Version 05.05.55, webOS 1.4.0-2529

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by lolodomo** [comment]
@hmerk : why closing a feature request ? Maybe one day someone would find time or interest to implement it.

**Comment by hmerk** [comment]
I closed it, as it is 3 years old now with nobody interested in implementing that feature.
How long should we keep such things open ?

**Comment by lolodomo** [comment]
I think we should close very old issue after requesting feedback and noone answerrd.
But I am clearly less convinced by feature request. The current one makes sense. I just did not take time to implement it because we have no DVB-T radios in France,

**Comment by hmerk** [comment]
Ok, so feel free to reopen this one and leave a comment on the actual state. If you like, we can assign it to you.

**Comment by kaikreuzer** [comment]
> But I am clearly less convinced by feature request.

I'd think that especially feature requests can be closed after some time. Reality is that it is very easy to think of potential features, while having them implemented is more unlikely. So if a feature request is not picked up in a reasonable time by a contributor, we should safely assume that it won't be done and rather close the issue to keep a better overview. Anyhow, if something is still picked up, it can always be re-opened and it will also still be found by googling or Github search.
Would you be fine with that @lolodomo?

**Comment by lolodomo** [comment]
I understand your point of view.
That's ok for me.
