### ISSUE TITLE
Clean up documentation which use an unclear textual configuration

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#3871]
Some bindings use an unclear syntax for textual configuration in their documentation (e.g. [Netatmo](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.netatmo/README.md)).

```
Bridge netatmo:netatmoapi:home [ clientId="<CLIENT_ID>", clientSecret="<CLIENT_SECRET>", username = "<USERNAME>", password = "<PASSWORD>", readStation=true|false, readHealthyHomeCoach=true|false, readThermostat=true|false, readWelcome=true|false] {
    Thing NAMain    inside  [ id="aa:aa:aa:aa:aa:aa" ]
    Thing NAModule1 outside  [ id="yy:yy:yy:yy:yy:yy", parentId="aa:aa:aa:aa:aa:aa" ]
```

```
Bridge netatmo:netatmoapi:home "Netatmo API" [ clientId="*********", clientSecret="**********", username = "mail@example.com", password = "******", readStation=true, readThermostat=false] {
    Thing netatmo:NAMain:home:inside "Netatmo Inside"  [ id="aa:aa:aa:aa:aa:aa" ]
    Thing netatmo:NAModule1:home:outside "Netatmo Outside"  [ id="bb:bb:bb:bb:bb:bb", parentId="aa:aa:aa:aa:aa:aa" ]
```

According to the [ESH](https://www.eclipse.org/smarthome/documentation/features/dsl.html#defining-bridges) docs the first one is the preferred way to use. So the syntax is  `Thing <thingTypeId> <thingId> []` . As a short cut it is possible to skip the `Thing` in the textual configuration.

I suggest to clean up all those different occurrences and reach an agreement on a preferred way how to use it.

Is this a possible check for the SAT tool?

**Comment by lolodomo** [comment]
Do you want to keep this open as the change was done for the netatmo binding ?

**Comment by cweitkamp** [comment]
In general I want to keep this issue because it occurs in others than the Netatmo documentation.

**Comment by hmerk** [comment]
@cweitkamp Should this still kept open ?
