### ISSUE TITLE
[smaenergymeter] Support for additional values

### ISSUE THREAD

**Issue by chas0rde** [openhab/openhab-addons#3878]
## Expected Behavior

Additional values read from SMA Energy Meter
- Total PV Generation
- Total Power Consumption
- Self-sufficiency quota
- Self-consumption rate

## Current Behavior

Only Grid feed-in energy, Grid feed-in power purchased energy and purchased power are shown

## Possible Solution

Not sure if the values I wish for are even available directly from the meter.
I use an SMA Home Manager 2.0 which at least works with the four currently available values

## Steps to Reproduce (for Bugs)

1.
2.

## Context

Try to get a more detailed view into power usage and generation. Also this would allow to have local logging of all power metrics (some of which currently are only available to me cloudbased)

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
SMA Home Manager 2.0

**Comment by DeepThoughtZero** [comment]
I got a SMA SHM 2.0 and a STP500TL wired to my LAN. Using the Sunny Portal, I can see the grid interface power and also my inverter power to calculate the self-sufficiency quota as well as the self-consumption rate. Therefore, I guess all the information shall be somehow accessible in the network.

I am controlling my heat pump using openHAB and the SG Ready interface. With the SMA Energy Meter Binding, I am considering the grid power only. It would be great to take the PV generation into account as well.

**Comment by Homer-Sim** [comment]
Is there a chance to add

powerConsumtion [W]  how much energy is the house cosuming independet if it is feed by sun or grid
powerGeneration [W]  how much power is generated by solar panels not reduced by house consumtion
energyConsumtion [kWh]  same as above as a sum of Consumtion in total
energyGeneration [kWh]  same as above as a sum of Generation in total

**Comment by kandersen01** [comment]
These values should be possible to get form a SMA Energy Meter. 
https://www.youtube.com/watch?v=ZdgHKEg3pQU&t=
I sure would like to see the binding supporting this.

**Comment by hmerk** [comment]
closed due to inactivity
