### ISSUE TITLE
[panasonictv] Add Panasonic Viera TV Binding

### ISSUE THREAD

**Issue by scienty** [openhab/openhab-addons#3904]
## Expected Behavior
Enhancement, implement panasonictv binding for oh2 using upnp services

## Current Behavior
Legacy binding for panasonictv works in many cases but there are better features in oh2 to handle upnp communication and discovery

## Possible Solution
Implementation done, creating issue for pull request, please assign it to me

**Comment by Mikeatthezoo** [comment]
Hello - is this expected to address the issues with later Panasonic TVs / HTTP 500 when trying to issue commands?

**Comment by hmerk** [comment]
closed due to inactivity. All related PRs have been closed before finished.
