### ISSUE TITLE
[zoneminder] Server status remains offline with version 1.32.0

### ISSUE THREAD

**Issue by tb205gti** [openhab/openhab-addons#3942]
Ubuntu, Openhab daily unstable.

Since Zoneminder has changed the login/logout in 1.32.0 and later the binding is no longer working properly.

Zoneminder Server status is: Offline, Configuration error

**Comment by poutnik** [comment]
Ubuntu, Openhab stable, Zoneminder 1.32.0.

Zoneminder version 1.30.4 was working well with Zoneminder binding. Since updating to version 1.32.0, it stopped working as tb205gti has written. With the same status message.

**Comment by openhab-5iver** [comment]
The Zoneminder API has changed. The binding has not been updated yet, but here is a workaround...

https://community.openhab.org/t/zoneminder-binding-in-marketplace-beta/39697/35?u=5iver

**Comment by poutnik** [comment]
No, unfortunatelly the workaround seems not to work anymore for me. The error message is:

Status: OFFLINE - CONFIGURATION_ERROR Cannot access ZoneMinder Server. Check provided usercredentials

and in the logs I can see:

[BRIDGE (f9092544)]: Exception occurred in updateAvailabilityStatus Exception='com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 6
 path $'

**Comment by tb205gti** [comment]
Workaround is not working for me - 1.32.0 :/ I still get the same error: 

Status: OFFLINE - CONFIGURATION_ERROR URL not a ZoneMinder Server

**Comment by tb205gti** [comment]
No progress is being made on the issue? I'm really missing my zoneminder binding in Openhab :/

**Comment by JMAnguita** [comment]
Some news about this?

**Comment by JMAnguita** [comment]
Here are the both API logins. It doesn't appear difficult to adapt the old bindind.

**Comment by e10kstarfire** [comment]
Same issue here, any progress possible please ?

**Comment by tb205gti** [comment]
Yes please, if I can assist in any way - let me know. I'm really missing this one.

**Comment by tb205gti** [comment]
Ok, I assume this is dead then.. :/

**Comment by underdog** [comment]
Has there been any progress on this issue.  the workaround with the update proposed to the DB with the path fix doesn't appear to work in 1.32.2.

**Comment by fastlorenzo** [comment]
same issue here using zoneminder 1.32.4
I tried disabling authentication but then I receive the error: 
`'zoneminder:server:ZoneMinderMain' changed from OFFLINE (CONFIGURATION_ERROR): Cannot access ZoneMinder Server. Check provided usercredentials to OFFLINE (CONFIGURATION_ERROR): URL not a ZoneMinder Server`

Any plan to update this binding? If you need some help/testing let me know.

**Comment by openhab-5iver** [comment]
In case this helps anyone...

https://community.openhab.org/t/zoneminder-binding-in-marketplace-beta/39697/53?u=5iver

**Comment by el00ruobuob** [comment]
The workaround has to be modified with latest zoneminder version, because Config table Ids are been used for other stuffs:  
https://community.openhab.org/t/zoneminder-binding-in-marketplace-beta/39697/59?u=el00ruobuob

**Comment by Tcsekhar74** [comment]
Can someone please share details on how you fixed Openhab communicating with ZoneMinder?

**Comment by ringnutz** [comment]
I downgraded zoneminder, didn't have time to mess with it

**Comment by Tcsekhar74** [comment]
Any option to use ZM_AUTH_HASH_SECRET to integrate ZoneMinder with Openhab?

**Comment by Tcsekhar74** [comment]
@ringnutz can you please let me know how you downgraded to a prior version? Where did you download zoneminder older version from?

**Comment by rb1205** [comment]
You should use your distribution package to do that

**Comment by hmerk** [comment]
closed due to inactivity
