### ISSUE TITLE
[lutron] Add support for window blinds

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab-addons#3962]
I have an enhancement to the Lutron binding that adds support for Lutron venetian blinds and horizontal sheer blinds on RadioRA 2 systems. It should also work with Lutron blinds on other systems that support the Lutron Integration Protocol (e.g. Homeworks QS and Caseta Pro). It has not yet been sufficiently tested to create a PR for it.

A brief description from the updated README.md file:

Each Lutron venetian blind or vertical sheer blind is controlled by a “blind” thing. The only configuration parameter it accepts is integrationId. 

Two channels, blindliftlevel and blindtiltlevel, with item type Rollershutter and category Rollershutter will be created for each shade thing. They control the up/down motion and the slat tilt motions of the blinds, respectively. Each channel accepts Percent, Up, Down, Stop and Refresh commands.
Sending a Percent command will cause the blind to immediately move so as to be open or tilted the specified percentage. You can also read the current setting from each channel. It is specified as a percentage, where 0% = closed and 100% = fully open. Movement delays are not currently supported.

**Note:** While a blind is moving, the Lutron system will report the target position for the blind rather than the actual current position.

**Comment by cweitkamp** [comment]
Is this issue this related to #3911?

**Comment by bobadair** [comment]
No. I probably should have explained that a bit more. PR #3911 is for shade control (i.e. roller shades, pleated shades, roman shades) and also motorized drape/curtain control.  Basically all devices with just one motor that can position them somewhere between open and closed.  The RA2 system describes them all as "SYSTEM_SHADE".

This issue is for blinds, e.g. devices like venetian blinds and horizontal sheer blinds.  They have one control for raise/lower, and one for slat rotate up/down.  The RA2 system calls these "VENETIAN_BLIND" or "SHEER_BLIND". They use a different set of commands, even for raise/lower, for some reason. So they need a separate handler.

I'll eventually be creating a new PR for this one.

**Comment by cweitkamp** [comment]
Thanks for clarification. I was a little bit confused because the description sounds similar to #3911.
