### ISSUE TITLE
Running openHAB2, build #24 (18.07.2014 03:01:53)

### ISSUE THREAD

**Issue by lcis** [openhab/openhab-addons#4]
Hi,
I wanted to test openHAB2 but I got an error accessing openhab with the browser:

http://localhost:8080/openhab.app?sitemap=demo

> HTTP ERROR 404
> Problem accessing /openhab.app. Reason:
>     >ProxyServlet: /openhab.app
> Powered by Jetty://

(openhab 1.5.0 works on my mac)

**Comment by yveshanoulle** [comment]
on https://github.com/openhab/openhab/wiki/Linux---OS-X#aptitude a similar documentation exists.
And I have troubles with both

**Comment by yveshanoulle** [comment]
I have the same error yet for the demo of 1.6.2.
What is the correct way to debug this?

**Comment by kaikreuzer** [comment]
This issue is about openHAB 2. Please note that the url is simply http://localhost:8080/

**Comment by yveshanoulle** [comment]
yes I know this is about 2-openHab 2,0, yet when I query for the same error in 1,6,2, I don't find any links. 
So' Im' trying to figure out how to debug this. 
(I'm rather New to openhab, raspberry pi and linux)

**Comment by kaikreuzer** [comment]
If you need help on 1.6.2, the best start would be to ask the question in the right forum :-)
https://groups.google.com/forum/#!forum/openhab

**Comment by consolacion** [comment]
i know this is closed but I see one reply missing: one sees this sometimes when another process is occupying the 8080 port

**Comment by aycgit** [comment]
this bug still exists as of 9-6-2017 with an apt-get install on raspian

**Comment by kaikreuzer** [comment]
No, there is no bug here, see my https://github.com/openhab/openhab2-addons/issues/4#issuecomment-76541810.

**Comment by aycgit** [comment]
i guess my error is something else, i am trying a clean manual install now, this seems like a cool project so i hope to get it working.

**Comment by kaikreuzer** [comment]
It definitely is a cool project :-)

After a clean install, you should definitely be able to see something at http://localhost:8080.
In case of problems, best join our community at https://community.openhab.org/ and ask for help there!
