### ISSUE TITLE
[lgwebos] Items are updated but commands don't work

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-addons#4055]
Hello,

Install and try plugin for LG WebOSTV. Successful Pair device. but all items works in Read only mode. Example, if I enable Mute button TV, then I see it on my panel... But if I try to Enable/Disable Mute from openhab, then nothing works.

Ed

**Comment by lolodomo** [comment]
@Bl00d-B0b : do you have this this problem with the binding in OH 2.5 ?
I think this issue can be closed now.
@sprehn for information.

**Comment by lolodomo** [comment]
I close this very old issue because we have no feedback from the user.
