### ISSUE TITLE
[knx] Serial communication with cEMI

### ISSUE THREAD

**Issue by KHBuchner** [openhab/openhab-addons#4126]
I try to combine openhab2 with a Weinzierl kBerry 838 on a raspberry pi 3B. The kBerry 838 is an addon board for raspberry which uses cEMI over a serial Ft1.2 connection. The board is marked as connected in openhab paper UI, but when I send group telegrams from openhab, there is no reaction on KNX. I looked deeper into the serial communication, and watched valid link layer telegrams from raspberry, but in EMI2 format. I'm no expert in openhab or calimero, but it seems that SerialClient is used in openhab for serial connection, which uses KNXNetworkLinkFT12 from calimero (https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/client/SerialClient.java and https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/link/KNXNetworkLinkFT12.java) . In this driver it seems that cEMI is always switched off. Is there a possibility in openhab to use a serial connection with cEMI?

**Comment by dddjjjppp** [comment]
I would be also very interested in having cEMI enabled to get kBerry 838 working with OpenHAB

**Comment by dddjjjppp** [comment]
The solution seems to be in
https://github.com/shabunin/org.openhab.binding.kberry

**Comment by petero-dk** [comment]
The solution linked above (the extra compiled by @shubunin) does not seem to receive data. However there was a new commit to the Calimero project which enables cemi communication and as far as I can tell both for sending and receiving. 
https://github.com/calimero-project/calimero-core/commit/b322db4f8bb7949e3d35299750049813d99cb25c

How long does it take for these changes to be reflected in the knx2-addin?

**Comment by petero-dk** [comment]
I have added a #5964 for the required code in the KNX binding, but I have not (yet) referenced the latest calimero - since I do not know how to do that.

**Comment by petero-dk** [comment]
I have managed to rebuild calimero in a build process that recompiles any new calimero to java8 but I have run into an issue with openHAB giving no messages about the new add-on, help needed: https://community.openhab.org/t/modified-addon-does-not-load-nor-gives-any-errors-both-on-openhabian-and-eclipse-launched/81579/1

**Comment by petero-dk** [comment]
Just to follow up. I have managed to backcompile the latest calimero source to work with openHAB (see here: https://github.com/petero-dk/javacrosscompiler) additionally I have set up a custom built of the latest KNX binding to use those new libraries:

[Latest KNX with latest calimero build service](https://zealofzebras.visualstudio.com/openHAB/_build/latest?definitionId=43&branchName=2.5.x)

**Comment by hmerk** [comment]
closed due to inactivity
