### ISSUE TITLE
[neato] Add option to find secret

### ISSUE THREAD

**Issue by yveshanoulle** [openhab/openhab-addons#4185]
## Expected Behavior
I would like to configure the neato account class with a user name and password and then get in the log file the secret that is needed to create the neato:vacuumcleaner.
I expect that I can delete the neato:account and it's user name and password from my neato.things after I found the secret.

## Current Behavior
At this moment, we need to install and use an external python script to figure out the secret.
For me, I want to avoid to need that. + I think it makes things a lot more complicated.

## Possible Solution
I assume that the python script contains the needed code to get to secret.

## Your Environment
* My openhab is completely configured from scripts, nothing is discovered from the paperui.
(most of the time that is not even installed.) This way all changes that I make to my configuration can be found in my source control system.

**Comment by jjlauterbach** [comment]
I think you can get the values you're after by adding the Neato Acount bridge and then automatically discovering the vacuum.  Then in PaperUI, edit the Thing for the vacuum.  In there, you'll find the robot serial number and secret.

**Comment by yveshanoulle** [comment]
As I said:

My openhab is completely configured from scripts, nothing is discovered from the paperui.
(most of the time that is not even installed.) This way all changes that I make to my configuration can be found in my source control system.

**Comment by stuart475898** [comment]
Just as an FYI for anyone trying to easily get the serial number of their BotVac, I noted if you turn logging up to trace on the Neato binding and then add the account thing, it will output the JSON returned from the Neato API that includes the secret for each robot.

**Comment by hmerk** [comment]
closed due to inactivity
