### ISSUE TITLE
[chromecast] Audio Groups IP's dont get updated when the group moves to another member

### ISSUE THREAD

**Issue by chriscolden** [openhab/openhab-addons#4186]
As the title states, the audio group's dont get updated when the group moves to another member. Ie the group is now master on another chromecast which is in the group.

I dont know if this is a more widespread issue where things of the other types dont get updated either, as I use fixed IP with dhcp reservations. So these never change.

Please let me know what information you need. I cannot really tell when one will move, but i can force it by turning the one its currently hosted on off.

Thanks
Chris

**Comment by jim77** [comment]
I tried installing the latest snapshot for the chromecast addons:

> openhab> bundle:list -s |grep chrome
> 230 │ Active   │  80 │ 2.5.0.201905061836     │ org.openhab.binding.chromecast
> 231 │ Active   │  80 │ 0.11.0                 │ su.litvak.chromecast.api-v2

However, I can't see where this "deviceId" is being used. The thing configuration still requires an ip address and port number, and not deviceId.
