### ISSUE TITLE
[knx] Binding keeps sending T_Disconnect telegrams to ETS5 causing device upgrade failures

### ISSUE THREAD

**Issue by JoveToo** [openhab/openhab-addons#4238]
I am using ETS5 to manage my KNX home automation and OpenHAB2 to allow me to turn everything on or off using the Android app and my computer.

However, if OpenHAB2 is running while I am performing a device upgrade, it keeps sending T_Disconnect telegrams to my ETS5 and the device in question, making everything slower and eventually even failing the device upgrade.

## Expected Behavior
OpenHAB2 KNX binding does not interfere with traffic that doesn't concern it.

## Current Behavior
OpenHAB keeps sending T_Disconnect messages to ETS5 and the device in question, slowing everything down and failing the device upgrade.

## Possible Solution
Ignore traffic that doesn't make sense.

## Steps to Reproduce (for Bugs)
1. Perform an Application download in ETS5

## Context
These are telegram logs made with ETS5, unless you read bus telegrams, they may not be useful.

This is a normal communication cycle:

> &lt;CommunicationLog xmlns="http://knx.org/xml/telegrams/01"&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:08:10.0223791Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B05011100001064E437A5CA70281"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:08:10.0228001Z" Service="L_Data.con" FrameFormat="CommonEmi" RawData="2E00B0600001111000CE"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:08:10.0232449Z" Service="L_Data.con" FrameFormat="CommonEmi" RawData="2E00B06000011110037E0A7B97"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:08:10.0845369Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B0501110000100FE"/&gt;
> 
> &lt;/CommunicationLog&gt;

While this is one when OpenHAB2 is active:

> &lt;CommunicationLog xmlns="http://knx.org/xml/telegrams/01"&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.3223658Z" Service="L_Data.con" FrameFormat="CommonEmi" RawData="2E00B06000011110036E0C5578"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.3452345Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000200010081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.3452982Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000200010081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.6530256Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B0501110000100EE"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.6540195Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000211100081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.6541099Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000211100081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.7566596Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B050111000010F424C55780FA1042603C7023AC6031B27"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.756963Z" Service="L_Data.con" FrameFormat="CommonEmi" RawData="2E00B0600001111000C2"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.7579076Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000211100081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.757972Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000211100081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.7580272Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000200010081"/&gt;
> 
> &lt;Telegram Timestamp="2018-11-17T18:01:45.7580837Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900B060000200010081"/&gt;
> 
> &lt;/CommunicationLog&gt;

## Your Environment
OpenHAB 2.3 running on CentOS 7

**Comment by lewie** [comment]
@JoveToo, need more about your environment!

- KNX Interface/Router/Eibd/serial/combination?
- Programming with ETS5 in Router-Mode (Broadcasting with 224.0.23.12) or Tunnel-Mode (direct fixed connection to your named Interface/Router)
- Settings (if IP Interface), especially if addresses above 14/15 are blocked or not.

But it is definitive no Bug! The limits are set by the quality of the used Interface/Router.
Normally this behavior happens, while ETS works in Tunnel-Mode AND another Actor like openHAB holds a Tunnel-Mode connection to the IP-Interfacs/Router too. The Interface has to filter AND resent to second connection too much telegrams at same time. 

Especially older ABB and Siemens IP Interfaces could handle only badly two Tunneling connections while programming with ETS.

Therefore Routing-Mode should be always the preferred connection. Routing needs no feedback and more scalable. This effect is similar to blocking or non-blocking web servers. Routing-Mode is none Blocking and can handle a lot more requests at the same time.

To prevent brutally, unplug the cable of openHAB for the time of programming. 
Better, if you have a Router, switch openHAB to Routing-Mode. 
Best/most modern, always use Routing-Mode.

It seams for me, lastly the problem arises in calimero, the KNX library we use, not in the openHAB Binding itself.

**Comment by JoveToo** [comment]
I am using a KNX Router (that also supports tunneling but this is not used afaict) and programming with ETS5 in router mode (Broadcasting with 224.0.23.12).  There is also an EIBD with LinKNX running on the same machine as OpenHAB, both of which are in router mode. The router is built into my powersupply (Elsner PS640-IP).

Why would OpenHAB react to traffic not addressed to it?  It is sending 2 T_Disconnect messages (according to ETS5) for every message sent during the programming. This tripples bus activity for no reason whatsoever.

Perhaps there is a misconfiguration somewhere but then I'd like to understand in which cases such a T_Disconnect message is sent.

**Comment by JoveToo** [comment]
This is the configuration of my router:

![routerconfig2](https://user-images.githubusercontent.com/18113628/48676739-45ceaa00-eb6b-11e8-9529-369a26b64f32.PNG)
![routerconfig1](https://user-images.githubusercontent.com/18113628/48676740-45ceaa00-eb6b-11e8-99a3-735ee02fd54e.PNG)

And these are the translated traces:
_Without openhab:_
![noopenhab_trace](https://user-images.githubusercontent.com/18113628/48676741-45ceaa00-eb6b-11e8-8119-1f19b50be99c.PNG)

_With openhab:_
![withopenhab_trace](https://user-images.githubusercontent.com/18113628/48676742-46674080-eb6b-11e8-9240-f9b054b9cadf.PNG)

**Comment by lewie** [comment]
@JoveToo, 
Your configuration is no source of error!
Basic behavior and the curse and blessing of such a bus is the fact that everyone can scream into it and only the receivers decide if they react. 

>Why would OpenHAB react to traffic not addressed to it?
Unfortunately, I do not know the deeper connections on the side of the device programming and in particular I do not know the meaning of a "T_Disconnect" telegram and when it is sent or must be.

In order to experience this, there are people who are familiar with it.

**Comment by JoveToo** [comment]
@lewie Thank you :)

**Comment by lewie** [comment]
@sjka, @kgoderis, do you have an idea to stop these weird sequence?

**Comment by dmiorandi** [comment]
Same slow down behavior (very slow down when use ETS4 + openhab via eibd tunnel while shutting down openhab it works). Eibd connect to bus via Siemens Ip interface.
I've bought a new http://busware.de serial interface to throw away siemens module implementing
this https://github.com/knxd/knxd/wiki/Adding-a-busware-pigator-KNX-TPUART-(Raspberry)
direct on same openhab raspberry hardware.

**Comment by JoveToo** [comment]
There was a fix to Calimero for this issue, not sure when and if this will it to OpenHAB.

**Comment by dmiorandi** [comment]
Probably @JoveToo you mean this commit

https://github.com/calimero-project/calimero-core/commit/658567236938cc3e189f10aec450e84d71a13f22

that solve this

https://github.com/calimero-project/calimero-core/issues/77

isn't it?

**Comment by JoveToo** [comment]
@dmiorandi Yes, that's the one.

**Comment by lewie** [comment]
@dmiorandi, @JoveToo,
here you can find a KNX binding Version with bmalinowsky's [fixes ](https://github.com/calimero-project/calimero-core/commit/658567236938cc3e189f10aec450e84d71a13f22) for https://github.com/calimero-project/calimero-core/issues/77

[Testfile_calimero-2.4-rc2-6585672](https://github.com/lewie/openhab2/raw/Testfile_calimero-2.4-rc2-6585672/addons/binding/org.openhab.binding.knx/org.openhab.binding.knx-2.5.0-SNAPSHOT.jar)

Please can you test this Version? If your feedback is positive I will make a PR.

Install Testfile:
uninstall current running KNX binding. [optional: restart openHAB]. Then put Testfile in addons Folder.

**Comment by JoveToo** [comment]
Uninstalling the knx binding will not remove the knx data?

**Comment by lewie** [comment]
No, it doesn't! You only should uninstall knx binding itself, not your Bridge or Things:
![grafik](https://user-images.githubusercontent.com/5707426/50727454-6b177780-111b-11e9-841b-94331e962734.png)

**Comment by perrin-1** [comment]
I am having the same issue - ETS5, IP Router (in my case Siemens N146/02). OPenhab is sending T_Disconnect when updating a KNX device. Is there already a PR?

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by matzetronic** [comment]
Hi,
I just wanted to let you know that this issue still exists. I just discovered it with OpenHAB 3.3.0 and ETS 6.0.6. This is especially frustrating if you like me just start with ETS and you think you are doing something wrong and then find out it is a long existing bug in OpenHAB/knxd 😞

So if this is not fixable, I would at least expect that there is a note to this bug in the documentation of the [knx addon](https://www.openhab.org/addons/bindings/knx/). I can also add it if you want.

thanks,
Mathias

**Comment by JoveToo** [comment]
From what I can tell, this fix is included in calimero 2.5.1, while openhab includes 2.5.

**Comment by wborn** [comment]
> From what I can tell, this fix is included in calimero 2.5.1

Where do you see this fix and 2.5.1 release?

**Comment by JoveToo** [comment]
> Where do you see this fix and 2.5.1 release?

https://github.com/calimero-project/calimero-core/releases/tag/v2.5.1

Link to the fix is in this issue: https://github.com/openhab/openhab-addons/issues/4238#issuecomment-451082420

**Comment by wborn** [comment]
That fix was merged in 2018 and 2.5 was released in 2021, so I think it already has that fix. 

If you open https://github.com/calimero-project/calimero-core/commit/658567236938cc3e189f10aec450e84d71a13f22 and expand the tags you'll also see it's already in 2.5:

![image](https://user-images.githubusercontent.com/12213581/196054014-35100db6-8337-453c-93fb-f439344fad90.png)

**Comment by JoveToo** [comment]
Then there isn't a fix :(
