### ISSUE TITLE
Add Mobile Alerts Binding

### ISSUE THREAD

**Issue by geeks-r-us** [openhab/openhab-addons#4249]
Hi,

I'm working on a binding for the MobileAlerts ecosystem: 
http://www.mobile-alerts.eu/

Basically there is a network gateway, wireless devices communicating over the gateway with a cloud and an app that shows the measurements and allows to set some alarms. 
They offer a rest API which is limited to query the devices of the pro series.

There are two other ways to collect the data:
### Screen scrapping 
the online view (https://measurements.mobile-alerts.eu) which is already working for some devices(the example sensors):
- MA10320 (temperature / humidity)
- MA10200 (temperature / humidity)
- MA10650 (rain)
- MA10660 (wind)
- MA10800 (door / window contact)
- MA10230 (humidity guard)

But there are still some more so if you own other device types please share the device id with me and I will add the type.

### Proxy 
setup the gateways to use a proxy which pareses the packages for measurements and forward it (or not) to the cloud. This solution would also allow an total offline usage and would be a good backup strategy if the services closes down. This part is still WIP because I own only some of the devices to analyse the data packages. All input of captured data packages or device donations are welcome.  

I hope you like the idea.
 
You can have a look at it here:
https://github.com/geeks-r-us/openhab2-addons/tree/4249-mobilealerts

**Comment by christoph2806** [comment]
did you see this: 
https://github.com/sarnau/MMMMobileAlerts/tree/master/maserver
there's an implemenation of your proxy idea

**Comment by renderender** [comment]
Are there any news on the proxy-way binding?

**Comment by mailando1** [comment]
Hello, when is the Add Mobile Alerts Binding available, I have some sensors from TFA (probably identical), and would like to test them.

**Comment by geeks-r-us** [comment]
It's in progress. 
web is working well, proxy mode needs still some improvement.

**Comment by renderender** [comment]
So how can i install this Binding?
Can anyone Provide me a little help?

**Comment by ElHoni** [comment]
Hey geeks-r-us,
is there progress in your Mobile Alerts binding?
I am using several mobile alerts item and would like to add theme to OpenHab 2 and test them.

**Comment by goair1** [comment]
Hi together
how i can download the jar File so I can install this one?!

regards

**Comment by m4rky-m4rk** [comment]
I like the idea of a Mobile_Alerts binding but you if your impatient you can also do it without the binding while waiting. See this thread:

https://community.openhab.org/t/mobile-alerts-and-openhab-2/21444

There I and others posted examples of how to get into Openhab items using the sensor web page cache and or API call for the 'pro' devices: rain gauge, wind sensor etc

**Comment by ElHoni** [comment]
Hey everyone,
is the binding already finished and where can I get it to test it?

**Comment by hmerk** [comment]
closed due to inactivity
