### ISSUE TITLE
[max] Thermostat keeps going back to automatic mode

### ISSUE THREAD

**Issue by Gwynnbleid1** [openhab/openhab-addons#4256]
## Expected Behavior
If I set thermostat to Manual mode it should stay in this mode until changed manually or from OH

## Current Behavior
One thermostat keeps going back to automatic mode.
Always when items file with is is changed and after some time (10 minutes or more, see below)
```
2018-11-21 14:24:17.202 [ome.event.ItemCommandEvent] - Item 'Thermostat_PGo_Mode_Setting' received command MANUAL
2018-11-21 14:24:17.231 [vent.ItemStateChangedEvent] - Thermostat_PGo_Mode_Setting changed from AUTOMATIC to MANUAL
2018-11-21 14:37:12.470 [vent.ItemStateChangedEvent] - Thermostat_PGo_Mode_Setting changed from MANUAL to AUTOMATIC
2018-11-21 15:25:04.232 [ome.event.ItemCommandEvent] - Item 'Thermostat_PGo_Mode_Setting' received command MANUAL
2018-11-21 15:25:04.251 [vent.ItemStateChangedEvent] - Thermostat_PGo_Mode_Setting changed from AUTOMATIC to MANUAL
2018-11-21 16:24:03.994 [vent.ItemStateChangedEvent] - Thermostat_PGo_Mode_Setting changed from MANUAL to AUTOMATIC
```

## Possible Solution
It is not a solution but more of a workaround: delete it from cube and add it again (using boost button)

## Steps to Reproduce (for Bugs)
I believe it was due to option "Actual Temperature Refresh Rate" set to 60 minutes previously. 
I have observed this issue in several thermostats and switched this option to 0, but I'm not sure if this is what solved this problem on all of them but the one from logs above

## Context
I'm using manual mode for all my thermostats and when one/some of them changes to auto mode, then it will have different temperature setting which me and my wife esspesialy finds very "disturbing". 
We want 25C and auto had 17C...

## Your Environment
Chrome (newest), android
Openhab installed from packets on Pi 3:
openhab2/stable,now 2.3.0-1 all [installed]
addons installed using config file
Linux pi 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

**Comment by cweitkamp** [comment]
@Gwynnbleid1 Thanks for reporting your issues. Can you please surround your log extract by code fences (three backticks before and after the code) to provide better readability?

**Comment by Gwynnbleid1** [comment]
> @Gwynnbleid1 Thanks for reporting your issues. Can you please surround your log extract by code fences (three backticks before and after the code) to provide better readability?

Done. I tried to do this but didn't know how. Thanks for info!

**Comment by marcelrv** [comment]
to do anything meaningful with this issue, please make a debug log
execute these in the karaf console:

``` 
log:set debug org.openhab.binding.max
log:tail debug org.openhab.binding.max
bundle:restart org.openhab.binding.max
```

than execute your commands that causes the issue you are facing.

Note that the `Actual Temperature Refresh Rate` feature is indeed still marked as experimental. As indeed changes during the 'measuring cycle' your manual input probably gets ignored/overwritten.
In case of issues, you best disable it (setting it to 0).

**Comment by hmerk** [comment]
closed due to inactivity.
