### ISSUE TITLE
[neato] Please add Vorwerk robots

### ISSUE THREAD

**Issue by clown522** [openhab/openhab-addons#4264]
hi!
At first thank you for your great work!
I am not alone with this wish. Could you integrate vorwerk to your binding? It is under the hood the same mechanic. I am sure you only have to add another website to sync the robot. One nice guy has adapted your original binding some time ago to be able to sync with vorwerk. But the version is not the newest anymore V2.0. We have also made a little turorial how to use this modded binding. You can find the modded file and the tutorial here.

https://community.openhab.org/t/connecting-vorwerk-kobold-vr200-to-openhab2/32054

The modded file is here but you have to change the ending from .pdf to .jar:

https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/b/bf0786743d51aea54a913c5f90224f421b6dd803.pdf

We would appreciate it if you could update the binding to support in the future also robots from vorwerk!

**Comment by hmerk** [comment]
closed due to inactivity.
