### ISSUE TITLE
[denonmarantz] Wrong input list for marantz m-cr611

### ISSUE THREAD

**Issue by Keltere** [openhab/openhab-addons#4274]
Hi, i've set my openhab but the input selector it's wrong for my m-cr611.
There are a lot of useless input and missing few.

Internet radio (iradio): working
online music: can't test it
music server (server): working
tuner (tuner): working
analog in: not working
digital in: missing
usb (usb/ipod or usb or ipd): working
bluethooth: not working
cd (cdr): working

another strange thing with the android app i can't change the input. After a long press it opens me the list but if i select something it just ask me for a nfc pairing
(don't mind the red filter)
![screenshot_2018-11-25-13-01-31-030_org openhab habdroid](https://user-images.githubusercontent.com/8084245/48979137-b5d2b800-f0b6-11e8-9219-71cd6f29b84c.png)
![screenshot_2018-11-25-13-01-41-080_org openhab habdroid](https://user-images.githubusercontent.com/8084245/48979138-b8351200-f0b6-11e8-8b5c-319a8c0d0b1c.png)

**Comment by hmerk** [comment]
closed due to inactivity
