### ISSUE TITLE
[pioneeravr] Add missing inputs for Pioneer X-HM82

### ISSUE THREAD

**Issue by koenig-dro** [openhab/openhab-addons#4278]
Still need some Inputs in this Binding.
Following IDs:
51: Audio In
52: Line1
56: BT Audio
58: Line2
59: Digital In
May Somebody Help me?

**Comment by wborn** [comment]
Which Pioneer AVR are you using?

**Comment by koenig-dro** [comment]
it's a Pioneer HM-82

**Comment by wborn** [comment]
Thanks!

**Comment by koenig-dro** [comment]
Will there be any Support?
At this time i only Control Power with this Binding.
Will be cool If there is full Control of Input....

**Comment by hmerk** [comment]
closed due to inactivity
