### ISSUE TITLE
[loxone] Support for Intelligent Heat Controller and Light Controller v2

### ISSUE THREAD

**Issue by jeckyllhavok** [openhab/openhab-addons#4315]
Hi there,
would it be possible to add the Intelligent Heat Controller and Light Controller (Including RGB) Block to the Loxone Binding?

Thanks in advance

JerckyllHavok

**Comment by ppieczul** [comment]
Hi @jeckyllhavok 
Could you describe which features of the Intelligent Heat Controller you would like to see? Best in terms of use cases - how you would like to use them.
Light Controller v2 is supported, could you tell more about what you mean by "including RGB"?
Thanks

**Comment by ppieczul** [comment]
@jeckyllhavok I think I understand "including RGB" - if it means using RGB as a subcontrol of lighting controller, the support for ColorPickerV2 was added as part of #2905. You can check it with that commit.
