### ISSUE TITLE
[KNX] No connection to bus after server restart (router mode)

### ISSUE THREAD

**Issue by FredericMa** [openhab/openhab-addons#4317]
## Expected Behavior
If OpenHAB starts it should correctly connect to the KNX bus and update all items with the current state, even after a full server restart. I never experienced this issue while using the KNX 1 binding.

## Current Behavior
Weird but true story...
After a restart of my server (Windows Server 2012), OpenHAB is not able to connect to the KNX bus correctly.
Polling, reading and writing data always fails. Restarting the KNX binding does not help (bundle:restart org.openhab.binding.knx).
If I launch ETS5, which is also installed on the server and I open the "Bus"-tab (below), so that it discovers the available connections, and restart the bundle after that, it connects correctly. Everything is up and running afterwards.
![image](https://user-images.githubusercontent.com/7840263/49382328-75a6b180-f716-11e8-9e91-a9a824527b44.png)

My interface is configured as follows:
`
Bridge	knx:ip:MDTIP "MDT IP Interface" [
		type="ROUTER",
		localIp="192.168.50.100",
		readingPause=50,
		responseTimeout=10,
		readRetriesLimit=3,
		autoReconnectPeriod=1,
		localSourceAddr="1.2.1" 
	]
`

I included some notes on my actions in the log file. I marked them with short lines of dashes (--------------).
Log file: 
[KNXIssue.txt](https://github.com/openhab/openhab2-addons/files/2640064/KNXIssue.txt)

## Steps to Reproduce
1. Restart complete server (Windows Server 2012).

## Your Environment
- OS: Windows Server 2012
- OpenHAB: 2.4.0-SNAPSHOT build 1422

**Comment by AngelosF** [comment]
@lewie is this a new bug? (localIp overwrites the ipAddress parameter if ipAddress is not set?)

I have:
```
Bridge	knx:ip:GIRA2167 "GIRA KNX/IP Router" @ "KNX" [
	type="ROUTER",
	ipAddress="224.0.23.12",
	portNumber=3671,
	localIp="172.16.13.100",
	readingPause=50,
	responseTimeout=10,
	readRetriesLimit=3,
	autoReconnectPeriod=30,
	localSourceAddr="1.2.200" ]
```

and it works fine

**Comment by lewie** [comment]
@AngelosF
No, neither one nor the other is a bug! Both is absolutely correct!

If `portNumber` and/or `localIp` are not set in your configuration, the binding will do it with the default values:
`localIp="224.0.23.12",`
`portNumber=3671,`

The 'ipAddress' of the gateway must be configured in 'TUNNEL' mode only. 
In ROUTER mode 'ipAddress' internally overwrites the 'localIp' 


```
[
	type="ROUTER",
	ipAddress="224.0.23.12",
	portNumber=3671,
	localIp="172.16.13.100",
	readingPause=10,
	responseTimeout=10,
	readRetriesLimit=3,
	autoReconnectPeriod=30,
	localSourceAddr="1.2.200" 
]
```

is same as:

```
[
	type="ROUTER",
	readingPause=10,
	responseTimeout=10,
	readRetriesLimit=3,
	autoReconnectPeriod=30,
	localSourceAddr="1.2.200" 
]
```

This does not work:

```
[
	type="ROUTER",
	localIp="172.16.13.100",
	readingPause=10,
	responseTimeout=10,
	readRetriesLimit=3,
	autoReconnectPeriod=30,
	localSourceAddr="1.2.200" 
]
```

We need this parameters for very special configurations with parallel multiple Router Networks for example.

**Comment by lewie** [comment]
> I think that one of the 2 is happening:
> Either:
> 
>     1. the Filter table on his KNX Router maybe blocking the routing of the telegrams and when he opens ETS (on the same PC as OH2) he gets routing done correctly
>        Or
> 
>     2. The NIC has multicasting off by default and it is enabled when ETS is fired up
> 
> 
> Maybe it's better to open up a new thread on the community forum to troubleshoot this

Is this new or does it refer to the ROUTER configuration? 
I do not understand the cause of your guess? I somehow miss the history... ;-)

**Comment by FredericMa** [comment]
Thanks guys for the quick replies.
I can clear things out here a little bit now.

It looks like I made a typo while migrating from KNX1 to KNX2.

Once I read your reply, @lewie, I noticed the typo in the IP address... The localip schould end in 101, not 100... :man_facepalming: 

So I modified the config to:
```
[
    type="ROUTER",
    localIp="192.168.50.101",
    readingPause=150,
    responseTimeout=50,
    readRetriesLimit=3,
    autoReconnectPeriod=60,
    localSourceAddr="1.2.1" 
]
```
and afterwards to:
```
[
    type="ROUTER",
    readingPause=150,
    responseTimeout=50,
    readRetriesLimit=3,
    autoReconnectPeriod=60,
    localSourceAddr="1.2.1" 
]
```
I can confirm that both configurations work.
Sorry for the confusion caused.

**Comment by lewie** [comment]
Simply in ROUTER mode forget IP addresses. ;-)

Cool, then it can be closed here.

**Comment by AngelosF** [comment]
Sorry to continue his discussion but I find interesting :)

I thought that using localIp with type="ROUTER" allows the user to configure the local interface to be used for multicasting (as you mentioned, useful when using multiple Router Networks)

I saw also that your second example (with localIp set but no ipAddress) worked for Frederic.  I haven't tested this scenario on my system yet.  I would expect that it will work (since ipAddress defaults to `224.0.23.12`).

Also, in the docs: https://www.openhab.org/addons/bindings/knx/#ip-gateway,  localIp is described as the `Network address of the local host`.

Regarding the filtering table: I was always under the impression that by default a KNX Router will NOT route telegrams between IP & BUS (either direction) if set to filter and the filtering table is not configured properly (e.g. using a dummy application).  Maybe I am wrong (but then.. what would be the role of the filtering function?)

**Comment by lewie** [comment]
> Sorry to continue his discussion but I find it interesting :)

@AngelosF, absolutely no problem! Had to look twice already. Fatally confused `localIp` and` ipAddress`. ;-(

> I thought that using `localIp` with type="ROUTER" allows the user to configure the local interface to be used for multicasting (as you mentioned, useful when using multiple Router Networks)

Yes `localIp` is used, if you have two or more Network Interfaces, then you can determine with which interface the KNX binding should communicate. If localIp is not set, the binding uses the primary Ipv4 host address. It does not matter if KNX Binding is configured for  ROUTER or TUNNEL mode. [See here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.knx/src/main/java/org/openhab/binding/knx/internal/handler/IPBridgeThingHandler.java#L84)


> I saw also that your third example (with `localIp` set but no `ipAddress` that was not supposed to work) actually worked for Frederic. I haven't tested this scenario on my system yet. I would expect that it will work (since `ipAddress` defaults to `224.0.23.12`).

You are right, that was just wrong! Thanks for the hint.
[I have corrected this in my upper comment and replaced the `localIp` variable with `ipAddress`. And explaned the full Story with an example of  parallel multiple Router KNX Networks.](https://github.com/openhab/openhab2-addons/issues/4317#issuecomment-443796968)

> Also, in the docs: https://www.openhab.org/addons/bindings/knx/#ip-gateway, `localIp` is described as the `Network address of the local host` and that it defaults to the `primary interface address` (it doesn't specify if this applies only to TUNNEL). Maybe we need to update the docs if this is overwritten by the `ipAddress` when using ROUTER.

I have not expressed myself exactly, nothing will be overwritten...
The documentation is correct. 
[I have explained it in the upper comment more accurate and correct](https://github.com/openhab/openhab2-addons/issues/4317#issuecomment-443796968)

> Regarding the filtering table: I was always under the impression that by default a KNX Router will NOT route telegrams between IP & BUS (either direction) if set to filter and the filtering table is not configured properly (e.g. using a dummy application). Maybe I am wrong (but then.. what would be the role of the filtering function?)

You are right, unless specifically directed to `forward everything`, the ROUTER only forwards the addresses used in the ETS project.

`forward everything` - ROUTER forwards everything.
`block` - ROUTER blocks everything.
`filter` - ROUTER builds a internal filter table based on addresses used and connected in your ETS project. Here you need a dummy application for addresses which should be forwarded but not connected in ETS.

**Comment by lewie** [comment]
@AngelosF, 
>     2. The NIC has multicasting off by default and it is enabled when ETS is fired up.
Normally, multicasting always is enabled at your NIC. [There are many other standards that uses multicasting over other multicast IPs.](https://en.wikipedia.org/wiki/Multicast_address)
UPnP/DLNA for example for uses multicasting for streaming Media (239.255.255.250).
