### ISSUE TITLE
[yeelight] Add support for LED Stripe v2 (YLDD04YL)

### ISSUE THREAD

**Issue by marukuru** [openhab/openhab-addons#4322]
The second revision of the Yeelight LED Stripe (YLDD04YL) isn't detected by the Yeelight binding (2.4.0.M7). It basically has the same API as the bulbs (LAN developer mode). Apps like Yeti already support it. Please let me know what addition information I need to provide.

**Comment by marukuru** [comment]
This issue pretty much solved itself by #2548. Even thou the Mi IO binding relies on the token method and not the _easier_ LAN developer mode.

**Comment by cweitkamp** [comment]
@marukuru Is your problem solved? Can we close this issue?

**Comment by claell** [comment]
@cweitkamp I don't think so, he now just uses the Mi IO binding.

**Comment by gargamelonly** [comment]
Not resolved.

As noted above by @marukuru 
Thing detected but missing channel for Brightness. 
The ColorTemperature channel is somewhat not working or not needed.
Missing switch channel for on/off.
Only color channel working as expected.

**Comment by hmerk** [comment]
closed due to inactivity
