### ISSUE TITLE
[miio] Brightness Channel as Dimmer

### ISSUE THREAD

**Issue by DerBurri** [openhab/openhab-addons#4388]
## Expected Behavior
I am trying to use the Dimmer Item with the Brightness Channel. Maybe it will be nice to switch the Channel Type of the Brightness channel to Dimmer instead of Type Number. So if a value is applied to the Dimmer Item the Brightness should adjust. 
 

## Current Behavior
I am using the Xiaomi Zhirui LED Bulb in OpenHab
If connect the Brightness Channel to a Dimmer Item the Brightness can not be adjusted. The value stays always at 100 % and is not accepting new values. Because of this the Hue Emulation also don't work. Linking the Channel to a Number item enables me to change the brightness, but then the Hue Emulation is unusable.

## Possible Solution
Change Channel Type for Brightness from Number to Dimmer

## Context
I try to control the Xiaomi LED Bulbs with Amazon Alexa, so i tried the Hue Emulation. I am able to turn the Lamps on/off, but i am not able to control the brightness. I tried many combinations.

## Your Environment

* Version used: (e.g., openhab and addon versions) openhab 2.4.0 #1455 
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Oracle Java 1.8.0_181
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspberry Pi 3 Debian Jessie

With best regards Maximilian Burr

**Comment by marcelrv** [comment]
what is the model Id for your item.
The Philips ones have been recently fixed

**Comment by marcelrv** [comment]
If it is different, pls try the following:
Download the database file for your device from here
https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.miio/src/main/resources/database
put that in your openhab/conf/misc/miio folder (the miio folder you probably need to create)
Change the line `"type": "Number",` to `"type": "Dimmer",` in the brightness channel section.

That should fix it. Please feedback the result so we can incorporate it in the main binding.
