### ISSUE TITLE
Add Withings Binding

### ISSUE THREAD

**Issue by PanderMusubi** [openhab/openhab-addons#4395]
<a alt="bounty" href="https://www.bountysource.com/issues/67624094"><img src="https://api.bountysource.com/badge/issue?issue_id=67624094"></a>

## Expected Behavior
Withings smart scales are supported.

## Current Behavior
Unsupported, but supported in version 1, see https://www.openhab.org/addons/bindings/withings1/

## Possible Solution
Port https://github.com/openhab/openhab1-addons/tree/master/bundles/binding/org.openhab.binding.withings

## Steps to Reproduce (for Bugs)
1. Install version 1 and it works.
2. Install version 2 and it doens't works.

## Your Environment
* Version used: openhab2

**Comment by wborn** [comment]
Did you try adding the [org.openhab.binding.withings-1.14.0-SNAPSHOT.jar](https://ci.openhab.org/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.withings/target/org.openhab.binding.withings-1.14.0-SNAPSHOT.jar) to the `addons` directory? This [community thread](https://community.openhab.org/t/setting-up-withings-binding/18800/27?u=wborn) suggests it should work. 

Because it is an OH1 addon you won't have discovery or Things in Paper UI. So you'd have to configure the binding with a .cfg file and setup items as shown in the [documentation](https://www.openhab.org/addons/bindings/withings1/). If the OH1 binding works we can add a feature for it so it is easily installable using Paper UI (like other supported OH1 addons).

**Comment by PanderMusubi** [comment]
I would like to have discovery and support in Paper UI. In order to get this binding ported to OH2, I'm willing to put up a small bounty at https://www.bountysource.com/

**Comment by wborn** [comment]
Yes I agree it would be nice to have a native OH2 binding with all the nice features! :+1: 

If we know that the 1.x binding works with OH2, we can still add it as a supported and installable binding while the full featured OH2 binding is being implemented. :wink:

**Comment by PanderMusubi** [comment]
Super. The bounty posted is for including discovery support.

**Comment by wborn** [comment]
Thanks for adding the [bounty](https://www.bountysource.com/issues/67624094-support-withings-from-version-1) @PanderMusubi !

**Comment by mgbowman** [comment]
I might take a stab at this. 

I have a Withings Body+ scale, 2x (old) Sleep Trackers (with the Aura alarm clock), 2 of the new Sleep trackers (without the clock but with IFTTT integration) and their blood pressure cuff 🤓

Will browse through the OH1 binding and go from there.

**Comment by wborn** [comment]
Does the OH1 addon work for you with OH2 @mgbowman?

**Comment by hakan42** [comment]
Excellent timing, I was just about to start myself :)

If you do, I can concentrate on getting my other stuff working...

I talked with @teichsta in April 2017, and at that time he told me that he had no intentions to work on the OH1 binding and the code could be taken over.

**Comment by PanderMusubi** [comment]
If OH2 support Withings, I'm also interested in a configuration rule for my FOSS [router](https://en.wikipedia.org/wiki/Turris_Omnia) to block sending this info to Nokia/Withings.

**Comment by mgbowman** [comment]
> If OH2 support Withings, I'm also interested in a configuration rule for my FOSS router to block sending this info to Nokia/Withings.

I don't think this is going to be possible. I think the data will have to get to Withings ([no longer Nokia](https://www.macrumors.com/2018/05/31/withings-co-founder-nokia/)) sooner or later. I think the only thing we can do is poll / pull the data from Withings into OH2.

> Guys, what do you think, should we open a thread over at the community forums to discuss the specifics?

I think this is a good idea. Maybe we should all list what devices we have and what data points we're interested in seeing integrated into OH2.

**Comment by victorhip** [comment]
Hi, can you describe the intstalation process?

**Comment by PanderMusubi** [comment]
Who is working on OH2 implementation (without IFTTT)?

**Comment by hakan42** [comment]
I am planning to, but not finding time for it ( as usual, getting distracted by $WORK )

**Comment by PanderMusubi** [comment]
Hope you can find it in 2020 :-)

**Comment by PanderMusubi** [comment]
Interesting to know, you can also connect the scale with USB, the ID is https://usb-ids.gowdy.us/read/UD/1fb2/0001 Should be possible to read out the data via e.g. a Raspberry Pi, but I have no idea how to interact with the device over USB? Somebody else know how to go about that?

**Comment by PanderMusubi** [comment]
Ah, there is a pairing wizard (Linux/Windows/macOS) that uses it.

**Comment by Novanic** [comment]
Hello, is someone still working on it? I think with the release of OpenHAB 3, this binding will get broken. I worked recently on the Innogy SmartHome and Netatmo binding and would now like to start with the Withings binding, because I'm owning a Withings Body Analyzer / scale and Withings Sleep. And I would like to see the discovery and other features like trigger channels.

**Comment by radokristof** [comment]
@Novanic I think only @hakan42 said that he started working on this, but I think he did not had time to finish it (I also started looking into the implementation, but I also did not had time to get any valuable result).
It would be great if someone would look into this. openHAB3 will completely break this binding, however I was not able to get this working even in openHAB2 and also the features it supports is very limited.
Would be great to get battery operated devices battery level, react on Sleep phases with Withings Sleep, etc...

**Comment by Novanic** [comment]
I have now started with a rewrite of the binding on OpenHAB 2.5 and it looks very good so far. The authorization process and the discovery of scales is already working. But there is of course a lot of work to do.

**Comment by kaikreuzer** [comment]
Sounds awesome! But I'd suggest to directly write it for openHAB 3, since this is where new bindings are being included now.

**Comment by Novanic** [comment]
> Sounds awesome! But I'd suggest to directly write it for openHAB 3, since this is where new bindings are being included now.

But I would like to use and test it within my productive system which is still on 2.5. ;-) I will migrate it later. When is the first stable release of OpenHAB 3 expected? December 2020?

**Comment by kaikreuzer** [comment]
Yes.

**Comment by Novanic** [comment]
I have now realized a version which supports scales and sleep monitors and the some useful measures. Please check if that is good / ok / usable. :-)

**Comment by chris400** [comment]
@PanderMusubi are you still interested in the binding?

**Comment by PanderMusubi** [comment]
Yes, but haven't tested it yet. Thanks for the great work.

**Comment by fabitom** [comment]
@Novanic does your first version will work on openhab 2 ? the problem is with openhab 3 ?

**Comment by hmerk** [comment]
closed due to inactivity and according PR was closed too.
