### ISSUE TITLE
[somfytahoma] expose whether the bridge status as an item

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab-addons#4396]
## Expected Behavior
It should be possible to show different sitemaps dependent on whether the bridge is logged in

## Current Behavior
Very often, status pulls fail because the tahomalink server rejects logins:

```
2018-12-17 12:04:52.443 [DEBUG] [oma.handler.SomfyTahomaBridgeHandler] - Login response: {"error":"Too many requests, try again later"}
```

At the same time, the "status" channel of the gateway is still "OK"

## Possible Solution
Either expose the status of the bridge as a channel or set the "status" channel of the gateway to specific value, depending on the success of the login attempt

## Steps to Reproduce (for Bugs)
1. set up the demo instance
2. add a tahoma bridge as with defined in the README of the somfytahoma binding, with wrong credentials
3. observer that the gateway always stays on "OK"

## Context
I cannot show on my wall panel that the gateway is offline and openHAB is not able to operate the rollershutters

## Your Environment
* Version used: 2.4.0, dockered

**Comment by davidgraeff** [comment]
Is the Thing also still online or offline?

**Comment by hakan42** [comment]
At the time I checked this, the Gateway Thing was online.

**Comment by davidgraeff** [comment]
Ok, then it's a bug not a feature request. The Thing should be offline when the bridge is not accepting a login.

**Comment by octa22** [comment]
@hakan42 can you please reproduce it in the 2.5.0-SNAPSHOT?
```
            {
                logger.debug("Login response: {}", response.getContentAsString());
                updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR, "Error logging in");
                throw new SomfyTahomaException(response.getContentAsString());
            }
```
When an error occurs during login, it always sets the bridge to OFFLINE...

**Comment by octa22** [comment]
I thing I have not touched this part of code, so it should be the same as in 2.4.0...

**Comment by hakan42** [comment]
o.k., I can confirm now that with the 2.5.0-SNAPSHOT (Build 1549) the bridge and the gateway are showing "OFFLINE" in Paper UI:

![somfytahoma-offline](https://user-images.githubusercontent.com/352641/54741746-a7f1f700-4bbf-11e9-864e-287d7d1bdb45.png)

The gateway status should be information enough to switch the sitemap on the wand panel. Sorry to have stolen your time 😊
