### ISSUE TITLE
[rfxcom] Not completely supported lighting4 command unknown(8)

### ISSUE THREAD

**Issue by buzink** [openhab/openhab-addons#4432]
One button on my lightning4 remotes sends a command that is not recognized, the raw data is

`0913004A0D8998016E60`

It is a 4 button device with a lock button, an unlock button, an alarm button and a lightning button. The lock button command is the one that is not recognized.

The remote is similar to this one: http://www.aliexpress.com/item/RF-Wireless-Remote-Control-Transmitter-Controller-for-receiver-switch-annunciator-alarm-Alarm-system-315-433MH-PT2262/609258640.html

Log:

```
14:54:36.095 [DEBUG] [.binding.rfxcom.handler.RFXComHandler] - Received message from bridge: rfxcom:bridge:1234567 message: Raw data = 0913004A0D8998016E60, Packet type = LIGHTING4, Seq number = 74, Sub type = PT2262, Device Id = 12345, Command = UNKNOWN(8), Pulse = 366
14:54:36.101 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'rfxcom:lighting4:1234567:12345' has been updated.
14:54:36.154 [INFO ] [smarthome.event.ItemStateChangedEvent] - Remote1_LIGHTING4_12345_CommandID changed from 4 to 8
14:55:09.949 [DEBUG] [ng.rfxcom.handler.RFXComBridgeHandler] - Checking RFXCOM transceiver connection, thing status = ONLINE
14:56:04.204 [INFO ] [ernal.messages.RFXComLighting4Message] - A not completely supported command with value 8 was received, we can send it but please report it as an issue including what the command means, this helps to extend the binding with better support.
```

**Comment by lmicheel** [comment]
Hello, 
i have a similar request for some cheap 433 mHz motion wireless sensor. These sensor are decoded by RFXCOM as Lighting4 PT2262 devices and, as I can understand, only sends their state to the system. To properly configure these sensors in OpenHAB. I get the SignalLevel, but no status change on command. The following INFO/Debug messages are written to the openhab.log

2019-01-26 11:40:08.679 [INFO ] [rnal.messages.RFXComLighting4Message] - A not completely supported command with value 15 was received, we can send it but please report it as an issue including what the command means, this helps to extend the binding with better support.
2019-01-26 11:40:08.683 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 091300290EC53F01EB70, Packet type = LIGHTING4, Seq number = 41, Sub type = PT2262, Device Id = 60499, Command = UNKNOWN(15), Pulse = 491

This Command 15 represent always a motion detection. Who can add this to the binding?

**Comment by martinvw** [comment]
@buzink as what is the unlock button recognized? It would be nice if the lock would be the counter I believe?
