### ISSUE TITLE
[knx] Update Readme to include color examples

### ISSUE THREAD

**Issue by AngelosF** [openhab/openhab-addons#4440]
Placeholder issue till I figure out the proper syntax for color Channel types

Refs:
1) https://github.com/openhab/openhab2-addons/pull/3433
2) https://community.openhab.org/t/knx2-color-channel/60936

Can anyone share working configs for HSB stuff? (I don't have such an actuator in my KNX setup)

**Comment by lewie** [comment]
@AngelosF, yes typo!  This examples should work as expected.
```
Type color : demoColor "Demo Color" [ hsb="232.600:<7/0/25", switch="1.001:<7/0/26", position="5.001:<7/0/27", increaseDecrease="3.007:<7/0/28" ]
Type color-control : colorControl "Demo Color Control" [ hsb="232.600:7/0/25", switch="1.001:7/0/26", position="5.001:7/0/27", increaseDecrease="3.007:7/0/28" ]
Type color : simpleColor "Simple Color Config" [ hsb="232.600:<0/0/81" ]
Type color-control : simpleControl "Simple Color Control Config" [ hsb="232.600:0/0/82" ]
```

**Comment by petrklus** [comment]
A relevant comment - should the RGBW type was implemented (https://github.com/openhab/openhab2-addons/issues/4939), how would this be represented in OH?

**Comment by hmerk** [comment]
closed due to inactivity
