### ISSUE TITLE
[astro] astro:sun:1411b2fa:morningNight#startcont incorrectly always at midnight

### ISSUE THREAD

**Issue by andrekoeln** [openhab/openhab-addons#4446]
Subject was meant to be "astro:sun:1411b2fa:morningNight#start"

When I create an astro thing with coordinates not in my timezone but e.g. 9.7,99.9 in Asia the "morning night start" is set to local midnight. See attached scrrenshot for two astro thing with loctions in Asia (left) and Germany (right).

## Expected Behavior
It should be set to midnight in the other timezone which gets recalculated to time in my timezone.

## Steps to Reproduce (for Bugs)
Just create an astro thing with above coordinates, add all items and check in Paper UI Control.

![astro-morning_night](https://user-images.githubusercontent.com/46106186/50403856-70cb9f80-07a2-11e9-8b02-4d828e7c3aa9.jpg)

**Comment by cweitkamp** [comment]
Thanks for reporting this issue.
Can you create an issue for this in the Eclipse SmartHome project [issue tracker](https://github.com/eclipse/smarthome/issues) instead?
That is the repository where the source code for the Astro binding is maintained.

**Comment by andrekoeln** [comment]
ok, thanks for the hint. 
I will

**Comment by wmarkow** [comment]
@cweitkamp, where is Astro maintained now? Was it moved from **Eclipse SmartHome** to **Openhab2 Addons**? For example issue #5692 was fixed in **Openhab2 Addons** repository.

**Comment by cweitkamp** [comment]
@wmarkow The code for the binding has been moved to this repository (openHAB 2 Add-ons) a few months ago. From now on it will be maintained here.

Thanks for looking into the open issues.

I reopened this issue.

**Comment by hmerk** [comment]
closed due to inactivity
