### ISSUE TITLE
[knx] Support for transformations

### ISSUE THREAD

**Issue by JonasMH** [openhab/openhab-addons#4490]
## The problem
I have a bunch of door contacts/sensors connected through KNX, but each of the contacts outputs true when closed and false when opened, which is opposite of how OpenHAB stores CLOSED/OPENED as seen in the following table:

| Actual door state | KNX signal | OpenHAB State |
|-------------------|------------|---------------|
| Opened            | 0          | Closed        |
| Closed            | 1          | Opened        |

So what I want to do is to invert the state in OpenHAB without altering the KNX setup/device.
## Current solution
Right now I have two items, one receiving the raw state, which in turn triggers a rule which writes the inverted state to the actual item like so:

**knx.things:**
```
[...]
Type contact		: R09_16_Opened			[ ga="<4/3/13" ]
[...]
```

**r09.items**
```
Contact R09_16_Opened "Door status [%s]"
Contact R09_16_Opened_Raw "Door status raw" { channel="knx:device:bridge:r09:R09_16_Opened" }
```

**r09.rules**
```
rule "R09 Door Invert"
when
	Item R09_16_Opened_Raw received update
then
	if(R09_16_Opened_Raw.state == CLOSED) {
		R09_16_Opened.postUpdate(OPEN)
	} else if (R09_16_Opened_Raw.state == OPEN) {
		R09_16_Opened.postUpdate(CLOSED)
	} else {
		R09_16_Opened.postUpdate(R09_16_Opened_Raw.state)
	}
end
```

But as evident by the amount of lines required to do so, it's pretty cumbersome and clutters the code when there's multiple door contacts.

## Suggested solution

Allow for a transform for each read/write, for example the modbus binding has transforms with the following syntax:

```
Thing data outdoor_temp [ readStart="0", readValueType="int16", readTransform="JS(divide10.js)" ]
```

I would imagine this would shorten my code to something similar to the following:

**knx.things:**
```
[...]
Type contact		: R09_16_Opened			[ ga="<4/3/13", readTransform="JS(invertDoor.js)" ]
[...]
```

**r09.items**
```
Contact R09_16_Opened "Door status [%s]" { channel="knx:device:bridge:r09:R09_16_Opened" }
```

Completely eliminating the rule

So if something similar was available for the KNX binding it would fix this and similar easy of use issues.

**Comment by J-N-K** [comment]
What about profiles for the channels? I don‘t know if we have an appropriate profile at the moment, but inverting a Boolean seems to be a good idea (we already have adding offsets, which is quite similar I think). But that would belong to ESH.

**Comment by J-N-K** [comment]
I don‘t know from memory how this is configured in DSL. In PaperUI you can select a „Profile“ when linking a channel to an item (such as applying a MAP or adding an offset). You could try a MAP which maps CLOsED to OPEN and vice versa. Or we could add a „invert“ profile.

**Comment by JonasMH** [comment]
Seems like the 'invert' profile would be the correct solution for most items, I did run into another problem though where the KNX status object is inverted in relation to the KNX control object, which is only solvable without rules if each group address can be transformed somehow.

**Comment by J-N-K** [comment]
Please add an issue for that in the ESH repository and link this issue. I‘m willing to implement that if the ESH maintainers agree that this is a mergable feature.

**Comment by davidgraeff** [comment]
Most profiles are implemented in the openhab-core and openhab2-addons bundles of the transformations. The invert profile could be added to the map transformation, I think.

**Comment by ssalonen** [comment]
As discussed here, profiles might be elegant solution when reading data, however not suitable for writing (pointed out by @JonasMH ) as far as I know?

**Comment by davidgraeff** [comment]
MQTT and Modbus are using transforms for input and output (unfortunately that means converting to java String back and forth). The coming http 2 binding is also using transformations that way, so I do not see a reason why the knx binding would not use transformations as configuration parameters for channels.

**Comment by vguna** [comment]
Hey. Any news on this? I started to use Openhab with my KNX system and I also have my contacts returning 1 for closed and 0 for open in KNX. This is mainly to reflect the status according to an alarm. If someone cuts the wire, it will end up in 0 and triggers the alarm. Because I will attach an alarm system later based on that value, I would like to avoid inverting in the KNX system but doing it on Openhab side. Any plans with those transformers?
I would like to avoid having to write all that boilerplate rule code mentioned above to get this done for all my contacts :).

**Comment by vguna** [comment]
Just FYI: with openhab 3 I could workaround it using the generic JS transformer and using profiles.
It's not 100% perfect, but avoids having the proxy items flying around and it's done at the lowest possible place - not just for the UI.

Item definition:
```
Contact Kontakt_Tor_Garage "Garage Tor" { channel="knx:device:bridge:bus:Kontakt_Tor_Garage"[profile="transform:JS", function="invert_knx_contact"]}
```

File `invert_knx_contact` in `transform` folder:
```
(function(knxContact) {
    return (knxContact == 'CLOSED') ? 'OPEN' : 'CLOSED';
})(input);
```
I hope this helps other KNX guys searching for a solution.

**Comment by aximut** [comment]
Nice, thanks for mentioning this. Reduces the clutter by quite a bit.
Still, would be nice to have this in the binding, as I feel this is the place where it belongs and where you would expect it.

**Comment by hanneshoettinger** [comment]
@vguna thx for this approach, however, I am getting the following output on my console:
`Could not transform state 'CLOSED' with function 'invert_knx_contact' and format '%s'`
any ideas? is the state of a contact not a string type?

**Comment by vguna** [comment]
Hmm could it be, that you have a typo or so in it? I saw similar errors while testing it on my side when syntax was incorrect. Also doublecheck, that you have restartet OpenHab when you did set the profile in knx items file. For debugging your transformation (what goes in, on which step it fails) you can use logging like described here: https://community.openhab.org/t/debug-javascript-in-transform-service/57156/6

**Comment by hanneshoettinger** [comment]
Yeah strange, it is defined like that:
Item:
`Contact                          cEGBueroFensterkontaktStatus                  "Büro Fenster"                                   <window>            (gOpening, gFenster, gBueroKontakt)                         ["OpenState", "Opening"]    {channel="knx:device:bridge:binaereingaenge:EGBueroFensterkontaktStatus"[profile="transform:JS", function="invert_knx_contact"]}`
KNX Thing:
```
Thing device binaereingaenge [
        address="1.1.22",
        fetch=true,
        pingInterval=300,
        readInterval=0
    ] {
        Type contact       : EGBueroFensterkontaktStatus                 "Büro"                      [ ga="<5/1/31" ]
}
```
and the transformation:
```
(function(i) {
    return (i == 'OPEN') ? 'CLOSED' : 'OPEN';
})(input)
```
restarted OpenHab but still getting the same error. I have tested the transformation also with:
`"Büro Fenster [JS(invert_knx_contact.js):%s]`" which works to display the inverted state, however, does not affect the item state.

I read about Contacts in OpenHab Documentation:
"A Contact Item carries a OpenClosedType. OpenClosedType is an Enumeration. "
Could that be an issue? Still got any ideas? Thx for the help!

**Comment by vguna** [comment]
Hm, are you using Openhab 3 or 2.5? 2.5 had the issue with only supporting Strings. I'm using OH 3 and the syntax in your file seems correct to me. If you're also on OH3, option left is only to add debug to the transform script.

**Comment by hanneshoettinger** [comment]
Yes, using OH3. The transform script works if I use it in a rule and input the item state as String....
How did you define your knx thing? Also as Type contact? Which dpt are you using? Could you share that with me?

**Comment by hanneshoettinger** [comment]
So it works now if I add .js to the filename and sourceFormat="%s":
`[profile="transform:JS", function="invert_knx_contact.js", sourceFormat="%s"]`
Thx for support!

**Comment by hmerk** [comment]
Closed due to inactivity and solution posted.
