### ISSUE TITLE
[chromecast] Add support for powering TV on/off using CEC

### ISSUE THREAD

**Issue by magd1978** [openhab/openhab-addons#4516]
Google Assistant can tell Chromecast to power on / off TV by CEC command. It would be great if the Chromecast binding could handle this Chromecast feature.

**Comment by zbot473** [comment]
I don't think it's possible: https://github.com/balloob/pychromecast/issues/196#issuecomment-345564899

**Comment by hmerk** [comment]
closed due to inactivity
