### ISSUE TITLE
[onkyo] Should each supported receiver have its inputs correctly listed and labelled?

### ISSUE THREAD

**Issue by Cossey** [openhab/openhab-addons#4517]
With the Onkyo receivers, each model sometimes has variances to what inputs they support depending on their release year, region and model. For example, my receiver supports the following inputs:
* BD/DVD
* Cbl/Sat
* Game
* Strmbox
* PC
* Aux
* CD
* TV
* Phono
* Tuner
* Net
* Bluetooth

However the _Input Source_ drop down in Paper UI has most of the possible sources listed including ones that are not relevant to the specific model of receiver _(ie: Tape 1, Tape 2, Multich)_ or inputs that are labelled slightly differently. 

Would it be worthwhile to consider adding the list of supported Source items as part of the `devicemodel.xml` files and make some changes to the add-on if that's even possible? My idea was along the line of having displaying them all by default, otherwise only show specific inputs when supplied in the `.xml` files.

Do you think something like this would be worthwhile @paulianttila and @marcelrv? Thanks.

**Comment by cweitkamp** [comment]
Is it possible to detect the available inputs during runtime? If so you can think about implementing a `DynamicStateDescriptionProvider` for it.

**Comment by Cossey** [comment]
From what I've seen in the ISCP protocol documentation it appears that there isn't a way to get supported inputs. The only way is to really document it on a per device basis but the version of the protocol documentation I have is probably a few years old  (I need documentation from 2018 onwards which may help).

Somehow the "Onkyo Controller" app on iOS and Android (for newer model Receivers) can seem to get the custom labelled input names made on the receiver so it must be possible to pull these down from the system in some way. I will try sniffing packets from Bluestacks to the tuner using Wireshark and see if I can find some undocumented protocol commands.

**Comment by Cossey** [comment]
Okay found it last night its the `NRIQSTN` command which returns an xml file which contains the different Inputs under one of the nodes. I'll look into the `DynamicStateDescriptionProvider`, thanks for pointing me in the right direction.

**Comment by cweitkamp** [comment]
Sounds great. Have a look into the [Kodi binding](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.kodi/src/main/java/org/openhab/binding/kodi/internal/KodiDynamicStateDescriptionProvider.java) how it works. Otherwise ping me in the [community](https://community.openhab.org/latest).
