### ISSUE TITLE
Maven Unleash Plugin removes explicit POM version on every release

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#4523]
The maven unleash plugin removes the explicit version number from [pom.xml](https://github.com/openhab/openhab2-addons/blob/master/pom.xml#L13). Examples:

- 378fe05
- 4709a99

This causes the releasebuild to fail with `Missing requirement: org.openhab.binding.airquality 2.4.0.qualifier requires 'package com.google.gson 0.0.0' but it could not be found`.

I already fixed it 2 times by #3812 and #4522. 

On other repositories, this issue does not occur, example: openhab/openhab-core@61e21d48

I / We have to find out the root cause and fix it permanently. Possible solution approaches:

- prevent explicit POM version from being removed during versions update **OR**
- find out why explicit version is needed at all / get it running without explicit version

**Comment by pfink** [comment]
Interestingly, this issue does or did not always occur. On zwave binding, it didn't occur on 2.2 release (openhab/org.openhab.binding.zwave@c0519c43a), but it did occur on 2.3 (openhab/org.openhab.binding.zwave@8398d2e38) and 2.4 (openhab/org.openhab.binding.zwave@6288b5650) release...

**Comment by pfink** [comment]
@kaikreuzer: I have to leave off for today, tomorrow I can take a look on the other repos as well.

**Comment by kaikreuzer** [comment]
All fine, thanks a lot!

**Comment by kaikreuzer** [comment]
@pfink FYI, I have created https://github.com/openhab/org.openhab.ui.habot/pull/38, https://github.com/openhab/org.openhab.ui.habmin/pull/306 and https://github.com/openhab/org.openhab.binding.zigbee/pull/351.

**Comment by kaikreuzer** [comment]
... and https://github.com/openhab/org.openhab.ui.habpanel/pull/348.

**Comment by pfink** [comment]
Thanks!

**Comment by kaikreuzer** [comment]
And I only forgot https://github.com/openhab/openhab-distro/pull/839 🙄.

**Comment by davidgraeff** [comment]
Can this be closed now? :)

**Comment by pfink** [comment]
No, the root cause is not solved (unleash will probably still remove the version on next release).

**Comment by pfink** [comment]
This does not occur anymore, I think it was resolved by #5005.
