### ISSUE TITLE
[groheondus] Grohe SenseGuard is missing flowrate channel

### ISSUE THREAD

**Issue by uspringis** [openhab/openhab-addons#4549]
Hi,
grohe sense guard has flowreate info available,
looks implemented in the grohe ondus java api:
 public static final class Measurement {
        @JsonProperty("timestamp")
        public String timestamp;
        @JsonProperty("flowrate")
        public Integer flowrate;
        @JsonProperty("pressure")
        public Float pressure;
        @JsonProperty("temperature_guard")
        public Float temperatureGuard;
    }

Would be useful to add the channel to openhab binding to be able to persist usage data and display in nice HABPanel graph :)

**Comment by TNRichard** [comment]
beside actual value, there is also a complete history (up to 3 months) available by API. Can this be made available to openHAB to be shown as chart?

**Comment by FlorianSW** [comment]
It may be pretty easy to expose the actual value of the flowrate, which (combined with persistence) then could be used for charting. Or is there a way to expose multiple values to an item without using persistence (I don't know any way)?

**Comment by TNRichard** [comment]
What I'm asking for is the value history available by API (like seen in the app).
I know about charting actual value, what will work also.

**Comment by FlorianSW** [comment]
Hmm, the question here is: What do you want to do with this data. The flowrate is kind of useless in my opinion. By the way: what you see in the app is not the "flowrate" value as requested in this PR, it's the combined waterconsumption value of the withdrawals array by day (or week, month, 3 months).

I would like to get some more context to better understand what you want to do with the flowrate value :) For now, I would work on getting the waterconsumption value into openHAB :)

**Comment by hmerk** [comment]
closed due to inactivity
