### ISSUE TITLE
[groheondus] Add support for GROHE Blue

### ISSUE THREAD

**Issue by TNRichard** [openhab/openhab-addons#4550]
In the ONDUS app you already see Grohe BLUE as new appliance. Can you add it to the binding?

**Comment by FlorianSW** [comment]
Without a test device to inspect the API responses, this is kind of impossible to do :( Additionally, it seems that there're multiple different types of the device, too, am I correct?

**Comment by TNRichard** [comment]
basically it is the grohe BLUE home. Different product versions are only due to different faucet types

**Comment by Sprocket02** [comment]
The Christ Child will hopefully bring me a [Grohe Blue Home](https://www.grohe.de/de_de/kueche-kollektion/kuechenarmaturen-grohe-blue-home.html?gclid=CjwKCAiA5JnuBRA-EiwA-0ggPWWEKeXQPquRQ1-q_BxTMD8Ow4Wsznz99iEx1cRzqSG2A1meqeeuKhoCg5kQAvD_BwE&gclsrc=aw.ds). I will try to expand the binding accordingly.

**Comment by Sprocket02** [comment]
I looked at the binding. I will first have to adapt the Grohe Ondus Api. 
@FlorianSW Can you give me a hint which classes I have to adapt for a new device? Maybe per mail: sebi.neu@gmail.com German language is also possible ;-)

**Comment by MichaelBeul** [comment]
I'm also very interested in this feature. We have a Grohe Blue Professional and need to manage it via API (or OH Binding). Let me know if I should do some tests.

**Comment by FlorianSW** [comment]
Together with the awesome help of @Sprocket02 I've added support for the GROHE Blue in the grohe-ondus-api (https://github.com/FlorianSW/grohe-ondus-api-java/issues/12), which is used in this binding. Once I took a look at the code, I'll release a new version of the library.

However, before this issue can be tackled here, the binding needs to update the library, as some breaking API changes were introduced as well. However, it would then be really interesting what information and settings are really needed in the binding (aka channels) :)

**Comment by FlorianSW** [comment]
Ok, all the changes needed in the Java API should be there, and the version 1.0.0 with them is released. Next step is to update the binding to the new version. Afterwards we can add new things and functionality for the GROHE Blue devices.

**Comment by Sprocket02** [comment]
Hey, what are the next steps? Where and how can I help?

Am Mo., 9. März 2020 um 15:54 Uhr schrieb Florian <notifications@github.com

**Comment by FlorianSW** [comment]
Until now there's nothing you can really do (except if you want to provide a PR for the Blue device on yoursefl). My next plan is:

* Update the java API to the new version
* Add basic support for blue device (probably starting with turning the tap on)
* Add more channels for the blue device if necessary

It would be great to have some people able to test the new features once they're here :)

**Comment by MichaelBeul** [comment]
I can do some tests when the binding is available. 
It would be great if the binding supports "Turning on the tap and automatically stop after X Liter". This is something you can already to with the app, so the API should already provide it.

**Comment by FlorianSW** [comment]
Yeah, the API supports that. It actually can not turn on the water indefinitely, as @Sprocket02 and I agreed on that this is not really a use case :P

**Comment by FlorianSW** [comment]
I created PR #7134, which should add very very basic support for the GROHE blue device. It allows you to turn on the tap with the setting CARBONATED for 100 mililiters :) Once it's build, you can check it out, if you want :)

**Comment by hmerk** [comment]
closed due to inactivity
