### ISSUE TITLE
[feed] Channels/items are not updated

### ISSUE THREAD

**Issue by Celaeno1** [openhab/openhab-addons#4551]
[feed binding] Channels/items are not updated, only a few.

## Expected Behavior
All channels/items are updated properly

## Current Behavior
Not all channels/items are updated/getting values

After EVERY RESTART of Openhab-Service (or RESTART of the complete Server), 
then --> feed binding is loading...

    'feed:feed:672bc615' changed from UNINITIALIZED to INITIALIZING
    'feed:feed:672bc615' changed from INITIALIZING to UNKNOWN

then the channels should be updated, but some of them are MISSED: (3 out of 5)

    Cannot update channel with ID latest-title; no data has been downloaded from the server!
    Cannot update channel with ID last-update; no data has been downloaded from the server!
    Cannot update channel with ID author; no data has been downloaded from the server!

Reason: thing is not ONLINE, this happens only afterwards:

    'feed:feed:672bc615' changed from UNKNOWN to ONLINE

Then it updates ONLY the values of NOT MISSED channels! (2 out of 5)

    Titel changed from NULL to openHAB-Distribution all builds
    Published changed from NULL to 2019-01-06T12:17:50.000+0100

See ALL details here:

https://community.openhab.org/t/feed-some-channels-title-last-update-are-not-updated/62560

## Steps to Reproduce (for Bugs)
https://community.openhab.org/t/feed-some-channels-title-last-update-are-not-updated/62560/3

## Environment
OS: Windows 10, 32 bit
JAVA: jdk1.8.0_161
OH2: snapshot build 1486
Binding: Feed

**Comment by hmerk** [comment]
closed due to inactivity
