### ISSUE TITLE
[mihome] Add support for Aqara Zigbee tunable white LED bulb 

### ISSUE THREAD

**Issue by Fabiancrg** [openhab/openhab-addons#4552]
Hi,
I am using the Xiaomi Mi Smart Home Binding for some time (OH and addons 2.4.0 on Raspbian Jessie).
I have now an Aqara tunable white LED bulb (Zigbee version), it's connected to my Xiaomi GW and I can control it. I have a few other devices (Sensors, plugs, switches) and they are working fine.

I tried to add the bulb to OH but it's not yet supported so I am creating this issue to see if it could be added to the supported device list in order to be able to:
- Set the color temperature
- Power on or off this device

I already tried to add it using its SID as a basic device but it's staying in status 'OFFLINE'.

Could you please let me know if this is possible and how I could help.

Thank you,
Fabian

**Comment by dimalo** [comment]
Hi @Fabiancrg,
if it is not popping up as a basic device in your inbox already, then it is not yet supported for developer mode by the gateway. As soon as the binding gets a message refering to an unknown device, it triggers the discovery of a basic device. So at the moment we have to be patient and wait until an upcoming gateway firmware update adds support for the bulb.

**Comment by Fabiancrg** [comment]
Hi
Thank you for your answer.
Coincidence, this morning I had en entry in my OH console with a new device, one of the two LED bul I have was there. Following this I got a firmware update on the Gateway (strange, it was after and not before the device appeared), the new version is 1.4.1_164.0158.
So I have now a new thing, for one of the two bulb, reported as Unsupported Xiaomi MiHome Device (Basic Xiaomi MiHome Device), I added it and configured an item for each channel but nothing was updated so far (thing is seen as "online").
Kind regards,
Fabian

**Comment by dimalo** [comment]
Seems like the gateway sends the information about the device but no data. As soon as you have something in the channels, please post it here so we can implement the device. Propably you have to wait for more gateway firmware updates...

**Comment by mahonni** [comment]
> Seems like the gateway sends the information about the device but no data. As soon as you have something in the channels, please post it here so we can implement the device. Propably you have to wait for more gateway firmware updates...

Just checked that with my new LEDs and same happen here. It seems like data is not being updated :(

**Comment by Fabiancrg** [comment]
I am not using the Xiaomi gateway anymore, I switched to zigbee2mqtt (with a 3$ CC2531 USB stick).
All my devices previously attached to the Xiaomi GW are now accessible using MQTT.
On top of that I can use much more devices than just the one supported by the GW.

**Comment by mahonni** [comment]
> I am not using the Xiaomi gateway anymore, I switched to zigbee2mqtt (with a 3$ CC2531 USB stick).
> All my devices previously attached to the Xiaomi GW are now accessible using MQTT.
> On top of that I can use much more devices than just the one supported by the GW.

Thanks for the info. It's an option I was considering, but it felt like a lot of work just to solve a problem with one device. Besides that, it looked like Openhab wasn't adapted to zigbee2mqtt very well, and I've read that CC2531 didn't have as much coverage than Xiaomi Gateway, but I'll continue looking at it.

**Comment by Fabiancrg** [comment]
CC2531 is working just fine for me as each plug and bulb are routers so you can extend the mesh each time you add one of these. If you are not using much routers there are other options; like the CC2530 with external antena.
Zigbee2mqtt is indeed not directly integrated in OpenHAB but mqtt is, so it's not that difficult to use.
Personaly I am using Node-Red between zigbee2mqtt and OpenHAB items, it allows me to do nearly anything.
Big advantage of zigbee2mqtt is the number of supported devices, info from the site:
"Currently 264 devices are supported from 59 different vendors."

**Comment by mahonni** [comment]
> CC2531 is working just fine for me as each plug and bulb are routers so you can extend the mesh each time you add one of these. If you are not using much routers there are other options; like the CC2530 with external antena.
> Zigbee2mqtt is indeed not directly integrated in OpenHAB but mqtt is, so it's not that difficult to use.
> Personaly I am using Node-Red between zigbee2mqtt and OpenHAB items, it allows me to do nearly anything.
> Big advantage of zigbee2mqtt is the number of supported devices, info from the site:
> "Currently 264 devices are supported from 59 different vendors."

I'll check on Node-Red too, I just wasn't finding a reason to try to learn it, but if it eases things with Zigbee2mqtt, it'll be a good reason to start with it too. Thanks for the info, @Fabiancrg !

**Comment by hmerk** [comment]
closed due to inactivity
