### ISSUE TITLE
[knx] Binding not updating values if address is set in Thing

### ISSUE THREAD

**Issue by mzanier** [openhab/openhab-addons#4553]
if i set address in the thing definition, the knx binding is not processing the telegram, only if i remove the address (KNX address of source actor) the binding is processing 

added some more info in community: https://community.openhab.org/t/issue-with-receiving-any-update-from-knx-binding/62391/3

**Comment by lewie** [comment]
@mzanier, some actors can not be red by the binding. Remove the address it is optional!

**Comment by mzanier** [comment]
hm. but even if it is optional - it should not deactivate the functionality to receive updates from the bus for the single elements of the device  ?

**Comment by hmerk** [comment]
closed due to inactivity
