### ISSUE TITLE
[avmfritz] Thing remains offline after reboot of FritzBox

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#4558]
The avmfritz binding (configured via PaperUI) is working perfectly until I reboot the FritzBox 7490.

After the reboot, I get this error:
2019-01-08 19:25:41.276 [hingStatusInfoChangedEvent] - 'avmfritz:fritzbox:192_168_0_1' changed from OFFLINE (COMMUNICATION_ERROR): FRITZ!Box does not respond to OFFLINE (COMMUNICATION_ERROR): Request is invalid

And it does not resolve by itself.

I can only fix this by changing the password of the thing to a wrong password, save, then change back to the correct password and save. Then the thing goes ONLINE again.

I am using user and password as login to the FritzBox and I have FritzOS 07.01.

* openHAB 2.4.0
* binding-avmfritz - 2.4.0
* Linux
* java version "1.8.0_192"

**Comment by cweitkamp** [comment]
May I ask you to provide a TRACE log?

**Comment by sidamos** [comment]
I have sent the log via message at the openHAB community.

**Comment by cweitkamp** [comment]
Your issue is reproducible. I will take a closer look.

**Comment by BlackEternity** [comment]
Adding feedback here - Encountered the same issue aswell. 
I could fix it by restarting the Bundle on the shell. A bit tedous but it works.

**Comment by WRP1992** [comment]
Hello,
is there any update or workaround?

**Comment by cweitkamp** [comment]
I did some research and submitted a fix for it (see #5346).

**Comment by pasbi** [comment]
I experience the same issue with a *FRITZ!Powerline 546E*:
After rebooting the device, openHAB does not reconnect, the status message reads:
`Status: OFFLINE - COMMUNICATION_ERROR FRITZ!Box does not respond`.

My openHab version is `2.5.7-1`, so I suppose the #5346-fix is applied already.
