### ISSUE TITLE
Add Yahoo Weather Binding with key/secret support

### ISSUE THREAD

**Issue by debendramodi** [openhab/openhab-addons#4568]
[Yahoo Weather] Binding stopped working from January 3.  Was working fine before this.  Message from Yahoo mentioned that AppID and secret key needs to be obtained.  We now have the App ID and the key from Yahoo but do not know how to use this with the binding

## Expected Behavior

Yahoo Weather Binding needs to be updated to include OAUTH protected calls.  
## Possible Solution

We have obtained the AppID and the secret key from Yahoo, but do not know how to use this.
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by cweitkamp** [comment]
The Yahoo binding has been removed from ESH repositories. And it will be removed from OH2 as well.

If anyone wants to work on this, this is very welcomed, but for now we have no solution for this.

**Comment by wborn** [comment]
It's more like a whole new binding if this issue is solved in this repo. :wink:

**Comment by 9037568** [comment]
I think this is a dead stick. Yahoo is about to kill off their free API (again):

https://developer.yahoo.com/api/
![image](https://user-images.githubusercontent.com/9916473/103328609-7ad6a780-4a27-11eb-9a27-b6f95117caaf.png)
