### ISSUE TITLE
[mihome] Can't handle command 1000 on channel mihome:gateway:7c49ebb18917:sound

### ISSUE THREAD

**Issue by sefradre** [openhab/openhab-addons#4589]
Sending the message XiaomiMiSmartHomeGateway_SoundSelector.sendCommand(x); follows to 
[WARN ] [nal.handler.XiaomiActorGatewayHandler] - Can't handle command 1000 on channel mihome:gateway:7c49ebb18917:sound 

It's anyway sending the message from rules or PaperUI. 

It seems that the problem starts with version 2.3.

One interessting point is that the sound value couldn't changed via the myopenhab-android-app interface.

## Expected Behavior
After SoundSelector.sendCommand(x) sending coming sound out of the gatway.

## Current Behavior
No sound, only a warn message

## Possible Solution
no Idea.

## Steps to Reproduce (for Bugs)
sending the message

## Your Environment
openhab 2.4
mihome addon 2.4
armbian 5.38
firmware on gateway: 1.4.1_164.0158

**Comment by dimalo** [comment]
I just checked and it works for me as intended. Are you able to change the gateway light? If not then perhaps your gateway key is not correct?

**Comment by sefradre** [comment]
Changing the gateway light works perfect. However I've already checked the gateway key - it is correct. As I wrote, with the old version 2.3 also changing the sound had worked perfect.

**Comment by dimalo** [comment]
@sefradre 
What sound are you actually trying to trigger?
[The readme](https://www.openhab.org/addons/bindings/mihome/#xiaomi-sitemap) tells that 1000 is not a valid ID for any sound. If you want to play own mp3s you uploaded to the gateway, then the IDs start from 10001. The native sounds are 0 - 29, and stop command is 10000. I didn't test own sound but the rest works for me.

**Comment by sefradre** [comment]
My Code is:
XiaomiMiSmartHomeGateway_SoundVolume.sendCommand(20/100);
//Gespenst
XiaomiMiSmartHomeGateway_SoundSelector.sendCommand(4);
Thread::sleep(100000) /* wait for 100 seconds */
XiaomiMiSmartHomeGateway_SoundSelector.sendCommand(1000);
XiaomiMiSmartHomeGateway_SoundVolume.sendCommand(0);

The reaction in the log is:
16:09:40.161 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'XiaomiMiSmartHomeGateway_SoundVolume' received command 20
16:09:40.187 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'XiaomiMiSmartHomeGateway_SoundSelector' received command 4
16:09:40.239 [INFO ] [arthome.event.ItemStatePredictedEvent] - XiaomiMiSmartHomeGateway_SoundVolume predicted to become 20
16:09:40.266 [WARN ] [nal.handler.XiaomiActorGatewayHandler] - Can't handle command 4 on channel mihome:gateway:7c49ebb18917:sound
16:09:40.278 [INFO ] [smarthome.event.ItemStateChangedEvent] - XiaomiMiSmartHomeGateway_SoundVolume changed from 0 to 20
16:09:40.290 [INFO ] [arthome.event.ItemStatePredictedEvent] - XiaomiMiSmartHomeGateway_SoundSelector predicted to become 4
16:09:40.306 [INFO ] [smarthome.event.ItemStateChangedEvent] - XiaomiMiSmartHomeGateway_SoundSelector changed from 1000.0 to 4.0

and no sound from the gateway.

**Comment by sefradre** [comment]
I've now tried it again with the Mi Home App. Of course, it works with the app. The interesting thing is, the last sound in the alarm sound list is now "bark". 
Might there be a problem with between the binding and the firmware on my gateway? 1.4.1_164.0158 and it seems to be version 3 of the gateway.

**Comment by sefradre** [comment]
An I'v found my mistake. I changed it from 1000 to 10000. But there comes still no sound with openhab. Sill the same War-Message.

**Comment by topsurfer** [comment]
I just try to play sounds over the mii hub, and I also get only the "Alarm sound" played on the Hub.
what ever I change in my rule, it plays always with same volume and same type of sound ("Alarm", like a "uuiii uuiii uuiii uuiii...."

Is there still a problem betwen the oH and the mii-hub?

**Comment by sefradre** [comment]
Very nice to read something here. Yes, I'm still getting only the warn-message in the log and no sound from the gateway.

**Comment by sefradre** [comment]
unfortunately I'm still getting only the log message and no sound.

**Comment by hmerk** [comment]
closed due to inactivity
