### ISSUE TITLE
[silvercrestwifisocket] Add support for Lumitek/Ankuoo devices

### ISSUE THREAD

**Issue by ljalves** [openhab/openhab-addons#4590]
The Silvercrest wifi socket binding can be easily enhanced to support "Ankuoo" devices.

Needed changes:
* AES encryption key is "1234567890abcdef" (instead of "0123456789abcdef"). This could be changed to be a config parameter.
* Company code is 0xd1 or 0xdf
* Device is 0xf1
* Auth code is 0x21b4

Some captured packets:

Socket plug (http://www.lumitek.cn/en/productsd.php?pid=1095):
0x0, 0x4, 0xdb, 0xdf, 0xf1, 0x21, 0xb4, 0x6, 0x0, 0x0, 0xff, 0xff

Module (http://www.lumitek.cn/en/productsd.php?pid=1093):
0x0, 0x0, 0x30, 0xd1, 0xf1, 0x21, 0xb4, 0x2, 0x0, 0x0, 0x0, 0xff
0x0, 0x16, 0x1a, 0xd1, 0xf1, 0x21, 0xb4, 0x6, 0x0, 0x0, 0xff, 0xff
0x0, 0x0, 0x39, 0xdf, 0xf1, 0x21, 0xb4, 0x61, 0x5c, 0x39, 0xf5, 0x63
0x0, 0x70, 0xd, 0xd1, 0xf1, 0x21, 0xb4, 0x62, 0x8, 0x8, 0x8, 0x8

**Comment by kattlukt** [comment]
These are also known as Malmbergs in Sweden. Would love to get them working with openhab!

**Comment by ljalves** [comment]
I ended up by making a new firmware for these devices...
For now it has a MQTT client (so it just works with openhab) and I plan to keep adding more features (my goal would be to make it similar to espeasy).
Can also be controlled by http requests (http://ip/state?sw=0 or 1)

Have it running on all my devices for 1 week now without any issue.

Feel free to try it: https://github.com/ljalves/hfeasy/
Can be easily reverted to the official firmware (something I'll never do!).


By the way, feel free to close this request... I don't need it anymore...

**Comment by kattlukt** [comment]
Ok, but the link does not work. Getting 404....

**Comment by ljalves** [comment]
Which link?

**Comment by kattlukt** [comment]
https://github.com/ljalves/hfeasy/

**Comment by ljalves** [comment]
Sorry, I forgot to make it public!
Should work now...

**Comment by kattlukt** [comment]
Thank you!

**Comment by ljalves** [comment]
0v2 released (mostly adds mqtt authentication)

**Comment by ljalves** [comment]
The cool thing is that I can have 2 modules subscribed to the same mqtt topic and control both with 1 switch :)

**Comment by stevo44444** [comment]
Hello, 
sorry i am new to this.
can you tell me how to decrypt the UDP data from wireshark? 
I understand to use the 123456789abcdef key but not too sure how to do it.
Thanks in advance
