### ISSUE TITLE
[lgwebos] There is an issue with "Mobile TV On", because with several Televisions it doesn't work

### ISSUE THREAD

**Issue by qpi** [openhab/openhab-addons#4613]
Below this link, You can see lot of people facing with that problem in the past 1 year when the "Mobile TV On" is properly set on the TV, but the TV does not want to turn on remotely:
https://lgcommunity.us.com/discussion/437/lg-smart-tv-wifi-wont-turn-on/p6

## Expected Behavior
When the "Mobile TV On" is on the TV should be able to turn on the remotely by openHAB and also with the LG's Android remote control application

## Current Behavior
Lot of LG TVs can not be turned on remotely, when the "Mobile TV On" properly set

## Possible Solution
I know it is a bug on the LG site, but did some tests to understand what is happening.
It seems when the TV turns down, it turns down LAN too. Here is a ping example (after I started the ping, immediately turned off the TV ):

C:\>ping 192.168.0.8
Pinging 192.168.0.8 with 32 bytes of data:
Reply from 192.168.0.8: bytes=32 time=2ms TTL=64
Request timed out.
Request timed out.
Request timed out.

I think with a small workaround this could be fixed. Because the Wake-on-LAN function can turn ON the TV. I downloaded WakeMeOnLan application and with that I was able to turn on the TV. So maybe in this cases the Wake-on-LAN request could be used instead of using the LG Connect SDK to turn on the TV.

## Steps to Reproduce (for Bugs)
It depends on the TV :(
1.
2.

## Context
OpenHAB to handle LG bug

## Your Environment
Synology DSM NAS with openHAB 2.4 package

**Comment by lolodomo** [comment]
Please try again with coming version 2.5.4, it includes the WOL feature inside the binding, and then close this issue if it is solved.

**Comment by hmerk** [comment]
closed as no further feedback was provided and related PR was merged
