### ISSUE TITLE
[mqtt] Item set to value then immediately set to UNDEF

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#4616]
## Expected Behavior

When an MQTT message is received, the Item linked to that channel is set to that value and keeps that value.

## Current Behavior

When an MQTT message is received in at least one configuration (see OH forum thread below) the Item is set to the value but then immediately gets set to UNDEF. 

What seems to be unique about the Item I'm seeing this behavior with compared to other Items is I'm using a transform. The incoming message is a String of the format of DD:HH:MM:SS (it's the updime) and I have an On Off Channel and a MAP transform to convert everything to ON. In short, I'm turning the uptime message into a Switch heartbeat Channel. I use Expire binding to time out the Item linked to this Channel.

Thing Definition
![image](https://user-images.githubusercontent.com/6385096/51330448-c1968700-1a34-11e9-90e4-1454308cfb72.png)

Item Definition
`Switch vManticore_SensorReporter_Online "Manticore sensorReporter [MAP(admin.map):%s]" <network> (gSensorStatus, gResetExpire) { channel="mqtt:topic:manticore-sr:heartbeat", expire="2m,command=OFF" }`

events.log
```
20x2019-01-16 14:55:20.850 [ome.event.ItemCommandEvent] - Item 'vManticore_SensorReporter_Online' received command ON                                                          x
20x2019-01-16 14:55:20.854 [vent.ItemStateChangedEvent] - vManticore_SensorReporter_Uptime changed from 00:21:04 to 00:22:04                                                   x
20x2019-01-16 14:55:20.860 [nt.ItemStatePredictedEvent] - vManticore_SensorReporter_Online predicted to become ON                                                              x
01x2019-01-16 14:55:20.863 [vent.ItemStateChangedEvent] - vManticore_SensorReporter_Online changed from UNDEF to ON                                                            x00
16x2019-01-16 14:55:20.864 [GroupItemStateChangedEvent] - gSensorStatus changed from OFF to ON through vManticore_SensorReporter_Online                                        x
16x2019-01-16 14:55:20.867 [vent.ItemStateChangedEvent] - vManticore_SensorReporter_Online changed from ON to UNDEF                                                            xvi
cex2019-01-16 14:55:20.869 [GroupItemStateChangedEvent] - gSensorStatus changed from ON to OFF through vManticore_SensorReporter_Online
```

MQTT Binding trace logging
```
16x16-Jan-2019 15:04:18.140 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.142 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.145 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.146 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.149 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.150 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.151 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.153 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
16x16-Jan-2019 15:04:18.155 [TRACE] [ternal.generic.MqttChannelStateDescriptionProvider] - Providing state description for channel mqtt:topic:manticore-sr:heartbeat           x
```

## Possible Solution

As a work around I use a Rule that triggers with an Item linked to the Uptime Channel and sendCommand(ON). Note that the Uptime channel, which subscribes to the same topic but doesn't transform the message does not exhibit this behavior.

## Steps to Reproduce (for Bugs)

See configuration above.

## Context

I'm migrating from MQTT1 to MQTT2 and I have a Python script that can sometimes stop reporting while remaining connected to the broker. So I use a heartbeat message as a signal to know if everything is going OK. Ultimately I need to fix the original script so I can rely on LWT, but nothing I did above should be supported.

## Your Environment

* Version used: OH 2.5 SNAPSHOT #1502
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Mosquitto is the broker
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): openHAB Docker Image

There is more discussion at https://community.openhab.org/t/mqtt-2-5-binding-strange-behavior-item-goes-on-then-immediately-to-undef/64500

**Comment by Rossko57** [comment]
Comment : behaviour similar to https://github.com/openhab/openhab2-addons/issues/5879

**Comment by J-N-K** [comment]
Is this still the case after latest changes to value handling in mqtt?

**Comment by rkoshak** [comment]
I totally forgot about this one. I just set up a similar setup as the above and can confirm that it works as expected in 2.5.2.
