### ISSUE TITLE
Add MCP23008 Binding

### ISSUE THREAD

**Issue by soosp** [openhab/openhab-addons#4628]
## Expected Behavior

Add-on for MCP23008 binding

## Current Behavior

Missing MC23008 support

## Possible Solution

As I see pi4j library supports MCP23008 too, but the java classes focus MCP23017 only.

## Steps to Reproduce (for Bugs)

1. There is no Add-on for MCP23008
2. I installed Add-on for MCP23017 binding, but it not support MCP23008 chip.

## Context

I tried th use a UniPi 1.1 board equipped with MCP23008 but there is no Add-on for these chips.

## Your Environment

* Version used: OpenHAB 2.4.0 installed from repository.
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Oracle java 1.8.0_201
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian 9.6
* Hardware: Raspberry Pi 3 Model B, UniPi 1.1

**Comment by hmerk** [comment]
closed due to inactivity
