### ISSUE TITLE
[avmfritz] Implement "Query script" for fast refresh interval for FRITZ!DECT 200

### ISSUE THREAD

**Issue by lionhe1966** [openhab/openhab-addons#4711]
The readings of power from FRITZ!DECT smart switches changes only every 2 minutes and not every 20-30 seconds, as it used to in the properly configured OpenHAB 1.x FritzAHA binding

## Expected Behavior
The poll frequency of FRITZ!DECT 200 should be 20-30 seconds as it used to be in fritzaha binding when the "query script" was also implemented

## Current Behavior
The poll frequency is 2 minutes, unless the web page of the fritz!box router showing the past values of the FRITZ!DECT 200 power is open.  I do not know if such a behavior happens also for newer version of the Fritz!OS (I am using a fritzbox 7360v1 with FritzOS 6.30)

## Possible Solution
Either implement the "query script" part in the 2.4 binding, porting it from the previous 1.x Fritzaha binding, or modify the OpenHAB 1.x Fritzaha binding sources so that it can be installed in OpenHAB 2.4 as a legacy 1.x binding (at present it does not appear as a possible binding to install, both in OpenHAB 2.4, and in OpenHAB 1.8)

## Steps to Reproduce (for Bugs)
The power item appearing in the events.log is updated every 2 minutes and not every 20 seconds

## Context

In OpenHAB 1.8.3 I am using the fritzaha binding to get every 20-30 seconds the power reading from 5 FRITZ!DECT 200 smart switches. In order to have such a fast refresh rate, I configured the binding for  the "query script" part instead of the "web service" part. By using the "web service" configuration, the fritzbox polls the smart switches every 2 minutes: no matter what the refresh interval of the binding in the openhab.cfg file is set. 
In OpenHAB 2.4 avmfritz binding the behavior is exactly the same as the "web service" and there is no possible configuration for the "query script".
More details are in my old [post](https://community.openhab.org/t/advice-on-upgrading-from-openhab-1-8-3-to-2-1-fritzaha-binding/34462).

## Your Environment
OpenHAB 2.4 with avmfritz on raspberry pi v3b
FritzOS 6.30 on Fritz!box 7360v1 (fritz!os cannot be upgraded to v7 for this device)

**Comment by lionhe1966** [comment]
I am running this binding since one week and it appears that the sampling rate is not always 2 minutes but it can be faster, usually when some switch measures some power.  If required, I can try to restore an old version of openhab (1.8.3) from my backups and try to see if such a behavior still occur.

**Comment by hmerk** [comment]
closed due to inactivity
