### ISSUE TITLE
[homematic] ON_TIME not working

### ISSUE THREAD

**Issue by tj2000bch** [openhab/openhab-addons#4712]
The function ON_Time for homematic actuators does not work anymore since the update to 2.4.

System:
Openhab 2.4 ond Debian 9
Java java version “1.8.0_191”
Homematic Binding 2.4
Homematic CCU3 3.41.11

Thing

`Thing		HM-LC-Dim1T-FM				MEQ0402217			"Licht-Gang-EG"					@	"Homematic"`

Item
`Number:Time Light_GangEG_ON_TIME "Gang EG [%.2f Sec.]" <homematic> (ON_TIME) {channel="homematic:HM-LC-Dim1T-FM:ccu2:MEQ0402217:1#ON_TIME"}`

Rules
```
createTimer(now.plusMinutes(1)) [|Light_GangEG_ON_TIME.sendCommand(0)]
createTimer(now.plusMinutes(2)) [|Light_GangEG_ON_TIME.sendCommand(900)]
createTimer(now.plusMinutes(3)) [|Light_GangEG.sendCommand(ON)]
createTimer(now.plusMinutes(5)) [|Light_GangEG_ON_TIME.sendCommand(0)]
```
           	

I found the following logs in debug mode.

```
openhab> log:tail homematic
17:02:08.134 [WARN ] [mematic.handler.HomematicThingHandler] - Can't convert type DecimalType with value '0' to FLOAT value with QuantityTypeConverter for 'MEQ0402217:1#ON_TIME', please check the item type and the commands in your scripts
17:02:12.127 [WARN ] [mematic.handler.HomematicThingHandler] - Can't convert type DecimalType with value '20' to FLOAT value with QuantityTypeConverter for 'MEQ0402217:1#ON_TIME', please check the item type and the commands in your scripts
```

**Comment by tj2000bch** [comment]
Yesterday I switched to version 2.5.0 M1 and OnTime works again.

**Comment by wborn** [comment]
Let's close the issue if it's no longer an issue in 2.5.0 M1!
