### ISSUE TITLE
[lgwebos] Allow manual configuration of TV's IP address

### ISSUE THREAD

**Issue by Alestrix** [openhab/openhab-addons#4753]
## Expected Behavior
Be able to work with the LG webOS binding across routed subnets.

## Current Behavior
Binding only supports automatic discovery which does not work across subnets.

## Possible Solution
Have an option to manualy configure the LG TV's IP address in the binding's configuration.

## Alternative Solutions
Hacks outside of the binding would be:
- Create an additional interface on OS level of the OpenHAB installation that is located in the TV's network. In this case a list of required ports should be given to be able to protect the OpenHAB install from anything coming from that additional interface with a local firewall.
- Use a broadcast relay on the router. This requires information about the necessary ports to be relayed. Also, relayed datagrams do not create a conntrack entry, thus the TV's response packets do not qualify as belonging to an "established" connection, raising the necessity of dirty firewall hacks.

## Context
My TV is in a dedicated network which can be reached (routed) from the network OpenHAB is on. Discovery is therefore not possible.
Having the TV on a separate network is my preferred setup since many TVs spy on the local devices. This way it is easier to block the TV from scanning the devices on the Private LAN, the Storage LAN, or the IoT LAN.

## Environment
Running OH 2.4 on Debian (TurnKey Core v15 appliance) as an ESXi VM.

**Comment by DaanDW** [comment]
I'm also running into this problem. This adjustment would be a major added value! Currently the Binding (Openhab) cannot find my TV because they are in a different subnet.

**Comment by sprehn** [comment]
This is already possible with the our 2.5 snapshot version, which is a major rewrite of the binding.

**Comment by DaanDW** [comment]
Do I just change `Thing lgwebos:WebOSTV:tv1 [ deviceId="<Device_ID>" ]` to `Thing lgwebos:WebOSTV:tv1 [ localIP="<TV_IP_address>" ]` ?

**Comment by sprehn** [comment]
keep deviceId but add host="<TV_IP_address>"

**Comment by DaanDW** [comment]
Like this: `Thing lgwebos:WebOSTV:tv1 [ deviceId="<Device_ID>", host="<TV_IP_address>" ]` ?

**Comment by sprehn** [comment]
actually, remove deviceId from the parameters
add host with the ip address
you will be prompted on the tv to accept the connection
afterwards use paperui to find the "Access Key" which was exchanged between OH and the device.
should look sth like this:

`Thing lgwebos:WebOSTV:tv1 [host="192.168.2.119", key="6ef1dff6c7c936c8dc5056fc85ea3aef"]`

**Comment by sprehn** [comment]
Thx for reporting this, updating documentation with PR #6436
