### ISSUE TITLE
[homematic] Change Channel Event Implementation BUTTON DOUBLE_PRESSED

### ISSUE THREAD

**Issue by lukicsl** [openhab/openhab-addons#4756]
## Expected Behavior
Pressing a button twice (or multiple) within a threshold  period (e.g. 0.3s) should generate an BUTTON DOUBLE_PRESSED event, no other events should be triggered.
It is either an SHORT or DOUBLE event not both.

## Current Behavior
First press of button generates a BUTTON SHORT_PRESSED event, if within 2s a second short press happens a BUTTON DOUBLE_PRESSED event is generated additionally.

## Possible Solution
Create a global  HM parameter (Bridge?) for double click threshold.
Suppress BUTTON SHORT_PRESSED for this threshold if within this time another short press event happens, create a BUTTON DOUBLE_PRESSED otherwise issue the held back event.

## Context
Double press event are rathe fast events and should be used for special (overridden) function of a button. In the current implementation this event is useless as the single click event comes first. 
Implementing this filtering threshold in a rule would be possible but rather complicated.

## Your Environment
OH 2.4.0 docker

**Comment by rancor187** [comment]
True, I experienced the same issue.

**Comment by hmerk** [comment]
closed due to inactivity
