### ISSUE TITLE
[amazonechocontrol] Add support to control xbox skill

### ISSUE THREAD

**Issue by fenngineering** [openhab/openhab-addons#4760]
As alexa now has an xbox one skill, how feasible would it be to control this through openhab using rules?

Id like to say "Alexa, Xbox ON"

This would:-

1) Turn on my TV - works perfectly :)
2) Turn on my Amp - works perfectly :)
3) Turn Amp to the correct input - works perfectly :)
4) Turn on Xbox - as there's no native xbox binding for openhab, the only solution I can see is to utilise the amazon echo control "somehow" to active the xbox skill.

below is a snippet of my rules file...

`//ALEXA XBOX ON`
`rule "XBOX ON"`
`when`
`  Item Xbox received command ON`
`then`
`    yamahaPower.apply("ON")`
`    YamahaAmp_Volume.sendCommand("50")`
`    YamahaAmp_Input.sendCommand("HDMI2")`
`    Echo_TTS_Volume.sendCommand("100")`
`    Echo_TTS.sendCommand("XBOX, ON")`
`    tvPower.apply("ON")`
`end`

Below is a snippet of my items file:-

`Group gLivingRoom`
`Switch      TV     		        "TV [%s]"	<tv> 			        (gLivingRoom)	[ "Switchable" ]`		
`Switch      Xbox   		        "Xbox [%s]"	<tv> 			        (gLivingRoom)	[ "Switchable" ] `
`String      Echo_TTS            "Text to Speech"                    (gLivingRoom)   {channel="amazonechocontrol:echo:b630d8da:G090LF11735626HS:textToSpeech"}`
`Dimmer      Echo_TTS_Volume     "Text to Speech Volume"             (gLivingRoom)   {channel="amazonechocontrol:echo:b630d8da:G090LF11735626HS:textToSpeechVolume"}`
I have tried issuing a TEXT TO SPEECH command but this does not work, alexa does speak "XBOX ON" but the xbox does not switch on...

Does anyone have any other solutions, I seem like I have tried everything.

Thanks

Andrew

**Comment by openhab-5iver** [comment]
[The OH forum](https://community.openhab.org/t/released-openhab2-amazon-echo-control-binding-controlling-alexa-from-openhab2/37844) would be the appropriate place for asking about functionality. TMK, this binding does not have access to skills, as answered several times in the forum. If you can't do it in the Alexa app, then you can't do it with this binding.

**Comment by fenngineering** [comment]
Ah right OK, instead of using the alexa binding - what about developing a new binding for xbox? or is there something out there?

**Comment by ngrodum** [comment]
The xbox skill can control my xbox in much cooler ways than just on/off - I can say "Alexa, tell xbox to start Netflix", or any of my xbox games, when I get to the gaming room, Netflix or my favorite game is already up and loaded. To be able to do this in a rule where I also adjust lighting, make sure the projector is on, and the amp is set to the right input etc would be quite nice.

Regardless, I think this "issue" should be closed, it should rather be discussed in the forums as a request for a new binding: controlling xbox directly in the same way the Alexa skill can do.

**Comment by fenngineering** [comment]
why was this closed?
