### ISSUE TITLE
[openhabcloud] Connection with Google Home is lost after a certain time

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#4763]
After few days, Google Home is no more working with openHAB. Google does no more connect with openHAB.
Restarting the openhab cloud connector binding solves the problem.
I am running snapshot 1480.

**Comment by Confectrician** [comment]
Maybe #4500 already solved this problem.

**Comment by wborn** [comment]
It more seems like an issue in the Cloud code see my https://github.com/openhab/openhab2-addons/pull/4500#issuecomment-451695654. If you raise the log level on `io.socket` you'll see it happily ping/pong-ing all the time. Which means the connection is up. So the cloud is marking an instance offline whereas it is online.

So I think the issue/fix should be created in the [openhab-cloud](https://github.com/openhab/openhab-cloud) project. I've already checked [app.js](https://github.com/openhab/openhab-cloud/blob/master/app.js) for bugs but couldn't find any. :neutral_face:

**Comment by lolodomo** [comment]
I can confirm that when it happens my access through myopenhab is still working.

**Comment by wborn** [comment]
There's already https://github.com/openhab/openhab-cloud/issues/134 for this. OK if we close the issue here @lolodomo? I've added my comment to it.

**Comment by lolodomo** [comment]
It looks different. In my case, the remote access in Android app is still OK. Only Google Home is not working. I could confirm the next time it happens.

**Comment by lolodomo** [comment]
It did not occur again.
