### ISSUE TITLE
[openhabcloud] Logging should be a little more talkative

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab-addons#4772]
The standard logging of the openHAB Cloud connector should provide some more basic information

## Expected Behavior
Standard INFO level logging should enable user to see if the basic functions work, like connecting to the cloud.

## Current Behavior
The only log entry I can see with standard level INFO is
```
[INFO ] [io.openhabcloud.internal.CloudClient] - Shutting down openHAB Cloud service connection
```
There's not even one entry when starting up.

## Possible Solution
I would like to see at least a log message at startup that is a counterpart of the above disconnect message. Even better, also a second message that tells if the connection was established successfully.

However, the latter I don't even see after having set the log level to TRACE.

## Steps to Reproduce (for Bugs)
Just use the connector and check the logs.

## Context
Especially useful while trying to setup the cloud connector.

## Your Environment

* openHABian with openHAB 2.4

**Comment by davidgraeff** [comment]
Logging is actually not the solution here. The framework requires an extended service status (that can than be requested via the OSGi/openHAB console or the rest interface).

**Comment by cubistico** [comment]
Well, yes, logging _is_ a solution for me, the user, who tries to find out why it doesn't work! :-)

I am not talking about extended detail logging, just in my case, the connector would not connect, and I had no idea about it, because there was no problem logged. However, I'm quite sure the connector knows the difference between being connected to the cloud or not, because once I managed to get a connection, the fact that it connected did get logged. So, what I'm asking for is a log message that tells me that it could not connect for whatever reason. I still haven't got an idea why it originally did not connect.

Reasonable?

**Comment by hmerk** [comment]
closed due to inactivity
