### ISSUE TITLE
[mqtt] Embedded broker does not retain messages over restart

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab-addons#4774]
When restarting openHAB, the embedded MQTT broker forgets all messages.

## Expected Behavior
After a restart of openHAB, retained messages should still be available from the Embedded MQTT broker.

## Current Behavior
After a restart, no messages are available on the embedded broker. The broker storage seems wiped.

## Possible Solution
I used the default configuration of the embedded broker with Persistence file = mqttembedded.bin which is the default value when creating the embedded broker. I've searched for the file on the drive, but didn't find it. Maybe I just didn't know where to look. It may be that the persistence file could not be used for some reason. In that case, an appropriate error message should be logged.

If that is not the problem, then some other problem within the binding seems to exist.

## Steps to Reproduce (for Bugs)
1. Install MQTT binding
2. Add Embedded Broker
3. Add a Generic Broker bridge
4. Add A Thing that uses the bridge
5. Put some messages (topics) on the broker
6. Restart
7. With an MQTT test client or similar, search for topics – they are all gone

## Context
The effect is that after a restart, Items that are bound to MQTT channels will not be set until new values are published to the broker.

## Your Environment
* openHABian 
* openHAB 2.4.0

**Comment by zbot473** [comment]
Is this the use of [MQTT Persistence](https://www.openhab.org/addons/persistence/mqtt/)? I'm not sure, but I think this is the way to go.

**Comment by cubistico** [comment]
I may be wrong, but I think the page you refer to belongs to MQTT 1 binding, while I refer to the new MQTT (2.4) binding.

**Comment by zbot473** [comment]
You are probably correct.
