### ISSUE TITLE
[nuki] Make state updates faster

### ISSUE THREAD

**Issue by rummens** [openhab/openhab-addons#4787]
I am using a Nuki 2.0 and the OpenHab Nuki Binding. Although it works fine, the rate at which the updates come in is very slow. It takes about 2 seconds before the "unlocked" status shows up and the "unlocking" or "locking" status never appears. Is there a way to make it faster or is the Nuki itself the issue here?

## Expected Behavior
Faster update time and appearing of the intermediate states "Locking" and "Unlocking".

## Current Behavior
Slow update time

## Possible Solution
Increase Pulling Interval?

## Context
Homecoming scenes are activated too late or not at all.

## Your Environment
OpenHab2 on Raspberry Pi with Nuki 2.0 and Bridge. 

Thanks
Marcel

**Comment by staehler** [comment]
The same thing here. I've the new nuki generation lock, which API has released a few weeks ago. Might this be the reason for missing the locking states? Does the binding need an update to a changed API?

On https://web.nuki.io the changes are recognised almost immediately, but openhab gets 'looking', 'unlooking' or 'latched', 'unlatched' more accidentally, than as a reliable state.
I think this is more a bug than a feature request, isn't it?

**Comment by hmerk** [comment]
closed due to inactivity
