### ISSUE TITLE
[verisure] Verisure Binding initial contribution

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#4788]
Verisure Binding

Initial commit of the Versiure Binding

This has already appeared as a pull request before #3455, but @jarlebh is no longer active in OH community.

I’ve made a re-design of the Verisure binding to support multiple installations/sites since I also have a Verisure installation at my summer house.

I’ve based the re-design on the work made by @Andreas_L, @jarlebh and @msv12 but updated it to handle multiple sites, the changes are not backward compatible so all discovered things will get new internal IDs.

I’ve also added support for some new things:

- Bridge
- Alarm
- Smoke Detector (climate)
- Water Detector (climate)
- Siren (climate)
- Night Control
- Yaleman SmartLock
- SmartPlug
- Door/Window Status
- User Presence Status
- Broadband Connection Status

**Comment by markus7017** [comment]
@jannegpriv @wborn any update here?

**Comment by jannegpriv** [comment]
@markus7017 Still under code review I assume, [community thread](https://community.openhab.org/t/testers-for-verisure-openhab-2-binding/7499/294) updated with the latest binding jar.
@cpmeister What is left to be done for my part?

**Comment by jannegpriv** [comment]
@cpmeister @wborn What is left to be done for this PR?
