### ISSUE TITLE
[powermax] Compatibility with RFC2217 ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#4849]
I plan to update the Powermax binding to make it fully compatible with serial over IP.
It should be easy.

**Comment by lolodomo** [comment]
For the first time, I tested my binding with the IP connection thing type and a remote serial port (serial over IP using ser2net). I can confirm that it works well.
I am trying to make RFC2217 working but with no success until now !

**Comment by lolodomo** [comment]
For RFC2217, as the read is a blocking read, I tried to use the available() method but it seems it always returns 0.
If a reader thread is running a blocking read, the read never ends even if another thread writes data.
Maybe RFC2217 is not compatible with parallel read and write ?
So finally, I will disable RFC2217. To get serial over IP, you just have to use the IP conection thing type.

**Comment by epicurean70** [comment]
hi lolodomo,
Does this means the binding will work with a USR-tcp232-e ? a direct connection from powermax panel to ethernet?

**Comment by lolodomo** [comment]
I don't know if such à card can be used.
