### ISSUE TITLE
[rfxcom] Move to the serial core bundles

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#4850]
As an old binding, the RFXCOM binding still relies on the gnu.io RXTX library.
It should be updated to use the serial openHAB core bundles.
I will work on that update.

**Comment by martinvw** [comment]
Serial over ip is already possible, but as a separate thing-type:

https://www.openhab.org/addons/bindings/rfxcom/#rfxcom-over-tcp-ip

**Comment by lolodomo** [comment]
This can be simplified; socat is not required.

**Comment by martinvw** [comment]
What do you mean? Socat offers the serial-to-ip and the binding itself does the serial-over-ip-to-binding.

So I have a pi with the RFXCOM with socat running. Then in my basement I have my server which has the specific thing-type to connect to the remote RFXCOM.

It would indeed by nice if this binding would also support it directly on the normal thing-type then we can deprecate the specific thing-type and in the end the special thing-type could be removed.

@lolodomo if needed I can test-drive, just let me know!

**Comment by lolodomo** [comment]
On your remote RPI connected to the RFXCOM, what is required is ser2net to share the local serial port on the LAN, not socat. In case socat can replace ser2net, I have not tested.

I will work on that as soon as we have again a stable IDE/OH repos and I get a new SD card for my RPI 1.

**Comment by martinvw** [comment]
Yes, I just quickly read the documentation which mentions socat, which might or might not work but I indeed also use `ser2net` sorry for the noise :-D

**Comment by lolodomo** [comment]
@kaikreuzer :  should I already consider moving the binding to the new core namespace ?

**Comment by kaikreuzer** [comment]
@lolodomo There is no new core namespace - all Java package names are untouched (with the exception of the automation component), so no need to do any kind of move. Or am I misunderstanding your question?

**Comment by lolodomo** [comment]
I just discovered and understood that the new openhab core files have an unchanged package name, that is org.eclipse.smarthome.io.transport.serial. So imports will continue to be relative to org.eclipse.smarthome.io.transport.serial.* even ifiles are org.openhab.core.io.transport.serial.

**Comment by lolodomo** [comment]
@martinvw : I see 4 opened PRs for the RFXCOM binding, all dated 2017 and all with already existing conflicts. Should I wait for a clear status on all these PRs before making the change (that will of course add more conflicts on these PRs) ?

**Comment by martinvw** [comment]
No just continue :-)
