### ISSUE TITLE
[mihome] Xiaomi Mi Smart Home Bridge - don't goes online itself

### ISSUE THREAD

**Issue by iro88** [openhab/openhab-addons#4855]
## Expected Behavior
Connection is established when Bridge goes back online.

## Current Behavior
In some cases when OpenHab loosing connection with Bridge it doesn't connect back by itself.
I also found some discussion about this on forum: https://community.openhab.org/t/xiaomi-mi-smart-home-bridge-never-goes-online-by-itself/58605 

Now I have to manually restarting binding:
`openhab> bundle:restart org.openhab.binding.mihome`

## Possible Solution
Trying to connect with offline Bridge in some interval.
Maybe it's related to: https://github.com/openhab/openhab2-addons/issues/4857

## Steps to Reproduce
Order of network connection is the key, when Bridge is established after initialization OpenHab it will stay "offline" forever. It's hard to reproduce in normal environment, because OpenHab initialization take some time and in theory Bridge should be connected to network before it ends, but it's happened to me.

Given: OpenHab with binding and connected Bridge (status "online")
When: power off network device, OpenHab, Bridge
And: power on network device, OpenHab (withouth Bridge)
And: after while power on Bridge
Then: OpenHab still have "offline" status

## Context
Bridge connects with sensors, which are part of my security system, so it's important for me to ensure everything work properly even unexpected power/network breaks. I know that, author of forum topic resolve his problem by adding a rule (not without problems), but it's some kind of workaround for me.

## Your Environment
* Version used: openHAB 2.4.0-1, binding-mihome 2.4.0
* Operating System and version: Openhabian on Raspberry PI 3B+

**Comment by hmerk** [comment]
closed due to inactivity
