### ISSUE TITLE
[mihome] Xiaomi Mi Smart Home Bridge - out-of-date status

### ISSUE THREAD

**Issue by iro88** [openhab/openhab-addons#4857]
## Expected Behavior
Status of Bridge is up-to-date.

## Current Behavior
When I power off Bridge it's still "online" in OpenHub Things. When I power on Bridge, after few minutes, everything works properly.

## Possible Solution
Checking status Bridge in some interval.

## Steps to Reproduce
Given: OpenHab with binding and connected Bridge (status "online")
When: power off Bridge
Then: it's still "online" (even after few minutes)

## Your Environment
* Version used: openHAB 2.4.0-1, binding-mihome 2.4.0
* Operating System and version: Openhabian on Raspberry PI 3B+

**Comment by hmerk** [comment]
closed due to inactivity
