### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#4870]
Here are the logs I got:
```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.2.0:compile (default-compile) on project org.openhab.binding.avmfritz: Compilation failure: Compilation failure:
[ERROR] D:\dev\openhab2\git\openhab2-addons\addons\binding\org.openhab.binding.avmfritz\src\main\java\org\openhab\binding\avmfritz\internal\AVMFritzHandlerFactory.java:[31]
[ERROR]         import org.eclipse.smarthome.io.net.http.HttpClientFactory;
[ERROR]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.eclipse.smarthome.io.net.http.HttpClientFactory cannot be resolved
[ERROR] D:\dev\openhab2\git\openhab2-addons\addons\binding\org.openhab.binding.avmfritz\src\main\java\org\openhab\binding\avmfritz\internal\AVMFritzHandlerFactory.java:[130]
[ERROR]         protected void setHttpClientFactory(HttpClientFactory httpClientFactory) {
[ERROR]                                             ^^^^^^^^^^^^^^^^^
[ERROR] HttpClientFactory cannot be resolved to a type
[ERROR] D:\dev\openhab2\git\openhab2-addons\addons\binding\org.openhab.binding.avmfritz\src\main\java\org\openhab\binding\avmfritz\internal\AVMFritzHandlerFactory.java:[134]
[ERROR]         protected void unsetHttpClientFactory(HttpClientFactory httpClientFactory) {
[ERROR]                                               ^^^^^^^^^^^^^^^^^
[ERROR] HttpClientFactory cannot be resolved to a type
```

**Comment by davidgraeff** [comment]
Just to be sure: You are using the very latest checkout of openhab2-addons? I'm wondering why there is still "org.eclipse.smarthome" referenced, as we do not use ESH anymore.

**Comment by lolodomo** [comment]
Yes, update done yesterday evening.
Note that imports to leave were unchanged.

**Comment by davidgraeff** [comment]
Hm. Why is Travis building the binding. It should use the exact same instructions to start a maven build.
I have added the bug label as it seems to be a build system issue.

@maggu2810 @kaikreuzer

**Comment by cweitkamp** [comment]
I am not faceing the reported build issue. Can you try `mvn dependency:purge-local-repository` to make sure your local dependencies are up-to-date? Purging the local `~/.m2` folder could help too but is a little but more aggressive :wink:.

**Comment by lolodomo** [comment]
After removing my .m2 folder, the build goes further. Thank you @cweitkamp for the tip.
In fact, it is failing in Astro Binding Tests.
But if I run `mvn clean install -Dmaven.test.skip=true`, then it fails in NEEO Integration with a OutOfMemoryError exception (GC overhead limit exceeded):
```
[ERROR] Failed to execute goal org.openhab.tools.sat:sat-plugin:0.5.0:spotbugs (default) on project org.openhab.io.neeo: Unable to execute mojo: Execution null of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.3:spotbugs failed: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by davidgraeff** [comment]
@lolodomo Could you please use the square brackets "[]" with the binding that causes problems in there? That patterns helps us organizing.

**Comment by lolodomo** [comment]
Finally if I disable tests AND checks ( mvn clean install -Dmaven.test.skip=true -DskipCheckss=true ), the build succeeds.
