### ISSUE TITLE
[yeelight] Problems when many devices are added

### ISSUE THREAD

**Issue by claell** [openhab/openhab-addons#4896]
As reported on the Forum, the Yeelight binding has problems when many devices are connected. They sometimes go offline and don't go online anymore: https://community.openhab.org/t/yeelight-binding/13735/247?u=clel

Maybe related to #3666

Maybe you have some time to look into this @goodfore? Also I think that @themillhousegroup has fixed a similar problem for the Broadlink binding recently.

**Comment by goodfore** [comment]
I can take a look, but I only have 2 bulbs, so I can't really replicate the issue. So far I have issues with the bulbs going into non-responsive mode when I switch binding (upgrading/sideloading Yeelight binding). Not sure that's related.

**Comment by claell** [comment]
Alright, no problem. Maybe you find some code which might cause it. I think the problem from @themillhousegroup was related to search requests not timing out or something like that. But it is up to you, if you want to take a look. If not, at least we have an issue to track the problem :smiley:

**Comment by goodfore** [comment]
@claell I am wondering about the following code. Is there a reason we need a task for each channel, instead of one updater task for one thing? The returned status should have enough info for all the channels.

```
    @Override
    public void channelLinked(ChannelUID channelUID) {
        logger.debug("ChannelLinked -> {}", channelUID.getId());
        super.channelLinked(channelUID);

        Runnable task = () -> {
            mDevice.queryStatus();
        };
        scheduler.schedule(task, 500, TimeUnit.MILLISECONDS);
   }
```

**Comment by claell** [comment]
I cannot remember a reason. However I remember that there might be redundant status queries etc. in the code which might not be needed. So if it works for you when removing it, it is probably fine. I agree with you that removing those unnecessary traffic is a good thing. However I fear this won't fix problems with devices going offline and not coming back again.

**Comment by claell** [comment]
Another user reports this problem with having only one light strip connected. Maybe this is related to certain device types.

**Comment by frest-de** [comment]
I have the offline-bug as well with 3 devices (bulbs). Some are online, some are offline. I can control them using miio, but that does not work for color or brightness.

**Comment by hmerk** [comment]
closed due to inactivity
