### ISSUE TITLE
[toon] Update binding for new API backend

### ISSUE THREAD

**Issue by GertJanArts** [openhab/openhab-addons#4902]
It looks like the Toon API add-on is no longer working. Since yesterday the status is OFFLINE. Invalid api resonse status: 503
Login and passwords are checked.

Found on Eneco forum:
_"I checked and received an answer that the old backend is no longer usable, the advice is to use the current Api backend, Apps such as Olisto and Homey already connect with the current backend."_

Looks like the OpenHAB Toon API uses the old (offline) backend.

**Comment by thomasmul** [comment]
Is anyone working on this?

**Comment by MichaBrans** [comment]
Any updates on this, still is not working, so the binding is completely useless :-(

**Comment by kaikreuzer** [comment]
Probably best to ask the original author of the binding, @jongj.
I agree that if the binding is not adjusted, we will have to remove it from the distro.

**Comment by jongj** [comment]
I replaced my boiler and with it came a new thermostat, as a result I no longer have a TOON subscription. As a result updating the binding to the new api is kind of difficult for me. 

The new api appears close to the old one, so it should not be to difficult to update the binding, provided you have a working TOON account ofcourse.

**Comment by MichaBrans** [comment]
Hoi Jorg,
Stuur me even een email met instructies als ik kan helpen.
Ik heb een Toon account.
Micha

**Comment by syrisara** [comment]
Mooie suggestie Micha,

Hopelijk komen we zo toch aan een werkende binding. Ik sta op het punt Toon samen met Eneco de deur uit te doen dit.omdat het mij om deze werkende binding ging.

Mocht ik met mijn beperkte kennis kunnen helpen dan doe ik dat ook graag.

Raymond

**Comment by thomasmul** [comment]
> Hoi Jorg,
> Stuur me even een email met instructies als ik kan helpen.
> Ik heb een Toon account.
> Micha

Kun je dat ook voor andere toons doen? Ik wacht al maanden op een oplossing om mijn toon weer werkend in openhab te krijgen?

**Comment by defcon8** [comment]
Anybody still working on this?

**Comment by Hilbrand** [comment]
Ter informatie: I've removed the current toon binding (#6802) because it doesn't work anymore so it won't result in disappointed users installing the toon binding only to find out it doesn't work. If someone wants to create a binding based on the old toon binding, the code is still here so it can still be used as starting point.

If someone wants to fix this binding make sure to start from a rebased branch with the binding removed otherwise merging could be some work due to conflicts with the removed code.

**Comment by syrisara** [comment]
Beste optie is je Toon te rooten en de openhab binding voor rooted Toons te gebruiken. Werkt prima.

**Comment by hmerk** [comment]
closed due to inactivity
