### ISSUE TITLE
[nadreceiver] Add NAD Receiver Binding

### ISSUE THREAD

**Issue by marcdevinci** [openhab/openhab-addons#4932]
**Context**
I own a NAD receiver (https://nadelectronics.com), the T758v3. I always owned NAD A/V receivers and I'm very happy with it. The need to have it connected to my home automation system increased with time. For example, I have a smart power plug for my amplifier and pre-amplifier, in addition to my A/V Receiver. My goal would be to activate my smart power plug when the NAD T758v3 has power status ON. The same when it goes OFF, the smart plug should be deactivated. I would reduce my power consumption by 10-12W (stand by consumption measured by my smart plug).
Another scenario that I imagined is to put on mute if I'm receiving a call or if someone is ringing at my door. Anyway, I shouldn't explain all possibilities that an OpenHab binding offers ;-)

I'm also using OpenHab to connect different home automation providers and it is very powerful. Because I didn't find a proper "NAD Receiver Binding", I decided to develop one.

**Project**
I'm implementing one binding for NAD receivers using the Telnet interface. For the initial version I plan to support following channels (or let's call them "features"):
- Power On/Off
- Volume control
- Mute
- Sources switch

In a second step I will include other supported features such as advanced sound control (Basse, Treble), etc. It will also depend on the potential feedback from the community.

A working prototype already exist but I plan to "release" something between April & June 2019.

**Solution description:**
- One thing `<nadreceiver>` with several channels (power, volume, mute, source). For the moment, the binding is done in a generic way - in other words if other or new receivers have different or new features, I will probably have to offer the possibility to declare different things.
- Sources will be read from the interface during the initialisation process (Maximum number of sources will have to be configured - on NAD T758v3 maximum number of sources is 10)
- IP address and port will have to be configured when the `thing` is declared (no UPNP possible since the receiver is not supporting it) - If someone has a reliable method how to detect the receiver, I'm happy ti listen.
- Optional: Connection retry interval will have to be configured as well
- As soon as the status is ONLINE, several Telnet requests will be done to collect current states of different channels (Power, mute, volume, sources, current source)

**Testing**
- I will test it with my NAD T758v3 but I would be happy to get some support from the community to test it on other NAD receivers or even on the same receiver. Different configurations might have different results and other receivers might have less or more features. 

** Next steps **
As recommended through the page https://www.openhab.org/docs/developer/development/bindings.html, I'm creating an issue and plan to come up with a pull request soon.

Any comments or feedback are welcome.

**Comment by marcdevinci** [comment]
Hi @wborn , I was not able to finalise my binding last year. I would like to finalise it during the next weeks but meantime lot of things changed (Great job btw). Could you please give me some advices how to proceed now? Should I create a new binding and copying my business logic to the new binding template? Or is there an easy way to "convert" my current code? Actually my current code is not working with OpenHab 2.5. So please help me and give me some guidance. Thanks a lot in advance!

**Comment by wborn** [comment]
There is a tutorial on how to convert your binding to the new build system:

[Tutorial: Migrate your binding to the Maven + Bnd based build system](https://community.openhab.org/t/tutorial-migrate-your-binding-to-the-maven-bnd-based-build-system/81389?u=wborn)

I missed one tiny detail myself the first time I converted a binding and then it became difficult. If you run into an issue just ask for help here or in that thread. It helps if you also provide a link to your GitHub branch so people can have a look at the code.
