### ISSUE TITLE
Travis: Use "GitHub App" instead of "Service"

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#4935]
There is still the old Travis service hook in place although the repository seem to run on the Travis Github App already. Can we remove the old hook?
![bildschirmfoto vom 2019-02-19 14-05-04](https://user-images.githubusercontent.com/66436/53017050-669aea00-344f-11e9-8b9d-7e6f68af5866.png)

**Comment by kaikreuzer** [comment]
Thanks - I've removed the service.

**Comment by davidgraeff** [comment]
To use the new Github checks API (let our sat tool append it's status report in the "Checks" tab for example) we need to use the Travis CI Github App. But I think we are currently only using webhooks.

**Comment by davidgraeff** [comment]
@openhab/2-x-add-ons-maintainers 
Can someone please add the travis github app to the organisation?
This is more powerful then webhooks.

See also https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com .

**Comment by martinvw** [comment]
@kaikreuzer its seems that I do not have enough power for such actions.

**Comment by kaikreuzer** [comment]
Done. It took me a while that the whole trick is to use travis-ci.com instead of travis-ci.org...
