### ISSUE TITLE
[knx] Add support for DPT 251.600 for RGBW colour

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab-addons#4939]
The DPT 251.600 is required to gain full control over the white channel as well.

The 251.600 is a 6-byte value, each value (R, G, B and W) occupying 12 bits.

**Comment by reneduhan** [comment]
I have the same requirement, can i support someone for this issue with my programer experience?

**Comment by petrklus** [comment]
@lewie may be able to help / provide roadmap?

**Comment by TOM01011963** [comment]
I have the same requirement, is there any new information?

**Comment by manroh** [comment]
Same requirement from my side

**Comment by imaginator** [comment]
This issue looks like it's a duplicate of https://github.com/openhab/openhab-addons/issues/4844

**Comment by doits** [comment]
👍 really important for dali dt8 lights and controlling them with knx dali gateways

**Comment by J-N-K** [comment]
How would you model RGBW in openHAB?

**Comment by imaginator** [comment]
@jnk - it's already modelled by other controllers. eg Philipps HUE.

**Comment by J-N-K** [comment]
I don't see RGBW support in the hue binding. I'm talking of the openHAB integration. There is no easy two-way conversion between RGBW and HSB and we can't link two items (Color for RGB and Dimmer for W) to one channel.

**Comment by imaginator** [comment]
You are right. What's then the best way to control the RGB channels and then probably independently configure the white channel. Would you recommend the brightness then control the white + rgb channels?

**Comment by florian-h05** [comment]
@holgerfriedrich Has this been fixed with your recent PRs?

**Comment by holgerfriedrich** [comment]
@florian-h05 it seems that we now have better support for different color controls. Docs could still be improved (examples) and I want to see it working.... I have a MDT color dimmer at hand but need to adapt the config. Needs some time to do it.
