### ISSUE TITLE
[homematic] HMW-IO-12-Sw14-DR error when using DIGITAL/ANALOG ( frequency) Input

### ISSUE THREAD

**Issue by meins0273** [openhab/openhab-addons#4944]
I have a problem with the Homematic Multi IO module hmw-io-12-sw14-dr. I use the file OH 2.4 and Raspberrymatic with the latest version. Where a test with a CCU2 with the latest version and OH2.4 came to the same result.
The binding has a problem with the input channels 15-20. With these channels you can usually choose whether you want to use the input as analog (frequency measurement) or digital (state). Openhab recognizes your input at first login and sets the configuration. After that, Openhab can no longer switch between analgo and digital. Openhab will not recreate the channel. Worse still, if you have more than one of these modules, all the other modules will be configured relative to channels 15-20 of the first one. Even if you deregister all modules and create new data points are not created again. Only after uninstalling Openhab and rebuilding it will the channels be recreated. But just as described above only once.

## my Environment:
Raspberrymatic with the latest Version.
OH 2.4
OS Linux Debian

Kind regards

**Comment by hmerk** [comment]
closed due to inactivity
