### ISSUE TITLE
[marytts] Upgrade to 5.2 to support a lot more languages

### ISSUE THREAD

**Issue by tigre-bleu** [openhab/openhab-addons#4952]
According to [MaryTTS Webiste](http://mary.dfki.de/), a lot more languages are supported than in current binding.
- Currently in OpenHAB: German or English
- In MaryTTS 5.2: German, British and American English, French, Italian, Luxembourgish, Russian, Swedish, Telugu, and Turkish

As far as I can see for this repository, the binding is based on MaryTTS 5.1.

It should be nice to upgrade to 5.2 and to improve the offline language support in OpenHAB.

**Comment by wborn** [comment]
There's a test JAR for MaryTTS 5.3-SNAPSHOT in https://github.com/openhab/openhab2-addons/issues/3953.

I also looked into adding more languages but it will hugely inflate the openHAB addons (> 100 MB if I remember correctly).

Maybe the other languages can be added through other means e.g. by installing them using the IoT Market Place.

**Comment by davidgraeff** [comment]
Can this be solved via a maven dependency after a bnd migration?

**Comment by hmerk** [comment]
closed due to inactivity
