### ISSUE TITLE
[hue] ON - OFF - ON does not keep brightness (Snapshot 1535)

### ISSUE THREAD

**Issue by michaeljoos72** [openhab/openhab-addons#4996]
It seems that the brightness is not restored correctly:

1.
Item Light_Sofa_Toggle = ON
Light_Sofa_Dimmer = "29,63,100" (REST API)

2. 
Item Light_Sofa_Toggle = OFF
Light_Sofa_Dimmer = "29,63,0" (REST API)

3.
Item Light_Sofa_Toggle = ON
Light_Sofa_Dimmer = "**29,63,1**" (REST API)

And the bulb does confirm this :)

My Items:

```
Switch Light_Sofa_Toggle "Sofa" <hue>	{channel="hue:0210:001788215d9c:1:color"}
Color Light_Sofa_Dimmer "Sofa" <colorlight> {channel="hue:0210:001788215d9c:1:color"}
```

openHAB Snapshot 1535
binding-hue - 2.5.0.SNAPSHOT

**Comment by cweitkamp** [comment]
Confirmed. Fixed with PR #5009.
