### ISSUE TITLE
[yamahareceiver] Party Mode not working with RX-V771

### ISSUE THREAD

**Issue by tlindener** [openhab/openhab-addons#5041]
Expected behavior:

Having configured the Receiver Binding I want to turn on the party mode. 

Actual behavior:
The second Zone is correctly activated but party mode is not started

The desc.xml is the following:

[desc.zip](https://github.com/openhab/openhab2-addons/files/2926970/desc.zip)

**Comment by hmerk** [comment]
closed due to inactivity
