### ISSUE TITLE
[homematic] HmIP-BBL not working if added as Rollershutter

### ISSUE THREAD

**Issue by lukaskrawczyk** [openhab/openhab-addons#5042]
## Expected Behavior

Clicking up/down/stop buttons on an Rollershutter item within any of OpenHUB interfaces should move the resp. shutters driven by an HmIP-BBL device

## Current Behavior

Clicking up/down/stop does not move the shutters for HmIP-BBL devices (HmIP-BROLL are working though). The command is recognized within the logs:

```
19:07:40.969 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'BBL_TYPE' received command DOWN
19:07:40.971 [INFO ] [arthome.event.ItemStatePredictedEvent] - BBL_TYPE predicted to become DOWN
19:07:40.973 [INFO ] [smarthome.event.ItemStateChangedEvent] - BBL_TYPE changed from 0 to 100
```

However, it is possible to control the shutters if the channel is configured as Dimmer typed item (using the slider). Controlling the shutters using the XML-API is working as well (e.g. http://raspmatic/addons/xmlapi/statechange.cgi?ise_id=1234&new_value=100, with 1234 being the resp. datapoints ise_id)

## Steps to Reproduce (for Bugs)
1. Install the Openhab binding
2. Register a HmIP-BBL device as thing
3. Add the datapoint HmIP-RF.{ID}:4.LEVEL as rollershutter

```
// homematic.items (Snip)
// Working
Rollershutter BROLL_TYPE "Level" (gRollershutter) {channel="homematic:HmIP-BROLL:deadbeef:001117deadbeef:4#LEVEL"}

// Not Working
Rollershutter BBL_TYPE "Level" (gRollershutter) {channel="homematic:HmIP-BBL:deadbeef:001118deadbeef:4#LEVEL"}

// Workaround (Working)
Dimmer BBL_TYPE "Level" (gRollershutter) {channel="homematic:HmIP-BBL:deadbeef:001118deadbeef:4#LEVEL"}
```

## Context
Since I have a mixed setup (Both, HmIP-BROLL and HmIP-BBL actors) and I'd like to control all shutters within a room at the same time. So far this is working for HmIP-BROLL, but not HmIP-BBL actors. 

## Your Environment

* Tested on OH 2.4M6 and OH2.5M1 (Docker)
* Tested on RaspberryMatic 3.43.15.20190223 and RaspberryMatic 3.41.11.20190126
* Latest XML-API on RaspberryMatic (1.20)
* Ubuntu Linux 18.04.02 LTS Server

**Comment by danst0** [comment]
Did you manage to control the slate orientation for Raffstores?

Daniel

**Comment by MHerbst** [comment]
Is probably the same problem as #6145. I have uploaded a test jar, see here: https://github.com/openhab/openhab-addons/issues/6145#issuecomment-655024735
