### ISSUE TITLE
[knx] Control item doesn’t respond to read request from the bus

### ISSUE THREAD

**Issue by FSeidinger** [openhab/openhab-addons#5044]
## Prerequisites
1. A configured knx thing with a channel of type *-control (e.g. switch-control)
2. A link of the channel to an item in OH2 (e.g. Switch)
3. A sitemap with an element type referencing the item (e.g. Switch)
4. The state if the item is defined (e.g. ON)

## Expected Behavior
If the bus sends a read request to the main GA of the control channel, OH responds with a read response telling the current state of the item.

## Current Behavior
If the bus sends a read request to the main GA of the control item, there is no response from OH2.

## Use Case
The bus lost and regains power or the device the GA is connected to was reset. Most devices can be configured to send a read request to get the current state.

## Possible Solution
None.

## Steps to Reproduce (for Bugs)
1. Configure a device to read from the main GA in ETS
2. Configure OH and the knx binding as described in the prerequisites
3. Start the group monitor in ETS
4. Select the main GA of the control item
5. Read from the address -> A read request is seen on the bus
6. Wait some 10 seconds
7. Verify that there is no response to be seen on the bus

## Context
My context is that I want to implement the general use case mentioned above.

In my case I use an LED indicator with 12 status LEDs build by MDT. One of the LEDs displays the status of an item owned by OH2. When I change the state the bus writes are OK and the LED displays the state accordingly.

But if the LED indicator lost connection either by lost power on the bus or because it was reprogrammed, it tries to get the current state from OH by sending a read request but never gets an answer and therefore doesn't display a state at all. This is the default as given by the application program of the LED indicator.

I followed the documentation of control items with the exception that there is only one channel (the knx channel) linked to the item. No second hardware is involved. I guess that this is called a virtual item in the OH2 terminology.

## My Environment
* I'm using openHAB 2.4 running from a docker image on my NAS
* The NAS (docker host) is running Ubuntu 18.04 LTS
* For network connectivity I'm using a macvlan directly attached to the main ethernet interface
* For programming and testing the knx installation I'm using the ETS5 professional version

**Comment by doits** [comment]
In my case it definitely works, but only for the main ga. Like if the switch-control has `ga="7/0/200+7/0/201"`, I can send read requests to the main ga `7/0/200` and openhab answers them correctly, but `7/0/201` stays silent and is never sent to the bus (not even when the switch changes its status).

So for the main ga it should work, at least it does in my oh2 2.4 setup.

**Comment by FSeidinger** [comment]
Maybe we are chasing ghosts here.

I took the calimero KNX lib distribution and experimented with the tools to manually create GroupValueRead telegrams. The result is that the group read times out. So no answer to calimero. And also no telegram can be seen in the ETS group monitor.

So my guess is, that my KNX router doesn't forward them. Because its a router I cannot say for sure, because the bus monitor is not supported by KNX routers.

Are there any known limitations on let's say vendors or protocols that might prevent that the GroupValueRead is send through the KNX router?

To be clear. This behavior can only be seen for group addresses, that have not association to a knx device. Hence being a *-control item in the KNX binding.

**Comment by FSeidinger** [comment]
After doing further investigation I can add now the following insights:

In my case using the MDT IP Interface/Router SCN-IP100.01 you have to configure the KNX bridge with type "ROUTER". If using the type "TUNNEL", the IP router doesn't forward the `GroupValueRead `telegram.

Without further doing the `GroupValueRead `telegram is picked up, but not answered by the `DeviceThingHandler`. The problem here lies in the code of the method `sendGroupValueResponse`. This method checks, if there is any matching `groupAddressesRespondingSpec` and skips sending the telegram if this is not the case (look for the `if (os.isPresent())` part for details).

Here is the draft from the source code:

```java
/** KNXIO */
private void sendGroupValueResponse(Channel channel, GroupAddress destination) {
    Set<GroupAddress> rsa = getKNXChannelType(channel).getWriteAddresses(channel.getConfiguration());
    if (rsa.size() > 0) {
        logger.trace("onGroupRead size '{}'", rsa.size());
        withKNXType(channel, (selector, configuration) -> {
            Optional<OutboundSpec> os = groupAddressesRespondingSpec.stream().filter(spec -> {
                GroupAddress groupAddress = spec.getGroupAddress();
                if (groupAddress != null) {
                    return groupAddress.equals(destination);
                }
                return false;
            }).findFirst();
            if (os.isPresent()) {
                logger.trace("onGroupRead respondToKNX '{}'", os.get().getGroupAddress());
                /** KNXIO: sending real "GroupValueResponse" to the KNX bus. */
                getClient().respondToKNX(os.get());
            }
        });
    }
}
```
After a fresh start the field `DeviceThingHandler.groupAddressesRespondingSpec` is initialized with an empty list. Hence the `GroupValueResponse` is never send but always skipped.

The `groupAddressesRespondingSpec` will get filled by the method `handleCommand` if you send a command the the control-item (look for the `rememberRespondingSpec` part for details):

```java
/** Handling commands triggered from openHAB */
@Override
public void handleCommand(ChannelUID channelUID, Command command) {
    logger.trace("Handling command '{}' for channel '{}'", command, channelUID);
    if (command instanceof RefreshType && !isControl(channelUID)) {
        logger.debug("Refreshing channel '{}'", channelUID);
        withKNXType(channelUID, (selector, configuration) -> {
            scheduleRead(selector, configuration);
        });
    } else {
        switch (channelUID.getId()) {
            case CHANNEL_RESET:
                if (address != null) {
                    restart();
                }
                break;
            default:
                withKNXType(channelUID, (selector, channelConfiguration) -> {
                    OutboundSpec commandSpec = selector.getCommandSpec(channelConfiguration, typeHelper, command);
                    // only send GroupValueWrite to KNX if GA is not blocked once
                    if (commandSpec != null
                            && !groupAddressesWriteBlockedOnce.remove(commandSpec.getGroupAddress())) {
                        getClient().writeToKNX(commandSpec);
                        if (isControl(channelUID)) {
                            rememberRespondingSpec(commandSpec, true);
                        }
                    } else {
                        logger.debug(
                                "None of the configured GAs on channel '{}' could handle the command '{}' of type '{}'",
                                channelUID, command, command.getClass().getSimpleName());
                    }
                });
                break;
        }
    }

}
```

There is something else going on with the `groupAddressesRespondingSpec` regarding the `groupAddressesWriteBlockedOnce` feature, which is unclear to me. It looks like some kind of `exactly once delivery` mechanism but gets in the way, when KNX and opnenhab are interacting. I've noticed the following behavior with that:

If knx emits GroupReadTelegrams for the control-item, it can happen that you cannot send commands to the control-item anymore. You will find the following log entries then:

```
[.internal.handler.DeviceThingHandler] - Handling command '1' for channel 'knx:device:bridge:cc31d1f0:10'
[.knx.internal.channel.KNXChannelType] - getCommandSpec testing Keys '[ga]' for command '1'
[.knx.internal.channel.KNXChannelType] - getCommandSpec key 'ga' uses expectedTypeClass 'class org.eclipse.smarthome.core.library.types.DecimalType' witch isInstance for command '1' and dpt '2.001'
[.internal.handler.DeviceThingHandler] - None of the configured GAs on channel 'knx:device:bridge:cc31d1f0:10' could handle the command '1' of type 'DecimalType'
```

Sending other command values can help to unlock this situation. Can help means in this context that sometimes it works, but sometimes not. Unlocking is guaranteed when writing the control-item a new value from the knx side via groupmonitor.

**Comment by FSeidinger** [comment]
I would like to jump in on this issue and try to make improvements. Unfortunately the knx binding currently doesn't have nearly any test.

This is why I think that adding a test net for the knx binding is the first thing to do in order to raise quality with respect to maintainability.

**Comment by 1896FCZ** [comment]
Not sure, but i think i am struggling exactly with this problem.
- ETS and the KNX bus do everything correct. They switch ON / OFF as expected. Leveraging the ETS diagnostic tool, all perfect and all as expected
- When using openHAB 2.5.3 Release Build, and the iPhone App to switch ON, than the KNX bus reacts as expected, however, in the GUI the status of the Switch immediately jumps back to OFF (even the status in the KNX bus is ON). The same happens the other way around. If turning OFF, Openhab remains ON, whilst the KNX does the right thing and goes to OFF.
- Reading in the ETS diagnostic tool the current value turns into Openhab immediately updating to the correct status (ON or OFF)

ETS
++++
- GA with MDT Switch BE-GT08x.01 Glass Plus
- connected to the GA (0/1/20) taste 3 and LED 3; There is no actor. 

Openhab
+++++++

Things:

> Bridge knx:ip:bridge [ 
    type="TUNNEL",
    ipAddress="10.1.1.2",
    portNumber=3671, 
    readingPause=50, 
    responseTimeout=10, 
    readRetriesLimit=3, 
    autoReconnectPeriod=30 //optional, do not set <30 sec.
] {
    Thing device generic [ 
        // 24.03.2020 deaktiviert address="2.1.1" und ersetzt durch address="1.1.3",
        address="1.1.3",
        fetch=true,
        pingInterval=300,  
        readInterval=3600 
    ] {
        Type switch-control             : FerienAbwesend                                                   "Wir sind in den Ferien / Abwesend"                          [ ga="<0/1/20" ]  
    }
}

Items:

> Switch FerienAbwesend                                                       "Wir sind in den Ferien / Abwesend [%s]"   <vacation>             (All, gTechnik, gUG_Garage, gSQLAllChangesRestoreOnStartup)                    { channel="knx:device:bridge:generic:FerienAbwesend", autoupdate="false" }

**Comment by tmsch13** [comment]
I’m strugeling with maybe the same problem while trying to send a Day/Night Object from OpenHAB (3.0) to the KNX Bus using a switch-control Channel

![Bildschirmfoto 2021-02-03 um 09 43 01](https://user-images.githubusercontent.com/47982199/106720893-4c3e8480-6604-11eb-8080-25f3eeb2b67c.png)

 ```
 - id: ch_Zentral_Status_TagNacht
    channelTypeUID: knx:switch-control
    label: KNX Tag Nacht
    description: ""
    configuration:
      ga: 1.002:10/0/1
```

When I have a active Diagnose Monitor in ETS I see changes of my Openhab Item on the Bus.
But when I stop the Monitor, change the Item in OpenHAB, then read the Value in ETS the wrong status is received in ETS.
So thats maybe a little bit different to the Problem reported above, but It’s as close that I thing my information are right here...

openhab.log:
![Bildschirmfoto 2021-02-03 um 09 50 55](https://user-images.githubusercontent.com/47982199/106722092-d3d8c300-6605-11eb-9e65-0e225752c194.png)

KNX Monitor in ETS5:
![Bildschirmfoto 2021-02-03 um 09 53 00](https://user-images.githubusercontent.com/47982199/106722102-d76c4a00-6605-11eb-889d-d59df0b4a664.png)

**Comment by Joerg-Dr** [comment]
I think I have a similar problem with read requests, but in my case the answer to the request causes an exception:

```
Read request on GA 5/5/3 (DPT 1.001) = switch control
-----------------------------------------------------

18:03:14.180 [TRACE] [knx.internal.client.AbstractKNXClient] - Received a Group Read Request telegram from '1.1.251' to '5/5/3' with value '[]'
18:03:14.185 [TRACE] [x.internal.handler.DeviceThingHandler] - onGroupRead Thing 'knx:device:4b5cd903:3db268168c' received a GroupValueRead telegram from '1.1.251' for destination '5/5/3'
18:03:14.191 [TRACE] [x.internal.handler.DeviceThingHandler] - onGroupRead isControl -> postCommand
18:03:14.195 [TRACE] [x.internal.handler.DeviceThingHandler] - onGroupRead size '1'
18:03:14.199 [TRACE] [x.internal.handler.DeviceThingHandler] - onGroupRead respondToKNX '5/5/3'
18:03:14.203 [TRACE] [knx.internal.client.AbstractKNXClient] - respondToKNX groupAddress '5/5/3', responseSpec 'org.openhab.binding.knx.internal.channel.WriteSpecImpl@d585f4'
18:03:14.207 [TRACE] [knx.internal.client.AbstractKNXClient] - sendToKNX mappedValue: 'on' groupAddress: '5/5/3'
18:03:14.211 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: null
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.send(ProcessCommunicationResponder.java:256) ~[?:?]
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.write(ProcessCommunicationResponder.java:249) ~[?:?]
        at tuwien.auto.calimero.device.ProcessCommunicationResponder.write(ProcessCommunicationResponder.java:226) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.sendToKNX(AbstractKNXClient.java:460) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.respondToKNX(AbstractKNXClient.java:439) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$8(DeviceThingHandler.java:297) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.sendGroupValueResponse(DeviceThingHandler.java:286) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.lambda$10(DeviceThingHandler.java:318) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.withKNXType(DeviceThingHandler.java:148) ~[?:?]
        at org.openhab.binding.knx.internal.handler.DeviceThingHandler.onGroupRead(DeviceThingHandler.java:312) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient$1.lambda$1(AbstractKNXClient.java:115) ~[?:?]
        at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$8(AbstractKNXClient.java:258) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```
