### ISSUE TITLE
[tplinksmarthome] Add support for TP-Link HS107, HS300, KP200, and KP400

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-addons#5051]
HS107, HS300, KP200, and KP400 are devices with more than 1 outlet on the same device. The HS107, KP200 and KP400 all have 2, and the HS300 has 6 outlets. These outlets can be controlled separately and also have the ability to read power usage. Because of this they also have different control commands and require additional programming to be supported by the tplinksmarthome binding.

_This issue report is also to report some work already has been done to add support for these devices. However since not all commands are known it's still a work in progress. And since I don't have either device I can't test this._

Anyone who has such a device and is interested in support for one of these devices please comment in this item.

### Power outlet devices:
* HS107 Smart Wi-Fi Plug, 2-Outlets
* HS300 Smart Wi-Fi Power Strip
* KP200 Smart Wi-Fi Power Outlet, 2-Sockets
* KP400 Smart Outdoor Plug

### Open questions
The following questions remain open with regards to how the devices work:
1. Is it possible to switch all outlets at once?
1. Energy reading command needs to be given for each outlet (based on what I see with other implementations of support for these devices). Is is possible to get readings for multiple devices at once?
1. Is is possible to get a total energy reading for all outlets combined?
1. Can the status leds be switch on and off like with the plugs and switched?

**Comment by babela** [comment]
In regard to the open questions:
1) on the HS200 it is possible to switch both outlets at once.  I am using tasker to control a HS100 as described here:
https://www.reddit.com/r/tasker/comments/52lvhq/how_to_control_a_tplink_hs100/

The same code when sent to the HS200 switches on/off both outlets.  I have not figured out how to automate switching the HS200 outlets individually. 

4) from the KASA app you can disable/enable the leds, so we should be able to do this programmatically as well.

**Comment by Hilbrand** [comment]
@babela thank you for your interest. But I don't understand what you're talking about. This is about multi socket plugs. The HS200 is already supported for some time by the binding and is a light switch, not a socket? Also the HS100 is supported by the binding. So I don't understand why you would need  tasker for that if you can use the binding?

**Comment by Hilbrand** [comment]
@babela do you mean the kp200 instead of the hs200?

**Comment by babela** [comment]
Sorry, yes, I meant KP200.  I have updated the original comment.  Separate from OpenHab, I am using tasker specifically to turn switches on/off when phone's charge is at a certain percentage to maximize the useful lifespan of the battery... The comment was to answer the question of turning on/off all sockets at once on the KP200.  This does work via the same methods as the already supported devices.  My OpenHab is currently down so I can not test via OpenHab currently.  I have not figured out or found any info on controlling the KP200 individual sockets.  It certainly is possible. Hoping to find time to do some packet sniffing in the near future.

**Comment by c6fc** [comment]
@Hilbrand I have a Kasa HS300 6-outlet power strip, and I'd be happy to help you test!

**Comment by mythbai** [comment]
I have a HS300 too, and would appreciate the support for it. I can help with the test as well.

**Comment by c6fc** [comment]
Another project seems to have had a lot of luck developing support for the HS300, and it's currently licensed MIT: https://github.com/plasticrake/tplink-smarthome-api/

The API documentation would probably shed a great deal of light on the questions you have about how the device behaves: https://github.com/plasticrake/tplink-smarthome-api/blob/master/API.md

**Comment by Hilbrand** [comment]
@babela, @mythbai  and @c6fc I've create an initial version supporting HS107, HS300, KP200 and KP400. The binding is available through the Eclipse IoT marketplace and can thus be installed from PaperUI when the MarketPlace is enabled in PaperUI -> Configuration -> System with Maturity Level Beta.

Let me know what works and what doesn't. If you are experiencing problems please enable log level TRACE. In karaf console: `log:set TRACE org.openhab.binding.tplinksmarthome`. Make sure to disable it when done, otherwise you'll get lots of logging: `log:set DEBUG org.openhab.binding.tplinksmarthome`

**Comment by Hilbrand** [comment]
I've made some changes. I changed the channels of the power outlet devices to channel groups. So it shows up nicer. If you had the experimental binding installed before this day you need to re-add the new things as the channels have changed.

**Comment by MyRaceData** [comment]
Hilbrand:
Do I need to uninstall the 2.4 version before installing the beta? My gut is telling me yes and because it is probably 4am in the Netherlands I'm going to try that first. Let you know
andy
