### ISSUE TITLE
[samsungtv] Support older models, e.g. H Series

### ISSUE THREAD

**Issue by sebi310781** [openhab/openhab-addons#5081]
Unfortunately, no version of the Samsung TV binding currently supports the models which use the, well let's call it "encypted" communication (probably all models between 2014 and 2016).
I found the following code on github, which also include a small demo applet, which works perfectly for my Samsung UE55H6600. 

https://github.com/tdudek/samsung-remote-models-2014-and-newer

The only issue I see is that you have to enter the “pairing code”, every time you start the applet, so the storing of the pairing code is probably not implemented at the moment.

It'd be great if someone could have a look, if there'd be a way to add this to the new binding. I'd be very happy to support you guys with testing any outcome of this.

**Comment by arjanmels** [comment]
Additional info can be found at: https://github.com/kdschlosser/samsungctl/
I thought about implementing it, but as I have no H or J TV I cannot test this and it is a bit too complicated to develop without being able to test locally.

**Comment by tnemrap** [comment]
@arjanmels If you help me with the coding i can test it on my UE65HU8505.

**Comment by tnemrap** [comment]
https://github.com/kdschlosser/samsungctl/commit/493735ed13a9f6b1541e470b20d81458774c6e4c
This is the commit that added this for samsungctl.

**Comment by arjanmels** [comment]
@tnemrap Yes I saw the code. Unfortunately I am too busy with other stuff to pick this up.

**Comment by hmerk** [comment]
closed due to inactivity
