### ISSUE TITLE
[mqtt] homie/device/$name not recognized in 2.5

### ISSUE THREAD

**Issue by RayBa82** [openhab/openhab-addons#5090]
The autodiscovery for homie things is broken.

Homie things are not recognized by name anymore in 2.5
They appear with device name from the topic instead of the homie/device/$name value.
In 2.4 they appeared with the correct name.

**Comment by J-N-K** [comment]
Please try `bundle:update <number> https://janessa.me/esh/org.openhab.binding.mqtt.homie-5090.jar`. Use the instructions on https://janessa.me/esh for updating (option 2). Thanks.
