### ISSUE TITLE
[mqtt] Homie devices are losing channel information after restart (2.5 and 2.4)

### ISSUE THREAD

**Issue by RayBa82** [openhab/openhab-addons#5091]
After a homie device is auto discovered everything works as expected, the channels have the right unit, the correct format and so on.

But after restarting openhab all channel Information is lost, the unit disappears and for enum values the possible selection values are disappearing too.

this can be configured in items and sitemaps, but this will lead to a lot of unnecessary configuration work and makes the autodiscovery almost superfluous.

This should work even if openhab is restarted.

**Comment by davidgraeff** [comment]
This is fixed in OH 2.5 snapshots afaik. Can you verify?

**Comment by RayBa82** [comment]
I can confirm it is working current snapshot :-D
Thanks a lot for fixing this issue, that was a very annoying bug, since i homified all my custom devices.

Now it is working really great
