### ISSUE TITLE
[cus][api-connection] Add support for transfering sensor based info to CuS-API 

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab-addons#5099]
You can find the community thread to discuss this issue here: https://community.openhab.org/t/cus-binding/69305

**Comment by wborn** [comment]
Can you reopen this when the [initial binding contribution PR](https://github.com/openhab/openhab2-addons/pull/5098) is merged and it is still an issue by then? Maybe you can add a comment to that PR or an issue in your own repo to keep track of it instead?
