### ISSUE TITLE
[mihome] Add support for tradfri bulbs to Mi Home

### ISSUE THREAD

**Issue by OhNoItSJoe** [openhab/openhab-addons#5109]
Since you can use Tradfri Bulbs with the Xiaomi Gateway, it would be great if it would be possible to control those bulbs.

If needed I can gather some information for at least some of the tradfri bulbs.

**Comment by cpoulsen2** [comment]
Would be great to get this feature

**Comment by menaceone** [comment]
That would be an awesome enhancement.

**Comment by hmerk** [comment]
closed due to inactivity
