### ISSUE TITLE
[lgwebos] Toast message on LG OLED55B87LC

### ISSUE THREAD

**Issue by Siflei** [openhab/openhab-addons#5126]
Hi,
I'm trying to show Toast messages on my OLED55B87LC when someone is calling. The rule is run, the connection to the TV works, but no Toast is shown.

14:06:34.808 [INFO ] [smarthome.event.ItemStateChangedEvent] - fboxRinging changed from OFF to ON
14:06:37.939 [INFO ] [.smarthome.model.script.notifications] - Telefon an FB klingelt, fuehre Regel aus.
14:06:38.044 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'SonosWohzimmer_Fernbedienung' received command PAUSE
14:06:38.225 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'LG_TV_Toast' received command Jemand ruft an.
**14:06:38.384 [DEBUG] [inding.lgwebos.handler.LGWebOSHandler] - handleCommand(lgwebos:WebOSTV:13bfc98e-10e5-40e4-8aa9-870663b72249:toast,Jemand ruft an.) is called**
14:06:38.414 [INFO ] [arthome.event.ItemStatePredictedEvent] - SonosWohzimmer_Fernbedienung predicted to become PAUSE
14:06:38.542 [INFO ] [arthome.event.ItemStatePredictedEvent] - LG_TV_Toast predicted to become Jemand ruft an.
14:06:39.778 [INFO ] [smarthome.event.ItemStateChangedEvent] - fboxIncomingCall changed from 08975201240,015771908379 to ,
14:06:39.891 [INFO ] [smarthome.event.ItemStateChangedEvent] - fboxIncomingCallResolved changed from 08975201240,Name not found for 015771908379 to ,
14:06:39.951 [INFO ] [smarthome.event.ItemStateChangedEvent] - fboxRinging changed from ON to OFF

The DEBUG line shows that the toast method is called, but nothing appears. May the reason be the relativly new model (OLED55B87LC) of the TV?

Regards,
Simon

**Comment by lolodomo** [comment]
This feature is working with 2019 OLED generation.

**Comment by lolodomo** [comment]
Please show your rule colde. It should look like that:
```
	val actions = getActions("lgwebos","lgwebos:WebOSTV:tv")
	if (null === actions) {
		logInfo("Rule", "Actions not found")
		return
	}
	actions.showToast("Voici un test")
```
Enable the TRACE logs for the binding and you should then see these logs when your rule is run:
```
13:30:04.751 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [out]: {"type":"request","id":198,"uri":"ssap://system.notifications/createToast","payload":{"message":"Voici un test"}}
13:30:04.778 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":198,"payload":{"returnValue":true,"toastId":"ezfVjvux.2269-1586691003771"}}
13:30:04.790 [DEBUG] [binding.lgwebos.action.LGWebOSActions] - Response: CommandConfirmation [returnValue=true]
```
Please consider this core bug that make actions unusable in case the binding was restarted:
https://github.com/openhab/openhab-core/issues/1265
So please try again and provide TRACE logs.

**Comment by lolodomo** [comment]
I close the issue as it is now very old, not reproduced and we have no feedback.
