### ISSUE TITLE
[javascript] Add support for parameters to JavaScript transformation

### ISSUE THREAD

**Issue by thewilli** [openhab/openhab-addons#5128]
Currently - and due to the signature, the JavaScript transformation [only works on the value and input script](https://github.com/openhab/openhab2-addons/blob/2b7415c/addons/transform/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java#L63).

There are few usecases where scripts are similar but not identical. If there was a way to add parameters to them, we could prevent redundancy and maintain a single script file where few were needed otherwise. One example might be upper and lower bounds of an otherwise identical transformation.

In order to not break compatibility, I'd propose to support [query string](https://en.wikipedia.org/wiki/Query_string)-like parameters as optional suffix to the script's file name. 

Those values would for the sake of simplicity be always strings, but could be easily converted in the JS source of course. (In theory) it should not be more than parsing the query string, removing it from the filename and adding the values as additional [bindings](https://github.com/openhab/openhab2-addons/blob/2b7415c/addons/transform/org.openhab.transform.javascript/src/main/java/org/openhab/transform/javascript/internal/JavaScriptTransformationService.java#L76).

## Example usage:

```plain
transform("JS", "my-script.js?a=foo&b=bar", value)

Number  Kitchen_Temperature    "Temperature [JS(temp.js?unit=F):%.1f °F]" {/* ... */}
```

**Comment by davidgraeff** [comment]
Sounds like a good idea.

**Comment by wborn** [comment]
We've been using the "enhancement" label in issues and PRs for this "Feature Request" label @davidgraeff. Similarly to how "bug" is used in issues and PRs.

**Comment by davidgraeff** [comment]
@wborn I tried to write some descriptions for the labels, so that it is more obvious when to use a label. I thought that "enhancement" is only used for PRs that "enhance" an extension.

**Comment by wborn** [comment]
Yes the the descriptions will certainly help! The "enchancement" label is actually a default GitHub label so you can find it in many projects. See the list of [default GitHub labels](https://help.github.com/en/articles/about-labels#using-default-labels).

**Comment by davidgraeff** [comment]
@thewilli Could you try to propose a PR to implement your idea?

**Comment by thewilli** [comment]
@davidgraeff sure, though it depends if you expected me to create the ([yet missing](https://github.com/openhab/openhab2-addons/tree/4489516/addons/transform)) unit tests for the JS transformation in order to extend them for the change :wink:

**Comment by davidgraeff** [comment]
If you are under 100 lines of code changes and comment well I guess I can live without unit tests.
Just make sure that you explain the feature in the readme file.

**Comment by thewilli** [comment]
sounds good, thanks.

I just did some basic structuring. 

@davidgraeff as for the change itself, would you agree that for the sake of simplicity and (runtime) efficiency

* we can assume that if a `?` is part of the filename, it is always considered a query string indicator. 
   * this would prevent any scripts with a `?` in their filename from being called
   * multiple occurencences would be considered an error
   * we would require a long and ugly regex otherwise
* we don't do an extensive validation of the query string
  * if it can somehow be parsed, it will be used
  * if it is malformed some unexpected values could be used (`file.js?name=alice&bob`)

**Comment by davidgraeff** [comment]
> we can assume that if a ? is part of the filename, it is always considered a query string indicator.

Question marks are not allowed in url query strings and I guess we want to adhere to that standard. What you therefore can do is split the string at the last question mark and consider the last part as query. This way filenames with question marks are still fine.

**Comment by thewilli** [comment]
> Question marks are not allowed in url query strings 

sure, I was referring to how to detect the query string, and how the separation happens.

> [...] split the string at the last question mark and consider the last part as query
> This way filenames with question marks are still fine.

not necessarily, what about `my?file`

**Comment by davidgraeff** [comment]
Because the transformation is re-evaluated every time, I'd say we don't do a proper validation. The thrown exception should be enough hint to a user that his filenames are suboptimal.

I'm currently blocking the bundle to be migrated to the new buildsystem until you have proposed your PR.

#5229
