### ISSUE TITLE
[unifi] Could not generate DH keypair

### ISSUE THREAD

**Issue by dR3b** [openhab/openhab-addons#5139]
## Expected Behavior

Connect openHAB with Unifi Controller.

## Current Behavior

```
2019-03-18 09:18:35.282 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'unifi.things'
2019-03-18 09:18:35.935 [ERROR] [.handler.UniFiControllerThingHandler] - Unknown error while configuring the UniFi Controller
org.openhab.binding.unifi.internal.api.UniFiException: java.lang.RuntimeException: Could not generate DH keypair
```

```
Bridge unifi:controller:home "UniFi Controller" [ host="<HOST>", port=8443, username="<USER>", password="<PASS>", refresh=10 ] {
  Thing wirelessClient BLA "BLA's ..." [ cid="<MAC>", site="default", considerHome=180 ]
}
```

## Steps to Reproduce (for Bugs)
1. Install openHAB (manual installation, Zip file) and start the it.
2. Add the Unifi controller

## Your Environment
* Version used: 2.4.0 stable
* Environment name and version: OpenJDK Runtime Environment (build 1.8.0_192-b26)
* Operating System and version: FreeBSD 12.0-RELEASE-p3

**Comment by davidgraeff** [comment]
The error message should be more comprehensive. It is probably because you haven't installed the "extended java security" thingy (I can't recall the name rn). Because of stupid old US restricted export laws, those are usually not part of a java jdk and need to be installed separately.

**Comment by dR3b** [comment]
@davidgraeff 
Do you mean this one?
https://github.com/open-eid/cdoc4j/wiki/Enabling-Unlimited-Strength-Jurisdiction-Policy

OpenJDK
Should be enabled by default. 

^^ And yes its enabled.

**Comment by hmerk** [comment]
closed due to inactivity
