### ISSUE TITLE
[tado] Server rejects change requests

### ISSUE THREAD

**Issue by stefaanv** [openhab/openhab-addons#5141]
I have a problem to change settings in my tado system from openHAB2.  When I change a tado item, it reverts back to the previous value after some time in openHAB, while the change is not noticed by my tado system.
I've tried making changes through scripts first, then tried the Karaf CL interface and notices the same problem.  There's some examples below.  What am I doing wrong ?

The measurement values from the tado system are being updated in openhab nicely, so that direction works fine.  I’ve install the 2.5.0 version of the tado binding in openhab2.

Here's part of my things file:
```
Bridge tado:home:AnneFrank6 [ username="******", password="******" ]{
zone badkamer [id=1]
zone bureau [id=2]
zone living [id=4]
}
```
Here's some of my item definitions
```
Number badkamer_tado_temp_raw “Temperatuur [%.1f °C]” <temperature> (gTemperatuur) { channel=“tado:zone:AnneFrank6:badkamer:currentTemperature” }
Number badkamer_tado_vocht “Vochtigheid [%d %%Rh]” { channel=“tado:zone:AnneFrank6:badkamer:humidity” }
Number badkamer_tado_power (gTemperatuur) { channel=“tado:zone:AnneFrank6:badkamer:heatingPower” }
Number badkamer_tado_target_raw (gTemperatuur) { channel=“tado:zone:AnneFrank6:badkamer:targetTemperature” }
String badkamer_tado_opmode { channel=“tado:zone:AnneFrank6:badkamer:operationMode” }
Number badkamer_tado_timerDuration { channel=“tado:zone:AnneFrank6:badkamer:timerDuration”}
```

Here's two examples of how things go wrong from the Karaf interface
```
openhab> smarthome:update badkamer_tado_opmode “MANUAL”
Update has been sent successfully.
openhab> smarthome:status badkamer_tado_opmode
SCHEDULE
openhab> smarthome:update badkamer_tado_opmode “MANUAL”
Update has been sent successfully.
openhab> smarthome:status badkamer_tado_opmode
MANUAL
openhab> smarthome:status badkamer_tado_opmode
SCHEDULE
```

```
openhab> smarthome:update badkamer_tado_target_raw 23.0
Update has been sent successfully.
openhab> smarthome:status badkamer_tado_target_raw
23.0
...
openhab> smarthome:status badkamer_tado_target_raw
23.0
openhab> smarthome:status badkamer_tado_target_raw
21.0
```

**Comment by tavalin** [comment]
Maybe I've missed something but don't you need to send the value as a command rather than post an update?

**Comment by stefaanv** [comment]
That seems to be the solution, thanks.
One more question, do you expect a QuantityType to be sent as target temperature in a script ?  So far, nothing else seems to work in my script, but I'm in trouble converting ordinary numbers into temperature QuantityTypes and back.  Any chance you could add a script example to the documentation where you set a zone overlay where the target temperature is a calculated value ?  That would help me a lot (and possibly others as well).

**Comment by hmerk** [comment]
closed due to inactivity
