### ISSUE TITLE
[deconz] Support for Resource Type : ZHAVibration

### ISSUE THREAD

**Issue by ncister** [openhab/openhab-addons#5191]
As stated in the topic the Resource Type ZHAVibration is not yet supported

## Your Environment
Using Openhab Stable 2.4.0
Openhabian on Raspi 3B+

Here is a complete Rest API printout of the 3rd Channel ZHAVibration
```
{
  "config": {
    "battery": 100,
    "on": true,
    "pending": [],
    "reachable": true,
    "sensitivity": 11,
    "sensitivitymax": 21,
    "temperature": 2400
  },
  "ep": 1,
  "etag": "xxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "manufacturername": "LUMI",
  "modelid": "lumi.vibration.aq1",
  "name": "Vibration 3",
  "state": {
    "lastupdated": "2019-03-21T22:53:34",
    "orientation": [
      0,
      0,
      90
    ],
    "tiltangle": 30,
    "vibration": false,
    "vibrationstrength": 147
  },
  "swversion": "20180130",
  "type": "ZHAVibration",
  "uniqueid": "xx:xx:xx:xx:02:e9:f7:xx-01-0500"
}
```

Hardware Model : Xiaomi DJT11LM Smart Home Aqara Vibration Sensor - White
https://it.gearbest.com/smart-home-controls/pp_009661787808.html?wid=1433363

**Comment by cweitkamp** [comment]
I added basic support for ZHAVibration sensors in #5225. The rest of the state values mentioned in your example are not yet documented in deCONZ [Supported Devices](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#measured-values-legend) and there have been recent changes in https://github.com/dresden-elektronik/deconz-rest-plugin/issues/748 thus I am not sure what is the state of the art for them. We can easily amend them later.
