### ISSUE TITLE
[groheondus] Allow to login using a refreshToken

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab-addons#5209]
With this pull request: 
https://github.com/FlorianSW/grohe-ondus-api-java/issues/3
The ondus-api library allows one to login using a refreshToken, instead of username and password. This should be possible in the respective grohe ondus binding, too, to get rid of a hardcoded username/password in configuration files and to maintain compatibility with newer versions of the API.

**Comment by standardgbg** [comment]
Until a solution can be implemented in the OH addon, is there a way to use only the log-on script in OH, to get the binding to work?

**Comment by FlorianSW** [comment]
> Until a solution can be implemented in the OH addon, is there a way to use a separate login script in OH, with the username/password hardcoded, to get the binding to work?

I don't see any, sorry. Also sorry that I didn't responded earlier here :( Some background to that:
OpenHAB changed the way of how bindings are build, which significantly broke my IDE setup, and until now I dind't have enough time to start from scratch and get the binding running on my local machine. This, however, made it impossible for me to integrate changes to PRs I already started. This will hopefully change in the near future, so that we can get this binding working again! :)
