### ISSUE TITLE
[Infrastructure] Auto generate the maven BOM

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#5214]
During the porting of a bundle you probably have noticed that you need to touch a few locations.

This Issue is about the maven BOM (https://github.com/openhab/openhab2-addons/blob/master/bom/openhab-addons/pom.xml) that we keep in this repository. It is used by the openhab-distro and openhab-demo-app repository to identify all available addons.

My question is: Can we use `bom-builder-maven-plugin` (in the maven reactor) to generate that bom?

### Background

I plan to update the current .travis.yml file in a way that it can identify when only one directory is touched (a new binding PR, or a fix for one binding) and only build that specific directory. With the maven cache we have in place we might have travis feedback in about 3 minutes including tests instead of 30 without tests as of now.

**Comment by davidgraeff** [comment]
@openhab/2-x-add-ons-maintainers

**Comment by wborn** [comment]
> only build that specific directory

But that would render the feature validation useless? I find that very useful. Especially if JARs are added/modified in the lib dir it could fail feature validation if bnd updates package imports.

**Comment by davidgraeff** [comment]
> But that would render the feature validation useless?

I'm aware of karaf and that is what I want to tackle after the bom.

The idea is to have a features.xml file per binding directory and they are merged as a final maven reactor step or to use 
https://svn.apache.org/repos/asf/karaf/site/production/manual/latest/karaf-maven-plugin.html
and generate the features file based on the maven dependencies.
