### ISSUE TITLE
[Infrastructure] Karaf features file per addon

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#5222]
During the porting of a bundle you probably have noticed that you need to touch a few locations.

This Issue is about the karaf feature file (https://github.com/openhab/openhab2-addons/blob/master/features/karaf/openhab-addons/src/main/feature/feature.xml) that we keep in this repository. It is used by the openhab-distro to make all bindings available as karaf features.

I propose to  
* either add a karaf feature.xml file per addon directory
* or generate the karaf feature.xml file

and merge those in the maven install phase within the reactor into one file.

### Advantages and goals

* The binding skeleton can contain that file and it cannot be forgotten by new binding PRs
* An addon directory is more self-contained
* During the CI build, the feature verification happens per directory and not as one big blob at the end

### Ideas and experiments for feature.xml auto generation

If we just have a separate "feature.xml" file per directory, there is not much to think about. That's different if we decide to auto-generate that based on the pom file.

I did some experiments with the `org.apache.karaf.tooling:karaf-maven-plugin`. I have added the following to the astro binding pom.xml:

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.karaf.tooling</groupId>
        <artifactId>karaf-maven-plugin</artifactId>
        <version>4.2.4</version>
        <extensions>true</extensions>
        <configuration>
          <enableGeneration>true</enableGeneration>
          <startLevel>80</startLevel>
          <inputFile>../../features/karaf/template_feature.xml</inputFile>
        </configuration>
        <executions>
          <execution>
            <id>generate-features-file</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>features-generate-descriptor</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

That instructs maven to generate the karaf feature file, based on a template in "/features/karaf/template_feature.xml":

```xml
<features name="${project.artifactId}-${project.version}">
  <repository>mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-core/${project.version}/xml/features</repository>
  <feature name="${project.artifactId}" description="${project.name}" version="${project.version}">
      <feature>openhab-runtime-base</feature>
      <bundle start-level="80">mvn:${project.groupId}/${project.artifactId}/${project.version}</bundle>
  </feature>
</features>
```

which results in a generated file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<features xmlns="http://karaf.apache.org/xmlns/features/v1.5.0" name="org.openhab.binding.astro-2.5.0-SNAPSHOT">
    <repository>mvn:org.openhab.core.features.karaf/org.openhab.core.features.karaf.openhab-core/2.5.0-SNAPSHOT/xml/features</repository>
    <feature name="org.openhab.binding.astro" description="openHAB Add-ons :: Bundles :: Astro Binding" version="2.5.0.SNAPSHOT">
        <details>This project contains the add-ons of openHAB</details>
        <feature>openhab-runtime-base</feature>
        <bundle start-level="80">mvn:org.openhab.addons.bundles/org.openhab.binding.astro/2.5.0-SNAPSHOT</bundle>
    </feature>
</features>
```

I would say we use the pom.xml `<description>` for the descriptive name of the binding, which is then reflected into the feature description parameter (at the moment it is coming from the pom.xml `<name>`).

Maven dependencies are automatically added.
* I'm not sure how to instruct the binding to use "wrap:mvn" though for non OSGi compatible dependencies.

The feature name, if auto-generated, will change to the package name though.
* Mavens architecture doesn't allow me to perform a name computation here.

### Suggestions and experiments for merging multiple feature files into one

I have not yet looked into that, but maybe someone has an idea. In the end it just boils down to xml processing, but maybe a 
```xml
combine.children="append"
```
configuration can do that already for us.

Personal note: https://github.com/apache/karaf/blob/master/tooling/karaf-maven-plugin/src/main/java/org/apache/karaf/tooling/features/GenerateDescriptorMojo.java#L154 (aggregateFeatures) seem to be what I want for feature merging.

**Comment by J-N-K** [comment]
If you use generation, is it automatically determining the dependencies? If so, will this conflict with our pre-defines features (e.g. mdns)? If not, how can we add those?

In general I agree that a feature.xml per binding that is merged is a lot better than the centralized we have now.

**Comment by davidgraeff** [comment]
> If not, how can we add those?

I have investigated a bit. People seem to have a template feature file for each subproject of a maven multi-project and in there you can have defined all the feature dependencies. The Karaf maven plugin is unfortunately missing waht is proposed here: https://issues.apache.org/jira/browse/KARAF-5512.

That would allow to define feature dependencies in your pom:

```xml
          <features> 
            <feature>openhab-runtime-base</feature> 
          </features> 
```

Because that is not implemented, auto-generation is not really feasible for us, I'm afraid. We would rather go with a user-defined feature.xml file per directory.

**Comment by J-N-K** [comment]
I had a look how to combine those per-binding-feature files into a global addons-features file and it seems that the maven-antrun-plugin might do the trick. I can try that if you don't mind.

**Comment by maggu2810** [comment]
* Compile time dependencies and runtime dependencies differ
* I am pretty sure also the Karaf team member will tell you that the automatic feature generation should just be used for a first template and feature files should be maintained manually

**Comment by davidgraeff** [comment]
We can define "runtime" scope dependencies, that was my idea. The PR solves it with static files.
