### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#5239]
It is not possible for me to execute the integration tests on current master.

Steps to reproduce:
* Go into the `itests` directory.
* Execute `mvn clean install -DwithResolver`

Output:
```
[INFO] --- bnd-resolver-maven-plugin:4.2.0:resolve (default) @ org.openhab.binding.astro.tests ---
[ERROR] Resolution failed. Capabilities satisfying the following requirements could not be found:
    [<<INITIAL>>]
      ⇒ osgi.identity: (osgi.identity=org.openhab.binding.astro.tests)
          ⇒ [org.openhab.binding.astro.tests version=2.5.0.201903250957]
              ⇒ osgi.wiring.package: (&(osgi.wiring.package=javax.measure)(&(version>=1.0.0)(!(version>=2.0.0))))
    [org.openhab.binding.astro version=2.5.0.201903241417]
      ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.eclipse.smarthome.config.core))

[INFO] Reactor Summary:
[INFO] 
[INFO] openHAB Add-ons :: Integration Tests ............... SUCCESS [ 34.103 s]
[INFO] openHAB Add-ons :: Integration Tests :: Astro Binding Tests FAILURE [  5.670 s]

[ERROR] Failed to execute goal biz.aQute.bnd:bnd-resolver-maven-plugin:4.2.0:resolve (default) on project org.openhab.binding.astro.tests: Unable to resolve <<INITIAL>>: missing requirement osgi.identity;filter:='(osgi.identity=org.openhab.binding.astro.tests)' [caused by: Unable to resolve org.openhab.binding.astro.tests version=2.5.0.201903250957: missing requirement osgi.wiring.package;filter:='(&(osgi.wiring.package=javax.measure)(&(version>=1.0.0)(!(version>=2.0.0))))'] -> [Help 1]
```

**Comment by J-N-K** [comment]
Did you use the patched core according to this comment https://github.com/openhab/openhab2-addons/pull/5050#issuecomment-470459971?

**Comment by davidgraeff** [comment]
@J-N-K Markus wrote "For Maven + Bnd on openhab2-addons it is already enabled."
So it should work, shouldn't it? I'm not using a patched core for "openhab2-addons", no

**Comment by J-N-K** [comment]
From my understanding this is enabled for opnhab2-addons but you need a patched core to resolve. I only tried once nd it didn't work without the patched core. If you build the core on the same machine it is automatically picked up by the build unless the remote build is newer than your local build.

**Comment by davidgraeff** [comment]
Hm. I'd say we finish off the migration and at the end we fix the failing migration tests :D 
I'm doing core development on my machine and my maven cache is polluted with different core binding versions. I don't want to build another core and rebuild it everytime I'm doing something with addons.
