### ISSUE TITLE
[netatmo] Live picture and live stream URLs update

### ISSUE THREAD

**Issue by jlchevet** [openhab/openhab-addons#5250]
## Expected Behavior

The Netatmo documentation says : “The vpn_url expire after 3 hours and if the camera reboots” (cf https://dev.netatmo.com/resources/technical/reference/security/live 

The Netatmo binding should update the Live Stream URL and Live Picture URL as soon as the vpn_url changes, since these URLs are built using the vpn_url.

## Current Behavior

I noticed that the netatmo binding does not update the Live Picture URL nor the Live Stream URL. After a while these URLs are not valid anymore and I need to stop and restart the netatmo binding to get new valid URLs.

## Possible Solution

I think that the problem is in the NAWelcomeCameraHander.java which does not take into account changes of vpn_url of the cameras.

1 - The getVpnUrl() method should always return the value obtained by calling module.getVpnUrl() since this value may change every 3 hours. It does not do so if the vpnUrl attribute has already been set by the first call to getVpnUrl().

2 - The getLivePictureURL() method should always rebuild the live picture URL by calling getVpnUrl(). It does not do so if the livePictureURL attribute has already been set by the first call to getLivePictureURL()

3 - getLiveStreamURL() method should always rebuild the live stream URL by calling getVpnUrl(). It does not do so if the liveStreamURL attribute has already been set by the first call to getLiveStreamURL().

## Your Environment

The bug can be reproduced wth the last version of openhab (2.5 on windows 10)

**Comment by davidgraeff** [comment]
Can you maybe provide a PR that fixes this behavior?

**Comment by clinique** [comment]
I'll do after migration to bnd PR merged

**Comment by lolodomo** [comment]
@clinique : do you plan to provide a fix ? If not, I can try.
