### ISSUE TITLE
[nanoleaf] Adding individual light panels

### ISSUE THREAD

**Issue by stevegroom** [openhab/openhab-addons#5261]
Just updated to latest ( 2.5.0-SNAPSHOT Build #1561 )

Removed the manually added Nanoleaf.jar and then added the new Nanoleaf Binding. 

After restarting the inbox had 18 new items called Light Panel. 

I clicked on the first one, activated the channel with a new binding. 
I clicked on the second one, activated the channel with a new binding.

Then I went to the Paper UI and selected the room with the two Light Panels. 
The panels are both working but are linked together - both controls adjust at the same time and apply the same settings to both panels. 

I deleted the channel binding on each and recreated - still the same result.  

Finally changing the Thing names to be unique successfully separated the controls. 

I think that the auto adding of the things to the inbox should have unique names to avoid this. 

## Your Environment
Latest 2.5.0-SNAPSHOT Build #1561
Raspbian on Pi 3B+

Steve.

**Comment by kaikreuzer** [comment]
This works on openHAB 3 - all discovered panels have individual thing UIDs, so there's no issue.
