### ISSUE TITLE
[homekit] networkInterface needs to be defined

### ISSUE THREAD

**Issue by apica-alfred** [openhab/openhab-addons#5269]
## Expected Behavior
If networkInterface is not defined, the addon should get it's own IP.

## Current Behavior
My current setup (just one light) only works if I define the networkInterface, but there is no reason (basic Openhabian image used) to not to work when networkInterface is not set.

## Possible Solution
It seems related in how InetAddress.getLocalHost() function works in the HomekitSettings.java. I don't know what should be changed, event not sure how to test/debug it (I don't know how to add log messages in the code and recompile it).

## Steps to Reproduce (for Bugs)

1. Openhabian default image.
2. Do not set the org.openhab.homekit:networkInterface configuration parameter.

## Context
It's a mess that the IP of the own device should be provided, adn this goes against DHCP typical configurations.

## Your Environment

* Version used: openhab 2.4.0 stable and addon 2.4.0 stable (I didn't found any newest commit that seems to solve it).
* Operating System and version: Raspbian Stretch.

**Comment by J-N-K** [comment]
I'm not sure I understand what the problem is. If the network interface is not set, the ip address of the local hostname is resolved. Is that not working for you?

**Comment by apica-alfred** [comment]
If I set the own IP, it works well. If it its not set at all, it appears as a device, but the commands are not reached. The shown IP is "localhost", so I guess the external devices don't know how to handle it.

**Comment by J-N-K** [comment]
Can you please show what the output of `hostname` (SSH shell) is?

**Comment by apica-alfred** [comment]
Executing `hostname` throws correctly `openHABianPi`. Did you test in a clean installation?

**Comment by J-N-K** [comment]
Ok. I think I can reproduce the problem on another system. Will try to make it more robust.
