### ISSUE TITLE
[vallox][feature] download time series of measurements potentially stored on the unit

### ISSUE THREAD

**Issue by gunarka** [openhab/openhab-addons#5276]
I made the same feature request in a related project (vallox websocket api by yozik04): https://github.com/yozik04/vallox_websocket_api

Hi, the openHAB binding was working out of the box for me (ValloPlus 270 MV) via paperUI!

Via the Vallox webinterface time series of hourly sensor data (tempertures, humudity, CO2) can be plotted (appart from current values). Therefore I assume that the unit stores these series information.

From my perspective it would be great to be able to retrieve (and plot) these information with this binding as well.

What do you think?

**Comment by d4n7e1** [comment]
Why didn't you simply use the persistence of OpenHab? This would be the easiest way. So I think, there is no need for this feature....

**Comment by gunarka** [comment]
Sure, if you have a (mini) PC running anyway you could repeatingly check actual measurements with openHAB and store those as time series.
But if you don't, then downloading these measurements (with 10 minutes time steps) once every two month (period stored on ValloPlus 270 MV) sounds more convinient to me.

**Comment by bjoernbrings** [comment]
Honestly I'd agree with @d4n7e1. OpenHab is designed to be running continously. So I don't see any reason for not using persistence.
Furthermore there is hardly the functionality in the binding API to provide historic values without misusing any variable for dumping the whole history in it.
A set of hundreds of channels (one per existing channel per time point provided) to solve this doesn't sound reasonable as well.

**Comment by hmerk** [comment]
closed due to inactivity
