### ISSUE TITLE
[avmfritz] Bridge ONLINE Things remain in STATE UNKNOWN after  build #1558

### ISSUE THREAD

**Issue by Kroki0815** [openhab/openhab-addons#5341]
In snapshot-version 1562/1563 the devices  of the avmfritz binding dosn't came online any more. Only the Bridge itself is up and running:

>2.5.0-SNAPSHOT Build 1563 
>avmfritz:fritzbox:1 (Type=Bridge, Status=ONLINE: Established FRITZ!Box connection with SID 89d65d77ef5239ad, Label=FRITZ!Box, Bridge=null)
>avmfritz:FRITZ_DECT_200:1:087610115212 (Type=Thing, Status=UNKNOWN, Label=Weihnachtsbaum, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_Repeater_100:1:087610886162 (Type=Thing, Status=UNKNOWN, Label=Repeater, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610187682 (Type=Thing, Status=UNKNOWN, Label=WeihnachtenWZ, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610187677 (Type=Thing, Status=UNKNOWN, Label=Sideboard, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610115206 (Type=Thing, Status=UNKNOWN, Label=Terrarium, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610115200 (Type=Thing, Status=UNKNOWN, Label=WeihnachtenFlurOG, Bridge=avmfritz:fritzbox:1)

With older version all is fine:

>2.5.0-SNAPSHOT Build 1558
>avmfritz:fritzbox:1 (Type=Bridge, Status=ONLINE, Label=FRITZ!Box, Bridge=null)
>avmfritz:FRITZ_DECT_200:1:087610115212 (Type=Thing, Status=ONLINE, Label=Weihnachtsbaum, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_Repeater_100:1:087610886162 (Type=Thing, Status=ONLINE, Label=Repeater, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610187682 (Type=Thing, Status=ONLINE, Label=WeihnachtenWZ, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610187677 (Type=Thing, Status=ONLINE, Label=Sideboard, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610115206 (Type=Thing, Status=ONLINE, Label=Terrarium, Bridge=avmfritz:fritzbox:1)
>avmfritz:FRITZ_DECT_200:1:087610115200 (Type=Thing, Status=ONLINE, Label=WeihnachtenFlurOG, Bridge=avmfritz:fritzbox:1)

I have a Frtiz!Box 7590 with version  07.08-67227 BETA.

I attached a trace from version 1563.

[debug_avmfritz.txt](https://github.com/openhab/openhab2-addons/files/3026343/debug_avmfritz.txt)

It look like the communication with the Fritz!Box is ok,

I didn't use the paperport-gui, all things are configured manualy:

```
Bridge avmfritz:fritzbox:1 [ ipAddress="192.168.50.1", password ="XXXXXXX", user="openhab", pollingInterval=15,asyncTimeout=10000,syncTimeout=2000] {

    Thing FRITZ_DECT_200 087610187677    "Sideboard"@"Wohnzimmer"    [ ain="087610187677" ]
    Thing FRITZ_DECT_200 087610115212    "Weihnachtsbaum"@"Wohnzimmer"    [ ain="087610115212" ]

    Thing FRITZ_DECT_200 087610001264    "Weihnachtkranz"@"Wohnzimmer"    [ ain="087610001264" ]
    Thing FRITZ_DECT_200 087610115200     "WeihnachtenFlurOG"@"Flur"    [ ain="087610115200" ]
    Thing FRITZ_DECT_200 087610187682     "WeihnachtenWZ"@"Wohnzimmer"    [ ain="087610187682" ]

    Thing FRITZ_DECT_200 087610001076    "UVC"@"Teich"    [ ain="087610001076" ]
    Thing FRITZ_DECT_200 087610115206    "Terrarium"@"Terrarium"    [ ain="087610115206" ]    

    Thing FRITZ_DECT_200 087610185224    "Hauswasserwerk"@"Gartenhaus"    [ ain="087610185224" ]    

    Thing FRITZ_DECT_Repeater_100 087610886162    "Repeater"@"Wohnzimmer"    [ ain="087610886162" ]

}
```

## Your Environment
Openhab is running on Debian-Buster with oracle-java8- 8u201-1

**Comment by cweitkamp** [comment]
Confirmed. Do you see any updates on your Channels? I cannot. Controlling outlets does not work either.

Related to #5217.

**Comment by Kroki0815** [comment]
Yes, that's wright. Channels can't be controlled and states are not updated.
