### ISSUE TITLE
Shrink repository (OH3)

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#5371]
The current repository size is 346.70 MiB downloadable data and 443 MB after checkout on disk (03.05.2019).

The actual workspace data is 87MB (including the remaining .jar files) and 79MB excluding any jar files.

I suggest to rewrite the git history and remove all binary data (or to archive this repo for OH3 and start fresh).

We can't perform a git bisect for bug hunting etc, because the entire directory structure has changed and the pde based build in old commits will not work anymore, so there is no reason to keep the history.

Consequences:
* Easier binding development because the checkout takes 1/4 of the time.
* All current open PRs and cloned repositories need to be forcefully rebased (file movement tracking will be broken)

Because we decided to go with one repo for all bindings, those clean ups are inevitable after huge changes to keep the ecosystem healthy. WDYT?

**Comment by kaikreuzer** [comment]
Makes sense to me, especially as the history won't be of much help due to the migration.
We could keep a copy of the current repo as a backup and rewrite the history of this repo once the migration is done.

**Comment by kaikreuzer** [comment]
Done:
```
➜  git clone https://github.com/openhab/openhab-addons
Cloning into 'openhab-addons'...
remote: Enumerating objects: 10296, done.
remote: Counting objects: 100% (10296/10296), done.
remote: Compressing objects: 100% (7161/7161), done.
remote: Total 18940 (delta 5548), reused 3185 (delta 3135), pack-reused 8644
Receiving objects: 100% (18940/18940), 20.54 MiB | 15.63 MiB/s, done.
Resolving deltas: 100% (6622/6622), done.
```

History is kept in the archived repo https://github.com/openhab/openhab2-addons/.
