### ISSUE TITLE
Unable to override default icon/missing base icon files

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab-addons#538]
I am trying to change the icon used for Switch items to the light icon but getting a 404 instead.

I think I have found a problem with trying to override a default icon. See here for more details: https://community.openhab.org/t/various-icon-woes/4895

Using Switch as an example, if I try to specify an icon for the individual item in the .items file, such as `<light>`, I will get the 404. If I remove the icon element from the item completely, I will get the default switch icon. I have verified this with the IDE and the demo conf files as well. 

 It looks like `<light>` is actually a special case. The base image for light.svg does not exist, only -ON and -OFF. If I use `<heating>` as the icon, it works as expected. I would have though that after toggling the switch with the light icon set that once the state was known, it would have selected the ON or OFF icon, but does not seem to be the case.

**Comment by kaikreuzer** [comment]
Sorry for taking so long and thanks for your analysis. The problem was indeed that no "fallback" icons were available - the existence of this file defines whether or not the iconset includes this icon. I have added all missing files, so that should be fixed now!
