### ISSUE TITLE
[paper] Dynamically created Trigger Channels have ChannelKind==STATE

### ISSUE THREAD

**Issue by 5iver** [openhab/openhab-addons#5410]
When parsing and validating triggers in the Jython helper libraries, I'm checking that Channels used in a ChannelEventTrigger have a ChannelKind of TRIGGER. A user reported an issue using this type of rule trigger with an MQTT Broker publish trigger Channel. In testing, I found that these actually have a ChannelKind of STATE.

The triggers are occuring, so maybe I'm incorrect in expecting them to have a ChannelKind of TRIGGER? Or there could be something wrong in how these Channels are configured.

Discussion/details in the forum... https://community.openhab.org/t/jsr223-jython-simplified-rule-definition-similar-to-rules-dsl-and-universal-decorator/53252/153?u=5iver.

**Comment by davidgraeff** [comment]
The generic mqtt channels are using a statically defined channel type.

If people are using those channels as trigger channels (despite that we have a real trigger channel on the broker thing) this problem occurs.

Looks like I need to use a channel type provider there as well.

**Comment by openhab-5iver** [comment]
It is the broker Thing Channels that are used here. I did not test the Channels from the other Things, and would expect there would not be a Triggered event for them.

**Comment by davidgraeff** [comment]
Hm. That would be strange if you are right, because:

https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt/src/main/resources/ESH-INF/thing/thing-types.xml#L178

```xml
	<channel-type id="publishTrigger">
		<kind>trigger</kind>
		<label>Publish trigger</label>
		<description>This channel is triggered when a value is published to the configured MQTT topic on this broker connection. The event payload will be the received MQTT topic value.</description>
		<event></event>
```

**Comment by martinvw** [comment]
@openhab-5iver where you able to confirm what @davidgraeff said?

**Comment by openhab-5iver** [comment]
@martinvw I'm not sure what you are thinking I was to confirm. I just tested using S1624 and this bug still exists...
```
from core.log import logging, LOG_PREFIX
#log = logging.getLogger(LOG_PREFIX + ".TEST")
from org.eclipse.smarthome.core.thing import ChannelUID
from org.eclipse.smarthome.core.thing.type import ChannelKind
log.warn("[{}]".format(things.getChannel(ChannelUID("mqtt:broker:mosquitto:Test")).kind))
```
logs...
```
2019-06-29 07:20:55.783 [WARN ] [jsr223.jython.TEST] - [STATE]
```
![image](https://user-images.githubusercontent.com/21967853/60383461-faed0d00-9a3e-11e9-8f22-ebc82a1f1ae2.png)

**Comment by davidgraeff** [comment]
I guess that's a core issue for dynamically added Channels. The binding correctly specifies the type.

**Comment by openhab-5iver** [comment]
@davidgraeff, do you know of another binding that uses dynamically added Channels? If so, I'll test to see if I can reproduce this with that binding and move this issue over to core.

**Comment by J-N-K** [comment]
OneWire

**Comment by cweitkamp** [comment]
I have the slight feeling that we are facing a Paper UI issue. The kind is not part of the request. Thus the channel is created with default kind which is `STATE`. @openhab-5iver can you track down the request from Paper UI towards the Rest API and maybe simulate an additional modified request?

(see https://github.com/openhab/openhab-webui/blob/eadf6e6e4e4be91cdba926f6f45cf73c64529a04/bundles/org.openhab.ui.paper/web-src/js/things/controller.things.view.js#L524-534).

**Comment by openhab-5iver** [comment]
Confirmed issue with dynamic Channels (I'll take a look at REST)...

from core.log import logging, LOG_PREFIX
log = logging.getLogger(LOG_PREFIX + ".TEST")
from org.eclipse.smarthome.core.thing import ChannelUID
log.warn("mqtt [{}]".format(things.getChannel(ChannelUID("mqtt:broker:mosquitto:Test")).kind))
log.warn("onewire [{}]".format(things.getChannel(ChannelUID("onewire:owserver:1df5a011:test")).kind))
log.warn("astro [{}]".format(things.getChannel(ChannelUID("astro:sun:local:rise#event")).kind))
```
2019-06-30 15:37:52.826 [WARN ] [jsr223.jython.TEST] - mqtt [STATE]
2019-06-30 15:37:52.827 [WARN ] [jsr223.jython.TEST] - onewire [STATE]
2019-06-30 15:37:52.827 [WARN ] [jsr223.jython.TEST] - astro [TRIGGER]

```

**Comment by openhab-5iver** [comment]
When creating a new Channel in Paper UI, the request payload includes kind STATE...
```
{"statusInfo":{"status":"OFFLINE","statusDetail":"COMMUNICATION_ERROR"},"editable":true,"label":"OW Server","configuration":{"port":4304,"network-address":"localhost"},"properties":{},"UID":"onewire:owserver:1df5a011","thingTypeUID":"onewire:owserver","channels":[{"linkedItems":[],"uid":"onewire:owserver:1df5a011:test","id":"test","channelTypeUID":"onewire:owfs-string","itemType":"String","kind":"STATE","label":"Test","defaultTags":[],"properties":{},"configuration":{"path":"statistics/errors/CRC8_errors"},"showItems":false,"items":null,"channelType":{"parameters":[{"description":"full path to the OWFS-node (e.g. statistics/errors/CRC8_errors)","label":"OWFS Path","name":"path","required":true,"type":"TEXT","readOnly":false,"multiple":false,"advanced":false,"verify":false,"limitToOptions":true,"options":[],"filterCriteria":[],"locale":null,"filterText":"","inputType":"text","element":"input"},{"defaultValue":300,"description":"Time in seconds after which the channel is refreshed","label":"Refresh Time","name":"refresh","required":false,"type":"INTEGER","min":1,"readOnly":false,"multiple":false,"advanced":false,"verify":false,"limitToOptions":true,"unitLabel":"s","options":[],"filterCriteria":[],"locale":null,"filterText":"","inputType":"number","element":"input","pattern":"-?\\d+"}],"parameterGroups":[{"name":"_default","label":"Others"},{"name":"_default","label":"Others"}],"description":"Allows direct access to the OWFS","label":"Direct Access to OWFS-Path (String)","itemType":"String","kind":"STATE","stateDescription":{"readOnly":true,"options":[]},"tags":[],"UID":"onewire:owfs-string","advanced":false},"acceptedItemTypes":["String"]},{"uid":"onewire:owserver:1df5a011:test2","id":"test2","channelTypeUID":"onewire:owfs-string","itemType":"String","label":"Test2","configuration":{"path":"statistics"},"defaultTags":[],"linkedItems":[]}],"hasProperties":false}
```

**Comment by cweitkamp** [comment]
I am not an UI expert but I guess we can solve it with a single line of code added in my linked file like this `kind : $scope.channelType.kind,`:

```
        var channel = {
            uid : thing.UID + ':' + $scope.channelId,
            id : $scope.channelId,
            channelTypeUID : $scope.channelType.UID,
            kind : $scope.channelType.kind,
            itemType : $scope.channelType.itemType,
            label : $scope.channelLabel,
            configuration : $scope.configuration,
            defaultTags : $scope.channelType.tags,
            linkedItems : []
        }
```

**Comment by openhab-5iver** [comment]
That should handle the PUT request, but I'm not convinced $scope.channelType.kind is populated. When debugging in the brownser, I do not see 'kind' in any of the responses leading up to the PUT, so a change may be needed in the REST API too. I'll also open a second issue about non-trigger Channels being able to trigger rules, which may be related to https://github.com/openhab/openhab-core/issues/706. I'm still poking at this one.

@kaikreuzer, could you please move this issue to the openhab-webui repo?

**Comment by cweitkamp** [comment]
I created https://github.com/openhab/openhab-webui/pull/84. Lets see what @openhab/webui-maintainers think about it.
