### ISSUE TITLE
[hueemulation] readyMarker not received. var started never gets true?

### ISSUE THREAD

**Issue by mbehr1** [openhab/openhab-addons#5419]
## Expected Behavior
the HueEmulation service never seems to start the httpServlets. Neither description.xml nor api/description.xml can be received (return 404).
I suspect that the ReadyMarker is never received and thus started is never set to true.

If I stop the bundle and restart it I see
Added items: ... 

and if I change configuration (e.g. enable pairing) I get ServiceEvent MODIFIED messages. 
So it seems as if the add-on itself is properly installed.
I changed log level to TRACE but get not hue related errors/warnings/traces...

Any help / hints appreciated!

## Your Environment
2.5.0-SNAPSHOT
Build #1566
Rasbian

**Comment by davidgraeff** [comment]
That is possible. I have rewritten the implementation (see pull requests) and I'm no longer using the readymarker but I process an item as soon as it comes in now.

Other io services are using a debounce mechanism for the item registry.

**Comment by mbehr1** [comment]
@davidgraeff please have a look at PR #5424. Can this serve as an interims workaround? I'd like to test your new PR as well but had some issues with testing (see comment on your PR).
