### ISSUE TITLE
[freemobilesms] Add FreeMobile SMS Binding

### ISSUE THREAD

**Issue by guyou** [openhab/openhab-addons#5420]
I wish to add support for a SMS service provided by [Free Mobile](http://mobile.free.fr/) operator. This service is a simple HTTP API to send SMS back to the customer (and not to arbitrary contact). It is clearly a service to integrate with Home Automation or Self-Hosting.

A it is my really first contribution to OpenHAB, I'm looking for help/mentoring as I thing such feature is quite different from standard bindings. Can someone point me to a related existing addon?

**Comment by guyou** [comment]
Perhaps something similar to https://www.openhab.org/addons/actions/mail/

**Comment by davidgraeff** [comment]
It's a mixture of a binding and an action, correct.

Have a look at the xmpp and mail pull requests. They are in the same category.

**Comment by lolodomo** [comment]
I am using this service. This is only one line of code in a DSL rule to call thr HTTP API.
I don't see the need of a binding for that.

**Comment by davidgraeff** [comment]
Almost all weather bindings are just http calls ;) It's still an external service and a binding with an action is a valid approach

**Comment by lolodomo** [comment]
When there is the need to parse returned data and expose data, it makes sense.
Here, there is no returned data.

**Comment by davidgraeff** [comment]
Ok I put it in a different perspective. I do not want to touch a single line of textual file for using a home automation system. If this service is wrapped in an automation action, I can use my Paper UI replacement to make a rule fully graphically to send sms on certain triggers. So I like this idea.

**Comment by J-N-K** [comment]
Perhaps @lolodomo can show what the request looks like and this can be done with the HTTP binding?

**Comment by davidgraeff** [comment]
But is there no api key and rate limiting involved that would require a queue to not hit the quota etc? That's what I would expect to be handled by such a binding

**Comment by guyou** [comment]
@lolodomo is certainly right: creating a binding for this use case is certainly overdesigned.

I imagined that a dedicated binding can simplify a lot the usage of such service. In my idea, the binding can ack like the http binding:
- in one hand I define Things to pack the different credentials
- in an other hand, I use these things as ouput

For example, first creating the things:
```
dad.account=1234
dad.token=abcdef
mom.account=5678
mom.token=fedcba
```
Then, creating Items:
```
Switch atHome { sms="ON:dad:I'm at Home!" }
```

Please, correct me if my idea is wrong or if the concepts are misunderstood.
I have to admit I still not yet deployed OpenHAB because the things I have are not supported (but I plan to add support for them):
- FreeboxV5
- Nabaztag:tag
- Karotz

**Comment by guyou** [comment]
At the opposite, how should I design the binding in order to be able to create rules like the following:
```
rule "Alert John at home"
when
  Item Presence_Mobile_John changed from OFF to ON
then
  DAD_SMS.sendMessage("John is at home!")
end

rule "Alert John leaving"
when
  Item Presence_Mobile_John changed from ON to OFF
then
  DAD_SMS.sendMessage("John leave the home.")
end
```

Any help appreciated.

**Comment by guyou** [comment]
I have a code working: https://github.com/guyou/openhab2-addons/tree/freemobile-sms

I still not yet created a pull request (because I still have some things to clean), but comments are appreciated.

**Comment by lolodomo** [comment]
As the question was asked, here is how I am sending a SMS from a rule:
```
val String CmdFreeSms = "https://smsapi.free-mobile.fr/sendmsg?user=xxx&pass=yyy&msg=%1$s"

sendHttpGetRequest(String::format(CmdFreeSms, "Message to send".encode("UTF-8")))
```

**Comment by guyou** [comment]
Pull request created: #5520

**Comment by hmerk** [comment]
closed as related PR was closed
