### ISSUE TITLE
[harmonyhub] Hub freezes on repeat key presses

### ISSUE THREAD

**Issue by wejgomi** [openhab/openhab-addons#5426]
Harmony hub freezes and stops sending commands to devices when sending fast repeated commands(same/different) through interface or NEEO Remote on 2.4.0 build.

Steps to Reproduce
1. Add any Bluetooth/IR device connected to Harmony Hub to Openhab as a thing.
2. Configure item bindings and set buttons (cursor up/down etc) through interface
3. Repeat commands quickly for one/multiple devices
4. Hub issues commands for a while and stops responding.
5. Hub only responds when cycled(disable-enable) through things but can be controller through harmony remote even when frozen to Openhab.

Same applies for 2.5.0 M1, but 2.5.0 Snapshot build seems to be better for issuing repeated commands, is there any fix/delay introduced in snapshot build regarding this problem ?

Logs to follow but seem normal with no apparent errors in trace output.

Environment:
Debian Stretch 9.8.0 no-gui
Openhab 2.4.0
Harmonyhub binding
NEEO Binding
NEEO Integration

**Comment by digitaldan** [comment]
Thanks for the report, i'll take a look at this over the weekend.

**Comment by digitaldan** [comment]
@wejgomi , i misread your post.  There was a substantial rewrite to the binding which is what is available in the 2.5 snapshot.  I can confirm this issue does not seem to be present in this newer version.  Its possible the 2.5 version of the binding may work in your 2.4 setup, but i have not tried that.

**Comment by wejgomi** [comment]
@digitaldan Thanks for confirming this. Been using Snapshot Build for some time now, though the freezing do not seem to occur,  some devices seem to register random commands endlessly until OpenHAB is restarted.

The behaviour usually occurs after a day of use and seems to be limited to some devices and protocols(AppleTV over Bluetooth), rarely affects some IR devices too.

I will investigate into this soon as I find time to go over logs, might/not have something to do with binding but the core itself, snapshot builds we're talking after all.

**Comment by hmerk** [comment]
closed due to inactivity
