### ISSUE TITLE
[rfxcom] Add Support for Inexpensive 433Mhz Motion Sensors

### ISSUE THREAD

**Issue by skydiverscott** [openhab/openhab-addons#5437]
Please add support for the inexpensive PIR Motion sensor from China I purchased here:
https://www.amazon.com/gp/product/B073WTR8PW/ref=oh_aui_detailpage_o00_s01?ie=UTF8&psc=1

I am running Openhabian (fully patched and updated as of 4/7/2019) on a RP3B.  I have a RFXCOM Trx433E with firmware version 1038 running on it. 

I have been working on getting these device working on OH3 for over a year now.  I just recently picked this project back up and there is a demonstrable difference in the OH2 Logs from my work last year.  

Previously there were Java error references when the data was received from the RFXCom Transceiver.  Now it looks like there is device detection but it is sending an unsupported command.  These devices ONLY send motion and do not receive any commands.

These devices are detected in RFXManager as Lighting4 devices/PT2262
Here is the device RFXManager output:

> 4/7/2019 09:59:47:314
> Packettype    = Lighting4
> subtype       = PT2262
> Sequence nbr  = 29
> Code          = D05FC6 decimal:13656006
> S1- S24  = 1101 0000 0101 1111 1100 0110 
> Pulse         = 410 usec
> Signal level  = 8  -56dBm
> 

Here is the devices data in OH2 Log files:
> 2019-04-09 08:40:58.981 [INFO ] [rnal.messages.RFXComLighting4Message] - A not completely supported command with value 6 was received, we can send it but please report it as an issue including what the command means, this helps to extend the binding with better support.
> 2019-04-09 08:40:58.985 [DEBUG] [g.rfxcom.handler.RFXComBridgeHandler] - Message received: Raw data = 091300EF505FC6019670, Packet type = LIGHTING4, Seq number = 239, Sub type = PT2262, Device Id = 329212, Command = UNKNOWN(6), Pulse = 406
> 
 Let me know else is needed from me to support these devices.

**Comment by skydiverscott** [comment]
I would be willing to pay a small bounty to someone to help resolve this provided they walk through how that identified the data that needed to be accommodated and the changes necessary to implement them in Openhab

**Comment by skydiverscott** [comment]
I did some more data captures if rfxmanager and have confirmed that these devices ONLY send data when a motion event is occurring.  I cannot tell if they send any order data in the packet other than motion status (i.e. battery level).  This would appear to be something simple to setup for motion events except the issue of the command value 6.
My offer for a small bounty with some guidance as to how the value is determined out of the data package and where to assign these values in the code base stands.

**Comment by skydiverscott** [comment]
I ran the device in a closed room with only two motion events.  It does not appear that the device sends any kind of update status while not detecting an active motion event,  I converted the data captures in RFXManager into a CSV attached here: https://srmservices-my.sharepoint.com/:x:/p/skydiver/EWo_B84xCrJNiWq3uMYm3zwBEGI8M-O67ooJdGDtrRx3ag?e=34ClLB

**Comment by martinvw** [comment]
Let me add this to PR https://github.com/openhab/openhab2-addons/pull/5685
