### ISSUE TITLE
Builds fail in logreader

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#5442]
Since today all builds fail while compiling logreader. This is happening for Travis, Jenkins and in my local builds. 

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.openhab.binding.logreader: Compilation failure
[ERROR] C:\Users\jnk\openhab2-master\git\openhab2-addons\bundles\org.openhab.binding.logreader\src\main\java\org\openhab\binding\logreader\internal\filereader\FileTailer.java:[64,1989] The constructor Tailer(File, TailerListener, long, boolean, boolean, boolean) is undefined
```

This constructor is the reason why the commons.io-library is included in the binding since it is not merged upstream and Eclipse is able to resolve it.

**Comment by maggu2810** [comment]
> it is not merged upstream

This explains why I did not found it in the current master of `commons-io`.
Can you point us to the relevant PR that adds the function?

**Comment by J-N-K** [comment]
Issue: https://issues.apache.org/jira/browse/IO-279
PR: https://github.com/apache/commons-io/pull/40

**Comment by maggu2810** [comment]
As long as this merge request is not accepted upstream, wouldn't it be much simpler to check in the modified Tailer.java file in a custom package instead of bundling the whole commons-io library using some strange addjars mojo?

**Comment by J-N-K** [comment]
As far as I can see we only use the `ignoreNew=true`, can't we just inherit a new `OHTailer` from `Tailer` and override the `public void run()`?

**Comment by maggu2810** [comment]
Is it a question for @paulianttila (codeowner)?
I personally don't know why it has not been done this way.

**Comment by paulianttila** [comment]
Initially, just modified Tailer class (+ TailerListener and TailerListenerAdapter) was included the binding. During code review I changed it jar.

**Comment by maggu2810** [comment]
So, back to the roots. :wink: 

IMHO the class(es) should be added and you should not use a subclass that inherits `Tailer`.
The specific commons-io implementation is not in your control and nobody knows if it will still work if a runtime uses 2.8 some time...
So, add the class(es) in a specific package again (if the maintainer agree) and add a message to its header that contains the links above and a message that the files can be removed if that PR is accepted.

**Comment by Misiu** [comment]
[The PR](https://github.com/apache/commons-io/pull/40#issuecomment-482089524) @J-N-K  mentioned won't get merged, because of missing tests and broken build.
I'm not a Java expert but if someone could look into this then new PR can be created and this can be fixed in commons-io

**Comment by J-N-K** [comment]
IMHO the original library should never have been merged.
