### ISSUE TITLE
[knx] Wrong device status. It's OFFLINE, while it is working. 

### ISSUE THREAD

**Issue by Pirx99** [openhab/openhab-addons#5484]
## Expected Behavior
The status should be ONLINE, because the devices are working properly

## Current Behavior
The binding sets the KNX-Bridge to ONLINE and all devices to OFFLINE despite the fact that the general communication with the devices are working without any issues.  I've set the DEBUG level, but was unable to find any bad entries.

## Possible Solution
No idea!

## Steps to Reproduce (for Bugs)
This is my bridge config and a device example:
(my KNX-Bridge is _Enertex KNX/netIP Router_)
```
Bridge knx:ip:bridge "KNX IP Interface"
[
    type="ROUTER",
    ipAdress="192.168.178.17",
    portNumber=3671,
    readingPause=50,
    responseTimeout=10,
    readRetriesLimit=3,
    autoReconnectPeriod=5,
    localSourceAddr="0.0.0",  
    localIp="192.168.178.18"
]
{
    Thing device KG_Gira2174_Dimmaktor1 "GIRA 4-fach Dimmaktor1" [address="1.1.4"]
    {
        Type switch : EG_WZ_EL_Schalten "WoZi-Esstischlampe Schalten" [ga="1.001:2/1/10+<2/1/11"]
        Type dimmer : EG_WZ_EL_Dimmen   "WoZi-Esstischlampe Dimmen"   [switch="1.001:2/1/10+<2/1/11", position="5.001:2/1/13+<2/1/14", increaseDecrease="3.007:2/1/12"]
        Type switch : EG_WZ_SP_Schalten "WoZi-Spots Schalten" [ga="1.001:2/1/30+<2/1/31"]
        Type dimmer : EG_WZ_SP_Dimmen   "WoZi-Spots Dimmen"   [switch="1.001:2/1/30+<2/1/31", position="5.001:2/1/33+<2/1/34", increaseDecrease="3.007:2/1/32"]
        Type switch : EG_KU_SP_Schalten "Kochinsel-Spots Schalten" [ga="1.001:2/1/40+<2/1/41"]
        Type dimmer : EG_KU_SP_Dimmen   "Kochinsel-Spots Dimmen"   [switch="1.001:2/1/40+<2/1/41", position="5.001:2/1/43+<2/1/44", increaseDecrease="3.007:2/1/42"]
    }
}

```
## Context
The disadvantage of the OFFLINE status comes, when a devices tries to sent periodic values to openhab. In this situation I see a new value coming, but OH refuses to update the item accordingly because the device status is OFFLINE.  This is somehow obvious and smart. 
However, I didn't find any reason why the binding is insisting to the OFFLINE status.

## Your Environment
OH 2.5.0-SNAPSHOT Build #1472 
Linux 4.9.45-ubilinux+ #2 SMP Fri Sep 8 10:51:36 IST 2017 x86_64 GNU/Linux

**Comment by Pirx99** [comment]
How can I help the developer of the KNX binding to start working on the solution?

**Comment by lewie** [comment]
@Pirx99,
thank you for asking, I only saw your request now.

Your ROUTER configuration is incorrectly configured at "ipAdress".
probably also on "localIp", for certain for "autoReconnectPeriod".

https://www.openhab.org/addons/bindings/knx/#ip-gateway

Please test the following configuration and it works:
```

Bridge knx:ip:bridge "KNX IP Interface"
[
    type="ROUTER",
    //ipAdress="192.168.178.17",  //DO NOT SET for ROUTER mode. 224.0.23.12 is set default, 224.0.23.12 is reserved for knx/IP ROUTER mode. Only if this value deviates from the standardized value in the IP Router interface, this value may be set or changed.
    portNumber=3671,  //3671 is set default, so this is optional. Better do not set.
    readingPause=50,
    responseTimeout=10,
    readRetriesLimit=3,
    autoReconnectPeriod=60, //5, //CHANGED 5 sec. is too short!
    localSourceAddr="0.0.0",  //"0.0.0" is set default, so this is optional. Better do not set. Let it do the Bus itself.
    //localIp="192.168.178.18",  //DO NOT SET if only one network card is available, not necessary. Wrong IP causes Errors
]
{
    Thing device KG_Gira2174_Dimmaktor1 "GIRA 4-fach Dimmaktor1" [ 
        //address="1.1.4" //DO NOT SET - aktor parameters are not needed/processed for a correct communication BUS<->openHAB.  The readout of the internal aktor parameters, loads the bus and can bring the communication of some devices to a complete standstill - simply do not use.
    ] {
        Type switch : EG_WZ_EL_Schalten "WoZi-Esstischlampe Schalten" [ga="1.001:2/1/10+<2/1/11"]
        Type dimmer : EG_WZ_EL_Dimmen   "WoZi-Esstischlampe Dimmen"   [switch="1.001:2/1/10+<2/1/11", position="5.001:2/1/13+<2/1/14", increaseDecrease="3.007:2/1/12"]
        Type switch : EG_WZ_SP_Schalten "WoZi-Spots Schalten" [ga="1.001:2/1/30+<2/1/31"]
        Type dimmer : EG_WZ_SP_Dimmen   "WoZi-Spots Dimmen"   [switch="1.001:2/1/30+<2/1/31", position="5.001:2/1/33+<2/1/34", increaseDecrease="3.007:2/1/32"]
        Type switch : EG_KU_SP_Schalten "Kochinsel-Spots Schalten" [ga="1.001:2/1/40+<2/1/41"]
        Type dimmer : EG_KU_SP_Dimmen   "Kochinsel-Spots Dimmen"   [switch="1.001:2/1/40+<2/1/41", position="5.001:2/1/43+<2/1/44", increaseDecrease="3.007:2/1/42"]
    }
}
```

**Comment by Pirx99** [comment]
@lewie 
many thanks. Now all devices are online :-)
IMHO the doc must be adjusted. For example in case of 'ipAdress' the doc is telling: "If type ROUTER is set, the IPv4 Multicast Address can be set."  which contradicts your statement suggesting: "DO NOT SET for ROUTER mode".

**Comment by lewie** [comment]
@Pirx99, I'm very happy about that!

In addition, the improved/simplified sample configuration in the official KNX-Binding documentation:
https://www.openhab.org/addons/bindings/knx/#examples

**Comment by J-N-K** [comment]
Resolved according to opener.
