### ISSUE TITLE
[tesla] Binding errors

### ISSUE THREAD

**Issue by flodorn** [openhab/openhab-addons#5486]
## Current Behavior

Binding installs fine, but after adding my model S as a thing, I'm getting the following error output in my log:

> 2019-04-18 22:37:49.681 [ERROR] [b.binding.tesla.handler.TeslaHandler] - An exception occurred while parsing data received from the vehicle: 'java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 492 path $.seat_heater_left'

Error pops up every minute or so. 

This Warning also shows up once in a while:

> 2019-04-18 20:49:17.553 [WARN ] [ore.internal.thing.ThingTypeResource] - Cannot find channel type: tesla:ispreconditioning

Same problem when I add my Model X. 

I tried uninstalling and reinstalling the binding, adding and removing cars, still same issue.

The binding actually works, but my log gets clotted by these unwanted msg.

## System

* Version used: Tesla binding 2.4.0 / Openhab 2.4.0-1

* Tesla Model S 2018 and Model X 2017

**Comment by hmerk** [comment]
closed due to inactivity
