### ISSUE TITLE
[tradfri] Bridge goes offline since Gateway 1.8.25 update

### ISSUE THREAD

**Issue by yapbreak** [openhab/openhab-addons#5489]
Since latest Tradfri gateway update, bridge goes offline even after Openhab restart.

## Expected Behavior

Gateway should be online!

## Current Behavior

When I start Openhab, I get error regarding Tradfri bridge connection. In events.log file, I get message like this:

```
[hingStatusInfoChangedEvent] - 'tradfri:gateway:mygateway' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR)
```

I did not find any other relevant log files or information! Feel free to ask me anything else that could help. Note that my setup was working for more than 4 mouths before, I did not recently update my openhab box, so the only relevant change is firmware update.

## Possible Solution

With previous gateway firmware, I sometimes need to _touch_ configuration file to force a reconnection and avoid communication errors, but with this new firmware, it does seems to work…

## Steps to Reproduce (for Bugs)

1. Configure a Tradfri gateway
2. Update Tradfri gateway firmware
3. Now, your bridge is offline.

## Context

I just wanna use my Tradfri stuff as before! :D

## Your Environment

* Version used: OpenHab 2.4.0 Release Build as provided by AUR repository on archlinux. 
* Environment: Openjdk 8.u212
* Operating System: Archlinux

Regarding the hardware, my openhab box and the Tradfri gateway are linked through wire to the same switch (no wifi or broadband over powerline issue)

## One last thing
Thank you for all your work on this project!

**Comment by FlipFlap3** [comment]
When using the things file to add the gateway, the gateway will go offline.
Using paperUI and autodiscovery however does result in the gateway being online.
the items file can however still be used.

**Comment by LightIsLife** [comment]
Just some additional info: 
The identity code changes every time the bridge is added to OH2 and hence, it seems impossible to add through text files only (e.g., copying identity code from PaperUI, deleting file and using old identity code in text file).
As a side node, if one tries to add it through the text files only with an invalid identity code, it seems to also knock out the TP-Link binding; all of my TP-LINK outlets became unreachable until I fixed the tradfri bridge.

**Comment by yapbreak** [comment]
Thank you for your hints. I switch back to a "paperUI" bridge configuration and it seems to work much better!

**Comment by thedannymullen** [comment]
> Just some additional info:
> The identity code changes every time the bridge is added to OH2 and hence, it seems impossible to add through text files only (e.g., copying identity code from PaperUI, deleting file and using old identity code in text file).

I disagree with this statement and have not seen this  behavior.    Can you site what steps taken to get the ID to change?  

I do agree though that the text file config needs some patching due to new firmware.

**Comment by thedannymullen** [comment]
See post: https://community.openhab.org/t/tradfri-1-8-25-offline-communication-error/72732/39

Several users with text files and no issues.  I have been online for several days across openhab restarts.  

My proposal would be to make the text file behave like paper UI.  You add the code and behind the scenes everything gets done.  This way we don't need to go through a multistep process of adding the gateway in paperui simply to get the key values, then deleting.    Maybe this info could simply be echoed to the log file similiar to phillips HUe binding first use.   That would be an acceptable solution.  

Hue similar steps I would see is:
1. Add thing file with gateway ip and code.
2. Identity and preshared key echoed to log file
3. User modifies thing file 
4. Happy user everything works!

**Comment by LightIsLife** [comment]
@thedannymullen I have performed the following operation three or four times
- delete bridge def from text file, restart OH2
- discover and add bridge through PaperUI;
- copy out Identity code and delete thing in PaperUI (mostly using the delete function in PaperUI, but once I simply deleted the whole jsonDB and its backups to see if that makes a difference)
- add newly received identity code in text file for bridge definition
- OH2 tries to add bridge Thing as now defined in text file, but status is stuck somewhere around “uninitialized”

I am seeing from your other posts that you never report that you actually delete the Thing in the PaperUI after the identity code is recovered. When I do not delete in PaperUI, I receive the a warning that bridge thing already exists. However, when I delete it...see above...as for the identity code changed

**Comment by thedannymullen** [comment]
You have to remove the code= statement and replace with identity and pre shared key.  
See the example file in the post I linked to.

**Comment by LightIsLife** [comment]
@thedannymullen not sure what you are referring to but apparently I am being unclear. Just to avoid further misunderstandings, here my text file configuration for the Tradfri bridge thing
```
Bridge tradfri:gateway:gwa0xxxxxxc85f [ host="192.XXX.X.XX", 
identity="45e379198xxxxxxxxxxxxxxxxxxxx67", preSharedKey="UIvQxxxxxxxxeatd"  ] { ...
 ```
Kept the length of the token intact, masked some digits for privacy. 
And it works...somewhat...e.g., here is what I have to do after a reboot to reconnect the bridge:
- take the bridge definition out of the config file
- restarting OH2 reconnects OH2 with the bridge (as I had previously added bridge via PaperUI and left the Thing definition from PaperUI in the jsonDB)
- putting the definition back into the Things files

**Comment by EliasGabrielsson** [comment]
### Issue:
I have my Trådfri Gateway on a separate subnet which prevents the auto-discover function to work.
Therefore I need to use the "add manual" function of paper-UI which gives me `OFFLINE - COMMUNICATION_ERROR`.

### Question?
Does anyone manage to add the gateway with "Add Manual" function in Paper-UI?

**Comment by chriscolden** [comment]
I can confirm im seeing the same thing. If i change the ip and change it back again it comes online briefly before going offline again.

Openhab and tradfri are in the same subnet in my case.

**Comment by olemr** [comment]
My story: after trying all hints and suggestions and then some, I had to reset my Ikea gateway with a pin and re-pair all devices. After that it was stable again. Trouble started with the 1.8.25 update when several remotes was low on batteries and the gateway tried and failed to update for several days. Ended in a bad state were it answered to ping, but the COAP interface and sometimes the Ikea App itself could not connect. (even after all the remotes was updated.) See my posts on the forum for more info.

**Comment by chriscolden** [comment]
Seems the issue was due to remotes not being updated. I had also removed the gateway trying to get this working. so after getting all remotes updated, I found my old pre shared key and identity and readded the gateway. This solved it for me.

**Comment by Orfait** [comment]
On my side, all remotes were updated and I got this issue again.

From my point of view, the issue label "enhancement" should be "bug".

**Comment by choppedpork** [comment]
Not sure if this is helpful at all but my setup ended up in a peculiar state where the wireless control outlet still works - and quite reliably, too - but all other Tradfri devices stop working within minutes of restarting OH (CoAP 4.04 error).
One other strange behaviour I've noticed is that the bridge remains online and Paper UI discovers all of my items correctly - using the very same IDs defined in my item files (for items which don't work due to the CoAP 4.04 error).

I'm on file configs (thing / item) updated to use identity + psk instead of code.

**Comment by alexf2015** [comment]
In my opinion the binding should persist the "security code" as it does not change. and cache "identity" and "Pre-Shared security key" as long as those values are valid. In case the "identity"/"pre shared secuirty key" become invalid (status: communication error) those values should be dropped and new connection should be initialized using the "security code".
This approach should be valid for both paper ui and file based configurations.

Currently I am using a paper ui config and in case of a reboot of the gateway or openhab I need to perform the above mentioned steps manually via paperui to get the binding working again.

**Comment by shutterfreak** [comment]
I only need to set the pre-shared security key in Paper UI to get the gateway back online since the 1.8.25 Tradfri gateway firmware update.

**Comment by chriscolden** [comment]
Mine has gone offline again, and wont come back online no matter what I do. All devices up to date. Gateway is now 1.8.26. Google home and ikea app has no issue connecting. So it must be something to do with the binding.

**Comment by EliasGabrielsson** [comment]
I have also problem to add it, no matter what.
Something I noticed when pairing the Android app in _manual mode_ was that it asked for the MAC address in complement to the IP address. Are they doing some layer2 communication stuff ignoring the IP protocol?

**Comment by chriscolden** [comment]
@EliasGabrielsson it sounds like the scan of the qr code failed it falls back to asking for the security code, which I believe is also the mac address.

**Comment by ulfwin** [comment]
I managed to get it online by:
1. remove host, security key, identity and pre-shared key from the configuration page and save.
2. Reenter host (ipv3 ip-address in my case) and security key and save.

Perhaps that helps someone

**Comment by flo-02-mu** [comment]
> Seems the issue was due to remotes not being updated. I had also removed the gateway trying to get this working. so after getting all remotes updated, I found my old pre shared key and identity and readded the gateway. This solved it for me.

I can confirm this. I had one remote with low battery that was not updated. Regardless whether using the app or openhab the gateway got unstable (sometimes reacting with a delay of a couple of seconds). Inserting a new battery, (auto)completing the update-process and re-adding it to openhab did the trick for me. I now blocked the internet access for the gateway in my router and the entire setup is now stable for more than 24 hours.

**Comment by Dennis14e** [comment]
I think the following function is the problem:
https://github.com/openhab/openhab2-addons/blob/6130907cfd42337a68374b3bcedbc0d7a194a796/bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java#L315-L327

The function tries to load the gateway firmware version, and depending on this, it logs in via Security Code or Identity/Preshared Key:
https://github.com/openhab/openhab2-addons/blob/6130907cfd42337a68374b3bcedbc0d7a194a796/bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java#L111-L113

Meanwhile you have to log in with Identity/Preshared Key, otherwise you won't get an answer from the gateway (I guess this wasn't the case before the update).

Since the binding cannot get a firmware version, the security code is used as a preshared key (legacy fallback). However, this does not allow any queries to be made:
https://github.com/openhab/openhab2-addons/blob/6130907cfd42337a68374b3bcedbc0d7a194a796/bundles/org.openhab.binding.tradfri/src/main/java/org/openhab/binding/tradfri/internal/handler/TradfriGatewayHandler.java#L124

**Comment by J-N-K** [comment]
Sounds reasonable. This also explains why PaperUI configured things are less affected, since managed things store the properties.

Can you provide a fix for that?

**Comment by Dennis14e** [comment]
Unfortunately not, I don't have much experience in Java programming and none in programming OpenHAB bindings.
Also I don't know how to get the firmware version (according to Gateway version 1.2.42 it should work over mDNS):
https://ww8.ikea.com/ikeahomesmart/releasenotes/releasenotes.html

**Comment by EliasGabrielsson** [comment]
Are there any reasons that the binding today exposes the `identity` and `Preshared Key` to the enduser?

Could not the binding just rehandshake these parameters if they are invalid. That would enable configurations like before with just the `Security Code`.

**Comment by Dennis14e** [comment]
The binding renegotiates the identity and the preshared key, but this doesn't work at the moment because the firmware version check (and so the decision how to log in) doesn't work (see here https://github.com/openhab/openhab2-addons/issues/5489#issuecomment-522236193).
Instead of renegotiating Identity and Preshared Key, the binding currently uses the (default) legacy way (Security code == Preshared Key, Identity == "").

**Comment by EliasGabrielsson** [comment]
Yes, got that. Well spotted! This was more of a general reflection, i.e. could it be possible to hide that mechanic for the end-user to minimize clutter during configuration.

**Comment by J-N-K** [comment]
@kaikreuzer since this is orginially your code, what do you think about dropping support for gateways with firmware versions below 1.2.42? 1.2.42 is around for nearly two years and already has 1.3.14, 1.4.15, 1.8.25 and 1.8.26 (current) as successors.

This would simplify the login-code very much and probably help in a lot of these cases without the need for programming workarounds for legacy firmware versions.

**Comment by shutterfreak** [comment]
Instead of applying “oldest-first”, wouldn’t it make more sense to apply
“newest-first”? In other words, first check whether the business logic for
recent gateway firmware releases applies, and if it fails, fall back to
older versions?

**Comment by kaikreuzer** [comment]
> @kaikreuzer since this is orginially your code, what do you think about dropping support for gateways with firmware versions below 1.2.42?

Fine for me, we should just mention it in the docs.

**Comment by shutterfreak** [comment]
I may have to reopen this issue, since the TRÅDFRI binding in OH2.5 Milestone build 4 still has one problem: when restarting openHAB I always have to log into the Karaf console and manually restart the TRÅDFRI binding, as in:
```sh
$ sudo sudo service openhab2 restart
$ openhab-cli console
openhab> bundle:restart "openHAB Add-ons :: Bundles :: TRÅDFRI Binding"
openhab> logout
$
```

**Comment by BasvanH** [comment]
I have the exact same issue. Reboot OH results in disconnected gateway. Restart of binding solves it.
