### ISSUE TITLE
[mqtt] Applies transformationPatternOut after formatBeforePublish

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab-addons#5507]
Running OH2.5 M1, OS is Ubuntu 18.04.2

Moving over from binding MQTT 1.x to MQTT 2.x I found that the transformation order when publishing is odd.

Specifically I have some switches that send to the same topic, but with different activation strings.
topic is `/roomba/setting` strings can be `openOnly true` `carpetBoost false` (plus several others) where the true/false changes with the switch setting. Note the incoming data is inverted, and is also true/false (that's just the way it works).
The outgoing true/false has to be transformed from the default 0/1 given by a switch (incoming is translated by a MAP). Trying
```
Type switch : roomba_edgeClean    "Edge Clean"        [ commandTopic="/roomba/setting", stateTopic="/roomba/feedback/openOnly", transformationPattern="MAP:inverse_switch.map",  transformationPatternOut="MAP:mqtt.map" ]
```
where mqtt.map maps 0/1 to true/false publishes true/false as expected when the switch is toggled.

mqtt.map is:
```
1:true
0:false
```

adding `formatBeforePublish="openOnly %s"` to give this:
```
Type switch : roomba_edgeClean    "Edge Clean"        [ commandTopic="/roomba/setting", stateTopic="/roomba/feedback/openOnly", transformationPattern="MAP:inverse_switch.map",  transformationPatternOut="MAP:mqtt.map",  formatBeforePublish="openOnly %s"]
```
Results in publishing NULL instead of the expected `openOnly true` (or false). I believe this is because formatBeforePublish seems to format the string _before_ sending the result to the transform (transformationPatternOut), which fails, because "openOnl;y true" is not in the transform map `mqtt.map`.

This would seem to be incorrect behavior, `formatBeforePublish` is actually `formatBeforeTransform` which would seem altogether less useful. Unless the order they are defined in the Thing matters? (does not seem to)

I have managed to get the behavior I need with the following thing definition:
```
Type switch : roomba_edgeClean    "Edge Clean"        [ commandTopic="/roomba/setting", stateTopic="/roomba/feedback/openOnly", transformationPattern="MAP:inverse_switch.map", formatBeforePublish="openOnly %s", on="true", off="false" ]
```
As the `on` and `off` definition seems to be applied to the outgoing publish command (and not the incoming data as seems to be implied in the documentation), and is then formatted before publishing correctly.

Is this expected behavior? or are the transforms in the wrong order? Surely you should transform the switch/dimmer/whatever _before_ formatting, it makes no sense to do it _after_.

**Comment by davidgraeff** [comment]
Unfortunately this need to be verified on an OH2.5m2 at some point, because ordering has changed as well as the "on" and "off" behaviour (they are used for incoming and outgoing now).

I'm also not sure about the implementation for "transformationPatternOut". I thought it was not part of OH2.5m1. What you at least can do now is to chain transformations to solve your specific usecase.

**Comment by NickWaterton** [comment]
Thanks for the feedback. I assume 2.5M2 will not be released until the build problems are sorted out (some time yet).
"transformationPatternOut" seems to work in 2.5M1, and the documentation covers it, but it's not clear what version the documentation covers (it just says 'latest" - whatever that is).

I saw some mention of chaining transformations, but that was only for incoming data, not outgoing, or can you do this with both? It also wasn't clear how you would do this.

I did also try:
```
formatBeforePublish="openOnly %b"
```
As I thought this would give me a boolean "true" or "false" for the switch toggle, but it only gives "true" all the time. I assume this is because a switch state is not really a boolean, as java would see it. so NULL would be false, but anything else evaluates as 'true".

I actually had my logic wrong in my "roomba" thing as well, on further testing, the thing that works is:
```
Type switch : roomba_edgeClean    "Edge Clean"        [ commandTopic="/roomba/setting", stateTopic="/roomba/feedback/openOnly", transformationPattern="MAP:inverse_switch.map", formatBeforePublish="openOnly %s", on="false", off="true" ]
```
ie. on="false" and off="true" (because roomba has reverse logic for some reason). You would think that i wouldn't need the incoming transform, but Roomba sends "False" and "True" (note the capital initial letter) and that gives you this error;
```
26-Apr-2019 12:06:22.584 [WARN ] [binding.mqtt.generic.internal.generic.ChannelState] - Command 'False' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.False
```
So you need the transform to handle the capital letter (unless there is a way to get multiple values for on and off (like on="false|False" or on="false,False"). I may have to resort to reading the source code...
It is really hard to test as well, as I have to restart OH every time I make any change to the things. I noticed that you said that you would try to fix this in 2.5, i guess it's still works in progress though?

Finally, I see in the log that when you toggle the switch the log says:
```
26-Apr-2019 11:25:22.115 [DEBUG] [.generic.internal.handler.AbstractMQTTThingHandler] - Successfully published value OFF to topic /roomba/feedback/test
26-Apr-2019 11:25:23.863 [DEBUG] [.generic.internal.handler.AbstractMQTTThingHandler] - Successfully published value ON to topic /roomba/feedback/test
```
Which is confusing as `/roomba/feedback/test` is the stateTopic, not the commandTopic (which is what it is actually published to).

So far, the new mqtt binding looks good, I'm running both in parallel (1.x and 2.x) as I have a bazillion (aprox) items to convert over - this is just the first.

In light of the changes in M2, is it worth me continuing the conversion, or should I wait for M2?

Thanks, and keep up the good work.

**Comment by davidgraeff** [comment]
You should probably write a script to perform the conversion.

Restarting should not be necassary in snapshots. OH 2.5m2 might be in sight actually. Only about 5 extensions left to migrate.

**Comment by NickWaterton** [comment]
OK,

Resorting to reading the source, in
`https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/ChannelState.java`
in 
```
    /**
     * Publishes a value on MQTT. A command topic needs to be set in the configuration.
     *
     * @param command The command to send
     * @return A future that completes with true if the publishing worked and false if it is a readonly topic
     *         and exceptionally otherwise.
     */
    public CompletableFuture<Boolean> publishValue(Command command) {
```
lines 343-355
```
        // Formatter: Applied before the channel state value is published to the MQTT broker.
        if (config.formatBeforePublish.length() > 0) {
            try (Formatter formatter = new Formatter()) {
                Formatter format = formatter.format(config.formatBeforePublish, mqttCommandValue);
                mqttCommandValue = format.toString();
            } catch (IllegalFormatException e) {
                logger.debug("Format pattern incorrect for {}", channelUID, e);
            }
        }
        // Outgoing transformations
        for (ChannelStateTransformation t : transformationsOut) {
            mqttCommandValue = t.processValue(mqttCommandValue);
        }
```
So that looks to me as though the formatting is applied _before_ the transform.

Maybe I'll try a snapshot binding (I'm usually wary of those though...).

As to writing a script, my mqtt items are a mishmash of years of trial and error making things work. I think picking through them carefully one by one is safer. maybe a good cleanup time as well.

**Comment by J-N-K** [comment]
@NickWaterton I agree that is probably wrong. I‘ll fix that.
