### ISSUE TITLE
[toon] Update binding for new API backend

### ISSUE THREAD

**Issue by jansen884** [openhab/openhab-addons#5516]
The Toon binding does not work anymore because of changes Eneco made. It returns an error: OFFLINE. Invalid api resonse status: 503

## Expected Behavior
Until februari 2019 the binding was working perfectly, could read and control Toon without any problems

## Current Behavior
It returns an error: OFFLINE. Invalid api resonse status: 503

## Possible Solution
It mus be connected to a new API backend?

## Context
Without this binding, Openhab has become useless for me

## Your Environment
Raspberry Pi, openraspbian.

**Comment by Hilbrand** [comment]
Duplicate of #4902
