### ISSUE TITLE
[hue] Missing color_temperature channel (Ikea CWS bulbs)

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-addons#5535]
![image](https://user-images.githubusercontent.com/28068256/57044252-46b34e00-6c6a-11e9-8dd2-30a893c59a38.png)

Connected to deconz HUE REST API.

Ikea CWS bulbs are listed as device type 200 hence lacking the color_temperature channel:
![image](https://user-images.githubusercontent.com/28068256/57044303-75312900-6c6a-11e9-995d-6e6dbb17f343.png)

![image](https://user-images.githubusercontent.com/28068256/57044468-f4bef800-6c6a-11e9-981b-1641f46348ab.png)

**Comment by cweitkamp** [comment]
Thanks for reporting but I am afraid we cannot change it.

Currently the Philips API sends wrong information about the bulb type thus we cannot discovery it correctly.

See for more information https://github.com/eclipse/smarthome/pull/5946#issuecomment-407035598

**Comment by hmerk** [comment]
closed as marked „won‘t fix“
