### ISSUE TITLE
[harmonyhub] No channel change by current activity

### ISSUE THREAD

**Issue by MisterBJ** [openhab/openhab-addons#5547]
Yesterday I installed the 2.5 snapshot version to control the current activity. Works fine too, but channelUp and channelDown do not work. Everything works perfectly with the original remote control or the harmony app.

`14:35:42.026 [INFO ] [arthome.event.ItemStatePredictedEvent] - harmony_HubWohnzimmer_ButtonPress predicted to become ChannelUp`
`14:35:42.042 [INFO ] [smarthome.event.ItemStateChangedEvent] - harmony_HubWohnzimmer_ButtonPress changed from Exit to ChannelUp`
`14:35:43.785 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'harmony_HubWohnzimmer_ButtonPress' received command ChannelDown`
`14:35:43.882 [INFO ] [arthome.event.ItemStatePredictedEvent] - harmony_HubWohnzimmer_ButtonPress predicted to become ChannelDown`
`14:35:43.895 [INFO ] [smarthome.event.ItemStateChangedEvent] - harmony_HubWohnzimmer_ButtonPress changed from ChannelUp to ChannelDown`

**Comment by hmerk** [comment]
closed due to inactivity
