### ISSUE TITLE
[IDE] After Bndtools Resolve in Eclipse, /rest/things returns HTTP ERROR 503

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#5557]
Launching Bndtools "Resolve" causes demo.app in the Eclipse IDE not to load `/rest/things` anymore, making impossible to test bindings.

## Expected Behavior
Launching Bndtools "Resolve" and then launching demo.app in the Eclipse IDE, all selected bindings and /rest endpoint should be reachable.

## Current Behavior
Launching Bndtools "Resolve" and then launching demo.app in the Eclipse IDE , `/rest/things` endpoint is not reachable and returns `HTTP ERROR 503`

## Possible Solution
bndtools resolve seems broken, at least with the current demo.app and Eclipse.
Comparing demo.app `app.bndrun` file before and after "Resolve", it turns out that this line is removed:
`org.eclipse.equinox.event;version='[1.4.300,1.4.301)',\`
Replacing manually this line into `app.bndrun` file and relaunching "Debug OSGi" makes `/rest/thing` available again 

## Steps to Reproduce (for Bugs)
1. Follow [Setup the Development Environment](https://www.openhab.org/docs/developer/#setup-the-development-environment) until the end: "Debug OSGi"
2. The selected binding (`astro`) is not loaded. `/rest/things` is available.
3. Click "Resolve" to include `astro` in the "Run Bundles" list, re-launch "Debug OSGi" -> the `astro` bundle is now loaded
4. However the endpoint `/rest/things` now returns `HTTP ERROR 503`

## Your Environment
Version used: openhab2-addons SNAPSHOT, maggu2810/openhab-demo SNAPSHOT
Environment name and version: Eclipse Eclipse IDE for Java Developers Version: 2019-03 (4.11.0)
Operating System and version: Windows10

**Comment by davidgraeff** [comment]
We have only recently (2 days ago) merged a critical PR in core that changes how bundles are resolved. Can you make sure that this is still a problem with the newest snapshot core (use `mvn install -U` for the demo app)?

If it is, we escalate this issue to Markus and delegate it to the demo repository. It's really a problem of the demo app, not of the openhab2-addons repository ;)

**Comment by mvalla** [comment]
Ok will do some test. 
Why is the demo app on a personal repo and not on the openhab group? Isn't it part of the official IDE setup ?

**Comment by davidgraeff** [comment]
We have no official developing setup yet, because openhab-distro is not yet ready for the new buildsystem. Kai is working on it. For the time being we are using this "private" repo to at least have something.

**Comment by mvalla** [comment]
after doing a "mvn clean install -U" of openhab-demo, now the problem is solved
