### ISSUE TITLE
[chromecast] Chromecast audiogroup ever changing elected leader 

### ISSUE THREAD

**Issue by jimtng** [openhab/openhab-addons#5564]
I have three google home mini added to openhab as three chromecast:chromecast Things.

I created a Chromecast audio group with all three minis as members. PaperUI discovered this audiogroup Thing, the ip address of the audiogroup thing is the address of one of the three minis above.

## Expected Behavior
The Chromecast audio group thing should work all the time regardless of the changing ip address. It should update the associated ip address whenever it changes. To facilitate this, assign a unique id for the audiogroup instead of an ip address, and perform automatic discovery / update in the background. Apparently, Chromecast provides this unique_id 

## Current Behavior
Whenever the audiogroup elected leader changed, the Thing would stop working (showing offline) because it's pointing to the old leader that's no longer valid as a new / different leader was elected. 

When this happened, you can see in openhab.log the following:
 [WARN ] [su.litvak.chromecast.api.v2.Channel ] -  <--  null payload in message

And in the Inbox ignored things, that audiogroup has been re-discovered with the new elected leader (different ip address).

## Possible Solution
Some ideas were presented here, most notably the "unique_id" mentioned in the second link 
https://github.com/balloob/pychromecast/issues/165
https://github.com/home-assistant/home-assistant/pull/12474
https://github.com/balloob/pychromecast/pull/167

If possible, all chromecast Things to be identified using this unique_id instead of ip address. An example is how the lgWebOSTV binding defines its things:

> Thing lgwebos:WebOSTV:lounge [ deviceId="4441bbff-xxxx-xxx-xxxx" ]

## Steps to Reproduce (for Bugs)
1. Simply have several google home minis and set up an audiogroup containing multiple google home minis
2. Notice that from time to time, the audiogroup thing would say offline, and when this happens, try a discovery process and the same audiogroup (as I only created/have one audiogroup) thing would be detected with a different ip address.

## Your Environment
* Version used: Openhab 2.4.0 inside a docker with network mode=host

**Comment by cweitkamp** [comment]
@jim77 Thanks for reporting this issue. It looks very similar to #4186 which has be solved some time ago.

**Comment by jim77** [comment]
perfect solution. sorry for the duplicate.
