### ISSUE TITLE
[samsungtv] offline_connection_error

### ISSUE THREAD

**Issue by mohsh86** [openhab/openhab-addons#5565]
[samsungtv] Samsung TV UA50MU6100 wired connection, static IP. initially discoverable,can be added as a thing, comes online initially, when issuing a command, log:tail says command not supported, TV goes offline in openhab.

The weird thing is that after adding the TV as a thing, i **don't get a prompt in the TV that open have is trying to access,** hence, openhab is not in the list of external devices controlling the TV.

Environment:

OH 2.4
binding-samsungtv - 2.4.0

==========update-1==========
On initial add-on, the values of volume, mute when changed on tv, reflects on openhab.
on initial command to TV, tv's thing becomes offline_connection_error. further changes on TV won't be reflected on openhab

**Comment by arjanmels** [comment]
I made some fixes, they have been merged into master just yet. You can give the nightly build a try tomorrow or try the jar I uploaded to: [org.openhab.binding.samsungtv-2.5.0-SNAPSHOT.jar](https://drive.google.com/open?id=1BAg5Xs1UtuZi61p5FpXjVJGWV31-HLK8)

**Comment by Cossey** [comment]
@mosh86 Can you check whether or not it is working for you now in the 2.5.0.M2+ builds? @arjanmels and others have done some fixes and got some good progress on Websocket support.

**Comment by mohsh86** [comment]
@Cossey tested now with 2.5.1 and seems working good. Turning off works, but on turning on: i get the following in the logs:


```
12:56:44.012 [WARN ] [gtv.internal.handler.SamsungTvHandler] - Cannot send WOL packet to 192.168.86.9 MAC address unknown
12:56:44.022 [WARN ] [gtv.internal.handler.SamsungTvHandler] - Channel 'samsungtv:tv:e6831ab7_33d2_46bb_b27a_effdfce66b82:power' not supported
```

**Comment by jaywiseman1971** [comment]
Please be aware that there is some fundamental issues with the SamsungTV Binding and jUpNp that is trying to be worked out.

https://github.com/openhab/openhab-addons/issues/5892

Best, Jay

**Comment by hmerk** [comment]
closed due to inactivity
