### ISSUE TITLE
"How to develop in the Eclipse IDE" does not work.

### ISSUE THREAD

**Issue by FischertBilligheim** [openhab/openhab-addons#5572]
The description how to debug/develop a binding does not work on my Windows-10 machine.

I installed the Eclipse-IDE in "advanced-mode" using the "openHAB Add-ons" Project.
With that Installation the descriptions works pretty well - but I have 2 problems:

1) It's not possible to drag-drop my example/test "Serial-button"-binding like described to the "Run-requirements". An error box pops up:

![runRequirements](https://user-images.githubusercontent.com/20623089/57391127-27fb0d00-71be-11e9-968f-c40cf2a38480.PNG)

2) If I start my browser with "http://localhost:8080" - the Access is forbidden….
It seems, that "localhost:8080/paperui/index.html" must be used….. This should be described in the docu…

![OSGI-Console](https://user-images.githubusercontent.com/20623089/57391761-7230be00-71bf-11e9-967a-d5f1bf586f5d.PNG)

**Comment by Gozilla01** [comment]
Start by installing from the latest` latest version (03-2019)`, do not select any additional components.
Then follow the new documentation
https://deploy-preview-968--openhab-docs-preview.netlify.com/docs/developer/#eclipse-ide-setup
@Confectrician The pages of the documentation do not work

**Comment by Confectrician** [comment]
>The pages of the documentation do not work

Can you give some more details which pages areas especially are affected?

**Comment by Gozilla01** [comment]
yesterday the PR was merged with the Eclipse installation update.
If you use the official website of the documentation the web page from loading error. For this I have attached the preview link.
sorry but I'm not in front of the computer

**Comment by FischertBilligheim** [comment]
The preview looks very good - and exactly covers my problems/experiences I had the last days!!!  
This evening, I will test this new description!!
Thanks really a lot for that !!

**Comment by Confectrician** [comment]
Ah now i get it.
Yes there is some trouble with the website build currently.
This may also be the reason for that page not being updated.

**Comment by davidgraeff** [comment]
Please remind me when the website is updated to also update the readme file of this repo. Thanks.

**Comment by FischertBilligheim** [comment]
I tested the new documentation with the link from Gozilla01. 
The creation of the Skeleton-binding Shows an error - on my Windows10-machine (I use the "create_openhab_binding_skeleton.cmd" Batch.
This is the error:

![Skeleton2](https://user-images.githubusercontent.com/20623089/57467985-e5036d00-7283-11e9-95de-a44d2a19674e.PNG)
- The "...\features\karaf.."-Folder does not exist.

**Comment by davidgraeff** [comment]
Yes that was moved. Remove the "karaf" part of the path in the batch file.

**Comment by FischertBilligheim** [comment]
Mmmmh - interesting. :-) 
I currently don't have the "openhab-core" repo mapped on my machine - but it exists in the repository:
"C:\Users\Thomas\.m2\repository\org\openhab\core" - and here the "karaf" Folder exists…...

**Comment by FischertBilligheim** [comment]
I meanwhile created a Karaf-folder in my repo and copied the "openhab-addons" Folder into it.
Now I can generate the Skeleton binding.

Also the "mvn -DskipChecks -DskipTests clean install" worked.
But this new binding cannot be seen in the "app.bndrun" Editor on the left side:"Repositories". 
If I'm adding the new Skeleton-Binding by using a text.editor, the "Resolve" does not work….

**Comment by davidgraeff** [comment]
> I meanwhile created a Karaf-folder in my repo and copied the "openhab-addons" Folder into it.

That might have triggered a redownload of openhab-core. And your other checkout works as well now.

**Comment by mvalla** [comment]
But this new binding cannot be seen in the "app.bndrun" Editor on the left side:"Repositories".

Try to close Eclipse and do a “mvn -DskipChecks -DskipTests clean install“ from the openhab-demo project main folder.
Then open Eclipse and you should now see the new binding listed

I currently don't have the "openhab-core" repo mapped on my machine - but it exists in the repository

That is normal : the whole setup depends also from openhab-core project(s) of course so even if you did not checked it out from git it has been downloaded my maven as a Dependency and put in your local repository

**Comment by procrastimax** [comment]
I still run in the same problem of missing Karaf folder.
I setup everything with the updated Setup-Guide: [https://deploy-preview-968--openhab-docs-preview.netlify.com/docs/developer/#eclipse-ide-setup](url)

This works so far in terms of adding existing bindings.

But when I try to create my own binding with the create_skeleton_...sh script, I get the same mvn error like @FischertBilligheim. But creating a karaf folder and copying the openhab-addon folder into karaf doesnt work, since there is no feature.xml in my openhab-addon folder. (And I also think that this cant be the solution). 
Is there anything else I can try?

**Comment by davidgraeff** [comment]
If you really want to work with your old openhab-core checkout (because the archetype skeleton is fixed in core for sure) you must restore the old directory structure: /features/karaf/openhab-addons/src/main/feature/feature.xml

**Comment by procrastimax** [comment]
Ok ok, no I just started with OpenHab2 dev, so I dont need the old core.
I work with the openhab2 demo from maggu, does this demo uses the old core?

**Comment by davidgraeff** [comment]
Usually not. But it also doesn't update your openhab-core once it has downloaded it. You need to do "mvn -U" on the command line or use the respective Eclipse menu to trigger an update.

If in doubt just copy /features/openhab-addons/src/main/feature/feature.xml -> /features/karaf/openhab-addons/src/main/feature/feature.xml. That modification is not important anyway, since a few days we handle it differently, but that doesn't affect your binding development.

**Comment by procrastimax** [comment]
Creating an empty feature.xml in the karaf directory seems to work.
But not the `mvn ... -U` way.
