### ISSUE TITLE
[modbus][feature] dualbit configuration

### ISSUE THREAD

**Issue by mohsh86** [openhab/openhab-addons#5577]
Similar to some SCADA software, a dual bit modbus data type can be used to indicate the status of a dual contact device, e.g. a device with two contacts to indicates if it is fully open, fully close or traveling.

once specified as a readValueType with say address 10.2, it will consider 10.2 & 10.3.

The corrosponding Item/Thing will be an integer, i.e:

10.3|10.2|thing/item|status|
  0  |   0  |       0        | travel
  0  |   1  |       1        | closed
  1  |   0  |       2        | opened
  1  |   1  |       3        | error

i know this can be done in rules, but it will be neater if it can be done directly from channels/things

**Comment by ssalonen** [comment]
I think you can do this using transformations? Read register address 10 (integer), and extract the relevant bits to conclude actual device state.

**Comment by ssalonen** [comment]
ping @mohsh86

**Comment by mohsh86** [comment]
> ping @mohsh86

i guess you can with javascript? MAP won't work since other bits in the word aren't catered for, RegEx for strings and Json for Json, ideally speaking having it in the binding is more efficient than and easier than calling js transform ? can you pass parameters to JS transform functions?

**Comment by ssalonen** [comment]
Yeah javascript for example.

In the example you would not need parameters, I think. Pass in the whole register (16 bits), extract the relevant bits, and transform it into number.

I understand that you want to avoid "extra" transformations but to me this is quite custom and thus belongs to device specific binding or transformations.

With custom I mean that there are so many permutations (e.g. How many bits as input, what output range to use, consecutive bits or not etc.) depending on your needs.

The upside of transformations is that users learn reusable skills, that can be applied with other bindings and rules.

Efficiency is relative.. I think it should work fine with reasonable polling rates

**Comment by ssalonen** [comment]
Ping @mohsh86

**Comment by ssalonen** [comment]
Ping @mohsh86

**Comment by ssalonen** [comment]
Closing since no further feedback from the user
