### ISSUE TITLE
[rfxcom] binding spin locks with high CPU load  when tcp socket disconnected

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab-addons#5579]
This bug bites in the following situation:

The rfxcomm binding connects via tcp to a remote device that is running ser2net to export a local rfxcomm device. If the socket is closed for whatever reason (in my case a poor setting of the "timeout" value in the ser2net config file), the binding starts running at 100% CPU load.
Here is the offending thread:

```
"Thread-4397" Id=10370 RUNNABLE
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.openhab.binding.rfxcom.internal.connector.RFXComBaseConnector.read(RFXComBaseConnector.java:63)
        at org.openhab.binding.rfxcom.internal.connector.RFXComTcpConnector.read(RFXComTcpConnector.java:100)
        at org.openhab.binding.rfxcom.internal.connector.RFXComStreamReader.run(RFXComStreamReader.java:57)


```
I believe the issue arises from this code in RFXComTcpConnector.java:

```

    @Override
    int read(byte[] buffer, int offset, int length) throws IOException {
        try {
            return super.read(buffer, offset, length);
        } catch (SocketTimeoutException ignore) {
            // ignore this exception, instead return 0 to behave like the serial read
            return 0;
        }
    }

```

Ideally, the binding should try to reestablish the socket. If that is too much hassle, then please at least log a clean error and terminate so users know what's happened.

**Comment by lolodomo** [comment]
Do you mean that in case of the connection is broken, read throws SocketTimeoutException rather than IOException ?

**Comment by berndpfrommer** [comment]
I cannot say what Exception is thrown. I do know that the socket is no longer open (netstat on the remote host does not show any connection), and that it spins indefinitely with the stack trace shown above.
The problem can be reproduced when ser2net is used on the remote end, by setting the timeout value to something low (in my case 600 seconds, but maybe shorter will trigger the issue even faster). When the timeout occurs due to inactivity, ser2net will close the connection on its end.

**Comment by martinvw** [comment]
FTR: https://github.com/openhab/openhab2-addons/pull/2433

@berndpfrommer It looks like the read should at max be retried every 100ms, maybe we can increase this to 250ms? I see no big dangers in that. Can you create such a build for your self?

**Comment by berndpfrommer** [comment]
I have not been able to successfully build openhab for more than a year, so testing would be difficult.
Are you saying that as the code is right now, it should only read() ever 100ms? That would probably not lead to the 100% CPU load that I'm seeing.

**Comment by martinvw** [comment]
> Are you saying that as the code is right now, it should only read() ever 100ms? That would probably not lead to the 100% CPU load that I'm seeing.

Indeed, it could be per bridge (rfxcom adapter) so if you configured them multiple times that could explain.

But to reach the part where the exception is ignored should at least take 100 ms, I can build a version which includes a log statement there, that could help pin-pointing the problem...

**Comment by lolodomo** [comment]
We have many bindings with this pattern, especially the ones I developed.
It would be very cool to clarify the situation.
I am using 2 of my bindings with a IP connection to a ser2net server. I believe I set the timeout to 0 in ser2net.

**Comment by lolodomo** [comment]
Confirmed: my timeouts are set to 0 in ser2net. Could it explain why I don't encounter this problem ?

**Comment by paulianttila** [comment]
Read return -1 when TCP socket is closed (EOF). -1 is not handled, so thread is in busy loop.

Will provide fix soon.

**Comment by lolodomo** [comment]
The reader thread will finish. And then? This will require a restart of the binding?

**Comment by paulianttila** [comment]
> The reader thread will finish. And then? This will require a restart of the binding?

Handler is now informed about EOF and automatic recovery mechanism tries to reconnect as long connection is re-established, so no need for manual binding restart.
