### ISSUE TITLE
[hueemulation] IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#5589]
Just updated to the latest distro 1589.
Directly on startup, I get this in my console:
```
Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.

openhab> Exception in thread "HueEmulation UPNP Server" java.lang.IllegalArgumentException: IPv6 socket cannot join IPv4 multicast group
        at sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:808)
        at sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:894)
        at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:439)
        at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:1)
        at org.openhab.io.hueemulation.internal.upnp.HueEmulationConfigWithRuntime.run(HueEmulationConfigWithRuntime.java:105)
```
Note that I did not even do a `log:tail` here, so this seems to go out to `System.out`...

**Comment by davidgraeff** [comment]
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/upnp/UpnpServer.java#L438

Looking at the code, there is already a case for IPv4 and IPv6, no idea what is misbehaving here.

**Comment by martinvw** [comment]
This also breaks the build for me

**Comment by martinvw** [comment]
@davidgraeff what is the intention of the code, should it bind to both ipv4 and ipv6 or pick one, because my machine is pretty strict in not mixing them in a single channel.

Should we have two or should we pick one as preference?

**Comment by davidgraeff** [comment]
> what is the intention of the code, should it bind to both ipv4 and ipv6 or pick one

It's not exactly for binding. We could just bind to "::" and IPv4 and IPv6 would work. The code is for sending a upnp broadcast message to every interface. And IPv4 has of course a different multicast target IP than IPv6 for upnp.
