### ISSUE TITLE
[hueemulation] Controlling rollershutters (somfy) via Alexa

### ISSUE THREAD

**Issue by hypetsch** [openhab/openhab-addons#5592]
I am trying to control my somfy rollershutters via hueemulation and came across the following issue: As rollershutters are exposed to alexa as dimmable lights Alexa sends commands ON/OFF when fully opening/closing a rollershutter.
ON and OFF seems to be invalid states for rollershutters as they expect UP/DOWN.

Wouldn't it make sense to also accept ON/OFF and map them accordingly (ON=DOWN, OFF=UP) or am I missing something?

...tried to reproduce this behavior manually:

```
20:12:27.493 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'RollerShutterKitchen' received command UP
20:12:27.508 [DEBUG] [ndler.SomfyTahomaRollerShutterHandler] - Received command UP for channel somfytahoma:rollershutter:7271fa8a:04f8b911-96cd-4c85-a72d-215920bd2249:control
20:12:27.547 [INFO ] [arthome.event.ItemStatePredictedEvent] - RollerShutterKitchen predicted to become UP
20:12:27.734 [INFO ] [smarthome.event.ItemStateChangedEvent] - RollerShutterKitchen changed from 100 to 0
20:12:28.003 [DEBUG] [rnal.handler.SomfyTahomaBridgeHandler] - Exec id: a818a2be-d9b6-8679-1fb9-f31bb25704ea
```

```
20:16:55.953 [WARN ] [.rest.core.internal.item.ItemResource] - Received HTTP POST request at 'items/RollerShutterKitchen' with an invalid status value 'ON'.
```

Another thing that came into my mind when looking at the code in the [somfytahoma](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.somfytahoma/src/main/java/org/openhab/binding/somfytahoma/internal/handler/SomfyTahomaRollerShutterHandler.java) binding:
The binding seems to treat OFF the same way as DOWN (and ON as UP). But wouldn't it make more sense to do it the other way round?
tread OFF as UP and ON as DOWN (at least in context of alexa)

## Your Environment
openHAB 2.5.0~S1587-1

**Comment by davidgraeff** [comment]
Hm, because Alexa (https://developer.amazon.com/docs/device-apis/list-of-interfaces.html) and also the Hue protocol doesn't support rollershutters, mapping the state makes sense.

**Comment by hypetsch** [comment]
Only out of interest: Would you do the mapping only on REST level or add the mapping code from UpDownType to OnOffType directly in RollershutterItem to make OnOffType acceptable in general (as far as I understand the openhab implementation)?

**Comment by hmerk** [comment]
closed due to inactivity
