### ISSUE TITLE
Integration test for every bundle

### ISSUE THREAD

**Issue by davidgraeff** [openhab/openhab-addons#5598]
@openhab/2-x-add-ons-maintainers 

I like to discuss the idea of auto-generate integration tests for all existing bundles and
* start up all thing factories,
* start up all discovery services.

And also make an integration test, doing mentioned things, mandatory for new addon PRs (add it to the archetype).

We recently had a few cases where bindings got broken because we had updated dependencies in core. We should make sure that at least all factories and public services of a bundle start up without ClassNotFound and other classloader exceptions.

To make it easier for the archetype and also for my travis-build-bundle-directory-only script we may also think about moving itests into the respective bundle directory.

**Comment by martinvw** [comment]
Sounds like a good idea, a drawback could be the added build time, so we should especially guard that building a single module still works (in an acceptable time)

**Comment by davidgraeff** [comment]
You usually never build the entire repo. Only the distro should do that. I have this workflow in mind:
* Travis/jenkins: A PR that adds a new binding or a PR that touches only a fixed set of bundles (max 2 for /bundles and /itests):
  - Build only those bundles with tests and integration tests and super restrict checks. (~6min)
* Travis: A PR that touches multiple bundles / infrastructure: Build all without checks and tests (~30min)
* Jenkins: A PR that touches multiple bundles / infrastructure or a distro build: Build all with checks and tests and itests (~5 hours)

**Comment by hmerk** [comment]
closed due to inactivity
