### ISSUE TITLE
[exec] Demo code endless loop

### ISSUE THREAD

**Issue by Coernel82** [openhab/openhab-addons#5603]
The demo.rules on https://www.openhab.org/addons/bindings/exec/ results in an endless loop:

```

  while(yourcommand.state != OFF){
         Thread::sleep(500)
      }

```

**Comment by 9037568** [comment]
Did you write that without all of the code that's supposed to go with it?

**Comment by Coernel82** [comment]
No, no! I used the complete set of files (things, items, rules etc.!).
After changing the three lines above to
`Thread::sleep(2000) `
without the loop the demo worked.

I debugged the demo.rules by placing a console-log message at each line to see where the rule stopped.

**Comment by Rossko57** [comment]
See also https://github.com/openhab/openhab2-addons/pull/5669

**Comment by 9037568** [comment]
Closing because this loop no longer exists in the docs.
