### ISSUE TITLE
[amazonechocontrol] Add support for DoorbellPress events

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#5616]
Hi all, 

I send an "alarm" to my echo's when the doorbell is triggered, but the delay of >10sec between the ButtonPressEvent and the actual sound playing is "bad". 

So I stumpled upon this: 
https://developer.amazon.com/de/docs/device-apis/alexa-doorbelleventsource.html

I can not add the necessary coding myself, but I was hoping that this might not be a big of a deal to be added by someone else. 

My hope is that this event is processed with much less delay than the current playAlarmSound. 

I currently have OH 2.4

Thanks!
PhiL

**Comment by mgeramb** [comment]
@wborn This can not be done in the binding. The api is related to the alexa openhab smarthome skill. 
So please close it here.
