### ISSUE TITLE
[philipsair] Add Philips Air Purifier Binding

### ISSUE THREAD

**Issue by justClouds** [openhab/openhab-addons#5618]
I started developing my first binding, now that the build system is getting in shape. It is a binding for the Philips Air Purifier.
I own one device type that I can test myself, but to my understanding all WiFi-enabled Philips Air Purifiers use the same protocol.

Initial version will probably only read the air quality data and filter status, since this is my first binding. But who knows...

**Comment by wborn** [comment]
Maybe you can test if the binding in https://github.com/openhab/openhab2-addons/pull/6543 also works for you @justClouds?

**Comment by hmerk** [comment]
closed due to inactivity
