### ISSUE TITLE
[opensprinkler] Make request timeout configurable

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab-addons#5619]
Hi, 

fist of all: Awsome Binding and thanks for providing it! Salves me from hacking the according http binds, which is always nasty.

The is one tiny point i miss: after what time does the valve close again, if i forget it?

in the API Constants i found: CMD_STATION_ENABLE_TIME = "t=64800" which is 18 Hours and quite a lot for me. I'm pretty aware: this is arguable.

Wouldn't it be great, if i could overwrite this timeout at the Thing? Or Item?

That would help me to sleep a bit better :-)

Best
Michael

**Comment by cweitkamp** [comment]
@FlorianSW something for you?

**Comment by FlorianSW** [comment]
That's funny, this is one of the things I've on my list for the binding and will come in the near future, once https://github.com/openhab/openhab2-addons/pull/5890 is finished :) So, yes, I'll work on this! :)

**Comment by kohlsalem** [comment]
Cool, thanks!
