### ISSUE TITLE
[mihome] Add Jython examples to documentation

### ISSUE THREAD

**Issue by NicoSoftware** [openhab/openhab-addons#5620]
Please update the Xiaomi mihome addon readme:
It's the pattern for everyone who's programming with Jython:
[GitHubXioami - Kopie.txt](https://github.com/openhab/openhab2-addons/files/3195029/GitHubXioami.-.Kopie.txt)
Thanks!

**Comment by Confectrician** [comment]
Hey @NicoSoftware,

Would you like to propose the change yourself?
It seems that you have prepared everything already. 🙂

You can find the correct file here:
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mihome/README.md

BR
Jerome

**Comment by NicoSoftware** [comment]
Hey,
of course!
I did a file update, but did it work?

**Comment by wborn** [comment]
I see your changes in your patch-2 branch. :-) 

You can now create a "pull request" for requesting the changes from your branch to be merged into the openHAB master branch:

https://github.com/openhab/openhab2-addons/compare/master...NicoSoftware:patch-2?expand=1

**Comment by hmerk** [comment]
closed due to inactivity
