### ISSUE TITLE
[onkyo] Binding not connecting to receiver after restart

### ISSUE THREAD

**Issue by dbghb** [openhab/openhab-addons#5629]
After a reboot of the server or a restart of openHAB the Onkyo binding shows the receiver as "online", but does not react to any commands. 

Maybe related to #2482, but this is already closed. 

## Expected Behavior

./.

## Current Behavior

./.

## Possible Solution

Currently I cannot think of another solution than to scan the code for possible timing issues. See "Context" below for reasons.

## Steps to Reproduce (for Bugs)

./.

## Context

This did not (or maybe very rarely) occur while I used a Raspberry 3. Now that I switched to a much faster ODROID N2 it happens almost every time. 

After taking the receiver off the power line for a couple of seconds plugging it in again, the binding correctly connects to the receiver after a while again.

It looks to me pretty much like a timing problem or race condition, as it did not happen on the slower RPI and it also does not occur (I did not try too often though) when I switch on trace logging for the Onkyo binding. Which is sort of a worst case for debugging purposes I'm afraid.

## Your Environment

ODROID N2, Ubuntu, Linux odroid 4.9.177-28 #1 SMP PREEMPT Thu May 16 23:10:54 -03 2019 aarch64 aarch64 aarch64 GNU/Linux

Onkyo TX-NR616 

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by dbghb** [comment]
Did some more investigation. It now seems to me that it is really more like [https://github.com/openhab/openhab2-addons/issues/2482](url) as mentioned above. 

But the thing that strikes me is that it did not happen regularly on the RPI. 

Meanwhile I have a trace log of a restart that left me with a disconnected device. It shows the effect that was mentioned in the aforementioned older issue, see the excerpt here:

2019-05-23 16:53:46.381 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Test connection to tx-nr616:60128
2019-05-23 16:53:46.395 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Send command: [command=PWR, value=QSTN] to tx-nr616:60128 (Socket[addr=tx-nr616/192.168.178.49,port=60128,localport=43540])
2019-05-23 16:53:46.397 [TRACE] [g.onkyo.internal.eiscp.EiscpProtocol] - Created eISCP message: 49534350000000100000000A0100000021315057525153544E0D -> ISCP[00][00][00][10][00][00][00][LF][01][00][00][00]!1PWRQSTN[CR]
2019-05-23 16:53:46.398 [TRACE] [nding.onkyo.internal.OnkyoConnection] - Sending 26 bytes: 49534350000000100000000A0100000021315057525153544E0D
**2019-05-23 16:53:56.484 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - No data received during supervision interval (70000 ms)!**
2019-05-23 16:53:56.496 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Reconnecting...
2019-05-23 16:53:56.516 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Connected to tx-nr616:60128
2019-05-23 16:53:56.529 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Test connection to tx-nr616:60128
2019-05-23 16:53:56.533 [DEBUG] [nding.onkyo.internal.OnkyoConnection] - Send command: [command=PWR, value=QSTN] to tx-nr616:60128 (Socket[addr=tx-nr616/192.168.178.49,port=60128,localport=43854])
2019-05-23 16:53:56.539 [TRACE] [g.onkyo.internal.eiscp.EiscpProtocol] - Created eISCP message: 49534350000000100000000A0100000021315057525153544E0D -> ISCP[00][00][00][10][00][00][00][LF][01][00][00][00]!1PWRQSTN[CR]
2019-05-23 16:53:56.544 [TRACE] [nding.onkyo.internal.OnkyoConnection] - Sending 26 bytes: 49534350000000100000000A0100000021315057525153544E0D
2019-05-23 16:53:56.547 [TRACE] [nding.onkyo.internal.OnkyoConnection] - Waiting status messages

**Comment by Cossey** [comment]
I have a _TX-NR686_ which is only last years model and connected via ethernet and sometimes the network component of it would crash (usually when I would play something via AirPlay and my phone would go flat).

Once crashed it doesn't respond to anything over the network (AirPlay, Chromecast, Onkyo Controller and using the Net Radio stations would not work). While the device shows up, when connecting it does nothing and the only way to resolve is a hard power off as turning off the device to standby does not reset this process. Unfortunately these devices just aren't too stable on the network end of things.

Looking at the firmware updates of the TX-NR616 model I can see three possible updates that may improve stability but I will assume that you've updated your device to version `1171-7110-0500` so you're likely out of luck with a firmware fix.

The binding does what it should, reconnect when it does not receive a reply; I think the way in which the firmware/device is crashes means that it can still open a connection to the receiver, but the receiver sends no data (which matches what I experience with AirPlay/Chromecast when my receiver crashes). The only thing I can think of to work around this is possibly having a counter when reconnecting to see if it occurs _X_ times without receiving data and then mark it as offline/off.

This does not explain however why it crashes with your new hardware - but I think it must get hit with too many requests all at once that it cannot handle.

**Comment by Cossey** [comment]
@dbghb are you still having this problem? I would like to close this issue due to inactivity.

**Comment by dbghb** [comment]
I currently have the workaround that I do the switch on/off actions for the device using the Logitech Harmony binding. I did not check again now but I would swear that the problem still exists if nothing was done about it.

**Comment by Cossey** [comment]
Curious - did you try the workaround mentioned on that referenced issue? Regarding the Album Art and Album Art URL channels, if they're enabled/selected you may want to remove them/comment out the items. Maybe also do the same to other channels in the binding you are not using to see if that reduces the problem. 

Again they're not really the likely culprit as its probably the unstable networking in the firmware. I wonder if its possible to downgrade the firmware on the problem receivers, maybe an older version is more stable?

**Comment by dbghb** [comment]
Actually I don't remember whether I tried that workaround :-) Getting older... Close the issue if you like as I don't think it makes much sense to provide a solution for a 5(?) year old device. I can live with my current workaround, controlling some functions via IR.

But thanks for bringing this up again. I really appreciate all of the work you guys are doing.

**Comment by dbghb** [comment]
Sorry, did not want to close it on my own.

**Comment by Cossey** [comment]
Closing due to device firmware instability. 

For those who land here in the future, try the following workarounds:
* Ensure that `albumArt` and `albumArtUrl` channels are not subscribed to (comment out chennels/un-check in Paper UI)
* Upgrade or downgrade Onkyo Receiver to a different firmware version
* Other suggestions in PR #2482
