### ISSUE TITLE
[homekit] Could not initialize homekit: Address already in use

### ISSUE THREAD

**Issue by Johannp02180** [openhab/openhab-addons#5635]
Hi,

I'm using openhab 2.4 and I keep getting this error when trying to start openhab and using homekit. 

Could not initialize homekit: Address already in use (Bind failed)
java.net.BindException: Address already in use (Bind failed)

**Comment by J-N-K** [comment]
Today I raised a PR that (among other things) fixes an issue that might have caused such a problem. However, the new version requires OH>2.5.

**Comment by wborn** [comment]
Can you test if this is still an issue in openHAB 2.5.0-SNAPSHOT build #​1600 (or newer) @Johannp02180?
It contains the fixes of #5637 by @J-N-K.

**Comment by Johannp02180** [comment]
Hi @wborn I just tried the snapshot that contains fixes from @J-N-K but now I get this error:

2019-05-25 13:50:46.104 [ERROR] [org.openhab.io.homekit              ] - bundle org.openhab.io.homekit:2.5.0.201905250651 (229)[org.openhab.io.homekit.internal.HomekitImpl(240)] :  Error during instantiation of the implementation object
java.lang.reflect.InvocationTargetException: null

**Comment by Johannp02180** [comment]
Also now my binding in my addons folder don't add.

**Comment by J-N-K** [comment]
How did you upgrade? Please check if this is still the case with a recent version of OH (i.e. 2.5 SNAPSHOT >= 1601).

**Comment by J-N-K** [comment]
Closing as probably fixed. WFM and no further report.
