### ISSUE TITLE
[enocean] Eltako FTK (window contact) stop working

### ISSUE THREAD

**Issue by ollikasp** [openhab/openhab-addons#5636]
## Expected Behavior

Eltako FTK (window contact) should report open/close state.

## Current Behavior

When I add an Eltako FTK device to openHAB, it works fine for a while. After a while (probably after a restart of openHAB) it will not report changes of the state anymore. I have to delete the thing, start the discovery process of the enocean binding and to include it again. After that, it works fine again for some time.
I use four Eltako FTK devices and the problem occurs with every one of them. It used to work with an previous version of openHAB or the binding (I do not really remember, when the problem started) and I do not have any problems with other enocean devices (I have many of them installed).

## Your Environment

* Version used: openHAB 2.4.0 release build, corresponding enocean binding (added via PaperUI)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): latest openhabian

**Comment by ollikasp** [comment]
This problem occurs after a short while (a couple of minutes, maybe one hour) after creating a new thing. A restart of openHAB is not necessary. After adding the thing, it works perfectly for a little while. Then, suddenly, no changes are reported anymore. I have to delete the thing, start the recovery process, and add the window contact again for it to work again for just a little while.

**Comment by J-N-K** [comment]
Anything in the logs when it stops to work? Please turn on trace or at least debug logging. No way to fix this without logs or hardware.

**Comment by fruggy83** [comment]
Do you see any exception in the log when this happens? Can you switch to snapshot? Maybe this bug is already fixed by #4581.

**Comment by hmerk** [comment]
closed due to inactivity
