### ISSUE TITLE
[allplay] native code missing

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#5643]
The Allplay binding uses an external library that is embedded in the /lib-folder. Additionally there are native-code libraries unser /src/main/resources. With our current configuration these are embedded but not properly declared by the bundle, this needs extra-bnd-instructions.

A solution is proposed in the latest additions to #5503.

Without a solution the binding is broken, therefore marking it as critical.

**Comment by openhab-5iver** [comment]
@J-N-K , should this be closed after the merge of #5503?
