### ISSUE TITLE
[gardena] Configurable URL

### ISSUE THREAD

**Issue by SciLor** [openhab/openhab-addons#5658]
It would be nice to have the api url configurable, as I am currently working on a project to replace the cloud with a local script running on the gateway.

https://github.com/openhab/openhab2-addons/blob/317cbb58a0273445548b479b8cf1b5c2ec9cbf2b/bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java#L108

**Comment by kaikreuzer** [comment]
@SciLor Sounds cool, do you have some more details on it? Is it a script running on the local Gardena gateway? How can you deploy anything there?

@gerrieg Should be simple to make the url a (advanced) configuration option, right?

**Comment by SciLor** [comment]
It is a python script which can run on the gateway. Rooting still needs hardware access
https://github.com/gardena-smart-reverse-engineering/deGardenServer/tree/develop

**Comment by kaikreuzer** [comment]
Wow, pretty cool, thanks, @SciLor!

**Comment by hmerk** [comment]
closed due to inactivity
