### ISSUE TITLE
[homematic] CUL switch changes do not trigger events

### ISSUE THREAD

**Issue by lobocobra** [openhab/openhab-addons#5661]
Issue summary
CUL receives data from my 433mhz remote and is able to change the status of a switch within the CCU2, BUT the event is not sent to openhab. I refer to the same issue here:
**https://github.com/openhab/openhab1-addons/issues/4109**
=> so after 3 days of searching, I assume it is a binding issue of the [homematic bridge]

## Expected Behavior
I would like that the bridge captures the changed switch within homematic CCU2 and sends it to openhab. 

## Current Behavior
Currently the homematic ccu2 switch can be switched by the remote, but no event is sent to openhab.

## Possible Solution
I have no idea, currently I need to have a script in the ccu2, which is triggering a regular switch (not created by cul). This was the remote triggers cul, cul triggers ccu2 switch, the script then triggers a regular ccu2 switch, which then sends a command to openhab.

## Steps to Reproduce (for Bugs)
1) install cull with firmware to read 433mhz protocol
2) in the cul create a generic switch, which sends the command to ccu2
3) in the ccu2 configure the switch and test it (it works when the remote it pushed)
4) in openhab open the event log and you will see that neither manual trigger nor the remote, triggers an event in openhab.

## Context
I want to use 433mhz switches to trigger events in openhab (they are cheap)

## Your Environment
Latest stable openhab running on debian on a VMM on a synology. All works well and stable, but while I am able to receive 433mhz commands, openhab is ignoring them.

**Comment by hmerk** [comment]
closed due to inactivity
