### ISSUE TITLE
[mihome] Add support for Aqara Wireless Relay (2 channel)

### ISSUE THREAD

**Issue by pavelvarganov** [openhab/openhab-addons#5662]
Please, add support for Xiaomi Aqara Wireless Relay LLKZMK11LM.

**Comment by pavelvarganov** [comment]
i tryed send command `"\"channel_0\":\"on\""` to Relay as basic device ( to channel mihome:basic:7c49eb1a5b44:158d00033e5b10:writeMessage )
in log i see:

`15:51:48.450 [DEBUG] [.internal.handler.XiaomiBridgeHandler] - Send to bridge mihome:bridge:7c49eb1a5b44: {"cmd": "write", "sid": "158d00033e5b10", "data": "{"channel_0":"on", \"key\": \"sfsefsefsefsefsefsefsefsefsfsfse\"}"}
15:51:48.452 [TRACE] [g.mihome.internal.socket.XiaomiSocket] - Sending message: {"cmd": "write", "sid": "158d00033e5b10", "data": "{"channel_0":"on", \"key\": \"sfsfsefesfsefsefsefsefsefsefsefse\"}"} to /10.1.2.52:9898
15:51:48.858 [DEBUG] [g.mihome.internal.socket.XiaomiSocket] - Received Datagram from 10.1.2.52:9898 on Port 9898
15:51:48.859 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Received message {"cmd":"write_ack","sid":"158d00033e5b10","data":"{\"error\":\"Unsupported device\"}"}
15:51:48.860 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d00033e5b10
15:51:48.863 [DEBUG] [.internal.handler.XiaomiBridgeHandler] - Device 158d00033e5b10 honored write request
15:51:48.866 [DEBUG] [ernal.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"write_ack","sid":"158d00033e5b10","data":"{\"error\":\"Unsupported device\"}"}`

What am I doing wrong?

**Comment by pavel-gololobov** [comment]
Do you update Hub firmware to latest version? Looks like this new device is unsupported by Hub.

**Comment by pavelvarganov** [comment]
Hub firmware is up to date.
Relay is fully functional from “Mi Home” app.

**Comment by pavelvarganov** [comment]
Hub identity relay’s model as lumi.relay.c2acn01
https://www.dropbox.com/s/mw44nxb2q1inmge/IMG_0257.PNG?dl=0

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by engelh** [comment]
Please add support for Xiaomi Aqara Wireless Relay LLKZMK11LM.
Or knows someone what to send to the relay drive
The command `"\" channel_0 \ ": \" on \ "" `does not work ?

**Comment by pavelvarganov** [comment]
in openhab i see new value from relay` "inuse":"2" `and channel 2 of relay realy on.
Today Hub firmware is updated to new version

**Comment by pavelvarganov** [comment]
Today the hub received a new firmware.
Relay continues to respond "Unsupported device"

**Comment by Toph92** [comment]
Please add support for Xiaomi Aqara Wireless Relay LLKZMK11LM :)

**Comment by jemaier** [comment]
Hi, as I have such a relay, too I would like to switch it from openhab.
Please add support :)

**Comment by Toph92** [comment]
Hi,
[Zigbee2mqtt](https://Zigbee2mqtt.io) and [Node Red](https://nodered.org/)  do the job for this device and much more [devices](https://www.zigbee2mqtt.io/information/supported_devices.html).
I'm uninstall openhab.

**Comment by VageR1981** [comment]
Please add support for Xiaomi Aqara Wireless Relay. Model: lumi.relay.c2acn01

**Comment by pavelvarganov** [comment]
Gateway FW updated to 1.4.1_175.0220
After update relay send heartbeat and action messages to openhab
`15:50:33.708 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"on\"}"}
15:50:33.710 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d00033e5b10
15:50:33.714 [DEBUG] [ernal.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"on\"}"}
15:50:33.716 [DEBUG] [ernal.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"on\"}"}
15:50:33.719 [TRACE] [g.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners
15:50:33.724 [TRACE] [g.mihome.internal.socket.XiaomiSocket] - Thread Thread[Thread-63,5,main] waiting for data on port 9898
15:50:39.585 [DEBUG] [g.mihome.internal.socket.XiaomiSocket] - Received Datagram from 10.1.2.52:4321 on Port 9898
15:50:39.587 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Received message {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"off\"}"}
15:50:39.589 [TRACE] [.internal.handler.XiaomiBridgeHandler] - Updated "last time seen" for device 158d00033e5b10
15:50:39.590 [DEBUG] [ernal.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"off\"}"}
15:50:39.593 [DEBUG] [ernal.handler.XiaomiDeviceBaseHandler] - Item got update: {"cmd":"report","model":"","sid":"158d00033e5b10","short_id":12100,"data":"{\"channel_0\":\"off\"}"}
15:50:39.594 [TRACE] [g.mihome.internal.socket.XiaomiSocket] - Data received and notified 1 listeners`

**Comment by pavelvarganov** [comment]
Fully worked if set relay as "Xiaomi "zero-fire" 2 Channel Wall Switch"

**Comment by xawme88** [comment]
Please, add support for Xiaomi Aqara Wireless Relay LLKZMK11LM.

**Comment by kkmaslowski** [comment]
> Fully worked if set relay as "Xiaomi "zero-fire" 2 Channel Wall Switch" (ctrl_ln2)
Confirmed. I can switch on/off. No power usage or other features.

**Comment by hmerk** [comment]
closed due to inactivity
