### ISSUE TITLE
[homematic] HMW-IO-12-Sw14-DR output channel 7 has no "state" and "value" channels in digital mode

### ISSUE THREAD

**Issue by real-easy** [openhab/openhab-addons#5672]
hello,

i think output-cannel 7 on the  HMW-IO-12-Sw14-DR is not fully programmed.
(it is the first output at this module)

in homematic i configured all cannel-parameters as digital-outputs.

in paper-ui i can see the "value" and the "state" but only for output-cannels 8-14

but the output channel 7 shows me only the "frequency". (for analog mode)
there is no "state" an no "value". (for digital mode)

so it is not possible to send an ON or an OFF to this output.

thanks & best regards 
easy

**Comment by hmerk** [comment]
closed due to inactivity
