### ISSUE TITLE
[homematic] variable from CCU2 not updating in panel after refresh command in OH2 console // referring to issue #2333 #2755

### ISSUE THREAD

**Issue by lobocobra** [openhab/openhab-addons#5675]
Expected Behavior
If I delete and add scripts from homematic CCU2, I would like to have them in Openhab updated.

Current Behavior
Existing variables are updated, but if I add new scripts or delete them, Openhab is not updated.
Also not if
- you do a refresh on any of the items
- restart Openhab
- delete all items and all things and reload the binding
- delete all items manually from JSON DB and reload the binding

Context
I have in the CCU2 variables and scripts. They are updated, but once you delete a script or you add a new one Openhab is not updating them.

Your Environment
CCU2 with latest stable firmware 
Latest Openhab2.4 stable version.
Latest Broweser (differnt types) have all the same behaviour.
Debian on Synology VMM (I have no issues with Openhab since 2 years due to that)

I hope you can point me to a solution.

**Comment by lobocobra** [comment]
I have now a work-around.
- delete the things in UI
- delete the items in UI
- delete the CCU2 binding
- reinstall CCU2 binding
- stop Openhab
- delete the items in JSON (as there were still in the things link file)
- start Openhab
- redo the old links from the things to the items
=> Now the scripts are updated

While this works it is a bit long to do. Does anyone else see that behavior?

**Comment by hmerk** [comment]
closed due to inactivity
