### ISSUE TITLE
[rfxcom] Chacon Dio 54754 as Rollershutter does not work

### ISSUE THREAD

**Issue by fgouland** [openhab/openhab-addons#5681]
Hello,
I think there is an issue with Chacon Dio 54754 which I want to use as a true Rollershutter item.

My device works fine when I configure it as a switch (channel: command) item but no RFXCOM command is sent when I use is as Rollershutter (channel:shutter) item.
The problem is perhaps with Rollershutter because when I define my device as Rollershutter (channel:command), it doesn't work.

I use binding-rfxcom - 2.4.0 with openHAB 2.4.0 Release Build.
I am a newbie with OH but long time IT professionnal I am ready to spend time to solve this issue.

Thank you in advance
Regards

**Comment by martinvw** [comment]
I suppose you configured it as an Curtain_1 device? 

The code already gives some hint, it seems to only accept out-going commands when its configured as command and only incoming commands when its configured as a Shutter, so I think that that causes the problem. Feel free to open a PR when you figured it out :-)

**Comment by fgouland** [comment]
Config that doesn't work :
Rollershutter VoletsChambreParents "Volets Chambre parents" {channel="rfxcom:lighting2:rfxtrx0:AcVoletRoulantChambre:shutter"}

Config that "works" :
Switch VoletsChambreParents "Volets Chambre parents" {channel="rfxcom:lighting2:rfxtrx0:AcVoletRoulantChambre:command"}

I don't know where to look for the code but it seems strange that the shutter is configured as incoming. The device itself waits for commands from my rfxcom. It is not so diffrent than a simple on/off Chacon switch, which accepts out-going commands.

I'll try to look for the code...
Thank you

**Comment by martinvw** [comment]
For lighting2 shutters are not supported, maybe you could check whether dimmingLevel works as expected, but I doubt it. 

Its for binding developers always hard to map the scala of hardware to internal openHAB concepts, especially this cases shows it. The developer of the RFXCOM product called it lighting2, we implemented it for light, but it seems that you use it to control rollershutters.

**Comment by martinvw** [comment]
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting2Message.java

https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.rfxcom/src/main/resources/ESH-INF/thing/lighting2.xml

**Comment by fgouland** [comment]
The Chacon Dio 54754 is sold as a shutter command. It is supposed to receive command from a remote but, we, as good hackers, cannot always do as the maker planned ;-)
I've not tried yet but it must be possible to open and close shutters by sending "on" and "off" commands from a script. More difficult to stop the engine when partialy opened !
I think dimming level can not be easyly implemented, if possible ! The behaviour of the 54754 is the following :
"on" command : one relay activated during 15 seconds (if I remember well). If a second "on" command during the 15 seconds : the relay switches off and the shutter stops.
Same process for "off" command, to start the other engine action.
The second "on" or "off" command implements the "stop" command.
As the device is not readable, the stop command, if sent too late, turns the relay on again. Actually, it is not really an issue as a manual switch keeps the engine command on all the time.
The process is to implement the "stop" command as the last command sent to the device.

Now, I'll dive into the code...
Bye !

**Comment by hmerk** [comment]
closed due to inactivity
