### ISSUE TITLE
[deconz] Initial WEBsocket events not coming through since 2.05.65

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-addons#5691]
After upgrading to:
![image](https://user-images.githubusercontent.com/28068256/58910634-4fd68580-8716-11e9-9b4f-f4ff52930965.png)
I noticed the following change in behavior. (I'm on M1 release)

I have several Mi Cubes. After the deconz update, both gesture and rotation was Offline.
I now need to handle each cube and then restart deconz in order for them to come Online in PaperUI. 2.05.64 did not behave this way.
After this initial 'kick' all works as before.

**Comment by cweitkamp** [comment]
@olemr Is this still an issue for you? Did you update deCONZ or / and openHAB in the meantime?

**Comment by olemr** [comment]
Yes, I'm on deconz 2.05.67 and OH2 M3 and it is still an issue.
If a switch, Cube or HUE-1 is flagged as Offline in PaperUI, events don't come through, but REST API is updated. (That's why I think it is WEBsocket related).
When restarting deconz, the last button event I tried while offline comes through in the OH2 log.
Weird.

**Comment by cweitkamp** [comment]
@olemr Thanks for your feedback. I did some research and pushed a fix for it. It will fix #5534 too.

**Comment by olemr** [comment]
Nice! Where/when can I pick it up for testing?

**Comment by cweitkamp** [comment]
I linked a test version in the [pull request](https://github.com/openhab/openhab2-addons/issues/6118).

**Comment by olemr** [comment]
Just loaded the .jar and restarted OH2.
All remotes online without restarting deconz! Nice work. Thank you.

**Comment by olemr2** [comment]
Did the fix make it to M4?
My initial test indicates that it did not?
It also seemed that the SNAPSHOT test version had issues on M4.
