### ISSUE TITLE
[knx] Some channel descriptions are missing or unclear

### ISSUE THREAD

**Issue by 1896FCZ** [openhab/openhab-addons#5711]
Unclear Descriptions for KNX in OpenHAB Paper UI when adding a Channel to a KNX Thing.

Version: OpenHAB 2.4.0 Stable
Binding Version: binding-knx - 2.4.0

Related conversation in KNX Forum: 
https://community.openhab.org/t/oh2-paper-ui-configuration-of-things-for-knx-what-is-the-channel-id/76058

## Expected Behavior
If Adding a new Channel to a KNX Thing, then you would expect a clear description of what the fields mean and what's required to enter.

## Current Behavior
Currently the following fields with the following description will be shown:

Channel Type
Description: Non - n/a

Channel ID
Description: Non - n/a

Label
Description: Non - n/a

Address
Description: The group address(es) in Group Address Notation

## Possible Solution
Describe the field that require to enter values. Proposal:

Channel Type
Description: Select the type of Channel you like to add to the Thing

Channel ID
Description: Enter a by you selected unique Channel ID to the Channel. Note: The Channel ID must be unique.

Label
Description: Enter a by you selected Label for the Channel

Address
Description: “The group address(es) in Group Address Notation. Note: The format to be entered is X.X.XX (1.1.0) and not like in ETS 1/1/0) If you enter more than one group address, enter the addresses as the following example: XXXXXXXXXXXXX<don't know how this needs to look like>XXXXX”

**Comment by davidgraeff** [comment]
Hey :)
You might help out here, by providing the fix as a pull request if you like to. You can do that here in Github even. Just navigate to /bundles/...knx.../src/java/main/resources/.../find-correct-xml-file.xml and edit from within your browser. Github will create a pull request out of your changes.

**Comment by fxpde** [comment]
The descriptions have been added and the UI in OH3 shows proper guidance now. Thus, I think this issue can be closed.

**Comment by hmerk** [comment]
closed due to inactivity
