### ISSUE TITLE
[buienradar] binding only reports 23 of the 24 available forecast values

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-addons#5718]
Although the binding correctly processes the 24 forecast values reported by the Buienradar web API, only 23 are propagated to OH.

Version: openHAB 2.5.0 Build #1601

Also the documentation states that there are 25 values available (current + 24 forecast), which is not possible.

I suppose there is an off-by-5-minutes bug in the binding.

See https://community.openhab.org/t/buienradar-binding/74954/12

**Comment by shutterfreak** [comment]
It seems to have resolved itself, thanks to a nonzero forecast value.

**Comment by wborn** [comment]
Maybe @gedejong can have a look at this issue? 

There are also some other [Buienradar Binding issues](https://github.com/openhab/openhab2-addons/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+buienradar) you might want to look into.

**Comment by gedejong** [comment]
Whoops, thank you for the posted issues. I’ll look into it as soon as I have time this week.

**Comment by gedejong** [comment]
I'm currently working on the buienradar issues. Where do I indicate that this is in progress?

**Comment by wborn** [comment]
We can assign them to you if you're working on them. :+1: 
Do you work on all 5 of them? :-)

**Comment by wborn** [comment]
Looks like you're not yet part of the [contributors team](https://github.com/orgs/openhab/teams/contributors). Maybe @kaikreuzer or @digitaldan can add you to it? After that you can be assigned to those issues. You can also then self assign yourself to them.

**Comment by gedejong** [comment]
Thanks, would be great.

**Comment by kaikreuzer** [comment]
Done!

**Comment by gedejong** [comment]
Alright, the issues were rather related to each other, so I decided to work it all into one commit. In CI at the moment...

**Comment by gedejong** [comment]
@shutterfreak thanks for the bug reports. Currently waiting for CI and CR. If you like, you can already checkout the PR and test it on your machine.
