### ISSUE TITLE
[buienradar] Expose timestamp of retrieval (or first prediction) as channel

### ISSUE THREAD

**Issue by shutterfreak** [openhab/openhab-addons#5723]
The buienradar binding exposes all 24 rain forecast values to OH but it doesn't yet expose the time of retrieval or the time of the first prediction (2nd parameter on the 1st line returned by the buienradar web API). This information can be relevant for tracking when a forecast update was performed, e.g., in a sitemap or in a rule.

**Comment by shutterfreak** [comment]
There might be another good reason for exposing the timestamp of retrieval (or of first prediction), see https://community.openhab.org/t/timer-rescheduling-exception-unable-to-store-job-xxx-because-one-already-exists-with-this-identification/76377

**Comment by justClouds** [comment]
Would be a nice addition, indeed. If the binding creator (@gedejong Edwin de Jong) doesn't want to maintain it or has no time, I can have a look at it.
