### ISSUE TITLE
[astro] Update Astro binding to use local country data for calculating seasons

### ISSUE THREAD

**Issue by lukiep** [openhab/openhab-addons#5732]
## Your Environment

* Version used: OpenHAB 2.4 stable
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): openHABian v1.4.1-468

Apparently season start and end dates are not consistently applied between countries. Some countries commence their seasons on the equinox or solstice (which may be the current Astro binding behaviour) however this differs between countries. In Australia the following is true:
Spring starts 1st September
Summer starts 1st December
Autumn starts 1st March
Winter starts 1st June 

Potential solutions include using location data to set the correct season behaviour or (if this is too complex due to the huge variance in how seasons are recorded) alternatively allow the user to set it themselves in the binding. I'm sure there are other options also.

Associated links:
https://github.com/eclipse/smarthome/issues/4767#issuecomment-501120686
https://community.openhab.org/t/oh2-astro-binding-feature-request-seasons-in-australia/37367/4

**Comment by idkpmiller** [comment]
New Zealand also uses the same dates as Australia. And I would support the ability to specify dates chosen locally rather than ones calculated through astro entitys. Nether seem to be 100% accurate as nature is not predictable to such a degree. So neither method can be consider right or wrong but we should accommodate both.

Regards
Paul

**Comment by cods69** [comment]
I would be happy for two items to come out of this change, one solar based as it is now, as well as calendar based season.  That would be the ideal scenario.

**Comment by clinique** [comment]
This PR follows discussion initiated with @Hilbrand in this [topic](https://github.com/eclipse-archived/smarthome/issues/4767#issuecomment-501120686)
