### ISSUE TITLE
Netatmo Binding issue since a few days....Thermostat-Things r ONLINE, but no values 4 "setpoint" and "currenttemperature"

### ISSUE THREAD

**Issue by uccwhity** [openhab/openhab-addons#5733]
## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by clinique** [comment]
Do you have any error in logs ?

**Comment by clinique** [comment]
The problem seem to have disappear by itself. No more errors in logs and data seem to be flying normally. I think we faced a server side modification of the API followed by a rollback.
