### ISSUE TITLE
[gardena] "ambient_temperature" missing as item

### ISSUE THREAD

**Issue by birnstingl** [openhab/openhab-addons#5748]
ambient_temperature/temperature are missing items - would be great to have them in the binding

**Comment by wborn** [comment]
For which Thing Type are you missing this channel?

According to the [Gardena Thing Types](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.gardena/src/main/resources/ESH-INF/thing/thing-types.xml) the `sensor` and `watering_computer` types should have a `ambient_temperature` channel group with `temperature` and `frost_warning` channels.

If these channels were added after you created your Things, it may help to recreate them so the channels are updated.

**Comment by KleemannT** [comment]
Today I installed a fresh system (openHAB 2.5, RPi 3+) and added the actual Gardena Binding.
All device from my Gardena account were detected, but most of the channels are missing!

Is this a known problem and is there a solution for it?
