### ISSUE TITLE
[transform profiles] channel profiles only support String types

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#5750]
Profiles allow for manipulation of values in between Items and binding channels.
Transform profiles allow user-defined manipulations e.g. numeric SCALE or arbitrary javascript JS.

Unfortunately, transform "output" is in string form.
Those bindings that support "upstream" transforms (i.e between binding and channel) allow the user to output from a JS transform into a number channel, presumably carrying out some parsing somewhere.
But when used as a profile, attempts to route transform (string) output to a Number type Item are silently rejected.

This really a restatement of [#4995](https://github.com/openhab/openhab2-addons/issues/4995) which was closed "won't fix", expanding it to include JS, and calling it an enhancement request.

It seems to me that an enhancement allowing transform profiles to feed Number and Number:UoM Items would be a useful enhancement.
For those bindings not directly supporting transforms, the uses of SCALE for e.g. sensor readings are obvious.  The greater flexibility of JS would allow parsing of numeric values from text, translation of units to OH standards e.g. "99 kilowatts" to "99 | kW", and even adding units where known but not sent in the data.
Equivalent functionality to postUpdate?

Unrelated issue really, but a means of logging transform profile errors would be an advantage.

**Comment by Rossko57** [comment]
Another use case - transform profile for incoming whatever to a Contact type Item.   
https://community.openhab.org/t/cant-use-homematic-tilt-sensor-hm-sec-tis-as-contact-item/76729

**Comment by Rossko57** [comment]
I do not understand why the earlier (SCALE) issue was closed, but it reads like there is some fundamental difficulty in doing the parse e.g. string->decimal between profile and Item state.  Seems odd in my ignorance when e.g. rules `postUpdate(numberItem, "string")` manages it.

Suggestion:  if **chaining** transforms in profiles were allowed, could a new profile type(s) be added for parsing e.g.
[profile="transform:JS", function="<filename>", sourceFormat="<valueFormat>"  ∩ "parseNumber"]

**Comment by shorty707** [comment]
Sadly this is still open. Not a very common problem.?

**Comment by Rossko57** [comment]
Comes up once a week.  Are you volunteering to fix it?  I don't know what is involved.
example
https://community.openhab.org/t/why-transformation-doesnt-work-in-my-case/67403/11

**Comment by Dirk68** [comment]
I fully support the idea of supporting numeric types in JavaScript Transformations in profiles, see [this issue](https://community.openhab.org/t/number-item-javascript-transformation-in-profile/100205) for details.

**Comment by Rossko57** [comment]
Closing this issue, as a new one created in more appropriate core category
https://github.com/openhab/openhab-core/issues/1565
