### ISSUE TITLE
[miio] Additional sensors and information in zhimi.airpurifier.v7

### ISSUE THREAD

**Issue by kovaga** [openhab/openhab-addons#5760]
Just a quick observation about the Mi AirPurifier Pro
There are additional sensors available in Air Purifier Pro that are missing from the current channels and some channels behave differently from how they are described in the manual

Missing - this data is available if requested directly from the purifier via ./miiocli
++++++
Motor 2 speed: 799 rpm
Sound volume: 100 %
Filter type: FilterType.Regular

Not supported - this data is not reported by the device, i.e. not supported
++++++
:usedhours         Use time: None s
:purifyvolume     Purify volume: None m³
:bright                 LED Brightness: None
:buzz                    Buzzer: None

Icorrectly described - Behaves differently from the description.
++++++
:bright    The value reports the Illuminance via the sensor at the top of the device.

:mode supported ( only this three modes are supported auto=Auto, silent=Silent, favorite=Manual)
:favoritelevel    (takes value from 1 to 17)

**Comment by marcelrv** [comment]
Can you find out what are the properties for the missing data, than we can make a specific database file for the `zhimi.airpurifier.v7 `

**Comment by kovaga** [comment]
what kind of properties are you looking for?
can you give an example so i know what to look for pls.

**Comment by marcelrv** [comment]
each device has it's own set of supported properties.
It is bit of trial & error to find the onces your device supports and what is the meaning.

if you set the binding to debug mode you see the 'get_properties' command being send with the current parameters. See which ones get a response and which not. Likewise, try to find the property you miss. You can use the cmd channel to try out new properties

**Comment by kovaga** [comment]
Thanks marcel, here are the properties requested by the miioctl
COMMAND: STATUS
'power' 'on'
'aqi' 5
'average_aqi' 4
'humidity' 52
'temp_dec' 229
'mode' 'silent'
'favorite_level' 7
'filter1_life' 64
'f1_hour_used' 1254
'use_time' None
'motor1_speed' 300
'motor2_speed' 647
'purify_volume' None
'f1_hour' 3500
'led' 'on'

'led_b' None
'bright' 32
'buzzer' None
'child_lock' 'off'
'volume' 100
'rfid_product_id' '0:0:0:0'
'rfid_tag' '0:0:0:0:0:0:0'
'act_sleep' None
'sleep_mode' None
'sleep_time' None
'sleep_data_num' None
'app_extra' 2
'act_det' None
'button_pressed' None

Power: on
AQI: 5 μg/m³
Average AQI: 4 μg/m³
Temperature: 22.9 °C
Humidity: 52 %
Mode: silent
LED: True
LED brightness: None
Illuminance: 32 lx
Buzzer: None
Child lock: False
Favorite level: 7
Filter life remaining: 64 %
Filter hours used: 1254
Use time: None s
Purify volume: None m³
Motor speed: 300 rpm
Motor 2 speed: 647 rpm
Sound volume: 100 %
Filter RFID product id: 0:0:0:0
Filter RFID tag: 0:0:0:0:0:0:0
Filter type: FilterType.Unknown
Learn mode: False
Sleep mode: None
Sleep time: None
Sleep mode learn count: None
AQI sensor enabled on power off: None

COMMAND: INFO
'life': 330864
'cfg_time': 0
'token': 'a29XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
'mac': '78:11:DC:XX:XX:XX'
'fw_ver': '1.4.3_19105'
'hw_ver': 'MW300'
'model': 'zhimi.airpurifier.v7'
'wifi_fw_ver': 'SD878x-14.76.36.p84-702.1.0-WM'
'ap': {'rssi': -47
'ssid': 'XXXXXX'
'bssid': '0E:EC:DA:XX:XX:XX'}
'netif': {'localIp': '192.168.XXX.XXX'
'mask': '255.255.255.0'
'gw': '192.168.XXX.XXX'
'gw_mac': '02:26:F2:XX:XX:XX'}
'mmfree': 133980
'ot': 'ott'
'otu_stat': [85, 20, 1164, 11, 1088, 17]
'ott_stat': [2, 0, 708, 2487]


Model: zhimi.airpurifier.v7
Hardware version: MW300

Hope that helps and let me know if I can be of further help.

**Comment by marcelrv** [comment]
Can you use recent version of the binding (with with local db file support) and add the unzipped file to your OH/configuration/miio folder.

This way the new database file can be tested. Let me know if it is working fine.

[zhimi.airpurifier.zip](https://github.com/openhab/openhab-addons/files/4413715/zhimi.airpurifier.zip)

**Comment by marcelrv** [comment]
```
mode supported ( only this three modes are supported auto=Auto, silent=Silent, favorite=Manual)
:favoritelevel (takes value from 1 to 17)
```
Note:
Currently the binding for basic devices does not control / limit the values send... Hence it sends whatever you send to the channel
