### ISSUE TITLE
[neato] Add housecleaning with map (category 4)

### ISSUE THREAD

**Issue by dharenkamp** [openhab/openhab-addons#5761]
If i start the cleaning in the Neato app it uses the map that the robot has saved.
If i use the cleaning command in openhab it ignores the maps and therefore my no-go-lines.

I think it is because of using category 2 for cleaning command.
In the documentation of neato api there is also a category 4 which should work with the maps.
Perhaps it is possible to add a new Command for "CleanMap" or something like this.

In NeatoRobot.java in lines 141 and 142 are these lines:
                request.addParam("mode", this.state.getCleaning().getModeValue());
                request.addParam("category", "2");

And i think this is the point were category 4 should be used in a new command.

I´m using openhab2 on a raspian stretch with openhab and plugin version 2.5.0.M1.
My neato robot is a D7 Connected.

**Comment by dharenkamp** [comment]
I´ve added the necessary changes by myself.
fork of addons is [here](https://github.com/dharenkamp/openhab-addons/tree/neato-dev)

Searching for assistance to get it to production status (testing, code quality etc.)

**Comment by ArjenKorevaar** [comment]
Hi @dharenkamp,

I just got my D7 Connected as well and would like to add the option to clean with a persistent map (ie. category=4). However, I noticed your fork is no longer available? Would you still like to work on this change and appreciate some help on the PR? Otherwise I might create my own fork and take it from there...

**Comment by Tukks** [comment]
I made a PR to clean with map activated

**Comment by kathagor** [comment]
cleaning with map ist working with the changes from Tukks,

but I found in issue:
cleaning ist now much slower, than started by the neato app. I Think it's because "cleaning with map" sets navigation mode to "deep(3)" .

**Comment by jjlauterbach** [comment]
This capability was added by https://github.com/openhab/openhab-addons/pull/8310
