### ISSUE TITLE
[loxone] Add support for Intelligent room Controller v2

### ISSUE THREAD

**Issue by Tihmann** [openhab/openhab-addons#5798]
This issue is taken from #5615 and #5756 @ppieczul 

I referenced the parameters taken from the Loxone log to the Openhab parameters according to https://www.openhab.org/docs/ecosystem/google-assistant

"tempActual":"1274aa9f-03b7-3862-ffff2759e0e2464e",
["CurrentTemperature"] as part of Thermostat or standalone.

"tempTarget":"1274aa9f-03b7-3886-ffff2759e0e2464e",
["TargetTemperature"] 

name":"Luftfeuchte","type":"InfoOnlyAnalog","uuidAction":"12742c2c-00ff-b085-ffffb669809575ee","room":"12705d7d-0340-1522-ffffb669809575ee","cat":"127059b5-00aa-1
["CurrentHumidity"]

About ["homekit:HeatingCoolingMode"] as part of Thermostat I am not shure. Anyway to find out what the current values are in Loxone ? This link http://loxone-ip/data/LoxAPP3.json only displays the names not actual values

"comfortTemperature":"1274aa9f-03b7-386a-ffff2759e0e2464e",
"comfortTolerance":"1274aa9f-03b7-386b-ffff2759e0e2464e",
"frostProtectTemperature":"1274aa9f-03b7-386e-ffff2759e0e2464e",
"heatProtectTemperature":"1274aa9f-03b7-386f-ffff2759e0e2464e",
"comfortTemperatureOffset":"1274aa9f-03b7-3857-ffff2759e0e2464e",

**Comment by ppieczul** [comment]
@Tihmann I have some time to add this feature. Can you please take a look if the set of parameters which you need from the room controller are fine above - those 5 temperatures.
Please also take a look at the Intelligent Room Controller V2 at https://www.loxone.com/enen/wp-content/uploads/sites/3/2016/10/1000_Structure-File.pdf
and see what parameters are available for reading and what commands are available for operating.
Maybe some of them also make sense? I don't have physically this controller and only can predict which functions would be nice to have.
Thank you
Pawel
