### ISSUE TITLE
[somfytahoma] Add support for the Tahoma Dock

### ISSUE THREAD

**Issue by riederd** [openhab/openhab-addons#5801]
Hi,

I noticed that openhab2 is detecting the Tahoma Dock as new unsupported device. 

See the related log entry:

2019-07-04 15:55:55.364 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: Dock
2019-07-04 15:55:55.366 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below
2019-07-04 15:55:55.368 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Supported commands: { getName (params: 0); refreshBatteryLevel (params: 0); blinkModemLed (params: 2); increasingF
requencyBip (params: 2); longBip (params: 1); rebootModem (params: 0); refreshAirplaneMode (params: 0); refreshBatteryStatus (params: 0); refreshGPRSRegistration (params: 0); refreshGSMRe
gistration (params: 0); refreshOperatorConfig (params: 0); refreshOperatorName (params: 0); refreshRSSILevel (params: 0); refreshSIMCardStatus (params: 0); refreshSirenStatus (params: 0);
 setAirplaneMode (params: 1); setLightingLedModemMode (params: 1); setModemLedOff (params: 0); setModemLedOn (params: 0); setOperatorConfig (params: 1); setSIMPinCode (params: 1); setSire
nStatus (params: 3); shortBip (params: 1); siren (params: 1); stopBlinkModemLed (params: 0); }
2019-07-04 15:55:55.370 [WARN ] [very.SomfyTahomaItemDiscoveryService] - Device states:
{name='core:NameState', type=3, value=Telit GE910-QUAD}
{name='internal:BatteryStatusState', type=3, value=no}
{name='core:RSSILevelState', type=2, value=85.828}
{name='internal:GSMRegistrationState', type=6, value=false}
{name='internal:GPRSRegistrationState', type=6, value=false}
{name='internal:SIMCardStatusState', type=3, value=KO}
{name='internal:ProviderNameState', type=3, value=3 AT}
{name='internal:SirenStatusState', type=3, value=off}
{name='core:BatteryLevelState', type=3, value=100%}
{name='internal:AirplaneModeState', type=3, value=no}
{name='internal:LightingLedModemModeState', type=1, value=0.0}
{name='internal:SIMCardActivationState', type=6, value=false}
{name='internal:SIMCardConnectivityState', type=3, value=offline}
{name='internal:LastConnectivitySwitchState', type=5, value=1.532588733215E12}

Would it be possible to include the dock?

Thanks
  Dietmar

**Comment by octa22** [comment]
Hi,
I'll look at that. This device has a lot of values to display in OH, my question is - 
1) what value is important for you to see in OH2
2) how do you use the DEVICE? do you want to control the device as well in OH2?

Thanks

**Comment by riederd** [comment]
Hi,
thanks for looking into this!

The dock has a internal siren and battery backup for the Tahomabox.

1. To see the "BatteryStatusState", "BatteryLevel" and "SirenStatusState" would be good.
2. Some controls would be great, e.g. increasingFrequencyBip, longBip, shortBip, siren on/off

Thanks
  Dietmar

**Comment by octa22** [comment]
OK, thanks.
I'll start working on reading statuses, can you meanwhile find out, what parameters does the tahomalink.com portal uses to control the siren or bips?
There are several commands and I am unable to guest what params to send (setSirenStatus, siren, ...)
thanks.
Ondrej

**Comment by riederd** [comment]
Sure,
do you have a suggestion how I can test sending the params? I did never programatically use the TahomaBox.

Thanks
  Dietmar

**Comment by octa22** [comment]
sure.
1) use Chrome to log in to Tahomalink web (https://www.tahomalink.com/)
2) press F12 on your keyboard, click on the network tab in the new debug window
3) try to control the siren and send me the data it sends via the apply command. (click on the apply command, then headers tab and in the bottom is request payload - that's what I need)
thanks

**Comment by riederd** [comment]
Hi,

I think I fond what you need, however, this is the only thing that I could control from the thahomalink webinterface, it is the siren test. The "shortBip" command gets send, and the siren is giving 3 short bips. The other commands are not available from the web interface, but I guess you could make them controllable for OH.

{"startTime":1562342815830,"owner":"xyz@abc.def","actionGroup":{"label":"Testalarm","shortcut":false,"notificationTypeMask":0,"notificationCondition":"NEVER","actions":[{"deviceURL":"internal://XXXX-XXXX-XXXX/modem/0","commands":[{"type":1,"name":"shortBip","parameters":[3]}]}]},"description":"Execution : Testalarm","id":"xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxx","state":"TRANSMITTED","executionType":"Immediate execution","executionSubType":"MANUAL_CONTROL"}

I guess "longBip" will be similar but just a longer bip tone.
"increasingFrequencyBip" I'm not sure, it has 2 parameters, since it is

BTW, it would also be cool to have control on the somke detector Bip tone. This way, we could use them as additional Alarm sirens in case of a intrusion by using a OH rule.

There is a test command in the tahomalink interface, by which the bip can be tested, so I guess it might be possible to use them. This is what I see when issuing the "test" command.
{"startTime":1562343038255,"owner":"xyz@abc.def","actionGroup":{"label":"Somke 1 - Testen - TaHoma PC","shortcut":false,"notificationTypeMask":0,"notificationCondition":"NEVER","actions":[{"deviceURL":"io://xxxx-xxxx-xxxx/xxxxxxx","commands":[{"type":1,"name":"checkEventTrigger","parameters":["short"]}]}]},"description":"Execution : Smoke 1 - Testen - TaHoma PC","id":"xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx","state":"IN_PROGRESS","executionType":"Immediate execution","executionSubType":"MANUAL_CONTROL"}

Best
   Dietmar

**Comment by octa22** [comment]
Hi, closer but not what I am looking for.
Once you execute the test, I need to see the parameters of apply command.
This seems to be rather result of fetch command...
thanks
Ondrej


________________________________
Od: riederd <notifications@github.com>
Odesláno: pátek, července 5, 2019 6:30 odp.
Komu: openhab/openhab2-addons
Kopie: Ondrej Pecta; Comment
Předmět: Re: [openhab/openhab2-addons] [SomfyTahoma][feature] Please add the Tahoma Dock (#5801)


Hi,

I think I fond what you need, however, this is the only thing that I could control from the thahomalink webinterface, it is the siren test. The "shortBip" command gets send, and the siren is giving 3 short bips. The other commands are not available from the web interface, but I guess you could make them controllable for OH.

{"startTime":1562342815830,"owner":"xyz@abc.def<mailto:xyz@abc.def>","actionGroup":{"label":"Testalarm","shortcut":false,"notificationTypeMask":0,"notificationCondition":"NEVER","actions":[{"deviceURL":"internal://XXXX-XXXX-XXXX/modem/0","commands":[{"type":1,"name":"shortBip","parameters":[3]}]}]},"description":"Execution : Testalarm","id":"xxxxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxx","state":"TRANSMITTED","executionType":"Immediate execution","executionSubType":"MANUAL_CONTROL"}

I guess "longBip" will be similar but just a longer bip tone.
"increasingFrequencyBip" I'm not sure, it has 2 parameters, since it is

BTW, it would also be cool to have control on the somke detector Bip tone. This way, we could use them as additional Alarm sirens in case of a intrusion by using a OH rule.

There is a test command in the tahomalink interface, by which the bip can be tested, so I guess it might be possible to use them. This is what I see when issuing the "test" command.
{"startTime":1562343038255,"owner":"xyz@abc.def<mailto:xyz@abc.def>","actionGroup":{"label":"Somke 1 - Testen - TaHoma PC","shortcut":false,"notificationTypeMask":0,"notificationCondition":"NEVER","actions":[{"deviceURL":"io://xxxx-xxxx-xxxx/xxxxxxx","commands":[{"type":1,"name":"checkEventTrigger","parameters":["short"]}]}]},"description":"Execution : Smoke 1 - Testen - TaHoma PC","id":"xxxxxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxxxx","state":"IN_PROGRESS","executionType":"Immediate execution","executionSubType":"MANUAL_CONTROL"}

Best
Dietmar

**Comment by riederd** [comment]
Hi,

What I see in the the Request Header
"Query String Parameters" is only the following (and this number seems to change each time)
_=1562246253658

Is this what you need?

**Comment by octa22** [comment]
I need data from the Request Header, but from the section Request Payload, for example:
```
{"label":"Living room roller shutter to 91% - TaHoma PC","actions":[{"deviceURL":"io://0204-4519-8041/6965109","commands":[{"name":"setClosure","parameters":[91]}]}]
```

**Comment by octa22** [comment]
One of the supported commands is "siren", since it has only one parameter, I guess it accepts on/off.
Can you try this binding version?
https://www.dropbox.com/s/milfiftoww77p1e/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

it should autodetect the dock and if you add the thing, you'll see three channels
(string) battery level
(string) battery state
(switch) siren

if you switch the siren channel, it should send on/off siren command to tahoma. Let's see if something happens :-)
Thanks.
Ondrej

**Comment by octa22** [comment]
> Is this what you need?

sorry I have read once again your post and now I see it, it is everything I need. (I was a bit lost with the communication with smoke detector and its command, because it doesn't match the siren command  :-)

so in tahomalink UI you have only shortBip and longBip and the parameter is number of beeps it generates, right?
Sorry for complications...
Ondrej

**Comment by riederd** [comment]
Hi, must have been to blind to spot the "apply", now I found it, sorry.
Anyway this is the payload for the siren test (shortBip, 3 times) on the Thahoma dock:

{"label":"Testalarm","actions":[{"deviceURL":"internal://1208-2658-1637/modem/0","commands":[{"name":"shortBip","parameters":[3]}]}]}

And this is the one for the smoke detector bip test (short bip 3 times):
{"label":"Rauch 2 Büro - Testen - TaHoma PC","shortcut":false,"internal":false,"actions":[{"deviceURL":"io://1208-2658-1637/9688780","commands":[{"name":"checkEventTrigger","parameters":["short"]}]}]}

Thanks
  Dietmar

**Comment by octa22** [comment]
Great! So we have the shortBip and longBip commands, please try to download and test the binding from the link above.
I am eager to test what does the "siren" command...
thanks.
Ondrej

**Comment by riederd** [comment]
Hi, thanks!
I'll do this tomorrow morning, it's to loud I'd wake up some people now :-)

**Comment by octa22** [comment]
Yeah, I thought so :-)
If you want to add the test for the smoke detector as a new channel, I can do it as well...

Ondrej

**Comment by riederd** [comment]
Hi,

Disclaimer: I'm new to OH and still need to learn some essential things 

Just to be sure. If I want to test the new version of the binding, I guess I have first to uninstall the binding-somfytahoma - 2.4.0 via the Paper UI and then put the new org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar under /usr/share/openhab2/addons , right?

Do I loose any of my settings with uninstalling (things, items and so on) that I created in the Paper UI which are related to the binding-somfytahoma - 2.4.0?

Best
  Dietmar

**Comment by octa22** [comment]
yes,

you are right. Just uninstall the bundled 2.4 version and install the 2.5.0-SNAPSHOT from the link I provided. (please redownload if you did so, I did some changes late in the night)
You won’t lose any settings, neither things.

Ondrej

________________________________
Od: riederd <notifications@github.com>
Odesláno: sobota, července 6, 2019 10:33 dop.
Komu: openhab/openhab2-addons
Kopie: Ondrej Pecta; Comment
Předmět: Re: [openhab/openhab2-addons] [SomfyTahoma][feature] Please add the Tahoma Dock (#5801)


Hi,

Disclaimer: I'm new to OH and still need to learn some essential things

Just to be sure. If I want to test the new version of the binding, I guess I have first to uninstall the binding-somfytahoma - 2.4.0 via the Paper UI and then put the new org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar under /usr/share/openhab2/addons , right?

Do I loose any of my settings with uninstalling (things, items and so on) that I created in the Paper UI which are related to the binding-somfytahoma - 2.4.0?

Best
Dietmar

**Comment by riederd** [comment]
Hi,

I installed the new version, and I can add the Security Base (dock). I can also get the state of the siren and the battery level. However, the siren switch does not seem to work, I get the following messages logged:


events.log:
2019-07-06 11:10:53.556 [ome.event.ItemCommandEvent] - Item 'SecurityBase_SirenStatusState' received command ON
2019-07-06 11:10:53.566 [vent.ItemStateChangedEvent] - SecurityBase_SirenStatusState changed from OFF to ON

openhab.log
2019-07-06 11:10:53.562 [INFO ] [ernal.handler.SomfyTahomaDockHandler] - Sending command siren with param: on
2019-07-06 11:10:53.762 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-07-06 11:10:53.766 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"com.fasterxml.jackson.databind.JsonMappingException: Unrecognized token 'on': was expecting ('true', 'false' or 'null')\n at [Source: org.apache.catalina.connector.CoyoteInputStream@14ddec73; line: 1, column: 144] (through reference chain: com.s2ih.server.model.business.setup.action.ManagedActionGroup[\"actions\"]->java.util.ArrayList[0]->com.s2ih.server.model.business.setup.action.Action[\"commands\"]->java.util.ArrayList[0]->com.s2ih.server.model.business.setup.action.Command[\"parameters\"]->Object[][0])"}

Best
  Dietmar

I'll be away until this evening, but I can do more tests then.

**Comment by octa22** [comment]
Thanks for testing. Apparently it expects true/false instead of on/off.
Can you try this version please?
https://www.dropbox.com/s/milfiftoww77p1e/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

Thanks.
Ondrej

**Comment by riederd** [comment]
Thanks, closer I guess but still not there:

events.log
2019-07-06 20:14:28.989 [ome.event.ItemCommandEvent] - Item 'SecurityBase_SirenStatusState' received command ON
2019-07-06 20:14:29.004 [vent.ItemStateChangedEvent] - SecurityBase_SirenStatusState changed from OFF to ON
2019-07-06 20:14:29.244 [hingStatusInfoChangedEvent] - 'somfytahoma:bridge:764e9cb0' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Unauthorized. Please check credentials

openhab.log
2019-07-06 20:14:28.998 [INFO ] [ernal.handler.SomfyTahomaDockHandler] - Sending command siren with param: true
2019-07-06 20:14:29.230 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-07-06 20:14:29.234 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : siren() : Invalid value for command parameter p1 : expected string value in (cyclic, off, on) but got true"}
2019-07-06 20:14:29.440 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-07-06 20:14:29.443 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : siren() : Invalid value for command parameter p1 : expected string value in (cyclic, off, on) but got true"}
2019-07-06 20:14:33.736 [INFO ] [ernal.handler.SomfyTahomaDockHandler] - Sending command siren with param: false
2019-07-06 20:14:34.642 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-07-06 20:14:34.645 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : siren() : Invalid value for command parameter p1 : expected string value in (cyclic, off, on) but got false"}
2019-07-06 20:14:34.943 [ERROR] [nal.handler.SomfyTahomaBridgeHandler] - Received error code: 400
2019-07-06 20:14:34.946 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"error":"Managed action group is invalid : siren() : Invalid value for command parameter p1 : expected string value in (cyclic, off, on) but got false"}

**Comment by octa22** [comment]
Hi,
ok I think I know what I did wrong.
siren_status channel may have three values (on/off/cyclic), therefore I changed it to String channel instead of Switch.
Could you please:
1) remove the dock thing
2) download the new version of binding from the same url
https://www.dropbox.com/s/milfiftoww77p1e/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1
3) add the dock thing (autodiscovery should work)
4) test sending "off", "on" and "cyclic" to siren status channel

thanks.
Ondrej

**Comment by riederd** [comment]
Hi,

I just downloaded and tested the new jar.
The ON/OFF commands work. ON gives a tone for as long as the state is ON. OFF switches the siren tone off again. CYCLIC does not do anything, however there is also no error logged.

Best
  Dietmar

**Comment by octa22** [comment]
Great!
so it works, do you want to add channels for long bip and short bip as well?

Ondrej

ne 7. 7. 2019 v 10:30 odesílatel riederd <notifications@github.com> napsal:

**Comment by riederd** [comment]
Yeah, that would be nice. Thanks so much!!!
BTW:
Did you already think about, adding control for the smoke detectors, as we were discussion above?

Thanks again
  Dietmar

**Comment by riederd** [comment]
...and it would also be very helpful if one could get the batterylevel of the smokesensors.

Dietmar

**Comment by octa22** [comment]
sure, can you find out what is the name of the status? It should be visible in chrome (F12) just after login or from debug of tahlma binding durin initialitation or discovery...
thanks

**Comment by riederd** [comment]
I'm afraid there is no way, to get the battery level of the smoke sensors. Nothing discovered. So never mind.

**Comment by octa22** [comment]
hi, I have added channels for testing shortBip and longBip
https://www.dropbox.com/s/milfiftoww77p1e/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

just remove the old dock thing and let it autodiscover. new channels short_beep and long_beep should  appear. (type switch)
If you send ON command to these switches, it should do the desired action...

Thanks for testing.
Ondrej

**Comment by riederd** [comment]
hi, I just installed the new version. I works like a charm! Thanks!

There are some additional commands that might be interesting:

increasingFrequencyBip (params: 2)  <- do not know which they are
refreshSirenStatus (params: 0)
refreshBatteryStatus (params: 0)
refreshBatteryLevel (params: 0)

Dietmar

**Comment by octa22** [comment]
Hi, thanks for confirming the binding functionality.
refreshing any of statuses is not necessary, it is done automatically in background. 
I have included the dock support in the lastest pull request and I hope it will be soon part of the new official version.
Can you please create a new issue requesting adding support for the testing of smoke sensor?
if you include this info it'll be sufficient :-)
```
{"label":"Rauch 2 Büro - Testen - TaHoma PC","shortcut":false,"internal":false,"actions":[{"deviceURL":"io://XXXX-YYYY-ZZZZ/9688780","commands":[{"name":"checkEventTrigger","parameters":["short"]}]}]}
```
I'll reference this issue once I prepare the support for the new channel
thanks
Ondrej
