### ISSUE TITLE
[mqtt.homie] Discovered devices should set autoupdate=false

### ISSUE THREAD

**Issue by peterhoeg** [openhab/openhab-addons#5817]
## Your Environment

* Version used: 2.4 (oh and addons2)
* Environment name and version: Oracle Java 8
* Operating System and version: NixOS (linux)

Since the homie convention specifies that a device will respond on it's state topic after receiving a command, any auto-discovered homie bindings should have ```autoupdate=false```.

Cc: @davidgraeff

**Comment by Rossko57** [comment]
autoupdate is a "property" of an Item.  Bindings should not be interfering with that.  Items may be bound to other channels that do not behave the same way. 
Also bear in mind one of the reasons for the existence of autoupdate is to provide a more responsive user experience.

What is the use case here, what problems does having the default autoupdate="true" bring?

**Comment by davidgraeff** [comment]
A channel description can of course declare that it does not want auto-updates. A user may overwrite it later. It makes sense for mqtt homie. 

> what problems does having the default autoupdate="true" bring?

Every device that has a back channel that mirrors the set value should have a binding that disables auto updates by default.

**Comment by hmerk** [comment]
closed due to inactivity
