### ISSUE TITLE
MQTT 3.1 and Homie, "Set" action does not send command in the set channel.

### ISSUE THREAD

**Issue by fleek** [openhab/openhab-addons#5819]
Hi,

I have configured a ESP8266 device to adhere to the Homie specifications.  According to specifications, when you specify a device property-attribute to $settable = true, the device will listen on the set channel and when setting the values, the MQTT binding should send the value via the set channel.  However, I believe currently it is setting it in the main property channel which is causing the error, "Read-Only Channel" and thus causing the device to go offline.

Eg.

I have a device with the property as such

homie/esp8266/led./$name -> LED
homie/esp8266/led/$type -> Switch
homie/esp8266/led/$properties -> switch
homie/esp8266/led/switch/$name -> Switch
homie/esp8266/led/switch/$settable -> true
homie/esp8266/led/switch/$datatype -> enum
homie/esp8266/led/switch/$format -> OFF,ON
homie/esp8266/led/switch -> ON

The device will listen on 
homie/esp8266/led/switch/set

The MQTT binding should publish value changes to 
homie/esp8266/led/switch/set but currently it is trying to send to homie/esp8266/led/switch instead which is a readonly channel.

**Comment by bodiroga** [comment]
I'm not sure if this is a bug, sorry. The 'settable' attribute makes the property 'writable' from the outside, that's why the binding makes a subscription to the ".../set" topic, because it's waiting for new commands to update the state of the items. And, accordingly, all state updates will be reflected in the non-set topic.

To make things more clear:
- "homie/esp8266/led/switch" -> topic where state updates will be notified
- "homie/esp8266/led/switch/set" -> topic where the binding will make a subscription to receive external commands and, after that, the new state of the property will updated through "homie/esp8266/led/switch"

As far as I know and with my own experience during some tests, the binding is behaving correctly (according to the Homie 3.0.1 specification) :+1:

**Comment by J-N-K** [comment]
After reading the spec I think it is just the other way round. OpenHAB is a controller, so it should listen on the topic and send commands to topic/set.

**Comment by bodiroga** [comment]
> After reading the spec I think it is just the other way round. OpenHAB is a controller, so it should listen on the topic and send commands to topic/set.

D'oh! :man_facepalming: I don't know why I was thinking from the device perspective, you are totally right! But that's what the binding is doing, isn't it?

Here you have a topic tree I'm using to test the latest snapshot version:

- homie/bedroom-music-controller/$name -> bedroom-music-controller
- homie/bedroom-music-controller/$homie -> 3.0.1
- homie/bedroom-music-controller/$localip -> xxx.xxx.xxx.xxx
- homie/bedroom-music-controller/$mac -> xx:xx:xx:xx:xx
- homie/bedroom-music-controller/$implementation -> homie-python
- homie/bedroom-music-controller/$fw/name -> music-controller
- homie/bedroom-music-controller/$fw/version -> 1.0.0
- homie/bedroom-music-controller/$stats/signal -> 56
- homie/bedroom-music-controller/$stats/interval -> 60
- homie/bedroom-music-controller/$stats/uptime -> 78480
- homie/bedroom-music-controller/$nodes -> speaker
- homie/bedroom-music-controller/speaker/$type -> speaker
- homie/bedroom-music-controller/speaker/$name -> Speaker
- homie/bedroom-music-controller/speaker/$properties -> on
- homie/bedroom-music-controller/speaker/on -> false
- homie/bedroom-music-controller/speaker/on/$name -> On
- homie/bedroom-music-controller/speaker/on/$settable -> true
- homie/bedroom-music-controller/speaker/on/$datatype -> boolean
- homie/bedroom-music-controller/speaker/on/set -> false
- homie/bedroom-music-controller/$state -> ready

It works flawlessly, even if I reboot the device or openHAB, so I can't confirm the issue. I have also added an enum type property with the same results: commands are sent to the "/set" topic and the item state is property updated. Great!

Many thanks for your hard work @J-N-K, you are doing an amazing job! :+1:

**Comment by J-N-K** [comment]
After setting up a test, I think that the publication is indeed done to switch/set, just the log message is wrong. Will check

**Comment by davidgraeff** [comment]
Subscriptions and Publishing is covered by tests, but log messages are not. Thanks J-N-K for finding this.
