### ISSUE TITLE
[hue] Color channel updates take much longer than bridge pollingInterval

### ISSUE THREAD

**Issue by ramon18** [openhab/openhab-addons#5820]
##  Expected Behavior
When using another app to control the bulbs color, openhab2 should sense the change almost instantaneous (as it does for brightness and color_temperature).

## Current Behavior
Openhab2 takes a lot to trigger the change event,

## Steps to Reproduce (for Bugs)
I'm using the bulb Philips LCT015 Extended Color (0210)
Set the pollingInterval=1 (just to be sure)

1. Open a console with tailf events.log 
2. Open "All 4 hue" app, open the bulb and choose change color
3. tailf events.log takes a long time to report the change [vent.ItemStateChangedEvent]

## Your Environment
Centros 7
Openhab 2.4.0

**Comment by wborn** [comment]
> events.log takes a long time to report the change

Can you quantify "a long time" and did you try changing the `pollingInterval` bridge configuration parameter? The default polling interval is set to everey 10 seconds. The configuration can be updated so it polls every second. See also the [Hue Binding documentation](https://www.openhab.org/addons/bindings/hue/#thing-configuration).

**Comment by wborn** [comment]
I see you already tried decreasing the polling interval. :wink:

**Comment by ramon18** [comment]
Yes I tested all different configurations I’m aware of.
Regarding the delay of the log update, it can’t be the case here, because I can see other updates (form other rules).

**Comment by lolodomo** [comment]
@ramon18 : was your problem finally solved by appropriate settings ?
If you want faster update of light status, you can increase the light refresh interval which is by default run every 10 seconds.
If you are not using hue sensors, take care of the sensor refresh interval which by default requests the bridge twice per second. With 2.5.6, you can disable it by setting to 0; before 2.5.6, you can increase its value to a very big value.

**Comment by cweitkamp** [comment]
@ramon18 Any news on this? Is your issue solved by one of the previous suggestions? If not feel free to reopen this issue.
