### ISSUE TITLE
[skeleton] Duplicated information when using create_openhab_binding_skeleton.sh

### ISSUE THREAD

**Issue by FredyR4zox** [openhab/openhab-addons#5860]
When executing the "create_openhab_binding_skeleton.sh" script with the following arguments "boas eu eu", the files CODEOWNERS, bom/openhab-addons/pom.xml and bundles/pom.xml are populated with duplicated data.

Reproduction steps:
git clone https://github.com/openhab/openhab2-addons.git
cd openhab2-addons/bundles
./create_openhab_binding_skeleton.sh boas eu eu
git diff

See the duplicated data with git diff

![Untitled](https://user-images.githubusercontent.com/6351888/61812956-87bb9880-ae3c-11e9-9375-9c51ad0856ed.png)

**Comment by cweitkamp** [comment]
I can confirm this behavior. It happens every time the script is executed. It looks like the new entries were added in each line until the alphabetical order is satisfied.

**Comment by Hilbrand** [comment]
It looks like the script can't handle the case where the new binding name is after a binding that consists of multiple projects. In this case the bluetooth binding.

**Comment by cweitkamp** [comment]
The adopted script is working nicely. Creating a new binding is now as easy as it was before - including compiling and running it via Eclipse IDE.

In the beginning I faced an issue using a binding name including whitespaces but everything was working afterwards even if the creation script failed with an error. After a quick search it seems to me that we did have this before and it is not allowed to have whitespaces in the binding name. Should we take care of that?

```
./create_openhab_binding_skeleton.sh "My Test Binding" "Christoph Weitkamp" "cweitkamp"
```

```
[INFO] Using property: package = org.openhab.binding.my
```

```
[ERROR] Unknown lifecycle phase "binding". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

**Comment by Hilbrand** [comment]
The script already prints to use camel case id when run without arguments. That should have been a hint it might not work😀
At some places using a spaced description would be nicer, but requires an extra argument to the script. I wasn't completely convinced it's really worth the effort, as it's not required to make it work and can easily be changed by a user if wanted.

**Comment by cweitkamp** [comment]
Yes, I agree. I bet there are other characters which are not allowed for binding ids. Would it be an option to apply a REGEX on the parameter inside the "create_openhab_binding_skeleton" scripts to prevent such failures?
