### ISSUE TITLE
[somfytahoma] Add support for AdjustableSlatsRollerShutter devices

### ISSUE THREAD

**Issue by s0k33t** [openhab/openhab-addons#5866]
Hi,

I noticed that openhab2 is detecting the AdjustableSlatsRollerShutter as new unsupported device.

See the related log entry:

```
2019-07-27 08:12:02.339 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: AdjustableSlatsRollerShutter
2019-07-27 08:12:02.343 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below
2019-07-27 08:12:02.346 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Supported commands: { close (params: 0); delayedStopIdentify (params: 1); down (params: 0); getName (params: 0); identify (params: 0); open (params: 0); setClosure (params: 1); setClosureOrOrientation (params: 2); setClosureOrRockerPosition (params: 1); setDeployment (params: 1); setName (params: 1); setRockerPosition (params: 0); setOrientation (params: 1); startIdentify (params: 0); stop (params: 0); stopIdentify (params: 0); up (params: 0); wink (params: 1); }
2019-07-27 08:12:02.349 [WARN ] [very.SomfyTahomaItemDiscoveryService] - Device states:
{name='core:NameState', type=3, value=Super Matrimonio}
{name='core:PriorityLockTimerState', type=1, value=0.0}
{name='core:StatusState', type=3, value=available}
{name='core:RSSILevelState', type=2, value=98.0}
{name='core:ClosureOrRockerPositionState', type=3, value=rocker}
{name='core:SlateOrientationState', type=1, value=65.0}
```

**Comment by octa22** [comment]
Hi, of course I can add the support.
How do you want to control the thing?
I see 
- setting the closure (0-100%)
- setting the orientation (0-100%)
- setting the rocker position

BTW What is the rocker position? If you set the rocker position what does the closure do - it the rollershutter open or closed? I do not see the MY position and I don't know how the rocker position replaces it...

Thanks
Ondrej

**Comment by s0k33t** [comment]
sorry, now we are one more in the family and I haven't time.
In Tahoma app this device has two sliders. One for closure, and other for orientation

**Comment by octa22** [comment]
Congrats! I know what you are talking about. Just one question regarding the support before I provide you with the version for testing...
Based on the Tahoma portal javascript reverse engineering it seems that orientation is possible only when the shutter is in 'rocker' position.

When in 'rocker' position, what is the closure of the roller shutter? ( I guess closed/down, am I right?)

Thanks

**Comment by s0k33t** [comment]
Yes! You are right

With the remote:
Up -> up
My (shutter in moviment)-> stop
Down -> Down

My(shutter is stopped) -> go to rocker position
UP (Rocker position) -> graduate Up
UP long push (Rocker position) -> Up
Down (Rocker Rocker) -> graduate Down
Down long push (Rocker position) -> Down



Thanks

**Comment by octa22** [comment]
Thanks.
I'd be glad if you try this version
https://www.dropbox.com/s/t3kzi4kvxve1jeb/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

the adjustable slats roller shutter thing exposes 3 channels
- rocker (switch for controlling/displaying the rocker position state ON/OFF)
- control (roller shutter control UP/DOWN, instead of MY command, it can set the rocker position too or stop the movement)
- orientation (dimmer for the slats orientation control)

Thanks.
Ondrej

**Comment by s0k33t** [comment]
Hi,
I test it, but discovery service can't find it.
If it try to add manually, need the url, but I don't know where find it :(

**Comment by octa22** [comment]
you are right, there was a bug.
Sorry for that.
Please try this one:
https://www.dropbox.com/s/t3kzi4kvxve1jeb/org.openhab.binding.somfytahoma-2.5.0-SNAPSHOT.jar?dl=1

**Comment by s0k33t** [comment]
Hi Ondrej, 
This version work fine.
Maybe the feedback tahoma-openhab with percentage of orientation not update properly. But work ok.

Thanks for your time. 
I contiune test it.

;)

**Comment by octa22** [comment]
Hi @s0k33t,

if you want to fix the percentage of the slats orientation, I need to get the trace log from openhab.log.
Thanks.
Ondrej
