### ISSUE TITLE
[hueemulation] Alexa announces device is malfunctioning when changing colors

### ISSUE THREAD

**Issue by ayushjain4484** [openhab/openhab-addons#5897]
Hi ,

I am working with ws2812b led strip to change the color of the led strip using alexa

I have exposed my item as :

Color LEDStrip_FF_Kitchen_Cabinet_1_Color “daksh” (FF_Kitchen,gLEDStrip_Kitchen_Color) [ “ColorLighting” ]

Sitemap as :

Color LEDStrip_FF_Kitchen_Cabinet_1_Color “daksh” (FF_Kitchen,gLEDStrip_Kitchen_Color) [ “ColorLighting” ]

Alexa is able to discover the device but on the top it says (Device doesn’t support requested value).

The leds are functional using the app when i click on the color basic color(rgb) the device works fine and gives no error the leds too are changing its color.

The problem comes when i ask alexa to change the color of the strip other than red,blue,green.Alexa changes the color of the strip but makes the device malfunction along with an announcement that the device is malfunctioning.
![WhatsApp Image 2019-08-08 at 3 02 22 AM (1)](https://user-images.githubusercontent.com/23170844/62665111-b9d00d00-b99b-11e9-9fcf-f138a45f8a1a.jpeg)
![WhatsApp Image 2019-08-08 at 3 02 22 AM (2)](https://user-images.githubusercontent.com/23170844/62665112-b9d00d00-b99b-11e9-90c0-6cdde63dcf01.jpeg)
![WhatsApp Image 2019-08-08 at 3 02 22 AM (3)](https://user-images.githubusercontent.com/23170844/62665113-b9d00d00-b99b-11e9-806f-ad03413ab094.jpeg)
![WhatsApp Image 2019-08-08 at 3 02 22 AM (4)](https://user-images.githubusercontent.com/23170844/62665114-b9d00d00-b99b-11e9-807a-43872d3613c5.jpeg)
![WhatsApp Image 2019-08-08 at 3 02 22 AM](https://user-images.githubusercontent.com/23170844/62665115-ba68a380-b99b-11e9-823c-45023787e5a6.jpeg)

Please can anyone help me with this.

Thanks,

**Comment by davidgraeff** [comment]
You are on the latest hue emulation version? Other people confirmed that Amazon Echos will respond with "Device does not respond" and similar. So there is a not expected response generated by the hue emulation code. But I don't have time to look into this.
