### ISSUE TITLE
[knx2] reading values does not work any more

### ISSUE THREAD

**Issue by Alex5719** [openhab/openhab-addons#5916]
Hello,

I am running a snapshot build of OpenHAB 2.5 with the knx2 binding accessing two different KNX IP Interfaces in TUNNEL mode. Therefor I have configured two separate KNX Bridges in my things file. My Configuration was running well till build 1607. The later builds showed the strange behaviour that KNX read requests did not work randomly on one or the other bridge.

I first thought the strange behaviour is due to the running refactorings but I now installed the new milestone 2 build of OH 2.5 and I still get the described strange behaviour.

I get the following exception in my log (2.5 Milestone 2 Build):

`2019-08-11 16:25:26.600 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.knx.internal.client.AbstractKNXClient.readNextQueuedDatapoint(AbstractKNXClient.java:283) ~[?:?]
	at org.openhab.binding.knx.internal.client.AbstractKNXClient.lambda$1(AbstractKNXClient.java:199) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51
1) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:
?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by nanosonde** [comment]
I am also experiencing the same issue here with the same error messages in openhab.log.
I am also using KNX in tunnel mode with a certified KNX Gateway from MDT.
In 2.5.0 M1 this was running flawlessly.

**Comment by Alex5719** [comment]
I am also using MDT devices.

**Comment by nanosonde** [comment]
There used to be the following NULL check before it was removed [here](https://github.com/openhab/openhab2-addons/pull/5695/files#diff-62af0fbcf4f60c06e22fe19181da0d80L280).

However, from [here](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/LinkedBlockingQueue.html#poll()) I can see that poll() returns NULL if the queue is empty.

**Comment by kaikreuzer** [comment]
@J-N-K as you worked on https://github.com/openhab/openhab2-addons/pull/5695, which was the only change: Can you reproduce this issue and would have an idea how to fix it?

**Comment by J-N-K** [comment]
My fault. Will provide a fix ASAP.

**Comment by Alex5719** [comment]
I have installed snapshot build 2.5.0~S1663-1 and can confirm that the bug is fixed.

Thank you for your great work on openHAB.
