### ISSUE TITLE
[SMA Energy Meter] Continue developing with advance features.

### ISSUE THREAD

**Issue by kandersen01** [openhab/openhab-addons#5919]
Anyone care to continue developing SMA Energy Meter binding. I believe it´s lacking quite alot of features which the Energy Meter can do. Unfortunatly it doesnt seem like there is anymore developing going on.. I cant do any developing myself :-(
The features can be viewed in this Youtube video. I have the exec file from the author of the video, which ofcouse is not the same as the binding for openHab2. But it´s quite awesome features which could come in hand.  
https://www.youtube.com/watch?v=ZdgHKEg3pQU&t=4s

**Comment by cribskip** [comment]
I've taken a quick look and found a description on http://www.eb-systeme.de/?page_id=3005 and http://www.eb-systeme.de/?page_id=1240.

Besides Voltages and Currents, there are also reactive powers per phase. For newer firmwares, there' also the grid frequency. Is this interesting for any automation? All I can think of is equalizing consumption and watching out for grid "usage" wrt the frequency. Anything else?

The binding seems to be structured very good. Here the magic begins to happen: https://github.com/openhab/openhab-addons/blob/c5fdd32420f98af893bba13c1be39e0f4d5e92eb/bundles/org.openhab.binding.smaenergymeter/src/main/java/org/openhab/binding/smaenergymeter/internal/handler/EnergyMeter.java#L51

**Comment by hmerk** [comment]
closed due to inactivity
