### ISSUE TITLE
[Meteoblue] [feature] Include current weather conditions

### ISSUE THREAD

**Issue by bummzulu** [openhab/openhab-addons#5953]
The Meteoblue binding is a great binding to retrieve accurate weather forecast data. I would consider it as a great feature if the binding would also provide the possibility to retrieve actual/current weather data. The latest version of the meteoblue API seems to provide this information. I have attached the documentation of the meteoblue API.

[meteoblue_API_data-packages_images_documentation_EN_v4.0.pdf](https://github.com/openhab/openhab2-addons/files/3516993/meteoblue_API_data-packages_images_documentation_EN_v4.0.pdf)

**Comment by 9037568** [comment]
Are you a paying subscriber of meteoblue, @bummzulu ? Because as far as I can tell, the current weather condition data is only available in the commercial plan.

**Comment by bummzulu** [comment]
Actually I just wanted to double check but cant find the description of the data packages on the website anymore. I have reached out to meteoblue to ask for clarification. Will update once I receive an answer. Thanks

**Comment by bummzulu** [comment]
upon my request meteoblue changed the data package of my api key from "basic-day" to "basic-1h" which provides current weather data but no forecast information. 

As this is data package does not work with the openhab binding I am trying to integrate the API into openahb using nodered.

**Comment by gstiegl** [comment]
I have a non-commercial subscribing model at Meteoblue but they extend it for free for current weather conditions. It looks like:
`"data_current": 
	{
		"pictocode": 4, 
		"time": "2020-01-24T16:00+01:00", 
		"temperature": -2.76, 
		"isdaylight": 1, 
		"windspeed": 0.40, 
		"isobserveddata": 1, 
		"zenithangle": 87.18, 
		"pictocode_detailed": 22
	}, `

**Comment by lduesing** [comment]
https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use

**Comment by lduesing** [comment]
(why closed?)
