### ISSUE TITLE
[mqtt.homie] Decrease subscribeTimeout time for Homie devices

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab-addons#5958]
Hi guys! (@davidgraeff, @J-N-K)

Now that many MQTT and Homie problems are solved, I think that we should decrease the subscribeTimeout parameter for Homie devices, because 15 seconds seems to be a little bit high. What about 2-3 seconds? It is still plenty of time to retrieve retained topics from the broker, so there shouldn't be any problem with constrained devices. What do you think? Do you want me to make a pull request with the changes? It is just a one line change:

https://github.com/openhab/openhab2-addons/blob/e775b4d09278cb97170dd8c4844fc5bb43a62027/bundles/org.openhab.binding.mqtt.homie/src/main/java/org/openhab/binding/mqtt/homie/generic/internal/MqttThingHandlerFactory.java#L93

Thank you for all your work and support!

**Comment by J-N-K** [comment]
What is the problem with 15s? I don't think that discovery is time-critical.

**Comment by boc-tothefuture** [comment]
I agree with @J-N-K, I think the longer is better.  In my experience it can take a while not because the broker isn't sending it but because openhab can be very busy during discovery (openhab restarting for example).

**Comment by bodiroga** [comment]
Hi guys!

As expressed in #5963, my only concern is that the timeout, as it is implemented, is not a safety wait, but a compulsory wait, because you need to wait those 15 seconds before channels are added to the Homie thing. As discussed with @davidgraeff, the optimal solution would be to replace it with a much shorter "no further messages" timeout, but that is more complex than what is proposed here. Let's see if we can "fix" it in the correct way :+1:
