### ISSUE TITLE
Google Assistant: Sorry I didn't get any response

### ISSUE THREAD

**Issue by tulamidan** [openhab/openhab-addons#5985]
This is pretty much - reopening issue #3805
The error is exactly the same So I just copy the text with small modifications:
 
Expected Behavior
Until yesterday the google home/assistant integration worked like a charm (using google assistant and myopenhab.org account). For example:
German command: Hey Google, schalte das Licht an (translated: Hey Google, turn on the lights)
German response: Alles klar, ich schalte das Licht an (translated: OK, turning on the lights)

Current Behavior
Now the response has changed. The funny thing is that it has changed from German to English language.
For example:
German command: Hey Google, schalte das Licht an (translated: Hey Google, turn on the lights)
"English" response: Sorry I didn't get any response (in an nice german accent)
Besides this silly response, everything works as expected.

Possible Solution
no clue

Steps to Reproduce (for Bugs)
seems many people noticed this behavior at the same time (Aug. 2019), see community forum:
https://community.openhab.org/t/chromecast-google-assistant-responds-sorry-i-didnt-get-any-response

PS: I personally use openhab 2.4 stable

**Comment by boggiano** [comment]
Same here today using Home Assistant and from Italy!
Everything worked from months.

I created a new project... unliked the old one... bla bla bla... same result!
Lights and everything is working beside that stupid answer in English.

**Comment by Poncerello** [comment]
Stesso identico problema io dall'Italia..

**Comment by smingoli** [comment]
I'm in Italy too and using home assistant. The problem started yesterday... Very annoying

**Comment by mirkochip88** [comment]
Stessa cosa... da un paio di giorni

**Comment by smingoli** [comment]
My assistant is set to understand both Italian and English

If I say: ok Google accendi lavandino then I get the sorry I didn't get any response 

If I say: ok Google turn on lavandino then I get: sure turning on lavandino

Looks like Google has screwed something up with languages other than English

**Comment by NeoMod** [comment]
Yes, it's been ascertained that this problem only affects non-English versions of GA.

**Comment by NeoMod** [comment]
I just received a "correct answer" from Google Assistant (in Italian) while switching off a light. 

Maybe the issue has just been fixed...

**Comment by smingoli** [comment]
I can confirm that it's fixed for me too.

**Comment by FredTachet** [comment]
I have the same problem with GA and openhab, but this is only when I want to use a group : If I say switch light1 on/off, it will work normally, if I say switch room1 lights on/off, I have this message : "Sorry, I didn't get any response". Everything is working fine though and all lights are turned on/off as requested.

**Comment by hmerk** [comment]
closed due to inactivity
