### ISSUE TITLE
[astro] Thing channel properties 'offset', 'earliest' and 'latest' to additionally have day options

### ISSUE THREAD

**Issue by DigiH** [openhab/openhab-addons#6003]
The Thing channel properties 'offset', 'earliest' and 'latest' are great, especially for adjusting sun rise and set event triggers, i.e. roller shutters, heating or colling systems etc., but many of these actions want a different behaviour on weekdays compared to weekends.

While this can all be achived by defining several Things and then kicking off the same rollershutter rule for example by checking which event trigger should be used on certain days, day-dependand 'offset', 'earliest' and 'latest' definitions in a Thing channel would make things more concise and efficient.

Requiring two Things currently to have different shutter UP and DOWN times during the week and on weekends, something like this could reduce these down to one, being able to trigger the shutter rule directly, withouth having to do any further day checks:

Thing   astro:sun:shutters           [ geolocation="xx.xx,yy.yy", interval=60 ] {
    Channels:
        Type rangeEvent : rise#event [
            earliest="1-5":"06:30",
            earliest="6-7":"08:30",
            latest="1-5":"07:30",
            latest="6-7":"10:00",
        ]
        Type rangeEvent : civilDusk#event [
            offset="1-5":-20
            offset="6-7":1
        ]
}

As an example using crontab Day of the Week syntax.

## Your Environment
OpenHAB 2.4 stable
openHABian 1.5
Rapberry Pi4

**Comment by hmerk** [comment]
closed due to inactivity
