### ISSUE TITLE
[adorne] Add Adorne Binding

### ISSUE THREAD

**Issue by theiding** [openhab/openhab-addons#6011]
Create a new binding that can control Legrand Adorne wireless whole house lighting devices (https://www.legrand.us/adorne/products/wireless-whole-house-lighting-controls.aspx).

**Comment by theiding** [comment]
I have a rough prototype of this binding, but I am new to the development process so it will take a while before this will be ready for submission.

**Comment by J-N-K** [comment]
I would recommend to open a pull request as soon as possible. We can have a look at the overall design then before you spend lots of time on things that need to be changed.

**Comment by theiding** [comment]
> I would recommend to open a pull request as soon as possible. We can have a look at the overall design then before you spend lots of time on things that need to be changed.

Thank you for the review offer! One of the things I have to learn is actually how to open a pull request :-). But since my prototype is standalone JavaScript I also have to do some more homework on how to lift it into OpenHab bindings. That part should be straight forward though as the Adorne binding will be a very simple binding.  
I'll try to put something meaningful together as soon as possible.
