### ISSUE TITLE
[harmonyhub] Binding loses connection after restart or bundle installs

### ISSUE THREAD

**Issue by dbghb** [openhab/openhab-addons#6013]
I started using the 2.5 test bindings. Since then the HarmonyHub binding often loses connection to the hub after operations that cause reloading of bindings. All things including the bridge go offline. I currently cannot explain it in more detail. But looking at the binding source code there was only one change in the last period of time, so I guess it has to do with that change (that, btw. seems to be related).

I am using an Odroid N2. 
openjdk version "1.8.0_222"
Linux odroid 4.9.187-53 #1 SMP PREEMPT Fri Aug 9 06:12:18 -03 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by wborn** [comment]
> after operations that cause reloading of bindings

Do you have an example of such an operation to reproduce the issue?

**Comment by dbghb** [comment]
Just did some more investigation. I think it does definitely happen when I do a full openHAB restart, i.e. with cache and tmp dir emptied. 

This is what a log with TRACE on for the harmonyhub binding shows (already grepped with "armony")

[harmony.log](https://github.com/openhab/openhab2-addons/files/3611784/harmony.log)

Feel free to ask for more details.

**Comment by dbghb** [comment]
The light on the hub becomes red. After some more actions (like taking the hub off the power AND/OR restarting the bundle AND/OR restarting openHAB --- don't ask me what finally does it) it goes online again.

**Comment by dbghb** [comment]
Is there anything else I can do in order to help finding the cause of the problem?

**Comment by digitaldan** [comment]
>Since then the HarmonyHub binding often loses connection to the hub after operations that cause reloading of bindings.

Are you saying that other bindings are being reloaded b/c of the HarmonyHub binding?

>But looking at the binding source code there was only one change in the last period of time, so I guess it has to do with that change (that, btw. seems to be related).

What change is this?  I'm not sure what the previous version of the binding you are using, so i don't have a reference point for changes

>I think it does definitely happen when I do a full openHAB restart, i.e. with cache and tmp directories emptied.

What happens? Not sure i understand what a restart of openHAB is doing?  FYI the harmony binding does not store any local data on its own

>Is there anything else I can do in order to help finding the cause of the problem?

It would be very helpful for you to explain what actions you are taking that makes the binding go offline, what commands are being sent to OH through the binding (button presses, power on, etc...), how quickly or often you are sending them, please be exact as possible.

Also log files would be very helpful, are there any errors printed in the log file?  You can also enable debug logging through the OH console which might help us debug this `log:set DEBUG org.openhab.binding.harmonyhub`
 
 @digitaldan

**Comment by dbghb** [comment]
> > Since then the HarmonyHub binding often loses connection to the hub after operations that cause reloading of bindings.
> 
> Are you saying that other bindings are being reloaded b/c of the HarmonyHub binding?

No. 

> > But looking at the binding source code there was only one change in the last period of time, so I guess it has to do with that change (that, btw. seems to be related).

> What change is this? I'm not sure what the previous version of the binding you are using, so i don't have a reference point for changes

I saw a recent change that had the  name"ThingHandlerFactory: start on demand" on the binding's github page.  I just had the feeling that this could be related to the problem I was describing. This may be complete nonsense though.

> > I think it does definitely happen when I do a full openHAB restart, i.e. with cache and tmp directories emptied.
> 
> What happens? Not sure i understand what a restart of openHAB is doing? FYI the harmony binding does not store any local data on its own

But it is what it is. When I do a full restart, the connection to the hub breaks (this did not happen in the 2.4 release and before). After normal restarts, it can happen as well. After "apt update"s it often happens. 

In most cases, a machine reboot helps. But this is certainly not a perfect solution.

> > Is there anything else I can do in order to help finding the cause of the problem?
> 
> It would be very helpful for you to explain what actions you are taking that makes the binding go offline, what commands are being sent to OH through the binding (button presses, power on, etc...), how quickly or often you are sending them, please be exact as possible.

See above. If you need a concrete example, do an "sudo apt-get update" when a new version is available. But maybe that does not cause the effects in your environment. 

I do not need to send any commands then. I have a shell command that identifies things that go offline. And this shows me that all harmonyhub-"things" are offline. And, to no surprise, commands that I send through the hub do not work anymore.

> Also log files would be very helpful, are there any errors printed in the log file? You can also enable debug logging through the OH console which might help us debug this `log:set DEBUG org.openhab.binding.harmonyhub`

I *did* attach a TRACE log in my second post above. Maybe you did not see it.

**Comment by dbghb** [comment]
Just one more comment. As it worked perfectly before the 2.5 test release, there must be something that can be reverted so that it works again :-) I hope....

**Comment by digitaldan** [comment]
Sorry i did miss the log file.  The binding logs shows `Could not connect: java.net.NoRouteToHostException: No route to host`  , this is OS level error, can your confirm when this happens that you can ping the IP/host of the hub from that box?  Also confirm first that the IP/host in the thing configuration page in the paper UI is correct when it fails,  not sure if maybe discovery is changing that to a bad value?

**Comment by dbghb** [comment]
> Sorry i did miss the log file. The binding logs shows `Could not connect: java.net.NoRouteToHostException: No route to host` , this is OS level error, can your confirm when this happens that you can ping the IP/host of the hub from that box? 

Sure. I will check that next time. 

Although it would be a strange effect if restarting openHAB (just to name the trigger situation somehow) causes IP connection problems on the OS level. But you never know.

> Also confirm first that the IP/host in the thing configuration page in the paper UI is correct when it fails, not sure if maybe discovery is changing that to a bad value?

I do not use Paper UI (as far as possible). I prefer manual thing configuration. In this case it reads like 
`Bridge harmonyhub:hub:logitech [ host="HarmonyHub.fritz.box" ] { .... `

**Comment by dbghb** [comment]
Okay...  I could just reproduce the problem. But I can ping the hub without any problems.

Restarting the harmonyhub binding from the karaf console causes the problem to vanish in many cases by the way.

**Comment by digitaldan** [comment]
in your log file, the time seems to jump around,  do you know why?
```
2019-09-13 22:39:33.096 [TRACE] [discovery.HarmonyHubDiscoveryService] - Request packet sent to: 192.168.178.255 Interface: eth0
2019-09-13 22:40:25.278 [DEBUG] [b.internal.handler.HarmonyHubHandler] - Connecting: host HarmonyHub.fritz.box
2019-09-13 22:40:28.380 [DEBUG] [b.internal.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at HarmonyHub.fritz.box
	at com.digitaldan.harmony.HarmonyClient.getDiscoveryFromHost(HarmonyClient.java:186) ~[?:?]
	at com.digitaldan.harmony.HarmonyClient.connect(HarmonyClient.java:122) ~[?:?]
	at org.openhab.binding.harmonyhub.internal.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:281) ~[?:?]
2019-09-13 22:40:28.406 [DEBUG] [b.internal.handler.HarmonyHubHandler] - Updating listeners with status OFFLINE
2019-09-13 22:31:56.301 [.ItemChannelLinkAddedEvent] - Link 'HarmonyActivity-harmonyhub:hub:logitech:currentActivity' has been added.
2019-09-13 22:31:56.303 [.ItemChannelLinkAddedEvent] - Link 'BLRCommand-harmonyhub:device:logitech:bp420:buttonPress' has been added.
2019-09-13 22:31:56.304 [.ItemChannelLinkAddedEvent] - Link 'CandleCommand-harmonyhub:device:logitech:candles:buttonPress' has been added.
2019-09-13 22:31:56.306 [.ItemChannelLinkAddedEvent] - Link 'FlircCommand-harmonyhub:device:logitech:flirc:buttonPress' has been added.
2019-09-13 22:31:56.308 [.ItemChannelLinkAddedEvent] - Link 'LEDCommand-harmonyhub:device:logitech:leds:buttonPress' has been added.
2019-09-13 22:31:56.310 [.ItemChannelLinkAddedEvent] - Link 'LMCommand-harmonyhub:device:logitech:lightmanager:buttonPress' has been added.
2019-09-13 22:31:56.312 [.ItemChannelLinkAddedEvent] - Link 'MRCommand-harmonyhub:device:logitech:mr401b:buttonPress' has been added.
```
Also can you list more of the log ?  We should try reconnecting after 60 seconds `RETRY_TIME = 60`  , i would like to see what happens there as well.

**Comment by dbghb** [comment]
Regarding the jumping time stamps: No, I just grepped through the file but that keeps the sequence intact as we all know.

I will come up with a better/longer log soon.

**Comment by dbghb** [comment]
There you go. TRACE switched on.  Left it running for a while. Grepped for -i Harmony.

Finally restarted the harmonyhub binding in the karaf console. You should see that it worked again. 

I fuzzed out my email address  to not endanger my email account from getting flooded by spam. 

[harmony2.log](https://github.com/openhab/openhab2-addons/files/3629820/harmony2.log)

**Comment by digitaldan** [comment]
The binding is having troubling establishing a connection to the hub:
```
Could not connect to HarmonyHub at HarmonyHub.fritz.box
	at com.digitaldan.harmony.HarmonyClient.getDiscoveryFromHost(HarmonyClient.java:186) ~[?:?]
	at com.digitaldan.harmony.HarmonyClient.connect(HarmonyClient.java:122) ~[?:?]
	at org.openhab.binding.harmonyhub.internal.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:281) ~[?:?]

```

Do any commands work?  Does it ever go online?  The last log file shows it did not ever become ONLINE. 

What version of the binding were you using previously ?  The reason i ask is that the binding was rewritten in 2.5 to use websockets rather then xmpp when Logitech decided to remove support for that protocol.  I don't think this change made it into the 2.4 branch, but it was a while ago, and i can't remember now.   In any case, do you know what  firmware version your hub is on?

**Comment by dbghb** [comment]
Sure. It works most of the time. It only loses connection under the mentioned circumstances. Hub firmware version is 4.15.250.

**Comment by dbghb** [comment]
Just some simple questions as I don't want to read (Java) source code... Would the binding get aware of the fact that it does not have a connection anymore? I suppose it does. But, if so, doesn't it try to connect again or does fail in doing so?

**Comment by digitaldan** [comment]
>Just some simple questions as I don't want to read (Java) source code... Would the binding get aware of the fact that it does not have a connection anymore? I suppose it does. But, if so, doesn't it try to connect again or does it fail in doing so? 

The binding is aware of its connection status, it sends heartbeat packets  frequently, and of course it tries to reconnect if it detects a failure.  

>What version of the binding were you using previously ?
 
can you answer this question from my previous post ?

>If the trace log does not show enough info, you could provide me with a modified one that shows even more

You can enable protocol level logging  of the harmony client lib
`log:set DEBUG com.digitaldan.harmony`

Also can you supply a complete log from systems start and to when it goes online, then offline? and not using grep?  I never see the binding go online in you last log, if you need to pm it to me , send an email to dan at digitaldan dot com .  I'm not sure if there are lines i am missing that may explain the reason for the failure.   

>It only loses connection under the mentioned circumstances. 

Ok, i think that was not clear to me. So it connects fine when the system loads, but if you make a change that causes  the system to reload bindings, it fails to connect?  Does it always do this?  Does it ever reconnect?  Do you see it trying continually in the logs trying to do so? 

>I think it does definitely happen when I do a full openHAB restart, i.e. with cache and tmp directories emptied.

re-reading this, i think i am also confused, so if you restart OH it does not connect?  When does it connect then?  

One last thing, what other bindings do you have loaded?  I  have seen issues in the past that i could not explain where http calls fail when too many bindings are trying to make connections at the same time.  I think its a long shot thats the case.

**Comment by dbghb** [comment]
> The binding is aware of its connection status, it sends heartbeat packets frequently, and of course it tries to reconnect if it detects a failure.

Sure. It was a bit unfair to ask :-)
> 
> > What version of the binding were you using previously ?
> 
> can you answer this question from my previous post ?

The one from the regular 2.4 release.

> > If the trace log does not show enough info, you could provide me with a modified one that shows even more
> You can enable protocol level logging of the harmony client lib
> `log:set DEBUG com.digitaldan.harmony`

Okay. I will use that. Log will follow.

> Also can you supply a complete log from systems start and to when it goes online, then offline? and not using grep? I never see the binding go online in you last log, if you need to pm it to me , send an email to dan at digitaldan dot com . I'm not sure if there are lines i am missing that may explain the reason for the failure.

Will do.

> > It only loses connection under the mentioned circumstances.
> 
> Ok, i think that was not clear to me. So it connects fine when the system loads, but if you make a change that causes the system to reload bindings, it fails to connect? Does it always do this? Does it ever reconnect? Do you see it trying continually in the logs trying to do so?

As you may certainly be afraid of, this is not deterministic. Normally I do another openhab restart and sometimes a system reboot and then it gets online again. It sometimes helped to just restart the only the binding.

> > I think it does definitely happen when I do a full openHAB restart, i.e. with cache and tmp directories emptied.
> 
> re-reading this, i think i am also confused, so if you restart OH it does not connect? When does it connect then?

See above. I would really like to give you a definitive sequence of steps so that it either works or does not work, but this is not possible. 

> One last thing, what other bindings do you have loaded? I have seen issues in the past that i could not explain where http calls fail when too many bindings are trying to make connections at the same time. I think its a long shot thats the case.

**That** sounds promising to me. It could explain the quite erratic behaviour. 

These are my addons:
`
binding = amazonechocontrol,astro,avmfritz,exec,expire1,fritzboxtr0641,ftpupload,harmonyhub,homematic,hue,ipp,lgwebos,logreader,mail,network,systeminfo,tado,weather1,wol1,zwave1

ui = basic,paper,habmin,habpanel

persistence = mysql

action =

transformation = map,regex,javascript,jsonpath

misc = openhabcloud,hueemulation,market

`
----

I just tried to produce the log with the settings that you proposed but this time the problem did not show (what else could we expect?). 

I have to leave now though and will retry tomorrow or on Monday. Thanks for your engagement.

**Comment by dbghb** [comment]
Believe me or not...... When I switch on `log:set DEBUG com.digitaldan.harmony` I cannot reproduce the problem anymore :-) I tried it in various ways but to no success. 

Let us be optimistic and regard this as a hint as to the cause (subtle timing issues or something like that).

Anyway I will keep on trying to reproduce the problem with a useful log.

**Comment by dbghb** [comment]
Dan did you receive my mail with the full log or shall I send it again?

**Comment by digitaldan** [comment]
I did receive it, but have not had time to troubleshoot it as in depth as i would like to.  what has stood out to me so far, is this line, which is not something i have seen before:

```
2019-09-23 21:48:44.282 [DEBUG] [b.internal.handler.HarmonyHubHandler] - Connecting: host HarmonyHub.fritz.box
2019-09-23 21:48:44.285 [WARN ] [e.jetty.util.thread.QueuedThreadPool] - QueuedThreadPool[HttpClient@2eefda5e]@6b7b3ad5{FAILED,8<=0<=200,i=0,r=-1,q=2}[NO_TRY] rejected org.eclipse.jetty.io.ManagedSelector$$Lambda$165/592144723@679241cb
2019-09-23 21:48:44.287 [DEBUG] [b.internal.handler.HarmonyHubHandler] - Could not connect to HarmonyHub at HarmonyHub.fritz.box
java.io.IOException: org.eclipse.jetty.io.ManagedSelector$$Lambda$165/592144723@679241cb
	at com.digitaldan.harmony.HarmonyClient.connect(HarmonyClient.java:119) ~[?:?]
	at org.openhab.binding.harmonyhub.internal.handler.HarmonyHubHandler.connect(HarmonyHubHandler.java:281) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

```
The QueuedThreadPool rejected our attempt to get a thread to make a connection, as if the thread pool has been exhausted.  Furthermore,  the original websocket was closed with a 1006 error, which is an abnormal close event, as if the system was out of resources.  It does seem as if something is starving your system of resources.

**Comment by dbghb** [comment]
Hmmm... It could also be another binding running wild. But we should not forget that things worked perfectly until I switched over to the 2.5 test release. So there must be a solution to this.

**Comment by ppieczul** [comment]
It may be something or nothing, probably worth checking. I recall there has been a bug in jetty websocket that prevented the threads from finishing correctly unless the thread pool had explicitly set stop timeout to zero.
I remember implementing it in my binding, you can see in this file: https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java

The source of the defect finding and fix is here: https://github.com/eclipse/smarthome/pull/6636

**Comment by digitaldan** [comment]
Thanks @ppieczul !  I was also looking at that., I am refactoring the library to use the shared jetty instance from OH.  I probably should have done this in the first place.  I noticed in your binding you are using your own version of the jetty client rather then the shared version, any reason for that (related to this) ?

**Comment by digitaldan** [comment]
>So there must be a solution to this.

No one is saying  there is not a solution to this.

**Comment by dbghb** [comment]
No one said that anybody else said that there is no solution to this :-) I just tried to keep myself optimistic. 

So if you need any more help, please do not hesitate to contact me.

**Comment by digitaldan** [comment]
:-)

**Comment by ppieczul** [comment]
No reason for the own version. I did not put a separate library for that
and frankly speaking I don’t know which version is pulled in. Can you show
me where do you deduct this and how to use the shared version?
Thanks
Pawel

**Comment by digitaldan** [comment]
@dbghb can you remove the harmony binding , and download and load the one here instead ?  The only change i made was to use the OH supplied jetty client, which has some optimizations in it.  I'm not sure why the socket is disconnected in the first place, but hopefully reconnects are smoother
https://github.com/digitaldan/openhab2-addons/releases/tag/harmony-2.5-jetty-fix-1

>Can you show me where do you deduct this and how to use the shared version?

See my iAqualink binding for an example, the Jetty client can be injected into your handler factory, then you can pass it to your handler when being created

https://github.com/openhab/openhab2-addons/blob/5ea0d779b593a7718328baa88a5773c5f3c80a96/bundles/org.openhab.binding.iaqualink/src/main/java/org/openhab/binding/iaqualink/internal/IAqualinkHandlerFactory.java#L57

**Comment by digitaldan** [comment]
@ppieczul i should elaborate a bit more, you can then pass the httpclient into the websocket class when constructing  it, and not deal with any threads

**Comment by digitaldan** [comment]
I should elaborate a bit more, you can pass the httpclient into the WebSocket class when constructing it here:
https://github.com/openhab/openhab2-addons/blob/5ea0d779b593a7718328baa88a5773c5f3c80a96/bundles/org.openhab.binding.loxone/src/main/java/org/openhab/binding/loxone/internal/LxServerHandler.java#L177

And remove all the threading you have around the client

**Comment by ppieczul** [comment]
Beautiful, thank you very much Dan. I will try that.

W dniu pt., 27.09.2019 o 19:45 Dan Cunningham <notifications@github.com>
napisał(a):

**Comment by ppieczul** [comment]
@digitaldan there is actually no WebSocketClient constructor that takes HttpClient, but I can pass SSLContextFactory, Executor and ByteBufferPool directly and I can get them from the httpClient. Would that be advisable? I can't predict whether all these resources are ok to be reused from the default HTTP client. I can pass only Executor, but why not ByteBufferPool too (and SSL context factory must be passed together anyway).

**Comment by digitaldan** [comment]
See https://www.eclipse.org/jetty/javadoc/current/org/eclipse/jetty/websocket/client/WebSocketClient.html#<init>(org.eclipse.jetty.client.HttpClient)  

Maybe you are using an old version ?  I am doing this my harmony library now, let me push my branch and i will link to it.

**Comment by digitaldan** [comment]
See https://github.com/digitaldan/harmony-client/blob/09f07cd01c237d17cec45b4dfb147436362fade8/src/main/java/com/digitaldan/harmony/HarmonyClient.java#L456

**Comment by ppieczul** [comment]
@digitaldan indeed, I have version 9.3.25.v20180904 of jetty and websockets. This is displayed in the Maven dependencies in Eclipse.
Unfortunately I have no idea how to update to a newer version. This is not something I specified in the binding, so I suppose it is some property of my whole environment. Can you help me with this?

**Comment by digitaldan** [comment]
The version in OH core is 9.4.11 for all jetty libraries, including websockets.  Are you building against OH 2.5  and are your local sources in sync with master ?

https://github.com/openhab/openhab-core/blob/fa416be05771bdeefb7d660aea30a03767287060/bom/runtime/pom.xml#L19

**Comment by ppieczul** [comment]
@digitaldan I did not have openhab-core at all (I selected only development and bindings during installation).
So I installed it fresh with openhab-core, but it does not seem to be used to determine the dependencies. I still have those old versions as a dependency, for all components, also in openhab-core. I have no idea where it comes from. There are two bndrun.app files inside openhab-distro that also specify the new version. Any ideas how the dependencies work here?
I am also wondering how to run it from openHAB today - there is no openHAB_runtime configuration anymore (or I can't see it). Thanks for your help.

**Comment by dbghb** [comment]
I just returned from a short trip. Any updates for me? 

It looks to me like the initial description ("Binding loses connection after restart or bundle installs") was not incorrect, but does not really describe what happens in the sense of causality. The effect happens in more situations. My assumption is that it happens under higher system load, but I leave it to the experts.

**Comment by dbghb** [comment]
Problem does not occur anymore. Thanks guys.

**Comment by dbghb** [comment]
I closed this one because if looks like the problem is solved. I don't see any problems anymore.

Thanks  @digitaldan and @ppieczul .

**Comment by digitaldan** [comment]
My fix has not yet been submitted, doing that today.
