### ISSUE TITLE
[yeelight] Smart LED Bulb Colorful 800 Lumens 10W E27 not supported

### ISSUE THREAD

**Issue by hartmood** [openhab/openhab-addons#6015]
[Xiaomi Yeelight Smart LED Bulb Colorful 800 Lumens 10W E27 Lemon Smart Lamp For Mi Home App White/RGB Option
](https://www.aliexpress.com/item/32885328641.html?spm=a2g0s.9042311.0.0.77084c4depxbba)

doesn’t seem to be supported. At least it does not show up in my inbox as usually all the other devices do. 

Is there a chance to support it?

**Comment by dote78** [comment]
I've got them working using "wonder", and you can turn them on and off, but if you turn them on outside Openhab using Yeelight app or Alexa, the status is not updated on openhab (wich is a bugger):

On things file:
Thing yeelight:wonder:entrada [ deviceId="0x00_whatever_0000" ]

on items file:
Switch Y_Entrada_Switch { channel="yeelight:wonder:entrada:color" }

**Comment by hmerk** [comment]
closed due to inactivity
