### ISSUE TITLE
[homekit] Dynamic group label is not read

### ISSUE THREAD

**Issue by MortenVinding** [openhab/openhab-addons#6018]
It seems that the HomeKit binding only reads the thermostat group label from items files.
It will not honor a group label set dynamically by a rule, using the:
<item-name>.label = "name"
function.

If no group label is set in the items definition it just shows up as "Unavailable" in HomeKit.

It has been discussed here: https://community.openhab.org/t/dynamic-group-label-is-not-read/81150

**Comment by yfre** [comment]
@MortenVinding  in case you still interested in dynamic names - homekit integration has now a dedicated characteristic with the tag "name" which can be set dynamically. integration will also notify home app about the change
e.g.
```
Group  gLeakSensor    						"Leak Sensor Group"       									{homekit = "LeakSensor"}
Switch leaksensor 							"Leak Sensor" 							(gLeakSensor) 		{homekit = "LeakDetectedState"}
String leaksensor_name 					"Leak Sensor Name" 						(gLeakSensor) 		{homekit = "Name"}
```

**Comment by MortenVinding** [comment]
Thanks @yfre.
Unfortunately I'm not using OpenHAB anymore so not so relevant to me, but it looks to be a cool way of implement it. 

> @MortenVinding in case you still interested in dynamic names - homekit integration has now a dedicated characteristic with the tag "name" which can be set dynamically. integration will also notify home app about the change
> e.g.
> 
> ```
> Group  gLeakSensor       "Leak Sensor Group"                    {homekit = "LeakSensor"}
> Switch leaksensor        "Leak Sensor"          (gLeakSensor)   {homekit = "LeakDetectedState"}
> String leaksensor_name   "Leak Sensor Name" 	(gLeakSensor)   {homekit = "Name"}
> ```

**Comment by yfre** [comment]
closing ticket as the issue is solved as described above.
