### ISSUE TITLE
[yeelight] Bugs and the try to fix them... Need help! Also Yeelight Meteorite support!

### ISSUE THREAD

**Issue by darkcheater** [openhab/openhab-addons#6026]
Hello,

I have a few Yeelight products and I like them as they are relatively cheap and of high quality.
I'd of course like to integrate them into openHAB.
The current yeelight binding kinda works sometimes but often the devices are found offline although they are in fact online.

Also there are quite a few bugs with the current binding:
- if you set the log level to DEBUG you'll notice that there is quite a lot happening because the discovery message is sent in a loop and the sent message is also being received **[fixed in my fork]**
- the color temperature is implemented the wrong way round, 0% is warm white although Alexa and Hue for example work the other way around (0% is cold white and 100% is warm white) **[fixed in my fork]**
- and as I also mentioned earlier, it has a problem with recognizing the online state... In my branch, the communication/discovery seems to be perfectly fine but somehow the construction of the objects or something I don't understand must be wrong. **[still problematic! need help here]**

@jakaZ0806 started adding support for the Yeelight Meteorite, which is a great light that has 2 light sources in one light, main and background light.
https://github.com/jakaZ0806/openhab2-addons/tree/yeelight-meteorite-support/bundles/org.openhab.binding.yeelight

I created a fork of his fork as there were a few little bugs and also I couldn't get it to work in my environment...
I would be very glad if someone could have a look and help me, as I am kinda stuck now...

Here is the link to my fork:
https://github.com/darkcheater/openhab2-addons/tree/yeelight-meteorite-support/bundles/org.openhab.binding.yeelight

**Comment by gt-de** [comment]
Hi,
I'm looking for a solution with the yeelight meteorite. I build your .jar, but the discovery does not work and there is no yeelight meteorite for manuel configuration.
with the XIAOMI MI IO Binding I get the lamp working, but only ON/OUT.

Did I someting wrong? How to configure with your solution?

**Comment by darkcheater** [comment]
[org.openhab.binding.yeelight-2.5.0-SNAPSHOT.zip](https://github.com/openhab/openhab2-addons/files/3721178/org.openhab.binding.yeelight-2.5.0-SNAPSHOT.zip)
Strange, discovery was working fine for me, I only had problems with the online state.
This build seems to work for me now. It somehow repaired itself.. I don't know what happens, if I have to restart my instance but you can try it and see if it works for you. (rename the file to .jar)

**Comment by gt-de** [comment]
Thanks for help. Discovery works. The other things I try tomorrow.

Thanks therefor.

**Comment by KorbinianP** [comment]
Hello, any update?

**Comment by claell** [comment]
Thanks for improving the binding! Maybe you can already create PRs for the things you already fixed? Then the outstanding point can be fixed independently of them.

**Comment by TheOriginal92** [comment]
Thank you all for the great work!
May i ask if the Yeelight Meteorite is now fully supported?

**Comment by OlliKantola** [comment]
At least on my OH3 installation I couldn't get Yeelight Meteorite recognised with yeelight binding. I did some tests with [yeelight python library](https://yeelight.readthedocs.io/en/latest/) and noticed that there isn't that many differences compared to ceiling4 (already supported by yeelight binding). I got the ceiling10 (Yeelight meteorite) working except ambilight brightness can't be controlled.

@darkcheater If you are still interested in controlling Meteorite via yeelight binding please take a look at my fork: https://github.com/OlliKantola/openhab-addons/tree/main/bundles/org.openhab.binding.yeelight

**Comment by hmerk** [comment]
closed as related PR was merged
