### ISSUE TITLE
[nuki] Support for the Opener device

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#6041]
The Nuki bindings does not yet support the new Nuki Opener device.

**Comment by jmahmens** [comment]
I'm an owner of this Opener device and may help testing.

**Comment by KenkiCK** [comment]
I'm too and can also help testing

**Comment by andrelung** [comment]
In case you didn't notice: the linked solution is working just fine. However there is some check missing to include it into the main codebase.

**Comment by lolodomo** [comment]
Closing in favor of #10671
