### ISSUE TITLE
[hueemulation] Echo not detecting devices on version > 2.5m2

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhab-addons#6042]
Hello Hope I am saying it all correctly.  I am trying to use Hue Emulation on 2.5m2, now m3.  My echo will not discover devices on these versions.  I started with a know working setup on 2.5m1, I have been running this setup since 2.3 with no issues.   When I upgraded a couple months ago from 2.5m1 to 2.5m2 I found the hue emulation did not function for me.  

**Happy to give more info, let me know what you need**

Here is the output of http/myip/api/testuser/lights "Do code fences not work for json?"

```json
{
    "2": {
        "state": {
            "on": false,
            "reachable": true,
            "mode": "homeautomation",
            "alert": "none"
        },
        "type": "On/off light",
        "modelid": "Plug 01",
        "uniqueid": "752d46b2-0dd8-4345-a081-9fed205659fc-2",
        "manufacturername": "OSRAM",
        "productname": "On/Off plug",
        "swversion": "V1.04.12",
        "hascolor": false,
        "name": "",
        "config": {
            "archetype": "classicbulb",
            "function": "functional",
            "direction": "omnidirectional"
        },
        "capabilities": {
            "certified": false,
            "streaming": {
                "renderer": false,
                "proxy": false
            },
            "control": {}
        }
    },
    "3": {
        "state": {
            "bri": 0,
            "ct": 500,
            "on": false,
            "reachable": true,
            "mode": "homeautomation",
            "alert": "none"
        },
        "type": "Color temperature light",
        "modelid": "LTW001",
        "uniqueid": "752d46b2-0dd8-4345-a081-9fed205659fc-3",
        "manufacturername": "Philips",
        "swversion": "66012040",
        "friendsOfHue": true,
        "colorGamut": "2200K-6500K",
        "hascolor": false,
        "name": "",
        "config": {
            "archetype": "classicbulb",
            "function": "functional",
            "direction": "omnidirectional"
        },
        "capabilities": {
            "certified": true,
            "streaming": {
                "renderer": false,
                "proxy": false
            },
            "control": {}
        }
    }
}
```

**Comment by wborn** [comment]
The code fences also work for JSON, see your edited comment. ;-)

**Comment by wborn** [comment]
Maybe it's similar to https://github.com/openhab/openhab2-addons/issues/5607? Do you see the same exceptions?

**Comment by thedannymullen** [comment]
Must have done something wrong when I tried code fences.  Thanks for edit.

Yes it is similar I need to install on a test box to test one more time and capture details.  I remember lots of Java error issues though.

I am ok if you want to close mine referencing the other as I am fairly confident that once you guys dive into the code it will all be resolved.  I can follow the other one and even test builds since they sound similiar.

**Comment by thedannymullen** [comment]
Following this topic here

https://github.com/openhab/openhab2-addons/issues/6121
