### ISSUE TITLE
[loxone] Token not clearing out, once expired. 

### ISSUE THREAD

**Issue by jatin-28** [openhab/openhab-addons#6048]
#Expected Behavior
After a certain period of time the token expires and needs to be refreshed. If this fails, a new handshake agreement needs to occur

## Current Behavior
After x months or so, I've noticed that loxone tends to fail. Haven't pin pointed the exact scenario but loxone is offline. (could be after a loxone config change on the server) 
Restarting openhab doesn't work. 
Instead clearing the cached token in the openhab loxone binding config, allows reauthentication. 

Environment:using latest version of github loxone addon. 

#possible solution
If token retry fails, evict token and try reauthentication from scratch.

**Comment by ppieczul** [comment]
Hi @jatin-28. Probably some problem with token refresh. 
The re-submission you suggest is not possible unless we decide to store the password. Currently after successful token gain, the password is cleared in the configuration, so nobody can steal it. This is kind of the way it should work.
Could you see if you have any traces in the log from around it failed?
Thanks
Pawel

**Comment by jatin-28** [comment]
That's true! (thought it was stored but it was my browser). Sounds to me though this is a bigger issue and requires a notification to an email or something to say hey login again.

**Comment by ppieczul** [comment]
@jatin-28 the token has an expiration date and there is a mechanism in the API to refresh the validity of the token. I suppose either there is a bug in the binding or in the Miniserver. The refresh is scheduled for several weeks or months in the future, so it is not often that it is needed and the problem might have not surfaced yet, because the Loxone applications do not maintain the connection for that long. I will try to write a unit test for that with a shortened expiration.
Anyway, if you have any logs, they could help a lot.
Thanks

**Comment by jatin-28** [comment]
With loxone it allows you to perform a refresh with the older token. However, I think rebooting the server causes the tokens to be cleared. Either that or the refresh call isn't being made at the right time.

**Comment by jatin-28** [comment]
I'll try and find logs for this, or try and recreate the issue at some point as well.

**Comment by ppieczul** [comment]
Thanks. I am sure I had multiple server reboots also due to power outage,
but I have not re-entered the password for months now, so it must have
logged in with a token. I have not yet had time to look into it.

śr., 18 wrz 2019 o 09:11 jatin-28 <notifications@github.com> napisał(a):

**Comment by ppieczul** [comment]
@jatin-28 did anything like that happen again? I checked logs of my installation and found a correctly performed token refresh. It happens once per 54 days, so it is hard to reproduce on the real installation.

**Comment by jatin-28** [comment]
@ppieczul Sorry - have been very tied up at the moment. It happens quite regularly. Just havent had the chance to analyse the logs - takes a while due to the amount of data to try and figure out at what point it stopped as it could be over a few days.

**Comment by hmerk** [comment]
closed due to inactivity
