### ISSUE TITLE
[exec] Autorun to accept duplicated commands

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#6052]
Current behaviour:
Exec binding offers an `autorun` option on Things.
This listens for commands to Thing `input` string channel, and upon receiving a command triggers an execution of the user defined script.  The command string content may be used for parameter substitution in the script call.
Should a new command have the same string content as the previous command, it is ignored. To rephrase, a **different** command must be sent every time script execution is desired.  The command must be different, even when it serves only as trigger and is not actually used as parameter.

This is counter intuitive, and is unlike the behaviour of other bindings.  There seems no technical reason to suppress a second request or to assume it is an unwanted repeat or duplicate.
When using the `interval` or 'run switch' options for periodic execution, there is no such limitation on repeated runs with same input string.

Requested behaviour:
For an on demand script to run with same parameters, simply allow "duplicate" commands in autorun mode.

There are of course workaround methods (see docs), so this should be regarded as a low priority request.

It is possible someone is actually taking advantage of this effect, so it might be regarded as a possible breaking change.

With OH3 in view it may well be sensible to delay until then, if implemented at all.

**Comment by hmerk** [comment]
closed due to inactivity
