### ISSUE TITLE
[bluetooth] Item on rssi channel won't update (stable 2.4)

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab-addons#6054]
## Expected Behavior
After the creation of a Number type item and the link creation to a new iBeacon General Bluetooth thing, updating of rssi values.

## Current Behavior
I'm trying to make the Bluetooth binding working, as bridge I'm using the integrated one.
Bridge is working properly, thing is in ONLINE status and if discovery is enabled the inbox shows all the devices discovered.
When I create a new general iBeacon Bluetooth thing (both manually and automatically) its state is always UNKNOWN until I link it to an item (that's already an issue I think), then goes ONLINE and the item is updated with the rssi value.
The issue is that the value doesn't change anymore. I tried with 2 devices, first an iPhone SE, but since I'm aware it can be tough I bought a Gigaset G-tag, but the behavior is the same, the rssi values is not updated.
The iBeacon tag is founded if I run:
`sudo hcitool lescan`
The android app Bluetooth 4.0 Scanner shows the tag with the different values of rssi.

## Your Environment
* Version used: openhab 2.4 (manual install), bluetooth 2.4
* Operating System and version: raspian stretch, BlueZ 5.43

**Comment by mortommy** [comment]
After the uninstall of the binding and the re-install the error disappeared, but the issue is still there, no item updates.

**Comment by pmknowles** [comment]
I have a similar issue  Binding finds new devices but the RSSI value doesn't change (even if the device is turned off).
I'm sure that it used to work and I haven't changed anything.

**Comment by pmknowles** [comment]
I have a similar issue. Devices appear in the Inbox and can be added but the RSSI doesn't appear to change (even if the device is turned off or not present).
I'm sure it used to work and I haven't changed anything.

**Comment by hmerk** [comment]
closed due to inactivity
