### ISSUE TITLE
[deconz] GW config based Websocket discovery fails on docker et al

### ISSUE THREAD

**Issue by ignidis** [openhab/openhab-addons#6072]
The DECONZ BINDING configuration attempts to find the port for the Websocket Interface by reading the DECONZ Gateway Configuration.
In situations where the DECONZ API is containerized, or if the DECONZ Application websocket port does not represent the port exposed by the Host, this discovery method fails. 

**Example** : 
DECONZ Application running in container, internal port 443 - as per default - external Container Port 8443 ... DECONZ BINDING tries to communicate with 443 and fails.

**Proposed Solution** : 
Add an optional WEBSOCKET PORT Parameter to the Gateway Thing configuration. If the parameter is set it shall override the auto discovery value, if not set the auto discovery value shall be used.

**Comment by cweitkamp** [comment]
Did you try to modify the `host` parameter and add the port? Like this `xxx.xxx.xxx.xxx:yyyy`?

**Comment by jwveldhuis** [comment]
Same here. Running Deconz on Docker on port 9080 and Websocket on 9443. When I update the Thing to xx.xx.xx.xx:9080 the Thing becomes online. When I then manually add a Thing through the Hue binding (discovery doesn't work) and selecting the Deconz GW, the port number is lost from the Thing configuration and the Deconz GW thing is offline.

**Comment by jwveldhuis** [comment]
(Nevermind my previous comment, I was using the Hue binding while adding the Deconz Gateway..)

**Comment by ignidis** [comment]
@cweitkamp 
Yes, sure.
The issue is not with the host definition - this is the Docker container external port; the issue is the internal side of the container where openhab / the bindings are running. Basically you need two parameters to be able to resolve this, the one for the host that indicates other external devices how to contact openhab and the internal for the binding that indicates the binding how to access the container internally.
You may want to look at the most current version of the Homematic Binding; they had a similar issue and resolved it by adding the internal parameter and the behavior indicated in my resolution proposal.

**Comment by ignidis** [comment]
Just as clarification to the above, the Homematic case.
They use a parameter call CALLBACK NETWORK ADDRESS for the external docker address + port and BIND ADDRESS for the internal docker container address + port.
For example : 
CALLBACK = 192.168.1.2:8443 <- public visible but not available to container
BIND = 172.15.0.1:443 <- only accessible in the container / internal docker network but not outside

**Comment by cweitkamp** [comment]
Thanks for clarification. I should be no big deal to add a dedicated parameter for the port. I will look into it.
