### ISSUE TITLE
[enocean] removing of manually defined things doesn't work

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#6083]
I have a FAH60 sensor, which I had defined as a generic thing in a file. With the new Binding 2.5.0 M3, I want to replace it by a defined thing. The definition has been deleted in the .things file, but the thing is still in PaperUI. If I try to remove it there (in PaperUI), I get the following error and the thing still remains. I had to delete it manually in the file `/var/lib/openhab2/jsondb/org.eclipse.smarthome.core.thing.Thing.json`
```
2019-09-15 10:20:07.574 [ERROR] [core.thing.internal.ThingManagerImpl] - The ThingHandler caused an exception while handling the removal of its thing
java.lang.NullPointerException: null
	at org.openhab.binding.enocean.internal.handler.EnOceanBaseActuatorHandler.handleRemoval(EnOceanBaseActuatorHandler.java:236) ~[?:?]
	at org.eclipse.smarthome.core.thing.internal.ThingManagerImpl$7.run(ThingManagerImpl.java:968) [184:org.openhab.core.thing:2.5.0.M3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]

```

Probably related:
I changed the Thing definition as seen below from lightSensor to genericThing. As it should, PaperUI shows the definition of the genericThing, but the lightSensor seems to remain somewhere:
`2019-09-16 19:39:05.611 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler EnOceanBaseSensorHandler of thing enocean:lightSensor:FT1ZI6SV:OutdoorLightSensorWest tried checking if channel Lux is linked although the handler was already disposed.
`
```
Bridge enocean:bridge:FT1ZI6SV "EnOcean Gateway" @ "Flur EG"
[
	path="/dev/ttyUSB0"
]
{
	Thing genericThing OutdoorLightSensorWest "Außenlichtsensor West" @ "Garten"
	[
      enoceanId="0582D29D",
      sendingEEPId="A5_FF_FF",
      broadcastMessages=true,
      receivingEEPId="A5_FF_FF",
      suppressRepeating=false
	]
	{
    Channels:
      Type genericNumber : genericNumber [ transformationType="JS", transformationFunction="EnOcean_FAH60.js" ]
      Type genericString : genericString [ transformationType="JS", transformationFunction="EnOcean_FAH60.js" ]
  }

/*
	Thing lightSensor OutdoorLightSensorWest "Außenlichtsensor West" @ "Garten"
	[
		enoceanId="0582D29D",
//		receivingEEPId="A5_06_01"
		receivingEEPId="A5_06_01_ELTAKO"
	]
	{
    Channels:
      Type illumination: Lux
			Type lastReceived: LastReceived
			Type repeatCount: RepeatCount
			Type rssi: RSSI
  }
*/
}
```

I'm using openhab 2.5.0 M3 on Raspbian GNU/Linux 9 (stretch).

**Comment by mister78** [comment]
Hi UrsusS,
I am actually trying to get the FAH60 work with V2.4. When I understand your post right, the only thing which is missing therefore ist the JS transformation function. Could you post it here for everyone to have a look at it? Or is something else missing?
Thanks alot.
P.S: If you think it should not be posted here I would be glad about a PM with the code :)

**Comment by UrsusS** [comment]
Hi mister78,
I'm using the transformation below to get the raw values and a rule to interpret it.
It is not perfect, especially as I can't reach the additional values for values < 300 lux.
If you have a better solution, it would be nice if you could share it.

```
/* aus OpenHAB Community, angepasst
*/
(function(inputData) {

  var parts = inputData.split('|'),
      hexToBytes = function(hex) {
      for (var bytes = [], c = 0; c < hex.length; c += 2)
      bytes.push(parseInt(hex.substr(c, 2), 16));
      return bytes;
  };
  
  if(!parts || parts.length != 2)
      return null;
  
  var b = hexToBytes(parts[1]);
  switch(parts[0]){
      case "genericSwitch":
          if(b[1] == 1){
              return "OnOffType" + "|" + "ON";
          } else if(b[1] == 2){
              return "OnOffType" + "|" + "OFF";
          }
          break;
          
      case "genericRollershutter":
          break;
          
      case "genericDimmer":
          break;
      
      case "genericNumber":   // Spannung im Sensor 0 .. 255 -> 0 .. 5.1 V
          return "DecimalType" + "|" + (b[0] * 5.1 / 255);
          break;
          
      case "genericColor":
          break;
          
      case "genericString":   // alle Daten zurückgeben
          return "StringType" + "|" + parts[1]; //b[0];
          break;
    }

    return (inputData);
})(input)
```
```
rule "Auswertung"
when
	Item str_Garten_Helligkeit_Raw changed
then
  // Aufbau vom String:
	//  +0: Versorgungsspannung
	//  +2: Helligkeit
	//  +4: Helligkeit (immer 0)
	//  +6: (immer 0)
	//  +7: div. Bits

  val String Raw = str_Garten_Helligkeit_Raw.state.toString
	val String Hex = Raw.substring(2, 4)
	var Number Value = Integer.parseInt(Hex, 16) as Number

  // Skalierung: 0..255 -> 300..30000 lux
	Value = Value * 30000/255
	if (Value < 300)
		Value = 0
	num_Garten_Helligkeit.postUpdate(Value)

end
```

**Comment by mister78** [comment]
Hi UrsusS,
uuh, that looks more complicated than I expected.
First thanks a lot for sharing. I will let you know when I managed to run it or even improve the code.

**Comment by mister78** [comment]
Hi Ursus,
ich changed the transformation function code, so that the additional rule is not necessary anymore.
I also included the low light range, but I think either my sensor is a bit strange or the specification values are not very precise. Anyway for my use case it is accurate enough.

![fah60spec](https://user-images.githubusercontent.com/36990973/66832093-74126080-ef59-11e9-9e5b-508cd06b9c2c.PNG)

`(function(inputData) {
  var logger = Java.type("org.slf4j.LoggerFactory").getLogger("fah60.js"); 
  logger.warn(inputData); 
	
  hexToBytes = function(hex) {
      for (var bytes = [], c = 0; c < hex.length; c += 2)
      bytes.push(parseInt(hex.substr(c, 2), 16));
      return bytes;
  };
  
  var parts = inputData.split('|');

  if(!parts || parts.length != 2)
      return null;
  logger.warn(parts[0]); 
  logger.warn(parts[1]); 
  
  var b = hexToBytes(parts[1]);
  logger.warn(b); 

  switch(parts[0]){
      case "genericSwitch":
          break;
          
      case "genericRollershutter":
          break;
          
      case "genericDimmer":
          break;
      
      case "genericNumber":   // Helligkeitswerte in lx
	  if (b[1]==0) {
		 return "DecimalType" + "|" + b[0];
	  }
	  else {
		 return "DecimalType" + "|" + (300.0 + b[1]/255.0 *29700.0);
	  }
          break;
          
      case "genericColor":
          break;
          
      case "genericString":   // alle Daten als String zurückgeben
          return "StringType" + "|" + parts[1];
          break;
    }

    return (inputData);
})(input)`

I hope this can help..

**Comment by UrsusS** [comment]
Thanks for posting this!

**Comment by hmerk** [comment]
closed due to inactivity
