### ISSUE TITLE
Binding debug in a maven/bnd world

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab-addons#6086]
Do we have any plans on how we are going to standardize binding debugging now that we support multiple IDEs?

Visual Studio [has people creating a bunch of files in all the projects](https://www.openhab.org/docs/developer/ide/vscode.html)
Eclipse [has people adding things to app.bndrun](https://www.openhab.org/docs/developer/ide/eclipse.html)
Intellij [has a video showing you how to load it from karaf](https://community.openhab.org/t/setting-up-development-environment-with-intellij/81217)

Looking at the [tasks.json](https://raw.githubusercontent.com/openhab/openhab-docs/master/developers/ide/examples/vscode/tasks.json) from VSCode example it is mostly around copying over the necessary jars starting openhab in debug mode.  Should we make that standard in some way so that multiple IDEs can debug bindings?  The method for VSCode doesn't seem scalable.

Is this something we can do in maven? - If so, I am not sure what lifecycle phase that would be?

I think we could do this in gradle.. But mixing in gradle with maven seems confusing.

Wondering if anyone has looked and thought about this yet.

**Comment by hmerk** [comment]
closed due to inactivity
