### ISSUE TITLE
[regoheatpump] Negative value for InOperationRAD

### ISSUE THREAD

**Issue by martin67** [openhab/openhab-addons#6101]
## Expected Behavior

Hours in operation (operatingTimes#heatPumpInOperationRAD) should return a positive value.

## Current Behavior

I'm getting negative hours on the heatPumpInOperationsRAD value:

2019-09-18 05:53:56.922 [vent.ItemStateChangedEvent] - Heatpump_InOperationRAD changed from -25934.0 h to -25933.0 h
2019-09-18 10:41:21.842 [vent.ItemStateChangedEvent] - Heatpump_InOperationDHW changed from 7218.0 h to 7219.0 h
2019-09-18 18:11:10.983 [vent.ItemStateChangedEvent] - Heatpump_InOperationRAD changed from -25933.0 h to -25932.0 h

All other InOperation values are positive. 

## Possible Solution

I've had the pump for 13-14 years and maybe the counter has wrapped around itself somehow?

## Your Environment

* Version used: openhab 2.5M3
* Heatpump; Carrier Heat 60
* Operating System and version: Ubuntu 18.04

**Comment by crnjan** [comment]
Hi @martin67! Can you maybe share what number of hours does the HP show? 

And please share logs - to `userdata/etc/org.ops4j.pax.logging.cfg` add:

```
log4j2.logger.regoheatpump.name = org.openhab.binding.regoheatpump
log4j2.logger.regoheatpump.level = TRACE
```

thx!

**Comment by crnjan** [comment]
Checked the code (it's a while I wrote that) and I guess you are right - rego uses 16 bit numbers and if one converts -25933 to unsigned counterpart you get 39603, which makes sense (that is about four and a half years in operation). Can you confirm this is the number you see in the HP?

**Comment by martin67** [comment]
Hi @crnjan ,

When I looked at the heatpump for running hours (could only find one menu item (7.1)), that should be running hours since installation, it showed -18701 (a negative value...)

Attaching log as well.
[rego.log](https://github.com/openhab/openhab2-addons/files/3633380/rego.log)

**Comment by crnjan** [comment]
Can you try with this one https://drive.google.com/open?id=1z8BgxgazIpfahuk2KYlf2wIePFomzoqa - you first need to remove (uninstall) the existing rego binding and simply drop [this](https://drive.google.com/open?id=1z8BgxgazIpfahuk2KYlf2wIePFomzoqa) one into the addons folder.

**Comment by crnjan** [comment]
Your running hours since installation (7.1) = -18701, converted to positive = 46835 hours.
When reading from the pump via the binding, values come separately for radiators and dhw. From the shared logs:

```
Got value for 'operatingTimes#heatPumpInOperationRAD' = -25923
Got value for 'operatingTimes#heatPumpInOperationDHW' = 7221
```

`-25923 converted to positive = 39613`

**39613 + 7221 = 46834**

which gives to value seen on the HP (converted to positive of course). Makes sense? There is a difference of ~1h but not sure which values I picked from the log so might be not from the same time as value read in the HP ...

**Comment by crnjan** [comment]
And please let me know if binding shared above works ...

**Comment by martin67** [comment]
Seems to be working!

2019-09-20 15:57:51.114 [vent.ItemStateChangedEvent] - Heatpump_InOperationRAD changed from -25917.0 h to 39619.0 h

and I don' see any of the rounding issues anymore. All sensor values (temperatures) are returned with one decimal.

Thanks!

**Comment by crnjan** [comment]
Thx for the feedback - removed WIP from the PR, hopefully it will be merged soon.

For reference - I use the following rule

```
rule OperatingTimes
when
  Item regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationRAD received update or
  Item regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationDHW received update or
  Item regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationRAD received update or
  Item regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationDHW received update
then
  var Number sumHeatPumpInOperation =
    (regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationRAD.state as QuantityType<Number>) +
    (regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationDHW.state as QuantityType<Number>)

  var Number sumAddHeatInOperation =
    (regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationRAD.state as QuantityType<Number>) +
    (regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationDHW.state as QuantityType<Number>)

  var Number dhwPercentHeatPumpInOperation = (regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationDHW.state as QuantityType<Number>) /
    (sumHeatPumpInOperation as QuantityType<Number>) * 100.0

  var Number radPercentHeatPumpInOperation = (regoheatpump_ipRego6xx_ivt_operatingTimes_heatPumpInOperationRAD.state as QuantityType<Number>) /
    (sumHeatPumpInOperation as QuantityType<Number>) * 100.0

  var Number dhwPercentAddHeatInOperation = (regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationDHW.state as QuantityType<Number>) /
    (sumAddHeatInOperation as QuantityType<Number>) * 100.0

  var Number radPercentAddHeatInOperation = (regoheatpump_ipRego6xx_ivt_operatingTimes_addHeatInOperationRAD.state as QuantityType<Number>) /
    (sumAddHeatInOperation as QuantityType<Number>) * 100.0

  heatPumpInOperationSum.postUpdate(sumHeatPumpInOperation)
  heatPumpInOperationDHWPercent.postUpdate(dhwPercentHeatPumpInOperation)
  heatPumpInOperationRadPercent.postUpdate(radPercentHeatPumpInOperation)

  heatPumpAddHeatInOperationSum.postUpdate(sumAddHeatInOperation)
  heatPumpAddHeatInOperationDHWPercent.postUpdate(dhwPercentAddHeatInOperation)
  heatPumpAddHeatInOperationRadPercent.postUpdate(radPercentAddHeatInOperation)
end
```

in order to get values that match HP values for 7.1, 7.2, 7.3 and 7.4. Easier to follow ;)

**Comment by martin67** [comment]
Thanks for the tip!

BTW, I have only 7.1 in the display on my heatpump. The other values are only available through the binding.
