### ISSUE TITLE
[modbus] Change some error / warn reporting

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#6113]
Modbus binding v 2.4 stable

Noted, that if a data Thing **is configured for writing** but OFFLINE e.g. UNITIALIZED_HANDLER_MISSING_ERROR (when for example one if its parent Bridge Things are failed/offline) and an attempt is made to **write** to it by sending command to linked Item - there is no error report in `openhab.log`
I would like to see a WARN level message here.

Separately, if a data Thing is configured for read only (none of the `writexxx` parameters have been supplied), a WARN message **is** generated when command sent to linked Item.
`2019-09-19 20:41:38.763 [WARN ] [ernal.handler.ModbusDataThingHandler] - Thing modbus:data:id2:poolpoll:bit_16_0 ‘Modbus data’: not processing command OFF since writeStart is missing and transformation output is not a JSON`

A use-case for this kind of activity, a set of bit-mode read only data things may be configured from a bit-packed register.  Individual Switches can be commanded from openHAB, and a rule can intercept the binary commands and combine to write a complete register.

In this particular case, where a dataThing has no write parameters e.g. it is _intended_ as read-only, I would like to see the message at DEBUG level instead of appearing in "normal" `openhab.log`
This would effectively give an "ignore", a silent failure in everyday usage.

**Comment by ssalonen** [comment]
I think your reasoning makes sense.  While it is possible to write with a data thing that uses JSON as transformation output, it is much common to have the bit logic you described using rules.

People who use the json transformation are probably more advanced users and can find their way with troubleshooting.

Would you like introduce a PR for this?

**Comment by Rossko57** [comment]
Alas, I am not a java programmer.
