### ISSUE TITLE
[daikin] Add Support for week and year power info

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab-addons#6115]
With some daikin units it's possible to gather information about the power consumption. It would be great seeing this supported here also.

The API is a bit weird:

On a week basis:

    # GET /aircon/get_week_power
    ret=OK,today_runtime=137,datas=0/0/0/100/0/300/500

And for the year:

    # GET /aircon/get_year_power
    ret=OK,previous_year=0/0/0/0/0/0/0/0/0/0/0/0,this_year=0/0/0/0/0/0/0/0/2

It seems to only return created till now, so "this_year" has 9 entries because it's September. 

Also the unit for week are in Wh while the unit of the year data is in kWh.

I'll try to do some wiresharking on my iPhones data because there are more information available (current day, last week, and year with decimal values).

I suggest catching only the last value and store it as "current_week" or "current_year" so it's easy to work with.

Bests
Pascal

**Comment by PascalTurbo** [comment]
The results of my Wireshark capture:

    # GET /aircon/get_week_power_ex
    ret=OK,s_dayw=0,week_heat=8/3/0/0/1/0/0/0/1/9/0/0/0/1,week_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0

    # GET /aircon/get_year_power_ex
    ret=OK,curr_year_heat=0/0/0/0/0/0/0/0/24/0/0/0,prev_year_heat=0/0/0/0/0/0/0/0/0/0/0/0,curr_year_cool=0/0/0/0/0/0/0/0/0/0/0/0,prev_year_cool=0/0/0/0/0/0/0/0/0/0/0/0

    GET /aircon/get_day_power_ex
    ret=OK,curr_day_heat=0/0/0/0/0/0/3/1/2/1/1/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_1day_heat=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/1/2/0/0/0,curr_day_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_1day_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0

**Comment by jimtng** [comment]
There's currently some work on this https://github.com/openhab/openhab-addons/pull/7471

**Comment by hmerk** [comment]
closed due to inactivity
