### ISSUE TITLE
[mihome] If Gateway MAC address starts with a '0' zero a duplicate gatway is also found with abbreviated MAC address

### ISSUE THREAD

**Issue by DigiH** [openhab/openhab-addons#6120]
Just an observation in the Paper UI inbox. I always see a duplicate gateway found there with the MAC address of my gateway, but the leading '0' zero character stipped off.

Since I'm setting up everything with manual text files, this really isn't an issue for me, but might be confusing for people setting up everything through the Paper UI, and also having a gateway which has a leading zero in its MAC address.
<img width="496" alt="Gateway" src="https://user-images.githubusercontent.com/17110652/65386596-14e87400-dd3e-11e9-8237-51ef16caad77.png">

With current openHAB 2.4 Release Build

**Comment by kristofejro** [comment]
I have the same issue on openHAB 2.5.0.M3 Milestone Build

**Comment by hmerk** [comment]
closed due to inactivity
