### ISSUE TITLE
[sonos] Documentation misinterpretable

### ISSUE THREAD

**Issue by fex01** [openhab/openhab-addons#6123]
## Expected Behavior
Documentation is as accessible and clear as possible to enable friction free use of the binding.

## Current Behavior
Section **Supported Things**, last sentence 'Please note that these thing types are case sensitive (you need to define them **in upper case**).' is wrong - One & Beam are not in upper case but just the first letter is capital.

Section **Binding Configuration**: Section unclear, where can I use these options? In the Thing file? Or should I create an *.cfg-file? Or can these options only be used in the PaperUI config?

Section **Thing Configuration**: No explanation how to acquire the UDN

## Possible Solution
Section **Supported Things** - alternative: Please note that these thing types are case sensitive (you need to define them **exactly as stated above**).

Section **Binding Configuration**: Rewrite?

Section **Thing Configuration**: Insert at the end of the second sentence '(value to be found via Sonos item in the PaperUI Inbox)

**Comment by fex01** [comment]
Did the proposed changes to sections **Supported Things** & **Thing Configuration** myself.
Still open: issues with section **Binding Configuration** (I don't have the necessary insight to fix that section)

**Comment by hmerk** [comment]
closed
