### ISSUE TITLE
[mqtt] Homeassistant abbreviations support in auto discovery

### ISSUE THREAD

**Issue by SBKila** [openhab/openhab-addons#6124]
Hi,

For iot device memory consumption is important, homeassistant protocol setup a set of abbreviation to decrease the size of the sent data during discovery process.

could you manage this abbreviation ?

https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by SBKila** [comment]
Ok guys, I see in master branch that is implemented gson..JsonReader.

**Comment by J-N-K** [comment]
Works with latest snapshot.
