### ISSUE TITLE
[deconz] Api Key is not displayed

### ISSUE THREAD

**Issue by micropet** [openhab/openhab-addons#6136]
I installed the Phoscon GW on an RPi and integrated an Aquara temperature sensor.

On Openhab 2.5 the deconz binding is activated and also shows "Online".

  things show deconz: deconz: Homeserver in the Openhab Console shows:

UID: deconz: deconz: homeserver
Type: deconz: deconz
Label: deCONZ
Status: OFFLINE (COMMUNICATION_ERROR): org.eclipse.jetty.io.EofException

No properties

Configuration parameters:
         host: 192.168.0.149

openhab> list | grep -i deconz
238 x Active x  80 x 2.5.0.201909222246    x openHAB Add-ons :: Bundles :: Dresden Elektronik deCONZ Binding

in my thingsfile stands:

Bridge deconz: deconz: homeserver [host = "192.168.0.149"]

I mean to have done everything right, but I do not get the Api Key.

**Comment by cweitkamp** [comment]
Did you follow the instructions from the [documentation](https://www.openhab.org/addons/bindings/deconz/#thing-configuration) to create an api key:

> Otherwise the field can be left empty and the binding will generate the key automatically. For this process the deCONZ bridge must be unlocked in the deCONZ software so that third party applications can register. See deCONZ documentation
