### ISSUE TITLE
[robonect] Remove time limit for the duration parameter of a mower job

### ISSUE THREAD

**Issue by demichve** [openhab/openhab-addons#6142]
I would like to trigger a smaller change for the Robonect binding.

Currently, there is a channel to trigger a mower “job” and setup a duration.
Unfortunately, this seems to be limited to 60 minutes. In the channel configuration on PaperUI I will get automatically an error, when I try to input a duration higher than 60.
When I try to parse a higher value to the channel using a file, it does not work.
But robonect is able to accept a duration higher than 60 minutes.
Is it possible to change this limitation?

Michael

**Comment by wborn** [comment]
The max value is defined in the duration configuration parameter definition:

https://github.com/openhab/openhab2-addons/blob/27a61570931166e040d22d9bdf7ab47f44677b2d/bundles/org.openhab.binding.robonect/src/main/resources/ESH-INF/config/config.xml#L12-L17

Do you know if it can be increased/removed @reyem?

**Comment by reyem** [comment]
Yes, this could be increased

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by joni1993** [comment]
I'd suggest to reopen this - should be an easy PR

**Comment by hmerk** [comment]
@joni1993 Feel free to provide a PR for this.
