### ISSUE TITLE
Discovery - duplicated things via search

### ISSUE THREAD

**Issue by francemgit** [openhab/openhab-addons#6144]
**Version:** openHAB 2.5.0 Build #1701

**Issue:** Things defined via configuration file are discovered during search but marked as NEW and not IGNORED. The issue appear with different bindings (Daiking, Samsung TV, OpenWebNet).

Made a test with another OH User: same version of OpenwebNet bindings detect duplicated things with 2.5.0 Snapshot during search but works fine with 2.4.0.
Things found via discovery and the one defined via config file have the same Serial.

Regards,
Marco

**Comment by mvalla** [comment]
I am author of one of the binding (OpenWebNet), and the binding already uses Representation property:
`<representation-property>serialNumber</representation-property>`

The following JSON are taken from running 2.5.0.SNAPSHOT. 
As you can see i have:
`representationProperty: "serialNumber"`
 
but still the device is put in inbox as NEW.

Note that if I do a first discovery, the device is correctly put in Inbox as `IGNORED`.
But if from PaperUI I select `SHOW IGNORED`, then delete the device, then re-discover it, the device is not ignored anymore and is shown as NEW in the Inbox.
So I think something is wrong with Inbox `IGNORED` management or there is some wrong state.

**/rest/things/**
```
[
{
statusInfo: {
status: "ONLINE",
statusDetail: "NONE"
},
editable: false,
label: "BUS Gateway MH200N",
configuration: {
host: "localhost",
discoveryByActivation: false,
passwd: "12345",
port: 20000
},
properties: {
model: "Unknown",
serialNumber: "00:03:50:01:EF:75",
firmwareVersion: "1.1.8",
vendor: "BTicino"
},
UID: "openwebnet:bus_gateway:mh200Nb",
thingTypeUID: "openwebnet:bus_gateway",
channels: [ ]
}
]
```

**/rest/inbox/**
```
{
flag: "NEW",
label: "MH200N (MH200N, 1.0, 192.168.1.6)",
properties: {
host: "192.168.1.6",
model: "MH200N",
serialNumber: "00:03:50:01:EF:75",
firmwareVersion: "1.0"
},
representationProperty: "serialNumber",
thingUID: "openwebnet:bus_gateway:MH202_00035001ef75",
thingTypeUID: "openwebnet:bus_gateway"
},
```

**Comment by cweitkamp** [comment]
Hi all,

I have to apologize. Maybe I was a little bit to fast with my assessment. I found a minor bug in the inbox which explains your observations. I submitted a fix for it (see https://github.com/openhab/openhab-core/pull/1051).

**Comment by mvalla** [comment]
No apologies ! The examples in the issue  were needed to explain better what is happening
