### ISSUE TITLE
[enocean] Replace ChannelTypes by corresponding system channels

### ISSUE THREAD

**Issue by fruggy83** [openhab/openhab-addons#6164]
As stated [here](https://github.com/openhab/openhab2-addons/pull/6155#pullrequestreview-296221243) Channeltypes introduced in this binding should be replaced by their corresponding system ChannelType. In this case we get a localized label and decription.

Candidates to be replaced
 * temperature
 * humidity
 * motionDetection

**Comment by kaikreuzer** [comment]
When doing so, please consider my [comment here](https://github.com/openhab/openhab2-addons/pull/6155#issuecomment-537992564).

**Comment by fruggy83** [comment]
After merge of #5741 the channel windspeed should be replaced by the system channel wind-speed.
