### ISSUE TITLE
[profile] Enhance Transform profile for numeric Types

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#6166]
Enhancement request

example Item with transform profile use
`Number  test "blah"   { channel="xxx:zzz:yyy" [profile="transform:JS", function="divideby10.js"] }`
The resulting Item state is not updated.

What seems to happen is that the **string** result returned from the transform is not parsed into the **numeric** required for update.  As I understand it, transforms always return strings and it's up to the framework to parse, if possible, (This seems to be how transforms embedded in binding configs work.)

I'm guessing this problem also arises with 'numeric' based Items like Dimmer types, 
The issue is encountered regularly in user forums, examples
https://community.openhab.org/t/why-transformation-doesnt-work-in-my-case/67403
https://community.openhab.org/t/item-value-js-transformation-error/67133
https://community.openhab.org/t/z-wave-how-to-filter-implausible-sensor-values/82881

Secondary request; handle **QuantityType**?  With a profile, it would then be possible to add Units of Measurement to the transform's return string.
e.g. a transform could take raw "`215`" and return `"21.5 | °C"` or similar for use with a quantity typed `Number:Temperature` Item
This would be of use with bindings that cannot 'discover' properties of sensors and so on.

**Comment by cweitkamp** [comment]
Transformations and their profiles are maintained in the add-ons repository.

Similar to #5750?

**Comment by Rossko57** [comment]
> Similar to #5750?

Yes - this is the same.  I decided I had imagined opening an issue before, what a dimwit.
Withdrawing this one as duplicate.
