### ISSUE TITLE
[powermax] Display alarm panel trouble report

### ISSUE THREAD

**Issue by big-col** [openhab/openhab-addons#6187]
Is it possible to have any error/system troubles on the alarm panel reflected in the binding please?

ie for tamper alarm, power failure as id like to run rules against any given issue

Thanks
Colin 
OH2.4 release 
Windows10

**Comment by lolodomo** [comment]
Sorry to answer so late, I probably missed the issue.
Isn't the channel "trouble" what you request ?

**Comment by big-col** [comment]
Yes I think it is. Thanks for the reply 😁😁😁

**Comment by lolodomo** [comment]
So I close your request.
