### ISSUE TITLE
[gpstracker] Add option to Disable Friends

### ISSUE THREAD

**Issue by rudz04** [openhab/openhab-addons#6196]
Currently Owntracks automatically adds connected devices as "Friends" when they are connected to different Things in OpenHab. An option to disable friend updates in OpenHab so multiple people can take advantage of presence rules without knowing the location of other people (i.e. I don't want to know where my wife is).

**Comment by chriscolden** [comment]
switch to gpslogger if you are on android.

**Comment by hmerk** [comment]
closed due to inactivity
