### ISSUE TITLE
[amazonechocontrol] options to play commands "one after another"

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#6207]
Hi there, 
it can happen that sometimes, I might want to responde multiple times per request. 

simplified example:

Rule 1) When Item Bathroom_AmazonEcho_LastVoiceCommand changed 
-> action 1: Bathroom_AmazonEcho_LastVoiceCommand .sendCommand('understood')
-> action 2: Bathroom_Lights.sendCommand(ON)
Rule 2) When Item Bathroom_Lights changed 
-> action 1: Bathroom_AmazonEcho_LastVoiceCommand,sendCommand('light changed').

My problem is, that action of rule 2 starts immediately and does not wait until the sentence of action 1 of rule 1 has finished.  
Is there a way to implement some "order"? 

best regards
PhiL

**Comment by hmerk** [comment]
closed due to inactivity
