### ISSUE TITLE
[draytonwiser] Binding blocks all ThingHandler threads

### ISSUE THREAD

**Issue by Neilc-gardner** [openhab/openhab-addons#6215]
I initially posted this in the OpenHAB forum.  The only response I got was that it should be posted here, on Github, not in the OpenHAB community forum.  

Original post follows
----------------------

I've just started making the move to use OpenHab as my automation hub.  So far I've only integrated a limited number of devices, as I fully familiarise myself with the architecture.  My system consists of :  

* Intel i3 CPU, 8GB DRAM, 1 x 512GB SSD system disk and 9TB magnetic disk storage

* Windows 10 Pro 1809

* Java (Zulu 8.40.0.25-win64)

* OpenHAB v2.4.0 (Stable)

I have 3 bindings loaded - Drayton Wiser, Z-Wave and Hue.  All appear to be working as intended, for the things and items I've defined, but the Hue lights become unresponsive very quickly.  The other bindings seem to continue to respond as expected.  

With the HUE devices, on restarting OpenHAB, everything is very responsive.  But very quickly, they become laggy and within a few hours are unusable.  I don't believe it's network latency, as pinging the Hue hub from the OpenHAB PC sees <1ms over a long period, and with no packet loss.  The PC is running at about 80-85% CPU idle, and DRAM use is around 40%.

I've put logging into DEBUG, and can see the delay in the logs, but don't really know what to look for in the Hue debug output.  I'm also not fully familiar with what other tools may be available to help me track this down.  

Below is a log extract, about 12hrs after restarting OpenHAB.  You will see the entry to switch one of the bulbs on at 08:53:38, but it doesn't appear to be sent the request until 08:54:47 - a full 1m9s later.  Initially, after a restart, this all takes place in 1s.

Anyone got into any insight as to what might be the cause of this?  If I can investigate further, I'm happy to take guidance on what else to try/look for, and what tools OpenHAB has to help me.

```csv
08:53:38.414 [INFO ] [smarthome.event.ItemCommandEvent     ] - Item 'LivingRoomTableLampSpeaker_onoff' received command ON
08:53:38.420 [INFO ] [arthome.event.ItemStatePredictedEvent] - LivingRoomTableLampSpeaker_onoff predicted to become ON
08:53:38.421 [INFO ] [smarthome.event.ItemStateChangedEvent] - LivingRoomTableLampSpeaker_onoff changed from OFF to ON
08:54:47.341 [DEBUG] [thome.binding.hue.internal.HttpClient] - Async sending put to address: http://192.168.1.218/api/gucwxrSfRvrZlQsTMSmc83C6icra3d5YDxlsz61m/lights/10/state delay: 40 body: {"on":true}
08:54:52.874 [DEBUG] [hue.internal.handler.HueBridgeHandler] - Status update for Hue light '10' detected.
08:54:52.875 [DEBUG] [hue.internal.handler.HueBridgeHandler] - Sending lightStateChanged for light '10'
08:54:52.875 [DEBUG] [hue.internal.handler.HueBridgeHandler] - Sending lightStateChanged for light '10'
08:54:52.875 [TRACE] [.hue.internal.handler.HueLightHandler] - onLightStateChanged() was called
08:54:52.876 [DEBUG] [hue.internal.handler.HueBridgeHandler] - Sending lightStateChanged for light '10'
08:54:52.876 [TRACE] [.hue.internal.handler.HueLightHandler] - onLightStateChanged() was called
08:54:52.877 [TRACE] [.hue.internal.handler.HueLightHandler] - Received state change for another handler's light (10). Will be ignored.
08:54:52.877 [INFO ] [smarthome.event.ItemStateChangedEvent] - LivingRoomTableLampSpeaker_Color changed from 0 to 84
```

**Comment by cweitkamp** [comment]
FTR: https://community.openhab.org/t/hue-light-response-increasing-slows-up/83366

**Comment by kaikreuzer** [comment]
This sounds pretty weird and I actually doubt that it is a bug in the hue binding (which I use myself and I have never seen any such issues).

I assume that you see this effect only on Hue, not on Drayton Wiser and Z-Wave in the same situation?

What could help for the analysis is a stacktrace. To retrieve it, just call `jstack <process id>` from the command line (use `jps` to find the right process id).

**Comment by Neilc-gardner** [comment]
Z-wave is instant response.  I don't notice any discernible problems with the Wiser either. There isn't the same feedback with it though, as there is with switching a light on and off.  Even normally with the Wiser iOS app, there can be a few seconds delay between a temperature change request and the TRV being heard to open/close. I believe this is 'as intended'. 

The Hue is now up to over 6 minutes response time!

Here's a stacktrace.

[jstack.txt](https://github.com/openhab/openhab2-addons/files/3722535/jstack.txt)

**Comment by kaikreuzer** [comment]
Thanks for the stacktrace! I think we can now clearly see the culprit: All 5 ThingHandler threads are blocked by Drayton Wiser:

```
"ESH-thingHandler-1" #136 daemon prio=5 os_prio=0 tid=0x0000000025890800 nid=0x1bf4 waiting for monitor entry [0x000000002fe6e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.openhab.binding.draytonwiser.handler.HeatHubHandler.notifyListeners(HeatHubHandler.java:153)
        - waiting to lock <0x0000000081e03808> (a org.openhab.binding.draytonwiser.handler.HeatHubHandler)
        at org.openhab.binding.draytonwiser.handler.HeatHubHandler.refresh(HeatHubHandler.java:145)
        at org.openhab.binding.draytonwiser.handler.HeatHubHandler.lambda$1(HeatHubHandler.java:546)
        at org.openhab.binding.draytonwiser.handler.HeatHubHandler$$Lambda$531/1612879112.run(Unknown Source)
```
If you disable this binding for a test, you should be able to confirm that hue is running smoothly again.

**Comment by kaikreuzer** [comment]
Ok, I only noticed now that the Drayton Wiser binding isn't yet available at all, but that it is work in progress in https://github.com/openhab/openhab2-addons/pull/3168. This bug hence needs to be fixed in the initial contribution before it can get merged.

**Comment by Neilc-gardner** [comment]
Tha

> Thanks for the stacktrace! I think we can now clearly see the culprit: All 5 ThingHandler threads are blocked by Drayton Wiser:
> 
> ```
> "ESH-thingHandler-1" #136 daemon prio=5 os_prio=0 tid=0x0000000025890800 nid=0x1bf4 waiting for monitor entry [0x000000002fe6e000]
>    java.lang.Thread.State: BLOCKED (on object monitor)
>         at org.openhab.binding.draytonwiser.handler.HeatHubHandler.notifyListeners(HeatHubHandler.java:153)
>         - waiting to lock <0x0000000081e03808> (a org.openhab.binding.draytonwiser.handler.HeatHubHandler)
>         at org.openhab.binding.draytonwiser.handler.HeatHubHandler.refresh(HeatHubHandler.java:145)
>         at org.openhab.binding.draytonwiser.handler.HeatHubHandler.lambda$1(HeatHubHandler.java:546)
>         at org.openhab.binding.draytonwiser.handler.HeatHubHandler$$Lambda$531/1612879112.run(Unknown Source)
> ```
> 
> If you disable this binding for a test, you should be able to confirm that hue is running smoothly again.

Thank you Kai. I've removed the Wiser binding, and will see how the Hue continues to run now.  I'll follow up in the Wiser issue once I confirm all is now good.

**Comment by dal31b05** [comment]
I had a similar problem with the Wiser binding. My Network binding presence detection stopped regularly pinging devices and failed to notice when they went off line, even if it did ping them and get no response. Also the range events in the Astro binding stopped triggering. 

Resolved by removing Wiser things. 

Currently resolved by using the Feb 19 version of the Wiser binding so appears the bug is between that and the 2.5.0 SNAPSHOT versions.
