### ISSUE TITLE
[mqtt] Chaining transformations with REGEX change in behavior

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#6224]
## Expected Behavior

In the MQTT 1.x binding there was a parameter where one could supply a REGEX to pre-filter messages before processing a message. For example, when you have a device that publishes multiple types of messages to the same topic one can filter out the messages you don't care about rather than having to process the message and see a warning in the logs (e.g. from the JSONPATH transform complaining the path is not valid). Sadly, there are a lot of devices MQTT users out there who follow this antipattern making this ability to filter messages like this important.

On the 2.5 M1 version of the binding one could chain the REGEX transform with the "real" transform letting the REGEX transform match only those messages you want to process. See https://community.openhab.org/t/mqtt-2-5-m1-how-to-implement-the-equivalent-to-mqtt1-regex-filters/68350.

At some point between then an now, the behavior of how the binding handles the REGEX transform returning null has changed. Previously it would stop the transformation entirely when there is no match, which is the desired result. Now it passes the full message on to the next transformation which breaks the ability to use the REGEX transform as a filter on the messages.

## Current Behavior

Using the example from the link above, we have two JSON messages published to a single topic, only one of which we care about.

Don't want to process this message:
```json
{
  "system": {
    "hostname": "Bar_NODE",
    "uptime": 284100,
    "rssi": -80,
    "freemem": 32656
  },
  "sensors": {},
  "pwm": {
    "0": 0,
    "1": 0,
    "2": 0
  },
  "gpio": {
    "16": 0
  }
}
```

Do want to process this message:

```json
{
  "system": {
    "hostname": "Bar_NODE",
    "uptime": 284100,
    "rssi": -80,
    "freemem": 32656
  },
  "sensors": { 
    "nrf1t1t" : 20,
     "nrf1h1" : 33
    
  },
  "pwm": {
    "0": 0,
    "1": 0,
    "2": 0
  },
  "gpio": {
    "16": 0
  }

}
```

Using the following incoming transform on the Thing:

```
REGEX:(.*nrf1t1t*)∩JSONPATH:$.sensors.nrf1t1t
```

When the first message is received the full JSON gets passed to JSONPATH which generates a warning in the logs.

## Possible Solution

Return to the behavior where when a transformation in the chain returns null simply drop the message. 

## Steps to Reproduce (for Bugs)

See link and discussion above

## Context

There are many examples where devices will publish different JSON to the same topic. For example, Shelly publishes telemetry for all the devices on a network to the same topic requiring one to filter the messages in the various Things so only the messages for a specific device get processed by the Thing that represents that device. Without the ability to filter, one must use Rules to process the message. With the ability to filter out messages that don't belong to a given Thing, one can avoid the need for the Rule and retain an important feature that the old 1.x version binding implements.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
openHAB 2.5 SNAPSHOT 1723
Running in Docker on an Ubuntu 18.4
Using Mosquitto as the broker
MQTT Generic Things are defined using PaperUI

**Comment by J-N-K** [comment]
Are you sure about that? 

https://github.com/eclipse/smarthome/blob/b8455de15d65512e8fac4e94d42de6ab2fccf1c5/extensions/binding/org.eclipse.smarthome.binding.mqtt.generic/src/main/java/org/eclipse/smarthome/binding/mqtt/generic/internal/generic/ChannelStateTransformation.java#L85

The `processValue` returned the original value if the transformation failed even at ESH times. And the code of the regex transformation itself looks untouched since then. 

I agree that this is somehow unexpected (I would expect an exception or at least `null`).

**Comment by J-N-K** [comment]
The transformation itself returns null. But the „wrapper“ in the mqtt binding replaces null with the original value. The problem is that this is part of the public API and I don’t know what other bundles rely on the way it is now.

**Comment by rkoshak** [comment]
I can't imagine a case where one would want the whole message in cases where a transform returns null. If a user went so far as to define a transformation to extract a value from the message, receiving the full text of the message as a result is surely as much of an error as receiving null I would think. 

Transformations like JSONPATH don't do this, it throws an exception instead. So not only is the current behavior counter intuitive, it's inconsistent among the transformations and inconsistent between ways of using the same transformation (e.g. REGEX used from a rule versus what ever parts of OH use this wrapper).
