### ISSUE TITLE
[yeelight] Support for Yeelight LED Ceiling Lamp v4

### ISSUE THREAD

**Issue by mralexjoin** [openhab/openhab-addons#6227]
I have the intention to add support for Yeelight LED Ceiling Lamp v4 in yeelight binding. I know the lamp supported in miio binding, but I have some trouble using it with official yeelight application and openhab at the same time. After adding it in yeelight app requests are expected to be not encrypted but miio trying to use encryption anyway (token is obligatory).

**Comment by vkoop** [comment]
As far as I've see there isn't much progress? 

I've already implemented most of the functionallity:
- possibility to control the ambient light 
- possibility to switch to nightlight mode and control the brightness

I've to work on some further points and will push my WIP branch soon.

**Comment by mralexjoin** [comment]
@vkoop thank you. At first I wanted to do the same, but didn't like code duplication in `DeviceBase`, `DeviceStatus` and device classes. Had an idea to make separate classes for property statuses, but didn't have much time.
I think we can close issue after merging.
