### ISSUE TITLE
[RFXCom] add LucciAir DC and DCII protocols to add-on

### ISSUE THREAD

**Issue by gstiegl** [openhab/openhab-addons#6231]
@martinvw please add these two protocols to the RFXCom add-on

**Comment by martinvw** [comment]
I added an initial version supporting (only) LucciAir DC (not yet the 2 version thus):

https://download.martinvw.nl/org.openhab.binding.rfxcom-2.5.0-SNAPSHOT-6231.jar

**Comment by gstiegl** [comment]
Great, I will test this during next week. Do I need a 2.5.0 OpenHAB for this or will it run under 2.4.0?

BR, Gerald 

PS: Are you by chance at EclipseCon in Ludwigsburg?

Von meinem iPhone gesendet

**Comment by martinvw** [comment]
It should run on 2.4 👍

Nope I’m not in Ludwigsburg this year 😒

**Comment by martinvw** [comment]
I updated the jar with support for LucciAir DC II
