### ISSUE TITLE
[MiHome] International unit (hPa or mbar) for Atmospheric Pressure

### ISSUE THREAD

**Issue by maxencep02** [openhab/openhab-addons#6247]
Hello,
The binding MiHome reports pressure in kPa for Aqara HTP sensor while the international system suggests to use hPa or mbar.

If I am not wrong, it only requires to change :
https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mihome/src/main/java/org/openhab/binding/mihome/internal/handler/XiaomiSensorHtHandler.java

Line 69: float pressure = (float) (data.get(PRESSURE).getAsFloat() / 1000.0);
by
            float pressure = (float) (data.get(PRESSURE).getAsFloat() / 100.0);

**Comment by hmerk** [comment]
closed due to inactivity
