### ISSUE TITLE
[deconz] support thing type ZHAThermostat (e.g. Eurotronic SPIRIT / SPZB0001)

### ISSUE THREAD

**Issue by MichaelHeimann** [openhab/openhab-addons#6251]
## Your Environment

* Version used: Openhab 2.4 release, deconz binding 2.5
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

According to Deconz Plugin Help all sensors are supported.
It seems like the Thermostat type isn't.
Link to deconz REST API code about thermostats: 
https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/thermostat.cpp

I have no clue about programming but I'd love to be able to set a heatsetpoint, or disable heating when the window is opened.

This is something I need to reach an acceptable WAF, so I'm happy to get directions for workarounds. REST binding? deconz to mqtt bridge that cannot only read sensors? anybody implemented zigbee thermostats in openhab?

Thanks,
Michael

**Comment by LukasA83** [comment]
Bump. How can this component type be easily implement into deconz binding? I attached my rest-api output:

```
{
    "config": {
        "battery": 100,
        "displayflipped": false,
        "heatsetpoint": 2000,
        "locked": null,
        "mode": "auto",
        "offset": 0,
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "xxxx",
    "manufacturername": "Eurotronic",
    "modelid": "SPZB0001",
    "name": "Thermostat Gaesteschlafzimmer",
    "state": {
        "lastupdated": "2020-01-28T18:44:02",
        "lowbattery": false,
        "on": true,
        "temperature": 1550,
        "valve": 251
    },
    "swversion": "20191014",
    "type": "ZHAThermostat",
    "uniqueid": "xxx"
}
```

**Comment by robinemde** [comment]
I have bought the Eurotronic Spirit ZigBee thermostates without checking the OpenHAB deCONZ binding support to replace my AVM DECT 301...........Lots of people seem to start using them and prefer ZigBee thermostates over DECT ULE (AVM) or others.

I was simply assuming that all devices compatible with deCONZ/Phoscon gateways (ConBee/RasBee) can be used in OpenHAB over the binding....Bad mistake!

Current workaround is using HomeAssistant and its deCONZ integration in parallel which can handle the Eurotronic devices.

I would LOVE to see full support by the deCONZ binding in the near future to switch back to OpenHAB.
