### ISSUE TITLE
[exec] Escapes single quotes not passing

### ISSUE THREAD

**Issue by delid4ve** [openhab/openhab-addons#6269]
## Expected Behavior

Single quotes to enclose a string with a space in for example 'Authorization:bearer accesstoken' when using as a header in a curl command

## Current Behavior

Log is treating the part after the space as a separate item, so for curl ‘cannot resolve host accesstoken’

command:
` var String GetFeatures = "curl -X POST https://publicapi.lightwaverf.com/v1/features/read -H \'Authorization:bearer " + Access_Token.state.toString + "\' -H Content-Type:application/json -d {\"features\":[{\"featureId\":\"5c7d64783c570522afb151b5-24-3157331848+1\"}]}"`

`curl: (6) Couldn't resolve host 'eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI4Y2YyZGUwOTAwMTQwOTczODRiZCIsImlzcyI6Imh0' `

## Steps to Reproduce (for Bugs)
Should be able to locate any api/url that can accept an authorization:basic token with a space

## Context

Exec binding currently unusable for commands that have a space present in a string (unknown if affects anything other than curl headers and jsondata(also confirmed spaces cause error)

Problem doesn’t exist in v1 binding and v2 binding also does not accept @@ in place of the space

## Your Environment

* Version used: current stable 2.4 and standard respository exec version
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): QNAP QTS4.4.1, also confirmed rPi openhabian and also 2.4-amd64 docker image

**Comment by Rossko57** [comment]
While I've no reason to think this may not also affect exec binding 2.x, the example string given is presumably used with exec **action**?   executeCommandLine() is I think a legacy 1.x action

**Comment by delid4ve** [comment]
No this is for v2 and does not involve v1 binding or action.
This string is passed as the argument %2$s (input channel) for the thing.
I have also tested the string directly in the thing with no arguments and it also fails with the white space between bearer and the actual accesstoken even though the quotes of either type are there and escaped

**Comment by openhab-5iver** [comment]
> executeCommandLine() is I think a legacy 1.x action

In OH 2.x, executeCommandLine is considered a [Core Action](https://www.openhab.org/docs/configuration/actions.html#exec-actions). 

https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.model.script/src/org/eclipse/smarthome/model/script/actions.

**Comment by delid4ve** [comment]
I’m not sure why executecommandline is even being discussed, this is a v2 thing bug

**Comment by Rossko57** [comment]
Only because it is not at all obvious that you would pass an entire command line string to the binding Thing input channel, it's not the usual usage.

**Comment by delid4ve** [comment]
It was just the current version in my files when I created the bug but doesn’t matter how it’s done, doesn’t work anyway I can find

**Comment by 9037568** [comment]
The string construction specified is working just fine.

````
22:58:00.026 [INFO ] [rg.eclipse.smarthome.model.script.ABC] - curl -X POST https://publicapi.lightwaverf.com/v1/features/read -H 'Authorization:bearer ME' -H Content-Type:application/json -d {"features":[{"featureId":"5c7d64783c570522afb151b5-24-3157331848+1"}]}
````

If you like, you can show how you're passing this string to an exec so that we can determine if it matters.

**Comment by Rossko57** [comment]
possibly related
https://github.com/openhab/openhab-addons/pull/6819

**Comment by delid4ve** [comment]
Rossko57 exactly the same issue just worded from a non tech person that didn’t know why 👍
