### ISSUE TITLE
[lutron] Add support for 0.1% dimming

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab-addons#6287]
The Lutron Integration Protocol supports the use of parameter values with up to two decimal places (e.g. 0.01). The current implementation of the IP bridge and device handlers is such that these values are rounded/truncated to integers in several places. This was ok before, since greater precision of parameters was generally not required for RA2 and Caseta device support. However, with the addition of HomeWorks QS system support and corresponding support for devices such as Hi-Lume Premier 0.1% LED drivers, this has become a significant limitation. It prevents these devices from being dimmed to less than 1%.

**Comment by hmerk** [comment]
closed due to inactivity
