### ISSUE TITLE
[tesla] API login error - "Failure:401 Unauthorized"

### ISSUE THREAD

**Issue by heinihuber** [openhab/openhab-addons#6294]
## Current Behavior
The binding was installed by Paper UI and configured (things/items/sitemaps) like described in the related binding description. Afterwards the items file created an log entry on openHAB start...

2019-10-28 11:48:22.958 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'tesla.items'

The sitemap loads without a problem but the Tesla related objects seemed to be uninitialized. Then I suspected that the logon procedure to Tesla could be the showstopper here and so I tried to generate the access token via the openHAB ssh console. After entering the username and password I received "Failure:401 Unauthorized" in the console.

The username and password combination works with the official Tesla app without any problem. The password includes characters and numbers, it length is about 32 characters.

## Your Environment
openHAB (Beta) version 4.2.6 | openhab-binding-tesla 2.5.0.SNAPSHOT
Ubuntu-Server 18.04.3 LTS | 4.15.0-66-generic

**Comment by kaikreuzer** [comment]
I cannot reproduce. I have set up the latest 2.5.0-SNAPSHOT, created a new Tesla Thing through Paper UI, entered username, pwd and vin in the Paper UI and the Thing directly went online and after a few minutes, all associated items were filled with values.

**Comment by kaikreuzer** [comment]
FTR: I am on V10 as well, so this does not seem to be related.

**Comment by heinihuber** [comment]
I've not found a dialogue to configure the Tesla login crendentials via Paper UI, that's the reason why I did this by creating the .thing file manually (etc/openhab2/things/tesla.thing) and put the crendentials within. I think normally this has to be done inside the Thing configuration part?

In my installation there a two points at Paper UI where I can see something about the Tesla Binding. The first one is the at Add-ons -> BINDINGS where I went to install the Binding, and the second is at Configuration -> Bindings what gives ; none of them enables me to enter my crendentials.

My car is a Model 3 not a Model S that is official supported by the Binding - but should the dialogue you spoke from not be visible independently from that?

I'll be one or two days off so my next answer will take a while.


Thank you for supporting me!

**Comment by kaikreuzer** [comment]
> I think normally this has to be done inside the Thing configuration part?

Correct. You get there through Configuration->Things->"Select Tesla Thing"->"Press blue edit button on top (above the Thing name)".

**Comment by heinihuber** [comment]
Since I understood how to add the TESLA related Thing and afterwards using your way to enter the API credentials there, the Binding works fine. Sorry for the inconvenience, and thank you for your help!

**Comment by kaikreuzer** [comment]
Glad I could help!
