### ISSUE TITLE
[deconz] Support thing type ZHAfire (e.g. Heiman smoke sensor)

### ISSUE THREAD

**Issue by mlimbacher** [openhab/openhab-addons#6298]
**Environment**
- Version used: OpenHAB 2.4 release (via repository), deCONZ binding 2.5
- Raspbian 9.11 Stretch

According to deCONZ Plugin Help all sensors are supported, including smoke/fire sensors.
The sensor is also listed by the REST query:
```
	"8": {
		"config": {
			"battery": null,
			"on": true,
			"pending": [],
			"reachable": true
		},
		"ep": 1,
		"etag": "e1b11b9233a5d9ba16355581e41eb4f6",
		"manufacturername": "Heiman",
		"modelid": "SMOK_V16",
		"name": "SMOK_V16",
		"state": {
			"fire": false,
			"lastupdated": "none",
			"lowbattery": false,
			"tampered": false
		},
		"swversion": "20150330",
		"type": "ZHAFire",
		"uniqueid": "00:50:43:c9:1f:2f:36:63-01-0500"
	}
```

Do you think you can integrate it into the binding in the near future? 

I'd try it myself if my guess was not that it shouldn't be too much lines of code. My overhead of getting back into JAVA, setting up a development environment and learning how OpenHAB does its things might be quite big compared to the expected count of lines. 

Best regards and thanks, Matthias

**Comment by cweitkamp** [comment]
Yes, it should be possible. The integration is not that difficult. You can have a look into https://github.com/openhab/openhab2-addons/pull/5071 to get an idea of how it is working. Will you give it a try? Do not hesitate to ask if you are facing any issues.

**Comment by mlimbacher** [comment]
Actually, I'm facing problems. I did some changes (just like for the vibration sensor), put the jar to the addons folder and started openhab. The new sensor however doesn't work. The stated error is "org.openhab.binding.deconz.internal.handler.DeconzBridgeHandler cannot be cast to org.openhab.binding.deconz.internal.handler.DeconzBridgeHandler". Do you have a good idea where I should look at?

**Comment by cweitkamp** [comment]
Just a guess: Did you uninstall the original binding before putting the modified version into your `addons/` folder?

**Comment by mlimbacher** [comment]
I had that guess, too. I had to do some more things like installing some perquisites. 
I think it's working now. I'll do some tests in the next days or weeks (depending on how much time I can spend). Afterwards, I'll learn how to commit my work.

**Comment by mlimbacher** [comment]
Couldn't sleep - so I did some testing. Maybe you have another good hint. 
The Rest-API says [...]"battery":93[...]. However, Paper UI says battery level is -NaN %.  I don't see why.
REST output for this sensor looks very similar to all the others.
Thanks in advance!

**Comment by cweitkamp** [comment]
That is a known issue (see e.g. https://github.com/openhab/openhab2-addons/issues/6362 or https://community.openhab.org/t/deconz-no-value-battery-level-change/84585/3).
