### ISSUE TITLE
[gpstracker] Add support for PhoneTrack (Android) as an additional source

### ISSUE THREAD

**Issue by TRSx80** [openhab/openhab-addons#6305]
Good evening! :)

I just began looking into bringing some family location data into openHAB. My first (and usually only) place to look for Android software is F-Droid, where I found [PhoneTrack](https://f-droid.org/en/packages/net.eneiluj.nextcloud.phonetrack/). That page says that it is not only for NextCloud, but "any custom server [using] (GET or POST HTTP requests)."

That got me going over to [the GitLab page for their server](https://gitlab.com/eneiluj/phonetrack-oc) where I found this [very interesting comparison of different (what they call) "Logging methods"](https://gitlab.com/eneiluj/phonetrack-oc/-/wiki_pages/userdoc#logging-methods).

Now, being a very privacy conscious and F/LOSS supporting person myself, all of this information rang very true to me. GPSLogger is very favorably compared, however I agree with them that I don't see any need to give that app access to my Contacts on my phone. So, at the moment, it seems as PhoneTrack would be my preferred solution, for sending the location data to openHAB.

Then reading the openHAB [GPSTracker Binding docs](https://www.openhab.org/addons/bindings/gpstracker/) I realized that currently, only OwnTracks and GPSLogger are supported. So I decided to create this issue.

I am imagining this is going to require either:
1. formatting the data which is sent to the binding from PhoneTrack into a format that the binding will accept, OR
2. adding support to the binding for the format as it comes from PhoneTrack

So I figured I would ask the maintainers a couple questions:
1. Which of the above is the better way to go about it?
2. If I can get something working, what are the chances it gets included back into the binding (I suppose this only applies to case 2 from above)?

FWIW, I think I will touch base with the developers of PhoneTrack as well, and see what they think.

**Comment by kaikreuzer** [comment]
@gbicskei As the author of the binding in question: Would you want to comment?

**Comment by gbicskei** [comment]
@TRSx80 
Hi,
The comparison is interesting indeed. I've checked it's [integration option](https://gitlab.com/eneiluj/phonetrack-android/-/wiki_pages/userdoc), and it looks promising. I don't have this app installed: could you check the authentication option as well? It need to support the basic authentication to get through myopenhab.org. If this is OK, than both options could work. I would also check the community's opinion on openHAB forum.
BR

**Comment by TRSx80** [comment]
Oh you are right, it seems you can make a custom POST URL using provided variables just like you can in GPSLogger in the format requited for openHAB. Somehow I didn't even see that.

I did not yet contact the author of PhoneTrack, due to login issues at GitLab which I have now solved in the meantime.

To be honest, I was sort of in a hurry just to see if I could get something working, and installed GPSTracker (it is available as a direct download pre-compiled APK from their GitHub), installed that, and got it working following the instructions within minutes. I can see why that program was chosen: lots of options, it's a neat program. And it has been flawlessly reporting my location to my home server as configured (I had read some post/review about GPS logging options somewhere else and that writer's conclusion was to use OwnTracks, as that was the only reliable solution; I found this not to be the case at all).

In addition, I am not even sure it asked for permissions to access Contacts, although I cannot swear to that. I will do another test installation on another phone (or re-install on mine) and pay closer attention next time (perhaps this has changed since that comparison I linked to was written?).

Because I thought it might be a while until PhoneTrack was supported (if ever) I never even installed or played with it yet. But now that I seem to have gained your attention, I suppose I had better make an effort to do so. :)

**Comment by TRSx80** [comment]
OK, now that I have my GitLab login issue sorted, I was able to [create an issue](https://gitlab.com/eneiluj/phonetrack-android/issues/144) over there at PhoneTrack about openHAB integration. Right now I don't have time to play with the software, until I do maybe I will get lucky and the author of that software might reply about authentication. If not, I will try and make some time to do some testing myself.

**Comment by TRSx80** [comment]
Well, that was fast (always a good sign!). :) [I received a reply already](https://gitlab.com/eneiluj/phonetrack-android/issues/144#note_239300647) from the maintainer of phonetrack-android and he said:
> Short answer is: no, authentication is not currently supported with "custom" log jobs. If the required authentication is "basic HTTP auth", I could add it pretty easily.
>
> Long answer is 😉 : When logging to PhoneTrack-Nextcloud with PhoneTrack-Android, authentication is done with a "token" placed in the logging URL (to target a session) and optionally another token for name reservation. I made it like that to maximize the amount of potential compatible logging softwares. In most compatible clients, you set an URL and bam, you're logging to PhoneTrack-Nextcloud app.
>
>I don't see why not supporting an authentication method for custom log jobs. It would make it potentially compatible with more server-side systems.
>
>Let me know if the required auth method is "basic HTTP" and I'll probably do it soon.

Since I do not use the myopenhab.org service, I am not familiar with how it's auth method(s) work, I figured I would punt this back to you for further advice?

**Comment by gbicskei** [comment]
Basic HTTP authentication is fine. Please also ask them if they can POST a JSON payload with parameters. This would be the same approach as GPSLogger app uses...

**Comment by eneiluj** [comment]
Hi there, I'm the developper of PhoneTrack-Android. Basic HTTP auth is now supported.

For the moment, values are passed as GET or POST key/value parameters. Is it really mandatory to send JSON payload to be received and parsed correctly by OpenHab?

I mean I could add it but I wanna make sure it's not already ok before doing some more work.

**Comment by gbicskei** [comment]
> Is it really mandatory to send JSON payload to be received and parsed correctly by OpenHab?

Hi,
Existing integrations with OwnTracks and GPSLogger post JSON payload with the parameters. Using the same approach would help to keep the these integration solutions together.

**Comment by eneiluj** [comment]
Thanks for your answer.

Alright, I'll add an option to enable such sending method. Could you briefly describe the expected JSON structure? Is it possible to send multiple points at once?

**Comment by gbicskei** [comment]
Here is the [documentation](https://owntracks.org/booklet/tech/json/) for OwnTracks message.

**Comment by eneiluj** [comment]
Thanks for the hints. PhoneTrack-Android is now able to send a JSON payload with basic HTTP auth. If someone feels like trying to make it work with OpenHab:

Just install the development version apk that can be found in [latest CI build artifacts](https://gitlab.com/eneiluj/phonetrack-android/-/jobs/353055109/artifacts/download). Then create a "custom log job", check "use POST method" and "send JSON payload", set the destination address to the target OpenHab instance, set the HTTP login and password, save, and finally start the logjob.

I hope "conn" parameter is not mandatory because it's not sent by PhoneTrack.

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by tjach** [comment]
I can confirm this works perfectly. It might be a good idea to post it as a third, supported application for Openhab presence.
