### ISSUE TITLE
[daikin] Add channel for swing mode and timer

### ISSUE THREAD

**Issue by JB5678** [openhab/openhab-addons#6308]
Swing mode and timer were both available in 1.x, but are missing from the new binding.  Is it possible to add them please?

Thanks,
Jeremy

**Comment by jimtng** [comment]
The swing mode is already implemented in daikin 2.x as the fandir channel

**Comment by JB5678** [comment]
Ah, yep so it is. I was going off of the docs, not actually checking for myself in the thing.

Sorry & thanks!

**Comment by ankou87** [comment]
Hi there,
which mappings must be used for the fandir? I can't find any information about that.

**Comment by jimtng** [comment]
I've just noticed that the "fandir" channel isn't on the current binding documentation. I'll make a note to fix that.

The options for fandir are: STOPPED, VERTICAL, HORIZONTAL, VERTICAL_AND_HORIZONTAL

```
String DaikinACUnit_Fan_Movement { channel="daikin:ac_unit:living_room_ac:fandir" }
```
