### ISSUE TITLE
[Bluetooth BlueZ binding] Access denied

### ISSUE THREAD

**Issue by wang70880** [openhab/openhab-addons#6321]
Hi all, I just installed openHAB2.4.0 on my Ubuntu 16.04, with bluez 5.45. When I install Bluetooth binding from paperUI and search for devices, it shows me:
` [ernal.discovery.BlueZDiscoveryService] - Cannot access BlueZ stack due to permission problems. Make sure that your OS user is part of the 'bluetooth' group of BlueZ.
`
However, I have to say that I checked the current user using `openhab-cli info`, and the information is shown below:
**Version:     2.4.0 (Build)
User:        openhab (Active Process 2195)
User Groups: openhab bluetooth**

I think I have added user openhab to bluetooth group, but it can not work. I even add openhab to root, but still it can not work. Can anyone help me figure it out? I have been struggling for a long time!

BTW, I have the following two questions irrelative to this topic, but it confuses me alot.
- Where is the binding installed from paperUI stored? I try to find any configure file and jsonDB, but there is no binding information.

- How can I debug a single bundle? For example I saw the source code of BlueZBridgeHandler from here[link](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.bluetooth.bluez/src/main/java/org/openhab/binding/bluetooth/bluez/handler/BlueZBridgeHandler.java) and I believe that this bundle gives me the wrong information. If I want to modify this source code, for example add some output sentence to check what exactly the error information is, like this message e in line 101
`if (e.getMessage() != null && e.getMessage().contains("AccessDenied"))`

How can I use maven to install and execute my test? Any idea is valueable for me and thanks a lot!

**Comment by J-N-K** [comment]
Can you explain how you solved that issue?
