### ISSUE TITLE
[yamahareceiver] volumeDB-channel should support 0.5dB steps

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#6326]
Yamaha receivers support increasing/decreasing the volume in 0.5dB steps. The volumeDB-channel of the yamahareceiver-binding actually accepts values like -30.5dB, but it seems to round the value to the next Integer. 

For example:
Receiver has a volume of -79dB. volumeDB-channels gets value of -78.5dB, the actual volume on the receiver changes to -78dB although it should change to -78.5dB.

## My Environment
* Version used: openHAB 2.4.0-1
* Operating System and version: Linux openHABianPi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l
* Yamaha Receiver: Yamaha CX-A5100

**Comment by zarusz** [comment]
I will have a look into this.

**Comment by hmerk** [comment]
closed due to inactivity
