### ISSUE TITLE
[yamahareceiver] Channel to switch HDMI OUT

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#6327]
Yamaha Receivers have multiple HDMI OUTs, e.g. HDMI_OUT_1 and HDMI_OUT_2. When controlling Yamaha Receiver with openHAB it would be great to be able to switch those HDMI OUTs, e.g. to disable HDMI_OUT_2 (with a connected preview monitor) and to enable HDMI_OUT_1 (with a connected beamer).

The Yamaha Extended Control API actually supports this:
http://192.168.0.55/YamahaExtendedControl/v1/system/setHdmiOut1?enable=true
http://192.168.0.55/YamahaExtendedControl/v1/system/setHdmiOut1?enable=false
http://192.168.0.55/YamahaExtendedControl/v1/system/setHdmiOut2?enable=true
http://192.168.0.55/YamahaExtendedControl/v1/system/setHdmiOut2?enable=false

It would be great, if the binding could also support that.

## My Environment
* Version used: openHAB 2.4.0-1
* Operating System and version: Linux openHABianPi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l
* Yamaha Receiver: Yamaha CX-A5100

**Comment by zarusz** [comment]
Hi @hr77,

The Yamaha Receiver binding is using the XML protocol and specifically the `/YamahaRemoteControl/ctrl` URL endpoint. The extended control is likely the JSON protocol (not supported on older models). If possible we should stick we the first one, as introducing the second will require more changes and will make existing feature detection harder across two protocols.

Can you please send me the response file?
http://<Your_Yamaha_IP>/YamahaRemoteControl/desc.xml

Essentially, you would need an extra switch channel for HDMI_OUT_1 and HDMI_OUT_2? 

My Yamaha model doesn't support multiple HDMI out, so need to rely on you here.

**Comment by hr77** [comment]
Hi zarusz,

I am sorry but I do not have the Yamaha receiver anymore. I changed back to my Marantz receiver, because OpenHAB integration was much more comfortable for me.

**Comment by fragger42** [comment]
Hi @zarusz ,
I have a RX-V775 with the same problem that I can't control HDMI out. The section from desc.xml is the following:
`<Menu Func_Ex="HDMI_Out" Title_1="HDMI OUT">
<Menu Func_Ex="HDMI_Out_1" Title_1="HDMI OUT 1">
<Put_1 Func_Ex="HDMI_Out_On" ID="P25">On</Put_1>
<Put_1 Func_Ex="HDMI_Out_Off" ID="P25">Off</Put_1>
<Get>
<Cmd ID="G1">Sound_Video,HDMI,Output,OUT_1=Param_1</Cmd>
<Param_1>
<Direct Func_Ex="HDMI_Out_On">On</Direct>
<Direct Func_Ex="HDMI_Out_Off">Off</Direct>
</Param_1>
</Get>
</Menu>
<Menu Func_Ex="HDMI_Out_2" Title_1="HDMI OUT 2">
<Put_1 Func_Ex="HDMI_Out_On" ID="P26">On</Put_1>
<Put_1 Func_Ex="HDMI_Out_Off" ID="P26">Off</Put_1>
<Get>
<Cmd ID="G1">Sound_Video,HDMI,Output,OUT_2=Param_1</Cmd>
<Param_1>
<Direct Func_Ex="HDMI_Out_On">On</Direct>
<Direct Func_Ex="HDMI_Out_Off">Off</Direct>
</Param_1>
</Get>
</Menu>
</Menu>`
The full file is this:
[desc.zip](https://github.com/openhab/openhab-addons/files/5286746/desc.zip)
It does work in FHEM (so I'm now doing MQTT to Openhab from there for HDMI switching). The FHEM YAMAHA binding had a similar problem of the missing option and did a change to support it which was discuessed here: https://forum.fhem.de/index.php?topic=41924.0

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by fragger42** [comment]
@hmerk : Can you please reopen? This enhancement request is still valid. Or are enhanxement reuests not wanted anymore?

**Comment by hmerk** [comment]
This is open for 2 years now and has been inactive for a long time now. So it is unlikely that someone will step in and implement this. But please feel free to come up with a contribution.

**Comment by fragger42** [comment]
@hmerk:
I tried it today and have patch that works fine on my side:
[HDMIOutput.patch.txt](https://github.com/openhab/openhab-addons/files/6887192/HDMIOutput.patch.txt)
How to get this into openhab-addons code? Can you commit this or has someone to review it?

**Comment by hmerk** [comment]
You need to create a Pull Request which needs to be reviewed by the maintainers.
Please check the contribution guidelines.

**Comment by hmerk** [comment]
Closed as related PR was merged
