### ISSUE TITLE
JDK11 / compile failures

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#6334]
A lot of the Travuis JDK11 builds fail recently in avmfritz. The reason is that bnd adds jaxb 2.3 as import, while we provide 2.2 in our feature. This can be fixed by adding the 2.2 bundles as dependencies to the binding pom, however I do not understand where 2.3 comes from and why the 2.2 in our core-compile-bom is ignored. `mvn dependency:tree` does not show the 2.3 dependency, only the 2.2. Did we upgrade something that might have introduced 2.3 recently? Any ideas?

**Comment by wborn** [comment]
I think it's caused by the Jollyday upgrade (https://github.com/openhab/openhab-core/pull/1170).
If I downgrade it my local Java 11 build succeeds again. :smile_cat:

**Comment by cweitkamp** [comment]
How ugly. What can we do?

**Comment by wborn** [comment]
I think it's only a compile time issue because the Jollyday bundle starts without issues on Java 11 and Karaf has a newer version in `lib/jdk9plus`:

```
$ ls lib/jdk9plus/
istack-commons-runtime-3.0.8.jar  javax.activation-1.2.0.jar    jaxb-runtime-2.3.2.jar
jakarta.xml.bind-api-2.3.2.jar    javax.annotation-api-1.3.jar  txw2-2.3.2.jar
```

**Comment by wborn** [comment]
Do you have time/plans to look into this issue @J-N-K or @cweitkamp? We could also downgrade Jollyday again for the time being until someone has time look into this.

**Comment by kaikreuzer** [comment]
Maybe removing the Java11 compilation on Travis could also be a temporary workaround?

**Comment by wborn** [comment]
I actually recently switch to building everything Java 11 on my desktop so it's easier to push https://github.com/openhab/openhab-distro/issues/768 forwards. So this issues forces me back to Java 8. :cry:

**Comment by J-N-K** [comment]
There problem is that 2.3 is not running on JDK8 (at least the last time I checked).

**Comment by kaikreuzer** [comment]
It is just currently painful for all contributors that the Travis check fails, although nothing is wrong with their PRs. If we disable it only for 2 days until the JDK11 issue is solved, it would imho still be helpful for the community (see https://github.com/openhab/openhab2-addons/pull/2531#issuecomment-551438602).

**Comment by wborn** [comment]
From my point of view it's better to revert the PR causing this issue again for a couple of days.

**Comment by cweitkamp** [comment]
I tried to look into it yesterday evening. But my new development environment was not prepared for Java 11. After setting it up my first steps were to investigate on the failing OHC tests for the Ephemeris bundle (see https://travis-ci.org/openhab/openhab-core/jobs/609155620?utm_medium=notification&utm_source=github_status) - which is probably related to the bump of the Jollyday library too. I did not find a working solution yet other than downgrading Jollyday again. I am sorry. I completely missed their integration of the different JAXB dependencies.

**Comment by kaikreuzer** [comment]
So anybody wants to create a revert PR for it then?

**Comment by wborn** [comment]
I was already working on it.

**Comment by cweitkamp** [comment]
Build is working again after https://github.com/openhab/openhab-core/pull/1195 and #6359.
