### ISSUE TITLE
[opensprinkler] Binding is not compatible with latest OpenSprinkler API version 2.1.9

### ISSUE THREAD

**Issue by quaylon** [openhab/openhab-addons#6348]
## Expected Behavior
Binding should connect the Thing to the OpenSprinkler device.

## Current Behavior
2019-11-06 12:41:52.357 [DEBUG] [nal.handler.OpenSprinklerHTTPHandler] - Refreshing state with the OpenSprinkler device.
2019-11-06 12:41:52.570 [DEBUG] [nal.handler.OpenSprinklerHTTPHandler] - Could not refresh current state of the OpenSprinkler device. Exception received: org.openhab.binding.opensprinkler.internal.api.exception.GeneralApiException: Could not get the current state of the rain sensor.

## Possible Solution
Failure is caused by the API changing the JSON response rain sensor tag from 'rs' to 'sn1' and 'sn2' when they added support for the second sensor. 

In the 'isRainDetected' function, the referenced constant, JSON_OPTION_RAINSENSOR, should be changed from 'rs' to 'sn1' at a minimum.  Ideally, both rain sensors (sn1 & sn2) would be anded or or'ed together based on a new bridge or thing parameter

## Steps to Reproduce (for Bugs)
1. Update OpenSprinkler firmware to version 2.1.9
2. OpenHab fails to update OpenSprinkler items and things

## Context
OpenHAB is not able to update the sprinkler status on any GUI

## Your Environment

* Version used: OpenHAB 2.4 OpenHab AddOns 2.4
* OS: Debian 4.9.189-3+deb9u1

**Comment by Hilbrand** [comment]
Should be possible to fix with `@SerializedName(value = "sn1", alternate = "rs")` on variable https://github.com/Hilbrand/openhab2-addons/blob/0589987e48343424aad9c414a2d6c252a381f506/bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/api/OpenSprinklerHttpApiV100.java#L259

**Comment by FlorianSW** [comment]
Looking into it! :) Thanks for reporting and please excuse my very late response :(

**Comment by FlorianSW** [comment]
PR: #6650

**Comment by FlorianSW** [comment]
The PR is merged.
