### ISSUE TITLE
[opensprinkler] Add channel to display voltage draw for each valve

### ISSUE THREAD

**Issue by lukiep** [openhab/openhab-addons#6386]
## Your Environment

* Version used: 2.5M2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): OpenHABian 1.5
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

I would like to be able to see what the current mA draw for each zone is

The information seems to be available in the opensprinkler app. 

The reason I’d like to do this is occasionally a valve gets stuck open and continue to draw power. Short of a flow meter, which I can’t currently do, this will help determine where the valve should be off, but continues to be open.

**Comment by FlorianSW** [comment]
Hmm, the API exposes a value `curr` for the controller itself, the doc says about that:
`total current draw of all zones (in milliamps). This is only available for controllers with current sensing capability.`

However, this seems to be the value for all zones, not for each zone as a separate value. Is that what you mean here?

**Comment by lukiep111** [comment]
Yes you are correct.  There is a single combined value of current draw for all zones. I think it would still be helpful if possible
