### ISSUE TITLE
[samsungtv] Samsung Binding version 2.5.0 receiving data, cannot send commands

### ISSUE THREAD

**Issue by TheOrion666** [openhab/openhab-addons#6398]
I have been  trying to add my Samsung TV to openhab. It does appear (by direct finding and also tried via adding it manually in .things). It receives information such as if it's online or offline, input name, channel, etc. But I cannot send command such as turning the TV off or mute. Version 2.4.0 was not even able to connect to my TV, hence why I upgraded.

## Expected Behavior
Should be able to send supported commands to the TV

## Current Behavior
[events.log](https://github.com/openhab/openhab2-addons/files/3849354/events.log)
[openhab.log](https://github.com/openhab/openhab2-addons/files/3849355/openhab.log)

## Your Environment

Latest Stable (2.4.0). Addon is on 2.5.0
Java 8
Windows 10

**Comment by hmerk** [comment]
closed due to inactivity
