### ISSUE TITLE
[Rotel] invalid value 44.1K for key freq

### ISSUE THREAD

**Issue by stefanroellin** [openhab/openhab-addons#6417]
The frequency response from an integrated amplifier A14 seems to be different than expected:

```
19:47:56.066 [DEBUG] [internal.communication.RotelConnector] - handleIncomingMessage: bytes 667265713D34342E314B24
19:47:56.067 [DEBUG] [internal.communication.RotelConnector] - handleValidAsciiMessage: chars *freq=44.1K*
19:47:56.068 [DEBUG] [g.rotel.internal.handler.RotelHandler] - onNewMessageEvent: key freq = 44.1K
19:47:56.069 [DEBUG] [g.rotel.internal.handler.RotelHandler] - Invalid value 44.1K for key freq
````
According to the documentation http://www.rotel.com/sites/default/files/product/rs232/A12-A14%20Protocol.pdf the response should not contain "K" at the end, but apparently does. 

* Version used: openHAB 2.5.0.M5
* The software version of the A14 is the newest:  V2.31 - January 23, 2019 
* The device is connected with RS232. However the problem exists also if connected by network.

**Comment by lolodomo** [comment]
Fantastic to finally get a first feedback from a user with a Rotel implementing the ASCII. Don't hesitate to provide a more detailed feedback. 

Regarding your issue, I will provide a fix today or tomorrow.

**Comment by stefanroellin** [comment]
Thanks for the fix! It works as expected.
