### ISSUE TITLE
[map] Transformation not applied to values shown in Paper UI

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-addons#6421]
Hello,

I am using openHAB 2.5.0 Build #1759

Using Air Quality Binding from examples:

**cat /etc/openhab2/transform/airquality.map**
UNDEF=No data
NULL=No data
NO_DATA=No data
GOOD=Good
MODERATE=Moderate
UNHEALTHY_FOR_SENSITIVE=Unhealthy for sensitive groups
UNHEALTHY=Unhealthy
VERY_UNHEALTHY=Very unhealthy
HAZARDOUS=Hazardous

**/etc/openhab2/things/airquality.things:**
airquality:aqi:home "AirQuality" @ "Home" [ apikey="XXXXXXXXXXXX", location="xx.xxxxx,xx.xxxxx", refresh=60 ]

**/etc/openhab2/items/airquality.items**
String Aqi_Description "AQI Level [MAP(airquality.map):%s]" <flow> (AirQuality) { channel="airquality:aqi:home:aqiDescription" }

MAP transformation is installed via **/etc/openhab2/services/addons.cfg** and I see in Paper UI the same information 
transformation=map,javascript

But why in paper UI I see this item is not transforming :(

![image](https://user-images.githubusercontent.com/23188529/69141024-71f96f80-0acc-11ea-89e8-260b1b7140ba.png)

Edward

**Comment by udo1toni** [comment]
afaik Paper UI doesn't use the dynamic labels like in items files and doesn't support transformation in labels.

**Comment by daftndaze** [comment]
For me this has worked on OH 2.4. Updated today to OH 2.5. Not working anymore.

**Comment by SchoenS** [comment]
I have the same issue when using such transformations in dummies of HABPanel. In OH 2.4 this worked and not anymore in OH 2.5

**Comment by hmerk** [comment]
closed due to inactivity
