### ISSUE TITLE
HUE binding look for bridge on different port

### ISSUE THREAD

**Issue by thedannymullen** [openhab/openhab-addons#6426]
I have my deconz Hue emulated bridge on port 8090.  Because I this I need to specify the port in the config file.  I tried as seen below the help docs state port is valid, but it does not get picked up.

`Bridge hue:bridge:00212E048A08[ ipAddress="192.168.1.20", port="8090", userName="USERNAME" ]  
{
}`

I also tried like this:
`Bridge hue:bridge:00212E048A08[ ipAddress="192.168.1.20:8090", userName="USERNAME" ]  
{
}`

Neither style of config file works.  **My Solution was:** configure a new thing in paper ui.  Once configured, I can save my config file and everything works.  

I have a couple developer questions:
1. Can port be specified like the docs say?
2. If so is this a bug or is the syntax incorrect?

 I am currently on 2.5m1 but I tried this syntax on 2.5m5.  It did not function there either.

**Comment by cweitkamp** [comment]
The `port` i an integer parameter. Did you try this - without hyphens:

```
Bridge hue:bridge:00212E048A08 [ipAddress="192.168.1.20", port=8090, userName="USERNAME"]
```

**Comment by thedannymullen** [comment]
@cweitkamp thanks for the information.  I will try again in the next 24hrs.

**Comment by thedannymullen** [comment]
I tried port=8090 on 2.5m1 it did not work.

**Comment by thedannymullen** [comment]
Looks like port = 8090 works on the 2.5m5 build, but not on the m1.  

This is good news, I will fix the config file when I update.  Currently the hue emulation only works for me on 2.5m1, so I can't update.
