### ISSUE TITLE
[pixometer] Follow up enhancements after initial binding implementation

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-addons#6444]
This is meant to be a storage for my "to-do's" that are based on the PR discussion from #4162.

Next steps should be:
- [ ] Introduce API related content in a special class (https://github.com/openhab/openhab-addons/pull/4162#discussion_r346169640)
- [ ] Move all API calls into the bridge implementation as a central point of the connection (https://github.com/openhab/openhab-addons/pull/4162#discussion_r336180136)
- [ ] Let things request api contents from the bridge
- [ ] Use api responses for a more granular error handling (https://github.com/openhab/openhab-addons/pull/4162#discussion_r347110346)

**Comment by hmerk** [comment]
@Confectrician Are you still working on this or should we close this issue ?

**Comment by Confectrician** [comment]
I am not sure if I will come back to pixometer at all. So we can close this one.

I will find it in case it will be useful again. :)
