### ISSUE TITLE
[sensebox] dynamic channel support for the senseBox Binding 

### ISSUE THREAD

**Issue by Bastlerstube** [openhab/openhab-addons#6455]
Original feature request in german:

seid einiger Zeit nutze ich Ihr Openhab senseBox Binding, doch bin jetzt an einem Punkt angekommen, wo ich mich mit dem Binding selbst auseinander setzen muss.

Mein Ziel ist es zusätzliche Sensoren von der openSenseMap einzubinden, was leider das existieren Binding nicht unterstützt, da die Channels im Binding selbst fest vorgegeben sind und ich noch keinen Weg gefunden habe, die anderen Sensordaten abzufragen.

Konkret teste ich grade eine senseBox Konfiguration, die selbst erstellt ist:

https://opensensemap.org/explore/5dd98e596e5e9f001a324e99

Ich würde mich bitte sehr über einen Tip freuen, wie ich es schaffen kann, auch noch andere Sensordaten abzufragen, bei anderen Bindings ist es möglich die Channel selbst zu erstellen.

Gibt es auch beim senseBox Binding die Möglichkeit, das entsprechend zu erweitern?

Das würde das OpenHab für Maker noch viel Interessanter machen.

**Comment by hakan42** [comment]
Original feature request in german:

seid einiger Zeit nutze ich Ihr Openhab senseBox Binding, doch bin jetzt an einem Punkt angekommen, wo ich mich mit dem Binding selbst auseinander setzen muss.

Mein Ziel ist es zusätzliche Sensoren von der openSenseMap einzubinden, was leider das existieren Binding nicht unterstützt, da die Channels im Binding selbst fest vorgegeben sind und ich noch keinen Weg gefunden habe, die anderen Sensordaten abzufragen.

Konkret teste ich grade eine senseBox Konfiguration, die selbst erstellt ist:

https://opensensemap.org/explore/5dd98e596e5e9f001a324e99

Ich würde mich bitte sehr über einen Tip freuen, wie ich es schaffen kann, auch noch andere Sensordaten abzufragen, bei anderen Bindings ist es möglich die Channel selbst zu erstellen.

Gibt es auch beim senseBox Binding die Möglichkeit, das entsprechend zu erweitern?

Das würde das OpenHab für Maker noch viel Interessanter machen.

**Comment by Hilbrand** [comment]
@hakan42 Just a meta comment. We've removed all binding specific labels as we use labels for meta information only. As you seem to have added such labels recently I wanted to inform you about this change.

**Comment by hakan42** [comment]
Cool, thank you for the heads-up.

**Comment by hakan42** [comment]
Note to self: API URL is:

https://api.opensensemap.org/boxes/5dd98e596e5e9f001a324e99

**Comment by hmerk** [comment]
closed due to inactivity
