### ISSUE TITLE
[bluetooth.bluegiga] BluetoothDevice manufacturerId always null

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#6465]
Exactly the same as #4658, just for the bluegiga binding. @ssalonen: Did you test with BlueGiga as well and had other results?

**Comment by ssalonen** [comment]
@pfink I have not tested with bluegiga since I do not have the hardware, actually.

However, if I recall correctly, I think there were references to manufacturer id in bluegiga implementation?

**Comment by pfink** [comment]
Yes, I saw the code does set it, but didn‘t do deep dive yet.

**Comment by pfink** [comment]
Cause of the issue is a type casting error here: https://github.com/openhab/openhab2-addons/blob/63114233c7f7002d1fbfaee707a122e14bc254c0/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/BlueGigaBluetoothDevice.java#L196

Returned type is actually `Map<Short, int[]>` which obviusly cannot be casted into byte. Have no clue why there is no exception thrown. Fix is in preparation.

**Comment by cpmeister** [comment]
This was fixed as of #6995 .
