### ISSUE TITLE
Loxone Binding not working with new miniserver firmware 10.3.11.25

### ISSUE THREAD

**Issue by geert-janklaps** [openhab/openhab-addons#6466]
## Expected Behavior
Connection to the Loxone Miniserver working

## Current Behavior
Thing status of the miniserver states OFFLINE - COMMUNICATION_ERROR
![2019-11-28_11-06-57](https://user-images.githubusercontent.com/2744548/69797019-4ca4e980-11cf-11ea-940a-f3d1b946bb12.png)

## Possible Solution
- Remove the existing thing from openHAB
- Restart openHAB
- Miniserver can be added again from inbox

## Steps to Reproduce (for Bugs)
1. Upgrade Loxone Miniserver to latest firmware
2. Check thing status in openHAB

## Your Environment
- OpenHAB 2.5M5 running in a docker container
- Loxone Miniserver with firmware 10.3.11.25

**Comment by ppieczul** [comment]
The Miniserver forgot the authentication tokens after the upgrade. You need to delete the token and Enter password again in the binding configuration.

**Comment by mgbowman** [comment]
Just following up to what @ppieczul said, I had the same problem and clearing the token from the thing configuration and re-authenticating solved it.

**Comment by Gekke-Jakke** [comment]
Exactly, it solved my issue as well. (Sorry for the delay in response)
I'm up and running again using the latest firmware! Thanks for the support!
