### ISSUE TITLE
[mqtt] homie binding cannot handle "-" in node/property IDs (for settable properties)

### ISSUE THREAD

**Issue by sebastianohl** [openhab/openhab-addons#6487]
The mqtt homie binding handles a node or property ID containing a "-" not correct while publishing values. The internal representation of 
For readonly properties, this problem do not come up because handleCommand is not called for settting values.

## Expected Behavior
org.openhab.binding.mqtt.homie.internal.homie300.Device.node(.properties) need to store the keys 
containing a "-" also with "_2D" or the lookup need to use the correct representation.

## Current Behavior
org.openhab.binding.mqtt.homie.internal.homie300.Device.node stores the key correctly (with a "-"). However, the search for a property by channelUID trys to look a node and the property not with a "-" but with a "_2D" as a substitute. This results in the error message "Channel XXX not supported!" from org.openhab.binding.mqtt.generic.AbstractMQTTThingHandler.handleCommand() because the channel cannot be found.

## Possible Solution
decide for one representation of "-" nodes/properties

## Steps to Reproduce (for Bugs)
create a homie device which contains nodes/properties with "-"s.
One property need to be settable
Public a new value to this propoperty

## Context
I want to set the target flow temperature of my heating controller which is currently named "heating-controller". 

## Your Environment
* Version used: openhab 2.5M5 (and git f156a05f3db42c639f53e6ee545d8cb0485ff5b3 from 2019, Nov 28)
* Operating System and version: RasberryPI 3B, raspian, Java(TM) SE Runtime Environment (build 1.8.0_65-b17)

**Comment by J-N-K** [comment]
Can you please try https://janessa.me/esh/org.openhab.binding.mqtt.homie-6487.jar and see if this works? Instructions: https://janessa.me/esh/ (use option 2!)

**Comment by sebastianohl** [comment]
thanks the jar fixed the problem. Are the changes already merged to the master? or is this your private branch?

**Comment by J-N-K** [comment]
Private. I‘ll do a PR if it works. I couldn’t test it because setting up a homie device manually is not that easy
