### ISSUE TITLE
[mqtt] [homie] property set behavior with retain flag

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-addons#6493]
Using OH 2.5M6

When controlling a homie device from openhab, the set message is correctly sent with retain false.

`   
qos : 0, retain : false, cmd : publish, dup : false, topic : homie/testdimmer/dimmer/dimmer/set, messageId : , length : 38, Raw payload : 4954
`

If I close and reopen the client subscribing to the set message, the "same" set message is resent with retain true. Ie. I leave OH connected to the broker, disconnect the homie client and then reconnect the homie client OH is sending the set message again and this time with retain true.

`   
qos : 0, retain : true, cmd : publish, dup : false, topic : homie/testdimmer/dimmer/dimmer/set, messageId : , length : 38, Raw payload : 4954
`

So what is happening, if the homie device goes offline and then reconnects to the broker, it is always getting the last set message from OH - even though it has already received this message. 

If I use a client like MQTT Explorer to send the set message, that message does not reappear if the homie device goes offline and back online.  So I am certain this retain true set message is coming from OH

So it seems that OH is sending a second set message with retain true when the homie device reconnects to the broker. Is there a way to turn this behavior off?

Also posted to see if anyone in community has an idea.

https://community.openhab.org/t/mqtt-homie-set-behaviour/86727/2

**Comment by mjcumming** [comment]
As a work around, any homie device can check the retain property of a set message and if it is true ignore that set message. I have been unable to determine at where this set message with retain true is coming from.

**Comment by davidgraeff** [comment]
This is a bug indeed. The underlying mqtt library has changed and also how retained is used. The mqtt binding might use the mqtt library API in a wrong way now.

**Comment by mjcumming** [comment]
Thanks for the note

**Comment by jochen314** [comment]
@davidgraeff 
I think, this is wrong:
`org.openhab.binding.mqtt.homie.internal.homie300.Property.createChannelFromAttribute()`:
```
        if (attributes.settable) {
            b = b.withCommandTopic(commandTopic).withRetain(true);
        }
```
As 5.3.2 of the spec says:
```
A Homie controller publishes to the set command topic with non-retained messages only.
```
But it would imply, that the message is **always** sent with `retain : true` which does not seem to be what we experience.

**Comment by jochen314** [comment]
OK, checking the specs:
```
[MQTT-3.3.1-8] | When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is sent as a result of a new subscription being made by a Client.
[MQTT-3.3.1-9] | It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received
```
This reads to me, that the client _only_ gets `retain=true` on a new connection. When the message is delivered directly we always have `retain=false`
