### ISSUE TITLE
[yamahareceiver] Support for RX-V575 with Zone_B/Speaker_A/Speaker_B is missing

### ISSUE THREAD

**Issue by flaute** [openhab/openhab-addons#6504]
The Yamaha Receiver RX-V575 "Zone_B" is not supported by the current version of the yamahareceiver binding.

The RX-V575 has 2 zones. The first zone is handled as the "Main_Zone" and works perfectly with the binding. The second zone is handled as "Zone_B" but is not supported by the current implementation that focuses on the emulation of "Zone_B" as "Zone_2" that was implemented for the HTR-xxxx.

The current emulation of "Zone_B" as "Zone_2" also just implements channels for "power", "mute" and "volume". Two important features are missing: "Speaker_A" and "Speaker_B" for switching off speakers pair A and B separately.

It would be nice to
- support "Zone_B" of the Yamaha RX-V575
- support the channels "Speaker_A" and "Speaker_B"

**Comment by flaute** [comment]
I think that emulating the "Zone_B" as "Zone_2" is not the cleanest way of solving the problem of "Zone_B".

The channels "power", "mute", "volume", "speaker_a", "speaker_b" are features that are originally placed in the commands for the "Main_Zone" (desc.xml). This is why I don't think that the approach of emulating "Zone_B" as "Zone_2" and then redirecting all "Zone_2" commands to the "Main_Zone" is compallingly needed.

I forked the repo and implemented all "Zone_B" commands (that are originally part of the "Main_Zone") as normal commands or channels in the "Main_Zone".

**Comment by flaute** [comment]
This is my fork:

https://github.com/flaute/openhab2-addons/tree/yamahareceiver-rx-v575/bundles/org.openhab.binding.yamahareceiver

**Comment by Hilbrand** [comment]
Feel free to create a pull request for your changes :smile:

**Comment by zarusz** [comment]
To add a bit of more context, the emulation of Zone_B as Zone_2 was introduced to retrofit that HTR-xxxx family into already established zone thing with defined channels (power, mute, volume). Without it, we would have to introduce new channels on the zone things specific to HTR-xxx (which other models do not have).

Looking briefly at your fork @flaute it looks like you've chosen to drop the Zone_B emulation and introduced new channels (zone_b_mute, zone_b_volume, etc). My thought on that are:
- Will that work on HTR-xxx? Ideally someone from community could test this out.
- That introduces a change in the way how HTR-xxxx would have to configure the thing.
- There is more channels there are specific to HTR-xxxx and RX-V575 that other models won't use. We are exposing the internal model differences to the outside users (less encapsulation).

I fully agree that adding new features to handle Speaker_A and Speaker_B channels (while still specific to RX-V575) makes sense. However, I am more on the side of:
- Continuing to do the emulation (as a way of abstraction of model differences), but make it work with RX-V575.
- Introduce just two new channels for Speaker_A and Speaker_B

What do you guys think?

**Comment by flaute** [comment]
A few more thoughts on this:

I still don't think that "Zone_B" should be emulated as "Zone_2" because all "Zone_B" commands (Power, Mute, Volume) are originally implemented as commands in the "Main_Zone" and should therefore be implemented as channels in the "Main_Zone".

However, there are many commands that are specific to a certain model (including the "Zone_B" ones mentioned above). I think these ones should all be implemented in a common and generic way without any model specific or zone specific  subclassing, because other models may have these features, too and should be supported out-of-the-box once the command has been implemented.

Furthermore there are some model-specific variations to existing commands (like "Vol" instead of "Volume" ([example](https://github.com/openhab/openhab2-addons/blob/746ecb7a8f856f8e21ca31b61b5edd4c6a65b5b4/bundles/org.openhab.binding.yamahareceiver/src/main/java/org/openhab/binding/yamahareceiver/internal/protocol/xml/ZoneControlXML.java#L123))). I think the current way of "overwriting" the commands is a good approach.

**Comment by hmerk** [comment]
closed due to inactivity
