### ISSUE TITLE
[samsungtv] Powering On N Series TVs Unreliable

### ISSUE THREAD

**Issue by Cossey** [openhab/openhab-addons#6535]
## Current Behavior
N Series TVs do not reliably Power On. Only sometimes do they Power On when triggered in OpenHAB.

## Expected Behavior
The N Series TV should always Power On when triggered. 

## Solution
* Check the Model No for the N series in the _Information Endpoint_ to use specific functionality
* Ensure the Websocket connection stays open after the UPnP Service goes down until closed by TV
* Dictate the Power state of the TV based on the Websocket state versus the UPnP Service availability

When Powering On
* Websocket connection is still open: send TV_Power command.
* Websocket connection is closed: send the WoL Packet.

This should then resolve the issue.

## Steps to Reproduce (for Bugs)
1. Power Off the TV. Then try to Power it on again after a few seconds. Failure.
2. Power Off the TV. Wait for around a minute and then power On. Success.

## Context
Failure to reliably Power On causes problems in the automation flow. This is due to the way WebSocket functions on N Series TVs. I have tested using a Websocket Test tool direct to the TV Remote API to determine the correct way to approach Powering On the TV.

## Your Environment
Raspberry Pi 3B+
openHAB 2.5.0.M5 Docker
Samsung UA50NU7090

**Comment by hmerk** [comment]
closed due to inactivity
