### ISSUE TITLE
Automatically generate channel list into README.md

### ISSUE THREAD

**Issue by gitMiguel** [openhab/openhab-addons#6545]
Opening this feature request to track long discussed "automatic document generator" and especially channel list. Thought came while developing Vallox Binding. Why do I have to declare channels both in readme.md and .xml configuration file? Could a part of readme be generated from channel configuration file?

Quoting @Hilbrand from https://github.com/openhab/openhab2-addons/issues/5374
> While we're at it. There was also the wish to generate the channel list from the xml files for the  documentation. Maybe we can also look into that too.

Here's two older issues about the same thing:
https://github.com/eclipse/smarthome/issues/657
https://github.com/openhab/openhab2-addons/issues/348

Under ESH it got as far as a PR but didn't get anywhere due inactivity:
https://github.com/eclipse/smarthome/pull/1853 

@cdjackson you merged something like this into zwave if I'm not totally mistaken? https://github.com/openhab/org.openhab.binding.zwave/pull/769

**Comment by cdjackson** [comment]
I worked on this for a while, but in the end didn’t use it. For ZWave, I have a database that generates the XML files, and it also generates the MD files for the documentation. This was easier and more useful (for me) than the database->XML->MD route.

**Comment by Hilbrand** [comment]
Yes would be great to have. First step would be to specify what columns should be in the tables for the readme and to identify some possible mismatches. For example the QoM or QuantityType channels most of the time don't have a unit in the pattern so if we want the unit in the readme this is not directly possible. Maybe something that can be discussed on the forum with users, with what they find important?

With the maven build system we have easier access to the core classes that parse the xml files, so we can reuse that code. I've done some very preliminary prototyping on reading those files and generating code (because not only the readme can be made simpler. The xml files contain also information duplicated in code.).

On a side note. As a side effect of this change it would break my unit test for the Network UPS Tools binding as the unit test reads the readme and checks if that matches with the channels xml :smile:

**Comment by gitMiguel** [comment]
Here's a suggestion as including just few basic columns. Units could be put in the description:

`| Channel | Type   | Writable | Description | `

Discussion in the forum would be helpful. Maybe a multiple selection poll.

> I've done some very preliminary prototyping on reading those files and generating code

Do you have something to show in your repo? I'm tempted but unsure to start testing with a base from https://github.com/eclipse/smarthome/pull/1853.

**Comment by Hilbrand** [comment]
Discussion on the forum would be a good thing I think. It should probably also include binding, thing and channel configuration. 

I don't have anything online yet. I'll have to dig up the source and post an update here.

The old pr doesn't look like a good starting point as all xml data object for the representation can simply be reused from core and don't need to be rewritten. So it would probably be a lot simpler. I started something as a maven plugin.

About including the tables in the readme. We use vue for the documentation generation. This has the option to include files. I don't know if this works on the addon documentation, but we could simply put such a tag in each readme where the table should be included and then generate that table file.

**Comment by gitMiguel** [comment]
> Discussion on the forum would be a good thing I think.

As a non-native English speaker I'm hoping that someone else volunteers.

> It should probably also include binding, thing and channel configuration.

This issue is about channel list. Should we discuss here only about the tool that generates these lists and continue the bigger picture maybe in #5374



> I don't have anything online yet. I'll have to dig up the source and post an update here.
> 
> The old pr doesn't look like a good starting point as all xml data object for the representation can simply be reused from core and don't need to be rewritten. So it would probably be a lot simpler. I started something as a maven plugin.

Ok, sounds good. I'll wait.



> About including the tables in the readme. We use vue for the documentation generation. This has the option to include files. I don't know if this works on the addon documentation, but we could simply put such a tag in each readme where the table should be included and then generate that table file.

Yes. So this "extractor tool" generates different .md files containing lists of channels, thing configurations etc. and vue would combine these for website? After going through docs and website repos a question came up. Is there something stopping us if we break binding documentation into smaller files? Off course vue should handle old and new type documentation.

**Comment by J-N-K** [comment]
This might be difficult for bindings like onewire where the channel are generated dynamically at runtime. It could be generated similar to what @cdjackson describes, as there is a properties [file](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.onewire/src/main/resources/sensor.properties) which contains the necessary information.

**Comment by gitMiguel** [comment]
I've always imagined this tool to be optional. So manually creating readme would be the default way as it has been and this eases document creation when dealing with lots of channels.

**Comment by shainmock** [comment]
thank you for this guidance






[خرید آب استاندارد مرک](https://www.avecinashimi.com/product/%d8%ae%d8%b1%db%8c%d8%af-%d8%a2%d8%a8-%d8%a7%d8%b3%d8%aa%d8%a7%d9%86%d8%af%d8%a7%d8%b1%d8%af-%d9%85%d8%b1%da%a9-water-standard-188050-188051-188052/)

**Comment by hmerk** [comment]
closed due to inactivity
