### ISSUE TITLE
[shelly] Add channel for button events

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#6548]
Currently, the shelly binding sends various custom button events on an undocumented `events` channel.
As mentioned in https://github.com/openhab/openhab2-addons/pull/6320#discussion_r355114883, it should instead make use of the existing `SYSTEM_BUTTON` channel type.

**Comment by markus7017** [comment]
This means a new channel of type system.button for the short and long push events, correct?

**Comment by kaikreuzer** [comment]
Yes - or rather replacing the current "event" channel by a "button" channel of this type.

**Comment by markus7017** [comment]
ok

Relay:
- a channel of type system.button would trigger SHORTPUSH and LONGPUSH
- I would same that BTN_ON and BTN_OFF correspond to the input channel in switch mode, so this could be achieved by the input channels.
- Is system.button restricted to SHORT/DOUBLE/LONG or does it also accepts PRESSED and RELESED? This would allow to use SHORT/LONG when in momentary switch mode and PRESSED/RELEASE when button is in edge mode. Is it possible to change the channel type dynamically depending on the configured button mode?
- OUT_ON/OUT_OFF correspond to the output channel

Roller:
Is there a pendant for the roller supporting OPEN/CLOSE/STOP? Otherwise I could define an own trigger channel with those payloads.

I will also add &lt;event&gt; definitions for the alarm channel.

**Comment by kaikreuzer** [comment]
> a channel of type system.button would trigger SHORTPUSH and LONGPUSH

To be precise: SHORT_PRESSED and LONG_PRESSED

> I would same that BTN_ON and BTN_OFF correspond to the input channel in switch mode, so this could be achieved by the input channels.

Yes, this is indeed a state channel, so the input channel is the best match.

> Is system.button restricted to SHORT/DOUBLE/LONG

It only issues SHORT_PRESSED, DOUBLE_PRESSED and LONG_PRESSED events.
For edge mode, you would go for SYSTEM_RAWBUTTON, which issues PRESSED and RELEASED events instead.

> Is it possible to change the channel type dynamically depending on the configured button mode?

Yes, you can add/remove channels in your handler code by calling `editThing()`. Just make sure that those channels are NOT defined in the XML, because those are expected to be always present.

> OUT_ON/OUT_OFF correspond to the output channel

Indeed.

> Is there a pendant for the roller supporting OPEN/CLOSE/STOP?

No, but the question is if this rocker couldn't be used for other things than rollershutters as well?
If it is meant as an input device, the SYSTEM_RAWROCKER would be the best match. If it is always tied to the rollershutter actuator in the shelly device itself, my suggestion would be to not offer events at all, but only update the rollershutter state channel.

**Comment by markus7017** [comment]
I'm still thinking on the best implementation
- the input channel is independend from the button events (input is the state and we have the event)
- system..rawbutton would work for the relay
- system.button for the short/long push events
- no system default for the roller events
- nor for the sensor events

Adding 4 channels for those events doesn't make sense

I picked the follow sample from the OH documentation:
&lt;channel-type id="trigger-channel"&gt;
    &lt;kind>trigger&lt;/kind&gt;
    &lt;label>Trigger Channel&lt;/label&gt;
    &lt;event&gt;
        &lt;options&gt;
            &lt;option value="PRESSED">pressed&lt;/option&gt;
            &lt;option value="RELEASED">released&lt;/option&gt;
            &lt;option value="DOUBLE_PRESSED">double pressed&lt;/option&gt;
        &lt;/options&gt;
    &lt;/event&gt;
&lt;/channel-type&gt;

So I think I'll go for a genric channel and the following event definition
&lt;channel-type id="trigger-channel"&gt;
    &lt;kind>trigger&lt;/kind&gt;
    &lt;label>Trigger Channel&lt;/label&gt;
    &lt;event&gt;
        &lt;options&gt;
            &lt;option value="PRESSED">pressed&lt;/option&gt;
            &lt;option value="RELEASED">released&lt;/option&gt;
            &lt;option value="SHORT_PRESSED">short pushed&lt;/option&gt;
            &lt;option value="LONG_PRESSED">long pushed&lt;/option&gt;
            &lt;option value="SENSOR_UPDATE">sensor data updated&lt;/option&gt;
        &lt;/options&gt;
    &lt;/event&gt;
&lt;/channel-type&gt;

**Comment by markus7017** [comment]
- BTN_ON/OFF  no additional trigger; input channel works as a trigger
- OUT_ON/OFF no additional trigger; output channel works as a trigger
- SENSORDATA no additional trigger; temp and humidity channels work as a trigger 
- I added a system.button, which receives the SHORT_PRESSED/LONG_PRESSED
- ROLLER_OPEN, ROLLER_CLOSE, ROLLER_STOP  will be mapped to the generic event channel

**Comment by markus7017** [comment]
implemented for Relay, Dimmer, Roller, Sensors; see PR

**Comment by markus7017** [comment]
included in #6592
