### ISSUE TITLE
[shelly] Remove usage of Apache Commons

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#6550]
The shelly binding makes some use of Apache Commons, which we are about to remove.
It would thus be nice, if the binding was refactored to use standard Java features instead.

**Comment by markus7017** [comment]
@kaikreuzer I already removed some of the stuff, mostly StringUtils some sometimes IOUtils are still used (maybe 20 times). I found https://eclipsesource.com/de/blogs/2013/11/06/get-rid-of-your-stringutils/

What is the recommendation to replace Apache Commons?

**Comment by kaikreuzer** [comment]
As mentioned in the description: "use standard Java features instead". There isn't any more specific answer I could give for such a generic question, sorry 😐.
