### ISSUE TITLE
[shelly][WIP] Refactor code to correctly use null annotations

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#6551]
The shelly binding code shows many SAT warnings due to  the lack of null annotations on class level - this needs some refactoring.

**Comment by markus7017** [comment]
What is a SAT warning?

**Comment by kaikreuzer** [comment]
"Static Code Analysis" - the report that falls out at the end of a build as `target/summary_report.html`.

**Comment by markus7017** [comment]
Almost all of those are related to @NonNullByDefault. As described I have a lot of small classes for the Gson mapping of the Shelly API. It seems that SAT doesn't support inner class. Where the IDE shows a warning because @NonNullByDefault is added to the inner class the SAT check will warn that those are missing even the outer class has it.

**Comment by kaikreuzer** [comment]
@cweitkamp Is it ok to leave the annotations away for such Gson DTOs?
If so, what's the best way to supress the warnings?

**Comment by cweitkamp** [comment]
Yes, I think it is okay to skip DTOs.

If DTOs are placed in a special folder we can exclude them for SAT checks on "NullAnnotationsCheck" in the [suppressions.xml](https://github.com/openhab/openhab2-addons/blob/746ecb7a8f856f8e21ca31b61b5edd4c6a65b5b4/tools/static-code-analysis/checkstyle/suppressions.xml#L6).

**Comment by markus7017** [comment]
is that something I could do? Is DTO a special folder?

I changed already ShellyProfile to @NonNullByDefault
but the Gson mappers are required to stay as @Nullable

From my point of view support for inner classes on the check would solve most of the warnings

**Comment by markus7017** [comment]
@cweitkamp What's the status here?
From my understanding Shelly*Gson.java could be added to suspressions.xml
or even better: the code check supports inner classes (the outer class has no @NonNullByDefault, which means the default for inner classes would be Nullable, but this is not handled properly by the style check)

**Comment by cweitkamp** [comment]
> is that something I could do?

Yes, you can do that. We have to amend `|NullAnnotationsCheck` to the list of checks:

```xml
    <suppress files=".+DTO\.java" checks="JavadocType|JavadocVariable|JavadocMethod|JavadocFilterCheck|NullAnnotationsCheck" />
```

> Is DTO a special folder?

No, it is not. It is a suffix for your class name. In your case you e.g. have to rename the classes `ShellyApiJson` -> `ShellyApiJsonDTO` and `ShellyCoapJSon` -> `ShellyCoapJsonDTO`.

Nullness validation of inner classes is a known problem. We keep track in https://github.com/openhab/static-code-analysis/issues/351.

**Comment by markus7017** [comment]
Does not work:

[WARNING] org.openhab.binding.shelly.internal.api.ShellyApiJsonDTO.java:[35]
Classes/Interfaces should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.shelly.internal.api.ShellyApiJsonDTO.java:[51]
Classes/Interfaces should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.shelly.internal.api.ShellyApiJsonDTO.java:[57]
Classes/Interfaces should be annotated with @NonNullByDefault
...

Do I need to do a rebase? (I always run a "mvn clean install")

**Comment by cweitkamp** [comment]
If you agree I would prefer the changes in `summary.xml` an a separate PR.

**Comment by markus7017** [comment]
sure, I'll remove that from #6592, open a new one and post the ID here (later today)

**Comment by markus7017** [comment]
PR #6728 was opened

**Comment by markus7017** [comment]
merged
