### ISSUE TITLE
[lgwebos] Connection issues after switching device on

### ISSUE THREAD

**Issue by dbghb** [openhab/openhab-addons#6556]
Sorry for the vague title. The issue that I am facing is that after switching on the TV the first request(s) sent to it does not get processed. After a while things the effect is gone.

I observe this behaviour for about one or two weeks now. Before it worked without any problems.

The log file attached should explain the problem a bit more.

## Expected Behavior
Rule switches on TV (does not care if it is already switched on)  and then selects an input channel.

## Current Behavior
Rule switches on TV (does not care if it is already switched on)  and then selects an input channel.

If TV was off before, selecting the input channel does not work. If TV was on for a while, it works.

[Comment: The effect is *not* related to the fact that the TV needs some time for "booting". The rule sends the input channel command twice, once immediately after switching the device on and then after 20 seconds again. This has alwas been necessary.]

## Possible Solution

The log file is just a grep over the openhab logs with "lgwebos" over the last couple of days. I hope it contains hints to the problem. If needed, I can do it with a higher log level. 

Please note: The log shows hints regarding pairing, but the device *is* paired. Maybe this is pointing to the actual problem.

[lgwebos.log](https://github.com/openhab/openhab2-addons/files/3939055/lgwebos.log)

## Steps to Reproduce (for Bugs)
See above.

## Context
./.

## Your Environment

* Version used: openHAB 2.5.0.M6 Milestone Build
* Environment name and version: openjdk version "1.8.0_222", OpenJDK 64-Bit Server VM 

* Operating System and version: Odroid N2,  Linux odroid 4.9.196-63 #1 SMP PREEMPT Thu Oct 17 00:44:03 -03 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by lolodomo** [comment]
After the TV is switched on, the binding needs a little time before being able to handle commands. During this short time, any command will be rejected.
There were changes regarding handling of the power channel and a new PR integrating the WOL feature will be merged probably soon.
I would suggest you trying again with all these changes.

**Comment by lolodomo** [comment]
Please try again with coming version 2.5.4, it includes the WOL feature inside the binding, and then close this issue if it is solved.

**Comment by lolodomo** [comment]
I close the issue as it is now old and we have no feedback.
