### ISSUE TITLE
[shelly] Convert channels into system types

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#6559]
For consistency the lowBatteryAlarm should be merged into the general alarm channel (triggering  a new BATTERY_LOW alarm condition).

**Comment by kaikreuzer** [comment]
It imho should not be replaced (the lowBattery system channel should be provided by all battery powered devices), but the alarm event channel can certainly be enhanced to also include low battery alarm events.

**Comment by markus7017** [comment]
ok, makes sense

**Comment by markus7017** [comment]
done

channel            new type
batteryLevel    system.battery-level
lowBattery       system.low-battery
wifiSignal         system.signal-strength

Channel signal was renamed to wifiSignal to prevent problem with existing JSONDB data
