### ISSUE TITLE
[yamahareceiver] Permanent warn messages "Could not perform feature detection for RX-V3900"

### ISSUE THREAD

**Issue by michel53** [openhab/openhab-addons#6561]
Since 2.5-M4, I get permanent warn messages in the log like
2019-11-02 11:22:41.873 [WARN ] [internal.protocol.xml.ZoneControlXML] - Could not perform feature detection for RX-V3900
on a Raspberry Pi with Openhabian, followed by a very long "java.net.SocketTimeoutException: connect timed out"
I own a RX-V671.

**Comment by emiksTT** [comment]
Look here
[https://github.com/openhab/openhab2-addons/issues/6328](url)

**Comment by zarusz** [comment]
Yes, It is going to get fixed along with #6328 once community verifies the fix.

**Comment by michel53** [comment]
Yes, with the fix, the error message is gone.
Thanks for the fix!
