### ISSUE TITLE
[onewire] Add temperature high/low channels for DS18B20 thermal sensor

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-addons#6563]
hello,

Maybe it's possible to add temperaturelow & temperaturehight chanells?
I have  DS18B20 termal sensor:
`/28.5EFA7A060000/address`
`/28.5EFA7A060000/alias`
`/28.5EFA7A060000/crc8`
`/28.5EFA7A060000/errata`
`/28.5EFA7A060000/family`
`/28.5EFA7A060000/fasttemp`
`/28.5EFA7A060000/id`
`/28.5EFA7A060000/latesttemp`
`/28.5EFA7A060000/locator`
`/28.5EFA7A060000/power`
`/28.5EFA7A060000/r_address`
`/28.5EFA7A060000/r_id`
`/28.5EFA7A060000/r_locator`
`/28.5EFA7A060000/scratchpad`
`/28.5EFA7A060000/temperature`
`/28.5EFA7A060000/temperature10`
`/28.5EFA7A060000/temperature11`
`/28.5EFA7A060000/temperature12`
`/28.5EFA7A060000/temperature9`
**`/28.5EFA7A060000/temphigh`**
**`/28.5EFA7A060000/templow`**
`/28.5EFA7A060000/tempres`
`/28.5EFA7A060000/type`

Then  sensor can store your high & low temperature. which is very useful.

Ed

**Comment by hmerk** [comment]
closed due to inactivity
