### ISSUE TITLE
[mqtt] Restore values from retained messages on system start

### ISSUE THREAD

**Issue by yozik04** [openhab/openhab-addons#6573]
Continuing after #5879

Currently if a value is retained in the broker openhab will not pick it up.

For example let's take **zigbee2mqtt** which publishes retained message `online` to `zigbee2mqtt/bridge/status`. Last will send retained `offline` to the same topic. After boot openhab always thinks that my item state is NULL. But the actual value at that moment is `online`.

## Your Environment
* Version used: Openhab 2.5 snapshot as of 11 Dec 2019.
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Any
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Linux, Docker

**Comment by hmerk** [comment]
closed due to inactivity
