### ISSUE TITLE
[mihome] Add support for Aquara Wall Switch SHORT_PRESSED event

### ISSUE THREAD

**Issue by Candy6132** [openhab/openhab-addons#6574]
Unlike the Aquara Wireless Switch, the Aquara Wall Switch seems to not work for the SHORT_PRESSED event.

The Wireless Switch gives the following log once I press it:
>  mihome:86sw1:158d000317723f:ch1 triggered SHORT_PRESSED

but the Wall Switch doesn't.

**Comment by hmerk** [comment]
closed due to inactivity
