### ISSUE TITLE
[hue] 2.5Milestone6 Hue dimmer switch and motion sensor is flooting log and uses 100% cpu

### ISSUE THREAD

**Issue by IngoBru** [openhab/openhab-addons#6578]
<a alt="bounty" href="https://www.bountysource.com/issues/85363614"><img src="https://api.bountysource.com/badge/issue?issue_id=85363614"></a>

## Expected behavior: 
Openhab system is running with 1-10 % cpu load and 2 GB memory consumption. Using of paper ui or Habmin is normal and system reaction is not delayed

## Current behavior:
After switching from openhab 2.5m5 to 2.5m6 hue dimmer switch and motion sensor causes flooting the log file with thousand of log entries for these devices. Also the memory consumption is going up to 5GB and the all CPU are running with 100%. This causes that the whole openhab system is slowing down and not useable any more. Reaction of inputs in UI is very delayed. It started directly after upgrading from Milestone 5 to 6 Version. It is still present in the RC1 Version.

## Possible Solution
Removing hue dimmer switch or motion sensor things solves the problem and gets the system stable again

## Steps to Reproduce (for Bugs)
1. install hue binding and include hue bridge
2. Include a hue motion sensor or dimmer switch thing with all their chanels via paper ui and simple linking.

## Context
This bug makes my system unstable and take 100% of all resources. When using frontail logviewer it is also possible that it crashes the browser

## Your Environment
* Version used: openHab 2.5 Milestone 6 from the offical Docker image
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Firefox 72.0b5
* Operating System and version: openmediavault 4.1.28 with docker CE 19.03.5

**Comment by cweitkamp** [comment]
Thanks for reporting. See my comment in https://github.com/openhab/openhab2-addons/issues/6577#issuecomment-565160525.

**Comment by kaikreuzer** [comment]
@cweitkamp As you have self-assigned you this issue, are you planning to have a fix today that should make it into the 2.5 release?

**Comment by cweitkamp** [comment]
Yes, I do. But I will not be able to get my computer handy before late afternoon.

**Comment by cweitkamp** [comment]
Fix is available: https://github.com/openhab/openhab2-addons/pull/6590
