### ISSUE TITLE
[digiplex] Error in Logic for "Area Ready"

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-addons#6600]
Hello,

Error in Logic. 

The channel Area Ready is not correct:
`	<channel-type id="ready">
		<item-type>Contact</item-type>
		<label>Area Ready</label>
		<description>Indicates if area is ready (no open zones)</description>
		<state readOnly="true">
			<options>
				<option value="CLOSED">Ready</option>
				<option value="OPEN">Not ready</option>
			</options>
		</state>
	</channel-type>`

Must be this way

`	<channel-type id="ready">
		<item-type>Contact</item-type>
		<label>Area Ready</label>
		<description>Indicates if area is ready (no open zones)</description>
		<state readOnly="true">
			<options>
				<option value="CLOSED">Not ready</option>
				<option value="OPEN">Ready</option>
			</options>
		</state>
	</channel-type>`

**Comment by rmichalak** [comment]
Confirmed in email communication. Logic is reversed in messages.
