### ISSUE TITLE
[homematic] Regensensor (HM-Sen-RD-O) offline after update to 2.5.0

### ISSUE THREAD

**Issue by BOFH90** [openhab/openhab-addons#6601]
Device is offline, even after restarting the CCU, openhab2 and removing + readding the thing again.
Device works just fine in the CCU2 (Firmware 2.49.18).

Error Message:
Status: OFFLINE - COMMUNICATION_ERROR -1 Failure (sending <?xml version="1.0" encoding="ISO-8859-1"?> <methodCall><methodName>getValue</methodName> <params><param><value>OEQXXXXXX:2</value></param><param><value>STATE</value></param></params></methodCall>)

The CCU got also errors if channel 2 is triggered:
```
Feb 24 19:10:26 ccu2 user.err rfd: Parameterset MASTER not found
Feb 24 19:10:26 ccu2 user.err rfd: HSSParameter::GetValue() id=WORKING failed getting physical value.
Feb 24 19:10:26 ccu2 user.err rfd: HSSParameter::GetValue() id=WORKING failed getting physical value.
```

**Comment by MHerbst** [comment]
Can you enable the trace mode, restart openhab and attach the log here.

**Comment by BOFH90** [comment]
sure, attached is my openhab.log. The device serial is: OEQ2596253.

[openhab.log](https://github.com/openhab/openhab2-addons/files/3969887/openhab.log)

**Comment by BOFH90** [comment]
I just noticed that the Rain-State is changing from DRY to RAIN and back even if the state of the Thing is offline.

**Comment by MHerbst** [comment]
Hmm, it is a bit strange. The binding tries to read data from channel 2 of the device but the sensor answers with an error. Therefore the thing shows the state OFFLINE. According to the Homematic documentation the device has got a channel with number 2 (RAINDETECTOR_HEAT). Therefore I don't understand why the device answers with an error state if the binding requests data from this channel.

This seems to be a problem of the device. I found an older post in the Homematic forum that describes the same problem with receiving data from channel 2. Maybe the binding should not set a device to OFFLINE if a request to one channel returns an error while other are working correctly. I will have a look into the code and try to understand how it is working.
