### ISSUE TITLE
[hueemulation] "Alexa switch the bathroom Light on" instead "Alexa switch the Light On"

### ISSUE THREAD

**Issue by goofy79** [openhab/openhab-addons#6603]
Hello,
with the Version 2.5.0-S1776-1 my Lights and Alexa work together like a charm and all was fine🥇.
The Update 2.5.0-S1778-1 brings, that all Lights powering on and off with the Alexa App works.
But if i say "Alexa switch the Light On" - anytime the Light in one room (bedroom) power on because this Light has the Name "Light" no mater in with room i tell Alexa to switch on.  Same with 2.5.0-1.
I think the Problem is : i tell Alexa "Alexa switch the Light On" but the Light in each room is called for example "Study Light", "Bedroom Light", and so on. 
If i call "Alexa switch the bedroom Light on" it works in the right room from any Alexa
If i call "Alexa switch the bathroom Light on" it works in the right room from any Alexa too

Before this Update / Patch it was, that if you are in one room and no Light has the Name "Light" all Lights switched on / off ... 

I think it is more intuitive to say "Alexa switch the Light On" if you enter the study as to say "Alexa switch the Study Light On", isn't it ?

**Comment by goofy79** [comment]
OK, i installed the Version 2.5.0-S1776-1, the same. maybe a few Versions earlier.

**Comment by goofy79** [comment]
ok, i find a workaroud by renaming the one lamp in the bedroom with the Name "light" (in the Alexa App) after this in each room where a alexa is present, i can say "alexa switch the light on" and the lamps in this room switch on.
therefor always the lamp in the bedroom with the name "light" goes on :)
I think thats ok for the moment. A few updates before it was like - if no lamp in the room with the name "light" - Alexa switch all devices on/off by the command "alexa switch the light on/off" and if a lamp has the name "Light" only this lamp in this room goes on.
At the moment the negativ aspect is, if no device/lamp has the name "Light" and you tell Alexa to turn on the light by telling her "Alexa switch the light on" all devices goes on in this room, the lights and all power plugs and scenes.

**Comment by hmerk** [comment]
closed due to inactivity
