### ISSUE TITLE
New binding skeleton didn't work

### ISSUE THREAD

**Issue by hyf980817** [openhab/openhab-addons#6609]
It seems that after this [commit](
https://github.com/ConfusedTA/openhab2-addons/commit/676d69a20962a3073684c1950b85690d94871535), the new binding skeleton didn't work.

## Steps to reproduce:
- git clone https://github.com/openhab/openhab2-addons.git
- cd bundles
- ./create_openhab_binding_skeleton.sh MyNewBinding foo foo
- cd org.openhab.binding.mynewbinding
- mvn clean install -DskipTests -DskipChecks
![image](https://user-images.githubusercontent.com/32120583/70960705-b3287380-20ba-11ea-8d93-8a092957dddb.png)

I think it was caused by the pom.xml
## Difference:
new pom.xml:
![image](https://user-images.githubusercontent.com/32120583/70960421-f0403600-20b9-11ea-9c56-ec03dd245ec2.png)

pom.xml created by sketeton:
![image](https://user-images.githubusercontent.com/32120583/70960527-43b28400-20ba-11ea-904c-4891af961a4f.png)

**Comment by cweitkamp** [comment]
Thanks for reporting this issue. Can you check if it is working after changing one of the following lines of the skeleton scripts to `"3.0.0-SNAPSHOT"`:

https://github.com/openhab/openhab2-addons/blob/86f06e85c99604c8b4ea7b13de84805cccb8b242/bundles/create_openhab_binding_skeleton.sh#L5

https://github.com/openhab/openhab2-addons/blob/86f06e85c99604c8b4ea7b13de84805cccb8b242/bundles/create_openhab_binding_skeleton.cmd#L13

**Comment by hyf980817** [comment]
> Thanks for reporting this issue. Can you check if it is working after changing one of the following lines of the skeleton scripts to `"3.0.0-SNAPSHOT"`:
> 
> https://github.com/openhab/openhab2-addons/blob/86f06e85c99604c8b4ea7b13de84805cccb8b242/bundles/create_openhab_binding_skeleton.sh#L5
> 
> https://github.com/openhab/openhab2-addons/blob/86f06e85c99604c8b4ea7b13de84805cccb8b242/bundles/create_openhab_binding_skeleton.cmd#L13

Thanks, I changed and now it works.

**Comment by cweitkamp** [comment]
May I ask you to contribute a fix for it?
