### ISSUE TITLE
[innogysmarthome] Wrong Dimmer values

### ISSUE THREAD

**Issue by RalphSester** [openhab/openhab-addons#6610]
when you Change the value of a dimmer, (in this case from 0 to 35) the binding will set the value from 0 to 100 and then from 100 to 35.

## Expected Behavior
When i Change the dimmer value from 0 to 35 it should not get a value of 100 before it gets 35.

## Current Behavior
At this moment the openhab-item changes from 0 to 100 and then from 100 to 35.
In the log of the innogy-api comes only the change from 0 to 35 - so i think it's a binding problem.

here is the log:

```
12:01:44.546 [DEBUG] [ogysmarthome.internal.InnogyWebSocket] - innogy WebSocket onMessage() - {"sequenceNumber":87746,"type":"StateChanged","desc":"/desc/device/ISD2.RWE/1.0/capability/DimmerActuator/event/StateChanged","namespace":"CosipDevices.RWE","timestamp":"2019-12-13T11:01:44.5056720Z","source":"/capability/53ac14a9012147b6a2ec6b2d0568a11c","properties":{"dimLevel":35}}
12:01:44.548 [DEBUG] [.internal.handler.InnogyBridgeHandler] - Event no 87746 found. Type: StateChanged
12:01:44.549 [DEBUG] [.internal.handler.InnogyDeviceHandler] - onDeviceStateChanged called with device Licht Ralph/fa1cda6804af4d21aacf0573321d3d4b
12:01:44.551 [DEBUG] [.internal.handler.InnogyDeviceHandler] - ->capability:53ac14a9012147b6a2ec6b2d0568a11c (DimmerActuator/Dimmer Actuator)
12:01:44.552 [DEBUG] [.internal.handler.InnogyDeviceHandler] - Dimlevel state 35
12:01:44.553 [DEBUG] [.internal.handler.InnogyDeviceHandler] - ->capability:8642e133911e4cbb9e8ed6713ff3c1c4 (PushButtonSensor/ISD2)
12:01:44.554 [INFO ] [smarthome.event.ItemStateChangedEvent] - DS_AZ_Ralph changed from 0 to 100
12:01:44.562 [DEBUG] [.internal.handler.InnogyDeviceHandler] - Pushbutton index null count 58
12:01:44.562 [INFO ] [home.event.GroupItemStateChangedEvent] - GR_Licht_AZ changed from OFF to ON through DS_AZ_Ralph
12:01:44.563 [DEBUG] [.internal.handler.InnogyDeviceHandler] - State for PushButtonSensor is STILL NULL!! cstate-id: 8642e133911e4cbb9e8ed6713ff3c1c4, c-id: 8642e133911e4cbb9e8ed6713ff3c1c4
12:01:44.564 [INFO ] [smarthome.event.ItemStateChangedEvent] - DS_AZ_Ralph changed from 100 to 35
12:01:44.565 [INFO ] [home.event.GroupItemStateChangedEvent] - GR_Licht_OG changed from 0 to 1 through GR_Licht_AZ
12:01:44.566 [INFO ] [home.event.GroupItemStateChangedEvent] - GR_Licht changed from 0 to 1 through GR_Licht_OG

```
## Possible Solution
Change the handling in the binding.

## Steps to Reproduce (for Bugs)
1. Change a Dimmer-value to any value (not 100 an not 0)
2. See the OpenHAB-Log - you see that the openhab-item gets 100 or 0 before it gets the correct value.

## Context
@Hilbrand should take a look at this issue.

## Your Environment
OpenHAB 2.4 on Windows Server 2016.

**Comment by Hilbrand** [comment]
I've created a new jar that should fix this issue:
https://github.com/Hilbrand/openhab-addons/releases/tag/innogy

**Comment by RalphSester** [comment]
Hi Hilbrand,
your update of the binding can not start in OH 2.4.

```
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.innogysmarthome [262]
  Unresolved requirement: Import-Package: com.google.gson; version="[2.8.0,3.0.0)"
```

Ralph

**Comment by Hilbrand** [comment]
Hmm apparently the build conflicted with me having eclipse open. I've added new jar version:  **(23/12/2019 19:30)**

**Comment by RalphSester** [comment]
Yes, now it works.
And it seems, that the bug was fixed!
Good Job! - Merry Christmas!
Ralph
