### ISSUE TITLE
[mail] Binding not configurable when using German in Paper UI

### ISSUE THREAD

**Issue by martin5233** [openhab/openhab-addons#6612]
I just upgraded from 2.4 to 2.5 and had to replace the mail action available in 2.4 by installing the new mail binding. I tried to configure the SMTP server via a German PaperUI, which is impossible, because the listing of available security methods (should display plain, SSL and TLS) is empty.

This may be a translation issue, e.g. that only the translations are missing and there's no fallback to the English texts.

One additional information: I configured the SMTP server in a "things" file instead, which works. When I view the configured "thing" in the PaperUI, the correct strings for the security method are shown. Now after viewing the configured SMTP server, I can even configure a new SMTP server inside PaperUI, so it looks like the problem only surfaces on first use.

**Comment by hmerk** [comment]
closed due to inactivity
