### ISSUE TITLE
mqtt:broker trigger stops working after "Payload Condition" was changed to a empty condition.

### ISSUE THREAD

**Issue by MarkusKress** [openhab/openhab-addons#6619]
I'm new with OpenHAB and installed 2.5. I've added a connection to a MQTT broker and adding a Channel (using for tests # as a topic). This works fine and event os triggered after received a MQTT Message (Broker is Mosquitto). But after I changed the "Payload Condition" and revert it back to a empty "Payload Condition", it's not triggered anymore (no new entries in events.log). 
The MQTT Broker was online in OpenHAB during the events were not triggered. Updating the MQTT Broker or stop and restarting OpenHAB does not solve the problem.
Only deleting the channel and add it again solved the problem.

**Comment by MarkusKress** [comment]
I found out, same issue is also valid for inital configured non empty Payload Conditions. 
Example: I configure a channel with payload condition TEMP. The trigger is fired correcly. Than I changed the payload condition to TEM (without P). It's not triggered anymore. After changing back to TEMP, it's triggered again.

**Comment by hmerk** [comment]
closed due to inactivity
