### ISSUE TITLE
[mqtt] Chained Incoming Value Transformation not working correct

### ISSUE THREAD

**Issue by tarabas73** [openhab/openhab-addons#6622]
My Input over MQTT looks like that:
{“lux”:306} or {“tem”:11.5}

## Expected Behavior
using a chained transformationPattern=“REGEX:(.*lux.*)∩JSONPATH:$.lux” ] within a number channel it should filter the input and send out e.g. 306 as a number

## Current Behavior
all inputs are skipped with followong log entry
=> Transformation ‘{“lux”:306}’ returned null on ‘REGEX’, discarding message

It's working as soon as i changed the channel to a string channel but not as number

## Possible Solution
chained transformationshould work also with number channels if the last transformation ends up with a number..

## Steps to Reproduce (for Bugs)
add a number channel to a mqtt thing and add the chained transformation

## Context
I want to get rid of warning messages with not used mqtt inputs

## Your Environment
PI3B+, OH2.50
Items & Things in files

Binding
266 │ Active │ 81 │ 2.5.0 │ openHAB Add-ons :: Bundles :: MQTT Things and Channels

**Comment by J-N-K** [comment]
Your regex is incorrect. Try `REGEX:(.*lux.*)∩JSONPATH:$.lux`.

**Comment by tarabas73** [comment]
Nearly sure that’s exactly what I started with. It‘s working as string and in the rules, but I‘ll check again!

**Comment by J-N-K** [comment]
`.` matches a dot. It only works as „catch everything“ if followed by a quantifier like `+`, `*` or something else. Since your string does not contain`.lux.` returning null is correct. If it matches if you change to a string-item then that is the bug.

**Comment by tarabas73** [comment]
damn,sorry

copy the original string
 transformationPattern="REGEX:(.*lux.*)∩JSONPATH:$.lux"

**Comment by J-N-K** [comment]
It is not working with that string. The regex is wrong. If you use my regex above it works. You can check with each regex tester.

**Comment by tarabas73** [comment]
yes, if I copy the string it is modified :-(

Here as a Picture
![image](https://user-images.githubusercontent.com/34721650/71289920-bd729800-236e-11ea-8a00-e99f89e85f35.png)

**Comment by tarabas73** [comment]
I didn't realize the effect. Nevertheless I'll check again at the Moment with stop openhab, clear Cache and reboot and see whats happen

It's a 1:1 copy of your string. At the Moment I still got warnings in the log so clear Cache and reboot.

**Comment by tarabas73** [comment]
okay, still the same:

![image](https://user-images.githubusercontent.com/34721650/71290864-3377fe80-2371-11ea-86de-ebfee1728b71.png)

"REGEX:(.\*tem.\*)∩JSONPATH:$.tem"

20-Dec-2019 21:38:15.317 [DEBUG] [org.openhab.binding.mqtt.generic.ChannelState     ] - Transformation '{"tem":10}' returned null on 'REGEX', discarding message

Message: {"tem":10}

**Comment by tarabas73** [comment]
SUCCESS

Sorry, seems I was to quick, sysrem wasn't up completely.

Now it works, only the Messages without tem in the message were discarded and thats what I want!

Sorry for the circumstances and many thanks for the help!

regards
Michael
