### ISSUE TITLE
Problem with ne MY Posistion at the TaHoma-Binding

### ISSUE THREAD

**Issue by luismauriz1** [openhab/openhab-addons#6625]
Hello Guys, I have a Problem with the Tahoma Binding at OH 2.5. Since the recent changes to the API 2 at Tahoma, the MY Position at my Rollershutters isn't working anymore. At the API V1 I allways used the command 
`sendCommand(Item, STOP)` And that worked fine.
But at the new System with the new API and OH 2.5, the Command isnt`t working anymore.
Is there a different command to come to the MY Position?
Thanks for your help!

**Comment by hmerk** [comment]
closed due to inactivity
