### ISSUE TITLE
[tesla] models thing is showing  "A Tesla Model X Vehicle"

### ISSUE THREAD

**Issue by furtber** [openhab/openhab-addons#6637]
Actually it seems to be a copy/paste error in:
bundles/org.openhab.binding.tesla/src/main/resources/ESH-INF/thing/modelx.xml

Line 7:
	<thing-type id="models">

Should read:
	<thing-type id="modelx">

Otherwise there would be 2 models things - and actually the wrong one is picked up ...

**Comment by kaikreuzer** [comment]
Fixed by https://github.com/openhab/openhab-addons/pull/6638.
