### ISSUE TITLE
[homekit] Learn from open source HomeKitADK

### ISSUE THREAD

**Issue by grouchal** [openhab/openhab-addons#6639]
Now that Apple have released the Open Source `HomeKitADK`.

https://github.com/apple/HomeKitADK

Perhaps the add-on can profit from this in terms of stability and scalability.

See Also:

https://developer.apple.com/homekit/whats-new/

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by kgoderis** [comment]
@grouchal @kaikreuzer FYI, I have an "(r)evolution" of the homekit binding in the making that will highly integrate openHAB and HAP, leveraging all the good stuff we developed over the years, and doing away with the current interfacing between openHAB and the external library. So far, it looks quite nice with Things automatically exposed to HAP clients and so forth. I think this open source lib, albeit written in C, will help understand how HAP clients behave with their server counterparts
