### ISSUE TITLE
[astro] Events don't respect 'earliest' and 'latest' channel properties

### ISSUE THREAD

**Issue by leifbladt** [openhab/openhab-addons#6653]
I upgraded from 2.4.0 to 2.5.0 and started to use the astro binding. I'm using 
* `astro:sun:local:civilDawn#start` with `earliest=06:30` and `latest=07:30` and
* `astro:sun:local:civilDusk#end` with `earliest=17:30` and `latest=20:30`.

The linked items show, that for `civilDawn` the `latest` property is used and for `civilDusk` the `earliest` property is used (at least on 2019-12-21).

## Expected Behavior
The events (`astro:sun:local:civilDawn#event START` and `astro:sun:local:civilDusk#event END`) should be fired at the displayed time, according to the linked items (and the configuration).

## Current Behavior
However, the events do not consider the additional channel properties. Here are the relevant log entries from last night, that show scheduled events.

```
2019-12-21 00:00:30.412 [DEBUG] [o.internal.handler.AstroThingHandler] - Scheduled Event job astro:sun:local/civilDawn#event/START in 27569589ms (at 2019-12-21T07:40:00)
2019-12-21 00:00:30.413 [DEBUG] [o.internal.handler.AstroThingHandler] - Scheduled Event job astro:sun:local/civilDawn#event/END in 29729587ms (at 2019-12-21T08:16:00)
[...]
2019-12-21 00:00:30.419 [DEBUG] [o.internal.handler.AstroThingHandler] - Scheduled Event job astro:sun:local/civilDusk#event/START in 59849581ms (at 2019-12-21T16:38:00)
2019-12-21 00:00:30.420 [DEBUG] [o.internal.handler.AstroThingHandler] - Scheduled Event job astro:sun:local/civilDusk#event/END in 62069580ms (at 2019-12-21T17:15:00)
```

## Context
* I did serveral restarts, without a change in this behavior.
* Geolocation and timezone (Europe/Berlin) is set
* The astro binding related configuration was made through PaperUI, except the rules of course.

## Your Environment
* Version used: openhab2-2.5.0-1 (APT installation)
* Operating System: Ubuntu 18.04.3 LTS

**Comment by leifbladt** [comment]
Seems different, but maybe it's related to #6584 .

**Comment by Rossko57** [comment]
The given earliest/latest Thing settings appear to relate to datetime channels, like `civilDawn#start`.
Event trigger channels like `civilDawn#event` have their earliest/latest settings specified separately in rangeEvents.

**Comment by leifbladt** [comment]
Thanks for your hint, now I can see the mentioned option in PaperUI. I'll give it a try tonight.

**Comment by leifbladt** [comment]
@Rossko57 It works exactly as you wrote, I monitored it the last few days. Thanks again, for pointing me to the right direction. So I will close this issue, since it's not a bug. 

But maybe the documentation could be enhanced, since the range event configuration is only mentioned in the example chapter.
