### ISSUE TITLE
[tesla] No way to escape "inactive" state

### ISSUE THREAD

**Issue by cguedel** [openhab/openhab-addons#6654]
Whenever the vehicle is not moving and not charging, the binding tries to skip updates for a while (I think 20 minutes), in order to allow the vehicle to go to sleep. Once it detects the car in sleep state, it only queries the general vehicle state which does not allow the vehicle to update.

So far so good. Except for one edge-case. You park the car, after a few minutes the binding stops polling to allow the car to sleep. In the meanwhile, you enter the car again and drive off. The binding will not notice until after the whole 20 minutes have elapsed.

In 2.4 binding, I have had added a channel "forceRefresh" which could be used to force query the vehicle once your smartphone detected it has been paired with the vehicle (using a Tasker request to openhab backend). This channel is now gone.

## Expected Behavior

Channel "forceRefresh" should be available for the use-case described above.

## Current Behavior

Channel is missing

## Possible Solution

I could add it again, however I'm unsure about the removal. Was there a good reason to do so or just overlooked? What do I need to do to make it end up in a 2.5.x release? Which branch to target?

## Your Environment

* Version used: 2.5.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows

**Comment by cguedel** [comment]
Maybe we could also set inactive to false, whenever wake_up is invoked?

**Comment by kaikreuzer** [comment]
> Maybe we could also set inactive to false, whenever wake_up is invoked?

Or at least when the wake up has been successfully performed. Isn't the inactive state automatically changed in that case?

**Comment by jfrank1845** [comment]
Just a thought - isn't the vehicle_data call safe to do without worries of waking the car so shouldn't we just use the vehicle state from that and use the sleep status from that to determine if we do the other polls or not?

**Comment by cguedel** [comment]
The problem with that approach is that as long as you pull from any other endpoint that vehicle_data, the vehicle will never go to sleep. So even though you can monitor the sleep state using vehicle_data, you need to stop pulling the other endpoints.

With PR #6677 merged, this should now work also in case you want to have a rule that forces a refresh once your phone signals your openhab instance that it is connected to the car.

**Comment by jfrank1845** [comment]
I guess my point was why would you poll the other endpoints if the vehicle was asleep ?
