### ISSUE TITLE
[homematic] Add support for WEEK_PROGRAM_POINTER

### ISSUE THREAD

**Issue by RolandRosenfeld** [openhab/openhab-addons#6655]
I use a Homematic CCU2 with several HM-CC-RT-DN (radiator valves including thermostat) as well as with virtual device groups containing one or two HM-CC-RT-DN and a HM-TC-IT-WM-W-EU (wall thermostat).

HM-CC-RT-DN can be switched between three different week programs, for example one for usual days (doesn't heat Mo-Fr 9-17) and a second program for holidays (heats every day 8-22 or the like).

Now I need a mechanism to switch between the different week programs from OpenHAB.  Sadly this isn't supported by the homematic binding.

After some research I found out, that you can switch between the week programs using an additional XMLRPC service.

You have to send a `call('getParamset', serial, 'MASTER')` to read the current WEEK_PROGRAM_POINTER or `call('putParamset', serial, 'MASTER', {'WEEK_PROGRAM_POINTER': programno})`

(no idea about the exact syntax of XMLRPC in Java, I coded this in Perl).

You have to access http://ccu:2001/ as URL for regular devices and http://ccu:9292/groups for virtual devices groups (INTxxxxxxx).

Please note, that you have to use program number 0, 1, 2 here, while CCU web UI uses the numbers 1, 2, 3.

You find my complete Perl script and a (German) description of this on my web page https://www.spinnaker.de/openhab/hm-weekprogram/

It would be great to be able to handle this using the homematic binding internally instead of using the exec1 binding for this.

Greetings
Roland

**Comment by MHerbst** [comment]
> HM-CC-RT-DN can be switched between three different week programs, for example one for usual days (doesn't heat Mo-Fr 9-17) and a second program for holidays (heats every day 8-22 or the like).

Are you sure that it is provided by the HM-CC-RT-DN? In my Homematic installation the HM-TC-IT-WM-W-EU provides this option :-).

> Now I need a mechanism to switch between the different week programs from OpenHAB. Sadly this isn't supported by the homematic binding.

I had the same problem and solved it with system programs on the CCU (one program for each program) and I start these programs from openHAB.

It is also quite interesting that option is not documented in the official data points documentation from eq3. Normally the binding provides all data points as channels that are retrieved by a getParamset call from the CCU. And on my Raspberrymatic based CCU this data point is missing.
Interestingly your perl script can read this value. Will have a close look at it.

**Comment by RolandRosenfeld** [comment]
You are right, please replace HM-CC-RT-DN by HM-TC-IT-WM-W-EU in my initial post.
Since I always use the virtual groups for switching, I forgot that the wall thermostat is the leader here.

**Comment by hmerk** [comment]
closed due to inactivity

**Comment by RolandRosenfeld** [comment]
As far as I can see support for WEEK_PROGRAM_POINTER was not yet added to the homematic binding.
So I think we shouldn't just close this ticket but someone with more knowledge should implement this...
Please reopen the ticket.

**Comment by hmerk** [comment]
@RolandRosenfeld There was no acticity for 1 1/2 years, so it is unlikely somebody will step up to implement this.
But feel free to contribute and provide a PR.
