### ISSUE TITLE
[Request] GPIO Binding for openhab2, supporting things

### ISSUE THREAD

**Issue by bks29b** [openhab/openhab-addons#6665]
Hey folks,

I think it would be very useful to many of us to have the GPIO binding as a openhab2 version, supporting things in paperUI. I am meanwhile very used to things and the concept behind it. Every time i look at paper UI i am missing the GPIO-connected Things of my smart home system.

The configuration of the GPIO binding is quite clear and straightforward. So I think it shouldn't be a big problem to migrate it to openhab2. 
The problem is: I can support the development and test it, but I am not able to do this for myself.

Who can help?

**Comment by Hilbrand** [comment]
There is a pending pr: #1334

**Comment by Hilbrand** [comment]
Duplicated by #1707
