### ISSUE TITLE
[network] Add channel for IP address (String)

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#6666]
I use this binding to measure latency and availability of my devices. 
I sometimes want to know the IP address of each devices while using sitemaps. 
I think it would be a good idea to have this information displayed as a channel. 

So the channels would look like this..

Channel Type ID | Item Type | Description
-- | -- | --
online | Switch | This channel indicates whether a device is online
lastseen | DateTime | The last seen date/time of the device in question. May be 1. Jan 1970 if no time is known
latency | Number:Time | This channel indicates the ping latency. May be 0 if no time is known
ip_address | String | The IP address of the device in question

Thanks!

**Comment by bortell** [comment]
I have added the ip address as a channel but the network bundle uses a project from fr.bmartel as discussed here to do a speed test.

https://community.openhab.org/t/missing-dependency-running-the-demo-app-in-eclipse/95463/33?u=gadstein

Removing the dependency and code that references it I have been able to add the ip as a channel so the question is do i need to find a replacement speed test or should it be removed from the binding.

**Comment by hmerk** [comment]
closed due to inactivity
