### ISSUE TITLE
[samsungtv] "arping: invalid option -- 'r'" warnings on CentOS 8

### ISSUE THREAD

**Issue by fapgomes** [openhab/openhab-addons#6682]
Hi,

 With centos 8 and openhab 2.5.0, the samsungtv binding have a problem with arp utility:

2019-12-24 22:55:30.814 [WARN ] [.samsungtv.internal.WakeOnLanUtility] - Cannot get MAC addres of host 192.168.1.72: arping: invalid option -- 'r'

The centos8 arping doesn't have -r option neither the man page in https://linux.die.net/man/8/arping
The -r is for what? Can be removed?

Best Regards,
Fernando Gomes

**Comment by lolodomo** [comment]
PR #7436 improved the WOL feature. For Linux OS, arp command is used if available. If not, arping command is used.
Can you check if your issue is solved with the current version (in branch 2.5.x) ?

**Comment by hmerk** [comment]
closed due to inactivity
