### ISSUE TITLE
[harmonyhub] Communication stopped working

### ISSUE THREAD

**Issue by pyro2k9** [openhab/openhab-addons#6683]
## Expected Behavior
Connection the the harmony hub should be stable all time.

## Current Behavior
The connection suddenly changed to OFFLINE without any reason. 

I can deliver following logs of the openhab.log file:
```
50.813 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not connect: null
	Line 11572: 2019-12-22 00:18:50.813 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not connect: null
**Comment: Some devices changed to OFFLINE - left out** 
	Line 11577: 2019-12-22 00:20:05.815 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: null to OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout
	Line 11577: 2019-12-22 00:20:05.815 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: null to OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout
	Line 11596: 2019-12-22 00:21:05.919 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout to ONLINE
	Line 11596: 2019-12-22 00:21:05.919 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout to ONLINE
```

A few hourrs later the communication error changes to:
`
Line 15530: 2019-12-22 07:28:41.348 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not connect: Disconnected
`

A restart of the binding fixed the situation.

## Steps to Reproduce (for Bugs)
I can not reproduce the bug - will change the log to TRACE. When it happens again, I can post new logged informations here.

## Your Environment

* Version used: 
```Karaf
  Karaf version               4.2.7
  Karaf home                  /XXXX/XXXX/openHAB/runtime
  Karaf base                  /XXXX/XXXX/openHAB/userdata
  OSGi Framework              org.eclipse.osgi-3.12.100.v20180210-1608

JVM
  Java Virtual Machine        Java HotSpot(TM) 64-Bit Server VM version 25.231-b11
  Version                     1.8.0_231
  Vendor                      Oracle Corporation
  Pid                         20064
  Uptime                      6 days 18 hours
  Process CPU time            1 hour 40 minutes
  Process CPU load            0.01
  System CPU load             0.02
  Open file descriptors       256
  Max file descriptors        4,096
  Total compile time          6 minutes
Threads
  Live threads                157
  Daemon threads              83
  Peak                        203
  Total started               128463
Memory
  Current heap size           117,495 kbytes
  Maximum heap size           2,510,848 kbytes
  Committed heap size         185,344 kbytes
  Pending objects             0
  Garbage collector           Name = 'G1 Young Generation', Collections = 7098, Time = 2 minutes
  Garbage collector           Name = 'G1 Old Generation', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      19,481
  Total classes loaded        55,498
  Total classes unloaded      36,017
Operating system
  Name                        Linux version 4.4.59+
  Architecture                amd64
  Processors                  2
```

* Synology DS218+, DSM 6.2.2-24922 Update 4

```
openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.5

Repository        Version
----------------------------------------
openhab-distro  : 2.5.0
openhab-core    : 2.5.0
openhab1-addons : 1.14.0
openhab2-addons : 2.5.0
karaf           : 4.2.7
```

* openHAB Installed by official .spk
* Harmony Hub Firmware is 4.15.250, XMPP is enabled. The upgrade is - lets say - far ago...

If any more informatin needed, please inform me. Thanks.

**Comment by digitaldan** [comment]
>Connection the the harmony hub should be stable all time.

I'm not sure thats 100% possible given we are at the mercy of networks and other environmental issues :-) 

`Line 11577: 2019-12-22 00:20:05.815 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: null to OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout`

The error shows our TCP connection (websockets in 2.5, xmpp is no longer used )  timed out which indicates we are not able to read any more from the connection, thats typically a network issue, although if the host system was staved for resources, i guess that could cause that as well, but 90% of the time its network/wifi.

`Line 11596: 2019-12-22 00:21:05.919 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout to ONLINE`

Your log also shows it connects again 60 seconds later, which is how long the binding waits to retry a connection.  It looks like that was successful. And you were online for another 7 hours.  So this looks normal and the binding is behaving as it should.

`Line 15530: 2019-12-22 07:28:41.348 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not connect: Disconnected`

When the binding went offline again, how long did you wait to restart the binding?  I would think you should have seen another message 60 seconds afterwords when the binding attempted to connect again, although you may need to turn up debug logging (`log:set DEBUG org.openhab.binding.harmonyhub`)  and look at the openhab.log to see failed attempts.  If the connection did not come back at all, but a restart did fix it, then i would need debug logging to see why reconnect attempts failed.

**Comment by digitaldan** [comment]
actually i misread the stack a bit, same conclusions, but a little more detail:

`Line 11572: 2019-12-22 00:18:50.813 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not connect: null`

Binding was unexpectedly disconnected from hub

`Line 11577: 2019-12-22 00:20:05.815 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: null to OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout`

First reconnect try fails, SocketTimeoutException means we could not establish a TCP connection to the HUB.  This could mean network or wifi issues, or power issues, like the HUB updating and/or rebooting, so it's not available to connect to. This timestamp is 1min 15 seconds later, which is probably our 60 second retry time plus 15 seconds waiting for the socket to connect (or not)

`Line 11596: 2019-12-22 00:21:05.919 [hingStatusInfoChangedEvent] - 'harmonyhub:hub:HarmonyHub' changed from OFFLINE (COMMUNICATION_ERROR): Could not connect: java.net.SocketTimeoutException: Connect Timeout to ONLINE`

Next retry after 60 seconds works

**Comment by pyro2k9** [comment]
I don't think it is a network issue because I checked the connect/disconnect event history of my (unifi) wifi equipment and even if - the binding should reconnect correctly.

> When the binding went offline again, how long did you wait to restart the binding? I would think you should have seen another message 60 seconds afterwords when the binding attempted to connect again, although you may need to turn up debug logging (log:set DEBUG org.openhab.binding.harmonyhub) and look at the openhab.log to see failed attempts. If the connection did not come back at all, but a restart did fix it, then i would need debug logging to see why reconnect attempts failed.

Yes, I will provide more informations about this issue if this happens again. Since now, it didn't happen again.

I will close this issue since we can't solve the problem for now.
