### ISSUE TITLE
[mqtt] Rollershutter/Dimmer: Different MQTT command topic to STOP motor

### ISSUE THREAD

**Issue by HGBAXXTER** [openhab/openhab-addons#6685]
For the so far already great OH 2.5 MQTT binding I would appreciate the following functionality: 

Currently, the rollershutter channel allows the following commands: 

    on: An optional string (like "Open") that is recognized as UP state.
    off: An optional string (like "Close") that is recognized as DOWN state.
    stop: An optional string (like "Stop") that is recognized as STOP state.

Nevertheless, for all these commands the same MQTT Command Topic is used with different values. However, the rollershutter implementation in the popular Tasmota firmware requires a different approach. The values for the shutter position are commanded via 

`cmnd/tasmota-XXYYZZ/SHUTTERPOSITION <value>`

The Stop command cannot be sent using the value <stop> but requires a different command topic:

`cmnd/tasmota-XXYYZZ/SHUTTERSTOP`

It would be great for the sake of improved compatibility with Tasmota to allow the use of a dedicated STOP command topic in this binding.

**Comment by ccutrer** [comment]
+1. while I've made this work on my own Homie device by supporting UP/DOWN/STOP on my position-percent channel, it's technically violating the Homie spec. I have a separate control enum channel that accepts up/down/stop. At the least manual configuration would be nice. I don't see how OpenHAB could automatically discover that a control property should be associated with a particular other position property.

**Comment by Rossko57** [comment]
I think MQTT handling of Rollershutter in general may benefit from a review.

At the moment, "mini-transforms" on= and off= are applied to OH commands, with a default of 0 and 100.
The effect of that is that command UP and command 0 cannot be distinguished by the time you apply an 'out' transform.  In most cases it doesn't matter,in some it will and there is no way around.

I haven't tried this, but a way to use current structure to send commands to different topics might be to use multiple channels, each dealing with a subset of commands and ignoring others.  Using a REGEX selection technique, as commonly used for selecting from variable input payloads?
