### ISSUE TITLE
[hue] Wrong Port used in Binding

### ISSUE THREAD

**Issue by NightDragon1** [openhab/openhab-addons#6686]
## Expected Behavior
The IP Port used at a HUE Bridge Emulation Thing should be permanent as entered in the settings and not using the Openhab port.

## Current Behavior
The Port number in the hue Bridge Thing gets reset to the openhab port instead of using the configured one. Changing it back to the deconz port is not permanent... a simple device discovery  leads the thing to be reset back to the openhab port again.

## Steps to Reproduce (for Bugs)
precondtion:
using paperUI
openhab at e.g. port 8090
deconz at e.g. 8080.
1. Create a hue bridge thing and set the port to 8080
2. start a discovery in paperUI via the hue binding.
3. Bug: hue thing is reset to 8090
4. changing back to 8080 in the things settings
5. thing connects properly again to deconz... until a scan is triggered.

## Your Environment
Dresden Elektronik deconz zigbee HAT
raspbian running openhab 2.5

**Comment by lolodomo** [comment]
This could be because one of the two discovery service is not setting the "port" property in the discovery result. Considering the code (the class BridgeJsonParameters), I guess that this information is not returned ! I will check that.

https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueBridgeNupnpDiscovery.java#L107

But just by reading the code, I don't understand why the port will be set to 8090 in that case. I will imagine port 80 to be considered in that case.

So your problem is more probably in the UPnP discovery service which provides a wrong port, 8090 rather than 8080. Are you sure that the bug is not on deconz side ?
This could be checked with an UPnP tool like "Device Spy" (this tool has a new name I think).

**Comment by lolodomo** [comment]
I just built a special version with few additional DEBUG logs:
[org.openhab.binding.hue-2.5.5-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/4531374/org.openhab.binding.hue-2.5.5-SNAPSHOT.zip)

Affter deploying this new version, enable the DEBUG logs and then start a new search in Paper UI: You should get these kinds of logs:
```
22:26:09.872 [DEBUG] [scovery.HueBridgeDiscoveryParticipant] - UPnP discovery base URL = http://192.168.x.xxx:80/
22:26:10.247 [DEBUG] [nal.discovery.HueBridgeNupnpDiscovery] - NUPnP discovery DISCOVERY_URL => json = [{"id":"yyyyyyyyyyyyyy","internalipaddress":"192.168.x.xxx"}]

22:26:10.265 [DEBUG] [nal.discovery.HueBridgeNupnpDiscovery] - NUPnP discovery description URL = http://192.168.x.xxx/description.xml
22:26:10.285 [DEBUG] [nal.discovery.HueBridgeNupnpDiscovery] - NUPnP discovery description = <?xml version="1.0" encoding="UTF-8" ?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://192.168.x.xxx:80/</URLBase>
<device>
<deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
<friendlyName>Philips hue (192.168.x.xxx)</friendlyName>
<manufacturer>Royal Philips Electronics</manufacturer>
<manufacturerURL>http://www.philips.com</manufacturerURL>
<modelDescription>Philips hue Personal Wireless Lighting</modelDescription>
<modelName>Philips hue bridge 2012</modelName>
<modelNumber>xxxxxxxxx</modelNumber>
<modelURL>http://www.meethue.com</modelURL>
<serialNumber>xxxxxxx</serialNumber>
<UDN>uuid:xxxxxxxxx</UDN>
<presentationURL>index.html</presentationURL>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<height>48</height>
<width>48</width>
<depth>24</depth>
<url>hue_logo_0.png</url>
</icon>
</iconList>
</device>
</root>
```

To deploy this version:

1. download and unzip the file on your server, for example in /home/pi/hue.jar
2. Identify your hue bundle number with this console command: bundle:list -s | grep hue
3. Update the bundle with this console command: bundle:update XXX file:///home/pi/hue.jar

**Comment by lolodomo** [comment]
The NUPnP discovery service should probably get the port from the XML description. This XML description is in fact the UPnP description of the hue bridge.
Even with a hue bridge, the UPnP discovery service is setting the port to 80 in the discovery result, while the NUPnP discovery service is not setting it.
This is not a problem in this case as 80 will be considered if not set.
But in my opinion, there is a little bug here.

**Comment by lolodomo** [comment]
I checked my Hue app if I am able to change the bridge port but this is not a parameter. It looks like a Hue bridge is always on port 80. So, that is difficult to investigate more for me, even if I am sure there is a bug in the NUpnp discovery service (port property not set).

**Comment by hmerk** [comment]
closed due to inactivity
