### ISSUE TITLE
[Telegram binding] telegramSendPhoto function does not work correct with base64 image data

### ISSUE THREAD

**Issue by pyro2k9** [openhab/openhab-addons#6687]
## Expected Behavior

An image as base64 data string always looks like this:
`data:image/jpeg;base64, LzlqLzRBQ...` 
(Please correct me if I am wrong...) The part up to the comma  "data:image/jpeg;base64"should be cropped by the telegramSendPhoto function because only the string after the comma is relevant.

## Current Behavior

I used the telegram action before and now switched to the telegram binding. The function "sendTelegramPhoto" has the same transfer parameters - a base64 image can be sent the same.
So i switched everything to the telegram binding. After that I got the fault `Cannot parse data fetched from photo URL as an image. Error: -1`
I investigated that the function sendTelegramPhoto of the telegram binding works different like the corresponding function in the telegram action function.

## Possible Solution

The same code of the telegram action code can be used in the binding:
Change this code to:
```
else {
//NEW: Split image String, data starting after comma (Same code as telegram action)
if (photoURL.split(",").length > 1) {
                String base64Image = photoURL.split(",")[1];
                // Load image from provided base64 image
                logger.debug("Photo base64 provided; converting to binary.");
                try {
                    InputStream is = Base64.getDecoder().wrap(new ByteArrayInputStream(base64Image .getBytes("UTF-8")));
                    try {
                        byte[] photoBytes = IOUtils.toByteArray(is);
                        sendPhoto = new SendPhoto(chatId, photoBytes);
                    } catch (IOException e) {
                        logger.warn("Malformed base64 string: {}", e.getMessage());
                        return false;
                    }
                } catch (UnsupportedEncodingException e) {
                    logger.warn("Cannot parse data fetched from photo URL as an image. Error: {}", e.getMessage());
                    return false;
                }
//NEW
} else {
                logger.warn("Invalid base64 image provided.");
                return false;
            }
}
```

## Steps to Reproduce (for Bugs)

Use the sendTelegramPhoto function with this string:
`data:image/gif;base64,R0lGODlhPQBEAPeoAJosM//AwO/AwHVYZ/z595kzAP/s7P+goOXMv8+fhw/v739/f+8PD98fH/8mJl+fn/9ZWb8/PzWlwv///6wWGbImAPgTEMImIN9gUFCEm/gDALULDN8PAD6atYdCTX9gUNKlj8wZAKUsAOzZz+UMAOsJAP/Z2ccMDA8PD/95eX5NWvsJCOVNQPtfX/8zM8+QePLl38MGBr8JCP+zs9myn/8GBqwpAP/GxgwJCPny78lzYLgjAJ8vAP9fX/+MjMUcAN8zM/9wcM8ZGcATEL+QePdZWf/29uc/P9cmJu9MTDImIN+/r7+/vz8/P8VNQGNugV8AAF9fX8swMNgTAFlDOICAgPNSUnNWSMQ5MBAQEJE3QPIGAM9AQMqGcG9vb6MhJsEdGM8vLx8fH98AANIWAMuQeL8fABkTEPPQ0OM5OSYdGFl5jo+Pj/+pqcsTE78wMFNGQLYmID4dGPvd3UBAQJmTkP+8vH9QUK+vr8ZWSHpzcJMmILdwcLOGcHRQUHxwcK9PT9DQ0O/v70w5MLypoG8wKOuwsP/g4P/Q0IcwKEswKMl8aJ9fX2xjdOtGRs/Pz+Dg4GImIP8gIH0sKEAwKKmTiKZ8aB/f39Wsl+LFt8dgUE9PT5x5aHBwcP+AgP+WltdgYMyZfyywz78AAAAAAAD///8AAP9mZv///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAAKgALAAAAAA9AEQAAAj/AFEJHEiwoMGDCBMqXMiwocAbBww4nEhxoYkUpzJGrMixogkfGUNqlNixJEIDB0SqHGmyJSojM1bKZOmyop0gM3Oe2liTISKMOoPy7GnwY9CjIYcSRYm0aVKSLmE6nfq05QycVLPuhDrxBlCtYJUqNAq2bNWEBj6ZXRuyxZyDRtqwnXvkhACDV+euTeJm1Ki7A73qNWtFiF+/gA95Gly2CJLDhwEHMOUAAuOpLYDEgBxZ4GRTlC1fDnpkM+fOqD6DDj1aZpITp0dtGCDhr+fVuCu3zlg49ijaokTZTo27uG7Gjn2P+hI8+PDPERoUB318bWbfAJ5sUNFcuGRTYUqV/3ogfXp1rWlMc6awJjiAAd2fm4ogXjz56aypOoIde4OE5u/F9x199dlXnnGiHZWEYbGpsAEA3QXYnHwEFliKAgswgJ8LPeiUXGwedCAKABACCN+EA1pYIIYaFlcDhytd51sGAJbo3onOpajiihlO92KHGaUXGwWjUBChjSPiWJuOO/LYIm4v1tXfE6J4gCSJEZ7YgRYUNrkji9P55sF/ogxw5ZkSqIDaZBV6aSGYq/lGZplndkckZ98xoICbTcIJGQAZcNmdmUc210hs35nCyJ58fgmIKX5RQGOZowxaZwYA+JaoKQwswGijBV4C6SiTUmpphMspJx9unX4KaimjDv9aaXOEBteBqmuuxgEHoLX6Kqx+yXqqBANsgCtit4FWQAEkrNbpq7HSOmtwag5w57GrmlJBASEU18ADjUYb3ADTinIttsgSB1oJFfA63bduimuqKB1keqwUhoCSK374wbujvOSu4QG6UvxBRydcpKsav++Ca6G8A6Pr1x2kVMyHwsVxUALDq/krnrhPSOzXG1lUTIoffqGR7Goi2MAxbv6O2kEG56I7CSlRsEFKFVyovDJoIRTg7sugNRDGqCJzJgcKE0ywc0ELm6KBCCJo8DIPFeCWNGcyqNFE06ToAfV0HBRgxsvLThHn1oddQMrXj5DyAQgjEHSAJMWZwS3HPxT/QMbabI/iBCliMLEJKX2EEkomBAUCxRi42VDADxyTYDVogV+wSChqmKxEKCDAYFDFj4OmwbY7bDGdBhtrnTQYOigeChUmc1K3QTnAUfEgGFgAWt88hKA6aCRIXhxnQ1yg3BCayK44EWdkUQcBByEQChFXfCB776aQsG0BIlQgQgE8qO26X1h8cEUep8ngRBnOy74E9QgRgEAC8SvOfQkh7FDBDmS43PmGoIiKUUEGkMEC/PJHgxw0xH74yx/3XnaYRJgMB8obxQW6kL9QYEJ0FIFgByfIL7/IQAlvQwEpnAC7DtLNJCKUoO/w45c44GwCXiAFB/OXAATQryUxdN4LfFiwgjCNYg+kYMIEFkCKDs6PKAIJouyGWMS1FSKJOMRB/BoIxYJIUXFUxNwoIkEKPAgCBZSQHQ1A2EWDfDEUVLyADj5AChSIQW6gu10bE/JG2VnCZGfo4R4d0sdQoBAHhPjhIB94v/wRoRKQWGRHgrhGSQJxCS+0pCZbEhAAOw==`

## Context

The issue showed up when changing the telegram action to telegram binding.

## Your Environment

* Version used: 
```Karaf
  Karaf version               4.2.7
  Karaf home                  /XXXX/XXXX/openHAB/runtime
  Karaf base                  /XXXX/XXXX/openHAB/userdata
  OSGi Framework              org.eclipse.osgi-3.12.100.v20180210-1608

JVM
  Java Virtual Machine        Java HotSpot(TM) 64-Bit Server VM version 25.231-b11
  Version                     1.8.0_231
  Vendor                      Oracle Corporation
  Pid                         20064
  Uptime                      6 days 18 hours
  Process CPU time            1 hour 40 minutes
  Process CPU load            0.01
  System CPU load             0.02
  Open file descriptors       256
  Max file descriptors        4,096
  Total compile time          6 minutes
Threads
  Live threads                157
  Daemon threads              83
  Peak                        203
  Total started               128463
Memory
  Current heap size           117,495 kbytes
  Maximum heap size           2,510,848 kbytes
  Committed heap size         185,344 kbytes
  Pending objects             0
  Garbage collector           Name = 'G1 Young Generation', Collections = 7098, Time = 2 minutes
  Garbage collector           Name = 'G1 Old Generation', Collections = 0, Time = 0.000 seconds
Classes
  Current classes loaded      19,481
  Total classes loaded        55,498
  Total classes unloaded      36,017
Operating system
  Name                        Linux version 4.4.59+
  Architecture                amd64
  Processors                  2
```

* Synology DS218+, DSM 6.2.2-24922 Update 4

```
openHAB Distribution Version Information
----------------------------------------
build-no        : Release Build
online-repo     : https://dl.bintray.com/openhab/mvn/online-repo/2.5

Repository        Version
----------------------------------------
openhab-distro  : 2.5.0
openhab-core    : 2.5.0
openhab1-addons : 1.14.0
openhab2-addons : 2.5.0
karaf           : 4.2.7
```

* openHAB Installed by official .spk
* Telegram binding 2.5.0

**Comment by 9037568** [comment]
This is incorrect.

See the example for [sending a base64 image](https://www.openhab.org/addons/bindings/telegram/#send-an-image-to-telegram-chat) in the documentation.

You need to pass just the base64 data, and not the label ````data:image/jpeg;base64, ````.

**Comment by pyro2k9** [comment]
The content type header seems defined in different regulations. RFC2045 e.g.

The more important questions though are if there are devices which send base64 image data **without** the content header type. Openhab should be user friendly even for the inexperienced user.  
And second thing is that most users will see a relationship of the telegram binding and the telegram action. For standardization reasons and - if possible of course - the functions should work the same to _not to confuse_ the users.

**Comment by ZzetT** [comment]
I agree to change it and make it compatible again with the old actions.

However, before splitting the string, we should maybe check if it starts with "data:". Otherwise, we would confuse users who already removed the "data:" prefix. So, let's just support both formats (simple payload and payload with header).

**Comment by pyro2k9** [comment]
> So, let's just support both formats (simple payload and payload with header).

That sounds like a good and easy solution.

**Comment by hamwong** [comment]
can telegram binding add support for sending mp4 as well?
