### ISSUE TITLE
[Wemo] unable to control devices with Tasmota firmware in Wemo emulation mode

### ISSUE THREAD

**Issue by roman-76** [openhab/openhab-addons#6694]
Hi,

Wemo emulation in Tasmota firmware may use non-standard Wemo ports(49151-49157). Mine uses port 80 in descriptorURL.
After fix #6253 my devices stop responding to the commands. 
Logs showing:
```
23:48:06.340 [DEBUG] [ing.wemo.internal.handler.WemoHandler] - Checking WeMo GENA subscription for 'org.openhab.binding.wemo.internal.handler.WemoHandler@2d62dcf0'
23:49:03.741 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49151'
23:49:03.823 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49152'
23:49:03.828 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49153'
23:49:03.831 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49154'
23:49:03.834 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49155'
23:49:03.837 [TRACE] [ing.wemo.internal.handler.WemoHandler] - Ping WeMo device at '/192.168.1.123:49156'
23:49:03.841 [ERROR] [ing.wemo.internal.handler.WemoHandler] - Failed to get actual state for device 'wemo:socket:Socket-1_0-201612K000C0385': Invalid URI host: null (authority: 192.168.1.123:null)
```
I propose ping first port from descriptorUrl and only if it doesn't respond try pinging a whole range.

I've made a fix in `getWemoURL` and `servicePing` methods in WemoHandler.java
<pre>
    public String getWemoURL(String actionService) {
        URL descriptorURL = service.getDescriptorURL(this);
        int portCheckStart = 49151;
        int portCheckStop = 49157;
        String wemoURL = null;
        String host = null;
        String port = null;
        if (descriptorURL != null) {
            
           <b> int defaultPort = descriptorURL.getPort();
            if(defaultPort == -1) {
                defaultPort = descriptorURL.getDefaultPort();
            }
            
            host = descriptorURL.getHost();
            boolean portFound = false;
            if (defaultPort != -1) {
                portFound = servicePing(host, defaultPort);
            }
            if (portFound) {
                port = String.valueOf(defaultPort);
            } else {</b>
                for (int i = portCheckStart; i < portCheckStop; i++) {
                        portFound = servicePing(host, i);
                        if (portFound) {
                            logger.trace("WeMo device {} responded at Port {}", getUDN(), i);
                            port = String.valueOf(i);
                            break;
                        }
                }
            }
            wemoURL = "http://" + host + ":" + port + "/upnp/control/" + actionService + "1";
            return wemoURL;
        }
        return wemoURL;
    }

    public boolean servicePing(String host, int port) {
        SocketAddress socketAddress = new InetSocketAddress(host, port);
        try (Socket socket = new Socket()) {
            logger.trace("Ping WeMo device at '{}'", socketAddress);
            socket.connect(socketAddress, 250);
            return true;
        } catch (<b>IOException ignored</b>) {
            return false;
        }
    }
</pre>

could you take that change?

PS: I've created a branch but I do not have permission to push it upstream.

**Comment by hmerk** [comment]
@roman-76 please see my comment at your PR. This is not a bug in the WeMo binding, but in 3rd party software. Tasmota‘s WeMo emulation should use WeMo typical port, not something „exotic“.
Terefore I labeled this as an external bug. Please report this as a bug in Tasmota.

**Comment by hmerk** [comment]
@roman-76 Just to add, there are other ha systems that fixed the WeMo port range bug in a similar way as I did within the WeMo Binding, so they all would need to fix this Tasmota issue. Therefore the best way to solve it, would be to soleve the root cause, which is on Tasmota side.

**Comment by roman-76** [comment]
> @roman-76 Just to add, there are other ha systems that fixed the WeMo port range bug in a similar way as I did within the WeMo Binding, so they all would need to fix this Tasmota issue. Therefore the best way to solve it, would be to soleve the root cause, which is on Tasmota side.
Hi @hmerk,
You know the human is the lazy animal, one wrote fast fix, others just copied :) why can’t you be the first who make it right? According to [upnp 1.1 spec](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf#page40) search response should have in location header the url that must be reachable. Even we implemented empirical way to find valid port, why can’t we check one more that defined by standard?

**Comment by hmerk** [comment]
@roman-76 i know the specs and have to admit that Belkins implementation in WeMo devices ist not compliant to the specs.
I had enough trouble to get around their UPnP issues and hat to write recovery fixes for JUPnP, the library we use.

**Comment by hmerk** [comment]
According PR was closed.
