### ISSUE TITLE
[samsungtv] start SmartHub apps on TV with KEY_SmartHub or different

### ISSUE THREAD

**Issue by timon89** [openhab/openhab-addons#6700]
@paulianttila #

In the samsungTV binding i miss the function to start the so called "samsung smart hub" on my TV.

If it is possible to start a spesific application on the smart hub, this would be perfect.

I found the spcific KEY for the smart hub, this can maybe implemented?

KEY:

10071 -- "SmartHub"

[Link to the KEY i found](https://developer.samsung.com/forum/thread/list-of-keycodes/201/310540?boardName=SDK&startId=zzzzz~&startPage=732&curPage=734)

If there is an alternative i don't know, i would be curious.

Regards
Timon

**Comment by hmerk** [comment]
closed due to inactivity
