### ISSUE TITLE
[sonos] Spotify playlist casted from Spotify App or Google Home not resumed after notification

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#6703]
When a playlist is casted to a Sonos device from the Spotify App, the playlist is not resumed after a notification. The binding is resuming the last playlist loaded through the Sonos App.

I will provide a fix.

**Comment by lolodomo** [comment]
Looks like it is not as easy to fix as I imagined.
The notification playback is breaking the "cast" and restoring it from the Sonos does not succeed. I guess only the Spotify App can run it again.

**Comment by lolodomo** [comment]
This is exactly the same problem when a Spotify playlist is run from Google Home.

**Comment by lolodomo** [comment]
I tried to spy network traffic but it was of no help.
Sorry, I give up.

**Comment by eikowagenknecht** [comment]
Just adding my experience here for the different scenarios. Notifications always played at 100% volume, music always played at 25% volume. Sonos devices are on current Version S2. Spotify premium account.

1) "Discover Weekly" playlist playing via "Spotify connect"
-> Stops after the notification sound
2) "Discover Weekly" playlist playing via iOS Spotify App -> AirPlay
-> Stops after the notification sound
3) "Discover Weekly" playlist playing via Sonos App
-> Continues after the notification, but with 100% volume, about 10-20s later it drops down to the original volume again.

**Comment by lolodomo** [comment]
As noone is able to find a solution, I close the issue. My personal feeling is that it is just not possible.
