### ISSUE TITLE
[mqtt] Let user define LWT as thing on/offline status

### ISSUE THREAD

**Issue by hamwong** [openhab/openhab-addons#6723]
I found MQTT 2.5 binding at thing status as on/offline status due to broker online or not, I think it's waste of MQTT LWT feature, most of the MQTT device will use LWT to indicate it's status, if there would be an option let user define LWT topic as thing status, it can be more handy at management in rules or use case. 

MQTT 2.5

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
OH 2.5
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):

* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
openhabian, Raspbian Buster

**Comment by mjcumming** [comment]
I think what you would like is what happens with Homie MQTT devices.

**Comment by bodiroga** [comment]
Shouldn't this be closed after #6738 was merged? :+1: 

@hamwong, have you tried the Availability Topic (it is an advanced configuration parameter of the generic thing) and checked if it works correctly?
