### ISSUE TITLE
[network] Misleading latency values

### ISSUE THREAD

**Issue by baitando** [openhab/openhab-addons#6741]
## Expected Behavior
I would expect latency values which are similar to the ones I get when I send a simple ping request. In my sample case shown below this would be 0.626ms.

```
[21:42:36] openhabian@abcde:~$ ping -c 1 192.168.0.6
PING 192.168.0.6 (192.168.0.6) 56(84) bytes of data.
64 bytes from 192.168.0.6: icmp_seq=1 ttl=64 time=0.626 ms

--- 192.168.0.6 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.626/0.626/0.626/0.000 ms
```

## Current Behavior
If I configure the network device and let the binding do its work, I get values like 15. It's not explicitly mentioned in the docs, but I assume that this value is given in milliseconds. As you can see, the value is much higher than the one provided in the output of the ping command.

## Possible Solution
I had a look at the code of the binding. The values are calculated in `PresenceDetection`. All `perform*Ping` methods (e.g. `performSystemPing`) calculate the latency as the duration it takes to execute the ping command.
* The nanos are stored (I call it `beforeNanos` here).
* The ping command is executed.
* The nanos are stored (I call it `afterNanos` here).
* Latency is calculated as `afterNanos - beforeNanos` and then it is converted from nanoseconds to milliseconds.

I suggest to use the output of the ping command to derive the latency value.

## Steps to Reproduce (for Bugs)
1. Install network binding.
2. Define a pingdevice thing.
3. Create an item and link it to the latency channel of the thing.
4. Check the result and compare it to the output of performing a ping to the IP of the pingdevice.

## Context
I want to monitor the latency in my network and was a bit surprised by the latency values shown by the binding.

## Your Environment

* Version used: openHAB 2.5.0, binding-network - 2.5.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openHABian on Raspbian GNU/Linux 10 (buster)

**Comment by baitando** [comment]
I also found a related community forum post from 2018 (https://community.openhab.org/t/network-binding-latency/39399). I added a link to this bug ticket.

**Comment by davidgraeff** [comment]
Problem is that the latency cannot be parsed easily. Depending on the ping version and operating system the output differs. But a patch is welcome to at least try to parse the output, with a fallback to the current behaviour.

**Comment by baitando** [comment]
I created a pull request with changes related to this issue. You can choose the behavior in the binding config now. By default the same behavior as before is active. If you explicitly configure it, it is tried to extract the latency from the ping command output. If not found, the method execution time is used as fallback.
