### ISSUE TITLE
[homematic] Error: rssiInfo method not found

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#6743]
This problem was first filed here:
https://github.com/openhab/openhab-addons/issues/3153

Then moved to Eclipse:
https://github.com/eclipse/smarthome/issues/5790

Then it was forgotten, I guess. ;-)

**Comment by MHerbst** [comment]
@regnets @sidamos This problem seems to occur only in special situations. Can you please enable DEBUG mode, restart openHAB and then post the beginning of the log file until the error occurs.

**Comment by eikowagenknecht** [comment]
Same problem here with 2.5.1. I'll try to get a debug log.

**Comment by eikowagenknecht** [comment]
I started openhab using "openhab-cli start --debug", but there seem to be no DEBUG entries in the log file. Is this correct? See the attached file below anyways:
[openhab.log](https://github.com/openhab/openhab-addons/files/4210523/openhab.log)

If I enable DEBUG logging with "log:set DEBUG" the following log results (please note that I replaced IP addresses with <device_IPv*_Address> instead, so you can identify the devices behind those addresses.
[debug.log](https://github.com/openhab/openhab-addons/files/4210537/debug.log)

**Comment by MHerbst** [comment]
I have never tried to use this --debug option. For the debug log it would be sufficient to enable debug only for the Homematic binding. It's now a bit too much information :-). 
But I think, I found the reason for the problem. The rssIInfo request ist sent to the RF and CUXD interface, but it seems that CUXD does not support this request.

**Comment by keepinslow** [comment]
Is there already a solution available? I still get that error in the log file and hometaic bridge is still not able to connect to my CCU3 (COMMUNICATION_ERROR). Thx in advance.

**Comment by MHerbst** [comment]
@keepinslow This problem is already open. I will try to work on it next. But I am not sure that the rssiInfo problem prevents communication with the CCU3. Are you sure that all necessary ports are open (like described in the binding's documentation)?

Do you have CUxD installed?

If all ports are open please enable DEBUG mode, restart openHAB and post the content of openhab.log until the message regarding rssiInfo appears.

**Comment by keepinslow** [comment]
Yes, CUxD is installed, ports are open. Any idea how to enable DEBUG mode on a synology disk station...

**Comment by MHerbst** [comment]
@keepinslow Unfortunately I don't have any experience with OH on Synology but I can remember that there have been several problems regarding ports. It is possible that the firewall on the disk station blocks the communication from the CCU to openHAB. Maybe you can find some information in the forum.

> Any idea how to enable DEBUG mode on a synology disk 

The normal way to set the the log level is to connect to the openHAB Karaf console via ssh. The console uses port 8101. From the command line (Linux or Windows 10) you can use the following command `ssh openhab@<OH address> -p 8101` (default password is "habopen").
On the console you can the set the log level with `log:set DEBUG org.openhab.binding.homematic`.
