### ISSUE TITLE
[telegram] Configuration issues in PaperUI for ChatId

### ISSUE THREAD

**Issue by um2ja** [openhab/openhab-addons#6750]
I faced some issue with the configuration of the ChatID in a new thing. The chatId - after saving it in PaperUI - was transformed to 1.xxxxxxxE8. Even if this is mathematically correct, the binding could not match the numbers and filter the according chat.
Log: 
2019-12-29 20:49:03.969 [WARN ] [me.config.core.internal.ConfigMapper] - Could not set field value for field 'chatIds': Can not set java.util.List field org.openhab.binding.telegram.internal.TelegramConfiguration.chatIds to java.math.BigDecimal
java.lang.IllegalArgumentException: Can not set java.util.List field org.openhab.binding.telegram.internal.TelegramConfiguration.chatIds to java.math.BigDecimal

2019-12-29 21:04:36.136 [WARN ] [ng.telegram.internal.TelegramHandler] - The chat id 1.xxxxxxxxxE8 is not a number and will be ignored
The workaround was to configure the thing in a file, which worked fine.

Next issue appeared when I wanted the binding to poll a second chatId in the things file. Which is described in the documentation and it should be done by a comma separated list of chatId's
Log: 
2020-01-02 15:14:16.154 [WARN ] [ng.telegram.internal.TelegramHandler] - The chat id 13xxxxxxxx,875xxxxx is not a number and will be ignored
2020-01-02 15:17:20.134 [WARN ] [ng.telegram.internal.TelegramHandler] - The chat id 13xxxxxxx, 875xxxxxx is not a number and will be ignored.
The workaround for that issue was to create group in telegram.

The openhab release is 2.5.0 and accordingly the telegram binding.
It is running on a PI.

**Comment by 9037568** [comment]
````
2019-12-29 21:04:36.136 [WARN ] [ng.telegram.internal.TelegramHandler] - The chat id 1.xxxxxxxxxE8 is not a number and will be ignored
````

The binding expects chat ids to be ints. What value was used here?

**Comment by um2ja** [comment]
A chat id has 9 digits in telegram and this is what I used. But - for 
some reason - it was converted to that 1.xxE8 value.

I did not enter it like that in PaperUI.



Am 03.01.20 um 14:11 schrieb Chris Carman:

**Comment by um2ja** [comment]
to explain it a bit better:

I entered a regular chat id (9 digits number)in the PaperUI.

I saved the thing configuration.

When I reopened the thing and the int (long) was converted to this 
1.xxxE8 value. Obviously that value was stored really as the binding 
could not fetch messages with this chat id. Meaning, it was converted 
while saving the thing.


Am 03.01.20 um 14:11 schrieb Chris Carman:

**Comment by 9037568** [comment]
I built a fix for the comma-separated list problem.  Try [this jar](https://drive.google.com/open?id=1Z6eaIEdLGpRep6E8arIpnIW1Yz0bhz4o) to test it out.

I can't do anything for the other problem without the actual id that was used.

**Comment by um2ja** [comment]
Here is the chat id  131790571I will test the jar and let you knowVon Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: Chris Carman <notifications@github.com> Datum: 03.01.20  18:20  (GMT+01:00) An: openhab/openhab-addons <openhab-addons@noreply.github.com> Cc: um2ja <udo@um2ja.de>, Author <author@noreply.github.com> Betreff: Re: [openhab/openhab-addons] [Telegram binding] Configuration issues in PaperUI for ChatId (#6750) I built a fix for the comma-separated list problem.  Try this jar to test it out.
I can't do anything for the other problem without the actual id that was used.

**Comment by um2ja** [comment]
i'll test and let you know

The chat id is: 131790571

Am 03.01.20 um 18:20 schrieb Chris Carman:

**Comment by um2ja** [comment]
I can confirm that two chat ids, configured in a file do work as expected.

still; configure the same in PaperUI isn't possible.
![grafik](https://user-images.githubusercontent.com/41586273/71767023-5aa10500-2f07-11ea-9040-47ca215d0dae.png)
The issue is, that a redline below the value is shown as long as you don't enter a value or a wrong value. For the bot Id it is enough to enter a single number or character and the red line disappears. For the chat id you can enter what ever you want, the red line stays visible and consequently, you can't save the configuration.

**Comment by J-N-K** [comment]
Did you press <Enter> after entering the chatId? That is required to put it in the list.

**Comment by um2ja** [comment]
No I didn't. I see now how it works. I can confirm that everything is working fine.Sorry for the confusionVon Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: J-N-K <notifications@github.com> Datum: 04.01.20  15:50  (GMT+01:00) An: openhab/openhab-addons <openhab-addons@noreply.github.com> Cc: um2ja <udo@um2ja.de>, Author <author@noreply.github.com> Betreff: Re: [openhab/openhab-addons] [Telegram binding] Configuration issues in PaperUI for ChatId (#6750) Did you press  after entering the chatId? That is required to put it in the list.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openhab/openhab-addons/issues/6750?email_source=notifications\u0026email_token=AJ5I4YPHZVSL5CLPBT34THDQ4CO4PA5CNFSM4KCKUGKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEICZLVY#issuecomment-570791383",
"url": "https://github.com/openhab/openhab-addons/issues/6750?email_source=notifications\u0026email_token=AJ5I4YPHZVSL5CLPBT34THDQ4CO4PA5CNFSM4KCKUGKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEICZLVY#issuecomment-570791383",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ZzetT** [comment]
> Did you press <Enter> after entering the chatId? That is required to put it in the list.

Do you know if there is any improvement planned for this? I already see many users in the forum that walked right into that trap. Would be nice if the chatId is considered even if the user did not press ENTER.

**Comment by crisjff** [comment]
> 
> 
> > Did you press  after entering the chatId? That is required to put it in the list.
> 
> Do you know if there is any improvement planned for this? I already see many users in the forum that walked right into that trap. Would be nice if the chatId is considered even if the user did not press ENTER.

Or just a note below the line saying that you should press ENTER after insert.

**Comment by olafnorge** [comment]
> 2020-01-02 15:17:20.134 [WARN ] [ng.telegram.internal.TelegramHandler] - The chat id 13xxxxxxx, 875xxxxxx is not a number and will be ignored.

Is still in issue in release 2.5.4. Is there any ETA when this will be fixed and released?

**Comment by HerzScheisse** [comment]
@olafnorge hey, did you use a .things file?

I also stumpled upon this exakt error as I added my chat ids with comma seperated... but you need to add each ID like this `chatIds ="ID1","ID2"`

this was not really clear to me... and thats why i did a PR yesterday which is already merged... https://github.com/openhab/openhab-addons/pull/7544

**Comment by olafnorge** [comment]
Thanks for coming back and fixing it. I wanted to use it in a things config file. But other stuff in openhab's version 2.5 is also quite broken so I decided to stay at 2.4 and do not have this issue right now.

**Comment by hmerk** [comment]
closed due to inactivity
