### ISSUE TITLE
[mihome] Add support for Aqara Hub

### ISSUE THREAD

**Issue by kornero** [openhab/openhab-addons#6754]
Hello.
I'm trying to add Aqara Hub (lumi.gateway.aqhm01).

I got token from patched mi home app, and add Thing.

But it was added via 'Xiaomi Mi IO Binding'.
Thing status is online, but I can't do anything with it.

I'm using openhub 2.5.0 on windows.

Thank you!

**Comment by agolks** [comment]
have a hub and key, too, and would like to help.
how to proceed?

**Comment by hmerk** [comment]
closed due to inactivity
