### ISSUE TITLE
[rfxcom] RFXCOM SF01 Fan Support 

### ISSUE THREAD

**Issue by josmeester** [openhab/openhab-addons#6767]
Hi,

It would be great if support could be added to the RFXCOM Binding to support the fan channel. Specifically in my case Siemens SF01 Fan.

If any further information or debug info is required I am happy to provide this as well as test code.

An example from RFXmngr for turning on or off the light is:

Packettype    = Fan
subtype       = Siemens SF01
Sequence nbr  = 4
ID            = 93A1 decimal:37793
Command       = Light
Signal level  = +10 dBm

Other commands differ only the Command parameter. The possible values are:
"Light", "+ or Learn", "-", "Timer", "Confirm".

Thanks.

**Comment by hmerk** [comment]
closed due to inactivity
