### ISSUE TITLE
[rfxcom] Sending RAW String doesn't work

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab-addons#6769]
I would like to send a raw string via the RFXCOM binding. Currently it seems to support receiving in Hexadecimal but it doesn't seem to support sending RAW Messages. Using the Windows RFXCOM Manager App I can send the string using the raw transmit function but the RFXCOM Binding doesn't seem to have this function, The string I am trying to send is in this file which the windows app reads and sends:

[Vapoiriser ON Test.txt](https://github.com/openhab/openhab-addons/files/4024184/Vapoiriser.ON.Test.txt)

**Comment by Jamstah** [comment]
RAW or UNDECODED?

I'm about to add support for receiving RAW, then we can look at sending RAW too.

I don't think you can send UNDECODED.

**Comment by sheppy99** [comment]
That would be great, happy to help with testing. I'm running OH3.1 nightly

**Comment by Jamstah** [comment]
Here's a version with Raw TX enabled: https://github.com/Jamstah/openhab-addons/blob/rfxcom-raw/bundles/org.openhab.binding.rfxcom/README.md#raw---rfxcom-raw-messages

I've done some fairly major refactoring to enhance testability etc as well, still some more cleanup to do before I am comfortable to PR, but it works for me and I'd like feedback on if this is a good way to use it.

The other option is to allow for the pulse channel to be updated in scripts etc, but that seems over the top and we probably don't need it at the moment.

Jar here: https://www.dropbox.com/s/7zmglgkvgag6ibd/org.openhab.binding.rfxcom-3.1.0-SNAPSHOT.jar?dl=0

**Comment by Jamstah** [comment]
Did some refactoring, PR now here: https://github.com/openhab/openhab-addons/pull/10866

**Comment by sheppy99** [comment]
Fantastic! Won't have time to test this for around 16 hours from now due to time zone (GMT + 12) I'll download and test whatever jar is there tomorrow late lunchtime

**Comment by sheppy99** [comment]
@Jamstah thanks for your work on this.

I've downloaded the jar from dropbox, uninstalled the original binding and added the jar. Existing items work. I've placed the binding into debug mode with the idea or seeing what if received from the remote so I could resend it. In the logs I get 
`
      2021-06-16 15:34:38.697 [DEBUG] [internal.handler.RFXComBridgeHandler] - Message received: Raw data = 0A0301122CE78062900448, Packet type = UNDECODED_RF_MESSAGE, Seq number = 18, Sub type = ARC
     2021-06-16 15:34:38.729 [DEBUG] [internal.handler.RFXComBridgeHandler] - Message received: Raw data = 0A03011330567806290451, Packet type = UNDECODED_RF_MESSAGE, Seq number = 19, Sub type = ARC
 `
from the original remote but the String item I've attached to the pulses channel doesn't change from NULL. I have another String item bound to rawPayload (String) which also doesn't change.

What am I missing?

**Comment by Jamstah** [comment]
That's an undecoded message you're pasting there, not a raw message.

I haven't worked out exactly what prompts RAW vs Undecoded messages. If the firmware can decode the subtype, I guess it does that instead of providing the raw pulses.

Try running with everything off except undecoded, that way everything should come through as raw. Alternatively, use RFXmngr to get the pulses instead.

**Comment by sheppy99** [comment]
It seems the RFXtrx433E needs the Pro firmware before it receives pulses. I've just updated the firmware and now the pulse channel is updated. I also added the pulses to the thing and I can now switch the device ON and OFF, albeit the command I'm sending is a power toggle with the same commands for ON and OFF

**Comment by Jamstah** [comment]
That's a good note for the readme!

Thanks for testing.
