### ISSUE TITLE
[miio] Add support for Xiaomi Ceiling Lamp (yeelink.light.ceiling11)

### ISSUE THREAD

**Issue by chlctt** [openhab/openhab-addons#6787]
I have ordered a new Xiaomi Ceiling Light and found out that it is currently not supported by the Xiaomi Mi IO Binding.

I was able to get the Token from the Mi Home App and configured the thing. The OpenHAB log shows the following.

```
[hingStatusInfoChangedEvent] - 'miio:basic:ceiling2' changed from OFFLINE (COMMUNICATION_ERROR) to ONLINE
[me.event.ThingUpdatedEvent] - Thing 'miio:basic:ceiling2' has been updated.
[WARN ] [internal.handler.MiIoAbstractHandler] - Mi Device model Unknown Mi IO Device (unknown) identified as: miio:unsupported, thingtype miio:basic. Does not matches thingtype miio:unsupported. Unexpected, unless unless manual override.
[me.event.ThingUpdatedEvent] - Thing 'miio:basic:ceiling2' has been updated.
[WARN ] [io.internal.handler.MiIoBasicHandler] - Database entry for model 'yeelink.light.ceiling11' cannot be found.
```

If more information is required, please let me know. I will provide as fast as possible.

**Comment by marcelrv** [comment]
@chilly163 please add it (manually) as miio:basic item.
Update the configuration to `yeelink.light.ceiling1` than test if all channels work
If it works we can add the model to the database.

If not, we need to make a specific database file for your model.
In that case we need to know what channels are okay and which not

**Comment by chilly163** [comment]
Hi @marcelrv ,

I added _model="yeelink.light.ceiling"_ to the thing configuration.

`Thing miio:basic:ceiling2  "Yeelight LED Ceiling Lamp" @ "Badezimmer"  [ host="192.168.xxx.xxx", token="xxx", deviceId="101C5B6B", model="yeelink.light.ceiling"]`

```
[INFO ] [internal.handler.MiIoAbstractHandler] - Mi Device model yeelink.light.ceiling11 has model config: yeelink.light.ceiling. Unexpected unless manual override
[WARN ] [internal.handler.MiIoAbstractHandler] - Mi Device model Unknown Mi IO Device (unknown) identified as: miio:unsupported, thingtype miio:basic. Does not matches thingtype miio:unsupported. Unexpected, unless unless manual override.
```

Next step:

`Thing miio:basic:ceiling2  "Yeelight LED Ceiling Lamp" @ "Badezimmer"  [ host="192.168.xxx.xxx", token="xxx", deviceId="101C5B6B", model="yeelink.light.ceiling**1**"]`

```
[INFO ] [internal.handler.MiIoAbstractHandler] - Mi Device model yeelink.light.ceiling11 has model config: yeelink.light.ceiling**1**. Unexpected unless manual override
2020-01-14 17:23:55.648 [me.event.ThingUpdatedEvent] - Thing 'miio:basic:ceiling2' has been updated.
[WARN ] [internal.handler.MiIoAbstractHandler] - Mi Device model Unknown Mi IO Device (unknown) identified as: miio:unsupported, thingtype miio:basic. Does not matches thingtype miio:unsupported. Unexpected, unless unless manual override.
```

Did the same for all device models yeelight.light.ceilingX listed on https://www.openhab.org/addons/bindings/miio/. No success. :(

So I assume, the device is currently not supported?

**Comment by chilly163** [comment]
Regarding the supported channels, I'm not sure how to identify the channels or the informations you require.

I do own another Yeelight ceiling lamp, which identifies itself as yeelight.light.ceiling3.

`[INFO ] [internal.handler.MiIoAbstractHandler] - Mi Device model yeelink.light.ceiling3 identified as: Yeelight LED Ceiling Lamp v3 (yeelink.light.ceiling3). Matches thingtype miio:basic`

The remote is the same and I have the same options within the Yeelight App.

**Comment by chilly163** [comment]
Hey all, sorry to bother.

Is there anything I can help with? Do you need any more information regarding my lamp? Any logging required?

Regads,
Sebastian

**Comment by marcelrv** [comment]
@chilly163 indeed, if you don't see anything than the device is not supported.
It would be slightly surprising as most yeelights share at least bit of the channels. (e.g. on/off I would certainly expect to work)

Maybe you can send me a more full log of what you see, things I would be looking for is what responses it gives for the various properties requested from the device (e.g. is the command not accepted or the property returned is empty)

In order to see that, you need to set the binding to debugging
`log:set DEBUG org.openhab.binding.miio`
and `log:tail org.openhab.binding.miio`
