### ISSUE TITLE
[sonos] when sonos speaker is muted notification sound is not played

### ISSUE THREAD

**Issue by mlommers** [openhab/openhab-addons#6795]
when sonos speaker is muted also no notification sounds are played. As you can set the notificationVolume in the Things configuration, I would expect that the mute wouldn’t have impact on notifications sounds. Besides that i wonder if it is Desired behavior Anyhow for notifications. Is this a bug in the binding? As designed? And or the behavior as implemented by Sonos itself.

**Comment by lolodomo** [comment]
Yes the binding is not unmuting. 
When you mute, that is you don't want any sound.

**Comment by mlommers** [comment]
Ok, than I will solve it in the rule firing the notification. Thanks!
