### ISSUE TITLE
Add Teleinfo Binding

### ISSUE THREAD

**Issue by nokyyz** [openhab/openhab-addons#680]
Hi,
I'm working on new binding OH2 which enables to manage data from **French electricity meter** (http://www.magdiblog.fr/wp-content/uploads/2014/09/ERDF-NOI-CPT_02E.pdf) : **Teleinfo binding**.

This binding will have the following features:
- retrieves ERDF frames from a serial port 
- retrieves ERDF frames from a remote serial port (server)
- management of all data types : ADCO, OPTARIF, HCHC, HCHP, ISOUSC, IINST, IMAX, PAPP, PTEC, ADPS, MOTDETAT, etc.
- calculates the cost of power consumption 

Any help will be appreciate !
##

**Comment by srsr** [comment]
Hello,
I am very interested in this module, have you progressed?

**Comment by mgallissot** [comment]
HI,
Interested by this new binding, how can I help?

**Comment by vdanjean** [comment]
Hi,
Are there any news or a git with preliminary code somewhere (so that we can participate)?

**Comment by kaikreuzer** [comment]
@vdanjean The code seems to be available at https://github.com/nokyyz/teleinfo-reader, but there wasn't any activity since 2016...

Not sure whether anyone would be interested to take this over and build on it? If not, I'd suggest to close this issue here.

**Comment by nokyyz** [comment]
Hi all, I am sorry but I have no enough free time to work on this plugin. The source code on my repository (https://github.com/nokyyz/teleinfo-reader) enables to read teleinfo frames and broadcast them on network.

**Comment by nokyyz** [comment]
Hi all, I have restarted my work on Teleinfo binding ! I think that in 2/3 weeks, I will have a first alpha release compliant with OH 2.5.
For the moment, I read all Teleinfo data from my Electrical meter with HC/HP option.

Can volunteers help me for tests on other types of meters (Base, Tempo, EJP options) ?

**Comment by nokyyz** [comment]
@davidgraeff @wborn is it possible to reopen this issue please ?

**Comment by wborn** [comment]
That's good news! I've reopened the issue. :-)

**Comment by nokyyz** [comment]
I just created a thread to discuss the binding and its features:
https://community.openhab.org/t/new-teleinfo-binding-tester-and-feedback-welcome/77857

**Comment by srsr** [comment]
Hello nokyyz,
Sorry I own a HC/HP option too.

**Comment by nokyyz** [comment]
Hi @srsr, have you planned to test this binding ? :-) The Teleinfo binding is working in my platform (hardware: GCE teleinfo module, Synology NAS 415+ & software : DSM 6.x, OpenHAB 2.5) but I will appreciate some feedbacks from differents platforms...

**Comment by nokyyz** [comment]
Hi all,
Here is the new release (Beta 20191104-2035) : https://github.com/nokyyz/openhab2-addons/releases/tag/beta-20191104-2035

Any feedback will be welcome !

**Comment by vdanjean** [comment]
Hi,
Thank you very much for this development. I will try it soon. Before looking in the sources, I've a question: my serial controler is plugged into a physical machine, however my OpenHAB run into a virtual machine. So, it there a simple way to configure this plugins to communicate through TCP/IP (for example with socat running on the physical machine to relay the data)?
Regards

**Comment by nokyyz** [comment]
Hi @vdanjean,
The latest release ([Beta 20191104-2035](https://github.com/nokyyz/openhab2-addons/releases/tag/beta-20191104-2035)) of Teleinfo binding must support the RFC2217 protocol. I can't test this feature but I have copy the source code of EnOcean for this RFC2217 protocol, so it should be OK. For more details, see the EnOcean binding documentation at https://www.openhab.org/addons/bindings/enocean/#concepts-configuration. 
Note: `ser2net` command  seems to be used instead of `socat` command

**Comment by vdanjean** [comment]
Hi,
I should have a bit of time to do tests. Do you have some documentation about how to compile the teleinfo binding? I'm using openhab packages from https://dl.bintray.com/openhab/apt-repo2 (currently, version 2.5.3-1)
Regards,
   Vincent

**Comment by nokyyz** [comment]
Hi @vdanjean,
I have compile the latest version of Teleinfo binding. You can download it here : https://github.com/nokyyz/openhab2-addons/releases/tag/beta-20200204-1329

To compile OpenHAB sources and Teleinfo binding, you must have Apache Maven. From memory, the 'mvn install' command on root sources folder must allow to generate a Teleinfo JAR file.

**Comment by fwolter** [comment]
@nokyyz @olivierkeke Can you give a short overview, why there are to open PRs? Which one should be reviewed/merged? What is the difference between the two?

**Comment by olivierkeke** [comment]
@fwolter The two PR are quite the same. 

In #7516 @nokyyz commits and my commits are mixed with upstream commits since we made some merge with upstream instead of rebasing on upstream. This prevents us to sign off our commits with a simple command.

In #7744 commit history is clean: our commits are at the last commits in the history. Since I have no news of @nokyyz for several weeks and no right on the branch of the initial PR, I made a separate PR. I also rebased our work on the last 2.5.6-SNAPSHOT version. AFAIK #7744 should be reviewed.

**Comment by fwolter** [comment]
@nokyyz If you agree with @olivierkeke, I would review #7744.

**Comment by nokyyz** [comment]
Hi @fwolter, @olivierkeke,
After analysing @olivierkeke commit clean history in #7744, I see that all of my commits have been sign-off by Olivier. Is it possible to fix this ?

**Comment by olivierkeke** [comment]
Hi @nokyyz,
Glad to read you again!
If you launch `git rebase HEAD~78 --signoff` on the PR branch you will add your signature on all our commits (without removing mine AFAIK).
After that you can push your change with `git push --force-with-lease origin rebase-2.5.x`.
I have added you as collaborator on my fork repo.
@fwolter Will this be OK?

**Comment by fwolter** [comment]
It should work this way, although I didn't count the `HEAD~78`.

**Comment by olivierkeke** [comment]
@nokyyz Since teleinfo binding is now an official addon, can you close this issue?

**Comment by nokyyz** [comment]
Of course. Done !
