### ISSUE TITLE
[darksky] Typo error in examples

### ISSUE THREAD

**Issue by hariskar** [openhab/openhab-addons#6812]
In this page: https://www.openhab.org/addons/bindings/darksky/ there are some mistakes:
In items
`Number localCurrentUVIndex "Current precipitation probability [%d]" <none> { channel="darksky:weather-and-forecast:api:local:current#uvindex" }`
should become
`Number localCurrentUVIndex "Current UV index [%d]" <none> { channel="darksky:weather-and-forecast:api:local:current#uvindex" }`

and in sitemap

```
        Text item=localDailyForecastTodayMinApprentTemperature
        Text item=localDailyForecastTodayMaxApprentTemperature
```

should become

```
        Text item=localDailyForecastTodayMinApparentTemperature
        Text item=localDailyForecastTodayMaxApparentTemperature
```

**Comment by cweitkamp** [comment]
Thanks for the hints. I submitted a PR (#6817) to fix them all.
