### ISSUE TITLE
One-time poll after command

### ISSUE THREAD

**Issue by feens** [openhab/openhab-addons#682]
See here for inspiration: https://community.openhab.org/t/zwave-feature-needed-polling-a-zwave-device-from-a-rule/2554/16

Being as the goal is to not allow polling from the rules, something that I feel would be super beneficial from the binding then is the ability to poll shortly after a change. My problem case is with GE dimmers (and I think other dimmers have the same issue): When they change, they just report the start value and current value (i.e. dim from 0 to 6), and not the end value. It makes it very difficult to do some rules; I'm currently in a mess of logic to properly determine if they are turned "ON" or "OFF". Sure, I can try and use refresh_interval, but I'd need to set it pretty low to be useful and I only need the data once, so it's silly to flood the whole zwave queue for something that's only needed once. Or perhaps a better solution is to build in a poll following SWITCH_MULTILEVEL commands.

**Comment by cdjackson** [comment]
Note that as of #690 it is possible to manually refresh a channel using the RefreshType.REFRESH command.

**Comment by feens** [comment]
This seems to do pretty much what I desired and seems to work well now, so I'm going to close.
