### ISSUE TITLE
[zwave] Fibaro FGMS001 with older firmware not recognized in OpenHAB 2.5

### ISSUE THREAD

**Issue by hainsilma** [openhab/openhab-addons#6822]
## Expected Behavior
I have 2 Fibaro FGMS001 multisensors, with different firmware revisions, both should be recognized at startup of OpenHAB. Openhab is installed on a Raspberry Pi 4 connecting to zwave devices through an Aeotec Gen 5 USB-stick. 

## Current Behavior
The FGMS001 with FW 3.2 is working as expected, but the older Firmware revision is not recognized.
Logs related to zwave attached from restart of Openhab, and node4 - the faulty one in separate log.

## Possible Solution
Updating the motion sensor with a newer firmware might be a solution, but as far as I know it requires either a Fibaro base station or sending the sensor to Fibaro for update. Both are not reasonable solutions.

## Your Environment
OpenHAB version 2.5.0
zwave binding version 2.5.0
Raspbian Release 10, 4.19.75-v71+
[zwaveinit.log](https://github.com/openhab/openhab-addons/files/4050826/zwaveinit.log)
[zwaveNode4.log](https://github.com/openhab/openhab-addons/files/4050827/zwaveNode4.log)
![Habmin picture](https://user-images.githubusercontent.com/59799766/72221877-5019e780-3567-11ea-8503-21e63086aafa.png)
![Habmin picture_2](https://user-images.githubusercontent.com/59799766/72221878-514b1480-3567-11ea-9a44-8f0061ca0ea5.png)

**Comment by wborn** [comment]
Can you transfer this issue to the [org.openhab.binding.zwave](https://github.com/openhab/org.openhab.binding.zwave/) repo @kaikreuzer?

**Comment by hainsilma** [comment]
Absolutely.
