### ISSUE TITLE
[Spotify] Playlist Amount/Offset

### ISSUE THREAD

**Issue by JiroMusik** [openhab/openhab-addons#6843]
Hi @Hilbrand 

**Request**
currently the Spotify Connect Binding receives the default 20 Playlists.
It would be nice to have an option to set the amount or if you could set it to the maximum of 50.
There is another option "offset" in the Spotify Docs which could be used for even more playlists, for example with <playlistid>#<offset>.

**My Environment**
Openhabian 2.5.0
Raspberry Pi 3B+

**Comment by ccaramel** [comment]
Hi, thank you for your request and the work with this binding. 
It would be appreciated to be able to increase the amount off available playlists.
Regards.
