### ISSUE TITLE
[knx] update to most recent calimero version

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#6849]
For reference:
https://community.openhab.org/t/sending-off-command-to-group-of-lights-results-in-some-lights-staying-on-with-missing-changed-to-log-message/85824/14?u=udo_hartmann

**Comment by holgerfriedrich** [comment]
@udo1toni Calimero 2.5M1 is available via Maven Central, update could be done. I have no idea if we can expect a final 2.5 release in the near future....
