### ISSUE TITLE
[mqtt] MQTT Item in PaperUI has no decimal points

### ISSUE THREAD

**Issue by moonilightshaker** [openhab/openhab-addons#6859]
After upgrading from 2.4 to 2.5.1-2 using APT package on Ubuntu , all mqtt items in the PaperUI have no decimal points and no decimal value. The value is rounded to the nearest whole number.

kind regards

**Comment by jochen314** [comment]
Hi,
I am not able to reproduce your problem.
Can you give us some more information on the item configuration you are using and the message you are receiving?
Thank you.

**Comment by moonilightshaker** [comment]
Hello,
no problem.

-MQTT Binding (binding-mqtt - 2.5.1)
-Mosquitto Broker
-MySQL Database

The items were configured via Paper UI.
![Item1](https://user-images.githubusercontent.com/59542603/72684971-84505380-3ae5-11ea-9e2e-d87e0da60c9a.JPG)
![Item2](https://user-images.githubusercontent.com/59542603/72684972-84e8ea00-3ae5-11ea-9dbc-74d38b92a9ea.JPG)

Broker:
![Item3](https://user-images.githubusercontent.com/59542603/72685038-4bfd4500-3ae6-11ea-94d9-ebceffd7a810.JPG)

Paper UI:
![Item4](https://user-images.githubusercontent.com/59542603/72685039-4c95db80-3ae6-11ea-81fe-aa5590c3e307.JPG)

Database:
![Item5](https://user-images.githubusercontent.com/59542603/72685081-cb8b1400-3ae6-11ea-8dd3-4518f73f323d.JPG)

Display in HABPanel:
![HabPanel](https://user-images.githubusercontent.com/59542603/72685161-74397380-3ae7-11ea-9f16-7cb8501e7e46.JPG)

**Comment by jochen314** [comment]
Sorry, but i have now idea.
My instance des not have the problem.
My only idea is, that it has to do with the fact, that the channel already existed before the update, which I cannot reproduce.

**Comment by J-N-K** [comment]
Since it is working in HABPanel an in the database it is a problem of PaperUI. Please open an issue there if the problem persists.

**Comment by moonilightshaker** [comment]
> 
> 
> Sorry, but i have now idea.
> My instance des not have the problem.
> My only idea is, that it has to do with the fact, that the channel already existed before the update, which I cannot reproduce.

Thanks for the info.
A new installation of PaperUI and creating new items didn't help either.
