### ISSUE TITLE
Provide generic channels for things

### ISSUE THREAD

**Issue by theater** [openhab/openhab-addons#6863]
I think that would be useful to provide a generic (non-user defined) channels for every thing that come from the framework. 
Example:
thing status - offline/online
I currently use a rule for one of my bridges that updates an item when the bridge status changes. That would be great if can come out of the box.

People who are more aware of what we have inside the things can propose more "reserved" channels.

Cheers,
Konstantin

**Comment by J-N-K** [comment]
But we can access the thing status from rules anyway. Why do you need a channel for that?

**Comment by theater** [comment]
The only reason is if you want to directly show the status of the thing in the UI. With this you can directly map the channel to an item and not do rule for that.
Of course that can be developed by extending the thing itself with additional channel but maybe if more people see sense in the idea we can develop this in the base of things. I'd just like to check if development community sees any value in this and if it doesn't violate the design.
If we decide to go for it I can give it a try to develop this. Does not look like a big feature, but I'm not very deep into the core code yet.

**Comment by Hilbrand** [comment]
> The only reason is if you want to directly show the status of the thing in the UI.

If the only reason is the UI then doesn't that mean the UI needs better support for showing a thing is offline? Making it a channel seems a work around to that functionality missing. Since the UI is now in development I would suggest to open a new issue in the UI repo.

**Comment by kaikreuzer** [comment]
Fully agree with @Hilbrand. In any case, online/offline is a system administration information and not related to items. The new UI will have better admin support and make use of such information.
