### ISSUE TITLE
[milight] MI light binding

### ISSUE THREAD

**Issue by oliverchapple** [openhab/openhab-addons#6870]
:
I added binding-milight - 2.5.1 and it picks up ibox

not picking. Up else like zones etc

.  On openhab 2.5.1 raspberry pi 3b 

From Oliver

**Comment by Hilbrand** [comment]
You need to add more information, just putting in a vage issue with lots of typos is not very helpful. If you have no other infoyry the only thing we can do about it is close this issue due to lack of detail.

**Comment by Skinah** [comment]
Closing as it is now 1 year on and no reply for more info.
