### ISSUE TITLE
[modbus] Changing things file cause some data things to go offline 

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#6876]
Reported here in community forums https://community.openhab.org/t/modbus-update-of-items-make-poller-go-offline-item-cache/72132

Editing `things` file can cause some `data` things to become offline.

## Expected Behavior

Editing things file should not "break" things.

## Current Behavior

Editing `things` file can cause some `data` things to become offline. It seems to be "random" which things get offline

## Possible Solution

In modbus binding there are three level of things
1. endpoint (representing connection to modbus server)
2. poller
3. data thing

Endpoint things have the following in `initialize` (see [AbstractModbusEndpointThingHandler.java](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/handler/AbstractModbusEndpointThingHandler.java#L68-L72)):
```java
            if (this.getThing().getStatus().equals(ThingStatus.ONLINE)) {
                // If the bridge was online then first change it to offline.
                // this ensures that children will be notified about the change
                updateStatus(ThingStatus.OFFLINE);
            }
```

The same piece of logic should be in poller `ThingHandler` `initialize`.

PR will follow.

## Steps to Reproduce (for Bugs)

1. Run `diagslave` (modbus server) at localhost, port 502
2. Create the following things and items
`test.things`:

```
Bridge modbus:tcp:endpointSMA [ host="127.0.0.1", port=502, id=3 ] {

	Bridge poller SMA_Yield [ start=30531, length=2, refresh=10000, type="input" ] {
		Thing data SMA_Yield [ readStart="30531", readValueType="uint32"]
	}

	Bridge poller SMA_DC1 [ start=30769, length=6, refresh=10000, type="input" ] {
		Thing data SMA_DC_A_1 [ readStart="30769", readValueType="int32" ]
		Thing data SMA_DC_V_1 [ readStart="30771", readValueType="int32" ]
		Thing data SMA_DC_P_1 [ readStart="30773", readValueType="int32" ]
	}
		
	Bridge poller SMA_DC2 [ start=30957, length=6, refresh=10001, type="input" ] {
		Thing data SMA_DC_A_2 [ readStart="30957", readValueType="int32" ]
		Thing data SMA_DC_V_2 [ readStart="30959", readValueType="int32" ]
		Thing data SMA_DC_P_2 [ readStart="30961", readValueType="int32" ]
	}		

	Bridge poller SMA_ACV [ start=30783, length=6, refresh=10000, type="input" ] {
		Thing data SMA_AC_V_L1 [ readStart="30783", readValueType="uint32" ]
		Thing data SMA_AC_V_L2 [ readStart="30785", readValueType="uint32" ]
		Thing data SMA_AC_V_L3 [ readStart="30787", readValueType="uint32" ]
	}

	Bridge poller SMA_ACAMPERE [ start=30977, length=6, refresh=10000, type="input" ] {
		Thing data SMA_AC_A_L1 [ readStart="30977", readValueType="int32" ]
		Thing data SMA_AC_A_L2 [ readStart="30979", readValueType="int32" ]
		Thing data SMA_AC_A_L3 [ readStart="30981", readValueType="int32" ]
	}
		
	Bridge poller SMA_Power [ start=30775, length=2, refresh=10000, type="input" ] {
		Thing data SMA_Power [ readStart="30775", readValueType="int32" ]
	}
		
	Bridge poller SMA_Temperature [ start=30953, length=2, refresh=10000, type="input" ] {
		Thing data SMA_Temperature [ readStart="30953", readValueType="int32" ]
	}

}  
```

`test.items`:
```
Number SMA_DC_A_1 "SMA_DC_A_1" { channel="modbus:data:endpointSMA:SMA_DC1:SMA_DC_A_1:number" }
Number SMA_DC_A_2 "SMA_DC_A_2" { channel="modbus:data:endpointSMA:SMA_DC2:SMA_DC_A_2:number" }
```

Observe that all things are online.

2. Change refresh of single poller

Change
```
	Bridge poller SMA_DC1 [ start=30769, length=6, refresh=10000, type="input" ] {
```
to
```
	Bridge poller SMA_DC1 [ start=30769, length=6, refresh=10001, type="input" ] {
```

Save the file.

3. Some data things are offline

## Your Environment
2.5.1 release with released addons

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by splatch** [comment]
Hey @ssalonen, I've run into this issue last week. For me it was happening with things file and a serial port connection. Once file was updated I was receiving "Port in use" errors. What I observed seems to be some kind of race condition.
I know that your issue is related only to things file, however mine symptoms were the same - flickering of data elements.

**Comment by ssalonen** [comment]
Hi @splatch , appreciate if you can test it out with this version.

I also have fixes to ensure that serial and tcp connections are closed when the endpoint thing is disposed. Will post separately pr for that. This might explain the "port in use" error.

If you still get problems with this version, appreciate if you can create a new bug about it with clear steps to reproduce.

**Comment by ssalonen** [comment]
@splatch I spent some more time to look into "Port in use" errors. I could not reproduce the issue, see https://community.openhab.org/t/problem-with-modbus-binding-with-dynamic-on-off/92288/14?u=ssalonen for more details. 

Could you please report to community forum thread with more details how to reproduce the issue?
