### ISSUE TITLE
[mqtt][homeassistant] Create some ComponentSensors as trigger channels

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab-addons#6878]
Hi @jochen314!

I would like to suggest if we could map some Home Assistant sensors to trigger channels. For example, zigbee2mqtt maps some buttons presses as "click" and "action" sensors (defined by their objectIDs: "click" and "action"). We can not know beforehand what type of values they will send (click, double, triple, long, release, rotate...), so it is impossible to assign them a DefaultSystemTrigger channel, but at least we can define them as trigger channels so that they can be used in rules without defining them as items. The framework states that this type of "click" events should not be modeled as items, because they are stateless. 

I have been digging in the source code and I'm afraid I'm not sure how to achieve this in the best way. The ComponentSensor class can easily determine the objectID of the component (```componentConfiguration.getHaID().objectID```), but we don't have a TriggerValue class in the generic mqtt binding (and it doesn't make sense to create one, because the base Value.java class stores a state attribute, whereas trigger channels don't store any state). The whole process of building a channel: [buildChannel](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/ComponentSensor.java#L64) -> [CChannel.Builder](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java#L134) -> [build](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java#L186) uses the [Value](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.generic/src/main/java/org/openhab/binding/mqtt/generic/values/Value.java#L52) class. The [build](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java#L186) method does consider the option to create a [trigger channel](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java#L201), but for that the state_topic must be blank, which, for our case, is not realistic.

How can this be addressed? I can try to make a PR to implement this feature, but I would like to discuss it first to agree on the final solution :wink: 

@davidgraeff, what do you think about allowing the PublishTriggerChannel in the MQTT generic binding? Why is this type of channel only reserved for the broker thing and not to generic things?

Best regards,

Aitor

**Comment by jochen314** [comment]
The `ChannelConfigBuilder` supports `makeTrigger`. 
```
/** If true, the state topic will not update a state, but trigger a channel instead. */
```
Is this, what you are looking for?
We could set this flag from [build](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/CChannel.java#L197).
But what would be the trigger in `ComponentSensor`?

Another discussion would be to enable this flag for generic things. There we could add the trigger flag to the configuration.

**Comment by bodiroga** [comment]
> But what would be the trigger in `ComponentSensor`?

Ok, let's start from here. Zigbee2mqtt allows the integration of devices like [this](https://www.zigbee2mqtt.io/devices/E1744.html), [this](https://www.zigbee2mqtt.io/devices/E1743.html), [this](https://www.zigbee2mqtt.io/devices/WXKG01LM.html) or [this](https://www.zigbee2mqtt.io/devices/WXKG02LM.html). All this devices send their "button press" information using the "action" or "click" objectID of the sensor component. If we take the first one as a reference, this is the information published when Home Assistant compatibility is enabled in Z2M:

Topic: ```homeassistant/sensor/0x14b457fffe64eb68/action/config```
Payload: 
```json
{"icon":"mdi:gesture-double-tap","value_template":"{{ value_json.action }}","state_topic":"zigbee2mqtt/tradfri-music-controller-1","json_attributes_topic":"zigbee2mqtt/tradfri-music-controller-1","name":"tradfri-music-controller-1_action","unique_id":"0x14b457fffe64eb68_action_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x14b457fffe64eb68"],"name":"tradfri-music-controller-1","sw_version":"Zigbee2mqtt 1.9.0","model":"SYMFONISK sound controller (E1744)","manufacturer":"IKEA"},"availability_topic":"zigbee2mqtt/tradfri-music-controller-1/availability"}
```

This device sends the following information using the "action" key of the "zigbee2mqtt/tradfri-music-controller-1" topic:

- "play_pause" -> single click
- "skip_forward" -> double click
- "skip_backward" -> triple click
- "rotate_left" -> rotate the knob to the left 
- "rotate_right" -> rotate the knob to the right
- "rotate_stop" -> stop rotating the knob

Right know the binding offers this information through a state channel and the user can link it to a string item. What I propose is to replace the state channel with a trigger channel, so that users can avoid creating a meaningless item and use the event directly in a rule with:

```Channel "<triggerChannel>" triggered```

And the [receivedEvent](https://www.openhab.org/docs/configuration/rules-dsl.html#channel-based-triggers) will be: "play_pause", "skip_forward", "skip_backward", "rotate_left", "rotate_right" and "rotate_stop".

If this is clear, now to your other questions :wink: 

> Is this, what you are looking for?

Yeah, but I'm not sure what should we do with the rest of the attributes of the Builder, mainly the valueState. This channel won't have any Value (not OnOffValue, not StringValue, not NumberValue...) and that parameter is used a couple of times in the build method. I don't want to add a workaround and make the code uglier.

Thanks for your answer @jochen314 and for the job you are doing recently on the binding :+1:

**Comment by jochen314** [comment]
So, from the config: What indicates the trigger?
Any icon which starts with `mdi:gesture`?
There does not seem to be any information about which triggers are possible in the config.
And we will not create specific code do deal with special devices on top of HA. That would defeat the purpose of HA.

**Comment by bodiroga** [comment]
> So, from the config: What indicates the trigger?
> Any icon which starts with `mdi:gesture`?

Ummmm... my idea was to use the objectID "action" or "click" to handle this situation, not something defined in the /config topic (although you can consider the "value_json.action" and "value_json.click" as the clue to identify the logical flow). IMO, an "action" or "click" information is going to be always stateless, so there is no point in representing it with a state channel. Do you agree?

> There does not seem to be any information about which triggers are possible in the config.

You are right, that's why I propose to use the "state_topic" value (extracted using the "value_template", sure) as the received event. The trigger channel won't have any category nor already predefined values (it is not going to be a system trigger channel), it will just trigger without the need to define an item:

```
rule "Example rule"
when
    Channel "<triggerChannel>" triggered
then
    switch(receivedEvent.getEvent()) {
        case "play_pause": {
	    logInfo("Example","play_pause triggered")
        }		
	case "skip_forward": {
	    logInfo("Example","skip_forward triggered")
        }
        case "skip_backward": {
	    logInfo("Example","skip_backward triggered")
        }	
	case "rotate_left": {
            logInfo("Example","rotate_left triggered")
	}
        case "rotate_right": {
            logInfo("Example","rotate_right triggered")
	}
        case "rotate_stop": {
            logInfo("Example","rotate_stop triggered")
	}
    }
end
```

> And we will not create specific code do deal with special devices on top of HA. That would defeat the purpose of HA.

I don't know what you mean here, sorry :cry:

**Comment by jochen314** [comment]
Hi,

I do not think, that we will run into a problem, once we decide, that we want to use the channel as a trigger.

The problem is, deciding, that the channel is a trigger.
The discovery only has the information in the config-json available.
So any condition of the information in the config-json must trigger this decision.
- It cannot be the `uom`, as there are other devices around, that do not have a uom, which are not triggers.
- We will not maintain an explicit list of devices, which should be handled as triggers (so compare aains `name`, `device/name` or `device/model` is a no-go)
- I do not think, it makes sense to give the user a configuration option. Then what is the purpose of using autodiscovery. It is really, that HA should have such an option -- or a switch to homie should be considered.....
- The only option I see is to for the `icon` and identify all possible icon values, which indicate an action.
