### ISSUE TITLE
[digiplex] configure add-on using things configuration file.

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab-addons#6927]
Hello,

in digiplex addon for paradox alarm system it would be nice to configure zones and areas using things configuration file.

I expect to se something like this:
Bridge digiplex:bridge:bridge "prt3_bridge" @ "Paradox" [ port="/dev/ttyUSB0", baudrate=19200 ] {
             Thing area area1  "prt3_area1" @ "Paradox" [ area_id=1 ]
}

currently area_id is used as parameter, and not synchronized with configuration option.

Ed

**Comment by hmerk** [comment]
Closed due to inactivity
