### ISSUE TITLE
[tradfri]- Pre-Shared Security Key is not retrieved on Gateway Setup

### ISSUE THREAD

**Issue by kathagor** [openhab/openhab-addons#6928]
The pre-shared security key and the identity is not retrieved during initial gateway setup.

Gateway shows "Status: OFFLINE - CONFIGURATION_ERROR Either security code or identity and pre-shared key must be provided in the configuration!" after discovery.

After entering the security code the gateway shows "Status: OFFLINE - COMMUNICATION_ERROR Error connecting to gateway." and no key or identity is obtained

Running openhab version 2.5.0 and the gateway firmware is 1.10.29 (tested before with 1.10.27, same issue). Tested two gateways, same error. 

The connection to the IKEA app is working, if you scan the code. If you try to connect manualy with serial and code it does not work. Checked QR-code data and contains the same data.

**Comment by SebastianRumohr** [comment]
I have the same problem with OH version 3.1.0 and gateway firmware version 1.16.26.

**Comment by kathagor** [comment]
Hi, sorry for not answering.

Solved the the issue. I didn't get the letters I (capital i)  and l (lower case L) correct. They look exactly the same on the gateway.
