### ISSUE TITLE
Weird thing status updates on startup

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#693]
Adding a Z-Wave stick as a thing, I see the following log:

```
12:18:25.358 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:ad1f4a49' changed from UNINITIALIZED to INITIALIZING
12:18:25.359 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Connecting to serial port '/dev/ttyACM1'
12:18:25.363 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:ad1f4a49' changed from INITIALIZING to ONLINE
12:18:25.388 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Serial port is initialized
12:18:25.411 [INFO ] [ve.internal.protocol.ZWaveController] - Starting ZWave controller
12:18:25.412 [INFO ] [ve.internal.protocol.ZWaveController] - ZWave timeout is set to 5000ms. Soft reset is false.
12:18:25.445 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:ad1f4a49' changed from ONLINE to INITIALIZING
12:18:26.155 [INFO ] [smarthome.event.ItemAddedEvent      ] - Item 'zwave_serial_zstick_ad1f4a49' has been added.
12:18:26.498 [INFO ] [rthome.event.ItemThingLinkAddedEvent] - Link 'zwave_serial_zstick_ad1f4a49-zwave:serial_zstick:ad1f4a49' has been added.
12:18:26.824 [ERROR] [ve.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2.
java.lang.NullPointerException
    at org.openhab.binding.zwave.internal.protocol.SerialMessage.getMessageBuffer(SerialMessage.java:216)
    at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1035)
12:18:31.816 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
12:18:36.829 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 1 attempts left!
12:18:41.835 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
12:18:46.840 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Too many retries. Discarding message: Message: class = AddNodeToNetwork (0x4A), type = Request (0x00), payload = 05 
12:18:47.074 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
12:18:47.076 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 2: Node found
12:18:47.077 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 3: Node found
12:18:47.079 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
12:18:47.081 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
12:18:47.082 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
12:18:47.084 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 3
12:18:47.085 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
12:18:47.098 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:ad1f4a49' changed from INITIALIZING to ONLINE
```

First of all, the NPE looks like a bug and must be avoided.
Then, the status transitions are: INITIALIZING -> ONLINE -> INITIALIZING -> ONLINE
Note that a binding should never set the status to INITIALIZING itself; if should only switch to ONLINE once it is ready. So I would expect it to be INITIALIZING -> ONLINE only.

**Comment by cdjackson** [comment]
Welcome to Z-Wave :)

I’d need to see a debug log really to see what message it’s trying to process for the NPE...

**Comment by kaikreuzer** [comment]
> Welcome to Z-Wave :)

Thanks! It is indeed my first day that I really look into it (I hope I won't regret it ;-)). Already have it running on a RPi3 with HABmin - works pretty well (apart from the exceptions) :sunglasses: 

> I’d need to see a debug log really to see what message it’s trying to process for the NPE...

Can't a few null checks harden the code so that no NPE bubbles up?
Atm, my controller does not come online again because of https://github.com/openhab/openhab2-addons/issues/694 during its initialization, so I cannot reproduce the NPE from above right now...

**Comment by cdjackson** [comment]
> 
> Can't a few null checks harden the code so that no NPE bubbles up?
> 
Of course, but where? The binding is very big, and the question is what message was it processing that threw the exception. We have dozens of command classes, and each command class supports multiple commands, so there’s a huge place to look. In general, I agree that we should protect against NPE (etc), but if I’ve missed one, I need to know where to look :)

> Atm, my controller does not come online again because of #694 <https://github.com/openhab/openhab2-addons/issues/694> during its initialization, so I cannot reproduce the NPE from above right now…
> 

I’ll push a fix for this now.
>

**Comment by kaikreuzer** [comment]
Testing your update already.
This should also rather go directly to OFFLINE:
```
16:35:58.544 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Connecting to serial port '/dev/ttyACM1'
16:35:58.545 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:b0479706' changed from INITIALIZING to ONLINE
16:35:58.672 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:b0479706' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Serial Error: Port /dev/ttyACM1 does not exist
```

**Comment by kaikreuzer** [comment]
Trying to update the config with the correct port results in
```
16:39:29.512 [DEBUG] [io.rest.JSONResponse$ExceptionMapper] - exception during REST Handling
java.lang.NullPointerException
	at org.openhab.binding.zwave.handler.ZWaveControllerHandler.handleConfigurationUpdate(ZWaveControllerHandler.java:163)
	at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.updateConfiguration(ThingRegistryImpl.java:87)
```

**Comment by cdjackson** [comment]
> This should also rather go directly to OFFLINE:

Agreed - this is very strange. The only way the controller / bridge should be able to go online is after it has received data from the serial port! The protocol stack sends an event once it's received the initial packets, and it's this that should have been used to set the controller online... And yet the next line says it can't open the port, so that seems not possible... There's not two bindings running or something is there?

**Comment by cdjackson** [comment]
> Trying to update the config with the correct port

What UI are you using and what are you updating? Are you using PaperUI?

 It looks to me like you're trying to send a controller reset command, which throws an error as the controller isn't initialised. I'll add protection around this, but I suspect you are using PaperUI and we have a very big problem.

**Comment by cdjackson** [comment]
@kaikreuzer can you confirm the above please as if the above is correct and PaperUI is sending updates to all config even if it's not changed, then I urgently need to remove stuff from ZWave. Currently, I use config as actions as we discussed on the Forum a year or so back, and there are actions (for example) to hard reset the ZWave stick which would erase peoples networks (!!).

**Comment by kaikreuzer** [comment]
> What UI are you using and what are you updating? Are you using PaperUI?

Yes, I was using the Paper UI and I also saw in the log that this triggered commands...

> PaperUI is sending updates to all config even if it's not changed

Yes, I think it does - as it does not keep track itself of what has changed. Maybe this is something that should be enhanced in the Paper UI, but in general the binding should be able to cope with that situation.

> I use config as actions

I know, but I do not understand why they are triggered. Aren't the actions just text params that are normally empty (and thus ""/null will be sent on such an update) and which only should only react if there is some other content sent?

**Comment by cdjackson** [comment]
Currently, I assume that if I receive an 'action', that it has been sent by the user, and not just sent each time the any config data is updated. In this way, the binding knows that if it receives this 'command' that it needs to do something. Otherwise, it can be difficult to know if something is required.

I don't think your example of receiving a null works does it, because I assume that PaperUI, or other UIs that send all current config, will send the last value, and so detecting null, or 'something else' doesn't work. It might be possible for us to update the config on receive (ie in the handler) to something different than received, so that it would make the change detection more reliable, but I'm not sure it guarantees it.

In Z-Wave at least, the consequences of this incorrectly detecting change are 'quite bad' as it will hard reset the controller) so we need to make sure this can't be false triggered. I would prefer to have something that allowed the binding to receive a clear, concrete, unquestionable action.

I'll remove this from Z-Wave tonight, but we should look to resolve how to handle this quite soon I think as people are using these functions.

**Comment by kaikreuzer** [comment]
> I assume that PaperUI, or other UIs that send all current config, will send the last value

But it is up to the binding to actually accept and set this configuration in the Thing. So you could implement HABmin in a way that it sends "DO" or whatever, which will end up in your handleConfigurationUpdate method. In there you can trigger the action and simply not update the configuration - this way, you can be sure that the Paper UI will never ever send "GO" as a value, because it does not know about that at all.

**Comment by cdjackson** [comment]
True - I don't think this is 100% guaranteed, but it's probably good enough for now. The issue I see is it still relies on the binding receiving the "DO", but not saving it in the config. If that somehow gets bypassed, and DO gets stored in the config (eg the thing config being updated as a whole) then subsequent config updates may still cause problems. I guess I could also fix this by resetting these configs on startup - it just doesn't feel very nice, and probably prone to error.

I'll work on this basis for now as it's probably reasonably ok, but I think we should re-open this discussion. I don't think ZWave is the only binding doing this as others have asked me about how to get the action menu items into the tools menu in HABmin (MQQT comes to mind).

**Comment by kaikreuzer** [comment]
> but I think we should re-open this discussion

Agreed, sooner or later. Not one of the top prios right now I guess.

**Comment by cdjackson** [comment]
Kai, I'd propose to close this as the binding no longer uses the initialising state so the "weird thing status updates" should be a thing of the past...
