### ISSUE TITLE
[innogysmarthome] - Low Battery Message does not change Channel value

### ISSUE THREAD

**Issue by RalphSester** [openhab/openhab-addons#6932]
When a low-battery-message arrives from the api, the binding does not change the low-battery-channel of the thing.

## Expected Behavior
when a message arrives, the low-battery-channel of the device hast to be set to ON
after replacing batteries the channel has to be set to OFF

## Current Behavior
Nothing happens.
The fix #6920 prevents the bridge from going offline but does not handle the message correctly.

## Steps to Reproduce (for Bugs)
see issue #6918 

## Context
this functionality was correct in previous versions of this binding (new binding). i think it is implemented.

See the message from API in the debug-log:

```
07:11:37.527 [DEBUG] [ogysmarthome.internal.InnogyWebSocket] - innogy WebSocket onMessage() - {"sequenceNumber":24387,"type":"MessageCreated","desc":"/desc/device/SHCA.RWE/1.0/event/MessageCreated","namespace":"core.RWE","timestamp":"2020-01-29T06:11:37.4781910Z","source":"/device/00000000000000000000000000000000","data":{"id":"f27d414c87e946f8b183e08ddf0b99e5","class":"alert","type":"DeviceLowBattery","namespace":"CosipDevices.RWE","desc":"/desc/product/CosipDevices.RWE/1.0/message/DeviceLowBattery","source":"product/CosipDevices.RWE/1.0","timestamp":"2020-01-29T06:11:34.462995Z","devices":["/device/a4b910eaa5f94204b4cf3147da0ed82c"],"capabilities":[],"read":false,"state":true,"properties":{"deviceLocation":"Arbeitszimmer","deviceName":"Fernbedienung","deviceSerial":"******","locationName":"","serialNumber":"*****"}}}
07:11:37.529 [DEBUG] [.internal.handler.InnogyBridgeHandler] - Event no 24387 found. Type: MessageCreated
07:11:37.530 [DEBUG] [.internal.handler.InnogyBridgeHandler] - Message received event not yet implemented for Messagetype DeviceLowBattery.
```
@Hilbrand ....can take please a look again?

## Your Environment
OH 2.5.1 on Windows Server 2016

**Comment by RalphSester** [comment]
This bug is still existing. Is there no one, who can take an eye on this?

**Comment by RalphSester** [comment]
@mmans is this something you can check?

**Comment by mmans** [comment]
Hi @RalphSester!

Unfortunately I'm unable to test this myself. But what I see in the code is, that a message-object expects a "DeviceLinkList". However, the Json you provided (in your excellently filed bugreport) doesn't contain this field. Instead there is a "devices" field.

I simply renamed this in the code. So if you like you could test this. I don't know exactly if this can cause other parts to fail. But as far as I could see it doesn't. So maybe this very quick and completely untested fix works :) If not could you set the log-level to trace, test again and send me the logs?

Link to my repo: https://github.com/mmans/openhab-addons/tree/bugfix/6932
(I will send you a pre-compiles jar as E-Mail)

Ps. I'm happy to help out, but my time is very limiting at the moment. So it sometimes can take some time till I answer. Thx!

Greetz,
Marco

**Comment by RalphSester** [comment]
Hi @mmans ,

i have tested your pre-compiled jar in my environment - and the test was positive!
Many thanks for your great help. i think, its good, that this issue is fixed now!

Good job!

Ralph

**Comment by mmans** [comment]
Hi @RalphSester!

That sounds great! Thanks for the quick test!
I will create a PR so the fix will be merged in the main code. 

Greetz,
Marco
