### ISSUE TITLE
[mqtt.generic] (Re-)add support for formatBeforePublish for contact & switch types?

### ISSUE THREAD

**Issue by crnjan** [openhab/openhab-addons#6933]
Hi all!

Tried to setup a channel as bellow using latest release version (2.5.1):

```
...
Type switch:power [ stateTopic="ESP_Easy/MitsubishiHeatPump", transformationPattern="JSONPATH:$.power", commandTopic="ESP_Easy/MitsubishiHeatPump/cmd", formatBeforePublish="power,%s" ]
...
```

but seems as `switch` does not use the `formatBeforePublish` (anymore?). AFAIK this was supported before and seems to be changed [here](https://github.com/openhab/openhab-addons/pull/6755) a couple of days ago.

So the question is - is there a reason not to allow `formatBeforePublish` for `switch` type or can we allow/extend the binding and process format for `switch` type? 

Thanks in advance,
 Boris

**Comment by xdanik** [comment]
I am also reporting this problem.
```
Type switch : power "Power" [ stateTopic="nad/out/Main/Power", commandTopic="nad/in/Main/Power", on="On", off="Off", formatBeforePublish="=%s" ]
```
And the to the MQTT is published only "On" or "Off" but it should be prefixed with "=".
This setup was working (and still is - I tried downgrading) on openhab2 version 2.5.0-1.
