### ISSUE TITLE
[gpstracker] Always pass through region enter/leave events from OwnTracks 

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-addons#6939]
## Your Environment

* Version used: OH 2.5.1 Release
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): official Docker image
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): official Docker image

From the docs for the binding we have the following warning:

> If the binding was restarted only the second transition update will trigger event as the binding has to know the previous state.

Based on my observations that's not entirely correct and I don't understand why that has to be the case. Consider the behavior I saw yesterday.

I'm running OwnTracks (OT) on two phones and there are regions defined in both phones. I know the regions are working because OT shows I'm inside/outside at the proper times and I can see leave/enter events from OT (e.g. when my wife leaves home I see she left that region in an OW notification).

I was in a region named "work" and my wife's phone was not in any defined region. OH had to be restarted. At that point, despite the fact that OW was reporting enter and leave events, the regionTrigger Channel *never* triggers. No matter how many events occur the Channel will not trigger for my Thing until I manually (using curl) submit a JSON showing a leave event from Work. For my wife, I had to manually send another enter event for home.

Once that is done the Channel triggers as expected.

This feature request has two parts:

1. The docs should probably be updated with more information about this behavior. It isn't just that it will wait for the second event, once you enter a region the binding *must* receive the corresponding leave event or else it gets stuck. 

2. Why does it behave this way? It would be so much more helpful if it just passed through the events to the Channel trigger whether it misses one or not. The binding can't keep track of the last event but I sure can in Items and Rules. And I can write my Rules in such a way that it doesn't matter if I miss an event. As it is now, the regions defined in OT are effectively useless to me because I can't rely on it. If OH restarts there is a really good chance that the regionTrigger will become completely broken.

Failing that, just completely disable regions defined in OT (though that would make me sad, I really would rather define them in the apps instead of OH so I can more easily create and delete regions on the go) and only support those defined in OH.

**Comment by sheppy99** [comment]
Further information: When a region boundary is passed owntracks publishes 2 packets. The first one is similar to this:
     `{"t":"c","tst":1580270363,"acc":yyy.yyyyyyyyyyyyyy,"_type":"transition","event":"leave","lon":xxx.xxxxxxxxxxxxx,"lat":xxx.xxxxxxxxxxxxxx,"wtst":1462335808,"tid":"XX","desc":"airport"}
`

The second one is a standard update similar to this

`"cog":205,"batt":61,"lon":xxx.xxxxxxxxxxxxxxxxx"acc":24,"p":xx.xxxxxxxxxxxxxxxxxx"bs":2,"vel":0,"vac":50,"lat":yyy.yyyyyyyyyyyyyyyyy,"inregions":["airport"],"conn":"o","tst":1580269372,"tid":"XX","_type":"location","alt":134}'`
     
If the standard updates were used to update the binding it would then know which regions were active as they are listed in the message. I've confirmed with the authors of Owntracks that this is standard behaviour, and both messages are always sent when region boundaries are crossed

**Comment by gbicskei** [comment]
Hi,
I've made some changes to solve the issues above. 

- In case a location message is received it will trigger the channel if based on the the new calculated distance the state differs from the previous state (now this includes the NULL state as well). So after an OH restart the linked switch will be updated even after the first location message
- In case the message is a transition (e.g. configured in OT application) the trigger event is forced regardless on any previous states
BR
