### ISSUE TITLE
[darksky] thing is not updating / no data refresh

### ISSUE THREAD

**Issue by macmeck** [openhab/openhab-addons#6945]
I have set up and configured the binding and created things and items. The initial data load works just fine, so I think my setup is complete. But no matter what I choose for the update interval, data will never be refreshed. Also with setting the log to DEBUG for the bundle, the karaf console shows just nothing after the initial load. So it seems that the update will just never be triggered.

Any additional configuration required to make periodic updates work?

* Version used: openHAB and addon on 2.5.1
* Operating System and version: Raspbian Stretch

**Comment by cweitkamp** [comment]
Did you already ask in the [community forum](https://community.openhab.org/) for help?

It is really hard to help without knowing how you set-up looks like.

**Comment by macmeck** [comment]
It seems that the scheduling stuff in my openHAB instance got stuck when a zigbee thing did not properly finish its removal. To me, the other addons should not be concerned by something like that, but for now it just works for me.
