### ISSUE TITLE
missing POMs for dependencies

### ISSUE THREAD

**Issue by maggu2810** [openhab/openhab-addons#6960]
While playing around I run into an error complaining about a missing POM file for `com.leapmotion.leap:leap-java:jar:2.0.0`

The "openhab-addon XML feature" depends on "org.openhab.addons.bundles:org.openhab.binding.leapmotion:jar".
The leapmotion binding depends on "com.leapmotion.leap:leap-java:jar:2.0.0".
The JAR file can be found here: https://openhab.jfrog.io/openhab/libs-release/com/leapmotion/leap/leap-java/2.0.0/
The POM file for that file is missing.

**Comment by maggu2810** [comment]
Would it be possible to add that POM file?

**Comment by maggu2810** [comment]
Hm and the next one: com.github.cbornet.netatmo-swagger-api:netatmo-java-retrofit:jar:1.1.3

Have the POMs been skipped by intention?

**Comment by J-N-K** [comment]
The reason is that the pom was not available when I uploaded the jar. Those jars had been in the /lib directory before and the corresponding pom has never been added to our repo.

**Comment by Novanic** [comment]
> Hm and the next one: com.github.cbornet.netatmo-swagger-api:netatmo-java-retrofit:jar:1.1.3
> 
> Have the POMs been skipped by intention?

Hi, this gets solved with this pull-request (hopefully with 2.5.6): https://github.com/openhab/openhab-addons/pull/7807

**Comment by lolodomo** [comment]
@kaikreuzer : I guess the problem was solved by your merged PR. Issue to close ?

**Comment by kaikreuzer** [comment]
Yeah, I hope so.
