### ISSUE TITLE
[knx] Dimmer Type has UNDEF state after relativ dimming to 100%

### ISSUE THREAD

**Issue by mitch-geht-ab** [openhab/openhab-addons#6970]
Hello,

when I dim (relativ) my lights with a Gira Tastsendor Plus to 100% and release the button, the openhab dimmer item get the state "UNDEF".
It's no problem with dimming to 10, 33, 68 and so on percent. But if the state reachs 100%, I release the finger from the button and the item changes from 100 to UNDEF.

After reaching 100% and releasing the button I expected that the item state keeps 100%.

I've attached an ETS trace of the relevant GA's and some screenshots from ETS with further information of the GA.
Also an OH2 event.log of the corresponding dim event (from ETS).

Here are some ENV details:

```
# dpkg -l|grep openhab
ii  openhab2                             2.5.0-1                      all          openhab2
ii  openhab2-addons                      2.5.0-1                      all          openhab2-addons
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
# java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

My OH2 items, things ...

```
knx.things
Type dimmer : R05_Deckenleuchte-Essen_Dimmen "R.05 Deckenleuchte-Essen Dimmen" [ switch="1/2/17+1/2/18", position="1/2/20+<1/2/21", increaseDecrease="1/2/19" ]

knx_licht.items
Dimmer R05_Dimmer_Esszimmer "Esszimmer [%s]" (gR05, gLicht) { channel="knx:device:router1:generic:R05_Deckenleuchte-Essen_Dimmen" }

default.sitemap
Default item=R05_Dimmer_Esszimmer
```

Any help is appreciated.

BR
Mitch

**Comment by mitch-geht-ab** [comment]
![trace screenshot](https://user-images.githubusercontent.com/8008251/74004521-415ffe00-4976-11ea-80cc-5ae965d3e7ad.JPG)
![GA1-2-19](https://user-images.githubusercontent.com/8008251/74004522-41f89480-4976-11ea-85e9-dbfa9a06d836.JPG)
![GA1-2-21](https://user-images.githubusercontent.com/8008251/74004523-41f89480-4976-11ea-91cd-0a9a353de0dc.JPG)
[eventlog.txt](https://github.com/openhab/openhab-addons/files/4169196/eventlog.txt)
[ets-trace.zip](https://github.com/openhab/openhab-addons/files/4169197/ets-trace.zip)

**Comment by mitch-geht-ab** [comment]
Hi,
could it be, that this is the wrong repo for the knx binding issue?

BR
Mitch

**Comment by udo1toni** [comment]
No, I think it's the right place. I've never seen such an issue here, but I haven't linked the increaseDecrease GA at all. openHAB only needs this GA when using Classic UI, which I don't. Maybe try it without increaseDecrease parameter?

**Comment by mitch-geht-ab** [comment]
Yes, without Increase/Decrease it works. 
But the strange behaviour started with OH2.5.
Thought it would be great to have it fixed or same behaviour in all Versions.
Maybe someone is using +/- in the UI instead of Sliders with absoulut GAs

**Comment by vguna** [comment]
Hey guys,
I've got the same issue with OH 3.0.2 as it seems.

I started to add a KNX `Dimmer` to OH and played around with it as a slider on the OH UI.
For me it's getting UNDEF not only when going to 100%, but randomly after each change of the value. I'm also using relative dimming. I checked the KNX bus monitor, but there everything looks fine. The correct value is reported back into the status object on the bus - that I configured in OH like so:

```
Type dimmer         : Dimmer_Wohnzimmer_Wand                                [ switch="0/1/19+<0/1/20", increaseDecrease="0/1/17+<0/1/18", position="0/1/36+<0/1/18" ]
```
`0/1/18` is the status object with the current dimming position in percent.


What's a bit strange though is, once it got into UNDEF, triggering a read in the ETS on the bus for that GA shows the value on the bus, but in OH it's still UNDEF. Usually I can trigger such updates in OH when triggering a read from the bus like this.
Also what is maybe different is, that I enabled "feedback" on the physical dimmer configuration to report back every 10% of change. So there is not only one value reported back from the physical dimmer for one change, but the whole "steps" in between. Maybe that confuses the KNX binding (shot in the dark)?

So dropping `increaseDecrease` is the way to go? Is it not allowed to have it together with `position` maybe?

**Comment by vguna** [comment]
I can confirm, that removing `increaseDecrease` fixes the UNDEF. Now question remains, why they won't work together.

**Comment by J-N-K** [comment]
That's a bug. The reason is that the core-type mapper return UNDEF to represent "stop dimming". this is properly handled for dimmer-control channels, but not for dimmer channels.

**Comment by vguna** [comment]
Ah, ic. Thanks for figuring that out and providing the PR 😍!
