### ISSUE TITLE
[shelly] Invalid firmware warning with latest firmware installed [solved]

### ISSUE THREAD

**Issue by soleetions** [openhab/openhab-addons#6971]
## Expected Behavior
No warning because the firmware version is the most recent one

## Current Behavior
After installing a new Shelly 1 with the latest firmware, the following warning is thrown in the logs:

`14:43:53.372 [WARN ] [ly.internal.handler.ShellyBaseHandler] - shelly1-xxxxxxx: WARNING: Firmware might be too old (or beta release), installed: v1.5.10/20200206-083100 (e6a4205e), required minimal v1.5.2. The binding was tested with version 1.50+ only. Older versions might work, but do not support all features or show technical issues. Please consider upgrading to v1.5.0 or newer!
`

latest (and installed) version is 1.5.10 and the minimal should be 1.5.2

## Steps to Reproduce (for Bugs)

1. Install a shelly (1?) with the latest firmware
2. look at the logs

## Your Environment

* Version used: openHAB 2.5
* Operating System and version : Synology DSM 6

**Comment by markus7017** [comment]
will be included in PR #6985

**Comment by markus7017** [comment]
included in version 2.5.4
