### ISSUE TITLE
[Zwave] Thing stays Online even there was no Commnication for a long time

### ISSUE THREAD

**Issue by shorty707** [openhab/openhab-addons#6972]
Referring to:
https://community.openhab.org/t/zwave-thing-properties-to-item/92346/25

There are examples from device without battery for months.
so definately no nif, wakeup, or any communication for a long time.
still the time does not change to OFFLINE

**Comment by cdjackson** [comment]
I would suggest to close this and open an issue in the [ZWave binding issue list](https://github.com/openhab/org.openhab.binding.zwave/issues).
