### ISSUE TITLE
[daikin] Add Compressor Speed to Binding

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab-addons#6980]
I currently use the HTTP binding to access my Daikin AC and would like to eventually migrate to the Daikin Binding. To do this I need to have access to the compressor speed value cmpfreq from

>http://MyACipAddress/aircon/get_sensor_info

Can the binding be extended to include this parameter please

**Comment by psmedley** [comment]
Should be too difficult to add. Can you post the full output of:
http://MyACipAddress/aircon/get_sensor_info

This is one that isn't supported on the Australian Airbase modules, so I wouldn't be able to test...

**Comment by sheppy99** [comment]
Thanks for the reply, I’m across the ditch and  will provide the output in the morning

**Comment by sheppy99** [comment]
the output is

>ret=OK,htemp=25.0,hhum=-,otemp=17.0,err=0,cmpfreq=36

**Comment by LukasA83** [comment]
Same request, european device (Daikin stylish), attached is my output:
`ret=OK,htemp=26.0,hhum=35,otemp=11.0,err=0,cmpfreq=0`

Additionally my device is reporting humidity under "hhum" and not under "shum". Can this be added as well?

**Comment by jimtng** [comment]
> Additionally my device is reporting indoor humidity under "hhum".

Isn't this already supported? The channel name is "humidity"

**Comment by jimtng** [comment]
Two ways to implement this:
- Add a new channel "sensorinfo" that will contain the raw output of aircon/get_sensor_info, or
- Add a new channel called "cmpfreq" that will contain just the cmpfreq if available.

In the second case, what would be the ideal channel name? `compressorfreq`? Is "freq" = frequency?

**Comment by sheppy99** [comment]
CompressorFreq makes it obvious what it’s referring to. Adding the full sensor output would allow people to use additional sensor items as they inevitably become available in the future. If it’s not a lot of work I’d add both

**Comment by sheppy99** [comment]
Additional I’m not sure what the value of freq actually means. Mine seems to peak at 59 when it’s first turned on in powerful mode but it doesn’t often stay there for long. No doubt other units will behave differently

**Comment by jimtng** [comment]
I think it might be useful to add a `sensorinfo` channel, but not add a compressorfreq channel. Compressorfreq seems too esoteric / rarely used. One can always parse and extract the value from sensorinfo using a rule. @psmedley  what do you think?

**Comment by LukasA83** [comment]
I agree, full sensorinfo might be benefical. Humidity seems to be supported but the channel is not available for me in my AC Thing. Any advise?

**Comment by jimtng** [comment]
> Additional I’m not sure what the value of freq actually means. Mine seems to peak at just over 60 when it’s first turned on in powerful mode but it doesn’t often stay there for long.

What do you do with this data?

**Comment by sheppy99** [comment]
> What do you do with this data?

I use it as part of a rule that controls what temperature I send it. Left to its own devices the temperature control isn't that great due to the AC location so I steer it a bit using Infra Red commands based upon the measured temperature at my head end of the bedroom. I need to use Infra Red rather than the WiFi Api as Mold Guard, Quiet Fan and Powerful mode aren't available from the WiFi Api.

**Comment by jimtng** [comment]
> Humidity seems to be supported but the channel is not available for me in my AC Thing. Any advise?

@LukasA83 There's a humidity channel according to the documentation:
https://www.openhab.org/addons/bindings/daikin/#channels

@sheppy99 
> I need to use Infra Red rather than the WiFi Api as Mold Guard, Quiet Fan and Powerful mode aren't available from the WiFi Api.

Can you set your AC to each of those modes (mold guard, quiet fan, powerful mode), and on each setting, please post the result of `http://ipaddress/aircon/get_control_info`

Then please also change the mode using `http://ipaddress/aircon/set_control_info` and see if it works. For set_control_info you need to pass these values:

http://ipaddress/aircon/set_control_info?pow=1&mode=XX&f_rate=X&f_dir=X&s_temp=XX&shum=XX`

Just copy the values from what get_control_info gave you, except change the f_rate part (I think that's the part that changes to quiet fan, powerful, etc).

**Comment by jimtng** [comment]
@sheppy99 also please post the output of 
* `http://ipaddress/aircon/get_model_info`
* `http://ipaddress/common/basic_info`

**Comment by LukasA83** [comment]
Compressor Frequency has been added, issue can be closed

**Comment by sheppy99** [comment]
Where can I find a JAR of the latest version with compressor frequency added? I've updated to openHAB 2.5.5 Release Build and installed the binding using PAPERUI, compressor frequency is missing although its in the documentation.

**Comment by stickybyte** [comment]
Can someone pleas explain the cmpfrequency to me? What Unit will ist be?

**Comment by sheppy99** [comment]
@stickybyte  cmpfrequency is how fast the AC's compressor is running and its a measure of how hard its working. It isn't available on all models. I don't know what units it is measured in and I graphed mine for a while to get a feel for how high it goes. I use it on to tell my rule how hard its working and also I graph it
