### ISSUE TITLE
[homematic] HMIP Dimmer 101% Bug

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab-addons#6996]
**Expected Behavior**

I would expect 100% level in OH mapped to full brightness in HM.

**Current Behavior**

he range 0% - 99% in openHAB is mapped to 0% - 100% in Homematic. Thus, setting the light in 99% will result in full brightness of the dimmer (i.e. 100%) whereas setting the light to 100% in openHAB will translates to 101% and results in a rather dim light level

(see report from user 36grad here https://community.openhab.org/t/solved-homematic-ip-dimmer-is-read-only/85497/14 which i can reproduce. I could not find any report here yet)

Context
I use the HMIP Dimmer in HM access point, the binding is done to homematic:HmIP-BDT:a8faecaa:0008DA498E78FB:4#LEVEL ) Except that 100% bug it works fine.

**Comment by MHerbst** [comment]
Probably a duplicate of #6688

**Comment by 36grad** [comment]
Yep, agree it's the same issue as #6688.

**Comment by kohlsalem** [comment]
Well, so I say "upps".

Thank you @MHerbst for his superior searching skills, i close this one....
