### ISSUE TITLE
[miio] Add support for Mi Home PTX Wall Switches (090615.switch.xswitch03)

### ISSUE THREAD

**Issue by jimmym101** [openhab/openhab-addons#7000]
<a href="https://shopee.com.my/Xiaomi-Mijia-3-Gang-Wall-Smart-Switch-(WIFI)-PTX-switch-i.12651691.2538078325">Device Link</a>

Got most of it's features working in openhab using a combination of rules and commands (found through WIFI packet sniffing). It would be great to have it added to the binding for greater control.

<b>Keys For Stored Values: </b> (for use with get_prop)
switch1    -->   <i>Key for state of left switch</i>
switch2    -->   <i>Key for state of middle switch</i>
switch3    -->   <i>Key for state of right switch</i>
???????    -->   <i>Key for state of backlight. Didn't work this key out yet</i>
switchname1    -->   <i>Key for name of left switch</i>
switchname2    -->   <i>Key for name of middle switch</i>
switchname3    -->   <i>Key for name of right switch</i>
<i>n.b. get_prop '[""]' returns the state of switch1, switch2, switch3 and the backlight's state.
 
<b>Commands To Control:</b>
SetSwitch1 [1]    -->   <i>Turns on the left switch</i>
SetSwitch2 [0]    -->   <i>Turns off the middle switch</i>
SetSwitch3 [0]    -->   <i>Turns off the right switch</i>
SetSwitchAll [0,0,0]    -->   <i>Turns off all 3 switches</i>
SetBlacklight [0]    -->   <i>Turns off the backlight on the switch. <b>"Blacklight" is not a spelling mistake</b></i>
SetSwtichname1 ["TestName"]    -->   <i>Changes left switch's name to TestName. <b>"Swtich" is not a spelling mistake</b></i>
SetSwtichname2 ["TestName"]    -->   <i>Changes middle switch's name to TestName. <b>"Swtich" is not a spelling mistake</b></i>
SetSwtichname3 ["TestName"]    -->   <i>Changes right switch's name to TestName. <b>"Swtich" is not a spelling mistake</b></i>

<b>Debug Log Examples:</b>
2020-02-12 17:18:18.772 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":1458,"method":"SetSwtichname1","params":["Testing"]} -> 192.168.31.147 (Device: 0E20329C token: *** Queue: 1)
2020-02-12 17:18:19.036 [DEBUG] [internal.handler.MiIoAbstractHandler] - Received response for 0E20329C type: UNKNOWN, result: [0], fullresponse: {"id":1458,"result":[0]}

2020-02-12 17:29:45.419 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":1470,"method":"SetSwitchAll","params":[1,1,1]} -> 192.168.31.147 (Device: 0E20329C token: *** Queue: 1)
2020-02-12 17:29:45.680 [DEBUG] [internal.handler.MiIoAbstractHandler] - Received response for 0E20329C type: UNKNOWN, result: [1,1,1], fullresponse: {"id":1470,"result":[1,1,1]}

**Comment by marcelrv** [comment]
Would you mind trying to create a database file for your device.
see the https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.miio/src/main/resources/database for many examples.  I think adjusting an existing template already will bring you close.

You may need to wait until https://github.com/openhab/openhab-addons/pull/6693 is incorporated as than it is easy to edit and try locally.

**Comment by jimmym101** [comment]
Does this look alright? I've left out the control for the backlight until I work out what the key for that value is. Also I have the 1 switch and 2 switch versions of this device in the post so will update once they have arrived and I have had a chance to test them. 

{
    "deviceMapping": {
        "id": [
            "090615.switch.xswitch03"
        ],
        "channels": [
            {
                "property": "switch1",
                "friendlyName": "Switch 1",
                "channel": "switch1state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch1",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switch2",
                "friendlyName": "Switch 2",
                "channel": "switch2state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch2",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switch3",
                "friendlyName": "Switch 3",
                "channel": "switch3state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch3",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switchname1",
                "friendlyName": "Switch Name 1",
                "channel": "switch1name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname1",
						"parameterType": "STRING"
					}
                ]
            },
            {
                "property": "switchname2",
                "friendlyName": "Switch Name 2",
                "channel": "switch2name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname2",
						"parameterType": "STRING"
					}
                ]
            },
            {
                "property": "switchname3",
                "friendlyName": "Switch Name 3",
                "channel": "switch3name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname3",
						"parameterType": "STRING"
					}
                ]
            }
        ]
    }
}

**Comment by jimmym101** [comment]
{
    "deviceMapping": {
        "id": [
            "090615.switch.xswitch02"
        ],
        "channels": [
            {
                "property": "switch1",
                "friendlyName": "Switch 1",
                "channel": "switch1state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch1",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switch2",
                "friendlyName": "Switch 2",
                "channel": "switch2state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch2",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switchname1",
                "friendlyName": "Switch Name 1",
                "channel": "switch1name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname1",
						"parameterType": "STRING"
					}
                ]
            },
            {
                "property": "switchname2",
                "friendlyName": "Switch Name 2",
                "channel": "switch2name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname2",
						"parameterType": "STRING"
					}
                ]
            }
        ]
    }
}

**Comment by jimmym101** [comment]
{
    "deviceMapping": {
        "id": [
            "090615.switch.xswitch01"
        ],
        "channels": [
            {
                "property": "switch1",
                "friendlyName": "Switch 1",
                "channel": "switch1state",
                "type": "Switch",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwitch1",
						"parameterType": "ONOFFBOOL"
					}
                ]
            },
            {
                "property": "switchname1",
                "friendlyName": "Switch Name 1",
                "channel": "switch1name",
                "type": "String",
                "refresh": true,
                "ChannelGroup": "actions",
                "actions": [
                    {
						"command": "SetSwtichname1",
						"parameterType": "STRING"
					}
                ]
            }
        ]
    }
}

**Comment by jimmym101** [comment]
Above is the data for the database files for these three devices (090615.switch.xswitch01, 090615.switch.xswitch02 & 090615.switch.xswitch03).

**Comment by jimmym101** [comment]
@marcelrv I have finally tested out the json data using MIIO's new local database feature. Had to make a few changes to the json for it to work but all seems ok now (updated the json data above).

Do you have any experience with xiaomi devices only acknowledging the first parameter when using get_prop? For the local database to work I had to set  "maxProperties": 1, because the additional parameters where being ignored and only the value for the first parameter was being returned in the response. Have read that this is a firmware problem, so potentially nothing can be done until a firmware update is released for these switches.

Finally I had to change the "type" to "Number" and then use sitemap mappings to create a switch, because these light switches send and receive "0" or "1", depending on the state. Do you have a suggestion for a better type and parameterType for these kind of devices. 

Thanks and great work on the local database update, great to be able to test locally.

**Comment by marcelrv** [comment]
Cool, I'll include these in the upcoming PR
