### ISSUE TITLE
Binding to host and control openHAB things as Mozilla WebThings

### ISSUE THREAD

**Issue by svensven94** [openhab/openhab-addons#7009]
I am currently developing a binding to host openHAB things as WebThings (https://iot.mozilla.org/wot/#web-thing-description) so that they are accessible by other applications - mostly the Mozilla Gateway (https://iot.mozilla.org/).

Furthermore, the binding enables controlling openHAB things via the Gateway and should later be able to control external WebThings via openHAB too.

Currently only selected cases are supported and some major issues still exist.

Work in progress code can be found here: https://github.com/svensven94/openhab-addons/tree/webthings/bundles/org.openhab.binding.webthings

_edit_: switched link to correct repo branch

**Comment by kaikreuzer** [comment]
Hi @svensven94, great that you are working on this!

Just a note, though: Exposing openHAB in a WoT-compatible way should be done as a so-called ["system-integration" add-on](https://www.openhab.org/addons/#io) (or "IO add-on"), NOT as a binding.
The other feature that you mention that might come later (discovering and using WoT-devices for use within openHAB) would then indeed be a binding.
Please make sure to keep those two aspects separate as they fulfull very different use cases.

**Comment by svensven94** [comment]
Thank you for the feedback, @kaikreuzer!

Unfortunately, there seems to be no documentation about IO add-on development (https://www.openhab.org/docs/developer/ioservices/). 

All existing system integrations also appear to be rather complicated, except for the JavaSound one. From what I have seen these add-ons use service components instead of things? Is there any documentation where I can read up on this?

**Comment by kaikreuzer** [comment]
You are right, there isn't any documentation on how to implement IO add-ons.
Best advice I can give is to take a look at the existing ones like https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.io.homekit.

> From what I have seen these add-ons use service components instead of things?

Yes, that's correct. As a general guideline: IO add-ons operate on Item (and not Things) level and they expose items to external systems in the format the external system expects it. E.g. Homekit exposes existing items as Homekit-compatible devices.

For the implementation that means that you should use the `ItemRegistry` to see what is there and potentially define your own metadata namespace for WoT, so that users can add WoT-specific metadata to their item definitions (similar to how [users do it for Alexa](https://www.openhab.org/docs/ecosystem/alexa/#single-endpoint)), which can then be read through the `ItemRegistry`.

**Comment by sebastiankb** [comment]
+1 for this initiative to expose openHAB in a W3C Web of Things compatible way by an add-on

However, I would suggest to follow the official W3C Thing Description specification that you can find [here](https://www.w3.org/TR/wot-thing-description/). 

@svensven94 are you still working on that? Do you need some help?

**Comment by svensven94** [comment]
I just pushed to latest update to my fork. 

AFAIK the Mozilla WebThing Description ["is intended to complement the current W3C [...] data model [...] by defining a simple concrete serialisation"](https://iot.mozilla.org/wot/). 

If we ignore the IO Addon/Binding problem for now, the binding currently uses WebThings with properties following either the Boolean, Integer, Number or StringSchema to represent openHAB things. Right now, it works with "NoSecurityScheme" and "BearerSecurityScheme". 

The actual conversion can be found in the [OpenhabtoWebThingConverter](https://github.com/svensven94/openhab-addons/blob/webthings/bundles/org.openhab.binding.webthings/src/main/java/org/openhab/binding/webthings/internal/converters/OpenhabToWebThingConverter.java) class. Supporting more parts of the W3C Thing Description _should_ be pretty straight forward. 

This is a university project for me and it is uncertain for now, whether I will have the time to create a system-integration add-on out of it, but I know that my department is highly interested in doing/supporting that. If anyone wants to start developing the IO add-on, I am willing to help/contribute. A possible implementation could e.g. use a dummy group items for each WoT thing and define the security scheme and/or server port via an annotation for the group. Each item of the group represents a property/action/event for which the data scheme is again chosen via annotation. 

Except for that I would appreciate help with adding the webthing dependency internally via a "lib" folder ([see here](https://www.openhab.org/docs/developer/buildsystem.html#adding-dependencies)) which i was unable to do.

Furthermore I am open to create a binding which only implements the WoT -> openHAB part, if this is desired by the maintainers/community (@kaikreuzer). The functionality for that is implemented now (including a dicovery service). For manually adding things, the user has to provide a link to the WebThing as well as relevant security information. Afterwards the openHAB thing is updated and generates a channel for each property of the chosen WebThing. Information is exchanged via a websocket which is also able to reconnect in case of a connection loss. This should work for Mozilla WebThings as well as general WoT things using the above mentioned schemes (for details see [WebThingToOpenhabConverter](https://github.com/svensven94/openhab-addons/blob/webthings/bundles/org.openhab.binding.webthings/src/main/java/org/openhab/binding/webthings/internal/converters/WebThingToOpenhabConverter.java) class).

**Comment by kaikreuzer** [comment]
> Furthermore I am open to create a binding which only implements the WoT -> openHAB part, if this is desired by the maintainers/community (@kaikreuzer)

If this is what you have been working on so far, this is certainly welcome as a contribution. An IO add-on can be developed independently and there is no need to have it done at once.

**Comment by svensven94** [comment]
I created a new [branch](https://github.com/svensven94/openhab-addons/tree/webthings_barebones/bundles/org.openhab.binding.webthings) in my fork for the discussed binding (only containing the WoT-> openHAB part).

I have been testing the feature in my own openHAB instance the last few weeks and except for one issue (cannot update the location of the WebThing) it works really well for me. 

I will try to find more testers and fix the bug and I guess the next step afterwards is a pull request for the branch?

**Comment by kaikreuzer** [comment]
You should create the PR as early as possible, even while you are still working on it - you can create it as a "work-in-progress" PR. This gives reviewers a chance to have a look early on and maybe provide input before you claim that you are done (and then are frustrated in case you are asked for some refactorings).

**Comment by hmerk** [comment]
@svensven94 Are you still working on this or should we close this issue?

**Comment by hmerk** [comment]
Closed due to inactivity
