### ISSUE TITLE
[mqtt] Homie $retained = false causes channel linking fail

### ISSUE THREAD

**Issue by michaelfung** [openhab/openhab-addons#7011]
## Expected Behavior

Using Paper UI,  should be able to link items to channels.

## Current Behavior

When try to link item, the "Select a profile" drop down and "Type" drop down are blank. That makes linking impossible.

## Steps to Reproduce (for Bugs)

Set the $retained property attribute to false. In the example below, you can link "Relay state" but not "Skip next schedule"

```
[Feb 15 14:28:03.446] init.js:35              Published:OK topic:homie/1581ca/$state msg:init
[Feb 15 14:28:03.484] init.js:35              Published:OK topic:homie/1581ca/$homie msg:4.0.0
[Feb 15 14:28:03.524] init.js:35              Published:OK topic:homie/1581ca/$name msg:Sonoff Basic (Homie Edition)
[Feb 15 14:28:03.562] init.js:35              Published:OK topic:homie/1581ca/$extensions msg:
[Feb 15 14:28:03.601] init.js:35              Published:OK topic:homie/1581ca/$nodes msg:relay,system
[Feb 15 14:28:03.640] init.js:35              Published:OK topic:homie/1581ca/relay/$name msg:relay
[Feb 15 14:28:03.679] init.js:35              Published:OK topic:homie/1581ca/relay/$type msg:on/off
[Feb 15 14:28:03.720] init.js:35              Published:OK topic:homie/1581ca/relay/$properties msg:state,skip,ensch,oncount
[Feb 15 14:28:03.760] init.js:35              Published:OK topic:homie/1581ca/relay/state/$name msg:Relay state
[Feb 15 14:28:03.800] init.js:35              Published:OK topic:homie/1581ca/relay/state/$datatype msg:boolean
[Feb 15 14:28:03.839] init.js:35              Published:OK topic:homie/1581ca/relay/state/$settable msg:true
[Feb 15 14:28:03.879] init.js:35              Published:OK topic:homie/1581ca/relay/state/$retained msg:true
[Feb 15 14:28:03.919] init.js:35              Published:OK topic:homie/1581ca/relay/skip/$name msg:Skip next schedule
[Feb 15 14:28:03.958] init.js:35              Published:OK topic:homie/1581ca/relay/skip/$datatype msg:boolean
[Feb 15 14:28:03.998] init.js:35              Published:OK topic:homie/1581ca/relay/skip/$settable msg:true
[Feb 15 14:28:04.037] init.js:35              Published:OK topic:homie/1581ca/relay/skip/$retained msg:false
```

 ## Your Environment
* Version used: 2.5.1-2 (Release Build)
* Env: openhabian on Rpi4 board

**Comment by jochen314** [comment]
Currently, non retained properties are mapped to triggers.
But only attributes with all of the following format values are mapped to predefined triggers:
- SYSTEM_RAWBUTTON
-- PRESSED
-- RELEASED
- SYSTEM_BUTTON
-- SHORT_PRESSED
-- LONG_PRESSED
-- DOUBLE_PRESSED
- SYSTEM_RAWROCKER
-- DIR1_PRESSED
-- DIR1_RELEASED
-- DIR2_PRESSED
-- DIR2_RELEASED

**Comment by michaelfung** [comment]
I see. That means, for controlling a power switch, in order to prevent unexpected power ON in certain cases, the firmware should require a timestamp for ON/OFF command.

Case example: OH crashed, but the MQTT server is still functioning.

**Comment by michaelfung** [comment]
Thanks! I overlooked the docs. I should use MQTT clean connection = false instead of $retained = false for my case.
