### ISSUE TITLE
[melcloud] HANDLER_INITIALIZING_ERROR in Thing after reboot

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#7014]
## Expected Behavior
After a reboot, all devices configured using this binding are usable and in "ONLINE" state.

## Current Behavior
I currently have two devices connected with this binding. After reboot, one of them is in "ONLINE" state and the other is in "UNINITIALIZED - HANDLER_INITIALIZING_ERROR" state.

The following error message is given in the Thing details:
`org.openhab.binding.melcloud.internal.handler.MelCloudAccountHandler cannot be cast to org.openhab.binding.melcloud.internal.handler.MelCloudAccountHandler`

## Workaround
Workaround: Clicking "Disable Thing" and then "Enable Thing" sets it to "ONLINE" state. But it is a bit cumbersome to have to do this after every reboot.

## Your Environment
* Version used: openHAB 2.5.1, Addon 2.5.1
* Operating System and version: Openhabian, current as of 2020-02-15.

**Comment by paulianttila** [comment]
@eikowagenknecht, could you provide full logs? For me this smell more oh core problem rather than binding issue. Could you also give output from command `bundle:list` in karaf console

**Comment by eikowagenknecht** [comment]
Of course. I rebooted the system and attached the logs that were written in this timespan (cleaned of some obviously unrelated entries and some private data).

[openhab_cleaned.log](https://github.com/openhab/openhab-addons/files/4209626/openhab_cleaned.log)
[events_cleaned.log](https://github.com/openhab/openhab-addons/files/4209630/events_cleaned.log)

bundle:list output:

[bundle_list.txt](https://github.com/openhab/openhab-addons/files/4209635/bundle_list.txt)

It seems there were multiple versions of the binding installed. I uninstalled the older one and after a clean-cache the error seems to have disappeared.
