### ISSUE TITLE
Husqvarna Automower Connect

### ISSUE THREAD

**Issue by pompel82** [openhab/openhab-addons#7022]
Feature request: Using the Automower Connect API it should be possible to create a binding to control the Husqvarna Automower from OpenHAB.

https://developer.1689.cloud/apis/Automower+Connect+API#/readme

**Comment by EjvindHald** [comment]
Yes, I agree that would be really nice. I guess the challenge is to find a person who can and is motivated do this + at the same time own a Husqvarna Automower. The models supporting this are a bit expensive.

**Comment by clown-m** [comment]
Yes i would appreciate this as well, i own a Husqvarna Mower Model 315 with a connect modul, but my JAV knowledge not existing, but i am willing to work as a tester

**Comment by majogross** [comment]
I would also appreciate this binding. I will get one in the next days and I could also do some beta testing.

**Comment by Jensilein** [comment]
I would also appreciate such binding very much. Would like to contribute for beta testing too.

**Comment by giterest** [comment]
I'd be highly interested, too and available for testing!

**Comment by giterest** [comment]
Hi guys, just wanted to tell you that I started binding development today. Will keep you updated!

**Comment by giterest** [comment]
Hi guys, I started development - but, to be honest, I neither have Java knowledge, nor do I have the time to get used to openHAB's binding-framework. I decided to stick with a PHP-based approach, what already works is to retrieve the necessary tokens and communication /w the Husqvarna APIs.

**Comment by airix1** [comment]
Would it make sense to combine this with the Gardena binding since it shares the husqvarna authentication for the API?

**Comment by hmerk** [comment]
Closed as there is an automower binding available

**Comment by jlaur** [comment]
Closed again after linking to PR.
