### ISSUE TITLE
[hue] Unexpected Behaviour in Basic UI with Hue Items and auto-update 

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#7039]
## Expected Behavior
If i am going to press a switch or a dimmer in the basic ui, the state should change to my decision directly. Also the switch should represent changes of connected devices in the basic ui.

## Current Behavior
The User changes the state of an item in the basic ui. The change is been undo by the openhab server and after the physical item change and the changed state is reported to openhab back the change is then shown in the basic ui. If i am going to describe it in steps, this is how it happens:

0. Base state of item: OFF
1. User wants to turn ON the item
2. User clicks on switch, which switches the item ON
2a. (openhab sends the change to the physical thing)
2b. (openhab detects the current state of the physical item - which is still OFF)
2c. (openhab switches the item back OFF)
3. The physical things switches ON
4. The change is represent in the basic ui and the item is switched ON.

Here is also a shot clip which shows this issue:
https://www.youtube.com/watch?v=r377Pu2vIYw

This also happes for a lot of other sitemap items connected to my hue bridge.

Please keep in mind that the steps 2a through 2c are just educated guesses based on my experience.

## Possible Solution
Don't know

## Steps to Reproduce (for Bugs)
In my opinion this should happen to every hue binding user. If i am wrong, i am will gladly provide my config which is a copy of the examples from the hue binding.

## Context
This is also an annoyance and i am not able to explain this issues to my family.

## Your Environment
I am using the latest openhab docker image from the official openhab repository on docker hub (https://hub.docker.com/r/openhab/openhab/).
By the time of writing this should be version 2.5.1. I am using a philips hue bridge (FW: 1937045000) with standard philips hue e27 bulbs with latest firmware (FW: 1.46.13_r26312) and a hue dimmer switch with current firmware (FW: 6.1.1.28573). The openhab docker image runs on unraid 6.8.2 however i thing this shouldn't matter. The latest chrome version for windows and android. This also happens in the openhab android app so i don't think this is related to the gui.

I also created a topic in the openhab forum about this:
https://community.openhab.org/t/unexpected-sitemap-behaviour-switch-resets-itself-and-gets-updated-a-few-seconds-later-hue-binding-video-included/83478/2

Since october i did a complete fresh install of 2.4 on docker and a complete fresh install of 2.5 in docker. This issue was first seen on a openhab 2.4 installation inside an ubuntu vm on esxi more than 12 months ago.

If it turns out, that this is related to a bug and not a configuration issue, than i will gladly add a bounty to this issue.

**Comment by regnets** [comment]
I had a second look at the topic on the forum:
@Rossko57 had an idea whats wrong:
"That’s the odd part; autoupdate is messing up the prediction.

Similar story: https://community.openhab.org/t/what-is-itemstatepredictedevent/52387/6"

**Comment by lolodomo** [comment]
This is similar to the discussion I had in issue #7326 .
In fact, it could happen in case the polling job runs just after you sent your command but before the physical light state iis updated.
It should not happen very often, I did a lot of tests when implementing the group feature and never encountered this problem.
Of course, more your refresh interval is small, more you have the chance to encounter it.
But change of state by the hue bridge is fast in general so the risk should be very low. Or maybe your bridge is not so fast because you have a lot of hue lights.
PS: take care of the sensors refresh interval too.

**Comment by lolodomo** [comment]
Maybe the binding should bypass any polling when it occurs just after a command. But how much time we should consider a polling is reasonable after a command ?

**Comment by DerOetzi** [comment]
This happens to me very often, especially for my groups of 4 light dimmer channels. The faders are really jumping. But I have lowest possible pollingInterval of 1s to be "live". So I will give it a try to double the interval. Or check even higher intervals.

**Comment by lolodomo** [comment]
I can try to bypass a new light poll in case it runs during the next second after a light command. It could help. I have myself the default interval, 10 seconds, so this probably explains why I did not notice this behaviour.

**Comment by DerOetzi** [comment]
I didn't work with Scheduler beside basic functionality. Maybe it would be a possibility to reschedule the polling on each command. But this affect all lights, which I think is not a good solution. In my opinion it would be better to block only the single light, so maybe a timestamp of last command which will be checked before accepting a new polling update?

**Comment by lolodomo** [comment]
Please try with the jar in the PR. The polling will be frozen/bypassed in case it occurs during the second following a light command.

**Comment by lolodomo** [comment]
The light commands are sent asynchronously and one by one (using a queue). Maybe we should just bypass the light poll if it occurs before we got the feedback from the bridge.
As soon as the bridge answered to the command, maybe getting the light states will be reliable.
I will trace how much time it takes to get the answer from the bridge.

**Comment by lolodomo** [comment]
Without queuing several commands (and with a sensors polling disabled), I measure a response time from the bridge between 44 and 80 ms. It is fast.

But if you send several commands to different lights at the same time, as there are queued, this response time could increase for certain commands.

**Comment by lolodomo** [comment]
Maybe just bypassing a light poll while a light command is still in progress could be sufficient ?

**Comment by regnets** [comment]
I see that issue with every change of hue light in openhab. 

However, it is terrible if I using predefined (custom in openhab) "Scenes". Theses are states for rooms which can be selected with a selection in the openhab ui and trigger for example this rule:

```
rule "Beleuchtung: Wohnzimmer Szene wurde geaendert"
when
	Item Openhab_Wohnzimmer_Szene received command
then
	switch(receivedCommand) {
		case 0: {
			Zigbee_Wohnzimmer_Schalter.sendCommand(OFF)
		}
		case 1: { 
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(75)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(75)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(75)
			Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(1)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(100)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(100)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(100)
		}
		case 2: {
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(75)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(100)
                        Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(50)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(75)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(75)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(75)
		}
		case 3: {
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(66)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(66)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(66)
			Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(66)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(75)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(75)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(75)
		}
		case 4: {
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(100)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(50)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(50)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(50)
		}
		case 5: {
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(0)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(25)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(25)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(25)
		}
		case 6: {
			Zigbee_Wohnzimmer_Leseleuchte_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Sideboard_Dimmer.sendCommand(100)
			Zigbee_Wohnzimmer_Decke_Dimmer.sendCommand(0)
			
			Zigbee_Wohnzimmer_Leseleuchte_Farbtemperatur.sendCommand(0)
			Zigbee_Wohnzimmer_Indirekte_Beleuchtung_Farbtemperatur.sendCommand(0)
			Zigbee_Wohnzimmer_Sideboard_Farbtemperatur.sendCommand(0)
		}
	}
end
```

Just to give you an idea: All items beginning with "Zigbee_Wohnzimmer_Decke_*" are groups and containing five hue lights and the same goes for "Zigbee_Wohnzimmer_Sideboard_*" which contains two lights. For example case 6 has 13 individual commands for hue lights. This now can be knocked down to seven due to the groups support, however this is still too much and it takes arround 5 seconds before the openhab basic ui has the same state as the phyiscal lamps.

**Comment by lolodomo** [comment]
Ok, first it is possible that the handling of a command sent to an openHAB group takes some little time to be sent to all members of the openHAB group. I cannot accelerate that.

Then with 13 hue commands sent to hue lights more or less at the same time, you are very probably in the case where the binding is queeing your commands. Considering an average of 60 ms per command, it could take around 780 ms to run the 13 commands.

My PR with a bypass of 1 second should already help, I guess, but in theory I should consider not the time the command was enqueued but the time it was run. Unfortunately, it is not obvious to do.

First, you should try without using openHAB groups (rather send a command to each item) to check if my PR resolves the issue.
Then check with your openHAB groups.

**Comment by lolodomo** [comment]
PR #7518 fixed this issue.
