### ISSUE TITLE
[philipsair] Add CoAP Support for new Philips Air Purifier Firmware Versions

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#7040]
## Your Environment
I got a Philips Hue Air Purifier AC3259/10. Normally this device is supported by the philips air binding. However based on my research i found out, that they are moving their firmware to a CoAP based approach. 

You can find the more information about this in the following issue
https://github.com/rgerganov/py-air-control/issues/21

I don't think we do need to do the same research as the guys over at py-air-control, however we should follow up this issue, so that the findings can be implemented in the openhab binding.

**Comment by michalboronski** [comment]
Hi @regnets ,
True, let's follow up this issue at py-air-control where the discussion as well overall support for Philips Air purifires protocol has been reversed engineered.

**Comment by regnets** [comment]
It seems like they got this working with some specific pyhton library version:
https://github.com/rgerganov/py-air-control/issues/35

**Comment by regnets** [comment]
Hi Michalboronski,

i think the issue is now solved, have a look at this:
https://github.com/rgerganov/py-air-control/issues/21#event-3491469848

Cheers

**Comment by WookieeCookiee** [comment]
Hi all,
are there plans on integrating the coap support into the OH binding? That'd be awesome!

**Comment by lolodomo** [comment]
This binding is apparently not yet in openhab github.
