### ISSUE TITLE
[exec] Whitelist not loaded at startup

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab-addons#7047]
As reported in multiple community threads, when the system or the exec binding starts, the whitelist is not loaded.

It will not be loaded until the file is modified and the modification is saved.
This appears to be because there is no code implemented to load the file UNLESS it is modified.

The block below is the only place I've been able to find that actually reads the contents of the whitelist file:

````
@Override
    protected void processWatchEvent(@Nullable WatchEvent<?> event,  WatchEvent.@Nullable Kind<?> kind, @Nullable Path path) {
        if (path.endsWith(COMMAND_WHITELIST_FILE)) {
            commandWhitelist.clear();
            try  {
                Files.lines(path).forEach(commandWhitelist::add);
                logger.debug("Updated command whitelist: {}", commandWhitelist);
            } catch (IOException e) {
                logger.warn("Cannot read whitelist file, exec binding commands won't be processed: {}", e.getMessage());
            }
        }
    }
````

## Expected Behavior
Whitelist file's contents should be loaded at startup.

## Current Behavior
Whitelist file's contents are not loaded at startup.

## Possible Solution
Remove the whitelist "functionality".

**Comment by J-N-K** [comment]
Removing the whitelist is not the way to go. Instead it should be read in startup. I‘ll fix that ASAP.
