### ISSUE TITLE
[Homematic] ACTUAL_TEMPERATURE no longer updated after update to 2.5.2

### ISSUE THREAD

**Issue by Aquariusquintini** [openhab/openhab-addons#7053]
Since the update to OpenHab 2.5.2 on rPi 3+, the ACTUAL_TEMPERATURE channels of my  HmIP-WTH-2 and HmIP-eTRV-B devices are no longer updating. Some old value is read from the database, and it never changes afterwards. I did not find any errors in the logs.
I tried to recreate the channel links, change the things and recreate the things, nothing worked. All other channels of the devices are updating properly.

How can I get it working again?

**Comment by MHerbst** [comment]
How did you define the items? Via Paper UI or text file?
If you have used text files, please try to change the definition to `Number:Temperature` and try again.

If it does not work please set the log level to TRACE for the Homematic and post the trace output.

**Comment by sidamos** [comment]
Same thing here. Defined in PaperUI. Changing from Dimensionless to Temperature and restart of openHAB fixed it.

**Comment by Aquariusquintini** [comment]
> How did you define the items? Via Paper UI or text file?
> If you have used text files, please try to change the definition to `Number:Temperature` and try again.
> 
> If it does not work please set the log level to TRACE for the Homematic and post the trace output.
> 
> Probably related to the fix for this issue: #6102

I used PaperUI. Changing the definition to Number:Temperature did fix the problem.
