### ISSUE TITLE
[nuki] Bridge Callback not working

### ISSUE THREAD

**Issue by djmguli** [openhab/openhab-addons#7061]
I have an issue with the openHAB [nuki] binding and bridge callbacks.
Although having the binding set up like the documentation one by one, callbacks do not work. 

When sending a command to the bridge like "lock door now", the status gets updatet to "locking" but never results in the final state "locked".
Screenshot of set up and errors: 
1) https://ibb.co/k5Vbgwc
2) https://ibb.co/rb4SnhX
3) https://ibb.co/sJ7b6k5
4) https://ibb.co/WnKSggT

In comparison the the binding, i also tried the manual JSON API from Nuki, where the state works. But i don't want to use the manual JSON API because it constantly draws battery from my Smartlock because it does not work with callbacks.
Screenshot: https://ibb.co/TRvXMCG

Thank you for your help!

**Comment by jtreml** [comment]
Seems the Nuki add-on is quite broken at the moment.
Callbacks seem not to be interpreted correctly at all.
Nuki bridge seems to send them correctly, e.g. final state 'locked', but the add-on doesn't handle things correctly it seems.

Maybe some recent bridge API changes broke the add-on?

**Comment by jtreml** [comment]
At least for my case, I've identified the issue:
Callback are both being sent by the Nuki bridge and received by the Nuki binding, but the latter responds with a `404 - smart lock not found' 

Reasons seems to  be this line of code here
https://github.com/openhab/openhab-addons/blob/127f05d7cbb865ae2f7a939c761707f0479d5143/bundles/org.openhab.binding.nuki/src/main/java/org/openhab/binding/nuki/internal/dataexchange/NukiApiServlet.java#L128
which expects 8-digit IDs for the smart lock.

Turns out, my smart lock has a 9-digit ID.
I guess that's what's changed. Numbers just got bigger.

**Comment by jtreml** [comment]
@Hilbrand @wborn Any chance you could have a look at this?

**Comment by wborn** [comment]
Maybe @mkatter can help with this.

**Comment by mkatter** [comment]
@jtreml I really doubt that your Nuki ID is 9 digits. Please double check and confirm. 
Also, please do a `log:set TRACE org.openhab.binding.nuki` in karaf console and share the anonymized log file.

Thanks & BR Markus

**Comment by jtreml** [comment]
@mkatter You're absolutely right. The missing piece was "back side of the Smart Lock". I hadn't seen those instructions and got the ID from the API, which indeed uses decimal format.
In short, I put the decimal ID in my thing configuration and that caused the 'smartlock not found' on the callback as it would take that as a hex ID and do an unnecessary transform on it.

Two things didn't help, though:

**Comment by djmguli** [comment]
@mkatter:
**I can also confirm with the 8-digit HEX. Working now!**
The Smart Lock sticker on the inside of the housing says the correct and needed 8-digit-HEX ("1BC1234D" example).

But the Nuki Binding instruction for example says, that you should get the Nuki-ID via Nuki API call, which is wrong in my opinion. It says:

> The ID of the Nuki Smart Lock. Get it through the Bridge HTTP-API (https://nuki.io/en/api/), Endpoint */list*.

But looking at the API via _http://YOURIP:8080/list?token=123456_ results in a JSON which says a 9-digit number. With this code, like @jtreml says, the Smart Lock actions work, but the callback does not. That's a little bit confusing ...
