### ISSUE TITLE
[homekit] - startHomekitServer method - extra logging required

### ISSUE THREAD

**Issue by gpr7700** [openhab/openhab-addons#7062]
## Environment
Raspberry 4 - 4 Gb
HypriotOS
openHAB 2.5.1 in docker

Hello,
I'm try to migrate my running instance of OH to docker and I'm having issue with the homekit bundle.

In order to investigate more easily why the bridge is not exposed, it could be helpful that the method startHomekitServer  logs the resolution of the networkInterface setting to the IP address. 

set TRACE level for :
log:set TRACE org.openhab.io.homekit
log:set TRACE io.github.hapjava - (readme file not up to date)

only shows trace such as
16:44:32.182 [DEBUG] [kit.internal.HomekitAccessoryRegistry] - Added accessory 
16:44:32.249 [INFO ] [io.github.hapjava.HomekitRoot        ] - Added accessory Salle de bain

but nothing about the HomekitServer being started nor the IP address used

regards

Gregory

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
