### ISSUE TITLE
[exec] commands are no longer whitelisted after reboot

### ISSUE THREAD

**Issue by dwrobel** [openhab/openhab-addons#7067]
Despite that command is whitelisted openhab2 refuses to execute it after reboot saying:
```
[WARN ] [ng.exec.internal.handler.ExecHandler] - Tried to execute '/usr/bin/uptime', but it is not contained in whitelist.
```
List of whitelisted commands:

```
$ sudo -u openhab cat /etc/openhab2/misc/exec.whitelist 
/usr/bin/uptime
/usr/bin/date
/usr/bin/sudo /usr/sbin/reboot
/usr/bin/sudo /usr/sbin/poweroff
```
Interestingly, to make it working it's enough to either modify the file by appending e.g. `/usr/bin/foo` or
by changing the timestamp:
```
# touch /etc/openhab2/misc/exec.whitelist
```
Then it starts to work fine till next reboot.

## Expected Behavior
Commands should be whitelisted permanently as per content of the /etc/openhab2/misc/exec.whitelist file.

## Current Behavior
Commands are no longer whitelisted after reboot.

## Possible Solution _(workaround)_
Modify the content or timestamp of the exec.whitelist file.

## Your Environment
Hardware: RPi4 4GB
Software: FedoraServer 31
```
$ rpm -qv openhab2 openhab2-addons java-1.8.0-openjdk-aarch32-headless
openhab2-2.5.2-1.noarch
openhab2-addons-2.5.2-1.noarch
java-1.8.0-openjdk-aarch32-headless-1.8.0.232.b09-1.fc31.armv7hl
```

**Comment by J-N-K** [comment]
Already fixed by #7049
