### ISSUE TITLE
[meteoblue] Wind speed using wrong units

### ISSUE THREAD

**Issue by gstiegl** [openhab/openhab-addons#7077]
Wind speed is calculated with the wrong unit. See more at [https://community.openhab.org/t/wrong-wind-speed-value-in-meteoblue-add-on-unit-confusion/93654](url)

**Comment by 9037568** [comment]
This comes close to being the worst defect report ever written.

**Comment by gstiegl** [comment]
> This comes close to being the worst defect report ever written.

I vow to to do better next time. Hope that it was useful nevertheless.
