### ISSUE TITLE
[alarmdecoder] OH2 migration of alarmdecoder binding

### ISSUE THREAD

**Issue by bobadair** [openhab/openhab-addons#7081]
Hi. Has anyone been working on, or planning to work on,  a OH2/OH3 version of the OH1 alarmdecoder binding? If not, a friend and I have been working on an OH2 port that we’d be happy to contribute once it is ready. It’s actually pretty far along already, with working ipbridge, serialbridge, keypad, zone, rfzone, and LRR things. It also provides some limited discovery functionality (of zones/RF zones) and some bridge thing actions. The main functionality that still has yet to be added is support for sending keypad commands and emulated virtual zone commands.

I don’t want to step on any toes if the original contributors, who I believe are @berndpfrommer and @LuckyMallari are planning their own OH2 port. But we’d be happy to contribute the code if they’re not.

**Comment by LuckyMallari** [comment]
Haven't had time to take a look but if you guys have done some work already, then it's better than starting from scratch. The only critical part is keeping it from having major breaking changes so that the transition for end users will seem transparent, considering this is an alarm/security binding.

**Comment by berndpfrommer** [comment]
@bobadair , by all means go for it! I don't have any time to work on the binding :(

**Comment by bobadair** [comment]
Ok. Cool. I'll probably be able to create a WIP PR for it within the next week or two. I'll reference this issue in it so that they'll be linked.

**Comment by bobadair** [comment]
The build of the current PR is available here:
https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.alarmdecoder/2.5.3-SNAPSHOT/org.openhab.binding.alarmdecoder-2.5.3-SNAPSHOT.jar
