### ISSUE TITLE
[deconz] Motion sensors dark state is not updated correctly

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#7088]
## Expected Behavior
Motion sensors dark state is update when boolean in api-response changed channel state should be updated

## Current Behavior
Channel is not updated:
`{"config":{"alert":"none","battery":60,"delay":600,"duration":12,"group":"22703","on":true,"reachable":true},"ep":1,"etag":"1ebc212a05cc7d70239a61b8ea8fb541","manufacturername":"IKEA of Sweden","modelid":"TRADFRI motion sensor","name":"Flur EG Hinten","state":{**"dark":true**,"lastupdated":"2020-03-02T06:24:38","presence":false},"swversion":"1.2.214","type":"ZHAPresence","uniqueid":"00:0d:6f:ff:fe:07:c9:3f-01-0006"}`

itemstate dunkelheitFlurEGHinten = OFF

## Possible Solution
I hadn't the time to have a closer look on the implementation but I noticed a different handling for example between presence channel and dark channel which are both Boolean states maybe this could be the problem

presence-channel is updated like:
`case CHANNEL_PRESENCE:
                if (presence != null) {
                    updateState(channelUID, OnOffType.from(presence));
                }
                break;`

dark-channel is updated like:
`case CHANNEL_DARK:
                updateState(channelUID, Boolean.TRUE.equals(newState.dark) ? OnOffType.ON : OnOffType.OFF);
                break;`

I don't know the OnOffType.from logic but maybe it is different from Boolean.TRUE.equals

## Steps to Reproduce (for Bugs)
Wait for statechange in deconz-api and have a look whether the channel is updated 

## Context
I wan't to start different lightning rules with the information

## Your Environment
* Version used: openhab and deconz-binding 2.5.2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Docker on Raspbian

**Comment by J-N-K** [comment]
Is this still the case with the latest version? If so, please provide a TRACE level log of a state change. Thanks.

**Comment by J-N-K** [comment]
Solved after refcatoring, not channels are treated the same now.
