### ISSUE TITLE
[insteon] add support for related parameter to the broadcastOnOff channel

### ISSUE THREAD

**Issue by mfedotov** [openhab/openhab-addons#7089]
Based on documentation my expectation of the 'related' keyword for a Scene is to make a priority update of the status of the related items (items that are part of the Scene). My testing of Insteon 2.5.3.202003020123 plugin indicates that this is not a case, and the related items are updated according to the regular polling cycle

Thing definition:

```
   Thing device Scenes "Insteon Scenes" [address="4F.4F.77", productKey="0x000045"] {
      Channels:
        Type switch : broadcastOnOff#88    [related="23.E7.1C+3C.68.12"]
   }

```

Event Logs:

> 2020-03-02 13:46:21.507 [ome.event.ItemCommandEvent] - Item 'Scene_Dusk' received command ON
> 2020-03-02 13:46:21.508 [nt.ItemStatePredictedEvent] - Scene_Dusk predicted to become ON
> 2020-03-02 13:47:01.984 [vent.ItemStateChangedEvent] - Backyard_Light changed from 0 to 19
> 2020-03-02 13:47:51.488 [vent.ItemStateChangedEvent] - Porch_Light changed from OFF to ON
> 2020-03-02 13:48:38.694 [ome.event.ItemCommandEvent] - Item 'Scene_Dusk' received command OFF
> 2020-03-02 13:48:38.695 [nt.ItemStatePredictedEvent] - Scene_Dusk predicted to become OFF
> 2020-03-02 13:48:38.697 [vent.ItemStateChangedEvent] - Scene_Dusk changed from ON to OFF
> 2020-03-02 13:52:01.464 [vent.ItemStateChangedEvent] - Backyard_Light changed from 19 to 0
> 2020-03-02 13:52:51.969 [vent.ItemStateChangedEvent] - Porch_Light changed from ON to OFF
> 2020-03-02 13:54:22.596 [ome.event.ItemCommandEvent] - Item 'Scene_Dusk' received command ON
> 2020-03-02 13:54:22.596 [nt.ItemStatePredictedEvent] - Scene_Dusk predicted to become ON
> 2020-03-02 13:54:22.600 [vent.ItemStateChangedEvent] - Scene_Dusk changed from OFF to ON
> 2020-03-02 13:57:01.463 [vent.ItemStateChangedEvent] - Backyard_Light changed from 0 to 19
> 2020-03-02 13:57:51.973 [vent.ItemStateChangedEvent] - Porch_Light changed from OFF to ON
> 
>

**Comment by robnielsen** [comment]
Per the documentation, related only works for switch and dimmer channels.  Once https://github.com/openhab/openhab-addons/pull/6911  is merged, I will add support of related for the broadcastOnOff channel.
