### ISSUE TITLE
Zwave ScheduledExecutorService is null

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#709]
Hey @cdjackson , I'm completely stumped on this one,  I'm getting a NPE at line 90 here:
https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveApplicationStatusClass.java#L90

Unless something is failing when the class is instantiated and being swallowed by the JVM, I can't see how the executor can be null, but sure enough if I add the following check, it logs that its nulll, creates a new one and everything works

```
if (scheduler == null) {
    logger.debug("NODE {}: scheduler was null, creating new one");
    scheduler = Executors.newScheduledThreadPool(1);
}
```

Do you have any ideas?

**Comment by cdjackson** [comment]
Not really...

However, a few random thoughts...

Firstly, is creating the scheduler as part of the class instantiation a good idea? It means we do this even if it's not needed - and it's only used in one response case. I don't know how often this happens (I don't think I've got any devices using this class) so I don't know how big a deal this is (probably not much in reality!).

Second, and more 'interestingly' - I'm wondering if we should have a more general 'deferred poll' class somewhere (or method in the controller - or something...). Somewhere there's an issue about doing a poll 'some amount of time' after a command class is updated. Maybe a general service to do this might be useful?

I guess my point here is that if you're looking to fix this issue, maybe we should rethink this slightly? What do you think?

**Comment by digitaldan** [comment]
Totally agree, my first thought was to try and somehow get access to the Thing Handlers ScheduledExecutorService since ESH is trying to keep the amount of these down.  I didn't see a 2 min fix so I left it alone ;-) I'll play around a little today (long flight) and report back.

**Comment by cdjackson** [comment]
One option might be to use an event to notify the thing handler which can then schedule the update? The thing handler already receives event about other changes, so can already support the delayed poll. If we added a ‘device is busy, call back later’ event, then we could handle all this in the thing handler - it might be cleaner?

Enjoy the flight :)

**Comment by digitaldan** [comment]
That's a great idea, I'll start there, thanks.   In flight Wifi is a wonderful thing ;-)

**Comment by cdjackson** [comment]
Dan - I propose we close this now as this code has now been changed to better support polling. Is that ok with you?

**Comment by digitaldan** [comment]
Yep
