### ISSUE TITLE
[homekit] - docker - HomeKitServer - HomekitRoot constructor with JmdnsHomekitAdvertiser never called

### ISSUE THREAD

**Issue by gpr7700** [openhab/openhab-addons#7097]
**Environment**
raspberry 4
hypriotOS
openhab in docker
AVAHI active reflector enabled (enable-reflector=yes - /etc/avahi/avahi-daemon.conf)
**Issue**
The bridge (_hap._tcp) is never advertised when specifying the host container ip address.
With container ip address bridge is advertised.

When looking at the code (HAP-java) it seems that HomeKitServer (createBridge) never calls the HomekitRoot constructor that takes the JmdnsHomekitAdvertiser instance. Therefore the bridge is not advertised and you have no logs at all to investigate why something is going wrong.

Regards

Gregory

https://github.com/hap-java/HAP-Java/issues/100#issue-573274217

**Comment by yfre** [comment]
closing as external bug https://github.com/hap-java/HAP-Java/issues/100#issue-573274217 is closed as well
