### ISSUE TITLE
[tado] Manual setting of away/home officially supported

### ISSUE THREAD

**Issue by Timtam** [openhab/openhab-addons#7114]
## Your Environment

* Version used: openHAB 2.5.2 release
* Environment name and version: openHAB on iOS, Chrome 80 and more, but rather unimportant for this request I assume
* Operating System and version: openHABian (latest)

## Feature request

Tado just recently pushed a new beta version via Testflight which allows to manually set Away/Home mode without requiring a device to be out of home/at home. As far as I can see in the link below, it should already be possible to read the current away state and also set it as long as at least one device is not at home. I didn't validate this, but I assume the API will reflect those changes by allowing to always set the state to home/away. It would be great to have support for this in the already available tado° binding for openHAB2.
See the API here: https://shkspr.mobi/blog/2019/02/tado-api-guide-updated-for-2019/

Thanks.

**Comment by andrewfg** [comment]
Question: as a result of https://github.com/openhab/openhab-addons/pull/8868 can this issue now be closed?

**Comment by andrewfg** [comment]
Closed by #8868
