### ISSUE TITLE
[lgwebos] State of Power channel not updated when first linked in Paper UI

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7118]
After linking the channel "Power" in Paper UI, its state is not set to ON even if the TV is ON and the thing is ONLINE.

**Comment by sprehn** [comment]
Issue is two fold:
binding currently still overrides channelLinked and does not call super.channelLinked which by default calls 
`      handleCommand(channelUID, RefreshType.REFRESH);
`
Also, the channel handlers have to be adapted to handle the REFRESH command

**Comment by lolodomo** [comment]
Yes, you're right, that would be better ideally to handle the `REFRESH` command.

If not, we could simply add few lines of code in `channelLinked` to handle the specifc case of this channel.
All the other channels are working because the subscription leads to a channel state update. At least this is true for volume, mute, channel, application. I have not yet tested the Player channel.

**Comment by sprehn** [comment]
player channel has no status that can be retrieved
