### ISSUE TITLE
Link is down 

### ISSUE THREAD

**Issue by Arut42** [openhab/openhab-addons#7121]
https://github.com/openhab/openhab-addons/tree/master/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW

page: openhab-addons/bundles/org.openhab.binding.nibeheatpump/

**Comment by wborn** [comment]
Eventually the link will work again when it's merged into the master branch again.

You can find it here:
https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW

Seems to be an issue for just a few links:

```
$ grep -R https://github.com/openhab/openhab-addons/tree/master
bundles/org.openhab.binding.miele/README.md:The definition of the channels in use can best be checked in the [source repository](https://github.com/openhab/openhab-addons/tree/master/bundles/org.openhab.binding.miele/src/main/resources/ESH-INF/thing).
bundles/org.openhab.binding.nibeheatpump/README.md:Arduino code is available [here](https://github.com/openhab/openhab-addons/tree/master/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/Arduino/NibeGW).
bundles/org.openhab.binding.nibeheatpump/README.md:C code is available [here](https://github.com/openhab/openhab-addons/tree/master/bundles/org.openhab.binding.nibeheatpump/contrib/NibeGW/RasPi).
```

**Comment by Arut42** [comment]
I already tried yesterday.

many thanks 
this one works
