### ISSUE TITLE
[avmfritz] AVM Fritz!DECT 500 and Magenta Smart Bulbs not discovered (7.19-labor)

### ISSUE THREAD

**Issue by Marlow925** [openhab/openhab-addons#7135]
Hi,
with 7.19-labor (BETA) of the AVM Fritz!Box firmware, these routers now support smart bulbs that either are offered by themselves (not available yet) or from other vendors, namingly Telekom Magenta.

Unfortunately these bulbs are not discovered as items, even though they work properly within the AVM eco-system. 

Is there any plan or work ongoing to get these added ?

I am running OpenHAB 2.5.2 and have 9 full color spectrum bulbs of these, so I can provide data/assistance, if needed. It would be great to be able to control them from OpenHAB.

I have no knowledge of Java coding, so I'd be quite useless on that end.

**Comment by cweitkamp** [comment]
As long as there is no proper documentation available for the [AHA-HTTP-Interface](https://avm.de/service/schnittstellen/) it will be quite hard to add support for new devices.

We can try to reverse engineere it by enabling DEBUG / TRACE logging for the binding (`org.opehab.binding.avmfritz`) and see what we will get in the response. Unfortunately I do not own such devices.

**Comment by Marlow925** [comment]
I can try and pull the debug data tonight or tomorrow. It would be nice to at least do basic things like report the lights are on/off and switch them on and off. 

I guess the issue is also, that the code still is changing..

**Comment by Marlow925** [comment]
It's been a while, as I've been very busy. I have emailed you a trace of the bulb being switch on and off.

I would also be willing to send you a bulb (to keep), if this would help getting support added for these.

You can send me your postal address as reply to the email.

**Comment by Diapolo** [comment]
If the not just have a quick press department, but also a quick development department, the documentation is now likely available?

https://avm.de/presse/presseinformationen/2020/07/ab-sofort-verfuegbar-led-lampe-fritzdect-500-und-vierfach-taster-fritzdect-440/

**Comment by cweitkamp** [comment]
Yes, a new version of the [documentation](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf) is available. I already have access to a FRITZ!DECT 500 bulb (and its equivalent SmartHome Telekom LED-Lampe) but did not find the time to work an it. Additionally I got contact to someone who wants to provide a FRITZ!DECT 440 switch for me for integration. So we maybe will see some results soon.

**Comment by jwsp1** [comment]
Any update on this issue?
Happy to help testing, when implemented :)

**Comment by cweitkamp** [comment]
Thanks for the reminder. I have to admit that I completely forget about this. Too much to do for OH3 and RL. I cannot promise a lot but I will try too look into it before christmas.

**Comment by shadoxxhd** [comment]
Any updates? Or will we have to wait until next christmas?

**Comment by tunichgud** [comment]
Hi, implemented a first throw on this in https://github.com/openhab/openhab-addons/pull/9757. I was able to auto discover my light bulb and turn it off and on.
