### ISSUE TITLE
Selection mapping to mqtt issue

### ISSUE THREAD

**Issue by marsic-84** [openhab/openhab-addons#7139]
I have a setup:

**Sitemap file:**

```
sitemap demo label="ROOM31"
{
   Frame {
        Text label="WLED-WS2812" icon="rgb"{
            Selection item=wled_FX   icon="line" mappings=[0="Solid", 1="Blink",2="Breathe",3="Wipe"]
        }
    }
}

```

**Items file:**
`Number wled_FX  "FX"  {channel="mqtt:topic:wled:W_Effect"}`

**Things file:**

```
Thing mqtt:topic:wled "Wled" (mqtt:broker:689cb32c)
	{
    Channels:  
       Type number  : W_Effect    "WLED Effect" [ commandTopic="wled/80da2c/api" ]   
	}
```

*openHAB 2.5.2 Release Build*

When I use selection tool in basicUI it should send "0" or "1" or "2" or "3"
 to MQTT Broker  "wled/80da2c/api" topic.
BUT!!! I receive in broker "0.000000" or "1.000000" or "2.000000" or "3.000000"

Tell me plz is it an issue, or it just i did something wrong?
...No errors in logs and with *openHAB 2.5.0 Release Build* was OK.

**Comment by MaxMlchrt** [comment]
Did you solve the problem yet?
It also appears when i use rules:
`example.sendCommand(1)`

**Comment by MaexProjects** [comment]
Did you solve the problem?
I also have the issue, when sending a command within a rule.
However when I use the "switch"-item and set up the ON/OFF-value in "things", it converts it correctly.

**Comment by jochen314** [comment]
It is a bug.
I created a PR for it.

In the meantime you can use the `formatBeforePublish`:

```
Thing mqtt:topic:wled "Wled" (mqtt:broker:bfdc3ee8)
    {
    Channels:  
       Type number  : W_Effect    "WLED Effect" [ commandTopic="wled/80da2c/api", formatBeforePublish="%d"]   
    }
```

**Comment by MaexProjects** [comment]
https://community.openhab.org/t/95272/
