### ISSUE TITLE
[deconz] Manually added Switch in Paper UI is broken

### ISSUE THREAD

**Issue by bkadykalo** [openhab/openhab-addons#7144]
Manually added Deconz switches in Paper UI are basically broken.

## Expected Behavior
I can specify custom UID for Deconz switches.

## Current Behavior
In Paper UI I manually added Deconz switch with Thing ID `ikea_remote3`. Generated UID is incorrect: ```deconz:switch:ikea_remote3```

In contrast, automatically discovered/added switch is correctly setup, with UID like ```deconz:switch:deconz:xxxxxxxxxxxxxxxxxxxx``` 
I believe thing UID gets generated following this pattern: ```[binding]:[thing_type]:[bridge_id]:[thing_id]```. Given we select the bridge when adding a thing, UID should include bridge id automatically. This is a bug.

As a workaround, I specified `deconz:ikea_remote3` in the Thing ID field. and created device works well.

## Possible Solution
Fix Paper UI and/or add missing information on the binding page:
- rule to form thing UID
- temporary workaround for Paper UI

## Your Environment
* openHAB 2.5.2
* Synology, Docker

**Comment by nougad** [comment]
I'm adding an item using config files but still the paperui discovery showing the same item again. Typically if an item id is added in config paperui will not discover it again. I can even add a item with the same id twice. Once via config and afterwards via paperui discovery. I already cleaned all discovery results but still same result. I'm wondering if that's related to this bug.

**Comment by J-N-K** [comment]
PaperUI is removed in OH3.
