### ISSUE TITLE
[onewire] switch to uncached reading for *IO Device* DS2406_DS2413 (other IO Devices already do)

### ISSUE THREAD

**Issue by Urmel** [openhab/openhab-addons#7148]
For response time critical applications, I would like to read data from 1W bus explicitely via the uncached path. I do not want to change the whole owserver timeout-setting, as I only need this feature for a sub set of sensors (for me, reed / dio; temperature can stay with standard time outs).

There is no config for a channel or a thing where I can set this option.
Trying to put "uncached" in the sensor ID (as a workaround) fails due to format testing of the sensorid.

Most granular, one could set the uncached option per channel. This should result in adding another path element in the queried path.

**Comment by Urmel** [comment]
Hi all,

first of all, I'm new to this - first approach to doing binding stuff for openHAB.... so excuse any strange assumptions or alike... ;)

I dug a bit into the topic and created a first testeable (it runs and works :)) version of a patch to configure uncached reads.

## Approach

My approach was to make it _configureable on the channel level_. This would in general correspond to the scope of the OwserverDeviceParameter instances used.

For the AbstractDigitalOwDevice, there are ways to read more than one channel. In general represented by the fullInParam and fullOutParam. I set these to uncached as soon as one of the channels is in uncached config.

In order to get things in line between AbstractDigitalOwDevice and its inheriting classes, I adapted the OwserverDeviceParameter to allow for updating the prefix.

## Questions

A few questions pop up...
- This feature seems to be located best in the channel configuration of the device class, but the most general one (AbstractOwDevice) has an abstract method. I did a first shot at AbstractDigitalOwDevice only (as that's where I personally need it). **Any thoughts on whether / how to broaden to the non-digitalIO-devices?**
- DS2405 and DS2408 seem to perfom uncached reads for input in general - **should we change that back to cached per default?**
- I was able to update the OwserverDeviceParameterTest, but the device specific test classes are tricky. Is it **possible with these to check config versus used prefix when reading the value** (which indirectly would also check whether fullInParam and fullOutParam are built correctly)?

Thanks in advance for any feedback!
Alex

**Comment by Urmel** [comment]
Hi @J-N-K , maybe you can give a short statement on this. That would be next on my todo list... Thanks.

**Comment by Urmel** [comment]
As this might only be relevant for IO devices which reflect e.g. the open state of a window (few people might care to update their humidity data every 2 seconds...), I changes the title to specificly only address these.
The binding furthermore already supports uncached reads for 2 of the 3 supported IO devices. So only the DS2406_DS2413 is missing.

**Comment by J-N-K** [comment]
That may be mistake then. All digital I/O should be uncached, so fixing that is highly appreciated.
