### ISSUE TITLE
[paradoxalarm] Not properly working Paradox Alarm System binding

### ISSUE THREAD

**Issue by mnmn2** [openhab/openhab-addons#7154]
I have installed the latest openhab2, with the latest Paradox addon.
When I start the things discovery, only the Partitions can bee seen.
But none of them came "Online" ever.
The most boring issue is, that most of the properties of the Partitions can not get linked to Items.
"String" and "Number" types are working (first character is upper-case), but there are properties like "contact" and "switch" (lower-case first character).
These can not be added as Item, Paper UI says: "Some error occured".
In the logs I can see, that the add method was rejected because an "invalid type" was used.
Lower case first character in the property-type is not working.
Of course in Paper UI I can not correct the "contact" to "Contact", so I can't make Items.

I think the Partitions should come "Online", but in my case they are offline.
(The main Paradox thing is Online).

I made several attempts with the things discovery, but still only the Partitions can bee seen.

I checked the openhab log, and realized, that it finds my first Zone also, but there is an exception, because it containes some Hungarian spec. character. 
I renamed the Zones to basic ASCII chars, and they came in my Inbox.
All of them "Offline".
And of course, most of their properties can not be linked to Items, because the lower-case first letter in their type.
 
Should I switch to "separate" PAI with MQTT solution?

Or can these issues get fixed?

(Or am I the only person, having these problems?)

Thanks a lot in advance,
Norbert

**Comment by lsiepel** [comment]
@mnmn2 this is an old issue from OH2. Could you verify if this is still an issue for OH4? If not, please close this issue, or if you need advice on setup, i would suggest to post in the community forums.

**Comment by theater** [comment]
I would suggest closing the issue, as there were many fixes in the mean time and obviously the author is not interested in providing new feedback.

**Comment by lsiepel** [comment]
@theater fyi when stale bot marks it as stale, it will be auto closed after 3 months, in this case 2nd januari

**Comment by theater** [comment]
> @theater fyi when stale bot marks it as stale, it will be auto closed after 3 months, in this case 2nd januari

Thanks. I was wondering why it did not get auto-closed already. Was going over my bindings labels to check if any new issues yesterday and noticed this one. It's for closure anyway... :)
