### ISSUE TITLE
[mqtt] usability request - dimmer menu option

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#7166]
Usability enhancement request. Version 2.5

When using PaperUI to configure a channel, the type drop-down selector offers a "Percentage type"

It is not clear that refers to the type commonly called "dimmer" everywhere else in openHAB.
Once created, the channel type is shown as "dimmer" type.

Suggestion to rename this menu selection to "Percentage (dimmer) type" or similar.

screenshot of user view
https://community.openhab.org/t/solved-esp8285-wifi-rgb-with-ir-tasmota-not-working-with-correct-colors-on-openhab2/94391/27

**Comment by jimtng** [comment]
Is this still an issue in 3.x? As I'm not familiar with MainUI (I use .things and .items files) could you please provide steps to see this on the UI? This sounds like a simple edit / change in the xml file.

**Comment by digitlength** [comment]
> could you please provide steps to see this on the UI?

Create a new Generic MQTT Thing.
Once saved, move to the Channels tab for the new Thing, and click Add Channel. You then get the following options - Percentage instead of Dimmer.

![Screenshot_20220129-223803](https://user-images.githubusercontent.com/62958838/151679820-e1365f33-d476-431b-b5ec-e9376b4e1a66.png)

**Comment by jimtng** [comment]
What should it be renamed to?
A. Dimmer
B. Dimmer (Percentage)
C. Dimmer (Percentage Value)

**Comment by Rossko57** [comment]
Every other binding just calls it dimmer.
Mentioning "percentage" risks confusion with stuff more suited to Number:Dimensionless e.g. humidity sensors.
