### ISSUE TITLE
[astro] add ability to disable auto discovery of Local Moon and Local Sun

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#7174]
Currently the Astro binding auto discovers Local Moon and Local Sun. Please add a way to disable the auto discovery of Local Moon and Local Sun.

**Comment by kaikreuzer** [comment]
Why? You can simply click once on "ignore" and that's it.

**Comment by cweitkamp** [comment]
You can disable the background discovery of the Astro binding - and others - by setting `discovery.astro:background=false` in your `$OPENHAB_CONF/services/runtime.cfg` file (see [Background Discovery](https://www.openhab.org/docs/concepts/discovery.html#background-discovery)).
