### ISSUE TITLE
[mqtt] [homie] not sending retained = true as per homie convention

### ISSUE THREAD

**Issue by chipec84** [openhab/openhab-addons#7188]
According to homie 3.0 specification (https://homieiot.github.io/specification, section 2.3), all messages must be sent as retained.

In OH 2.5.2 , when a new homie device is auto-discovered with homie/..../$retained true, thing and item work properly but all messages are sent as retained=false.

came across [mqtt][homie] Fix retain flag for outgoing messages #6903
I see that a change was merged on jan 26 in homie300/properties.java, which seems to involve setting retain as false. I don't understand why.
       -     b = b.withCommandTopic(commandTopic).withRetain(true);
       +    b = b.withCommandTopic(commandTopic).withRetain(false);

**Comment by jochen314** [comment]
Because:
section 5.3.2:
```
A Homie controller publishes to the set command topic with non-retained messages only.
```

**Comment by chipec84** [comment]
This seems to be a major limitation for the following use cases:
- If a device is offline and you want to set it futur state for it will back online
- If the device is set ON, it goes offline and you want it back ON when it comes back online
- Check mismatch between states and commands
- ...

**Comment by jochen314** [comment]
This is, what the spec says. So we will not argu about it.
We the argument the other way round, which made us make the above mentioned change. Just imagine, if the Homie controller is not the only source for the change of the state (local button).
Then getting a command from MQTT after startup might be totaly wrong.

**Comment by chipec84** [comment]
This is exactly my setup, I also have a local  physical button to change the state of the device, it can be used when device is online or offline. when back online if broker $set topic mismatches local command, local command always wins and device publishes immediately to the $set topic.  local command are physcial and intended they should always win over IP.
