### ISSUE TITLE
[hueemulation] Hue app prompts update to new version 

### ISSUE THREAD

**Issue by Speaka** [openhab/openhab-addons#7191]
The official Philips Hue app prompts to update the emulated bridge. You cant use the app if you dont, even not with other real existing bridges. The software version in this addon is **1901181309**
The app shows for my real hue bridge **1937113020**

## Expected Behavior
App accepting the emulated bridge like the real one.
## Current Behavior
Prompting to update the fake bridge due to old hard coded fw version.

## Possible Solution
Editing the function "makeV2bridge" in
openhab-addons/bundles/org.openhab.io.hueemulation/src/main/java/org/openhab/io/hueemulation/internal/dto/HueAuthorizedConfig.java

public void makeV2bridge() {
        ...
        swversion = "**1901181309**";
        ...
    }
to the newewst value.

Maybe firmware and api version need to be updated too.
Api Version is now **1.37.00** instead of **1.22.0**
datastoreversion is now **91** instead of **60**
fwversion?

Otherwise possibly make it a config entry to edit it on the fly?

## Steps to Reproduce (for Bugs)
configure addon in oh2.5,  port forward 80->8080, discover bridges in official hue app.

## Your Environment
OH 2.5, raspberry 3 running Raspbian GNU/Linux 10 (buster)
misc-hueemulation - 2.5.1

**Comment by CroMarmot1** [comment]
No response for over a year. AddOn cannot be used like this.
What is the problem?

**Comment by SeeAge** [comment]
It would be great to have the possibility again to add the emulated bridge in the Hue app.

**Comment by lsiepel** [comment]
This doesn’t look to be an issue anymore, can some one confirm? If so please close this isssue
