### ISSUE TITLE
New binding for linktap devices

### ISSUE THREAD

**Issue by becksen** [openhab/openhab-addons#7192]
Link-Tap offers an API which I'd like to use to setup an Openhab2 binding.
[https://www.link-tap.com/#!/api-for-developers](https://www.link-tap.com/#!/api-for-developers)

It was a feature request in the community and as I'd like to use the devices as well for water irrigation I'm highly interested to have a binding available. By the way Openhab is not offfering many binding for garden water irrigation systems so far.

[https://community.openhab.org/t/binding-request-linktap/77192](https://community.openhab.org/t/binding-request-linktap/77192)

Devices to be supported in the initial version are:
LinkTap Wireless Water Timer (TP-1B)
LinkTap Gateway (GW-01)

Features:
- Thing channel for start and stop watering
- Select water irrigation scheduling plans
- Thing discovery connected to LinkTap Gateway

As it will be my first contribution to Openhab I'd need some advise to efficiently complete the development task.

Please get back to me that I can start a pull request.

## Your Environment

- Openhab2 2.5.x
- Java 8
- Firefox 74 / Chrome 80.0.3987.132
- Eclipse 2019-12 (4.14.0) (whereas VS Code is preferred but setup is not that straight forware as with eclipse)
- OS MacOS X Catalina development / openhabian for testing binding

**Comment by becksen** [comment]
No didn't succeed 😟

**Comment by hmerk** [comment]
@becksen Thanks for feedback, therefore closing this issue.
