### ISSUE TITLE
[lgwebos] Volume issue since update

### ISSUE THREAD

**Issue by inis1981** [openhab/openhab-addons#7207]
Since update, I'm not longer able to use delta volume from LG WebOs Tv. Previously tv set to "LG Sound Sync" openhab WebOS binding would watch for volume changes, I then in turn would use this in a rule to control my Denon Receiver located in a different portion of the house. 

On "Internal Speaker" Openhab/WebOs binding see's the volume change, on any other setting it does not.

I believe this issue is related to this change. Can I get this reverted or instructions on where to locate this file to change.

https://github.com/openhab/openhab-addons/commit/e1b14edd146c9bfe93e5200ba0368929f55bb3ba

Openhabian / Pi 3
LG OLED 55' 2017
WebOS binding
on latest updates.

**Comment by lolodomo** [comment]
Without this PR, it would have not work in my case because with my setup scenario field in the JSON response is set to mastervolume_tv_speaker_ext in my case.
We would need to know what is the JSON response you get in your case. You can get this information by enabling the TRACE logs for the binding and then search for this kind of log entry:
```
Message [in]: {"type":"response","id":2,"payload":{"returnValue":true,"volumeMax":100,"ringtonewithvibration":true,"scenario":"mastervolume_tv_speaker_ext","muted":false,"hac":false,"subscribed":true,"volume":17,"action":"requested","supportvolume":true,"ringer switch":true,"slider":false,"active":false}}
```

**Comment by inis1981** [comment]
`2020-03-27 19:37:13.071 [TRACE] [bos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":2420,"payload":{"changed":["volume"],"returnValue":true,"cause":"volumeDown","volumeMax":100,"scenario":"mastervolume_ext_speaker_lg_optical","muted":false,"volume":3,"action":"changed","active":false}}

2020-03-27 19:37:14.161 [TRACE] [bos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":2420,"payload":{"changed":["volume"],"returnValue":true,"cause":"volumeDown","volumeMax":100,"scenario":"mastervolume_ext_speaker_lg_optical","muted":false,"volume":2,"action":"changed","active":false}}`

**Comment by sprehn** [comment]
@inis1981  please test beta version published here 
https://github.com/sprehn/openhab-addons/releases/tag/lgwebos-2.5.4-snapshot-202003280806

**Comment by lolodomo** [comment]
@sprehn :for your information, I tested the different setting of my TV and here are the "scenario" I can have:

- `mastervolume_tv_speaker` with valid volume value and supportvolume being set to true
- `mastervolume_ext_speaker_optical` but with volume value being -1 and supportvolume being set to false
- `mastervolume_lineout` but with volume value being -1 and supportvolume being set to false
- `mastervolume_headphone` with valid volume value and supportvolume being set to true
- `mastervolume_tv_speaker_hp` with valid volume value and supportvolume being set to true
- `mastervolume_tv_speaker_ext` with valid volume value and supportvolume being set to true

So I would suggest to consider any scenario while scenario starts with `mastervolume_` AND supportvolume is true and volume is >= 0.

**Comment by lolodomo** [comment]
I see in @inis1981 logs that he has not the field `supportvolume` in his messages so you should avoid it.
So I think the good condition to consider could be: `scenario` starts with mastervolume_ AND `volume` is >= 0.

**Comment by lolodomo** [comment]
@sprehn : this was merged too fast in my opinion. Can we have a global fix ? As you see in my above, it will still not work depending on what value I select for the audio output.

**Comment by cpmeister** [comment]
Take your time discussing this, but don't create a PR without a [WIP] if you are still discussing things.

**Comment by inis1981** [comment]
> @inis1981 please test beta version published here
> https://github.com/sprehn/openhab-addons/releases/tag/lgwebos-2.5.4-snapshot-202003280806

Yes this worked! I'm back in business. Thank you so much!

**Comment by sprehn** [comment]
I think first of all it is good we provided a timely fixed for a specific issue which @inis1981  reported. Thx for support.

Now we can look into a long term better solution as @lolodomo suggested. 

@lolodomo is the volume also "-1" on volume increase operations? In this case it can simply rely on volume is >= 0.

I had not spotted "supportvolume" so far and I cannot test right now, but it seems it is not present in all versions of the device. But we could use it if present.

I think checking if scenario starts with string "mastervolume_" would be obsolete.

**Comment by lolodomo** [comment]
I checked again and yes volume is -1 when volume update is not available. Thjis is true in the message coming from the subscription, either when changing the volume from the remote control or from openHAB.
So your proposal to consider only volume >= 0 looks good to me.
Note that we have to change the log level for volume increase/decrease commands that can response with a normal error message. We should avaoid a WARN log in this case.
I will propose a fix.

**Comment by lolodomo** [comment]
@sprehn : the comment in the code seems to indicate that you can have a delta value in the response, rather than an absolute value. How do you trigger such response ?

**Comment by sprehn** [comment]
approved #7259 from my perspective
