### ISSUE TITLE
[knx] Numerical values with DPT 9.004 are not shown

### ISSUE THREAD

**Issue by samuixx** [openhab/openhab-addons#7216]
* Version used: openHAB 2.5.2 Release Build with binding-knx - 2.5.2
* Operating System and version: Debian Buster

Values of numerical items defined with DPT 9.004 in the KNX Binding are not shown in the sitemap or in the Control. 

Definition of Thing: KNX Device via Paper UI with configured Channels 
   ChannelLUX : Address: 9.004:<29/1/4 linked Item=lux Label=LUX Ost [%.2f °C] Type=Number 
   ChannelTemperature: Address: 9.001:<29/1/3 linked Item=lux Label=Temperatur [%.2f °C] Type=Number
Items also generated via Paper UI

The Sitemap and the Control shows the Temperature Value but not the Lux value at all

see also:  [knx] DPT 9.004 not working in KNX 2.4.0 Binding (but was in 1.X) #6109

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.

**Comment by holgerfriedrich** [comment]
DPT 9.004 is known to work with current version of the binding. Closing ticket. Please create a new one if you still have an issue in a recent version of the KNX binding.
