### ISSUE TITLE
[squeezebox] Sending MUTE on twice sets volume to 0

### ISSUE THREAD

**Issue by cd-tronic** [openhab/openhab-addons#7217]
## Expected Behavior
If i send a mute ON command to a squeezebox item it should mute the music. If i send mute ON again it should stay muted. If i send mute OFF now it should unmute and set volume back to the value it had before

## Current Behavior
mute works fine if i send a mute ON command and mute OFF after that. If i send mute ON twice i can't reset the volume using mute OFF command. mute turns off but the Volume is set to 0.

## Possible Solution
Check if mute is already set to ON on the player before muting againg.

## Steps to Reproduce (for Bugs)
1. send mute ON command to Squeezebox Player
2. send mute ON command again to Squeezebox Player
3. send mute OFF command to Squeezebox Player

## Your Environment
* Version used: openHAB 2.4.0, squeezebox 2.4.0
* Environment name and version :
* Operating System and version : synology DSM

**Comment by mhilbush** [comment]
I'm not sure why, but the binding doesn't use the `<playerid> mixer muting <0|1|toggle|?|>` command to mute/unmute the player. Instead, on mute, it saves the current volume, then sets the volume to 0. On unmute, it restores the saved volume. That explains why sending 2 mutes in a row causes the volume to be 0 after the unmute.

Unfortunately, I don't know why it was done this way. Perhaps there was an issue with the `mixer muting` command is some early versions of the LMS.

It looks like an easy change to replace the call to setVolume with the `mixer muting` command [here](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java#L148) and [here](https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxServerHandler.java#L152).

**Comment by mhilbush** [comment]
I built a version with the change to use `<playerid> mixer muting 0/1`. It's here if you want to try it out.

https://github.com/mhilbush/openhab-binding-releases/tree/master/squeezebox

**Comment by cd-tronic** [comment]
Hi @mhilbush ,

sounds good. I tried to test it but only get dependecy error (org.eclipse.smarthome.config.discovery.upnp not found). I don't know how to resolve that issue but i think it is related to the manual installation usind Add-Ons folder.

**Comment by mhilbush** [comment]
@cd-tronic Why did you close the issue?

Regarding the dependency issue, did you install the upnp feature as described in the above link?
```
feature:install openhab-transport-upnp
```

**Comment by cd-tronic** [comment]
Hi @mhilbush,
ah sorry. wasn't my intention to close this. I think i clicked the button by accident.

i installed the dependency using feature:install command. Didn't know that command till now.

Looks good and works like it should :) 
Thank you!

Should i reopen the issue? I would close it now.

**Comment by mhilbush** [comment]
Yes, please reopen. I'll test it on my side, too. If I don't see any problems, I'll submit a PR with the change.
