### ISSUE TITLE
[lgwebos] channel number not always updated in case you switch between sources

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7243]
If you use only the tuner source of your LG TV, the channel `channel` is updated as expected when your TV channel is changed.
But after switiching between sources and then coming back to the TV tuner, it can happen that the channel `channel` is no more updated.
I am not yet sure whether the trigger of the problem is the TV source not being the TV tuner when the binding is started.

**Comment by lolodomo** [comment]
Of course, I can't reproduce it now !
Maybe it happens after a certain time, either the subscription is lost or not renewed after a particular change of source.
I added few logs and I will take care how it behaves in the next coming days.

**Comment by lolodomo** [comment]
I finally found how to reproduce th ebug. It happens if I switch to HDMI3 and then come back to TV tuner. Note that I have no device connected to HDMI3.
Here are the logs:
```
18:44:58.200 [INFO ] [smarthome.event.ItemStateChangedEvent] - TvApplication changed from com.webos.app.hdmi3 to com.webos.app.livetv
18:44:58.211 [DEBUG] [g.lgwebos.internal.BaseChannelHandler] - LauncherApplication received: org.openhab.binding.lgwebos.internal.handler.core.LaunchSession@cf4382.
18:44:58.267 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":3,"payload":{"subscribed":true,"appId":"com.webos.app.livetv","returnValue":true,"windowId":"","processId":""}}
18:44:58.277 [DEBUG] [webos.internal.handler.LGWebOSHandler] - postUpdate channelId appLauncher state com.webos.app.livetv
18:44:58.301 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [out]: {"type":"unsubscribe","id":11}
18:44:58.313 [DEBUG] [g.lgwebos.internal.BaseChannelHandler] - Unsubscribed org.openhab.binding.lgwebos.internal.TVControlChannel on Thing: lgwebos:WebOSTV:tv
18:44:58.323 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [out]: {"type":"subscribe","id":16,"uri":"ssap://tv/getCurrentChannel"}
18:44:58.335 [DEBUG] [g.lgwebos.internal.BaseChannelHandler] - Subscribed org.openhab.binding.lgwebos.internal.TVControlChannel on Thing: lgwebos:WebOSTV:tv
18:44:58.425 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":16,"payload":{"returnValue":true}}
18:44:58.433 [INFO ] [ing.lgwebos.internal.TVControlChannel] - retrieving channel: ChannelInfo [channelId=null, channelNumber=null, channelName=null, channelType=null].
```
As you can see, the subscribe message is succeeding but does not include the expected channel information (values are null).
Then if I change the channel with my remote control, no message is received and so of course the channel is not updated.

Here are the logs when it works:
```
18:42:05.325 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [out]: {"type":"subscribe","id":11,"uri":"ssap://tv/getCurrentChannel"}
18:42:05.336 [DEBUG] [g.lgwebos.internal.BaseChannelHandler] - Subscribed org.openhab.binding.lgwebos.internal.TVControlChannel on Thing: lgwebos:WebOSTV:tv
18:42:05.444 [TRACE] [ebos.internal.handler.LGWebOSTVSocket] - Message [in]: {"type":"response","id":11,"payload":{"subscribed":true,"channelId":"1_25_15_15_2_515_8442","physicalNumber":25,"isScrambled":false,"channelTypeName":"Terrestrial Digital TV","isLocked":false,"dualChannel":{"dualChannelId":null,"dualChannelTypeName":null,"dualChannelTypeId":null,"dualChannelNumber":null},"isChannelChanged":false,"channelModeName":"Terrestrial","channelNumber":"15","isFineTuned":false,"channelTypeId":1,"isDescrambled":false,"isReplaceChannel":false,"isSkipped":false,"isHEVCChannel":false,"hybridtvType":null,"isInvisible":false,"favoriteGroup":null,"channelName":"BFM TV","channelModeId":0,"signalChannelId":"2_515_8442"}}
```

It looks like we could check whether the field `subscribed` is present and equal to true in the response. If not, we could implement a retry mechanism.

If I switch to HDMI4 which is connected to a device and then again to the TV tuner, the problem is solved (the subscription is working).

**Comment by lolodomo** [comment]
@sprehn : WDYT about a retry mechanism for the subscriptions ?

Do you think it could be due to the subscription being requested too early after switching to tuner ? We could wait a little before requesting it in this case ?

**Comment by sprehn** [comment]
we could try it with a delay, it seems like a bug in webos to me. I did not get this to work for my setup, even with the recent fix provide. It only works when I start the tv on the tuner, even without delay.

**Comment by lolodomo** [comment]
I just tried again and now it work well !
But I think we should at least check the content of the subscription command response.

**Comment by lolodomo** [comment]
There is apparently no response to the unsubscribe request.
One idea: the unsubscribe and the subscribe rerquests are sent in a short sequence (around 20 ms).
Maybe we should add a little sleep in `removeAnySubscription` after the call to `unsubscribe` ?
