### ISSUE TITLE
Z-Wave binding: channel for meter_reset

### ISSUE THREAD

**Issue by pnijsters** [openhab/openhab-addons#727]
Need the equivalent of the 1.8 binding meter_reset functionality (`{ zwave="6:command=METER,meter_reset=true", autoupdate="false" }`) to reset counters/meters in Z-Wave devices like Aeon Labs Smart Switch 6 or Aeon Labs HEM G2.

**Comment by cdjackson** [comment]
This should now be implemented in the latest binding. It may require updates to the database though to add the meter_reset channel. I think I've added this to the smart switch already.

**Comment by pnijsters** [comment]
Hi Chris, apologies for the delayed response > business trip. Anyways, I just upgraded the binding and recreated the items. This meter_reset works well with the Aeon Labs Smart Switch 6, so I guess this channel can be added to the other database items as well that support this channel (like the HEM G2).

**Comment by cdjackson** [comment]
That's great - thanks for the feedback.
