### ISSUE TITLE
[kostalinverter] Exception while formatting value after openHAB upgrade

### ISSUE THREAD

**Issue by stieler-it** [openhab/openhab-addons#7283]
I am collecting and storing values of our KOSTAL inverter in openHAB. This worked with openHAB v2.5.0 but is broken with later versions. It seems to be related to unit conversions.

Since I am not defining unit conversions, I assume it is part of the addon's provided defaults. I do define unit of measurements but exactly like specified in the docs and it still works with other non-KOSTAL bindings.

## Expected Behavior

Values of KOSTAL inverter can be used by just defining them as Items.

## Current Behavior

Values are shown in Basic UI as "Err". In Paper UI I see old values. In the log there are lots of exceptions like this:

```
2020-04-04 14:53:04.108 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.0' of item C_Inverter_DEVICE_LOCAL_PVSTRING_3_POWER with format '%.2f %unit%': Conversion = 'u'
2020-04-04 14:53:04.142 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '663.2942552484268' of item C_Inverter_STATISTIC_CO2SAVING_YEAR with format '%.2f %unit%': Conversion = 'u'
```

## Possible Solution

Downgrade to openHAB 2.5.0 solves the issue.

## Steps to Reproduce (for Bugs)

kostal.things

```
Thing kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter   "Wechselrichter"    @ "Waschküche" [ url="scb", userPassword="XXX", refreshInternalInSeconds="30" ]
```

I use items with unit of measurement like it is shown in the [example](https://www.openhab.org/addons/bindings/kostalinverter/) in the docs.

kostal.items

```
Number:Power                C_Inverter_DEVICE_LOCAL_DC_POWER                        "DC power"  <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:deviceLocalDCPower"}
...
Number:Power                C_Inverter_DEVICE_LOCAL_PVSTRING_3_POWER                "Strang 3 Leistung"     <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:deviceLocalPVString3Power"}
...
Number:Energy               C_Inverter_STATISTIC_YIELD_DAY                          "Yield of the photovoltaic plant today" <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:statisticYieldDay"}
```

I want to show all values in an extended page in Basic UI.

home.sitemap

```
    Frame label="Strom" {
        Text label="Strom" icon="energy" {
            ...
            Default item=C_Inverter_DEVICE_LOCAL_AC_CURRENT_POWER
            Group item=gPower label="Erweitert" icon="settings"
        }
        
        ...
    }
```

## Context

I want to show current values and log them in an InfluxDB.

## Your Environment

openHAB running from Docker image openhab/openhab:2.5.3 on host with [HypriotOS](https://blog.hypriot.com/) (Debian GNU/Linux 10) on a [RevPi Core 3+](https://revolution.kunbus.de/revpi-core/)

**Comment by stieler-it** [comment]
@cweitkamp Would be nice if you could take a look...

**Comment by cweitkamp** [comment]
May I ask you to place a pattern using the unit placeholder (e.g. `%.2f %unit%`) into the label of your items? Otherwise you might face the same like reported in https://github.com/openhab/openhab-core/issues/986.

**Comment by stieler-it** [comment]
I changed my items to look like this:

```
Number:Power  C_Inverter_DEVICE_LOCAL_DC_POWER "DC power [%.1f %unit%]"  <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:deviceLocalDCPower"}
...
Number:Power  C_Inverter_DEVICE_LOCAL_PVSTRING_3_POWER  "Strang 3 Leistung [%.1f %unit%]"     <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:deviceLocalPVString3Power"}
...
Number:Energy C_Inverter_STATISTIC_YIELD_DAY  "Yield of the photovoltaic plant today [%.1f %unit%]" <energy>  (gPower)    { channel="kostalinverter:PLENTICOREPLUS55WITHOUTBATTERY:cInverter:statisticYieldDay"}
```

but it doesn't seem to help:

`2020-04-05 03:36:19.337 [WARN ] [ui.internal.items.ItemUIRegistryImpl] - Exception while formatting value '0.0' of item C_Inverter_DEVICE_LOCAL_DC_POWER with format '%.1f %unit%': Conversion = 'u'
`

The error message changed to the new format, though. As it was asked in the issue you mentioned, all of the item states are part of the InfluxDB persistence configuration.

**Comment by cweitkamp** [comment]
Solved by https://github.com/openhab/openhab-core/pull/1404
