### ISSUE TITLE
Readme points to non-existent page

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-addons#7285]
The Link pointing to the add-on maintainers (first link) in the Readme.md points to https://github.com/orgs/openhab/teams/add-ons-maintainers which gives a 404.

**Comment by kaikreuzer** [comment]
It is visible for anyone that is part of the openHAB organisation - that's how team visibility in Github works, we cannot do anything about it. I've added you to the contributor list, so you should see it now.
