### ISSUE TITLE
[rme] RME Binding, adding adjustable interval to Thing

### ISSUE THREAD

**Issue by clown-m** [openhab/openhab-addons#7309]
[rme] Add an adjustable interval rate to Thing definition of RME Binding

openHAB versions
openhab2-addons-legacy/stable,now 2.5.3-1 all [installed]
openhab2-addons/stable,now 2.5.3-1 all [installed]
openhab2/stable,now 2.5.3-1 all [installed]

Debian Buster 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

i am using openHAB2 with lots of KNX Equipment, and if a setup the RME Binding with a twu channel definition (additional KNX) it will send every 5 seconds all parameters to the bus, it will be great if the updates will be event driven instead of a fixed interval?

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
