### ISSUE TITLE
[pioneeravr] add 2016+ models

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#7315]
The pioneeravr binding is missing support for AVR models released since 2016.
As the protocol has not changed it is merely a matter of adding products names to a list.

Pinging @gersilex who might be able to author a PR as the original author isn't available.

[PioneerAvrBindingConstants.java.txt](https://github.com/openhab/openhab-addons/files/4440859/PioneerAvrBindingConstants.java.txt)

**Comment by gersilex** [comment]
@mstormi I added the models under the assumption that the features do not differ from the previous models.

Can you please check if it works as expected?

» https://s3.eu-central-1.amazonaws.com/leroy.foerster.it.dienstleistung/org.openhab.binding.pioneeravr-2.5.4-SNAPSHOT.jar

**Comment by mstormi** [comment]
looks good to me
