### ISSUE TITLE
[gardena] provide device scheduled events

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#7316]
The response of the query 
`07-Apr-2020 09:04:24.706 [TRACE] [ng.gardena.internal.GardenaSmartImpl] - GET request:  https://smart.gardena.com/v1/devices/?locationId=xxx
`
returns for the device a structure "scheduled_events" which holds the information about the time schedule for the device. This information is very useful for me.

```
"scheduled_events":[
{"id":"4301760b-e276-44aa-b541-4a25f4c18538","start_at":"09:30","end_at":"19:00","recurrence":{"type":"weekly","weekdays":["monday"]}},
{"id":"4db1db0b-f3cc-437e-bd0a-7f4a3aa54e16","start_at":"09:30","end_at":"19:00","recurrence":{"type":"weekly","weekdays":["tuesday"]}},
{"id":"cfc5833b-8de8-49b0-b7fa-98bd07dd5998","start_at":"09:30","end_at":"19:00","recurrence":{"type":"weekly","weekdays":["wednesday"]}},
{"id":"d31a689e-344e-4563-b2ae-79c2a10cc4f2","start_at":"09:30","end_at":"19:00","recurrence":{"type":"weekly","weekdays":["thursday"]}},
{"id":"cf3ee83f-946c-44cc-b887-0ffdff0745af","start_at":"09:30","end_at":"19:00","recurrence":{"type":"weekly","weekdays":["friday"]}}
]

```
Please make this information available.
Thanks a lot!

**Comment by jwsp1** [comment]
I'd also be very interested in this!

**Comment by jwsp1** [comment]
looks like the bridge is being rebuilt (source #7169). You may want to kindly ask there if someone has free time to implement schedules...

**Comment by lsiepel** [comment]
This binding had a rewrite and many opther PR's can you confirm if this is still a needed enhancement?

**Comment by UrsusS** [comment]
The functionality would still be interesting, but I'm unsure if the data is still available with the new API.

**Comment by lsiepel** [comment]
Had quick look at the openAPI: https://developer.husqvarnagroup.cloud/apis/gardena-smart-system-api?tab=openapi
That does not seem to hold schedule information. But there is also a similar api that does look to have this information:
https://developer.husqvarnagroup.cloud/apis/automower-connect-api?tab=openapi

A Gardena mover is still on my nice-to-have list. :-/ and i don;t think i will buy it on the short term. Withoutthe a mower, it would be hard to enhance this part of the binding. It looks like it is possible, from API perspective.
