### ISSUE TITLE
[hue] Inconsistent handling of brightness restoration

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#7326]
There are multiple Hue lights and ways to control their on/off state or brightness in openHAB with the hue binding. This is ignoring the color settings of the lamp for simpler explanation.

1. Simple light (on/off)
    1. Switch item

2. Dimmable light
    1. Switch item
    2. Dimmer item

3. Dimmable light with different white tones
    1. Switch item (brightness channel)
    2. Dimmer item (brightness channel)

4. Color light
    1. Switch item (color channel)
    2. Dimmer item (color channel)
    3. Color item (color channel)

## Expected Behavior
Sending an "OFF" command to any of these items turns the lamp off, Sending an "ON" command turns the lamp on, restoring the previous brightness and color (like the official Hue app does for example, and also other bindings like the Homematic binding). If the lamp should go to full brightness, we would send the command "100".

## Current Behavior
Given that the lamp is turned off (which works for all constellations with the "OFF" command), the following behaviour can be noticed. Setting is that to each thing there are multiple items linked (e.g. Switch and Dimmer) to show the behaviour of those. It also behaves the same way when only one item is linked.

Item | Sent command | Item change | Physical lamp change
--- | --- | --- | ---
1i Simple light | ON (Switch item) | ON | on
2i / 3i Dimmable light | ON (Switch item) | Switch item: ON,<br>Dimmer item: (previous value) | (previous value)
2ii / 3ii Dimmable light | ON (Dimmer item) | Switch item: ON,<br>Dimmer item: **100** | **100**
4i Color light | ON (Switch item) | Switch item: ON,<br>Dimmer item: (previous value),<br>Color item: (\*,\*,(previous value) | (previous value)
4ii Color light | ON (Dimmer item) | Switch item: ON,<br>Dimmer item: **100**,<br>Color item: (\*,\*,**100**) | (previous value)
4iii Color light | ON (Color item) | Switch item: ON,<br>Dimmer item: **100**,<br>Color item: (\*,\*,**100**) | (previous value)

\* represents the hue and saturation parts of the Color items (which are not affected).

So with everything other that a simple on/off light, it goes wrong in some way or another. The bolded entries are wrong.

Sending "ON" to a Color light that is already at 50% for example also setzs the item brightness to 100 (but does not affect the physical lamp).

Especially with color lights there seem to be problems, where after an "ON" command the item representation (brightness 100) does not match the physical item any more (which restores to its previous brightness level just fine).

A typical log for a Dimmer Item ("EG_Buero_Hue_Decke") would look like this:

Sending 50:
```
2020-04-09 09:50:34.386 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command 50

2020-04-09 09:50:34.393 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become 50

2020-04-09 09:50:34.427 [vent.ItemStateChangedEvent] - EG_Buero_Hue_Decke changed from 0 to 50

2020-04-09 09:50:34.711 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command 50

2020-04-09 09:50:34.716 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become 50

2020-04-09 09:50:35.871 [vent.ItemStateChangedEvent] - EG_Buero_Hue_Decke_sw changed from OFF to ON
```
Sending OFF:
```
2020-04-09 09:50:40.557 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command OFF

2020-04-09 09:50:40.564 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become OFF

2020-04-09 09:50:40.629 [vent.ItemStateChangedEvent] - EG_Buero_Hue_Decke changed from 50 to 0

2020-04-09 09:50:40.944 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command 0

2020-04-09 09:50:40.950 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become 0
```
Sending ON:
```
2020-04-09 09:50:44.272 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command ON

2020-04-09 09:50:44.278 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become ON

2020-04-09 09:50:44.304 [vent.ItemStateChangedEvent] - EG_Buero_Hue_Decke changed from 0 to 100

2020-04-09 09:50:44.616 [ome.event.ItemCommandEvent] - Item 'EG_Buero_Hue_Decke' received command 100

2020-04-09 09:50:44.623 [nt.ItemStatePredictedEvent] - EG_Buero_Hue_Decke predicted to become 100
```

A typical log for a Color Item ("EG_Essen_Hue_Decke") with a previous brightness of 50 percent looks like this:

Sending OFF:
```
2020-04-09 09:44:18.623 [ome.event.ItemCommandEvent] - Item 'EG_Essen_Hue_Decke' received command OFF

2020-04-09 09:44:18.628 [nt.ItemStatePredictedEvent] - EG_Essen_Hue_Decke predicted to become OFF

2020-04-09 09:44:18.656 [vent.ItemStateChangedEvent] - EG_Essen_Hue_Decke changed from 48,42,50 to 48,42,0

2020-04-09 09:44:24.171 [vent.ItemStateChangedEvent] - EG_Essen_Hue_Decke_sw changed from ON to OFF
```
Sending ON:
```
2020-04-09 09:44:25.480 [ome.event.ItemCommandEvent] - Item 'EG_Essen_Hue_Decke' received command ON

2020-04-09 09:44:25.487 [nt.ItemStatePredictedEvent] - EG_Essen_Hue_Decke predicted to become ON

2020-04-09 09:44:25.521 [vent.ItemStateChangedEvent] - EG_Essen_Hue_Decke changed from 48,42,0 to 48,42,100

2020-04-09 09:44:34.235 [vent.ItemStateChangedEvent] - EG_Essen_Hue_Decke_sw changed from OFF to ON
```
Sometimes it corrects itself shortly after (sometimes it doesn't):
```
2020-04-09 09:44:34.251 [vent.ItemStateChangedEvent] - EG_Essen_Hue_Decke changed from 48,42,100 to 48,42,50
```

## Steps to Reproduce (for Bugs)
1. Create Things as described above
2. Create and link Items as described above
3. Send "ON" command e.g. with console command `smarthome:send (item) ON`

## Context
I'm trying to build a habpanel dashboard that behaves consistensly for all lights, including those from the hue binding. Turning a light "ON" should restore the previous state, otherwise I would send a "100" command.

For now, I need a workaround using proxy switch items (Item_Name_sw in my example) and send the command to those. While this works, it unneccessarily duplicates all light items and also needs various hacks at other places (e.g. the Dimmer item is updated with a delay when firing the Switch item).

## Your Environment
Using openhabian, newest version, as of now 2.5.3.

## Other
- All rules turned off, habPanel cleared, openHAB restarted to avoid interference.

Note that this is not a duplicate of #4996. But maybe something can be learned from the solution in PR #5009 (just a wild guess, might be a completely unrelated issue).

**Comment by doits** [comment]
Thanks for this great sum up! I was going crazy while implementing some rules that touch hue lights where lights would seemingly randomly change the brightness which I also traced down is because the item brightness diverges from the physical brighness and the next time the color is sent the bulb goes to full brightness. I am sending ON/OFF to color items, too.

So if I see it correctly currently the only way to send ON/OFF without changing brightness is to have a switch item. At least a workaround.

**Comment by lolodomo** [comment]
Are you sure that the channels state is not updated to the correct value at the next polling ?
Remember the polling is done every 10 seconds per default.

Did you try to add `autoupdate="false"` to your items ? I guess this will avoid this first update to 100.

**Comment by lolodomo** [comment]
I just tested your cases 4i 4ii and 4iii using 2 items, one without autoupdate and one with autoupdate set to false:
```
Color LampeConsole "Lumière derrière la console" <colorwheel> { channel="hue:0200:bridge1:console:color" }
Color LampeConsole2 "Lumière derrière la console 2" <colorwheel> { channel="hue:0200:bridge1:console:color", autoupdate="false" }
```
And in my sitemap, I show 2*3=6 widgets:
```
			Switch item=LampeConsole icon="light"
			Slider item=LampeConsole icon="light"
			Default item=LampeConsole icon="light"
			Switch item=LampeConsole2 icon="light"
			Slider item=LampeConsole2 icon="light"
			Default item=LampeConsole2 icon="light"
```

If I use the item LampeConsole (without autoupdate) to send an ON command, I see the dimmer first set to 100% but that is expected as a ON command is translated to 100% for a slider widget. Few seconds later, everything is updated to its expected values (when the states are polled by the binding). The 3 last widgets linked to LampeConsole2 are not updated immediately but only when the states are polled.

If I use the item LampeConsole2 (with autoupdate set to false) to send an ON command, I see no impact on the slider widget. Everything is updated only when the states are polled by the binding.

So in my point of view, I see nothing wrong with your cases 4i, 4ii and 4iii, all this is linked on how you defined your item. You should add `autoupdate="false"` to your item if you want the behaviour you describe.

**Comment by doits** [comment]
Thanks for testing and the `autoupdate` suggestion, though I think it does not completely solve the case.

For me the main culprit is that the item state diverges from physical state *while only openhab is changing the bulb*. Even if it might correct itself after some time (the next poll), there is a period where the item state is wrong. And this can lead to rules working with wrong data in that period.

So if it is correct that sending `ON` to a dimmer item should always change the brightness to `100`, fine, but then the physical brightness of the bulb should always change to `100` there, too.

So more generally with `autoupdate="true"`: When I do a `item.sendCommand(state)` I'd expect that item state and physical state match right after I send that command, not having to wait for the next poll. Which seems to be a misconception currently, at least with the Hue binding in case of a Dimmer item.

I don't know if the Hue binding is the only binding where states diverge like this, though it never occurred to me in the KNX binding yet (but maybe I simply didn't notice).

**Comment by lolodomo** [comment]
> So more generally with autoupdate="true": When I do a item.sendCommand(state) I'd expect that item state and physical state match right after I send that command, not having to wait for the next poll. Which seems to be a misconception currently, at least with the Hue binding in case of a Dimmer item.

It will happen if the binding updates quickly the state of the channel. This is not how the hue binding is working.
Considering how the hue binding works, in case you want to display different kind of widgets for the same item, I will strongly recommend to use `autoupdate="false"`.
In addition, you can reduce the refresh interval to be sure to get a faster update.

**Comment by lolodomo** [comment]
The only real bug I would consider in your bug report would be your cases 2ii and 3ii in case your phisical lamp was really changed tp 100. I will check myself that case later.

**Comment by lolodomo** [comment]
More generally, I agree that it is better when a binding updates the states immediately after handling a command.

It also exists a possibility for a binding to veto the automatic refresh of the state by the core framework. Maybe it should be used by the hue binding. The only time I tried to use this feature, I got an unexpected behaviour and I forgave (unfortunately I don't remember what was wrong in this case).

**Comment by eikowagenknecht** [comment]
> Are you sure that the channels state is not updated to the correct value at the next polling ?
> Remember the polling is done every 10 seconds per default.

Sometimes it is, sometimes it is not. Unfortunately I can't put a finger on why and when it is updated.

> Did you try to add `autoupdate="false"` to your items ? I guess this will avoid this first update to 100.

This will probably work with Color items. I think it's not ideal though, since 10s (the default) is a very long time to wait for a response in a GUI for example. Setting the polling to 2s or less makes this almost tolerable but puts on some more load on openHAB and the hue bridge. Not sure how low we can go with the polling interval.

**Comment by lolodomo** [comment]
> I think it's not ideal though, since 10s (the default) is a very long time to wait for a response in a GUI for example. Setting the polling to 2s or less makes this almost tolerable but puts on some more load on openHAB and the hue bridge. Not sure how low we can go with the polling interval.

Keep in mind that per default, the binding has a polling job for sensors run twice per second. If you have no sensors, like me, you can increase a lot this interval. Then it should be reasonable to reduce the interval for lights.
Even if the sensor job run twice per second, my hue bridge was OK.

**Comment by lolodomo** [comment]
> I'm 100% sure about this, I'm sitting right under the lamp and was wondering why it behaves so weirdly. That's when I started this whole investigation ;-)

I just tested your case 2ii with a dimmable white light and for me the restored physical brightness is not 100% but the previous one.
So sorry, I can't reproduce this issue.
Maybe this is due to your particular light model ? What model is it ?

**Comment by eikowagenknecht** [comment]
I was testing with this light for case 2ii. Official Hue "Aurelle", details see below:

Name | Wert
-- | --
capabilities | {"certified":true,"control":{"mindimlevel":100,"maxlumen":4200,"ct":{"min":153,"max":454}},"streaming":{"renderer":false,"proxy":false}}
config | {"archetype":"ceilingsquare","function":"functional","direction":"downwards","startup":{"mode":"powerfail","configured":true}}
manufacturername | Signify Netherlands B.V.
modelid | LTC015
name | Büro Decke
productid | Philips-LTC015-1-AurelleRtP_v1
productname | Hue ambiance panel
state | {"on":false,"bri":139,"ct":230,"alert":"select","colormode":"ct","mode":"homeautomation","reachable":true}
swconfigid | DDCAF849
swupdate | {"state":"noupdates","lastinstall":"2020-03-04T13:43:12"}
swversion | 1.50.2_r30933
type | Color temperature light
uniqueid | <redacted>

**Comment by lolodomo** [comment]
> Color temperature light

The Philips Hue Aurelle is a white light with color temperature adjustment. Unfortunately, I have no light with color temperature adjustment. Maybe the problem is only with such light with color temperature.
I see some code in the binding setting the color temperature in the request when handling an ON command but not the brightness. Maybe that is the point.

**Comment by eikowagenknecht** [comment]
Closing my issues with openHAB that seem to have gone stale.
