### ISSUE TITLE
[yamahaReceiver] Channel playback not working with PC/MCX input on Yamaha RX-V3900

### ISSUE THREAD

**Issue by stormy-gh** [openhab/openhab-addons#7328]
## Expected Behavior
Playback control should work with PC/MCX source on Yamaha RX-V3900 like in Yamaha web interface (see attached screenshot).
Artist/album/song also should be displayed on openhab.
![yamaha](https://user-images.githubusercontent.com/30049588/78899492-cd290000-7a75-11ea-8b2a-3f56aff5a42e.png)

## Current Behavior
Playback control not working for PC/MCX source on Yamaha RX-V3900.
Artist/album/song are also not displayed on openhab.
PC/MCX source on RX-V3900 is used to play music from UPnP/DLNA network server.
This is NOT the same source as "NET RADIO" or "USB".
Message in logs:
`2020-04-09 14:51:54.984 [WARN ] [ernal.handler.YamahaZoneThingHandler] - Channel playback not working with PC/MCX input!`

## Your Environment

* Version used: openhab 2.5.3-1

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
