### ISSUE TITLE
[tradfri] Incorrect color is returned if brightness is 0

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#7342]
## Expected Behavior

I have a color picker for a Tradfri color bulb in my sitemap. If the bulb is turned off and I open the color picker, the color is set to the previous color. If I change the brightness of the bulb, the previous color is restored.

## Current Behavior

If the bulb is turned off and I open the color picker, the color is set to white. This is because the rest api returns the state `0,0,0`. Even if hue and saturation might not be 0.
If I change the brightness of the bulb, it turns on in the previous color, which might not be `0,0,100`.

## Possible Solution

Return the correct color for Tradfri color bulbs.

## Steps to Reproduce (for Bugs)

0. Have a color picker for the Tradfri color bulb
1. Set the bulb to blue
2. Set the brightness to 0
3. Reopen the color picker

## Context

First I thought this is an[ issue with the new color picker in the android app](https://github.com/openhab/openhab-android/issues/1926), but I figured out it's a rest api issue.

## Your Environment

* Version used: (e.g., openHAB and add-on versions) 2.5.3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Android app > 2.12.6-beta
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
