### ISSUE TITLE
[netatmo] Heat index calculation is incorrect

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#7351]
Heat index is producing incorrect results. 

indoor temp 69.1 F
Iindoor humidity 41%
indoor heat index 83.9

outdoor temp 30.7 F
outdoor humidity 86%
outdoor heat index 212.7 F

Using https://www.wpc.ncep.noaa.gov/html/heatindex.shtml or https://www.calculator.net/heat-index-calculator.html produce the results:

indoor heat index 68 F, outdoor heat index 31 F

**Comment by robnielsen** [comment]
Here's sample code from the US Department of Labor: https://github.com/USDepartmentofLabor/Calculate-Heat-Index-Java/blob/master/src/main/java/gov/dol/CalculateHeatIndex.java

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/WeatherUtils.java#L30

@clinique: do you remember where you got your algorythm ?

**Comment by robnielsen** [comment]
The sample code from US Department of Labor produces incorrect results as well. (77.2 and 166.9)

**Comment by lolodomo** [comment]
If it exists several algoryths, how to be sure that the one you chose has more value than the previous ?

**Comment by robnielsen** [comment]
Per https://en.wikipedia.org/wiki/Heat_index#History:

> The heat index was developed in 1978 by George Winterling as the "humiture" and was adopted by the US's National Weather Service a year later.

George Winterling worked for the  television station WJXT in Jacksonville, Florida  

The formula used is from the US National Weather Service's site.
