### ISSUE TITLE
[Homematic] support for HmIP-SWO-PR

### ISSUE THREAD

**Issue by maedball** [openhab/openhab-addons#7353]
Hi,

Please add support for the Homematic IP Weather station: HmIP-SWO-PR

**Comment by MHerbst** [comment]
Is the weather station not detected at all or is it displayed as "unknown device"?

**Comment by maedball** [comment]
It is detected but all i see is the Battery stautus, signal strength and a broken humidity (broken because it seems it is showing the data from channel 1 instead of 4)
![Capture](https://user-images.githubusercontent.com/23019308/83350840-3ffc7c00-a33f-11ea-9dc9-1f10a465f092.PNG)

**Comment by chrostek** [comment]
@maedball you can close the issue, the device was in my PR #7911 included and will have a description in OH 2.5.6

**Comment by maedball** [comment]
Thank you very much!
