### ISSUE TITLE
[lgwebos] mediaPlayer and mediaStop channels state not updated

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7356]
When handling a channel command, the channel state is not updated.

**Comment by lolodomo** [comment]
PR #7355 is fixing the case of the power channel.
Another PR is necessary for other channels (volume, mute, ...).

**Comment by lolodomo** [comment]
After first  checking, I was wrong, it is working well at least for the following channels: volume, mute and channel. It is due to the subscription for these channels.

**Comment by lolodomo** [comment]
It also depends on whether `autoupdate="false"` is set or not on the item.
I think only the channels power, mediaPlayer and mediaStop require a fix.

**Comment by sprehn** [comment]
let us not discuss the power channel in too many threads.

MediaControlPlayer see comment:  // TODO: playstatesubscription
I have not found out how to listen for those play states yet in the api

**Comment by lolodomo** [comment]
For mediaPlayer, I tried few commands to get the player status but with no success.
So we have no known way to detect player commands from external devices (like TV remote control).
At least, we could try to maintain a coherent state between mediaPlayer and mediaStop channels, when used only from openHAB. This is better than nothing, but of course not perfect.

**Comment by koshisan** [comment]
Is there any hope this will be fixed? I would love to get a reliable play/pause state from the tv to control the living room lights...

**Comment by lolodomo** [comment]
@sprehn : do you see something in the provided link that could help identify the URL to subscribe to?

**Comment by sprehn** [comment]
hi, no I don't find it in there and this is just the error handling piece. Connect SDK was trying to implement a universal abstraction, not only for WebOS, but also for ChromeCast, AppleTV etc. - so it does not mean this works in WebOS. 
@lolodomo  you are correct, if we know which url to subscribe to, we could do it. But I don't.

**Comment by lolodomo** [comment]
As there is no identified solution to determine the playback status, I mark this issue with the tag "won't fix".

**Comment by lolodomo** [comment]
... and I even close it.

**Comment by jimtng** [comment]
Any more development on this? It's a shame that this isn't currently possible.
