### ISSUE TITLE
[lgwebos] Thing properties

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7398]
Some system properties exist and they could be used by the binding rather than defining new specific properties.
Few properties may be useless or even confusing for the final user.
Here are the list of current properties:

- deviceId: OK - we have serialNumber (Thing.PROPERTY_SERIAL_NUMBER) as system property but I am not sure the current deviceId property is really a serial number.
- deviceOS : is it useful ? Its value is "webOS".
- deviceOSVersion / deviceOSReleaseVersion : it is not clear for the final user why several versions are provided. In my case, the first one is "4.1.0" and the second "4.7.1". The second is the nearest to what the TV is showing in menu: 04.71.25. I suggest to keep only the value of the current property deviceOSReleaseVersion and to name it firmwareVersion (system property Thing.PROPERTY_FIRMWARE_VERSION). In case 4.1.0 is a hardware version, we could use hardwareVersion (system property Thing.PROPERTY_HARDWARE_VERSION)
- lastConnected: OK
- modelName: we should use modelId (system property Thing.PROPERTY_MODEL_ID)
- manufacturer: we should use vendor (system property Thing.PROPERTY_VENDOR)

**Comment by lolodomo** [comment]
@sprehn : did you notice that in the response to the hello request, in addition to deviceOS, deviceOSVersion, deviceOSReleaseVersion, you get deviceUUID and its value seems to be the id you are getting from the UPnP discovery ?
I would suggest to set the deviceId property of the thing when not set (meaning when the thing was created manually, not from the discovery). I have to check that but it is possible that the discovery will then automatically set the other properties (model and manufacturer).

**Comment by lolodomo** [comment]
I just checked and even when the representation property (deviceId) is set, the core framework is apparently not updating the other properties from the discovery. I will check the core framework code, maybe only the configuration settings are updated.

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.config.discovery/src/main/java/org/openhab/core/config/discovery/internal/PersistentInbox.java#L253

Confirmed, the core framework ignores the simple properties and will update the thing only if one thing configuration setting is updated. Makes fully sense.

So if we want to set, for things created manually, the properties that are set only by the UPnP discovery, some code has to be added.

**Comment by lolodomo** [comment]
> @sprehn : did you notice that in the response to the hello request, in addition to deviceOS, deviceOSVersion, deviceOSReleaseVersion, you get deviceUUID and its value seems to be the id you are getting from the UPnP discovery ?

@sprehn: could you please confirm that with your model ?

**Comment by sprehn** [comment]
cant test at the moment - no access to tv anymore
