### ISSUE TITLE
[bluetooth/velux] Remove deprecated methods for OH3

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#7402]
In openHAB 3.0 we will remove some deprecated methods (see https://github.com/openhab/openhab-core/issues/1408 and https://github.com/openhab/openhab-core/pull/1414). Corrently some of them are still used by bindings in this repository. Most of the time it is not very hard to remove or replace them by preferred methods. In other cases it is not that easy because it requires bigger refactoring.

For the replacement of the deprecated method [ThingUID#getThingTypeUID()](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/ThingUID.java#L161) in Bluetooth and Velux binding I have to ask the initial contributors (@cpmeister and @gs4711) for help.

Thanks in advance.

Bluetooth binding:
https://github.com/openhab/openhab-addons/blob/e1040a69ddee6f36f0f3d93288459437506fe972/bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java#L303-L305

https://github.com/openhab/openhab-addons/blob/e1040a69ddee6f36f0f3d93288459437506fe972/bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java#L318-L320

https://github.com/openhab/openhab-addons/blob/e1040a69ddee6f36f0f3d93288459437506fe972/bundles/org.openhab.binding.bluetooth/src/test/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryServiceTest.java#L373-L375

Velux binding:
https://github.com/openhab/openhab-addons/blob/e1040a69ddee6f36f0f3d93288459437506fe972/bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBindingHandler.java#L86-L88

https://github.com/openhab/openhab-addons/blob/e1040a69ddee6f36f0f3d93288459437506fe972/bundles/org.openhab.binding.velux/src/main/java/org/openhab/binding/velux/internal/handler/VeluxBridgeHandler.java#L191-L193

**Comment by cpmeister** [comment]
@cweitkamp I only use those methods in testing and would gladly change them if you could give me an alternative to use in those tests. My tests don't use Thing objects so I can't use the recommended replacement. Suggestions?

**Comment by cweitkamp** [comment]
Do you have an idea how the resulting `ThingUID` looks like? If so you can try to replace the `argThat(...)` by `same(thindUID)`.

**Comment by cpmeister** [comment]
> Do you have an idea how the resulting ThingUID looks like? If so you can try to replace the argThat(...) by same(thindUID).

I randomly generate it for the test, but your suggestion should be doable. I'll give it a shot.

**Comment by gs4711** [comment]
>  replace them by preferred methods.

@cweitkamp , in both cases the semantic is the following:
Retrieving the appropriate `ThingTypeUID` for a given `ChannelUID`.

Seems to be an easy relationship, but my experiences have been that none of the suggested alternatives provide such a functionality.

Any suggestions?

**Comment by cweitkamp** [comment]
@gs4711 What's the idea behind that? Isn't the `ThingUID` sufficient?

**Comment by gs4711** [comment]
Sounds reasonable ... the use case is the asynchronous handler
`public void handleCommand(ChannelUID channelUID, Command command)`
in which the determination of the `ChannelType` would be sufficient. But how to get it? Any pointers are appreciated!

**Comment by cweitkamp** [comment]
In the same handler where the `handleCommand()` will be processed?

```java
getThing().getChannel(channel UID).getChannelTypeUID()
```

I think what you want to do is to determine the accepted item type? Do you?

```
getThing().getChannel(channel UID).getAcceptedItemType()
```

Otherwise if you know the `ChannelTypeUID` you can map it because the definitions of them are known as they are written down in your XML-files or provided by an binding related `ChannelTypeProvider`.

**Comment by gs4711** [comment]
Thanks, @cweitkamp, for your support.

Having included some debugging statements in the actual code, it seems that the `ChannelTypeUID` is the combination of the the binding name and the channel name, which is visible within the constructor `public ChannelTypeUID(String bindingId, String id)` as well.

This raises two questions:

1. What happens if a binding is using the same channel identifier with a different context, i.e. (_bridge_,_status_) and (_window_,_status_) ?

1. Is it a valid approach to use constants like:
```
public static final ChannelTypeUID CHANNEL_TYPE_BRIDGE_STATUS = new ChannelTypeUID(BINDING_ID, CHANNEL_BRIDGE_STATUS);
public static final ChannelTypeUID CHANNEL_TYPE_WINDOW_STATUS = new ChannelTypeUID(BINDING_ID, CHANNEL_WINDOW_STATUS);
```

where
 ```
   public static final String CHANNEL_BRIDGE_STATUS = "status";
   public static final String CHANNEL_WINDOW_STATUS = "status";
```

 I do not see how to distinguish the both `ChannelTypeUID`s, if I have an overall handling for all kind of Channels of a binding?

**Comment by cweitkamp** [comment]
The `ChannelTypeUID` should be unique. In your case you have to choose an more specific id - e.g. `"bridge-status"` and "windows-status"` - to distinguish between them. It is okay to use a channel type multiple times for the very same functionality e.g. having an actuator with 5 relays, which each is a simple "switch", but you want to individually name the channels "switch-n" (n = 1...5).

**Comment by cweitkamp** [comment]
@gs4711 I just want to check if you are still working on a solution for this? Time for OH3 is coming and we have to reach an agreement if we should wait for a refactoring of the Velux binding or exclude it for add-ons port build. Would be nice to get a feedback? Thanks.

//CC @openhab/core-maintainers

**Comment by wborn** [comment]
Since https://github.com/openhab/openhab-core/pull/1414 has been merged now, the Velux Binding has been removed from the OH3 add-ons port.
It would be awesome if you can update the Velux Binding so we can add it back to OH3 builds again @gs4711.

**Comment by gs4711** [comment]
Thanks for your reminder. In fact, I had missed your response some months ago (this seems to be no big deal... but I'd like to have some quality checks). Therefore, I have been focusing onto enhancements within 2.5. Will check whether a parallel development environment is possible within Eclipse.

CC @openhab/core-maintainers

**Comment by wborn** [comment]
Please also keep in mind that all major developments will happen on 3.0 (master) in about a week time. See the [announcement](https://community.openhab.org/t/openhab-2-5-x-patch-releases/90248/260?u=wborn).

**Comment by gs4711** [comment]
Just a few weeks on vacation ... and there's big news. Sounds good to me.

**Comment by wborn** [comment]
It might fall into the "major and critical fixes" category then which can be backported. Enjoy your vacation! :palm_tree: :sun_with_face:

**Comment by andrewfg** [comment]
Just to say that I have written a fix for deprecated methods in the `velux` binding in #8520

**Comment by cweitkamp** [comment]
@andrewfg First of all thanks for working on it. Yes, it looks like a workaround, but we had to do the same in OHC to get rid of it too. I would suggest not to start on `ChannelUID` but - if possible - on `ThingUID`.

```
String[] segments = thingUID.getAsString().split(AbstractUID.SEPARATOR);
// the length of segments will always be greater than 1 for ThingUIDs, class AbstractUID will take care of that during initialization
if (!segments[1].isEmpty()) {
    thingTypeUID = new ThingTypeUID(thingUID.getBindingId(), segments[1]);
}
```

**Comment by andrewfg** [comment]
@cweitkamp many thanks for the tip. I think the problem with the `velux` binding is that the code is called on a channelUID name (string) of a channel that could be potentially in the system but not yet instantiated in reality. Therefore one cannot get the ThingTypeUID of a real Thing+Channel, and instead it must determine _"what would be the ThingTypeUID of this channelUID if it would actually be instantiated in a real Thing+Channel?"_

**Comment by cweitkamp** [comment]
Alright, we are done over her. Thank you all.
