### ISSUE TITLE
Marantz / Denon binding

### ISSUE THREAD

**Issue by WalterDudw** [openhab/openhab-addons#7414]
I have Openhab 2.5 running on Raspberrt pi 3.
My question is regarding the Marantz/Denon binding.
Only older receivers are tested. I would like to know if newer models Networkreceivers are also supported.
In particular the new Marantz  NR1200 : is this support by the binding / will it work ?

Before I buy this AV receiver I need to know this :)

thanks

**Comment by 9037568** [comment]
Questions belong in the community forum.
