### ISSUE TITLE
Add support for Cherubini Blinds in RFXCom binding

### ISSUE THREAD

**Issue by Bleizig** [openhab/openhab-addons#7417]
RFXCom added support for Cherubini in Version 5.68 - 26/02/2020.
This feature request is about adding support in the RFXCom binding.

**Comment by RudiAcacia** [comment]
This improvement is not present in the RFXcom binding openhab2 nor openhab3. I have Motostar blinds whith SubType=15 and the update of the binding could resolve my problem as the solution seams to bee easy ....
