### ISSUE TITLE
[hue] Support for Groups/Rooms

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#7419]
<a alt="bounty" href="https://www.bountysource.com/issues/91154112"><img src="https://api.bountysource.com/badge/issue?issue_id=91154112"></a>

It would be great to see the addition to rooms/groups to the hue binding.

Of course, you can achieve similar things with openHAB Groups, however the reliability using hue groups/rooms is higher and the response time is much shorter than using groups in openHAB.

For example, I got about 15 lights in my living room. If I switch the group on/off all lights turn on/off at the same time (I am not able to see a chronological order on how the lights switch on). If I am doing the same thing with openHAB groups I can clearly see an order on how the lights turn on and it takes a lot longer as all lights are activated in a serial way.

I saw that @leluna is working on support for scenes, so that might be another addition.

I will add a bounty for that feature request.

Thanks a lot

Cheers

Andreas

**Comment by regnets** [comment]
Bounty added:
https://www.bountysource.com/issues/91154112-hue-support-for-groups-rooms

**Comment by lolodomo** [comment]
I can have a look.
If we create one thing for each group/room, what kind of channels should it have ? Only a switch channel ?

**Comment by lolodomo** [comment]
I have already something working. I still need to add the update of the group state and then I will be able to provide a PR.

**Comment by lolodomo** [comment]
This is now implemented. The new thing type for a Hue group has a switch channel to turn on or off the lights in the group (room). Discovery is implemented too.

**Comment by regnets** [comment]
Hi lolodomo, that was a really fast development. I can test the binding tomorrow.

You said there there is only a switch channel? From the hue app it seems that you can control more than just the On/Off state. I am not sure how the api works, do you think it would be possible to also add a color/brightness/color temperature channel?

Cheers

Andreas

**Comment by regnets** [comment]
Maybe you could have a look at the unofficial documentation? It seems, that you can send besides the On/Off also all other parameters which can be send to an individual light.

http://www.burgestrand.se/hue-api/api/groups/

http://www.burgestrand.se/hue-api/api/lights/#changing-light-color-and-turning-them-onoff

Thanks a lot for your hard work so far.

Cheers

Andreas

**Comment by lolodomo** [comment]
I added the brightness control now.

One problem with a group color control could be that if your group/room has few lights without color control, I am not sure what could be the result. But I will be able to test, so I will see.

**Comment by regnets** [comment]
I had a look at the PR, looks good! Will test it tomorrow.

Based on my experience, i think the hue bridge will just discard values for non-color lights. Same goes for the brightness with on/off units. So that might not be a perfect solution, However if you got large installations this will greatly reduce the command to send to the hue bridge and the commands send to the hue lights.

**Comment by lolodomo** [comment]
I have no lights with color temperature control, so I can try to add this control but I will not be able to test it.

**Comment by lolodomo** [comment]
The hue app does not offer the feature to set the same color for all lights in a group. It rather shows to you the different lights on a color wheel and you can adjust each of them.

I can give the ability to send a color command for all lights in the group but to get the color state of a group, this is not obvious ! For dimmer, I computed the average of all lights. I am not sure how computing the average between different colors !

**Comment by lolodomo** [comment]
As color state for the group, I could set it to the color of lights in case they have all the same color and to black in case they have not the same color.

**Comment by regnets** [comment]
That would be absolutely OK for me. I would really like to see the option to control the color of a group of lights, it doesn't matter to me if the representation is black.

**Comment by lolodomo** [comment]
@regnets : I have a doubt because @leluna said that the groups are not working. Even if this is still workiong for me, please try again with this compiled version from the branch 2.5.x and tells us if this is still working for you too.
[org.openhab.binding.hue-2.5.5-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/4571985/org.openhab.binding.hue-2.5.5-SNAPSHOT.zip)

**Comment by Tomibeck** [comment]
@lolodomo 

It seems to me that the behaviour of hue groups isn't consistent with hue lights in openhab yet their behaviour is the same with the hue API let me explain:

On the hue API, both groups and specific lights will only accept a hue, saturation, brightness change if they are already turned on or are turned on with the same API call.
From openhab I can send (100,100,100) (example) as a command to a hue bulb which is turned off and it is going to turn on with the desired values. Now if I do the same with a group which is turned off it will not turn on. 
To me it looks like the binding makes sure that the bulb is turned on even though you only send hue,sat,bri. It doesn't with groups. I think it would make things easier if the groups behave the same way because otherwise, you would need to send an on command to the switch item of the group followed by a second (100,100,100) command to the color item

**Comment by lolodomo** [comment]
The handling of groups and lights by the binding is the same. 
I will try again your case but I am sure it was working. 
What is your way to send the color? With what UI? With a rule?

**Comment by Tomibeck** [comment]
I use jython via js323 with the helper libraries this is my test code :

`from core.rules import rule
from core.triggers import when 

@rule("Testrule", description="Optional Rule Description")

@when("Item LA_Motion_OR received update")

def my_rule_function(event):
    events.sendCommand("Fernseherlinks", "129,0,20")
 
`
 described works with  the single light item but not with the group ( room)

**Comment by Tomibeck** [comment]
@lolodomo : ANy updates can I somehow help?

**Comment by lolodomo** [comment]
@Tomibeck : could you please open a new issue for your problem.
I can confirm your issue. I will put my analysis in the new issue.

**Comment by lolodomo** [comment]
Good news, I know how to fix the issue.
So it is no more required to open the issue,.

**Comment by lolodomo** [comment]
@Tomibeck : PR #7907  is fixing the issue.

**Comment by Tomibeck** [comment]
@lolodomo thats amazing thanks a lot
