### ISSUE TITLE
[hue] Support for Pressure and Humidity devices

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#7420]
Hue already supports different sensor types for example Temperature. My Xiaomi Aqara although provides pressure and humidity as seperated sensors. Those should be accessible by hue binding as well

**Comment by regnets** [comment]
I wasn't aware that the hue bridge allows pairing of other Zigbee Devices.
Could you please explain how do you paired the Aqara Sensor to the hue bridge?

**Comment by DerOetzi** [comment]
@regnets We are discussing at the moment inside the PR #7426. I'm not sure whether it is possible, I have only a conbee II stick at home no original hue bridge. Maybe I will redraw this Feature Request Because it is better to use deconz binding here.

**Comment by regnets** [comment]
I think the original motion sensor has a temperature sensor built in.

So far the only way to get to that data was through a http request.

So the preparation for humidity and temperature are a good thing and should be added to the hue binding. Just keep in mind that the pairing of the aqara sensor is not possible (as far as I know). I just sold my aqara sensors in favor of homematic.

**Comment by DerOetzi** [comment]
I redraw the PR and would close this issue as well, because I connected the aqara sensors not to original hue bridge, but to conbee II. They are already supported by the belonging deconz binding.
