### ISSUE TITLE
[jsonpath] Incoming Value Transformations invalid character

### ISSUE THREAD

**Issue by hdavid** [openhab/openhab-addons#7421]
for one of my Thing's channels i need to chain two transformations
like so :
`JSONPATH:$.channelPowers[1].current∩JS:divideByTen.js`
Using the `∩` as documented. It works perfectly, but upon restart of openHab (and some other occasions i could not pinpoint, but i suppose it has to do with saving/reloading config from disk) the special character gets replaced by `?` like so `JSONPATH:$.channelPowers[1].current?JS:divideByTen.js`
It seems it started to happen with the last release version, but i am not 100% as i used the previous version for not long and i was just getting started with openHab

if it matters i am running openHab 2.5.3 on a raspberry pi 3 / raspbian and everything else is working smoothly.

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
