### ISSUE TITLE
[wemo] Discovery service

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7428]
The Wemo binding defines a service `WemoDiscoveryService` in addition to the default UPnP discovery service provided by the core framework. The difference is that the general discovery service is starting an UPnP search through this call:
`upnpService.getControlPoint().search();`
while the Wemo specific service do it through:
`upnpService.getControlPoint().search(new RootDeviceHeader());`
I am asking myself if it was done like that because the standard UPnP discovery is not working for the Wemo UPnP bridge ?

**Comment by jaywiseman1971** [comment]
I worked with Hans extensively to fix the issues with the WeMo binding last April - September 2019.  He wrote it originally years ago and has extensive knowledge of why it was changed to get it to work consistently now.

https://community.openhab.org/u/hmerk

Best, Jay

**Comment by hmerk** [comment]
The WemoDiscovery Service was written cause the standard UPnP search is doing a ST:ALL search but the WeMo devices respond on a ST:RootDevice search only.

**Comment by lolodomo** [comment]
I am just studying why few bindings are using JUPnP rather than the UPnP stuff provided by the openHAB core framework.
That is clear now for the Wemo binding.
Thank you for your explanation.

**Comment by hmerk** [comment]
openHAB core is interfacing JUPnP to make usage simpler and to reduce dependency handling. This wotks great for the basics, but when you need to mock around, cause your device does not follow UPnP standard completely, you have to adress it directly.
