### ISSUE TITLE
[mqtt][moquette] Formally deprecate embedded moquette?

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#7442]
It is generally accepted in the user community that the Embedded MQTT broker has been abandoned by its original developers, and as a few issues have emerged this year, there is a general recommendation not to use it.
https://community.openhab.org/t/mqtt-embedded-broker-advantages/88441/7

The official OH docs remain enthusiastic about it, and new users continue to install it.
https://www.openhab.org/addons/integrations/mqttembeddedbroker/
https://community.openhab.org/t/mqtt-broker-version/97204/2

It's above my pay grade to go adding warning messages to the docs about deprecating it, this I feel is a policy decision for some developer.

**Comment by kaikreuzer** [comment]
Yeah, I agree, it isn't working great and it does not get better over time with the original author not maintaining Moquette anymore :-(.

My suggestion would be to remove this add-on for openHAB 3 (i.e. for current master), but keep it on 2.5.x for backward compatibility reasons - for the ones that currently use it.

And yes, I would also be fine to add a note that it is considered deprecated and be removed in future versions to the docs.

**Comment by splatch** [comment]
FYI HiveMQ ce recently got embedded api: https://github.com/hivemq/hivemq-community-edition/issues/19 :-) just in time!

**Comment by andsel** [comment]
Hi @kaikreuzer, sorry to reply on an closed issue.

Recently (almost 2 years) I worked a lot on Moquette, and re-architected the way it process events. So it's (should be) stable and easy to maintain. Since this comment there have been 3 [releases](https://github.com/moquette-io/moquette/releases) and have been used in AWS greengrass and other IoT projects.

BTW, I'm actually moving forward to support MQTT5 in the broker: https://github.com/moquette-io/moquette/issues/695

Would you reconsider it?

**Comment by kaikreuzer** [comment]
Hi @andsel, nice to hear from you, it has been a while!
Great to hear that Moquette is again under active maintenance. Sure, I still think it would be nice to have an embedded MQTT option in openHAB, so we can consider to bring it back. I am personally not a heavy MQTT user, so I would want to check with the other @openhab/add-ons-maintainers on their opinion. I know that we removed some code in openhab-core as well after dropping the embedded broker option, so it might mean some effort to bring it back.

So @openhab/add-ons-maintainers wdyt? Is anyone interested in bringing the feature back in?
