### ISSUE TITLE
Netatmo Binding support Presence Camera

### ISSUE THREAD

**Issue by Hombre2205** [openhab/openhab-addons#7444]
Netatmo Binding support Presence Camera
Netatmo Presence Camera
Netatmo Binding

Nobody in the community could help me.

## Your Environment
* Version used:Openhab 2.5.3-1

**Comment by Hombre2205** [comment]
HI,

i am absolutely new. 
But i tried to add a Netatmo Presence Camera to Openhab 2. Is there a chance to add it?
I can not choose it in the binding.
My Openhab is installed on an Raspberry Pi3 and openhab is running 2.5.3-1

**Comment by lolodomo** [comment]
Duplicate of #3059
