### ISSUE TITLE
[hue] scan with multiple bridges removes items during scan again

### ISSUE THREAD

**Issue by Marlow925** [openhab/openhab-addons#7451]
In a scenario with multiple Philips Hue Hubs (due to the recommended limitation of max 50 lights per hub), the following is happening:

- when OpenHAB is started fresh, it will scan through all the hubs and discover all the items, that are not defined in things and add these to the inbox.

- if you subsequently rescan the Hue Binding in the inbox, it will discover these items again, but then remove them, as it scans the next hub. Only the items from whatever hub is scanned last will remain in the inbox.

As a result, one has to know, what one wants to add and has to be quick to add these before the scan gets to the next hub. Or completely restart OpenHAB, which is a bit meh.

I am currently running OpenHAB 2.5.4 on Ubuntu 14.04.6 LTS on an ODroid board and that behavior is still present there.

**Comment by lolodomo** [comment]
Ithink this is due to this line:
https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/discovery/HueLightDiscoveryService.java#L140
removeOlderResults should be called with the bridge id as second parameter.
