### ISSUE TITLE
[miio] Error using Xiaomi cloud in miio binding

### ISSUE THREAD

**Issue by antonmarin** [openhab/openhab-addons#7459]
==> openhab.log <==
2020-04-24 08:54:45.437 [INFO ] [miio.internal.cloud.MiCloudConnector] - Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 70016

## Expected Behavior

Just found in logs. I filled creds to mihome, expected that binding will get tokens itself.

Would be great if it will fill tokens from cloud when i add thing

## Current Behavior

When i have humidifier thing in inbox, there is no token filled. Humidifier connected to mihome and credentials filled in binding

## Possible Solution
I'm a newbie, so no idea right now

## Steps to Reproduce (for Bugs)
- install miio binding
- fill creds to mihome (there should be something connected)
- wait for inbox
- add thing from inbox
- view config (should not be a token there)

## Your Environment

* Version used: openHAB 2.5.4 in docker using docker-compose
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Synology 218+
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): DSM 6.2.2-24922 Update 6

**Comment by marcelrv** [comment]
Cloud functionality has been created by reverse engineering the logon process.
Unfortunately the meaning of the error codes returned by the cloud are not known.

**Comment by equake** [comment]
70016 seems to be "wrong password" as I was getting this error consistently and my password was wrong :see_no_evil:

**Comment by antonmarin** [comment]
thanks @equake . I'll check this

**Comment by antonmarin** [comment]
Well. No error, but no token too ))

**Comment by 130s** [comment]
Though with a different device, as I posted in my personal ticket https://github.com/130s/hut_10sqft/issues/466 that I got the same error code, and somehow was able to resolve when I was tinckering the setting on Smart mi's Android app. I don't know what exactly worked.

**Comment by marcelrv** [comment]
@antonmarin do you still have this issue.
In that case, maybe you share a TRACE logging on the cloud login process.

`log:set TRACE org.openhab.binding.miio.internal.cloud`


Note, this log will have some of your personal data in it, please edit the file so the userID & password are changed.
The session keys etc are all one time, so don't believe they are harmful, but you can always replace 1 or 2 charaters with X (please keep the length as original so I can spot possible differences with the usual responses)

**Comment by jirizaloudek** [comment]
I have the same problem and got error: 
```
Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 70016
```

I reset my Xiaomi password and everything start to work.

**Comment by domoticaDude** [comment]
I also had to do a password reset. But afther the reset it worked for 50% The device is found when searching in openhab. But thare is only an ip  filled in. No token. I had to download the old version of the app to find the token.

**Comment by marcelrv** [comment]
@domoticaDude what you describe sounds a lot like it did not have a working cloud connection yet. (or setup for the wrong countries)
Did you see any error messages is the log?

**Comment by domoticaDude** [comment]
> 
> 
> @domoticaDude what you describe sounds a lot like it did not have a working cloud connection yet. (or setup for the wrong countries)
> Did you see any error messages is the log?

Yes i did get Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 70016

**Comment by xduseko** [comment]
Same problem here.

```
Error logging on to Xiaomi cloud (0): Error getting logon location URL. Return code: 0
```

It seems to be working from my home PC but not from cloud VPS. I have switched to trace level and it looks like there is some kind of user verification step that is missing in openhab addon.

```
Xiaomi login step 2 content = &&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=passport&context=sMlx600MPFo9smESNZmGDdkmc7e2Z4sYqW81z2t4F3LTh9vz7gf0sNeze4znW9ytwEsqYzgWj0KQ1dl2CDw9Sne6w9qMFRCC6zg0de7L_8y-8xeaHHo6nn35dLNtMQOi8NvYi-RGx0rkivMCpbaPnsFYzDoRliupXK-Ox_r5MWElldDjtKTCY2mxQGinj_eAQdcERP5iV2wG2TqxQdy3AdXAKmfyg6y044u1491wG7tosQAIQriMFmPnhZqBzQjNN8rBmHfnogcvbfxGV0-eqRJTN4XemWcLkO_lLNB0sC26tx4W1rQ2chwK1v5N3DOxJxGofmuXkmq1VqVBqFp7DdVWoy5nGsZnI3CK0WT9cfTQWCXpOeYyJRWGkLP35irZRlgQ5cakPLzARHzc80X339akC_IkTEOJvMtXL4pOlNEZRP2kfBVKhtD9jHYDT_4N1CQlg4OXeJMVWAN6Jn0xUC9RfX6p8QxjxeoLx3reCxV-4Cvgz8yOsCndaSyzfWdym4tWlIR4fNeeaq_nX6NQLDDsmv4k2mPEWHZACry9iF5w85fvRmTB6Tlr3NVGBb4xKOZCRcJUXkN9PiCwWcpZqwAh9qoMIi4b2-HYgBejOGbr8GojeZbU_-19bsTdVU5eJCEeusGP9B_WQwgYrbfnCJJCbJCKjOydE2Ddyvd7bRxxicG-0fdD_eusuboHJre5vC9Ff9vkJ1rFEyDVdOwSmohAhjVLTEG6IhHfFWFSlTyHdYCQyMvHe4WPhusrRf6r&_locale=de_DE","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}
```

```
{
  "notificationUrl": "https://account.xiaomi.com/identity/authStart?sid=passport&context=sMlx600MPFo9smESNZmGDdkmc7e2Z4sYqW81z2t4F3LTh9vz7gf0sNeze4znW9ytwEsqYzgWj0KQ1dl2CDw9Sne6w9qMFRCC6zg0de7L_8y-8xeaHHo6nn35dLNtMQOi8NvYi-RGx0rkivMCpbaPnsFYzDoRliupXK-Ox_r5MWElldDjtKTCY2mxQGinj_eAQdcERP5iV2wG2TqxQdy3AdXAKmfyg6y044u1491wG7tosQAIQriMFmPnhZqBzQjNN8rBmHfnogcvbfxGV0-eqRJTN4XemWcLkO_lLNB0sC26tx4W1rQ2chwK1v5N3DOxJxGofmuXkmq1VqVBqFp7DdVWoy5nGsZnI3CK0WT9cfTQWCXpOeYyJRWGkLP35irZRlgQ5cakPLzARHzc80X339akC_IkTEOJvMtXL4pOlNEZRP2kfBVKhtD9jHYDT_4N1CQlg4OXeJMVWAN6Jn0xUC9RfX6p8QxjxeoLx3reCxV-4Cvgz8yOsCndaSyzfWdym4tWlIR4fNeeaq_nX6NQLDDsmv4k2mPEWHZACry9iF5w85fvRmTB6Tlr3NVGBb4xKOZCRcJUXkN9PiCwWcpZqwAh9qoMIi4b2-HYgBejOGbr8GojeZbU_-19bsTdVU5eJCEeusGP9B_WQwgYrbfnCJJCbJCKjOydE2Ddyvd7bRxxicG-0fdD_eusuboHJre5vC9Ff9vkJ1rFEyDVdOwSmohAhjVLTEG6IhHfFWFSlTyHdYCQyMvHe4WPhusrRf6r&_locale=de_DE",
  "result": "ok",
  "code": 0,
  "captchaUrl": null,
  "description": "成功",
  "location": "",
  "securityStatus": 16,
  "pwd": 0,
  "child": 0,
  "desc": "成功"
}
```

![image](https://user-images.githubusercontent.com/9591957/198335686-05414938-e27a-4f9a-9c9d-7777fe43bf56.png)

![image](https://user-images.githubusercontent.com/9591957/198335936-de955e92-d9a9-4f03-89c1-d4026d13ad1b.png)

![image](https://user-images.githubusercontent.com/9591957/198336520-1f0b6a81-038b-491f-a65c-ab9db5ce38d8.png)

Unfortunately completing the verification flow using home PC browser doesn't help. Openhab addon is still unable to logon. It could be connected to an IP address or something like that.
