### ISSUE TITLE
[shelly] implement Shelly Vintage

### ISSUE THREAD

**Issue by fab33** [openhab/openhab-addons#7468]
I have a shelly vintage currently not supported by the binding.
output of /status with max power (6W) : 
```
{"wifi_sta":{"connected":true,"ssid":"Fab-Domo","ip":"192.168.2.103","rssi":-45},"cloud":{"enabled":false,"connected":false},"mqtt":{"connected":true},"time":"14:26","unixtime":1587824789,"serial":1,"has_update":false,"mac":"ECFABC6EE918","lights":[{"ison":true,"has_timer":false,"timer_remaining":0,"brightness":100}],"meters":[{"power":6.00,"is_valid":"true","timestamp":1587824789,"counters":[6.000, 6.000, 6.000],"total":84}],"update":{"status":"idle","has_update":false,"new_version":"20200309-103920/v1.6.0@43056d58","old_version":"20200309-103920/v1.6.0@43056d58"},"ram_total":50544,"ram_free":39680,"fs_size":233681,"fs_free":164154,"uptime":900}`
and /settings : 
`{"device":{"type":"SHVIN-1","mac":"ECFABC6EE918","hostname":"ShellyVintage-6EE918","num_outputs":1},"wifi_ap":{"enabled":false,"ssid":"ShellyVintage-6EE918","key":""},"wifi_sta":{"enabled":true,"ssid":"Fab-Domo","ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"mqtt": {"enable":true,"server":"mqtt.lan:1883","user":"fab_33","id":"ShellyVintage-6EE918","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":60,"max_qos":0,"retain":false,"update_period":30},"coiot": {"update_period":15},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":false,"unprotected":false,"username":"admin","password":"admin"},"pin_code":"","name":"","fw":"20200309-103920/v1.6.0@43056d58","discoverable":true,"build_info":{"build_id":"20200309-103920/v1.6.0@43056d58","build_timestamp":"2020-03-09T10:39:20Z","build_version":"1.0"},"cloud":{"enabled":false,"connected":false},"timezone":"Europe/Paris","lat":46.580200,"lng":0.340380,"tzautodetect":true,"tz_utc_offset":7200,"tz_dst":true,"tz_dst_auto":true,"time":"14:28","unixtime":1587824908,"hwinfo":{"hw_revision":"prod-2019-12","batch_id":0},"mode":"white","transition":5000,"lights":[{"ison":true,"brightness":18,"default_state":"last","auto_on":0.00,"auto_off":0.00,"schedule":false,"out_on_url":"","out_off_url":"","schedule_rules":[]}],"night_mode":{"enabled":false, "start_time":"00:00", "end_time":"00:00", "brightness":0}}
```

**Comment by markus7017** [comment]
please try https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.5-SNAPSHOT.jar?raw=true

**Comment by markus7017** [comment]
what are min/max for the color temp?

**Comment by fab33** [comment]
> what are min/max for the color temp?

You can't change color temp. I will try tomorrow your SNAPSHOT. Can you give me channels for textual configuration ?

**Comment by markus7017** [comment]
check README

**Comment by fab33** [comment]
Nothing about Shelly-vintage in README here perhaps under a particular tag ?

**Comment by fab33** [comment]
I try the JAR you provide and It doesn't seem to work :
`10:28:08.976 [INFO ] [ig.discovery.internal.PersistentInbox] - Added new thing 'shelly:unknown:6ee918' to inbox.
10:28:08.976 [INFO ] [smarthome.event.InboxAddedEvent      ] - Discovery Result with UID 'shelly:unknown:6ee918' has been added.
`

**Comment by markus7017** [comment]
please re-check, provided a new build

**Comment by fab33** [comment]
I have only one warning :
`23:12:02.571 [WARN ] [ore.thing.internal.ThingFactoryHelper] - Could not create channels for channel group 'white' for thing type 'shelly:shellyvintage:lampevintage1', because channel group type 'shelly:whiteSettingsSimpe' could not be found.`
So I can't change brightness.
But all others channels seems to work.

**Comment by markus7017** [comment]
ok, typo fixed, README updated

**Comment by markus7017** [comment]
please send me a copy&paste of coapDescr in the thing properties

**Comment by fab33** [comment]
Sorry for late response :
`coapDeviceDescr | {"blk":[{"I":0,"D":"Channel0"}],"sen":[{"I":121,"T":"S","D":"State","R":"0/1","L":0},{"I":111,"T":"S","D":"Brightness","R":"0/100","L":0},{"I":141,"T":"P","D":"Power","R":"0/6","L":0},{"I":211,"T":"S","D":"Energy  counter 0 [W-min]","L":0},{"I":212,"T":"S","D":"Energy counter 1  [W-min]","L":0},{"I":213,"T":"S","D":"Energy counter 2  [W-min]","L":0},{"I":214,"T":"S","D":"Energy counter total  [W-min]","L":0}]}
`
It's the first time I use a shelly lamp (I mostly have milight), and there is no switch item to send ON/OFF to lamp ? Only the dimmer ?

**Comment by markus7017** [comment]
On/off is part of the brightness channel, you could link 2 channels to it
- a Switch, which acts as on/off
- a Number, which receives the brightness in %

This confirms to the OH DimmableLight thing type class, do ask me why this has to be one channel, but it was requested by review.

Does the last version discovery the thing properly?

**Comment by fab33** [comment]
Yes sorry, last version works fine.

**Comment by markus7017** [comment]
did you tried all functions?

**Comment by fab33** [comment]
With brightness item, when I wend ON/OFF or 0-100 value, it's ok. But INCREASE doesn't work as I excepted. If Brightness is 0 and I send INCREASE, Brightness switch to 100. If Brightness is different from 0 when I send INCREASED it increased last value by 5. I would like when brightness is 0 and send INCREASE to set value to 5 (or better a parameter value !). For other channels, I continue my tests.

**Comment by markus7017** [comment]
I always use the brightness set in the device. INCREASE/DEcREASE doesn‘t have a parameter AFAIK

If you want to set it to 5 when it‘s 0 just send 5 to the brightness channel.

**Comment by F43RY** [comment]
Hi,
just arrived a new shelly vintage and got "Unknown device" under PaperUI.
openhab Version:     2.5.6 (Build)
bundle:list
252 │ Active │  80 │ 2.5.6                   │ openHAB Add-ons :: Bundles :: Shelly Binding

No problems with other 8 shellies (2.5, EM, PM ecc)

Thanks for any help
![shelly_vintage](https://user-images.githubusercontent.com/4217502/85797767-8c6b8980-b73c-11ea-97a2-5cbb6fc52c28.png)

**Comment by markus7017** [comment]
check out DEV build 2.5.7, just tested various models yesterday
