### ISSUE TITLE
[WARN ] [ab.binding.mqtt.generic.ChannelState]  not supported by type 'NumberValue'

### ISSUE THREAD

**Issue by neurax6** [openhab/openhab-addons#7483]
Hi 

Trying to setup a tamostised sonoff pw r2 in openhab using mqtt and json parsing. Seems pretty straight forward but only the first entry is visible in the board. All the other display : NaN

Using:
 JSONPATH:$.ENERGY.Voltage
 JSONPATH:$.ENERGY.Current
 JSONPATH:$.ENERGY.Total
 JSONPATH:$.ENERGY.Today
 JSONPATH:$.ENERGY.Yesterday
 JSONPATH:$.ENERGY.Power
 JSONPATH:$.ENERGY.ApparentPower
 JSONPATH:$.ENERGY.ReactivePower

Getting a bunche of this in my openhab.log
2020-04-26 17:36:28.652 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '{"Time":"2020-04-26T16:36:28","ENERGY{"TotalStartTime":"2020-03-01T18:50:05","Total":50.051,"Yesterday":3.239,"Today":1.788,"Period":2,"Power":139,"ApparentPower":153,"ReactivePower":63,"Factor":0.91,"Voltage":120,"Current":1.275}}' not supported by type 'NumberValue'

**Comment by Dorme** [comment]
I have the same setup (tamostised device, mqtt and json parsing) and when I configured it, I first forgot to install the JsonPath Transformation Service. After installing it, it was working perfect with the same transformations as you describe.

**Comment by bodiroga** [comment]
Hi @neurax6!

Have you tried installing the JSON Transformation Service? As @Dorme has told you, it should fix your problem :wink:

**Comment by neurax6** [comment]
Hi guy late respond.

I'm already running JSON Transformation pluggin.  Already run a uninstall/reinstall of the plugin without result.
Running transformation-jsonpath - 2.5.4

I'm getting partial result its pretty weird some data  seem to be extracted other dont. 

![image](https://user-images.githubusercontent.com/9092245/81183741-84357000-8f7d-11ea-9f60-0fd800eea8b2.png)

**Comment by Dorme** [comment]
NaN means it's 'Not A Number'... could you change the Thing to a String to see what the information is you are receiving?

**Comment by neurax6** [comment]
![image](https://user-images.githubusercontent.com/9092245/81189102-2d7f6480-8f84-11ea-9199-7eaca5c151d7.png)


in openhab.log different message.

2020-05-06 10:21:07.604 [WARN ] [ofiles.JSonPathTransformationProfile] - Could not transform state '122' with function 'JSONPATH:$.ENERGY.Voltage' and format '%s'

2020-05-06 10:22:07.591 [WARN ] [ofiles.JSonPathTransformationProfile] - Could not transform state '{"Time":"2020-05-06T09:22:07","ENERGY":{"TotalStartTime":"2020-03-01T18:50:05","Total":86.028,"Yesterday":
4.581,"Today":0.888,"Period":4,"Power":242,"ApparentPower":262,"ReactivePower":102,"Factor":0.92,"Voltage":122,"Current":2.151}}' with function 'JSONPATH:$.ENERGY.Current' and format '%s'

**Comment by neurax6** [comment]
Sure!
Pretty weird result, Only Voltage work with number. Other string give me different result over time most of the time its a --(without any log error) sometime its the whole json string data(with log error).
![image](https://user-images.githubusercontent.com/9092245/81196829-8a334d00-8f8d-11ea-9892-29440e7b57af.png)

There is my config

![image](https://user-images.githubusercontent.com/9092245/81197075-db434100-8f8d-11ea-88c1-c957e0f01c86.png)

![image](https://user-images.githubusercontent.com/9092245/81197208-02017780-8f8e-11ea-89dc-8cc1884f2547.png)
![image](https://user-images.githubusercontent.com/9092245/81197387-2fe6bc00-8f8e-11ea-991f-19dc4c2930dd.png)
![image](https://user-images.githubusercontent.com/9092245/81197627-83590a00-8f8e-11ea-9424-e6197884b608.png)

![image](https://user-images.githubusercontent.com/9092245/81197767-adaac780-8f8e-11ea-977e-277482c064cd.png)

**Comment by bodiroga** [comment]
So the "JSONPATH:$.ENERGY.Voltage" transformation works, but the "JSONPATH:$.ENERGY.Current" doesn't? Ummmm... perhaps it is related to the decimal point in the current value, because the voltage has an integer value :thinking:

Can you show as the edit screen of the mqtt:topic:a87d5471:Current channel? :+1:

**Comment by neurax6** [comment]
![image](https://user-images.githubusercontent.com/9092245/81202362-7ccd9100-8f94-11ea-8ac8-27f35b8a0bec.png)

**Comment by Dorme** [comment]
Your configuration seems to be the same as mine:

![image](https://user-images.githubusercontent.com/3600370/81213093-2e40e680-8fd6-11ea-800e-df6036a4768c.png)

**Comment by neurax6** [comment]
Thanks all for your time . I've moved in with a temporary solution. Im already pushing a lot of date from i2c sensor using python and mqtt server. So i create a parser for my tasmota, republishing all the data each on her own mqttchannel.  I've rebuil the whole panel with classic mqtt pull on publish and its seems to work all fine.  
![image](https://user-images.githubusercontent.com/9092245/81214626-1fdad680-8fa6-11ea-82e3-c68a3f1c75ed.png)

**Comment by hmerk** [comment]
closed as seems to be solved
