### ISSUE TITLE
How to debug with Paper UI ?

### ISSUE THREAD

**Issue by clinique** [openhab/openhab-addons#75]
I'm porting Freebox binding to oh2 - most is done but I would like to test discovery and inbox function on it. Only classic ui is currently available in IDE, then ...question in the title :)

**Comment by paulianttila** [comment]
I have started to port binding from OH1 to OH2 as well. I fetched latest paper-ui from Dennis repo, but it's seems to be broken. I see that you Dennis have made few massive commits in few days, so I assume that it's broken in purpose? Could you inform when it should work again? It would be much more easier to use UI than commands on the console.

**Comment by dnobel** [comment]
Hi, yes at the moment I´m completely rewriting the Paper UI. It also uses the latest changes of another branch of ESH. Hopefully this branch will be merged until the beginning of the next week. After this the Paper UI should be compatible to the the latest openHAB build. 

But please be aware, that I´m developing the Paper UI actively and the branch is not stable. Maybe with the next release of openHAB the Paper UI will be contributed to the project. Then it should be stable and can also be developed and extended by other people.

**Comment by Stratehm** [comment]
Hi, 
First of all, good job for the Paper UI GUI. Really beautiful.

I have a question about the items rendering (I do not know if it is the right place but I have not found another way to ask the question): Is the Paper UI rendering based on the items definitions (files *.item) or on the sitemaps definition (files *.sitemap) ?

If it is based on the items definition, is there a way to configure the item rendering. A concrete example:
I have a Dimmer item to control a volume level. The default dimmer on Paper UI has a slider to control the level and a switch. Is there a way to remove the switch ?

Thank you.
