### ISSUE TITLE
[goecharger] phases count is wrong on single phase charge

### ISSUE THREAD

**Issue by dahuafschmied** [openhab/openhab-addons#7501]
Problem:
Single Phase Charging shows Phases: 3

fixed Problem:
show Phases: 1

Problem is the Phases are counted with power>0 but the idle 2 Phases are showing 0.1kW

![go-e](https://user-images.githubusercontent.com/3955019/80591707-6e282c80-8a1e-11ea-9c6a-e5fd3e51db7b.png)

**Comment by SamuelBrucksch** [comment]
Thanks for the issue. I got my goecharger before i moved to the new house, so i could only do some basic tests. Guess i will add a check, if the value is below 6A or so, as the minimum charge power is 6A.

**Comment by SamuelBrucksch** [comment]
I just checked it and for me it shows 0W for not used phases. Are you on latest firmware? Which car do you use? Can it also charge with more than 1 phase but reduces because of limited power or so?

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
