### ISSUE TITLE
[somfytahoma] Somfy Thermostat show target temperature

### ISSUE THREAD

**Issue by Numberone77** [openhab/openhab-addons#7508]
## Expected Behavior

Somfy Thermostat Handeler should update item linked to core:DerogatedTargetTemperatureState, should be updated like the items core:BatteryLevelState and core:RSSILevelState.
## Current Behavior

Item linked to core:DerogatedTargetTemperatureState is not updated.
## Possible Solution

No Idea
## Steps to Reproduce (for Bugs)

1. Add Somfy Thermostat Thing manually and configurate it with the correct io-adress.
2. Add via Paper-UI a iten to the channel Target Temperature

## Context

I would like to see the target temperature set.

## Your Environment

OpenHAB 2.5.4 on a openhabian

**Comment by octa22** [comment]
Hi,

can you provide me with your get setup response or the trace log of the Somfytahoma binding initialization? I need to see what states and commands the termostat exposes, since I do not have this device. Currently no channel is bound to _core:DerogatedTargetTemperatureState_, target_temperature channel is bound to _core:TargetTemperatureState_
Thanks
Ondrej

**Comment by Numberone77** [comment]
Dear Ondrej,
Do no not know what you need. Could you please guide me, to get the logs you need.
Cheers Matthias

**Comment by octa22** [comment]
Hi, it's been a long time -what exactly do you need?
I can add a new temperature channel called _derogated_temperature_, which will be bound to _core:DerogatedTargetTemperatureState_
Is this what you need? Thanks.

**Comment by octa22** [comment]
This might help to investigate your problem:
1) remove the thermostat thing from PaperUI
2) uninstall the bundled spmfy tahoma binding
3) download https://www.dropbox.com/s/yp1i69y2tlqjhef/org.openhab.binding.somfytahoma-2.5.11-SNAPSHOT.jar?dl=1
4) install the .jar to the addon directory
5) rediscover somfy tahoma things 
6) send me the openhab.log containing information about unsupported device

thanks.
Ondrej

**Comment by lolodomo** [comment]
@octa22 : as there was no answer from @Numberone77  since many months, do we close that feature request or do you like to keep it opened?

**Comment by Numberone77** [comment]
Issue can be closed. Functionality is implemented in OH3 and is working since M3.0.5

**Comment by lolodomo** [comment]
Feature implemented.
