### ISSUE TITLE
[InfluxDB] Migrate InfluxDB Add-On to v3

### ISSUE THREAD

**Issue by mbaehr2909** [openhab/openhab-addons#7515]
With OpenHAB 3.0 dropping support for v1 Add-Ons, the InfluxDB Add-On should be ported over to v3.
Are there any plans on doing so at this time?

**Comment by kaikreuzer** [comment]
It's already part of openHAB 3: https://github.com/openhab/openhab-addons/tree/master/bundles/org.openhab.persistence.influxdb

**Comment by mbaehr2909** [comment]
Alright!
Thanks for the quick answer!
