### ISSUE TITLE
[Homematic] Please support Wired devices HmIPW-DRS8 and HmIPW-DRS4

### ISSUE THREAD

**Issue by hoegertn** [openhab/openhab-addons#7545]
Hi,

please support the HomeMatic IP Wired components HmIPW-DRS8 and HmIPW-DRS4. They show up as unknown devices and the current state of the relais is not mirrored to the item.

**Comment by MHerbst** [comment]
Hi @hoegertn 

generally, it is not necessary to add new devices to the Homematic binding. The binding contacts the CCU and retrieves information from the CCU about all connected devices and their data points. Based on this information the things and their channels are created in openHAB. The only information that can't be retrieved from the CCU is the product name of the device and description. Therefore this information is missing for new devices until they are added to some properties file.

If I understand your post correctly, the devices are detected by the binding, and things can be created successfully. Do the created channels look correctly?

> current state of the relais is not mirrored to the item.

What exactly do you mean? Did you create an item and the state is not updated if you switch the relay? Can you switch the relay from openHab? How did you define the item. Sometimes the HM devices provide similar data points in different "channel groups" but they work different.

Depending on your information we probably need some trace outputs.

**Comment by hoegertn** [comment]
I can switch the relay on/off from the PaperUI but if I enter the Control panel the current state of the relay is not reflected. It is always shown as off. The same is true for the HMIP-PS power outlet.

What info do you need?

**Comment by MHerbst** [comment]
Can you add it to a sitemap and test whether it is updated in Basic UI? Is the state updated if you refresh the sitemap in the browser? It seems that sometimes the switch states are not automatically updated in Paper UI (and I had the same effect in Basic UI), but after manual refresh the state was correct.

If this does not help please active the TRACE log mode for the Homematic binding, change the state of the device e.g. from CCU and attach openhab.log with the trace output. If openHAB received a message from the CCU it should appear in the log.

If no message appears, it could be a problem with the firewall setting on the machine where openHAB is running. Ports 9125 and 9126 need to be open for receiving messages from the CCU.

**Comment by hoegertn** [comment]
Ok, I have no idea why, but now it is working. It was not showing the State via the REST API either so refresh was not the problem. But know it is working fine using the PaperUI and the REST API. Maybe some restart fixed some listeners.

Where can the product names be updated so it would show up with the correct description?

**Comment by MHerbst** [comment]
It seems that sometimes the communication between the binding and the CCU stops working. Especially if HM IP devices are used.

But good to hear that it's working now.

> Where can the product names be updated so it would show up with the correct description?

They are part of the binding and stored in the two properties files extra-descriptions.properties and extra-descriptions_de.properties. You can find them here https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.binding.homematic/src/main/resources/homematic

**Comment by hoegertn** [comment]
I created a PR #7557 with some more HmIP names. I will close this and it was resolved.
