### ISSUE TITLE
[pushover] Sending to Pushover stopped working

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-addons#7567]
## Expected Behavior
Having the following row in a rule should send me a Pushover message:
sendPushoverMessage(pushoverBuilder("Just testing!"))

## Current Behavior
I get the following in my log:
13:40:02.327 [ERROR] [untime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'pushovertest': The name 'sendPushoverMessage' cannot be resolved to an item or type; line 10, column 5, length 54

## Context
I'm not really sure when this stopped working, but I'm sure it has worked on 2.5.something. I haven't changed anything in my config related to this. At least one other person is affected by the same problem, see [https://community.openhab.org/t/pushover-action-stopped-working/96779](url). An openhab restart didn't make any difference for me.

## Your Environment
* Version used: openHAB 2.5.4, Pushover addon 1.14.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Oracle Java 8u201
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Debian 8.11 on arm32

**Comment by DanielMalmgren** [comment]
Just for the record: Also tried restarting the binding and sending a message with debug turned on, which gives no further indication on what's wrong. Pasting output:

> 15:23:11.429 [DEBUG] [shover.internal.PushoverActionService] - Pushover action service deactivated
15:23:11.444 [DEBUG] [n.pushover.internal.PushoverActivator] - Pushover action has been stopped.
15:23:11.474 [DEBUG] [shover.internal.PushoverActionService] - Pushover action service activated
15:23:11.497 [DEBUG] [shover.internal.PushoverActionService] - Configuration file is being parsed.
15:23:11.507 [DEBUG] [shover.internal.PushoverActionService] - Configuration data exists. Parsing the paramaters.
15:23:11.509 [DEBUG] [n.pushover.internal.PushoverActivator] - Pushover action has been started.
15:25:02.688 [ERROR] [untime.internal.engine.ExecuteRuleJob] - Error during the execution of rule 'pushovertest': The name 'sendPushoverMessage' cannot be resolved to an item or type; line 10, column 5, length 54

**Comment by cweitkamp** [comment]
@DanielMalmgren Do you think we can close this issue as we now have a new OH3 binding?

**Comment by DanielMalmgren** [comment]
Absolutely. It works fine in OH3. Thanks for a great job! Closing.
