### ISSUE TITLE
MIIO - continuously increasing number of Threads

### ISSUE THREAD

**Issue by jenicek001** [openhab/openhab-addons#7583]
## Expected Behavior
Fixed number of MIIO threads (regardless of number of MIIO Things and if they are on-line or off-line).

## Current Behavior
After upgrade to OpenHAB version 2.5.4 (Release build) the system stopped working after approx. 12 hours in my configuration. I started monitoring CPU_Threads (under Systeminfo) + CPU_Load1 + CPU_Load5 + CPU_Load15 + Memory_Used_Percent and discovered they are continuously growing. When number of threads reaches approx 4200, the system stops responding, I solved by manual openhab restart.
I prepared a parallel system (both Raspberry Pi w. Raspbian), same config, same behaviour.
I started monitoring details in Karaf: shell:threads --list | grep Mi
output:
1522 x Mi IO MessageSenderThread                                                                     x TIMED_WAITING
...
...
...

shell:threads returns high number of these:
"Mi IO MessageSenderThread" Id=6171 in TIMED_WAITING
    at java.lang.Thread.sleep(Native Method)
    at org.openhab.binding.miio.internal.transport.MiIoAsyncCommunication$MessageSenderThread.run(MiIoAsyncCommunication.java:228)

I started removing all offline devices and number of threads stopped growing - just a constant number of threads (shell:threads --list | grep Mi | wc -l)
restart of the system just confirmed.

Whenever I added any MIIO device (e.g. a ceiling lamp), configured Thing token - just one new thread was added.

But - whenever I switched off the ceiling lamp, the number of threads started increasing again (approx. 1 new thread per (switched off) MIIO device per 1 minute)

With my home config with total 25 MIIO devices this leads to a max system lifetime 12hours until the system reaches the maximal number of threads and has to be restarted.

## Possible Solution

Seems that MIIO is creating threads for off-line devices, which never stops and are never deallocated. Used memory is also continuously increasing.

## Steps to Reproduce (for Bugs)

1. Configure a MIIO Thing (e.g. ceiling lamp) - I use Automated search and Inbox
2. Configure Token for this device (BTW no tokens are got automaticcaly from Mi Cloud)
3. in Karaf: shell:threads --list | grep Mi
4. or count number of lines: shell:threads --list | grep Mi | wc -l
5. repeat line 4 - a constant number will be visible
6. switch the device (ceiling lamp) off (from electricity)
7. repeat line 4 - a growing number will be visible (approx increase 1 per off-line device per minute)

## Your Environment

Version used: OpenHAB 2.5.4 release with MIIO binding addon
Environment name and version: (Chrome 81.0.4044.138, Zulu8, Node.js v12.16.3)
Operating System and version (Raspberry Pi 4B, Raspbian Buster Lite 2020-02-13-raspbian-buster-lite.zip - with all apt up-to-date)

**Comment by lolodomo** [comment]
Ok, I think I probably found something.
One thread with name "Mi IO MessageSenderThread" is created by the class `MiIoAsyncCommunication` each time it is instantiated. It is instantiated only by getConnection() in `MiIoAbstractHandler`. If the ping does not answer, close() is not called on this instance, meaning the thread is not interruped.
I am going to propose a possible fix for that.

**Comment by lolodomo** [comment]
Looking at the binding code (thing handlers), I found another weird thing: the MiIoVacuumHandler is directly establishing a connection in its constructor ! This kind of thing should certainly be done in initialize().

**Comment by OliverHi** [comment]
Is there already a way to use the fixed version? Otherwise when will it be released? Just asking because I love having this binding but I can not use it currently, as it will crash my Raspberry Pi after a  couple of days.

**Comment by lolodomo** [comment]
It is included in 2.5.5.

**Comment by OliverHi** [comment]
Thank you very much. I updated to 2.5.5 and have no more problems.

**Comment by jenicek001** [comment]
Thank you, after update to OpenHAB version 2.5.5 problem solved.
Jan

po 25. 5. 2020 v 17:12 odesílatel OliverHi <notifications@github.com>
napsal:
