### ISSUE TITLE
[somfytahoma] Error when using dimmer on sitemap

### ISSUE THREAD

**Issue by coop-git** [openhab/openhab-addons#7584]
Expected Behavior
Value sent from dimmer should be handled without errors by the Somfy Binding.
Item is created with the following channel : {channel="somfytahoma:awning:ID:control"}

Current Behavior
When using a dimmer on a sitemap for this item, I get the following error
 Apply command response: {"errorCode":"INCOMPATIBLE_VALUE","error":"setDeployment() : Invalid value for command parameter p1 : expected integer value between 0 and 100 but got 30.0"}
Tested with HABPanel and that works fine.

Possible Solution
Accept or convert the received value.

Steps to Reproduce (for Bugs)
1. Add the Somfy binding, thing and item. See example of channel above.
2. Add the item to a sitemap and a panel
3. Assign a value via sitemap : NOK / Assign a value via HABpanel : OK

Context
When using multiple devices in and outside the house, sitemaps are easier and  lighter thann habpanel.

Your Environment
Debian Buster, virtualised via ProxMoxx. 
Separate VLAN for all IoT related things
OH 2.5.4

**Comment by octa22** [comment]
please paste here a portion of your .items file and .sitemap file. There must be problem with your environment or setup, sitemaps work fine and no conversion is necessary when dimmer is used.

**Comment by coop-git** [comment]
`Items`
Dimmer BrustorDimmer "" {channel="somfytahoma:awning:b4ec2e7e:788fca8e-f2cc-4397-8afe-1562a92b1ed1:control"}
`Sitemap`
Slider item=BrustorDimmer label="Brustor" minValue=0 maxValue=100 step=10 icon="sun"

I hope this is enough for you.

**Comment by Rossko57** [comment]
So far as I can see, it is legitimate for a Dimmer Item to accept non-integer commands like 27.5
Historically, UIs using sliders etc. have produced integer commands, but this is not a requirement, decimal commands are acceptable.
The binding should accept non-integer values for dimmer commands. (There are/were several bindings that do not)
https://community.openhab.org/t/solved-slider-items-with-new-android-app-2-8-0-not-working-anymore/79344/47

**Comment by octa22** [comment]
OK, if this is afecting only Android, that's why I cannot reproduce the bug. IOS works fine.
Can you please try this version?
https://www.dropbox.com/s/ix5y4lqy2bjcoud/org.openhab.binding.somfytahoma-2.5.5-SNAPSHOT.jar?dl=1
Thanks.
Ondrej

**Comment by coop-git** [comment]
Copied it to addons directory.
Removed binding, installed binding.
Awning is working, thank you.
No error in logs as well.
