### ISSUE TITLE
[miio] Bridge configuration

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#7593]
I prefer textual configuration instead of UI setup. Because the binding allows textual declaration of, i would also expect the binding/bridge to be setup the same way. Not sure if it is available or not, but at least the documentation is not mentioning it. 

Something like:

```
Bridge miio:cloud "Bridge Label" [user ="", pass="", country=""] {
    Thing miio:basic:light "My Light" [ host="192.168.x.x", token="put here your token", deviceId="0326xxxx" ]
    }
```

**Comment by marcelrv** [comment]
No this is indeed not possible. It is at binding level atm. 
You can do text setup of binding properties as well. You would need to look at the forum https://community.openhab.org/t/xiaomi-robot-vacuum-binding/31317/1432

Background for not developing it in the suggested way (bridge) is 2 fold:
1) Adds technical challenges as the whole authorizations is heavily relying on cookies, which are for jetty shared amongst the instances. Hence without some special ways or by using different http lib (non-standard for OH) you would be able to work around that.
2) not sure how the cloud is reacting to multiple logons on the same account. As there is no clear documentation and errors are cryptic at best I wanted to avoid additional causes of issues.
