### ISSUE TITLE
[lgwebos] Problem with channel number as identifier

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7623]
As a reminder, we have the channel `channel` which state/command is the channel number.
A user reported that he got several channels with the same channel number, which is in fact possible with TV channels of different types. The channel number is not a good identifier. That is why LG created the channel id.

Rather than considering the channel number, I suggest to consider the channel id returned by the LG webOS API. The state of this channel would become the channel id.

In UIs, the display would be unchanged for the selection widget, the option will be displayed (option label unchanged with channel number and channel name but option id would be set to the channel id). For a text widget, of course, the display would be the channel id rather than the channel number.

For compatibility reasons, we should keep the ability to receive channel number as command for this channel. So we would search for the channel considering the received command first as a channel id and if not found as a channel number.

To help the user identifies the channel ids, I would display them in the appropriate console command (PR already created but should be updated).

The change is very easy.

@sprehn : WDYT ?

**Comment by sprehn** [comment]
agreed
