### ISSUE TITLE
[sonos] Support of Sonos Radio

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7657]
Sonos introduced a new service named Sonos Radio.
Compatibility of the binding with this new feature has to be checked.
Feadback is welcome,
I have not yet enabled this new service myself.

**Comment by lolodomo** [comment]
As there was no complaint and no answer, I assume the binding is already working with Sonos Radio service.

**Comment by sbushnell** [comment]
As per my reply in #13208 it is 'Radio App' and not Sonos Radio
