### ISSUE TITLE
Z-Wave: Lock status change is not processed for Yale Deadbolt

### ISSUE THREAD

**Issue by grizzlyjere** [openhab/openhab-addons#770]
This applies to the "Yale Real Living Touchscreen Deadbolt" model YRD-220 - I'm not sure if it applies to other Yale Z-Wave Locks.

When it is locked or unlocked from the device, OpenHAB does not process the change in the lock status.  It appears that the lock sends an alarm to notify state changes which OH2 is not able to understand.

When unlocked, the logs show:
`[ERROR] [col.security.ZWaveSecureNonceTracker] - NODE 9: Device message contained nonce that is unknown to us, id=0xEB, table={}, expiredList=[], usedList=[-35, -118, -88, -87]
[ERROR] [.commandclass.ZWaveAlarmCommandClass] - NODE 9: Unknown Alarm Type = 22, ignoring report.`

and on a lock, it reports:
`[ERROR] [col.security.ZWaveSecureNonceTracker] - NODE 9: Device message contained nonce that is unknown to us, id=0xFE, table={}, expiredList=[], usedList=[-118, -88, -87, -21, -115, -56, 26, 74, -29, -123]
[ERROR] [.commandclass.ZWaveAlarmCommandClass] - NODE 9: Unknown Alarm Type = 21, ignoring report.`

I've also seen the lock report alarm type 19, 25, 24, 34 but I haven't yet been able to figure out what these all mean (as well as confirm that 21/22 is always lock/unlock).

I'm not sure if the best approach is to use the alarms to update the lock status, or use it as an indication to requery the lock (I'm assuming this is possible in zwave?)

**Comment by grizzlyjere** [comment]
I found a reference to what should be the alarm codes and typed them up
[Yale Lock Alarm Codes.pdf](https://github.com/openhab/openhab2-addons/files/191253/Yale.Lock.Alarm.Codes.pdf)

**Comment by cdjackson** [comment]
I propose we close this until the security classes are supported. This may also be resolved once the notification class is merged (soon I hope).
