### ISSUE TITLE
[homekit] home app lose the room assignment

### ISSUE THREAD

**Issue by yfre** [openhab/openhab-addons#7701]
home app loses time-to-time the assignment of devices to the rooms.  it looks like that this happened on openHAB restart or on items changes.  but it doesnot happened always, just sometimes. 

it was also reported by other users.
it looks like this old issue is relevant. potentially the same fix can help here.
https://github.com/openhab/openhab-addons/issues/929

**Comment by J-N-K** [comment]
Unfortunately, since https://github.com/eclipse-archived/smarthome/issues/1896 ist still not resolved, there is no such event.

That‘s probably why the idea of the configurable delay (default 30s) was born in the issue you linked.
