### ISSUE TITLE
bridgeStatusChanged must not be called by the bridge handler

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7704]
Call to bridgeStatusChanged for any thing of a bridge is managed automatically by the core framework. There is no reason for a bridge handler to call this method for its things. This is a sign of a bad implementation of bridge/things in the binding.

I found 3 bindings doing that:

* [x] dscalarm
* [x] digitalstrom
* [x] yamahareceiver

**Comment by lolodomo** [comment]
@RSStephens : for the DSCalarm binding, I imagine the current implementation is because the binding is old and there was at a certain time a bug in the handling of bridge/things in the core framework ?
What I understand is that the bridge handler has to trigger a particular report command when it detects a new thing.  Except that, there is nothing special and we could let the framework update the things status when the bridge status is changed.

**Comment by RSStephens** [comment]
Hello @lolodomo,

It has been a long time since that was done so I really don't remember why the bridge handler is calling bridgeStatusChanged.  Allowing the framework to handle it is good to me. 👍

**Comment by ssalonen** [comment]
The discussion here https://github.com/openhab/openhab-addons/pull/6877 might be relevant for this.

In modbus certain workarounds are in place in order to pick up changes of bridge / child status.

**Comment by lolodomo** [comment]
This is not the same case but yes the modbus binding is apparently doing very weird things. I don't think it is expected for a thing handler to call its initialize() and dispose() methods. These methods are called only by the thing manager.

**Comment by ssalonen** [comment]
The reason I pick this up

I was wondering if this is related to some of the hacks / tricks of these other bindings. In pioneer we can see a comment  "If thing still thinks that the bridge is offline, update its status."... 

In modbus, the intention is exactly the same: to notify the child things properly when the bridge status changes. 

Based on previous discussions, the framework is actually not doing this, perhaps even by design (see comments below). This has lead to workarounds at least in modbus binding. Perhaps you are better equipped if this indeed the case.

As you can imagine, having the notification broken leads to very confusing situations. For example, we have seen that configuration changes might not be picked up properly (bridge goes to configuration error but notifying child, later issue is resolved but child was not ever reseted with dispose / initialize loop, continues with old settings).

https://github.com/openhab/openhab-addons/pull/5244#issuecomment-476338666
https://github.com/openhab/openhab-addons/pull/6877#discussion_r371015927

**Comment by lolodomo** [comment]
A long time ago, there were problems in the core framework with bridge/thing handling but at my knowledge the core framework is now correctly handling bridge/thing. When the state of the bridge thing is updated by a binding, the core framework is calling bridgeStatusChanged on each thing of the bridge. In this method, the thing handler must take care if the status of the bridge. This is not done by the modbus bridge for example.
Your problem with the state remaining ONLINE is very probably due to the strange calls to dispose() and then initialize() in bridgeStatusChanged. When the thing manager is calling initialize(), I guess that it first changes the state to INITIALIZING.
We have to check if there are other bindings calling dispose() and initialize() and create a specific issue for that.
In case the modbus binding is not trying to implement complex logic between bridge and things, I can have a look to see if I can clean up the current handling.

**Comment by ssalonen** [comment]
Ok this explains a lot.

I was suggesting myself with modbus to set state to offline in dispose (https://github.com/openhab/openhab-addons/pull/5244#issuecomment-476340622) but did not insist it per maintainer's advice https://github.com/openhab/openhab-addons/pull/5244#issuecomment-476341672. Dispose is called by Configuration changes in basethinghandler.

I think without changing the status (online to offline) of the bridge, it does notify the children. 

Today I think I know how to test this out somewhat, happy to help out.

Perhaps we get some new guidelines in the documentation on what is allowed, and what is not.

**Comment by lolodomo** [comment]
Ok, I let you do.
IMHO, there is no need to override `bridgeStatusChanged` in class `ModbusPollerThingHandlerImpl` as it is a bridge handler. I am not sure it is even called.
`ModbusDataThingHandler` is apparently the unique thing (not bridge) handler. IMHO, there is no reason to call dispo() and initialize() in `bridgeStatusChanged`. Rather use the code from method `initialize` but add a check of the bridge status (if OFFLINE, set the thing status to OFFLINE / BRIDGE_OFFLINE). What you can find in several bindings is the creation of a common method that is called by `initialize` and `bridgeStatusChanged`.
Once you removed this call to initialize() you don't need anymore thios code in `initialize` of the bridge handler:
```
            if (this.getThing().getStatus().equals(ThingStatus.ONLINE)) {
                // If the bridge was online then first change it to offline.
                // this ensures that children will be notified about the change
                updateStatus(ThingStatus.OFFLINE);
            }
```
The need of `updateStatusIfChanged` has to be checked too.

**Comment by ssalonen** [comment]
@lolodomo I am not sure if I understood your suggestion Re: modbus  :( could you break it down one more time?
