### ISSUE TITLE
[mqtt.homie] Number item is divided by 100 when receiving percentage value

### ISSUE THREAD

**Issue by PatMan6889** [openhab/openhab-addons#7711]
## Expected Behavior
When my humidity sensor is sending a value of e.g. 60 % to openHAB I expect the number item to show 60.

## Current Behavior
The value in the number item is 0.60 instead of 60. So it is divided by 100.
I already have a thread in the forum regarding this issue: 
[(https://community.openhab.org/t/percentage-changes-to-decimal-with-homie/97754/10?u=ingenieur89)]

## Possible Solution
No idea unfortunately. It was confirmed that the dimmer item is working in this case.
It was working before 2.5.4-1 update. Something went wrong in 2.5.4.

## Steps to Reproduce (for Bugs)
See my post:
[(https://community.openhab.org/t/percentage-changes-to-decimal-with-homie/97754/10?u=ingenieur89)]

## Your Environment
See my post:
[(https://community.openhab.org/t/percentage-changes-to-decimal-with-homie/97754/10?u=ingenieur89)]

**Comment by bodiroga** [comment]
I'm so sorry for the regression introduced in openHAB 2.5.4, that should not have happened. The problem is identified, so we will fix it as soon as possible :+1:

**Comment by francois-nitenberg** [comment]
When can we expect this fix to be available in the raspbian stable repos?

**Comment by bodiroga** [comment]
Hi @francois-nitenberg!

openHAB 2.5.5 version was released 29 days ago, so we are close to the 2.5.6 version release ;) I would say that during this week @kaikreuzer will trigger the button :wink:

**Comment by francois-nitenberg** [comment]
Excellent! thanks for contributing to this project  @bodiroga 👍
