### ISSUE TITLE
[hue] add channel for action/alert

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-addons#7742]
@lolodomo 
So glad to discover that support for HUE groups have been added.
Up until now I have relied on the http binding sending actions to HUE groups via the REST API.

Before I can burn all bridges though, I would really appreciate if you could include a channel for the action/alert. I use that a lot notifying my disabled mother when the door chimes, or telephone rings.

This feature is really nice, because the lights resume their initial state after done blinking.

I have found that when you do a http GET request for a HUE group over REST, only the original HUE hub return the alert action in the reply, but deconz does not.
It works just fine on deconz as well though. I just tested it on my deconz on a group of 2 HUE strips and 2 Ikea Floalt panels. Here is the REST reply:

```
2020-05-22 18:15:48.899 [INFO ] [clipse.smarthome.model.script.deconz] - deconzAlarm triggerd by vAllLightsAlarm=ON
2020-05-22 18:15:48.910 [INFO ] [clipse.smarthome.model.script.deconz] - sendHttpPutRequest() returned: [{"success":{"/groups/3/action/alert":"lselect"}}]
```
The OH2 channel should accept 2 alarm types, and the ability to abort:

NONE, SELECT and LSELECT

Thanks.

**Comment by lolodomo** [comment]
I did not know this alert feature. 
I will first test it with my lights and if supported, I will add the feature to groups by adding a new channel.

**Comment by olemr** [comment]
Nice.
More here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2818
