### ISSUE TITLE
[mvn] download maven-metadata.xml fail with HTTP 503

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#7743]
I'm not sure if this is the right place to post this question, but ..

I am trying to build a binding using `mvn clean install` and it is trying to download a whole bunch of `org.eclipse.*.*/maven-metadata.xml` files, but all these downloads fail with **_"failed to transfer file with status code 503"_**..

Is there a problem on the server? Or is it something wrong at my end?

**Comment by kaikreuzer** [comment]
503s are server errors, so I would assume that some server has some instabilities. Can you say from your logs, which server it is?

**Comment by andrewfg** [comment]
Ok, I tried this again today, and it now works again; so I am guessing it was a temporary server problem..
