### ISSUE TITLE
[shelly] Shelly 2.5 as roller shutter - strange position changes in log file every 15 seconds

### ISSUE THREAD

**Issue by c0d3-n1nja** [openhab/openhab-addons#7757]
Shelly 2.5 in roller mode logs control events every 15 seconds - even with no postion changes.

Shelly Binding -> added thing Shelly 2.5 in roller mode. Linked control to new item. Shelly is calibrated, setting a position works fine. But event is fired every 15 seconds with two position changes (jumping to false value and jumping back to right value):

> 2020-05-23 20:35:54.083 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:35:54.677 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:36:09.090 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:36:10.442 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:36:24.090 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:36:25.974 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:36:39.096 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:36:41.554 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:36:54.109 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:36:57.275 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:37:09.115 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:37:09.799 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:37:24.124 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:37:26.296 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:37:39.130 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:37:41.879 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:37:54.136 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:37:54.394 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:38:09.140 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:38:09.968 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:38:24.143 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:38:25.501 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0
> 2020-05-23 20:38:39.141 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 0.0 to 60.0
> 2020-05-23 20:38:39.144 [vent.ItemStateChangedEvent] - Shellyswitch2569124b104011_Roller_Steuerung0Offen100Geschlossen changed from 60.0 to 0.0

Actual position/value: 0. Every 15 seconds the position changes from 0 to 60 and back to 0. A second Shelly 2.5 in roller mode shows the same beavior, but with the values 0 and 100.

As I want to log events into an InfluxDB, this false events are very annoying.

Tested scenarios: autodiscovery / manually added thing, CoIoT enabled / disabled, OpenHAB 2.5.5 and 3.0.0-snapshot, even resetting the Shelly - same issue.

**Comment by DpunktKpunkt** [comment]
CoIoT was still active somehow ... after deactivating CoIoT everything works now
