### ISSUE TITLE
[shelly] update channels when value hasn't changed

### ISSUE THREAD

**Issue by stuart938503** [openhab/openhab-addons#7764]
Started using the Shelly binding with a Shelly 1PM for monitoring the amount of electricity being diverted into the immersion heater/hot water tank when our solar cells are generating more than we are using. I've noticed that channel values only appear to be updated when they change, which means I frequently find gaps in the data when its persisted to a time-series database e.g. Influx. This impact is further amplified when I want to carry out mathematical functions on other time series data e.g. subtract diverter usage from whole house usage to get actual power demand.

Could the binding be updated such that channel values are always updated please? This would allow me to save these states regularly into a TSDB. Those people who still only want to invoke and event/action when the values change could use _on change_ or _everyChange_ as required.

**Comment by markus7017** [comment]
This doesn't make sense and would flood the logfile, esp. when having more Shellys.

Are you using Garfana? There is an option how to fill the gap between datapoints. It's a drop down in the definition of the field, but I can't remember the exact naming

**Comment by markus7017** [comment]
Stuart: Sid you tried the recommended solution so we could close this issue?

**Comment by markus7017** [comment]
Stuart: Sid you tried the recommended solution so we could close this issue?
