### ISSUE TITLE
[homekit] Documentation is wrong regarding the available console commands

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#7784]
Opening this mostly as a reminder. If I have some free time in the next weeks, I'll create a PR for this.

## Expected Behavior
Documentation should match reality.

Console:

```
openhab> smarthome:homekit list
Unknown command 'list'
Usage: smarthome:homekit listAccessories - list all HomeKit accessories
Usage: smarthome:homekit printAccessory <accessory id> - print accessorty details
Usage: smarthome:homekit clearPairings - removes all pairings with HomeKit clients
Usage: smarthome:homekit allowUnauthenticated <boolean> - enables or disables unauthenticated access to facilitate debugging
```

## Current Behavior
Documentation shows different commands (probably outdated).

Documentation:

https://github.com/openhab/openhab-addons/tree/2.5.x/bundles/org.openhab.io.homekit

> smarthome:homekit list - list all HomeKit accessories currently advertised to the HomeKit clients.
> 
> smarthome:homekit show <accessory_id | name> - print additional details of the accessories which partially match provided ID or name.

## Possible Solution
Change documentation.

**Comment by J-N-K** [comment]
Unfortunately the documentation points to latest snapshot and not to latest release. It seems the documentation for latest release is not available at all.

The latest documentation is correct for >2.5.5. the 2.5 documentation is correct for <2.5.5. The correct documentation for 2.5.5 is not available on the website.

**Comment by eikowagenknecht** [comment]
Ah I see.. so that was a recent change (5943cd3919fe990b1a73063857e716cf49bc524b for reference) and the documentation is newer than the latest release now. From a users point of view, I would expect the documentation to refer to the latest **released** version and not the latest developer build, but I'm pretty sure this is the way it is for a reason.

I'm closing this issue now as it it not related to the homekit binding but more of a general thing.
