### ISSUE TITLE
[alarmdecoder] Binding not discovering or working with manually added wired zones

### ISSUE THREAD

**Issue by WSumrell** [openhab/openhab-addons#7787]
I recently upgraded from alarmdecoder1 whereby I was detecting zone faults in rules by parsing the keypad text.  With the new openhab2 2.5.5 binding, the RF things are being discovered and are working just fine, but the wired zones 1-8 aren't being discovered nor are they working when I manually add these zones.

## Expected Behavior
I expect that wired zones should be automatically discovered and these things should be triggered when the zones fault.

## Current Behavior
The wired zones 1-8 aren't being discovered nor are they working when I manually add these zones.

My alarmdecoder device has the following config:
!VER:ffffffff,V2.2a.8.8,TX;RX;SM;VZ;RF;ZX;RE;AU;3X;CG;DD;MF;L2;KE;M2;CB;DS;ER;CR
With the binding set at TRACE-level logging, I see the RFX messages but no wired-zone notifications except for the kepad panel text.

## Possible Solution
Is this a configuration problem of some sort?

## Your Environment
openhab core v2.5.5 on Windows, alarmdecoder binding v2.5.5
Ademco Vista 20SE

**Comment by bobadair** [comment]
If you’re not seeing any REL or EXP messages from the AD, then it’s probably a configuration problem with the AD and/or your alarm panel rather than the binding. On at least some panels it requires additional configuration for messages from the built-in zones (1-8) to show up. See the V1 binding docs, or you may want to ask in the forum about it. I can’t offer much help, as I’ve never set that up.

**Comment by bobadair** [comment]
Hi @WSumrell. Have you been able to look in to this any more? I’m interested to hear what you find. At the least I can probably use it to improve the docs.

 I’m removing the bug label for now. If we identify a bug I’ll add it back on.

**Comment by WSumrell** [comment]
Hi @bobadair.  You were absolutely correct that this was a panel config issue.  I am running the Ademco Vista 20SE panel which is a lightweight version of the Vista 20p.  I saw the note in your binding documentation "Although not mentioned in the Quick Start guide, configuring virtual relay boards is absolutely necessary on panels like the Honeywell Vista 20p and similar, or else all of the eight on-board zones will not be visible!" and configured 3 of my 8 hardwired zones using virtual relays and they're now being discovered and the items are being triggered properly in openhab.

The configuration involved:
1. Enabling the 4 virtual relays in the AD config
2. Enabling the *25 option on the panel to 2
3. Configuring *81 zone lists with one hardwired zone in each zone list
4. Configuring the *80 output devices 1-3.

This allows me to receive the !REL messages from the panel for 3 hardwired zones.

So, it looks like the 20SE panel only supports 3 total output devices and I won't be able to monitor the remaining 5 hardwired zones.  Does anyone know of an alternate strategy to monitor all 8 hardwired zones on a Vista 20SE panel?  In the meantime, I guess I can just parse the the keypad text for the remaining 5 hardwired zones rather than configuring things for them.

Thanks for your help!

**Comment by bobadair** [comment]
> This allows me to receive the !REL messages from the panel for 3 hardwired zones.

Where did you find the instructions on how to configure that? I would like to add something to the docs about it. The original V1 README.md file included a link to an AD support article about it (http://archive.nutech.com/index.php?option=com_fireboard&Itemid=74&func=view&catid=4&id=656) but that doesn't seem to work anymore.

>So, it looks like the 20SE panel only supports 3 total output devices and I won't be able to monitor the remaining 5 hardwired zones. Does anyone know of an alternate strategy to monitor all 8 hardwired zones on a Vista 20SE panel?

I'm afraid I can't help you much there. You would probably be better off asking about it on community.openhab.org. If you have a free slot on your panel you could always stick in an expander board and move your other hardwired zones to it, but that seems a bit silly. @LuckyMallari or @berndpfrommer, do you know anything about configuring the built-in zones on a Vista 20SE?

**Comment by billfor** [comment]
> 
> 
> Hi @bobadair. You were absolutely correct that this was a panel config issue. I am running the Ademco Vista 20SE panel which is a lightweight version of the Vista 20p. I saw the note in your binding documentation "Although not mentioned in the Quick Start guide, configuring virtual relay boards is absolutely necessary on panels like the Honeywell Vista 20p and similar, or else all of the eight on-board zones will not be visible!" and configured 3 of my 8 hardwired zones using virtual relays and they're now being discovered and the items are being triggered properly in openhab.
> 
> The configuration involved:
> 
>     1. Enabling the 4 virtual relays in the AD config
> 
>     2. Enabling the *25 option on the panel to 2
> 
>     3. Configuring *81 zone lists with one hardwired zone in each zone list
> 
>     4. Configuring the *80 output devices 1-3.
> 
> This allows me to receive the !REL messages from the panel for 3 hardwired zones.
> 
> So, it looks like the 20SE panel only supports 3 total output devices and I won't be able to monitor the remaining 5 hardwired zones. Does anyone know of an alternate strategy to monitor all 8 hardwired zones on a Vista 20SE panel? In the meantime, I guess I can just parse the the keypad text for the remaining 5 hardwired zones rather than configuring things for them.

*25  option 2 is the 4229 expander. Are you saying you have 16 hardwired zones and can only get 3 of the original 8?

**Comment by WSumrell** [comment]
No, I only have 8 hardwired zones.  The Vista 20SE documentation has a note in the *80 section that states “Output Devices: Interactive menu mode applicable only if field *25 is programmed for a 4229, 4204, …”.

**Comment by WSumrell** [comment]
>> Where did you find the instructions on how to configure that?

Yes, documentation was extremely hard to find.  I pieced it together through various posts including the following and also the Vista 20SE panel programming manual.

               http://www.alarmdecoder.com/forums/viewtopic.php?f=3 <http://www.alarmdecoder.com/forums/viewtopic.php?f=3&t=527> &t=527

               https://www.ragingcomputer.com/2015/11/taking-over-an-adt-alarm-and-integrating-it-with-openhab

 

               http://forum.micasaverde.com/index.php?topic=7266.585

               http://www.alarmdecoder.com/wiki/index.php/Protocol#AUI

               http://www.info-techs.com/ademco/files/controls/programming/v20sepf.pdf

**Comment by billfor** [comment]
I have a vista20SE without any extras.  My *25 is set to 0 and I receive all the hardwired zone info.  

Maybe you are trying to receive the faults in an armed mode? That does require setting up the relays I guess.
In the new binding, this is my entire configuration:
```
Bridge alarmdecoder:ipbridge:bill [ hostname="localhost", tcpPort=10000 ]
//Bridge alarmdecoder:serialbridge:bill [ serialPort="/dev/ttyAMA0" ,bitrate=115200 ]
{
  Thing keypad keypad [ sendCommands=true, addressMask=0 , sendStar = true  ]
}
```

With that, whatever the keypad is emitting is what you'll be able to handle in openhab. I haven't had any issues. However the limitation is that you don't get faults when its armed. But if something faults when its armed (Away),  a fault  will trigger the alarm anyway.  

I don't have remote radio devices though. Maybe that's the problem. Everything in my system is hardwired to one of the 8 zones.

**Comment by bobadair** [comment]
> I have a vista20SE without any extras. My *25 is set to 0 and I receive all the hardwired zone info.

Yeah, but you're not using zone things. All of your rules are based on keypad status indicators and messages.
