### ISSUE TITLE
Plugwise smile P1

### ISSUE THREAD

**Issue by Glenn1986** [openhab/openhab-addons#7803]
Hi,

I have a plugwise smile P1 for my energy monitoring. I was wondering if this hardware will be added in the future? It would be awesom.

Kind regards.

Glenn

**Comment by Hilbrand** [comment]
I doubt someone is willing to invest their time in this as the DSMR binding already supports reading the smart meter. What is the added value?

**Comment by Glenn1986** [comment]
I don't know if the plugwise smile has an API but on this hardware you have daily consumption and little bit more. For me de DSMR doesn't work. I tried a couple of times. I have a Belgian smart meter. Thanks for you quick answer.

**Comment by Hilbrand** [comment]
Which version of openHAB do you use? The DSMR binding has support for the Belgian smart meter since 2.5.1 So if you had any problems I'm interested to find out to see if these problems can be fixed.

**Comment by Glenn1986** [comment]
I have the newest version of openhab, i believe 2.5.2. I will try it again later on. I will let you know if which problems I have. Thanks!
