### ISSUE TITLE
[mqtt] Duplicate clientID keys in JSON when custom client ID defined

### ISSUE THREAD

**Issue by stuart938503** [openhab/openhab-addons#7812]
I have an MQTT broker thing used as a bridge to an MQTT server. I noticed today when trying to parse some data in PowerShell that the JSON returned for my things has duplicate clientID keys:

```
PS C:\> $Things = ConvertFrom-Json (Invoke-RestMethod -Method Get -Uri "https://<openhab>/rest/things")         
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated keys 'clientid' and 'clientID'.
```
A checked the JSON output and noticed the duplicate keys are from the MQTT broker:
```
{
  "statusInfo": {
    "status": "ONLINE",
    "statusDetail": "NONE"
  },
  "editable": true,
  "label": "EmonTX MQTT Broker",
  "configuration": {
   <blah>
    "clientid": "c8b188c9-ae7a-4327-87cd-a374e59b3107",
    "clientID": "openhab",
   <blah>
  },
  "properties": {},
  "UID": "mqtt:broker:5132a9f7",
  "thingTypeUID": "mqtt:broker",
  "channels": [],
  "location": "MQTT"
}
```

I cleared the clientID from under 'advanced' settings within PaperUI, and the openhab client ID is removed. Not sure why I set that or whether it was automatic or not, but everything still works without it.

Raising this bug report on the chance it is a possible bug. From what I have read the JSON spec doesn't prohibit duplicate keys, although many clients may not be happy with them, PowerShell being one. If clientID is set under 'advanced' settings, should this replace the auto generated one?

Running OpenHAB `openHAB 2.5.4-1` on openHabian, and MQTT binding `binding-mqtt - 2.5.4`

Thanks

**Comment by Rossko57** [comment]
Strictly, they're not duplicate. JSON keys are case sensitive, PowerShell is misreporting.
https://github.com/PowerShell/PowerShell/issues/3705

Doesn't mean this is not some unexpected situation, though.

**Comment by lsiepel** [comment]
Looking at the powershell github, i see several issues regarding case sensitive json, but i cannot fully asses if it is fixed or not. Anyway, it seems to be (openHAB perspective) an external issue, i guess we can close this for now. If needed it can be re-opened.
