### ISSUE TITLE
[HP Printer] Status: Offline

### ISSUE THREAD

**Issue by pc-bastler** [openhab/openhab-addons#7815]
HP Printer

## Expected Behavior

My HP Color LaserJet 2025n shown as online and as "color"-Model

## Current Behavior

When I add my Printer using Paper UI from Inbox (it's automatically detected) a thing is created. This Thing shows up like:
Status: OFFLINE  Content ist nicht zulässig in Prolog.
I also have "only" the Ink/Toner-Channel for Black Toner listed in Channels.

## Steps to Reproduce (for Bugs)

1. Switch on the printer
2. Wait until it is detected and shown in the inbox (Paper UI)
3. Add the printer as thing

## Context

I wanted to include my CP2025n to my open hab configuration

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
openHAB 2.5.5 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
Safari 13.1.1 as browser, macOS 10.15.5
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 1.8.0_152-b76)
OpenJDK Client VM (Zulu Embedded 8.25.0.76-linux-aarch32hf) (build 25.152-b76, mixed mode, Evaluation)
NodeJS v11.7.0
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
Raspian Buster on Raspi 3B+

**Comment by Cossey** [comment]
The status message said *Content ist nicht zulässig in Prolog* - If Google Translate is correct, that says *Content is not allowed in Prolog* - whatever *Prolog* is. 

If you have no channels but the 3 *non-dynamic* ones displayed, then this error is occurring when the Binding is being initialized - probably when its doing the first request to the `http://<PrinterIP>/DevMgmt/ProductUsageDyn.xml` endpoint. It reads the XML tags in this file to figure out what channels are supported. 

Can you go to that XML file and see if it gets loaded up correctly?

**Next lets see if the log files point to any obvious problems.** 

If you are not sure how, you can get the logging for the Binding doing the following:
1. Remove the HP Printer thing from Paper UI.

2. Enable `TRACE` level logging for the binding in the openhab console (`log:set TRACE org.openhab.binding.hpprinter`). 

3. Re-add the printer from the Inbox and then see what errors come through the log file and display them here. You can use the `log:display` or `log:tail` to watch the logs real time.

**Comment by pc-bastler** [comment]
Hi,

I tried to open the URL, you mentioned (of course replacing the <PrinterIP> with the correct IP of my CLJ) but get just a 404, to be exactly, it just says "404 not found" on the page.

Does that possibly mean, my printer is not supported?

**Comment by Cossey** [comment]
Possibly, yes. Can I also get you to the same url above, but instead of start with `http` can you change it to `https` to see if that makes a difference?

Additionally, can I get you to try this url as well to see if it works? `http://<PrinterIP>/DevMgmt/DiscoveryTree.xml`.

**Comment by Cossey** [comment]
@pc-bastler are you able to confirm the other page `DiscoveryTree`also does not work? 

Does the **HP smart** app work for your printer? _Available on the iOS, Android and Microsoft stores._ I developed the binding based on Wireshark captures from that app on Windows 10. 

Thanks! I just want to rule out some things and your feedback would greatly help improve the Binding.

**Comment by Cossey** [comment]
Closed due to lack of response. 

If this is still a problem please reopen issue.

**Comment by petero-dk** [comment]
I have a HP Color LaserJet CP5225n (with the same symptoms) so that is why I am commenting on this old thread @Cossey 

It gets a 404 on both pages, and I cannot test https, as that is not enabled on the device. Is there anything I can do to find a way to get this printer supported, or is it simply not available?

**Comment by Cossey** [comment]
> I have a HP Color LaserJet CP5225n (with the same symptoms) so that is why I am commenting on this old thread @Cossey 
> 
> 
> 
> It gets a 404 on both pages, and I cannot test https, as that is not enabled on the device. Is there anything I can do to find a way to get this printer supported, or is it simply not available? 

Does the HP Smart phone app work with your printer? If it does then there might be hope otherwise you'd be stuck trying to use SNMP for getting back printer status/state.

**Comment by s-kilger** [comment]
I have a HP Color LaserJet M552 which behaves the same way.
There is no http://<PrinterIP>/DevMgmt/ProductUsageDyn.xml but there is a http://<PrinterIP>/DevMgmt/DiscoveryTree.xml page.
My printer is recognized by the HP Smart phone app but it says that some functions are not available.
Is there anything else I can contribute @Cossey?
