### ISSUE TITLE
[Dwd Pollenflug] Binding Not working with openhab 2.5.5

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-addons#7820]
Hello,
Some people including me reporting dwd Pollenflug Binding ist mit working since openhab update 2.5.5

## Expected Behavior
Show pollen Info

## Current Behavior
No pollen I do anymore

## Steps to Reproduce (for Bugs)

1.install openhab 2.5.4 everything is working
2. Install 2.5.5 no information anymore

**Comment by J-N-K** [comment]
Any errors in the log?

**Comment by miloit** [comment]
@J-N-K unfortunately not

**Comment by chiefymuc** [comment]
I just checked, it works normally for me on 2.5.5

**Comment by miloit** [comment]
Cleared the cache running fine now
