### ISSUE TITLE
[mqtt] Homie Device divides value with unit '%' by 100

### ISSUE THREAD

**Issue by RayBa82** [openhab/openhab-addons#7859]
I have a humidity sensor which sends homie messages. The humidity is defined with '%' as unit.
The device sends the value as 61 but openhab displays 0.61 %

That changed with the recent versions, it worked in 2.5.0

**Comment by bodiroga** [comment]
Hi @RayBa82!

You are right, it was introduced in 2.5.4, as reported [here](https://github.com/openhab/openhab-addons/issues/7711).

Fortunately, it should be fixed (by https://github.com/openhab/openhab-addons/pull/7774) in the latest snapshot and in the next stable version (2.5.6).

Thanks for your patience!

**Comment by RayBa82** [comment]
Thx for the info.
Unfortunately there is no 2.5.6 snapshot docker container, so I hope 2.5.6 will be published soon ;-)
