### ISSUE TITLE
[deconz] on-off-status not working with color lights

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#7867]
Very nice enhancement of the binding. I could also test it with the following thing types: 'onofflight', 'dimmablelight', 'colorlight' and 'extendedcolorlight'.

Everything works fine so far. I only have problems with the on/off status of 'colorlight' and 'extendedcolorlight'. When a colorlight is switched on/off externally to Openhab, for example in Phoscon, the on/off status of the item will not be set correctly. With the other thing types, the status setting works fine. For the colored lights only the color is set, but not the on/off status.

But even if you use the element type 'switch' in the sitemaps for a colorlight, it does not work correctly. The light will turn on/off, but the state of the switch will not change correctly.

Here is an example of my configuration:

Things file:
```
Bridge deconz:deconz:homeserver [ host="192.168.0.10", apikey="ABCDEFGHIJ" ] {
    extendedcolorlight    livingroom   "Livingroom"   [ id="1" ]
    colorlight            bedroom      "Bedroom"      [ id="2" ]
}
```

Items file:
```
Color  Livingroom  "Livingroom"  <colorlight>    { channel="deconz:extendedcolorlight:homeserver:livingroom:color" }
Color  Bedroom     "Bedroom"     <colorlight>    { channel="deconz:colorlight:homeserver:bedroom:color" }
```

Sitemaps file:
```
Switch item=Livingroom  // this status will not be set correctly
Colorpicker item=Livingroom
Switch item=Bedroom  // this status will not be set correctly
Colorpicker item=Bedroom
```

I have tested it with the [FLS-PP lp from dresden elektronik](https://www.dresden-elektronik.com/product/fls-pp-lp-wireless-ballast.html), it is a ZLL device of the type 'extended colour light'.

_Originally posted by @Markkuuss in https://github.com/openhab/openhab-addons/pull/7608#issuecomment-639147806_

**Comment by J-N-K** [comment]
@Markkuuss, it's usually better to open an issue instead of commenting in merged PR. I don't read them every time.

I have prepared a fix, can you check if that solves your problem: https://janessa.me/esh/org.openhab.binding.deconz-2.5.6-SNAPSHOT.jar

**Comment by Markkuuss** [comment]
Very nice.  That's how it works!  Thanks for a great job, @J-N-K .
