### ISSUE TITLE
Echonet Lite Support? (for Mitsubishi MAC-568IF-E Wifi Controller)

### ISSUE THREAD

**Issue by jmone1** [openhab/openhab-addons#7872]
<a alt="bounty" href="https://www.bountysource.com/issues/91653932"><img src="https://api.bountysource.com/badge/issue?issue_id=91653932"></a>

As discussed in the [OpenHAB Community Post](https://community.openhab.org/t/echonet-lite-support-for-mitsubishi-mac-568if-e-wifi-controller/100159):

I have a Mitsubishi Air Conditioner with a MAC-568IF-E Wifi Controller that supports Echonet Lite direct integration.  I see there was some work done for a binding years ago:
https://github.com/kaz260/org.openhab.binding.echonetlite

There is also a working integration being discuss at HA 
https://community.home-assistant.io/t/mitsubishi-aircon/37454/99

It seems that there is a whole range of HVAC equipment produced in Japan that uses Econet Lite so hopefully this would work with a wide range of such devices.  The full specification for Echonet Lite is here
https://echonet.jp/product_en/echonet_lite_specification/

Thanks
Nathan

**Comment by jmone1** [comment]
FYI - I created a Bounty for this (not sure why it is not taged on this request however).
https://www.bountysource.com/issues/91653932-echonet-lite-support-for-mitsubishi-mac-568if-e-wifi-controller

Thanks
Nathan

**Comment by wborn** [comment]
Thanks for adding the significant bounty! Adding the label is a manual operation. :wink:

**Comment by ab3be6** [comment]
Hello Nathan,

I also would like OH to support the echonet lite device.
So I found a tool and solution for this and I share it with you.
I hope this information helps you.

[https://github.com/KAIT-HEMS/node-picogw](url)
This gateway runs on node.js and can convert the echonet device to the MQTT topic.
If your OH has the MQTT binding and broker, you can find the echonet device as the MQTT topic.

I tried to set up this GW and MQTT broker, but I don't have experience with MQTT binding.
Now my OH does not detect an echonet device yet...

just for your information, the PicoGW could not run on a raspberry pi which already has MQTT broker mosquitto.
of course, vanilla raspberry pi can run the PicoGW.

If you have interested in this configuration, and you have succeeded to set it up, could you share your work steps with me?

**Comment by jmone1** [comment]
Thanks - I did see that, but was hoping by adding a bounty someone (with much more knowledge than me) would be able to create a native adapter for it for OH3

**Comment by mikeb01** [comment]
Is there still interest in seeing this implemented?  I have Mitsubishi heat pumps and I wrote an Echonet client in Rust, but I'm thinking of porting my code across to Java and OpenHAB.

**Comment by jmone1** [comment]
I'm certainly still interested! ( and the Bounty is unclaimed if that helps )

**Comment by mikeb01** [comment]
I'll have a look at this over the next couple of weeks.

Assuming you are the one putting up the bounty, if I get this done, how would you feel about donating the bounty to a charity?

**Comment by jmone1** [comment]
Sounds good to me.  I've never used the bounty system before so I don't know how it works.  You may have to claim it then donate it?  It may even be possible to donate to the OH Foundation.

**Comment by mikeb01** [comment]
Finally got around to getting this working, PR is open.

**Comment by jmone1** [comment]
Great Stuff! Thanks.

**Comment by mikeb01** [comment]
The PR for the EchonetLite implementation has now been merged and will be included in 3.4.

**Comment by jmone1** [comment]
Hi Mike, sounds good.... but I'm no longer able to test as I moved off OpenHab to HA (which already had an echonetlite support).  Thanks for taking this up however.  Also I've no idea how to release the bounty?

**Comment by mikeb01** [comment]
Once this issue gets closed the bounty is released.

**Comment by jmone1** [comment]
Perfect!
