### ISSUE TITLE
[deconz]  Color Temperature not functional

### ISSUE THREAD

**Issue by danli003** [openhab/openhab-addons#7884]
For lamps (extendedcolorlight / colortemperaturelight) the Color Temperature item is defined as "Number". Setting this item to any number in the interval 0 to 100 does not change the actual lamps color temperature.
I would also expect the color temperature to be a dimmer item rather than a number item

## Expected Behavior
Setting a number to the colortemperature item should change the lamps color temperature
It should preferably be a dimmer item rather than a number item

## Current Behavior
Opposite to Expected

## Context
I am trying to migrate from Zigbee binding to deconz. But need colortemperature control

## Your Environment
* Version used: (e.g., openHAB 2.5.5 and deconz add-on snapshot build 2020-06-06)
* Environment name and version (e.g.  Java 8.):
* Operating System and version (openhabian on pi4.):

**Comment by Rossko57** [comment]
Would you clarify "Setting this item to any number..."
You would normally send a **command** to an Item to invoke binding action.

**Comment by danli003** [comment]
Fair enough.

**Comment by batje** [comment]
> IMO color temperature is not a dimmer. There is no useful definition for ON or OFF, which are fully valid commands for a dimmer item.

This is very confusing. In the Deconz software (and in Tasmota) the temperaturecolor is a slider. and for a Number that can take a few thousand different values, that makes a lot of sense.

This is very confusing and a lot of extra work, because you cant control the temperaturecolor directly from the UI, you have to program it with sendCommands. Could this be reconsidered?

**Comment by J-N-K** [comment]
I use `Slider item=RoteKugelIKEAofSweden_ColorTemperature step=1 minValue=2200 maxValue=4000` in my sitemap and can control the color temperature with a slider

**Comment by batje** [comment]
That would work, but I am trying to transition to the new semantic interface, where things are supposed to work automagically, and so far, this is the only thing that requires programming.
