### ISSUE TITLE
[Hue] Status of Hue binding connection to the Hue bridge

### ISSUE THREAD

**Issue by andreasscherbaum** [openhab/openhab-addons#7905]
Issue #7863 explains that the ONLINE/OFFLINE status of the Hue binding has no direct relation to whenever the binding is connected to the Hue bridge, but merely shows that the bridge is currently trying to connect (OFFLINE -> ONLINE) and it that fails it will fall back to OFFLINE again. As a result the binding can bounce between OFFLINE and ONLINE many times in a matter of seconds.

Being able to monitor the status of devices/bridges is an important aspect to figure out if there is a problem with the setup. Currently the Hue binding does not provide a way to determine if the binding is connected to the Hue bridge and able to transmit commands to the bridge and connected devices.

## Suggested changes:

1) Change ONLINE to show the actual status of the binding, not the attempt to connect to the bridge.

Or:

2) Implement a channel(?) which shows the status of the connection between the binding and the bridge.

**Comment by lolodomo** [comment]
Just to understand, why are you duplicating your own issue? 

I would suggest to close this one. 

I agree that the current behavior makes no sense. The bridge should be set to ONLINE only if the request to the hurricane bridge succeeds.

**Comment by lolodomo** [comment]
Please close the other issue as I mentioned this one in the enhancement PR.

**Comment by andreasscherbaum** [comment]
@lolodomo Because the other Issue was "turned down" as "works as intended", therefore I created this one. The two issues differ though: #7863 is about the ONLINE/OFFLINE status of the binding, #7905 is about having a proper channel to monitor the status of the connection between the binding and the bridge.

I agree that the binding should only report ONLINE when the connection is established, and authenticated - but apparently there are other opinions. Will close the other PR.

**Comment by lolodomo** [comment]
My proposal does not include any new channel.

**Comment by andreasscherbaum** [comment]
@lolodomo I've seen your PR, thank you.
I'm fine with whatever reports the correct status.

(I don't know how to test just this PR, sorry)
