### ISSUE TITLE
[netatmo] Support for the floodlight of the Presence camera

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#7912]
The Presence camera is supported since OpenHAB 2.5.6 (see #3059 ).

It would be neat when the floodlight of the Presence camera could get switched. That would for example allow ...
- to build a remote control
- to program complex rules where the floodlight gets switched on (only) under certain conditions.
- flashing the floodlight to signal an alarm

**Comment by Novanic** [comment]
I got it already running, but it may take some time for optimizations and till the pull-request is done.

If you want to review or test it, you can find the current state here: https://github.com/Novanic/openhab-addons/tree/netatmo-presence-enhancements

**Comment by yfre** [comment]
@Novanic is it possible to switch camera ON and OFF? is it supported by Netatmo API?

**Comment by Novanic** [comment]
> @Novanic is it possible to switch camera ON and OFF? is it supported by Netatmo API?

Yes, with an undocumented API endpoint. I have opened issue #7938 for that.

**Comment by yfre** [comment]
> > @Novanic is it possible to switch camera ON and OFF? is it supported by Netatmo API?
> 
> Yes, with an undocumented API endpoint. I have opened issue #7938 for that.

cool. really need it. (tired to switch camera everyday off when the mower robot start to work - it gets detected as a car :)
