### ISSUE TITLE
[netatmo] Null annotations

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#7913]
@clinique @Novanic : for your information, I will add null annotations on all classes in the Netatmo binding.
We have many classes but it should not be too much difficult I think.
I am now just waiting for a merge to get again a compiling version of the binding in branch 2.5.x.

**Comment by Novanic** [comment]
Ok, thank you. I think it's a good idea to refactor this one-time, that may be less work and after that it is easier to make "correct" changes. ;-) There are about 30 classes within the binding, 6 are currently annotated with NonNullByDefault.

**Comment by lolodomo** [comment]
To finish the job, I msut wait for the merge of #7938

**Comment by lolodomo** [comment]
https://github.com/openhab/openhab-addons/blob/2.5.x/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/homecoach/NAHealthyHomeCoachHandler.java#L50

@clinique : is there a valid reason that for the homecoach you just get the first device while for the weather station for example you apply a filter on the id ? My feeling is that the filter on the id was to be sure to get a device in case the provided id was wrong.

**Comment by clinique** [comment]
@lolodomo : the homecoach part has not been developped by me so there may be possible enhancements I did not see

**Comment by lolodomo** [comment]
OK, I fixed it in my PR.

Please note that I also suppressed the usage of Optional in class fields and method arguments after reading that it is not recommended (Optional only recommended as return of methods).
