### ISSUE TITLE
[deconz] Battery value is no longer shown for ZHABattery sensor

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-addons#7920]
The battery sensor that is created for Ikea blinds no longer delivers a value for the "battery_level" channel. 

The trace log shows that the value is correctly retrieved, but this is the only message regarding the battery level:
```
20:50:53.730 [ient-common-184] TRACE o.o.b.d.i.h.SensorBaseThingHandler:270 - deconz:batterysensor:c291659a:086bd7fffe602991010001 received SensorState{dark=null, daylight=null, lightlevel=null, lux=null, temperature=null, humidity=null, open=null, fire=null, water=null, alarm=null, tampered=null, vibration=null, carbonmonoxide=null, pressure=null, presence=null, power=null, battery=85, consumption=null, voltage=null, current=null, status=null, buttonevent=null, gesture=null, lastupdated='2020-06-14T18:41:24.823'}
```

The `lastupdated` channel is correctly updated but not the `battery_level`.

It seems that the battery_level ist handle in the wrong method: https://github.com/openhab/openhab-addons/blob/24e083850ac41cb7e809491f63f79a32ce4308ad/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java#L205 
contains a case for `CHANNEL_BATTERY_LEVEL` but the other `valueUpdated` method (https://github.com/openhab/openhab-addons/blob/24e083850ac41cb7e809491f63f79a32ce4308ad/bundles/org.openhab.binding.deconz/src/main/java/org/openhab/binding/deconz/internal/handler/SensorBaseThingHandler.java#L230) is called instead.

This problem has been introduced with one of the latest commit. With older versions it worked correctly.

Tested with commit https://github.com/openhab/openhab-addons/commit/f9e54549c6b1cf2b6e3cdbef9dd17627a27b673f

**Comment by J-N-K** [comment]
The reason is that most sensors report it as config, while Ikea reports it as state. The support for that was unintentionally dropped in the refactoring #7828. I'll provide a PR to add it back.
