### ISSUE TITLE
[resol] Add Resol Controller Binding

### ISSUE THREAD

**Issue by ramack** [openhab/openhab-addons#7921]
<a alt="bounty" href="https://www.bountysource.com/issues/91722438"><img src="https://api.bountysource.com/badge/issue?issue_id=91722438"></a>

I propose to add a new binding to connect solar and heating controllers from the supplier Resol, which includes a whole bunch of OEM devices branded for different suppliers (Viessmann, SOLEX, COSMO, SOLTEX, DeDietrich). Those devices have an interface to the so call "VBUS" - for which network interfaces (VBUS LAN, DL3, etc.) are available.
Such a binding will allow to read temperatures of the solar and heating system.

There was a previous development activity by @MitchSUEW in https://github.com/openhab/openhab1-addons/pull/3110 but this seems to be abandoned. Therefore I developed a new, more generic version for Resol devices based on the [VBUS-Java](https://github.com/danielwippermann/resol-vbus-java) which was discussed in the [community forum](https://community.openhab.org/t/beta-of-resol-binding-available-on-iot-marketplace/43550) is available in [Eclipse IoT Marketplace](https://marketplace.eclipse.org/content/resol-binding) and it is now the time to clean it up and submit a PR into openhab.

**Comment by wborn** [comment]
Thanks for adding the bounty @EjvindHald! :+1:
