### ISSUE TITLE
[squeezebox] SqueezeBoxPlayerHandler caches state leading to missed Item updates

### ISSUE THREAD

**Issue by t2000** [openhab/openhab-addons#7928]
The `SqueezeBoxPlayerHandler` caches the state of each channel here:

https://github.com/openhab/openhab-addons/blob/bc73c602efd6d5ab6737693d5a56fc6790fd3770/bundles/org.openhab.binding.squeezebox/src/main/java/org/openhab/binding/squeezebox/internal/handler/SqueezeBoxPlayerHandler.java#L512

What I notices it that during startup of openHAB my squeezebox items were not updated until I changed something on the player itself. Only then my items got filled.

While debugging I found the caching line above and I assume that the items were not (yet) linked when the statemap was first filled and thus the first channel update was done without an effect on an item. Consecutive status updates from the squeezebox server then do not lead to item updates if nothing has changed.

I always thought that a binding shouldn't do caching, unless the work to obtain the values is expensive, i.e. a huge database query or remote internet connection query for example.

In this squeezebox example the values are pushed to the binding anyway, since we are subscribed to updates.

Thus I would vote for removing the cache. Shall I create a MR?

**Comment by mhilbush** [comment]
@t2000 I'd have no issue removing the cache. The status updates only occur a couple times a minute, so there would be no performance impact.

Did you try removing it, and did it resolve the issue you were having?

**Comment by mhilbush** [comment]
Alternatively, if the `stateMap` is filled before the REFRESH commands are received (I'm not sure if this is the case), you could update the channel state using the `stateMap` when a REFRESH is received.

**Comment by t2000** [comment]
Indeed I have also throught about it, but wasn't sure if this fixes the problem too.

I just give it a try and it worked. Thanks for the hint!

I have created a PR to fix this.

**Comment by mhilbush** [comment]
Glad that worked!!
