### ISSUE TITLE
[mail] enhance feedback from sending emails

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#7937]
Currently v2.x mail binding provides no feedback to rules about success or failure of sending a mail using a sendMail action
For example, it is not possible to readily invoke some alternative communication or some local action if the external smtp server is down, or an attachment fails.

For discussion - add feedback features to mail smtp Thing.
Using exec binding as a loose model, we might have any or all of:
A Switch type channel "run", which turns ON when a sendMail Action is invoked, with good parameters , and OFF when mail has been successfully sent or failed.
A datetime channel "lastExecution", which gets updated when successfully sent.
A string channel "result", which could be updated to UNDEF or empty string or "OK" for a successful transmission, or an error message if failed to send to smtp.

An alternative approach is to have the sendMail action wait for completion, and return a result string
`val myResults = sendMail(x,y)`
but this does not feel in keeping with openHAB design principles.

**Comment by clinique** [comment]
It is not clearly documented, but based on the source code, sendMail actually returns a boolean telling if the operation is a success or not.
