### ISSUE TITLE
[netatmo] NAPresenceCameraHandlerTest uses internal I18nProviderImpl class

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#7949]
When you build the ported OH3 add-ons, the build fails to compile the `NAPresenceCameraHandlerTest` class because the `I18nProviderImpl` constructor changed with https://github.com/openhab/openhab-core/pull/1487.

There should not be any usages of internal OHC/ESH classes in tests at all and it would be better if the build failed whenever they are used in imports.

Instead the `NAPresenceCameraHandlerTest` should use the `TimeZoneProvider` interface and use it with a mock for instance.

Can you have a look at this @Novanic? This import was added in https://github.com/openhab/openhab-addons/pull/7927.

**Comment by Novanic** [comment]
Ok, how can I trigger the build? Is there a separated Git project?

**Comment by wborn** [comment]
You can port the add-ons using this [script](https://gist.github.com/wborn/0e3cd275be724e827ef88bb04b7eb12a). But I don't there's any need. Just remove the `I18nProviderImpl` from the imports and use something that implements the `TimeZoneProvider` instead. If that builds with OH2 it should also work with OH3. :-)

**Comment by Novanic** [comment]
Ok, the pull-request is created, see #7959

**Comment by wborn** [comment]
Thanks it works!
