### ISSUE TITLE
[telegram] add sendAnimation and sendVideo

### ISSUE THREAD

**Issue by bgilmer77** [openhab/openhab-addons#7971]
Please add sendAnimation and sendVideo to the Telegram add-on.

I have confirmed that those functions are supported by the Telegram API.

Evidence for sendAnimation:
```
https://api.telegram.org/bot[your_API_key]/sendAnimation?chat_id=[your_chatId]&animation=http://gif.server.ip/gif_animation.gif
```

Evidence for sendVideo:
```
https://api.telegram.org/bot[your_API_key]/sendVideo?chat_id=[your_chatId]&video=http://gif.server.ip/gif_animation.gif
```

This would be extremely useful in conjunction with the ipcamera binding which generates both .gif and .mp4 files which can be linked to motion events.

Thank you.

**Comment by bgilmer77** [comment]
Another way to handle this enhancement request would be to provide the ability to pass a Telegram API command directly from the add-on straight through to https://api.telegram.org.  This way one modification would allow the add-on to be used as Telegram modifies their API without having to make repeated updates to the add-on.  For example, how about this?

```
sendTelegramAPIComand("[botname]", "[telegram_api_command"])
```

So to send an animation, you would enter this.

```
sendTelegramAPICommand("bot1", "bot[your_API_key]/sendAnimation?chat_id=[your_chatId]&animation=http://gif.server.ip/gif_animation.gif")

**Comment by J-N-K** [comment]
How would you use animation or video from rules?

**Comment by bgilmer77** [comment]
> How would you use animation or video from rules?

Here is an example with an attachment.  The `ipcamera` addon also will create a short .mp4 file, and you could send this as well instead of a .gif.

```
rule "doorbell Send Pushover with attachment"
when
        Item doorbellCreateGIF changed from ON to OFF
then
        if (doorbellSendGIF.state == ON) {
                logInfo("doorbell", "Sent pushover motion GIF")
                sendPushoverMessage(pushoverBuilder("doorbell motion").withAttachment("/tmpfs/doorbell/ipcamera.gif"))
        }
end

**Comment by mtzro2003** [comment]
+1 

I use the telegram action for text notification, but to send video I have to resort to an external script.
My use case is: whenever the front door opens, I start recording to an mp4. When front door closes, I stop recording and send the mp4 file to my telegram chat_id.
Here's the script I use:
```
#!/bin/sh

# $1 = chat_id
# $2 = video.mp4
# $3 = duration
# $4 = width
# $5 = height

/usr/bin/ffmpeg -loglevel error -i "$2" -ss 00:00:00.500 -vf  "scale=320:180" -frames:v 1 /etc/openhab2/html/recordings/thumb.jpg
/usr/bin/curl -s -F chat_id="$1" -F video=@"$2" -F caption=$(basename "$2") -F duration=$3 -F width=$4 -F height=$5 -F supports_streaming=true -F thumb=@/etc/openhab2/html/recordings/thumb.jpg https://api.telegram.org/botXXXXXXXXXXXXXXX/sendVideo
rm -f /etc/openhab2/html/recordings/thumb.jpg
```

The openhab rule is something like this:
```
......................
val telegram_chat = "-XXXXXXXXX"
val rec = "/etc/openhab2/html/recordings/Front_Door_" + Front_Door_RecordTimestamp.state.toString + ".mp4"
val rec_details = executeCommandLine("/usr/bin/ffprobe -v quiet -show_entries format=duration -show_entries stream=width,height -of json " + rec, 1000)
val rec_duration = Double::parseDouble(transform("JSONPATH",".format.duration",rec_details))
if(rec_duration > 0) {
	val rec_width = transform("JSONPATH","$.streams[0].width",rec_details)
	val rec_height = transform("JSONPATH","$.streams[0].height",rec_details)
	
	val result = executeCommandLine("/etc/openhab2/scripts/my_scripts/sendTelegramVideo.sh " + telegram_chat + " " + rec + " " + rec_duration + " " + rec_width + " " + rec_height,30000)
	if(transform("JSONPATH", "$.ok", result) != "true") {
		logError("sendTelegramVideo", result)
		getActions("telegram","telegram:telegramBot:openHAB").sendTelegram(-XXXXXXXXX + "L","sendTelegramVideo.sh result:\n" + transform("JSONPATH", "$.ok", result))
	}
	executeCommandLine("/usr/bin/find /etc/openhab2/html/recordings/ -mtime +7 -delete")
......................
```

**Comment by Skinah** [comment]
Closing issue as this is added and waiting for a merge. 
Feel free if your using openHAB V3.x to use the precompiled jar to test with found at the following link.

https://github.com/openhab/openhab-addons/pull/8969

**Comment by J-N-K** [comment]
Please close issues automatically when PR are merged.
