### ISSUE TITLE
[amazonechocontrol] Announcement/TTS ERROR POST url Error "Too Many Requests"

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab-addons#7995]
When sending a TTS or Announcement to more than one echo device, you can get the error "Too Many Requests". I believe this is because the post is made to the same api end point url too frequently.

This results in announcements not being made, the announcement not being displayed, or the volume not being restored.

The error is:
```
openhab.log.7:2020-06-23 13:48:19.433 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.amazonechocontrol.internal.handler.EchoHandler@25e4be35': POST url 'https://alexa.amazon.ca/api/behaviors/preview' failed: Too Many Requests
openhab.log.7-org.openhab.binding.amazonechocontrol.internal.HttpException: POST url 'https://alexa.amazon.ca/api/behaviors/preview' failed: Too Many Requests
openhab.log.7-2020-06-23 13:48:21.348 [DEBUG] [mazonechocontrol.internal.Connection] - POST: {"behaviorId":"PREVIEW","sequenceJson":"{\"@type\":\"com.amazon.alexa.behaviors.model.Sequence\",\"startNode\":{\"@type\":\"com.amazon.alexa.behaviors.model.SerialNode\",\"nodesToExecute\":[{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"Alexa.DeviceControls.Volume\",\"operationPayload\":{\"deviceType\":\"A3VRME03NAXFUB\",\"deviceSerialNumber\":\"G0016H0295040LMH\",\"locale\":\"\",\"customerId\":\"A2CLIDWUORIW31\",\"value\":80}},{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"AlexaAnnouncement\",\"operationPayload\":{\"deviceType\":\"A3VRME03NAXFUB\",\"deviceSerialNumber\":\"G0016H0295040LMH\",\"locale\":\"\",\"customerId\":\"A2CLIDWUORIW31\",\"expireAfter\":\"PT5S\",\"content\":[{\"locale\":\"\",\"display\":{\"title\":\"OH Message\",\"body\":\"Switch is OFF\"},\"speak\":{\"type\":\"text\",\"value\":\"Switch is OFF\"}}],\"target\":{\"customerId\":\"A2CLIDWUORIW31\",\"devices\":[{\"deviceSerialNumber\":\"G0016H0295040LMH\",\"deviceTypeId\":\"A3VRME03NAXFUB\"}]}}},{\"@type\":\"com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode\",\"type\":\"Alexa.DeviceControls.Volume\",\"operationPayload\":{\"deviceType\":\"A3VRME03NAXFUB\",\"deviceSerialNumber\":\"G0016H0295040LMH\",\"locale\":\"\",\"customerId\":\"A2CLIDWUORIW31\",\"value\":25}}]}}","status":"ENABLED"}
```
## Expected Behavior
You should be able to send an announcement to several echo devices at the same time (or at least with minimal delay between them).

## Current Behavior
If you send an announcement to more than one echo device, then sometimes you get the error message given above, which results in the announcement not being made, displayed or the original volume not being restored on some echo devices. This is somewhat random, as it depends on the timing as to when `Too Many Requests` is triggered.

The more echo devices you send the announcement to, the more likely the error is to happen. It also depends on the length of the announcement, as the restore volume api call timing can conflict with the api call for the next echo announcement. This is why a simple delay between announcements for echo devices doesn't fix the issue.

I believe the same would happen with TTS as well.

## Possible Solution
The solution would be to implement a minimum delay between api calls. I don't know what Amazon allows as the minimum delay between api calls, so some experimentation may be required. something in the range of 0.5 to 3 seconds should work.

## Steps to Reproduce (for Bugs)
```
rule "Test Echo Announcement"
when
    Item test_switch changed
then
    var msg = '{ "sound": true, "speak": "This is a test Announcement", "title": "Message", "body": "This is a test Announcement", "volume": 80 }'
    echo_1.sendCommand(msg)
    echo_2.sendCommand(msg)
    echo_3.sendCommand(msg)
    echo_4.sendCommand(msg)
end
```
if you have 4 different echo's defined as
```
String echo_1 "Announcement [%s]" { channel="amazonechocontrol:echo:account1:<serial Number>:announcement" }
String echo_2 "Announcement [%s]" { channel="amazonechocontrol:echo:account1:<serial Number>:announcement" }
String echo_3 "Announcement [%s]" { channel="amazonechocontrol:echo:account1:<serial Number>:announcement" }
String echo_4 "Announcement [%s]" { channel="amazonechocontrol:echo:account1:<serial Number>:announcement" }
```
Activating `test_switch` will produce the error after a couple of switches.

## Context
I am trying to make an announcement throughout the whole house, not just on one echo device. eg "Front Door Unlocked", "X Just Arrived Home" etc. Otherwise making an announcement assumes you know which room a person is in - which mostly you don't.

## Your Environment
* Using Current 2.5.6 V of Openhab, with 2.5.7 Snapshot version of amazonechocontrol (but happens in 2.5.6 version as well).
* Running in Ubuntu 18.04 Server VM with Java 8.

**Comment by NickWaterton** [comment]
Update,
There is an alternative way of making announcements, in that it is possible to make announcements to a multi-room audio group. The current binding does not expose this functionality, in that a WHA Thing does not have an announcement channel.

It would be possible to add this functionality. Speak is not possible to multi-room audio groups, but Announcements are, if the notification feature is turned on for each device in the group.

**Comment by J-N-K** [comment]
fixed
