### ISSUE TITLE
[warmup] Add Warmup Binding

### ISSUE THREAD

**Issue by jamesmelville** [openhab/openhab-addons#7996]
I'm in the process of developing a new binding for the Warmup 4iE controller https://www.warmup.co.uk/thermostats/smart/4ie-underfloor-heating, using the API at https://my.warmup.com/. This has been previously requested, and may have been worked on by others: https://community.openhab.org/t/warmup-thermostat-41e/37394/5

**Comment by hmerk** [comment]
Closed as contribution has been merged
