### ISSUE TITLE
[mqtt.homeassistant] - allow setting of base topic 

### ISSUE THREAD

**Issue by psyciknz** [openhab/openhab-addons#7997]
Hoping for a method of changing the base topic of a homeassistant based item away from the default of `homeassistant`  So in an item it would just be an alteration of the base topic :
```
 "channels": [],
      "configuration": {
        "properties": {
          "topics": [
            "binary_sensor/0x00158d00027bac3a/contact",
            "sensor/0x00158d00027bac3a/linkquality",
            "sensor/0x00158d00027bac3a/battery"
          ],
          "basetopic": "homeassistant"
        }
      },
```

I thought i saw something similar for a homie based item?

**Comment by ccutrer** [comment]
This is already implemented.
