### ISSUE TITLE
Editing the config files causes infinate loop

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-addons#8]
When I run the latest OH2 snapshot and modify one of the config files (e.g. demo.items, demo.things, etc) there seems an infinate loop with  processing/refreshing.

The only way to stop this is by closing.
e.g.:
08:09:59.840 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.items'                                08:09:59.841 DEBUG o.e.s.m.i.i.GenericItemProvider[:147] - Processing binding configs for items from model 'demo.items'08:09:59.842 DEBUG o.e.s.m.i.i.GenericItemProvider[:126] - Read items from model 'demo.items'                          08:09:59.844 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.sitemap'                              08:09:59.846 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.items'                                08:09:59.847 DEBUG o.e.s.m.i.i.GenericItemProvider[:147] - Processing binding configs for items from model 'demo.items'08:09:59.847 DEBUG o.e.s.m.i.i.GenericItemProvider[:126] - Read items from model 'demo.items'                          08:09:59.850 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.sitemap'                              08:09:59.852 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.items'                                08:09:59.854 DEBUG o.e.s.m.i.i.GenericItemProvider[:147] - Processing binding configs for items from model 'demo.items'08:09:59.854 DEBUG o.e.s.m.i.i.GenericItemProvider[:126] - Read items from model 'demo.items'                          08:09:59.857 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.sitemap'                              08:09:59.859 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.items'                                08:09:59.860 DEBUG o.e.s.m.i.i.GenericItemProvider[:147] - Processing binding configs for items from model 'demo.items'08:09:59.860 DEBUG o.e.s.m.i.i.GenericItemProvider[:126] - Read items from model 'demo.items'                          08:09:59.863 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.sitemap'                              08:09:59.865 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.items'                                08:09:59.866 DEBUG o.e.s.m.i.i.GenericItemProvider[:147] - Processing binding configs for items from model 'demo.items'08:09:59.866 DEBUG o.e.s.m.i.i.GenericItemProvider[:126] - Read items from model 'demo.items'                          08:09:59.868 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:97] - Refreshing model 'demo.sitemap'

**Comment by marcelrv** [comment]
Quick update on this older issue (no solution though :( )

For now I believe the rootcause of the issue is the interaction of OH2 with the file and with the installed virus scanner (McAfee On-Access scan). I believe OH causes the virusscanner to be triggered and somehow that triggers again the processing in OH


21:11:48.963 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'logging.cfg'
21:11:48.971 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'runtime.cfg'
21:11:48.979 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'logging.cfg'
21:11:48.988 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'runtime.cfg'
21:11:48.996 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'logging.cfg'
21:11:49.004 [DEBUG] [.c.d.internal.ConfigDispatcher:222  ] - Processing config file 'runtime.cfg'

**Comment by nhimden** [comment]
I run version: 2.0.0-alpha2 on Windows 8.1 32 bit.
Error:
C:\OpenHab\openhab-2.0.0.alpha2-runtime>start.bat
Launching the openHAB runtime...
16:19:44.492 [main] DEBUG o.o.core.init.internal.InitActivator - UUID file alrea
dy exists at 'C:\OpenHab\openhab-2.0.0.alpha2-runtime\userdata\id\uuid' with con
tent '4b79ff18-a94b-41f1-901d-b807baafbb61'
16:19:44.508 [main] DEBUG o.o.core.init.internal.InitActivator - Created file 'C
:\OpenHab\openhab-2.0.0.alpha2-runtime\userdata\id\version' with content '2.0.0'

16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - BundleEvent STARTED
16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - BundleEvent STARTED
16:19:44.633 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - FrameworkEvent INFO
16:19:44.914 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.914 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.914 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - BundleEvent STARTED
16:19:44.930 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.930 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - ServiceEvent REGISTERED
16:19:44.961 [org.openhab.core.init.internal.OSGILogListener$NLogListener@1a65e4
e] INFO  OSGi - BundleEvent STARTED

My java version:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) Client VM (build 25.45-b02, mixed mode)

Please help!
