### ISSUE TITLE
Somfy myLink Binding missing in 2.5.6 feature.xml

### ISSUE THREAD

**Issue by calderoc** [openhab/openhab-addons#8008]
The add-on Somfy myLink (Binding #5652) is missing a `feature.xml` file and this prevents the binding from showing up in both paperUI and the console.

It's also missing in the `bom/openhab-addons/pom.xml`, that should be fixed too, but has no effect on runtime of the binding.

**Comment by Hilbrand** [comment]
It's missing the feature.xml. the missing pom.xml is no problem.

**Comment by LoungeFlyZ** [comment]
I'll get this fixed up. Thanks for letting me know.

**Comment by calderoc** [comment]
HI, i just updated to  2.5.7-1 and the Somfy myLink binding  (#5652) still isn't showing up in PaperUI or the console via "feature:list"

**Comment by LoungeFlyZ** [comment]
Thanks for letting me know. I'll get this fixed. Apologies.
