### ISSUE TITLE
zwave2.0-SNAPSHOT: NullPointerException from ZWaveController.java:1080

### ISSUE THREAD

**Issue by smyrman** [openhab/openhab-addons#801]
Zwave binding 2.0-SNAPSHOT as of 2016-04-17 gives a NullPointerException. The exception occured when trying to add a Zwave thing (Aeon Lab SmartSwitch 6) from the Paper UI. As a result, the Paper UI hangs, and I need to restart Openhab2

```
root@osmc:~# systemctl status openhab2
* openhab2.service - Starts and stops the openHAB Home Automation Bus
   Loaded: loaded (/etc/systemd/system/openhab2.service; enabled)
   Active: active (running) since Sun 2016-04-17 00:44:49 CEST; 11min ago
     Docs: http://www.openhab.org
 Main PID: 1355 (karaf)
   CGroup: /system.slice/openhab2.service
           ├─1355 /bin/sh /opt/openhab2/runtime/karaf/bin/karaf
           └─1468 /usr/bin/java -Dopenhab.home=/opt/openhab2 -Dopenhab.conf=/opt/openhab2/conf -Dopenhab.runtime=/opt/openhab2/runtime -Dopenhab.userdata=/opt/openhab2/userdata -Dorg.osgi.service.http.port=80...

Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1080)
Apr 17 00:55:54 osmc start.sh[1355]: java.lang.NullPointerException
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.handler.ZWaveThingHandler.ZWaveIncomingEvent(ZWaveThingHandler.java:1068)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController.notifyEventListeners(ZWaveController.java:536)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveMeterCommandClass.handleApplicationCommandRequest(ZWaveMeterCommandClass.java:163)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.serialmessage.ApplicationCommandMessageClass.handleRequest(ApplicationCommandMessageClass.java:119)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:236)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:203)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:197)
Apr 17 00:55:54 osmc start.sh[1355]: at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1080)
```

**Comment by smyrman** [comment]
Note: Once Openhab was restarted, the device was added, and there was no issues. Maybe this is a timing issue? Something trying to access a value while it's not set?

**Comment by cdjackson** [comment]
I will add some thread synchronisation and we can see if that helps (hopefully it will solve the problem).

**Comment by smyrman** [comment]
Cool. I have only seen it once so far, so probably uncommon.

**Comment by cdjackson** [comment]
I also saw it tonight - it’s not a synchronisation issue I think. I’ve made a change, but as you say, it’s not common so I’m not sure it’s fixed… Let me know if it re-occurs…

**Comment by foxytocin** [comment]
Latest OH-Snapshot #248

```
13:01:03.313 [ERROR] [ome.core.thing.internal.ThingManager] - Exception occured during notification about bridge status change on thing 'zwave:device:153e307c039:node3': null
java.lang.NullPointerException
    at org.openhab.binding.zwave.handler.ZWaveThingHandler.initialiseNode(ZWaveThingHandler.java:155)[162:org.openhab.binding.zwave:2.0.0.201604180954]
    at org.openhab.binding.zwave.handler.ZWaveThingHandler.bridgeStatusChanged(ZWaveThingHandler.java:422)[162:org.openhab.binding.zwave:2.0.0.201604180954]
    at org.eclipse.smarthome.core.thing.internal.ThingManager$13.run(ThingManager.java:820)[102:org.eclipse.smarthome.core.thing:0.8.0.201604151434]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_65]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_65]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)[:1.8.0_65]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)[:1.8.0_65]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_65]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_65]
    at java.lang.Thread.run(Thread.java:745)[:1.8.0_65]
```

Z-Wave Controller is still working. DEBUG shows that all the data is reported correctly. Also data from all nodes are incoming. But openhab doesn't react to them (don't updates items).
In Habmin2 controller is marked as working. All the nodes are "false / red". Removing and readding one node worked for 10 seconds. Becomes "green" and then false back to "false / red".

**Comment by ifUpEth0** [comment]
I can replicate this error by using the paper ui to send a "Hard Reset Controller". I get this exception every time.

`java.lang.NullPointerException
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ZWaveCommandProcessor.checkTransactionComplete(ZWaveCommandProcessor.java:71)
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ControllerSetDefaultMessageClass.handleRequest(ControllerSetDefaultMessageClass.java:37)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:236)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:203)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:197)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1080)`

With debug I captured the following:

`20:32:05.063 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:5abab6a5' changed from ONLINE to OFFLINE
20:32:05.070 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Connecting to serial port '/dev/ttyUSB0'
20:32:05.079 [INFO ] [ing.zwave.handler.ZWaveSerialHandler] - Serial port is initialized
20:32:05.083 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:5abab6a5:node22' changed from OFFLINE (BRIDGE_OFFLINE) to OFFLINE
20:32:05.084 [INFO ] [mmandclass.ZWaveSecurityCommandClass] - Update networkKey
20:32:05.085 [INFO ] [ve.internal.protocol.ZWaveController] - Starting ZWave controller
20:32:05.087 [INFO ] [ve.internal.protocol.ZWaveController] - ZWave timeout is set to 5000ms. Soft reset is false.
20:32:05.089 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:device:5abab6a5:node22' changed from OFFLINE to OFFLINE (BRIDGE_OFFLINE)
20:32:05.093 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 9 to 10
20:32:06.988 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
20:32:06.992 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 10 to 11
java.lang.NullPointerException
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ZWaveCommandProcessor.checkTransactionComplete(ZWaveCommandProcessor.java:71)
        at org.openhab.binding.zwave.internal.protocol.serialmessage.ControllerSetDefaultMessageClass.handleRequest(ControllerSetDefaultMessageClass.java:37)20:32:07.826 [ERROR] [ve.internal.protocol.ZWaveController] - Exception during ZWave thread: Input 2.

        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:236)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:203)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:197)
        at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1080)
20:32:07.829 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 10 to 11
20:32:08.094 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 11 to 12
20:32:08.097 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 11 to 12
20:32:08.100 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 12 to 13
20:32:08.103 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 12 to 13
20:32:08.110 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 13 to 14
20:32:08.114 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 13 to 14
20:32:08.118 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 14 to 15
20:32:08.122 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 14 to 15
20:32:08.124 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 15 to 16
20:32:08.126 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 15 to 16
20:32:08.128 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 16 to 17
20:32:08.175 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 16 to 17
20:32:08.176 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
20:32:08.176 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
20:32:08.177 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
20:32:08.177 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
20:32:08.177 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
20:32:08.177 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
20:32:08.182 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 17 to 18
20:32:08.183 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 17 to 18
20:32:08.187 [INFO ] [me.event.ThingStatusInfoChangedEvent] - 'zwave:serial_zstick:5abab6a5' changed from OFFLINE to ONLINE
20:32:08.233 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 18 to 19
20:32:08.236 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 18 to 19
20:32:08.239 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 19 to 20
20:32:08.242 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 19 to 20
20:32:08.244 [WARN ] [zwave.handler.ZWaveControllerHandler] -
20:32:11.990 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Too many retries. Discarding message: Message: class=SetDefault[0x42], type=Request[0x00], priority=High, dest=255, callback=0, payload=
20:32:12.004 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 20 to 21
20:32:12.041 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 20 to 21
20:32:12.042 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
20:32:12.043 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
20:32:12.043 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
20:32:12.044 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
20:32:12.044 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
20:32:12.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
20:32:12.047 [WARN ] [ve.internal.protocol.ZWaveController] - NODE 1: Attempting to add node that already exists
20:32:16.991 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 2 attempts left!
20:32:16.995 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 21 to 22
20:32:17.043 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
20:32:17.044 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
20:32:17.044 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
20:32:17.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
20:32:17.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
20:32:17.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
20:32:17.046 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 21 to 22
20:32:17.047 [WARN ] [ve.internal.protocol.ZWaveController] - NODE 1: Attempting to add node that already exists
20:32:21.992 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 1 attempts left!
20:32:21.995 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 22 to 23
20:32:22.043 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 22 to 23
20:32:22.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
20:32:22.047 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
20:32:22.048 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
20:32:22.050 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
20:32:22.051 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
20:32:22.052 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
20:32:22.054 [WARN ] [ve.internal.protocol.ZWaveController] - NODE 1: Attempting to add node that already exists
20:32:26.993 [ERROR] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Timeout while sending message. Requeueing - 0 attempts left!
20:32:26.997 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_ack changed from 23 to 24
20:32:27.045 [INFO ] [marthome.event.ItemStateChangedEvent] - zwave_serial_zstick_5abab6a5_serial_sof changed from 23 to 24
20:32:27.045 [INFO ] [age.SerialApiGetInitDataMessageClass] - NODE 1: Node found
20:32:27.046 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller using Controller API
20:32:27.046 [INFO ] [age.SerialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
20:32:27.047 [INFO ] [age.SerialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
20:32:27.047 [INFO ] [age.SerialApiGetInitDataMessageClass] - # Nodes = 1
20:32:27.047 [INFO ] [age.SerialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
20:32:27.049 [WARN ] [ve.internal.protocol.ZWaveController] - NODE 1: Attempting to add node that already exists
20:32:31.994 [WARN ] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Too many retries. Discarding message: Message: class=SerialApiGetInitData[0x02], type=Request[0x00], priority=High, dest=255, callback=0, payload=`

**Comment by cdjackson** [comment]
> I can replicate this error 

This looks like a completely different error. Please start a separate issue, and please provide a debug logfile.

**Comment by ifUpEth0** [comment]
I am taking my comment and making a separate issue thanks.

**Comment by cdjackson** [comment]
It would be good to know if this is still occurring from tomorrows build. If so, please provide an updated log.

**Comment by smyrman** [comment]
I will let you see if I see it again.

**Comment by cdjackson** [comment]
Closing - if this still exists, please re-open with an updated log as the binding has changed quite a bit since this was opened.
