### ISSUE TITLE
[astro] Provide position channels azimuth and elevation for events

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#8016]
Would it be possible that the binding provides the position data for the events it supports. For example position at rise, noon, set, daylight start, daylight end ...

**Comment by clinique** [comment]
There existed an 'action' package on OH1 that could answer this. This has not been transposed when migrated to OH2.

**Comment by DerOetzi** [comment]
I want to generate a graphic like the following directly inside rules with data from astro binding directly when any of the input values changes. Because at the moment I cron trigger an external python script on the machine which recalculate with astral library all values and as you can see in screenshot, has some small deviations from astro binding.

![grafik](https://user-images.githubusercontent.com/2345662/85987712-49d0d800-b9ee-11ea-8f02-1a0f73c81a0e.png)

As additional inputs which I don't get from astro binding at the moment, would be the sun positions for all events like sunrise, sunset, dawns, noon and so on to set markers like the green and red one. I see two possible solutions for this. Like I suggested before position channels for all events or another would be a rule action getAzimuth and getElevation for a given datetime

**Comment by clinique** [comment]
It's what I did in the PR, with the ability to get date time for each event, and then getAzimuth and getElevation for a given timestamp.

**Comment by DerOetzi** [comment]
Oops, I didn't recognize your linked PR, sorry! Yes, this is exactly what I was searching for, but not only for sun. Can you please add those functions for moon thing as well?

**Comment by clinique** [comment]
I did add Azimuth and Elevation for moon as well.
