### ISSUE TITLE
[netatmo] Add support for favorite stations

### ISSUE THREAD

**Issue by Crazyphil** [openhab/openhab-addons#8020]
Since pull request #7912 updated the netatmo-swagger-decl reference a few days ago, it is now also possible to request a user's favorite weather stations in addition to their own. This is useful for example when a user doesn't own a Netatmo device, but they want to read outdoor temperatures and get weather data from their neighborhood.

The required change is simple: In class `NetAtmoBridgeHandler`, method `getStationsDataBody(String)`, change the line
```java
NAStationDataBody data = getStationApi().getstationsdata(equipmentId).getBody();
```
to
```java
NAStationDataBody data = getStationApi().getstationsdata(equipmentId, true).getBody();
````
(i.e. set the parameter `getFavorites` of the method call to `getstationsdata(String, Boolean)` to true.

**Comment by lolodomo** [comment]
Interesting. Will you provide a PR? ?

**Comment by lolodomo** [comment]
This silence probably means you will not.

I will try in this case.
This might be just a false to replace by a true in the code.

**Comment by lolodomo** [comment]
It works. We just have to find an appropriate naming for the discovered things (stations and modules) to avoid confusion between the local weather station and the favorite weather stations.

**Comment by Novanic** [comment]
@lolodomo Are still working on it? Otherwise I would suggest that I add the station_name to the thing name and something like "(fav)" as you suggested. Would that be good enough to merge it to 2.5.7 or later?

It seems that the station name contains the city of the station when the user hasn't setup a station name, that could help some users to identify/differ the stations. I requested also that the street name should be available via the Netatmo forum but I don't know if and when it will be available...

**Comment by lolodomo** [comment]
I let you finish the enhancement, you were the first to propose a PR.
I let you propose the best solution you can find for the naming of the discovered stations and modules in the inbox. I can confirm that when I tried, the favorite station I selected has the name of the city in the API.
I disagree with you with the need of a configuration setting. On that point, I would like @clinique 's advice to converge to the best solution. In my opinion, I see no problem to have favorite stations being systematically discovered by the binding and put in the inbox. Then the user can ignore them. But maybe I am wrong.
This will be a small enhancement, so you can certainly expect a fast feedback from myslef and @clinique and very probably a fast merge.
I have no idea when 2.5.7 will be released.

**Comment by clinique** [comment]
I join you @lolodomo , adding favorite stations on Netatmo website is already a deliberate action, so no need of a dedicated option FMPOV

**Comment by Novanic** [comment]
The pull-request is now updated. The naming logic was extended and the dedicated option is removed again.

See https://github.com/openhab/openhab-addons/pull/8112#issuecomment-658396514
