### ISSUE TITLE
[openSprinkler] Channel nextDuration does not accept values

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#8028]
While connecting openHAB to openSprinkler i encountered the following behavior with the channel nextDuration. The channel does not accept value of any format i could think of.

The item is defined as described in the documentation and i build a selection as desired in the documentation to set the next duration.

`Selection item=RB_BM_SC_SprinklerValve01_NextDuration label="Laufzeit [%.0f s]" mappings=[300="5 min", 600="10 min"]`

by selecting on of the values i got an error in the log

` [INFO ] [.handler.OpenSprinklerStationHandler] - Ignoring implausible non-QuantityType command for NEXT_DURATION`

Any other label with %d or mappings or with out doesn't succeed either. In addition the option to use a sendCommand from a rule doen't work too.

## Expected Behavior
The channel should accept a value an set it in openSprinkler

## Current Behavior
As described above. The binding does not accept any value and openSprinkler starts with a default of 18 hours

## Possible Solution
A soulution might be to switch channel from Numer:Time to simply Number

## Your Environment
Debain based openHAB installation on a VM with latest 2.5.6 openHAB.

**Comment by TBail** [comment]
I tried to display the current NextDuration vaue in the Paper ui and it did not work.

`Text item=RB_BM_SC_SprinklerValve01_NextDuration label="Next Duration [%d %unit%]" icon="time_timer"
Text item=RB_BM_SC_SprinklerValve01_NextDuration label="Next Duration [%.0f %unit%]" icon="time_timer"
Text item=RB_BM_SC_SprinklerValve01_NextDuration label="Next Duration [%.1f %unit%]" icon="time_timer"`

just showing ERR in Paper UI. If i erase the %unit% option the value in seconds without any unit is displayed

**Comment by galexey** [comment]
I can write values in seconds, but it seems that the binding is not sending the stationState ON to opensprinkler.
I do get updates on stationState and remainingWaterTime from opensprinkler.
I´m not sure if this is connected.

**Comment by TBail** [comment]
@galexey Could you show us your items and sitemap. If openSprinkler is online should be shown in the papaer UI under Configuration Things

**Comment by galexey** [comment]
I use config-files:
**mysprinkler.things:**
```
Bridge opensprinkler:http:http @ "opensprinklertest" [hostname="10.10.20.101", port=8080, password="XXXXXX", refresh=10] {
    
    Thing station 01 @ "opensprinklertest" [stationIndex=0]
    Thing station 02 @ "opensprinklertest" [stationIndex=1]
    Thing station 03 @ "opensprinklertest" [stationIndex=2]
    Thing station 04 @ "opensprinklertest" [stationIndex=3]
    Thing station 05 @ "opensprinklertest" [stationIndex=4]
    Thing device device @ "opensprinklertest"
 }
```


**mysprinkler.items:**
```
Switch opensprinkler_rainsensor                             { channel="opensprinkler:station:http:device:rainsensor" }
Number:ElectricCurrent opensprinkler_currentDraw            { channel="opensprinkler:station:http:device:currentDraw"}

Switch opensprinkler_station01_stationState                 { channel="opensprinkler:station:http:01:stationState" }
Number:Time opensprinkler_station01_station01RaminingTime   { channel="opensprinkler:station:http:01:remainingWaterTime" }
Number:Time opensprinkler_station01_station01NextDuration   { channel="opensprinkler:station:http:01:nextDuration" }
Switch opensprinkler_station01_queued                       { channel="opensprinkler:station:http:01:queued" }

Switch opensprinkler_station02_stationState                 { channel="opensprinkler:station:http:02:stationState" }
Number:Time opensprinkler_station02_station01RaminingTime   { channel="opensprinkler:station:http:02:remainingWaterTime" }
Number:Time opensprinkler_station02_station01NextDuration   { channel="opensprinkler:station:http:02:nextDuration" }
Switch opensprinkler_station02_queued                       { channel="opensprinkler:station:http:02:queued" }
```



opensprinkler_station01_stationState and opensprinkler_station01_station01RaminingTime are update when the programm runs in opensprinkler.

opensprinkler_station01_station01NextDuration, opensprinkler_station01_queued, opensprinkler_currentDraw and opensprinkler_rainsensor do not work. for me.

**Comment by TBail** [comment]
Luckily it is now working. Nothin done except installing the corona binding. So i clse this issue.
