### ISSUE TITLE
[ecobee] Reduce ecobee:thermostat thing-type default channels

### ISSUE THREAD

**Issue by falmanna** [openhab/openhab-addons#8029]
The `ecobee:thermostat` thing type has too many default channels at the moment, which makes it really heavy and messy for users who use the UI setup. 
I think that only the thermostat-related channels can be kept, while everything else should be switched to an advanced channel.

Also, would it be possible to switch all settings-related channels to the thing configuration? 

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lsiepel** [comment]
Gentle ping @mhilbush as you are listed as codeowner to ecobee binding. This is an old issue and maybe the enhancement request is no longer valid, if so we can close this. Otherwise, would this be something to consider?

**Comment by mhilbush** [comment]
Thanks for the reminder. This definitely fell off my radar screen.

I agree that some of the channels should be made advanced, although not as many as recommended above.

Moving the settings-related channels to the Thing config would be a breaking change, so I don't see where the value of the change offsets the impact.
