### ISSUE TITLE
[amazonechocontrol] Add support for audio tag in SSML

### ISSUE THREAD

**Issue by openPhiL** [openhab/openhab-addons#8037]
Hello!
I found some discussions in the forums related to the audio tag. It is not supported yet. 
So I thought, why not creating a feature request. Haven't found one created yet. I'd love the feature. 

So currently, this command: 
`AmazonEcho_TTS.sendCommand('<speak>Start <audio src="soundbank://soundlibrary/transportation/amzn_sfx_car_accelerate_01" /> 
<break time="1s"/>
 Ende</speak>')`
does behave like this: 
`AmazonEcho_TTS.sendCommand('<speak>Start
<break time="1s"/>
 Ende</speak>')`
the audio tag is just skipped. 

Can you have a look into what needs to be done? 
Thanks!
PhiL

**Comment by J-N-K** [comment]
implemented
