### ISSUE TITLE
[astro] Next visible eclipse

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#8042]
At the moment for example the next total sun eclipse is reported at 2020-12-14 17:15. I'm pretty sure this want be visible here, because sun will be below horizon at this time. Would be great to have the datetime for all sun and moon eclipses which are visible on groundlevel.

**Comment by clinique** [comment]
I took the approach to add the elevation for each kind of eclipse, so you'll definitively know if its visible or not.
