### ISSUE TITLE
[Unifi] - controller/api still reporting wireless device when off network

### ISSUE THREAD

**Issue by psyciknz** [openhab/openhab-addons#8044]
Not particularly a binding issue.  But it seems  that the api and therefore binding are seeing a  missing wireless device as wired after they leave.  So a device never goes offline.

Wondering if there's a way, or changee to the binding that a wireless device would not be allowed to be wired...and therefore be offline.

On OH 2.5.6 and Unifi Controller 5.12.66

**Comment by yfre** [comment]
it looks like well known issue for unifi
https://community.ui.com/questions/Disconnected-clients-still-appear-in-clients-list-of-UniFi-controller/7872e8bf-7783-497c-aa42-dc85defa1a51

**Comment by J-N-K** [comment]
How should we find out which are really wired or wireless?  

Since this is clearly an external bug and needs to be fixed by Ubiquiti, I'm closing here. Looking at their past record in fixing annoying bugs, I would not bet too much money that'll ever happen.

**Comment by psyciknz** [comment]
So let’s not be hasty. 

Since ubiquiti are too slow, we can provide the intent to openHAB users. 

Are there other,  
can the binding detect a device going from
Wireless to wired that we could trigger off?

Can the binding display the wireless channel when Wireless  and null when it’s wired...and reflect that when it switches.


Else the binding for presence detection is not really suitable.
