### ISSUE TITLE
[lcn] Make up and down on RollerShutters interchangeable   

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-addons#8047]
I am using lcn OH2 binding #7509 and rollershutters that apparently have a non-canonical cabling: up and down are reversed.
On OH1 I was using:

`Rollershutter lcnJalousieWZWestLinks "Jalousie WZ West links" (gWZ,  gEGJalousien, gHausJalousie, gJalousienWest, gEGJalousienWest, gLcn) 
{lcn="[UP:myHome:RELAYS.0.54.11------], 
[DOWN:myHome:RELAYS.0.54.10------], [STOP:myHome:RELAYS.0.54.0-------]"}`

On OH2 binding this gets:

`Rollershutter lcnJalousieWZWestLinks "Jalousie WZ West links" (gWZ, gEGJalousien, gHausJalousie, gJalousienWest, gEGJalousienWest, gLcn) {channel="lcn:module:0242e6e48a96:0C050E1DBD:rollershutterrelay#1"}`

With OH2 I have to press the up button to get the shutters down as I can't intervene.

It would be great if the binding was allowing to interchange up and down buttons.
Obviously I would not like to change the cabling.

## Your Environment
* Version used: 2.5.6
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): raspberry pi + Debian

**Comment by fwolter** [comment]
Please try this:

[org.openhab.binding.lcn-2.5.7-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/4859566/org.openhab.binding.lcn-2.5.7-SNAPSHOT.jar.zip)

The Rollershutter Channels provide a configuration parameter, now to invert Up/Down.

**Comment by timbms** [comment]
@fwolter: Did this feature get carried over to OH3? I can't find it in the UI .

**Comment by fwolter** [comment]
Yes, click on "Configure Channel" in the Channels tab of the Thing/module:
![grafik](https://user-images.githubusercontent.com/1894841/103175544-f6d7c080-486a-11eb-84d5-ad25a700dbd4.png)

**Comment by timbms** [comment]
Thanks so much for the quick turnaround.
