### ISSUE TITLE
[lcn] Implement send key command in OH2 binding

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-addons#8060]
It would be great if the new OH2 binding would also support sending keys to lcn modules.
On OH1 it was possible to send keys from switches 
`Switch exampleC456 "M005 C4 lock" {lcn="[ON:myhome:LOCK.0.5.C.---111--], [OFF:myhome:LOCK.0.5.C.---000--]"}`
and also from roller shutters:
`Rollershutter lcnDFFWest "DFF Emma"                               (gDZ, gDFF, gLcn) {lcn="[DOWN:myHome:KEYS.0.44.A5.HIT], [UP:myHome:KEYS.0.44.A6.HIT], [STOP:myHome:KEYS.0.44.A6.BREAK]"}
## Your Environment
* Version used: 2.5.6

**Comment by fwolter** [comment]
This can already be done via an *Action*. https://www.openhab.org/addons/bindings/lcn/#hit-key

Actions can be executed by a Switch via a Rule.

Nevertheless, the examples you are mentioned are realizable via existing Channels. E.g. `keylocktablec` or `rollershutterrelay`. In case you don't want the Rollershutter Command to interact with the relays directly, but with some keys, you could handle this via a Rule.

**Comment by timbms** [comment]
You are right. Got it working with the following item:

`Rollershutter lcnDFFOst  "DFF Arbeitszimmer"                      (gDZ, gDFF, gLcn) 
`

and rule:
```
rule "Rollershutter lcnDFFOst"
when
    Item lcnDFFOst received command 
then
    val actions = getActions("lcn","lcn:module:0242e6e48a96:0C060443B9")
    switch receivedCommand {
        case DOWN: { actions.hitKey("A", 3, "HIT") }
        case UP: { actions.hitKey("A", 4, "HIT") }
        case STOP: { actions.hitKey("A", 4, "BREAK") }
    }
end
```
I will close the issue.
