### ISSUE TITLE
Private link in readme

### ISSUE THREAD

**Issue by jeremystucki** [openhab/openhab-addons#8063]
The following link from the first paragraph is private:  
openHAB Add-on maintainers: https://github.com/orgs/openhab/teams/add-ons-maintainers

Is this intentional?

**Comment by openhab-5iver** [comment]
This is a link to the Maintainer Team. This defaults to their Discussions, which is visible to all members of the openHAB Github organization and it is not possible to make this visible to the public... https://docs.github.com/en/github/building-a-strong-community/about-team-discussions. 

Is this link visible?

https://github.com/orgs/openhab/teams/add-ons-maintainers/members

**Comment by jeremystucki** [comment]
No, it's also private
