### ISSUE TITLE
[mail] Upgrade from 2.5.3 to 2.5.6-2 caused org.sun.jna to fail 

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#8064]
When upgrading from 2.5.3 to 2.5.6-2 I ran into an issue where org.sun.jna would stall and never build properly.  This caused most of my bindings to sit at Resolved and never attempt to start.  The only fix to this was to remove "mail" from the addons.config file.  After removing that, jna started cleanly and the system was able to function like normal.

**Comment by J-N-K** [comment]
Is this still the case now?

**Comment by morph166955** [comment]
I have no idea.  I had so many issues I pulled the mail binding out completely and haven't looked back since.  I've got too many things unstable right now as I move to OH3 that I wouldn't be comfortable dropping something in and assuming that failures aren't related to other issues.

**Comment by J-N-K** [comment]
Since we are at least five versions later and nobody reported issues, it doesn’t seem to be a problem of the binding.
