### ISSUE TITLE
[hue] Discovered things updated too much often in the inbox

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8065]
https://community.openhab.org/t/excessive-disk-access-from-hue-deconz-after-oh-upgrade/101757

@DerOetzi : I think the problem is due to your refactoring (PR #7518) : in case you don't have a thing, `discovery.addSensorDiscovery` is called at each poll (twice per second by default) and the inbox is updated (even if it is only the timestamp).
Same thing for lights and groups (done every 5 seconds).
discovery should be triggered only in case the object was not previously discovered.

Of course, it does not happen in you have openHAB things.

The solution is I think to check if the object is in lastSensorStates before calling discovery.addSensorDiscovery.

**Comment by lolodomo** [comment]
I can confirm the unexpected behaviour.

I am going to prepare a fix.

**Comment by DerOetzi** [comment]
@lolodomo Thanks for doing the fix, for me being offline the whole weekend
