### ISSUE TITLE
[homematic] Binding fails to parse device description from homegear 

### ISSUE THREAD

**Issue by rokru** [openhab/openhab-addons#8081]
The Homematic binding 2.5.2 recognizes the Homegear 0.8.3031 gateway (“online”), but fails to discover the paired devices.

## Expected Behavior
OpenHAB should list all devices paired and listed in homegear as things

## Current Behavior
None of the homegear devices is listed as thing.

I reinstalled homegear and homematic binding and tried to configure OpenHab by files and by PaperUI - but without success.

[This ](http://s158882432.online.de/outgoing/openhab-homematic-homegear-Kruse1-7-2020.log) is an excerpt from a TRACE-log.

## Possible Solution
@MHerbst is guessing that  
> the BinRPC response method uses a data type that is currently not supported by openHAB: Integer64 datatype (209 = 0xd1) has not been used by older Homegear versions and now causes this problem.

## Environment
* I have openHAB version: 2.5.2 running on Synology and homegear 0.8.3031 on Raspbian Buster and HM-MOD-RPI-PCB (Firmware 1.4.1)
* Another user reported the same problem with Openhab 2.5.6-1 and 2.5.6-2 respectively and homegear 0.8.0-3039.

**Comment by Andreas-Fink** [comment]
I can confirm that this problem also occurs under Homegear 0.8.0-3039 on Debian 9.11 in conjunction with openHAB 2.5.5 release build.  (Interface: 1x HM-LGW-O-TW-W-EU for HM-BidCos and 1x RaspberryMatic for HM-IP)

**Comment by MHerbst** [comment]
@rokru  @Andreas-Fink I have  added support for the Integer64 datatype and uploaded a  test jar here: https://github.com/MHerbst/openhab-addons-test

**Comment by rokru** [comment]
@MHerbst Thanks! I followed your instructions, but the data type error still exists. I guess the SNAPSHOT-jar is not operational. In BINDINGS it still reports 2.5.2. How can I assure that the new jar is used and not the old binding?

**Comment by MHerbst** [comment]
@rokru First uninstall the old binding, stop openHAB, completely clear the cache, and start openHAB again. After the restart you can check the active binding on the console with command `bundle:list | grep Homematic`. You should see only one binding with a version starting with 2.5.7.

**Comment by rokru** [comment]
It still binds Homematic 2.5.6...the datatype error is still there. 
I placed your jar in openhab/addons with group/user "openhab" and full access, stopped OH, deleted userdata/cache- & tmp-folders, started again (twice) and checked the version with `bundle:list | grep Add-Ons`
What am I missing? 
In addons.cfg I set the bindings with `binding = astro, chromecast, homematic`.

**Comment by MHerbst** [comment]
@rokru Please remove homematic from addons.cfg. And then try it again (stop, clear cache, start again). As far as I remember the entry in addons.cfg has the same effect as installing the binding via PaperUI and then the binding in the addons folder is probably not loaded.

**Comment by thunders82** [comment]
Thanks @MHerbst,
OpenHab is now discovering items with homegear 0.8.3031

**Comment by rokru** [comment]
> @rokru Please remove homematic from addons.cfg. And then try it again (stop, clear cache, start again). As far as I remember the entry in addons.cfg has the same effect as installing the binding via PaperUI and then the binding in the addons folder is probably not loaded.

@MHerbst Sorry to bother you, but after removing "homematic" from addons.cfg and some more restarts, the new add-on is still not listed as bundle. 
![Kruse-addon-dir](https://user-images.githubusercontent.com/40894519/87715129-2909d000-c7ad-11ea-8f76-bf14a246d425.jpg)
Any idea what might get wrong.

**Comment by MHerbst** [comment]
@roku No problem. Are there any error messages in openhab.log? Sometimes if you uninstall a binding other dependent components are also installed and they must then be installed manually via the console. Best example is upnp.

**Comment by rokru** [comment]
@MHerbst Nope, no errors or any other homematic-entries in openhab.log (TRACE-Mode) and events.log after reboot of the Synology-NAS.

**Comment by MHerbst** [comment]
Hmm strange. Maybe a rights problem and openHAB is now allowed to access the jar. I have no experience with Homematic on Synology. I will creat a PR soon and probably the solution will then be part of the August release.

**Comment by rokru** [comment]
I now transferred OH2 to a Raspberry 2 with Openhabian. With the bundled "old" Homematic Binding 2.5.7 the data type error still exists, which at least proves the communication with homegear. But I still do not get the addon-SNAPSHOT that you kindly provided (2.5.7 resp. 2.5.8) integrated: "bundle:list" does not list any homematic-addon. Access rights of your jar are the same as the "openhab-addons-2.5.7.kar" which comes with the distribution. "openhab.log" does not contain anything related in TRACE-mode. So I probably have to wait for the August release ;-)

**Comment by MHerbst** [comment]
@rokru Maybe the problem is caused by using the openhab-addons.kar file. The .kar also contains the old version of the Homematic binding and I don't know what happens in this case.
