### ISSUE TITLE
|netatmo] Disabling background discovery

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8083]
The current behaviour of the binding is a background update of the discovery inbox every time device data is refreshed by calling the Netatmo API.
This could lead to relatively frequent inbox updates (depending on how refresh intervals are setup by the user), just to update timestamps when there are no changes in the user Netatmo setup, and as a consequence this could contribute to accelerate SD card corruption.
Considering we have a manual discovery that could be triggered by the user at any time (using Paper UI) and considering the discovery is generally only helpful when you setup your OH installation, the disadvantage of this background discovery is IMHO bigger than its advantage.
I propose to add a new setting to control this background discovery and to disable this background discovery by default.
@clinique: WDYT ?

**Comment by clinique** [comment]
I completely agree with you
