### ISSUE TITLE
[enocean] Switching a dimmer on does not restore the last value

### ISSUE THREAD

**Issue by benderl** [openhab/openhab-addons#8086]
## Expected Behavior
I am using the enocean binding with some actuators from Eltako. This issue is related to EEP A5-38-08 with the FUD14 type actuators. These actuators store the last dimming value before turning off and restore it when turned on again with a enocean switch. I expect the same behavoiur if the FUD14 is controlled with openhab.

## Current Behavior
If I send an "ON" command to the item with openhab, the dimmer always lights up to 100%. The last value in the actuator is ignored. The generated payload of the "ON" command:
`Sending data, type RADIO_ERP1, payload A502640009FFAD371D0001FFFFFFFFFF00`
Corresponding to the EEP definition this is:
```
0xA5 = EEP
DB3 = 0x02 = Dimming Type telegram
DB2 = 0x64 = 100% (dimming value)
DB1 = 0x00 = ramping time (not used here)
DB0.7-0.4 = 0x0 = <unused>
DB0.3 = 1 (Data telegram)
DB0.2 = 0 (Absolute value)
DB0.1 = 0 (do not store final value)
DB0.0 = 1 (Switching command ON)
```

## Possible Solution
I am not quite shure, but looking at the [code](https://github.com/openhab/openhab-addons/blob/3c5fb4292c9a24e35da2ba55dde2c3ea0b824283/bundles/org.openhab.binding.enocean/src/main/java/org/openhab/binding/enocean/internal/eep/A5_38/A5_38_08_Dimming.java#L57) there has to be a special enocean command for ON/OFF type commands. Maybe set the dimming value to "0x00" and DB0.0 to "1"?

## Steps to Reproduce (for Bugs)
1. Turn light on to a value < 100% (let's say 50%)
2. Switch light off (enocean rocker or openhab)
3. Switch light on with an enocean rocker
4. The light restores our last 50%
5. Switch light off (enocean rocker or openhab)
6. Send the command "ON" with openhab
7. The light ignores the 50% in memory and dimms up to 100%

## Context
I noticed this behaviour while trying to control the dimmer item with a flow from node-red. In detail I want to control the light with an IKEA Zigbee rocker switch.

## Your Environment
Current stable openhabian with openhab 2.5.6 release build.
Enocean binding from stable release.
Node-Red 1.1

**Comment by benderl** [comment]
@fruggy83 
Can you please have a look at this issue?

**Comment by markusuidl** [comment]
Had a similar problem with my knx dimmers (and openhab-android client).

Added _switchSupport_ to my item, and then I can click on the icon and it restores previous dimmed state. (Of course, dimmer has to be programmed to restore last value).

`Slider item=DG_Hauptlicht switchSupport	`

Don't know if you can apply this to your problem with enocean.

**Comment by benderl** [comment]
Thanks for the hint. I added `switchSupport` to my items but the result is the same.
Recently I upgraded OpenHab to the last stable release 2.5.7.

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
