### ISSUE TITLE
[telegram] Use of % in sendTelegram

### ISSUE THREAD

**Issue by froido** [openhab/openhab-addons#8092]
An error occures when sending a message via telegram binding which includes a %.

## Expected Behavior
1. Percentage symbol (%) in message string shall be escaped by the binding.
2. Raising an error with a clear message.

## Current Behavior
Rule engine throws an error:
[ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'xyz': Conversion = ')'

## Possible Solution
Replace percentage symbol manually.

## Steps to Reproduce (for Bugs)
1. Send a message including % via sendTelegram()

## Your Environment
* Version used: openHAB 2.5.0 Release Build

**Comment by 9037568** [comment]
Need to include the rule you're using

**Comment by Skinah** [comment]
Closing due to no reply requesting more info.
