### ISSUE TITLE
[lcn] Reference modules and groups by segment id and module/group id instead of serial number

### ISSUE THREAD

**Issue by toweosp** [openhab/openhab-addons#8097]
I would like to propose to use a combination of segment and module/group id instead of the serial number to identify LCN things (when using automatic discovery).

It could be represented e.g. in the format 

**S**_<segment_id>_**M**_<module_id>_
resp.
**S**_<segment_id>_**G**_<group_id>_

LCN modules (smart/bus modules) are uniquely identified by this combination. Furthermore - as far as I know - using the module id (in combination with the segment id, if in bigger environments the installation is splitted into segments) is the common approach to identify modules when planning/programming LCN bus systems. (Logical) LCN groups are handled analogously.

In my opinion this would make textual item and rule definitions much more readable and maintainable.

**Comment by fwolter** [comment]
You might be right. From the usability perspective that would be better. Do you want to file a PR?
