### ISSUE TITLE
[netatmo] Support for favorite weather stations

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8111]
It should be possible to include favored weather stations. That enables users to get weather data of other users without having an own Netatmo weather station.

The Netatmo weather API supports it (see parameter "get_favorites"): https://dev.netatmo.com/apidocumentation/weather#getstationsdata

I have already realized it and created a pull-request.

**Comment by lolodomo** [comment]
This feature request was already declared : #8020

**Comment by lolodomo** [comment]
Duplicate
