### ISSUE TITLE
Reliable implementation of thing actions

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8116]
Due to a bug in the core framework, any binding defining thing actions should take care about the implementation to have a reliable behavior. The issue: openhab/openhab-core#1265

Here are the bindings defining thing actions and whether the feature will be reliable or not:

- [x] alarmdecoder (PR #8130)
- [x] astro (PR #8021)
- [x] DMX (PR #8159)
- [x] doorbird (PR #8122) 
- [x] ecobee
- [x] enigma2
- [x] heos (PR #8136)
- [x] hue (PR #8115)
- [x] lcn
- [x] LGwebOS (PR #8114)
- [x] mail (PR #8118) 
- [x] MQTT (PR #8140)
- [x] onkyo (PR #8134)
- [x] pushbullet (PR #8143)
- [x] radiothermostat (PR #8145(
- [x] satel (PR #8128)
- [x] telegram (PR #8141)
- [x] volvooncall (PR #8117)
- [x] xmppclient (PR #8160)

**Comment by lolodomo** [comment]
As an example, you can see how it was implemented in the LCN binding. You need to define an interface + the method invokeMethodOf. This pattern can be applied to any binding.

**Comment by pavel-gololobov** [comment]
Thank you, I will fix it soon.

**Comment by lolodomo** [comment]
@mlobstein for the radiothermostat binding

**Comment by bobadair** [comment]
Ok. I’ll update the alarmdecoder binding. It only supports one action (reboot), which I’d be surprised if anyone is using, so it’s probably not a high priority fix.

Is the plan to revert these changes for 3.0?

**Comment by lolodomo** [comment]
Yes, the plan is to revert these changes as soon as a solution is found on core framework side. We will see later if the problem is fixed in OH 3.

**Comment by mhilbush** [comment]
Submitted PR #8122 for doorbird.

Thanks to @cpmeister for coming up with this workaround.

Thanks to @lolodomo for pushing to get the workaround applied to all the other bindings.

**Comment by clinique** [comment]
@lolodomo : I added astro actions in the list as it contains the workaround, while not being merged as of today, it will help find it back when we'll remove the workaround once core as evoluted.

**Comment by lolodomo** [comment]
I would like to list in the first message only bindings having actions really merged in the 2.5.x branch. 
My idea is to close this issue as soon as possible, not to keep it opened for ever.

**Comment by clinique** [comment]
> I would like to list in the first message only bindings having actions really merged in the 2.5.x branch.
> My idea is to close this issue as soon as possible, not to keep it opened for ever.

I think you can add it back, the Astro actions PR has been merged ;-)

**Comment by lolodomo** [comment]
Marked as reliable. 

Remains one PR to review & merge.

**Comment by lolodomo** [comment]
All bindings have now the workaround implemented. 
All except xmppclient are available in release 2.5.7. xmppclient will be in 2.5.8.
