### ISSUE TITLE
Items: json Data not parsed correctly

### ISSUE THREAD

**Issue by wbuh123** [openhab/openhab-addons#8123]
There is a problem with the items data and external requests of them.
In visual studio the items section of the openhab plugin stays empty
![grafik](https://user-images.githubusercontent.com/48272763/87400862-acfb6680-c5b9-11ea-936e-e1a9124fe22b.png)

If I request them by REST API, I get
![grafik](https://user-images.githubusercontent.com/48272763/87400946-c4d2ea80-c5b9-11ea-97e1-16905defe41f.png)

The raw data ends like this
![grafik](https://user-images.githubusercontent.com/48272763/87401054-e7650380-c5b9-11ea-920f-133b7367b350.png)

Paper UI shows no items at all (endless loading).
![grafik](https://user-images.githubusercontent.com/48272763/87401496-7a9e3900-c5ba-11ea-8c2a-205ba4b7d6c8.png)

In openhab.log every time an external routine seems to start a request there is
![grafik](https://user-images.githubusercontent.com/48272763/87401250-301cbc80-c5ba-11ea-8a59-d90d10e76e0d.png)
The log is full of repetetive messages like this.

More of our investigations can be found here
https://community.openhab.org/t/paper-ui-control-stays-empty/98368/23

**Comment by DerOetzi** [comment]
Do you use Scale Transformation on any item? Had problems with NaN Values. See #8011

**Comment by DerOetzi** [comment]
Duplicate to #8011 

See comments at:
https://community.openhab.org/t/paper-ui-control-stays-empty/98368/23
