### ISSUE TITLE
[homekit] LightSensor doen't work - not picked up by homekit

### ISSUE THREAD

**Issue by 2xPower** [openhab/openhab-addons#8129]
# Expected Behavior
added following items:

Number								FF_Stairwell_Lux			"traphal 1ste"									(FF_Stairwell)										{homekit="LightSensor", channel="knx:device:bridge:generic:Traphal1_lux"}
Number								F2_Stairwell_Lux			"traphal 2de"									(F2_Stairwell)										{homekit="LightSensor", channel="knx:device:bridge:generic:Traphal2_lux"}

Expectation:
Items to be picked up as Light Sensors in Home app. 

## Current Behavior
Items have a value, seem to be working fine. LightSensor is not shown in home app though.
example values, anywhere from null, to 2.03 up to 40.49

## Your Environment

* Version used: openhab2  2.5.7~S170-1  

@yfre if any furter info is needed, let me know

**Comment by yfre** [comment]
@2xPower looks like you are an early adopter :)
the support for light sensor was merged 20 hours ago. it appears immediately on the documentation but you need to update to the latest snapshot of the binding. not sure what is the version "2.5.7~S170-1"
in see in my karaf "2.5.7.202007141927"

![image](https://user-images.githubusercontent.com/11726616/87470793-94bd3300-c61d-11ea-9514-34a332a95b6a.png)

url for update 
`https://openhab.jfrog.io/openhab/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.io.homekit/2.5.7-SNAPSHOT/org.openhab.io.homekit-2.5.7-SNAPSHOT.jar

`

**Comment by 2xPower** [comment]
Whooops, thanks for the info (and again thanks for al the work).

already using heatercooler too, i think i have a use for anything you add :-)
