### ISSUE TITLE
[shelly] shelly1pm relay#input is ghosting (toggeling between on and off) after device reboot (from web interface) or power loss with detached switch

### ISSUE THREAD

**Issue by t8103** [openhab/openhab-addons#8142]
## Current Behavior

Shelly1pm relay#input is ghosting (toggeling between on and off) after device reboot (from web interface) or power loss with detached switch. After the physical switch is toggled the ghosting stops.

## Steps to Reproduce (for Bugs)

I was able reproduce this behavior with several shelly1pm (but not with shelly25) like follows:
button type: detached switch
power on default mode: on

1.) shelly:shelly1pm:xxxxxx:relay#input state = ON
2.) device reboot (from web interface) or power loss
=> shelly:shelly1pm:xxxxxx:relay#input is ghosting (toggeling between on and off)
3.) After the physical switch is toggled the ghosting stops.

Like follow the obove suspicios behavior does not occur:
1.)shelly:shelly1pm:xxxxxx:relay#input state = OFF
2.)device reboot (from web interface) or power loss
=> shelly:shelly1pm:xxxxxx:relay#input keeps OFF

## Your Environment

* Version used: openhab 2.5.6-2, binding-shelly - 2.5.6
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openhabian

**Comment by markus7017** [comment]
I could be an inconsistent state between 
- reported REST API status (run /status in the browser on the device IP)
- a different state reported by CoIoT
- the channel cache for the device has the state before the reboot, but this should be in sync after the next device poll (REST)

Please include the firmware version

**Comment by t8103** [comment]
Thanks for the response!

The Firmware-Version of the shelly1pm devices is: 20200601-123334/v1.7.0@d7961837.
The Firmware-Version of the shelly25 device is:      20200601-122849/v1.7.0@d7961837.

**Comment by markus7017** [comment]
Is this still a problem? Did you tried the latest DEV build?


---

[Latest DEV build](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.9-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)

**Comment by markus7017** [comment]
Was the problem solved in between so we could close this issue? 
fyi: he latest version become part of the regular 2.5.9 release

**Comment by t8103** [comment]
Thanks for the feedback! I've finally found the time and updated to version
2.5.9. The problem is actually fixed :-).
Thank you for your support and all the great work you are doing here.

Markus Michels <notifications@github.com> schrieb am Sa., 3. Okt. 2020,
08:35:
