### ISSUE TITLE
[avmfritz] Add window-open and boost mode for radiator thermostats

### ISSUE THREAD

**Issue by JHCD** [openhab/openhab-addons#8144]
I would like to set the window open mode for my Fritz! radiator thermostats, to improve control with existing window contacts.

With Fritz!OS 7.15 the following two commands where introduced in the AHA-HTTP-Interface:
* `sethkrwindowopen`: Activate window open mode with end time
* `sethkrboost`: Activate boost mode with end time

Source: [AVM Technical Note - AHA-HTTP-Interface](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf), Version 1.33 from 24.04.2020

Since AVM's window-open control is only suboptimal and the window contacts registered in the Fritz!Box cannot be used for control either, I would like to use my existing window contacts and pass the information on to the thermostats. 

Desired behavior:
* If the window contact triggers OPEN, `sethkrwindowopen` is set to now plus n hours (maximum 24h).
* If the window is closed, the value is set to 0 and the window open mode is ended.

The support of the boost mode could also be implemented at the same time in order to be able to control all relevant functions via openHab. The control command `sethkrboost` is identical implemented to that of  `sethkrwindowopen`.

**Comment by cweitkamp** [comment]
Thanks for the feature request. I will look into it. Thinking about the modelling these could be nice ThingActions for heating devices / heating groups.

**Comment by cweitkamp** [comment]
I submitted #8222 to add ThingActions to handle Boost and Window-Open modes for heating devices / groups.
