### ISSUE TITLE
[tradfri] Sending "ON" to a color bulb turns on the bulb, but brightness is still at 0

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-addons#8149]
## Expected Behavior
Sending "ON" to the color item of a color bulb turns on the bulb and the brightness is at the correct level.

## Current Behavior
Sending "ON" to the color item of a color bulb turns on the bulb, but brightness is still at 0.

## Steps to Reproduce (for Bugs)
1. Have a color bulb and a color item linked to the bulb
2. Turn it off
3. Send the command "ON" to the Color item

## Context
This is especially an issue when using the quick tiles or widget in the Android app with the "TOGGLE" command. This command is converted by the app in ON or OFF, based on the current state. If the brightness is 0, the command "ON" is sent.

## Your Environment

* Version used: openHAB 2.5
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu

**Comment by J-N-K** [comment]
That's not a bug. In Zigbee brightness and on/off are independent. This is useful to turn on devices with the same brightness they had before.

**Comment by mueller-ma** [comment]
> Has the lamp been turned of by OFF or by brightness=0?

Case A: I set the brightness to 100% with a slider and short after to 0%. Now I send `ON` and the brightness changes to 1%. Everything seems to work in this case.

Case B: I set the brightness to 100% with a slider and short after I send `OFF` and the brightness changes to 0%. Everything ok so far. Now I send `ON` and the bulb goes on, but the brightness in openHAB is still set to 0%.

To me case B seems like a bug, because the brightness of the Item doesn't reflect the brightness of the bulb.

**Comment by vivienbo** [comment]
I guess the main problem is that the Tradfri binding only has a `brightness` channel but has no `switch` channel, as opposed to the Hue binding.
I cannot reproducethis bug nowadays with latest Tradfri v1 gateway and OpenHAB 3.4.3 thought, so it's more of a feature request to add `switch` channel to tradfri module.

I created issue #14815 to reflect this.

**Comment by lsiepel** [comment]
@mueller-ma is the post from @vivienbo with the new issue to add a channel sufficient to close this issue?

**Comment by mueller-ma** [comment]
I haven't tried to reproduce this issue with the latest versions of openHAB, the tradfri binding and the gateway firmware.
I also don't use the quick tiles in the Android app anymore, so I don't care so much about this issue anymore. Let's close it for now.
