### ISSUE TITLE
login to amazon stop to works after introducing two factor authentication from amazon

### ISSUE THREAD

**Issue by alazzari74** [openhab/openhab-addons#8156]
Now when I login on amazon website or alexa, a message comes on my phone to enable the requests so I think they had enabled the two factor authentication.

The amazonEchoControl stop to works. 
In the Paper UI I can find  OFFLINE - COMMUNICATION_ERROR POST url 'https://api.amazon.com/auth/token' failed: Bad Request

If I try to connect to http://openhab:8080/amazonechocontrol/[myaccount] a login page appear but every time a try to connect i receive an error on valid email/mobile number wrong (but on amazon and on alexa app it works). 

 
![image](https://user-images.githubusercontent.com/42973429/87886705-873de980-ca1f-11ea-8090-78d0bab7b41d.png)

I'm using binding version 2.5.6

In the log I can found this kind of message:
2020-07-19 22:47:02.015 [WARN ] [trol.internal.handler.AccountHandler] - handling of websockets fails
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 8 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[bundleFile:?]....

2020-07-19 22:47:04.931 [WARN ] [mazonechocontrol.internal.Connection] - Illegal json:

<!doctype html><html class="a-no-js a-touch a-mobile" data-19ax5a9jf="mongoose">
  <head>
<script type='text/javascript'>var ue_t0=ue_t0||+new Date();</script>
<script type='text/javascript'>
window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);

    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);

var ue_id = '3YYB310ZRPMA6VYQJW0K',
    ue_url = '/ap/uedata',
    ue_navtiming = 1,
    ue_mid = 'APJ6JRA9NG5V4',
    ue_sid = '257-2377463-8005035',
    ue_sn = 'www.amazon.it',
    ue_furl = 'fls-eu.amazon.com',
    ue_surl = 'https://unagi-eu.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-eu.amazon.com/1/batch/1/OP/APJ6JRA9NG5V4:257-2377463-8005035:3YYB310ZRPMA6VYQJW0K$uedata=s:',
    ue_sbuimp = 1,
.....

So I think that the calls are changed and now it doesn't work anymore.

**Comment by J-N-K** [comment]
Fixed by #8139
