### ISSUE TITLE
[tplinksmarthome] HS110 reports wrong value in energyUsage

### ISSUE THREAD

**Issue by HarrysLapTimer** [openhab/openhab-addons#8158]
I read the energyUsage channel to derive an average daily energy usage for a TP-Link HS110.

openHAB 2.5.5-1 (Release Build)
Device Info: TP-Link model HS110, HW version 2.0, firmware 1.5.6

In Kasa app I see 

- Today total consumption 1.31 kWh
- Past 7 days total consumption 9.37 kWh
- Past 30 days total consumption 38.9 kWh

These values look sound.

In openHAB, the energyUsage channel gets 16.39 kWh(!) propagated. The device is operational since March 25th this year, so something like 4 month.

Independent from a potential reset since installation, the value reported in energyUsage cannot be lower than the highest value in the Kasa stats? In case it can be lower because the Kasa stats shown include extrapolations, is it possible to get access to the last reset's point in time?

**Comment by Hilbrand** [comment]
You can run the binding with log level trace (`log:set TRACE org.openhab.binding.tplinksmarthome`) to see what the device reports. I expect it to give the value you see. But I don't know how it derives this value. Can you post the data you get from the device?

**Comment by Hilbrand** [comment]
The energyUsage comes from: `"total_wh":16395`, which seems to match value you see. I don't know how it comes up with that value, but it's all there is. So it does seem to report the correct value, but it might not be a useful value as it's not known when that reset time is. It only reports the `on_time`. Which is, I suspect, is the total time the device was in state on. The binding doesn't read this value though.

**Comment by HarrysLapTimer** [comment]
on_time looks like the state_on time in seconds, so this is not helping anyway. It looks like the TP-Link API is too limited here...
Thanks for looking into it.
