### ISSUE TITLE
Zwave:2.0_snapshot NULL pointer exception when doing hard reset on controller

### ISSUE THREAD

**Issue by ifUpEth0** [openhab/openhab-addons#816]
I get the following error by using the paper ui to send a "Hard Reset Controller". I get this exception every time.

```
java.lang.NullPointerException
at org.openhab.binding.zwave.internal.protocol.serialmessage.ZWaveCommandProcessor.checkTransactionComplete(ZWaveCommandProcessor.java:71)
at org.openhab.binding.zwave.internal.protocol.serialmessage.ControllerSetDefaultMessageClass.handleRequest(ControllerSetDefaultMessageClass.java:37)
at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingRequestMessage(ZWaveController.java:236)
at org.openhab.binding.zwave.internal.protocol.ZWaveController.handleIncomingMessage(ZWaveController.java:203)
at org.openhab.binding.zwave.internal.protocol.ZWaveController.access$6(ZWaveController.java:197)
at org.openhab.binding.zwave.internal.protocol.ZWaveController$ZWaveInputThread.run(ZWaveController.java:1080)<
```

Attached is debug while causing the exception.

[debug.txt](https://github.com/openhab/openhab2-addons/files/230835/debug.txt)

**Comment by cdjackson** [comment]
Thanks. But as mentioned, please can you provide the debug log. The log you provided, while it might be called ‘debug’ doesn’t contain any debug information.

**Comment by ifUpEth0** [comment]
So I am new to openhab2 and karaf. Please let me know if this is right.
I start openhab2 with start_debug.sh
then issue
log:set DEBUG org.openhab.binding.zwave
But I do not see where the logs would go on the file system. Still searching. Just wanted to let you know I am not ignoring your request for the logfile. The above is what I could grab from the console. Sorry it was not helpful.

**Comment by cdjackson** [comment]
The logs should be in userdata/logs.

Thanks.

**Comment by ifUpEth0** [comment]
Thanks I had just found it and put it on the wrong ticket. So here is the log.
[openhab.txt](https://github.com/openhab/openhab2-addons/files/230857/openhab.txt)

**Comment by ifUpEth0** [comment]
You put a comment on my other ticket that I think was for this one about the log file above not having the debug. I stopped openhab2. started in debug as described and issued log:set DEBUG org.openhab.binding.zwave then caused the issue with the hard reset. Attached to the comment you will find the debug log. I looked through it and see a lot of [DEBUG] so I think this one should be good.
[openhab.txt](https://github.com/openhab/openhab2-addons/files/230870/openhab.txt)

**Comment by cdjackson** [comment]
Thanks - that looks good. I’ll take a look at this tomorrow (it’s getting late here).

**Comment by ifUpEth0** [comment]
I would like to get up to speed enough to contribute. Java is my weakest language so it may take a bit, seems like the syntax is a lot like c++ so that helps.

**Comment by cdjackson** [comment]
Hopefully I've fixed this now.

Your log looks like your system is a bit screwy - htere are multiple messages received - is it a Pi?

**Comment by ifUpEth0** [comment]
It is not a Pi. Which messages are you talking about? I confirmed this fix in the snapshot I pulled today.

**Comment by cdjackson** [comment]
There appeared to be duplication on a number of messages from the controller during initialisation which I've only seen on the ARM/Pi boards...

Anyway, since this is fixed, I'll close - thanks.
