### ISSUE TITLE
[avmfritz] missing current amperage (Stromstärke aktuell)

### ISSUE THREAD

**Issue by Diapolo** [openhab/openhab-addons#8174]
My FRITZ!Box 7490 (FRITZ!OS: 07.19-80499 BETA) is showing "Stromstärke aktuell" under "Energieanzeige" for the FRITZ!DECT 200 and I'm wondering, if that could be exposed as channel to openHAB?

![Stromstärke](https://user-images.githubusercontent.com/1419649/88227806-7636e780-cc6e-11ea-9c72-44cbfdc28903.png)

**Comment by cweitkamp** [comment]
No, it is not directly available via the AHA interface. But it should be no problem to calculate / estimate it (e.g. in a Rule) because we have the values power and voltage:

**P = U * I**   <=>    **I = P / U**

**Comment by Diapolo** [comment]
@cweitkamp That's the way to do it :), closing this.
