### ISSUE TITLE
[avmfritz] documentation, troubleshooting, debug logging

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#8175]
AVM Fritz! binding documentation at
https://www.openhab.org/addons/bindings/avmfritz/
lacks a 'Troubleshooting' or 'What to do if things go wrong' section.

At its simplest this needs only the instruction for how to set debug and/or trace logging for this binding, and perhaps a pointer to discussion forum.

With zero knowledge of this binding, afraid I will not do it myself :(

**Comment by kaikreuzer** [comment]
This does not make sense to me. How to enable debug logs for a binding is not specific for a binding and thus should not be mentioned 200 times, but only once in the documentation. Also, the documentation should not point to the discussion forum, but be standalone. How to get support, report bugs etc. is again something that is the very same for every binding.

If you feel that this isn't well documented in the openHAB documentation, you might want to address it in https://github.com/openhab/openhab-docs/.

**Comment by Rossko57** [comment]
> How to enable debug logs for a binding is not specific for a binding

But it is from a user viewpoint.  In this case you need to know the package name
org.openhab.bindings.avmfritz
But if they're supposed to guess, that's fine.

**Comment by kaikreuzer** [comment]
>you need to know the package name org.openhab.bindings.avmfritz

The package name is `org.openhab.binding.avmfritz`. And this is again a general pattern and the very same for all bindings: `org.openhab.binding.<bindingid>`.

**Comment by Rossko57** [comment]
In this case, yes a reasonable guess can be made. (but why guess, it's two lines in the binding docs)
For some bindings, there are multiple packages, example
https://www.openhab.org/addons/bindings/zigbee/#when-things-don-t-appear-to-be-working
which suggest three packages.
What is likely to be _actually_ useful in troubleshooting varies by technology and so by binding.

Just trying to make it easier for frustrated users who get into difficulties, have lost interest now. Don't worry about it.
