### ISSUE TITLE
[lifx] Switch support for LIFX binding

### ISSUE THREAD

**Issue by Aussie-Luftikus** [openhab/openhab-addons#8190]
I am using OpenHAB for a couple of years, mostly with LIFX lights, and I am very happy with it. I got now the LIFX switch and realised that there is no support for a LIFX switch in the binding.

I would like to request the "feature" to support the LIFX switch so I can use it in my OpenHAB setup.

**Comment by wborn** [comment]
See also this [community topic](https://community.openhab.org/t/lifx-switch-support/102760/4?u=wborn). There currently don't seem to be any official APIs that can be used for integrating this device in openHAB.

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
