### ISSUE TITLE
[dlinksmarthome] 2.5.7 does not work with Java 11

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-addons#8194]
Testing 2.5.7 with Zulu java 11 results in the following error during startup:

`ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.dlinksmarthome.internal.handler.DLinkMotionSensorHandler@7fcdc9': javax/xml/soap/SOAPException                                                  java.lang.NoClassDefFoundError: javax/xml/soap/SOAPException                         at org.openhab.binding.dlinksmarthome.internal.handler.DLinkMotionSensorHandler.initialize(DLinkMotionSensorHandler.java:53) ~[?:?]                       at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]                                                                            at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]                                                          at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

**Comment by MikeJMajor** [comment]
@J-N-K do you have any ideas how to fix this?

I'm guessing this is due to "<bnd.importpackage>!javax.xml.soap" in the pom.xml which I had to add to get it to work with java 8.

**Comment by J-N-K** [comment]
Why did you need to add that?

**Comment by MikeJMajor** [comment]
From what I remember there seemed to be some issue with duplicate class definitions at runtime

**Comment by J-N-K** [comment]
Are you sure the jaxws feature is installed?

**Comment by MikeJMajor** [comment]
I shutdown OH and swapped from java 8 to java 11 and restarted OH, perhaps I needed to clean the tmp and cache directories before restarting.

Looking at my setup which is back to running java 8 it shows:

`openhab> feature:list |grep jaxws                                            openhab.tp-jaxws                                  │ 2.5.0            │          │ Started     │ distro-2.5.7             │ JAX-WS (SOAP) bundles`

After the build changes in order to get it to work I ended up changing feature.xml to use openhab.tp-jaxws, but it needed com.sun.xml.messaging.saaj.soap explicitly referencing in pom.xml to avoid runtime errors. However, that seemed to cause conflicts with the version of javax.xml.soap used in openhab.tp-jaxws compared with the one in java 8 which is why I excluded it.

I'll try again tomorrow after clearing the cache.

**Comment by MikeJMajor** [comment]
@J-N-K The original problem I was trying to solve was a runtime issue finding a SAAJ implementation.
I think my fix was wrong as its probably forcing it to use the java 8 implementation.

I'm guessing in the pom.xml referencing "com.sun.xml.messaging.saaj.soap" is the bit that's wrong and instead it should be something referencing Jakarta?

**Comment by MikeJMajor** [comment]
@J-N-K you were right, it looks like when I was trying to fix the 2.5.0 version I probably didn't have the jaxws feature installed.
