### ISSUE TITLE
[astro] Documentation error

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#8199]
@clinique I think there is a mistake in documentation for the new action features introduced by you for issue #8016 

Method signature is:

`getEventTime(sunPhaseName, moment, date)`

Parameter explaination says:

```
sunPhaseName (String), values: SUN_RISE, ASTRO_DAWN, NAUTIC_DAWN, CIVIL_DAWN, CIVIL_DUSK, NAUTIC_DUSK, ASTRO_DUSK, SUN_SET, DAYLIGHT, NIGHT. Mandatory.

date (ZonedDateTime), only the date part of this parameter will be considered - defaulted to now() if null.

moment (String), values: START, END - defaulted to START if null.
```
Example code is like this which match to parameter description but not to method signature:

`val sunEventTime = sunActions.getEventTime(sunEvent,today,"START")`

Which parameter order is correct?

**Comment by clinique** [comment]
Yes, you're right, I forgot to update doc while developping, the right order is phaseName, date, moment. Will update doc accordingly.
