### ISSUE TITLE
[netatmo] refreshInterval config setting never used for the thermostat device

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8200]
As the `NAPlug` thing type defines the property `refreshPeriod` (with value 3600000 ms), the configuration setting `refreshInterval` will never be considered by the binding (method `defineRefreshInterval`) and a refresh will be triggered evey hour.
Either the thing property or the configuration setting has to be removed. 
@clinique : WDYT ?

**Comment by clinique** [comment]
Yes, you're right, for NAPlug this could be removed from configuration as it is overriden by the value presented in the property.
