### ISSUE TITLE
[netatmo] Support for Welcome camera event categories (the Welcome indoor camera can now also detect animals and humans)

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8202]
A Welcome indoor camera can also detect human and animals. A detected human or animal should also trigger an event to the "cameraEvent" trigger channel (like the Presence outdoor camera).

**Comment by Novanic** [comment]
I have already prepared a pull-request, see #8203

**Comment by Novanic** [comment]
https://forum.netatmo.com/viewtopic.php?f=5&t=18506

**Comment by lolodomo** [comment]
Closed n'y #8203
