### ISSUE TITLE
[amazonechocontrol] existing account things still failing after upgrade to 2.5.7 with invalid user/pwd in login mask

### ISSUE THREAD

**Issue by mgeramb** [openhab/openhab-addons#8210]
## Expected Behavior
- login through the binding proxy is working

## Current Behavior
- for existing account thing, the login if failing with invalid user/pwd
Note: if you create a new one with a never used name, the login is possible

## Your Environment
OH 2.5.7

**Comment by J-N-K** [comment]
fixed
