### ISSUE TITLE
Normalize thread naming of threads in add-ons

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-addons#8216]
A number of add-ons start there own threads. To track threads better I propose these threads should all name their thread using a specific name convention. My proposal is to use:
* If there is 1 thread::`OH-binding-<thingUID>`,
* If there are multiple threads: `OH-binding-<thingUID>-<custom>`. Where `custom` is a developer defined word that suggest which specific thread it is.

Some bindings use `Executors`. My suggested would be to either standardize to all use the `org.eclipse.smarthome.core.common. ThreadPoolManager` or another option to allow a generic `Executors`, but initialize with the openHAB `NamedThreadFactory`. The named thread factory/pool manager should than be initialized with `binding-<thingUID>`. Note that using the ThreadPoolManager` will add an incremental number to the thread name for each thread started.

**Comment by fwolter** [comment]
Many bindings append hostname and port number to the thread name. I think this is more meaningful than a number. I suggest to leave the part after the binding ID up to the binding developer.

**Comment by Hilbrand** [comment]
Yes that might be a better idea, to leave it to the developer. Maybe the ThingID and some additional info so one can see which thing has started the thread. Or just instead of bindingId use the thing UID. I'll update the text.

**Comment by kaikreuzer** [comment]
I'd like to mention that the general advice is to NOT use any threads at all within bindings. Most things should be possible to solve with the existing `scheduler` that is provided within the handlers. Requiring a dedicated thread should thus be an exception for the situations where it is really needed, such as continuously listening on TCP ports for events.

Please keep that in mind for all binding reviews!

**Comment by Hilbrand** [comment]
@kaikreuzer my idea is to go through all bindings and see how threads are used and see if we can make them consistent. For example some use thread.start, while others use a single thread executor. Some use our thread executor to create a thread pool, others use the generic executor. I don't know what is preferred. But would like if we can make a general guideline. (Besides don't use a thead when not needed) Do you have an opinion about this?

**Comment by kaikreuzer** [comment]
@Hilbrand Yes, I think a general guidelines makes sense.
Just like we offer thread pools through `ThreadPoolManager`, we should have a way to deal with single/permanent threads.
I don't have a strong opinion, how this guideline should look like, so feel free to suggest one. Aligning thread naming across all binings as a first step definitely makes sense as well 👍 .

**Comment by lsiepel** [comment]
How can we determine if all bindings have the thread name set correct?
