### ISSUE TITLE
[somfytahoma] Somfy RTS garage door not working

### ISSUE THREAD

**Issue by TsvetomirIliev** [openhab/openhab-addons#8219]
I have tried to command my Somfy RTS garage door using Tahoma Box with no success. Followed all instructions and tried both PaperUI and manual adding. I'm getting the following error:

[nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"errorCode":"UNSUPPORTED_OPERATION","error":"No such command : my on device rts://xxxx-xxxx-xxxx/16727717 (rts:GarageDoor4TRTSComponent)"}

openHAB version 2.5.6-2 

The garade door is working great with Tahoma Android app.

**Comment by octa22** [comment]
Hi @TsvetomirIliev ,
I will do my best to find and fix the error. But I need some help, can you please provide me with the trace log during the discovery phase of this binding?
I guess the garage door gets recognized, but expects other commands... thanks.

**Comment by octa22** [comment]
Apparently you are trying to send "my" command to the gate. Only open/close/pedestrian/stop commands are currently supported

**Comment by lolodomo** [comment]
@TsvetomirIliev : can you please give a feedback or close the issue?

**Comment by lolodomo** [comment]
Closed due to missing feedback
