### ISSUE TITLE
[goecharger] Configurable HTTP timeout

### ISSUE THREAD

**Issue by 5n8ke** [openhab/openhab-addons#8227]
The goecharger binding has a hardcoded HTTP request timeout of 5 seconds. In my setup, due to a low-quality WiFi connection, the response time, as measured by arping, is sometimes longer in the range of 8-10 seconds. The requests are still answered correctly.

A configurable HTTP timeout would allow me to still use the binding. even when the network connection to the charger is bad.

**Comment by SamuelBrucksch** [comment]
It is configurable. 5s ist just the default. Please check the documentation:

https://www.openhab.org/addons/bindings/goecharger/#thing-configuration

**Comment by SamuelBrucksch** [comment]
I guess this could automatically be calculated by refresh interval. Timeout should be refresh interval -1s or so.

**Comment by lsiepel** [comment]
Many enhancements to the the binding have been made since creating this issue. And i hope you wifi has improved too ;-) Is this still a alid enhancement request for 3.4.0+ ?
