### ISSUE TITLE
[Onkyo] Please add the TX-RZ900 to the list of supported devices

### ISSUE THREAD

**Issue by gabsoftware** [openhab/openhab-addons#8245]
I just tested that the Onkyo Binding can link to the TX-RZ900, and so far everything works even if the receiver is listed as unsupported.

Could you please add the receiver to the list of supported devices?

Thanks!

**Comment by Cossey** [comment]
@gabsoftware enjoy. Open another issue and @ me if it doesnt work in the next release.
