### ISSUE TITLE
HTTP binding

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-addons#8247]
<a alt="bounty" href="https://www.bountysource.com/issues/92221922-http-binding"><img src="https://api.bountysource.com/badge/issue?issue_id=92221922"></a>

This is a placeholder to track progress on a HTTP binding mainly created for support of bountysource. 

I will add a small bounty to add because a bounty from another issue was not claimed.

See also: #7851 (and it's predecessor #4342) and the generic migration issue #6179

**Comment by martinvw** [comment]
fyi @J-N-K there is now a bounty on completing the http binding.

**Comment by cweitkamp** [comment]
@martinvw Thanks for posting a bounty on this issue :+1:.

**Comment by J-N-K** [comment]
I think this can be closed. Implemented in #8521
