### ISSUE TITLE
[openhabcloud] sendNotification not working. cannot be resolved to an item or type

### ISSUE THREAD

**Issue by TommyFive** [openhab/openhab-addons#8248]
I recently discovered an unexpected behavior regarding the notification when there is an active network cable connection and an WIFI interface even it there is no WIFI connection setup.

## Expected Behavior
sendNotification should work properly on setups where there is an network cable connection and an unconfigured /unconnected wifi interface.

## Current Behavior
Openhab is up and running
Network connection via cable 
myopenhab.org shows status online
WIFI Interface is enabled but without an connection (unconfigured)
Primary Address is not set (under PaperUI->Configuration->Settings->Network Settings)
A rule tries to execute sendNotification. The log shows following error:

``` 
2020-08-03 09:51:28.663 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 'test': The name 'sendNotification' cannot be resolved to an item or type; line 23, column 5, length 62
``` 

## Possible Solution
Deactivate WIFI Interface via openhabian-config
reboot machine (implies restarting openhab)
Now everything works as expected if a rule tries to send an notification

## Steps to Reproduce (for Bugs)

1. At least in my case the sendNotification ecevution always throws an error in the log

## Your Environment
* Release = Raspbian GNU/Linux 9 (stretch)
* Kernel = Linux 4.19.66-v7+
* Platform = Raspberry Pi 3 Model B Plus Rev 1.3

* Version used: openHAB 2.5.7 Release Build

**Comment by hmerk** [comment]
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.
