### ISSUE TITLE
[Shelly]: Use mDNS name for defining things instead of/additional to IP address

### ISSUE THREAD

**Issue by Boby71** [openhab/openhab-addons#8259]
The title says it all: The IP address can change, the shellys report a unique mDNS name into the WiFi.
So why not using this unique name to identify the Shellies in the WiFi? This could either replace the ipaddress as ID or could be implemented as additional way to identify the devices in the wireless lan.

![image](https://user-images.githubusercontent.com/22266373/89341733-08dd7a80-d6a2-11ea-98cc-6ec028e61620.png)

**Comment by markus7017** [comment]
the could can change this name, nevertheless: where is the problem? this is a one-time setup and the device should have a static/same-DHCP IP anyways. This is not just a matter of binding initialization, those assignments could change anytime

**Comment by Boby71** [comment]
Well, I don‘t see why the mDNs should change. And even if: It might change way less often than the IP address does. Probably Shelly will support custom names in the future - would you still like to go for the static ip’s then?

Static IP‘s are a concept from the 80’s and using mnemonic names is far more easy For users than to define static ip addresses. When you get a new router, you need to set up everything again from the scratch. And defining the IP address on the devices itself is not manageable in real life. 

Decide yourself: What do you prefer? Typing 172.217.7.142 - or typing www.google.com?

**Comment by markus7017** [comment]
well, I want to know what‘s going on in my network
and no, I type nothing, because the binding supports auto discovery
How to resolve the IP? This would required to do a mdns discovery and wait for the result each time the thing initializes

**Comment by markus7017** [comment]
another reason: After a restart it might happen that a device just sends a Coap update while the thing is in state unknown. In this case the binding performs an auto-initialization. There is no way to perform an mdns discovery at that time, because the device immediatly goes back to sleep.

There might be other ways ro identify the device (e.g. based on the mac address), but for time being I‘ll not invest time into that.

**Comment by markus7017** [comment]
issue closed

**Comment by markus7017** [comment]
closing this issue
