### ISSUE TITLE
[shelly] New setting led_status_disable also for relay, dimmer etc

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#8262]
Starting with firmware 1.8 there is a new setting "led_status_disable" for alls relays, dimmers, DW2 and Button1. With this you can switch off the internal device LED, similar to the Plug-S.
Maybe interesting to implement it?

**Comment by markus7017** [comment]
work-in-progress, will be include in upcoming release (2.5.8/2.5.9)

**Comment by markus7017** [comment]
Included in PR #8198
