### ISSUE TITLE
[shelly] New setting for device/channel name

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#8263]
Starting with firmware 1.8 it is possible to set the Device and the Channel a name via the Web GUI.
The parameter "name" in the root of REST JSON and then below relays/lights.
If set, you could use the names for Thing or Relay name at discovery.

**Comment by markus7017** [comment]
I don't know how this could be mapped to OH. The only meaningful way would be creating dynamic channels matching this name, but this would also impact the code, e.g. don't do the update on channel relay#output, but on relay#myname etc.

**Comment by markus7017** [comment]
included in PR #8936
