### ISSUE TITLE
[zway] Allow smaller polling intervalls

### ISSUE THREAD

**Issue by DataWorm** [openhab/openhab-addons#8264]
Apparently the pollingIntervall in zway binding is the one setting that affects how fast I can receive state updates but it doesn't allow values below one minute. Obviously this reaction time is quite useless for several use cases. For example I don't like to wait a minute for the (not via zway controlled) light to be turned on when movement is detected inside the room. Therefore I would like to ask why I can't use smaller values (like 1-3 seconds) and request to change that.

**Comment by Ryz3D** [comment]
@kaikreuzer Thanks for merging #11122, thus this issue can be closed.
