### ISSUE TITLE
[netatmo] Adapt code generation to newer swagger libraries

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#8274]
For openHAB 3, the netatmo binding fails to build, see https://github.com/openhab/openhab-core/pull/1576#issuecomment-671114655.
Once this binding is moved to the master branch, the code generation needs to be adapted accordingly. Until then, this binding is excluded from https://ci.openhab.org/job/openHAB-Addons-port/.

**Comment by kaikreuzer** [comment]
@clinique, @cweitkamp & @lolodomo, since you are listed as CODEOWNERS here:

This is the last "excluded" binding in the openHAB 3 distro, which should be added before we do the milestone 1.
Is any of you volunteering to look into adapting the code?

**Comment by lolodomo** [comment]
I have not the skill to do the chsnge myself.

**Comment by clinique** [comment]
I think the issue comes from the direct integration of cbornet librairies (wonderfull by the way). I think we could ask help @novanic who integrated this evolution in the binding.

**Comment by Novanic** [comment]
Yes, I could take a look at it.

The used libraries (retrofit, okhttp, okio) are very outdated and can not simple get updated, because newer versions contain major breaking changes. I could imagine that it is easier to change to another library.

I have a few questions:
* Where should the changes get committed? Still within the normal openhab-addons repository or is there a separated OpenHAB 3 repository?
* Are there preferred code generation libraries for OpenHAB 3?

**Comment by kaikreuzer** [comment]
> Where should the changes get committed? Still within the normal openhab-addons repository or is there a separated OpenHAB 3 repository?

Right here on the `main` branch, see https://github.com/openhab/openhab-addons/issues/8512.

> Are there preferred swagger code generation libraries for OpenHAB 3?

Swagger is used in version 2.1.0 - see https://github.com/openhab/openhab-core/pull/1576.

> Newer libraries of retrofit and okhttp are missing within org.openhab.osgiify. How can we get new versions to that groupId?

That's probably something @J-N-K can best answer.

**Comment by mdillmann** [comment]
> I could imagine that it is easier to change to another library...

@Novanic : you may want to have a look a the attempt of refactoring the binding with an alternative netamo-lib [https://github.com/navybk/netatmo-java-api](url). It looks at least complete in what it implements from the Netatmo side. (Version in maven-central is more recent than release on github).

The swagger-based lib lacks support for newer devices like valves. @navybk also made a shot a while ago at adapting the binding, see here: [https://github.com/openhab/openhab-addons/issues/3806](url)

**Comment by Novanic** [comment]
Thank you for the hints. I have now a working version, I think I can create a pull-request tomorrow. It uses the latest swagger-codegen version and the outdated retrofit library is removed.
