### ISSUE TITLE
[daikin] implement support for the KKRP01A wired module (as was available in v1 binding)

### ISSUE THREAD

**Issue by sumnerboy12** [openhab/openhab-addons#8278]
The original v1 of the daikin binding supported the KKRP01A wired module, via this [library](https://bitbucket.org/JonathanGiles/jdaikin). This module is not supported in the new v2 binding. 

The KKRP01A module reports the device state via `http://host/param.csv` and looks like;

```
OK. OFF. NONE. NONE. NONE. OFF. 24,5. OFF/OFF. ENA. ---. NOR.NOR.NOR.NOR. Living. AUTO.25.23.16.F1. admin. 20,0. 50. -. -. -. 0.
```

Commands are set via HTTP POST, see the `jdaikin` module for how this has been implemented.

**Comment by ssvenn** [comment]
https://www.domoticz.com/forum/viewtopic.php?t=16649 has another example implementation showing how to communicate with the KKRP01A module that can be referenced.

**Comment by sumnerboy12** [comment]
Closing as I no longer have a Daikin system in my home,
