### ISSUE TITLE
[bluetooth.bluegiga] Explain adapter configuration parameters more in detail / tuning guide

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#8279]
In the bluegiga binding, we got quite a lot configuration parameters right now. I think it would be good to have kind of a "tuning guide" which explains the user in which cases it makes sense to adjust these values, which implications such changes (could) have and also how they interact with each other (if they do).

@cpmeister @paulianttila: Any idea about this? Maybe you know about an existing resource which contains more information about the parameters?

**Comment by pfink** [comment]
@openhab/add-ons-maintainers: Sorry for the wrong label, could you please change it to _documentation_? Unfortunately, there is no issue type for documentation issues. I created #8280 to add one.

**Comment by pfink** [comment]
@cpmeister @paulianttila: Short reminder in case you didn't see. I mean e.g. [these parameters](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/resources/OH-INF/thing/bluegiga.xml#L24)

**Comment by cpmeister** [comment]
I'll address this after I sort out my generic and govee bluetooth bindings.

**Comment by pfink** [comment]
>I'll address this after I sort out my generic and govee bluetooth bindings.

Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pfink** [comment]
Here a nice thread regarding scanInterval and scanWindow: https://electronics.stackexchange.com/questions/82098/ble-scan-interval-and-window

**Comment by lsiepel** [comment]
This is an old thread, so just to be sure is there still a wish to enhance the documentation? If so, could we reboot this thread ?

**Comment by pfink** [comment]
From my side it still would be very appreciated, but unfortunately I don't have the expertise to do it.

**Comment by lsiepel** [comment]
When i look at the provided link , i think this kind of documentation goes beyond the scope of the openHAB binding documentation. If there is a need for a more general guide on tuning this bluetooth settings, i think the community forum is the best place to discuss.
