### ISSUE TITLE
[smartmeter] Set boolean-items (e.g. switch or contact) directly based on OBIS status

### ISSUE THREAD

**Issue by grdigit** [openhab/openhab-addons#8288]
It would be great if the OBIS status (the status bits) could be converted directly into items or channels.
My counter (DZG DVS74) has coded the energy direction and other things in bits in the status of OBIS 1-0:1.8.0:
https://www.dzg.de/fileadmin/dzg/content/downloads/produkte-zaehler/dvs74/dzg_dvs74_Handbuch.pdf (page 37)

Maybe the functionality around the negation could be expanded to address the OBIS status directly via channel parameters.

## Your Environment

* Version used: Openhab 2.5.7 & Smartmeter-Bindung 2.5.7

**Comment by grdigit** [comment]
Is there still a maintainer for this binding?

**Comment by J-N-K** [comment]
Can this be changed (can the channels be switched on the smartmeter from r/o to r/w)?
