### ISSUE TITLE
[bticinosmarther] Thing UID clash for modules on same Plant

### ISSUE THREAD

**Issue by MrRonfo** [openhab/openhab-addons#8307]
## Expected Behavior
Having more than one chronothermostat module on the same Plant, it is expected the binding to generate a unique UID for each of the Chronothermostat things. So that, also with auto-discovery, each module in the same house is found and added to the Inbox.

## Current Behavior
There are reported cases of clashing Chronothermostat thing UID for chronothermostat modules registered under the same Plant. 
Currently UID is generated taking the last 8 chars from the module ID; the logic need to be reviewed, as the BTicino module ID generation rule is not public domain and there are cases where the last 8 chars are identical between two sibling modules.

## Possible Solution
CRC32 of the module ID could be a straightforward solution.
The thing UID is calculated only once, so there should not be a great computational overhead; the algorhithm should grant quite similar module ID (like the ones under the same Plant happen to be) to have a different thing UID.

## Steps to Reproduce (for Bugs)
Depends on BTicino, it can be reproduced only in case they provide you with two module ID with the last 8 char identical.

## Your Environment
The issue is OH version, environment and OS indipendant.

**Comment by lsiepel** [comment]
@MrRonfo as i can not find a PR related to this issue, i assume this has not been fixed yet. I just looked at the code responsible for creating the UID:

```
    private String getThingIdFromModule(Module module) {
        final String moduleId = module.getId();
        return moduleId.substring(0, moduleId.indexOf(ID_SEPARATOR));
    }
```
I don't know why this moduleId is stripped to only the first set of chars until the -, maybe for readability. Can you share a full moduleId ? I think ti should be listed under the Thing properties. 
And i fi create a fix, are you able to test and verify?
