### ISSUE TITLE
[somfytahoma] Please Add support for Exterior Heating System controlled via Somfy (in this Case Solamagic)

### ISSUE THREAD

**Issue by SeKaTho** [openhab/openhab-addons#8313]
Hey Guys, 
this is my first Github Issue, so i hope i got it right. Please let me know if some information are missing or anything else. 
At first thanks for the binding, works great with my installation so far. 
When Adding my Somfy Devices i noticed that my exterior Infrared Heating System was not detected by the Binding. 
The logfile encouraged me to open an issue here, for adding support in the binding. 
The following Data is provided in the Logfile: 
`Device definition:
Commands: { delayedStopIdentify (params: 1); getLevel (params: 0); getName (params: 0); identify (params: 0); off (params: 0); on (params: 0); setLevel (params: 1); setName (params: 1); startIdentify (params: 0); stopIdentify (params: 0); wink (params: 1); pairOneWayController (params: 2); unpairAllOneWayControllers (params: 0); unpairOneWayController (params: 2); }
States: {core:DiscreteRSSILevelState (values: good, low, normal, verylow); core:LevelState (values: ); core:NameState (values: ); core:PriorityLockTimerState (values: ); core:RSSILevelState (values: ); core:StatusState (values: available, unavailable); io:PriorityLockLevelState (values: comfortLevel1, comfortLevel2, comfortLevel3, comfortLevel4, environmentProtection, humanProtection, userLevel1, userLevel2); io:PriorityLockOriginatorState (values: LSC, SAAC, SFC, UPS, externalGateway, localUser, myself, rain, security, temperature, timer, user, wind); }
2020-08-18 14:31:24.312 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 
{name='core:NameState', type=3, value=HEAT. VAR IO}
{name='core:PriorityLockTimerState', type=1, value=0.0}
{name='core:StatusState', type=3, value=available}
{name='core:DiscreteRSSILevelState', type=3, value=normal}
{name='core:RSSILevelState', type=2, value=44.0}
{name='core:LevelState', type=1, value=100.0}
`

Used Device: 
Device is a Solamagic S1 Infrared Heater with support Somfy connectivity by an additional Control Unit (Dimmbox WSI / Anschlussmodul S1/S3 WSI) 

My Environment:
Openhab 2.5.7 Release Build in Docker Container on Synology DS916+ 

Please let me know if some more Information or testing is needed. 

BR
Sebastian

**Comment by octa22** [comment]
Hi,
thanks for the log, unfortunately I am missing an extra line above the device definition, it should start with "Detected a new unsupported device".
Can you provide it, please?
Thanks.
Ondrej

**Comment by SeKaTho** [comment]
Hi Ondrej, 
sorry i forgot the line in my copy. Information should be complete now. 
Just give me some hint if i can provide some more information. 
`2020-08-20 22:31:31.493 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Detected a new unsupported device: ExteriorHeatingSystem with widgetName: DimmerExteriorHeating
2020-08-20 22:31:31.493 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below
2020-08-20 22:31:31.494 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition:
Commands: { delayedStopIdentify (params: 1); getLevel (params: 0); getName (params: 0); identify (params: 0); off (params: 0); on (params: 0); setLevel (params: 1); setName (params: 1); startIdentify (params: 0); stopIdentify (params: 0); wink (params: 1); pairOneWayController (params: 2); unpairAllOneWayControllers (params: 0); unpairOneWayController (params: 2); }
States: {core:DiscreteRSSILevelState (values: good, low, normal, verylow); core:LevelState (values: ); core:NameState (values: ); core:PriorityLockTimerState (values: ); core:RSSILevelState (values: ); core:StatusState (values: available, unavailable); io:PriorityLockLevelState (values: comfortLevel1, comfortLevel2, comfortLevel3, comfortLevel4, environmentProtection, humanProtection, userLevel1, userLevel2); io:PriorityLockOriginatorState (values: LSC, SAAC, SFC, UPS, externalGateway, localUser, myself, rain, security, temperature, timer, user, wind); }
2020-08-20 22:31:31.494 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 
{name='core:NameState', type=3, value=HEAT. VAR IO}
{name='core:PriorityLockTimerState', type=1, value=0.0}
{name='core:StatusState', type=3, value=available}
{name='core:DiscreteRSSILevelState', type=3, value=normal}
{name='core:RSSILevelState', type=2, value=50.0}
{name='core:LevelState', type=1, value=100.0}
`
Thanks.
Sebastian

**Comment by octa22** [comment]
Thanks,
please can you try this SNAPSHOT? It should autodetect the exteriror heating system thing with one channel - heating_level
https://www.dropbox.com/s/w4fxohowt56lpfy/org.openhab.binding.somfytahoma-2.5.8-SNAPSHOT.jar?dl=1
Hope it works.
Ondrej
