### ISSUE TITLE
[gree] the Gree binding should allow for setting the swingUpDown setting to values 7-11

### ISSUE THREAD

**Issue by taboneclayton** [openhab/openhab-addons#8330]
As per documentation on the [gree-remote project](https://github.com/tomikaa87/gree-remote#reading-status-of-a-device), Gree AC devices should support modes 7, 8, 9, 10, 11 for the `SwUpDn` field. These values map to partial swings as defined below:
> 7: swing in the downmost region (5/5)
> 8: swing in the middle-low region (4/5)
> 9: swing in the middle region (3/5)
> 10: swing in the middle-up region (2/5)
> 11: swing in the upmost region (1/5)

In the Gree openHAB binding this is mapped to the `swingUpDown` channel. The method [GreeAirDevice#setDeviceSwingUpDown](https://github.com/openhab/openhab-addons/blob/25671d4cf270e7f168bf055fda584c5ac8112d61/bundles/org.openhab.binding.gree/src/main/java/org/openhab/binding/gree/internal/handler/GreeAirDevice.java#L191-L197) includes a comment specifying that values between 0 and 11 should be allowed. However the validation code only allows values between 0 and 6.

This is quite an easy fix and I could apply the fix myself by wanted to open an issue first to make sure that this would be a wanted fix/improvement.

**Comment by taboneclayton** [comment]
@fwolter, @markus7017 would you like me to implement a fix for this issue?

**Comment by markus7017** [comment]
sure, one thing is the validation, but the values are also mapped to textual channel values, please check both aspects

I already noticed this, bit nobody reported this issue and if I remember correctly it was the same way in the code I took over
