### ISSUE TITLE
[Homematic] - Channel not found for datapoint '00109A498XXXXX:1#STATE_CONTACT' - (HmIP-SWDO-I)

### ISSUE THREAD

**Issue by fibu-freak** [openhab/openhab-addons#8337]
`*******  Hardware-Info        = Model		: Raspberry Pi 4 Model B Rev 1.1
*******  Linux-Version-Info   = Raspbian GNU/Linux 10 (buster) (Pretty-Name)

*******  OH-Version-Info      = openHAB Distribution Version Information 
*******  OH-Version-Info      = ---------------------------------------- 
*******  OH-Version-Info      = build-no        : Release Build 
*******  OH-Version-Info      = online-repo     : https://openhab.jfrog.io/openhab/libs-release 
*******  OH-Version-Info      =  
*******  OH-Version-Info      = Repository        Version 
*******  OH-Version-Info      = ---------------------------------------- 
*******  OH-Version-Info      = openhab-distro  : 2.5.8 
*******  OH-Version-Info      = openhab-core    : 2.5.0 
*******  OH-Version-Info      = openhab1-addons : 1.14.0 
*******  OH-Version-Info      = openhab2-addons : 2.5.8 
*******  OH-Version-Info      = karaf           : 4.2.7 
*******  OH-Version-Info      = Homematic-Binding (jar)      :   2.5.8.202008111717

*******  Homematic-Info      = Homematic gateway            : ccu3                      actual Firmware: 3.51.6
*******  Homematic-Info      = Door/Window-Sensor          : HmIP-SWDO-I      actual Firmware: 1.16.10
`
I found the warning-message in my logger

`2020-08-24 23:13:10.293 [WARN ] [ternal.handler.HomematicThingHandler] - Channel not found for datapoint '00109A498xxxx:1#STATE_CONTACT'` 

I have created the Thing for my "HmIP-SWDO-I" via PaperUI but there is no such Channel in the Thing nor visible in VSC
![grafik](https://user-images.githubusercontent.com/41429646/91100268-29776f80-e665-11ea-92cc-804865f602e6.png)

Anyone with the same problem ? Anyone to help ?

**Comment by fibu-freak** [comment]
@MHerbst  f.y.i.
I found a solution for me for this problem. I think there was a change in the AutoDiscovery of Homematic in OH with PaperUI.
What I have done:
Removing the Thing in PaperUI and readded, and voilà the missing channel for "STATE_CONTACT" was visible. 
But what I also saw, the Channel-Definition was a bit different from the older one -> no more Bridge-Definition in the Channel <-
![HM-Sensor](https://user-images.githubusercontent.com/41429646/91231933-75dab200-e72e-11ea-930a-05986ae954a6.jpg)
Maybe an update of the Docs is needed ??!!

**Comment by MHerbst** [comment]
@fibu-freak The need for a new discovery in certain situation is a general problem of openHAB. Each time the channel definition changes (e.g. new or removed channels or changes of the type) a thing has to be recreated.

The change in the name seems to be a bit longer ago. Can't remember when something changed here.
