### ISSUE TITLE
[innogysmarthome] no Battery state for Thermostat 2nd Generation

### ISSUE THREAD

**Issue by acidburn78** [openhab/openhab-addons#8344]
Hi there,

my Environment is Openhab 2.5.7  with Innogy Binding and the Innogy Bridge 2nd Generation. 

i dont get the state of low battery for the 2nd Generation Thermostat in Openhab normaly the state is Off or ON but i don't have any state. The Window Sensor and Smokewarner have a state.

i testet Version of the Binding 2.5.7, 2.5.8 SNAPSHOT and 2.5.9 SNAPSHOT

**Comment by Novanic** [comment]
I probably found the bug, the RST2 device isn't recognized as battery-powered. I will try to fix that and provide a pull-request.

**Comment by Hilbrand** [comment]
Closed by #8375
