### ISSUE TITLE
[homematic] Clean up naming inconsistencies in thing types

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#8346]
I was searching for issues with some homematic devices in my installation and discovered, that the thing types got different casing for the hmip abbreviation. This was really hard to find, as i am using only the textual based configuration.

Here are some examples were they differ:
```
Thing	HmIP-SWDO-PL		0023DA55A3A7F1	"Homematic: Kontakt Haustür" @ "Flur Erdgeschoss"
Thing	HMIP-SWDO			0000DA66A63691	"Homematic: Kontakt Garage" @ "Garage"
Thing	HmIP-BROLL			00111A77A5F7C1	"Homematic: Rollade Arbeitszimmer" @ "Arbeitszimmer"
Thing	HmIP-SRH			0007D5889E90E1	"Homematic: Griffsensor Essbereich" @ "Essbereich"
Thing	HMIP-PSM			0001D3999C8281	"Homematic: Steckdose Server" @ "Anschlussraum"

```

I am not sure if the binding provides the thing type naming or this is coming directly from the ccu. So far i couldn't find any systematic when HmIP or HMIP is used.

This isn't really a bug just some minor inconvenience for the user if they are doing textual based configuration.

**Comment by MHerbst** [comment]
@regnets As far as I know the inconsistent names are a "feature" of the Homematic IP devices. In the binding there have been some changes to work case-insensitive regarding the device names.  I would have to check whether these changes may have a negative impact on the textual thing definitions. I would have expected that the names could be used care-insensitive.

**Comment by regnets** [comment]
@MHerbst: As far as i experienced it with the current stable (2.5.8 - using the official Docker Repository) i am unable to access any channels of the device if i change the case of the M character. 

This isn't a bug, this is just me carelessly copying lines in the things-file and not finding the wrong typed thing type.

**Comment by lsiepel** [comment]
Many [PR's have been merged](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+%5Bhomematic%5D+in%3Atitle+created%3A%3E2020-05-01+) since. I don't recognise one that alters this behavior. Is this still an issue to resolve and/or is this something that can't be fixed ?

**Comment by dirkbe** [comment]
This inconsistency is not related to the homematic binding as the thing type namings have been defined by the device manufacturer. On the CCU check in Settings->Devices, Filter on Types "IP-" and you'll see e.g. HmIP-BROLL, HmIP-SWDO-I, HMIP-PSM, HMIP-WRC2, ...
It's annoying in the things-file but nothing we should fix here therefore I suggest we close this issue.
