### ISSUE TITLE
2.5.7 -> troubles with expert package

### ISSUE THREAD

**Issue by bd8392** [openhab/openhab-addons#8355]
When choosing the expert-package (fresh-install), openhab doesn't seem to work correctly...-> store doesn't work properly, openhab crashes etc. Everthing works on standard-install.

1. Install hypriot os on pi 4
2. run openhab docker-container with docker compose like described in the official forum behind a reverse proxy (here traefik 2.3)
3. choose expert install
4. get broken openhab 

Raspberry pi 4 inside docker container with openhab/openhab 2.5.7

**Comment by Hilbrand** [comment]
Your description is a bit vague to tell what is wrong. But this is the repository for the addons and this seems not related to that, but i don't know what it is. You might have more luck if you first post on the forum and if that results in a concrete bug please do post it in the repository where the bug applies to.

**Comment by bd8392** [comment]
Oh sorry I missreaded it...thanks for the advice I'll try :-)
