### ISSUE TITLE
[MiHome] Xiaomi Mi Smart Home Gateway added twice with different IDs

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab-addons#8365]
[mihome debug.log](https://github.com/openhab/openhab-addons/files/5146692/mihome.debug.log)
## Expected Behavior
A Xiaomi gateway should only be added once. This worked fine when I was on openHAB 2.4.x

## Current Behavior
On openHAB 2.5.7 one of my Xiaomi gateways is added twice, first with the correct ID (04cf8c915156s) and then it shows up in the inbox again but with wrong ID (4cf8c915156s). **The leading 0 has been truncated**. See attached log. I can then no longer change the brightness of the Gateway LED using the correct ID with mihome:gateway:04cf8c915156:brightness.

**Valid:**
![image](https://user-images.githubusercontent.com/13090236/91656573-1841bf00-eaba-11ea-9eb5-6fab8cf4e0ea.png)

**Invalid:**
![image](https://user-images.githubusercontent.com/13090236/91656599-50490200-eaba-11ea-96d1-20292aaeaeb3.png)

## Your Environment
openHAB 2.5.7 running on Windows 10
MiHome binding 2.5.7

**Comment by lolodomo** [comment]
Unfortunately, your logs do not contain any scan for bridges.
If you have requested bridge things, I should see at least this log entry: Start scan for bridges

By the way, I can provide a simple workaround in case it is a bug in the gateway !

**Comment by lolodomo** [comment]
Fixed by mergez PR
