### ISSUE TITLE
[modbus] Link to developer section broken

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-addons#8382]
@ssalonen The link to the developer section doesn't work in the rendered documentation, as only the README.md seems to be exported: https://www.openhab.org/addons/bindings/modbus/#for-developers

**Comment by ssalonen** [comment]
Good catch, it must been like that for a while!

How to fix it?

**Comment by fwolter** [comment]
You could link to the file in the Github repo. I don't know if there is a better solution.
