### ISSUE TITLE
[unifi] Unifi G4 Doorbell

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-addons#8384]
It would be nice if the unifi g4 doorbell can be integrated in the unifi binding. https://store.ui.com/collections/unifi-protect-cameras/products/uvc-g4-doorbell

Unifi Binding

**Comment by lsiepel** [comment]
Two months after your post, a dedicated binding was developed. A background thread is here:  https://community.openhab.org/t/unifi-protect-binding-cloudkey-gen2-dream-machine-pro-nvr/107692 
The binding is available in the marketplace.

**Comment by lsiepel** [comment]
As the unifi binding is able to list the g4 doorbell as any other device and there is a marketplace binding that supports about all features of the G4, i close this request. Feel free to re-open if i misunderstood your request.
