### ISSUE TITLE
[hue] Support activation/deactivation of motion sensor

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#8389]
<a alt="bounty" href="https://www.bountysource.com/issues/92746115-hue-support-activation-deactivation-of-motion-sensor"><img src="https://api.bountysource.com/badge/issue?issue_id=92746115"></a>

Currently the hue binding doesn't support the activation or deactivation of motion sensors.

I am aware that i could replace the inbuilt feature of the bridge with openhab rules, however i really would like that the hue system handles such small tasks by its own. So it would be nice to deactivate motion sensors if a person uses lights in a room and activate the motion sensor again at midnight or so.

Here is some information about the request to the bridge:
https://community.home-assistant.io/t/hue-motion-sensor-on-off-switch-possible/121555

This could be integrated as another channel for the motion sensor.

**Comment by regnets** [comment]
I created a small bounty for this feature request:
https://www.bountysource.com/issues/92746115-hue-support-activation-deactivation-of-motion-sensor

**Comment by cweitkamp** [comment]
@regnets Thanks for posting a bounty on this issue :+1: .

**Comment by cweitkamp** [comment]
I submitted a proposal for this (#8721).

// CC @rgrollfitz

**Comment by cweitkamp** [comment]
Reopen and closed for triggering Bountysource.
