### ISSUE TITLE
[milight] Wrong comparison for animation-speed in-/decrease

### ISSUE THREAD

**Issue by NiklasHil** [openhab/openhab-addons#8430]
## Expected Behavior
Sending a "INCREASE" to a dimmer-Item on "animation_speed_relative" should increase the animation Speed

## Current Behavior
Sending a "INCREASE" to a dimmer-Item on "animation_speed_relative" decreases the animation Speed.
Caused by a wrong comparison in:
org\openhab\binding\milight\internal\handler\MilightV6RGBCWWWHandler.java: line 87,
org\openhab\binding\milight\internal\handler\MilightV6RGBWHandler.java line: 80
relative Speed cannot be greater than one, as it is called with the values -1 or 1 from handleCommand() inside AbstractLedHandler.java.

## Possible Solution
Change comparison from 
"relativeSpeed > 1 ? 3 : 4"
to
"relativeSpeed == 1 ? 3 : 4"

## Steps to Reproduce (for Bugs)
1. Try to Increase Animation Speed and one will notice, that the speed decreases.

**Comment by Skinah** [comment]
Just wondering if you tested making that change as it sounds like you looked into this in depth? I don't have any of the milight hubs as I use a DIY made one but I do know this binding a little bit.

**Comment by NiklasHil** [comment]
Hey @Skinah,
yes, I have it up and running fine with that change atm.

**Comment by Skinah** [comment]
Are you able to do a PR for this single line change?

**Comment by lsiepel** [comment]
Did not find a PR so i guess this is still an issue. As this issue is very detailed, creating a PR won't be that difficult. I don't have this device and don't know if it would cause side effects (e.g. existing users depending on the current behavior). 
What can we do to solve this?

**Comment by lsiepel** [comment]
Gentle ping @NiklasHil

**Comment by NiklasHil** [comment]
Sorry, I totally forgot about this issue. I moved away from Openhab a while ago, so I cannot be of much help anymore.

**Comment by Skinah** [comment]
@lsiepel If you want to do the PR it would be worth doing as a user has confirmed it already. I don't have the hardware needed as I use the espmilight hub project to control the globes by MQTT.
