### ISSUE TITLE
[gree] Not all GREE models support currentTemperature

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#8452]
@taboneclayton I tried the new build with the merged PR and current temp is reported with -40°C
<img width="386" alt="Bildschirmfoto 2020-09-11 um 11 33 12" src="https://user-images.githubusercontent.com/12601656/92924364-1d4b2a80-f439-11ea-83f6-9d2a11cfe17b.png">

I verified with the debugger that the device returns current temp = 0.0. Therefore you should change updateCurrentTemp to provide NaN in this case:
```
  private @Nullable State updateCurrentTemp() throws GreeException {
        if (device.hasStatusValChanged(GREE_PROP_CURRENT_TEMP_SENSOR)) {
            double temp = device.getIntStatusVal(GREE_PROP_CURRENT_TEMP_SENSOR);
            return temp != 0 ? new DecimalType(temp + INTERNAL_TEMP_SENSOR_OFFSET + config.currentTemperatureOffset.doubleValue()) : UnDefType.UNDEF;
        }
        return null;
    }
```

The channel description in the README should outline the fact that this channel is not supported for all device types

**Comment by taboneclayton** [comment]
Thanks for testing and reporting. Will work on the suggested fix and documentation changes.

**Comment by markus7017** [comment]
@taboneclayton fyi: I'm already working on this issue as part of a new PR including improved timeout handling (when UDP packets gets lost)
