### ISSUE TITLE
[upnpcontrol] Adding UPNP thing manually by URL

### ISSUE THREAD

**Issue by Beanow** [openhab/openhab-addons#8478]
I'm running openHAB from a docker container that's *not* in `network_mode: host`.
Therefore SSDP queries won't find any devices.

The devices are reachable on a static IP though, so given the URL of the device's XML file we could control devices. Of course coming with all the drawbacks of static configuration, so discovering by UDN would still be the preferable way for most people.

Additionally having this option would allow you to roll your own discovery such as setting DNS names for them or programmatically adding the things.

**Comment by hmerk** [comment]
This sounds like a really bad idea to me. If your appliance does not anser on SSDP queries, the underlying UPnP service does not know anything about it, e.g registered services. As a conclusion, none of the used UPnP methods would work in the binding, as it cannot retreive any information from the UPnP device registry.

**Comment by Beanow** [comment]
> As a conclusion, none of the used UPnP methods would work in the binding, as it cannot retreive any information from the UPnP device registry.

Based on your comment I glanced over the addon's implementation. If I understand correctly the problem is that the addon doesn't implement the SSDP + Device description parsing. This is handed off to a central registry which will expose a device handle.

What my suggestion is is to replace one of those two steps (SSDP) with a statically configured URL to the device description. So possibly my feature request is in the wrong place. If the UPnP device registry allows adding entries manually from static config, everything else should work?

**Comment by hmerk** [comment]
openHAB is using JUPnP as the underlying package, which has no interface for setting such a configuration and this would be completely against the UPnP specification afaik.
So why not just changing network mode to host for your docker container ???

**Comment by mherwege** [comment]
There are multiple bindings that use upnp in one form or the other. To my knowledge, they all rely on the framework and underlying jupnp library for device communication. Decoupling this and directly implementing in the binding would be a major undertaking. I am also not sure it is at feasible.
The openHAB framewor only exposes a limited set of methods. I ran into this when trying to get hold of the services descriptions in a further development of the binding. The url changes over time, as the port may change when the device goes offline and online again. So statically setting it was not an option. I had to get hold of the registry in the jupnp library that keeps track of these changes.
Therefore, if at all feasible, resolving this should be done in the core.

**Comment by Beanow** [comment]
Well, I opened the issue because I ran into one use-case and believe it would afford a lot more configuration flexibility in general. If the chosen architecture and libraries make it too difficult, that's unfortunate.

---

> and this would be completely against the UPnP specification afaik.

Wasn't sure about this, but what I could find to be within spec we should add an extra step, unicast SSDP queries.
https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf

> 1 Discovery
> ...
> In addition, a control point is allowed to unicast a discovery message to a specific IP address on port  1900  or  on  the  port  specified  by  the  optional  SEARCHPORT.UPNP.ORG  header  field  (which  supersedes  port  1900  for  this  use),  searching  for  a  UPnP  device  or  service  at  that  specific IP address. This action presumes the control point already knows the device at this IP address  is  a  UPnP    device (which listens on the appropriate port)

I had _assumed_ that SSDP was required to implement but not required to be the only discovery mechanism. Haven't found a clear answer on this, other than this part.

> To reiterate, a control point is allowed to learn of a device of interest because that device sent discovery  messages  advertising  itself  or  because  the  device  responded  to  a  discovery  message searching for devices. In either case, if a control point is interested in a device and wants to learn more about it, the control point uses the information in the discovery message to  send  a  descriptionquery  message.  The  clause   on  Description  explains  description messages in detail.

Which you could interpret as, SSDP is the exclusive means for discovery. But seems to contradict with "the control point already knows the device at this IP address  is  a  UPnP device..." as it wouldn't be _allowed_ to know if this were the exclusive discovery mechanism.

---

>  So why not just changing network mode to host for your docker container ???

Well again, it's just a use-case. I can (and probably will) change my setup, but I opened the issue as it seems like it would give greater flexibility. Whether you're having an issue or want to add some security on top of the unauthenticated, unencrypted control APIs these typically have :man_shrugging:.

Why I didn't start with host networking is because this machine is already running another 30+ services in swarm-mode. With much existing infrastructure for routing, monitoring, authentication, etc. Support for a mixture of orchestrated and local containers is pretty poor so I'll have to add workarounds on that end.

But given that swarm-mode comes with other limitations affecting openHAB (such as WoL and access to USB dongles) it's probably the way to go.

**Comment by hmerk** [comment]
There might still be some kind of a misunderstanding.
Yes, a controlPoint (e.g. UPnP binding in openHAB) can send multicast or unicast SSDP discovery messages, unicast specified by IP-Address. Without these discovery messages, there will be no further information exchange about available services to call or GENA-Events to subscribe to. If I understand correct, your docker instance will not react on SSDP packets at all if not in host mode. So your feature request would not work.

**Comment by Beanow** [comment]
Good point. Forgot the unicast is still UDP with limited TTL, that wouldn't be much of an improvement. So it would need to be as my original suggestion, not using SSDP and going straight to the description XML as that's all HTTP from there on out.

Which I'm still not sure is allowed by spec, and I had assumed would be easier based on other libraries I'd tried out before. If not worthwhile, feel free to close.
