### ISSUE TITLE
[shelly] shelly_de.properties contains some entries containing wrong encodings

### ISSUE THREAD

**Issue by MHerbst** [openhab/openhab-addons#8528]
The properties files is encoded as ISO-8859-1 but it contains some characters with a wrong encoding. 
These problems are now visible with the new OH 3 UI:
![image](https://user-images.githubusercontent.com/616792/93814192-79d9f100-fc54-11ea-92bf-accf3bb1783b.png)
![image](https://user-images.githubusercontent.com/616792/93814242-8cecc100-fc54-11ea-9321-bf51e1c7d164.png)

**Comment by markus7017** [comment]
âC is replaced by °C
do you saw other chars?
