### ISSUE TITLE
[modbus.e3dc] [modbus.helioseasycontrols]  [modbus.stiebeleltron]  [modbus.studer] Missing in features xml?

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#8538]
We are missing all the new modbus binding "extensions" in `openhab-addons/features/.../footer.xml`: https://github.com/openhab/openhab-addons/blob/main/features/openhab-addons/src/main/resources/footer.xml#L23-L28

https://github.com/openhab/openhab-addons/blob/5297ac252477d4afa86b3c1051aed88fb48fcd8e/features/openhab-addons/src/main/resources/footer.xml#L23-L28

Only `modbus.sunspec` is listed in the `openhab-binding-modbus` feature.

The corresponding modbus bindings were introduced in the following PRs:
- modbus.e3dc #8172 @weymann
- modbus.helioseasycontrols #8250 @bern77
- modbus.stiebeleltron #7718 @pail23
- modbus.studer #8163 @giovannimirulla

_______

- Does this explain installation issues reported by users? https://community.openhab.org/t/e3dc-modbus-binding-test-request/103968/
- Is this the only file that has missed the update or should the bindings be in other files/manifests as well?

## Possible Solution

Add bindings listed above to footer.xml

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by kaikreuzer** [comment]
That should be the only file, I think. Can you create a PR for it?

**Comment by kaikreuzer** [comment]
Btw, while you are on it, could you also remove the word "Binding" from the READMEs of those extensions to avoid confusion?
