### ISSUE TITLE
[meteoalerte] Use number instead of string for alert level channels

### ISSUE THREAD

**Issue by olivierkeke** [openhab/openhab-addons#8543]
Alert level channels provide a string encapsulating an integer.
It would be great to have instead a `number` type. This would permit to use the group state functionality: https://www.openhab.org/docs/configuration/items.html#derive-group-state-from-member-items

**Comment by clinique** [comment]
This is a very valid point, but it is not currently permitted by the framework to have a channel of type Number with options.
Options can only be strings.

**Comment by clinique** [comment]
@openhab/core-maintainers : do you think it would be possible to extend option definition to handle also numeric values in 3.0.0 core ?

**Comment by kaikreuzer** [comment]
>  it is not currently permitted by the framework to have a channel of type Number with options

Hey @clinique, Really, is that the case? I would actually consider it a bug then and yes, I'd think the framework should support that!

> Options can only be strings.

What I can see is that the `value` within the `StateOption` is a string - but my assumption would be that this is simply a string representation of the type's value. At what place does it crash, if you have state options defined for number channels? Feel free to open a bug report in openhab-core for that.

**Comment by cweitkamp** [comment]
The options can be used with `Number` too. I remember a discussion about that some days ago and we agreed on a mistake in the documentation. Unfortunately I cannot find the link to the discussion. But I know a valid example for it - the system default channel type for signal strength:

https://github.com/openhab/openhab-core/blob/2f2bfde500892ac3346edba5e7fcb241d95f7ff8/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/DefaultSystemChannelTypeProvider.java#L60-L73

**Comment by clinique** [comment]
@cweitkamp : thanks for the information. I was mislead because I tried to describe options in the resource xml file without quotes.

**Comment by olivierkeke** [comment]
> It would be great to have instead a `number` type. This would permit to use the group state functionality: https://www.openhab.org/docs/configuration/items.html#derive-group-state-from-member-items

To my great surprise group state is working even if the number is encapsulated in string. I use `MAX` grouping state on alert levels without problem. It seems that string are somewhere cast to number when using group state...

**Comment by clinique** [comment]
Yes, good surprise, but I still consider your demand as very valid.
