### ISSUE TITLE
[wifiled] - support single-channel white controller

### ISSUE THREAD

**Issue by gooman-uk** [openhab/openhab-addons#8548]
## Your Environment

* Version used: openHAB 2.5.5-1
* Operating System and version: OpenHabian

I have a single channel white WiFi LED controller. After doing a deep-dive into Wireshark, I can see that the protocol used is based on LD382A but with two important differences:

1. The single white channel is sent in the first byte after the 0x31 (which is usually red)
2. The last byte which is usually 0x00 is sent as 0x01

Here's what's sent by the MagicHome app setting the brightness to 53% (0x86):   31 86 00 00 03 01 0f ca

Can the binding be updated to support this protocol variant?

Thanks

**Comment by davidgurr** [comment]
There's a *much* more complete implementation of the protocols (including support for the white-only variant) in this project: https://github.com/beville/flux_led/tree/master/flux_led

**Comment by davidgurr** [comment]
There is a viable workaround. By default, this LED controller will work with the default LD382A protocol but maps the white LEDs to the red channel.

If you just use a Dimmer Item to control the Thing (rather than a Color Item) then it all works fine.
