### ISSUE TITLE
[netatmo] Webhook uri not configured in app/not triggered for Presence camera

### ISSUE THREAD

**Issue by giejay** [openhab/openhab-addons#8550]
## Expected Behavior
When adding the Netatmo API Bridge with the correct clientId, secret, mail + password and a webhook, I expect that webhook being pushed to my Netatmo app. Or at least a webhook event being triggered whenever I walk by the camera.
I enabled Access Welcome camera + Access Presence camera. Should the webhook be visible in the app under App technical parameters? 

## Current Behavior
Nothing happens, I dont see anything in the logs regarding receiving an event. When I test the webhook url with a dummy event using Postman, then I see something in the logs: 
```
20:55:30.004 [DEBUG] [nternal.webhook.WelcomeWebHookServlet] - Event transmitted from restService
```

## Steps to Reproduce (for Bugs)
1. Create an application at https://dev.netatmo.com/apps
2. Use the creds from that application to create a Netatmo API bridge
3. Enable Access Welcome camera + Access prsencce camera
4. Fill in the webhook url
5. Save it, check the Presence camera being discovered + Welcome Home and add both as a Thing.
6. Sent a telegram whenever the channel action "Camera Event" in Welcome Home is being triggered
7. Only get Telegrams whenever the Bridge polls Netatmo, which is like 10 minutes after the event occurred. 

## Context
The logs:
```
20:29:55.683 [DEBUG] [internal.handler.NetatmoBridgeHandler] - Initializing Netatmo API bridge handler.
20:29:57.689 [DEBUG] [internal.handler.NetatmoBridgeHandler] - Initializing API Connection and scheduling token refresh every 5400s
20:29:58.166 [DEBUG] [nternal.webhook.WelcomeWebHookServlet] - Started Netatmo Webhook servlet at /netatmo/0b2c7b23/camera
20:29:58.174 [DEBUG] [internal.handler.NetatmoBridgeHandler] - Setting up Netatmo Welcome WebHook
20:31:42.776 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Data aged of 329 s
20:31:42.782 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Trying to update channels on device --
20:31:43.320 [DEBUG] [internal.welcome.NAWelcomeHomeHandler] - welcome home '----' calculate Persons at home count
20:31:43.326 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Successfully updated device -- readings! Now updating channels
20:31:43.853 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Updating child modules of ----
20:31:43.858 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Updating child module 70:ee:50:3a:1111
20:31:43.865 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Scheduling update channel thread in 329 s
20:37:12.868 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Data aged of 329 s
20:37:12.871 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Trying to update channels on device --
20:37:13.130 [DEBUG] [internal.welcome.NAWelcomeHomeHandler] - welcome home '----' calculate Persons at home count
20:37:13.142 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Successfully updated device -- readings! Now updating channels
20:37:13.621 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Updating child modules of ---
20:37:13.629 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Updating child module 70:ee:50:3a:11:11
20:37:13.637 [DEBUG] [internal.handler.NetatmoDeviceHandler] - Scheduling update channel thread in 329 s
```

What I also tried is setting the webhook in my app myself, but also does not trigger anything in Openhab

## Your Environment
Openhab 2.5.5

**Comment by lolodomo** [comment]
Did you read the binding documentation and what is written about webhook? 
Is the URL you setup in the binding accessible from the internet?

**Comment by giejay** [comment]
Yes and yes. As I already mentioned, using postman to reach my url (from outside) works fine and I see a log entry

**Comment by giejay** [comment]
Any idea how to debug this? Is there some kind of webhook logs available at netatmos site I can look at?

**Comment by lolodomo** [comment]
If the URL was called by Netatmo, you should see this log entry: Event transmitted from restService
Or the URL is called but the message is not the one expected by the binding and JSON conversion is triggering an exception. 
Note that Netatmo will very quickly bannidh you in case there is no valid answer to the call. You will have to wait for one day to try again, During this time, the URL is no more called by Netatmo. 
The most probable reason is that you did something wrong in your setup and you were bannished. 
Unfortunately a log entry is missing in the binding to be 100℅ sure that the URL was called or not.

**Comment by giejay** [comment]
So, after more debugging, I figured it out. My nginx mapping had a / at the end and that resulted in netatmo seeing a 301 from my side. Removing the slash resulted in 200's. 

Now the second problem was that my channel does not get triggered, I added some log statements to the binding and compiled it again, it seems that's because n=Netatmo is now providing a new eventType called "human":

```
{
    "user_id": "5d3b527c61",
    "snapshot_id": "5f72f27906c1c34",
    "snapshot_key": "724b2300f158f43984a427732aa6ff3f14accb97",
    "snapshot_url": "https:\/\/netatmocameraimage.blob.core.windows.net\/production\/",
    "vignette_id": "5f72f2791c35",
    "vignette_key": "0fee09db78cf74c8adbdc1de539e6a1e697d0a62",
    "vignette_url": "https:\/\/netatmocameraimage.blob.cor",
    "event_type": "human",
    "camera_id": "70:ee:50:2a:--:--",
    "device_id": "70:ee:50:2a:--:--",
    "home_id": "id",
    "home_name": "Home",
    "event_id": "eventId",
    "subevent_id": "d9b0530889-f631cddc3bbe",
    "message": "Person seen",
    "push_type": "NOC-human"
}
```

Also, as you can see, there is no app_type so therefore the check in the NetatmoBridgeHandler (event.getAppType() == NAWebhookCameraEvent.AppTypeEnum.CAMERA) is preventing the channel from being triggered. 

Next to that, "human" is not in the list of eventTypes. I made some changes to the binding (add the eventType, modify the if statement and add the snapshot_url to the WebhookCameraEvent fields) and now it all works:)

What I am wondering, am I doing something wrong or did Netatmo change its webhook data?

**Comment by retos** [comment]
Hello giejay

I'm not sure if I experienced the same thing. I do not use a nginx server at the moment and therefore left the webhook empty on the configuration on my application under https://dev.netatmo.com/apps.

```
Bridge netatmo:netatmoapi:home "Netatmo API" [ clientId="myclientid", clientSecret="mysecret", username="myusername", password="mypassword", readStation=true, readHealthyHomeCoach=true, readThermostat=false, readWelcome=false] 
{ 
     Thing NACamera camera [ id="70:ee:50:32:62:c4" ] 
}
```

In Paper UI the Netatmo API appears online. But my camera has an error: Status: UNINITIALIZED - HANDLER_CONFIGURATION_PENDING

In the log I only see this:
```
2020-09-29 20:16:11.045 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'netatmo.things'

2020-09-29 20:16:11.088 [me.event.ThingUpdatedEvent] - Thing 'netatmo:netatmoapi:home' has been updated.

2020-09-29 20:16:11.095 [hingStatusInfoChangedEvent] - 'netatmo:NACamera:home:camera' changed from UNINITIALIZED (HANDLER_CONFIGURATION_PENDING) to UNINITIALIZED (HANDLER_MISSING_ERROR)

2020-09-29 20:16:11.104 [me.event.ThingUpdatedEvent] - Thing 'netatmo:NACamera:home:camera' has been updated.
```
Not sure what you mean with step 3 from above:

> 3. Enable Access Welcome camera + Access prsencce camera

**Comment by giejay** [comment]
I'm not sure about the binding through text but I guess you need to add "readPresence" to your config. 

You are right about the polling mechanism, it works but with a 5 minute delay. Webhook is 3 seconds.

**Comment by retos** [comment]
Thanks for the hint. Unfortunately it still does not work. I event tried accessing the netatmo API directly through Python. That worked. Unfortunately, the logs offer not more Information. I'm stuck.

I have a suspicion, that it might only work if you own a Welcome Home camera? I only own an Welcome Camera, but in the config there is a parent relationship:
```
    Thing NAWelcomeHome home   [ id="58yyacaaexxxebca99x999x", refreshInterval=600000 ]
    Thing NACamera camera [ id="cc:cc:cc:cc:cc:cc", parentId="58yyacaaexxxebca99x999x" ]
```
Do you think a Welcome Home camera might be needed? Or do you know what the parentId is used for?

**Comment by giejay** [comment]
There is no such thing as a Welcome Home camera. Welcome Home is the place the camera resides. You need both a Home and a Camera thing to be present. Can you try to add it using the paper ui? That will automatically discover your home and camera, makes it a lot easier. Otherwise, you need to figure out what your home id is, somewhere in the app or API.

**Comment by retos** [comment]
Wow, thanks a lot for that comment. It works now. For whatever reason I thought the NAWelcomeHome is the indoor Camera. *facepalm* The home id I know already from connecting through python. Once the line was added with the home id it did the trick.
I shouldn't have done It through the config file...

**Comment by lolodomo** [comment]
@giejay : eventType called "human" is now supported by the Netatmo binding.
As the Netatmo binding was largely revamped, please try again with the new version and open a new issue in case you still have problem with webhook.
