### ISSUE TITLE
[modbus] Dev docu references to jamod 1.2.4.OH

### ISSUE THREAD

**Issue by fwolter** [openhab/openhab-addons#8551]
The Modbus developer documentation refers to net.wimpi.jamod 1.2.4.OH, but in the public Maven repo only 1.2.3.OH is available: https://mvnrepository.com/artifact/org.openhab.osgiify/net.wimpi.jamod
https://github.com/openhab/openhab-addons/blame/main/bundles/org.openhab.binding.modbus/DEVELOPERS.md#L25

@ssalonen Is this an error in the documentation or in the repo?

**Comment by ssalonen** [comment]
@fwolter I don't know anything about repos but jamod was updated some time ago: https://github.com/openhab/openhab-addons/pull/8067

**Comment by fwolter** [comment]
This resolves correctly (to our fork of Jamod):
```
		<dependency>
			<groupId>net.wimpi</groupId>
			<artifactId>jamod</artifactId>
			<version>1.2.4.OH</version>
			<scope>runtime</scope>
		</dependency>
```
This is also referenced in [io.transport.modbus](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.transport.modbus/pom.xml#L30).

The osgiified version is still 1.2.3.OH: https://github.com/openhab/openhab-osgiify/blob/master/net.wimpi.jamod/pom.xml#L13

@kaikreuzer I'm not sure if the osgiify version needs a bump, too. Or is it used in OH at all?

**Comment by kaikreuzer** [comment]
Afaics, https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.io.transport.modbus/pom.xml is not referencing the osgiified version of that lib, but the normal one, which hence gets packaged within the io.transport.modbus bundle.
I'd hence say that the dev docs are outdated and need to be changed.
@J-N-K You as the master of the OSGiified libs: Please correct me, if I state anything incorrect here.

> but in the public Maven repo only 1.2.3.OH is available

Your link is a reference with the group id "org.openhab.osgiify". If you look under "net.wimpi", you will also find the 1.2.4.OH referenced on Bintray: https://mvnrepository.com/artifact/net.wimpi/jamod/1.2.4.OH (btw, pretty interesting that there are [7 other projects](https://mvnrepository.com/artifact/net.wimpi/jamod/usages) using that version of the library...)

**Comment by J-N-K** [comment]
We can probably remove nearly all bundles from the osgiify repo, since we embed them. There are some bundles which are not available from other sources at all (even non-OSGi-version). These would need to be uploaded to the openhab-addons-dep.
