### ISSUE TITLE
[netatmo] Support for the Netatmo video doorbell

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8571]
The Netatmo video doorbell will get released at 2020-09-28. It should get supported by OpenHAB like the other Netatmo cameras.

Exclusive features of the doorbell which should be available within OpenHAB:
- The ring event should get recognized (probably as a new channel)

Unfortunately I didn't got access to the beta or ambassador test program, so I'm not able to realize the support of the camera (soon).

**Comment by giejay** [comment]
Also very interested in this one, I don't see the doorbell yet in their API documentation so I will sent them a mail.

**Comment by L-A-15** [comment]
Hi @Novanic -

hope you are doing good. I just bought the camera and was wondering if we have already made some progress with the implementation. Is the API ready from their side? I would be more than excited to get this feature :).

Thanks already for your contribution!

**Comment by Novanic** [comment]
Hello, the API seems to be ready, but I still don't have the device. ;-)

**Comment by giejay** [comment]
Where did you see that the API is ready? The dev.netatmo.com page is blank for me.

For now I hacked ring support into the binding by checking if the message from the webhook contains Ring and I added a Doorbell event  Works very fast btw!

I can help you with providing payloads of the webhook if that's helpful.

**Comment by Novanic** [comment]
Ah, you are right, at least the documentation isn't updated. But your forum post describes that the webhook is already working and that there are new scopes (which aren't yet documentated).

**Comment by giejay** [comment]
Yes, Im currently using those scopes to get the webhook events in the binding. Unfortunately there are no events yet for motion but I hope that the devs will add those soon

**Comment by L-A-15** [comment]
Nice, thanks you folks for your responses. I see it's just a matter of time - cain't wait to bring the doorbell into the ecosystem :). Thanks

**Comment by giejay** [comment]
The API is finally sending some more useful information in the webhook payload.

Person seen: 

2021-01-18 19:02:07.806 [DEBUG] [ternal.webhook.WelcomeWebHookServlet] - Event transmitted from restService, data: {"user_id":"d","snapshot_id":"d","snapshot_key":"longkey","snapshot_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/id","vignette_id":"d","vignette_key":"d","vignette_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/id","event_type":"human","camera_id":"70:ee:50:6ea","device_id":"70:eef1:4a","home_id":"32234","home_name":"Home","event_id":"323","subevent_id":"5sdf","message":"Persoon gezien door Frontdoor","push_type":"NDB-human"}

Ring:

2021-01-18 19:28:41.281 [DEBUG] [ternal.webhook.WelcomeWebHookServlet] - Event transmitted from restService, data: {"user_id":"d","event_type":"incoming_call","device_id":"d:4a","home_id":"d","home_name":"Home","camera_id":"70:d1:4a","event_id":"d","subevent_id":"7a9d328-d","snapshot_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/d","vignette_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/d","push_type":"NDB-incoming_call"}

Missed call:

2021-01-18 19:29:20.729 [DEBUG] [ternal.webhook.WelcomeWebHookServlet] - Event transmitted from restService, data: {"user_id":"d","event_type":"missed_call","device_id":"7:de:f1:4a","home_id":"d","home_name":"Home","camera_id":"70:dd0:d:4a","event_id":"d","subevent_id":"d-d328-41fe1c519654","snapshot_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/d","vignette_url":"https:\/\/netatmocameraimage.blob.core.windows.net\/production\/d","push_type":"NDB-missed_call"}

**Comment by clinique** [comment]
Please note that a complete rewrite of the Netatmo binding has been [submitted ](https://github.com/openhab/openhab-addons/pull/9486)- focused on removing all external dependencies so update cycle with new APIs will be easier. I'm testing it in prod since two weeks and everything seems fine.

**Comment by giejay** [comment]
Thanks @clinique. I'm guessing that does not include  doorbell support yet?

**Comment by clinique** [comment]
No, I've prepared some elements (scope, moduletype) but I do not own one, so not able to test it.

**Comment by Novanic** [comment]
@clinique I have implemented support for it based on 3.0.0 to use and test it within my productive system. But I have a conceptional problem. The doorbell needs webhook events to get fast information about a call/ring event. But what is with the other data which aren't receiveable via webhooks, like the snapshot picture? I would like to send a message with a snapshot picture to the Telegram app, but this isn't possible when the snapshot picture is available after a few minutes... Do you have an idea to get this together or is there a better solution within the 3.1 binding draft? Thank you and best regards, Sven.

**Comment by clinique** [comment]
I suppose that the picture, or at least an url to the picture will be pushed via the webhook. Take a look at NAWebhookEvent, it contains a reference to a snapshot.

**Comment by Novanic** [comment]
> I suppose that the picture, or at least an url to the picture will be pushed via the webhook. Take a look at NAWebhookEvent, it contains a reference to a snapshot.

Ah, you are right, there is a snapshot_url. But it isn't mapped/used from the 3.0 version of the binding. So it should update the event snapshot channel before the trigger channel is executed? With this order a rule can react to the trigger channel and use the snapshot channel data. A little bit complicated. ;-)

**Comment by clinique** [comment]
I would strongly recommend that you switch to current version of the binding presented in this [PR](https://github.com/openhab/openhab-addons/pull/9486), you'll be more future proof.

**Comment by Novanic** [comment]
Ah, it is working now with updating the snapshot channels (before triggering the trigger channel). Thank you.

I can have only one system with a configured webhook with a public accessible adress on my network and that is of course my productive system and I prefer developing on a stable plattform. And I'm able to test and use it already. I can take a look at your PR when it is ready. Will your PR get merged before the release of 3.1?

**Comment by clinique** [comment]
you can have one webhook per Netatmo application, this means different credentials for each environment (clientId, clientSecret).
I would love to have it merged in 3.1 but I'm pending finalization of Valves - and that I do not master timeline, while on the other side I have no complains of people using preview version of the 3.1 binding, apart for the auth renewal that I tried to addess once again today.

**Comment by giejay** [comment]
Can someone with this doorbell check if ring events are still being received? I am only receiving person seen events. I raised my concern on the forum as well: https://forum.netatmo.com/viewtopic.php?f=5&t=20027&p=87673#p87673

**Comment by lolodomo** [comment]
@clinique: is the doorbell now fully supported ? I see it listed here:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/api/data/ModuleType.java#L101
Please close the issue if it is.

**Comment by clinique** [comment]
No, currently only basic support exists : 
It is detected as a radio module.
Work has to take place to make it interesting. I plan to do it as I've purchased and installed one.
