### ISSUE TITLE
[avmfritz] Support for missing important features of the TR064 binding

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#8578]
I think this "AVM FRITZ! Binding" is the current FritzBox binding which should replace the other outdated bindings ("Fritz AHA", "Fritz!Box", "Firtzbox (using TR064 protocol)"). Is that correct? At least these bindings seem to be outdated ("v1") and I think that could be a problem with the release of OpenHAB 3. And one hint for that theory is that the support for the call monitor was recently added (which is also realized within the TR064 FritzBox binding).

I'm still using these features of the TR064 FritzBox binding and I think these are also the most important features which should get realized within this binding:
* Presence detection (get the online status of configured MAC addresses)
* Information about the connection speed (to check if the connection is normally available)

**Comment by Novanic** [comment]
I could help developing the features if that is desired.

**Comment by kaikreuzer** [comment]
You might be interested in https://github.com/openhab/openhab-addons/pull/8523.

**Comment by hartmood** [comment]
More than happy to test if someone provides a binding jar file. Thanks.

**Comment by oRRs** [comment]
> More than happy to test if someone provides a binding jar file. Thanks.

Here you go (built off a3d33fa60b063bf6c8c3ff70c4ab8172e7b29244 and zipped to be able to upload here). Unfortunately, I wasn't able to get it to work, I only get 3 channels (uptime, deviceLog and reboot).
[org.openhab.binding.tr064-3.0.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/5517092/org.openhab.binding.tr064-3.0.0-SNAPSHOT.zip)

**Comment by J-N-K** [comment]
Already implemented in the tr064 binding. Please file a bug if it doesn‘t work.

@oRRs did you click on „advanced“ in the Channels tab?

**Comment by oRRs** [comment]
@J-N-K I didn't manage to find enough time for troubleshooting, which is why I didn't file a report. It's probably an issue on my side anyways and could come from migrating from 2.x.
I just wanted to supply hartmood with the compiled binding, sorry if I wasted someones time!

**Comment by hartmood** [comment]
@J-N-K Thanks for the file. Very nice of you. I just installed it. I have to Fritzboxes (6490, 7490). The second one is added to the mesh network and pops up in the inbox. The main box is not being identified. When trying to add it manually I cannot connect. What I get with a user that worked before is 

`2020-11-10 21:48:06.213 [hingStatusInfoChangedEvent] - Thing 'tr064:fritzbox:2c6d53e9fd' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): java.util.concurrent.TimeoutException: Total timeout 2000 ms elapsed
`
I tried different users including admin with username and email. Same result.

**Comment by J-N-K** [comment]
Looks like a network issue. Not sure if you can disable TR064 access,

**Comment by hartmood** [comment]
@J-N-K What do you mean with "disable network access"?

**Comment by J-N-K** [comment]
TR064 access needs to be enabled, in german language it's here: Heimnetz (home network)> Netzwerk (network)> Netzwerkeinstellungen (network settings) > Zugriff für Anwendungen zulassen (allow app access)

**Comment by hartmood** [comment]
That was already activated.

**Comment by hartmood** [comment]
Just tested the Bindung from the current snapshot. Still the same timeout as above mentioned

**Comment by J-N-K** [comment]
Did you enable debug/trace logging? What is in the logs?

**Comment by hartmood** [comment]
```
2020-11-22 19:29:20.217 [hingStatusInfoChangedEvent] - Thing 'tr064:fritzbox:6ca8732e7a' changed from OFFLINE (COMMUNICATION_ERROR): java.util.concurrent.TimeoutException: Total timeout 2000 ms elapsed to UNKNOWN
2020-11-22 19:29:20.233 [me.event.ThingUpdatedEvent] - Thing 'tr064:fritzbox:6ca8732e7a' has been updated.
2020-11-22 19:29:24.719 [hingStatusInfoChangedEvent] - Thing 'tr064:fritzbox:6ca8732e7a' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): java.util.concurrent.TimeoutException: Total timeout 2000 ms elapsed
==> /var/log/openhab/openhab.log <==
2020-11-22 19:29:28.019 [DEBUG] [binding.tr064.internal.util.SCPDUtil] - HTTP Failed to GET uri 'http://192.168.179.1:49000/tr64desc.xml': Total timeout 2000 ms elapsed
```

**Comment by J-N-K** [comment]
Look like you either did not enable TR064 access, blocked the address you are trying to connect from (e.g. other subnet may be detected by the FB as "remote" and blocked) or the FB is not reachable from your network. This is a configuration issue, not a binding problem.

**Comment by hartmood** [comment]
This is strange as the OH1 binding used to work perfectly. And now both Fritzboxes are not accessible anymore. But thanks - I will further investigate.

**Comment by hartmood** [comment]
A simple restart of the master mesh Fritzbox made it. Thanks again for support.
