### ISSUE TITLE
[amazonechocontrol] cannot configure account because of page refresh / no successfull login

### ISSUE THREAD

**Issue by scamille** [openhab/openhab-addons#8590]
When configuring the addon amazonechocontrol, login to the amazon account cannot be completed.

## Expected Behavior
Sign in works and discovery/setup completes.

## Current Behavior
* I set up a Thing 'Amazon Account'
* I go to <YOUR_OPENHAB>/amazonechocontrol/<YOUR_ACCOUNT>
* Sign in to my amazon account
* Amazon sends a security SMS to approve the login attempt
* Usually before being able to complete the security approval / even with fast approval, the page reloads after 3-4 seconds and resets back to the login page without a successful login.

## Context
I cannot complete the login step and thus not configure amazonechocontrol.

## Your Environment
Windows 10 2004 64bit 
openhab 2.5.9
Java 8 Update 261 (64bit)
Firefox 81  / Microsoft Edge 85 (tested with both)

**Comment by Tukks** [comment]
Same here

**Comment by ohaak** [comment]
Same issue for me. Binding was connected before, but somehow lost connection. Now I'm unable to log in again with the same situation as mentioned by @scamille  and @Tukks

**Comment by Tukks** [comment]
I added 2fa auth on my Amazon account, and it's working again.

**Comment by mattialibera** [comment]
> I added 2fa auth on my Amazon account, and it's working again.

For me the @Tukks solution works too. Thanks

**Comment by Caden-k** [comment]
Could you give the finished url then? I dont know what 2fa and Auth mean.

**Comment by Tukks** [comment]
> 
> 
> Could you give the finished url then? I dont know what 2fa and Auth mean.

https://www.amazon.com/gp/help/customer/display.html?nodeId=202073820 here's a guide

**Comment by jpvlsmv** [comment]
Mine was failing because I did not have a proper SSL certificate on my OpenHAB url.  Once I convinced LetsEncrypt to give me one, I had enough time to give the text-message code.
