### ISSUE TITLE
[somfytahoma] Add support for WaterHeatingSystem widgetName: AtlanticPassAPCDHW

### ISSUE THREAD

**Issue by ozirissp** [openhab/openhab-addons#8592]
Detected a new unsupported device: WaterHeatingSystem with widgetName: AtlanticPassAPCDHW

2020-09-27 23:00:25.744 [INFO ] [very.SomfyTahomaItemDiscoveryService] - If you want to add the support, please create a new issue and attach the information below

2020-09-27 23:00:25.748 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Device definition:

Commands: { refreshComfortTargetDHWTemperature (params: 0); refreshDHWDerogationAvailability (params: 0); refreshDHWOnOffState (params: 0); refreshEcoTargetDHWTemperature (params: 0); refreshTargetDHWTemperature (params: 0); setBoostOnOffState (params: 1); setComfortTargetDHWTemperature (params: 1); setDHWOnOffState (params: 1); setEcoTargetDHWTemperature (params: 1); refreshDHWConfiguration (params: 0); refreshPassAPCDHWMode (params: 0); refreshPassAPCDHWProfile (params: 0); setPassAPCDHWMode (params: 1); }

States: {core:BoostOnOffState (values: off, on); core:ComfortTargetDHWTemperatureState (values: ); core:DHWDerogationAvailabilityState (values: available, unavailable); core:DHWOnOffState (values: off, on); core:EcoTargetDHWTemperatureState (values: ); core:StatusState (values: available, unavailable); core:TargetDHWTemperatureState (values: ); io:PassAPCDHWConfigurationState (values: cumulated, snapshot); io:PassAPCDHWModeState (values: comfort, eco, externalScheduling, internalScheduling, manu, peakAndOffPeakScheduling, peakAndOffPeakTimes, stop); io:PassAPCDHWProfileState (values: absence, comfort, derogation, eco, externalSetpoint, frostprotection, manu, stop); }

2020-09-27 23:00:25.754 [INFO ] [very.SomfyTahomaItemDiscoveryService] - Current device states: 

{name='core:StatusState', type=3, value=available}

{name='io:PassAPCDHWConfigurationState', type=3, value=cumulated}

{name='io:PassAPCDHWModeState', type=3, value=comfort}

{name='io:PassAPCDHWProfileState', type=3, value=comfort}

{name='core:ComfortTargetDHWTemperatureState', type=1, value=48.0}

{name='core:EcoTargetDHWTemperatureState', type=1, value=40.0}

{name='core:TargetDHWTemperatureState', type=1, value=48.0}

{name='core:DHWDerogationAvailabilityState', type=3, value=available}

{name='core:BoostOnOffState', type=3, value=off}

{name='core:DHWOnOffState', type=3, value=on}

**Comment by octa22** [comment]
Hi @ozirissp,
I will add the support, but I need a little help. The controlling of this device seems to be a bit foggy to me.
How to you want to control this device in OH2? I see two switches (boost and ???DHW???), readonly target temperature, ...
What does DHW stand for? Maybe a screenshot from Tahomalink will be sufficient...
Thanks.
Ondrej

**Comment by lolodomo** [comment]
@ozirissp : can you provide the requested information ?
