### ISSUE TITLE
[ Systeminfo] CPU-Load1/5/15 delivers UNDEF every time

### ISSUE THREAD

**Issue by HomeOfSourceCode** [openhab/openhab-addons#8597]
On OH 2.5.8 and 2.5.9 (others not tested) I got these bug:

According to the documentation cpu#loadxx should hold the CPU load. 
```
Number CPU_Load1                  "Load (1 min)"        <none>           { channel="systeminfo:computer:work:cpu#load1" }
Number CPU_Load5                  "Load (5 min)"        <none>           { channel="systeminfo:computer:work:cpu#load5" }
Number CPU_Load15                 "Load (15 min)"       <none>           { channel="systeminfo:computer:work:cpu#load15" }
```

But this does not work. On my live and my test system the value is always UNDEF. On my old OH 2.4 system all is working fine with
```
Number CPU_Load                  "Load"        <none>           { channel="systeminfo:computer:work:cpu#load" }
```

## Expected Behavior
CPU_Load1 should hold the CPU load of 1min.

## Current Behavior
CPU_Load1 is always UNDEF
All other possible items (network, storage, memory) working well, all other CPU-items are workign well too. Only CPU-Load is faulty

## Possible Solution
no idea

## Steps to Reproduce (for Bugs)
use the example provided and you will see that the items are always UNDEF

## Your Environment
OH 2.5.8 and OH 2.5.9 on microsoft windows 10 (x86 and x64) (1703 and 2004) with zulu java current version (also tested with older versions of java)
Same config with OH 2.4 is working fine

**Comment by pacive** [comment]
Unfortunately, the OSHI library that the binding uses to get the info from the computer does not support load averages for windows, since windows doesn't provide these values natively. Also, the cpu#load channel was removed because the method to get this info was removed from OSHI when the version used by the systeminfo binding was updated.
