### ISSUE TITLE
[ComfoAir] EWT Temperature high / EWT Temperature low is shown as negative number

### ISSUE THREAD

**Issue by SnapStef** [openhab/openhab-addons#8600]
EWT Temperature high / EWT Temperature low is shown as negative temperature
It worked fine with the OH1 implemenation of the binding but with v2 of the binding the number got negative. I also think that the absolute value of the number is wrong but I'm not quite sure here

**Comment by boehan** [comment]
@SnapStef thanks for reporting this bug. I just had a look at the protocol again and it actually seems that these temperatures are the only ones that are directly submitted as celsius values by the device (all the others have to be transformed like `celsius = value / 2 - 20`). I obviously didn't consider this when implementing UoM on this channels.
Will provide a fix shortly.

**Comment by boehan** [comment]
@SnapStef if you would like to test the fix (I can't test due to missing ewt module), here is a jar for 2.5.x
[org.openhab.binding.comfoair-2.5.10-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/5300954/org.openhab.binding.comfoair-2.5.10-SNAPSHOT.zip)

**Comment by SnapStef** [comment]
I just tested it and it seems to work. Thank you for the quick reaction & fix!
