### ISSUE TITLE
[Hue] Add channel to activate/ disable the motion sensor

### ISSUE THREAD

**Issue by rgrollfitz** [openhab/openhab-addons#8605]
Currently theres a switch on the config page (OH3 1945) of the hue motion sensor item, which indicates to activate / disable the motion sensor trigger configured in the hue app. This switch seems to doing nothing atm.

Nevertheless, it would be nice to have this functionality as an channel of the motion sensor thing to use it in rules and so on.

**Comment by cweitkamp** [comment]
Thanks for the feature request. There already is #8389 and we can close this as being a duplicate.
