### ISSUE TITLE
Update Paper UI and HABmin references in add-on documentation

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#8607]
Many add-on `README.md` files reference or contain instructions for "Paper UI" or HABmin which are UIs that no longer exists in OH3.

**Comment by Skinah** [comment]
I can probably contribute to this especially after next week when I get some holidays.
Some questions:

+ What is the preferred replacement text for PaperUI? replace with 'the UI' ?
+ What is preferred, one PR per readme ?
+ If other typos or grammar are noticed, is it ok to include them in the same PR ?

**Comment by wborn** [comment]
Thanks for your help @Skinah!

> What is the preferred replacement text for PaperUI? replace with 'the UI' ?

Perhaps @ghys can answer that? I would personally go with "... the Main UI ..."

> What is preferred, one PR per readme ?
> If other typos or grammar are noticed, is it ok to include them in the same PR ?

It will probably be more efficient to fix multiple READMEs per PRs. If they are small typos/fixes you can also add them to such PRs. :+1: 

> Can we advertise this on the forum if not already done? Better to get people that can not code, to look at doing this if possible.

There was just an announcement for this to get previous contributors involved https://github.com/openhab/openhab-docs/issues/1133#issuecomment-743219806.

**Comment by kaikreuzer** [comment]
> What is the preferred replacement text for PaperUI? replace with 'the UI' ?

The preferred way is definitely to do completely without any references to a UI. Bindings are abstracted away from UIs as much as possible, so that UIs can evolve and change completely independent of bindings. So keeping that separation in tact as much as possible within the prosa docs would be most welcome!

Anything that needs to be explained about UIs is in general not specific to a single binding and thus should rather go to a generic place in openhab-docs!

**Comment by wborn** [comment]
Please don't unpin this issue @markus7017.

**Comment by Skinah** [comment]
Created a WIP here:
https://github.com/openhab/openhab-addons/pull/9439/

**Comment by Skinah** [comment]
Can anyone help out?

As an update: I found around 60% as a guess needed a change and I have probably only done half the bindings. Bindings from A to L still need to be checked plus the other addons that are not bindings.
