### ISSUE TITLE
[somfytahoma] When trying to control more than 10 devices at once, bridge returns error

### ISSUE THREAD

**Issue by georg138** [openhab/openhab-addons#8628]
The Tahoma gateway only accepts at most 10 commands. When sending additional commands, the following error message is logged:
2020-10-01 18:02:44.892 [WARN ] [nal.handler.SomfyTahomaBridgeHandler] - Apply command response: {"errorCode":"EXEC_QUEUE_FULL","error":"Execution queue is full on gateway: #       1223-6154-5758 (soft limit: 10)"}
the command will not be carried out by the Tahoma gateway. 

Currently, the openhab addon will not retry this command.
At my home, I have way more than 10 rollershutters and using action groups is no real solution. I'm currently implementing a fix to the addon which will retry failed commands after a delay.

**Comment by hinterreiter** [comment]
same problem here... 13 covers, only 10 are working.

**Comment by georg138** [comment]
I implemented a fix which I have been using locally for a while. It adds some options to the binding which allow to configure a number of retries and delay inbetween. 
As soon as I've got spare time I will make a pull request.

**Comment by georg138** [comment]
I created a PR: [https://github.com/openhab/openhab-addons/pull/10023](url)

**Comment by lolodomo** [comment]
PR was merged so this issue can be closed ?

**Comment by georg138** [comment]
PR to fix this issue was mergerd.
