### ISSUE TITLE
Telegram Binding and experimental-Rule creator for Paperui don't work [telegram]

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-addons#8632]
## Current Behavior

When choosing the telegram send message action in the experimental rule machine, it should let you define a message -> it doesn't. Also there are multiple telgram bot shown, that do not exsist. Also the "then" section has duplicates and missing config:

![image](https://user-images.githubusercontent.com/45922770/94901989-c95fbe80-0497-11eb-9d9c-cf717b51b1fd.png)
![image](https://user-images.githubusercontent.com/45922770/94902260-2bb8bf00-0498-11eb-95b5-6f7ea54c8d6f.png)
![image](https://user-images.githubusercontent.com/45922770/94902390-602c7b00-0498-11eb-96fe-19c22633bc31.png)

Remove duplicates and add missing sections.

## Steps to Reproduce (for Bugs)

1. Install Rule engine (experimental) addon
2. Install telegram binding
3. try to add rule to rule engine in perperui

## Your Environment
Raspberrypi 4 B+
hypriot os 1.12.3
docker: 19.0.3
openhab-docker 2.5.7

**Comment by bd8392** [comment]
Issue persists on openhab-docker 2.5.9

**Comment by Rossko57** [comment]
The PaperUI graphical rule editor is known to be incomplete in many aspects, and will not now be worked on any further.   Use alternative rules editors with OH 2.

**Comment by bd8392** [comment]
> Use alternative rules editors with OH 2.

Okay :-) which would be an alternative rule-editor?

**Comment by Rossko57** [comment]
You could consult the documentation
https://www.openhab.org/docs/configuration/editors.html
