### ISSUE TITLE
[fronius] did not work with new Fronius inverters

### ISSUE THREAD

**Issue by zysmo** [openhab/openhab-addons#8633]
I have a Fronius Symo Gen24 Plus inverter.
When trying to connect the bridge, I get the following error:

`13:42:04.852 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - 'fronius:bridge:6d8cb88d' changed from INITIALIZING to OFFLINE (COMMUNICATION_ERROR): hostname or ip is not reachable`

I think the problem causes the function for checking if host is reachable.
Because when I try to get the inverter by  curl, it works fine

`alex@heisenberg2:~$ curl http://fronius-pv1.intern/solar_api/v1/GetPowerFlowRealtimeData.fcgi
{
   "Body" : {
      "Data" : {
         "Inverters" : {
            "1" : {
....`

Maybe the java function **.isReachable**  in `FroniusBridgeHandler.java` does nor harmonize with the device?
I read somthing about this function uses a special port... Perhaps the inverter does not accept connection on this port.

**Comment by freiwerk** [comment]
Same here, also a with the new Symo Gen24. Can access the API from the inverter using the solar_api, but I get a communication error.

**Comment by jimtng** [comment]
@zysmo and @freiwerk which openhab version are you currently using? Could you a test jar file for me before I submit the fix as a PR? I can't test it myself because I don't have a Gen24.

**Comment by freiwerk** [comment]
I've used the latest stable OpenHAB 2.5 release from early October but I currently do not have physical or remote access to the installation with the Gen24 for the next few weeks to test the JAR file (and determine the exact OpenHAB version). @zysmo Could you run a test?

**Comment by zysmo** [comment]
I'm using openHAB 2.5.9 release.
Sure, I can test a jar file

**Comment by jimtng** [comment]
[org.openhab.binding.fronius-2.5.11-SNAPSHOT.jar.zip](https://github.com/openhab/openhab-addons/files/5582118/org.openhab.binding.fronius-2.5.11-SNAPSHOT.jar.zip)
Please try this jar file. It should work on any 2.5.x installation.

**Comment by zysmo** [comment]
It seems that it should work now. What did you change?

**Comment by jimtng** [comment]
I replaced isReachable() with HttpUtil.executeUrl(). I'll submit a PR to `main` and once that's merged, backport to `2.5.x`.
