### ISSUE TITLE
Projects are missing source folders when being imported as Maven project

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#8641]
With https://github.com/openhab/openhab-addons/issues/8451, the Eclipse specific files were removed from the repo and instead the user is expected to use the "import existing Maven project" feature in Eclipse.

I just tried this for the first time with the LametricTime binding and noticed that it is lacking the source folders
`src/3rdparty/java`, `src/3rdparty/test` and `src/main/feature` after the import. I assume the same problem exists for other bindings, most likely the `src/main/feature` is missing on all.

@Hilbrand & @wborn How can we address this?

**Comment by Hilbrand** [comment]
If I import the project as maven project it has no problem. Due to the pom.xml configuration these directories should be added to the build path in eclipse. (I did have a fresh eclipse install). So I don't know why it doesn't work for you. Does it make a difference when doing a maven update project (Alt-F5) on the project?
The feature was never a source path.

**Comment by wborn** [comment]
At first it also didn't work for me. But after installing the build-helper-maven-plugin in Eclipse and making sure its lifecycle was not ignored it worked.

Here is where you can install it:

![1](https://user-images.githubusercontent.com/12213581/94992252-fa6bec00-0588-11eb-8216-04ff23030ac5.png)

You can check if it is being ignored in the project properties of any project:

![2](https://user-images.githubusercontent.com/12213581/94992255-fcce4600-0588-11eb-849b-0e0e4520a027.png)

I had to unignore it by editing the mappings via "Open workspace lifecycle mappings metadata":

![3](https://user-images.githubusercontent.com/12213581/94992374-e07ed900-0589-11eb-9283-2bb9965ca8ca.png)

It would be nice this worked for everyone automatically. :-)

**Comment by kaikreuzer** [comment]
So I guess this should be added to the Oomph IDE setup then?

**Comment by wborn** [comment]
I haven't reinstalled the openHAB IDE myself for awhile so I don't know if it is already added.
Does it also get added for you using that plugin @Hilbrand and did you manually install it?

**Comment by wborn** [comment]
At first I thought it worked automatically for me... but I forgot to remove the hidden `.classpath` files where this config is stored. :wink:

**Comment by Hilbrand** [comment]
I checked with a eclipse (2020-09) I installed yesterday. So I guess this is installed by default in the recent versions of eclipse (or a plugin).
It seems to work out-of-the-box then, except for the complain about the lifecycle version of the spotless plugin (I guess this still needs to be updated in the our setup file each time the spotless plugin is updated or set to a wider range, although that might not work if I remember correctly when I tried that).

**Comment by kaikreuzer** [comment]
I did a new IDE install yesterday and I can see that the build-helper-plugin is set to ignore. This is the lifecycle-mapping-metadata.xml that has been created in my workspace:
```
<?xml version="1.0" encoding="UTF-8"?>
<lifecycleMappingMetadata>
  <pluginExecutions>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <versionRange>1.8</versionRange>
        <goals>
          <goal>add-source</goal>
          <goal>add-test-source</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
    <pluginExecution>
      <pluginExecutionFilter>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <versionRange>1.24.3</versionRange>
        <goals>
          <goal>check</goal>
        </goals>
      </pluginExecutionFilter>
      <action>
        <ignore />
      </action>
    </pluginExecution>
  </pluginExecutions>
</lifecycleMappingMetadata>
```
@Hilbrand Are you really sure that your's look different? I'd be interested in what the difference between our setups might be.

**Comment by kaikreuzer** [comment]
Btw, this is exactly what is [defined in our Oomph setup](https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup#L2382-L2416).

**Comment by wborn** [comment]
It makes sense to ignore to prevent errors when the plugin is not installed.

I had a look at the update site and feature ID and perhaps we can unignore it after adding an new requirement and repository to the setup file?

```xml
      <requirement
          name="org.sonatype.m2e.buildhelper.feature.feature.group"/>

      <repository
          url="https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-buildhelper/0.15.0/N/0.15.0.201207090124/"/>
```

**Comment by wborn** [comment]
I think it would also be better add those ignored plugin executions to POM files instead of the Oomph file. We already do this for many other executions and also use version ranges, see the [openhab-addons POM section](https://github.com/openhab/openhab-addons/blob/be7e9c9680d4725dcc3ea6b2eb02267b57f313a5/pom.xml#L421-L501) for this.

**Comment by Hilbrand** [comment]
I did a clean setup again. I have the same `lifecycle-mapping-metadata.xml` as shown above. I than imported just the `lametrictime` binding and it just sets all the paths. I have linux and installed eclipse `2020-09`.

When the import is finished it still complains about the spotless plugin in pom of the binding. When I then fix this by writing it to the eclipse configuration it overrides the `lifecycle-mapping-metadata.xml` file and only the spotless plugin remains afterwards.

Some other observation.  In `lifecycle-mapping-metadata.xml` for the `build-helper-maven-plugin` it says `versionRange` `1.8`. When I look up effective POM of the `lametrictime` `pom.xml` it says that plugin is version `3.0.0`. So I would expect that would explain why the mapping in the xml is not used as it's a different version.

**Comment by kaikreuzer** [comment]
Afair, this now works quite well, so I guess we can close this issue.
