### ISSUE TITLE
[mihome] - binding crashes when sid is not in read_ack message 

### ISSUE THREAD

**Issue by roieg** [openhab/openhab-addons#8656]
After upgrading to the latest mihome binding i noticed binding crashes (I have 3 mihome gateways at home)
Seems that the gateway sends read_ack message without sid (example below) and the binding does not deal with it correctly in **XiaomiBridgeHandler**

message received from gateway - {"cmd":"read_ack","data":"{\"error\":\"No sid\"}"}
Example : XiaomiBridgeHandler:197
private synchronized void defer(String sid, JsonObject message) {
       synchronized (retentionInbox) {
            **retentionInbox.remove(sid);**     -> null exception 
            retentionInbox.put(sid, message);
        }

There are at least 3 more cases I found that caused null exception if sid is null. 

## Your Environment

* binding version used: 2.5.9  (or latest)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (Windows 10):

**Comment by lsiepel** [comment]
Is this still an issue with 3.4.0? As i don't see any mihome PR, i guess it is still happening?
