### ISSUE TITLE
[nest] Add support for Smart Device Management (SDM) API

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#8664]
The current API used by the binding is based on the Works With Nest (WWN) API for which new users can no longer sign up (see [What's happening at Nest?](https://nest.com/whats-happening/)).

Recently a new Smart Device Management API has become available which again allows for controlling Nest devices, see:
* [Device Access](https://developers.google.com/nest/device-access/)
* [Smart Device Management (SDM) API](https://developers.google.com/nest/device-access/api/)

There is a non-refundable $5 registration fee for creating a developer account to gain access to this API.

See also the following community topics:
* [Google Nest Device Access Console now available](https://community.openhab.org/t/google-nest-device-access-console-now-available/105404?u=wborn)
* [Works With Nest - Deprecating on August 31, 2019](https://community.openhab.org/t/works-with-nest-deprecating-on-august-31-2019/73974?u=wborn)

I'll start implementing this SDM API in the existing binding so existing WWN API users can migrate over time.
The new SDM API may also not provide the same functionality.
Most likely the WWN API will be retired and can then be removed from the binding.

**Comment by Lovett1991** [comment]
Just seen your message on the forum. Any help required?

**Comment by wborn** [comment]
Hi! Do you have Doorbells or Displays? I don't have these so it will be difficult to test this functionality. :-)

I think I'll first refactor the existing binding and add some basic implementation and functionality and get that merged. That should get it merged quickly (less code to review) and allows for everyone to start using it and it will make it easier for others to collaborate using the usual PR process.

**Comment by Lovett1991** [comment]
I've only got the thermostat / protects. Ok no worries.

**Comment by wborn** [comment]
OK I've got those too, as well as some cameras.
But it is too bad the Protects aren't part of the new API and I also don't like that you can't updat the away/home state. :neutral_face: 
Let's hope they will still add this and the product owner decided to go for the most popular stuff first. :crossed_fingers:

**Comment by Lovett1991** [comment]
Yeah that is annoying, is that finalised or are they just gradually rolling stuff out on the new API as the protects would be handy to have.

Home/away state is annoying especially because you could do something cool like a baysian sensor rather than just rely on the gps. But I guess you could have a rule in OpenHab to just switch to ECO mode.

As you seem to be a big/regular contributor to OpenHab, thought I'd ask, how do you get started contributing? I've been using 2.4 for a while and figured I should probably start contributing to the code base.

**Comment by wborn** [comment]
Just like anything new, it's probably best to start small and learn/find your way around it. I first started with fixing bugs in bindings I used. After that I started adding enhancements to bindings I used. Then I created a binding from scratch and contributed to the core. Now that I know my way around everything, I'm confident enough to touch anything without severely breaking it. :-)

But I've been doing Java development for more than 10 years. The only challenges for me with openHAB were getting to know OSGi and learning the ESH/openHAB framework/domain.

**Comment by meingraham** [comment]
I agree it's best to start small, get it right and add incrementally. But they shut down old API new access over a year ago... and still have no equivalent. Ideally, they would continue to allow people to use the old... and when the new is ready and full featured, then cut off the old.

But, it is what it is... and I'm hopeful that the new will eventually surpass the old. Not only in terms of keeping capability the same (e.g., home/away), but also things like accessing temperature sensors through the API, making their schedule more customizable, adding a selectable radius geofence, etc. But now I'm just dreaming 😜

**Comment by syndicate0017** [comment]
@wborn 

No Nest Hub here, but I do have a doorbell and am happy to send any required info. I've already transitioned to the Google login and am using a Starling Hub in the meantime.

**Comment by pieterdevriesch** [comment]
I've got a Thermostat v3 and ready to test. Still on the old Nest login but there's no point anymore so I might as well convert it.

**Comment by Lovett1991** [comment]
@wborn ok, thanks for that. Yeah I need to have a poke in OH, I've been a java developer for over 7 years :)

**Comment by JeewanBahra** [comment]
I've got a thermostat and doorbell and happy to help 👍

**Comment by robnielsen** [comment]
> Hi! Do you have Doorbells or Displays? I don't have these so it will be difficult to test this functionality. :-)

I have both, and am looking forward to helping out.

**Comment by BobMiles** [comment]
Also having a Thermostat, 5 Protects, Hello Doorbell and a Camera. I'll be happy to test for you! All the best, Bob

**Comment by CorneNick** [comment]
I'm also having Thermostat, Protects & Hello Doorbell, happy to help!

**Comment by bulletprooffool** [comment]
This is great guys. 
I am happy to convert my existin gaccount over - the old one has been flakey anyway - but it would be nice if you could post a simple 'how to get going' guide.

Juist a 'visit xxz
register an abc abd request a token

Drop jar from y in z location
Manage via paperui

**Comment by randye007** [comment]
Thanks @wborn for the work on this!
Is the jar snapshot at a point we can test it using the new google SDM API? Thx.

**Comment by wborn** [comment]
Hello! The coming week I plan on spending a lot of time on this PR and if it all works out well I'll also update the JAR so it has the camera support. :slightly_smiling_face: :crossed_fingers:

**Comment by randye007** [comment]
That’s great! Thank-you! 👍

**Comment by techie66** [comment]
I've been testing the jar with OH3.0.0 I am using my own developer account and tokens. Everything was great until I restarted OH. Now I am getting a NullPointer Exception:
`2021-01-10 13:14:05.246 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NullPointerException: null
        at org.openhab.binding.nestdeviceaccess.internal.nesthelper.NestUtility.isAccessTokenExpired(NestUtility.java:128) ~[?:?]
        at org.openhab.binding.nestdeviceaccess.internal.nesthelper.NestUtility.getAccessToken(NestUtility.java:108) ~[?:?]
        at org.openhab.binding.nestdeviceaccess.internal.nesthelper.NestUtility.getDeviceInfo(NestUtility.java:171) ~[?:?]
        at org.openhab.binding.nestdeviceaccess.internal.thermostat.NestThermostat.getThermostatInfo(NestThermostat.java:414) ~[?:?]
        at org.openhab.binding.nestdeviceaccess.internal.thermostat.NestThermostatHandler.refreshChannels(NestThermostatHandler.java:148) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

I tried getting new authorization codes, but the error remains.

**Comment by bulletprooffool** [comment]
Yup - seems you have to redo the tokens every time you reboot.
Was wondering is this might be because we’re hard coding the tokens in a config file, rather than storing them as a property somewhere - meaning as the token updates each time, the stored and active token is the current one, rather than(after rebooting) being the one we started with?

It’s a real problem, if you do anything like maintenance reboots

**Comment by techie66** [comment]
I got it to work by updating new tokens, deleting the Thing and discovering it again. Looks like something is getting read from ephemeral storage and not getting restored on reboot.

**Comment by bulletprooffool** [comment]
Yup - it’s a known issue, a ballache, but it is what it is. Still grateful for the work that has been done On this.

**Comment by dschoepel** [comment]
I have 2 thermostats, 5 Cameras (Nest Cams, Drop Cams, Outdoor Cams), and 5 Nest Protects 2nd Gen.  Happy to be part of the group testing the binding. 

I also put together a guide (GitHub Wiki) to help folks get set up using the SDM API [Nest On OpenHAB - Step By Step Guide](https://community.openhab.org/t/google-nest-device-access-console-now-available/105404/189?u=dschoepel)

**Comment by wborn** [comment]
Hello everyone! I've finished my work on the PR that adds SDM support to the Nest Binding and marked it as ready for review. :slightly_smiling_face:
If you want to help with testing/reviewing, there are links to JARs and the updated documentation in the [initial PR comment](https://github.com/openhab/openhab-addons/pull/8947).
