### ISSUE TITLE
[mihome] Add support for Aqara d1 wall switch 

### ISSUE THREAD

**Issue by SavvasR6** [openhab/openhab-addons#8688]
## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by lolodomo** [comment]
@marcelrv : do you know if this was requested to be supported in the miio binding ?

**Comment by lsiepel** [comment]
Is t this a duplicate of https://github.com/openhab/openhab-addons/issues/8251 ?
