### ISSUE TITLE
[omnikinverter] The binding is missing shutdown code

### ISSUE THREAD

**Issue by ppieczul** [openhab/openhab-addons#8703]
Each thing created with the Omnik Inverter binding creates a periodic data pull thread that remains forever, even after thing is deleted.

## Expected Behavior
Binding should clean up scheduled executor on shutdown. No more polling the network.

## Current Behavior
Now every 10 seconds there is an attempt to read the device even when things are removed.

## Possible Solution
Implement shutdown.

## Steps to Reproduce (for Bugs)
Create thing, enable debug logs, remove thing, observe logs continue.

## Context
I am trying to use this binding with my inverter :)

## Your Environment

* Version used: 2.5.9 release

**Comment by hansbogert** [comment]
late to the party, thanks for fixing this. I had no idea of this dispose method. In fact, the documentation is pretty sparse on making robust bindings, or did I just not look at the documentation correctly when I made the binding?
