### ISSUE TITLE
[tplinksmarthome] Add support for TP-Link KL430 Strip Light

### ISSUE THREAD

**Issue by irishismyname** [openhab/openhab-addons#8709]
There doesn't appear to be support for the Kasa KL430 strip light. I captured the following JSON between the Kasa app on an Android phone and a KL430 strip light with a KL430E extension. I removed what I think was the phone's id and replaced it with `<id>` below. The format of `<id>` was `<32-bits>-<16-bits>-<16-bits>-<16-bits>-<48-bits>`. I also replaced the real ssid with `<ssid>` below.

### Request
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"transition":0}},"context":{"source":"<id>"}}`
### Response 
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"mode":"normal","groups":[[0,31,0,0,100,4970]],"err_code":0}}}`

### Request
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":0,"transition":0}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":0,"dft_on_state":{"mode":"normal","groups":[[0,31,0,0,100,4970]]},"err_code":0}}}`

### Request
`{"smartlife.iot.lightStrip":{"set_light_state":{"brightness":73,"on_off":1,"transition":150}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"mode":"normal","groups":[[0,31,0,0,73,4970]],"err_code":0}}}`

### Request
`{"smartlife.iot.lightStrip":{"set_light_state":{"color_temp":5275,"hue":0,"on_off":1,"saturation":0,"transition":150}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"mode":"normal","groups":[[0,31,0,0,73,5275]],"err_code":0}}}`

### Request
`{"smartlife.iot.lightStrip":{"set_light_state":{"color_temp":0,"hue":115,"on_off":1,"saturation":75,"transition":150}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"mode":"normal","groups":[[0,31,115,75,73,0]],"err_code":0}}}`

### Request
`{"smartlife.iot.lightStrip":{"apply_preset":{"index":1}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.lightStrip":{"apply_preset":{"err_code":0}}}`

### Request
`{"smartlife.iot.common.emeter":{"get_daystat":{"month":9,"year":2020}},"context":{"source":"<id>"}}`
### Response
`{"smartlife.iot.common.emeter":{"get_daystat":{"day_list":[{"year":2020,"month":9,"day":14,"energy_wh":141},{"year":2020,"month":9,"day":15,"energy_wh":257},{"year":2020,"month":9,"day":16,"energy_wh":264},{"year":2020,"month":9,"day":17,"energy_wh":283},{"year":2020,"month":9,"day":18,"energy_wh":240},{"year":2020,"month":9,"day":30,"energy_wh":1}],"err_code":0}}}`

### Request 1
`{"smartlife.iot.common.softaponboarding":{"get_stainfo":{}},"context":{"source":"<id>"}}`
### Response 1
`{"smartlife.iot.common.softaponboarding":{"get_stainfo":{"ssid":"<ssid>","key_type":3,"rssi":-50,"err_code":0}}}`
### Request 2
`{"smartlife.iot.common.timesetting":{"get_timezone":{}},"context":{"source":"<id>"}}`
### Response 2
`{"smartlife.iot.common.timesetting":{"get_timezone":{"index":18,"err_code":0}}}`
### Request 3
`{"smartlife.iot.common.timesetting":{"get_time":{}},"context":{"source":"<id>"}}`
### Response 3
`{"smartlife.iot.common.timesetting":{"get_time":{"year":2020,"month":10,"mday":9,"hour":12,"min":0,"sec":56,"err_code":0}}}`

### Request 
`{"smartlife.iot.lighting_effect":{"set_lighting_effect":{"custom":0,"direction":4,"duration":0,"enable":1,"expansion_strategy":1,"id":"xqUxDhbAhNLqulcuRMyPBmVGyTOyEMEu","name":"Aurora","repeat_times":0,"segments":[0],"sequence":[[120,100,100],[240,100,100],[260,100,100],[280,100,100]],"spread":7,"transition":1500,"type":"sequence"}},"context":{"source":"<id>"}}`
### Response 
`{"smartlife.iot.lighting_effect":{"set_lighting_effect":{"err_code":0}}}`

**Comment by droidrzrlover** [comment]
I second adding this to OpenHAB.

**Comment by Hilbrand** [comment]
On the forum there was also a request containing json commands and responses. To get everything in one place I've put it here.

```
{"system":{"get_sysinfo":{"sw_ver":"1.0.5 Build 210616 Rel.122727","hw_ver":"1.0","model":"KL400L5(US)","deviceId":"deviceIDhere","oemId":"oemidhere","hwId":"hwIdhere","rssi":-54,"latitude_i":548594,"longitude_i":-787978,"alias":"Led Strip","status":"new","description":"Kasa Smart Light Strip, Multicolor","mic_type":"IOT.SMARTBULB","mic_mac":"11:11:11:11:11:12","dev_state":"normal","is_factory":false,"disco_ver":"1.0","ctrl_protocols":{"name":"Linkie","version":"1.0"},"active_mode":"none","is_dimmable":1,"is_color":1,"is_variable_color_temp":0,"LEF":0,"length":16,"light_state":{"on_off":0,"dft_on_state":{"mode":"normal","hue":230,"saturation":97,"color_temp":0,"brightness":7}},"lighting_effect_state":{"enable":0,"name":"Ocean","custom":0,"id":"oJjUMosgEMrdumfPANKbkFmBcAdEQsPy","brightness":7},"preferred_state":[],"err_code":0}}}
{"smartlife.iot.lightStrip":{"get_light_state":{"on_off":0,"dft_on_state":{"mode":"normal","groups":[[0,15,230,97,7,0]]},"length":16,"transition":0,"err_code":0}}}
{"smartlife.iot.lighting_effect":{"get_lighting_effect":{}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lighting_effect":{"get_lighting_effect":{"custom":0,"id":"oJjUMosgEMrdumfPANKbkFmBcAdEQsPy","brightness":7,"name":"Ocean","segments":[0],"expansion_strategy":1,"enable":0,"type":"sequence","duration":0,"transition":2000,"direction":3,"spread":16,"repeat_times":0,"sequence":[[198,84,30],[198,70,30],[198,10,30]],"err_code":0}}}
{"smartlife.iot.lightStrip":{"get_all_presets":{}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lightStrip":{"get_all_presets":{"preferred_state":[],"err_code":0}}}
{"smartlife.iot.lightStrip":{"set_light_state":{"ignore_default":0,"on_off":1,"transition":0}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":1,"mode":"normal","groups":[[0,15,230,97,7,0]],"err_code":0}}}
{"smartlife.iot.lightStrip":{"get_light_state":{}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lightStrip":{"get_light_state":{"on_off":1,"mode":"normal","groups":[[0,15,230,97,7,0]],"length":16,"transition":0,"err_code":0}}}
{"smartlife.iot.lighting_effect":{"get_lighting_effect":{}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lighting_effect":{"get_lighting_effect":{"custom":0,"id":"oJjUMosgEMrdumfPANKbkFmBcAdEQsPy","brightness":7,"name":"Ocean","segments":[0],"expansion_strategy":1,"enable":0,"type":"sequence","duration":0,"transition":2000,"direction":3,"spread":16,"repeat_times":0,"sequence":[[198,84,30],[198,70,30],[198,10,30]],"err_code":0}}}
{"smartlife.iot.lightStrip":{"set_light_state":{"ignore_default":0,"on_off":0,"transition":0}},"context":{"source":"46a4d58b-6279-432c-ae23-e115c2db8354"}}
{"smartlife.iot.lightStrip":{"set_light_state":{"on_off":0,"dft_on_state":{"mode":"normal","groups":[[0,15,356,100,20,0]]},"err_code":0}}}
```

source: https://community.openhab.org/t/new-tp-link-smart-home-binding-with-bulb-plug-and-switch-support/34233/169

**Comment by iammenotyou** [comment]
Using the python communication script from [https://github.com/softScheck/tplink-smartplug](https://github.com/softScheck/tplink-smartplug) I was able to test/reproduce local control functionality.

1. My observation is that the color is controlled by hue, saturation and temperature.
2. The "source" is required, however it will accept any in the proper format.   
3. All LEDs are controlled by the single command

I was able to send the following commands successfully:

Turn on
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"ignore_default":0,"on_off":1,"transition":0}},"context":{"source":"12a4b56c-7654-321d-ab12-ec34c5de6789"}}'`

Set red
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"brightness":73,"on_off":1,"transition":150}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

Set blue
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"color_temp":0,"hue":238,"ignore_default":1,"on_off":1,"saturation":68,"transition":150}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

Set red
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"brightness":73,"on_off":1,"transition":150}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

Set brightness to 15%
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"brightness":53,"on_off":1,"transition":150}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

Turn off
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lightStrip":{"set_light_state":{"ignore_default":0,"on_off":0,"transition":0}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

Set theme Aurora, CandyCane, Lightning
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lighting_effect":{"set_lighting_effect":{"custom":0,"direction":4,"duration":0,"enable":1,"expansion_strategy":1,"id":"xqUxDhbAhNLqulcuRMyPBmVGyTOyEMEu","name":"Aurora","repeat_times":0,"segments":[0],"sequence":[[120,100,100],[240,100,100],[260,100,100],[280,100,100]],"spread":7,"transition":1500,"type":"sequence"}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lighting_effect":{"set_lighting_effect":{"custom":0,"direction":1,"duration":700,"enable":1,"expansion_strategy":1,"id":"HCOttllMkNffeHjEOLEgrFJjbzQHoxEJ","name":"Candy Cane","repeat_times":0,"segments":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],"sequence":[[0,0,100],[0,0,100],[360,81,100],[0,0,100],[0,0,100],[360,81,100],[360,81,100],[0,0,100],[0,0,100],[360,81,100],[360,81,100],[360,81,100],[360,81,100],[0,0,100],[0,0,100],[360,81,100]],"spread":0,"transition":500,"type":"sequence"}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`
`./tplink_smartplug.py -t -192.168.0.10 -j '{"smartlife.iot.lighting_effect":{"set_lighting_effect":{"backgrounds":[[200,100,100],[200,50,10],[210,10,50],[240,10,0]],"brightness_range":[90,100],"custom":0,"duration":0,"enable":1,"expansion_strategy":1,"fadeoff":150,"hue_range":[240,240],"id":"ojqpUUxdGHoIugGPknrUcRoyJiItsjuE","init_states":[[240,30,100]],"name":"Lightning","random_seed":600,"saturation_range":[10,11],"segments":[7,20,23,32,34,35,49,65,66,74,80],"transition":50,"type":"random"}},"context":{"source":"12a4c56c-7654-321d-ab12-ec34c5de6789"}}'`

**Comment by Hilbrand** [comment]
I've added primarily support for the KL430 in the beta version available via the [community marketplace](https://community.openhab.org/t/tp-linksmarthome-beta/130407) .
