### ISSUE TITLE
Amazon echo Control Binding leads to error 500 [amazon echo control]

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-addons#8762]
I once had the amazon echo control binding installed. I had it removed and now when I try to install it back, it leads to error 500 in paperui (not resolvble by deleting cache)

* Version used: (e.g., openHAB and add-on versions)
OpenHab Docker 2.5.9
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
Hypriot 1.12.3

**Comment by bd8392** [comment]
Okay nevermind...it resolved by itself...absolutely no idea what was causing it....
