### ISSUE TITLE
[shelly] RGBW2 white mode - no status update via Coap

### ISSUE THREAD

**Issue by ijasan** [openhab/openhab-addons#8766]
Device: RGBW2 white mode
Firmware: 20200827-070232/v1.8.3@4a8bc427
Dev build: 2.5.9.202009051712

The status updates via Coap seem not to be processed. The status update changes only every 60 seconds via REST.

[RGBW2_White.log](https://github.com/openhab/openhab-addons/files/5390784/RGBW2_White.log)

[RGBW2_White_Events.log](https://github.com/openhab/openhab-addons/files/5390785/RGBW2_White_Events.log)

**Comment by markus7017** [comment]
2 issues have been identified
- "Unable to update input, index is out of range (1/1)" -&gt; the RGBW2 has 4 light channels, but only 1 input
- In white mode the wrong group names are used for the channel updates (white instead of channel&lt;n&gt;)

```
Coap Updates
Channel white#brightness$Switch updated with ON
Channel white#brightness$Value updated with 50 %
```
vs.
```
REST updates
Channel channel1#brightness$Switch updated with ON
Channel channel1#brightness$Value updated with 50 %
```

**Comment by markus7017** [comment]
@ijasan please verify with the latest DEV build


---

Latest **DEV** build: [2.5.11](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true) - [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)  -

**Comment by ijasan** [comment]
Confirmed as working with DEV build 2.5.11.202012102236

**Comment by markus7017** [comment]
was included in last PR
