### ISSUE TITLE
[denonmarantz] More than 4 devices leads to uncontrollable ones

### ISSUE THREAD

**Issue by mdsolutech** [openhab/openhab-addons#8769]
## Expected Behavior
Be able to control any number of device

## Current Behavior
When more than 4 devices are bound, some of them are in "unknown" state and are not controllable.
If one "online" device is disabled, one in the "unknown" state automatically passes in "online".
Not sure what log can be helpful. "openhab.log" displays nothing.
Note: The 4 devices limit is an empiric value, based on the fact I did not managed to get more than 4 devices online altogether. One day, the limit was 3, but without any actions, the next day it goes back to 4 "online" devices.

## Possible Solution
No idea.

## Steps to Reproduce (for Bugs)
1. Declare more than 4 Marantz things
2. Try controlling all off them
3. Check the things statuses

## Context
I am trying to control all the marantz device of the house. I happen to have 7 of them, and more to come.
Right now, I cannot control half of them, I have to disable another before doing so.

## Your Environment
OpenHab 2.4.0, running in docker. (image: "openhab/openhab:2.4.0")

Please let me know about any information you might require. Just be kind enough to provide information about where to get them, as I am an OpenHab new comer and I do not know all of its subtleties.

Thanks a lot to all who might pass by to give a hand !

**Comment by J-N-K** [comment]
This looks like it is solved with #9511. Probably threads were exhausted. Could you check?
