### ISSUE TITLE
[tplink] Add support for Archer VR2800

### ISSUE THREAD

**Issue by Daniel10001** [openhab/openhab-addons#8784]
TP-Link Router support  - Archer VR2800

Can we please add TP-Link Router  - Archer VR2800 support to the TP-LINK binding?

Your Environment

Version used: OpenHab 3.0.0-SNAPSHOT
Environment name and version Chrome 76, Java 11, 
Operating System and version Windows 10

**Comment by Hilbrand** [comment]
Routers are not part of the TP-Link smarthome product range and have a different app. So it requires a complete different implementation. Therefor it probably should not be added to the tplinksmarthome binding, but get it's own binding.

However just asking for it to be added without any additional information is basically useless. Only when a developer who has the device itself will be interested it might have a chance to be added. So if no additional information is provided this issue doesn't have any added value and can be closed.
