### ISSUE TITLE
[MQTT] Add "Allowed States" for MQTT Switch and Contact Channel

### ISSUE THREAD

**Issue by gnilebein** [openhab/openhab-addons#8789]
## Your Environment

* Version used: openHAB 2.5.9 (Docker)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Chrome
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows

It would be helpful if the switch and contact channel had an "Allowed States" setting available. 

My Ikea button sends the states for ON / OFF (State ON / OFF) and Long Press (brightness_move_down / brightness_move_up) in the same topic (zigbee2mqtt).

I have two items with the same topic for ON / OFF and the dimmer setting. But one of the items always throws an error during an update.

> 13: 34: 51.926 [WARN] [hab.binding.mqtt.generic.ChannelState] - Command 'brightness_move_up' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.brightness_move_up

This error could be prevented.

**Comment by jochen314** [comment]
I am puzzeled.
Please give you complete configuration.

Could you use a `Percentage Value`for this?
Use an `Incoming Value Transformation` (a map) to transform the values send by the device to the values `ON`, `OFF`, `INCREASE`, `DECREASE`

**Comment by gnilebein** [comment]
My Configuration:
Short press Channel:
![Short press Item](https://i.ibb.co/q19L85t/2020-10-18-14-48-09-Paper-UI.png)

Long press Channel:
![Long Press Item](https://i.ibb.co/yFGQWFz/2020-10-18-14-48-27-Paper-UI.png)

Example value for normal press:
>{
>	"action": "on",
>	"click": "on",
>	"device": {
>		"applicationVersion": 33,
>		"dateCode": "20190723",
>		"friendlyName": "TRADFRI-E1743-Kueche",
>		"hardwareVersion": 1,
>		"ieeeAddr": "0x842e14fffe7ddf84",
>		"manufacturerID": 4476,
>		"manufacturerName": "IKEA of Sweden",
>		"model": "E1743",
>		"networkAddress": 20141,
>		"powerSource": "Battery",
>		"softwareBuildID": "2.2.010",
>		"stackVersion": 98,
>		"type": "EndDevice",
>		"zclVersion": 3
>	},
>	"last_seen": "2020-10-18T12:12:14+00:00",
>	"linkquality": 234,
>	"update_available": false
>}

Example value for Long Press:
>{
>	"action": "brightness_move_down",
>	"click": "brightness_move_down",
>	"device": {
>		"applicationVersion": 33,
>		"dateCode": "20190723",
>		"friendlyName": "TRADFRI-E1743-Kueche",
>		"hardwareVersion": 1,
>		"ieeeAddr": "0x842e14fffe7ddf84",
>		"manufacturerID": 4476,
>		"manufacturerName": "IKEA of Sweden",
>		"model": "E1743",
>		"networkAddress": 20141,
>		"powerSource": "Battery",
>		"softwareBuildID": "2.2.010",
>		"stackVersion": 98,
>		"type": "EndDevice",
>		"zclVersion": 3
>	},
>	"last_seen": "2020-10-18T12:12:14+00:00",
>	"linkquality": 234,
>	"update_available": false
>}

As you can see, the transformation is already in use to extract the value out of the JSON String. I don't want to use the button as a dimmer, but my goal is to control two different switch items (one with short press and another with long press).

**Comment by jochen314** [comment]
OK,

If you map an incomming vlaue to `null`, then it will be ignored by the channel.

**Comment by gnilebein** [comment]
I tried null, NULL and an empty value. But it doesn't work.

> 17:23:42.483 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Command 'null' not supported by type 'OpenCloseValue': No enum constant org.eclipse.smarthome.core.library.types.OpenClosedType.null

> 17:24:20.087 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Command '' not supported by type 'OpenCloseValue': No enum constant org.eclipse.smarthome.core.library.types.OpenClosedType.

> 17:23:12.333 [WARN ] [hab.binding.mqtt.generic.ChannelState] - Command 'NULL' not supported by type 'OpenCloseValue': No enum constant org.eclipse.smarthome.core.library.types.OpenClosedType.NULL

**Comment by jochen314** [comment]
Sorry, I was not clear in my saying:

Use the following as Incomming Value Transformations:

```
JSONPATH:$.action∩REGEX:.*(on|off).*
```
and
```
JSONPATH:$.action∩REGEX:.*(brightness_move_up|brightness_move_down).*
```
Note the special character `∩` to chain transformations.
The `Regex` transformation will return `null` (not any string, but the null-value) for any value, not explicitly mentioned. Then these messages will be ignored.

**Comment by gnilebein** [comment]
Thanks, This works fine.
