### ISSUE TITLE
[rrd4j] "Tried to set invalid state" errors when restoring values on startup

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-addons#8806]
I see the following in openhab.log:

```
2020-10-14 16:59:40.497 [ERROR] [org.openhab.core.items.GenericItem  ] - Tried to set invalid state 0.0 (DecimalType) on item bathFans of type SwitchItem, ignoring it
```

The .items file is similar to:

```
Group:Switch:OR(ON, OFF) bathFans    "All Bath Fans [%d are on]" (all)
Switch mMainBathFan   (bathFans) {channel=""}
Switch sMasterBathFan (bathFans) {channel=""}
Switch sBathFan       (bathFans) {channel=""}
Switch bBathFan       (bathFans) {channel=""}
```

**Comment by wborn** [comment]
It seems when rrd4j restores values the precision gets lost causing #8798 and it has other issues as well.

When I use the demo setup it also cannot restore the [Heating](https://github.com/openhab/openhab-distro/blob/0445facdcb7dbb6fe425b0c636d26eb1d0fd4668/features/distro-resources/src/main/resources/items/demo.items#L24)  item:

`[ERROR] [org.openhab.core.items.GenericItem   ] - Tried to set invalid state 1.0 (DecimalType) on item Heating of type SwitchItem, ignoring it`

**Comment by kaikreuzer** [comment]
I have found a few flaws in rrd4j and am working on fixing it - stay tuned.

**Comment by kaikreuzer** [comment]
Here you go: https://github.com/openhab/openhab-addons/pull/8815
