### ISSUE TITLE
Why are the units attached to the Shelly Plug S with the channels for power (accumulatedWatts) and consumption (accumulatedTotal)?

### ISSUE THREAD

**Issue by DiKaY1969** [openhab/openhab-addons#8828]
Why are the units attached to the Shelly Plug S with the channels for power (accumulatedWatts) and consumption (accumulatedTotal), which is bad when calculating and has to be removed? The user can add the units himself at any time if he wants to. Can't you omit this like it is with many other devices from other manufacturers? I assume that it is the same with the other Shellys ...

**Comment by hmerk** [comment]
This is not a bug, it is a feature. Since Units Of Measurement (UOM) was introduced into openHAB, bindings should make use of it, that‘s what the Shelly binding does.
If you see other bindings/devices not using UOM, the might have been developed before introduction.

**Comment by DiKaY1969** [comment]
Hello and thank you for the information.  Unfortunately, I didn't know that this was a standard.  Unfortunately, all of my devices do not have a UOM and so I concluded that this was a bug.SorryDierkAm 22.10.2020 22:23 schrieb Hans-Jörg Merk <notifications@github.com>:

This is not a bug, it is a feature. Since Units Of Measurement (UOM) was introduced into openHAB, bindings should make use of it, that‘s what the Shelly binding does.

If you see other bindings/devices not using UOM, the might have been developed before introduction.

**Comment by wborn** [comment]
The units are optional so you can also define your items using only `Number`  and not specify the unit. Then you won't need to do conversions.

Another way is to specify the unit in rules like the example below, so you don't need to do conversions, e.g.:

```php
if (TemperatureItem.state >= 20|°C) {
    // insert code here
}
```

There's also a [community thread](https://community.openhab.org/t/i-gave-up-on-oh-2-3-unit-of-measure-um/52273?u=wborn) on this and https://github.com/openhab/openhab-docs/issues/782 to improve the documentation how to easily deal with it.
