### ISSUE TITLE
RRD4J and charts no more working in OH3 for items of  type Number with a dimension

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8856]
I find no rrd files created for items of type Number with a dimension.
A file is present for Items of type Number.

I have no chart working but I imagine this is a consequence of this problem.

I did not set any file rrd4j.cfg.

Here is the content of my rrd4j.persist file:
```
// persistence strategies have a name and a definition and are referred to in the "Items" section
Strategies {
	// for rrd charts, we need a cron strategy
	everyMinute : "0 * * * * ?"
}

Items {
	GTemperature*, GHumidite*, GSuiviConsoElec* : strategy = everyChange, everyMinute, restoreOnStartup
	GVirtualData*, GParametres* : strategy = everyChange, restoreOnStartup
}
```

**Comment by JueBag** [comment]
Check this [merged PR](https://github.com/openhab/openhab-addons/pull/8815) , it might be solved in this one.

**Comment by lolodomo** [comment]
Unfortunately not because I am runnign snapshot 1983 built yesterday.

**Comment by JueBag** [comment]
OK. Now there are TRACE loggings that should print which default Database is used for each item. Could you check for those?
There should be a line from thiis
`logger.trace("Using rrd definition '{}' for item '{}'.", useRdc, itemName);`
or another line stating that the item was not in the registry.

**Comment by lolodomo** [comment]
OK, I got it:
```
08:53:01.690 [TRACE] [rd4j.internal.RRD4jPersistenceService] - Ignoring item 'OWMHumiditeExt' since its type Number:Dimensionless is not supported
08:53:01.697 [TRACE] [rd4j.internal.RRD4jPersistenceService] - Ignoring item 'OWMTemperatureExt' since its type Number:Temperature is not supported
```
Why is it no more supported ? It is supported in OH2.

**Comment by lolodomo** [comment]
I am running snapshot 1983.
```
bundle:list | grep ersis
 82 x Active x  80 x 2.16.0.v20190528-0725   x EMF XML/XMI Persistence
169 x Active x  80 x 3.0.0.202010220309      x openHAB Core :: Bundles :: Model Persistence
170 x Active x  80 x 3.0.0.202010220309      x openHAB Core :: Bundles :: Model Persistence IDE
171 x Active x  80 x 3.0.0.202010220313      x openHAB Core :: Bundles :: Model Persistence Runtime
184 x Active x  80 x 3.0.0.202010220300      x openHAB Core :: Bundles :: Persistence
214 x Active x  80 x 3.0.0.202010240354      x openHAB Add-ons :: Bundles :: Persistence Service :: RRD4j
```

**Comment by lolodomo** [comment]
@kaikreuzer : I see you are the one who broke this compatibility with your PR #8815 . Can you please help to restore the compatibility for Number with dimension ?

**Comment by kaikreuzer** [comment]
Mea culpa - should be fixed with https://github.com/openhab/openhab-addons/pull/8866.
