### ISSUE TITLE
[TR-064 Binding] configuration for fritzbox-root device not stored properly

### ISSUE THREAD

**Issue by jgantenberg** [openhab/openhab-addons#8864]
I changed from version 1 binding to the test version of the fritzboxtr064 binding. I managed to set it up I receive valid values for example from the WAN-sub-device. I set it up via paper ui and filled in proper values for the root device for hostname, user, password etc. Also for tam index and the number of days for incoming and outgoing calls. 

## Expected Behavior
the filled in hostname should be used for communication with the fritzbox.
I also expect additional things to be automatically created corresponding to the configuration settings, for example a ringing indicator or missed calls thing.

## Current Behavior
The configuration for hostname is stored but the name fritz.box has to be resolvable. Otherwise the binding won't start complaining fritz.box can't be resolved.
In the section for the additional values none of the values is stored and I don't see additional things for incoming calls etc. 

## Steps to Reproduce (for Bugs)

1. setup new root device
2. reopen configuration
3. search for things

## Your Environment

* Version used: openHAB 2.5.9, org.openhab.binding.fritzboxtr064-2.5.6-SNAPSHOT.jar
* Fritzbox 6591 cable, 7.13
* ubuntu focal x86
* OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)

**Comment by kaikreuzer** [comment]
Sorry, but there isn't such a binding yet in the distro - it is still an open PR at https://github.com/openhab/openhab-addons/pull/8523. If you are testing that already, please directly provide review comments on that PR.
