### ISSUE TITLE
[miele] Things via .things broken for ZigBee protocol devices

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#8877]
https://github.com/openhab/openhab2-addons/commit/4c6ad1efef157735fec858f85e549464e36b9727 breaks the Miele binding for Zigbee devices defined via a .things file. @MartinLepsy  are you still around?

**Comment by J-N-K** [comment]
What do you mean by "breaks"? What is in the log? Which version of the binding? When did it last work?
