### ISSUE TITLE
[miio] Mi IO Binding - zhimi.airpurifier.mc2 unknown device

### ISSUE THREAD

**Issue by Dude88** [openhab/openhab-addons#8886]
Hi,

added the miio Binding an d connceted to my Account.
added my Air Purifier and get following log entry:

2020-10-27 22:36:02.650 [INFO ] [internal.handler.MiIoAbstractHandler] - Mi Device model zhimi.airpurifier.mc2 identified as: Unknown Mi IO Device (unknown). Does not match thingtype miio:generic. Changing thingtype to miio:unsupported

If I am right zhimi.airpurifier.mc2 should be supported?

any idea?

Working with 
Openhab version:   2.5.6
miio version:           2.5.6

**Comment by marcelrv** [comment]
I'm not sure if it was already available in your version.
Can you pls pull the snapshot version of the binding or take the json file for your device and save it locally
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.miio/src/main/resources/database/zhimi.airpurifier.m1.json

**Comment by marcelrv** [comment]
Closing as this is in snapshot and no response from submitter
