### ISSUE TITLE
[amazonechocontrol] Amazon host name should be able to be selected

### ISSUE THREAD

**Issue by ab3be6** [openhab/openhab-addons#8908]
Current binding configuration is not able to change or select the Amazon host name (e.g. alexa.amazon.com or alexa.amazon.co.jp).
it may be defined as "https://alexa.amazon.com" in the source code Connection.java?

I would like the binding to be added a feature to select the host name.
The user can find own host name in the Alexa application (e.g. Android app). so the host name is a string is OK.

**Comment by J-N-K** [comment]
What would be the benefit of that?

**Comment by ab3be6** [comment]
> What would be the benefit of that?

Dear J-N-K,
Thank you for your reply.
If this feature is applied, Alexa users who live in Japan and so on(not Amazon.com users) can connect this binding to their account.

**Comment by J-N-K** [comment]
Is that really necessary? My account is with `amazon.de` and it works perfectly the way it is now.

**Comment by ab3be6** [comment]
Thank you for your comment.
I checked I can connect to my account again, I have been able to connect it!
As you said, even if I have a jp account I can connect with the binding.
So this issue can be closed, thank you so much for your answer.
