### ISSUE TITLE
[deconz] Definition of trigger channels

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8910]
While I was searching for trigger channels in existing bindings, I noticed that all bindings are defining such channel with `trigger` as kink, like `<kind>trigger</kind>`, except the Deconz binding which uses `Trigger`: `<kind>Trigger</kind>`
Is the case important ?
If it is, there is probably an error in the Deconz binding.

**Comment by cweitkamp** [comment]
The `ChannelKind` is an enum and the tag `<kind>` will be parsed with ignored case. Thus it does not matter. But feel free to change it to streamline `ChannelType` definitions.

See
https://github.com/openhab/openhab-core/blob/5683cc247236f9424c17dce2b21938bc27069720/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/type/ChannelKind.java#L42-L46

**Comment by lolodomo** [comment]
Ok, thank you for the answer.
