### ISSUE TITLE
[tacmi] Unable to change numeric values in Schema API

### ISSUE THREAD

**Issue by woklei** [openhab/openhab-addons#8927]
Hello, 

In my Sitemap, I have a Setpoint linked to a Number item which is connected to a channel of type Number:Temperature in the Schema API. I succeeded in showing numbers and states from my CMI. Also, I can change status values in on/off/auto switches. However, I cannot change number values.

## Expected Behavior
When changing the value in OpenHab, I expect the value to be changed in CMI, as well.

## Current Behavior
The value changes in OpenHab only until the next refresh and then goes back to the old value.
The log says:

2020-11-01 07:52:24.782 [DEBUG] [i.internal.schema.TACmiSchemaHandler] - Got command for unhandled type NUMERIC_FORM channel tacmi:cmiSchema:2d23e725:HzgBivPkt: -4.0 �C

## Possible Solution
NUMERIC_FORM seems to be missing from TACmiSchemaHandler.handleCommand

## Environment
OpenHab 2.5.9 Release Build

**Comment by marvkis** [comment]
should also be fixed by #9047

**Comment by woklei** [comment]
Just looked at the PR. Yes, that should be it. I will be happynto test it when it is released as an update.

Thank you for fixing that issue and for investing the time to create this binding. This is really helpful.

(I was trying to add the NUMERIC_FORM block myself but I am having a hard time convincing Eclipse to build the addon. Somehow, I do not get all dependencies resolved...)

**Comment by marvkis** [comment]
I've compiled a version against 2.5.10 and uploaded it here: https://github.com/marvkis/openhab-addons-dist/raw/master/org.openhab.binding.tacmi-2.5.10-SNAPSHOT.jar - you can give it a try...

**Comment by woklei** [comment]
I have tested it successfully. The value was changed in the CMI now. Thank you very much.
