### ISSUE TITLE
LIFX :  massive # of " NullPointerException while reading data for the light" 

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#8932]
I just did an upgrade to 3.x, and I noticed a *massive* amount of 

[org.openhab.binding.lifx.internal.util.LifxSelectorUtil     ] - NullPointerException while reading data for the light (D0:73:D5:01:XX:XX) : null

entries in the log (with LIFX binding put at the DEBUG level). These originate at line https://github.com/openhab/openhab-addons/blob/03d77fb81bf83906912e7e3910f3b61c38b7cc6a/bundles/org.openhab.binding.lifx/src/main/java/org/openhab/binding/lifx/internal/util/LifxSelectorUtil.java#L172

@wborn Is this normal? 

ps. It has been literally *years* since I have looked at the LIFX binding's code, so excuse me if this would be a silly question

**Comment by wborn** [comment]
Yes I can improve the exception handling a bit for that. Does it work properly besides those NPEs in the logging?
