### ISSUE TITLE
[opensprinkler] Offline detection does not work reliably

### ISSUE THREAD

**Issue by eikowagenknecht** [openhab/openhab-addons#8942]
## Your Environment
* Version used: openHAB, current version 2.5.10
* OpenSprinkler on another Raspberry Pi (3b)

4 Things in openHAB:
- OpenSprinkler HTTP Interface
- Station 1
- Station 2
- Station 3

## Expected Behavior
When the OpenSprinkler is offline (e.g. network cable on the Raspberry is pulled where OpenSprinkler is installed), openHAB should reflect this correctly in Things status (after a while).

## Current Behavior
When I disconnect the OpenSprinkler Pi, the following happens:
- Station 1 shows as offline, logged 8 times `(2020-11-02 14:31:12.460 [hingStatusInfoChangedEvent] - 'opensprinkler:station:2a99e487' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): Could not get the station channel 2 current state from the OpenSprinkler thing. Error: There was a problem in the HTTP communication with the OpenSprinkler API: Request to OpenSprinkler device failed: java.net.SocketTimeoutException: Connect Timeout)`
- Station 1 shows as ONLINE again, logged 1 time
- Station 2 shows as offline, logged 8 times
- Station 2 shows as ONLINE again, logged 1 time
- Station 3 shows as offline, logged 8 times
- Station 3 shows as ONLINE again, logged 1 time
- Then all station remain in ONLINE state

All the time the HTTP Interface is in ONLINE state

Only after disabling / reenabling the thing the HTTP interface goes to OFFLINE - COMMUNIATION_ERROR and the Stations to INITIALIZING (I would also have expected OFFLINE (BRIDGE_OFFLINE) here according to https://www.openhab.org/docs/concepts/things.html).

## Possible Solution
Correctly show offline status. When The Pi is not reachable, all things should be OFFLINE.

## Steps to Reproduce (for Bugs)
1. Setup OpenSprinkler
2. Shutdown OpenSprinkler or remove network cable

## Context
I'm using the Thing state for detection when something goes wrong and with most other bindings this works fine, sending me an email after 1 Minute continuous downtime. But not here. If my OpenSprinkler Pi failed (like it did some days ago) I would not notice it and my garden would be too dry.

**Comment by Skinah** [comment]
I can take a look into this when my unit arrives in a few weeks time.

**Comment by Skinah** [comment]
I have the non PI version based on esp8266 and I can reproduce this here. Just need some time to get used to the API and the binding before making changes.

**Comment by eikowagenknecht** [comment]
Thank you for looking into this @Skinah !

**Comment by Skinah** [comment]
Try this build to see if it works and if any new bugs have cropped up.

http://www.pcmus.com/openhab/opensprinkler/org.openhab.binding.opensprinkler-3.1.0-SNAPSHOT.zip

**Comment by eikowagenknecht** [comment]
I'm not on openHAB 3 yet and currently have some hardware issues with my openSprinkler, so it will take some time before I can test this. Thank you again for the fix!

**Comment by eikowagenknecht** [comment]
I just wanted to test this, but it seems it's not compatible with my OH version?

```
2021-05-20 20:33:32.386 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.opensprinkler-3.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.opensprinkler [82]
  Unresolved requirement: Import-Package: org.openhab.core.config.core
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]
```

I'm currently on 3.0.2.
