### ISSUE TITLE
Documentation "Create a bundle" is outdated

### ISSUE THREAD

**Issue by beulenbilly** [openhab/openhab-addons#8972]
Since the release 2.5.10 the files create_openhab_binding_skeleton.(sh|cmd) are missing which you are referencing in https://www.openhab.org/docs/developer/#develop-a-new-binding.

I appreciate if you update the documentation to describe the correct way for creating new bindings.

**Comment by kaikreuzer** [comment]
What do you mean with missing?
Here they are:
https://github.com/openhab/openhab-addons/blob/main/bundles/create_openhab_binding_skeleton.cmd
https://github.com/openhab/openhab-addons/blob/main/bundles/create_openhab_binding_skeleton.sh

**Comment by beulenbilly** [comment]
True.
I started my first steps with the tag 2.5.10 and looked into the tag 2.5.9 .. not in the current dev branch
