### ISSUE TITLE
[modbus] Thing creation shows picks up wrong binding description

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#8973]
## Expected Behavior

I'm not sure... Something general here would make sense, from org.openhab.binding.modbus?. Best would be perhaps to refer to modbus as general protocol _and_ call by name the specific device types (sunspec, e3dc). 

Or should we have each binding separately in the list?

OH2 shows it like this:
![image](https://user-images.githubusercontent.com/315866/98436068-ff204480-20e0-11eb-9b2b-8a970840e7a2.png)

## Current Behavior

MainUI picks up one of the many `modbus.*` binding descriptions for the 

![image](https://user-images.githubusercontent.com/315866/98435927-aac89500-20df-11eb-8d69-b7525497bfc1.png)

I am not sure why helios is picked?

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

OH3 M2

**Comment by mstormi** [comment]
FWIW I've hit that, too.
Running OH3, I added the modbus binding by adding it to the bindings= line in /etc/openhab/services/addons.cfg
Now when clicking + in OH3 Main UI Things view I'm expected to select from the list of installed bindings.
Modbus is shown for selection here but the 2nd (larger) label line is labeled "HeliosEasyControls Binding" so it has a wrong default label. I'm not using any Helios stuff and never did.

**Comment by eikowagenknecht** [comment]
This is really irritating. Had to check twice just to make sure I really installed the correct binding. Some more screenshots:

![image](https://user-images.githubusercontent.com/1475672/107533997-c9976580-6bbf-11eb-929b-6a6ddc595695.png)

![image](https://user-images.githubusercontent.com/1475672/107534050-d7e58180-6bbf-11eb-890e-cb00b9ba2d9f.png)

**Comment by mstormi** [comment]
@ssalonen did you have a look ?

On a sidenote, there's typos ("responsed" and "reseting") in some Modbus error log messages.
I think you should find 'em with a simple grep next time you work on the code.

```
COMMUNICATION_ERROR Error with read: org.openhab.core.io.transport.modbus.internal.ModbusSlaveErrorResponseExceptionImpl: Slave responsed with error=3 
```

```
Try 2 out of 3 failed when executing request (ModbusReadRequestBlueprint [slaveId=1, functionCode=READ_INPUT_REGISTERS, start=12999, length=44, maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketException Connection reset [operation ID 363322a7-d699-426b-8bb8-d4a3edaf2863]
```

**Comment by ssalonen** [comment]
@mstormi No I haven't. The relevant pieces in openhab core are quite unknown to me.

**Comment by mstormi** [comment]
@wborn Wouter could you please have a look and eventually give a helping hand ?

**Comment by wborn** [comment]
It seems that the UI simply renders the response of the `/rest/bindings` reponse which seems to be wrong:

```
[
  {
    "description": "This binding supports the integration of Helios ventilation systems with easyControls using a Modbus TCP implementation.",
    "id": "modbus",
    "name": "HeliosEasyControls Binding"
  }
]
```

It could be a i18n/l10n regression. Currently don't have time to further debug it.

**Comment by wborn** [comment]
It was an easy fix. :smile:

**Comment by ssalonen** [comment]
Great find!
