### ISSUE TITLE
[openhabcloud] OH3 Support ThingActions

### ISSUE THREAD

**Issue by DejanBukovec** [openhab/openhab-addons#8978]
## Expected Behavior
I think that openHAB Cloud addon is not full OH3 compatible. As Im quick check sourcecode(Im new at this) looks like there is missing "ThingActions" and this is reason why sendNotification can't be used in rules or scripts.

Error:
`2020-11-07 17:22:13.139 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID '75b6964fbe' failed: ReferenceError: "sendNotification" is not defined in <eval> at line number 26`

## Possible Solution
So probably plugin need to be reworked that it  implements ThingActions

## Steps to Reproduce (for Bugs)
For example run simple script like:
`sendNotification("user", "This is notification");`

## Your Environment
* Version used: openHAB 3.0.0M2
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 20.04

**Comment by lolodomo** [comment]
You closed without any explanation.
But at the same time I just tested openhabcloud and sendNotification in OH3 and it works perfectly.

**Comment by DejanBukovec** [comment]
Im get it working on both DSL and ECMA scripts. For some strange reason after installation of openhab cloud addon openhab server MUST be restarted otherwise sendNotification do not work in ECMA script(Crash with ClassNotFoundException) and function is visible on DSL(Do not crash) but do not send anything and in log write “No connection, notification is not sent” but cloud connection work normaly and over wan I normaly see sitemaps…
So only script access didn’t work until restart after addon installation… Im test this few times and can confirm that this can be reproduced… But is not big deal... Because Im develop openhab addon on my computer and add access to rest api with token authentication it didn’t work because Im rebuild&install addon without openhab restart and push messages never didn’t work...
