### ISSUE TITLE
[shelly] ActionURL in OpenHAB as Docker set to Dockerinternal IP

### ISSUE THREAD

**Issue by MajorTwip** [openhab/openhab-addons#8982]
As I use multiple Subnet in ma setup I can't use CoIoT. So I need polling (working) and ActionURLs. These ActionURLs are set automaticaly, but use the OpenHAB config.localip which represents the Docker internal IP.

## Expected Behavior
Sets ActionURL to an accessible IP.

http://192.168.20.202:58080/shelly/event/shellyswitch25-abc123/relay/0?type=btn_on

## Current Behavior
Sets ActionURL to config.localip, which is in case of Docker an internal IP

http://172.18.0.2:58080/shelly/event/shellyswitch25-abc123/relay/0?type=btn_on

## Possible Solution
Either let me chose in OpenHAB as config.localIP the IP of the host (errorprone if portforwarding not properly done)
Suggested: Setting in the Shelly Config which lets me set an alternate URL to set in the ActionURLs

## Steps to Reproduce (for Bugs)
Docker compose:

version: '2'

services:
  openhab:
    image: "openhab/openhab:3.0.0-snapshot"
    ports:
      - "58080:58080"
    environment:
      OPENHAB_HTTP_PORT: "58080"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Zurich"

## Context
-

## Your Environment
Subnet x.x.20.x whit all servers (including  Docker hosts)
x.x.10.x with all the IoT-Stuff including multiple Shellys (2, 2.5, 1, HT)
OpenHAB 3 (same problem I had allready with 2.5)

**Comment by markus7017** [comment]
Did you tried to set the proper default interface ip in openhab network config?

**Comment by markus7017** [comment]
@MajorTwip Did you check setting the Local interface address in the binding configuration? This should allow to setup any ip, which will be used to build the action url and setup the CoAP listener

**Comment by MajorTwip** [comment]
![image](https://user-images.githubusercontent.com/6123320/102020821-e65c1c00-3d7b-11eb-9133-5f998b853b47.png)

Those are in OpenHAB 3.0.0SNAPSHOT the only binding-settings available. If I understood the code corectly, there is no such setting available. It is directly taken from OpenHAB. And as I have OH behind a reverse proxy, the listening-IP from OH and the url in Shelly Actions is not the same.

**Comment by markus7017** [comment]
This is the declaration in the xml definition
```
		<parameter name="localIP" type="text">
			<label>@text/binding.shelly.config.localIP.label</label>
			<description>@text/binding.shelly.config.localIP.description</description>
			<default></default>
		</parameter>
```
![Bildschirmfoto 2020-12-14 um 08 35 01](https://user-images.githubusercontent.com/12601656/102053093-75eae480-3de7-11eb-94a1-793b6741dd64.png)

Do you have updated to the latest DEV Build? The code based included in OH 3.0 is way older. PR is ready to submit, but I want to make sure that various fixes and improvements are well tested before triggering the review. Yes, it's sad that this doesn't happened before the final 3.0 release, but there has to be the time to do that...

**Comment by markus7017** [comment]
Here the info how to install the DEV build. V2.x and 3.x now share the same code base


---

Latest **DEV** build: [2.5.11](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true) - [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)  - Note: The 3.0 build is behind 2.5.11. Let me know if someone needs a 3.0 build due to new device support etc.

**Comment by MajorTwip** [comment]
If you like me to test it I will do the upgrade. Otherwise I'll wait for the RP to be merged to a Milestone Build.
Meanwhile I put the OH Docker on Network=host, like this it allready worked with the old codebase.

**Comment by markus7017** [comment]
A test would be helpful then we could add some info to the README how to set it up as part of the PR

**Comment by MajorTwip** [comment]
So, following https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md I have uninstalled the Shelly Binding over the OpenHAB 3 GUI, shut down OH, put the 3 JARS (shelly 3.0.0, Californium and Element binder 2.0.0) in addons.

Now:

When I add a shelly device it stays at "configuration pending"

Karaf Log:

20:19:59.080 [DEBUG] [.shelly.internal.ShellyHandlerFactory] - 0_0_Out LightDoor: Create new thing of type shelly:shelly25-relay using ShellyRelayHandler
20:19:59.087 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shelly25-relay:f4c159e881' changed from UNINITIALIZED to INITIALIZING
20:20:01.091 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Thing name derived from UID shelly:shelly25-relay:f4c159e881
20:20:01.094 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Using userId admin from bindingConfig
20:20:01.095 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Device config: IP address=10.87.10.100, HTTP user/password=admin/***, update interval=60
20:20:01.096 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Configured Events: Button: false, Switch (on/off): false, Push: false, Roller: true, Sensor: true, CoIoT: true, Enable AutoCoIoT: false
20:20:01.098 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Start initializing thing 0_0_Out LightDoor, type shelly25-relay, ip address 10.87.10.100, CoIoT: true
20:20:01.099 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'shelly:shelly25-relay:f4c159e881' changed from INITIALIZING to UNKNOWN (CONFIGURATION_PENDING): message.status.unknown.initializing
20:20:01.447 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Initializing device shellyswitch25-688723, type SHSW-25, Hardware: Rev: prod-2019-03, batch 1; Firmware: v1.9.2 / 20201128-102046 (e83f7025)
20:20:01.448 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Shelly settings info for shellyswitch25-688723: {"device":{"type":"SHSW-25","mac":"2CF432688723","hostname":"shellyswitch25-688723","num_outputs":2, "num_meters":2, "num_rollers":1},"wifi_ap":{"enabled":false,"ssid":"shellyswitch25-688723","key":""},"wifi_sta":{"enabled":true,"ssid":"Comstock_HW","ipv4_method":"static","ip":"10.87.10.100","gw":"10.87.10.1","mask":"255.255.255.0","dns":"10.87.20.200"},"wifi_sta1":{"enabled":false,"ssid":null,"ipv4_method":"dhcp","ip":null,"gw":null,"mask":null,"dns":null},"mqtt": {"enable":true,"server":"mqtt.comstock.ch:1883","user":"","id":"shellyswitch25-688723","reconnect_timeout_max":60.000000,"reconnect_timeout_min":2.000000,"clean_session":true,"keep_alive":60,"max_qos":0,"retain":false,"update_period":30},"coiot": {"update_period":15},"sntp":{"server":"time.google.com","enabled":true},"login":{"enabled":false,"unprotected":false,"username":"admin"},"pin_code":"","name":null,"fw":"20201128-102046/v1.9.2@e83f7025","factory_reset_from_switch":true,"discoverable":true,"build_info":{"build_id":"20201128-102046/v1.9.2@e83f7025","build_timestamp":"2020-11-28T10:20:46Z","build_version":"1.0"},"cloud":{"enabled":false,"connected":false},"timezone":"Europe/Zurich","lat":47.473301,"lng":8.195960,"tzautodetect":true,"tz_utc_offset":3600,"tz_dst":true,"tz_dst_auto":true,"time":"20:20","unixtime":1608063601,"led_status_disable":false,"actions":{"active":true,"names":["btn_on_url","btn_off_url","longpush_url","shortpush_url","out_on_url","out_off_url","btn_on_url","btn_off_url","longpush_url","shortpush_url","out_on_url","out_off_url","roller_open_url","roller_close_url","roller_stop_url","ext_temp_over_url","ext_temp_under_url","ext_temp_over_url","ext_temp_under_url","ext_temp_over_url","ext_temp_under_url","ext_hum_over_url","ext_hum_under_url"]},"hwinfo":{"hw_revision":"prod-2019-03", "batch_id":1},"mode":"relay","max_power":1840,"longpush_time":800,"relays":[{"name":null,"appliance_type":"General","ison":false,"has_timer":false,"default_state":"off","btn_type":"toggle","btn_reverse":0,"auto_on":0.00,"auto_off":0.00,"max_power":0,"schedule":false,"schedule_rules":[]},{"name":null,"appliance_type":"General","ison":true,"has_timer":false,"default_state":"last","btn_type":"detached","btn_reverse":0,"auto_on":0.00,"auto_off":0.00,"max_power":0,"schedule":false,"schedule_rules":[]}],"rollers":[{"maxtime":20.00,"maxtime_open":20.00,"maxtime_close":20.00,"default_state":"stop","swap":false,"swap_inputs":false,"input_mode":"openclose","button_type":"toggle","btn_reverse":0,"state":"stop","power":0.00,"is_valid":true,"safety_switch":false,"schedule":false,"schedule_rules":[],"obstacle_mode":"disabled","obstacle_action":"stop","obstacle_power":200,"obstacle_delay":1,"safety_mode":"while_opening","safety_action":"stop","safety_allowed_on_trigger":"none","off_power":2,"positioning":true}],"favorites_enabled":false,"favorites":[{"name":"Position 1","pos":0},{"name":"Position 2","pos":0},{"name":"Position 3","pos":0},{"name":"Position 4","pos":0}],"ext_sensors":{},"ext_temperature":{},"ext_humidity":{}}
20:20:01.449 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Device hasRelays:true (numRelays=2),isRoller:false (numRoller=1),isDimmer:false,numMeter=2,isEMeter:false),isSensor:false,isDS:false,hasBattery:false,isSense:false,isLight:false,isBulb:false,isDuo:false,isRGBW2:false,inColor:false,updatePeriod:70sec
20:20:01.653 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Updating channel definitions, 6 channels
20:20:01.653 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'shelly:shelly25-relay:f4c159e881' has been updated.
20:20:01.654 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#internalTemp
20:20:01.656 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#accumulatedWatts
20:20:01.657 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#accumulatedWTotal
20:20:01.658 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#updateAvailable
20:20:01.658 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#heartBeat
20:20:01.658 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Adding channel device#statusLed
20:20:01.660 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Channel definitions updated
20:20:01.660 [INFO ] [smarthome.event.ThingUpdatedEvent    ] - Thing 'shelly:shelly25-relay:f4c159e881' has been updated.
20:20:01.660 [DEBUG] [ly.internal.handler.ShellyBaseHandler] - shelly25-relay-f4c159e881: Update status job started, interval=20*3=60sec.
20:20:01.661 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NoClassDefFoundError: org/openhab/core/library/unit/Units
        at org.openhab.binding.shelly.internal.handler.ShellyComponents.updateDeviceStatus(ShellyComponents.java:57) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.fillDeviceStatus(ShellyBaseHandler.java:496) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.initializeThing(ShellyBaseHandler.java:275) ~[?:?]
        at org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.lambda$0(ShellyBaseHandler.java:161) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]


And even worse: under Settings-> Addons Shelly seems not to be installed, so no Config possibility.

**Comment by MajorTwip** [comment]
My bad, i tried with the Milestone 1. Will try later this day with MS5

**Comment by markus7017** [comment]
nope, you need to use the Shelly DEV Build!


---

[2.5.11](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true) or [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)

**Comment by markus7017** [comment]
did you tested, make sure to use 2.5.12-SNAPSHOT (DEV Build)

**Comment by MajorTwip** [comment]
works now
