### ISSUE TITLE
[miio] Dreame F9 robot

### ISSUE THREAD

**Issue by sicanins** [openhab/openhab-addons#8986]
Hi, 
I am trying to get my Dreame F9 robot working. 
First idea was to use the C1 mc1808, but that does not work. 
Besides SSID and RSSI, it can only read "Battery level", "Battery charging state", "Robot cleaner device fault" and "Robot cleaner status". Everything else is NULL. And it does not accept any commands. That might be due to "condition not met" as the logfile says. I think the commands are not even sent to the robot.

I am running the openhabian stable.

The device is discovered as unsupported.
I ran the test commands, but it literally showed that nothing is supported.
Files are here:
[https://www.dropbox.com/sh/1caxu9xdhtlwlb0/AAACwzCYoRUK_-6QvWCFB11Oa?dl=0](https://www.dropbox.com/sh/1caxu9xdhtlwlb0/AAACwzCYoRUK_-6QvWCFB11Oa?dl=0)

Also I did a wireshark capture containing the start and dock commands.

Currently I am out of ideas how I could get this to work myself.
Tried to copy the model .json file to the conf/misc/miio folder, but either its not read or the folder is different for openhabian.

Any help would be appreciated.

Thanks,
Simon

**Comment by marcelrv** [comment]
Can you try below database file to your conf/misc/miio folder (see readme for more details)
It has all known properties for your specific model from http://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-p2008:1

When the binding is starting it will print the location of the local folder.. it has a message like Started miio basic devices local databases watch service. Watching for database files at path: …”. Though I think if you create the path the first time while OH is already running, you may have to restart the binding once more to have it actually starting to watch it

[dreame.vacuum.p2008-miot.zip](https://github.com/openhab/openhab-addons/files/5507230/dreame.vacuum.p2008-miot.zip)

I have not copied in the actions, I think with your debug output the and the actions from the  mc1808 model that can be created as well.

**Comment by marcelrv** [comment]
note, your model is a so-called miot model, the testing indeed only tries to find the regular models. Hence little is found.

Once I have bit of time, these miot models will also get some automated database creation logic similar as recently introduced for the regular models.

**Comment by sicanins** [comment]
Thanks for the fast answer!
The file worked and I can get all info from the robot now.

Tried to copy the commands from the mc1808, but no success so far.
Could you maybe point me to the correct lines in the command capture? Then I am happy to try around.

Thanks!
Simon

**Comment by marcelrv** [comment]
You can try these commands, see if they work (they are coming from reading miotspec hyperlink. I posted in my earlier reply) there are a few more actions in there.

action {"did":"start-sweep","siid":1,"aiid":1,"in":[]}
action {"did":"stop-sweep","siid":1,"aiid":2,"in":[]}
action {"did":"Start-Charging","siid":1,"aiid":2,"in":[]}
action {"did":"StartClean","siid":4,"aiid":1,"in":[10]}
action {"did":"StopClean","siid":4,"aiid":2,"in":[]}
action {"did":"getmap","siid":6,"aiid":1,"in":[2]}

note, if these don't work try to add outer square brackets e.g. action [{"did":"StartClean","siid":3,"aiid":1,"in":[10]}]

**Comment by marcelrv** [comment]
note, you need to have a rather recent version of the snapshot binding for these action commands to work...

**Comment by sicanins** [comment]
Hi,

installed the latest snapshot I found (few days old).
Tried a lot of different combinations of the command, but so far nothing worked.
Without the extra brackets I get an exception, so I added them.

But the response is always:
```
2020-11-10 22:28:49.924 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Communication error for Mi device at 192.168.77.51: Receive timed out
2020-11-10 22:28:49.926 [DEBUG] [nal.transport.MiIoAsyncCommunication] - No response from device 15BFA46F at 192.168.77.51 for command {"id":414,"method":"action","params":[{"did":"getmap","siid":6,"aiid":1,"in":[2]}]}.
2020-11-10 22:28:49.927 [DEBUG] [internal.handler.MiIoAbstractHandler] - Received response for Vacc type: ACTION, result: {}, fullresponse: {"error":"No Response"}
2020-11-10 22:28:49.928 [DEBUG] [internal.handler.MiIoAbstractHandler] - Error received: "No Response"
```

I even tried ssid and aaid values I captured previously with the exact same did value, also no response. 
So I rather suspect this is something in the java code?

Thanks!

**Comment by marcelrv** [comment]
Can you try to install really the latest. The MalformedJsonException  erro was fixed very recent. (or share the error you are getting)

The similar model indeed requires curly brackets instead and just indicated it was working.
https://community.openhab.org/t/problem-with-miio-binding-for-vacuum-1c-stytj01zhm-dreame-vacuum-mc1808/102631/31
