### ISSUE TITLE
[shelly] logs show "New firmware available" though device is upgraded according to Shelly app

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-addons#8994]
## Expected Behavior
Logs to be aligned with status of device 
## Current Behavior
Logs state
`2020-11-07 21:31:01.786 [INFO ] [y.internal.handler.ShellyBaseHandler] - shelly1-10521c459c88: INFO: New firmware available: current version: 20191217-140757/1047-
long-id-for-shelly-devices@a0661583, new version: 20200827-065344/v1.8.3@4a8bc427`
while app shows
![IMG_4370FB6D2697-1](https://user-images.githubusercontent.com/5411131/98640584-8f9d9580-232a-11eb-8556-4073c0137114.jpeg)

## Steps to Reproduce (for Bugs)
1. Connect new shelly to setup, add item to openhab 
2. Update to latest firmware
3. Check logs
4. Restart openhab
5. Recheck logs - Problem persists

## Your Environment
* Version used: 2.5.10
* Environment name and version : Shelly 1
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): raspberry Pi

**Comment by markus7017** [comment]
Did you installed the Shelly binding from within PalerUI or are you using the DEV build?


—

Latest DEV build: [2.5.10](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.10-SNAPSHOT.jar?raw=true) - [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)

**Comment by timbms** [comment]
I am using the shelly 2.5.10 provided by Debian on my raspberry Pi.

**Comment by markus7017** [comment]
did you restarted OH?
