### ISSUE TITLE
[unifi] add support for  Controller Version 6.x and Cloud Key version 2.x

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#9001]
Unifi offers an update for the cloudkey to version 2.x and the networkcontroller to 6.xx. After installing the updates the binding cannot access the contoller. This is maybe based on the fact that the URL to acces the controller has changes.

http://192.168.x.x/network/site/default/dashboard

The Binding shows an communikation error.

**Comment by taakberg** [comment]
For the Cloud Key Gen2 device, the api endpoint the binding uses changed from `[hostname]:8443/api` to `[hostname]/proxy/network/api`. It now always uses https and port 443.

Unfortunately, there's no way to adjust this in the binding config. All paths seem to be hardcoded (e.g. `/api/self/sites`). I've tried changing the hostname to `my_hostname/proxy/network`, but unfortunately, that doesn't work.

**Comment by timbms** [comment]
Is this topic currently being addressed? I would love to have it solved

**Comment by TBail** [comment]
Unforunately i dont think that someone is working on that.

**Comment by TBail** [comment]
Just installed the latest nightly #2182 and unfortunately i still get a commcunication error

My config is a Cloudkey Gen2 plus OS 2.0.27 and Netwerok controller 6.0.45

This is the configuration of the bridge. The Cloud key is reachable using Ping an the url in the browser is: https://unifi-cloudkey-gen2-plus.thing.home/network/site/default/dashboard

image
![image](https://user-images.githubusercontent.com/40339145/107007199-7c1b9280-6792-11eb-99b3-15a4a8af2f33.png)


So it seems that there is something else wrong

**Comment by WatcherWhale** [comment]
The default port for UniFi OS is 443 not the old 8443 port.

**Comment by TBail** [comment]
Thanks for that hint. I think it was a rst from the old configuration. With 443 it works instantly
