### ISSUE TITLE
[miio] "Unknown Mi IO Device"  XIAOMI MI ROBOT VACUUM MOP ESSENTIAL

### ISSUE THREAD

**Issue by phuongpham** [openhab/openhab-addons#9005]
I just purchased XIAOMI MI ROBOT VACUUM MOP ESSENTIAL
The binding do find the vacuum but it’s listed as “unsupported xiaomi mi device”
I only get few channels inside the thing. I do get the execute channel/action.
But when I try to run this command in karaf:
smarthome:send MiRobotVacuumMopEssential_Actions_ExecuteCommand find_me
It doesn’t work. When I run same command on other vacuum (S50) it works fine.

 openhab> bundle:list org.openhab.binding.miio
 ID │ State  │ Lvl │ Version │ Name

260 │ Active │  80 │ 2.5.10  │ openHAB Add-ons :: Bundles :: Xiaomi Mi IO Binding

After running "(experimental)Execute test for all known properties to find channels supported by your device." I get this:

17:57:15.684 [INFO ] [ternal.handler.MiIoUnsupportedHandler] - Info for mijia.vacuum.v2
Properties: power -> 796, aqi -> 797, battery -> 798, usb_state -> 799, time_state -> 800, night_state -> 801, night_beg_time -> 802, night_end_time -> 803, pm25 -> 804, co2e -> 805, tvoc -> 806, humidity -> 807, temperature -> 808, co2 -> 809, mode -> 810, limit_hum -> 811, trans_level -> 812, led_b -> 813, buzzer -> 814, depth -> 815, dry -> 816, use_time -> 817, speed -> 818, temp_dec -> 819, child_lock -> 820, average_aqi -> 821, led -> 822, f1_hour -> 823, f1_hour_used -> 824, motor1_speed -> 825, filter1_life -> 826, favorite_level -> 827, purify_volume -> 828, bright -> 829, volume -> 830, motor2_speed -> 831, ptc_on -> 832, ptc_level -> 833, ptc_status -> 834, screen_direction -> 835, display -> 836, sound -> 837, control_speed -> 838, favourite_speed -> 839, temperature_outside -> 840, filter_intermediate -> 841, filter_inter_day -> 842, filter_efficient -> 843, filter_effi_day -> 844, filter_rate -> 845, filter_day -> 846, angle_enable -> 847, angle -> 848, poweroff_time -> 849, speed_level -> 850, natural_level -> 851, ac_power -> 852, bat_charge -> 853, roll -> 854, roll_angle -> 855, timer_off -> 856, beep_sound -> 857, light -> 858, doorbell_volume -> 859, gateway_volume -> 860, alarming_volume -> 861, doorbell_push -> 862, ambstatus -> 863, ambvalue -> 864, dvalue -> 865, eyecare -> 866, cct -> 867, snm -> 868, dv -> 869, pow -> 870, sw -> 871, bl -> 872, ms -> 873, ac -> 874, mb -> 875, scene_num -> 876, wifi_led -> 877, on -> 878, usb_on -> 879, power_consume_rate -> 880, power_price -> 881, current -> 882, run_state -> 883, err_state -> 884, battery_life -> 885, box_type -> 886, mop_type -> 887, s_time -> 888, s_area -> 889, suction_grade -> 890, water_grade -> 891, remember_map -> 892, has_map -> 893, is_mop -> 894, has_newmap -> 895, switch1 -> 896, switchname1 -> 897, switch2 -> 898, switchname2 -> 899, switch3 -> 900, switchname3 -> 901, run_status -> 902, rinse -> 903, tds_in -> 904, tds_out -> 905, f1_totalflow -> 906, f1_totaltime -> 907, f1_usedflow -> 908, f1_usedtime -> 909, f2_totalflow -> 910, f2_totaltime -> 911, f2_usedflow -> 912, f2_usedtime -> 913, f3_totalflow -> 914, f3_totaltime -> 915, f3_usedflow -> 916, f3_usedtime -> 917, seat_temp -> 918, status_seatheat -> 919, water_temp_t -> 920, fan_temp -> 921, status_led -> 922, delayoff -> 923, ct -> 924, color_mode -> 925, toggle -> 926, rgb -> 927, name -> 928, bh_mode -> 929, nl_br -> 930, bg_bright -> 931, bg_power -> 932, bg_rgb -> 933, bg_ct -> 934, bg_lmode -> 935,

**Comment by marcelrv** [comment]
Closes with #91339
