### ISSUE TITLE
[homematic] Devices do not update status

### ISSUE THREAD

**Issue by maedball** [openhab/openhab-addons#9016]
## Expected Behavior
If you switch on a Light switch by using the physical Switch, the status should be shown in openhab aswell

## Current Behavior
The update is not reflected. Meaning if the light was off and someone switched it on via the physical switch. Openhab is still showing the light as off

## Steps to Reproduce (for Bugs)
1. Have the switch matching the status (Light off = Light off in openhab)
2. Switch the light on via the physical switch
3. Check in openhab ist the status is reflected

## Context
I tried it with force update on and off

![image](https://user-images.githubusercontent.com/23019308/99077453-1073c000-25bd-11eb-98d8-597a686efe96.png)

## Your Environment
Ubuntu 20.04 LTS
Openhab 3 M2
OpenJava 11

**Comment by MHerbst** [comment]
I assume that it worked correctly with 2.5. 

What happens in Basic UI? Is the state correctly updated?

Can you enable trace log mode and post the log when after you switched the light on and off. What kind of Homematic device is it?

**Comment by maedball** [comment]
It is also shown wrong in Basic UI.

I have set 15 % via BasicUI, this stays than the shown value even thou I switched the lights on and off. 
In this case itis the homematic:HmIP-BDT. But the same thing happens to normal Brand Light Switches.

[New Text Document.txt](https://github.com/openhab/openhab-addons/files/5542305/New.Text.Document.txt)

![image](https://user-images.githubusercontent.com/23019308/99184257-cff17f00-2741-11eb-8c78-87681d173a6c.png)

**Comment by MHerbst** [comment]
@maedball You could try whether the problem is solved with this binding version: https://github.com/MHerbst/openhab-addons-test/blob/master/org.openhab.binding.homematic-3.0.0-SNAPSHOT.jar

**Comment by maedball** [comment]
Hmm i have now version: 3.0.0.202011221749 (hope this is the one) still it is not updating.

**Comment by MHerbst** [comment]
OK :-(. This means I have to further investigate what is causing the problem.  Acoording to the log, you have configured a delay of 2 s for the event. Can you set it to 0 and test what happens then? A log file with log mode TRACE would help me. I can see a message that the execution of the event is delayed and the last line of your posted log file contains the entry that it is executed. I would need some more lines of the log to see what happens after the event is executed. 

BTW: Did this work correctly with a 2.5 installation?

**Comment by maedball** [comment]
Well after checking what is happening I recognized that the same thing happens to normal switches like the HmIP-BSM. what ever is done to the hardware switch or by switching on the light via the CCU directly is not reflected in openhab.

Do you know where the 2s delay is been configured? I have not set it by myselfs so it has to be some kind of default. Once i found the setting i will post the TRACE logs ;-)

Yes it worked in 2.5.

**Comment by MHerbst** [comment]
This seems to be a problem of HmIP devices. I have tested it an older device and this works, but with a HmIP-PDT I can reproduce it.

A log for the HmIP-BDT is not necessary, because I can probably debug it. But I would be helpful to have a log of switch activities  with the HmIP-BSM.

> Do you know where the 2s delay is been configured?

I think this may be this configuration:
![image](https://user-images.githubusercontent.com/616792/100141376-a0095080-2e92-11eb-8732-69acbeeae53b.png)

**Comment by maedball** [comment]
[New Text Document.txt](https://github.com/openhab/openhab-addons/files/5593380/New.Text.Document.txt)
Here you go. I have the same settings as you have for the event delay and random part.
![image](https://user-images.githubusercontent.com/23019308/100163418-ed4ae980-2eb5-11eb-8d0f-ad806982afcd.png)

**Comment by MHerbst** [comment]
Thanks for the log. Which device is the Hm-BSM? If I am not wrong, I can see several messages from different devices and I would like to concentrage on the correct :-).  I would also like to know, to which device channel you connected the item.

**Comment by maedball** [comment]
I have to many devices that are changing states way too much ;-)

The connection is to this channel homematic:HmIP-BSM:-:000858A991952D:4#STATE

**Comment by MHerbst** [comment]
Can you retest it again with the latest OH Milestone build (or even better the latest snapshot)? In my test environment, I can not longer see update problems.
But I also replaced my PC in the meantime with a much faster PC and so I am not sure whether it maybe is a timing issue on slower machines.

**Comment by maedball** [comment]
Hmm still the same, I would doubt that this is a slow hardware issue as this is a xeon with 4 cores and just a couple of small services running.

![image](https://user-images.githubusercontent.com/23019308/101535649-411aff80-3999-11eb-8459-a355a7dcc826.png)

![image](https://user-images.githubusercontent.com/23019308/101535691-4f691b80-3999-11eb-9cae-f61f3f5cefed.png)

Do you need again some logfiles?

**Comment by MHerbst** [comment]
I can see a difference to my test environment. Next to the item name, there should be a large "H". Can you delete item + thing and create a it new? In the item list it should looke like here:
![image](https://user-images.githubusercontent.com/616792/101538160-fa2f0900-399c-11eb-83cd-01db70751a59.png)

**Comment by maedball** [comment]
I still have the L next to the Level instead of the H but I can confirm that after the deletion of the device and recreation, everything is working as it should ;-)

Thank you very much!

**Comment by MHerbst** [comment]
The important thing was that there appeared a letter, because that was a part of the last fix. 😀. Good to hear that it is working now. Can please set this issue to solved?
