### ISSUE TITLE
[keba] Binding is not compatible with older firmwares

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-addons#9020]
The original code base of the binding supported different firmware versions for the Keba 20/30 wallboxes. During my absence from the "scene" support for the different firmware versions has been removed, and features are added that are not backward compatible. The binding is totally broken, sadly enough. :-( Upgrading firmware on older hardware versions of the KEBA Wallbox is not a walk in the park, therefore support for older firmware version should be restored for those users that do not want to upgrade firmwares!!

**Comment by J-N-K** [comment]
I didn’t find a PR where support for older versions was removed. Can you point me to that?

**Comment by kaikreuzer** [comment]
> The binding is totally broken

I wouldn't say so - it works perfectly with recent firmwares (I didn't upgrade mine since 2 years), so "recent" is even relative here.
I don't think that bindings need to support any older firmware of any device - in contrast, it is quite standard practice to keep firmwares of devices up to date and expect that from users.
If there's an easy way to also support older versions, that's clearly fine, so if you see a way to do so, feel free to come up with a PR. If this would mean that current firmwares are not fully supported anymore (e.g. by losing features), it might be the better way to go and update the KEBA firmware.

**Comment by kgoderis** [comment]
> > The binding is totally broken
> 
> I wouldn't say so - it works perfectly with recent firmwares (I didn't upgrade mine since 2 years), so "recent" is even relative here.
> I don't think that bindings need to support any older firmware of any device - in contrast, it is quite standard practice to keep firmwares of devices up to date and expect that from users.
> If there's an easy way to also support older versions, that's clearly fine, so if you see a way to do so, feel free to come up with a PR. If this would mean that current firmwares are not fully supported anymore (e.g. by losing features), it might be the better way to go and update the KEBA firmware.

I don't agree. As said before, older hardware iterations are a p-in-the-a to update, and unfortunately, being the front-runner here as original binding developer, I do run older hardware (>6j old!) that I explicitly do not want to update. @J-N-K You can't find this back because all history was lost, apparently in 2019. I originally built in a mechanism to deal with different firmware revisions because I run multiple of these stations, all at a different firmware version. 

On a separate note, the handler binds to an IPv6 socket (even if IPv6 is disabled in the runtime), which needs to be fixed because the (at least older firmware/devices) wallboxes only support IPv4. It explains why some other people are reporting that the binding is not working anymore (I suspect them to be on IPv6)

**Comment by kgoderis** [comment]
@kaikreuzer Its's even worse. I just checked the Keba website, and for the older P20 there are even no firmware updates available, it seems not be supported anymore, it is not even mentioned anymore in any API documentation. There are 2 options to approach this. (1) 1 Thing, which can differentiate firmwares (90% is common) or (2) separate things per firmware, with a 90% code duplication (or a bit less, if we use inheritance for the common stuff). 

This is really not cool

**Comment by kaikreuzer** [comment]
> You can't find this back because all history was lost

No history is lost, everything is available at https://github.com/openhab/openhab2-addons.

**Comment by lsiepel** [comment]
@kgoderis did you find the history and get a fix? As this is an old issue it might be no longer relevant, so I’m just checking. Is there anything left here to do?
