### ISSUE TITLE
[ipcamera] ONVIF Discover failing due to probe type

### ISSUE THREAD

**Issue by puzzle-star** [openhab/openhab-addons#9022]
Using 2.5.10, trying to discover an ONVIF IP Camera fails silently. This camera is discovered correctly by other ONVIF software.

Sniffing the network, the discovery message is sent but not answered by the camera.

**Discovery message sent by the binding:**

```
<?xml version="1.0" encoding="UTF-8"?>
<e:Envelope xmlns:e="http://www.w3.org/2003/05/soap-envelope" xmlns:w="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl">
  <e:Header>
    <w:MessageID>uuid:b1bf6b3f-ab94-42f3-a225-c75e2f0b00c1</w:MessageID>
    <w:To e:mustUnderstand="true">urn:schemas-xmlsoap-org:ws:2005:04:discovery</w:To>
    <w:Action a:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</w:Action>
  </e:Header>
  <e:Body>
    <d:Probe>
      <d:Types xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types>
    </d:Probe>
  </e:Body>
</e:Envelope>
```

Looking at the message sent by other software, I see that the camera does indeed respond when changing the probe type tag from:

```
<d:Types xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types>
```

To:

```
<d:Types xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dp0="http://www.onvif.org/ver10/network/wsdl">dp0:NetworkVideoTransmitter</d:Types>
```

Or just (as seen in the ONVIF examples documentation):

```
<d:Types>dp0:NetworkVideoTransmitter</d:Types>
```

Could the probe message be changed to allow for these cameras to be discovered?

**Comment by Skinah** [comment]
What other software are you comparing against? I may have done a trace on the 'onvif device manager' software to see what it was using, as the ONVIF example failed on some of my test cameras. I guess a solution would be to send both with a delay in between to try and capture more cameras, but I will do some tests when I have some spare time so thanks for the suggestions.
