### ISSUE TITLE
[homematic] Change channel type for HmIP-eTRV "WINDOW_STATE" to Contact

### ISSUE THREAD

**Issue by just-grizzle** [openhab/openhab-addons#9050]
## Explaination and current behavior
Homematic IP Radiator Thermostats (HmIP-eTRV-\*) can be directly coupled with window contacts (HmIP-SWDO-\*). The thermostat has its own channel to reflect if the window contact sends open or closed state.

Atm, the Homematic binding recognizes this channel as a string. 

## Expected behavior
Channel `WINDOW_STATE` should be a contact type.

## Possible solution
It's up to you.

## Context
Snippet from Homematic documentation for eTRV-2 (chapter 172, PDF page 10.988 following).
![image](https://user-images.githubusercontent.com/66440907/99362532-e9b2d380-28b3-11eb-9dbf-cef3fc54f283.png)

## My environment
Tested with
* openHAB `2.5.10`
* openhab-addons `2.5.10`
* CCU (Debmatic) `3.53.30.50`
* HmIP-eTRV-2 FW `2.2.8` (latest)
* HmIP-eTRV FW `2.2.8`(lastest)

**Comment by MHerbst** [comment]
With OH 3 (I have tested it with a current snapshot) you can override the default item type and set it to "Contact":
![image](https://user-images.githubusercontent.com/616792/115969455-4ab69580-a53d-11eb-86b0-38a03b45595e.png)

The contact item is updated correctly. I therefore do not see the need for a change in the binding, which would also be quite costly.

**Comment by lsiepel** [comment]
@MHerbst it might still be a breaking change if the type is changed, but now with the upgrade `instructions.xml`, it's a bit less.
User experience wise it would be better, so if i create a PR, would you review and or test it? or would you prefer to close this issue?
