### ISSUE TITLE
[homematic] Dimming Actuators are shown as Switches in Homekit

### ISSUE THREAD

**Issue by maedball** [openhab/openhab-addons#9068]
## Expected Behavior
A Dimming Actuator should be shown as a Dimming Actuator when selected Lightning in OpenHAB

## Current Behavior
Instead of showing the slider to select a percentage of brightness, the Dimming actuator is shown as an on/ off switch

## Steps to Reproduce (for Bugs)
Set Lightning in the new Main UI for the item and check on the IOS device that the dimmer is shown as a switch

![image](https://user-images.githubusercontent.com/23019308/99602963-b2067180-2a02-11eb-83be-397cc1c8328b.png)

![20201119_000359000_iOS](https://user-images.githubusercontent.com/23019308/99603269-3f49c600-2a03-11eb-982c-4a1448282196.png)

## Context
I am currently playing around with Openhab3. Unfortunately I have no idea if this is a Homematic / Homekit or even a core issue :-(

## Your Environment
Ubuntu 20.04 LTS
Openhab 3 M2 + Homematic Test jar (the dimming actuator fix)
OpenJava 11

**Comment by MHerbst** [comment]
Ist this really a problem of the binding? I must admit that I have no idea about Homekit and possible defaults, but according to the Homekit documentation it necessary to set some tags or metadata (https://www.openhab.org/addons/integrations/homekit/#using-metadata). You could use the metadata editor for Homekit in Main UI and set e.g. it to Lightning.Brightness.

**Comment by maedball** [comment]
My guess is this is more a homekit Issue. I am still waiting for some non homematic dimmers to arrive in the mail to verify that the same thing happens with non homematic dimmers. I will post an update once they are here.

**Comment by MHerbst** [comment]
I have the same feeling. I in yesterday's test version, that has been merged today, I made a correction for dimmers because they had a wrong category and the display in Main UI was not correct. Maybe this also can have an influence on Homekit.

**Comment by maedball** [comment]
Once the test Repo is back: [i got hit by this issue](https://github.com/openhab/openhab-linuxpkg/issues/170), i will try it out

**Comment by maedball** [comment]
It is still persistent in this version, is that the one you are talking about?
228 │ Active │  80 │ 3.0.0.202011230332      │ openHAB Add-ons :: Bundles :: Homematic Binding

**Comment by yfre** [comment]
looks like homekit configuration issue. the item can be even a virtual item not connected to any physical device/homematic.
i have not tried with OH3 but in OH2.x you would need to add something like this (depending whether it 

`
Dimmer           legacy_color_light_dimmable       "Legacy Color Light Dimmable"                                [ "DimmableLighting" ]
`
`Color           legacy_color_light_hue            "Legacy Color Light Hue"                                     [ "ColorfulLighting" ]
`

**Comment by yfre** [comment]
@maedball i checked, in OH3 you can do it via UI. please add to your metadata L"ighting.Brightness"

**Comment by maedball** [comment]
@yfre: Thanks for the help. Looks like multiple and the assignment of Lightning. Brightness in addition to Lightning fixed my misconfiguration.

![image](https://user-images.githubusercontent.com/23019308/101294560-68968e80-3818-11eb-8227-6feac60b32d5.png)

Maybe it would make sense to have a database which device needs which Tag in every Binding? I think this would make a lot of first installations a lot easier.

**Comment by yfre** [comment]
glad to hear that it worked for you. so, im closing the ticket. 
the database of device -> tag is in the documentation https://www.openhab.org/addons/integrations/homekit/ 
which for sure can be improved and adapted to openhab3.
