### ISSUE TITLE
[shelly] RGBW2 Brightness for White Channel in Color Mode

### ISSUE THREAD

**Issue by redwhale240** [openhab/openhab-addons#9078]
The Shelly RGBW2 is working with Openhab using an RGBW LED strip. The issue that I’m seeing is that the White channel brightness cannot be controlled with Openhab like in the Shelly App where there is a white brightness slider.  Color picking, gain, and saturation all work with the RGB leds.

Please review if this is a feature that can be added.  See the attached picture from the shelly app. It shows a white brightness slider for the white channel along with the rgb. 

Thank you! 
![Screenshot_20201027-213803_Samsung Internet](https://user-images.githubusercontent.com/74747659/99744758-e9762c00-2a9d-11eb-9c27-a8b27e691551.jpg)

## Expected Behavior
The shelly thing should have an item available to control the brightness of the white channel of an rgbw light strip. 

## Current Behavior
Currently an item that control the white changed off an rgbw strip white it's in color mode does not exist. 

## Possible Solution
Add white brightness item to the shelly RGBW2 thing

## Steps to Reproduce (for Bugs)

1.
2.

## Context
Without this feature it is not possible to control the brightness of the white led in a rgbw light strip in color mode.  The rgb brightness can be set. 

## Your Environment
Openhab 2.5, raspbian

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by markus7017** [comment]
There is an advanced channel white (use [Show More]). Did you tried that?

**Comment by markus7017** [comment]
I made the white channel a standard one (not advanced)
