### ISSUE TITLE
[Bluetooth Binding] Support for generic BLE devices

### ISSUE THREAD

**Issue by PRosenb** [openhab/openhab-addons#9085]
Hi guys,

Is there active development to support [generic BLE devices](https://www.bluetooth.com/specifications/gatt/) for openHAB 3 or are there interested parties to continue such a development?

There is an outdated binding that looks abandoned and it would probably be a lot of work to get it running again.
[eclipse-smarthome-bluetooth-binding](https://github.com/sputnikdev/eclipse-smarthome-bluetooth-binding)

I’m wondering if it’s easier to try to update it to current openHAB versions or to extend `Bluetooth Binding` with using code from there where possible.

Cheers,
Pete

**Comment by ssalonen** [comment]
https://github.com/openhab/openhab-addons/pull/8775

**Comment by PRosenb** [comment]
Great, thanks @ssalonen for mentioning the issue, I'll check out that branch.

**Comment by bwosborne2** [comment]
Why was this closed without providing the functionality in OH ?

**Comment by jlaur** [comment]
There is also #20880 now.
