### ISSUE TITLE
[homekit] min/max value not working for Thermostat or TemperatureSensor 

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#9089]
Hi,

set minValue or maxValue for HomeKit Thermostat or TemperatureSensor not working anymore.

Here the code from Item metadata:

```
value: TemperatureSensor
config:
  minValue: 0
  maxValue: 100
```

Here the log output
```
2020-11-21 12:26:50.161 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range 61.7. Returning max value instead. Characteristic io.github.hapjava.characteristics.impl.thermostat.CurrentTemperatureCharacteristic@94862
2020-11-21 14:22:37.244 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range -3.6. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.thermostat.CurrentTemperatureCharacteristic@efda36
```

OH3: build 2024 and all before.

**Comment by yfre** [comment]
@grzegorz914 can you provide some more information
- how you have created the item and meta data for it? using UI or importing items.xml?
- have you changed min/max value after the creation?

**Comment by grzegorz914** [comment]
@yfre 
Im using UI and also check org.openhab.core.items.Metadata.json,

here the code from UI:
<img width="1559" alt="Zrzut ekranu 2020-12-8 o 16 54 38" src="https://user-images.githubusercontent.com/28867813/101506915-3e5ae300-3976-11eb-832a-04002f70792b.png">

here the org.openhab.core.items.Metadata.json:
```
"homekit:PLC_PogodaTemp": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "homekit",
          "PLC_PogodaTemp"
        ]
      },
      "value": "TemperatureSensor",
      "configuration": {
        "minValue": 0.0,
        "maxValue": 100.0
      }
    }
  }
```

**Comment by yfre** [comment]
@grzegorz914  thank you for reporting. 
i could re-produce the issue and it looks like mainUI create numbers for meta data differently than text based configuration in the past. 
i have submitted a fix for it
please re-test once the PR get merged and released

**Comment by grzegorz914** [comment]
@yfre 

yes, if create test.items file with:
`Number   PLC_PogodaTemp	        "Test"       {homekit="TemperatureSensor" [minValue=-10.0, maxValue=100] }`
then working OK, create same item from UI not working.

**Comment by grzegorz914** [comment]
@yfre 

Build 2060 nothing changes, or is not merged?

**Comment by yfre** [comment]
im not sure about build process. 2060 is the core, right? which version of homekit binding you see in karaf or UI?
maybe you need to reinstall homekit binding

**Comment by grzegorz914** [comment]
OK,

updated to 2061 and all working correct.
