### ISSUE TITLE
[netatmo] Useless code (MeasurableChannels) ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#9090]
@clinique : while I was looking at the potential impact of openhab/openhab-core#1707 on the Netatmo binding, I discovered that one part of the code is useless if my analysis is correct.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBindingConstants.java#L290
MEASURABLE_CHANNELS is an empty set.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/MeasurableChannels.java#L50
The list `measuredChannels` in class `MeasurableChannels` will then always be empty.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/MeasurableChannels.java#L67
As a consequence, index will always be equal to -1, meaning that `getNAThingProperty` will always returns `Optional.empty()` and more generally that this class `MeasurableChannels` is useless.

https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/handler/AbstractNetatmoThingHandler.java#L181
And finally overriding `channelLinked` is useless too.

Do I miss something ?

Do you remember what was the idea behind this class `MeasurableChannels` ?
Is there a bug with constant `MEASURABLE_CHANNELS` definition ?

**Comment by clinique** [comment]
@lolodomo  : yes, sure, you got my attention :). I'll be back on this as soon as doable.

**Comment by clinique** [comment]
@lolodomo : I'm not 100% sure, but I think you're right. I'm not able to go older in modification history, but I think this has been modified around [this PR](0a706f7a28604f215f9637a12764d4ca307c1dd8) by @robnielsen . From the older generic measurement system, he implemented detailed of all possible measurement channels

**Comment by robnielsen** [comment]
@lolodomo, It appears this was added about 4 years ago by @clinique . See https://github.com/openhab/openhab2-addons/commit/eda1ebed9c963f8b7ea7ff24f5f3cca9dca73408

**Comment by lolodomo** [comment]
@robnielsen : are you ok with us that this code can be removed now?

**Comment by robnielsen** [comment]
@lolodomo, yes the functionality I added doesn't use it.
