### ISSUE TITLE
[shelly] Support for Shelly UNI

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#9096]
Shelly launched the Shelly UNI, which is kind of an embedded sensor/actor for appliances

Binding needs to support this device type

**Comment by Dom1n1c** [comment]
+1 for Shelly Uni Support
Right now, i get:  **IP address of the Shelly device is missing. / This device is currently not supported**



![image](https://user-images.githubusercontent.com/8407566/106271227-76bcc600-622f-11eb-9829-d936b1621a59.png)

**Comment by markus7017** [comment]
switch to the current DEV build


---

Latest **DEV** build: [2.5.12](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.12-SNAPSHOT.jar?raw=true) - [3.1.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)
Note: The binding version included in the final OH 3.0 distro is significantly older than the DEV build. I can't make it in-time. Make sure you deleted older versions of the binding when installing the 2.5.12-SNAPSHOT or 3.1.0-SNAPSHOT if you are already on OH 3.
