### ISSUE TITLE
[mqtt] Broker port of MQTT system broker connection is not considered

### ISSUE THREAD

**Issue by MikeTheTux** [openhab/openhab-addons#9098]
`Broker port` config parameter of `MQTT system broker connection` configuration is not considered.
Default encrypted port is used instad.

OpenHab 3.0.0.M2

As workaround the normal, non-system broker can be used instead.

**Comment by wborn** [comment]
The MQTT embedded broker has been removed from OH3, see #8643, #8649.

**Comment by MikeTheTux** [comment]
Hmm, I'm not talking about the embedded broker, but the system broker configuration from `OH3`: `Settings` -> `MQTT system broker connection`

**Comment by jochen314** [comment]
I am not sure, I understand your configuration.
Can you please share the configuration of your system boker?

An please keep in mind, that the configuration assumes `secure` to be the default. If you broker is not secure, then you need to explicitly set `secure=false`

**Comment by MikeTheTux** [comment]
![grafik](https://user-images.githubusercontent.com/44850211/99914691-5a684e80-2cff-11eb-8eb6-065d06777042.png)

**Comment by MikeTheTux** [comment]
I guess I found the issue. Whenever you change something in the system settings, you have to derive the thing again.
