### ISSUE TITLE
Zwave - Fibaro Dimmer2 (FGD212) Scene Channel

### ISSUE THREAD

**Issue by christianwaite** [openhab/openhab-addons#910]
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/133

Is missing the scene channel, as discussed:
https://community.openhab.org/t/testing-z-wave-binding-on-openhab-2/7522/1237?u=christianjwaite

**Comment by cdjackson** [comment]
Can you add the XML file please - preferably from a reasonably recent version of OH2.

**Comment by christianwaite** [comment]
Sure, I've locked out my server though, so I'll do it tonight.

**Comment by pail23** [comment]
I have added the following to fibaro_fgd212_0_o.xml

`      <channel id="scene_number" typeId="scene_number">
        <label>Scene Number</label>
        <properties>
          <property name="binding:*:DecimalType">SCENE_ACTIVATION</property>
        </properties>
      </channel>`

Now it works. You can find my xml file here: [https://community-openhab-org.s3-eu-central-1.amazonaws.com/original/2X/a/a6c6f0c7fa9a0a4603798ff332fce8f6b53f09ee.xml](url)

**Comment by cdjackson** [comment]
Please can you provide the xml from the device - the link doesn't work.

**Comment by pail23** [comment]
I hope this time it works:

[node29.zip](https://github.com/openhab/openhab2-addons/files/278884/node29.zip)

**Comment by cdjackson** [comment]
I've now added this to the database - thanks.

**Comment by cdjackson** [comment]
Closing as the device was added. If there's still issues, please reopen and provide further information
