### ISSUE TITLE
[mielecloud] New binding: Miele Cloud

### ISSUE THREAD

**Issue by BjoernLange** [openhab/openhab-addons#9106]
This issue should serve as the enhancement issue for the new binding contribution of the Miele Cloud binding for openHAB 3.0.

Resources associated with the contribution:
- [Community discussion](https://community.openhab.org/t/miele-cloud-binding/93266)
- [Repository used for beta versions and issue tracking](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta)

We plan on opening a PR on 27th of November 2020.

**Comment by BjoernLange** [comment]
@kaikreuzer I think this issue can be closed, now that the binding got merged and released :smile:

**Comment by kaikreuzer** [comment]
Indeed!
