### ISSUE TITLE
[sonos] Item state not updating

### ISSUE THREAD

**Issue by flo-mic** [openhab/openhab-addons#9119]
On OH3 M3 the sonos binding is not retrieving any item state from the devices. All item states are null. Even after reinstalling the binding.

Sending commands is possible but more or less useless because I can not read the item state.

On OH3 M2 this was working without any issues. The issue started after replacing the docker container to OH3 M3.

**Comment by HazeHunter11** [comment]
I was able to solve the issue. It seams that the binding now uses also ports below 1024 for communication with the sonos devices. After editing my inbound firewall to allow any port of the sonos speaker ip and not only 1024-65534 the binding worked again without any issues.
