### ISSUE TITLE
Homekit Integration error when items have a Semantic Class

### ISSUE THREAD

**Issue by erling-henningsen** [openhab/openhab-addons#9126]
##Expected Behavior
Openhab Homekit Integration creates Homekit accessories for Openhab items when Apple Homekit Metadata is specified. And this works 
##Current Behavior
Openhab Homekit Integration also creates Homekit accessories for Openhab items without Homekit Metadata when a Semantic Class is defined.
##Steps to Reproduce (for Bugs)
The following item setup for a Group and a Semantic Class will create a Door accessory in Homekit.

 
![image](https://user-images.githubusercontent.com/49533202/100153079-ed41ee00-2ea3-11eb-84ba-2f26b5609d79.png)

##Environment
Openhab 3.0.0 M3 running on Pi4.
iPhoneX with IOS 14.3

**Comment by grzegorz914** [comment]
Same for me.

**Comment by J-N-K** [comment]
@yfre We should remove the old tag support for 3.0. WDYT?

**Comment by yfre** [comment]
> @yfre We should remove the old tag support for 3.0. WDYT? Would you create the corrresponding PR?

@J-N-K  yes, it is good idea. let use OH3.0 release to clean up. i will create PR.
