### ISSUE TITLE
[ipcamera] Make goto preset work with new Amcrest camera

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#9127]
## Expected Behavior
Goto preset should work.

## Current Behavior
Goto preset does not work. Tested with OH 2.5.9 and 3.0 M3.

## Possible Solution
https://community.openhab.org/t/ipcamera-new-ip-camera-binding/42771/2140?u=sidamos

## Steps to Reproduce (for Bugs)
Send goto preset to new Amcrest camera IP2M-841B-V3.

**Comment by Skinah** [comment]
Those changes are already merged, see here:
https://github.com/openhab/openhab-addons/pull/8948/commits/24cb8f63fc5b4d299a870fbf1cbe5e78582b1e33
I downloaded the M3 build and it appeared the changes were not included despite the change log mentioning the changes, will be interesting to see if the SNAPSHOT builds get it over the next few builds.

**Comment by sidamos** [comment]
There is an "x" besides this commit and another one in the PR https://github.com/openhab/openhab-addons/pull/8948

**Comment by Skinah** [comment]
I checked the code and it has been merged into MASTER. If something went wrong with the M3 build it should show up in SNAPSHOT as mentioned. I have been using the snapshot builds updating every few days and not had any issues so don’t stress if you think the unstable label is scary.

**Comment by Skinah** [comment]
Can you retest This please Using the latest MAIN code please? I suspect this report is in error as you were missing the recent changes that were merged when you just made your PR. Close this issue if it works.

**Comment by sidamos** [comment]
Yes, I can confirm that it works with the snapshot code. Thanks.
