### ISSUE TITLE
[ZWave] No way to leave exclusion mode

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab-addons#913]
When configuring the controller via paper ui there is only an option to "send" that action. Sadly this stays all the time and there is no way to unset it back to "default".

PS: Same for soft- and hard-reset.

**Comment by cdjackson** [comment]
This should be a 30 second timer, but currently it's not implemented. I will add this shortly.

> PS: Same for soft- and hard-reset.

No - these are single shot actions - it's not a mode you can enter and leave!

**Comment by cdjackson** [comment]
This should now be implemented, so closing. Any further issues, please feel free to reopen.

**Comment by thopiekar** [comment]
Okay. Thank you for adding this 👍
