### ISSUE TITLE
[shelly] Support for Shelly 1L

### ISSUE THREAD

**Issue by aflagge** [openhab/openhab-addons#9148]
Shelly launched the Shelly 1L
Couldn't find the coapDescr in thing properties, but see https://github.com/alexryd/homebridge-shelly/issues/221

[SHSW-L_settings.txt](https://github.com/openhab/openhab-addons/files/5609155/SHSW-L_settings.txt)
[SHSW-L_status.txt](https://github.com/openhab/openhab-addons/files/5609156/SHSW-L_status.txt)

**Comment by markus7017** [comment]
I already started implementation, please check https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true

**Comment by aflagge** [comment]
Hi Markus,
first, thanks for your work.

I loaded the latest binding:
67 │ Active │  80 │ 2.0.0                   │ Californium (Cf) Element Connector
268 │ Active │  80 │ 2.0.0                   │ Californium (Cf) Core
271 │ Active │  80 │ 2.5.11.202011291921     │ openHAB Add-ons :: Bundles :: Shelly Binding

But I get every few seconds an error message, see [openhab.log](https://github.com/openhab/openhab-addons/files/5617493/openhab.log)

Also now i have a [coapDeviceDescr.txt](https://github.com/openhab/openhab-addons/files/5617499/coapDeviceDescr.txt)

I updated also to latest firmware 1.9.2.

I see in PaperUI that there is only one input switch, but the hardware has to switch inputs.

**Comment by aflagge** [comment]
Hi Markus,
lastest DEV build works for me. Thanks.

**Comment by davorf** [comment]
Hello!
I just got Selly 1L and tried to integrate it in my OpenHAB installation, but then I found out it isn't yet supported (I have OpenHAB 2.5.10 on Raspberry Pi). I tried manually installing binding (adding it to addons folder), but every time I do, in bundle:list it says installed, but not active. I tried both, 2.5.11 and 2.5.12 version of snapshots. What am I doing wrong?

Best regards, 
Davor

**Comment by HarriPinter** [comment]
@aflagge and @markus7017 
Can we reopen this? I am asking because I cannot add Shelly1L to openhab 2.5.11 things. It still reports: 
- Unknown Shelly Device
- This device is currently not supported

I added Shelly1, Shelly1PM, Shelly Plug ... but Shelly1L is not working (for me).
I also tried the 2.5.12 binding and I tried openHAB3. Shelly1L is obviously not supported (?)

Any help or idea is highly appreciated.

**Comment by markus7017** [comment]
you need to switch to the 2.5.12 DEV build


---

Latest **DEV** build: [2.5.12](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.12-SNAPSHOT.jar?raw=true) - [3.1.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)
Note: The binding version included in the final OH 3.0 distro is significantly older than the DEV build. I can't make it in-time. Make sure you deleted older versions of the binding when installing the 2.5.12-SNAPSHOT or 3.1.0-SNAPSHOT if you are already on OH 3.
