### ISSUE TITLE
Enocean Issues with Eltako FGW14-USB

### ISSUE THREAD

**Issue by MrAtlantis646** [openhab/openhab-addons#9153]
![Unbenannt](https://user-images.githubusercontent.com/7769989/100483499-7dc53c00-30f9-11eb-884e-1bbccf94edab.JPG)

Receiving Data works just fine. Sending commands on the other hands doesn’t work.
Unbenannt|690x289 1

Maybe there is a bug in the EnOcean binding? It seems as OpenHab is sending with the ESP3 protocol instead of the ESP2? I’m running version 2.5.10

**Comment by fruggy83** [comment]
@MrAtlantis646 could you please post your bridge config here. Maybe you have really configured it to use ESP3 instead of ESP2.

**Comment by MrAtlantis646** [comment]
@fruggy83 Here the config and the config of one of the actuators
![Gateway Config](https://user-images.githubusercontent.com/7769989/102013779-7b4a1f80-3d52-11eb-9982-34288d364ce5.JPG)
![Actuator Config](https://user-images.githubusercontent.com/7769989/102013793-9157e000-3d52-11eb-917e-a53a728577c9.JPG)
![Actuator ID](https://user-images.githubusercontent.com/7769989/102013795-91f07680-3d52-11eb-98ac-ccf9474898c4.JPG)

**Comment by fruggy83** [comment]
@MrAtlantis646, thanks a lot for your screenshot.
I would suggest to remove the baseid of your bridge. Messages directly send on the bus do not need the full address, the offset is enough. This baseid is just needed if you have another device connected to the bus, which sends messages into it too and you want to mimic these messages.

**Comment by MrAtlantis646** [comment]
@fruggy83 Still no reaction of the actuator. I removed the BaseID of the Gateway and left the actuator as is. 

Maybe there is a mistake in my PCT14 config?

![PCT14](https://user-images.githubusercontent.com/7769989/102014704-a3884d00-3d57-11eb-9ab9-c54f7cd2d290.JPG)

**Comment by fruggy83** [comment]
@MrAtlantis646 PCT14 config looks ok. Did you setup it manually or did you a teach in from openhab? If you did the setup manually you could try the following:
 1. Remove this second entry in PCT14 and transfer the config to your FAM.
 2. Link the teach in channel of your FSB in openhab to an item, set the teach in message to FFF80D80 (channel config)
 3. Set your FSB into teach in mode, upper "Drehschalter" in position 180, middle "Drehschalter" in position LRN
 4. Switch your teach in item in openhab

Afterwards you should be able to switch your FSB from openhab. In this case reopen PCT14 and re-read the current config and post a screenshot here.

**Comment by MrAtlantis646** [comment]
@fruggy83  It's working now! Thank you so much for your help this Sunday 😃 

![PCT14_2](https://user-images.githubusercontent.com/7769989/102015701-6d4dcc00-3d5d-11eb-94bf-b9dfc3b73cee.JPG)

**Comment by fruggy83** [comment]
@MrAtlantis646 Did you see the difference between your first and second PCT14 config screenshot. Just remember, if you connect openhab to the FAM the ID is 00 00 00 SenderId, if you connect it to your FGW the id is 00 00 01 SenderId. I am currently not sure which EnOceanId you have to set up in openhab to receive the status updates of your FSB. I would guess 00 00 00 06, but I am not sure. Would be nice if you could validate this and post your results here. Thanks a lot in advance.
