### ISSUE TITLE
getHandler() returns NULL after configuration update

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-addons#92]
After I make an update though paperUI/REST UI for an item, seems the thing().gethandler() returns a NULL. Which causes the child things to not find the handler anymore.

workaround seems  to call getThing().setHandler(this) in the bridgehandler when a bridge is updated

e.g. the childs have this code where handler will return NULL after the update

``````
Bridge bridge = getBridge();
    if (bridge == null) {
        logger.debug("Required bridge not defined for device {}.", maxCubeDeviceSerial);
    return null;
    }
ThingHandler handler = bridge.getHandler(); ```
``````

**Comment by dnobel** [comment]
There is a bug in the ThingManager class. After a thing is updated through the REST interface a new instance of the thing object is created. But the ThingManager does not refresh the internal thing cache on updates (ThingManager#thingUpdated). So its a serious bug in the core of Eclipse SmartHome.

**Comment by dnobel** [comment]
Created a bug in the ESH bug tracker for it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=456528

**Comment by kaikreuzer** [comment]
Fixed in ESH with https://github.com/eclipse/smarthome/pull/151.
I will make it available in the openHAB2 target platform tomorrow

**Comment by kaikreuzer** [comment]
New target platform is now available with https://github.com/openhab/openhab2/commit/ab84b5cc9f12d71fd99588fb5ab44c811d1aa900.
