### ISSUE TITLE
[lcn] sendDynymicText does not work if strings have 12, 24, 36 characters

### ISSUE THREAD

**Issue by harteknut** [openhab/openhab-addons#9208]
## Expected Behavior
String is shown on display (e.g. LCN-GT4D) when using action **_sendDynamicText_**

## Current Behavior
String is not shown on LCN-GT4D if it has a length of 12, 24, 36 characters.
No error log entry in openHAB log, no error in LCN Busreport

## Used Environment
Bug was found on openHAB 2.5.10-1 on Raspberry Pi 4 Model B Rev 1.1 and using LCN-PKE.

**Comment by fwolter** [comment]
I can confirm this with LCN-GT10D firmware 8.0. This seems to be a bug in the display firmware. I added a workaround that adds a space if the length of the text is a multiple of the chunk lengths (which is 12 bytes).
