### ISSUE TITLE
[bluetooth] Duplicate RSSI channel

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#9217]
Doesn't PR https://github.com/openhab/openhab-addons/pull/8813 have to be applied to all bluetooth bindings (e.g. also ruuvitag)? I don't use the other ones, but have had issues with the duplicate RSSI channel using the binding I currently develop (handler initialization failed because of duplicate RSSI channel).

**Comment by cpmeister** [comment]
This is already fixed in OH3.0.  But the fix was never backported to 2.5.x.

**Comment by pfink** [comment]
So should new bindings contain the RSSI channel in their OH-INF or not?

**Comment by cpmeister** [comment]
New binding don't have to since they will be added automatically.

If you want to fix the bug locally for development, take a look at https://github.com/openhab/openhab-addons/commit/bb9a286167f94f114f921a1303a2838cd1aadbe4.

**Comment by pfink** [comment]
So maybe we should define **not** adding them to OH-INF as the best practice and remove it from all bindings where it is not needed?

**Comment by cpmeister** [comment]
I agree.

**Comment by cpmeister** [comment]
Since this bug is already fixed in the latest version I'm going to close this.
