### ISSUE TITLE
[shelly] Avoid using  org.apache.commons.lang.*

### ISSUE THREAD

**Issue by markus7017** [openhab/openhab-addons#9220]
Building the binding code brings up
```
[WARNING] org.openhab.binding.shelly.internal.handler.ShellyBaseHandler.java:[29]
The package org.apache.commons.lang.time.StopWatch should not be used.
```
Packages org.apache.commons.lang are going to be removed with final 3.0 distro. The code has to be replaced by native Java code.

**Comment by markus7017** [comment]
will be replaced by native java code

**Comment by markus7017** [comment]
@fwolter I implemented the change, but the PR will most likely not make it into 3.0 initial release (because it contains features and we passed feature freeze). Does this screw up compatibility = will apache.commons.lang technically removed in 3.0.0 and binding will fail to load?

**Comment by fwolter** [comment]
As far as I know bindings using Apache Commons will continue to work with OH3.

**Comment by markus7017** [comment]
ok, nevertheless it will be fixed with the upcoming PR
