### ISSUE TITLE
[linky] Takes 1 second to dispose the handler + Invalid cookie 

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#9231]
Don't know why the bindiong requires 1 second to dispose the handler.
Additionally, you can see an error related to cookie.
```
21:10:32.541 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'linky:linky:local' changed from ONLINE to UNINITIALIZED
21:10:33.450 [ERROR] [java.net.CookieManager               ] - Invalid cookie for https://www.xxxxxxxx/: HttpOnly;Secure
21:10:33.473 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'linky:linky:local' changed from UNINITIALIZED to UNINITIALIZED (HANDLER_MISSING_ERROR)
```

**Comment by lolodomo** [comment]
I easily imagine that the "problem" is in this method:
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.linky/src/main/java/org/openhab/binding/linky/internal/api/EnedisHttpApi.java#L161

3 HTTP requests, it could explain the 1 second.

@clinique : is this code really necessary ?

**Comment by clinique** [comment]
Yes, it is the real unlog process...

**Comment by lolodomo** [comment]
You really need 3 HTTP calls ?
Any chance to avoid the cookie error ?

**Comment by lolodomo** [comment]
I close this issue, considering @clinique answer.
