### ISSUE TITLE
[deconz] Open Window Detection as Channel for Thermostat thing

### ISSUE THREAD

**Issue by sodalu** [openhab/openhab-addons#9233]
I'm using the Danfoss Ally Thermostats in openHAB and would love to use a channel with the information about the "Open Window Detection". @J-N-K Is it possible to enhance the binding?

**Comment by J-N-K** [comment]
Please show the REST API response for that device. Thanks.

**Comment by sodalu** [comment]
Sorry for the delay, here the REST API device information

    "11": {
        "config": {
            "battery": 91,
            "displayflipped": null,
            "heatsetpoint": 2100,
            "locked": null,
            "mountingmode": null,
            "offset": 0,
            "on": true,
            "reachable": false,
            "schedule": {},
            "schedule_on": null
        },
        "ep": 1,
        "etag": "6ee6648df7b0e82a94a7b2a714dd669d",
        "lastseen": "2020-12-03T04:32Z",
        "manufacturername": "Danfoss",
        "modelid": "eTRV0100",
        "name": "Heizung_Bruno",
        "state": {
            "errorcode": null,
            "lastupdated": "2020-12-03T04:48:56.475",
            "mountingmodeactive": false,
            "on": true,
            "temperature": 1428,
            "valve": 100,
            "windowopen": "Closed"
        },
        "swversion": "01.02.0008 01.02",
        "type": "ZHAThermostat",
        "uniqueid": "14:b4:57:ff:fe:d3:57:a8-01-0201"
    },

**Comment by J-N-K** [comment]
That's possible. One question: is that an input or an output? I.e. do we need to provide that value to the thermostat or is the thermostat reporting that value?

**Comment by sodalu** [comment]
I'm mostly using the Phoscon App together with the openHAB deconz binding, so I'm not an expert in the deconz application but I found an excel file attached in another [issue discussion](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3591#issuecomment-722085204) that stated "windowopen" as readonly attribute. (It's on the second sheet of the excel in line 68)

**Comment by J-N-K** [comment]
Ok. Will add that later today.

**Comment by J-N-K** [comment]
@sodalu, do you use OH3?

**Comment by sodalu** [comment]
> @sodalu, do you use OH3?

Not yet but would like to upgrade in near future
