### ISSUE TITLE
Update CODEOWNERS for bluetooth bindings

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#9236]
@cdjackson and @kaikreuzer are the current CODEOWNERS for the bluetooth bindings, although those bindings have been mostly completely rewritten by other users, and Chris as well as Kai did not seem to be much involved into that. So maybe we should update the CODEOWNERS for these bindings accordingly?

Looping @cpmeister @paulianttila @blafois

**Comment by cpmeister** [comment]
I'm fine with getting labeled code owner for all of them. I don't know about the others though.

**Comment by kaikreuzer** [comment]
Yeah, I agree that @cpmeister would be the best choice as being listed as a CODEOWNER on it! 👍
