### ISSUE TITLE
[mqtt.homie] [OH3] Hyphen (-) translated to "_2D" in channel definition

### ISSUE THREAD

**Issue by schmidmuc** [openhab/openhab-addons#9240]
## Expected Behavior
I have a homie device with name "smartdevice" which publishes a node with name "dht22-room".
Information are sent from the device via mqtt via
homie/smartdevice/$nodes = dht22-room
homie/smartdevice/dht22-room/$name = room
homie/smartdevice/dht22-room/temperatur = 22
[and so on]

This node should show up in OH3 with a channel id 
mqtt:homie300:1234567890:smartdevice:dht2_room#temperatur

## Current Behavior
Instead of above behaviour the channel shows up with the following id:
mqtt:homie300:1234567890:smartdevice:dht22_2Droom#temperatur

As it can be seen, the hyphen (-) is replaced with "_2D".

This should not be done because the hyphen is a regular character.
Please see the homie convention specification here: https://homieiot.github.io/specification/

## Possible Solution
Leave the hyphen untouched and do not translate it to "_2D"

## Steps to Reproduce (for Bugs)
Create a node with an hyphen.

## Your Environment
* Version used: openHAB 3.0.0.M3 / openHAB 3.0.0.M4 (tried on both versions)
* Environment name and version: Chrome 87.0.4280.88
* Operating System and version: Ubuntu 20.04 LTS

**Comment by jochen314** [comment]
Sorry, but I do not understand your problem.

What is not working for you?
Your are talking about the **internal** id of the channel. Nothing in there is covered by the homie spec. We could generate random numbers als well as long as the interaction with the devices works fine.
As far as I can see, the conversion to and from the **internal** id to the *real* value is done whenever needed.

**Comment by schmidmuc** [comment]
Thanks for the feedback. You are right, channel id and homie topic are not linked. For me it would have been more "logical" that these ids are identical, to make configurations easier.
