### ISSUE TITLE
[mqtt] stops processing events after thing configuration update

### ISSUE THREAD

**Issue by skrobul** [openhab/openhab-addons#9242]
## Expected Behavior
I'd expect the binding to continue processing data just the same as after first start. By "processing" I mean both consuimg inbound and producing outbound MQTT messages.

## Current Behavior

I have started building my MQTT configuration and had all sorts of problems where I thought it works intermitttently. After lengthy troubleshooting I found out that the binding completely stops reacting to any external actions such as receiving message from a broker as result of someone pressing hardware switch, or sending a command/changing state of an item in openhab.

My configuration is pretty minimal:

**mqtt.things**

```
Bridge mqtt:broker:main [ host="localhost", clientid="openhab", secure=false, enableDiscovery=false ] { 
  Thing topic wireless { 
    Channels: 
    Type string : click "click" [ stateTopic = "zigbee2mqtt/0x00158d000454fdf6/click" ]
  }

 Thing topic LivingRoom_LightSwitch { 
    Channels:
    Type string : action "action" [ stateTopic = "zigbee2mqtt/LivingRoom_LightSwitch/action" ]
    Type switch : left "left" [ 
      stateTopic = "zigbee2mqtt/LivingRoom_LightSwitch/state_left", commandTopic = "zigbee2mqtt/LivingRoom_LightSwitch/left/set", on="ON", off="OFF"
    ]
 }
}
```

**mqtt.items**
```
String SW2 { channel="mqtt:topic:main:wireless:click" }
Switch LivingRoom_LightSwitch_LeftState "Left [%s]" <switch> {channel="mqtt:topic:main:LivingRoom_LightSwitch:left"}
```

Now, both items work perfectly when they are added for very first time. After changing absolutely **anything** in the things file, the binding seems to drop current subscriptions, reconnects to the broker and resubscribes but that's about it.

I have attached a debug log that shows the problem:
[mqtt_bugreport_20201205_1208.txt](https://github.com/openhab/openhab-addons/files/5647024/mqtt_bugreport_20201205_1208.txt)

The timeline of interesting events is as follows:
* `11:54:08.734` I click the hardware switch and it is received by OH correctly.
* around `11:54:15` I have updated `mqtt.things` by changing `Type string : click "click"` to `Type string : click "CLICKY"` to simulate the change
* around `11:54:20` and after, I repeat the same action of pressing the same hardware switch

I have verified following things:
* the inbound messages are definitely published on the relevant MQTT topics.
* after the switch is pressed, those messages are being delivered to openhab process (verified on the network level with tcpdump)

In other words, this seems to happen when the binding reloads the configuration. 

The only workaround I was able to find is to execute `bundle:restart org.openhab.binding.mqtt.generic` in the console, after which everything comes back to live almost immediately.

## Possible Solution
For a minute I thought it might be related to the binding failing to unsubscribe from the Homie and Homeassistant
discovery topics even when the `enableDiscovery` is set to `false` , because it's not subscribed in the first place but
temporarily setting it to `true` did not  make a difference.

## Steps to Reproduce (for Bugs)
1. Configure basic Bridge + topic thing with at least one channel. 
2. Configure an item that links to that channel
3. Verify that it works as expected.
4. Force binding to reload thing configuration by making any trivial configuration change (i.e. change label)
5. It does not work anymore.

## Context
Nothing complicated here, just trying to setup few zigbee switches through zigbee2mqtt.

## Your Environment

* Version used: openhab 2.5.10, 
* openjdk version "1.8.0_152", nodejs : v12.20.0
* OS: openhabian running on Rpi 3
* Broker: mosquitto 1.4.10-3+deb9u4, installed on the same machine
* mqtt binding  2.5.10, installed through PaperUI

**Comment by lsiepel** [comment]
@skrobul unfortunately this issue wasn't picked up earlier. As many changes to mqtt binding and openHAB runtime have been committed, it would be wise if you can confirm this issue is still occuring on openHAB 4.1.x

**Comment by skrobul** [comment]
@lsiepel no worries:) unfortunately I won't be able to test this, I don't have the hardware nor the software anymore, sorry

**Comment by benderl** [comment]
I do not now exactly if my described problem here is related to this issue, but it seems familiar for me.
https://community.openhab.org/t/home-assistant-auto-discovery-zigbee2mqtt-restart-makes-things-not-responding/154217

Tested with openHAB 4.2.0 Build #3945 and Zigbee2MQTT 1.35.3 commit 8b694432
