### ISSUE TITLE
[powermax] Expose panel status messages, and/or add a zone status to each Zone Thing

### ISSUE THREAD

**Issue by ronisaacson** [openhab/openhab-addons#9250]
(Copied from https://community.openhab.org/t/powermax-binding/2824/289)

I see that you’re triggering the alarm_active channel when you get an 0xA5/0x04 message with bit 7 set in the system state flags (sysFlags in PowermaxStatusMessage.java). However, I’ve found that this only represents a _potential_ alarm condition, not necessarily a real one.

For example: if your system is armed and you violate a Delay zone (e.g. open your front door), you’ll immediately get a bit 7 message. If you walk to the keypad and disarm within the Delay period then there’s no alarm condition. If you don’t, then you have a real alarm. But the binding isn’t raising any event that correlates with this. If you want to write a rule that triggers on “my alarm is currently ringing,” there’s no way to do that.

A much better state for this is in the 0xA7 panel status message. You’re already decoding these in PowermaxPanelMessage.java but not really doing anything with them. In the example above, where you violate a Delay zone and then fail to disarm, you’ll get an 0xA7 message with an 0x03 (Delay Alarm) event at the instant the alarm starts ringing. Then it sends one of the Restore messages when it stops ringing. (0x1C General Restore if you disarm, and I’m not sure which one if you let it ring until the timeout.)

In any case… the 0xA7 messages are really useful. It would be great to have a channel that exposes these so you can trigger on various events. The system_status channel is useful but not detailed enough, and it’s a comma-separated list which you have to parse if you want to use it in a rule.

I’m also thinking about adding a Status channel to the Zone thing so you can more easily monitor and trigger on updates by zone. That channel could update on either an 0xA5 or 0xA7 message that affects the zone.

**Comment by lolodomo** [comment]
You are welcome if you want to propose improvements.
I would like to avoid updating the behavior of the existing channels. But I am open for additional channels.
The channel alarm_active with its current behavior has sense even if its name is maybe not ideal.

What panel model do you own ?

**Comment by ronisaacson** [comment]
Thanks, agreed on not changing the existing channels. I have a Powermax+. I'm doing some testing now and will have a PR for you soon.

**Comment by lolodomo** [comment]
I will be able to validate your changes with a PowermaxPro.

**Comment by lolodomo** [comment]
Don't forget we have the channel alert_in_memory which matches your need or at least partially your need.

**Comment by lolodomo** [comment]
@ronisaacson : any progress in the enhancements you mentioned?

**Comment by bash-tp** [comment]
@lolodomo yes I did a bunch of work on this but then got distracted by other things. Give me a few days and I'll come back with an update!

**Comment by ronisaacson** [comment]
@lolodomo yes I did a bunch of work on this but then got distracted by other things. Give me a few days and I'll come back with an update!

**Comment by ronisaacson** [comment]
Hey @lolodomo just want to give you an update: I have this almost fully working with some new channels. One of my goals was to replicate the list of active conditions you can scroll through on the keypad whenever there's an alarm or trouble indicator.

It's tricky because certain conditions are set by one message and cleared by another message (e.g. a tamper message, followed later by a tamper restore) and the stateless nature of PowermaxState doesn't lend well to persistence. I've got one possible approach though, and I'll open a PR in the next few days for you to review.
