### ISSUE TITLE
Sensebox lumination

### ISSUE THREAD

**Issue by heiler** [openhab/openhab-addons#9256]
The Luminance/Illuminance is not shown. in the openhab.log is remarked:

`[DEBUG] [box.internal.handler.SenseBoxHandler] - Command received for an unknown channel: measurements#luminance`

My item is:

`Number:Illuminance   Illuminance   "Illuminance [%.2f %unit%]"      <light>         { channel = "sensebox:box:5ae77940:measurements#luminance" }`

In the addon documentation both terms are used. Could someone check this?

I enclose two screenshots.
![Bildschirmfoto vom 2020-12-06 12-02-04](https://user-images.githubusercontent.com/2920260/101278742-ec6f5d00-37bd-11eb-97d2-ac381170ada4.png)
![Bildschirmfoto vom 2020-12-06 12-10-05](https://user-images.githubusercontent.com/2920260/101278743-ed07f380-37bd-11eb-9d35-ec43a4a81191.png)

**Comment by J-N-K** [comment]
I don't see a reference to `measurements:luminance` in the documentation. Where did you find that?

**Comment by heiler** [comment]
In the documentation you can find "Illuminance" in the description of channels  and items, Iuminance in the description of the sitemap. I followed the wording in the thing description in the PaperUI.

**Comment by J-N-K** [comment]
How did you define the thing? With Paper UI?

**Comment by heiler** [comment]
With PaperUI, the version is 2.5.10.

**Comment by J-N-K** [comment]
Delete the thing and re-create. The channel-name was changed in #4507, nearly two years ago in 2.5.0 This was also in the release-notes back then: https://github.com/openhab/openhab-distro/pull/84.
