### ISSUE TITLE
[networkupstools] Add status CHRG to ups-status options

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-addons#9276]
## Expected Behavior
APC UPS returns status "OL CHRG" while charging. openHAB only recognizes the "0L".

Add
``` 
<option value="CHRG">Charging</option>
``` 
under 
``` 
<channel-type id="ups-status">
```

**Comment by lolodomo** [comment]
Is the option value to add "OL CHRG" or "CHRG" ?

**Comment by sidamos** [comment]
I have done some more testing and I confirmed that we need:
``` 
				<option value="OL CHRG">Online charging</option>
				<option value="OL CHRG LB">Online charging low battery</option>
``` 
And probably also:
``` 
				<option value="OL LB">Online low battery</option>
``` 
I don't know, if other combinations can also happen.

**Comment by lolodomo** [comment]
So the problem is rather that the value would be a combination of states while the binding expects one unique state ?
Is it a good approach trying to cover all combinations in the list of options ?

**Comment by lolodomo** [comment]
Rather than a static list of options, maybe the binding should parse the value and build the status considering multiple states in the value.

**Comment by lolodomo** [comment]
My proposal would be a breaking change and rules based on this channel should be updated. Not ideal.

**Comment by lolodomo** [comment]
Other proposal, we reduced the value to its last part, so "OL CHRG" would be reduced to "CHRG" and the option will be correctly found.

**Comment by sidamos** [comment]
We would lose information. "OL CHRG LB" would show "Low battery" only.

I do not think that ALL combinations can happen, so I would add those that could happen.

**Comment by lolodomo** [comment]
In your examples, there are in order of priority, from low to high.
I imagine you will have with the time first "OL CHRG LB" then "OL CHRG" and finally "OL".

**Comment by sidamos** [comment]
That seems to be correct.

**Comment by sidamos** [comment]
BTW, for your proposal, "CHRG" will still need to be added.

**Comment by lolodomo** [comment]
Yes.

**Comment by lolodomo** [comment]
Finally, we could just add the 3 missing values you identified. My previous proposal was leading to a truncated status. 
I am going to fix that today.
