### ISSUE TITLE
[remoteopenhab] large response from REST API causes COMMUNICATION_ERROR

### ISSUE THREAD

**Issue by bern77** [openhab/openhab-addons#9281]
I'm running 2 OH instances in my house and I'm really happy about the new remoteopenhab binding which should make the MQTT based workaround to connect the instances obsolete. Thanks for this valuable contribution!

Trying to establish a connection with one of my instances from an OH3 test instance showed the behavior described under "Current Behavior". This instance uses the DoorBird binding which provides Image channels for camera stills. The linked items' state is the corresponding Base64 encoded image, leading to a substantially sized response from the REST API. In my case the response body contained 2323008 bytes and thus exceeded the below mentioned buffer capacity, preventing the bridge to become ONLINE.
Removing some if the image items immediately solved the problem.

## Expected Behavior
If the OH instance which should be integrated via the binding is online and reachable via the network, the binding should have the status ONLINE, regardless of the size of the response.

## Current Behavior
When requesting the remote instance' items via its REST API (URL http://<remote-instance-ip>:8080/rest/items?recursive=false) a response exceeding a buffer size of 2097152 bytes causes a COMMUNICATION_ERROR with the following error message:
`Failed to get the list of remote items using the items REST API: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Buffering capacity 2097152 exceeded`

## Possible Solution
The problem seems to root in the `FutureResponseListener`'s limitation to 2MB.
Probably switching to another approach (asynchronous) will be necessary.

## Steps to Reproduce (for Bugs)
See above introduction...
1. Create items of type Image and update them with image data
2. Check that URL http://<remote-instance-ip>:8080/rest/items?recursive=false returns a response exceeding 2097152 bytes
3. Connect remoteopenhab binding to this instance

**Comment by lolodomo** [comment]
Interesting issue.

First, I see in the items API a field to restrict to certain fields the content of the response. I should use this to reduce the size of the response to what I really need. Should not be sufficient if you have a lot of items with big images. As a reminder, this request is run hopefully only at binding startup.

Second I could search if it is possible to extend this limit of 2 Mb with a setting in the code.

Third, I could have one request including sall items except images + one request to list image items without their state + one request for each image item to get the state (image). There is one parameter in the API to filter on item type. I don't know what is the syntax to ask all item types different from "Image".

**Comment by bern77** [comment]
I believe as soon as you have an image item's state exceed the buffer limit (which is not unlikely) the filtering approaches will not suffice. You can of course limit the fields you request; if you exclude the state then this should work for initializing the bridge.
But once a single image item has a state >2MB the problem will resurface. IMHO the issue is in `RemoteopenhabRestClient.executeUrl`. `request.send()` uses the above mentioned `FutureResponseListener` with its limitation and it seems to me this is the central point of sending requests to the REST API.

**Comment by lolodomo** [comment]
It depends on the isze of your images. I did not encounter the problem while I got album arts for example, but only small PNG files.

So you think it is the default response content listener which is limiting the response size to 2MB ?
It seems possible to override this default response content listener. This is your proposed solution ?

**Comment by lolodomo** [comment]
Ok, I found an example with an asynchronous reading of the response.

**Comment by lolodomo** [comment]
Any idea how I could set a big image to an item and so reproduce the issue?

**Comment by bern77** [comment]
Hi, sorry for the late replay, for some reason I had deactived email notifications for comments on Issues & PRs.
Great to see you already found solutions for the immediate problem! 😊

Regarding a suitable test approach for large images I thought assigning a Base64 encoded image as text to an Image item via REST should do the job but so far I've not succeeded (Status 400).

**Comment by lolodomo** [comment]
I have now just proposed a workaround to avoid the bridge thing being OFFLINE but this is not a full solution. In your case, the items will not be initialized at binding startup.

**Comment by lolodomo** [comment]
And even if I replaced one API call by 2 API calls, the amount of data transfered has been reduced. That is an improvement for everybody.

**Comment by bern77** [comment]
Yes, I think this really does solve the immediate problem very well.

I'm not sure, but I just think that it would still be good if also larger images could be processed, just in case. Otherwise the issue might resurface some time down the road when a Photobucket binding or something like that is introduced 😉
I've not given up and will try a few more things to enable testing for larger images...

**Comment by bern77** [comment]
Hm, I don't seem to find a way to simply assign an image to an item.
The approaches I can think of would be to

- either implement a stub binding to read image data from a file and assign this to an item. Seems like a lot of effort...
- or to use persistence on an Image item, changing the persisted data in the databse before restoring.

For my specific use case the latest version of your binding works like a charm, though - so personally, I'm good for now 😉

**Comment by lolodomo** [comment]
> I'm not sure, but I just think that it would still be good if also larger images could be processed

That's the reason why the issue is still opened.

To fix it, I need first to be able to reproduce it and as you noticed, this is clearly not something obvious. One solution could be to duplicate an Image item I have until the 2 MB limit is reached.

**Comment by lolodomo** [comment]
My second request with state has size around 290 KB with my current OH3 server.
My camera image size is around 144 KB.
So with around 15 items linked to this channel, I should reach the 2 MB limit.

**Comment by lolodomo** [comment]
Reproduced just now.

**Comment by lolodomo** [comment]
The problem is fixed. The API response can now be bigger than 2 MB.

**Comment by bern77** [comment]
Awesome, I can confirm this works perfectly now 😊
Thanks!
