### ISSUE TITLE
Sonos Binding: Notification is staring stream

### ISSUE THREAD

**Issue by meyercg** [openhab/openhab-addons#9293]
If a stream is currently paused for the sonos speaker and a notification was played that has a longer duration than the timeout setup in the configuration the stream is started afterwards. 

## Expected Behavior
Stream should only start after a notification was played if the stream was running before

## Current Behavior
A paused stream is started after a notification was played

## Steps to Reproduce (for Bugs)
1. Start any stream with your sonos. 
2. Play a notification which is longer than the configured timeout.

## Your Environment

* binding-sonos - 2.5.10
* openHAB 2.5.10 Release Build

**Comment by lolodomo** [comment]
I wil fix it if I can reproduce it. 
Does it depend on the kind of the paused stream?

**Comment by meyercg** [comment]
Most of the time I have this stream opened. Because it is my default stream that is set via a rule.

sendCommand(SON_uri, "x-rincon-mp3radio://http://sr.audiostream.io/sr/1009/mp3/128/sr1")

But I ca test if it occours with otherr streams as well. Does it not ouccur in your setup?

**Comment by lolodomo** [comment]
I have no notification exceeding the default 20 seconds timeout. This is not very common to have such long notification.

**Comment by lolodomo** [comment]
Yes please try with another source.

**Comment by lolodomo** [comment]
I can't reproduce.
I am playing a Amazon Music track then I pause the playback and finally I use the console with command `openhab:voice say` to say a long notification.
The notification is interrupted and then my Sonos is back on my Amazon Music track and is paused.

**Comment by meyercg** [comment]
I just testet with amazon and it happened again.

- timout set to 5 seconds
- Amazon Playlist started and paused via sonos App
- Notification played with a rule (but with say as well in the rule)
- Notification was interrupted and the playlist starts again.

crazy

**Comment by meyercg** [comment]
If you can't reproduce should I close the "bug" because it is not a big issue and I can solve it by setting a larger timeout. Or do you have any idea what I can do to support you finding the reason?

**Comment by lolodomo** [comment]
You just have to find the clear case that trigger the issue.
Is it only with a certain kind of source ?
It looks like the URL you provided is a WEB radio I have access to. I will try with this WEB radio.

And yes, as a workaround until it is fixed, you could increase the default timeout.

**Comment by meyercg** [comment]
Dear lolodomo, I installed the last updates for my sonos. restarted openhab and now the strange behaviour on my side is gone. So I will close the bug. But I'm still wondering why it happened before. Thanks for your support and wish you all the best.
