### ISSUE TITLE
[homekit] LightSensor and AirQualitySensor characteristics not available in Main UI

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#9310]
Hi,

In OH3 UI LightSensor is not available in The list of available HomeKit charcteristics.

**Comment by diRk262** [comment]
I can confirm, LightSensor Metadata for HomeKit is missing in OH3.
![11A107B7-5143-456B-A38F-632C93A7BBFD](https://user-images.githubusercontent.com/76136884/102423430-4f0bf880-4009-11eb-9a35-240d96f04590.jpeg)

**Comment by Cossey** [comment]
It should also be noted that neither is the Air Quality metadata.

**Comment by Cossey** [comment]
Can you please transfer this issue to openhab/openhab-webui @kaikreuzer - I am unable to do so.

**Comment by Cossey** [comment]
PR resolving this has been merged.
