### ISSUE TITLE
[deconz] Add support for deCONZ scenes

### ISSUE THREAD

**Issue by katiuskt** [openhab/openhab-addons#9329]
## Your Environment

* Version used: openHAB 3.0 M5+
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker snapshot

First of all, please take into account this is my first request ever in github so please, forgive me if I'm not filling this properly. I've tried to read the contributing help and I've also searched just to avoid duplicated requests and I wasn't able to find it so... here I am :-)

I came from HA and their support for deconz includes the **support for deconz scenes** (https://www.home-assistant.io/integrations/deconz/#scene) and I would love to have them also supported in openHAB as in now it seems created scenes in Phoscon/deCONZ are no visible from OH. No "things" are detected for those scenes and they aren't shows as supported things: https://www.openhab.org/addons/bindings/deconz/

Why consider that support could be interesting? Because creating scenes both in Phoscon (deCONZ web gui) or with mobile apps like "Hue Essentials" (*) is quite simple and easy and portable: once you've created for instance "Scene for TV", "Scene for reading" and if OH could support them, you could only send a command like "activate scene X": you don't need to deal with with brightness, colors, lights are on/off and configure that in OH because you already have an scene you can use with other apps (there is a Hue Essential app for Android TV, for instance) as they are managed by Phoscon/deCONZ itself.

(*) One cool thing of that app is you can create and scene from an image. As you can do with the official Hue app but without need to have the Hue bridge.

Taking a look at the Philips Hue binding doc (https://www.openhab.org/addons/bindings/hue/) it does support scenes so I guess OH framework is able to manage them hence to have or not support for them relies on bindings themselves and that's why I raise this request to add its support in deCONZ binding if you also consider it a good idea.

Thank you in advance

**Comment by J-N-K** [comment]
Good point. Will look into that. But this will be a post-OH 3.0.0 feature. I don‘t have time before the release to implement it

**Comment by katiuskt** [comment]
> Good point. Will look into that. But this will be a post-OH 3.0.0 feature. I don‘t have time before the release to implement it

Oh, it will be great, thank you! Really glad to see you like the idea too 😊
Totally expected you guys are focusing on OH3 release (great job! thanks for that!) so no problem at all if it cames in a later release. If needed by then, I could try to help testing (no code skills at all but see if it works or not in my system... I think I could do that)
