### ISSUE TITLE
[mainui] Generated item-names in Main UI are not unique if channels are part of a group

### ISSUE THREAD

**Issue by kjasdal** [openhab/openhab-addons#9374]
## Expected Behavior
When creating Items from Things, the proposed names should be unique. 

Example: 
```
Channel 'systeminfo:computer:odin:memory#availablePercent'
=> Localcomputer_MemoryAvailablePercent
Channel 'systeminfo:computer:odin:storage#availablePercent'
=> Localcomputer_StorageAvailablePercent

Channel 'systeminfo:computer:odin:memory#usedPercent'
=> Localcomputer_MemoryUsedPercent
Channel 'systeminfo:computer:odin:storage#usedPercent'
=> Localcomputer_StorageUsedPercent

```
## Current Behavior
When creating Items from Things, the proposed names are NOT unique. 

Example:
```
Channel 'systeminfo:computer:odin:memory#availablePercent'
=> Localcomputer_Available
Channel 'systeminfo:computer:odin:storage#availablePercent'
=> Localcomputer_Available

Channel 'systeminfo:computer:odin:memory#usedPercent'
=> Localcomputer_Used
Channel 'systeminfo:computer:odin:storage#usedPercent'
=> Localcomputer_Used
```

## Steps to Reproduce (for Bugs)
1. Added 'systeminfo' binding.
2. Scanned for Things. 
3. Added 'Local computer'.
4. Went into dialog to create Items from Thing channels: 
5. Used option to "Create a new Item", and got a proposed Name for the item.

## Your Environment
Ubuntu 20.04
openHAB 3.0.0.M5
Docker container

**Comment by J-N-K** [comment]
@ghys, can you have a look? @wborn can you transfer this issue tu the UI?

**Comment by ghys** [comment]
Just noticed this was reported in https://github.com/openhab/openhab-webui/issues/549 and I missed it. I've reopened this issue, so no need to transfer this one.
