### ISSUE TITLE
[xmppclient] Could not establish connection to XMPP server 'a.b.c.d:5222': null

### ISSUE THREAD

**Issue by WelterRocks** [openhab/openhab-addons#9378]
[XMPP] addon is unable to connect to servers with Could not establish connection to XMPP server 'a.b.c.d:5222': null, since last update of OH.

Log says:
[esoftware.smack.filter.IQReplyFilter] - Rejected potentially spoofed reply to IQ-packet. Filter settings: packetId=AABBCC-1, to=null, local=null, server=xmpp.server.local. Received packet with from=openhab@xmpp.server.local
[hab.action.xmpp.internal.XMPPConnect] - Could not establish connection to XMPP server 'a.b.c.d:5222': null

Already tried to downgrade DH to 2048 and 1024 bit, but still not working. Also tried with and without encryption.

Error comes with ejabberd, prosody and openfire.

OH version is 2.5.11

**Comment by lsiepel** [comment]
@pavel-gololobov created the xmpp binding, maybe he can be of any help if this is still an issue?

**Comment by lsiepel** [comment]
I just made a new draft for XMPPclient binding related to a diffent but somewhat related change. If possible could you test and let me know if the problem you have still exists?
openHAB 3.4.2: https://1drv.ms/u/s!AnMcxmvEeupwjqVFDy9C1Eh--QOA5g?e=P1pKSa
openHAB 4.0.0: https://1drv.ms/u/s!AnMcxmvEeupwjqVFDy9C1Eh--QOA5g?e=7j3aZM

A debug log would help, including the server + version you are connecting to.

**Comment by lsiepel** [comment]
@WelterRocks  are you available to perform a test?
