### ISSUE TITLE
[astro] getAzimuth(ThingActions, ZonedDateTime) from the type AstroActions refers to the missing type Object

### ISSUE THREAD

**Issue by DaToBi-89** [openhab/openhab-addons#9381]
from the openHAB community forum https://community.openhab.org/t/astro-getelevation-has-missing-type-object/108945

## Current Behavior
the getAzimuth() ant get Elevation() Actions generate a warning when used in a rule:

`16:34:16.758 [INFO ] [del.core.internal.ModelRepositoryImpl] - Validation issues found in configuration model 'astro.rules', using it anyway:
The method getAzimuth(ThingActions, ZonedDateTime) from the type AstroActions refers to the missing type Object`

## Possible Solution
Change the return type of the functions from 

`QuantityType<Angle>`

to

`QuantityType<Number>`

## Steps to Reproduce (for Bugs)

the rule where it is used:

```
rule "Update Azimuth"
when
    Item UpdateAzimuth received command ON
then
    val sunActions = getActions("astro","astro:sun:home")
    if(null === sunActions) {
        logInfo("actions", "sunActions not found, check thing ID")
        return
    } else {

        val sunSetEvent = "SUN_SET"
        val sunRiseEvent = "SUN_RISE"
        val today = ZonedDateTime.now
        val sunSetEventTime = sunActions.getEventTime(sunSetEvent,today,"START")
        val sunRiseEventTime = sunActions.getEventTime(sunRiseEvent,today,"START")
        val sunSetAzimuth = sunActions.getAzimuth(sunSetEventTime)
        val sunRiseAzimuth = sunActions.getAzimuth(sunRiseEventTime)
        SunsetPositionAzimuth.sendCommand(sunSetAzimuth.toBigDecimal)
        SunrisePositionAzimuth.sendCommand(sunRiseAzimuth.toBigDecimal)

    }

    UpdateAzimuth.sendCommand(OFF)
end
```

## Your Environment

* VMware with Ubuntu 20.04 and openhab 2.5.10
* raspberry pi with Raspbian GNU/Linux 9 and openhab 2.5.10

**Comment by robnielsen** [comment]
This only happens for me if I modify the rules file that contains the astro action. No messages when starting up.
