### ISSUE TITLE
[Shelly] Shelly2.5 in roller mode produces status updates continuously in eventlog

### ISSUE THREAD

**Issue by magnus1674** [openhab/openhab-addons#9413]
## Expected Behavior
I'm using 16 Shelly 2.5 in roller mode without problems. I have 1 more installed in nearly the same way. The Shelly is expected to open and close a roller shutter when triggered.

The difference in installation is:

- The device has no roller motor attached directly, but switches a GIRA roller switch, that itself then has a motor attached. This means is cannot measure any power when the roller motor is running.
- Therefore a calibration of the roller shutter is *not* possible.

## Current Behavior
The Shelly device works fine. Rollers are opening an closing as expected.
But: In OpenHab eventlog I can see a lot of status changes (nearly every second) that look like this:

...
2020-12-18 08:35:35.265 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 100.0 to 0.0
2020-12-18 08:35:49.029 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 0.0 to 100.0
2020-12-18 08:35:50.764 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 100.0 to 0.0
2020-12-18 08:36:09.077 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 0.0 to 100.0
2020-12-18 08:36:12.005 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 100.0 to 0.0
2020-12-18 08:36:24.091 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 0.0 to 100.0
2020-12-18 08:36:27.276 [vent.ItemStateChangedEvent] - JL_EG_WC_Ost changed from 100.0 to 0.0
...

The rollers do not change at all in this timeframe, and the switch is also not triggered. All my other Shellys, acting as roller switches, don't show this behavior.

## Possible Solution

I'm not sure if this is a problem of the Shelly Binding or of the Shelly device itself. I also opened a ticket with Allterco / Shelly Support. They don't have any useful solution so far. 

## Steps to Reproduce (for Bugs)
Install a Shelly2.5 in roller mode without calibration and configure ist in OpenHab. I use this channel in the item configuration to switch between up / down - this must be the way the log infos are coming into OpenHab.

---
xx.items
Rollershutter ....  <itemname> ... {channel="shelly:shelly25-roller:xxxx:roller#control"}
--

## Context
-

## Your Environment
Shelly2.5 Firmware: 1.9.2
OpenHab: 2.5.10
Shelly Binding: 2.5.10
Running on Openhabian on a Raspberry 4.

**Comment by markus7017** [comment]
This has already been fixed, you need to switch to DEV build


---

Latest **DEV** build: [2.5.11](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true) - [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)

**Comment by magnus1674** [comment]
Ok, thanks a lot!

**Comment by s4ndst0rm** [comment]
I'm on Openhab 3.0.1 and Shelly binding 3.0.1. I have the same issue. 
What to do?

**Comment by magnus1674** [comment]
I don't know - I also have the problems still on version 3.0.1 - you can see it still on the event stream...

**Comment by s4ndst0rm** [comment]
@markus7017 : This seems not to be fixed comletely. Would you give us a hint how to solve it or do you need more informations?

**Comment by markus7017** [comment]
upgrade to latest DEV build


---

Latest **DEV** build: [2.5.13](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.13-SNAPSHOT.jar?raw=true) - [3.1.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.1.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)
Note: The binding version included in the final OH 3.0 distro is significantly older than the DEV build. I can't make it in-time. Make sure you deleted older versions of the binding when installing the 2.5.13-SNAPSHOT or 3.1.0-SNAPSHOT if you are already on OH 3.

**Comment by magnus1674** [comment]
Ok - I'll wait until it is available in the normal releases - thanks a lot for your effort!

**Comment by markus7017** [comment]
For 2.5 this will never happen - no more features coming into 2.5 branch
For 3.x you need to wait until 3.1

The DEV build is pretty stable, so consider this option

**Comment by izicam** [comment]
hello! 
I just got Shelly 2.5 and I have the same problems with roller shutter.
I am using OH 3.2 and have installed the Add-on "Shelly Binding" Version 3.2.0. I think the latest version. 
Is there any solution already?
