### ISSUE TITLE
[Tibber Binding] Add "Price Level" channel as in 2.5.8 version of binding

### ISSUE THREAD

**Issue by jostein1989** [openhab/openhab-addons#9425]
## Your Environment

* Version used: 2.5.11/OH3 RC1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Openhabian
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Buster

**Comment by kjoglum** [comment]
Can be closed: #9814
