### ISSUE TITLE
Visibility setting in OH3 Sitemap Editor

### ISSUE THREAD

**Issue by gnilebein** [openhab/openhab-addons#9436]
Please add the posibility to use the visibility function in openHAB 3 Sitemap Editor. Currently i only get the message 

> Unexpected identifier token: "visibility". Instead, I was expecting to see one of the following:

when im am trying to import my existing sitemap. I suspect that this will cause the same problem with Value and Label Colors.

## Your Environment
* Version used: openHAB 3.00 RC2
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Newest Chrome Version
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): openHAB 3.00RC2 Docker Image

**Comment by gnilebein** [comment]
Sorry, Wrong REPO.

**Comment by fcostantino64** [comment]
how did you solve it?

**Comment by gnilebein** [comment]
Currently this is not supported.

**Comment by gnilebein** [comment]
https://github.com/openhab/openhab-webui/issues/324

**Comment by RodBelaFarin** [comment]
is this still unsolved?
The documentation says it's available.
