### ISSUE TITLE
[deconz] alert channel isn't working

### ISSUE THREAD

**Issue by katiuskt** [openhab/openhab-addons#9440]
Hello,

Trying OH3 Build #2091 (docker environment)
Created an item attached to the alert channel of a deCONZ light group.
Deconz Version 2.08.00 / 8.12.2020

It fails when you try to set it to ON. I expected lights on that group blinking but nothing happens but this error in "openhab.log":

> 2020-12-20 10:44:01.458 [WARN ] [ernal.handler.DeconzBaseThingHandler] - Sending command ON to channel deconz:lightgroup:ConBeeII:13:alert failed: 400 - [{"error":{"address":"/groups/13/action/alert","description":"invalid value, alert, for parameter, alert","type":7}}]

Taking a look at https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/groups/#parameters_2 
![image](https://user-images.githubusercontent.com/75622100/102710402-4722b180-42b2-11eb-9e2e-215d0abda3b7.png)
I'm not able to guess what is wrong (the URL seems fine to me, isn't it?)

I see "alert" is expecting to be a "string" so I changed the item created by OH (by default it is a switch) to a string one and I've tried:

> DS_LightGroup_Alert.sendCommand("select")

or

> DS_LightGroup_Alert.sendCommand("lselect")

With no luck either.

Any clue? Am I doing something wrong at OH side? Is it something wrong with the binding?

I can confirm there is no issue at deconz side because either this:

> curl -H 'Content-Type: application/json' -X PUT -d '{"alert": "select"}' http://IP:PORT/api/API/groups/13/action

or this:

> curl -H 'Content-Type: application/json' -X PUT -d '{"alert": "lselect"}' http://IP:PORT/api/API/groups/13/action

make lights blinking accordingly.

On the other hand (and I don't know if I should raise a new issue for this or it is a feature request), according dresden documentation ( https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#parameters_2 ) it seems you could also set "alert" for individual lights but I can't see an "alert" channel in deCONZ binding in OH for that. Is it known, right?

**Comment by J-N-K** [comment]
Wrong implementation in openHAB.

**Comment by katiuskt** [comment]
Thank you @J-N-K  for such great speed fixing this
