### ISSUE TITLE
[deconz] Light group "all on" doesn't work as a switch

### ISSUE THREAD

**Issue by katiuskt** [openhab/openhab-addons#9444]
Hello,

Trying OH3 Build #2091 (docker environment)
Deconz Version 2.08.00 / 8.12.2020
Created an item attached to the "all_on" channel of a deCONZ light group.

By default it is a switch and its default widget is the "oh-label-card". 

Its report is accurate: it tells you if all lights in the group are ON or OFF. But I would expect to be able to interact with it like a switch to turn on/off all the lights in the group.

Example: If all lights in the group are OFF the switch must be OFF. And if you click on the switch, all the lights on the group will turn on.
In the same way, if all lights are ON the switch must be ON and if you click on it, all lights must turn off.

I thought it could be the widget was only informative so I changed it from oh-label-card to oh-toggle-card with no luck:

> 2020-12-20 17:08:29.203 [WARN ] [ernal.handler.DeconzBaseThingHandler] - Sending command ON to channel deconz:lightgroup:ConBeeII:13:all_on failed: 400 - [{"error":{"address":"/groups/13/action","description":"body contains invalid JSON","type":2}}]

According deCONZ API you can turn on/off the whole light group either with the "on" field (the most appropiate if I would say) or the "toggle" one
https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/groups/#set-group-state
![image](https://user-images.githubusercontent.com/75622100/102718339-ed3cde80-42e7-11eb-841b-33b03207a403.png)

Is the "all_on" channel implemented in OH3 intended to be only "informative" or is it expected to allow to set the group on/off too as detailed (and also expected at least by me) above? 

Thank you

PS: I know you are focus on GA release of OH3 so I'm not expecting this fixed for that GA due to the feature freeze but I would appreciate a comment confirming if the actual behavior is or not the expected one.

**Comment by J-N-K** [comment]
Not a bug. Use the color channel.
