### ISSUE TITLE
[knx] Thing channelTypeUID isn't displayed correctly when using *-control channel

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#9462]
## Expected Behavior
If using a *-control channel Type, "Control" should be displayed in addition to the general Type (Switch, Dimmer...)

## Steps to Reproduce (for Bugs)
Create a *-control Channel in a knx thing and save. Look at the configuration...

This issue is available in openHAB2.x as well as in openHAB3 :)

**Comment by Confectrician** [comment]
Related to openHAB 3:

I have faced a similar issue during configuration but mostly the channels should be displayed correct.

Example:
![image](https://user-images.githubusercontent.com/7161177/103158001-7016db00-47b9-11eb-8fce-c39b0ca8a8c1.png)

For the configuration part it seems to look good except for the DateTime Control channel type.

![image](https://user-images.githubusercontent.com/7161177/103158020-99376b80-47b9-11eb-9dd2-38644c53a64f.png)

But that's just i wrong xml definition which i have checked some minutes ago in the repo.

**Comment by holgerfriedrich** [comment]
This is how the items are displayed at the moment:

![grafik](https://user-images.githubusercontent.com/2121139/206874940-b6e3ad5f-d820-4601-8aed-828d40cb3edc.png)

You can check the conversation I had with @kaikreuzer in #12710 on improving the textual description.
The outcome was not the change it.

@udo1toni @kaikreuzer shall we close this ticket?

**Comment by kaikreuzer** [comment]
Yep, let's close it - since the description shows the fact that these are control channels, the user is able to distinguish them.
