### ISSUE TITLE
[mapdb] not functioning

### ISSUE THREAD

**Issue by SuperDave51** [openhab/openhab-addons#9481]
I am newly on the full release of 3.0.  However mapdb has not been functioning since some time after migrating early to a test release of 3.0.  I've had a number of questions answered for me on the openhab community pages at 
[https://community.openhab.org/t/mapdb-not-working-in-oh3/106935](url)
There are more details there.

My mapdb.persist file consists of:
`Strategies {
        default = everyUpdate
}
Items {
       * : strategy = everyChange, restoreOnStartup
}`

I've uninstalled the mapdb service and deleted the log files, then reinstalled the service to no avail.  I also had removed mapdb and waited for yesterdays release, then updated and reinstalled the service.  No change.
I also just set the console to debug with log:set DEBUG org.openhab.persistence.mapdb, and there are NO entries in the log.  
It's been very frustrating and I'm hoping someone here can help.

**Comment by wborn** [comment]
OH3 installs RRD4J persistence by default so OH may use that for restoring values on startup. It might work better when RRD4J is reconfigured to not restore values on startup... or just uninstall it if you are going to use some other persistence add-on for historic data.

**Comment by SuperDave51** [comment]
> OH3 installs RRD4J persistence by default

Thanks for the reply, @wborn. I'm not an OH developer but this seems to not be the case.  RRD4J is not showing as installed; although obviously is able for installation.

I'd looked at using it but I have strings that I am persisting, not just number files.  And I could make some programming changes and move away from string data types, but why when mapdb should work?  Several others have commented that they are running without issue but I've not been able to pinpoint my specific problem....it seems unique to my installation?

**Comment by lsiepel** [comment]
AS this issue is 3.5 years old, i assume the OP found a way to fix this. If not and want to discuss this further, feel free to re-open.
