### ISSUE TITLE
[homekit] Add configuration options to Security System

### ISSUE THREAD

**Issue by EjvindHald** [openhab/openhab-addons#9482]
As a default the Homekit Security System has 4 modes: StayArm", "AwayArm", "NightArm" and "Disarmed".

However, it is possible to restrict usage of some of these, if they are not needed. Eg. StayArm. This is supported by the Homekit IOS app, and it is implemented [in Homebridge mqttthing](https://github.com/arachnetech/homebridge-mqttthing/blob/HEAD/docs/Accessories.md#security-system), where it works fine.

It would be great to have the same functionality in openhab.

**Comment by yfre** [comment]
im already working on this. not only for Security System but for all accessories with value list, e.g. thermostats.

**Comment by diRk262** [comment]
@yfre 
Hi Eugen,
Is this already implemented?
I use the securitysystem Meta data for HomeKit. For me would be NIGHT_ARM and DISARMED enough. How can I disable the other 2 values so that they don’t show up in HomeKit?
Thank you!

**Comment by yfre** [comment]
just add mapping for NIGHT_ARM and DISARMED and it will reduce to these 2 modes

you can mapped them to default values DISARM/NIGHT_ARM 
`String	security_target_state  "Security Target State" (gSecuritySystem) 							{homekit="TargetSecuritySystemState" [DISARM="DISARM", NIGHT_ARM ="NIGHT_ARM"]}`


or to values that your security system returns, e.g

`String	security_target_state  "Security Target State" (gSecuritySystem) 							{homekit="TargetSecuritySystemState" [DISARM="VALUE_FOR_DISARM", NIGHT_ARM ="VALUE_FOR_NIGHT_ARM"]}`

**Comment by diRk262** [comment]
> just add mapping for NIGHT_ARM and DISARMED and it will reduce to these 2 modes
> 
> you can mapped them to default values DISARM/NIGHT_ARM
> `String security_target_state "Security Target State" (gSecuritySystem) {homekit="TargetSecuritySystemState" [DISARM="DISARM", NIGHT_ARM ="NIGHT_ARM"]}`
> 
> or to values that your security system returns, e.g
> 
> `String security_target_state "Security Target State" (gSecuritySystem) {homekit="TargetSecuritySystemState" [DISARM="VALUE_FOR_DISARM", NIGHT_ARM ="VALUE_FOR_NIGHT_ARM"]}`

@yfre sorry for the dumb question, but how do I map them via UI in OH3? I got a .map transformation for changing the active/inactive shown state on my dashboard, but this doesn’t affect HomeKit? Can this be done via the state description meta data?

I just added an item with the securitysystem meta data so that I can change the state via HomeKit.
I created a rule in OH3 like:
When window open then play sound but only if item state = NIGHT_ARM.
So there is no real device, just a switch for HomeKit.

Thank you

**Comment by yfre** [comment]
no, no, you dont need transformation.  mapping is part of meta data configuration. 
take a look how it is done for thermostat in the documentation 
https://www.openhab.org/addons/integrations/homekit/#thermostat

it looks in UI like this

![image](https://user-images.githubusercontent.com/11726616/108624719-eb59dd80-7446-11eb-99f8-ea8e4b611733.png)

replace HEAT and OFF with NIGHT_ARM and DISARM

**Comment by diRk262** [comment]
@yfre 
I can’t get it to work. If I add only the `SecuritySystem.TargetSecuritySystemState` Meta data to the item, it doesn’t show up in HomeKit. When I add multiple like `SecuritySystem,SecuritySystem.TargetSecuritySystemState ` it shows up in HomeKit but with all states.
This is my code.. but no item in HomeKit.
![C8E28DA5-B5AC-4AE1-B9DF-C975C8A197E7](https://user-images.githubusercontent.com/76136884/108626369-0c72fc00-7450-11eb-9884-86055794ea76.jpeg)

Thanks for your support

**Comment by yfre** [comment]
you need to have both, current and target system states, otherwise the accessory will not be created. 
so, add both of them the same item and do the mapping. 
if you see all states then your homekit addon version is older than required for that patch.  you would need to upgrade homekit addon (only the addon, not the openHAB) to more recent version, e.g. latest milestone.

**Comment by diRk262** [comment]
@yfre 
I added current and target state.. item shows up in HomeKit but with all states.
![5F63D759-26B2-480B-AB65-12476A13326C](https://user-images.githubusercontent.com/76136884/108630611-ef492800-7465-11eb-84e5-05373debd521.jpeg)

My version is 3.0.1.
So I will try to update the addon (when I found out how to do it 🤣)

thank you

**Comment by yfre** [comment]
here are upgrade instructions 
https://community.openhab.org/t/qr-code-not-shown-in-homekit-config-in-oh3/114864/4?u=yfre

**Comment by diRk262** [comment]
> here are upgrade instructions
> https://community.openhab.org/t/qr-code-not-shown-in-homekit-config-in-oh3/114864/4?u=yfre

Oh perfect, this is what I was looking for. 👍 

Before I update..Do I need to stop openhab.service or anything else? Will HomeKit remember the binding after the update or do I have to add the bridge again and rearrange all items?

**Comment by yfre** [comment]
you dont need to do anything. just update. you dont need to backup data, stop service or remove the bridge. 
after updade it takes few seconds until new version is started, in that time the homekit item will be not responsive in home app. after that, all items should be as they are before, only the security could lose some states :)

**Comment by diRk262** [comment]
> you dont need to do anything. just update. you dont need to backup data, stop service or remove the bridge.
> after updade it takes few seconds until new version is started, in that time the homekit item will be not responsive in home app. after that, all items should be as they are before, only the security could lose some states :)

@yfre 
Really sorry to bother you again.. but update isn’t working.
Maybe the url has changed?
![89F84569-7395-4C4D-8CCD-C13BA6E3D4A5](https://user-images.githubusercontent.com/76136884/108639346-55e53a80-7494-11eb-807a-46ba27da6df1.jpeg)

**Comment by yfre** [comment]
yes, your url is the latest one.  it looks like previous one is not working anymore

**Comment by diRk262** [comment]
> yes, your url is the latest one. it looks like previous one is not working anymore

It‘s working! Thank you so much for your help and the awesome work with the HomeKit binding 🥇 

Now there is a slider with 2 modes, perfect.
![A2A4F285-526A-4593-8F7E-B4C0BA58F82B](https://user-images.githubusercontent.com/76136884/108640507-600a3780-749a-11eb-8750-454c75d39990.jpeg)

**Comment by diRk262** [comment]
@yfre 
Hi Eugen,
Sorry but I need to check with you again...
The 2 states are working, but there are warnings in the log. How can I get rid of them?
Changing to NIGHT_ARM is ok:
`2021-02-22 18:26:06.454 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Alarmanlage' received command NIGHT_ARM
2021-02-22 18:26:06.467 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Alarmanlage' changed from DISARM to NIGHT_ARM `

But changing back to DISARM throws this:
`2021-02-22 18:26:10.160 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED.
2021-02-22 18:26:10.166 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED.
2021-02-22 18:26:10.172 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED.
2021-02-22 18:26:10.177 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for TargetSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED]. Returning DISARM.
2021-02-22 18:26:10.181 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED.
2021-02-22 18:26:10.184 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for TargetSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED]. Returning DISARM.
2021-02-22 18:26:10.189 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED.
2021-02-22 18:26:10.194 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED. `

This comes up every few minutes without changing a state:
`2021-02-22 18:31:47.444 [WARN ] [ssories.AbstractHomekitAccessoryImpl] - Wrong value DISARM for CurrentSecuritySystemState characteristic of the item Alarmanlage. Expected one of following [STAY_ARM, AWAY_ARM, NIGHT_ARM, DISARMED, TRIGGERED]. Returning DISARMED. `

Looks like I need a DISARM for for TargetState and a DISARMED for CurrenState?

Thank you!

**Comment by yfre** [comment]
you are right, the current and target have different states according to Apple spec. i have myself linked them to different openHab items. 
but maybe it will work with 1 item - try to add DISARMED: DISARMED mapping
if this does not help, then you would need to split it into 2 different items. you can use rule to sync them if needed

**Comment by diRk262** [comment]
> you are right, the current and target have different states according to Apple spec. i have myself linked them to different openHab items.
> but maybe it will work with 1 item - try to add DISARMED: DISARMED mapping
> if this does not help, then you would need to split it into 2 different items. you can use rule to sync them if needed

Adding the DISARMED mapping doesn’t work.
Now I changed my states. I am using now NIGHT_ARM (as armed mode) and STAY_ARM instead of DISARM.
STAY_ARM replaced the DISARM for, now there are no warnings anymore in the log. 
For me personally there are no difference in state disarmed and stay_arm, so I can use this one and don’t need another item and rule.

thanks
