### ISSUE TITLE
[remoteopenhab] (Docker) IP address of local server is same as remote server but port is different

### ISSUE THREAD

**Issue by GitKalle** [openhab/openhab-addons#9487]
Hello,

I would like to migrate an openHAB 2.5 instance to the new openHAB 3.0 instance step by step. That's why I create a new openHAB 3.0 instance and configure the openHAB remote binding to connect to my openHAB 2.5 instance. After configuration the error occurs:

```
Status: Offline
**CONFIGURATION_ERROR** 
Do not use the local server as a remote server in the thing configuration
```
I use Docker for the openHAB server. I think that is the problem because the remote and the local server have the same IP address and only the port differs.

What can I do to solve the problem?

**Comment by lolodomo** [comment]
I believe you can do nothing. The check has to be fixed, probably by considering IP + port.

**Comment by kaikreuzer** [comment]
Have you tried using the hostname instead of the IP address?

**Comment by lolodomo** [comment]
Oh yes, good idea, with host name it should allow bypassing the check.

**Comment by GitKalle** [comment]
> Have you tried using the hostname instead of the IP address?

Perfect, works like a charme. Thanks for the fast reply.
