### ISSUE TITLE
[tr064] Software Version and Model Name as channel

### ISSUE THREAD

**Issue by MS1982** [openhab/openhab-addons#9491]
I have installed a new OH3 installation and trying to migrate my OH2 installation.
However, with the old TR-064 binding it was possible to display the software version and model name in a sitemap via an item.
With the current version of this binding for OH3 it is no longer possible because the software version and model name is only available as thing property.

**Comment by kaikreuzer** [comment]
... which is absolutely correctly modelled as this data is static and thus should not be a channel.
In general, static information is not really that interesting for sitemaps. As a workaround you could also add it as a static text widget.
Another solution I could imagine is to give rules access to thing properties, which should be fairly simple. You could then at least access it in rules and fill some "virtual" items for your sitemap with it. Feel free to create an enhancement request for this in openhab-core.

**Comment by MS1982** [comment]
Dear Kai, 

thanks for your reply. I agree with the model name, but the software version change from time to time. I will open an enhancement request for this in openhab-core.

Best Regards,
Marcel
