### ISSUE TITLE
[linky] thing remain OFFLINE  Error opening connection with Enedis webservice

### ISSUE THREAD

**Issue by CondormanFr** [openhab/openhab-addons#9493]
## Expected Behavior
After adding and setuping the binding, it must get info from enedis services.

## Current Behavior
I setuped with my login/password and Auth ID
But, the thing remains in OFFLINE Status with message 
COMMUNICATION_ERROR
Error opening connection with Enedis webservice

## Your Environment
openHAB 3.0.0.
docker image

**Comment by lolodomo** [comment]
Did you follow the instructions from the documentation? 
Because works well for me.

**Comment by CondormanFr** [comment]
J'ai réessayé avec Firefox et Chrome... Je n'ai pas revu la variable attendue.
Voilà ce que j'ai : 
![image](https://user-images.githubusercontent.com/2799574/103243918-a68c5b80-495b-11eb-90de-ac81585611c4.png)

**Comment by lavirott** [comment]
+1

**Comment by lolodomo** [comment]
I just tried again, following the documentation instructions and I can find the required field in the cookie.
You find it when you are in the login page.

**Comment by CondormanFr** [comment]
I get the internalAuthId from the login page (a 189 char length string)
![image](https://user-images.githubusercontent.com/2799574/103477733-d1463c00-4dc1-11eb-8737-8fd16f69aa8c.png)

I put it with my login (email) and password and I still get the error message.

(with openhab 2.5.10, the login/password only bindings is working.)
I  updated my password and there is still the issue.
I used firefox too because there is some issues with chrome (css not loaded).
Very strange.

**Comment by lavirott** [comment]
I've got exactly the same issue. Now, it's ok, I can get the internalAuthId, I added it to my linky.things config 
```Thing linky:linky:local "Linky" [ username="...", password="...", internalAuthId="..." ]```

and when I save it, I've got the following message in the openhab log:
```
14:42:42.249 [INFO ] [del.core.internal.ModelRepositoryImpl] - Loading model 'linky.things'
14:42:42.365 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'linky:linky:local' changed from OFFLINE (COMMUNICATION_ERROR): Error opening connection with Enedis webservice to UNKNOWN
14:42:42.772 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'linky:linky:local' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): Error opening connection with Enedis webservice
```
I use openhab 3.0.0.
When I connect with the web browser, everything is fine with the login/password.

**Comment by maximesauvaget** [comment]
Just tried today and it fails with "Error opening connection with Enedis webservice".
Did I miss something ? I just bootsrapped OpenHab as docker container for testing.

**Comment by fligneul** [comment]
Brand new install with OpenHab 3 and i've got the same error

**Comment by lolodomo** [comment]
By the way, the current implementation is no nore working to authenticate. 
The problem is followed in issue #10360.
