### ISSUE TITLE
[mcp23017] pi4j not compatible with Java 11

### ISSUE THREAD

**Issue by Hilbrand** [openhab/openhab-addons#9503]
The mcp23017 binding uses pi4j. This library is not compatible with Java 11 (see [Known issues](https://github.com/Pi4J/pi4j#known-issues)) and therefor this binding doesn't work anymore. They mention a new version will support new Java versions, but it's unclear when this version will be available. There is also a new pi4j version 2 in development, but that is not yet recommend (dec 2020) for use so it's not a direct option to change to that library.

So there is no quick fix to get this working. So should we remove this binding for now?

**Comment by lolodomo** [comment]
I would be better to remove it if it can't work.

**Comment by mrumpf** [comment]
Finally there seems to be some progress on the issue: https://github.com/Pi4J/pi4j/issues/521
So I would keep it and check whether version 1.4 solves the JDK11 compatibility issue.

**Comment by mrumpf** [comment]
Version 1.4 with the JDK 11 fix has been released yesterday!

**Comment by mrumpf** [comment]
I updated pi4j-core to version 1.4 and pi4j-gpio-extension to 1.3 and since then the mcp23017 binding is working again under Java 11. I will prepare a PR.
