### ISSUE TITLE
[tr064] MAC online detection is not working

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#9523]
I can't get the MAC online detection of the new TR-064 binding from OpenHAB 3 to work. As described in the documentation, I discovered all things via the Main-UI inclusing "subdeviceLan" and configured the MAC addresses at the macOnline parameter. After that new channels should "magically" appear for each MAC address, but the channels don't appear (there are still only the 3 WiFi switch channels).

Is it a bug that it isn't working or am I doing something wrong or is a step missing? The log has no error messages (since adding the subdeviceLan thing).

I tried also the newest snapshot build of the binding (from 2020-12-24).

**Comment by lionhe1966** [comment]
Have you looked in this [thread](https://community.openhab.org/t/oh3-fritz-box-tr064-add-on-binding/108299/43) ?

**Comment by Novanic** [comment]
> Have you looked in this [thread](https://community.openhab.org/t/oh3-fritz-box-tr064-add-on-binding/108299/43) ?

Yes. Maybe it is working with a textual thing configuration, but this isn't described within the documentation and the documentation hints to Main UI because discovery should be used to create the subdeviceLan device.

And I found this thread. There are screenshots from Main UI which really shows the new, dynamically created channels, but these don't appear at my installation: https://community.openhab.org/t/oh3-tr-064-binding-missing-channels/109672/6

**Comment by J-N-K** [comment]
Configuration issue. Use UI, works fine.

**Comment by Novanic** [comment]
> Configuration issue. Use UI, works fine.

@J-N-K What??? I'm using the UI and it's not working fine... Please read the issue description!

**Comment by J-N-K** [comment]
Show the code display from the UI. Should look like

```
UID: tr064:subdeviceLan:2a28aee1ee:uuid_3A75802409_2Dbccb_<redacted>
label: LANDevice - FRITZ!Box 6591 Cable (lgi)
thingTypeUID: tr064:subdeviceLan
configuration:
  refresh: 60
  uuid: uuid:75802409-bccb-<redacted>
  macOnline:
    - 11:11:11:11:11:11
    - ""
bridgeUID: tr064:fritzbox:2a28aee1ee
```

**Comment by Novanic** [comment]
UID: tr064:subdeviceLan:7fb1fdfc45:uuid_3A75802409_2Dbccb_2D40e7_2D8e6b_2D444E6D6FB49A
label: LANDevice - FRITZ!Box 7590
thingTypeUID: tr064:subdeviceLan
configuration:
  refresh: 60
  uuid: uuid:75802409-bccb-40e7-8e6b-444E6D6FB49A
  macOnline:
    - 3C-28-6D-D9-DA-BC
bridgeUID: tr064:fritzbox:7fb1fdfc45

**Comment by J-N-K** [comment]
Use : instead of -

**Comment by Novanic** [comment]
> Use : instead of -

Ah, you are right, and it is really described in the documentation and really working (the channels appear directly in the UI). Thank you for the fast response and sorry for opening the issue. ;-)
