### ISSUE TITLE
[tr064] channel dslCRCErrors is not appearing after discovery due to typing error in channels.xml

### ISSUE THREAD

**Issue by lionhe1966** [openhab/openhab-addons#9526]
The channel dslCRCErros does not appear in the list of available channels for the WANDevice.
If the TRACE log is enabled for the tr-064 binding , the following error appears in the log
**[hab.binding.tr064.internal.util.Util] - Channel dslCRCErrors not available: Get-Argument 'NeCRCErrors' not found**
This is likely due to a spelling error in channels.xml, line 261
`<getAction name="GetStatisticsTotal" argument="NeCRCErrors"/>`
which should probably be
`<getAction name="GetStatisticsTotal" argument="Ne**w**CRCErrors"/>`

**Comment by J-N-K** [comment]
Correct. See attached PR.
