### ISSUE TITLE
[irtrans] Bundle in OH3 not providing the needed channel "receiver"

### ISSUE THREAD

**Issue by microcheese** [openhab/openhab-addons#9532]
## Expected Behavior
The Bundle should provide a channel called "receiver" for use in actions (of received IR Commands)

## Current Behavior
The Bundle does only installs the Network Bridge for ITRans (gets online Correctly). But it does not supply a channel called receiver - with you obviously need. It is also not possible to install it through a additional thing by add (only Blaster ist supplied, which is not working if you not using the blaster)

## Possible Solution
I did a quick fix which is providing the needed functionality by adding to ethernetbridge.xml
		`<channels>`
`			<channel typeId="receiver" id="receiver"/>`
`		</channels>`
This adds the Channel which is defined already in the Config. You need obviously configure then the Channel after adding the IRTrans Bridge to get the Thing online.

## Context
Without the functionality, the binding is not usable

**Comment by lsiepel** [comment]
@microcheese not much has changed to the binding since this issue was raised. Do you still think the binding needs this channel or have you found another way? I also don't see other related issues about irtrans, so is it still a problem?
Don't want to give you any false hope about a resolution, i'm just checking older issues that are not commented on and see from there.

**Comment by microcheese** [comment]
I do not longer use the Device (irtrans) - therefore I didn't have not longer the need. Anyway, include the channel Receiver in the binding will be make sense as you need it for receiving IR Signals on Openhab if you have the requirement.

**Comment by lsiepel** [comment]
The `receiver` channel is already available on the `ethernetbridge` Thing. I adpated the readme to make it more clear.
