### ISSUE TITLE
[homekit] thermostat min/max values not treated in system units

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#9538]
I have a Thermostat exposed to HomeKit with the following items:

```
Group gLoftThermostat "Loft Minisplit" { homekit="Thermostat" }

Number LoftThermostat_SetPoint "Set Point [%.1fºF]" <temperature> (gLoftThermostat, gIntesisSetPoints) { channel="mqtt:homie300:intesisbox:001dc9835e29#setptemp", autoupdate="false", homekit="TargetTemperature" [minValue=60.8, maxValue=86.0] }
Number LoftThermostat_AmbTemp "Ambient Temperature [%.1fºF]" <temperature> (gLoftThermostat) { channel="mqtt:homie300:intesisbox:001dc9835e29#ambtemp", autoupdate="false", homekit="CurrentTemperature" }
String LoftThermostat_HomeKitTargetMode <heating> (gLoftThermostat, gIntesisHomeKitTargetModes) { homekit="TargetHeatingCoolingMode" }
String LoftThermostat_HomeKitCurrentMode (gLoftThermostat) { homekit="CurrentHeatingCoolingMode" }
```

The items are backed by a MQTT Homie device that exposes the properties with a unit of `ºF`, and a format of `60.8:86.0`. AFAICT, the OpenHAB Homie binding sets up the channel properly for the min/max (Basic UI automatically limits my inputs), but ignores the unit (see https://github.com/openhab/openhab-addons/issues/8076; if I change the Item to a Number:Temperature, it never updates at all, regardless of if the actual Homie devices sends it in F or C).

My system is set to Imperial units. In the openhab log file, I get
`2020-12-26 20:48:07.198 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range 24.0. Returning min value instead. Characteristic io.github.hapjava.characteristics.impl.thermostat.TargetTemperatureCharacteristic@55781a93` quite often. On my phone it shows "Heating to 141º". Strangely, that corresponds to if you take the minValue(60.8ºF), treat it as C, and convert back to ºF (141.44). This really feels like minValue is always being treated as C, instead of as the item or system unit type, and then converting from F to C for internal comparisons and sending to devices.

## Your Environment
* Version used: OpenHAB 3.0.0
* Java 11
* Ubuntu 20.04 Focal, amd64

**Comment by ExcelsiorEyer** [comment]
Actually, I'm trying to do a Nest thermostat integration with Homekit and am facing a similar situation. I see that the following don't seem to map correctly between Celsius and Farenheit.

1. minValue, maxValue and Step are treated as Celsius
2. HeatingThresholdTemperature and CoolingThresholdTemperature used for AUTO mode are taking values only as Celsius

However, my items are defined as Number:Temperature

Regional settings is set to US Imperial. Homekit settings have "Use Farenheit" ON

I have set up a dummy set of items to debug this thing as I got temporary blocked by the Nest API for apparently sending way out of range temperature settings, which seems to happen if you even open the thermostat control on the Homekit app
