### ISSUE TITLE
[tr064] set phonebookInterval to 0 by default

### ISSUE THREAD

**Issue by lionhe1966** [openhab/openhab-addons#9544]
When creating a fritzbox thing, either by paperUI or by textual configuration in things file, 
the phonebookInterval parameter is set by default to 600, causing an unnecessary download of all phonebooks, even if not required, every 10 minutes.
The workaround I use is to set that parameter to 0.
On the other hand, other parameters, concerning phone calls are left undefined and corresponding channels are not added: if the user need the missedCalls channels he has to add the corresponding parameter and the channel appears. Phonebooks could be treated in a similar way.

**Comment by J-N-K** [comment]
Defaults are always a trade-off between „fits a majority“ and the impact on the „minority“. IMO a few HTTP requests every ten minutes is a low impact on performance.
