### ISSUE TITLE
[teleinfo] Memory leak

### ISSUE THREAD

**Issue by olivierkeke** [openhab/openhab-addons#9546]
Memory consumption increases indefinitely when teleinfo binding is in use.
This seems to be more critical on OH3 (one or two days before `out of memory` error versus one or two weeks on OH2.5).

This bug seems to appear only after receiving a timeout exception when waiting for the next teleinfo frame (which is systematic on my configuration with rfc2217 teleinfo device).

**Comment by J-N-K** [comment]
Please provide a  DEBUG log of the moment when the TimeoutException occurs.

**Comment by olivierkeke** [comment]
@J-N-K I can't provide debug log since I'm currently testing some fixes on this binding. But I can point out from where the exception is thrown:
https://github.com/openhab/openhab-addons/blob/6da56da7a84a68af47ef5d02bc6e19c657e60d40/bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/reader/io/TeleinfoInputStream.java#L187
or
https://github.com/openhab/openhab-addons/blob/6da56da7a84a68af47ef5d02bc6e19c657e60d40/bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/reader/io/TeleinfoInputStream.java#L266

It seems that the `Thread.sleep()` of one minute long after the exception is logged in the code below make memory consumption increase:
https://github.com/openhab/openhab-addons/blob/6da56da7a84a68af47ef5d02bc6e19c657e60d40/bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/serial/TeleinfoReceiveThread.java#L71-L80

My current test consist in removing the two timeout and executing instructions in the main thread in the following code:
https://github.com/openhab/openhab-addons/blob/6da56da7a84a68af47ef5d02bc6e19c657e60d40/bundles/org.openhab.binding.teleinfo/src/main/java/org/openhab/binding/teleinfo/internal/reader/io/TeleinfoInputStream.java#L167-L282
It seems better but the binding is only running for two days so I can't conclude.

Since teleinfo protocol provide a new frame at least every 33.4 ms, I wonder if the openhab framework can handle such work load? Could input data be stored indefinitely somewhere waiting to be processed by the binding and then causing memory leak?
