### ISSUE TITLE
GPSTracker regionTrigger Link Item is missing

### ISSUE THREAD

**Issue by jsiemon** [openhab/openhab-addons#9552]
## Expected Behavior

Ability to link Item to the regionTrigger Channel using the UI.  regionTrigger states that a rule is required, but nothing in the Documentation gives a clue as to what and how this should be done.  Documentation appears to be OH2 Documentation.

## Current Behavior

No way to link a trigger Item to regionTrigger using the UI, only by using .items  text files 

## Possible Solution

The only obvious/easy way to use the current binding is by susing an items file and linking to the channel site with a geo-fence profile. 

{channel="gpstracker:tracker:ex:regionTrigger" [profile="gpstracker:trigger-geofence", regionName="Home"]}

## Steps to Reproduce (for Bugs)

1.
2.

## Context

![image](https://user-images.githubusercontent.com/6732269/103183006-d402d780-487d-11eb-8175-8adc22d1c3d5.png)

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by gbicskei** [comment]
Hi,
I'm aware that OH3 UI doesn't support linking trigger channels to items through profiles yet, but my understanding is that it will be supported in the future. @kaikreuzer please confirm this.

**Comment by kaikreuzer** [comment]
I can only confirm that you are right and that I have created https://github.com/openhab/openhab-webui/issues/886 for it a while ago. I guess we need some JS guru like @ghys to come up with a PR for this.

So while this isn't implemented, the only way to link the channel to an item is through an items file. This is therefore no bug in the binding, hence I close this issue.

**Comment by ghys** [comment]
Yes I never encountered trigger profiles and forgot about them back then.
In my defense there aren't too many of them either... :)
https://github.com/openhab/openhab-addons/search?q=TriggerProfile
https://github.com/openhab/openhab-addons/search?q=system.rawbutton
https://github.com/openhab/openhab-addons/search?q=system.rawrocker

> So while this isn't implemented, the only way to link the channel to an item is through an items file. This is therefore no bug in the binding, hence I close this issue.

Or if you're feeling adventurous you can use the API Explorer under Developer Tools, and do a
`POST ​/links​/{itemName}​/{channelUID}`
and specify the details both in the path and the body:
```json
{
  "itemName": "YourItem",
  "channelUID": "gpstracker:tracker:ex:regionTrigger",
  "configuration": {
    "profile": "gpstracker:trigger-geofence",
    "regionName": "Home"
  }
}
```
Hopefully it won't break in other parts of the UI, YMMV.

**Comment by jsiemon** [comment]
Thanks to all for taking time to respond to this issue.  Using text file based .items and .rules is the solution that I have successfully implemented for this binding.
