### ISSUE TITLE
[http] Method PUT-GET-POST per Channel

### ISSUE THREAD

**Issue by JiroMusik** [openhab/openhab-addons#9563]
Hi there,
I played around with the new http binding and it is really cool since it now supports everything I needed to bring my multiroom system into openhab as neat as possible but now I have another device with a REST API:  https://rest.moodo.co/
Is there any possibility to make the method of Get Post or Put per Channel or do I have to create 3 different things for this device (login 3 times) and create some script for communication between items?

**Comment by J-N-K** [comment]
Create three things.
