### ISSUE TITLE
[openweathermap] Request Condition field to be capitalized (first letter of each word)

### ISSUE THREAD

**Issue by giri-v** [openhab/openhab-addons#9570]
It would be nice if the Condition string was properly capitalized. I'm using OH3 and cannot capitalize in the widget.

Thanks!

**Comment by Jochen1980** [comment]
I took a short look at the code. The data comes from the openweathermap API, so it is necessary to know what Strings are exactly bothering you? Otherwise it seems to me like a dead end with some unpleasant side effects, for example "Ein paar Wolken" seems to be exactly what is expected.

**Comment by cweitkamp** [comment]
Yes, the binding just forwards data received from OWM API. It does neither applies a formatter nor a translation on values. To be honest we will not fix that. If you like to have optimized casing I have to ask you to look for a solution elsewhere (e.g. by creating a rule or a transformation). See also https://github.com/openhab/openhab-addons/issues/4650#issuecomment-463235797.
