### ISSUE TITLE
[yioremote] Wrong handling of action sendIRCode

### ISSUE THREAD

**Issue by miloit** [openhab/openhab-addons#9573]
## Expected Behavior
if the action sendIRCode is used in a rule it should send out an IR code

## Current Behavior
action sendIRCode is not sending out any IR code

## Possible Solution
see pull request https://github.com/openhab/openhab-addons/pull/9574

**Comment by lsiepel** [comment]
Can I assume this issue can be closed as the related PR is merged a long time ago?
