### ISSUE TITLE
[modbus] modifying poll length does not refresh polls until restart of poller

### ISSUE THREAD

**Issue by edolis** [openhab/openhab-addons#9577]
Minor thing but can be confusing when setting up Data things using Modbus.
If you create a data thing, whose start is out of range, you realize it and change the poller length to include its registers in the polled range, the data thing will show NULL - untill the poller is manually disabled and then enabled.

**Comment by ssalonen** [comment]
@edolis does this happen with latest binding version?

**Comment by ssalonen** [comment]
@edolis any update?

**Comment by ssalonen** [comment]
@edolis any update?

**Comment by ssalonen** [comment]
@edolis any update?

**Comment by ssalonen** [comment]
@edolis any update?

**Comment by wborn** [comment]
I think no update means it no longer happens.
