### ISSUE TITLE
[influxdb] OH3.0.0 Persisted values are restored from Influx without UoM

### ISSUE THREAD

**Issue by schmidmuc** [openhab/openhab-addons#9578]
Situation:
- Running a OH3.0.0 installation under Ubuntu 20.04 LTS
- 
- I have UoM items in my configuration which get persisted to Influx DB
- After restart of OH, values of these items get restored, but without any units
- As a consequence there are many errors because of wrong item type (Number insted of Number with Unit), many rules don't work until a new value (including UoM) is written to the item
- In addition it's seems not to be transparent with which unit the values are persisted to Influx

Preferred behavior:
- Values are always persisted using the base unit value, so Byte instead of GigaByte, Watt insted of KiloWatt, etc.
- Values are restored after restart including this base unit

Alternative behavior:
- Define the preferred unit in the item configuration which should get used for persistence and as the default unit (if not defined explicitly in sitemaps, etc.)

My influxdb.persist:
`Strategies {
	everyHour : 	"0 0 * * * ?"
	default = everyChange
}
Items {
    gInflux* : strategy = everyChange, everyHour, restoreOnStartup
}
`

**Comment by cweitkamp** [comment]
Related to https://github.com/openhab/openhab-core/issues/1954
