### ISSUE TITLE
OH3 : An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by jmone1** [openhab/openhab-addons#9587]
I'm not sure if this is related to the NTP Binding in 3.1.0-Snapshot but I Karaf Console and log reports the following:

`An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/C:/Users/natha/Downloads/openHAB/userdata/cache/org.eclipse.osgi/27/0/bundleFile) to field java.time.LocalDateTime.date
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`
From the Community Thread - https://community.openhab.org/t/oh3-an-illegal-reflective-access-operation-has-occurred/111982 , Bruce Osborne suggested to raise the issue here.  He also mentioned that "There should not be any eclipse paths in OH3".  This is a clean install with all bindings being installed from the OH3 UI, with the excpetion of the Alpha 3.0.0 of the Wiz Binding which is in the Addon Folder

## Your Environment
* 3.1.0 - Snapshot (Clean Install)
* Windows 10 64-Bit

**Comment by marcelrv** [comment]
Did a quick check, gson is not directly used by the NTP binding.

So it must be a bit more complex interaction that causes this. 
Note that the message indicates `Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory ` so it may be related to  something internal to gson

**Comment by jewesta** [comment]
I had the same message this morning (3.1.0-SNAPSHOT - Build 2101). The system has been running uninterrupted for several days. I do not remember seeing this before.
```
WARNING: An illegal reflective access operation has occurred                                                                              
WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/Users/administrator/openhab/userdata/cache/org.eclipse.osgi/27/0/bundleFile) to field java.time.LocalDateTime.date
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
System: mac Mini 2012 / macOS 10.15.7 / AdoptOpenJDK 11.0.9+11

**Comment by garywild** [comment]
> I had the same message this morning (3.1.0-SNAPSHOT - Build 2101). The system has been running uninterrupted for several days. I do not remember seeing this before.
> 
> ```
> WARNING: An illegal reflective access operation has occurred                                                                              
> WARNING: Illegal reflective access by com.google.gson.internal.bind.ReflectiveTypeAdapterFactory (file:/Users/administrator/openhab/userdata/cache/org.eclipse.osgi/27/0/bundleFile) to field java.time.LocalDateTime.date
> WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.bind.ReflectiveTypeAdapterFactory
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> ```
> 
> System: mac Mini 2012 / macOS 10.15.7 / AdoptOpenJDK 11.0.9+11

I'm having a comparable Warning. Have you already solved it? hope somebody knows the answer!!!

I posted a thread about my comparable warning on stackoverflow: https://stackoverflow.com/questions/67667112/warning-an-illegal-reflective-access-operation-has-occurred
