### ISSUE TITLE
[TR-064] : searching for fritz.box instead of the given IP address

### ISSUE THREAD

**Issue by dacchio** [openhab/openhab-addons#9592]
## Expected Behavior
The binding should bring the things online reaching the IP address given in binding configuration

## Current Behavior

When adding a fritzbox router the binding tries to reach out for the hostname **fritz.box** instead of the given IP address , if you are not using the fritzbox as your DNS  the thing does not come online.
In the log you can see the current error:

` java.util.concurrent.ExecutionException: java.net.UnknownHostException: fritz.box to UNKNOWN`

## Possible Solution

The binding should use the given IP address instead of the ftiz.box hostname
## Steps to Reproduce (for Bugs)

1. Make sure your openhab server cannot resolve the name  fritz.box
2. Configure a new thing for a fritzbox router.

## Context

This behavior prevented me to bring the thing online and use it,  manually editing the server hosts file rapresents a  working workaround.

## Your Environment

* Openhab version: Openhab 3 stable installed via apt on a rapsberry pi 4
* Binding version: the one provided by the MainUI

**Comment by J-N-K** [comment]
Fixed in #9454
