### ISSUE TITLE
[pushover] @nullable "Title" is required or script execution fails

### ISSUE THREAD

**Issue by Masssssy** [openhab/openhab-addons#9621]
## Expected Behavior

The documentation for the pushover binding shows that the title should be possible to omit as there is a default title available. However the title parameter/argument needs to be supplied in order for the command to execute properly. 

The following is stated in the documentation: 
`The parameter message is mandatory, the title parameter defaults to whatever value you defined in the title related configuration parameter.`

## Current Behavior

E.g 
  `val actions = getActions("pushover", "pushover:pushover-account:myaccountID")`
  `var receipt = actions.sendMessage("TESTING")`
  
  vs 
  
  `val actions = getActions("pushover", "pushover:pushover-account:myaccountID")`
  `var receipt = actions.sendMessage("TESTING", "TITLE")`
  
  Where only the last will execute and the first errenously return:
  Script execution of rule with UID '123' failed: An error occurred during the script execution: index=2, size=2 in 123

## Possible Solution

Either change the documentation or the binding to match. Since there is a default title supplied in the pushover "thing" I'd suggest this is used.

## Steps to Reproduce (for Bugs)

Write a rule with the code snippets supplied above in section "Current Behavior".

## Context

Took a while to figure out why all my rules stopped working when moving from the OH1 action to OH3 binding. 

## Your Environment

* Version used: OH3 with latest 3.0 pushover binding
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 11
* Ubuntu 18.04

**Comment by Masssssy** [comment]
Actually it seems like none of the default arguments work. 

For .sendPriorityMessage everything needs to be supplied manually. 

E.g 
` var receipt = actions.sendPriorityMessage("FIRE(SMOKE) in " + fireName + "!!", "TITLE", 2)`

Omitting "TITLE" or 2 (priority) causes script execution to fail.

**Comment by bjsjr** [comment]
I can confirm that the issue also exists in sendAttachmentMessage.  The parameter contentType is listed as optional in the documentation but the script will fail without it.
