### ISSUE TITLE
[avmfritz] Persisted values polluted with 0 on restart of FritzBox

### ISSUE THREAD

**Issue by timbms** [openhab/openhab-addons#9625]
## Expected Behavior
No value from radiator controllers should be permitted during restart of Fritz!Box

## Current Behavior
I am operating some thermostats (COMET DECT) connected to an AVM Fritzbox for my radiators.
Currently, when the FritzBox is restarted, a zero value is persisted in database on the item actual_temp.
This pollutes the charts. 

## Steps to Reproduce (for Bugs)
1. Connect thermostats item actual_temp
2. Restart Fritz!Box
3. Watch chart of actual_temp
<img width="1323" alt="Screenshot 2021-01-01 at 16 58 04" src="https://user-images.githubusercontent.com/5411131/103442010-9671c600-4c52-11eb-9174-a7df49b39a92.png">

## Context
Clean charts would be nice.

## Your Environment

* Version used: 3.0
* Environment name and version: openhabian 
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian

**Comment by cweitkamp** [comment]
Thanks for reporting. I have to admit that I never user `actual_temp` Channel before. I always use the `temperature` Channel. I will set-up a test and give it a try.

**Comment by cweitkamp** [comment]
After more than one week and several OH and / or FRITZ!Box restart it was not possible for me to reproduce your situation.

![grafik](https://user-images.githubusercontent.com/5131747/104127249-50f37e00-5361-11eb-8084-bbb844e377ac.png)

Please tell me more about your persistence setup.

**Comment by timbms** [comment]
@cweitkamp : I am making use of openhabian and standard persistence configuration - It is therefore rrd4j.

One more observation: 0 values get stored also when thermostat disconnects from fritzbox (see attached screenshot - thermostat was disconnected over night). This happens sometimes because the distance is at the limit. Still I would prefer to have Not Available in the database, if this handled by rrd4j and the scripting library. 

<img width="965" alt="Screenshot 2021-01-23 at 12 33 39" src="https://user-images.githubusercontent.com/5411131/105577035-441a5580-5d77-11eb-9189-b4d7a8f06cd6.png">

**Comment by lsiepel** [comment]
> aking use of openhabian and standard persistence configuration - It is therefore rrd4j.
> 
> One more observation: 0 values get stored also when thermostat disconnects from fritzbox (see attached screenshot - thermostat was disconnected over night). This happens sometimes because the distance is at the limit. Still I would prefer to have Not Available in the database, if this handl

There are some wokarounds possible. For instance, make rule that gets triggered for every change. Whenver the value is 0>, set the value to an alternative Item. Have this alternative item persisted.
