### ISSUE TITLE
Missing wifiGuestEnable Channel

### ISSUE THREAD

**Issue by Peter-DD** [openhab/openhab-addons#9665]
I'm using this binding to enable WiFi Guest Wlan. Since upgrading to OpenHab 3.1.0 Snapshot and the must to have migrate from "Fritzbox Binding" to "TR-064 Binding" the "wifiGuestEnable" channel isn't seen anymore in "fritzbox","subdevice","subdeviceLan" things. It's a "FRITZ!Box Fon WLAN 7360". The TR064 communication is enabled.

Update:
I observed when I switch on/of the WiFi Guest via FritzBox Web Gui I receive a "LANDeviceFRITZBoxFonWLAN7360_wifi5GHzEnable" change event. Hence I try to switch WiFi Guest via "LANDeviceFRITZBoxFonWLAN7360_wifi5GHzEnable" channel and this works!. It seems the channels wifi5GHzEnable and wifiGuestEnable are reversed.

**Comment by J-N-K** [comment]
It's on the `subDeviceLan`. I just checked it works as designed. How did you configure the things?

**Comment by Peter-DD** [comment]
> It's on the `subDeviceLan`. I just checked it works as designed. How did you configure the things?

The things are configured via gui. The wifiGuestEnable item I tried with text file:
and gui, too.

**Comment by J-N-K** [comment]
There is no `wifiGuestEnable` channel in the UI?

**Comment by Peter-DD** [comment]
> There is no `wifiGuestEnable` channel in the UI?

No, only:
![image](https://user-images.githubusercontent.com/52273778/103475623-09904f00-4daf-11eb-8636-07bed2580123.png)

**Comment by J-N-K** [comment]
Then the Fritzbox reports it doesn’t support that.

**Comment by Peter-DD** [comment]
> Then the Fritzbox reports it doesn’t support that.
The old "Fritzbox Binding" supported this on my Fritzbox, but it isn't available for OpenHab 3.0. 
However as I wrote when switching ON the "LANDeviceFRITZBoxFonWLAN7360_wifi5GHzEnable" channel the WiFi Guest will enabled. This is a workarround for me..

**Comment by J-N-K** [comment]
I think I found the issue. But it may be difficult to work around that. Your FB does not support 5 GHz, correct? The WLAN Interfaces are numbered, on my FB there are three: #1 = 2.4 GHz, #2 = 5 GHz and #3 = Guest. If you don't have 5 GHz, Guest is probably #2, which is why it works for you with the 5GHz channel. Unfortunately it is not reported if #2 is Guest or 5 GHz.

**Comment by Peter-DD** [comment]
> Your FB does not support 5 GHz, correct? 

Yes , this is correct. My FB doesn't support 5GHz. It would be nice if your binding decides per FB model the offered channels, but I think this wouldn't be easy to implement! 
Many thanks for your support. The workaround is acceptable for me.
