### ISSUE TITLE
[linky] Knowing if data include values from yesterday or not yet

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#9666]
As you know, the binding is retrieving the data every morning, retrying every 2 hours until the values from the previous day are available.
Unfortunately, the values are available relatively late. If you check your items at 07am, it is more than probable than the item corresponding to the consumption from yesterday is still the value from the day before yesterday.
If you look at your items after 09am, they probably include data form yesterday.

So we need something to let the user know if his data include values from yesterday or not yet.

I imagine 2 options:

1. Option 1 is to set channels (only channels depending on the value form yesterday) to UNDEF at midnight and let the binding set them again later in the morning when data are available. Doing that, if you see UNDEF values, you know that values form yesterday are not yet available and you have to check later.
2. Option 2 is to add a new switch channel that will inform the user if data already include values form yesterday or not. This channel will be set to OFF at midnight.

@clinique: what option do you prefer ? 
I think option 1 will make more sense.

**Comment by clinique** [comment]
@lolodomo : yes I think option 1 is the best way to proceed.
