### ISSUE TITLE
[powermax] Add a catch-all exception handler

### ISSUE THREAD

**Issue by ronisaacson** [openhab/openhab-addons#9688]
As discussed at: https://community.openhab.org/t/exception-handling-for-bindings/112809

In the event of an exception, the Powermax binding will stop but the error message won't be logged properly, and the things won't be taken offline. @Hilbrand suggests we add a handler for RuntimeException in addition to the handlers already present in PowermaxReaderThread, and mark all of the things offline whenever the reader stops.

**Comment by Hilbrand** [comment]
I don't think this can be done at the binding level. Because the handler would work for everything I guess and I don't know if such a handler works nicely with OSGI. So that needs to be tested. And if that works it should probably be added to openhab-core. In any case the binding itself should be responsible for setting the thing offline because only the binding knows the reason and if it might be something temporary or if it might be a bug and should be reported.

**Comment by ronisaacson** [comment]
I was comparing the logic in PowermaxReaderThread with some other bindings. Here's a simplified version of the Powermax logic:

```
public void run() {
  try {
    while (!Thread.interrupted()) {
      // do stuff
    }
  } catch (InterruptedIOException e) {
    Thread.currentThread().interrupt();
    logger.debug("Interrupted via InterruptedIOException");
  } catch (IOException e) {
    logger.debug("Reading failed: {}", e.getMessage(), e);
  }
}
```

Comparing with DigiplexBridgeHandler, to pick one at random:

```
public void run() {
  while (!interrupted()) {
    try {
      // do stuff
    } catch (IOException e) {
      handleCommunicationError();
      break;
    } catch (InterruptedException e) {
      break;
    }
  }
}
```

where `handleCommunicationError()` does `updateStatus(ThingStatus.OFFLINE, ThingStatusDetail.COMMUNICATION_ERROR);` and also schedules a task to attempt a reconnection. So it seems like maybe that's a better model?

Then for core, maybe `Thread.setDefaultUncaughtExceptionHandler()` for a global handler. What about bindings that take commands but don't explicitly start their own threads though, what context do those handlers run in?

**Comment by lolodomo** [comment]
Guys, what error do you want to catch? 

I am running this binding since several years and the reader thread never stopped abnormally. 

PS: The pattern for this reader thread is the same as in other bindings like the RFXCOM binding.

**Comment by lolodomo** [comment]
Why not improving this thread but I believe many bindings should be checked too.

**Comment by Hilbrand** [comment]
I think he was experimenting with the binding and introduced a bug that threw a NullPointerException.  So no specific failure to this binding at the moment.

This is a general issue with also other bindings and probably not easy to solve generic (deciding what to do when a problem happens). So yes it might be an idea to check all threads, but I won't pursue that for fun. If a global handler works that would at least provide some better logging. So I think looking into the global handler might be worth looking into and leave the rest for when one works with such a binding. 

> What about bindings that take commands but don't explicitly start their own threads though, what context do those handlers run in?

If it's on a thread of core it's logged by core and if it's on a scheduled thread using the thing provided scheduler it's catched and logged by that scheduler. So it's a custom thread specific issue.

**Comment by ronisaacson** [comment]
Yes and outside of that I've had two or three instances where communication with the panel is fine and then all of a sudden it just... stops. It's getting messages normally and then nothing. No more messages received, and attempts to send a message (arm/disarm) show nothing in the logs. The bridge and all things continue to show online though. I know my serial connection to the panel is flaky and the problem is not with the binding, but I'm guessing there's an I/O error which is getting swallowed.

**Comment by ronisaacson** [comment]
I can confirm btw, I did a pull-the-plug test on the serial cable. All of my powermax things continued to show online and the binding never recovered. I'll try switching it around to be more like the other example above and submit a pr if it works.

**Comment by ronisaacson** [comment]
Another update: when using a serial connection, I'm not sure the binding will ever get notified of an exception in the event of a pull-the-plug or similar serial disconnect, possibly due to this in PowermaxSerialConnector:

```
    @Override
    public void serialEvent(SerialPortEvent serialPortEvent) {
        try {
            logger.trace("RXTX library CPU load workaround, sleep forever");
            Thread.sleep(Long.MAX_VALUE);
        } catch (InterruptedException e) {
        }
    }
```

@lolodomo can you provide some more background on this and whether it's still necessary?

The practical effect is that we might not realize the pipe is closed until we next try to send a message. In Powerlink mode, that will be soon because we expect a keepalive every minute and will send a RESTORE message if we don't get one. But in download mode, there are no periodic messages, so a lost connection will never recover on its own.

In download mode, the panel will always send an unsolicited STATUS message at least once an hour and often more frequently than that, so we could have a watchdog timer which attempts a reconnect if we're in download mode and nothing has been received in over an hour. We could also try to send STATUS requests more proactively, e.g. whenever the connection is idle for 5 minutes.

There's already an exception handler which kicks in when sendMessage fails, updates all of the things and tries to reconnect. So I think the two changes needed here are:

1. Add a handler for RuntimeException to PowermaxReaderThread and have it call `connector.setConnected(false)`
2. Better detect lost connections in download mode

**Comment by lolodomo** [comment]
What you call download mode is probably what I call the standard mode. 
The download mode is a special and temporary mode when the setup of the panel is downloaded and only occurred at binding startup (or when exiting the physical panel admin).

**Comment by ronisaacson** [comment]
Sorry, yes I mean standard mode. The Powerlink mode doesn't work very well for me so I use the standard mode.

**Comment by lolodomo** [comment]
Regarding the RXTX library CPU load workaround  it is what it is. You can find it in at least 8 bindings using a serial connection. 
It was introduced to avoid high CPU loaf when using RXTX library. 
I have no idea if it is still necessary. 
It should be checked if without this workaround the CPU load is not growing up.

**Comment by ronisaacson** [comment]
Hmm, what a pain. It seems that workaround comes from [here](https://github.com/NeuronRobotics/nrjavaserial/issues/22#issuecomment-59206246) and it [should be fixed](https://github.com/NeuronRobotics/nrjavaserial/pull/48), but at least [one other binding](https://github.com/openhab/openhab-addons/pull/1826) has tested since then and found it to still be an issue. I'm thinking I will leave that alone for now and just focus on adding keepalive-style behavior to standard mode.
