### ISSUE TITLE
[OpenWeatherMap] OpenWeatherMap Binding language DA missing

### ISSUE THREAD

**Issue by pelindberg** [openhab/openhab-addons#9695]
According to the OpenWeatherMap, the language can be set do Danish (da), but the binding cant handle that

https://openweathermap.org/current#multi

**Comment by Hilbrand** [comment]
You can simply create a pr to this file and add the language: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.openweathermap/src/main/resources/OH-INF/config/config.xml

**Comment by lolodomo** [comment]
That is not enough. The languages supported by the API are defined here. 
https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.openweathermap/src/main/java/org/openhab/binding/openweathermap/internal/config/OpenWeatherMapAPIConfiguration.java#L33

**Comment by cweitkamp** [comment]
I submitted a PR to add more supported languages: #9717.
