### ISSUE TITLE
[gpio] link to jar

### ISSUE THREAD

**Issue by maheshdada1** [openhab/openhab-addons#9696]
> @phuongpham here it is: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.gpio/3.1.0-SNAPSHOT/org.openhab.binding.gpio-3.1.0-SNAPSHOT.jar

Great! I will give it a try now

_Originally posted by @phuongpham in https://github.com/openhab/openhab-addons/issues/1334#issuecomment-753627679_

**Comment by Hilbrand** [comment]
Looks like something went wrong here. It's not an issue, so closing.
