### ISSUE TITLE
[LIFX] binding: can't change color temperature without turning on LIFX mini Day & Dusk bulbs & channel on/off channel missing

### ISSUE THREAD

**Issue by GeorgesPaul** [openhab/openhab-addons#9700]
## Expected Behavior
The "temperature" channel of these bulbs can be set from 0 to 100, corresponding to bright daylight to reddish candle light. There's also a brightness channel (0 to 100 for min to max brightness). Using the LIFX manufacturer's Android app schedule feature, color temperatures and brightness settings can be set while the light isn't turned on (as long as the bulb has power of course). This allows a user to send different temperature and brightness settings to the bulb regardless of whether it is switched on or off and without toggling the light on or off. 

As a third "channel" the LIFX Android app has an "on/off" channel. This channel seems to be missing from the LIFX openHAB binding. 

This issue was evaluated on LIFX mini Day & Dusk bulbs. These are the types of bulbs that can change from warm to cold whites (no "disco" colors). 

## Current Behavior
Whenever the "temperature" channel or "brightness" channel of the OpenHAB LIFX binding is changed, it causes the light to turn on (as in: emit light). This is unexpected and undesired behavior. These channels should just alter the color temperature and/or brightness settings on the bulb without changing its on/off state.

Furthermore the [documentation](https://www.openhab.org/addons/bindings/lifx/) of the LIFX binding states that there should be an on/off channel for all types of LIFX bulbs. However the only channels that are (auto)detected are temperature, brightness and signal strength. The on/off channel doesn't appear. 

Forum link: https://community.openhab.org/t/lifx-command-to-change-color-without-turning-lamp-on/112078?u=g11

## Possible Solution
Figure out how the LIFX Android app manages to send setting commands over the network without switching the lights on? Wireshark? I'm not an expert... 

## Steps to Reproduce (for Bugs) using PaperUI

**To reproduce on/off channel missing:** 
1. Install LIFX binding 
2. Check inbox for auto-detected LIFX lights
3. Observe missing on/off channel. The only channels that appear are temperature, brightness and signal strength. 

**To reproduce temperature setting change = toggle on issue:** 
1. Install LIFX binding 
2. Check inbox for auto-detected LIFX lights
3. Add the channels temperature and brightness to Things
4. Go to "control" in the PaperUI
5. Switch LIFX bulb OFF through the control UI (and observe how there's an on/off switch, but no on/off channel when you added the light Thing in OpenHAB)
6. Change brightness or temperature and observe how the bulb automatically also switches on as soon as the brightness or temperature settings are changed. The on/off state shouldn't have changed. 

## Context
The main application for LIFX mini Day & Dusk bulbs (at least for me) is to change color temperature of artificial lights throughout the day/night to support the natural sleep cycle. Bright white/blueish color sends "wake up" signals to the human brain (even with eyelids closed). Most people will want a lot of blue light in the early morning to help with waking up and very little blue light at night to help with going to sleep more easily. 

The color that the bulbs have as soon as they are switched on should match the color temperature setting for that time of day. This doesn't seem possible the way the current LIFX binding works. 

## Your Environment
* Version used: openHAB 2.5.2.000 (Synology package), LIFX bindings 2.5.2
* Environment name and version: Java 8, Firefox 84.0.1
* OS: Synology DSM 6 for the openHAB server, Windows 10 for the browser/client.

**Comment by wborn** [comment]
IIRC this behavior is by design so the channels of lights of different bindings all behave the same. I.e. it works exactly this way with the hue binding. So the binding is behaving how light things in openHAB work and not how one vendor decided to implement this in their app.

**Comment by GeorgesPaul** [comment]
> 
> 
> IIRC this behavior is by design so the channels of lights of different bindings all behave the same. I.e. it works exactly this way with the hue binding. So the binding is behaving how light things in openHAB work and not how one vendor decided to implement this in their app.

That's all fine and dandy, but it also makes the LIFX openHAB binding useless for me and probably every other LIFX day & dusk user out there?

Is there some way that would allow to use openHAB to do what is described in the "context" of the opening post? 

PS: offtopic. I don't get why somebody didn't release smart bulbs that just store a desired schedule on the bulb itself. That way the schedule would just work even if you power the lights off (allowing one to use standard light switches). I guess smart light manufacturers want that sweet sweet cloud spyware?

**Comment by wborn** [comment]
> Is there some way that would allow to use openHAB to do what is described in the "context" of the opening post?

Maybe we can add some configuration options to channels or add a thing action for that. Customizable fade times are also something I'd like to see. The LAN protocol isn't the limiting factor.

> I guess smart light manufacturers want that sweet sweet cloud spyware?

I also work on projects with devices managed through the cloud and usually it is just more convenient to run logic in the cloud so you can bring features to all devices (including unsupported) instead having to wait for them to be manually upgraded by users. All the data gathered by spying on you needs to comply to GDPR and also needs to be stored which is something you'd rather avoid.

**Comment by GeorgesPaul** [comment]
> Maybe we can add some configuration options to channels or add a thing action for that. Customizable fade times are also something I'd like to see. The LAN protocol isn't the limiting factor.

That would be totally great and would make those LIFX lights usable with openHAB. I love the concept (I'm new at openHAB). I find openHAB easier to use than home assistant personally. 

> I also work on projects with devices managed through the cloud and usually it is just more convenient to run logic in the cloud so you can bring features to all devices (including unsupported) instead having to wait for them to be manually upgraded by users. All the data gathered by spying on you needs to comply to GDPR and also needs to be stored which is something you'd rather avoid.

I think I agree that from a business/dev point of view the online-only sync is more convenient. However from a user point of view (in my humble opinion as a smart-stuff user) I find the "store schedule locally and optionally sync with cloud and/or openHAB" option way more attractive. 
It's basically a nice fallback for when there's no WIFI connection. Which is every single time you power cycle a bulb for the first 10 seconds, which every single beginner LIFX user will run into. It's also a great fallback for unstable WIFI connections and/or unstable bulb firmware, which are both also very common. One "killer feature" would be that you could use regular existing light switches and still have "smart" functionality (such as dynamic/alternating schedules and using lamps as indicators) at the same time. 

Anyway, not really on-topic, but just some user friendliness thoughts I had about this tech.

**Comment by kaikreuzer** [comment]
> it works exactly this way with the hue binding

@wborn I actually have to correct you on this. When sending a command to the color temperature channel on hue, the bulb will stay off and the next time it is turned on, it will show the last received color temperature.
I specifically took care of that implementation because I had exactly the same use case in mind as @GeorgesPaul describes.

So if the "similar behavior to hue" is your only concern: Feel free to happily treat this as a bug and change the implementation in LIFX accordingly 😎 .

**Comment by wborn** [comment]
Does the hue binding also leave the lights off if you change the brightness? That's also part of the request.

**Comment by kaikreuzer** [comment]
Ah, I didn't read it closely enough.

> Furthermore the documentation of the LIFX binding states that there should be an on/off channel for all types of LIFX bulbs.

The docs say, there is an ON/OFF capability, but not a dedicated ON/OFF channel. The ON/OFF commands are simply sent through the brightness channel.

When sending a command to brightness, clearly the bulb should set the brightness accordingly. In openHAB, there is no such notion as a separate power state - 0% brightness simply means that the bulb is off.

So what I said above, clearly only applies to the color temperature channel: When setting a color temperature, the bulb should immediately change to that color temperature, while not changing its brightness. So if brightness is 100% it is kept, if brightness is 50%, it is kept and if brightness is 0%, it is kept as well.

**Comment by GeorgesPaul** [comment]
> > Furthermore the documentation of the LIFX binding states that there should be an on/off channel for all types of LIFX bulbs.
> 
> The docs say, there is an ON/OFF capability, but not a dedicated ON/OFF channel. The ON/OFF commands are simply sent through the brightness channel.

In that case the documentation isn't correct, because the docs do say that there is a dedicated ON/OFF channel in the way I read the docs. Quote from the documentation LIFX openHAB bindings page (the sentence above the table): 
>The following matrix lists the capabilities **(channels)** for each type:

> When sending a command to brightness, clearly the bulb should set the brightness accordingly. In openHAB, there is no such notion as a separate power state - 0% brightness simply means that the bulb is off.

That's unfortunate, because that means the scenario that I wrote in the opening post is still not possible in case the user wants the lamps to turn on with a certain brightness and color temperature setting. 

Example of what I mean: the lights are off in the bathroom, it becomes 1 passed midnight and that causes openHAB to trigger a rule that sets the bathroom LIFX bulb to "candlelight color @ 50% brightness" without turning the light on (since there's no reason to turn it on, there's nobody in the bathroom). User wakes up at 1 am to go to the bathroom, user turns bathroom-light on (using a "smart" switch that simply sends an "on" command to the bulb through openHAB or directly to the bulb) and there's a nice soft non-bright candle light color to avoid user from completely waking up. 

> So what I said above, clearly only applies to the color temperature channel: When setting a color temperature, the bulb should immediately change to that color temperature, while not changing its brightness. So if brightness is 100% it is kept, if brightness is 50%, it is kept and if brightness is 0%, it is kept as well.

With the above in mind this makes little sense to me. Why would a user always only want to "preset" the color temperature and not the brightness for the next time the lamp is turned on? 

In case somebody wants to test/confirm that this is feasible with the LIFX API, here's some code. I'm using this type of script with cron now to set the LIFX bulb schedule independent of openHAB, but of course I would prefer to do it in openHAB instead, once that becomes possible): 
```
import lifxlan as lx
import time

lan = lx.LifxLAN(2)   # find max 2 lights

bur = lan.get_device_by_name("bureau1")

bur.set_power(0, 0) 			# turn off
bur.set_brightness(10000)		# set 1/6th brightness  without turning bulb on 
bur.set_colortemp(1500) 		# set candle light color temperature without turning bulb on
time.sleep(2) 					# sleep for 2 seconds
bur.set_power(65535, 1000)		# turn on light. Light now turns on with candlelight and low brightness
```

**Comment by kaikreuzer** [comment]
> In that case the documentation isn't correct

Well, it says there is a channel for ON/OFF commands and that is fully correct. It does not say that it is a Switch channel type.

> Why would a user always only want to "preset" the color temperature and not the brightness for the next time the lamp is turned on?

There is no such thing as a "preset". Sending a brightness command should adjust the brightness, sending a color temp command should adjust the color temp. It's as simple as that.
If you want to hold back commands that you send at 1am at night (like setting brightness to 50%) and only want them considered at a later moment, you'd best create some automation rules for that.

**Comment by GeorgesPaul** [comment]
> 
> 
> > In that case the documentation isn't correct
> 
> Well, it says there is a channel for ON/OFF commands and that is fully correct. It does not say that it is a Switch channel type.

Maybe I'm being pedantic here, but there is simply no channel for ON/OFF commands. What I mean is: there's no channel called ON/OFF or anything that sounds like ON/OFF in the openHAB bindings. So it's confusing for the manual to read "here are the channels" and then literally show an ON/OFF channel that doesn't exist in the binding when you look for it in openHAB as a user. There's a brightness setting channel that you can set to 0 or 100 (which looks like on or off), but that's not the same as an ON/OFF channel. In fact, to me, showing an ON/OFF channel in the table implies that brightness does _not_ toggle the ON/OFF state, otherwise why would you show 2 separate channels with different names (one of which doesn't show up as a binding) that are meant to achieve the same thing? Why show the ON/OFF "channel" at all in the table if it doesn't exist? 

I as a reader would assume that setting the "Brightness" channel would be setting the Brightness of the bulb and not "setting the brightness value, but actually also turning it on if it was off". 

To put it differently: If setting the Brightness in the manual means "setting the brightness and also turning the lamp on" then it would make sense to simply write that explicitly? Since... that's what it is?  

To continue on my pedantic path, the manual explains the brightness channel as: 
> This channel supports adjusting the brightness _**value**_.

What you're explaining here, would be much less ambiguous if it was written as:
> This channel supports adjusting the brightness **_actuation_**. 

> > Why would a user always only want to "preset" the color temperature and not the brightness for the next time the lamp is turned on?
> 
> There is no such thing as a "preset". Sending a brightness command should adjust the brightness, sending a color temp command should adjust the color temp. It's as simple as that.

I totally agree. Setting the brightness should set the brightness and not "set the brightness value and also turn the lamp on". Just like "setting color temp" should mean "setting color temp" and not "setting color temp and also turn the lamp on". 

> If you want to hold back commands that you send at 1am at night (like setting brightness to 50%) and only want them considered at a later moment, you'd best create some automation rules for that.

So a user needs to couple bulb settings to every single on/off signal rule for every single switch thing channel that can turn a bulb on/off?

Why would it make sense to make a switch rule know about bulb color temperatures, times of day and desired brightnesses? 

I'm not even sure how to do that (sounds super complicated and labor intensive to be honest) and it's literally easier for me to write a Python script that runs with cron outside of openHAB than to figure out how to do that in openHAB. That's probably not the point of openHAB?

**Comment by lsiepel** [comment]
@GeorgesPaul scanned/read most of this issue, hope you got everything setup the way you need it. There are some excellent posts in the community forums about how to setup light fading functionality, complete with example rules.

The table from the documentation you refer to has this intro:
_The thing type determines the capability of a device and with that the possible ways of interacting with it. The following matrix lists the capabilities (channels) for each type:_

So it lists the capabilities and for allmost all of them this maps to a channel, except the on/off, it is a capacbility, but not a channel. I agree that for the inexperienced openHAB user, this might be a bit confusing.
If you have a suggestion on how to actually improve that part of the documentation, i'm happy to take your sugggestion into a PR and offer it for a merge.
