### ISSUE TITLE
[pushover] Move sound configuration parameter from Thing to Channel

### ISSUE THREAD

**Issue by sihui62** [openhab/openhab-addons#9701]
Would it be possible to move the configuration parameter for the sound notification from Things to Channels?

Currently you have to setup multiple Things to get a different sound.

According to the openHAB concepts page it would be more appropriate to have that parameter for the Channels. 

Discussion on this already started in the community:
https://community.openhab.org/t/pushover-binding-in-oh3-help-needed/111361/8

**Comment by cweitkamp** [comment]
I added a universal method in #10422 which allows to pass any possible parameter.
