### ISSUE TITLE
[network] arping detection not working, since arping --help writes to stderr and returns with 2

### ISSUE THREAD

**Issue by marcel-kanter** [openhab/openhab-addons#9707]
The network binding does not correctly detect the installed arping.

Reason is the behavior of ExecUtil.executeCommandLineAndWaitResponse. It discards the error output, since arping --help writes to stderr and returns with 2.

This results in an null result value.

## Expected Behavior
arping should be detected correctly by using existing options.

## Current Behavior
See description

## Possible Solution
Check for the differend version options of the tools. E.g. arping -V etc.
Or better let the user choose the version. maybe provide and commandline with variables which get substituded.

## Steps to Reproduce (for Bugs)
Install the network binding and use iptools arping. It will call arping with argument --help. The arping does not know the argument and returns with code 2 and the argument list printed to stderr.

## Context
I'm trying to get the Network binding working and discovered this issue with arping. But it may be an issue with other arping versions.

## Your Environment
current main & master of openHAB (problem seem to exist since long time OH 2.5.x with network binding.)
Ubuntu 20 on Odroid C2 with iputils arping
Linuxmint on Oracle VB with iputils arping

arping -V returns "arping from iputils s20190709"

**Comment by lolodomo** [comment]
It could be interesting to compare how it was implemented in the LGwebOS / SamsungTV bindings.

**Comment by marcel-kanter** [comment]
The Samsung binding calls some executable too. Which one, I currently don't know. But it does nothing else. If the call returns with an error code it asumes there is no device.

This is a conceptional problem in the core of openhab, because such calls (or calls of executables in general) result a trinary result: Exit code 0 (no error) - Exit code != 0 (which does not mean that there was an error - some programs exit with an info exit or warning code) and an OS based error (which is an real error, because maybe the executable is missing or the access rights are not properly set)...

**Comment by sprehn** [comment]
In LGWebOS binding we use WakeOnLanUtility class and try to detect the tools depending on the OS.

```
private static final String COMMAND;
    static {
        String os = System.getProperty("os.name").toLowerCase();
        LOGGER.debug("os: {}", os);
        if ((os.indexOf("win") >= 0)) {
            COMMAND = "arp -a %s";
        } else if ((os.indexOf("mac") >= 0)) {
            COMMAND = "arp %s";
        } else { // linux
            if (checkIfLinuxCommandExists("arp")) {
                COMMAND = "arp %s";
            } else if (checkIfLinuxCommandExists("arping")) { // typically OH provided docker image
                COMMAND = "arping -r -c 1 -C 1 %s";
            } else {
                COMMAND = "";
            }
        }
    }
```

**Comment by cweitkamp** [comment]
@marcel-kanter Can you check if it is working again for the Network binding in the latest snapshot with https://github.com/openhab/openhab-core/pull/2114 in place?

**Comment by marcel-kanter** [comment]
I decided to throw away the existing code and rewrite the whole binding. Because for each detection method a separate thread and a process is created (and destroyed). The detection uses notifiers and stuff which can be reduced.
Then at configuration changes, the configuration is created from the properties of the osgi component, then copied and then the temporary configuration destroyed. I'm running the openhab on a small SBC and this kind of stuff isn't needed.

**Comment by marcel-kanter** [comment]
> 
> 
> In LGWebOS binding we use WakeOnLanUtility class and try to detect the tools depending on the OS.
> 
> ```
> private static final String COMMAND;
>     static {
>         String os = System.getProperty("os.name").toLowerCase();
>         LOGGER.debug("os: {}", os);
>         if ((os.indexOf("win") >= 0)) {
>             COMMAND = "arp -a %s";
>         } else if ((os.indexOf("mac") >= 0)) {
>             COMMAND = "arp %s";
>         } else { // linux
>             if (checkIfLinuxCommandExists("arp")) {
>                 COMMAND = "arp %s";
>             } else if (checkIfLinuxCommandExists("arping")) { // typically OH provided docker image
>                 COMMAND = "arping -r -c 1 -C 1 %s";
>             } else {
>                 COMMAND = "";
>             }
>         }
>     }
> ```

On Windows, this only checks the arp cache and does not ping the device. I have no Mac, but I think this true for MacOS too.

**Comment by clinique** [comment]
Is this still true since this [PR](https://github.com/openhab/openhab-addons/pull/12316) ?
