### ISSUE TITLE
[icalendar] eventfilter thing can crash openHAB

### ISSUE THREAD

**Issue by chris922** [openhab/openhab-addons#9723]
I noticed that the eventfilter thing can crash openHAB.

I've got a ical file containing repeating VEVENTs without a fixed end. When I setup an eventfilter without defining an end date filter openHAB will crash after some time.

## Expected Behavior
Misconfiguration is not possible and openHAB will not crash

## Current Behavior
I tried to figure out what happened and analyzed a heap dump and also stack traces.
Doing this I figured out that among others the `eventList` [here](https://github.com/openhab/openhab-addons/blob/813ac27c0ee5b8bcd856b836cd91eec9fadf022f/bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java#L252) contains multiple million entries.
For me it looks like the reason is that the given `frameEnd` is a date thats far in the future (see [here](https://github.com/openhab/openhab-addons/blob/813ac27c0ee5b8bcd856b836cd91eec9fadf022f/bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/EventFilterHandler.java#L283)) and because I've got repeating VEVENTs the biweekly library will always return new events.

-> The loop will run a really long time until an OutOfMemory error comes up

## Possible Solution
Several solutions are possible I think, just some ideas:

* Set a default end-date filter and/or don't allow using no end-date filter -> `frameEnd` will then be set to this date
* Add documentation (directly in the UI or somewhere in the docs) that a end-date filter should be set in case the calendar contains repeating events
* 
## Steps to Reproduce (for Bugs)

Reproduce via openHAB:
1. Setup iCalendar binding
2. Configure Bridge with a ics file that contains repeating events
3. Configure an eventfilter thing without an end-date filter
4. Wait ...

Reproduce via code:

```java
        var cal = AbstractPresentableCalendar.create( TestReadingSmarthome.class.getResourceAsStream( "/smarthome.ics" ) );

        cal.getFilteredEventsBetween( Instant.now(), Instant.ofEpochMilli( Long.MAX_VALUE ), null , 3 );
```

`smarthome.ics` is a file with a repeating event. The test will run a really long time and maybe stop with an OutOfMemory.

## Context
Having repeating events that are doing some actions every day.

## Your Environment
* Version used: openHAB + binding v3.0.0
* Operating System and version: openHABian on Raspberry Pi 4

**Comment by J-N-K** [comment]
Did you configure maxevents? In general that should be prevented by that parameter. Can you share an example ics?

**Comment by chris922** [comment]
Yes I configured maxEvents. It looks for me that it might be considered too late?

The first place where I see the `maxEvents` value will be considered is here: https://github.com/openhab/openhab-addons/blob/813ac27c0ee5b8bcd856b836cd91eec9fadf022f/bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/logic/BiweeklyPresentableCalendar.java#L273 (as `maximumPerSeries`).
Maybe OH hangs before this point? Today I was able to setup an environment where I can debug my running instance... I will try to find out where the infinite/long running loop might be or where openHAB hangs.

Here you can find the ICS _(saved as .txt to be able to upload it here):_ [icalendar_issue_9723.txt](https://github.com/openhab/openhab-addons/files/5791717/icalendar_issue_9723.txt)

**Comment by J-N-K** [comment]
The test above finishes immediately for me and produces three results.

**Comment by chris922** [comment]
Aah, I just noticed that there were some changes **after** the release of 3.0.0 that probably fixes this:

This commit here adds support for the max-events also to the method `getVEventWPeriodsBetween`:
https://github.com/openhab/openhab-addons/commit/a7ac71f1e081e06d9ca88a5785e04f3934007837#diff-d436467bf54d75fdd2f69b70a9e47448746efcab48755d42ceb518f4d486423b

I debugged it right now and noticed that in the version I am using (v3.0.0) there is no `maximumPerSeries` parameter that will break the loop after x-entries, so it was nearly an infinite loop because the `frameEnd` is the date that belongs to the Long.MAX_VALUE timestamp... so a few thousands years away from now :-D 

Can I somewhere find a guide how I can test the current snapshot release with my running instance to verify that the mentioned changes fixed this issue? I remember for OH2 I had to download the JAR and put it somewhere.. but it was long time ago I did it the last time. Maybe now there is even an easier way?!

**Comment by daMihe** [comment]
You already found the issue and it's fix. You can download the jar from the [openHAB JFrog](https://openhab.jfrog.io/ui/builds/openHAB-Addons?type=builds) or change your whole openHAB to snapshot builds by using `openhabian-config` on your Pi.
