### ISSUE TITLE
[smartthings] Discovery service is broken

### ISSUE THREAD

**Issue by BobRak** [openhab/openhab-addons#9727]
## Expected Behavior
The Discovery Service should run at startup and then once every 5 minutes. It should find devices connected to the Smartthings hub and add them to the Inbox.

## Current Behavior
No devices show up in the Inbox.

## Possible Solution
I @BobRak am the author of this addon.
I have diagnosed why the Discovery service isn't running explain the problem below. **I would like one of the openhab maintainer look at the @Component and @Reference statements and advise if how these should be coded.**

### Existing code
**SmartthingsHandlerFactory**
`@Component(service = { ThingHandlerFactory.class,  
        EventHandler.class }, immediate = true, configurationPid = "binding.smarthings", property = "event.topics=org/openhab/binding/smartthings/state")    
public class SmartthingsHandlerFactory extends BaseThingHandlerFactory implements ThingHandlerFactory, EventHandler  
 {
`

SmartthingsDiscoveryService
`    @Reference  
    protected void setThingHandlerFactory(ThingHandlerFactory handlerFactory) {  
        if (handlerFactory instanceof SmartthingsHandlerFactory) {  
            smartthingsHandlerFactory = handlerFactory;  
        }  
    }  
`

The problem is when setThingHandlerFactory is called it is being passed a class that is not an instance of the SmartthingsHandlerFactory.

### Possible solution
**SmartthingsHandlerFactory**
`@Component(service = { ThingHandlerFactory.class, SmartthingsHandlerFactory.class,  
        EventHandler.class }, immediate = true, configurationPid = "binding.smarthings", property = "event.topics=org/openhab/binding/smartthings/state")  
public class SmartthingsHandlerFactory extends BaseThingHandlerFactory implements ThingHandlerFactory, EventHandler  
 {
`

SmartthingsDiscoveryService
`    @Reference  
    protected void setThingHandlerFactory(SmartthingsHandlerFactory handlerFactory) {  
        smartthingsHandlerFactory = handlerFactory;  
    }  
`
### Question
Is this an acceptable solution? If not, what should be done?

## Steps to Reproduce (for Bugs)

1. Make sure there are devices connected to the Smartthings hub
2. Make sure the OpenHabAppV2 in the Smartthings app on your phone includes the devices
3. Notice that nothing shows up in the Inbox

## Context
The Smartthings Addon works with manual configuration but not for users that want to take advantage of the Discovery service

## Your Environment

* openHAB 2.5.11-1. I know the behaviour is the same with openHAB 3.0
* Raspberry Pi built with openhabian 1.6.1

**Comment by lsiepel** [comment]
Couple of weeks after this issue was raised a PR was merged: https://github.com/openhab/openhab-addons/pull/9889 
It seems that this issue is resolved now.  If there is still something wrong with the discovery, please re-open this issue and we will continue from there.
