### ISSUE TITLE
[mqtt.homie] Missing Channel Groups

### ISSUE THREAD

**Issue by Maenthyx** [openhab/openhab-addons#9728]
As I understood the documentation, the UI should group the channels by the corresponding nodes for Homie thing. But instead there is only a list of channels, and no groups shown.
The grouping feature I'm missing can be seen in a [screenshot of OpenWeatherMap binding](https://community-openhab-org.s3.dualstack.eu-central-1.amazonaws.com/original/3X/7/6/7674870c1bdeed0be3cdf6df3b2d1fdafb54be24.png). Please note the channels grouped in "Wetterstation" and "Aktuelles Wetter"

## Expected Behavior
Autodetect a thing having multiple nodes with multiple channels each.
When created, in the UI the thing should group all channels by their nodes.
3 nodes with 2 channels each, should result in 3 channel groups named by their nodes and having 2 channels appropriately to the node properties.

## Current Behavior
All channels are listed in one list, there is no grouping in the UI.

## Possible Solution
Group the channels by their nodes as described in the [documentation](https://www.openhab.org/addons/bindings/mqtt.homie/).

## Steps to Reproduce (for Bugs)
1. Auto-discover a MQTT Homie Thing, having multiple homie nodes with multiple homie properties each.
2. Create the thing from inbox when it was auto-discovered.
3. Show the thing details in the UI
4. Find a list of all channels, but without grouping.

## Context
I have a device with multiple sensors, each sensor can have/publish multiple values. Simple example: 3 temperature sensors, each with properties "temperature" and "enabled". First one measures temperature. Second one defines whether the sensor is enabled or disabled, this property is settable.
When auto-discovering and creating the thing in openHAB, I get a list of all channels. But as there is no grouping, the list contains 3 entries "temperature"  and 3 entries "enabled".
It's OK to search a list of 6 entries, but the full blown device has 16 nodes with 3-5 properties each, while nodes of the same type have properties of same name. A list of 60-80 ungrouped items would be easier to manage if that grouping feature would work.

## Your Environment
* openHAB version: 2.5.10 (Paper UI), 2.5.11 (Paper UI), 3.0.0 (Main UI)
* Firefox 84, Chrome 87
* Java Zulu 8 (current) for openHAB 2.5.x, Java AdoptOpenJDK 11.0.9.101 for openHAB 3.0.0
* Windows 10 (current)
* Device implements Homie 3.0.1
* MQTT server: Mosquitto, on external system (not provided by openHAB)

Thx guys!

**Comment by ccutrer** [comment]
The underlying issue is that the binding doesn't ever define a ThingType that includes ChannelGroupDefinitions. it just blindly throws channels out that happen to be in groups. I've got a fix worked up, but I'm still testing it, since it took significant refactoring.
