### ISSUE TITLE
Warning when implementing ThingHandlerService

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#9742]
When trying to implement the discovery as a ThingHandlerService (See this preview documentation: https://deploy-preview-1262--openhab-docs-preview.netlify.app/docs/developer/bindings/#discovery-that-is-bound-to-a-thing)
I get a error/warning:
`Redundant superinterface DiscoveryService for the type PlugwiseHADiscoveryService, already defined by AbstractDiscoveryService`

Other users seem to have the same problem. Guess the documentation (or interface) needs some work. Or is this an accepted warning?

_Originally posted by @lsiepel in https://github.com/openhab/openhab-addons/pull/9504#discussion_r550755793_

**Comment by J-N-K** [comment]
That's a documentation issue. Remove `DiscoveryService` from you implementatipn if it extends `AbstractDiscoveryService`.

**Comment by Confectrician** [comment]
@J-N-K 

>That's a documentation issue.

May you provide a doocumentation fix for this?
I have seen that the content is notyet available in the latest docs.
Only in the 2.5.x version.

I think the sub article is still valid for opwnHAB 3?

**Comment by J-N-K** [comment]
I always struggle with the location of the developer documentation. Can you point me to the file that needs changing? I'll adapt it then.

**Comment by Confectrician** [comment]
Hi @J-N-K 

Sorry for the delay, here you go.

Developer docs in general are located here:
https://github.com/openhab/openhab-docs/tree/main/developers

Binding development documentation is a whole subfolder of articles.
Since the part should be located in the main article it should be available in the index page of that folder.
https://github.com/openhab/openhab-docs/blob/main/developers/bindings/index.md

**Comment by J-N-K** [comment]
But in that file, the text from the link in the first post here can't be found. It's mostly accurate, just the `implements` clause is wrong.

**Comment by Confectrician** [comment]
Sorry i was not completely in the topic yesterday.

From https://github.com/openhab/openhab-addons/issues/9742#issuecomment-759751551
> If it is still valid, i will cherry pick it into the latest docs, so we can improve it.

The changes linked above where from a preview that has been merged in the 2.5.x docs version.
If the file is valid in general we can cherry pick it into main and make the improvements then.

**Comment by J-N-K** [comment]
Ah. Yes, in general that is correct.

**Comment by Confectrician** [comment]
Ok. 
I will cherry pick it (may take some time, i want to fix our docs ci build first) and come back to you after that.
We can then make adaptions.

**Comment by Confectrician** [comment]
Hey @J-N-K,

I have done the cherry-pick now and you can do the improvements. 🙂
