### ISSUE TITLE
[neeo] Forward Actions URL in brain no longer set when initializing the brain thing

### ISSUE THREAD

**Issue by mherwege** [openhab/openhab-addons#9743]
## Expected Behavior
When initializing the brain thing, the Forward Actions URL should be set in the brain to make the Forward Actions trigger channel on the bridge thing work.
I rely on this to interpret thing happening in the brain in a rule.

## Current Behavior
Currently, this parameter is not set in the brain. It used to work in OH2, probably before the changes in [#9028](https://github.com/openhab/openhab-addons/pull/9028).
Note that this parameter is still required to be set in the brain, even when the actions are not forwarded any further from the binding.

## Possible Solution
I suspect this error was introduced with the changes in [#9028](https://github.com/openhab/openhab-addons/pull/9028).

**Comment by J-N-K** [comment]
Sorry.
