### ISSUE TITLE
[homekit] Add item name as serial number

### ISSUE THREAD

**Issue by ecdye** [openhab/openhab-addons#9746]
@yfre Could we add the item label as the serial number propagated through HomeKit as it would allow proper automatic restoration using the Controller app.

i.e. Change        https://github.com/openhab/openhab-addons/blob/d87c94d603af0a1495026a8c963720ad8e9a2639/bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/AbstractHomekitAccessoryImpl.java#L99

to 

``` java
return CompletableFuture.completedFuture(accessory.getItem().getName());
```

**Comment by yfre** [comment]
@ecdye  perfect feature request "please replace that line with this line" :)
done
