### ISSUE TITLE
openhab 3.0.0 influxdb persistence defect with retentionpolicy

### ISSUE THREAD

**Issue by scriptwriter13** [openhab/openhab-addons#9790]
Influxdb 1.8.2 with retentionpolicy is used:
`create retention policy "2year" on openhab duration 120w replication 1 default`

Since openhab 3 the behavior is not as before with openhab2 in influxql, ,so the queries are not correct:

writing to database works correctly (result 204):
`[httpd] 192.168.2.244 - openhab [10/Jan/2021:16:12:19 +0000] "POST /write?db=openhab&rp=2year&precision=n&consistency=one HTTP/1.1" 204 0 "-" "okhttp/3.14.4" 9d2bb4d6-535e-11eb-9ee3-0242ac1b0002 2908`

reading from database is not correctly (result 400):
`[httpd] 192.168.2.244 - openhab [10/Jan/2021:15:48:54 +0000] "GET /query?db=openhab&epoch=ms&q=SELECT+value+FROM+2year.LichtEG_Gang+ORDER+BY+time+DESC+LIMIT+1%3B HTTP/1.1" 400 85 "-" "okhttp/3.14.4" 57a442d8-535b-11eb-9d3d-0242ac1b0002 262`

Manual Try on database:

> > SELECT value FROM 2year.LichtEG_Gang limit 1
> ERR: error parsing query: found 2year, expected identifier at line 1, char 19
> > SELECT value FROM "2year".LichtEG_Gang limit 1
> name: LichtEG_Gang
> time                value
> ----                -----
> 1588262006927000000 0

So it seems on reading from database the double quotes were not send urlcoded before and after the retentionpolicyname

**Comment by DrTron** [comment]
Same bug still exists in OH3.1.0 M2.
