### ISSUE TITLE
[tibber] Unable to Initalize binding without a subscription

### ISSUE THREAD

**Issue by janbanan007** [openhab/openhab-addons#9796]
## Expected Behavior
The binding is supposed to work with or without a subscription

## Current Behavior
Apparently, Tibber has switched from using emtpy arrays to null values for subscription queries without subscription account. Thus the initialisation fails, and you never get live data measurements in OH.

## Possible Solution
Need to make changes to the code wrt initalisation to ignore null values rather than empty arrays

## Steps to Reproduce (for Bugs)
N/A

## Context
Tibber binding can't be initialized without a Subscription

## Your Environment
Openhabian
Linux ZZZZZZZ 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux
```
262 │ Active │  80 │ 3.0.0                   │ openHAB Add-ons :: Bundles :: Tibber Binding
264 │ Active │  80 │ 2.8.5                   │ Gson
```

**Comment by kjoglum** [comment]
Plan to update binding and create PR.
