### ISSUE TITLE
The binding skeleton creation script does not work properly on windows

### ISSUE THREAD

**Issue by Daniel-42** [openhab/openhab-addons#9813]
Using openHab eclipse installed according to the guide, maven, openJDK11 and fresh forks of the current main openhab-distro and openhab-addons I was not able to properly add a new binding skeleton using the above mentioned script.

The binding files are created, however the new project does not get added to the bundles/pom.xml file nor does the binding get added to the CODEOWNERS file.

When I then run the script again for a 2nd binding it will be added to the aforementioned files.

What seems to happen is:

- .gitattributes file forces git on windows to convert line endings to CRLF
- The script that modifies pom.xml does not handle CRLF properly. It does not add a new entry, however it will expand each CRLF into: LF<x times 4 spaces>LF resulting in a file which has a seemingly empty line (that does contain spaces) after every line from the original file
- The script that modifies CODEOWNERS does not handle CRLF properly. It does not add a new entry, however it will change CRLF into LF
- When adding the second skeleton the files no longer contain CRLF but just LF and both files will be updated properly.

**Comment by Daniel-42** [comment]
As a follow up, when I run mvn clean install in the root of the repository the spotless check fails on the \r\n line endings in the pom.xml

If I run apply... a lot of files in ALL add ons will be touch and have the \r\n line endings replaced by \n

**Comment by fwolter** [comment]
I can confirm this. @wborn @J-N-K Could that result from the line ending change, necessary to fix the spotless issue?

**Comment by J-N-K** [comment]
This a known, yet unresolved issue. Can be fixed by locally adding `core.eol=crlf`. See #8712

**Comment by lsiepel** [comment]
As the line end related issue has been solved, can I assume the binding skeleton script works as intended and this issue can be closed?

I just did a quick check and I as unable to reproduce the OP issue, but my build system may not be as clean as needed.
