### ISSUE TITLE
[icalendar] Calendar entries will not be started in-time

### ISSUE THREAD

**Issue by chris922** [openhab/openhab-addons#9821]
## Expected Behavior
Setting up a calendar entry at 06:30am should trigger the rule at this time (+ a few seconds).

## Current Behavior
The rule will not always be triggered in time, sometimes a few minutes later. 

**Calendar configuration:**
![image](https://user-images.githubusercontent.com/3875742/104563692-43344600-564a-11eb-9a8a-f32a7c417b3b.png)

**icalendar TRACE log:**
```
2021-01-14 06:39:03.630 [TRACE] [.icalendar.internal.logic.CommandTag] - Command Tag Trace: "END:OG_Bad_Heizung_Radiator_Mode:11" => Fully valid Command Tag!
2021-01-14 06:39:03.642 [DEBUG] [ar.internal.handler.ICalendarHandler] - Event: [OG Bad] Heizung aktiv, Command Tag: BEGIN:OG_Bad_Heizung_Radiator_Mode:1 => OG_Bad_Heizung_Radiator_Mode.postUpdate(QuantityType: 1)
```

## Possible Solution
?

## Steps to Reproduce (for Bugs)
1. Setup some calendar entries
2. Check the log when the entries actions will be executed

## Context
I want to change states according to calendar entries on-time and not a few minutes later than expected.

## Your Environment
* Version used: openhab + icalendar v3.0.0
* Operating System and version: raspbian on raspberry pi 4

**Comment by chris922** [comment]
Could it be the case that the refresh-time that I can configure on Thing level is not only meant as the time when the ics file will be reloaded from the remote URL, but also means as the interval when the entries of the calendar will be evaluated if some commands needs to be fired?

If yes I think it would be great to split this into two distinct values or even better: Only allow defining the interval when to reload the calendar from external and evaluate the entries as often as possible to fire events nearly in-time. This was the way I was expecting the binding would work.
I want the events to be fired in-time, but don't want to e. g. reload the external calendar every minute....

**Comment by daMihe** [comment]
No. Normally the events are planned exactly (there are multiple timers (technically `ScheduledFuture`s), the events are reloaded on refresh). Please do more tracing  - maybe something is wrong outside the binding but influencing it.

**Comment by chris922** [comment]
Okay thanks for the answer, I will try to get more information what is happening within my setup

**Comment by daMihe** [comment]
Please check again with the current version. Maybe this issue is fixed, as there was a bug in the calculation of reevaluating the next update.

**Comment by chris922** [comment]
I can't remember that I had the issue in the past, maybe it was really solved with an update.. I will close this one and if I face the issue again I try to give more details and reopen it. Thanks anyway for having a look at this issue :)
