### ISSUE TITLE
[HomeWizard] Provide a binding for the HomeWizard Wi-Fi P1 Meter

### ISSUE THREAD

**Issue by Daniel-42** [openhab/openhab-addons#9825]
The HomeWizard P1 Meter is a small dongle that attaches to the P1 port of Dutch Smart Meters. It's main purpose is to upload data from the meter to the cloud but the manufacturer has added an api that can be queried locally.

https://www.homewizard.nl/shop/homewizard-wi-fi-p1-meter

I have a working version of the binding in a branch in my fork and am now going through the steps preparing for a pull request.

**Comment by lsiepel** [comment]
Closed by https://github.com/openhab/openhab-addons/issues/9825
