### ISSUE TITLE
[tplinksmarthome] Kasa firmware update has broken compatibility with HS100/HS110 plugs

### ISSUE THREAD

**Issue by syzwax** [openhab/openhab-addons#9826]
Apologies if this is a duplicate report.

As reported [here](https://github.com/home-assistant/core/issues/43088) and [here](https://github.com/python-kasa/python-kasa/issues/113#issuecomment-726263084), it would appear that at some point in November 2020 (or slightly before), TP-Link pushed out a new firmware update to certain hardware revisions of Kasa Smarthome plugs (to "improve security"), which has broken compatibility with the tplinksmarthome addon (in addition to other projects such as the aforementioned home assistant and python-kasa).  

The smart plugs are perfectly servicable from inside the Kasa phone app, however it seems that TP-Link have disabled access to port 9999, which the openhab binding relies on to communicate and have switched to a HTTP-based communication method on port 80.  The firmware update (version 1.1.0) appears to affect only hardware revision 4.1 (previous hardware and firmware revisions appear to work):

Hardware Version | Firmware Version | Status
-- | -- | --
2.1 | 1.5.7 | Working (x2)
4.1 | 1.0.4 | Working
4.1 | 1.1.0 | Unavailable in openHab

[This thread](https://github.com/python-kasa/python-kasa/issues/115) on the python-kasa project details thier efforts to referse engineer the new protocol.  As far as I'm aware it's not possible to downgrade the plug firmware to a previous version.

I experienced this using binding version 3.0.0

**Comment by Hilbrand** [comment]
Thanks for creating the issue so we have a place to track this. There is also a topic on our [forum]( https://community.openhab.org/t/tplink-closed-port-9999/108652). It's possible to reverse this by contacting tplink, see the topic. It only seems to be affecting UK devices. Home Assistant has been in contact with tplink and they seem to be willing to improve local access in general. So it's a bit unclear if it's worth to create a fix for this.

**Comment by MikeJMajor** [comment]
The following link gives details about how to request updated firmware to restore local control.

[https://community.tp-link.com/en/smart-home/forum/topic/239364](https://community.tp-link.com/en/smart-home/forum/topic/239364)

After a couple of weeks and some chasing I did eventually receive firmware 1.1.1 which works fine with OH.

Support also told me that the 1.1.0 firmware had been pulled and I didn't need to worry about my other plugs which hadn't yet upgraded to 1.1.0 losing local control.

**Comment by Mattsouthgate** [comment]
Is there any hope for anyone after the deadline to modify/downgrade/upgrade the firmware from 1.1.0?
I have several HS110 on 1.04 which are fine, but a couple I bought have 1.1.0.

**Comment by Hilbrand** [comment]
This issue doesn't seem to relevant anymore as current versions work with the binding.
