### ISSUE TITLE
[loxone] Loxone integration not working

### ISSUE THREAD

**Issue by hazaart** [openhab/openhab-addons#9848]
Added the Loxone add on to openhab.

Getting the following error when connecting to the miniserver:
"Error communicating with Miniserver (normally closed)"

All connection details are correct. My loxone miniserver is also exposed to the outside via dyndns. I tried both with local connection string and external.

**Comment by ppieczul** [comment]
What version of Loxone Config (or firmware) and which generation of Miniserver?

**Comment by hazaart** [comment]
Gen 2 miniserver running firmware version11.1.9.14

**Comment by ppieczul** [comment]
@hazaart 11.1 only for GEN2 introduces websocket level encryption. This needs to be implemented in the binding. Unfortunately I have only GEN1. I think it should not be hard to implement, but I would need remote access to a GEN2 miniserver, or to find someone who has GEN2 and can implement this encryption.

**Comment by ppieczul** [comment]
@hazaart I just got GEN2 Miniserver at home and installed latest Beta FW (11.3.2.16). I can see the binding connects just fine, like with GEN1 and all earlier FW versions.
So it looks like we are facing here some other problem. Does the issue still occur for you?

**Comment by hazaart** [comment]
Unfortunately yes.

**Comment by ppieczul** [comment]
Please check first if you have a token field empty under thing preferences advanced. It should be blank. If this is the case please enable debug logging: 
log into console: openhab-cli console (default password habopen)
in console run: log:set DEBUG org.openhab.binding.loxone
Then try to connect and send me the log from /var/log/openhab*/openhab*.log

**Comment by sirkserac** [comment]
I have the same issue whit the same firmware and miniserver gen2. Did you find a solution?

**Comment by ppieczul** [comment]
@sirkserac can you please post debug logs? It is not possible to diagnose this without it.

**Comment by sirkserac** [comment]
Hi, I wil try to do this later this week.

**Comment by sirkserac** [comment]
first of all  i c this warning in the openhab log:
2021-04-18 14:45:21.957 [WARN ] [fig.discovery.DiscoveryResultBuilder] - Representation property 'MAC' of discovery result for thing 'loxone:miniserver:MAC' is missing in properties map. It has to be fixed by the bindings developer.

**Comment by sirkserac** [comment]
hi, i just removed the thing and added it manualy instead of automatic and now it works.

**Comment by ppieczul** [comment]
Ah, ok, I haven't checked how the discovery works for a long time. I will test it.
Also, if binding refuses to connect in the future, please remember that in order to enter a password, you need to delete the key under advanced properties. Otherwise it will keep on logging on with the key, which may be invalid.
I am happy that it works now.

**Comment by lsiepel** [comment]
As no follow-up was post, can i assume this issue was fixed?
