### ISSUE TITLE
[tr064] Ignore rounded brackets in phone-number matching with phonebook

### ISSUE THREAD

**Issue by cherub-i** [openhab/openhab-addons#9853]
Given the following (made up) German mobile phone number:
0170 1234567

A commonly used way to store such a phone number in Microsoft Outlook is, to enclose the area code 0170 in brackets and replace the 0 by the correct country code (+49).
This will result in the following:
+49 (170) 1234567

Apart from MS Outlook, this syntax is probably also in use to make phone number easier to read.

Currently it seems that rounded brackets are relevant for phone-number matching with the phonebook.
I propose to eliminate rounded brackets before trying the matching.

I am not aware of square brackets being used, but as they have no significance for a number either and might be used somewhere by someone, why not also eliminate those from the match?

**Comment by J-N-K** [comment]
Already fixed in SNAPSHOT (#9733)
