### ISSUE TITLE
[neeo] OK or ENTER Button

### ISSUE THREAD

**Issue by GekoCH** [openhab/openhab-addons#9867]
Currently when you select the Hard Button "OK" on the remote it does not work.
When you select it in the drop down for an Item in the Integration Settings it gets rewritten to ENTER. It should be instead "CURSOR ENTER" since this works as tested on my OH3 build.
So pls if anyone can change this to "CURSOR ENTER" instead of just "ENTER" that would be great since may people are struggling with this.

Andy

**Comment by lsiepel** [comment]
Not sure if this is still an issue. But could you be a little more specific? How and or where the binding shoudl be adjusted? Did you also test with 4.0.x ?
