### ISSUE TITLE
[knx] Things can only be related to one Equipment 

### ISSUE THREAD

**Issue by gockel74** [openhab/openhab-addons#9868]
## Expected Behavior
I can relate Things of a Knx bridge to more than one equipement of the semantic class

## Current Behavior
Currently, if I link one thing of the Knx bridge to an equipement, the equipment changed for all other things of the Knx bridge. All things of a Knx bridge must belong to one equipement.

## Possible Solution
dont know

## Steps to Reproduce (for Bugs)
take the attached file as things definition file
Rename the extension to .things
Using the GUI, link device blinds to equipment blinds with some new blinds items
Using the GUI, link device lightbulb to equipement lightbulb with some new items
Check, if the blinds items is linked to equipement blind
(In my case it was related to equipement lightbulb)
[knx_things.txt](https://github.com/openhab/openhab-addons/files/5832390/knx_things.txt)

## Context
[knx_things.txt](https://github.com/openhab/openhab-addons/files/5832376/knx_things.txt)

## Your Environment
OpenHAB 3.0 running a raspberry [4]([url](url))

**Comment by holgerfriedrich** [comment]
Cannot reproduce with current setup (OH4.1.1, snapshot of KNX binding).
I will close now, please reopen this ticket if it is still an issue.
