### ISSUE TITLE
[zigbee] openhab3 docker image - XStream not explicitly initialized after startup on tty

### ISSUE THREAD

**Issue by lmicheel** [openhab/openhab-addons#9872]
Hello,
i face more a  issue as the log voulme on my tty get increased after migrating into my openhab3.0 environment running on a docker container on RpI 4t. The issue is similar as decribed here for other Bindings with openhab 3.0: 
https://community.openhab.org/t/issues-after-upgrade-from-oh2-to-oh3-openhabian/111033/8

The functionality is given but i get flooded with this output on my console:
_Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
Security framework of XStream not explicitly initialized, using predefined black list on your own risk._

It stops after uninstalling the zigbee binding and comes reproducable back after new installing the zigbee Binding in my openhab3 docker container.

**Comment by wborn** [comment]
It should be fixed by https://github.com/openhab/org.openhab.binding.zigbee/pull/633. Maybe the @openhab/zigbee-maintainers can cherry pick the fix onto their 3.0.x branch? I already asked for that in https://github.com/openhab/org.openhab.binding.zigbee/pull/634.

**Comment by cdjackson** [comment]
> I already asked for that

Apologies - as I've said elsewhere I am very busy at the moment trying to move house (or get the house ready to sell). This is taking a lot of my time at the moment and will do for at least the next month. I think I already expressed this in the maintainers list.

Sorry for the inconvenience.

**Comment by wborn** [comment]
Yes that's why I created that cherry pick PR (https://github.com/openhab/org.openhab.binding.zigbee/pull/634) to make life easy and make it a one click effort. :wink:

**Comment by cdjackson** [comment]
Ah - ok, I understood from this point that you still needed it picked across. Sorry - I’m not following things very well at the moment so missed that.

Thanks - it’s much appreciated, and I can’t wait to not be moving!! :)

**Comment by wborn** [comment]
It's certainly a huge time sink moving places! I hope the new place doesn't have a lot of RF interference. :wink:

**Comment by cdjackson** [comment]
Yep - an a bigger time sink in the current climate :(

The hope is to get a place in the country - hopefully “RF Free” :)
