### ISSUE TITLE
[MQTT] Generic color channel type color_mode not working

### ISSUE THREAD

**Issue by DerOetzi** [openhab/openhab-addons#9880]
## Expected Behavior

Like documentation tells generic channel with type need a required attribute color_mode in text file configuration with value of hsb, rgb or xyY

## Current Behavior

Using color_mode attribute has no affect on channel configuration. Using instead colorMode like defined [here](https://github.com/openhab/openhab-addons/blob/d6364aceb1d952e80c0c8ed758af5d06d072ffa4/bundles/org.openhab.binding.mqtt.generic/src/main/resources/OH-INF/config/color-channel-config.xml#L15) works only with values given in uppercase.

## Possible Solution
Change documentation or channel definition to the desired version color_mode or colorVersion and values in upper or lower case

## Steps to Reproduce (for Bugs)
configure Color channel in text file

## Your Environment

* Version used: OH 3.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by J-N-K** [comment]
Same issue as #10117
