### ISSUE TITLE
[icalendar] Errors after changing Calendar Event Title

### ISSUE THREAD

**Issue by softy2417** [openhab/openhab-addons#9894]
## Expected Behavior
Download ICS-file and update channels Current (and next Event Title) , as well as all the other channels

## Current Behavior
2021-01-21 10:02:54.451 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
ICS file will be not downloaded
Calendar Thing cannot be removed before restarting oh3

## Steps to Reproduce (for Bugs)
Change Event title in Calendar

## Your Environment
docker oh 3.0.0 stable on Synology
Webdav Calendar on Synology 6.2

**Comment by ekkards** [comment]
#9827 has same error message

**Comment by softy2417** [comment]
deleting the ics in /userdata and restart of oh3 helps, but that is not a proper solution

**Comment by daMihe** [comment]
I would assume a similar source of this "bug" as in #9827, closing this as duplicate. Feel free to reopen if needed.
