### ISSUE TITLE
[jdbc] JDBC persistence ignores operator set in FilterQuery

### ISSUE THREAD

**Issue by splatch** [openhab/openhab-addons#9906]
Given that `FilterQuery` makes it possible to specify additional operator I am convinced that ignoring it is a bug. There is currently no way to tell JDBC persistence to be inclusive.

The generated query always uses `>` for begin date and `<` for end date. There are cases where these should be `=>` or `<=`.

**Comment by jlaur** [comment]
Probably this is the logic in question:
https://github.com/openhab/openhab-addons/blob/cf241f8b4f090e1548345d94e1643404d5129636/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/internal/db/JdbcBaseDAO.java#L515-L528

**Comment by splatch** [comment]
Yup, these are places I been patching in order to get boundaries.

**Comment by jlaur** [comment]
But unfortunately the current implementation seems correct, at least according to these comments in core implementation:
https://github.com/openhab/openhab-core/blob/06c0e905357a2478ef4fdccae3a6fcff14c7a7be/bundles/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/FilterCriteria.java#L70-L74

These are only comments, though, not official documentation. @cweitkamp - do you know if these comments are to be interpreted literally?

The operator is for comparing state, not dates:
https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/filtercriteria

It seems to be interpreted differently here:
https://github.com/openhab/openhab-addons/blob/cf241f8b4f090e1548345d94e1643404d5129636/bundles/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jPersistenceService.java#L314-L318

And here:
https://github.com/openhab/openhab-addons/blob/cf241f8b4f090e1548345d94e1643404d5129636/bundles/org.openhab.persistence.jpa/src/main/java/org/openhab/persistence/jpa/internal/JpaPersistenceService.java#L204-L215

And here:
https://github.com/openhab/openhab-addons/blob/cf241f8b4f090e1548345d94e1643404d5129636/bundles/org.openhab.persistence.mongodb/src/main/java/org/openhab/persistence/mongodb/internal/MongoDBPersistenceService.java#L370-L379

So I would agree that we can change to "TIME>=" and "TIME<=" in lines 519 and 524, is that also how you patched it?

If this would be the outcome, I would also open a PR towards core to change those comments.

**Comment by jlaur** [comment]
@splatch - you could have a look at this draft pull request: #13734.
