### ISSUE TITLE
FRONIUS Binding in OH3 - no Meter Thing

### ISSUE THREAD

**Issue by ThomasBrodkorb** [openhab/openhab-addons#9926]
Is there anything I am doing wrong or is there no METER thing type anymore in OH3 Fronius Binding?
This is the most important part for controlling consumption.

When adding a thing with Fronius Binding it just shows the thing types "bridge" and "inverter".

Hope, someone can help

**Comment by Hilbrand** [comment]
Looking at the code here there is a `meter`, and `powerinverter`, but no `inverter`. What version did you install?

**Comment by ThomasBrodkorb** [comment]
Well, not sure about the version, the one that is in the list of the OH3.
It pretends to be version 3.0.0
When you try to add a new thing for the Fronius Binding, it let's you select from "Fronius Bridge" and "Fronius Symo Inverter".
For now, I use the meter with the http binding as with OH2.

**Comment by Hilbrand** [comment]
Looking at the timeframe. The meter was just added after 3.0 release. That explains it. It will be available in 3.1, and is already available in the snapshot version.

**Comment by bananajoe86** [comment]
Thanks for this information. 
With an upgrad in the konsole the meter is working.

update org.openhab.binding.fronius https://ci.openhab.org/job/openHAB-Addons/lastSuccessfulBuild/artifact/bundles/org.openhab.binding.fronius/target/org.openhab.binding.fronius-3.1.0-SNAPSHOT.jar

**Comment by jimtng** [comment]
If it's working now (post 3.1), please close this issue.
