### ISSUE TITLE
[miio] Wrong datatype for channel ambientBrightness in yeelink.light.ceiling4.json

### ISSUE THREAD

**Issue by mrumpf** [openhab/openhab-addons#9936]
It seems as if the datatype for the channel "ambientBrightness" is wrong in the device database JSON file:
https://github.com/openhab/openhab-addons/blob/9203603f2a0265a3c67393d06a0559b4d6d57ef6/bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json#L59

For the channel "brightness" the type is defined as "Dimmer":
https://github.com/openhab/openhab-addons/blob/9203603f2a0265a3c67393d06a0559b4d6d57ef6/bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json#L30

When defining a slider in a sitemap, the percentage value gets submitted as a fraction 0.68 for 68% and this gets rejected by the device. Even changing the value range of the slider to "step=1 minValue=1 maxValue=100" does not change the value being submitted to the devic.

## Expected Behavior
The expected behaviour is that the channel is of type Dimmer and a Slider can be used in the sitemap to control the ambient light brightness in the same way it works for the main light brightness value.

## Current Behavior
````
2021-01-24 11:05:10.345 [DEBUG] [nal.transport.MiIoAsyncCommunication] - Command added to Queue {"id":70,"method":"bg_set_bright","params":[0.65000000]} -> 192.168.178.83 (Device: 158D3A35 token: CEBE3475
XXXXXXXXXXXXXXXX100059C3 Queue: 1).
2021-01-24 11:05:10.421 [TRACE] [nal.transport.MiIoAsyncCommunication] - Connection 192.168.178.83:60488
2021-01-24 11:05:10.533 [TRACE] [nal.transport.MiIoAsyncCommunication] - Message Details:Message:
Header  : 21 31 00 60 00 00 00 00 15 8D 3A 35 00 00 08 47
checksum: B2 3C FA 69 7A 74 62 83 ED 2D B8 87 7B 85 03 D5
content : 9D 10 98 3D B4 DB FF 5D 65 3C 75 92 3D 97 14 BE DA CB 90 80 46 82 11 5B 05 9B 1C 69 6E 5D 89 9A 86 97 AC 57 D7 06 03 AB B7 5A 4B 35 57 61 FB FD 44 83 DD 37 24 A4 26 54 8E D4 63 8F 39 61 66 BA
Header Details: Magic:21 31
Length:   96
Serial:   15 8D 3A 35
TS:1970-01-01 01:35:19
2021-01-24 11:05:10.535 [TRACE] [nal.transport.MiIoAsyncCommunication] - Received response from 192.168.178.83: {"id":70,"error":{"code":-5001,"message":"invalid params"}}
````

## Possible Solution
The channel type should be changed from "Number" to "Dimmer":
https://github.com/openhab/openhab-addons/blob/9203603f2a0265a3c67393d06a0559b4d6d57ef6/bundles/org.openhab.binding.miio/src/main/resources/database/yeelink.light.ceiling4.json#L59

## Steps to Reproduce (for Bugs)
1. Add a device of type yeelink-light-ceiling10 as defined here https://www.openhab.org/addons/bindings/miio/#yeelight-crystal-pendant-lamp-yeelink-light-ceiling10-item-file-lines 
2. Try to control the ambient brightness from Openhab

## Context
I cannot control the brightness of the ambient light.

## Your Environment
* Version used: 3.0.0 (Build)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Safari on Mac OSX
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspian 10.7

**Comment by michiii1337** [comment]
same bug with yeelink.light.light15.json, please fix
