### ISSUE TITLE
[modbus] Modbus transformations should support cascaded transformations with ∩

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#9944]
Similar to HTTP and serial binding, modbus should support cascading/chaining transformations with ∩.

(will provide PR)

**Comment by Rossko57** [comment]
Probably not a great deal of application as we don't really get complex payloads like JSON in Modbus, But if it's done, it's done. :)

**Comment by ssalonen** [comment]
Haha probably true... I like the consistency though :)
