### ISSUE TITLE
[Pushover] Stopped working after upgrade to OH 3.0.1

### ISSUE THREAD

**Issue by DanielMalmgren** [openhab/openhab-addons#9974]
It seems for some reason the Pushover binding stopped working after an upgrade from 3.0 to 3.0.1.

I'm using it like this:

> val actions = getActions("pushover", "pushover:pushover-account:Pushover_Daniel")
> actions.sendMessage("Test message", null)`

and it results in the following in my log:

> The method sendMessage(String, Object) is undefined for the type ThingActions; line 4, column 129, length 11

System information:
OS: Debian 10.7 (arm64)
Java: openjdk 11.0.9.1 (Zulu)
OH installed from official repo

**Comment by kaikreuzer** [comment]
There were absolutely no changes in that area, I guess all you need to do is to restart once more.

**Comment by DanielMalmgren** [comment]
Yep, you're right. Forgot that second restart after the upgrade...

Actually, this time I didn't have one single error in my log file after starting openhab. I don't think that has ever happened to me before. Good job!
