### ISSUE TITLE
[homematic] Dimmer HM-LC-Dim1T-DR not working in OH3

### ISSUE THREAD

**Issue by acfischer42** [openhab/openhab-addons#9986]
### Expected Behavior

On creation of the Hm Dimmer Item via the new UI the Item should have a dimming range of 0-100.

Wireless Dimming Actuator 1-channel, trailing edge, DIN rail mount (HM-LC-Dim1T-DR)

P.S. I have similar issues with a 
Wireless Dimming Actuator 2-channel PWM LED (HM-DW-WM)
and a
No Description (HM-LC-RGBW-WM)
Do you prefer separate Issues to be opened?

### **Current Behavior**

Instead it is ranging from 0-1.

### **Steps to Reproduce (for Bugs)**
This seems similar to: [https://github.com/openhab/openhab-addons/issues/8799](url)

Create a Point (item) in Openhab 3 via the new interface.
### **Context**

adding new item(s) to my installation. 

**Let me know where I can help.** and thanks a lot for this binding!

### **Your Environment**

Debian 
Openhab 3 
OpenJava 11

### **Troubleshooting **info:****

{
  "parameters": [
    {
      "context": "string",
      "defaultValue": "string",
      "description": "string",
      "label": "string",
      "name": "string",
      "required": true,
      "type": "TEXT",
      "min": 0,
      "max": 0,
      "stepsize": 0,
      "pattern": "string",
      "readOnly": true,
      "multiple": true,
      "multipleLimit": 0,
      "groupName": "string",
      "advanced": true,
      "verify": true,
      "limitToOptions": true,
      "unit": "string",
      "unitLabel": "string",
      "options": [
        {
          "label": "string",
          "value": "string"
        }
      ],
      "filterCriteria": [
        {
          "value": "string",
          "name": "string"
        }
      ]
    }
  ],
  "parameterGroups": [
    {
      "name": "string",
      "context": "string",
      "advanced": true,
      "label": "string",
      "description": "string"
    }
  ],
  "description": "string",
  "label": "string",
  "category": "string",
  "itemType": "string",
  "kind": "string",
  "stateDescription": {
    "minimum": 0,
    "maximum": 0,
    "step": 0,
    "pattern": "string",
    "readOnly": true,
    "options": [
      {
        "value": "string",
        "label": "string"
      }
    ]
  },
  "tags": [
    "string"
  ],
  "UID": "string",
  "advanced": true,
  "commandDescription": {
    "commandOptions": [
      {
        "command": "string",
        "label": "string"
      }
    ]
  }
}

**Comment by MHerbst** [comment]
I assume that it is a duplicate to #8799. Can try this test version of the binding: https://github.com/MHerbst/openhab-addons-test 

You will probably have to remove the thing and re-create it. If this does not help I would need to know the HM channels that are used for the dimmer.

**Comment by acfischer42** [comment]
Perfect. Thanks a lot. Sorry that I didn't read #8799 correctly.
