### ISSUE TITLE
Zwave binding - Aeon Labs ZW080-A17 : configure siren types via Items 

### ISSUE THREAD

**Issue by nikoizs** [openhab/openhab-addons#999]
Please add the option to configure the Aeon Labs siren sound via Items like in OH1 
https://community.openhab.org/t/need-code-for-aeon-labs-zw080-a17-siren/3554/39

**Comment by cdjackson** [comment]
Transferred to https://github.com/openhab/org.openhab.binding.zwave/issues/3
