### ISSUE TITLE
[http] POST support for Status

### ISSUE THREAD

**Issue by moodyblue** [openhab/openhab-addons#9996]
## Your Environment
* Version used: OH 3.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Oracle Java 11.0.9
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): QNAP NAS, Intel processor 64bit, QTS 4.5.1

Several devices (and url's) report status using POST method. HTTP binding only supports GET method to obtain device status. I am submitting this feature request for evaluation.

More info in the forum https://community.openhab.org/t/http-binding-enhancing-post-support/115235?u=moody_blue

**Comment by J-N-K** [comment]
As I already said: What sgould be the content of the POST request? And how should that be configured? Addid POST support for the status is easy, but setting the content is difficult.

**Comment by off14** [comment]
can't get status - system always sends GET request, even if POST is configured for Command Method

**Comment by off14** [comment]
2021-01-31 00:06:15.525 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'https://xxxxxxx/devices?load_io=true' (method='GET', content='null') failed: 405 Method Not Allowed

**Comment by moodyblue** [comment]
This is how I do it using RESTer (a Firefox plugin)
![imagem](https://user-images.githubusercontent.com/6073615/106366619-f2ed0180-6334-11eb-9bf2-776afd5915e7.png)
In the above image `idOperacion=1002` is the body. This should be parametrized in the channel as input for the status request, then a transformation will take care of the answer. Another channel for the same thing could have a different body.

@J-N-K  I hope this is what you have asked.

**Comment by moodyblue** [comment]
> Addid POST support for the status is easy, but setting the content is difficult
In my case the body content can be hard coded in the channel definition, but I don't know if this is a general case.
