### ISSUE TITLE
[Sonos] Support for audio formats on HDMI input

### ISSUE THREAD

**Issue by stjx79** [openhab/openhab-addons#9997]
At least for the soundbars with HDMI or optical input there is the possibility to read out the audio format (possibly also on the Sonos Amp).
The audio format can be found as a code in the HTAudioIn parameter:
`` 2021-01-30 12:04:51.255 [TRACE] [s.internal.handler.ZonePlayerHandler] - Received pair 'HTAudioIn':'33554434' (service 'DeviceProperties') for thing 'sonos:zoneplayer:Wohnzimmer'
``

So far, I have been able to find the following codes related to an audio format.
| audio format           | code     |
|------------------------|----------|
| Silence                | 22       |
| Silence 2.0            | 33554454 |
| Stereo PCM 2.0         | 33554434 |
| Dolby Digital 2.0      | 33554488 |
| Dolby Digital 5.1      | 84934713 |
| Dolby Digital Plus 5.1 | 84934714 |
| DTS (unsupported)      | 32       |

I am sure there are other codes as well. For example for Dolby Atmos.
I determined the codes with a Sonos Arc and a Sonos Beam. Both were connected to a TV via HDMI Arc.
This property also appears on devices without audio input. Here the value is always 0.

The current audio format can be found under "About My System" in the Sonos app. The corresponding code can be read out in the trace or under the corresponding IP address on the support page (HTAudioInCode under "Zone Player Info"). For example: http://192.168.1.218:1400/support/review

It is possible to simply output the code as an item and then translate it with a transformation.

**Comment by TomMarg** [comment]
I would not really need this value in my setup but I've seen following codes:
59 - Atmos
21 - No Signal

**Comment by morph166955** [comment]
I second/third/fourth this!  I have the Arc and I would definitely enjoy this feature.  I use the neeo remote and would love to throw this onto the remote so that I can see what audio mode my system is operating in.

**Comment by morph166955** [comment]
I may try to work on a PR for this in the next week or two if @lolodomo doesn't have any issue with me submitting it.  It should be easy enough to roll and I can test locally.

**Comment by lolodomo** [comment]
No problem, I will review your PR.

**Comment by morph166955** [comment]
Works for me.  Thanks!

**Comment by morph166955** [comment]
I've got a test JAR that creates a channel called codec.  Right now it's just populating with the numeric value.  I've run out of time for now to put the translator in.  I'll work that when I get time again.  

For anyone who wants a sneak peak: https://github.com/morph166955/openhab-addons/tree/sonos-codec

Adding for notes:
84934718 = Dolby Multichannel PCM 5.1

**Comment by morph166955** [comment]
I lied.  Had a few minutes so I put the translator in.  This seems to work without issues on my system thus far.  I for whatever reason don't get a whole bunch of codecs show on mine so I'm assuming what was posted above to be correct.

@lolodomo requesting you review the PR

**Comment by morph166955** [comment]
Just adding another one so I don't lose it.  I hope to update the PR this weekend.

33554494 - Dolby Multichannel PCM 2.0

**Comment by lolodomo** [comment]
> Dolby Multichannel PCM 2.0

Certainly a bad naming.

https://en.wikipedia.org/wiki/Dolby_Digital

Dolby Surround
Dolby Pro Logic
Dolby Pro Logic II
Dolby Pro Logic IIx
Dolby Pro Logic IIz

https://en.wikipedia.org/wiki/Dolby_Pro_Logic

Dolby Digital (= Dolby AC-3)
Dolby Digital EX
Dolby Digital Surround EX
Dolby Digital Plus
Dolby AC-4
Dolby TrueHD
Dolby Atmos

**Comment by morph166955** [comment]
No disagreement. That's what it said on the Sonos app.

**Comment by lolodomo** [comment]
Probably a bug in the Sonos app!

**Comment by morph166955** [comment]
Did some research. Apparently this is something my Nvidia Shield and Plex are doing. Its basically converting other formats (I've caught AC3 and MP3 doing it) to raw PCM and sending it that way through my TV to the Arc. It's not DD or any of the others really. Its just either two or six old school PCM waveforms being sent.

**Comment by lolodomo** [comment]
Yes that is just multichannel PCM, something very common. But this is not a Dolby format.
Maybe Sonos is tagging "Dolby" as soon as he detects more than 2 channels ?!

**Comment by morph166955** [comment]
Who knows. I'd say keep what the app has for consistency and if the app changes we can just submit a PR to update the strings.
